### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by krishamoud** [mholt/caddy#1000]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.0

#### 2. What are you trying to do?
I'm trying to get websockets to work for my Meteor.js application

#### 3. What is your entire Caddyfile?
```text
test.chucktweets.com {
  proxy / {
    websocket
    transparent
    upstream 198.199.93.167:8080
  }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
docker run -d \
    -v $(pwd)/Caddyfile:/etc/Caddyfile \
    -v $HOME/.caddy:/root/.caddy \
    -p 80:80 -p 443:443 \
    abiosoft/caddy \
    -http2=false \
    --conf /etc/Caddyfile
```
#### 5. What did you expect to see?
I expected to see a `websocket` connection
<img width="1399" alt="screen shot 2016-08-05 at 12 12 29 am" src="https://cloud.githubusercontent.com/assets/5006294/17429100/c8841fdc-5aa1-11e6-8a56-9ae5e601b0fb.png">
(this is behind Nginx)

#### 6. What did you see instead (give full error messages and/or log)?
I got the `xhr-polling` protocol insteady and a failed websocket hanshake
<img width="1404" alt="screen shot 2016-08-05 at 12 13 02 am" src="https://cloud.githubusercontent.com/assets/5006294/17429111/d4fb8be2-5aa1-11e6-9117-1c1a2142f9be.png">
(this is behind Caddy)
#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

**1. Run the following command with the aforementioned `Caddyfile` (replace IP and domains with your own)**
```
docker run -d \
    -v $(pwd)/Caddyfile:/etc/Caddyfile \
    -v $HOME/.caddy:/root/.caddy \
    -p 80:80 -p 443:443 \
    abiosoft/caddy \
    -http2=false \
    --conf /etc/Caddyfile
```

**2. Run the following command**
```
docker run -d \
  -p 8080:80  \
  -e ROOT_URL=https://test.chucktweets.com \
  -e PORT=80 khamoud/test
```

**3. Visit your url and type the following in the console** 
```
Meteor.connection._stream.socket
```

Which will say that `xhr-polling` is the current protocol instead of websockets.

You will also get an error along the lines of:
`WebSocket connection to 'wss://test.chucktweets.com/sockjs/457/x7qwmdjw/websocket' failed: Error during WebSocket handshake: Unexpected response code: 400`

What's interesting is if I run locally using an IP:PORT instead everything works just fine.

**Comment by mholt** [comment]
Thanks for the detailed report! This might already be fixed on master or in one of the pending PRs.

**Comment by krishamoud** [comment]
Thanks for the quick reply!  I'll build from source and create my own Dockerfile and see if it changes anything

**Comment by krishamoud** [comment]
I tried this with `Caddy 0.9.0 (+4c6082d Sat Aug 06 04:03:38 UTC 2016)` and everything worked as expected.  Thanks!

**Comment by mholt** [comment]
That's good news! Thanks.

**Comment by volkanunsal** [comment]
I've been getting this error in version 0.9.0. This is my Caddyfile:

```
beta.example.dev:80, beta.example.dev:443 {
  proxy / localhost:3000 {
    websocket
    transparent
  }
  tls /Users/newuser/.ssl/server.crt /Users/newuser/.ssl/server.key
}
```

Then I start the server with 

```
sudo caddy -http2=false &
```

Should I create a separate issue for it?

**Comment by mholt** [comment]
@volkanunsal No, you should upgrade to the latest version.

**Comment by volkanunsal** [comment]
@mholt Just tried it with 0.9.3. Still getting the same error, alas.

**Comment by mholt** [comment]
@volkanunsal Create a separate issue then, make sure you minimize the instructions to reproduce so that it's as simple as can be; once you've eliminated to the point that it's working again you can know what caused the problem, so that should help anyone debugging it find the problem sooner.

**Comment by volkanunsal** [comment]
@krishamoud Would you post your Docker image to Github so I can use it to try to reproduce this error?
