### ISSUE TITLE
Errors building Caddy from source

### ISSUE THREAD

**Issue by jesselucas** [mholt/caddy#1006]
I didn't see any vendoring information and building caddy from source after using `go get` to acquire the dependencies.

I'm getting errors in two packages used.

#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.7.4

#### 2. What are you trying to do?
run `go build` or `go install` or `go test` from within `github.com/mholt/caddy/caddyhttp`

#### 3. What is your entire Caddyfile?
n/a

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
n/a

#### 5. What did you expect to see?
n/a

#### 6. What did you see instead (give full error messages and/or log)?
```
# github.com/lucas-clemente/quic-go/h2quic
../../../lucas-clemente/quic-go/h2quic/request.go:24: h.IsPseudo undefined (type "golang.org/x/net/http2/hpack".HeaderField has no field or method IsPseudo)
# github.com/xenolf/lego/acme
../../../xenolf/lego/acme/dns_challenge.go:167: unknown dns.Client field 'Timeout' in struct literal
../../../xenolf/lego/acme/dns_challenge.go:170: undefined: dns.ErrTruncated
../../../xenolf/lego/acme/dns_challenge.go:171: unknown dns.Client field 'Timeout' in struct literal
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
`go get -u github.com/lucas-clemente/quic-go/`
`go get -u github.com/xenolf/lego/`
cd into `github.com/mholt/caddy/caddyhttp`
`go test`

**Comment by mholt** [comment]
> Download Caddy and latest dependencies.

What do you mean by this? What commands are you running? How can I reproduce this if I was starting from scratch?

**Comment by jesselucas** [comment]
Updated the comment above with more detail. It looks like I'm having issues with `h2quic` and `acme` packages.

**Comment by skorokithakis** [comment]
I'm having similar issues, although with the `h2quic` and `markdown` packages:

~~~
# github.com/mholt/caddy/caddyhttp/markdown/summary
Go/src/github.com/mholt/caddy/caddyhttp/markdown/summary/render.go:10: cannot use (*renderer)(nil) (type *renderer) as type blackfriday.Renderer in assignment:
	*renderer does not implement blackfriday.Renderer (wrong type for Header method)
		have Header(*bytes.Buffer, func() bool, int, string)
		want Header(*bytes.Buffer, func() bool, int)
Go/src/github.com/mholt/caddy/caddyhttp/markdown/summary/summary.go:12: cannot use renderer literal (type renderer) as type blackfriday.Renderer in argument to blackfriday.Markdown:
	renderer does not implement blackfriday.Renderer (wrong type for Header method)
		have Header(*bytes.Buffer, func() bool, int, string)
		want Header(*bytes.Buffer, func() bool, int)
# github.com/lucas-clemente/quic-go/h2quic
Go/src/github.com/lucas-clemente/quic-go/h2quic/request.go:24: h.IsPseudo undefined (type "golang.org/x/net/http2/hpack".HeaderField has no field or method IsPseudo)
~~~

**Comment by mholt** [comment]
I'm not having this problem; what commit are you building Caddy from?

**Comment by skorokithakis** [comment]
I was using both the latest master head and the v0.9.0 tag, and had the same problem in both.

**Comment by mholt** [comment]
@skorokithakis Make sure you use the latest blackfriday. See https://github.com/russross/blackfriday/blob/4e6f303e8d936855981ddcdbfc092b03d2b2b68e/markdown.go#L167 - Caddy's latest is correct.

I'm not sure how to fix your problems with this, it's all working here just fine after some `go get -u` commands. Sorry, but I don't think this is an actionable Caddy issue. CI tests are passing fine too.

**Comment by skorokithakis** [comment]
I'll try again, thanks.

**Comment by skorokithakis** [comment]
I managed to build after a `go get -u`, thanks @mholt.

**Comment by jesselucas** [comment]
@skorokithakis How did you resolve the `h2quic` error? I've tried `go get -u` and removing the package.

**Comment by skorokithakis** [comment]
With `go get -u`, that completely resolved it (although I think I had to update blackfriday by hand).
