### ISSUE TITLE
Add ability to log request body.

### ISSUE THREAD

**Issue by itskenny0** [mholt/caddy#1015]
#### 1. What version of Caddy are you running (`caddy -version`)?
any

#### 2. What are you trying to do?
Log the entire request body.

In #858, the ability to log the request headers was added. However, my use case would require me to log the entire input. Would this be possible using a secondary placeholder, maybe?

**Comment by definitelycarter** [comment]
Do we want to log only certain request bodies either by type, length, both?  I don't think we want to log out binary for example.

**Comment by itskenny0** [comment]
I personally would be interested in POST requests with application/json.

**Comment by mholt** [comment]
- How do we handle newlines (you want a log entry that spans an arbitrary number of lines?)
- How do we handle binary data?
- How do we handle huge request bodies (10+ MB... ?)

**Comment by itskenny0** [comment]
We already have a method to print the headers, which print newlines as \n. That sounds reasonable to me. The implementation by @definitelycarter restricts it to XML and JSON inputs, so binary shouldn't be an issue. A size limitation would be a good idea, however I'm not sure where the limitation should be put.

Maybe this feature would be good in a seperate plugin, which would allow for some configurability.

**Comment by definitelycarter** [comment]
> How do we handle newlines

I saw [this code](https://github.com/mholt/caddy/blob/59b1e8b0bc1f14832a721b9177dbd3884e47d0b4/caddyhttp/httpserver/replacer.go#L20) used in a couple of replacers; However, In my testing I found newlines were not getting logged so I decided to leave it out.

> How do we handle binary data?

I'm currently limiting the logging done based on the Content-Type parameter.  Now that I think of it, It probably won't stop someone from posting binary data with Content-Type of application/json.  Should we use [DetectContentType](https://golang.org/pkg/net/http/#DetectContentType)?

> How do we handle huge request bodies (10+ MB... ?)

Currently I'm copying the entire body.  What would be a good default limit?

**Comment by slightfoot** [comment]
Would this feature just be used for development/debugging? If so then wouldn't a middle-ware host dashboard be better. Like `/debug/requests` and see a live request log with the ability to expand/collapse stuff and all that jazz.

**Comment by mholt** [comment]
@slightfoot That's a totally separate beast, and it'll come, I'm working on it.

**Comment by itskenny0** [comment]
I would definitely require a log though (part of the reason I want this is to be able to replay for debugging). A live view wouldn't suffice as it wouldn't save the requests to disk.

**Comment by definitelycarter** [comment]
Hey @itskenny0,

It's now possible to log request bodies up to 100 KB with {request_body}

Thanks!

**Comment by itskenny0** [comment]
First of all, thanks for implementing this. Unfortunately, I can't get it to work.

I currently get this output:
`xxx.xxx.xxx.xxx 17/Aug/2016:11:26:57 +0200 POST /xxx/xxx.php HTTP/1.1 200 23 - 55ms || POST /xxx/xxx.php HTTP/1.1\r\nHost: xxx.xxx\r\nConnection: keep-alive\r\nContent-Length: 229\r\nContent-Type: application/json\r\n\r\n || BODY: -`

My log directive looks like this:

`log / /www/xxx.xxx/access.log "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency} || {request} || BODY: {request_body}"`

**Comment by itskenny0** [comment]
Also here's how I can reproduce this:

```
curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' https://domain.com/test.php

xxx.xxx.xxx.xxx 17/Aug/2016:11:44:16 +0200 POST /test.php HTTP/1.1 200 0 curl/7.35.0 1ms || REQUEST: POST /test.php HTTP/1.1\r\nHost: domain.com\r\nAccept: */*\r\nContent-Length: 35\r\nContent-Type: application/json\r\nUser-Agent: curl/7.35.0\r\n\r\n || BODY: -
```

**Comment by mholt** [comment]
Works for me!

Caddyfile:

```
localhost

log / stderr "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency} || {request} || BODY: {request_body}"
```

Log after using that curl command:

```
::1 17/Aug/2016:09:35:34 -0600 POST / HTTP/1.1 404 14 curl/7.43.0 167µs || POST / HTTP/1.1\r\nHost: localhost:2015\r\nAccept: */*\r\nContent-Length: 35\r\nContent-Type: application/json\r\nUser-Agent: curl/7.43.0\r\n\r\n || BODY: {"username":"xyz","password":"xyz"}
```

**Comment by abiosoft** [comment]
@itskenny0 which version of Caddy are you running ?

**Comment by itskenny0** [comment]
This is the entire host directive:

```
domain.com {
        tls letsencrypt@kenny.cat

        browse
        root /www/domain.com/htdocs/
        gzip
        log / /www/domain.com/access.log "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency} || {request} || BODY: {request_body}"
        log / /www/domain.com/test.log
        errors /www/domain.com/error.log
        fastcgi / /var/run/php5-fpm.sock php

        header / Strict-Transport-Security "max-age=31536000"

        internal /git/listenerbot/.git
        git {
                repo https://github.com/itskenny0/listenerbot
                then git submodule update --init --recursive
                path git/listenerbot
                interval 120
        }
}
```

Do you see anything that could cause this?
Also, just to clarify, I got the latest caddy by go-getting caddy-git (since I need this) and caddydev, then used caddydev to generate a binary which is the one I'm using. Since Caddy seems to be replacing the {request_body} (as opposed to before where it would just leave it), it seems the code is present.

Please let me know if I can add any details that would help explain this.

**Comment by mholt** [comment]
@itskenny0 Use the build.bash script in the caddy folder to get proper version information, that will help us out. :+1:

**Comment by itskenny0** [comment]
Manually building it, it gives me this:

**Comment by mholt** [comment]
So is it fixed now that we know it's the latest version?

**Comment by itskenny0** [comment]
Well, as I said, I can't test this exact binary unfortunately as I need the Git module built in to run it in place of the existing Caddy I use. Could you tell me how I use the build.bash while including the Git module?

**Comment by mholt** [comment]
Just add `_ "github.com/abiosoft/caddy-git"` to the imports in run.go and re-build.

**Comment by itskenny0** [comment]
Thank you. I did that, and it builds correctly, but unfortunately the body is still only a hyphen.

**Comment by mholt** [comment]
It works for me with your full Caddyfile and on the same build version. :confused: Not sure what else to suggest at this point.

**Comment by definitelycarter** [comment]
I have seen that when an empty body is printed (i.e. GET request).  Can you try removing some of the directives and try again?

**Comment by itskenny0** [comment]
I was able to narrow it down to the fastcgi directive.
`fastcgi / /var/run/php5-fpm.sock php`

Once I remove this, the request body is correctly logged. Any advice?

**Comment by definitelycarter** [comment]
I'd help test; However, I'm having difficulty setting up php to test fastcgi on my machine.  My thought is that `fastcgi` is consuming the body before `log` is able to read it.

**Comment by definitelycarter** [comment]
Well - my first thought was to capture the result [rep.Replace](https://github.com/mholt/caddy/blob/master/caddyhttp/log/log.go#L56) before `l.Next.Invoke` is called.  The problem I have now is that `{latency}` will not be correct.  @mholt any ideas?

**Comment by tw4452852** [comment]
Ah, I know what is the culprit. Because we capture the request's body after the following middlewares done, if one of them consumes the entire (or part of) body, we will get empty (or part of) body. I will give a fix later.

**Comment by itskenny0** [comment]
Hi guys, I have just tested the latest commit on this matter and unfortunately I still can't log the request body if fastcgi is enabled. Same symptoms as before.

```
root@www:/opt/caddy# ./caddy -version
Caddy 0.9.1 (+1d3212a Sun Aug 21 14:15:30 UTC 2016)
 1 file changed, 2 insertions(+)
caddy/caddymain/run.go
```

**Comment by tw4452852** [comment]
@itskenny0 For edit 2, does it happen with fix patch?

**Comment by itskenny0** [comment]
It does. I'm not sure if it happens before the fix, I can test that later if relevant.

**Comment by tw4452852** [comment]
Oh, It recognized the `{` in request's body as a place holder...

**Comment by tw4452852** [comment]
@itskenny0 , Thanks for reporting. Yes it's a bug. It recognized `{` in request's body as a place holder which is not our expected. And now I have refined my patch to fix it. Give it a try again?

**Comment by itskenny0** [comment]
Yes, this seems perfect.

`
xxx.xxx.xxx.xxx 22/Aug/2016:21:08:31 +0200 POST /test.php HTTP/1.1 200 23 - 50ms || REQUEST: POST /test.php HTTP/1.1\r\nHost: domain.com\r\nConnection: keep-alive\r\nContent-Length: 302\r\nContent-Type: application/json\r\n\r\n || BODY: {"update_id":182392271,\n"message":{"message_id":1163439,"from":{"id":163275918,"first_name":"user","last_name":".","username":"user"},"chat":{"id":-10010507343434,"title":"user \ud83d\udc45 \ud83d\udca6 \ud83d\udd25","username":"user","type":"supergroup"},"date":1471892911,"text":"test"}}
`

Thank you!

**Comment by tw4452852** [comment]
Hi @itskenny0 , I think we could close this issue for now because the patch has been merged. 
Feel free to reopen if you have any problems. Thanks.

**Comment by francislavoie** [comment]
@MariusWiencke I think you want https://caddyserver.com/docs/log, not `errors`. `log` prints every request (think of it like an access log) whereas `errors` only prints when there's an error 😛

**Comment by MariusWiencke** [comment]
@francislavoie yeah but what if the post data on a requests caused the error ?
That request goes to the error log not the normal log and you have currently no chance to log that like:

`errors / /var/log/errors.log "{remote} {when} {method} {uri} {proto} {status} {size} || BODY: {request_body}"`

You know what i mean?

**Comment by itskenny0** [comment]
@MariusWiencke Errored requests will be logged to both the access log and the error log.

**Comment by phith0n** [comment]
Does this feature be removed in Caddy2?
