### ISSUE TITLE
Certificates is gotten even though the port is 8080

### ISSUE THREAD

**Issue by kevinsimper** [mholt/caddy#1016]
## Read the comment, misunderstod sites and proxy!
----

#### 1. What version of Caddy are you running (`caddy -version`)?
0.9

#### 2. What are you trying to do?
Access a site

#### 3. What is your entire Caddyfile?
```text
docker.dev:8080 {
    proxy nginx
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile"]

#### 5. What did you expect to see?
That is binds to :8080 and only responds on docker.dev

#### 6. What did you see instead (give full error messages and/or log)?
```
caddy_1  | Activating privacy features...2016/08/08 19:48:20 [docker.dev] failed to get certificate: acme: Error 400 - urn:acme:error:unknownHost - No valid IP addresses found for docker.dev
caddy_1  | Error Detail:
caddy_1  | 	Validation for docker.dev:80
caddy_1  | 	Resolved to:
caddy_1  |
caddy_1  | 	Used:
caddy_1  |
caddy_1  |
hyperloadbalancer_caddy_1 exited with code 1
```
#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

```
version: "2"
services:
  caddy:
    build: .
    ports:
      - 2015:2015
    volumes:
      - ./Caddyfile:/etc/Caddyfile
  nginx:
    image: nginx:latest
```
```
FROM alpine:3.2

RUN apk add --update openssh-client git tar curl

RUN curl --silent --show-error --fail --location \
      --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
      "https://caddyserver.com/download/build?os=linux&arch=amd64&features=git" \
      | tar --no-same-owner -C /usr/bin/ -xz caddy \
    && chmod 0755 /usr/bin/caddy \
    && /usr/bin/caddy -version

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile"]
```

**Comment by kevinsimper** [comment]
I misunderstod the proxy syntax and thought it was like nginx, where you can just do it like this because the path is already set at the site block:
http://nginx.org/en/docs/http/ngx_http_proxy_module.html

```
docker.dev:8080 {
    proxy nginx
}
```

**Comment by mholt** [comment]
You can't obtain certificates for internal hostnames - they have to be publicly verifiable.

**Comment by kevinsimper** [comment]
Yes, I did not want certificates, just wanted proxy :)

**Comment by mholt** [comment]
I see. That should be spelled out pretty clearly here: https://caddyserver.com/docs/proxy
