### ISSUE TITLE
Add check before requesting certificate

### ISSUE THREAD

**Issue by meyskens** [mholt/caddy#1018]
It is probably a good idea to add a check to Caddy that it will check if it can control a domain before trying to request a certificate. On-demand TLS seems to generate a keypair once the first request it sent, when sending a bunch of https calls on domains it can't control it still generates keys causing high CPU usage.

**Comment by mholt** [comment]
> It is probably a good idea to add a check to Caddy that it will check if it can control a domain before trying to request a certificate.

We looked into this but ultimately decided that this doesn't work, that simply performing the validation is the best and only way to know for sure.

> On-demand TLS seems to generate a keypair once the first request it sent, when sending a bunch of https calls on domains it can't control it still generates keys causing high CPU usage.

ECC keys are pretty quick to generate, and with Caddy 0.9 you can enable on-demand TLS only for subdomains that you do control, so I don't really see this as an issue...

Thanks for your questions!
