### ISSUE TITLE
Caddy hijacks requests to .well-known/acme-challenge

### ISSUE THREAD

**Issue by bobobo1618** [mholt/caddy#1019]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.0

#### 2. What are you trying to do?

Create/verify Lets Encrypt certificates for non-HTTP services on a server that also happens to run Caddy.

#### 3. What is your entire Caddyfile?
```text
http://*/.well-known {
    root /stuff/.well-known
}
https://domain {
    root /otherstuff
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp -email=me@me.me`

#### 5. What did you expect to see?

```text
certbot certonly --manual -d domain.com
printf '%s' "challenge" > /stuff/.well-known/acme-challenge/challenge
<cert is verified and added here>
``` 

#### 6. What did you see instead (give full error messages and/or log)?

From `certbot`:

```text
Failed authorization procedure. domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://domain.com/.well-known/acme-challenge/challenge
2sU [123.456.789.10]: 500
```

From caddy:

```text
http: proxy error: dial tcp [::1]:5033: getsockopt: connection refused
```

I see in the code that 5033 is the port used for a secondary verification server, so it looks like Caddy is hijacking all requests to that URI for its own purposes.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

```
cat > Caddyfile <<EOF
http://*/.well-known {
    root /stuff/.well-known
}
https://domain {
    root /otherstuff
}
EOF
caddy
<new session here>
certbot certonly --webroot -w /stuff -d domain.com
```

**Comment by mholt** [comment]
Yes, if you have Caddy running, it completes the challenges for you - this a crucial component of Caddy's functionality, so we do not let the user disable it. If you need to use another ACME client for some reason, I recommend turning off Caddy. Thanks for your question!

**Comment by bobobo1618** [comment]
What I was getting at is that it would be better to have Caddy only hijack requests for verifications it has initiated itself. Is there a particular reason why it has to hijack _all_ of them, even when it's clear the request isn't for Caddy?

**Comment by mholt** [comment]
> even when it's clear the request isn't for Caddy?

How this "the request isn't for Caddy" defined, exactly? And why is it so clear?

**Comment by bobobo1618** [comment]
> How is "the request isn't for Caddy" defined, exactly? And how is it so clear? (I ask because I have not yet found a good answer to these questions.)

As I understand it the verification flow looks something like:
- Caddy asks the CA for a cert
- The CA says "respond with XXXX when I request /.well-known/acme-challenge/YYYY"
- When Caddy receives a request for XXXX, it looks at some data structure and responds with YYYY

So a request should clearly not be intended for Caddy if:
- Caddy has not initiated any requests
- XXXX is not in Caddy's path -> response map

**Comment by mholt** [comment]
cf. #549

**Comment by mholt** [comment]
@bobobo1618 I'll have a patch I'd like you to try in a little bit, it'll just require that you build from source.

**Comment by mholt** [comment]
@bobobo1618 Patch is applied with 8e75ae249524e4d39b9ff21907b227c88d1f5a21 - when you have a chance, give it a try and confirm that it works for you! (Make sure to pull the latest.) I will close this for now since I think this is resolved, but please still let me know.

**Comment by bobobo1618** [comment]
Confirmed this works, thanks!
