### ISSUE TITLE
Possible bug in "transparent" preset

### ISSUE THREAD

**Issue by Andrew-Tan** [mholt/caddy#1021]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?
0.9

#### 2. What are you trying to do?
I am trying to run local OSM Tasking Manager which uses Python's Pyramid framework. Pyramid framework runs on port 6543 on localhost. Caddy is used as a proxy to redirect www.example.com to localhost:6543

#### 3. What is your entire Caddyfile?
What works:
```text
www.example.com {
    proxy / localhost:6543 {
        header_upstream Host www.example.com
        header_upstream X-Real-IP {remote}
        header_upstream X-Forwarded-For {remote}
        header_upstream X-Forwarded-Proto {scheme}
    }
    gzip
    ext .html .pdf .md
}
```
What does not work:
```text
www.example.com {
    proxy / localhost:6543 {
        transparent
    }
    gzip
    ext .html .pdf .md
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
```bash
sudo ./caddy
```

#### 5. What did you expect to see?
entering www.example.com will correctly proxy to localhost:6543

#### 6. What did you see instead (give full error messages and/or log)?
If using transparent preset, the main page is able to be loaded, but all css and and js files (and all links with relative path) in the page points to the wrong location. For example, https://www.example.com/js/sample.js is instead pointing to https://http/js/sample.js
It seems that Caddy does not resolve and pass the correct Host header.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Clone OSM Tasking Manager from: https://github.com/hotosm/osm-tasking-manager2 and set it up to run on localhost:6543 (There's tutorial in README), then also set up caddy to proxy to localhost:6543 using transparent preset. Then open a browser to see the difference between localhost:6543 and www.example.com

**Comment by mholt** [comment]
Can you build from source and try again? I think we've fixed this on master already.

**Comment by piotrkowalczuk** [comment]
@mholt could you plz release patch for this fix?

**Comment by Andrew-Tan** [comment]
@mholt Thanks for your reminder:) But I think I'll stick with current version until the next release.

**Comment by mholt** [comment]
Okay, well, I'll just assume it's fixed then...

**Comment by vsivsi** [comment]
FYI, I just verified that this issue (Host request header not properly set when using `proxy` with `transparent` preset) is indeed fixed on the current `master`.
