### ISSUE TITLE
Relative paths in Caddyfile

### ISSUE THREAD

**Issue by bcremer** [mholt/caddy#1022]
This is a follow up the the recent change of the import directives (https://github.com/mholt/caddy/issues/867).

IMO all files based directives like `root`, `log` etc. should be relative to the Caddyfile.

Given I have the Caddyfile of my project in a separate directory say, `contrib/Caddyfile` to keep my project root clean.

In my Caddyfile the log / root paths are referenced relative like this:

```
root ../
log ../var/log/caddy_access.log
```

Now it makes a difference how I start caddy

```
cd contrib && caddy
```

or

```
caddy -conf contrib/Caddyfile
```

A possible solution would be the introduction of a new placeholder eg. `{caddyfile}` that contains the absolute path to the used caddyfile.

```
root {caddyfile}/../
log {caddyfile}/../var/log/caddy_access.log
```

This would remove ambiguity how relative paths are handled.

**Comment by mholt** [comment]
Well this is actually a problem in the broader picture, because Caddyfiles won't always be actual files on disk - they can be loaded over the network, from memory, via an API (soon), etc. In those cases, `import` doesn't make sense, so since that directive is only used with actual file Caddyfiles, it seemed reasonable to make that one relative to the Caddyfile's path.

So I'm not sure that making all paths relative to the Caddyfile is a feasible solution; and what would the value of `{caddyfile}` be in those cases? (This is also really tricky because placeholders aren't evaluated until request-time.)

Maybe you could use an environment variable?

**Comment by avail** [comment]
@mholt Another question on that behalf, why does import not handle both absolute paths and relative paths (just a check whether the path begins with a slash, or, on windows, the second letter be a `:`)

for example: in my Caddyfile I have an `import /home/avail/.caddy/*.conf`, in a conf there, let's say /home/avail/.caddy/avail.pw.conf I have `import /etc/caddy/common.conf`, and it tries importing `/home/avail/.caddy/etc/caddy/common.conf`

**Comment by bcremer** [comment]
@mholt 

> [...] Caddyfiles won't always be actual files on disk - they can be loaded over the network, from memory, via an API [...]

Good point. That's indeed a good reason against `{caddyfile}`. I'll just solve it with a shellscript for now.

Thanks for you prompt answer. Please feel free to close this issue.

**Comment by mholt** [comment]
@avail 
> for example: in my Caddyfile I have an import /home/avail/.caddy/*.conf, in a conf there, let's say /home/avail/.caddy/avail.pw.conf I have import /etc/caddy/common.conf, and it tries importing /home/avail/.caddy/etc/caddy/common.conf

Oops, that's a bug. I reproduced it; can you please file a new issue to document it and so we can track progress? Thanks.

@bcremer 
>Good point. That's indeed a good reason against {caddyfile}. I'll just solve it with a shellscript for now.

It's that and the fact that placeholders aren't evaluated when the Caddyfile is parsed, generally only when a request comes in.

Anyway, sorry that I won't be changing this; there are valid arguments on both sides as well, we just have to choose one thing for paths to be relative to (again, with import being an exception unfortunately), and stick to it. So an env variable or script might help you out here, as you said. Thanks for your question!

**Comment by kalvdans** [comment]
Would still be nice to document that all directives except import, are relative to cwd where you start caddy from.

**Comment by mohammed90** [comment]
Your comment is on a ticket from 10 years ago and pertains to v1.
