### ISSUE TITLE
CORS Directive is not Available  on site 

### ISSUE THREAD

**Issue by stanzheng** [mholt/caddy#1029]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?
`Caddy 0.9.0`

#### 2. What are you trying to do?
enable CORS

#### 3. What is your entire Caddyfile?
```text
xxx xxx ocalhost:80 {
    proxy / localhost:4000 {
        proxy_header X-Forwarded-Proto {scheme}
        proxy_header X-Forwarded-For {host}
        proxy_header Host {host}
    }
   cors / {
         origin            http://allowedSite.com
         origin            http://anotherSite.org https://anotherSite.org
          methods           POST,PUT
         allow_credentials false
        max_age           3600
        allowed_headers   X-Custom-Header,X-Foobar
        exposed_headers   X-Something-Special,SomethingElse
     }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

2016/08/11 16:06:55 no action found for directive 'cors' with server type 'http' (missing a plugin?)

#### 5. What did you expect to see?

ability to download CORS plugin

**Comment by mholt** [comment]
Thanks for the report. It will be on the site again next week (assuming that's when we release Caddy 0.9.1). :smile:
