### ISSUE TITLE
upload addon missing from download options

### ISSUE THREAD

**Issue by smcmurray** [mholt/caddy#1030]
https://caddyserver.com/docs/upload says, "To get it, select this feature when you download Caddy."

But https://caddyserver.com/download doesn't offer "upload" as a choice of directives.

**Comment by mholt** [comment]
Yeah, we're [working on it](https://github.com/wmark/caddy.upload/issues/12) - will probably be there when the next release of Caddy is out. We've had [a few issues](https://github.com/wmark/caddy.upload/issues/12) but they don't appear to manifest on Linux which is what the build server runs, so... I guess I can just hope it works without testing it locally... 😛
