### ISSUE TITLE
"Transparent" option or {remote} of reverse proxy passes incorrect remote IP addresses

### ISSUE THREAD

**Issue by papulovskiy** [mholt/caddy#1031]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.0

#### 2. What are you trying to do?
I'm proxying incoming requests to my Python/Flask application.

#### 3. What is your entire Caddyfile?
```text
https://[hostname] {
        root [root dir]
        gzip
        log /var/log/caddy_access.log
        rewrite {
                if {path} is /
                to /proxy/{uri}
        }
        proxy /proxy 127.0.0.1:5010 127.0.0.1:5011 127.0.0.1:5012 {
                without /proxy
                transparent
        }
        git [deleted] ../ {
                key [deleted]
                hook /hooks/push
        }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Under supervisord:
```text
[program:caddy]
command=[path to caddy]caddy -agree -quic -email "[email]" -conf="[path to config file]Caddyfile"
directory=[path to caddy]
autostart=true
```

#### 5. What did you expect to see?
I expect to get correct values of remote IP addresses in my Flask app by getting header X-Real-IP.

#### 6. What did you see instead (give full error messages and/or log)?
I always see the same IP, no matter where I'm getting request from.
If I change config file to
```text
        proxy /proxy 127.0.0.1:5010 127.0.0.1:5011 127.0.0.1:5012 {
                without /proxy
                proxy_header X-Real-IP {remote}
        }
```
I'm getting following headers:
```text
User-Agent: curl/7.47.0
Caddy-Rewrite-Original-Uri: /
X-Forwarded-For: 83.68.1.88
Host: 127.0.0.1:5012
Accept-Encoding: gzip
X-Real-Ip: 66.249.76.53
Accept: */*
```
There is a difference between X-Forwarded-For and X-Real-IP and the correct value is in X-Forwarded-For.

#### 7. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?
Just check X-Forwarded-For and X-Real-IP headers for requests from different places.

**Comment by mholt** [comment]
This is fixed on master, if you can build from source and try again you should see that; it will go out with Caddy 0.9.1. Thanks!

**Comment by papulovskiy** [comment]
Thank you Matt!
