### ISSUE TITLE
Support for lego's timeout option

### ISSUE THREAD

**Issue by dangmai** [mholt/caddy#1034]
Lego added an option to specify timeout for reaching the ACME server: https://github.com/xenolf/lego/issues/207 Is there any chance that we can change this option from Caddy?

Why it'd be helpful: I run Caddy in containers on IBM Bluemix, and for some reason it takes a long time for Lego to contact the ACME server from the containers (usually more than the default 10 second time out), so the Caddy would sometimes be unable to activate the HTTPS feature.

Thanks!

**Comment by mholt** [comment]
The HTTP timeout is set by changing the whole ACME package's `http.Client` value, which means we could make this a command line flag at best - it won't be customizable on a per-site basis, which I guess is fine.

**Comment by dangmai** [comment]
Yes that'd be enough for my use case. Thanks!
