### ISSUE TITLE
Caddy fails to start

### ISSUE THREAD

**Issue by aek** [mholt/caddy#1038]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3
#### 2. What are you trying to do?
Run caddy with multiple (sub)domain name host/backend definition

#### 3. What is your entire Caddyfile?
```text
import /etc/caddy/sites-enabled/*
```
### 3.1 Imports file template that gets vars between brackets sustituted
```text
{server_name} {
    proxy / http://127.0.0.1:{instance_port} {
        proxy_header Host {host}
        fail_timeout 1s
    }
    gzip
    log /var/log/caddy/instance-{instance_name}_access.log {
        rotate {
            size 50
            age  90  # Keep log files for 90 days
        }
    }
    errors {
        log /var/log/caddy/instance-{instance_name}_error.log {
            size 50
            age  90
        }
    }
}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf=/etc/caddy/caddy.conf

#### 5. What did you expect to see?
Caddy should start always loading valid (sub)domain name host/backend definition. If a (sub)domain name host/backend definition fail to be set properly the others that are ok and previously working should continue working and the bad ones should be reported to the log or when someone access to their urls

#### 6. What did you see instead (give full error messages and/or log)?
If some of the imported files have been bad configured then caddy fail to start and give errors due to letsencrypt certificate resolution or something, for example:
- if the domain name is something like subdomain_name.domain.com or it's malformed for letsencrypt 
- dns resolution for the domain fail
- caddy definition is bad like there is no space before the"{" like "subdomain-name.domain.**com{"**
- log write permission or something like that

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
yes, just create 2 or more (sub)domain name host/backend definition one good and one bad defined and caddy will not run

**Comment by mholt** [comment]
> Caddy should start always loading valid (sub)domain name host/backend definition. If a (sub)domain name host/backend definition fail to be set properly the others that are ok and previously working should continue working and the bad ones should be reported to the log or when someone access to their urls

**Comment by mholt** [comment]
> just create 2 or more (sub)domain name host/backend definition one good and one bad defined and caddy will not run

That is intentional.

> Caddy should start always loading valid (sub)domain name host/backend definition. If a (sub)domain name host/backend definition fail to be set properly the others that are ok and previously working should continue working and the bad ones should be reported to the log or when someone access to their urls

See, I disagree with this. Caddy should not be half-working. See #971 and #872 for same and related discussion.

**Comment by mholt** [comment]
Also, I'm not sure what `{server_name}` is -- it's not a valid placeholder; if you want to use environment variables you need something like `{$SERVER_NAME}`.

**Comment by aek** [comment]
I replace {server_name} with the valid domain names using sed. I will check all the reference issues, but this could take down the whole ecosystem of served domains just because of one of the listed errors or any other that I couldn't imagine now

**Comment by mholt** [comment]
@aek Why does it take all the rest of them down? How can they be up before you start Caddy?

**Comment by aek** [comment]
Suppose that I have a lot of running domains served with caddy and someone add a new one and restart caddy with USR1 or stop and start approach. If the new import file definition contains those errors caddy will exit or not run properly taking down the access to all of those valid domains that were previously running without issues

**Comment by mholt** [comment]
> restart caddy with USR1  ... If the new import file definition contains those errors caddy will exit or not run properly taking down the access to all of those valid domains that were previously running without issues

That's not true: if USR1 fails to reload the config successfully, the old one continues running without interruption. The beauty of graceful restarts. :smile: Now if this is not the case, that should be a specific, fully-reduced bug report.

> stop and start approach

This would be your own fault. :wink: Use USR1 if you can't afford downtime.

**Comment by aek** [comment]
I have this configs generated automatically and I'm adding my own checks in the generation process but I have no idea about what others issues could take down caddy among the listed ones. Also to solve it I need to manually enter to the server to run caddy in the console to see where is the error to fix it and start the service again

**Comment by aek** [comment]
I use USR1 to graceful restarts and I have the caddy down too using that way.

**Comment by mholt** [comment]
> Also to solve it I need to manually enter to the server to run caddy in the console to see where is the error to fix it and start the service again

You'd have to do this if it started anyway, because you'd have to look at logs. Except most people won't look at logs or even turn them on. If Caddy can't enable security for your site, that's a critical error.

> I have this configs generated automatically

That's fine. Use USR1.

**Comment by aek** [comment]
I check it again, USR1 works a few times until get caddy down
