### ISSUE TITLE
proxy to backend be told mixed-content

### ISSUE THREAD

**Issue by Visoar** [mholt/caddy#1040]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.0

#### 2. What are you trying to do?
visit example.com and show the website on localhost:8080

#### 3. What is your entire Caddyfile?
```
example.com {
proxy / localhost:8080 {
        proxy_header Host {host}
        proxy_header X-Forwarded-Proto {scheme}
        proxy_header X-Real-IP {remote}
        }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy

#### 5. What did you expect to see?
show the website on localhost:8080

#### 6. What did you see instead (give full error messages and/or log)?
https://example.com is show,but .js/.css files was requested by http,so chrome blocked it because mixed-content.

code in example.com

```
<link rel="shortcut icon" href="img/logo.ico">
```

when I request example.com, it's redirect to https://example.com but http://example.com/img/logo.ico was requested

**Comment by mholt** [comment]
Does the same thing happen if you build and run Caddy from source?

**Comment by Visoar** [comment]
the same thing happen

![image](https://cloud.githubusercontent.com/assets/2937078/17701746/987ea3b0-63fd-11e6-8e03-5c8083969411.png)

**Comment by mholt** [comment]
I can't reproduce this. What do you have running your backend?

**Comment by Visoar** [comment]
java web with tomcat

**Comment by mholt** [comment]
Your page has this HTML tag in it:

```
<base href="http://wx.shaikebiao.com:80/">
```

Which causes it to use HTTP instead of HTTPS.
