### ISSUE TITLE
build.bash can only be executed when you are in the correct directory

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#1043]
~~~
% ../../mholt/caddy/caddy/build.bash
fatal: No names found, cannot describe anything.
~~~
I would be nice if this worked

**Comment by mholt** [comment]
build.bash could be improved, for sure. Just so you know, it can take two arguments. First one is the output file name and the second one is the path to the repo's folder. The build server uses both arguments so that it can perform a build from a different folder.
