### ISSUE TITLE
static compilation of caddy

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#1047]
Building a static caddy binary of caddy is not support with the build.bash script, this means running it in (Alpine based) dockers is more annoying than it should be.

It would be nice to add a `-static` option to the build script that generates a completely static binary.

**Comment by mholt** [comment]
`CGO_ENABLED=0 ./build.bash` does the trick doesn't it?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] static compilatio..." ]
>`CGO_ENABLED=0 ./build.bash` does the trick doesn't it?

almost, you'll need '-tags netgo -installsuffix netgo' as well to disable glibc
dns stack.

**Comment by mholt** [comment]
Really? I haven't noticed that in my testing. At least, not since... Go 1.4 or 1.5.

**Comment by miekg** [comment]
Ha, cool, that *is* enough.

Note I'm reworking stuff slightly, so that I don't need build.bash also
