### ISSUE TITLE
Caddy with quic enabled is leaking server ports of backend servers

### ISSUE THREAD

**Issue by stp-ip** [mholt/caddy#1051]
#### 1. What version of Caddy are you running (`caddy -version`)?
v0.9.1

#### 2. What are you trying to do?
Testing quic.

#### 3. What is your entire Caddyfile?
-

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy --quic --conf=/Caddyfile --email=mail@example.com

#### 5. What did you expect to see?
One header set to alt-svc:quic="" and one to alternate-protocol:443=""

#### 6. What did you see instead (give full error messages and/or log)?
```alt-svc:quic=":443"; ma=2592000; v="33,32,31,30"
alt-svc:quic=":8080"; ma=2592000; v="33,32,31,30"
alt-svc:quic=":8081"; ma=2592000; v="33,32,31,30"
alternate-protocol:8081:quic
alternate-protocol:8080:quic
alternate-protocol:443:quic```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Run caddy as backend and reverse proxy and enable --quic on both.


Sidenote. It might make sense to not use quic on the backends, but as I wanted to test the implementation this is on as default in all dev/staging envs.

**Comment by mholt** [comment]
I'll look at this in more detail when I'm not running out the door, but just FYI, Caddy doesn't have a QUIC client implementation, so using it to connect upstream to a QUIC server will be futile...

**Comment by stp-ip** [comment]
Yeah it was more to test, than to actually be used on the upstream connection. Same for http/2, wich is not yet used on the upstream connection too. Test all the things ;)

Thanks for looking into it. Probably just adding the header instead of replacing/overwriting it.

**Comment by mholt** [comment]
Well, Caddy doesn't have a QUIC client and this is not something it's likely to support in a while. Also, I think this is expected since proxy just carries the headers from the response back downstream. Perhaps using `header_downstream` in the proxy directive, you could control them:

```
proxy ... {
    header_downstream -alt-svc
    header_downstream -alternate-protocol
}
```

Not sure if that'll do what you want, but I'm not sure what else there would be to do on this for now.

**Comment by stp-ip** [comment]
Sure it's an edge case, but I don't think the protocol specific headers should be pushed downstream. They should be replaced. It's for the communication between client and server including were the client is another server (with the proxy directive). Therefore the "helper" headers aren't needed outside of this communication.

**Comment by mholt** [comment]
@stp-ip So you think we should add those two headers to [hopHeaders](https://github.com/mholt/caddy/blob/1d3212a598e14fa4dbc6f0561faec52fe52f4ecd/caddyhttp/proxy/reverseproxy.go#L263-L274)? (Will doing it break anything?) (Haha, needs moar testing...)

**Comment by stp-ip** [comment]
Yeah add those to hopHeaders and in my opinion it shouldn't break anything, but probably best to check with the quic experts ;)

**Comment by mholt** [comment]
Pinging @lucas-clemente: removing Alt-Svc and Alternate-Protocol headers from hop-to-hop is the correct way to handle it, right? It makes sense, as they seem fairly similar to the Connection and Upgrade headers which deal with the protocol for that specific connection only.

**Comment by lucas-clemente** [comment]
I agree, they should be cleared from hop to hop. If not, the browser might try to connect to one of the backend servers directly, which doesn't make much sense.

**Comment by mholt** [comment]
Thanks Lucas. This is now an easy fix if anyone wants to jump on it!

**Comment by stp-ip** [comment]
As I was the annoying person to push this edge case: #1064
