### ISSUE TITLE
Let's Encrypt DNS and CloudFlare

### ISSUE THREAD

**Issue by d4l3k** [mholt/caddy#1052]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy (untracked dev build)

#### 2. What are you trying to do?
Use Let's Encrypt DNS authorization.

#### 3. What is your entire Caddyfile?
```text
:443
gzip
tls {
  dns cloudflare
  max_certs 100
}

log /var/log/caddy.out
errors /var/log/caddy.err

proxy / http://localhost:8880 {
  transparent
  websocket
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/local/bin/caddy -agree=true -conf=/etc/caddy/Caddyfile -email=rice@fn.lc -quic

#### 5. What did you expect to see?
It use cloud flare as the DNS provider.

#### 6. What did you see instead (give full error messages and/or log)?
```
2016/08/19 16:38:35 /etc/caddy/Caddyfile:4 - Parse error: Unsupported DNS provider 'cloudflare'
```
Nothing in `/var/log/caddy.err`.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Checkout master and build.

**Comment by d4l3k** [comment]
If this hasn't made it into the 0.9 rewrite it should probably be removed from the docs.

**Comment by mholt** [comment]
How did you build Caddy? It's missing version information. You need to plug in the Cloudflare DNS provider. Make sure to check it on the download page: https://caddyserver.com/download

**Comment by d4l3k** [comment]
Oh... I missed that there were pluggable DNS providers. I was just following the https://github.com/mholt/caddy/blob/master/README.md#running-from-source instructions. Maybe there should be a "have you installed the provider" message if caddy can't find it?

**Comment by mholt** [comment]
I'll try to add a line to the readme to clarify that. Thanks!
