### ISSUE TITLE
about html5 canvas drawing problem

### ISSUE THREAD

**Issue by arden** [mholt/caddy#1053]
i'm use nodejs as server, html5 canvas drawing success.
but use caddy as server, html5 canvas drawing can't success.
please see the links as bellow.

caddy server, and nodejs as backend server
https://tuya.tujiao.co/drawing/play/?id=431

nodejs server only
http://tuya.tujiao.co:8361/drawing/play/?id=431

**Comment by mkody** [comment]
For me, it works just fine.

**Comment by tboerger** [comment]
And what does not work? Wrong mime type?

**Comment by arden** [comment]
sorry，the link mistake.
it's 
https://tuya.tujiao.co/drawing/play/?id=431
it's looks like http works fine. but https does not work.

**Comment by mkody** [comment]
Well, it's not a Caddy issue but a problem with the way you load the ressources. 
The json file from `http://tuyastatic.tujiao.co/` needs to be loaded in HTTPS too.
![1471701965](https://cloud.githubusercontent.com/assets/843787/17831691/1aaca28e-66f0-11e6-95b6-5489e8c504e9.png)

**Comment by mholt** [comment]
Yup, make sure you load everything over HTTPS when on an HTTPS page. :+1:
