### ISSUE TITLE
redir requires the `from` to be set for a catch-all when using a specific status code (vs. docs)

### ISSUE THREAD

**Issue by LukeHandle** [mholt/caddy#1055]
#### 1. What version of Caddy are you running (`caddy -version`)?

```
$ /usr/local/bin/caddy19 -version
Caddy 0.9.1
```

#### 2. What are you trying to do?

Create a "catch-all" redirect using instructions from [docs](https://caddyserver.com/docs/redir), but using a specific status code. The docs state:

>To create a "catch-all" redirect, omit the from value:
> `redir to [code]`
>The default status code is 301 Moved Permanently.

This works fine when omitting the status code eg. `redir /path`.

#### 3. What is your entire Caddyfile?
Using a short Caddyfile, but previously tested with:
```
:80 {
    redir /path 307
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Env: RPi 3
```
$ cat /etc/system-release
CentOS Linux release 7.2.1511 (Core)
$ uname -a
Linux hostname 4.1.19-v7 #1 SMP Tue Mar 15 14:54:48 UTC 2016 armv7l armv7l armv7l GNU/Linux
```

Full command used (binary from getcaddy.com downloader):
```
$ /usr/local/bin/caddy19 -log stdout -port 8080 "redir /path 302"
```

#### 5. What did you expect to see?

```
$ curl -sv 0:8080 2>&1 | grep -E "< (Location|HTTP)"
< HTTP/1.1 302 Found
< Location: /path
```

#### 6. What did you see instead (give full error messages and/or log)?

It is interpreting the "/path" as the `from` and the redirect code as the `to`. 

```
$ curl -sv 0:8080 2>&1 | grep -E "< (Location|HTTP)"
< HTTP/1.1 404 Not Found

$ curl -sv 0:8080/path 2>&1 | grep -E "< (Location|HTTP)"
< HTTP/1.1 301 Moved Permanently
< Location: /302
```

#### 7. How can someone who is starting from scratch reproduce this behaviour as minimally as possible?

Should be fairly self explanatory from above, I did my best to be minimal 😉 

It should be noted, this works if I specify the `from` as "/", though the docs imply I don't need to.
```
$ /usr/local/bin/caddy19 -log stdout -port 8080 "redir / /path 302"

$ curl -sv 0:8080 2>&1 | grep -E "< (Location|HTTP)"
< HTTP/1.1 302 Found
< Location: /path
```

edit: sorry for title spam >.<

**Comment by mholt** [comment]
Oops. There is an ambiguity based on argument count between these two syntaxes:

```
redir /from /to
redir /path 307
```

Maybe we need to do some clever parsing of the 2nd argument to see if it's a status code... is that a correct resolution?

**Comment by LukeHandle** [comment]
Honestly, I think changing the docs to specify using "/" as the from would be suitable (assuming that correctly does a catch-all).

If the desire is for a _slightly_ shorter/simpler catch-all directive, then I guess checking the 2nd argument for [300-308] makes sense ;)

And it probably took me more time to write my report than it took for you to arrive and reply 😆

**Comment by mholt** [comment]
> Honestly, I think changing the docs to specify using "/" as the from would be suitable (assuming that correctly does a catch-all).

Unfortunately that's a major breaking change -- which I guess we _could_ do since we're pre-1.0 but I'd rather not... I know many sites depend on the current syntax. So maybe we should go with this:

> If the desire is for a slightly shorter/simpler catch-all directive, then I guess checking the 2nd argument for [300-308] makes sense ;)

I don't know that we should validate the actual code, maybe just see if it's a 3xx integer.

**Comment by LukeHandle** [comment]
And of course "meta" will need to be included in that check as it's also treated to a 301 redirect:

```
$ /usr/local/bin/caddy19 -log stdout -port 8080 "redir /path meta"

$ curl -sv 0:8080 2>&1 | grep -E "< (Location|HTTP)"
< HTTP/1.1 404 Not Found

$ curl -sv 0:8080/path 2>&1 | grep -E "< (Location|HTTP)"
< HTTP/1.1 301 Moved Permanently
< Location: /meta
```

How against are you for leaving the current method as working, but changing the docs to specify that "/" is needed? Or saying in the docs that `redir to` will catch-all redirect to 301, but `redir / to [code]` is needed for a custom response code + catch-all?

I'm not sure I love the idea of preventing people from using a `to` (normally 2nd argument) that matches any of the accepted codes.

**Comment by mholt** [comment]
> Or saying in the docs that redir to will catch-all redirect with 301, but redir / to [code] is needed for a custom response code + catch-all?

The docs do need some help in this regard; I think this is a better solution. Thanks!

**Comment by mholt** [comment]
I've updated the docs and they will go out on the next release.
