### ISSUE TITLE
Header name auto-titlecasing breaks some applications

### ISSUE THREAD

**Issue by ntauthority** [mholt/caddy#1057]
So after a helpful contribution from another user fixed #708, it turns out that ffmpeg/libavformat doesn't handle another, um, concern, though this time it is a spec violation on their end.

Said issue is that even though the basicauth module sets the header as `WWW-Authenticate`, a later part of the server code 'normalizes' header names to `Www-Authenticate`, which, while technically allowed by the spec, breaks libavformat's use of a direct `strcmp`.

I also reported this on the [counterparty ffmpeg tracker](https://trac.ffmpeg.org/ticket/5786), but heard bad experiences about the project's staffing and their responses to 'trivial' bugs - and given how widely libavformat is deployed it could take months to years for a fix to propagate to client applications.

**Comment by mholt** [comment]
Dang, that's too bad. Go's standard library normalizes header casing according to the HTTP/1.1 spec, and HTTP/2 doesn't even have cased header field names. If we don't standardize header field names it will break a number of other applications. From [a Go issue opened a while ago](https://github.com/golang/go/issues/5022#issuecomment-66225169) with your same concern:

> If you have an application that cares, it's broken, has always been broken, and needs to be fixed sooner than later.

So they will have to fix their implementation. Looks like [some traefik users experienced the same problem](https://github.com/containous/traefik/issues/466).

**Comment by ntauthority** [comment]
Ah, that's indeed a shame that the issue happens on a lower level than can be handled by the project... I'm hoping that the ffmpeg developers will fix it; this seems to have been an oversight when [fixing](https://ffmpeg.org/pipermail/ffmpeg-cvslog/2011-March/035813.html) the issue for general HTTP handling back in 2011, but forgetting to change handling in the authentication code... still, this'll bite for a while to come, given the downstream clients embedding libavformat. :(

**Comment by mholt** [comment]
I'm sorry I can't help you here. :confused: Maybe ffmpeg would accept a code change contribution?
