### ISSUE TITLE
Feature Request: QUIC Protocol Support

### ISSUE THREAD

**Issue by ApfelUser** [mholt/caddy#106]
I'd love Caddy to support the [QUIC](https://en.wikipedia.org/wiki/QUIC) Protocol.

It seems that currently [QUIC](https://en.wikipedia.org/wiki/QUIC) doesn't have a lot of changes over [HTTP/2](https://en.wikipedia.org/wiki/HTTP/2), as they share the same [HPACK](http://http2.github.io/http2-spec/compression.html) and the same semantics layer. Instead [QUIC's](https://en.wikipedia.org/wiki/QUIC) main focus is to improve upon [TCP](https://en.wikipedia.org/wiki/Transmission_Control_Protocol) by replacing it with [UDP](https://en.wikipedia.org/wiki/UDP-based_Data_Transfer_Protocol).

What do you think? I'm currently searching for a high performance QUIC/HTTP2 webserver. And I also think that this would be a killer-feature.

I guess, ideally, it would be only a matter of swapping the TCP under the current HTTP implementation, with QUIC's UDP replacement. But I guess it isn't that easy? Isn't it?

**Links:**

  * [Quick Protocol Implementation In Go](https://github.com/romain-jacotin/quic)
  * [Quick Wikipedia Link](https://en.wikipedia.org/wiki/QUIC)
  * [Quick Source](https://src.chromium.org/chrome/trunk/src/net/quic/)
  * [Quick Project](https://www.chromium.org/quic)

**Comment by mholt** [comment]
Great suggestion! I've been keeping a close eye on the progress of QUIC - see issue #47 which also asks about this, and where I first answered about it. We may want to wait until the QUIC protocol is finalized (or nearly so). But don't worry, it's definitely a priority to add support for it as soon as possible.

Thanks for the link to that new QUIC library by the way - it definitely has a long ways to go before it is usable, but I'm watching it now anyway.

**Comment by mholt** [comment]
I'm gonna close this issue so we can keep the conversation in one place - feel free to continue discussing if needed in the other issue. Thanks!
