### ISSUE TITLE
Alternate index

### ISSUE THREAD

**Issue by DeltaWhy** [mholt/caddy#1065]
Is it possible to specify an index file other than index.html? This would be equivalent to nginx's 'index' directive.

My use case is serving a scraped copy of a Wordpress blog - a URL ending in `/feed` should serve the file at `/feed/index.xml`.

I also want to serve the file with content type `application/rss+xml` rather than the default `application/xml` but I believe that's already possible with the existing directives.

**Comment by mholt** [comment]
Not currently, but you can probably do a manual `rewrite` that works similarly. You can use the `mime` directive to serve a Content-Type for .xml files.

Something like this? Maybe @abiosoft would have a better answer :smile::

```
rewrite {
    {path} {path}/index.xml
}
```

**Comment by DeltaWhy** [comment]
I thought that might work but wanted to check if there was a simpler way before digging into it. The conditional is a bit tricky - `/feed`, `/category/foo/feed`, `/feed/podcast` should all rewrite to index.xml, but `/some-page-with-feed-in-title` should not, and `/feed/index.xml` obviously should not rewrite to `/feed/index.xml/index.xml`.

Forgot to mention I tried `ext .html .htm .xml` with no effect.

**Comment by abiosoft** [comment]
You can have this in your Caddyfile.
```
rewrite {
    if_op or
    {path} is /feed
    {path} is /category/foo/feed
    {path} is /feed/podcast
    to {path}/index.xml
}
```

**Comment by circlingthesun** [comment]
@mholt: Your suggestion does not appear to work on caddy 0.9.1.

```
rewrite {
    {path} {path}/index.xml
}
```

It results in a 404 when accessing the site root.
