### ISSUE TITLE
Provide a numeric latency format for easier log parsing/analysis

### ISSUE THREAD

**Issue by seedifferently** [mholt/caddy#1066]
Many http log analysis tools expect the "latency" param to be able to be parsed as a number (e.g. `123` or `123.45`, but not `123ms`). However, caddy does not provide such an option since its `{latency}` value utilizes `time.Duration.String()`.

cf. #995, and [GoAccess](https://goaccess.io/)'s `%T` and `%L` params: https://goaccess.io/man#custom-log

#### 1. What version of Caddy are you running (`caddy -version`)?

`Caddy 0.9.1 (+e8e5595 Thu Aug 18 03:21:48 UTC 2016)`

#### 2. What are you trying to do?

Read the `{latency}` log parameter using [GoAccess](https://goaccess.io/).

#### 3. What is your entire Caddyfile?
```text
:80 {
    log / access.log "{remote} - [{when}] {method} {path} {status} {size} {latency}"
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

#### 5. What did you expect to see?

`111.11.11.11 - [04/Aug/2016:12:28:12 +0800] GET /product/type 200 347 18.86`

#### 6. What did you see instead (give full error messages and/or log)?

`111.11.11.11 - [04/Aug/2016:12:28:12 +0800] GET /product/type 200 347 18ms`

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

See above.

**Comment by seedifferently** [comment]
For reference:

- Apache provides `%D` for microseconds, `%T` for seconds, and `%{UNIT}T` for other formats (https://httpd.apache.org/docs/2.4/mod/mod_log_config.html#formats).
- nginx provides `$request_time` for "time in seconds with a milliseconds resolution" (http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_time).
- The W3C extended log format (utilized by IIS) specifies `time-taken` for number of seconds in milliseconds (https://www.w3.org/TR/WD-logfile.html).

**Comment by mholt** [comment]
If the format was always just ms, would that be suitable? Maybe a `{latency_ms}` placeholder or something. I don't really want to get into time formatting syntaxes...

**Comment by aishraj** [comment]
Hey @mholt I'd like to work on this.
Regarding the formatting syntaxes, I agree with your notion that it would it make more sense to have the value always in ms.

**Comment by mholt** [comment]
Cool, make it be! :)

**Comment by seedifferently** [comment]
@aishraj thanks for picking this up! I've been away on vacation.
