### ISSUE TITLE
Feature: Reload Config on signal

### ISSUE THREAD

**Issue by pastjean** [mholt/caddy#107]
I'd love caddy to reload the config file when receiving a signal,

I would use caddy paired with [consul](consul.io) and hashicorp/consul-template to generate the config file and when something changes in consul the config file is regenerated, i would like to be able to tell caddy that it's config file changed and to reload it when this happens.

__Use case:__

- Consul in a docker container
- Consul template running and generating a Caddyfile
- Caddy in a docker container running with some proxy sites up (to other docker conainers)

*Then:*

- A new service gets up 
- Consul-template updates the caddyfile
- Consul-template sends signal to caddy
- Caddy reload the config

**Comment by pastjean** [comment]
Other service discovery tools have similar processes to configure services automatically, i think reloading the config file from a signal is a nice portable way to do it

**Comment by mholt** [comment]
Glad you brought this up. Planning has already begun for this feature, including an automatic failsafe: Caddy will roll back to the last working configuration if the new one fails to start for some reason.

I like the signal idea - but which signal would be used that would work cross-platform? SIGINT and SIGKILL are the only two that are guaranteed to be present on any OS, and those terminate the process. My other thought was to open a high port on the loopback interface so that a new Caddyfile could be streamed into that any time from the local machine.

We're also working on a RESTful API that can make both incremental and major changes to the server's configuration on-the-fly. You can see its progress on the api branch of this repo.

**Comment by pastjean** [comment]
I don't know how they handle it with other web servers, would need to poke in code, or they communicate through an api (listening on another port with an external tool) or they send a signal.

Apache: https://httpd.apache.org/docs/2.2/programs/apachectl.html (graceful option)
Nginx: http://nginx.org/en/docs/beginners_guide.html


[From wikipedia](https://en.wikipedia.org/wiki/Unix_signal#SIGHUP)

**SIGHUP**:
> The SIGHUP signal is sent to a process when its controlling terminal is closed ...
> ... Many daemons will reload their configuration files and reopen their logfiles instead of exiting when receiving this signal....

I can check this a little, but the rest api to control Caddy is also a good plan

**Comment by pastjean** [comment]
In apache from `./include/mpm_common.h`
```c
/* Signal used to gracefully restart */
#define AP_SIG_GRACEFUL SIGUSR1
````

From mod_so.c
```
 * This module is used to load Apache modules at runtime. This means that the
 * server functionality can be extended without recompiling and even without
 * taking the server down at all. Only a HUP or AP_SIG_GRACEFUL signal
 * needs to be sent to the server to reload the dynamically loaded modules.
 *
```

So I guess those 2 signals (HUP and USR1) are used. I've seen occurences where in windows they use something else

But i also like the idea of the rest api to control the server

**Comment by mholt** [comment]
Would an API be compatible with the etcd/consul workflow? Or possibly a port where a file could be piped in? (I'm not a consul/etcd user so I have no idea.)

**Comment by pastjean** [comment]
An API would indeed be compatible, consul, etcd have a lot of programs (consul-template , kelseyhightower/confd) permit to run a command after a config file has been generated, so would be easy to run something like `curl` to reload or send the config. 

API would also permit new types of interractions, so i kinda like this way.

But signal is always more standard way to reload config. So having both would really be nice. If this is something you think easy to do I would even lend a hand

**Comment by mholt** [comment]
I'm making really good progress on the API - almost ready to "mass-produce" the endpoints for all the middleware.

As for reloading config, what do you mean by "more standard way"? Is there a way to get the signal to work on Windows?

**Comment by pastjean** [comment]
i was meaning : `SIGHUP` is standard on unix systems to reload config. 

For windows systems, I really don't know since normally there is a windows service involved.I don't know how reload is handled. I've just started digging go programs on windows.

**Comment by mholt** [comment]
Okay. Well, I'm not opposed to a quick-and-easy way to reload config, but it does have to be cross-platform. That's why I'm leaning more toward opening a port on loopback and letting a new Caddyfile be piped in through there. But at that point, it's a network request, which is like what the API does anyway, so... it just depends if we want to be required to use HTTP to reload config. The port could just listen for raw bytes, but I'm still not convinced this is necessary since the API will be able to do this.

**Comment by pastjean** [comment]
I'm seeing that even apache doesn't support windows *graceful* reloading without restarting the server completely :confused: So, that is up to you if you want to do the same (unix only graceful reloading) or using the api, which i find a good idea (the api).

**Comment by j-mcnally** [comment]
so if we rely on a socket rather than signal trapping we should probably have a caddyctl binary or something that speaks api to the socket. then we could accomplish hot reloads from the cli via `caddyctl -s reload` or something

**Comment by mholt** [comment]
That's basically what the API will do. If we speak HTTP, then any HTTP client (like curl) can interact with Caddy, no special binaries needed (without precluding others from writing Caddy-specific API clients.)

**Comment by j-mcnally** [comment]
personally i feel like we should ship a cli for the api with caddy, that does basic things like reload. The are must haves to use caddy as a server process in any sort of production environment.

**Comment by mholt** [comment]
@j-mcnally Sure, anyone is welcome to write clients for the Caddy API when it is ready.

Question for you. I'm starting the API endpoint that will do a reload of the config without killing the process. The big question is *Where does it get the config from?* Sure, it's easy if Caddy's input happens to be from a Caddyfile - just reload the Caddyfile and use it as input. But what about input that gets piped into Caddy? I guess in that case we can just return an error code and say that the original input is no longer available. *-or-* we could just restart all the servers using the same configuration as was piped in, but that's inconsistent with loading from the file.

Then we need to remember that the API can make other incremental (or major) changes to the server configuration, altering it from what the Caddyfile had when the server first started. Do we reload the server with its current, mutated configuration or use the Caddyfile from disk?

Of course, if a reload does fail, it will roll back to last working configuration.

I can make this happen, but I need some help figuring out these details. Maybe the request could specify what kind of reload to do? How would that look?

**Comment by mholt** [comment]
After giving it some more thought, I think I've cleared some things up in my head. Here is what will probably happen, feel free to comment if I missed something:

If you use the API to invoke a reload, it only succeeds if Caddy was started with a Caddyfile. When you reload, it just reloads the same Caddyfile, and if it fails, it rolls back. Any changes made to Caddy by the API since it was started would be discarded, since if you invoke a reload, that must mean that you've updated the Caddyfile and want to use that now.

**Comment by pastjean** [comment]
:+1:

**Comment by brodock** [comment]
I have a similar use-case except that I want to integrate it with Chef outside of docker. 
But the whole idea is that a change in machine metadata will trigger chef to recreate Caddyfile and will issue a signaling for reload configuration. 

Caddy has the potential to became the "go to" reverse proxy alternative for the DevOps era.
(Thanks for the hard work)

**Comment by mholt** [comment]
This is almost done.

**Comment by mholt** [comment]
Okay, this just landed in the `le-graceful` branch. You can trigger graceful reload with `SIGUSR1`. This change will soon be merged into the `letsencrypt` branch, which will then be merged into the master branch when nearing release. But if this is something you're very interested to try, go ahead by cloning it down.

If the new configuration is invalid and the child fails to start successfully, the parent process will not terminate and will keep listening. (This is not bulletproof yet: if a startup functions returns an error, for example, the parent may still terminate... same with trying to bind to new ports... I need to work that out later. But if the Caddyfile is invalid, it should failover properly.)

Keep in mind that startup functions _will_ execute on restarts, but shutdown functions will _not_ execute on SIGUSR1.

**Comment by pastjean** [comment]
nice ! good job :+1:

**Comment by coolaj86** [comment]
Is this in the v0.8 beta?

**Comment by mholt** [comment]
@coolaj86 Yep

**Comment by faddat** [comment]
@mholt 

If I understood the thread - currently, caddy has an API, at which I can fire Caddyfiles with an updated configuration.  If I got something wrong, the new config will not take.  

Is that right?  

Is there an established way to use Caddy with Docker across multiple hosts?  

Many thanks
-Jake

**Comment by abiosoft** [comment]
Caddy does not have an API, but it is being worked on. 

You cannot pass a new Caddyfile to caddy yet but you can update the existing Caddyfile and send `USR1` signal to get caddy to restart with new config.

> Is there an established way to use Caddy with Docker across multiple hosts?

I'm assuming you mean as a reverse proxy/load balancer. None yet but there's a work in progress specifically for proxy [here](https://github.com/mholt/caddy/pull/564) with demonstration video [here](https://youtu.be/I0Kax0F1XWM).

**Comment by mholt** [comment]
>  If I got something wrong, the new config will not take.

If you got something wrong *that prevents Caddy from using the new Caddyfile*, the new config will not take. So you could misspell a value and it would still work, but Caddy would not reload if the Caddyfile was malformed or something.

**Comment by faddat** [comment]
@abiosoft @mholt 

Yes, as an RP/LB, you got it.  I'll check out the repo and demo.  I think I'll take a second and tell about my pans, so that if caddy isn't the right tool, you can let me know.  Basically, I want to use caddy to act as the RP for many docker containers across many hosts because I love what it's got going on with let's encrypt.  Is that reason enough?  I mean-- it is certainly not a feature I have seen elsewhere.  Thanks guys.  

@mholt okay, that is what I figured.  

Thanks guys!  BTW..... **CADDY IS GREAT!**

**Comment by mholt** [comment]
Glad you like it :) And see #564 for a relevant PR for what you're wanting. I think.

**Comment by myguidingstar** [comment]
there should be a CLI flag to tell caddy just dry check the config file syntax then print out errors and warnings

**Comment by mholt** [comment]
@myguidingstar You could just start another instance of Caddy with that Caddyfile and it will tell you if there are problems.

**Comment by myguidingstar** [comment]
I thought that will be a bit noisy with unavailable ports (used by running instance) and HTTPS may take some time or even impossible in local machine if public ip is not available. But maybe that's  just fine.

**Comment by mholt** [comment]
Well, if the Caddyfile has problems, it won't even get to that point. If the Caddyfile is good, it will just fail to bind the needed ports and abort anyway.

**Comment by martindale** [comment]
@mholt would you mind putting [this comment](https://github.com/mholt/caddy/issues/107#issuecomment-151275963) in a more public location, perhaps in the documentation itself?  Perhaps point me to the ideal place and I can submit a pull request.

**Comment by mholt** [comment]
@martindale It's on the [CLI](https://caddyserver.com/docs/cli) page already. :wink:

**Comment by hickford** [comment]
For future reference:

    pkill -USR1 caddy

> Reloads the configuration file, then gracefully restarts the server.

https://caddyserver.com/docs/cli#signal

**Comment by codeskyblue** [comment]
Why not use SIGHUP signal, I know nginx use SIGHUP for hot reload signal.

**Comment by mholt** [comment]
@codeskyblue Because Caddy doesn't "hang up" when doing a reload. :wink:

**Comment by codeskyblue** [comment]
@mholt perfect answer

**Comment by wildskyf** [comment]
For people who don't know how to send SIGNAL.

```
sudo pkill -USR1 caddy
```

**Comment by NightMachinary** [comment]
> For future reference:
> 
> ```
> pkill -USR1 caddy
> ```
> 
> > Reloads the configuration file, then gracefully restarts the server.
> 
> https://caddyserver.com/docs/cli#signal

@hickford What about caddyv2? This signal doesn’t work there.

**Comment by francislavoie** [comment]
You run `caddy reload` instead, which under the hood makes a request to the config API.

Please don't comment on years-old issues. Please instead ask your questions on the forums https://caddy.community
