### ISSUE TITLE
Caddy fails with domains that start with numbers 'Parse error'

### ISSUE THREAD

**Issue by rothgar** [mholt/caddy#1076]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.1 (arm on a raspberry pi)

#### 2. What are you trying to do?
host 2 sites

#### 3. What is your entire Caddyfile?
```text
defenestrateeverything.com www.defenestrateeverything.com {
        root wordpress/defenestrateeverything
        gzip
        tls justinleegarrison@gmail.com
        fastcgi / /var/run/php5-fpm.sock php
        rewrite {
            if {path} not_match ^\/wp-admin
            to {path} {path}/ /index.php?_url={uri}
}

www.1n73r.net 1n73r.net {
        root wordpress/1n73rnet
        gzip
        tls justinleegarrison@gmail.com
        fastcgi / /var/run/php5-fpm.sock php
        rewrite {
            if {path} not_match ^\/wp-admin
            to {path} {path}/ /index.php?_url={uri}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
running inside a docker container with 
CMD service php5-fpm start && caddy

#### 5. What did you expect to see?
Both websites hosted from the server

#### 6. What did you see instead (give full error messages and/or log)?
2016/08/27 08:14:06 Caddyfile:11 - Parse error: Unknown directive 'www.1n73r.net'

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
I tried with www.1n73r.net 1n73r.net and both throw the same error.

**Comment by mholt** [comment]
You're missing the closing curly brace to your `rewrite` directive.

**Comment by rothgar** [comment]
@mholt you are completely right. Combination of copy/paste failure and working on something when I should go to bed.

Thanks for the help and sorry for the false issue.

Also thanks for caddy, it rocks!
