### ISSUE TITLE
Location header is not set properly when redirecting to HTTPS

### ISSUE THREAD

**Issue by admiralobvious** [mholt/caddy#1077]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.1

#### 2. What are you trying to do?
Redirect all users to HTTPS based on the load-balancer's X-Forwarded-Proto header.

#### 3. What is your entire Caddyfile?
```
:2015 {
    errors stderr
    log / stdout "{remote} - [{when}] {method} {uri} {proto} {status} {size} {>Referer} {>User-Agent} {path}"

    # Force HTTPS
    redir {
        if {>X-Forwarded-Proto} is http
        / https://{uri}
    }

    # To make History Location work
    rewrite {
        to {path} {path}/ /index.html
    }

    # HSTS
    header / Strict-Transport-Security "max-age=31536000"

    gzip {
        level 1
    }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
CMD ["caddy"] in Docker container.

#### 5. What did you expect to see?
I expect all users to be redirected to https://{uri}.

#### 6. What did you see instead (give full error messages and/or log)?
Mobile users (Chrome on Android, Safari/Chrome on iOS) are redirected to https://localhost instead. This problem doesn't happen with Desktop clients.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

1. Add this to your `Caddyfile`:
```
redir {
    if {>X-Forwarded-Proto} is http
    / https://{uri}
}
```
2. Start caddy: `caddy`
3. Send a request to the server: `curl -vH "X-Forwarded-Proto: http" http://some.host:2015`
4. Notice the Location header is set to: `https:///` while it should be set to `https://some.host:2015`.

**Comment by mholt** [comment]
I was able to reproduce the Location header of "https:///`. The `{uri}` placeholder does not include the hostname, only the path, query string, and fragment. You probably want:


```
/ https://{host}{uri}
```

instead. :+1:
