### ISSUE TITLE
Stuck on 'Activating privacy features...'

### ISSUE THREAD

**Issue by gordonmurray** [mholt/caddy#1078]
I'm using Caddy version 0.8.3 as a Proxy.

This worked well for a number of months, until I tried to restart Caddy today. 

Now its just stuck on 'Activating privacy features...'

My caddyfile is the following and I start it using: ./caddy. The domains and their DNS are online and unchanged.

```text
:80 {
}

my.domain.com:443 {
	proxy / other.domain.com {
		proxy_header Host {host}
		proxy_header X-Real-IP {remote}
		proxy_header X-Custom-SSL "true"
	}
}

```

**Comment by gordonmurray** [comment]
Upgrading to Caddy 0.9.1 solved it, without any other change. It would be great to know what might have cased it though.

**Comment by mholt** [comment]
Would have been helpful to have some log output but I'm glad you fixed it by upgrading. :+1:

**Comment by onodera-punpun** [comment]
I'm running into the same issue right now, running caddy git master.
