### ISSUE TITLE
Caddy fails to start when root points to a folder that doesn't exist (yet) and the browse directive is enabled

### ISSUE THREAD

**Issue by martijnve** [mholt/caddy#1085]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.1 (+e8e5595 Thu Aug 18 05:10:45 UTC 2016)

#### 2. What are you trying to do?
In a project I'm working on the root folder is only placed after caddy is started. If I also enable the browse directive caddy fails to start.

I'm currently working around this by having a dummy webroot in place (with a dummy file in it because there can be no empty folders in the git repo).

#### 3. What is your entire Caddyfile?
```text
:8080
root does_not_exist_yet
browse
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
I run ./caddy in a folder containing only the caddy binary and the Caddyfile on my ubuntu 16.04 machine.

#### 5. What did you expect to see?
I expect caddy to start successfully and give some sort of http error if requesting content before the webroot is put in place. This is what currently happens if I leave out the browse directive.

#### 6. What did you see instead (give full error messages and/or log)?
Caddy crashes during startup with the following error:
2016/08/31 13:37:09 open does_not_exist_yet: no such file or directory

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Place above caddyfile and the caddy binary in a folder cd to the folder and run ./caddy

**Comment by mholt** [comment]
This behavior was introduced in 72bc6932b017edd246c2e6eadd34758e7dee1d68 by @wmark. See #772. It was just one piece of a series of improvements to this middleware. I don't recall it ever being a real problem; in fact I like catching potential errors early like this rather than letting them go unnoticed to fester.

But I do seem to recall removing this check from the `root` directive since sometimes a directive would run a process at startup that creates the root directive before serving actually begins.

Should we just drop this existence check?

**Comment by martijnve** [comment]
Hmm i see your point. There's a balance between protecting people against their mistakes and maximum fIexibility. In both cases I feel the behavior should be consistent (either always crash or never crash) and independent of what directives are used (if possible).

I didn't report this issue because it was causing me any problems that aren't easily worked around, it's just an unexpected gotcha. Maybe there can be an explicit attribute to set to indicate the root may not exist yet. That way user error is cought and flexibility is preserved.

Either way it's not a big issue.

**Comment by abiosoft** [comment]
I think I go for consistency as well. I'd rather caddy not start as a whole than caddy not start when browse is used.

But my preference is to drop the check in browse as well.

**Comment by mholt** [comment]
Okay. I think we can remove the check in the browse middleware's setup function if there are no objections.

**Comment by wmark** [comment]
There's *eager* checks (»fail early«) and deferred ones. Caddy has eager checks in all other places; for example, it won't start if the address to bind is not assigned to a network interface.

Removing the check will just yield an error later provided the error condition.

It's not my decision, but I'd stay with eager checks for consistency and, IMHO, it's easier for beginners to see all errors upon startup than later debugging why something does not work.

**Comment by mholt** [comment]
^ I do agree with that.

I can also see how it's valid for directories to be created during startup before serving actually begins.

I'd still be ok with removing the check here (at least for now) -- it's a simple change and if we have a better way of doing this in the future we can always add it back.

**Comment by mholt** [comment]
Thanks @pbeckmann! Would you like to be made a collaborator so that you can help review pull requests and make improvements in a branch instead of a fork?
