### ISSUE TITLE
QUIC isn't working on Chrome 53 (Caddy from build server)

### ISSUE THREAD

**Issue by betrisey** [mholt/caddy#1088]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.1 (+e8e5595 Mon Aug 29 16:15:56 UTC 2016)
Last build from https://caddy.com/download

### 2. What are you trying to do?
Use QUIC with Chrome 53

### 3. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -quic -agree=true -email=email@example.com

### 4. What did you expect to see?
In the security tab of the Chrome dev tools
Protocol: QUIC

### 5. What did you see instead (give full error messages and/or log)?
Protocol: TLS 1.2
In the network tab, the response header says that the server supports QUIC v30-33 and Chrome 53 only supports QUIC >=34
alt-svc:quic=":443"; ma=2592000; v="33,32,31,30"
alternate-protocol:443:quic

I resolved the issue by building caddy from the source.
Now the header is
Alt-Svc:quic=":443"; ma=2592000; v="35,34"
Alternate-Protocol:443:quic

Could you update the build server please?

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Install Chrome Beta (v53) and download caddy from the build server (https://caddy.com/download)

**Comment by elcore** [comment]
Hello @betrisey,

thank you for your report!!!

ping @mholt

**Comment by mholt** [comment]
Thanks, this will be updated at the next release.
