### ISSUE TITLE
Rewrite to a file not in root directory not being routed through fastcgi

### ISSUE THREAD

**Issue by w4** [mholt/caddy#1089]
I'm using this: 

```
*.dev:80 {
    root /var/www/

    tls off
    gzip
    log stdout
    errors stderr

    rewrite {
        r .*
        ext /
        to {host}/htdocs/index.php?{query}
    }

    fastcgi / 127.0.0.1:9000 php
}
```

To allow for faster development locally, without messing with any config files, however whenever I route to a page I'm getting the raw PHP file back. To counter this I have to set the root directory and then route to `/index.php?{query}` rather than `{host}/htdocs/index.php?{query}`.

```
test.dev:80 {
    root /var/www/test.dev/htdocs/

    tls off
    gzip
    log stdout
    errors stderr

    rewrite {
	r .*
	ext /
        to /index.php?{query}
    }

    fastcgi / 127.0.0.1:9000 php
}
```

**Comment by w4** [comment]
What's interesting to note is that is also happens when not using htdocs.

```
*.dev:80 {
    root /var/www/

    tls off
    gzip
    log stdout
    errors stderr

    rewrite {
        r .*
        ext /
        to {host}/index.php?{query}
    }

    fastcgi / 127.0.0.1:9000 php
}
```

Doesn't work, whereas this does work:

```
test.dev:80 {
    root /var/www/test.dev/

    tls off
    gzip
    log stdout
    errors stderr

    rewrite {
    r .*
    ext /
        to /index.php?{query}
    }

    fastcgi / 127.0.0.1:9000 php
}
```

**Comment by mholt** [comment]
I guess I'm not quite sure what the problem here is specifically. Are you asking a question? Requesting a feature? Filing a bug report? (If a bug report, please use the provided template.)

Closing until we can have anything to act on.
