### ISSUE TITLE
Caddyfiles read from STDIN have empty server types

### ISSUE THREAD

**Issue by mikepulaski** [mholt/caddy#1090]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.1

### 2. What are you trying to do?

Use a config file from STDIN.

### 3. What is your entire Caddyfile?
```text
:2016 {
     root /var/www/public
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`cat Caddyfile | caddy -conf stdin -log stdout`

### 5. What did you expect to see?

Caddy running

### 6. What did you see instead (give full error messages and/or log)?

```text
2016/09/05 18:25:03 no action found for directive 'root' with server type '' (missing a plugin?)
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

`echo -e ":2016 {\n root /var/www/public \n}" | caddy -conf stdin -log stdout`

------

I’ve found and fixed the problem; basically files parsed from STDIN do not have a server type associated with them, so HTTP plugins/directives are not correctly parsed.

I’m attaching a Pull Request which fixes this bug.

**Comment by mholt** [comment]
Thanks! Really appreciate your contribution. :smile:
