### ISSUE TITLE
Rewrite “status” rule unimplemented

### ISSUE THREAD

**Issue by mikepulaski** [mholt/caddy#1092]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.1

### 2. What are you trying to do?

Use the `status` rewrite rule in the `rewrite` directive.

### 3. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

### 5. What did you expect to see?

Caddy running.

### 6. What did you see instead (give full error messages and/or log)?

```text
Activating privacy features... done.
2016/09/06 15:44:35 Caddyfile:10 - Parse error: Wrong argument count or unexpected line ending after ‘status'
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

`echo -e ":2016 {\n rewrite { \n status 200 \n} \n}" | caddy -conf stdin -log stdout`

**Comment by mikepulaski** [comment]
I’ll fork and submit a pull request momentarily.

**Comment by abiosoft** [comment]
This has been removed here https://github.com/mholt/caddy/pull/1042 to provide a permanent fix for this issue https://github.com/mholt/caddy/issues/1012.

It still works if you're on version <=0.9.1 but starting from 0.9.2 (or if you build from source), you will need to use **status** directive instead.

**Comment by ehyland** [comment]
@abiosoft is is possible to use regex path match conditions with the status directive?

I'm trying to achieve the following now it's not possible to use status in rewrites
```
# block access to php files in mysite, framework and cms
rewrite {
  if {path} match /(mysite|framework|cms)/.*\.(php|php3|php4|php5|phtml|inc)$
  if {path} not_match /framework/.*(main|rpc|tiny_mce_gzip)\.php$
  if_op and
  status 403
}

# block access to other files
rewrite {
  if {path} match /\..
  if {path} match \.ss$
  if {path} match web\.config$
  if {path} match \.ya?ml$
  if {path} match ^/vendor/
  if {path} match /silverstripe-cache/
  if {path} match composer\.(json|lock)$
  if {path} match /(cms|framework)/silverstripe_version$
  if_op or
  status 403
}
```

**Comment by abiosoft** [comment]
Try something like this
```
status 403 /forbidden

rewrite {
  if {path} match /(mysite|framework|cms)/.*\.(php|php3|php4|php5|phtml|inc)$
  if {path} not_match /framework/.*(main|rpc|tiny_mce_gzip)\.php$
  if_op and
  to /forbidden
}

# block access to other files
rewrite {
  if {path} match /\..
  if {path} match \.ss$
  if {path} match web\.config$
  if {path} match \.ya?ml$
  if {path} match ^/vendor/
  if {path} match /silverstripe-cache/
  if {path} match composer\.(json|lock)$
  if {path} match /(cms|framework)/silverstripe_version$
  if_op or
  to /forbidden
}
```

**Comment by ehyland** [comment]
That worked, thanks @abiosoft

**Comment by kaihendry** [comment]
I've updated to 0.9.3 and it has been an ENORMOUS ball ache today that

        rewrite {
                r   /\.(.*)
                status 404
        }

has broken. WHY? :(

**Comment by mholt** [comment]
@kaihendry Because #1042

**Comment by kaihendry** [comment]
Breaking the API is always something you **really must avoid** or people will drop this like a hot potato.

The ultra **common use case** is to forbid hidden files or folders (stuff prefixed with a dot). https://caddyserver.com/docs/status annoyingly doesn't answer that.

**Comment by mholt** [comment]
I know breaking changes are inconvenient, I'm sorry about that. [I'd rather make them before 1.0 than after](https://github.com/mholt/caddy/wiki/Compatibility-Notice), frankly, because they have to be had.

What doesn't answer what exactly?

**Comment by kaihendry** [comment]
The question is: "How do I stop Caddy serving hidden files?"

You expect to find the answer in https://caddyserver.com/docs/status but I couldn't.

**Comment by mholt** [comment]
Don't you just specify the files you want to hide, and give them a 404 status?

**Comment by kaihendry** [comment]
Ok, what is the canonical way to hide '.' prefixed files & directories?

**Comment by mholt** [comment]
At this point, something like this:

```
status 404 {
    /.htaccess
    /.hidden
    /.whatever
}
```

How many dotfiles do you have in your site? O.o

(Don't mind my questions -- trying to gauge the needs of users here.)

**Comment by kaihendry** [comment]
Isn't it more reasonable just to do all dotfiles?

This is almost the default I think in Apache
```
<DirectoryMatch "^\.|\/\.">
    Order allow,deny
    Deny from all
</DirectoryMatch>
```

**Comment by mholt** [comment]
Maybe for one user, but not for another. I'm just not sure what their needs are yet. (Now I know what yours are at least!)

**Comment by kaihendry** [comment]
I'm not asking for defaults, I'm asking for documentation that answers the question in a canonical way btw.

**Comment by mholt** [comment]
Hmm, so like an example? Is what I posted above good for that?

**Comment by kaihendry** [comment]
You mean https://github.com/mholt/caddy/issues/1092#issuecomment-251284815 ?

No because it's not in the docs and it doesn't handle all dotfiles.

**Comment by mholt** [comment]
I can't predict all the dotfiles that any user would have :confused:

But thank you for your feedback, I'll look into ways to improve the docs!

**Comment by kaihendry** [comment]
Match any file with a dot prefix!? === dotfile. What's difficult about that? It was one as easy as `r   /\.(.*)`

**Comment by mholt** [comment]
I'm confused, status doesn't have an `r` subdirective. Are you referring to rewrite?

**Comment by kaihendry** [comment]
Well, it used to work ;) https://github.com/mholt/caddy/issues/1092#issuecomment-250957848

**Comment by samwalls** [comment]
Hmm, would be great to apply status to regex match: note, this breaks the default Caddyfile for [grav](https://github.com/getgrav/grav/blob/master/webserver-configs/Caddyfile). I will also open an issue with them.

**Comment by technopagan** [comment]
After digging through the docs & lots of small Caddyfile example snippets, I've now found this thread that discusses this problem.

@mholt I'd love to see Caddy implement an easy way to cleanly block access to all dotfiles while still following other defined rules inside a Caddyfile. Dotfiles creation inside a site's root is sometimes out of our control, e.g. ".gitignore" in subdirectories or ".etckeeper" can pop into existence without us being able to always update a blacklist as suggested when using your example:

```
status 404 {
    /.htaccess
    /.hidden
    /.whatever
}
```

What I've managed to scrape together from all the other Caddyfile examples that I've read while trying to implement this, is the following:

```
# Prevent access to hidden files (.htaccess, .htpasswd, .DS_Store etc)
        rewrite {
                if {file} starts_with .
                to error/index.html
        }

# Prevent clients from accessing to backup, config or source files
        rewrite {
            r /(.*).(bak|config|sql|fla|psd|ini|log|sh|inc|swp|dist)$
            to error/index.html
        }

 status 404 error/index.html
```

While this at least throws the appropriate status code and shows the defined 404 error HTML page, this approach using **rewrite does not honor any custom headers** defined for this location block in the Caddyfile.

Expected headers result:
```
HTTP/1.1 404 Not Found
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Strict-Transport-Security: max-age=31536000;
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Ua-Compatible: IE=Edge
X-Xss-Protection: 1; mode=block
```

Actual headers result:
```
HTTP/1.1 404 Not Found
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Expires: Sat, 07 Jan 2017 01:49:00 CET
Server: Caddy
Vary: Accept-Encoding
```

How can we implement a clean blocking of access to dotfiles + other defined file types without losing control over response headers?

**Comment by mholt** [comment]
@technopagan What version of Caddy are you using? And why are those the expected headers, your Caddyfile doesn't have anything in there to set those or remove the Server header?

**Comment by Zakay** [comment]
I expected also being able disable serving files based on a regex. But only for actual files. If file doesn't exists then it should continue execution as some other rewrite rule might use that path and sends it to another proxy.
