### ISSUE TITLE
Caddy on Plan 9

### ISSUE THREAD

**Issue by kare** [mholt/caddy#1093]
- [0001-Cross-compile-Caddy-for-Plan-9.patch.txt](https://github.com/mholt/caddy/files/457432/0001-Cross-compile-Caddy-for-Plan-9.patch.txt)
- [0002-Remove-non-Plan-9-signals.patch.txt](https://github.com/mholt/caddy/files/457431/0002-Remove-non-Plan-9-signals.patch.txt)
### 1. What version of Caddy are you running (`caddy -version`)?

Current git head.
### 2. What are you trying to do?

I'm trying to run Caddy on 9front (Plan 9)
### 3. What is your entire Caddyfile?

``` text
9p.fi {
    root 9p.fi
    log logs/9p.fi-access_log
    errors logs/9p.fi-error_log
    gzip
}
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?

``` bash
go get github.com/mholt/caddy
cd ~/src/github.com/mholt/caddy/caddymain
# apply attached patches
./build.bash
# deploy caddy binary to plan9
caddy -conf'='Caddyfile &
```
### 5. What did you expect to see?

Caddy doesn't compile out of the box for Plan 9 since rlimit system call and SIGQUIT and SIGUSR1 signals aren't supported on Plan 9.
### 6. What did you see instead (give full error messages and/or log)?

I'm not familiar enough with Go build tags (+build !windows) and build file extensions (*_posix.go) to produce an acceptable patch. However in this case Plan 9 is not a POSIX system. Current build system tries to build it as a POSIX system anyway.

With the attached patches applied I'm happy to announce that Caddy runs on Plan 9!

Some kind of code/build tag reorganization is required to get Caddy running on Plan 9 out of the box.
I'd be happy to help to get it running on Plan 9
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

See [0001-Cross-compile-Caddy-for-Plan-9.patch.txt](https://github.com/mholt/caddy/files/457432/0001-Cross-compile-Caddy-for-Plan-9.patch.txt)

**Comment by mholt** [comment]
You probably can just add `!plan9` to the build tag to exclude it from the build, and add a `*_plan9.go` file -- I think. Or, instead of making a bunch of files, we could just use build tags instead.

Take a look at the docs on build here: https://golang.org/pkg/go/build/

As I don't have time (or convenient access to Plan9 right now), feel free to submit a pull request with modified build tags!

**Comment by mholt** [comment]
Just for fun, I spent 5 minutes and made it compile for Plan 9. If anyone reading this finds it useful, please comment. :flushed:

**Comment by wioxjk** [comment]
Is there any guide to set up a server with Plan 9? I am really interested in starting with it
