### ISSUE TITLE
Feature request:fastcgi timeout options

### ISSUE THREAD

**Issue by Echsecutor** [mholt/caddy#1094]
In nginx, there are various fastcgi  timeout options, e.g.:
http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_connect_timeout
http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_read_timeout

It would be nice to also have these options (or at least know the current values) in caddy.

**Comment by ericdreeves** [comment]
I'll give this a shot.

**Comment by ericdreeves** [comment]
Hello, just wanted to touch base on this request. I'm getting pretty close to a fix and hope to soon have a PR to review!

**Comment by ericdreeves** [comment]
I've noticed an issue with the read_timeout directive. I'm working on the changes. Also, as requested, I'll set default values for both read_timeout and connect_timeout.

**Comment by ericdreeves** [comment]
Work continues. I'll be investigating a send_timeout property next.

**Comment by ericdreeves** [comment]
Hello, @Echsecutor!

We've added the following timeout properties to the fastcgi directive:
* connect_timeout
* read_timeout
* send_timeout

Each of these have a default value of 60 seconds.

Are these updates sufficient? If so then I'll close this issue.

**Comment by ericdreeves** [comment]
Closing.
