### ISSUE TITLE
Question: would caddy/letsencrypt fail to work with certain domain name extensions?

### ISSUE THREAD

**Issue by gordonmurray** [mholt/caddy#1095]
I'm using the latest version of Caddy and its working well for several domain names.

I'm unable to get a cert for a .studio domain name. Would the domain name be an issue?

Thank you.

**Comment by mholt** [comment]
What's the error message? :confused:

**Comment by mholt** [comment]
Closing unless there's any more information we can go off of and identify an issue. Thanks!

**Comment by gordonmurray** [comment]
Hi @mholt My question was mainly to ask if a non-typical domain extension such as a *.studio would have a problem in getting a cert.

In the mean time, I've been able to get it working, so it doesn't seem to be an issue.

**Comment by mholt** [comment]
Should be fine as long as your ACME CA can verify it. (Let's Encrypt doesn't forbid .studio domains AFAIK.)
