### ISSUE TITLE
Let's Encrypt

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#110]
@xenolf is working on this. See https://letsencrypt.org. When completed, Caddy will be able to serve your site over HTTPS automatically and for free, with no setup required.

**Comment by coolaj86** [comment]
I've been able to get the python letsencrypt demo to run successfully https://coolaj86.com/articles/lets-encrypt-on-raspberry-pi/

An interim solution would be to run the python tool manually and have a handler in caddy for `*.acme.invalid` that serves `.well-known/acme-challenge/`.

`letsencrypt` puts the issued certificates in well-defined locations in `/etc/letsencrypt` (see the article) so when the kill SIGHUP and or API are implemented it should be trivial to write a script to fetch the cert and update the config.

**Comment by mholt** [comment]
Status update: [We're making progress](https://twitter.com/mholt6/status/655247573670727681) on the [letsencrypt](https://github.com/mholt/caddy/tree/letsencrypt) branch.

**Comment by mholt** [comment]
Closing in favor of #284.

Btw sorry @xenolf I just found out in a really clumsy moment that I can only assign one person to an issue... :disappointed:
