### ISSUE TITLE
redir with wildcard binding cause 404 error?

### ISSUE THREAD

**Issue by vibbow** [mholt/caddy#1100]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.1

### 2. What are you trying to do?
Set redir with wildcard binding
(Basically I want to bind http://*.vsean.net/[any] and redirect it to https://*.vsean.net/[any])

### 3. What is your entire Caddyfile?
```text
http://vsean.net, http://*.vsean.net {
	redir https://{hostonly}{uri} 301
	header / -Server
}

https://dev.vsean.net {
	tls self_signed
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Windows 10 x64, save above config file as Caddyfile, and just double click caddy to run

### 5. What did you expect to see?
Access  http://dev.vsean.net, redir to https://dev.vsean.net

### 6. What did you see instead (give full error messages and/or log)?
Get an 404 error.

**Comment by mholt** [comment]
Do you have an index file at the root of your site (which is cwd)?

**Comment by vibbow** [comment]
No I dont have a index file.

And I found the workaround for this issue:
redir **/** https://{hostonly}{uri} 301
Just add a slash and problem solved.

┑(￣Д ￣)┍

**Comment by mholt** [comment]
Oh! Yes, if you specify a redirect code, you need all 3 arguments. (You can discard the `/` and `301` to get the same result.)

And if you add an index file, the 404 will go away.

Glad you figured it out!
