### ISSUE TITLE
https does not work

### ISSUE THREAD

**Issue by notedit** [mholt/caddy#1101]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

0.9.1

### 2. What are you trying to do?

enable https

### 3. What is your entire Caddyfile?
```

http://xxxxxx.com,https://xxxxxx.com {
    gzip
    root /root/xxxxx
    log /var/log/xxxxx-access.log {
        rotate {
            size 100
            keep 10
        }
    }

    proxy /   localhost:5001 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -http2 -agree -conf   xxxxCaddyfile

### 5. What did you expect to see?

visite  https://xxxxxx.com  

### 6. What did you see instead (give full error messages and/or log)?

can not visite

**Comment by notedit** [comment]
am i doing some wrong?

**Comment by mholt** [comment]
You closed the issue, does that mean you figured it out?

**Comment by notedit** [comment]
yes   thanks your project
