### ISSUE TITLE
Caddy exits on Lets Encrypt certicate failure

### ISSUE THREAD

**Issue by sexybiggetje** [mholt/caddy#1105]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.1 (+e8e5595 Fri Aug 26 13:30:46 UTC 2016)

### 2. What are you trying to do?
Using a multi domain set up, with a configuration that contains a domainname that isn't yet pointed to the server.

### 3. What is your entire Caddyfile?
Not relevant.

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy

### 5. What did you expect to see?
The working domains being served. Whilst printing the errors to the console, instead of not being able to startup. Some sort of auto renegiotiating when it's being discovered that the domain works. E.g. try every hour.

### 6. What did you see instead (give full error messages and/or log)?
Caddy exiting while requesting a certificate for a domain mismatch.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Configure a random domain not pointing to the same server.

**Comment by mholt** [comment]
Thanks for your report, although this is intentional behavior. The fix is to not ask Caddy to serve a site that is not ready to be served. See #1038.
