### ISSUE TITLE
misleading Markdown support

### ISSUE THREAD

**Issue by tomByrer** [mholt/caddy#1106]
Right on the homepage:

> Modern feature set
Caddy supports HTTP/2, IPv6, **Markdown**

But [v0.9 release notes](https://caddyserver.com/blog/caddy-0_9-released):

> markdown middleware no longer supports static site generation. We did this out of concern for scope creep, and I recommend using Hugo for your static site needs

When I hear Markdown is supported, I automatically think of a MD static site generator.  I think there needs to be clarification, like every time MD is mentioned, say 'dynamically served MarkDown' instead.  Or just drop as a 'feature', & mention you have MD middle where burried somewhere.

OTOH, I'd prefer to use 1 server platform for most everything, since I don't have to learn another API if I want to switch between dynamic & static...

**Comment by mholt** [comment]
Thanks for your comments.

> When I hear Markdown is supported, I automatically think of a MD static site generator.

Static site generation and Markdown are two entirely different concepts. I don't think many people conflate Markdown with "static site generation" -- markdown is used in many contexts, including GitHub comments. I don't think it's reasonable to say that the phrase "Markdown support" is misleading.
