### ISSUE TITLE
Execute redirections before rewrites

### ISSUE THREAD

**Issue by hlidotbe** [mholt/caddy#1107]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.1 (+e8e5595 Thu Sep 01 09:31:58 UTC 2016)
### 2. What are you trying to do?

Redirect old uri to their new location AND rewrite missing paths to default handler
### 3. What is your entire Caddyfile?

``` text
:8080
gzip
log stdout
errors stderr
root /var/www
fastcgi / /var/run/php-fpm.sock php

realip {
  from 172.17.0.0/16
}

redir 307 {
# Lots of from/to (about 200)
}

rewrite {
  r ^/(.*)$
  to {path} {path}/ /index.php?q={1}&{query}
}
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?

Caddy is running in a docker container under runit supervision alongside php-fpm in an alpine 3.4 image.

``` sh
#!/bin/sh
export CADDYPATH=/tmp
exec chpst -u caddy /sbin/caddy -conf=/etc/caddy.conf
```
### 5. What did you expect to see?

I expect/want redirections to be run BEFORE rewrites. So if a redirect matches, it should be executed and stop further processing
### 6. What did you see instead (give full error messages and/or log)?

Not an error per-se but the final url is rewritten to `/index.php?q={1}&{query}` and never matches the redir paths
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

```
:9000

root .
log stdout
errors stderr

redir 302 {
  /something /something-else
}

rewrite {
  to {path} /foo?q={path}
}
```

If I comment the rewrite block I'm redirected to /something-else but otherwise I see in the logs Caddy trying to fetch /foo?q=/something

**Comment by hlidotbe** [comment]
Looking a bit further, I see why it happens. in `caddyhttp/httpserver/plugin.go` "redir" is after "header", way after "rewrite".

Is it preferable that I make a PR and discuss it there?

**Comment by elcore** [comment]
Hello @hlidotbe,

feel free to create a PR 😄 (my opinion)

@mholt what do you think?

**Comment by hlidotbe** [comment]
I was going to do that after the expires plugin 😀

**Comment by elcore** [comment]
@hlidotbe 👍 😄

**Comment by mholt** [comment]
What kind of effects would this change have for those who expect rewrites to happen before redirects?

**Comment by hlidotbe** [comment]
Well it wouldn't work since redirects are "final". It's a bit of a conundrum, most other servers out there (at least nginx and Apache) merge the redirect and rewrite functionality in the same rules. 

While I like that you can express redirects distinctly from rewrite (and much more efficiently), having it separate makes it impossible to have both working correctly when you have some kind of catch all (which is almost always the case with any fastcgi/proxy app server behind caddy).

I can't speak for everybody but we are hosting 50+ sites, rails, WP, Drupal, custom, ... and I can't remember having used redirect rules that relied on the url being rewritten beforehand.

**Comment by mholt** [comment]
@hlidotbe But even with redir + rewrite merged, one of those two actions has precedence over another when both are specified, doesn't it? Do you know what the case is for nginx? (Googling isn't revealing anything obvious for me...)

**Comment by hlidotbe** [comment]
Well no because when merged you get to decide the order and when you terminate at the rule level. You get full control (but it can be more complex and sometimes less obvious so in this regard separating the two concept is nicer).With nginx you can put redirects before, after or in between rewrites, whatever fits your needs best. A way to decide the order at the configuration level would be enough for most cases but I don't see how it would be easily done.

**Comment by mholt** [comment]
> Well no because when merged you get to decide the order

How does that work, though? I'm trying to figure out the logic we would need to implement here.

> With nginx you can put redirects before, after or in between rewrites, whatever fits your needs best.

A redirect is final, though, why would you want to rewrite after a redirect?

FWIW, in your case you could rewrite everything except `/something`, no?

**Comment by hlidotbe** [comment]
> How does that work, though? I'm trying to figure out the logic we would need to implement here.

It's simply rule order. There's 4 flags to a rewrite (well five):

- permanent or redirect, 301, 302
- last stops the processing and restart the search of a matching location
- break stops and serves whatever is found
- nothing continue the rewrite process (meaning you can "build" rewrite by accumulating them)

You just get them in whichever order makes sense to your case.

> A redirect is final, though, why would you want to rewrite after a redirect?

You wouldn't want a rewrite applying to this redirect but in our (and probably most) case we need to NOT rewrite the uri before redirecting. I can turn this around, given more or less the same matching capabilities, why would you want to rewrite something before redirecting the user anyway.

And no I my case I don't want "everything except something". In the first post it's a basic "reproducibility" case. Our case is: we create a new website for a client, we or their SEO agency build a list of old "important" urls that they don't want to go 404 and we redirect them to some new relevant page. Sometime it's less than 10, sometimes we have hundreds. And depending on the "quality" of the previous website then can be more or less "groupables" or completely wild. So, even if it was possible (because redirects are only matching on path and most of the time we need to redirect everything to a single page with a querystring), writing redirects as the expected result of the rewrites is much more tedious and complicated than just /oldurl /newurl.

Actually, that would be less of an issue if caddy had something equivalent to nginx's try_files and named locations. We almost never use actual rewrites with nginx thanks to that construct (but I still think that redirect should come before rewrites if not merged)

**Comment by hlidotbe** [comment]
Thinking about it, I might try to implement something equivalent because that would make life so much easier with proxy and fastcgi. Letting people mix physical files and application's routes seamlessly without resorting to `except` and `without`

**Comment by abiosoft** [comment]
I think it's fine to have redir come before rewrite. I may be wrong but I do not think there is anything that can go wrong since redir also support if conditions.

If not for simplicity, I would not mind rewrite being able to redir. Something like the way proxy can modify headers even though there's header directive.

**Comment by abiosoft** [comment]
This should work but it seems you have a long list of redirects.
```
redir 302 {
    if {>Caddy-Rewrite-Original-URI} is /something
    / /something_else
}
```

**Comment by hlidotbe** [comment]
@abiosoft I don't think it's much of an issue either but obviously there's someone somewhere that needs to rewrite stuff before redirecting. 

The question is: does he uses caddy and is this case more frequent than "simple" redirects ? 😃

And yeah that would force me to have tens or hundreds of redir blocks instead of one tidy block.

**Comment by mholt** [comment]
So this bit me today (very mildly though).

Frankly I have found nginx's rewrite/redirect logic confusing and I would like to avoid that...

I kind of hate this idea, but what if `redir` moved to happen before `rewrite` but we gave `rewrite` the ability to do redirects as well? Basically it applies a redir after rewrites happen. Is that confusing? (I think so, but want to figure this out.)

**Comment by hlidotbe** [comment]
This would be the simplest way. A bit redundant but not too confusing I guess.

**Comment by jleclanche** [comment]
Yep, got bit by this as well just now.

The intuitive behaviour would be to execute redir/rewrite in the order they are specified.

Concrete example: api.example.com/v1/ proxying www.example.com/api/v1/ with helper redirects

```
api.example.com {
        redir /api/v1/ /v1/ 307
        redir / /v1/ 307 {
                if {path} is /
        }
        rewrite /v1 { # core rewrite
                regexp .*
                to /api{uri}
        }
        proxy / ...
}
```

In order:

- First redirect turns actual /api/v1/ urls into /v1/ urls
- Second redirect for the root exactly, directly to /v1/
- *Then* rewrites happen, /v1 into /api/v1

**Comment by jleclanche** [comment]
PS: the `if {path} is /` is required because of `/` being a catch all :/ but that's another issue

**Comment by hotgen** [comment]
I have a related issue. Rewrite goes before proxy and i need the other way around. Is there a better way to implement this?
```
proxy /api localhost:5000
rewrite {
    if {path} not_match ^\/api\/.*
    to {path} index.html
}
```
I'm following [these](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#serving-apps-with-client-side-routing) recommendations.

**Comment by hlidotbe** [comment]
@mholt any update on this one? This is, unfortunately, the only issue preventing us from using Caddy. We had to go back to nginx but I'd love to use caddy as it would simplify a lot of thing.

**Comment by realguess** [comment]
Got hit with a similar problem, but with different plugin:

```
jwt /
rewrite {
        to /{>token-claim-user}/{uri}
}
log / stderr "{path} {rewrite_path} {>token-claim-user}"
```

Looking to rewrite the URL with a new request header generated by `jwt` plugin, so it will serve the file based on user.

I thought the ordering is based on `Caddyfile`, but apparently not. So, rewrite happens before the header was generated by `jwt`.

However, `log` correctly replaces the header placeholder, even it is ordered before `rewrite` in `plugins.go`.

**Comment by mholt** [comment]
@hlidotbe Sorry, no progress. I've been really focused on other things; this issue needs more serious thought before any coding happens.

@realguess 

> I thought the ordering is based on Caddyfile, but apparently not.

Right, if the plugins executed in arbitrary order, it would break lots of things (basically the end of the world as we know it).

> So, rewrite happens before the header was generated by jwt.

It's always possible to reorder the directives, but it's only allowed if it is the _correct_ change. It's not obvious yet how to determine that except through trial and error. (This kind of issue is on my roadmap for future Caddy version milestones, believe me.)

**Comment by hlidotbe** [comment]
I was wondering how hard/stupid/bad for performances it would be to have some kind of user-configurable priority for plugins processing.

Currently it's hardcoded but having some way to alter the order at runtime without depending on directive ordering in the Caddyfile would solve many problems without breaking (too much) stuff.

If it's a priority, we could change it without providing the full list each time, just setting a lower/higher priority on the select few plugin that need to move around.

**Comment by mholt** [comment]
Priorities is one possibility for more thought. The correct ordering of the execution of the plugins' middlewares is _very_ important, though: For example, if `templates` is prioritized before `log`, then any time a templated file is served up, it would never be logged. Or if `errors` came after `fastcgi`, then any errors up to FastCGI or before it would not be recorded/handled.

**Comment by hlidotbe** [comment]
🤔 yeah. Probably not a good idea then. Back to square one then.

It would be interesting to know how many people actually rely on redir being after rewrite. Unless accidental still I don't think it's a common use case. And it makes redir much more complicated to grasp since you have to "preprocess" mentally what the final URL to redirect from will be.

**Comment by realguess** [comment]
It might be a breaking change, but why not give the power to the users. They ought to know that you have to place `log` before `templates`, `errors` before `fastcgi`. But they can `rewrite` then `redir` or `redir` then `rewrite`. If they're not sure what to do, use the default or the recommended way.

If the number of plugins grows, trial and error will not come up to a correct ordering that satisfies all the potential use cases.

**Comment by mholt** [comment]
@realguess If we are to do that, a few big questions need to be answered:

> They ought to know that you have to place log before templates, errors before fastcgi.

How/why? This goes against the Caddy philosophy that it just works; you describe a site by listing features you want in the Caddyfile, not by coding up a procedural config.

> If they're not sure what to do, use the default or the recommended way.

How do we encode the user's uncertainty into the Caddyfile so Caddy can know which to do?

> If the number of plugins grows, trial and error will not come up to a correct ordering that satisfies all the potential use cases.

How about the 90% of use cases then; Caddy has never shot for the 100%. There _is_ a correct order, by the way, middlewares just have to be written and ordered properly. I'm still trying to figure out if the rewrite/redir conundrum is a special case or not.

**Comment by hlidotbe** [comment]
@realguess I have to agree with @mholt, allowing the user to choose that would be way to painful for everyone involved. It was a bad idea.

I think there's really only two (and a half) options:

1. merge redir and rewrite as most/all web servers do which makes the problem disappear and remove all ambiguity about it;
2. order rewrite after redir which may break some use cases but should limit surprises for most;
3. (2.5) allow rewrite to redirect too but that would render redir redundant and often unused when rewrites are involved;

I really like the syntax of redir and it's way more efficient for our use case (mapping lots of old url to new ones) but I'd rather have a merged "rewrite/redir" plugin instead if it can avoid troubles with the rewrites.

That being said it really is not just some small config issue, as it is you basically can't host anything behind a catch all fastcgi/proxy such as a rails app or wordpress instance and have caddy defined redirections.

**Comment by mholt** [comment]
This is mostly irrelevant with Caddy 2, as the order of middleware is defined by the user.
