### ISSUE TITLE
Feature Request: Running caddy as a Windows Service

### ISSUE THREAD

**Issue by Echsecutor** [mholt/caddy#1108]
It would be very useful for a Webserver running on Windows to register it as a service. This would give Caddy an edge over nginx. ;)
http://nginx.org/en/docs/windows.html

Using
https://godoc.org/golang.org/x/sys/windows/svc
this should be doable.

**Comment by mholt** [comment]
Thanks for the request! This has been requested before in #293. You're welcome to add to the discussion there. :+1:

**Comment by Echsecutor** [comment]
Oh, sorry. I did only search for open issues ;)
