### ISSUE TITLE
Please try the API

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#111]
The [api branch](https://github.com/mholt/caddy/tree/api) contains the current progress on Caddy's REST API. I'm at a point now where it would be useful to get your feedback before going further and "mass-producing" endpoints with the help of others. Each middleware will eventually have their own set of API endpoints to do things specific to that middleware - for example, add and remove proxy backends or change TLS settings.

Currently, the API can do the following:

- List servers
- Show info about a specific server
- Start new servers
- Replace all servers with a new Caddyfile
- Stop servers gracefully
- Change a server's root path
- The "ext" middleware (chosen because it's simple):
  - View current state
  - Add it to a server
  - Remove it from a server
  - Set the list of extensions
  - Add extensions
  - Remove extensions

What I need to know from you is if the API is headed in the right direction generally. For the capabilities listed, are there too many endpoints? Too few? Does it follow REST pattern that is familiar to you? Basically - should we continue in this manner?

**Obviously, do not use this in production.** The API has no authentication yet - that will come later. If you have any thoughts about this, please feel free to share. I'm thinking of using Basic Auth. (All API requests must be over HTTPS or it will be forbidden - the exception is an API that's only exposed to localhost.) When completed, the API will be optional but for right now it's always on for testing purposes.

Things are subject to change before the API is finished - this is just a prototype. It is incomplete and probably has bugs. But you can start having fun with it already.

Ad-hoc Documentation
--------------------------------

The API listens on http://localhost:10000. GET requests will have a JSON body in the response. Errors will also have JSON body and, if a client error, it includes the error message.

See the godoc comments and actual code for more information.

When you see :addr in the request path, that's the server address, like `localhost:2015`.

- **List servers**
  - GET /
- **Show info about a specific server**
  - GET /:addr
- **Start new servers**
  - POST /
    - Body must be a Caddyfile from which to create servers. If a new server has the same address as an existing one, the request will fail unless "replace=true" is in the query string.
- **Replace all servers with a new Caddyfile**
  - PUT /
    - Body must be a replacement Caddyfile to use
    - If there is an error, failover mechanism kicks in and Caddy immediately rolls back to last good configuration.
- **Stop servers gracefully**
  - DELETE /:addr
- **Change a server's root path**
  - PUT /:addr/root?root=newroot
    - newroot is the new root path
- **The "ext" middleware:**
  - **View current state**
    - GET /:addr/ext
  - **Add it to a server**
    - POST /:addr/ext
      - Body is the Caddyfile for ext, for example: `ext .html .htm .txt`
  - **Remove it from a server**
    - DELETE /:addr/ext
  - **Set the list of extensions**
    - PUT /:addr/ext
      - Body is JSON array of extensions, like `[".ext1", ".ext2", ...]`
  - **Add extensions**
    - POST /:addr/ext
      - Body is JSON array of extensions, like `[".ext1", ".ext2", ...]`
  - **Remove extensions**
    - DELETE /:addr/ext
      - Body is JSON array of extensions, like `[".ext1", ".ext2", ...]`

Please let me know your thoughts - you'll have to checkout that branch (or [download the zip file](https://github.com/mholt/caddy/archive/api.zip)) and run it from source. I've tried to make the design of the API as easy and convenient as possible to use, so I hope you like it so far. Thanks for getting involved!

**Comment by mholt** [comment]
For changing the site root, should it remain a query string parameter like that or should it be moved to the POST body, where the body is simply the new root path (no JSON)? (I prefer to use JSON only where necessary/convenient.)

**Comment by ApfelUser** [comment]
Some questions and thoughts:

Some options I would see useful for authentication are:

  * TLS authentication
  * IP address authentication
  * Standard Username/Token authentication

Personally I would prefer __IP address__ combined with __TLS__ authentication. But also would have no problem using __Username/Token__ authentication if you decide that you only want to implement the standard one.

Also if there would be an option to don't even open a port and instead listen to a (sub-)domain would be great. E.g. 

```
api api.web.argon.domain.tld
```

"Argon" is just an example because we name our servers after elements.

A question not regarding the API. I can't find an caddyfile with SNI or more than 1 domain in the docs. Can you provide a quick example?

**Comment by mholt** [comment]
Although I can see the utility for IP address + TLS auth, if we implement those, they'll have to wait, since most people would probably like to access their machine from anywhere, and may not always have their cert handy. I think user/pass authentication (over TLS, of course) will be more widely used, so I will probably implement that first.

I like your idea to be able to specify a hostname rather than opening a different port, especially since some firewalls will block things not on port 80 or 443. (Though the default will be :10000). I haven't yet integrated the API config into the Caddyfile, so I'll see what we can do to make this possible when I get to that.

Re: SNI

SNI just happens, you don't have to think about it. For example:

```
domain1.com {
   tls domain1.crt server.key
}
domain2.com {
   tls domain2.crt server.key
}
```

Assuming both those domains resolve to the same IP, Caddy will automatically use SNI to serve both of those on the same port.

**Comment by Nixtren** [comment]
I will probably sooner or later create a basic command line control panel for Caddy (Add websites, remove websites, create reverse proxies and stuff like that), so I decided to check this API stuff.

> Start new servers
> Stop servers gracefully

Does this means starting and stopping Caddy instances? Or starting and stopping websites?

**Comment by mholt** [comment]
@Nixtren Those mean to start and stop websites; you should only need one Caddy instance running per machine (or user, I guess) in most cases.

**Comment by Nixtren** [comment]
Thanks for the clarification @mholt. I usually associate the word "server" with "instance".

**Comment by mholt** [comment]
I've just had an epiphany.

### This API sucks

This current API design is complicated, racey, and not compatible with graceful restarts which, on Linux, will use `syscall.ForkExec()`. (I'm implementing this right now for the Let's Encrypt integration which requires swapping out listeners when certificates renew, which is why I started thinking ahead about the API.) A graceful restart on Unix will require the new process to receive the same configuration that the old process was using. The API can change the config after the process starts, and that mutability makes things *really* complicated, especially since functions can't be serialized and piped to the new process (and the API changes functions, like HTTP handlers).

The level of granularity of this API is very fine and powerful, but also huge and very limiting since so many specific functions need to be implemented.

So I will probably scratch this prototype and start anew.

### New backend design

Here's what I'm thinking: an API with two primary endpoints: GET the Caddyfile, and POST the Caddyfile. (There may be other auxiliary endpoints -- for example, to get the Caddy version -- that don't change the core server configuration.)

The Caddyfile is just plain text, so it can easily be piped to a new process when the server restarts. It also means that the changes can be persisted without any trouble, since all you have to do is GET the Caddyfile or maybe a PUT endpoint would let you save it to disk too, replacing the Caddyfile that Caddy was started with.

This way, the only unit of change is the entire Caddyfile, so all we have to do is restart Caddy (gracefully). A few other little things need to be taken care of (like whether or not to run Startup/Shutdown functions), but that's mainly it.

### API clients

Now, how does an API client do anything useful with the whole Caddyfile, and not specific endpoints? The GET endpoint can return the Caddyfile as plaintext *or* as JSON according to the Accept header. I can write functions that convert between Caddyfile and JSON - it's not too difficult except for Go's static typing. It's worth it since JSON is so ubiquitous.

For example, this Caddyfile:

```
mysite.com, www.mysite.com

root /www/mysite.com
ext .html .md .txt
git git@github.com:user/mysite {
	key /home/user/.ssh/id_rsa
}
proxy /api 127.0.0.1:5001 127.0.0.1:5002
```

Would become this JSON (structure might change; just brainstorming right now):

```json
[
	{
		"hosts": ["mysite.com", "www.mysite.com"],
		"block": {
			"root": ["/www/mysite.com"],
			"ext": [".html", ".md", ".txt"],
			"git": ["git@github.com:user/mysite", {
				"key": ["/home/user/.ssh/id_rsa"]
				}],
			"proxy": ["/api", "127.0.0.1:5001", "127.0.0.1:5002"]
		}
	}
]
```

This is already structured for the client, so all the clients have to do is look up the host and directive they are interested in, and (for example) render a form on the page for the user to change the values.

However the client does it, all it has to do is serialize the changes into JSON (or even simply change the existing JSON) and POST or PUT it to the server. For example, to add a new proxy backend, all you have to do is append to the list of hosts for the "proxy" directive and POST that back. Upon POST, the server will install the new Caddyfile and restart gracefully.

Now you have an API that is incredibly powerful and also remarkably simple and easy to implement.

I'm excited to try this after Let's Encrypt. Meanwhile, thoughts?

**Comment by mholt** [comment]
I have just [committed](https://github.com/mholt/caddy/commit/ee5c842c7d5abb5613b536deb749296beb078bb9) functions that convert between JSON and Caddyfile (not too difficult). I think all that's left are the middleware handlers.

So this may come very soon, but not before the next release.

**Comment by martijnve** [comment]
Awesome work. This will make automatic deployments so much easier. Maybe you want to consider also allowing the caddyfile to be supplied as json in the normal way.

So just start up the server als usual (without using the api) but with a .caddyfile.json instead of a .caddyfile?

**Comment by martijnve** [comment]
Also, with this in place it might be relatively easy to add partial updates and gets.

So for instance if a GET to / results in a list of server blocks, maybe a GET to /mysite.com/ could return just the info for that block.

And then you could *add* an upstream server to with with a POST to /mysite.com/block/proxy with a body of "127.0.0.1:5003".

I'd be willing to build this if you are interested and the basic api is up and runnig.

**Comment by mholt** [comment]
> Also, with this in place it might be relatively easy to add partial updates and gets.

Yes, but this does complicate the API. We'll start simple... and I wouldn't even want to do this at all, but it may be the best way to solve the race of multiple clients changing the Caddyfile at the same time.

**Comment by mholt** [comment]
Another idea to prevent racy use of the API would be to implement something like XPath, where the API client could command the server specifically which token(s) to change, add, or remove using some sort of "path" notation. I'll keep thinking on this.

Serious work on the API will resume before too long.

**Comment by mholt** [comment]
Gonna close this since the API we're keeping is _not_ the one on the current 'api' branch, which will be deleted soon.

**Comment by nii236** [comment]
I can't find any information about the management REST API that Caddy ended up going with, nor can I find it in the source code.

Can someone please point me in the right direction?

**Comment by tobya** [comment]
@nii236 I dont think it every really got as far as being released.  I think it is on the timeline but not yet available.

**Comment by wusatosi** [comment]
@mholt is there any update on the apis? really looking forward to it!

**Comment by mholt** [comment]
Caddy 2 has an API. It is the primary way to configure it, instead of a config file.
