### ISSUE TITLE
force https

### ISSUE THREAD

**Issue by runningman84** [mholt/caddy#1110]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.1

### 2. What are you trying to do?

I would like to force ssl usage. But the documentation is not clear how to do this.

```text
www.example.loc {
...
}
```
it is only serving at port 2015 using https only

```
http://www.example.loc {
        redir https://www.example.loc
}

https://www.example.loc {
...
}
```
Eror message: cannot both use PreferServerCipherSuites and not use it

### 3. What is your entire Caddyfile?

```text
http://www.example.loc https://www.example.loc {

        prometheus 0.0.0.0:9180

        log stdout

        git github.com/xxx/xxx.github.io

        root /tmp/xxx.github.io

        gzip

        tls self_signed
        #tls example@example.com #Your email for Let's Encrypt Verification
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

docker container

### 5. What did you expect to see?

I would expect a automatic rewrite to https://....

The problem is that 

http://www.example.loc https://www.example.loc {

### 6. What did you see instead (give full error messages and/or log)?

```
curl -I www.example.loc
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 9481
Content-Type: text/html; charset=utf-8
Etag: W/"57c2ceec-2509"
Last-Modified: Sun, 28 Aug 2016 11:45:48 GMT
Server: Caddy
Date: Fri, 16 Sep 2016 20:40:07 GMT

curl -k -I https://www.example.loc
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 9481
Content-Type: text/html; charset=utf-8
Etag: W/"57c2ceec-2509"
Last-Modified: Sun, 28 Aug 2016 11:45:48 GMT
Server: Caddy
Date: Fri, 16 Sep 2016 20:40:41 GMT
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Btw. my examples use a self signed certificate the same problem occurs with acme.

**Comment by mholt** [comment]
Thanks for the report -- this was fixed and is already available if you build from source. (See #1075)
