### ISSUE TITLE
Discussion: use of hashicorp go-plugin

### ISSUE THREAD

**Issue by joshglendenning** [mholt/caddy#1111]
The current plugin system is great, but has the disadvantage of needing to recompile Caddy whenever you want to add or remove a plugin. Has something like [go-plugin](https://github.com/hashicorp/go-plugin) or a similar IPC-style architecture been considered? It would be nice to be able to just drop plugin binaries into some plugins directory.

**Comment by abiosoft** [comment]
Worth trying out and looks pretty straight forward.

**Comment by mholt** [comment]
You're welcome to play with the idea for sure -- but I don't think this is something that's going to happen in the near-term. At least, not near enough to keep the issue open. But feel free to continue discussing of course.

Also [note initial plugin package committed on Go tip](https://www.reddit.com/r/golang/comments/53adu8/initial_plugin_support_has_been_merged/) recently.

(At this time I have no plans to change Caddy's plugin design.)
