### ISSUE TITLE
Unexpected proxy behaviour

### ISSUE THREAD

**Issue by Flameborn** [mholt/caddy#1121]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.1

### 2. What are you trying to do?

Use the proxy directive to publish a Fossil repository.

### 3. What is your entire Caddyfile?
```text
repo.MyDomain.com {
log /var/log/caddy.log
startup /usr/bin/fossil server /mnt/hd/rep --repolist --baseurl https://repo.MyDomain.com/ --localhost --https
proxy / https://localhost:8080
shutdown /usr/bin/pkill fossil
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy

### 5. What did you expect to see?

The properly redirected Fossil site on repo.MyDomain.com.

### 6. What did you see instead (give full error messages and/or log)?

The Caddy server started listening on port 8082 (I have a different service running on 8081).

**Comment by abiosoft** [comment]
What do you mean here ?
> The Caddy server started listening on port 8082 (I have a different service running on 8081).

**Comment by Flameborn** [comment]
See this log entry:
"Listening for HTTP requests on TCP port 8082"

**Comment by abiosoft** [comment]
That does not look like a log from Caddy. 
> See this log entry:
> "Listening for HTTP requests on TCP port 8082"

**Comment by Flameborn** [comment]
It seems that this was a mishap in Fossil, which blocked Caddy from binding to any port. The 'fossil server' command is not supposed to return unless it is demonised.

**Comment by abiosoft** [comment]
FYI the process can run in background by suffixing the startup command with `&`.
