### ISSUE TITLE
Caddyfile changed hml imported

### ISSUE THREAD

**Issue by fanyer** [mholt/caddy#1122]
Recently, w3c add some new properties for web components [link](http://w3c.github.io/webcomponents/spec/imports/#link-type-import) . For example. like the HTML tag `link` ,as below: (this is usually used by Google Polymer)
```
 <link rel="import" href="/src/my-app.html">
```

My problem is that when I add a Caddyfile to host a server locally, the html file imported by `link` tag would be interpreted by caddy, which shouldn't be interpreted. However when there is no Caddyfile and I enable the caddy server by defalut, html files are imported normally.

When it is interpreted , caddy seems to nest a `p` tag outside the imported html `my-app.html` ,and this make my web app down.

In addition , I add a template engine plugin [caddy-ace](https://github.com/fanyer/caddy-ace) in caddy for self-use, which like jade for node, as below:
```
= doctype html
html lang=en
  head
    meta charset=utf-8
    = yield title
    link rel="import" href="bower_components/google-chart/google-chart.html"
    script src="bower_components/webcomponentsjs/webcomponents.js"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
```

As a result, I must configure caddy server with a Caddyfile , and this would make my html import down. Could caddy work just like Nginx for those don't need to change?
Is there any solutions?

**Comment by mholt** [comment]
> the html file imported by link tag would be interpreted by caddy, which shouldn't be interpreted

What do you mean by "interpreted"?
