### ISSUE TITLE
Possible to log redirects?

### ISSUE THREAD

**Issue by eldondev** [mholt/caddy#1130]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.2

### 2. What are you trying to do?
Log verbosely. I would like redirects (301, 302, etc) generated in the log.

### 3. What is your entire Caddyfile?
www.example.com {
proxy / 1.1.1.1:8080
tls {
 max_certs 10
}
log / stdout "{remote} - [{when}] \"{method} {uri} {proto}\" {status} {size} {host}" 
errors
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
sudo ./caddy 
On coreos.
### 5. What did you expect to see?
I expected to see 301's logged in the stdout log. For example, if I go to http://example.com, I get 301redirected to https://example.com automatically. It would be nice if this were logged.

### 6. What did you see instead (give full error messages and/or log)?
I only see the 200 in the logs, and only if the client follows the 301 redirect.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Use the above caddyfile with their domain, and curl -Lvv <theirdomain>

**Comment by mholt** [comment]
You can set up logging for the plaintext version of the host. (Also, you don't need on-demand TLS when you specify the hostname in the Caddyfile. So I'll take that out.)

```plain
https://www.example.com {
    proxy / 1.1.1.1:8080
    tls {
        max_certs 10
    }
    log / stdout "{remote} - [{when}] \"{method} {uri} {proto}\" {status} {size} {host}" 
    errors
}

http://www.example.com {
    redir https://www.example.com{uri}
    log / stdout "{remote} - [{when}] \"{method} {uri} {proto}\" {status} {size} {host}" 
}
```

But usually logging these redirects is not very useful.

**Comment by eldondev** [comment]
@mholt Thanks. This seems reasonable, although it wasn't intuitive to me. I think having this logging available might be useful for debugging when clients are connecting from environments where only plaintext connections are allowed. Is there a place that makes sense to specify this behavior in the docs, or is it there somewhere already and I just missed it?

**Comment by mholt** [comment]
Which behavior, exactly? Caddy [automatically redirects HTTP to HTTPS](https://caddyserver.com/docs/automatic-https):

> Caddy will also redirect all HTTP requests to their HTTPS equivalent if the plaintext variant of the hostname is not defined in the Caddyfile.

**Comment by eldondev** [comment]
Explicit log directives in a scheme-less virtual host directive don't apply to the http server started by that directive, is the exact behaviour that is unintuitive to me.

 If my virtual host name doesn't include a scheme, and has an explicit logging configuration, I would expect all requests to that hostname served by caddy to generate a log for that configuration. Specifically, I would expect [this](/mholt/caddy/blob/bedad34b25cfcc67620fa5b854fed020547efbdf/caddyhttp/httpserver/https.go#L139) to include some kind of logging middleware similar to the logging middleware for the parent config. I would be happy to generate such a PR, but your initial response made me think hesitate before jumping into the pool.

**Comment by mholt** [comment]
Well, if this logging is used primarily for debugging, what's wrong with adding those two lines to debug?

I can understand the intuition of the schemeless host, but frankly we don't want the HTTP one doing anything in the server for obvious reasons. The fact that we even have to redirect is regrettable...

**Comment by eldondev** [comment]
No problem with adding the two lines, that method was just not obvious to me. Presumably someone looking for the same answer might locate this github issue, but I might also offer [this](/caddyserver/caddyserver.com/pull/81). Thanks for your help, and for the great work with Caddy overall!

**Comment by mholt** [comment]
Thanks for the PR! I'll take a look.
