### ISSUE TITLE
Cannot disable Etag and Last-Modified headers

### ISSUE THREAD

**Issue by upsuper** [mholt/caddy#1131]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.2

### 2. What are you trying to do?
Disable `Etag` and `Last-Modified` headers.

### 3. What is your entire Caddyfile?
```text
mydomain.com {
        gzip {
                min_length 64
        }
        header /somefile {
                -Etag
                -Last-Modified
        }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy`

### 5. What did you expect to see?
The `Etag` and `Last-Modified` headers are not sent for `/somefile`.

### 6. What did you see instead (give full error messages and/or log)?
They are still sent.

**Comment by upsuper** [comment]
The reason I want to disable `Etag` and `Last-Modified` is that, the file is small enough (e.g. 40 bytes) so that it isn't even worth attaching those headers. (Those two headers can take 38 bytes in HTTP/2.)

**Comment by tw4452852** [comment]
Thanks for reporting, @upsuper .

This is a bug in header directive. I will try to give a fix soon.

**Comment by upsuper** [comment]
FWIW, #843 was raised for Etag header, which was closed as deferred.

**Comment by tw4452852** [comment]
Hi @mholt . 
This issue is due to the expected header(ETag here) hasn't been set when `header` plugin is handling:

```
func (h Headers) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, error) {
        replacer := httpserver.NewReplacer(r, nil, "")
        for _, rule := range h.Rules {
                if httpserver.Path(r.URL.Path).Matches(rule.Path) {
                        for _, header := range rule.Headers {
                                // One can either delete a header, add multiple values to a header, or simply
                                // set a header.
                                if strings.HasPrefix(header.Name, "-") { 
                                        w.Header().Del(strings.TrimLeft(header.Name, "-")) <-- the header may not be set here
                                } else if strings.HasPrefix(header.Name, "+") {
                                        w.Header().Add(strings.TrimLeft(header.Name, "+"), replacer.Replace(header.Value))
                                } else {
                                        w.Header().Set(header.Name, replacer.Replace(header.Value))
                                }
                        }
                }
        }
        return h.Next.ServeHTTP(w, r) <-- the header is set on the following chain actually.
}
```

So we must think out a way to revise the headers after they are actually set but before writing to the underline connection. I think out  a potential way: just implement our own `http.ResponseWriter`, especially its `WriteHeader` method and export a api that registers a operation which will be done before writing headers actually. 

Any idea for this change or do you have some other suggestions?

**Comment by mholt** [comment]
@tw4452852 Hmm, can we do it without buffering the response body at all? Right now we can take advantage of Go's use of `sendfile()` for static files when we don't have to buffer it in memory first; it can flush the contents directly to the socket without leaving the kernel...

**Comment by tw4452852** [comment]
@mholt ,I mean the response headers here not body.

**Comment by mholt** [comment]
@tw4452852 I know, but the headers have to be written out to the response before the body... so we would have to have a place to store the body while we wait for all the headers to be collected, wouldn't we?

**Comment by tw4452852** [comment]
@mholt Yes, the headers are written before the body by  `http.ResponseWriter.WriteHeader()`. We could implement it and revise the headers in it. So I think there is no need to buffer the body.

**Comment by upsuper** [comment]
> Right now we can take advantage of Go's use of `sendfile()` for static files when we don't have to buffer it in memory first; it can flush the contents directly to the socket without leaving the kernel...

Curious whether it is possible for TLS...

Also I think you need to read through the file for generating `Etag` anyway, which reminds me that, if the `Etag` header is suppressed, probably you can just eliminate that step?

So a potential solution would be, add some flag from `header` plugin for headers explicitly suppressed, then skip generating that header in later steps.

**Comment by mholt** [comment]
@tw4452852 If we can do it without buffering the body, then that sounds great - as little footprint as possible... I'd be interested to see how this looks.

@upsuper TLS is at the listener level, not the application layer, so I am not sure if it is excluded, actually... hmmm.

**Comment by mholt** [comment]
Nice work @tw4452852 -- this is a good fix. Thanks!

**Comment by upsuper** [comment]
Thanks for fixing this! Looking forward to the next release :)
