### ISSUE TITLE
caddyserver for iOS?

### ISSUE THREAD

**Issue by jet10000** [mholt/caddy#1132]
I want have a app for storage my files in iphone.

**Comment by mholt** [comment]
I'm gonna tag this for Hacktoberfest and see if anyone wants to tackle this, or see if it's even possible. :smile: Could be fun, I just have no clue.

**Comment by DenBeke** [comment]
So what do you really want, @jet10000? Caddy running on your iPhone with `browse` page of your whole file system? (is that even possible?)

**Comment by jet10000** [comment]
First of all, I want to transfer files between PC and iPhone using the HTTP protocol. Secondly, I look forward to using Web technology to organize, view, and share my files. Maybe have some other ideas. @DenBeke

**Comment by 0xbaadf00d** [comment]
I m not sure you can run Go binary on iOS without heavy modification (maybe change from Go to another language). Whatever you do, you will still need bindings to the iOS API's in order to do anything interesting with it.

**Comment by DenBeke** [comment]
> Whatever you do, you will still need bindings to the iOS API's in order to do anything interesting with it.

We don't really need the iOS API, do we?
Just run the Caddy executable with a Caddy file to browse data on the system...

I'll look a bit into it, but I'm finishing a couple of projects right now...

**Comment by derekargueta** [comment]
iOS uses a sandboxing model such that any application that runs must be an official iOS app, compiled with XCode and all the proper signatures, etc. AKA there's no way to run an arbitrary executable on iOS primarily for security reasons.

http://stackoverflow.com/a/24936109/2540895

**Comment by mholt** [comment]
@derekargueta That's fine -- although I think there's a way for developers to hack an iOS app together and run it on phones, no? I was at Gophercon 2015 when Hana Kim did this demo:

- https://www.youtube.com/watch?v=sQ6-HyPxHKg&feature=youtu.be&t=24m08s
- https://talks.golang.org/2015/gophercon-go-on-mobile.slide#1

**Comment by mholt** [comment]
Just gonna post this here: https://twitter.com/MthsBk/status/831210843287195649 courtesy of @DenBeke

**Comment by mhoIt** [comment]
This is a stupid idea

**Comment by mholt** [comment]
(Disregard any comment notifications you may have gotten from a user account that _looked like mine_ earlier today.)

**Comment by mholt** [comment]
@DenBeke So what ever happened to this? Looks like it was actually working -- kinda sorta. :)

**Comment by DenBeke** [comment]
@mholt There happened nothing more than that...
The lack of time, the lack of a real usecase, and the restrictions of iOS sandboxing made that I couldn't do more than starting Caddy with a Caddyfile. I don't know if I actually committed the code somewhere. Will look for it.

**Comment by mholt** [comment]
@DenBeke Might as well. And/or the instructions to do even what you did - maybe they can go in our wiki. (Thanks in advance!) I'm sure it'll be interesting to someone. Once that is wrapped up we can probably close this issue since an actual, native iOS app is still a ways out, I think, given the current progress of gomobile.

**Comment by DenBeke** [comment]
I did a quick wrap-up about how to run Caddy on iOS (or any other Go app): https://denbeke.be/blog/programming/go-mobile-example-running-caddy-ios/

**Comment by mholt** [comment]
Thanks! I'll link to that.
