### ISSUE TITLE
Quic support is broken

### ISSUE THREAD

**Issue by wendigo** [mholt/caddy#1133]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.2

### 2. What are you trying to do?

Use QUIC on Chrome 53.

### 3. What is your entire Caddyfile?

Does not matter in this case

### 4. How did you run Caddy (give the full command and describe the execution environment)?

./caddy -quic

### 5. What did you expect to see?

QUIC working :)

### 6. What did you see instead (give full error messages and/or log)

When I inspect requests to my site I am not switching to QUIC - forcing QUIC leads to err_quic_protocol_error in Chrome

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

I tried to use quic_client from Chromium project and noticed this:
```
./out/Default/quic_client --quic-version=33 https://serafin.tech
Connected to 52.58.86.221:0
[0924/224005:ERROR:spdy_utils.cc(125)] Malformed header: Header name Alternate-Protocol contains upper-case characters.
```

When I dropped validation in Chromium's SpdyUtils::CopyAndValidateHeaders quic_client works as expected.

It's weird that response headers are uppercase because HTTP/2 spec clearly states:

```
8.1.2 HTTP Header Fields

HTTP header fields carry information as a series of key-value pairs. For a listing of registered HTTP headers, see the "Message Header Field" registry maintained at <https://www.iana.org/assignments/message-headers>.

Just as in HTTP/1.x, header field names are strings of ASCII characters that are compared in a case-insensitive fashion. However, header field names MUST be converted to lowercase prior to their encoding in HTTP/2. A request or response containing uppercase header field names MUST be treated as malformed (Section 8.1.2.6).
```

I don't know if it's related to quic not working in Chrome 53.

**Comment by mholt** [comment]
The current release still uses an older version of QUIC, but next week we'll update it to the newer one. Thanks!

**Comment by wendigo** [comment]
Yeah, you're probably right: https://github.com/lucas-clemente/quic-go/commit/e856c08645698df9187bcb34e27787996050649c :)

And chromium's: https://chromium.googlesource.com/chromium/src/net/+/426ef2caff450b802e58137d79757cb70d2bfcb9

Makes sense to me :)

**Comment by wendigo** [comment]
Ok, you were right @mholt. I've built caddy using own buildsrv with updated quic-go and everything works like a charm on newest Chrome :)

**Comment by mholt** [comment]
That's great news. Will release next week!
