### ISSUE TITLE
Missing path in access logs with fpm and rewrite

### ISSUE THREAD

**Issue by commarla** [mholt/caddy#1137]
### 1. What version of Caddy are you running (`caddy -version`)?
Master :
```
root@334f7c7a0ba3:/app# /caddy/caddy -version
Caddy 0.9.2 (+bac54de Sat Sep 24 08:26:45 UTC 2016)
```

### 2. What are you trying to do?
Display access log with docker logs command.

### 3. What is your entire Caddyfile?
```text
:80 {
  root /app/public
  fastcgi / 127.0.0.1:9000 php
  rewrite {
    to {path} {path}/ /index.php?{query}
  }
  gzip
  log sdtout
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Caddy is dockerized. I'm doing a GET curl on a basic url.
```
curl 'localhost:10801/test/path/?myarg=42' -v
```
### 5. What did you expect to see?
The whole path in access log:
```
172.19.0.1 - [26/Sep/2016:11:18:00 +0200] "GET /test/path?myarg=42 HTTP/1.1" 404 0
```

### 6. What did you see instead (give full error messages and/or log)?
```
172.19.0.1 - [26/Sep/2016:11:18:00 +0200] "GET /index.php?myarg=42 HTTP/1.1" 404 0
```

I think there is a conflict with the rewrite as the real url after rewrite is /index.php?/test/path...

I have tried to play with log format option but I can't find the information anywhere.
`log / stdout "{remote} - [{when}] \"{method} {proto} {uri}\" {status} {size} {latency} {dir} {file} {path} {query} {query_escaped} {uri} {uri_escaped} {>REQUEST_URI}"`

**Comment by mholt** [comment]
Thanks for the report!

I wonder if this is because the `log` directive defers the evaluation of the request's values until after the response has been written -- meaning that `rewrite` has already changed the request path. Maybe we should look into evaluating the request placeholders immediately and defer evaluation of the response ones until later like we do now...

**Comment by abiosoft** [comment]
Try `{>Caddy-Rewrite-Original-URI}`

**Comment by commarla** [comment]
I got a "-" with this header.

**Comment by tw4452852** [comment]
`{>Caddy-Rewrite-Original-URI}` should work. It's actually a bug in replacer!

**Comment by mholt** [comment]
Fixed! Hopefully will go out in a new release today.
