### ISSUE TITLE
Error 502 with PHP  backend on 0.9.2

### ISSUE THREAD

**Issue by devil1591** [mholt/caddy#1138]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.2

### 2. What are you trying to do?
serve some PHP

### 3. What is your entire Caddyfile?
```text
192.168.10.66:80, mydomain.fr:80, mydomain:443
root apache2/htdocs
tls myemail@mydomain.fr
gzip
fastcgi / 127.0.0.1:9123 php
errors apache2/logs/caddy-error.log
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
I'm running Caddy on Windows 2012 R2

### 5. What did you expect to see?
I'm using Caddy and everything work great for a while, and now, since 0.9.2 I'm having many 502 errors. If I go back to 0.9.1, I've got no error.

### 6. What did you see instead (give full error messages and/or log)?
Some errors I get in the log file:
```text
26/Sep/2016:21:38:24 +0200 [ERROR 502 request.php] write tcp 127.0.0.1:53995->127.0.0.1:9123: wsasend: Une connexion existante a dû être fermée par l’hôte distant.
26/Sep/2016:21:38:46 +0200 [ERROR 502 graph.php] fcgi: invalid header version
```
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
I suppose it will happens on any PHP backend...I haven't made tests that way.

**Comment by abiosoft** [comment]
This is the same issue reported here https://github.com/mholt/caddy/issues/1128 but a fix is on the way here https://github.com/mholt/caddy/pull/1129 and here https://github.com/mholt/caddy/pull/1134.

You can build from source right now (which has the broken feature disabled) or wait till later this week for 0.9.3 that comes with the proper fix.

**Comment by devil1591** [comment]
Sorry for the duplicate. Thanks for your work Abiosoft
