### ISSUE TITLE
Caddyfile and hashed password

### ISSUE THREAD

**Issue by clement-igonet-at-galaxy-semi** [mholt/caddy#1142]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.2
### 2. What are you trying to do?

I'd like to http basic authentication inside Caddyfile, without being force to write my plain text password.
Moreover, I'd like to push my commits in a git repo. So, I can not imagine to let my plain text password in it.
### 3. What is your entire Caddyfile?

``` text
xxx.yyy.net {
    basicauth / user:$2y$05$iIhoKBnUjfoz9HjV6OOHYO4GD7uVbcrP1PbByFx6K2tOxxaEE/E/6
    proxy / 10.0.50.1:8080 {
        transparent
    }
}
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?

As a systemd service in debian jessie (8.5) with caddy-ansible role.
### 5. What did you expect to see?

I expect basic auth to work without suggesting to write my plain text password.
### 6. What did you see instead (give full error messages and/or log)?

I get a deprecated warning about using htpasswd in the documentation
I get source code able to maange hassh password
I get no implementation if hash inside Caddyfile itself, but a documentation suggesting to write plain text password.
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

It's not a real bug but I think a very big improvement to do in term of minimal security level.

**Comment by pbeckmann** [comment]
Hello,

two ideas for this.

1. Extend the original _basicauth_ directive with a parameter for the hash algorithm or just that the password is hashed. Maybe its cleaner, but i think it makes the syntax more complex.

2. Prefix the given password, so for example `sha1=0a4d55a8d778e5022fab701977c5d840bbc486d0` to use _Hello World_ as a password. So in the development everybody could use plain passwords and for the production we can use hashed ones.

Greetings

**Comment by clement-igonet-at-galaxy-semi** [comment]
Ho please... Whatever is the environment we are working on (development or production env), storing plain text password is a bad solution.

If we want to give caddy a little bit of credibility in term of security, we should not let the ability to rely on plain text password at all, but rely on a format like the one used by /etc/shadow. This last is extensible and let the ability to use salted hash with a decent algorithm.

**Comment by clement-igonet-at-galaxy-semi** [comment]
Ho no, please!
Whatever we are working on a dev or production environment, relying on plain text password is a bad solution.
We should not accept the ability to use plain text password, but rely on format like those used in /etc/passwd. It's well known, extensible, and let the ability to use salted hash password with decent algorithms.

F.Y.I.: your sha1 hash could be brute forced with a dictionnary !

**Comment by pbeckmann** [comment]
Hey,

if you want a strong security, it shouldn't use HTTP Basic Authentication (in my opinion). 

For that there are plugins like https://caddyserver.com/docs/multipass.

In my opinion a change here in the BasicAuth middleware shouldn't break older installations of caddy.

Greetings

**Comment by yumaikas** [comment]
If multipass is a stronger password system than HTTP basic auth, should the basicauth docs be updated to point to it as a solution?

**Comment by pbeckmann** [comment]
Hello

> If multipass is a stronger password system than HTTP basic auth, should the basicauth docs be updated to point to it as a solution?

I think the docs contain a really good description, about what BasicAuth is and what not. And multipass is not really a "better" alternative. It's just an other way of authentication, which removes user credentials from the caddyfile.

But this is going to be OT.

If @mholt or other maintainers think we should use hashed passwords, it would be nice to get their comment here, and i'll look into a useful Merge Request for it.

Otherwise i suggest to close this issue 

Greetings from Germany

**Comment by mholt** [comment]
You could use environment variables to store your password and then you can just reference the env variable in the Caddyfile like so: `{$MY_PASSWORD}`.

But I agree, I think with the use of env variables, that should satisfy this request. The question is more about password storage than basicauth itself.

**Comment by clement-igonet-at-galaxy-semi** [comment]
Well, playing with environment variable is not the solution, it just shift the problem outside the config file.
The main problem is to keep clear passwords somewhere in the machine.
The problem is not just "about password storage", the problem is about the way we decide to implement "basicauth itself".
Multipass is a totally different solution, out of scope.
I don't think this case should be closed as is. But if you're not at all concerned by a minimal security level...

**Comment by ywLBhGk2noZLbY7** [comment]
I have to agree with @clement-igonet-at-galaxy-semi, utilizing environment variables still keeps the passphrase in plaintext somewhere on the system and is, as such, not an viable solution.

As of current, I am using .htpasswd, which from my understanding does allow hashed passphrases, however is current deprecated by Caddy and as such also isn't a viable solution.

**Comment by pbeckmann** [comment]
Hello,

.htpasswd is not safer than hashed passwords without salt in Caddyfile.

And the chosen hash procedure md5 in .htpasswd without salt is broken...

So you could prevent the hacker from using Google to decrypt the password and store it in plaintext.

And I have no idea how to use that salted, cause then the salt must be stored somewhere in clear text....

Greetings

**Comment by mholt** [comment]
> The main problem is to keep clear passwords somewhere in the machine.

> utilizing environment variables still keeps the passphrase in plaintext somewhere on the system and is, as such, not an viable solution.

If your machine gets compromised, it doesn't matter anyway. If your env is not safe, you've got bigger worries. ;)

**Comment by clement-igonet-at-galaxy-semi** [comment]
Well, mholt, I really appreciate caddy because of his simplicity to use. It does just work, it's so good to use in a DevOps automated environment.
And then, because I'm used to put all my scripts (vagrant, ansible, jenkins, caddy, ssh public keys) to automatically mount virtualized server infrastructure, I'm also confortable with the idea of putting my hashed+salted password (with good algorithm and size) in a (limited) shared repo because I trust in the way it is obfuscated.

And no, in this way, my machine is not compromised and I feel confortable enough to keep my clear password secret for some years.

F.Y.I., trusting in an algorithm for a delimited period is what is applied with all modern certificates that used exposed hashes to sign data.

**Comment by clement-igonet-at-galaxy-semi** [comment]
So, is there a chance to reopen this case.
To summarize, I suggest an important enhancement quite easy to implement.
I feel you don't understand my request and you autoritarily close it. Is it the way you want people to help you?

**Comment by elcore** [comment]
> So, is there a chance to reopen this case?

Yes and No! Authentication should be done by the application, not by the server!

> To summarize, I suggest an important enhancement quite easy to implement.

Feel free to implement it!

> I feel you don't understand my request and you autoritarily close it. Is it the way you want people to help you?

We totally understand you, but basicauth should only be used in development (to test restricted access), not in production.

**Comment by clement-igonet-at-galaxy-semi** [comment]
So, what's the interest of testing basicauth restricted access by server in development only?

Why do you suggest me to do it myself if you think it's not for production?

Well, Ok, I'll do it myself...

**Comment by elcore** [comment]
> So, what's the interest of testing basicauth restricted access by server in development only?

Security!

> Why do you suggest me to do it myself if you think it's not for production?

Authentication should be done by the application e.g. 2FA or you could use https://caddyserver.com/docs/multipass

> Well, Ok, I'll do it myself for myself...

Good luck 😄

**Comment by mholt** [comment]
@elcore

> Yes and No! Authentication should be done by the application, not by the server!

The server can help with authentication in some cases.

> basicauth should only be used in development (to test restricted access), not in production.

Not necessarily -- again, it depends on the threat model. Production use of basic auth is fine for some things if done properly (and Caddy does it pretty well, as long as the user protects the credentials on their machine).

@clement-igonet-at-galaxy-semi 
> So, is there a chance to reopen this case?
To summarize, I suggest an important enhancement quite easy to implement.
I feel you don't understand my request and you autoritarily close it. Is it the way you want people to help you?

This issue has a couple different things going on that make it a little confusing. You want a way to use basicauth without writing the plaintext password in the Caddyfile, and we showed you a way using environment variables. So I closed the issue. Then it shifted to be more about hashing passwords _anywhere_ on the machine which is outside of the scope of Caddy.

If you're specifically requesting the ability to paste a hashed password into the Caddyfile, then maybe we should open a _new_ issue to discuss that specific feature request without the cruft of the rest of the earlier discussion. We would have to discuss important implementation details such as hashing algorithm, salt, whether we allow use of hashes with weak algorithms or without salt, etc.

**Comment by elcore** [comment]
@mholt 

> The server can help with authentication in some cases.
> Not necessarily -- again, it depends on the threat model. Production use of basic auth is fine for some things if done properly (and Caddy does it pretty well, as long as the user protects the credentials on their machine).

Right, basic auth is fine for simple things. In terms of security, there are better implementations (https://caddyserver.com/docs/multipass).

Have a nice day Matt 😄

**Comment by clement-igonet-at-galaxy-semi** [comment]
I really feel misunderstood since the beginning of this case, in any point. So, it must come from me, sorry for that. I disagree your explanations.
Putting the clear password in an environment var does not solve the problem, it just put it somewhere else.
I'm not talking about having password anywhere, but just in Caddyfile.
Rather than just closing my case and good bye, I would have prefer you create yourself the new case you suggest if requered.
About specs: it's the same as /etc/shadow

**Comment by mholt** [comment]
@clement-igonet-at-galaxy-semi 

> I really feel misunderstood since the beginning of this case

Sorry about that. In your original issue you said that what you are trying to do is: "I'd like to http basic authentication inside Caddyfile, without being force to write my plain text password.
Moreover, I'd like to push my commits in a git repo. So, I can not imagine to let my plain text password in it." And we gave you a way to do that with env variables, which in my understanding closed the issue.

> I would have prefer you create yourself the new case you suggest if requered.

This is a feature _you_ are requesting; I would like you to create it and describe exactly how you want it. :+1: If accepted, before anyone can implement it, they'll need all the details in the issue so they know exactly how it works and they (or you) can write the code to do it.

> I disagree your explanations.
Putting the clear password in an environment var does not solve the problem, it just put it somewhere else.

As I said, from your original issue statement, it does solve the problem you mentioned. :wink: This is why I suggest creating a new issue with a very specific, well-thought-out, and detailed feature request, so that somebody can implement it if accepted. (Saying "same thing as /etc/shadow" isn't specific enough, unfortunately -- and it assumes that all the developers are Unix gurus!)

**Comment by clement-igonet-at-galaxy-semi** [comment]
Ok!
