### ISSUE TITLE
FastCGI troubles with release, not on development

### ISSUE THREAD

**Issue by DenBeke** [mholt/caddy#1148]
When running Caddy 0.9.2 with a standard PHP-FPM 7 installation, Caddy (or PHP) serves random pages. The Caddy log shows the correct page.

The debug this problem I compiled Caddy from source and printed out the FastCGI `scriptName`. But since I ran it from the master it works perfectly again. (and does print out the correct `scriptName`)

Is this a known bug that was already fixed for real? Or should I look into this?
I hope you have enough information...

**Comment by elcore** [comment]
Hello @DenBeke,

could you test if this bug occurs in Caddy 0.9.3?

Soon,

Eldin H.

**Comment by DenBeke** [comment]
Okay, apparently we're already on Caddy 0.9.3. But I downloaded Caddy from website a couple of hours ago... And that version was apparently 0.9.2.

Just downloaded Caddy again and it's 0.9.3 (and this solves the problem). I guess it's all fine then?

**Comment by elcore** [comment]
@DenBeke everything is fine 😄
