### ISSUE TITLE
Backend unreachable after canceling request

### ISSUE THREAD

**Issue by crackcomm** [mholt/caddy#1149]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.2

### 2. What are you trying to do?

Access a URL through caddy after previous request was canceled.

### 3. What is your entire Caddyfile?

```text
domain.com {
  proxy / nginx:8080 {
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy --conf /etc/Caddyfile

### 5. What did you expect to see?

web page

### 6. What did you see instead (give full error messages and/or log)?

502 Bad Gateway

backend was marked as unreachable

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Sure, just use a slow endpoint behind proxy and request it, cancel request and try again.

**Comment by mholt** [comment]
Hi, please upgrade to the latest Caddy version first and try again. Thanks!

**Comment by crackcomm** [comment]
Thanks! It works now. I missed the latest update, sorry about that.

**Comment by elcore** [comment]
@crackcomm You do not need to be sorry 😄
