### ISSUE TITLE
Take advantage of writev()

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#1151]
We should look into possible ways [this recent commit to Go](https://github.com/golang/go/commit/8e69d43b32be578cd36eebe491b6e1205dbf32a4) could improve performance or reliability of certain functions of Caddy. I don't really have a solid grasp on this yet but wanted to put it out there to see if anyone might be interested in this.

(Related discussion: https://github.com/golang/go/issues/13451)

**Comment by notedit** [comment]
cool

**Comment by mholt** [comment]
Well, I can't find anywhere in Caddy that we use a `[][]byte` or even "multiple byte slices" in general over the network. And if we do, I'm not sure it would even be this performance-critical. So, closing.
