### ISSUE TITLE
'root' directive requires argument, docs say otherwise

### ISSUE THREAD

**Issue by elimisteve** [mholt/caddy#1156]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

0.9.3

### 2. What are you trying to do?

Tell Caddy to serve a static site.

### 3. What is your entire Caddyfile?
```text
https://www.cryptag.org
root
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

In a screen session with

    $ sudo ~/bin/caddy

### 5. What did you expect to see?

Caddy successfully start

### 6. What did you see instead (give full error messages and/or log)?

```
$ sudo ~/bin/caddy 
2016/10/01 10:28:19 Caddyfile:2 - Parse error: Wrong argument count or unexpected line ending after 'root'
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Specify whatever domain you want, then on the second line just put 'root'.

**Comment by elimisteve** [comment]
@mholt Perhaps these docs https://caddyserver.com/docs/root are just out of date?

Just putting `root` didn't work, but `root .` did.

**Comment by elimisteve** [comment]
Perhaps this argument was originally optional, and is now mandatory?

**Comment by mholt** [comment]
Thanks for the question... If you use the root directive, the path has always been always required, the docs don't have the `path` argument in brackets (`[path]`) meaning it's required.

**Comment by elimisteve** [comment]
@mholt I see, thanks. You may want to clarify what "The default root is the current working directory." means. (How can this default be used?)

**Comment by mholt** [comment]
If you don't change the root, the default one is the current working directory... you don't do anything to use the default. It's just that... by default...
