### ISSUE TITLE
Support for Protocol Handshake Header in Websocket connections

### ISSUE THREAD

**Issue by InAnimaTe** [mholt/caddy#1170]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.3

### 2. What are you trying to do?

SSL/TLS Reverse Proxy Websocket connections to a WAMP router provided by Crossbar.io

### 3. What is your entire Caddyfile?

Initially, I tried everything with the following caddyfile:

```text
wamp.arroyonetworks.com {
    proxy / localhost:14553 {
        transparent
        websocket
    }
    tls {
        max_certs 1
    }
    errors
}
```

But only got errors like `04/Oct/2016:17:49:24 +0000 [ERROR 502 /] EOF` when connecting via browser and `wss`.  This seems to induce that the backend is closing the connection.

Then, after deeper inspection into headers (thx wireshark), I found the `Sec-WebSocket-Protocol` is necessary for the wamp router backend to actually continue with the connection, or else, it closes it, explaining the above errors.

You can see more information about Protocol Handshake requests [here](https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake) and [`Sec-WebSocket-Protocol`](https://tools.ietf.org/html/rfc6455#section-11.3.4)

```text
wamp.arroyonetworks.com {
    proxy / localhost:14553 {
        transparent
        websocket
        header_upstream Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}
    }
    tls {
        max_certs 1
    }
    errors
}
```

The above config works perfectly fine ;)

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Running in the Docker container `abiosoft/caddy:0.9.3`

`caddy -conf="/etc/Caddyfile" -http2=false -log=stdout`

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Use a crossbar docker image, a config.json that serves a websocket connection, and declare config in caddy like above.

### So why am I opening this

In my belief, Caddy should handle and automatically send through `Sec-WebSocket-Protocol` to backends. This header should be included in the `websocket` config option as it is critical to a large set of modern applications which need to clearly define subprotocols on which to operate of websocket connections.

**Comment by mholt** [comment]
Okay, this is an easy fix. Thanks for looking into it!

**Comment by ericdreeves** [comment]
Hello,

I took a shot at a fix but I'm a little confused about the desired behavior.
I'm new to Caddy so please excuse any misunderstandings that I may have.

Adding an upstream header via:

	header_upstream Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}

does indeed add the header to the upstream request, however it will be empty
if the header did not exist in the original request.

Is the request to always include the header, even if it has no value? Crossbar
did not like that: it responds with HTTP 400 before closing the TCP connection.

Or, is the request that Caddy negotiate the WebSocket subprotocol on its own?

I elaborate on this a bit more below.

## Environment

I'm using Docker Compose to recreate the environment. Here's my
docker-compose.yml:

	version: '2'
	
	services:
	  crossbar:
	    image: crossbario/crossbar
	  caddy:
	    image: abiosoft/caddy
	    ports:
	     - 2015:2015
	    volumes:
	     - $PWD/Caddyfile:/etc/Caddyfile
	    entrypoint:
	     - /usr/bin/caddy
	     - -conf=/etc/Caddyfile
	     - -http2=false
	     - -log=stdout

Here is the Caddyfile:

	localhost {
	    proxy / crossbar:8080 {
	        transparent
	        websocket
	    }
	    tls self_signed
	    errors
	}

## Using Firefox Web Console

I used the Firefox Web Console to create a new WebSocket connection, but since the
default Crossbar configuration is not configured for TLS I had to change the following
in about:config:

	network.websocket.allowInsecureFromHTTPS = true

When I create a WebSocket object, Caddy forwards the GET request to Crossbar:

	var s = new WebSocket("wss://localhost:2015/ws");

	GET /ws HTTP/1.1
	Host: localhost:2015
	User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
	Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
	Accept-Encoding: gzip, deflate, br
	Accept-Language: en-US,en;q=0.5
	Cache-Control: no-cache
	Connection: keep-alive, Upgrade
	Dnt: 1
	Origin: https://localhost:2015
	Pragma: no-cache
	Sec-Websocket-Extensions: permessage-deflate
	Sec-Websocket-Key: oeEuPGRShinMIFmuQLbXGw==
	Sec-Websocket-Version: 13
	Upgrade: websocket
	X-Forwarded-For: 172.19.0.1
	X-Forwarded-Proto: https
	X-Real-Ip: 172.19.0.1

Crossbar responds with:

	HTTP/1.1 400 This server only speaks WebSocket subprotocols wamp.2.cbor.batched, wamp.2.cbor, wamp.2.msgpack.batched, wamp.2.msgpack, wamp.2.json.batched, wamp.2.json

When I create a WebSocket object and specify the subprotocol:

	var s = new WebSocket("wss://localhost:2015/ws", "wamp.2.json.batched");

The following GET and corresponding response occurs:

	GET /ws HTTP/1.1
	Host: localhost:2015
	User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
	Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
	Accept-Encoding: gzip, deflate, br
	Accept-Language: en-US,en;q=0.5
	Cache-Control: no-cache
	Connection: keep-alive, Upgrade
	Dnt: 1
	Origin: https://localhost:2015
	Pragma: no-cache
	Sec-Websocket-Extensions: permessage-deflate
	Sec-Websocket-Key: 3Jimzbb2Gb2ZdEvTkKZ24A==
	Sec-Websocket-Protocol: wamp.2.json.batched
	Sec-Websocket-Version: 13
	Upgrade: websocket
	X-Forwarded-For: 172.19.0.1
	X-Forwarded-Proto: https
	X-Real-Ip: 172.19.0.1

	HTTP/1.1 101 Switching Protocols
	Server: Crossbar/0.13.2
	X-Powered-By: AutobahnPython/0.13.1
	Upgrade: WebSocket
	Connection: Upgrade
	Sec-WebSocket-Protocol: wamp.2.json.batched
	Sec-WebSocket-Accept: 9Ys/jPnlrC6fYJ4kOskOMIoiuag=

**Comment by InAnimaTe** [comment]
In my eyes, it should only be passed upstream if it was provided with the incoming request. Not sure what @mholt thinks but I can't see any reason to pass an empty header.

**Comment by ericdreeves** [comment]
Thank you for the quick reply.

I've been unable to create a request such that Caddy does not pass the Sec-Websocket-Protocol header upstream when it comprises the incoming request.

Perhaps you could share more about your environment? Or, if you have the GET request that generated the HTTP 502 from Caddy, I can recreate it on my own and observe.

**Comment by InAnimaTe** [comment]
Hmm not sure if you're using some newer version or something then. The whole point of the issue is that Caddy doesn't pass that header on incoming websocket connections. Utilizing the crossbar client for connecting should plainly show you (this is pretty much how I did it) that the incoming request does contain the Sec-WebSocket-Protocol header but the backend upstream connection Caddy makes to the wamp router does not contain that header, hence the manual header_upstream addition is needed.

Unless I'm very wrong...

**Comment by ericdreeves** [comment]
I've tried very hard to reproduce this to no avail. @mholt has already labeled it so there's no need for me to hold it back. I'll submit a pull request very soon and the maintainers can accept or reject as they see fit.

An additional thought: the specifications of the two WebSocker versions supported by crossbar ([Hybi10](https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-10#section-5.1), [RFC6455](https://tools.ietf.org/html/rfc6455#section-4.1)) seem to have similar requirements with respect to this header:

	The request MAY include a header with the name "Sec-WebSocket-
	Protocol".  If present, this value indicates one or more comma
	separated subprotocol the client wishes to speak, ordered by
	preference.

There are MUST requirements for certain headers, e.g. Sec-WebSocket-Version, but this is only based on a cursory reading of certain sections of both specs.

Anyway, here's what I tried. I'm documenting this in case someone notices an error in the configuration or some oversight. Just as in my previous update, I set up various scenarios using docker compose, exposing caddy's port to the client. Here's where I ended up:

```yaml
	version: '2'
	
	networks:
	  client_to_proxy:
	  proxy_to_crossbar:
	
	services:
	  crossbar:
	    image: crossbario/crossbar
	    networks:
	     - proxy_to_crossbar
	  caddy:
	    image: abiosoft/caddy
	    networks:
	     - client_to_proxy
	     - proxy_to_crossbar
	    volumes:
	     - $PWD/Caddyfile:/etc/Caddyfile
	    entrypoint: /usr/bin/caddy -conf=/etc/Caddyfile -http2=false -log=stdout
```

And, the Caddyfile:

	caddy {
	    proxy / crossbar:8080 {
	        transparent
	        websocket
	    }
	    tls self_signed
	    errors
	}

When I exposed port 2015 and created the WebSocket connection from Firefox Web Console to caddy, all the necessary headers were in the upstream request. It didn't matter if I used the generic WebSocket object or the AutobahnJS object-each time the Sec-Websocket-Protocol header was present and the connection successful.

2. Using the above setup, I even ran the crossbario client container on the same network as caddy, e.g.

```bash
	$ docker run -it --network=wss_client_to_proxy --rm crossbario/autobahn-js sh
	/app# export NODE_TLS_REJECT_UNAUTHORIZED="0" # Needed for self-signed TLS
	/app# export CBURL=wss://caddy:2015/ws
	/app# node client.js 
	session open! { authrole: 'public',
	  authprovider: 'static',
	  authid: 'GGTQ-VR9J-YF37-JEMV-CMQU-GKQA',
	  roles: 
	   { broker: { features: [Object] },
	     dealer: { features: [Object] } },
	  authmethod: 'anonymous',
	  realm: 'realm1',
	  x_cb_node_id: 'e1f597ed8a8a' }
	session closed: closed { reason: 'wamp.close.normal',
	  message: '',
	  retry_delay: null,
	  retry_count: null,
	  will_retry: false }
```

**Comment by InAnimaTe** [comment]
So you're effectively disproving my findings (not being harsh, just surprised). Hmm, this is interesting. I'll try to cut out some time and reproduce what I was seeing with header outputs from wireshark etc.. (the whole 9yrds as they say). 

BTW, I appreciate your effort in trying to work on this and your thorough report. This is why the Open-Source community thrives (and also, we can have nice things ;)

**Comment by ericdreeves** [comment]
Agreed! Thanks for continuing to work through it with me.

**Comment by InAnimaTe** [comment]
> Unless I'm very wrong...

YUP! 

Did a simple test of this with wscat: `wscat -c ws://localhost/ -s caddy.is.awesome`

![screenshot from 2016-10-28 22-23-24](https://cloud.githubusercontent.com/assets/1192726/19826626/6d6213d0-9d5d-11e6-9418-626b2a9ee663.png)

Going to try to emulate the environment I had before *exactly* and figure out what was actually going on. Probably no need for #1224 anymore. Really sorry I didn't double check here. @ericdreeves thx for shooting in the dark with me ;) I owe you a beer sir!
