### ISSUE TITLE
HTTP/2 with backend

### ISSUE THREAD

**Issue by git001** [mholt/caddy#1171]
Hi.

I have asked me why this lines have hard coded the HTTP/1.1 Proto

https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/reverseproxy.go#L175-L177

Isn't it possible to run a HTTP/2 request from client to backend also in HTTP/2?

**Comment by mholt** [comment]
It's a carry-over from the Go standard lib (`net/http/httputil`) which sets it to HTTP/1.1.

I'm out of the country for a week -- can you confirm that it's using HTTP/1.1 when it should be using HTTP/2? (You'll need to make the connection to the backend using HTTPS first.) And then is there any real benefit to using HTTP/2 upstream? I assume your network to your backend is local, if not loopback, and thus is pretty fast/reliable.
