### ISSUE TITLE
Ability to specify 308 instead of 301 for automatic HTTP -> HTTPS redirect

### ISSUE THREAD

**Issue by aneeshusa** [mholt/caddy#1176]
I just started using Caddy and it's working very smoothly - sub 5 minutes to get it working!
One feature I especially like is the automatic HTTPS, with the HTTP -> HTTPS redirect. However, it looks like that redirect is [currently hardcoded to use a `301` code](https://github.com/mholt/caddy/blob/9ced4b17e56e7ea260dcdd11657a09c09e6f2406/caddyhttp/httpserver/https.go#L152). Would it be possible to add a feature to specify a different code, e.g. `308`? I tried using `redir` in my Caddyfile but couldn't get it working.

**Comment by krishamoud** [comment]
Could you paste the Caddyfile you tried?

**Comment by krishamoud** [comment]
I have had success in the past using two separate blocks.

```
sub.domain.com:80 {
  redir 308 {
    / https://sub.domain.com:443
  }
}
sub.domain.com:443 {
  ...
}
```

**Comment by aneeshusa** [comment]
@krishamoud thanks, that Caddyfile works perfectly! I was getting tripped up by `The Caddyfile always starts with the address of the site to serve` [in the docs](https://caddyserver.com/docs/caddyfile) and my Caddyfile started like so:
```
sub.example.com

sub.example.com:80 {
...
```
