### ISSUE TITLE
run as QUIC server

### ISSUE THREAD

**Issue by p2227** [mholt/caddy#1179]
Chrome 56.0.2887.0 canary / win7 x86

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.3

### 2. What are you trying to do?
RUN caddy as QUIC server

### 3. What is your entire Caddyfile?
```text
https://10.x.x.x(my ip) {
	tls path/to/server.crt path/to/server.key2
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -quic

### 5. What did you expect to see?
with wireshark I can found the QUIC packet, or open chrome://net-internals/#quic I can find QUIC sessions

### 6. What did you see instead (give full error messages and/or log)?
the website use h2,with http headers:
```
alt-svc:quic=":443"; ma=2592000; v="36,35,34"
alternate-protocol:443:quic
```
in wireshark I found the TLS package,but can't found QUIC package

and , if i don't use tls, it will be come http1.1

**Comment by elcore** [comment]
Sometimes you need to enable QUIC in Chrome

**Comment by elcore** [comment]
Hello,

you need to enable QUIC : chrome://flags/#enable−quic

**Comment by p2227** [comment]
> Hello,
> 
> you need to enable QUIC : chrome://flags/#enable-quic

I did.
I also add `--quic-host-whitelist="https://10.x.x.x(my ip)"`

**Comment by elcore** [comment]
Hello,

it is working with a FQDN. You should ask here visit the unofficial support channel at irc.freenode.net/ #chromium-support

**Comment by p2227** [comment]
> Hello,
> 
> it is working with a FQDN. You should visit the unofficial support channel at irc.freenode.net/ #chromium-support

how can i use this for playing with QUIC ? I want to run a QUIC server locally.

**Comment by elcore** [comment]
I am not sure -- I guess it is not possible (without a FQDN)

ping @lucas-clemente

**Comment by lucas-clemente** [comment]
Right now we only support QUIC with a certificate, and that means with a FQDN. If you really just want to try it locally, you can probably self-sign a cert for your hostname. Another option is to take an existing (valid) cert for a domain you own, give that to Caddy, and run Chrome with `--host-resolver-rules='MAP your.domain.com:443 127.0.0.1:6121'`, where 127.0.0.1:6121 are your ip and port.

**Comment by elcore** [comment]
Thank you very much @lucas-clemente :smile:
