### ISSUE TITLE
Caddyfile syntax error => Serving over HTTPS

### ISSUE THREAD

**Issue by probandula** [mholt/caddy#1182]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?
I was experimenting with Caddy (first day) and trying to take my startup scripts not into a virtual host, but after the block on the end of the file.

### 3. What is your entire Caddyfile?
```text
localhost:2015 {
	# logging paths
	log log/localhost:2015/access.log
	errors log/localhost:2015/error.log
	# document root
	root www/localhost:2015

	fastcgi / /run/php/php7.0-fpm.sock php
}

# These lines I was experimenting with. When I remove them everything works.
startup sudo /etc/init.d/php7.0-fpm start
shutdown sudo /etc/init.d/php7.0-fpm stop
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy` in the directory of my Caddyfile

### 5. What did you expect to see?
An error, if my Caddyfile isn't valid.

### 6. What did you see instead (give full error messages and/or log)?
```text
vagrant@vagrant:/vagrant$ caddy 
Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address:
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Take my Caddyfile and changes the document root, log paths and maybe remove the fastcgi stuff.

**Comment by probandula** [comment]
Same message is shown if my Caddyfile looks like this (without host)
```text
log log/localhost:2015/access.log
errors log/localhost:2015/error.log

root www/localhost:2015

fastcgi / /run/php/php7.0-fpm.sock php
```

**Comment by tobya** [comment]
Do you have the startup and shutdown scripts with your updated comment

**Comment by mholt** [comment]
Hi @probandula ,

> and trying to take my startup scripts not into a virtual host, but after the block on the end of the file.

This is one problem -- directives have to go within a site description (a site block), there is no such thing as "global" scope for directives. So when it sees words outside of site blocks, it parses them as site addresses. In your case, it's trying to start sites at addresses of `startup`, `sudo`, etc. It's not a syntax error, just a semantic one (on your part).
