### ISSUE TITLE
Support for .NET Core?

### ISSUE THREAD

**Issue by donnyv** [mholt/caddy#1187]
Have you guys thought about supporting .NET Core? I think this would bring you a ton of new developers.

**Comment by mholt** [comment]
What do you mean by supporting .NET Core, exactly?

**Comment by elcore** [comment]
I am not sure if that's possible! -- .NET Core wants to be a Node and Go competitor! 

It's a framework for C# and F#, while Go is a whole language.

So, what do you mean exactly? How do you (exactly) want to achieve it?

**Comment by rbtbar** [comment]
I'm not sure what kind of special support you need for .NET Core.
Have you tried to setup Caddy as a reverse proxy for some Kestrel servers?
If I was interested in pairing .NET Core with Caddy (or ngnix) then setting it up as the reverse proxy would be the very first step for me.

**Comment by stanislavromanov** [comment]
You don't need to "support" it. Just use it as reverse-proxy and you're set.

**Comment by donnyv** [comment]
Gotcha, I didn't notice the reverse proxy support. Thanks!

**Comment by lucaslorentz** [comment]
Although caddy supports reverse proxy, it doesn't support managing and starting the the .NET Core application. That's something .NET developers expect because IIS does that.

FYI. I'm creating a plugin enables caddy to run the target .Net Core applications: https://github.com/mholt/caddy/pull/2061

**Comment by ScottRFrost** [comment]
For anyone who found this via web search, @lucaslorentz 's plugin doesn't appear to exist.

To get reverse proxy working, just add this to your Caddyfile:

```
whatever.yoursite.com
{
     reverse_proxy http://127.0.0.1:5005
}
```

Add or edit the appsettings.json in the directory of your app (/opt/web/whatever in my example) to force the localhost URL and port

```
{
  "Urls": "http://localhost:5005",
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
 ... the rest of your appsettings.json file here ...
```

then add a file like this (whateverapp.service) to /etc/systemd/system:

```
[Unit]
Description=WhateverApp
After=syslog.target network.target

[Service]
User=someuser
Group=www-data
Type=simple
WorkingDirectory=/opt/web/whateverapp/
ExecStart=/usr/bin/dotnet /opt/web/whateverapp/whateverapp.dll
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

and finally an execute the following:

```
sudo systemctl daemon-reload
sudo systemctl enable whateverapp
sudo service whateverapp start
```

**Comment by lucaslorentz** [comment]
@ScottRFrost sorry for the broken link.

I implemented the plugin for caddy V1: https://github.com/lucaslorentz/caddy-supervisor

It allows caddy itself to start and monitor dotnet execution. So you can add only caddy to systemd and configure dotnet execution in your caddyfile.

All the other concepts you mentioned like reverse_proxy should be as you described.

Your solution looks pretty solid with systemd.

But just in case you want to try the plugin, baldinof recently ported the plugin to caddy V2: https://github.com/Baldinof/caddy-supervisor/
https://caddyserver.com/docs/modules/supervisor
