### ISSUE TITLE
Getting config file from environmental variables

### ISSUE THREAD

**Issue by zignig** [mholt/caddy#1195]
Cross post,

https://github.com/miekg/coredns/issues/350

Talking to Miek Gieben about having the entire config file as an environment variable for caddy/coredns

My use case is with rkt containers , so I can pass a complete config into caddy/coredns without having to bake the config into the container. 

Is this possible to do, would you want to ?

**Comment by mholt** [comment]
How would that even look? I have no idea. For these kinds of things I typically recommend piping in the config, but if that's not possible with rkt, then I recommend filing an issue with them. ;)

Anyway, feel free to discuss, but not something likely to be implemented (especially soon).

**Comment by tobya** [comment]
How about the import directive accepting a URL or is that an awful idea?

That would allow you to bake in a basic caddyfile that would call a URL to get full config.
