### ISSUE TITLE
Integrate HHVM support

### ISSUE THREAD

**Issue by zorrobyte** [mholt/caddy#12]
HTTP/2 is fast, HHVM instead of FastCGI is even faster. It would be nice to have a config/template to use HHVM.

Here are example configs for Apache/Nginx: https://github.com/facebook/hhvm/wiki/FastCGI

**Comment by r3wt** [comment]
:+1:

**Comment by mholt** [comment]
So if I understand the docs you linked to, it's essentially the same as proxying to php-fpm? What would need to be done for then Caddy to work with HHVM if it does not already?

```
fastcgi / 127.0.0.1:9000 php
```

**Comment by r3wt** [comment]
@mholt i think he is requesting a manner to embed hhvm directly in the caddy process, like `mod_php`. else i have no idea what he meant

**Comment by Immortalin** [comment]
Maybe hhvm can be embedded into caddy via gobindata to make deployment easier and expose it via a cgo binding?

**Comment by zorrobyte** [comment]
As I am restricted on time, I have yet to dig through caddy's source code for a proper integration suggestions.

As of now, there are parameters such as gzip that can be placed in the caddyfile to enable support: https://caddyserver.com/docs/caddyfile

It would be interesting if HHVM could be activated on a site with param hhvm, much like param gzip in the caddy file. FastCGI is recommended for compatibility and would be default. hhvm param would invoke HHVM instead of FastCGI for PHP handling (and HHVM works with Hack language, which brings more devs to the project).

As for the link I posted (https://github.com/facebook/hhvm/wiki/FastCGI), as you are using FastCGI now, it should be simple to setup HHVM in proxy mode (localhost:9000).

An auto config script is located here for HHVM (https://github.com/hhvm/packaging/blob/master/hhvm/deb/skeleton/usr/share/hhvm/install_fastcgi.sh) which can give you further idea as to integration.

I wish I could be more help as to the specifics of the caddy project.

**Comment by mholt** [comment]
I find HHVM's speed compelling. Thanks for the resources @zorrobyte - they'll surely be helpful!

As for me personally, I do not have time to devote to this right now either, but HHVM seems like a technology that Caddy would do well to support in the long run, assuming PHP keeps being popular. Anyone is welcome to tackle this - just comment here.

**Comment by el3ctro-** [comment]
Hi,

I have some questions regarding adding HHVM.  It looks like it is largely written in C++, so how would we include it with Caddy and still have Caddy be cross platform for all the currently supported operating systems?  Are you suggesting to to gather binaries of HHVM and include it with each version of Caddy?  The other option is to have the user compile it them self.  How were you imagining shipping it with Caddy?

Not saying this is a bad idea just trying to figure out how it would allow Caddy to be cross platform.... Or do we end up leaving out support for any OS that can't compile HHVM?

**Comment by mholt** [comment]
We would need to use a pure Go library to build HHVM into Caddy for exactly that reason; I was under the impression there was some other way to bind to an external HHVM process - but it does appear that FastCGI can do that already.

**Comment by zorrobyte** [comment]
My two cents,

HHVM is a “nice to have” as in it works very well for most things but fails at certain other things, see http://hhvm.com/frameworks/ <http://hhvm.com/frameworks/> . You are right, it isn’t cross platform and adds complexity however, I did mention it for Caddy as it can go far as to help popularize your platform as many others do not currently offer HHVM/Hack integration. I suppose it could come down to a caddy including HHVM as a module, as in a setup script that would be ran to compile and integrate HHVM into caddy. This way HHVM stays an optional, doesn’t clutter core code but is easily added to caddy with minimal setup, keeping it simple per the caddy philosophy.

Anywho, that’s just my high level suggestion. I’m an Advanced Beginner at best :)

**Comment by steelbrain** [comment]
I am a power user of HHVM and I think that fastcgi support should be enough. The protocol is well tested and works. HHVM wasn't built with embedding in mind. Furthermore HHVM also has a builtin web server called Proxygen.

and to @zorrobyte HHVM may fail for the frameworks but I have been using HHVM in production for more than a year and never had a problem with it. It may not be cross-platform at the moment but during the last few months, they have announced an official Homebrew tap and a heavily-under-development windows build. Here's a graph I saw today, I think you should have a look at it too :) https://www.facebook.com/groups/hhvm.general/permalink/539355092884555/

**Comment by mholt** [comment]
Closing this issue since it doesn't seem to be going anywhere, bug discussion is still welcome on it for any interested.

**Comment by abiosoft** [comment]
There is actually no discussion. HHVM is accessible via FastCGI.
