### ISSUE TITLE
Missing yaml sources?

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#120]
Not super sure what this means or why I am getting it.

Am I missing some sort of dependency?

```
pi@jmcnallypi ~/.go $ go get github.com/mholt/caddy
src/gopkg.in/yaml.v2/decode.go:4:2: no Go source files in /usr/lib/go/src/pkg/encoding
```

**Comment by Xe** [comment]
What version of go are you using?

**Comment by j-mcnally** [comment]
I'm going to check in the Am I put my raspberry away. It's the latest raspbian.

**Comment by mholt** [comment]
It might be that Go is outdated or somehow the .go files in pkg/encoding disappeared. Either way, I'm willing to bet that (re)installing the latest Go will fix the problem.
