### ISSUE TITLE
Caddy not proxying to default address/path

### ISSUE THREAD

**Issue by HazCod** [mholt/caddy#1201]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?
Redirect everything not in /js/, /css/, /img/, /fonts/ to my PHP-FPM backends index.php. This processes it out based on `$_SERVER['REQUEST_URI']` and `$_SERVER['SCRIPT_NAME']`.

### 3. What is your entire Caddyfile?
```text
http://hazcod.com/ {
    log stdout
    errors stderr

    header / {
        #"Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload"
        "X-Frame-Options" "DENY"
        "X-Content-Type-Options" "nosniff"
        "X-XSS-Protection" "1; mode=block"
        "Access-Control-Allow-Origin" "{host}"
        "Access-Control-Allow-Methods" "GET, POST, OPTIONS"
        -Server
    }

    gzip
    minify

    rewrite / /index.php{uri}

    fastcgi / php:8080 php {
        env HTTP_PROXY ""
        env SCRIPT_FILENAME /www/index.php
    }
}

http://hazcod.com/js/ {
    header / -Server

    gzip
    minify

    root /assets/js/
    expires {
        match .js$ 1d
    }
}

http://hazcod.com/css/ {
    header / -Server

    gzip
    minify

    root /assets/css/
    expires {
        match .css$ 1d
    }
}

http://hazcod.com/img/ {
    header / -Server

    gzip
    minify

    root /assets/img/
    expires {
        match .png$ 1d
    }
}

http://hazcod.com/fonts/ {
    header / -Server

    gzip
    minify

    root /assets/fonts/
    expires {
        match .tiff$ 1w
    }
}


```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
(Docker)

  HOME=/etc/caddy/ cap_net_bind_service=+ep \
      /etc/caddy/caddy \
      -conf /etc/caddy/caddyfile \
      -email "${EMAIL}" \
      -agree

### 5. What did you expect to see?
`curl http://hazcod.com/` proxied to PHP-FPM. 

`curl http://hazcod.com/home` proxied to PHP-FPM.

### 6. What did you see instead (give full error messages and/or log)?
`curl http://hazcod.com/` is proxied to PHP-FPM.

`curl http://hazcod.com/home` is NOT proxied to PHP-FPM. (I check php-fpm access logs)

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Everything proxied to the php-fpm backend will just return the URI. Else, 404.

**Comment by tpng** [comment]
```
rewrite / /index.php{uri}
```
only matches ```/```, to achieve what you want to do, you will need to use
```
rewrite / {
    regexp .*
    to /index.php{uri}
}
```
Other usage can be found in the documentation. https://caddyserver.com/docs/rewrite

**Comment by HazCod** [comment]
Ahh, I thought it also included everything beneath it. Thansk @tpng !
