### ISSUE TITLE
TestWebSocketReverseProxyFromWSClient failed on go tip

### ISSUE THREAD

**Issue by tw4452852** [mholt/caddy#1206]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

0.9.3

### 2. What are you trying to do?

go test -run=TestWebSocketReverseProxyFromWSClient github.com/mholt/caddy/caddyhttp/proxy

### 3. What is your entire Caddyfile?

N/A

### 4. How did you run Caddy (give the full command and describe the execution environment)?

N/A

### 5. What did you expect to see?

Test pass.

### 6. What did you see instead (give full error messages and/or log)?

```
--- FAIL: TestWebSocketReverseProxyFromWSClient (0.00s)
        proxy_test.go:205: EOF
FAIL
FAIL    github.com/mholt/caddy/caddyhttp/proxy  0.004s
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Make sure go stdlib contains [this commit](https://github.com/golang/go/commit/4859f6a416b053d57fcc9d8f43e81e9d218280e9)

**Comment by mholt** [comment]
This must have something to do with https://github.com/golang/go/issues/17525. Thanks for the PR!
