### ISSUE TITLE
Websockets get 200 status code after upgrading when using header middleware

### ISSUE THREAD

**Issue by tehscorpion** [mholt/caddy#1208]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.3
### 2. What are you trying to do?

Proxy websocket connections while setting/removing headers.
### 3. What is your entire Caddyfile?

``` text
host {
    header / {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Frame-Options SAMEORIGIN
        X-XSS-Protection "1; mode=block"
        X-Content-Type-Options nosniff
        -Server
    }
    proxy /api api:8080 {
        transparent
        websocket
        header_upstream Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}
        header_upstream Sec-WebSocket-Extensions {>Sec-WebSocket-Extensions}
    }
}

```
### 6. What did you see instead (give full error messages and/or log)?

Caddy answers with `200 OK` and with Server header

Maybe related to #1183 and #1206

**Comment by mholt** [comment]
Thanks for the report -- most likely _not_ related to #1183.

**Comment by shantanuthatte** [comment]
I can confirm. Removing the `header` from the config file fixed the websocket issue.

```
myapp.mydomain.com {
  tls mymail@mydomain.com
  proxy / 127.0.0.1:8065 {
    transparent
    websocket
  }
#  header / {
#    Strict-Transport-Security "max-age=31536000"
#  }
  log / /var/log/caddy/myapp.log {
    rotate {
        size 50
    }
  }
}
```

**Comment by tw4452852** [comment]
I think this issue should be fixed by e5d33e7. @shantanuthatte could you please try to confirm? Thanks!

**Comment by shantanuthatte** [comment]
Building at e5d33e7 resulted in
```
# github.com/mholt/caddy/caddytls
../caddytls/client.go:200: not enough arguments in call to c.acmeClient.ObtainCertificate
../caddytls/client.go:288: not enough arguments in call to c.acmeClient.RenewCertificate
```
Had to go up to 53e1178

I can confirm that @53e1178 it works!

**Comment by tw4452852** [comment]
Ok, so we can close this issue now. Thanks @shantanuthatte !

**Comment by tehscorpion** [comment]
Thanks!
