### ISSUE TITLE
JSONP middleware

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#122]
Could be used to wrap JSON api's in a callback function to allow them to be used via script tag proxies.

Upstream returns

```json
{"hello": "world"}
```

we could wrap that in

```js
callback({hello: "world"})
```

We would also likely accept a get param for the callback method name.

**Comment by mholt** [comment]
Is it not possible to get the backend to support JSONP? Or CORS? Is JSONP still prevalent in the modern web, in your experience? (I haven't used it lately so I thought I'd ask.)

**Comment by j-mcnally** [comment]
just an idea, i figure we'll throw it all against the wall and see what sticks.

**Comment by j-mcnally** [comment]
this is more if you are using something like twitter as an upstream.... or a service you dont control that you want to create a read-only api for, you could of course expose cors headers.

**Comment by mholt** [comment]
Makes sense. I do like the idea, if JSONP isn't on its way out. If we were to do this, it seems fitting as a directive for the proxy middleware. Something like this:

```
proxy / backend:9000 {
    jsonp  # wraps JSON responses in a function specified by ?callback= from the original request
}
```

Even if it was its own middleware, the functionality could be the same.

I wouldn't mind going forward with this as long as there are long-lasting use cases for JSONP, where CORS won't suffice.

**Comment by mholt** [comment]
@j-mcnally I forgot to mention, work on this is almost finished thanks to @pschlump. See https://github.com/pschlump/caddy-jsonp.

**Comment by mholt** [comment]
This is now available on the download page. /cc @j-mcnally
