### ISSUE TITLE
Master is broken, because of acmeClient signature changes.

### ISSUE THREAD

**Issue by smancke** [mholt/caddy#1222]
The master is broken againt the acmeClient library, because 
ObtainCertificate and RenewCertificate got an additional parameter: mustStaple bool

github.com/mholt/caddy/caddytls
caddytls/client.go:200: not enough arguments in call to c.acmeClient.ObtainCertificate
caddytls/client.go:288: not enough arguments in call to c.acmeClient.RenewCertificate

**Comment by elcore** [comment]
Fixed and merged 😄

**Comment by smancke** [comment]
thx
