### ISSUE TITLE
Caddy passing empty headers

### ISSUE THREAD

**Issue by InAnimaTe** [mholt/caddy#1225]
During some testing on #1170 it was found that when a `header_upstream` is defined, even if the incoming request didn't contain one, an empty one is provided to the upstream server. @ericdreeves confirmed this in his testing [here](https://github.com/mholt/caddy/issues/1170#issuecomment-255552317):

```
Adding an upstream header via:

header_upstream Sec-WebSocket-Protocol {>Sec-WebSocket-Protocol}

does indeed add the header to the upstream request, however it will be empty
if the header did not exist in the original request.
```

Effectively, this means Caddy is sending malformed HTTP to the upstream ;( More on that [here](http://stackoverflow.com/a/12131993). Ideally, we should be intelligently checking for this first ;)

**Comment by mholt** [comment]
This should be pretty easy to fix. :) Thanks for the report. 

FWIW, empty header fields are valid (they may contain 0 values), but it does seem a bit tacky, and I guess would bloat the request (though negligible perhaps).

**Comment by gyulavoros** [comment]
I have a similar issue. I use [Upsource](https://www.jetbrains.com/upsource/) which is using Jetty to serve requests. It recently got updated to use Jetty 9.3, and it seems the latest version is more strict about HTTP headers: http://stackoverflow.com/a/32302263

Upsource uses websockets, so I have to use the following proxy settings:
```
header_upstream Connection {>Connection}
header_upstream Upgrade {>Upgrade}
```

I've captured request from Caddy to Upsource and it looks like to following (`Upgrade` header is empty):
```
GET / HTTP/1.1
Host: <host>
User-Agent: <agent>
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8,hu;q=0.6
Cache-Control: no-cache
Connection: keep-alive
Cookie: <cookie>
Pragma: no-cache
Upgrade:
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 10.2.90.1
```

These requests get rejected by Jetty with the following error:
```
eclipse.jetty.http.HttpParser - bad HTTP parsed: 400 for HttpChannelOverHttp@2f683d43{r=0,c=false,a=IDLE,uri=null}
```

If I remove `header_upstream Upgrade {>Upgrade}` the page loads, but websocket doesn't work. Is it possible to tell Caddy to proxy only non-empty headers?

**Comment by mholt** [comment]
> Is it possible to tell Caddy to proxy only non-empty headers?

I blame Jetty for being too strict in its parsing (the spec allows empty fields) but as soon as someone fixes this, Caddy won't send empty fields upstream.
