### ISSUE TITLE
Not possible to register a custom http plugin

### ISSUE THREAD

**Issue by smancke** [mholt/caddy#1228]
I 'm on creating my own custom directive (likely to be open at a later time).

When I register it with

``` go
func init() {
    caddy.RegisterPlugin("uic", caddy.Plugin{
        ServerType: "http",
        Action:     setup,
    })
```

and than run caddy with `caddymain.Run()`, this results in `Parse error: Unknown directive 'uic'`.

The only way to fix this is by calling `httpserver.RegisterDevDirective("uic", "")`,
which seems not to be intended for production use.

I guess it would be good to also officially support custom directives.

**Comment by wendigo** [comment]
Hi, couple of questions:

1. Do you develop your plugin in external repository?
2. Have you added your plugin to https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L392
3. Have you added your plugin to buildsrv? 

Custom directives are supported. Take a look at https://github.com/mholt/caddy/pull/1215 when I've added new plugin with `push` directive.

**Comment by mholt** [comment]
^ Bingo. And step 3 is only necessary if you are going to publish the plugin (and it's temporary until the new build server is ready) or are using the build server locally...

But step 2 is definitely what @smancke is missing I think.

**Comment by smancke** [comment]
Hi, 

> 1. Do you develop your plugin in external repository?
no, I'm embedding caddy and for now my plugin is rather project specific and not published in the open.

I saw the directives slice, mentioned in 2., but this always needs a source change in the upstream project to write a plugin. This is ok, if a plugin is of general interest and public available.
But in my current usecase is would be cool to just import caddy as dependency (embedded) and hook a custom plugin into caddy before starting.
If not relevant for you, I can help me out with the `httpserver.RegisterDevDirective()`, but I thought, that others would hit this too.

**Comment by mholt** [comment]
If you're just using it for you, then `RegisterDevDirective()` should be fine, noting the caveats that go along with it.

Plugins have to be ordered correctly, or there will be bugs. Hence a single authoritative list.

Anyway, hope that helps. :)

**Comment by wendigo** [comment]
@mholt maybe instead of single authorative list we can model plugins order as a relation "must be loaded before/after" and build this list according to plugins spec?

**Comment by mholt** [comment]
I've thought about that, where the capabilities or functions of each plugin are enumerated and then the server can order them automatically. However, this turns out to be way more painstaking than just adding a string to a slice. (Have you ever dealt with Android permissions?)

**Comment by smancke** [comment]
ok, thanks for clarifying!
