### ISSUE TITLE
healthcheck status code and retry options

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#123]
Status Code

I have several APIs that I want to proxy, but none of them have a well-defined /status or /health yet.

The easiest way to see if the server is up is if it returns a 404 within a *very* short amount of time - say 300ms. It would be nice to have an option to say that a 404 is actually ok.

Retry

If the process goes down it will likely come back up within 3 seconds and then the first request may take slightly longer than usual to respond (maybe ~1s instead of the usual ~10ms).

Rather than a `fail_timeout 10s` which reinserts the dead process back into the pool after x seconds, I would want a `retry 1s` that puts the process back into the pool once the status check has succeeded, retrying the status check every x seconds. Maybe that's what fail_timeout actually does and I just misunderstood the docs.

**Comment by mholt** [comment]
Status code: Are there no paths that the backends could serve which would return a status code in the 200s or 300s?

Retry: I think you can do that by setting your fail_timeout to 1s. I might be wrong, but original PR is #40.

**Comment by mholt** [comment]
Closing for now; feel free to re-open if this still needs to be addressed!
