### ISSUE TITLE
Caddy 0.9.3: proxy transparent does not pass header_upstream Host {host}

### ISSUE THREAD

**Issue by treviser** [mholt/caddy#1230]
### 1. What version of Caddy are you running (`caddy -version`)?

0.9.3

### 2. What are you trying to do?

Trying to proxy to a remote backend server

### 3. What is your entire Caddyfile?
```text
proxy / http://xxx.xxx.xxx.xxx:xxxx transparent
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

As a systemd service on Ubuntu 16.04.1 LTS

### 5. What did you expect to see?

The backend server receives "request.host.tld" as hostname because header_upstream Host {host} should be included in the placeholder "transparent" according to the documentation: https://caddyserver.com/docs/proxy

### 6. What did you see instead (give full error messages and/or log)?

The backend server receives xxx.xxx.xxx.xxx:xxxx instead of request.host.tld and is not able to fulfill the request

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Solution:
I have changed the Caddyfile as following:
```
proxy / http://xxx.xxx.xxx.xxx:xxxx {
      header_upstream Host {host}
      transparent
      }
```

**Comment by tw4452852** [comment]
Hi @treviser where is `request.host.tld` from?

**Comment by treviser** [comment]
This is just a sample host definition coming from the client's browser request, you could also say "my.domain.tld" or "www.example.com" etc. Sorry for misleading you.

**Comment by mholt** [comment]
Your Caddyfile syntax is invalid, unless `transparent` is a backend.

```
proxy / http://xxx.xxx.xxx.xxx:xxxx {
    transparent
}
```

**Comment by treviser** [comment]
The backend is a tomcat server. And with the addition of the header upstream to the transparent placeholder it works flawlessly.

This is my complete Caddyfile:

*.twanda.ch:80 { # Your url should go here..

  proxy / http://192.168.110.189:8080 {
      header_upstream Host {host}
      transparent
      }
}

**Comment by mholt** [comment]
Yep!
