### ISSUE TITLE
systemd Service won't start

### ISSUE THREAD

**Issue by dpsi** [mholt/caddy#1231]
@bdaehlie re systemd:

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.3

### 2. What are you trying to do?
systemd

### 3. What is your entire Caddyfile?
```text
confluence.dpsi.jp {
	proxy / confluence.dpsi.jp:8090 {
		transparent
	}
	tls admin@dpsi.jp
	gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Followed this: https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd

### 5. What did you expect to see?
Caddy starting correctly

### 6. What did you see instead (give full error messages and/or log)?
```text
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2016-10-31 13:13:03 PDT; 13ms ago
     Docs: https://caddyserver.com/docs
  Process: 10935 ExecStart=/usr/local/bin/caddy -agree=true -conf=/etc/caddy/Caddyfile (code=exited, status=1/FAILURE)
 Main PID: 10935 (code=exited, status=1/FAILURE)

Oct 31 13:13:01 proxy systemd[1]: Started Caddy HTTP/2 web server .
Oct 31 13:13:03 proxy systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Oct 31 13:13:03 proxy systemd[1]: caddy.service: Unit entered failed state.
Oct 31 13:13:03 proxy systemd[1]: caddy.service: Failed with result 'exit-code'.
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Fresh Ubuntu 16.04.01 LTS with the above instructions.

**Comment by dpsi** [comment]
Before this I had an issue where it was denied permission from the Caddyfile. Changing that to 544 instead of the 444 suggested in the guide fixed that issue.

Caddy runs fine when running the command caddy. Just systemd won't work. I have it working right now using init.d but that defeats the purpose of systemd.

**Comment by mholt** [comment]
Hey @dpsi, thanks for the report. However we don't support the init scripts in that folder, and since this isn't a Caddy bug (there was no log output provided to show otherwise), I'm going to close this. But you are welcome to ask the community about this on the [Caddy forum](https://forum.caddyserver.com)!

**Comment by coolaj86** [comment]
@mholt but the init scripts sometimes point to bugs in caddy. For example: it seems to `mkdir .`, which it should not do, which can cause `systemd` scripts to fail when they begin in, say `/`, which is owned by `root` and not `www-data`.
