### ISSUE TITLE
Specifying multiple addresses in multiple lines

### ISSUE THREAD

**Issue by mk-pmb** [mholt/caddy#1233]
From "[The Caddyfile](https://caddyserver.com/docs/caddyfile)":
> For sites which share the same configuration, specify multiple addresses:
> `localhost:2020, https://site.com, http://mysite.com {`

Do these addresses all have to be in the same line?
That could lead to quite long lines if I want to configure a lot of sites.
Also you need better sort and diff tools than the standard GNU ones.
How about merging address lines (and for now, only those) if they end with a comma? And to reduce diff flickering, it would be nice if the last address could have a trailing comma as well, which would merge the `{` from the next line. Example:

```text
blogs.local/arts/,
blogs.local/cats/,
blogs.local/foss/,
blogs.local/meme/,
blogs.local/nodejs/,
blogs.local/sec/,
{
  markdown {
    ext .txt
    css blog.css
    js  blog.js
  }
}
```

I consider clarification in the docs more urgent than a possible change of accepted syntax.

**Comment by mholt** [comment]
So actually you can do this (as long as you use the comma), but I didn't document it because I wasn't sure if it would stick (it's uncommon to define many sites for a single site block).

**Comment by mholt** [comment]
Oh, sorry -- the last address cannot have a comma, because that comma means "the next line is a site address". If that's specifically what you're referring to changing, we could look into this, although I find it a little confusing. I'm not sure your use case is very common...

**Comment by mk-pmb** [comment]
The trailing comma is one of the requirements for less diff flickering. Don't mind though, I found other reasons to generate my configs anyway.

**Comment by mholt** [comment]
Fair enough, but probably won't change it anytime soon. Thanks for at least raising the concern!
