### ISSUE TITLE
docs for vars

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#124]
I see a few vars referenced here and there like {query} {path} {host} throughout the doc page, but I don't see any list of them.

Also, I'm not sure what {host} represents (I may be about to find out), but the de facto standard is that it should be `{host} == {hostname}:{port}`.

**Comment by abiosoft** [comment]
Variables are not global. They are middleware dependent and the two middleware that supports it so far are [rewrite](https://caddyserver.com/docs/markdown) and [log](https://caddyserver.com/docs/log).

Are you suggesting we provide support for global variables ?

**Comment by mholt** [comment]
The {host} variable is just the hostname; use {host}:{port} if you want both. It is slightly different from nginx, but way more clear.

I agree that the variables should be documented more clearly. Middleware ought to be using the `middleware.Replacer` type, which replaces values in a standardized way, so maybe it'd be worth splicing them out of the log documentation and into their own page. I can look at this as I begin documentation for the API in the future.

**Comment by abiosoft** [comment]
Oops. I'm not aware of this. Obviously docs are lacking.

**Comment by mholt** [comment]
I forgot to label this as in progress, but the site was updated and will be deployed soon, so that the placeholder values (variables) are clearly documented. They have their very own page. Thanks for the feedback!

**Comment by hunter** [comment]
It seems that the functionality has changed since the earlier comment? {host} now appears to include the port. If I do something like `redir https://{host}:8443{uri}` then the browser ends up at https://locahost:8080:8443/uri. Is that now correct behaviour?

**Comment by mholt** [comment]
Hm, no, I'll look into it. I think Karthic is in the process of writing tests for that code right now, actually. Thanks for the heads up.

**Comment by mholt** [comment]
@hunter After a closer look, it seems that this is the expected behavior, since {host} just replaces whatever was in the Host header of the request, which may include the port if one was specified. This is counter-intuitive, given that {port} is the client port, which has nothing to do with the Host header. We're looking at changing a few of these around.
