### ISSUE TITLE
Self signed certificate does not work

### ISSUE THREAD

**Issue by raeesbhatti** [mholt/caddy#1240]
### 1. What version of Caddy are you running (`caddy -version`)?
`Caddy 0.9.3`

### 2. What are you trying to do?
Run caddy locally with TLS using its self signed certificate.

### 3. What is your entire Caddyfile?
```text
tls self_signed
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Run it without any additional parameters `caddy`. Nothing special.

### 5. What did you expect to see?
`caddy` to run a web service with TLS.

### 6. What did you see instead (give full error messages and/or log)?
It starts asking for Let's Encrypt email because I think, it's not trying to create a self-signed certificate.
```
Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address: 
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
```
echo "tls self_signed" > Caddyfile
caddy
```

**Comment by mholt** [comment]
Your Caddyfile must start with the address of the site to serve. ;)

**Comment by raeesbhatti** [comment]
Sorry my bad 🙈. Have another problem now.

Caddyfile:
```
localhost:2016
tls self_singed
```
Log output:
```
Activating privacy features... done.
https://localhost:2016
WARNING: File descriptor limit 256 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```

When I visit `https://localhost:2016` in Chrome, it says "This site can’t provide a secure connection". Error code is "ERR_SSL_PROTOCOL_ERROR"

**Comment by wendigo** [comment]
Self-signed certificates are not trusted by browsers.

**Comment by mholt** [comment]
There should be a prompt to bypass a security warning, you'll have to click advanced to do that.

**Comment by raeesbhatti** [comment]
But the browser tells us about invalid certificate when the certificate is not trusted. Instead, now it says `ERR_SSL_PROTOCOL_ERROR `

**Comment by raeesbhatti** [comment]
@mholt There is no advanced option like there is usually when using invalid certificate.

**Comment by mholt** [comment]
Hm, well, it works for me (just tried again) -- so without further details to replicate the behavior you're seeing or without further error details I'm not sure what more I can do to help here.
