### ISSUE TITLE
ERR_SPDY_COMPRESSION_ERROR Caddy 0.9.3

### ISSUE THREAD

**Issue by binarious** [mholt/caddy#1242]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.3

### 2. What are you trying to do?
Open a Symfony application served via caddy.

### 3. What is your entire Caddyfile?
```text
https://hum.localhost:8000
root /Users/MYUSER/projects/MYAPP/web
gzip

tls self_signed

rewrite {
  to {path} {path}/ /app_dev.php?{query}
}

fastcgi / 127.0.0.1:9000 php {
  index app_dev.php
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Just ran `caddy` in my app directory via fish shell 2.3.1 on macOS 10.12.1.

### 5. What did you expect to see?
The running web app.

### 6. What did you see instead (give full error messages and/or log)?
Chrome's (Version 54.0.2840.87 (64-bit)) error page `ERR_SPDY_COMPRESSION_ERROR`:
<img width="1348" alt="hum_localhost" src="https://cloud.githubusercontent.com/assets/200375/20053446/e331b520-a4d8-11e6-91ee-2b83be647ffb.png">

**Comment by mholt** [comment]
Does this error occur without the fastcgi directive?

**Comment by binarious** [comment]
No, without fastcgi the php source code is shown in the browser (as the application isn't interpreted anymore).

**Comment by mholt** [comment]
Okay, so the error seems to have something to do with the fastcgi middleware and/or your backend. Can you provide some details about your backend and even the source code of the page maybe so we can reproduce it?

**Comment by binarious** [comment]
We have this on every Symfony 2 project on macOS machines since Sierra (doesn't occur on linux, didn't happen on El Capitan). I can't provide source code for now since all are corporate projects.

**Comment by mholt** [comment]
That's fascinating, that it only happens on Sierra. Symfony bug (incompatibility with Sierra maybe)?

**Comment by binarious** [comment]
It works when running Apache via https. It just happens with the combination of Sierra and Caddy - very strange.

**Comment by mholt** [comment]
Are you running Apache with HTTP/2 enabled?

**Comment by mholt** [comment]
Closing pending answering of question ;)

**Comment by binarious** [comment]
Sorry, missed it. Yes, I was running it with mod_http2.

**Comment by mholt** [comment]
Okay. So I don't know what the problem would be. :-/
