### ISSUE TITLE
Activating privacy features for Private IP: Error 400 - urn:acme:error:unknownHost - No valid IP addresses found for xxx

### ISSUE THREAD

**Issue by kokizzu** [mholt/caddy#1243]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?
Activating HTTPS for Private IP Address.
pub.test.bill10ns.com and sub.test.bill10ns.com resolves to 10.100.10.228 (private ip)
pub.local.bill10ns.com and sub.local.bill10ns.com resolves to 127.0.0.1 (localhost)
it resolves normally on the computer:

```sh
$ dig pub.test.bill10ns.com

; <<>> DiG 9.11.0-P1 <<>> pub.test.bill10ns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32014
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pub.test.bill10ns.com.         IN      A

;; ANSWER SECTION:
pub.test.bill10ns.com.  3600    IN      CNAME   test.bill10ns.com.
test.bill10ns.com.      3600    IN      A       10.100.10.228

;; AUTHORITY SECTION:
bill10ns.com.           56214   IN      NS      ns102.cloudns.net.
bill10ns.com.           56214   IN      NS      ns101.cloudns.net.

;; Query time: 3186 msec
;; SERVER: 10.100.10.220#53(10.100.10.220)
;; WHEN: Tue Nov 08 16:39:05 WIB 2016
;; MSG SIZE  rcvd: 131

$ dig pub.local.bill10ns.com

; <<>> DiG 9.11.0 <<>> pub.local.bill10ns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41202
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pub.local.bill10ns.com.                IN      A

;; ANSWER SECTION:
pub.local.bill10ns.com. 3600    IN      CNAME   local.bill10ns.com.
local.bill10ns.com.     3424    IN      A       127.0.0.1

;; AUTHORITY SECTION:
bill10ns.com.           49023   IN      NS      ns101.cloudns.net.
bill10ns.com.           49023   IN      NS      ns102.cloudns.net.

;; Query time: 799 msec
;; SERVER: 10.100.10.220#53(10.100.10.220)
;; WHEN: Tue Nov 08 18:42:17 WIB 2016
;; MSG SIZE  rcvd: 132
```

### 3. What is your entire Caddyfile?
```text
pub.bill10ns.com, pub.test.bill10ns.com, pub.local.bill10ns.com {
        root /home/web/public
        proxy / 127.0.0.1:8083 {
                proxy_header Host {host}
                proxy_header X-Forwarded {remote}
                proxy_header X-Real-IP {remote}
                proxy_header X-Forwarded-Proto {scheme}
        }
}

sub.bill10ns.com, sub.test.bill10ns.com, sub.local.bill10ns.com {
        root /home/web/public
        proxy / 127.0.0.1:8088 {
                proxy_header Host {host}
                proxy_header X-Forwarded {remote}
                proxy_header X-Real-IP {remote}
                proxy_header X-Forwarded-Proto {scheme}
        }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
caddy
# caddy is on /usr/bin 
```

### 5. What did you expect to see?
started normally.

### 6. What did you see instead (give full error messages and/or log)?
```
Activating privacy features...2016/11/08 16:39:16 [pub.test.bill10ns.com] failed to get certificate: acme: Error 400 - urn:acme:error:unknownHost - No valid IP addresses found for pub.test.bill10ns.com
Error Detail:
        Validation for pub.test.bill10ns.com:80
        Resolved to:

        Used:


```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
create a server that listen on 8083 and 8088 localhost, change your ip to 10.100.10.228 or remove the *test.bill10ns.com from the Caddyfile above, then start the caddy using the Caddyfile above

**Comment by mholt** [comment]
Hi @kokizzu, I like your profile pic. :)

> Activating HTTPS for Private IP Address.

Caddy gets certificates from Let's Encrypt, which only verifies domains on public networks. Unless you set up your own CA on your private network (and its certificates of course won't be trusted), you can't do this. ;) See letsencrypt.org for more information.
