### ISSUE TITLE
Basicauth not working when the url is rewritten

### ISSUE THREAD

**Issue by fab120** [mholt/caddy#1244]
Don't know if it's the indented behavior or not.

### 1. What version of Caddy are you running (`caddy -version`)?
```text
root@server1:~/test# ./caddy --version
Caddy 0.9.3
```

### 2. What are you trying to do?
Using basicauth to protect an url that is in a rewrite statement.

### 3. What is your entire Caddyfile?
```text
[website]:8000

tls off

root /root/test/html

fastcgi / unix:/run/php5-fpm.sock php

rewrite {
        to {path} {path}/ /index.php?{query}
}

basicauth /test user pass
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`./caddy`

### 5. What did you expect to see?
I expect the browser ask for credentials when i visit the url
`http://[website]:8000/test`

### 6. What did you see instead (give full error messages and/or log)?
The browser didn't ask for credentials and showed directly the requested page.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
This behavior can be reproduced using the Caddyfile that i provided at point 2.
If you comment the rewrite block, the basicauth works fine.

**Comment by tobya** [comment]
Does /test/index.php exist?

What is your requested url being rewritten to?

**Comment by fab120** [comment]
No it doesn't exist.
Every url is rewritten to /index.php: the entry point of the application that will manage the request.
This is the usual setup for php frameworks like laravel, symfony, ...

This is an equivalent nginx configuration:
```text
server {
    listen 8000;
    root /root/test/html;
    server_name [website];
    index index.php index.html;

    location / {
            try_files $uri $uri/ /index.php?$query_string;
    }

    location /test {
            auth_basic           "Password required";
            auth_basic_user_file /root/test/.htpasswd;

            try_files $uri $uri/ ../index.php?$query_string;
    }

    location ~ \.php$ {
        [..omitted..]
    }
}
```

When you make a request to
`http://[website]:8000/`
nginx pass the request to `/index.php`

With
`http://[website]:8000/test`
nginx first ask you for the authentication and then it will pass the request to `/test/../index.php` (so `/index.php`).

The directory `/root/test/html` contains just the `index.php` file. Nothing else.

Instead caddy completely ignores basicauth statement and it passes the request directly to `/index.php`

**Comment by elcore** [comment]
Hello @fab120 and @tobya,

I created a PR to fix this issue 😄

**Comment by mholt** [comment]
You're rewriting /test to a different URL; why don't you set basicauth to work for index.php instead?

**Comment by fab120** [comment]
`index.php` is the entry point for the application that i wanna serve through caddy.

Set basicauth on `index.php` means extending the setting to all the urls and not to a particular one.

BTW i agree that #1245 could not be the best solution.

I'm very interested to continue with discussion, but today i will be out for working all day long.

I will reply / write more as soon as i come back home.

**Comment by mholt** [comment]
> Set basicauth on index.php means extending the setting to all the urls and not to a particular one.

This sounds like a definite weakness in the design of the web app; if all the URLs converge to one, how is Caddy supposed to differentiate them? Maybe the web app should be doing authentication.

**Comment by tobya** [comment]
I think I would agree with @mholt that this behaviour seems to me by design rather than a bug.

**Comment by mholt** [comment]
Since basicauth, like most middlewares, operates on the request URI, and rewrite is designed to adjust the URI for internal use only, it seems that this is not a bug but is actually the intended behavior of the basicauth middleware.

Thanks for opening the issue, @fab120.

**Comment by fab120** [comment]
Hi everyone.
I was trying to keep the discussion 'application' agnostic and i just wanna know what is the intended behavior in this sistuation and if it is correct.

FYI: for doing my tests the 'weak designed' app that i used was just
```php
<?php print_r($_SERVER); ?>
```

Anyway @mholt you said:
> This sounds like a definite weakness in the design of the web app; if all the URLs converge to one, how is Caddy supposed to differentiate them?

All urls are converging to one but that doesn't mean the requested url is always the same:

`http://website/urlAaa` rewritten to `http://website/index.php` is different from
`http://website/urlBbb` rewritten to `http://website/index.php`

Different requests url, but same converging url.
From what you said it seem caddy ignores the original url after a rewrite.

> Since basicauth, like most middlewares, operates on the request URI, and rewrite is designed to adjust the URI for internal use only, it seems that this is not a bug but is actually the intended behavior of the basicauth middleware.

If `rewrite` is designed to adjust the uri for **internal use only**, this adjustment should be transparent and let me operate with the original url while he internally does the stuff he needs to serve the request correctly.

> Maybe the web app should be doing authentication.

Are you telling me that caddy behavior can change based on the 'application' he serves?
I mean if i need this particular rewrite configuration, and for any reasons i need also a basic http auth, caddy can't help me in any way?

**Comment by mholt** [comment]
>  this adjustment should be transparent and let me operate with the original url while he internally does the stuff he needs to serve the request correctly.

This is contradictory, though: the URL is either one thing or another, it isn't both. By "internal" use I mean within the web server (plugins and middleware included), such that the browser doesn't know the URL was changed (i.e. not an HTTP redirect).

I admit the semantics of what a rewrite is are not well defined, hence the 'discussion' tag here. Other web servers do rewrites iteratively, but that's even more confusing IMO, so Caddy's rewrite is simpler: adjust the URL in the request without issuing an HTTP redirect.

One other (adversarial) way of approaching this edge case, is: For web apps that expect all the requests to be to index.php, why doesn't the browser just issue requests to index.php in the first place?

I only ever added the rewrite directive reluctantly anyway, because it is mainly used for:

- Making backend apps with poorly designed web semantics work (important for Caddy adoption)
- Hacking around certain path matching between middlewares for proxying, redirects, etc.

And both of these I feel kinda dirty about. Rewrite is useful as long as web applications served by Caddy don't know how to do their own routing...
