### ISSUE TITLE
syslog to external server

### ISSUE THREAD

**Issue by myReaper** [mholt/caddy#1246]
Hi,

This is basically a feature request :-)

Currently I'm missing an option to output error and access logs directly to our centralized syslog server, or at least I haven't found it :-)

Nginx for example has an option to directly log to a syslog server via ip and port:
https://nginx.org/en/docs/syslog.html

The main benefit of this is:
- Using a centralized syslog server (of course :-)) for multiple instances to easier monitor them
- Optimize I/O on the Caddy/Webserver as no local files need to get written anymore

Right now, we are running most sites in development or low usage systems but we'd like to move caddy to our production environment in about 2-3 weeks, would be great to have this implemented "soon" [can't really estimate the work amount for this as I'm no coder :( ]

btw. great job on caddy, I'm using it already on almost all of my private sites for a few months now and it works super smooth :-)

Best Regards
Michael

**Comment by wendigo** [comment]
Would you like to stream access/errors log to syslog or every log message?

**Comment by myReaper** [comment]
Sorry for my late reply :-)

Right now, streaming access and error log to an remote syslog server currently would be sufficient for us. Of course, receiving all messages would also not be wrong.

Our main goal is to have all caddy log messages available in our central Logstash installation. So the best option for us would be to directly output error/access logs as json to the logstash server.

However, the quicker integration option into caddy might be to "simply" stream current error and {combined] access log format to a remote syslog (which would also be ok for us as we could parse this in Logstash then).

**Comment by mholt** [comment]
You can specify `syslog` for error and access logs (using the `errors` and `log` directives) already. Does that meet your needs?

**Comment by myReaper** [comment]
@mholt no, just specifying syslog will log to the internal syslog, we require caddy to log to an external syslog server (using ip:port) like nginx offers for example.

The local log should not be written at all, also in terms of disk i/o performance.

**Comment by wendigo** [comment]
Can you use relay to bounce logs to an external syslog using local one?

**Comment by myReaper** [comment]
@wendigo for performance reasons it would be good to have caddy directly log to an external syslog server (or send json to logstash) instead of first writing to local syslog and then relaying using the local syslog server.

**Comment by wendigo** [comment]
@myReaper as Caddy is using https://github.com/hashicorp/go-syslog syslog wrapper I've submitted PR to allow dialling remote syslog server https://github.com/hashicorp/go-syslog/pull/5/files. When it will be merged I can add support for remote syslog in Caddy.

Or... @mholt: we could drop go-syslog in favour of using build tags and ```log/syslog``` WDYT?

**Comment by mholt** [comment]
I'm all for fewer dependencies, but go-syslog already does what essentially we would have to do ourselves, no? I'm fine with keeping it at this point -- assuming that PR, https://github.com/hashicorp/go-syslog/pull/5 can get merged.

**Comment by wendigo** [comment]
@mholt I give myself a 2 weeks deadline - if there is no response from hashicorp team I will move syslog wrapper to caddy

**Comment by wendigo** [comment]
Ok, so the PR is merged :) I will send PR in following days

**Comment by wendigo** [comment]
Here you go: https://github.com/mholt/caddy/pull/1301 ;) Took more time than I expected

**Comment by mholt** [comment]
@wendigo Thank you for implementing it! I've started reviewing it, as you can see. As soon as we finish up the changes after reviews, I'll be happy to merge it.

**Comment by wendigo** [comment]
Merged :)

**Comment by tobya** [comment]
There is an issue with building PR this on windows
