### ISSUE TITLE
Markdown serving issue

### ISSUE THREAD

**Issue by ptman** [mholt/caddy#1249]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.3

### 2. What are you trying to do?

Render README.md from https://github.com/mholt/caddy/blob/master/dist/init/README.md as http://localhost:8080/README.md

### 3. What is your entire Caddyfile?
```text
http://*:8080
root init/

markdown /
browse /

filemanager /_fileman {
    show init/
    allow_commands false
    allow_edit true
    allow_new true
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

    caddy -log stdout -port 8080

### 5. What did you expect to see?

markdown processed README.md

### 6. What did you see instead (give full error messages and/or log)?

plaintext README.md

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

caddy release + filemanager and the included init/README.md

If I make a copy of README.md to readme.md, that works correctly

**Comment by mholt** [comment]
I'm gonna go out on a limb and ask if you're sure you've cleared your browser cache? Try `curl`...

**Comment by ptman** [comment]
I would've thought that I checked it, but maybe that was it because I cannot reproduce. I was assuming that maybe markdown and browse aren't meant to work together, but apparently they are supported in combination?

**Comment by mholt** [comment]
Yep, totally should work. :) Glad it's fixed for ya now!
