### ISSUE TITLE
Caddy picks first IP in sorted, returned DNS record

### ISSUE THREAD

**Issue by ar0ch** [mholt/caddy#1251]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?

Use caddy to provide HTTPS for a domain that's servers by two servers/IPs. 

### 3. What is your entire Caddyfile?
```text
vibriocholera.com {
    root /home/blast/public/www/www/
    gzip
    errors ./errors_ani.log
    log ./log_ani.log
}

t6ss.vibriocholera.com {
    errors ./errors_ani.log
    log ./log_ani.log
    proxy /websocket/ http://127.0.0.1:4545 {
        websocket
    }
    proxy / http://127.0.0.1:4545 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Run via service on two different servers, which share the same caddyfile (above)

```text
[Unit]
Description=Caddy HTTP/2 web server %I
Documentation=https://caddyserver.com/docs

[Service]
User=blast
WorkingDirectory=/home/blast
LimitNOFILE=4096
Environment=STNORESTART=yes
ExecStart=/opt/caddy -log stdout -agree=true -email=le@atc.io -conf=/home/blast/public/www/Caddyfile
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

```text
$sudo service caddy status
caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2016-11-10 18:54:21 CST; 1s ago
     Docs: https://caddyserver.com/docs
 Main PID: 12867 (caddy)
   CGroup: /system.slice/caddy.service
           └─12867 /opt/caddy -log stdout -agree=true -email=le@atc.io -conf=/home/blast/public/www/Caddyfile
```
### 5. What did you expect to see?

Functional HTTPS on both servers

### 6. What did you see instead (give full error messages and/or log)?

DNS challenge consistently picks the wrong IP for one of the servers, `hostname -i` returns the correct/expected IP on each server. 

In the below logs, 69.195.153.6 should be used for the challenge. Setting it as the bind address does not change things

```
Nov 10 18:53:21 vibriocholera.com caddy[12765]: 2016/11/10 18:53:21 [INFO][vibriocholera.com] acme: Could not find solver for: dns-01
Nov 10 18:53:21 vibriocholera.com caddy[12765]: 2016/11/10 18:53:21 [INFO][vibriocholera.com] acme: Trying to solve TLS-SNI-01
Nov 10 18:53:23 vibriocholera.com caddy[12765]: 2016/11/10 18:53:23 [ERROR] Renewing: acme: Error 403 - urn:acme:error:unauthorized - Incorrect validation certificate for TLS-SNI-01 challenge. Requested <snip>.acme.invalid from 62.2
Nov 10 18:53:23 vibriocholera.com caddy[12765]: Error Detail:
Nov 10 18:53:23 vibriocholera.com caddy[12765]:         Validation for vibriocholera.com:443
Nov 10 18:53:23 vibriocholera.com caddy[12765]:         Resolved to:
Nov 10 18:53:23 vibriocholera.com caddy[12765]:                 62.210.131.151
Nov 10 18:53:23 vibriocholera.com caddy[12765]:                 69.195.153.6
Nov 10 18:53:23 vibriocholera.com caddy[12765]:         Used: 62.210.131.151
Nov 10 18:53:23 vibriocholera.com caddy[12765]: ; trying again in 10s
```
Changing the order of IPs in the DNS zonefile doesn't change things.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Two IPs, serving the same hostname with the same conf. The server/IP first in the list, when sorted numerically, is the IP caddy picks for the DNS challenge. Should be the IP returned by `hostname -i` or similar. 

I don't recall this being an issue on earlier version, and rolling back to previous releases doesn't help. Was there an API change at LE?

**Comment by mholt** [comment]
> DNS challenge consistently picks the wrong IP

Huh? The DNS challenge doesn't contact your server. If this wasn't an issue an issue in an earlier version it's probably because you just got lucky? I dunno -- Caddy isn't doing the work here, it's a Let's Encrypt thing; you might want to ask on their forums instead. :+1:
