### ISSUE TITLE
Reverse Proxied website redirects to proxy without final / if not transparent

### ISSUE THREAD

**Issue by tobya** [mholt/caddy#1254]
### 1. What version of Caddy are you running (`caddy -version`)?

 0.9.3
### 2. What are you trying to do?

Navigate to backoffice.example.ie/subdir

note the missing final /

If I navigate to backoffice.example.ie/subdir/   it works perfectly.

Also works perfectly if proxy clause in caddy file includes `transparent`.

IS this the desired behaviour?  Should transparent fix this issue in this one instance?

### 3. What is your entire Caddyfile?
```
 backoffice.example.ie bcsbackoffice.example.ie   {
     
        gzip

        # Calling Site uses old version of TLS so need to set minimum protocol lower.
        tls {
          protocols tls1.0 tls1.2
        }

       #Logging
       log  /  c:\example\logs\example.example.ie.log "{remote} - [{when}] '{method} {uri} {proto} {status} {port}' {>:scheme} [{>Caddy-Rewrite-Original-URI}] " {
            rotate {
                  size 2
                  age 30
                  keep 12
                }
        } 

       errors  {
            log c:\example\logs\exampleerr.example.ie.log {
              size 50
              keep 5
            }
            502 example.502.html
        }

      #Proxy to Apache
      proxy /  backoffice.example.ie:2020 
 }
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
C:\example\example\htdocs\PRODUCTION\utilities\caddy\caddy.exe -quic 
-conf="C:\example\example\htdocs\PRODUCTION\utilities\caddy\caddyfile" -log std
out

### 5. What did you expect to see?

The site server from https://backoffice.example.ie/subdir

### 6. What did you see instead (give full error messages and/or log)?

Site served from http://backoffice.example.ie:2020/subdir

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

proxy to an apache installation go to t directory with an index.php file but dont include the index.php file or the final / in the url.

**Comment by mholt** [comment]
Is a 3xx redirect being issued? If so, it must be your backend app that is causing that.

**Comment by tobya** [comment]
Ok I'll investigate if this is where the issue is
