### ISSUE TITLE
add a prefix to error messages returned by plugins

### ISSUE THREAD

**Issue by wmark** [mholt/caddy#1255]
In order to make debugging easier, and because sometimes the origin of error messages is not apparent, please add a prefix to error messages returned by plugins.

For example, an operator could encounter this in the logs and wonder about where the error came from, *Caddy* or a *plugin* (for brevity, I've omitted the HTTP Error code 422):
```
MIME Multipart exploding failed on part 1: permission denied
```

Wrapping errors is one way to implement this:
```go
import (
  "github.com/pkg/errors"
)

// When iterating over plugins, return an error as follows:
if err != nil {
  return retval, errors.Wrap(err, "plugin " + pluginName)
}
```
The improved message will guide the operator with every part:
```
plugin upload: MIME Multipart exploding failed on part 1: permission denied
```

**Comment by elcore** [comment]
A very good idea @wmark 👍

**Comment by mholt** [comment]
That errors package is [known](https://github.com/restic/restic/pull/731#issuecomment-274275126) for having high memory usage.

But this is a good idea, I just don't think it is best implemented within Caddy core. I would suggest that plugins should wrap errors like `fmt.Errorf("pluginname: doing this or that: %v", err)` to give better context.
