### ISSUE TITLE
rin HTTPS and HTTP on the same port (or redirect to https)

### ISSUE THREAD

**Issue by My1** [mholt/caddy#1259]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.3

### 2. What are you trying to do?
I saw this kinda feature in imscp (seemingly using nginx backend) where when you go onto the administration port that you dont have to enter HTTPS but if you go onto it via HTTP it throws a 302 to the HTTPS version. which is a really nice feature if you want to run HTTPS on a custom port so you dont need to enter every little detail.

### 3. What is your entire Caddyfile?
```text
localhost:2020, https://bla.domain:2020, http://bla.domain:2020 {
gzip
root c:\somepath
fastcgi / 127.0.0.1:9000 php

tls certs@comain {
protocols tls1.2
key_type p384
dns cloudflare
}
}
```
-> memo: domain name removed.
### 4. How did you run Caddy (give the full command and describe the execution environment)?
I kickstart caddy wit a batch file that sets my cloudflare values as envvars and then runs caddy with the following:
caddy -conf="caddyconf.txt"

### 5. What did you expect to see?
well not really expect but would have been nice if both would be able to run on the same port

### 6. What did you see instead (give full error messages and/or log)?
2016/11/13 18:23:33 cannot multiplex bla.domain (TLS) and bla.domain (not TLS) on same listener

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
just try putting the same domain/port with http and HTTPS in the caddyfile

**Comment by mholt** [comment]
> if you go onto it via HTTP it throws a 302 to the HTTPS version. 

Caddy already does automatic HTTP->HTTPS redirects (unless you disable them).

Anyway, Caddy doesn't serve HTTP and HTTPS on the same port. You'll have to serve HTTP and HTTPS on different ports.

**Comment by My1** [comment]
well it might have been nice to be able to have HTTP and HTTPS on the same port, and as far as I saw it's not impossible. well sad but if it wont get into caddy, nothing I can do...
