### ISSUE TITLE
let the browser decide whether or not to gzip

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#126]
Browsers that support gzip send a header such as "Accept-Encoding: gzip, deflate, sdch", so it's not necessary to specify that it should or shouldn't be used.

The exception to that is that you wouldn't want files such as .zip, .mp3, or extremely small files to be gzipped.

**Comment by abiosoft** [comment]
Caddy already reads that header to decide whether to gzip or not. However, people raised https://github.com/mholt/caddy/issues/108 and this led to https://github.com/mholt/caddy/pull/112 where you can specify accepted file extensions.

Work is currently ongoing to specify accepted MIME types. 

I want to assume we have got you covered. Have we ?

**Comment by coolaj86** [comment]
Yep.
