### ISSUE TITLE
Does Caddy support ECC cert now ? 

### ISSUE THREAD

**Issue by ghost** [mholt/caddy#1260]
Hello,
Caddy 0.9.3
I found from  PR https://github.com/mholt/caddy/pull/706 that I can use ECC cert
here is my conf
```
www.sample.com {
        gzip
        log ./access.log
        tls admin@sample.com {
                key_type ec384
        }
        ......
}
```
but I just got error message:
```
2016/11/14 04:44:34 Caddyfile:9 - Parse error: Wrong key type name or key type not supported: 'EC384'
```
Could you please kindly check ?

**Comment by Remonli** [comment]
Sorry I just deactived previous account and it may confuse you guys about the display name ghost.

**Comment by elcore** [comment]
Hello @Remonli,

> [...] is the type of key to use when generating keys for certificates (only applies to managed or TLS or self-signed certificates). Valid values are rsa2048, rsa4096, rsa8192, p256, and p384. Default is currently rsa2048.

You need to use `key_type p384`
