### ISSUE TITLE
Error pages not beneffiting from markdown directive

### ISSUE THREAD

**Issue by Sirtea** [mholt/caddy#1265]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy (untracked dev build)
(0.9.3-r0 from alpine linux)

### 2. What are you trying to do?

I have declared a 404 error page, but I cannot make it markdownify even that the path is for markdown files

### 3. What is your entire Caddyfile?
```text
8080
root /srv/www
log stdout
errors {
    404 404.html
}
status 404 /templates
markdown / {
    ext .html
    template blog templates/blog.html
    template page templates/page.html
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy
(no arguments)

### 5. What did you expect to see?

I want the page /404.html to be rendered as markdown

### 6. What did you see instead (give full error messages and/or log)?

Plain text, including the front matter

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Reproduce a simple folder with a index (optional), caddyfile and a template for the page.

```text
gerard@aldebaran:~/docker/caddy/www$ tree
.
├── templates
│   ├── blog.html
│   └── page.html
├── 404.html
├── Caddyfile
└── index.html

1 directory, 5 files
gerard@aldebaran:~/docker/caddy/www$ 
```
Place a "page" template and a 404 as follows

```text
gerard@aldebaran:~/docker/caddy/www$ cat 404.html
---
title: Error 404
template: page
---

Error 404: BOOOM!
gerard@aldebaran:~/docker/caddy/www$ cat templates/page.html 
<!DOCTYPE html>
<html>
	<head>
		<title>{{.Doc.title}}</title>
	</head>
	<body>
		{{.Doc.body}}
	</body>
</html>
gerard@aldebaran:~/docker/caddy/www$ 
```

visit http://localhost:8080/nonexistentpage and view the plain text in 404.html

**Comment by mholt** [comment]
One possibility for this issue and both #753 and #1447 is for the errors directive to be configured such that, upon an error, it rewrites the request and sends it back through the chain again. Then proxy or markdown or other middlewares could try to handle the "new" request, and do what they would want to with them.

**Comment by mholt** [comment]
The design of Caddy 2 allows for this.
