### ISSUE TITLE
run as QUIC server

### ISSUE THREAD

**Issue by zhaozhiwen2014** [mholt/caddy#1266]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.1

### 2. What are you trying to do?
RUN caddy as QUIC serverr
### 3. What is your entire Caddyfile?
```
  www.caddy.com:443
  root /var/www/html
  tls /root/ca/intermediate/certs/caddy.cert.pem /root/ca/intermediate/private/caddy.key.pem

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

./caddy  -http2=false -quic

### 5. What did you expect to see?
 with  Chrome DevTools  I can found the QUIC packet or open chrome://net-internals/#quic I can find QUIC sessions

### 6. What did you see instead (give full error messages and/or log)?
with  Chrome DevTools   I  saw that the protocol was httpt/1.1 ,but not quic

 I had enable QUIC : chrome://flags/#enable-quic and my windows hosts had map www.caddy.com to the site's IP

**Comment by mholt** [comment]
You need to update to the latest version of Caddy. :)
