### ISSUE TITLE
Can caddy add substitutions filter modules

### ISSUE THREAD

**Issue by Menma123** [mholt/caddy#1269]
Like https://github.com/yaoweibin/ngx_http_substitutions_filter_module in Nginx.
It is useful for some website to provide backup address.

**Comment by tobya** [comment]
@Menma123 Could you provide an example of what you would like to achieve with this?

**Comment by Menma123** [comment]
a filter module which can do regular expression and fixed string substitutions on response bodies.
For example , it can replace all abc.com to def.com.

**Comment by mholt** [comment]
Hey @Menma123, thanks for your request. This was already attempted in https://github.com/mholt/caddy/pull/76, but it didn't land. Would make a fine [plugin](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127) though! Anyone is welcome to contribute it.
