### ISSUE TITLE
runtime error: index out of range

### ISSUE THREAD

**Issue by slav123** [mholt/caddy#127]
I'm getting this PANIC

````
[PANIC /index.php?/api/record/] middleware/fastcgi/fcgiclient.go:386 - runtime error: index out of range
````

 error with super simple redirect:

````
fastcgi / 127.0.0.1:9000 php
rewrite {
        regexp .*
        ext    /
        to     /index.php?/{path}{query}
    }
````

**Comment by abiosoft** [comment]
Just taken a look at that and realised it happens when the fastcgi sever responds without `Status` header. From your experience with it, is there a specific situation that this happens ?

**Comment by slav123** [comment]
I have two codeigniter projects, and it happens when I'm pasing couple
parameters after authorisation. My guess - sessions, cookies or long URL?

On Wed, Jun 10, 2015 at 6:44 pm, mholt/caddy
<reply@reply.github.com>
wrote:
Just taken a look at that and realised it happens when the fastcgi sever
responds without Status header. From your experience with it, is there a specific situation that this
happens ?

—
Reply to this email directly or view it on GitHub
[https://github.com/mholt/caddy/issues/127#issuecomment-110657094] .[https://github.com/notifications/beacon/AALVJf2kgYS2owR5uBuaK-6l93Sy9SuNks5oR_BSgaJpZM4E-DOm.gif]

**Comment by abiosoft** [comment]
Modify the `to` line to read `to    /index.php?/{path}&{query}`. Does that change anything ?

**Comment by slav123** [comment]
I tried that and it isn't working. Got same set up with phalcon project and it's
ok. It's something specifying with CI.
I think one way or another your middleware code should check range before call
to slice portion. Panic is never good ;)

On Wed, Jun 10, 2015 at 7:58 pm, Abiola Ibrahim <notifications@github.com>
wrote:
Modify the to line to read to /index.php?/{path}&{query} . Does that change anything ?

—
Reply to this email directly or view it on GitHub
[https://github.com/mholt/caddy/issues/127#issuecomment-110678113] .[https://github.com/notifications/beacon/AALVJQCx9SKxopzpkJIhLMdBp56Z1tDLks5oSAHjgaJpZM4E-DOm.gif]

**Comment by abiosoft** [comment]
Yeah. I have seen the issue. I have the fix for that already that would display a proper message instead of panic. I am just trying to see if we can get it to work for you.

Thanks.

**Comment by slav123** [comment]
Probably will try to compile it tomorrow from source, with your fix or my patch
;)
So far caddy works for me very well. I'm trying to replace nginx

On Wed, Jun 10, 2015 at 8:11 pm, Abiola Ibrahim <notifications@github.com>
wrote:
Yeah. I have seen the issue. I have the fix for that already that would display
a proper message instead of panic. I am just trying to see if we can get it to
work for you.

Thanks.

—
Reply to this email directly or view it on GitHub
[https://github.com/mholt/caddy/issues/127#issuecomment-110680523] .[https://github.com/notifications/beacon/AALVJUpJKZydiKWT6nG7mJ6Emv_vbTQlks5oSAS0gaJpZM4E-DOm.gif]

**Comment by slav123** [comment]
I just compiled check what kind of headers i'm getting from my php-fpm (PHP 5.5) - and value coming from
````
resp.Header.Get("Status")
````
returns only status code - 200
