### ISSUE TITLE
Incorrect content-type on custom 404

### ISSUE THREAD

**Issue by wayneashleyberry** [mholt/caddy#1270]
### 1. What version of Caddy are you running (`caddy -version`)?

```
Caddy 0.9.3
```

I'm using a custom build off of https://caddyserver.com/download with the `git`, `expires` and `minify` extensions.

### 2. What are you trying to do?

Serve a custom 404 page generated with Hugo.

### 3. What is your entire Caddyfile?

```text
https://wearenext.co.za {
    gzip
    minify
    root /home/devops/site

    git git@github.com:we-are-next/next-website.git {
       then hugo --destination=/home/devops/site
    }

    expires {
        match .css$ 1y
        match .js$ 1m
        match .png$ 1d
        match .jpg$ 1h
        match .pdf$ 1i
        match .txt$ 1s
        match .html$ 5i30s
    }

    errors {
        404 404.html
    }
}

http://139.59.170.79:80 {
    redir https://wearenext.co.za{uri}
}

http://wearenext.co.za:80 {
    redir https://wearenext.co.za{uri}
}

http://www.wearenext.co.za:80 {
    redir https://wearenext.co.za{uri}
}

https://www.wearenext.co.za {
    redir https://wearenext.co.za{uri}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
./caddy
```

It's running on a Digital Ocean droplet. 1 GB Memory / 30 GB Disk / LON1 - Ubuntu 16.04.1 x64

### 5. What did you expect to see?

https://wearenext.co.za/foo/bar should render the custom 404 page, with the following content type:

```
text/html; charset=utf-8
```

### 6. What did you see instead (give full error messages and/or log)?

The correct html is being rendered, but with an incorrect content-type.

```
text/plain; charset=utf-8
```

The same behaviour occurs on Ubuntu and macOS.

**Comment by wayneashleyberry** [comment]
The full source of our Hugo site is here: https://github.com/we-are-next/next-website

The live site can also be viewed here: https://wearenext.co.za/

**Comment by mholt** [comment]
If you take out other directives like minify, expires, etc, does that eventually fix the problem?

**Comment by wayneashleyberry** [comment]
@mholt it looks like `minify` is the culprit :(

**Comment by mholt** [comment]
Okay. Please see github.com/hacdias/caddy-minify -- I think it's already being addressed.

**Comment by wayneashleyberry** [comment]
Thanks, will do

**Comment by mholt** [comment]
Part of that might be my fault; if he's fixed it I just haven't updated the build server yet (haven't had a chance).

**Comment by wayneashleyberry** [comment]
I don't think it's been fixed @mholt 

https://github.com/hacdias/caddy-minify/issues/7
