### ISSUE TITLE
static files should use strong etag

### ISSUE THREAD

**Issue by rickb777** [mholt/caddy#1271]
I have git rev b783caaaeddaee61384b963ce48bfe385a65b9a5 cloned on master.

This issue is about github.com/mholt/caddy/caddyhttp/staticfiles/fileserver.go.

At line 125

	e := fmt.Sprintf(`W/"%x-%x"`, d.ModTime().Unix(), d.Size())

a weak etag is generated from the modification time and file size.

Is this correct? I think possibly not: it should instead be a strong etag (i.e. without the "W/" prefix).

For static files, it is clear that the representation will not change until the modification time and/or file size change. This allows the use of strong etags.

From Wikipedia,

> A strongly validating ETag match indicates that the content of the two resource representations is byte-for-byte identical and that all other entity fields (such as Content-Language) are also unchanged. Strong ETags permit the caching and reassembly of partial responses, as with byte-range requests.

> A weakly validating ETag match only indicates that the two representations are semantically equivalent, meaning that for practical purposes they are interchangeable and that cached copies can be used. However the resource representations are not necessarily byte-for-byte identical, and thus weak ETags are not suitable for byte-range requests. Weak ETags may be useful for cases in which strong ETags are impractical for a web server to generate, such as with dynamically-generated content.

I noticed this because it stood out as a difference between Nginx and Caddy on my static website.

**Comment by rickb777** [comment]
I've had an alternative idea - I have been developing my own file-serving handler for some time (hence the interest in this topic). You might like to take a look at it: https://github.com/rickb777/servefiles

We might merge some of this code into Caddy's fileserver, or possibly just link to my servefiles directly.

**Comment by mholt** [comment]
You're probably right.

> I noticed this because it stood out as a difference between Nginx and Caddy on my static website.

I wonder, by this do you mean that when loading a page, the browser loads an old version because the weak eTag is the same even though the file has changed?

> I have been developing my own file-serving handler for some time (hence the interest in this topic). 

Cool, I'll take a look!

**Comment by mholt** [comment]
I think this is now done in #1435
