### ISSUE TITLE
Caddyfile in directory listing

### ISSUE THREAD

**Issue by theel0ja** [mholt/caddy#1287]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?

Show directory listing in root what have no index file.

### 3. What is your entire Caddyfile?
```text
localhost:8080

gzip
browse
ext    .html
log    access.log
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
theel0ja@mursu-3:~/Työpöytä/caddy$ caddy
```
Ubuntu 16.04
Installed via [getcaddy.com](https://getcaddy.com/)

### 5. What did you expect to see?
Caddyfile is hidden from directory listing, because it returns "404 Not Found"...
![404 Not Found on /Caddyfile](https://cloud.githubusercontent.com/assets/5832930/20868705/77406512-ba6a-11e6-9c89-f9c57cb29960.png)

### 6. What did you see instead (give full error messages and/or log)?
Directory listing with **Caddyfile**.
![Directory listing on /](https://cloud.githubusercontent.com/assets/5832930/20868683/0d6d9dda-ba6a-11e6-8af3-c79a2a607c45.png)

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Caddyfile to directory root with **browse** enabled in Caddyfile.

**Comment by wendigo** [comment]
You're right - browse plugin did not take into account hidden files :)
