### ISSUE TITLE
Caddy reports "No such site" when using very long subdomain chain

### ISSUE THREAD

**Issue by coderobe** [mholt/caddy#1291]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?
Serve http://according.to.all.known.laws.of.aviation.there.is.no.way.a.bee.should.be.able.to.fly.its.wings.are.too.small.to.get.its.fat.little.body.off.the.ground.the.bee.of.course.flies.anyway.because.bees.dont.care.what.humans.think.is.impossible.cdr.li/

### 3. What is your entire Caddyfile?
```text
according.to.all.known.laws.of.aviation.there.is.no.way.a.bee.should.be.able.to.fly.its.wings.are.too.small.to.get.its.fat.little.body.off.the.ground.the.bee.of.course.flies.anyway.because.bees.dont.care.what.humans.think.is.impossible.cdr.li {
  tls off # LE ACME fails as well
  root /path/to/mysite
  gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/bin/caddy -log stdout -agree=true -conf=/srv/www/Caddyfile -root=/var/tmp -quic

### 5. What did you expect to see?
Caddy serving the site

### 6. What did you see instead (give full error messages and/or log)?
No such site at :80

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Route a very long (but [totally valid](https://en.wikipedia.org/wiki/Subdomain#Overview))  subdomain to your server
Set up Caddy using my example Caddyfile

The site will **serve fine** when using `:80` instead of `according.to.all.known.laws.of.aviation.there.is.no.way.a.bee.should.be.able.to.fly.its.wings.are.too.small.to.get.its.fat.little.body.off.the.ground.the.bee.of.course.flies.anyway.because.bees.dont.care.what.humans.think.is.impossible.cdr.li` in the Caddyfile.

**Comment by coderobe** [comment]
Note: There are no errors in the log(s) (excluding the "No such site" error)

**Comment by mholt** [comment]
Works fine for me, following your instructions.

You know that turning TLS off will not serve the site at port 80, right? https://caddyserver.com/docs/automatic-https

> # LE ACME fails as well

How do you know this?

**Comment by coderobe** [comment]
> You know that turning TLS off will not serve the site at port 80, right?
Oh. Whoops

> How do you know this?

`failed to get certificate: acme: Error 400 - urn:acme:error:malformed - DNS name has too many labels`

**Comment by coderobe** [comment]
i'm going to close this. if the acme issue actually does happen within caddy we should open another issue

**Comment by mholt** [comment]
Let's Encrypt only allows a certain number of labels, I don't know what the limit is though. Double check you're serving the site at the right port.
