### ISSUE TITLE
Cookie issues over QUIC (woocommerce)

### ISSUE THREAD

**Issue by meyskens** [mholt/caddy#1294]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.3 (armhf)

### 2. What are you trying to do?
Woocomerce (WordPress): adding a product to a cart, aka setting a cookie
(only happens on QUIC enabled chrome)
### 3. What is your entire Caddyfile?
```text
abctheater.be, www.abctheater.be {
	root /var/www/abc
	 fastcgi /  /var/run/php/php7.0-fpm.sock php
	rewrite {
        	to {path} {path}/ /index.php?{query}
    	}

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemd, QUIC enabled

### 5. What did you expect to see?
It being able to set the cookie
### 6. What did you see instead (give full error messages and/or log)?
No cookie set

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Install PHP, wordpress and woocomerce default configuration add a sample product and try to order it in a QUIC enabled browser

**Comment by wendigo** [comment]
Maybe related to: https://github.com/lucas-clemente/quic-go/issues/338 ?

**Comment by mholt** [comment]
^ Probably! Nice find @wendigo. I'll do a Caddy release next week that should include that fix.

**Comment by mholt** [comment]
@meyskens Try it now with the latest release. Still having trouble?

**Comment by meyskens** [comment]
@mholt am unable to test as i have another bug that causes the site not to load. Will look if it has been reported before and if not place a new issue.

**Comment by elcore** [comment]
Hello @meyskens,

any updates? Does it work now (with master)?

**Comment by mholt** [comment]
Probably busy with the holidays. :) I'll close this for now, since I'm pretty sure it's been fixed, but if you can confirm it is still there, it might be another bug in the upstream QUIC library, try filing an issue there.
