### ISSUE TITLE
Caddy wildcard tls issuing certs problem in combination with binding to specific ip

### ISSUE THREAD

**Issue by tgmedia-nz** [mholt/caddy#1296]
### 1. What version of Caddy are you running (`caddy -version`)?
CADDY 0.9.3, built via

```
go get github.com/mholt/caddy/caddy
```

### 2. What are you trying to do?

Use caddy in front of apache using wildcard vhosts.

### 3. What is your entire Caddyfile?
```text
:443 {

        bind 1.2.3.4
        proxy / http://127.0.0.1:8080 {
            transparent
            header_upstream Host {host}:443
        }

        tls {
            max_certs 50
        }

        gzip
        errors visible

}

:80 {
	bind 1.2.3.4
        proxy / http://127.0.0.1:8080 {
        transparent
       header_upstream Host {host}:80
        }
        gzip
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
env CADDYPATH=/etc/caddy

limit nofile 1048576 1048576

script
        cd /etc/caddy
        rootdir="$(mktemp -d -t "caddy-run.XXXXXX")"
        exec /usr/local/src/go/bin/caddy -agree -log=stdout -conf=/etc/caddy/Caddyfile -root=$rootdir -ca https://acme-staging.api.letsencrypt.org/directory -catimeout 20s
end script
```
### 5. What did you expect to see?

serving https for all sites that resolve to this host

### 6. What did you see instead (give full error messages and/or log)?

On start of caddy I can request a url with my browser, e.g. https://test.domain.nz and caddy serves it fine. If I then request https://test2.domain.nz after (without caddy restart), it fails with

```
2016/12/15 16:05:08 [INFO] Obtaining new certificate for test2.domain.nz
2016/12/15 16:05:08 [INFO][test2.domain.nz] acme: Obtaining bundled SAN certificate
2016/12/15 16:05:08 [INFO][test2.domain.nz] acme: Trying to solve HTTP-01
2016/12/15 16:05:09 http: proxy error: dial tcp 127.0.0.1:5033: getsockopt: connection refused
2016/12/15 16:05:10 http: TLS handshake error from 1.2.3.4:48202: [test2.domain.nz] failed to get certificate: acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://test2.domain.nz/.well-known/acme-challenge/sbm0Ck1kJo45z8tKnBO89HoQV5eXeyT1isps15D4tEE [223.165.66.205]: 502
Error Detail:
        Validation for test2.domain.nz:80
        Resolved to:
                1.2.3.4
        Used: 1.2.3.4
```

Note the proxy error... - this doesn't always happen straight with the next new domain but it will eventually fail 

If I remove the bind in the Caddyfile to make caddy listen to 0:0:0:0:443 (not a specific IP), it works without a problem.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Build a test server with the following:

```
cd /usr/local/
wget https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz
tar -xzf go1.7.3.linux-amd64.tar.gz
apt install git

go get github.com/mholt/caddy/caddy
```

install startup script, use caddyfile as provided (replace IPs to match yours), test via a domain that resolves to that IP.

**Comment by mholt** [comment]
What's in your hosts file?

**Comment by tgmedia-nz** [comment]
> What's in your hosts file?

hosts file contains one line with

127.0.0.1 servername.fqdn servername localhost

> And what's port 5033 all about?

Looking at the code its this:

`DefaultHTTPAlternatePort = "5033"`


> What's the actual IP you're binding to?

The second public IP address on that server where the main IP is in use with apache and caddy is supposed to bind to the second public IP. Unfortunately in my scenario I can't use the main IP for other system integration reasons, e.g. apache2 configs are in config management control.


> You know that redacting the domain names is pointless, right? Because they go into public CT logs anyway

No, I didn't know :) it's general habit of mine to redact as much as possible, hehe

**Comment by mholt** [comment]
> Looking at the code its this:

Oh oops :smile: I forgot about that -- I just wrote my reply as I was headed out the door. Thanks for finding that. ;)

Are you binding to an IP other than the one the hostnames resolve to?

**Comment by tgmedia-nz** [comment]
> Are you binding to an IP other than the one the hostnames resolve to?

My domains resolve to the IP that caddy binds to, yes. The host name of the server though resolves to the main IP, not caddy's IP :)

**Comment by mholt** [comment]
I see... I'll try to reproduce this...

**Comment by mholt** [comment]
@tgmedia-nz  It's a miracle. I am able to reproduce this. Working on a fix.

**Comment by mholt** [comment]
The fix will go out in the next release, to get it now just build from source. :) Thanks!
