### ISSUE TITLE
Use tls with explicit certificates and HTTP redirects

### ISSUE THREAD

**Issue by xrstf** [mholt/caddy#1297]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.3

### 2. What are you trying to do?

Run a frontend proxy that forces HTTPS and uses explicitely configured certificates. The manual redirect works just fine as long as I don't enable the `tls` section in my Caddyfile. Putting `redir` before or after the `tls` has no effect. I _can_ just have two server blocks (one for http, one for https), but this would require me to duplicate a few things.

### 3. What is your entire Caddyfile?
```text
http://0.0.0.0, https://0.0.0.0 {
  root /var/www

  # redirect to HTTPS
  redir 301 {
    if {scheme} not https
    / https://{host}{uri}
  }

  tls my.crt.pem my.key.pem

  proxy / myapp-container:3002 {
    transparent
  }

  log stdout

  errors {
    log stdout
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

    bash% sudo caddy -conf Caddyfile.proxy
    Activating privacy features... done.
    http://0.0.0.0
    https://0.0.0.0
    WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".

### 5. What did you expect to see?

    bash% curl -I http://localhost/foo
    HTTP/1.1 301 Moved Permanently
    Location: https://localhost/foo
    Server: Caddy
    Date: Thu, 15 Dec 2016 12:47:28 GMT
    Content-Type: text/plain; charset=utf-8

### 6. What did you see instead (give full error messages and/or log)?

    bash% curl -I http://localhost/foo
    HTTP/1.1 502 Bad Gateway
    Content-Type: text/plain; charset=utf-8
    Server: Caddy
    X-Content-Type-Options: nosniff
    Date: Thu, 15 Dec 2016 12:51:00 GMT
    Content-Length: 16

The 502 is expected, as this Caddy is not running within our Docker environment and there is no `myapp-container` hostname reachable. That doesn't matter though, it's only important to note that it's not the expected 301 redirect.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Take the Caddyfile, run Caddy and perform any HTTP request against it.

**Comment by tobya** [comment]
Maybe I'm missing something here, but caddy automatically serves on https you do not need a redirect.

    0.0.0.0 {
      root  /var/www

      etc....
     }

will server only on https and issue a 301 on a request to http.  Is this not what you require?

**Comment by mholt** [comment]
@tobya Caddy only does the automatic redirects as part of automatic HTTPS: https://caddyserver.com/docs/automatic-https.

**Comment by mastercactapus** [comment]
Just ran into this..

```
:80, :443
tls {
	load /certs
}

redir /oldurl.html /new
```

`curl localhost/oldurl.html` gives a 404, not a redirect as would be expected

**Comment by mholt** [comment]
@mastercactapus @xrstf If you can build from master, go ahead and give it a try now that the fix has been merged in. I'll close this but re-open if you confirm it is still not fixed!

**Comment by jeremiahmegel** [comment]
This has not been fixed. Here are my results when attempting to redirect `/foo` to `/bar` with a custom TLS cert/key.

```
user@machine:/var/www/test$ cat Caddyfile 
http://, https://
tls /path/to/cert.pem /path/to/key.pem
redir /foo /bar
user@machine:/var/www/test$ curl -I http://localhost/foo                               
HTTP/1.1 404 Not Found
Content-Type: text/plain; charset=utf-8
Server: Caddy
X-Content-Type-Options: nosniff
Date: Wed, 15 Mar 2017 18:31:33 GMT
Content-Length: 14

user@machine:/var/www/test$ curl -Ik https://localhost/foo                             
HTTP/1.1 301 Moved Permanently
Location: /bar
Server: Caddy
Date: Wed, 15 Mar 2017 18:31:35 GMT
Content-Type: text/plain; charset=utf-8

```

**Comment by mholt** [comment]
@jeremiahmegel 

Works for me 🤷‍♂️  

```plain
$ curl -I http://localhost/foo
HTTP/1.1 301 Moved Permanently
Location: /bar
Server: Caddy
Date: Wed, 15 Mar 2017 18:44:36 GMT
Content-Type: text/plain; charset=utf-8
```

**Comment by jeremiahmegel** [comment]
Whoops, you're right. I was running `v0.9.5` instead of building from source. Carry on.
