### ISSUE TITLE
serveFile TODO is fixed in http.Dir

### ISSUE THREAD

**Issue by nhooyr** [mholt/caddy#1299]
https://github.com/mholt/caddy/blob/54c63002ccc41e9fd533384a9d87437371bc85df/caddyhttp/staticfiles/fileserver.go#L50

Seems to be fixed at https://github.com/golang/go/blob/aeaa4c3c1da9e7a4afd4152913d6f2bfcf4fad2d/src/net/http/fs.go#L37

**Comment by mholt** [comment]
Thanks for the heads up @nhooyr  --- can you describe how that line resolves the TODO? I'm not seeing it at a glance at least... :confused:

**Comment by nhooyr** [comment]
Ah, I misread, sorry!
