### ISSUE TITLE
Automatic HTTPS failed when using TLS-SNI-01

### ISSUE THREAD

**Issue by deanrock** [mholt/caddy#1305]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.3

### 2. What are you trying to do?
Use Caddy with multiple domains with automatic HTTPS.

### 3. What is your entire Caddyfile?
```text
:80 {

        gzip
        proxy / localhost:81 {
            transparent
        }
        log /path/to/logs/access.log

}

domain.xyza {
        gzip
        proxy / localhost:81 {
            header_upstream Host {host}
            header_upstream X-Real-IP {remote}
            header_upstream X-Forwarded-For {remote}
            header_upstream X-Forwarded-Proto http
        }
        log /path/to/logs/access.log
}
```
(config for other domains is the same as the one for `domain.xyza`, except the domain name)

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```bash
/opt/caddy/bin/caddy -agree -log=stdout -conf=/opt/caddy/etc/Caddyfile
```

### 5. What did you expect to see?
Caddy to automatically grab SSL certs for all of my domains from Let's encrypt, and starts using it.

### 6. What did you see instead (give full error messages and/or log)?
```text
Activating privacy features...2016/12/19 21:52:46 [INFO][example.com] acme: Obtaining bundled SAN certificate
2016/12/19 21:52:46 [INFO][example.com] acme: Trying to solve HTTP-01
2016/12/19 21:52:47 [INFO][example.com] Served key authentication
2016/12/19 21:52:48 [INFO][example.com] The server validated our request
2016/12/19 21:52:48 [INFO][example.com] acme: Validations succeeded; requesting certificates
2016/12/19 21:52:49 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2016/12/19 21:52:49 [INFO][example.com] Server responded with a certificate.
2016/12/19 21:52:49 [INFO][random-domain.xyza] acme: Obtaining bundled SAN certificate
2016/12/19 21:52:49 [INFO][random-domain.xyza] acme: Trying to solve TLS-SNI-01
2016/12/19 21:52:56 [random-domain.xyza] failed to get certificate: acme: Error 400 - urn:acme:error:connection - Failed to connect to x.x.x.x:443 for TLS-SNI-01 challenge
```

Caddy successfully retrieves SSL certs for domains with HTTP-01. However, at some point when obtaining the certificates it randomly switches to `TLS-SNI-01` which fails, because it apparently cannot connect to port 443.

Not sure why it's not using HTTP-01 verification for all domains. Restarting Caddy helps, at least until it switches back to `TLS-SNI-01` verification. I had to verify approximately 50 domains, and needed to restart Caddy at least 10 times.

Port 443 is not blocked and works just fine, because after Caddy successfully verified all domains (using HTTP-01), it started serving websites via HTTPS without a problem.

**Comment by mholt** [comment]
Unfortunately, I cannot reproduce this behavior with what you've given here. I just tried your configuration with my own domain and it works just fine.

**Comment by deanrock** [comment]
Thanks for checking it out. I tried to reproduce the issue on another server, but couldn't get TLS-SNI-01 to fail. I guess it's a problem with the configuration of the first server, but oddly enough, SSL works without a problem, after the certs were successfully requested.
