### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by meyskens** [mholt/caddy#1308]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.4 (armhf)

### 2. What are you trying to do?
accessing my site

### 3. What is your entire Caddyfile?
```text
abctheater.be, www.abctheater.be {
	root /var/www/abc
	 fastcgi /  /var/run/php/php7.0-fpm.sock php
	rewrite {
        	to {path} {path}/ /index.php?{query}
    	}

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemd

### 5. What did you expect to see?
site loading

### 6. What did you see instead (give full error messages and/or log)?
500 internal error
in journal:
```
Dec 25 17:52:34 maartje-tm caddy[11746]: 2016/12/25 17:52:34 [PANIC] runtime error: invalid memory address or nil pointer dereference
Dec 25 17:52:34 maartje-tm caddy[11746]: 2016/12/25 17:52:34 [PANIC] runtime error: invalid memory address or nil pointer dereference
Dec 25 17:52:36 maartje-tm caddy[11746]: 2016/12/25 17:52:36 [PANIC] runtime error: invalid memory address or nil pointer dereference
Dec 25 17:52:36 maartje-tm caddy[11746]: 2016/12/25 17:52:36 [PANIC] runtime error: invalid memory address or nil pointer dereference
Dec 25 17:52:44 maartje-tm caddy[11746]: 2016/12/25 17:52:44 http2: server: error reading preface from client 81.82.132.241:57232: timeout waiting for client preface
Dec 25 17:52:44 maartje-tm caddy[11746]: 2016/12/25 17:52:44 http2: server: error reading preface from client 81.82.132.241:57230: timeout waiting for client preface
Dec 25 17:52:44 maartje-tm caddy[11746]: 2016/12/25 17:52:44 http2: server: error reading preface from client 81.82.132.241:57231: timeout waiting for client preface
Dec 25 17:52:44 maartje-tm caddy[11746]: 2016/12/25 17:52:44 http2: server: error reading preface from client 81.82.132.241:57228: timeout waiting for client preface
Dec 25 17:52:44 maartje-tm caddy[11746]: 2016/12/25 17:52:44 http2: server: error reading preface from client 81.82.132.241:57229: timeout waiting for client preface
```
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Install Caddy on an armhf device (I can provide a server if needed) and run Caddy to serve a php-fpm (my reverse proxy worked) site. 

I suspect this has to do with it being 32bit, I have seen issues with that in golang apps before

**Comment by mholt** [comment]
Hey @meyskens, Merry Christmas.

This was already reported and fixed in #1306. Also see https://twitter.com/caddyserver/status/812057852558745600. Try building from source.
