### ISSUE TITLE
MIPS build

### ISSUE THREAD

**Issue by itskenny0** [mholt/caddy#1319]
Hi there,

I'd like to use Caddy on my D-Link DIR-860L router running OpenWRT. The CPU in this model is a ralink/MediaTek MIPS. Any chance a MIPS build could be offered?

Best, 
Kenny

**Comment by mholt** [comment]
Hey Kenny! Yes, the new site's download page will definitely offer MIPS builds. :+1: It's already working for me locally, just give me a few weeks to get the design and content finalized on all the docs pages.

Since this is effectively already done, I'll close the issue now. STay tuned!
