### ISSUE TITLE
Compete with python -m SimpleHTTPServer

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#132]
Often times I want a self-contained ad-hoc server that I could get within an instant and setup in the current directory within an instant.

Some ideas:

* have a curl / wget install script grab the right bin and shove it into /usr/local/bin/caddy ([I've done this before](https://github.com/coolaj86/iojs-install-script))
* serve http from the current folder with indexes when no config exists
* also serve local https (bundle-in certs for localhost.caddyserver.com) for easy development

Currently there are a few node packages that partially do this. Obviously python kinda does it. It would be nice to have an easy-to-share 0-dep bin to handle it and perhaps caddy can fit in that space.

**Comment by mholt** [comment]
That's been the purpose of Caddy from day one. When you run `caddy` in any directory, it defaults to serving static sites from that directory, complete with support for index files. And unlike Python's SimpleHTTPServer, it actually honors the Range header.

**Comment by coolaj86** [comment]
It doesn't serve directory indexes is what I meant.

**Comment by coolaj86** [comment]
I'll work on an installer script and give you arm-compiler arm bins.

We could put a

`cur -fsSL  caddyserver.com/install | bash`

On the homepage?

**Comment by mholt** [comment]
Oh, directory indexes. Just place a Caddyfile with `browse` somewhere in it - or if you prefer to stay purely on the command line, you can pipe it in: `echo "localhost\nbrowse" | caddy` - something like that.

As for the installer script, I *love* piping scripts from the Internet into bash :smile: That aside, is this just for the ARM binaries? If so, I can just make the cross-compile work. There's a trick to getting them to work on older RasPis - I've done it before - just have to remember what it is.

**Comment by coolaj86** [comment]
Install script for `caddy` + `caddy-browse` (with indexes): https://github.com/mholt/caddy/issues/142
