### ISSUE TITLE
Customize the working directory of the startup command

### ISSUE THREAD

**Issue by oliverpool** [mholt/caddy#1320]
It could be nice if the `startup` (resp. `shutdown`) commands could provide a way to customize the working directory for the command.

Example:
```
startup ls . {
   workingdir /
}
```
Should output the content of `/` (and not the content of the working directory of the caddy executable - which is the current behavior)

**Comment by tobya** [comment]
What would this be used for?  I'm not sure why you would want to output a list of files on startup?  Could you achieve it with a script?

**Comment by oliverpool** [comment]
My example is a customized [tus](https://tus.io/) server which stores the files to a relative location.

I get around the missing working directory by using a location relative to the executable.
Such behavior could probably also be implemented via a script.

So after thinking a bit, I do not see this feature as essential (I got around without it), but more as a "nice-to-have".
Maybe it could be a good feature for new contributors to implement (nothing urgent and small enough to get used to the code) - when I have some time (unfortunately not so soon) I might give it a shot! (if you are ok with it)

**Comment by mholt** [comment]
Well, the workaround is simple enough. You could probably also give an absolute path maybe? For now, I'd rather avoid adding this complexity unless it's really needed. Thanks for the request though!
