### ISSUE TITLE
Get certificates from certbot folder, if available.

### ISSUE THREAD

**Issue by jcgruenhage** [mholt/caddy#1321]
I use certbot to get my certificates for other services (ejabberd, cockpit, mailserver and some more), where I use domains that I also use in caddy. I could manually specify path of key and cert, but for those 10 or so subdomains, that would be a lot of work (and it would make my caddy file rather bloated), and I can't imagine being the only one with a setup like that. 
If automatic TLS could just look in that folder first, that would make things a lot easier. 

Alternatively, caddy could just use the same folder/format as certbot to store it's certificates, so that you don't have the acme certs in multiple locations in the first place, so that certbot only would have to take care of certificates caddy doesn't use.

**Comment by mholt** [comment]
If you use certbot, you'll have to reload Caddy when the certificates are renewed, so you might as well just specify the certs in your Caddyfile manually too. (Bloat? It's one line per site. Compare that to your apache or nginx configs.)

It's not as easy as just "looking" in a folder. It needs to know when the files change, and the files need to have the same format and naming conventions. 

Sorry, but I'm not going to implement this. You can tell Caddy where to load certificates and keys from with the `tls` directive, but auto HTTPS is either on or off, not halfway. It's confusing.
