### ISSUE TITLE
Proxy / only, exclude /ANY

### ISSUE THREAD

**Issue by txthinking** [mholt/caddy#1322]
The nginx config is
```
server {
    ...
    location = / {
        proxy_pass http://127.0.0.1:1041;
    }
    location / {
        root   /public;
    }
    ...
}
```
@abiosoft 

Thanks

**Comment by elcore** [comment]
Hello @txthinking,

this is not a bug nor a feature request! Please use our forum at https://forum.caddyserver.com/

**Comment by elcore** [comment]
Hello @txthinking,

this is not a bug, nor a feature request. Please use our forum at https://forum.caddyserver.com/ 😄

**Comment by mholt** [comment]
Yeah, I'm not really sure what this is about. Can you please clarify?

**Comment by txthinking** [comment]
OK, Thank you.
