### ISSUE TITLE
Markdown plugin to generate meta elements from prelude items description and keywords

### ISSUE THREAD

**Issue by pepa65** [mholt/caddy#1326]
Right now the markdown plugin uses the front matter 'title' item for use in the html title element. It would be great if it could also generate html meta elements from the markdown front matter items description and keywords:

`description: ...` becomes `<meta name="description" content="..." />`

`keywords: ...` becomes `<meta name="keywords" content="..." />`

**Comment by mholt** [comment]
I haven't seen the meta keywords tag be relevant for years... description, I could see that being useful. (Keywords though? Search engines don't use that anymore AFAIK.)

Just trying to stay as simple as possible. :) At what point does it become better to fill out a custom template?

**Comment by pepa65** [comment]
It just seemed logical for a module that translates into html. I think it would make a lot of sense to do it, and it's really easy and quick win. Maybe only "description", "author" and perhaps "copyright"? Or you could just put any legal meta name in the front matter into a meta tag. Setting the front matter is a user choice, and there is an obvious way of translating/using it.

**Comment by pbeckmann** [comment]
I think it's a good idea, and i would do it, but i see a small problem. 

Not all meta tags are applicable via 
`<meta name="key" content="value" />`

For example with HTML5 we got
`<meta charset="...">`
`<meta http-equiv="..." content="..."/>`

And i think, if we do this, next month we get an request, 
Adding generics headers with key value pairs ;)

**Comment by pepa65** [comment]
I think the meta http-equiv elements aren't in wide use anymore now that we have meta charset="utf-8" (which markdown already uses).

**Comment by pbeckmann** [comment]
Okay,

so i would implement a list with allowed meta tag names, like _description_, _author_ and so on.
Then check every front matter if it's in this list or not.

If we found the front matter, adding that to another list and iterate in the template over the list like we do it with the styles.

But i think we should not remove it from the existing Variables Map, so we don't kill existing templates and their use of those front matters..

**Comment by pepa65** [comment]
I think there is no actual clash between template use of front matter items and using them as a meta tag when it is a valid meta tag. But to avoid unhappiness it's probably best to just have a limited and useful list of supported meta tags.
