### ISSUE TITLE
Caddy rewrites example.com/foo/bar to example.com/bar/

### ISSUE THREAD

**Issue by Mxbonn** [mholt/caddy#1327]
I am trying to host a site on a specific path on my domain, so my caddy file looks like this:
```text
example.com/foo/
```
My directory structure looks like this
```text
root/
| -- Caddyfile
| -- index.html
| -- bar/
|     | -- index.html
````
So when I want to see the content of index.html on my site I would go to:
`example.com/foo/bar/index.html` or `example.com/foo/bar/`.
This works all like expected, but if I don't include that final '/' and type `example.com/foo/bar` it gets redirected to `example.com/bar/`, which is not a valid page, nor what I intended.

I know that `foo/bar` and `foo/bar/` are not the same by default but the fact that Caddy does add a trailing slash make me think the intention is to make them both equal when there is no file called bar.

Is this a bug or what should I do to redirect `example.com/foo/bar` to `example.com/foo/bar/`?

**Comment by mholt** [comment]
Does the same thing happen if using curl? Use curl -v and post the exact, unmodified output.

**Comment by tobya** [comment]
Can you post your caddyfile?

**Comment by Mxbonn** [comment]
@tobya I posted it in the first part of the issue (although abstract) but concretely its just:
```text
bonnaerens.me/best/
```

**Comment by mholt** [comment]
Oh, I think I might know what's going on. Somebody have a chance to look at it? https://github.com/mholt/caddy/blob/3f770603bc8d55dfd6d90131f62bbf61e70c7ebd/caddyhttp/httpserver/https.go#L151 -- I'm willing to bet that URI has `/best` stripped from the URI because the site definition includes `/best` -- see https://github.com/mholt/caddy/blob/3f770603bc8d55dfd6d90131f62bbf61e70c7ebd/caddyhttp/httpserver/server.go#L258-L266.

But I'm speculating. Would love if someone could verify and fix. I'm super busy until next week. ;)

**Comment by ericdreeves** [comment]
@mholt Indeed, pathPrefix is trimmed from the path.

As a quick test, I used RequestURI from http.Request (+"/") [here](https://github.com/mholt/caddy/blob/3f770603bc8d55dfd6d90131f62bbf61e70c7ebd/caddyhttp/staticfiles/fileserver.go#L87).

Here's the result when allowing curl to follow redirects (some curl output omitted).

	# curl -v -L https://example.com/foo/bar
	> GET /foo/bar HTTP/1.1
	> User-Agent: curl/7.38.0
	> Host: example.com
	> Accept: */*
	>
	< HTTP/1.1 301 Moved Permanently
	< Location: /foo/bar/
	< Server: Caddy
	< Date: Sat, 07 Jan 2017 01:01:05 GMT
	< Content-Length: 44
	< Content-Type: text/html; charset=utf-8
	<
	* Ignoring the response-body
	* Connection #0 to host example.com left intact
	* Issue another request to this URL: 'https://example.com/foo/bar/'
	* Found bundle for host example.com: 0x55fd8f68e6c0
	* Re-using existing connection! (#0) with host example.com
	* Connected to example.com (172.19.0.2) port 443 (#0)
	> GET /foo/bar/ HTTP/1.1
	> User-Agent: curl/7.38.0
	> Host: example.com
	> Accept: */*
	>
	< HTTP/1.1 200 OK
	< Accept-Ranges: bytes
	< Content-Length: 0
	< Content-Type: text/html; charset=utf-8
	< Etag: W/"58703dc6-0"
	< Last-Modified: Sat, 07 Jan 2017 01:00:54 GMT
	< Server: Caddy
	< Date: Sat, 07 Jan 2017 01:01:05 GMT
	<
	* Connection #0 to host example.com left intact

**Comment by ericdreeves** [comment]
Closing, as the fix has been implemented.
