### ISSUE TITLE
*middleware.responseRecorder is not http.Hijacker: missing method Hijack

### ISSUE THREAD

**Issue by lmas** [mholt/caddy#133]
Hello, I'm getting this error when trying the websocket stuff with caddy and using `Go 1.4.2`. 
Running caddy with:

    localhost
    log stdout
    errors stdout
    websocket /echo cat

And when I try to test that websocket, using [`ws`](https://github.com/yhat/ws) (for simplicity's sake):

    ws ws://localhost:2015/echo

I get this error in the caddy log (and the `ws` script fails with a "bad status"):

    [PANIC /echo] /home/lmas/.go/src/golang.org/x/net/websocket/server.go:74 - interface conversion: *middleware.responseRecorder is not http.Hijacker: missing method Hijack
    127.0.0.1 - [11/Jun/2015:21:57:20 +0200] "GET /echo HTTP/1.1" 500 26

Another thing I noticed is that if I instead try to run:

    ws ws://127.0.0.1:2015/echo

I get no errors in the caddy logs but `ws` fails again with the same message.

Any ideas why this is happening? Any suggestions for how to fix it?

**Comment by mholt** [comment]
Ah, nuts. I know why that's happening. If you take out the `log` directive it should work.

I won't have a chance to fix this today, but maybe somebody else will?

**Comment by mholt** [comment]
Basically, log is replacing the net/http ResponseWriter with its own responseRecorder, which is not a hijacker. Log shouldn't be logging ws requests, I think - they're not regular HTTP requests in that regard.

**Comment by tw4452852** [comment]
Why not we just implement `http.Hijacker` if any ?

**Comment by lmas** [comment]
I haven't looked at the source yet, but will ws errors still be logged in
some other way if we remove that log? Or is it the only logger for ws?

**Comment by mholt** [comment]
@lmas `log` only logs accesses; `errors` logs errors, but does not replace the ResponseWriter. I need to double-check how `log` should be handling websocket connections.

**Comment by lmas** [comment]
Oh you meant THAT log.

**Comment by mholt** [comment]
Closed with #134 - honestly, I'm surprised that worked. :100:

**Comment by lmas** [comment]
Hell yeah! Thanks guys!
