### ISSUE TITLE
Wrong arguments for function acme.Client.ObtainCertificate() and acme.Client.RenewCertificate()

### ISSUE THREAD

**Issue by FTwOoO** [mholt/caddy#1339]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Latest clone

### 2. What are you trying to do?
try to build and run my caddy plugin

### 3. What is your entire Caddyfile?
```text
0.0.0.0
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddydev

### 5. What did you expect to see?
caddy server running with the plugin activated

### 6. What did you see instead (give full error messages and/or log)?

```
../gopath/src/github.com/mholt/caddy/caddytls/client.go:200: too many arguments in call to c.acmeClient.ObtainCertificate

../gopath/src/github.com/mholt/caddy/caddytls/client.go:288: too many arguments in call to c.acmeClient.RenewCertificate
```

**Comment by mholt** [comment]
Hi,

This isn't a Caddy issue so I'm closing this (Caddy does compile) -- your deps are out of date. Run `go get -u github.com/xenolf/lego`.

Thanks!
