### ISSUE TITLE
caddy download tarballs are tarbombs?

### ISSUE THREAD

**Issue by winny-** [mholt/caddy#1346]
caddy download tarballs are tarbombs? There is probably a well thought out reason behind a root-less tarball, but I figured it wouldn't hurt to ask on the issue tracker.

https://en.wikipedia.org/wiki/Tar_(computing)#Tarbomb

**Comment by dprandzioch** [comment]
Actually also drives me crazy from time to time when setting up a host... +1 👍

**Comment by mholt** [comment]
I guess now's a better time than ever to change this, since I'm rewriting the website and all the build server code.

**Comment by mholt** [comment]
Hmm, wait. This would be the responsibility of whatever extraction program you're using, isn't it? My Mac always extracts to a folder when I open an archive, even if the contents weren't originally in one (sometimes that drives me crazy).

**Comment by winny-** [comment]
That's one of the nicer features of Finder. It always ensures an archive has a root directory. Unfortunately that isn't the case for `tar`.

**Comment by mholt** [comment]
Hmm, so isn't it good practice to untar into an empty directory, since tar doesn't do that for you?

**Comment by pbeckmann** [comment]
Yes, it should be good practice. In fact i think, we are just too lazy. We could look into the tarball before with `tar tf` and see if there is a root folder or not. Anyway i think it would be nice to have the root folder there. But if its too much overhead, then I can deal with it.

Maybe we should create a PR to the tar source code :thinking: :laughing:

**Comment by mholt** [comment]
Would love that. Saves me lot of time so I can focus on (frankly) more important things. ;)

I was looking into doing this in [archiver](https://github.com/mholt/archiver). If the archive name had a trailing file separator (filepath.Separator), it would bundle the top-level files within a folder called after the name of the archive (without the extension).

For example:

```
$ archiver make mytar.tar.gz/ item1.txt item2.txt dir1
```

Would create a file called "mytar.tar.gz" and within it, a folder called "mytar", and within that, three items (two text files and a directory with its contents). Make sense? Anyway, I'd accept PRs there. It was just taking a little more time than I wanted right now.
