### ISSUE TITLE
Add {code} variable for custom error pages

### ISSUE THREAD

**Issue by 9999years** [mholt/caddy#1347]
I’d like to have a variable for error pages like `{uri}` is for the `rewrite` directive.

To mirror a site on another (trivial example) you could use something like

```
site.com {
    rewrite / mirroredsite.com/{uri}
}
```

which would redirect `site.com/foo/bar?baz=buzz` to `mirroredsite.com/foo/bar?baz=buzz`.

However, error pages must be written either on a per-page basis:

```
errors {
    log ../error.log
    404 404.html # Not Found
    500 500.html # Internal Server Error
}
```

or with a one-size-fits-all approach:

```
errors {
    * default_error.html
}
```

I’d love to see variables for the `errors` directive so I could use something like

```
errors {
    * error_handler.html?code={code}&description={description}&debug={debug}
}
```

Where `{code}` could have a value like `404`, `{description}` could be `File not found`, and `{debug}` could be something like `Path /whatever/url not found on the server!`.

An `int code` variable is already passed to `findErrorPage`, would a suitable implementation replace `{code}`, in `h.GenericErrorPage` [here (`errors.go:104`)](https://github.com/mholt/caddy/blob/master/caddyhttp/errors/errors.go#L104)? What would the potential scope of this be? I think a `{code}` variable is reasonable, but `{description}` and `{debug}` might be a bit out of scope — or they could be slightly separated, like static and regexp redirects are with `rewrite`.

**Comment by 9999years** [comment]
Oh! In case it wasn’t clear, I’d love to code this and make the PR, I’d just like a bit of insight on what a good implementation would look like, so I know *what* to code.

👍

**Comment by mholt** [comment]
So, I'm not sure that a query string on the errors page will work; if I recall correctly, the errors middleware just opens the file that you specify; it doesn't do a redirect.

There is already a {status} placeholder. Is that what you want?

**Comment by 9999years** [comment]
Yes, exactly! Unfortunately, it looks like placeholders aren’t implemented by the errors middleware though:

```
18/Jan/2017:21:11:33 -0500 [NOTICE 404 /eiarsntoiaernstoie] could not load error page: open www/site.tld/error/index.php?code={status}: no such file or directory
```

(For context, it worked fine with `* error/index.php`, only `* error/index.php?code={status}` failed. FWIW, I tried a few other placeholders as well to similar effect.)

**Comment by mholt** [comment]
Right, the errors directive doesn't do a redirect, it only loads a static file from disk. It also won't execute PHP... what is the change you're proposing, exactly?

**Comment by 9999years** [comment]
For the errors middleware to support placeholders and ideally run through fast CGI layers as well, just like other pages are served.

**Comment by coderobe** [comment]
> Where {code} could have a value like 404, {description} could be File not found, and {debug} could be something like Path /whatever/url not found on the server!.

Displaying URI content on your site is generally a bad idea, it opens up the possibility of XSS & phishing attacks.

**Comment by mholt** [comment]
Going to close this, since those ^ security concerns are real (and also for inactivity).
