### ISSUE TITLE
How to use it with Tomcat.

### ISSUE THREAD

**Issue by aadrian** [mholt/caddy#1348]
Please extend the docs (or wiki) showing how to use Caddy with Tomcat (maybe with other Application Servers too?)

Thank you.

**Comment by mholt** [comment]
I haven't used Tomcat. There's an examples repo here: https://github.com/caddyserver/examples and a forum here, where  you could ask for this kind of help: https://forum.caddyserver.com :)

**Comment by aadrian** [comment]
@mholt well, this is kind of catch 22 : googling for "caddy +tomcat" returns no relevant information, so most user won't even consider caddy for their projects in first place, hence my suggestion.

Examples are a nice thing, but more helpful would be a wiki page (with a described example) for each relevant platform that was usually used with Apache HTTPD or NginX .

**Comment by mholt** [comment]
Do you really want a Tomcat example from someone who has never used Tomcat before? :innocent:

I think most Caddy users are not Tomcat users, but I wholly welcome a Tomcat example!

**Comment by aadrian** [comment]
> Do you really want a Tomcat example from someone who has never used Tomcat before?

If you put it like that, one could have serious doubts about using Caddy at all for anything else than static pages :) .

> I think most Caddy users are not Tomcat users

Most users seem to use it for static resources or simpler stuff so far :) .

> This is the kind of thing that makes me wonder if offering paid support options for people who need specific integrations would be beneficial

Payed support would be important for any open source project that wants to be adopted by companies.

However, a few issues need to be considered:
  - developers don't like crippleware (e.g. see nginx plus) , so those projects won't be adopted in first place (hence for most projects with Application Servers still Apache Httpd is used - see mod_jk/ajp).
  - documentation for money is also perceived like extortion
  - if a project (open source) is complete and well documented, companies still need payed support because in most cases it's a requirement to be able to adopt them in first place. Even if companies won't make much use of the payed support (except when things go wrong), they really need that "insurance" that someone very competent would help if their own developers can't fix a problem.

**Comment by paragonie-scott** [comment]
> Most users seem to use it for static resources or simpler stuff so far :) .

I use it for serving PHP sites and never having to worry about TLS management. It's great!

> documentation for money is also perceived like extortion

Access to existing documentation to money? I can kind of see that, from an anti-Elsevier crowd especially.

But "taking the time to research and publish new documentation" is a service that someone should be paid to do, not something that everyone is entitled to for free (else, it's extortion).

**Comment by mholt** [comment]
> If you put it like that, one could have serious doubts about using Caddy at all for anything else than static pages :) .

Why?

> Most users seem to use it for static resources or simpler stuff so far :) .

I'd love to see your analysis on this. What's your data source?

> developers don't like crippleware (e.g. see nginx plus) , so those projects won't be adopted in first place

And yet NGINX Plus is successful. 🤔 

Caddy's not "crippleware", as you call it. It's the same software for everyone.

> documentation for money is also perceived like extortion

I honestly don't know what to say to this. I'm appalled that you think that you or any other user of OSS is entitled to a developer's time for free just because the software is free to use. I have helped companies integrate Caddy in custom ways and they're billed for it. Why should you get it for free?

You're welcome to contribute an example to the [examples repository](https://github.com/caddyserver/examples) just as other users have done -- users who took their own time to figure something out and then they, of their own good will, have shared it with the rest of the community (which includes you) to use and build upon, free of charge. I add examples there myself when I encounter a situation in my own line of work (like when I fronted Discourse with Caddy) that others could benefit from.

> if a project (open source) is complete and well documented, companies still need payed support because in most cases it's a requirement to be able to adopt them in first place. Even if companies won't make much use of the payed support (except when things go wrong), they really need that "insurance" that someone very competent would help if their own developers can't fix a problem.

I agree completely. But that is a different topic.

**Comment by jorinvo** [comment]
It makes me sad seeing someone demanding things from open source projects like this without any guilt 😞 

I just recently found caddy and I had a really great experience getting everything up and running.
Just felt like letting you know that there are many silent grateful users out here :blush:
Thank you for all the hard work @mholt! Keep it up!

**Comment by abiosoft** [comment]
I do not see anything wrong with the response that @mholt gave here https://github.com/mholt/caddy/issues/1348#issuecomment-272230578.

The fact that you use Tomcat (or any other technology) quite well neither translates to nor require everyone else to become a Tomcat Pro. Also, this is the probably the first Tomcat issue, and that makes it logical that indeed most Caddy users are not Tomcat users (yet).

How about you share how you currently use Tomcat (or Nginx config if you use it). That will be more beneficial and will help us to help you.

**Comment by aadrian** [comment]
> Why?
> I'd love to see your analysis on this. What's your data source?

was meant to be joke, but it doesn't seems to work :) 

> And yet NGINX Plus is successful.

Companies supporting Apache Httpd are even more successful (and there are many more of them too).
If NginX wouldn't have gone "crippleware", it would have completely replaced Apache Httpd by now.

> Caddy's not "crippleware", as you call it. 

I haven't suggested that it might be :) , but turning a project into one, usually slows completely the adoption rate (despite having the option for extra payed features that otherwise wouldn't even exist).

> I'm appalled that you think that you or any other user of OSS is entitled to a developer's time for free ..
> ... Why should you get it for free? 

That took an unexpected turn :) .

What I wanted to express (but seems to be lost in digitization/translation) is that if a good project project also has good documentation and that "insurance support" is present too, than really there are **no** perceived barriers for companies in adopting that project at a totally different scale :) .
