### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by petey** [mholt/caddy#1351]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.4 
https://hub.docker.com/r/abiosoft/caddy/

### 2. What are you trying to do?
About a month and a half ago, the home automation software I use started using websockets. Since I have caddy setup to terminate tls and act as a reverse proxy for this service, it is broken in 0.9.4 (Should be fixed by PR #1309)

### 3. What is your entire Caddyfile?
```text
redacted.org {
    tls redacted@gmail.com
    errors stderr
    log stdout
}

service.redacted.org {
    errors stderr
    log stdout
    proxy / 192.168.1.36:8123 {
        transparent
        websocket
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
With docker: /usr/bin/caddy -conf\=/etc/Caddyfile -log\=stdout -http2\=false

### 5. What did you expect to see?
websocket connections do not return a 502

### 6. What did you see instead (give full error messages and/or log)?
No errors in logs.
Websocket connections stall. All https connections are ok. 

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Set up home assistant, fronted by caddy with a similar proxy config. https://home-assistant.io/

**Comment by mholt** [comment]
I will get around to it eventually! Releases are half-day projects until the new site is up and running (then it will just be the push of a button).

**Comment by abiosoft** [comment]
@petey does introducing an `edge` or `nightly` version of the docker image makes sense. An image that builds daily or on every push to `master`. 

The caveat is that you aren't guaranteed an iota of stability or up to date documentation. Documentation usually get updated during releases.

**Comment by mholt** [comment]
Also, I thought https://github.com/mholt/caddy/pull/1316 was the fix for Home Assistant?

**Comment by petey** [comment]
@abiosoft Yeah, something like that would be greatly appreciated. I'm fine with accepting the risk of using pre-release software if it is labeled that way. I can always change my docker compose to pull a different label if it doesn't work, and it affects no one but myself.

**Comment by petey** [comment]
@mholt Wasn't aware of that issue. Could be. I haven't had the opportunity to build a docker image from source to test any of this out.

**Comment by petey** [comment]
Yeah, the code that is on master isn't yet enough to get home assistant working again. FWIW, here's the docker image I set up to build the server from source: https://hub.docker.com/r/linuxpete/caddy-from-source/

**Comment by mholt** [comment]
New version going out in a few hours. Thanks!

**Comment by jungle-boogie** [comment]
YEA, thank you @mholt!

**Comment by abiosoft** [comment]
FYI https://hub.docker.com/r/abiosoft/caddy/ also updated to 0.9.5
