### ISSUE TITLE
TestReverseProxy failed on go tip

### ISSUE THREAD

**Issue by tw4452852** [mholt/caddy#1359]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

8464020

### 2. What are you trying to do?

go test github.com/mholt/caddy/caddyhttp/proxy -run=TestReverseProxy$

### 3. What is your entire Caddyfile?

N/A

### 4. How did you run Caddy (give the full command and describe the execution environment)?

N/A

### 5. What did you expect to see?

Test pass

### 6. What did you see instead (give full error messages and/or log)?

--- FAIL: TestReverseProxy (0.00s)
	proxy_test.go:51: Expected to receive trailers
	proxy_test.go:54: Expected header 'X-Trailer' to be proxied properly
	proxy_test.go:51: Expected to receive trailers
	proxy_test.go:54: Expected header 'X-Trailer' to be proxied properly

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Get go tip and test.

**Comment by mholt** [comment]
Thanks for catching this so early!
