### ISSUE TITLE
reserve proxy error

### ISSUE THREAD

**Issue by la0wei** [mholt/caddy#1361]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.4

### 2. What are you trying to do?
Reserver resilio-sync(btsync) web interface with https.

### 3. What is your entire Caddyfile?
abc.xyz.com {
    proxy /sync 0.0.0.0:8888
    root /home/wei/Downloads
    gzip
    browse
    log /var/log/online.log
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemctl start caddy
Ubuntu server 16.04

### 5. What did you expect to see?
1.root directory for https file server
2.resilio web interface with https

want file server and reverse proxy work toghter

### 6. What did you see instead (give full error messages and/or log)?
https://abc.xyz.com/sync   invalid request
https://abc.xyz.com will redirect to https://abc.xyz.com/gui and show 404 not found.

**Comment by mholt** [comment]
Hi, thanks for the issue. Unfortunately I don't know what to do with this, because you did not include any instructions for reproducing it. My inclination right now is to suggest that you inspect your backend and make sure it is working properly; the redirect, for example, is not being done by Caddy with that Caddyfile.

**Comment by la0wei** [comment]
@mholt Hello.
I mean
root /home/wei/Downloads
proxy / 0.0.0.0:8888
these two instructions can't work toghter.they work sepreated alone.
And proxy / 0.0.0.0:8888 works but proxy /sync 0.0.0.0:8888 don't.

**Comment by mholt** [comment]
It could be anything. Try asking on the forums: https://forum.caddyserver.com
