### ISSUE TITLE
Encoded commas (%2C) make proxy omit base directory

### ISSUE THREAD

**Issue by mbirth** [mholt/caddy#1362]
### 1. What version of Caddy are you running (`caddy -version`)?

`0.9.4` (also happened with `0.9.1`)

### 2. What are you trying to do?

Downloading an eBook from my local [COPS](https://github.com/seblucas/cops) instance. The (generated from COPS) URL is:

`https://cops.myserver.com/download/2731/abc%2Cdef.mobi`

### 3. What is your entire Caddyfile?
```text
:80 {
    proxy / http://localhost:81/
    log stdout
    errors stderr
}

cops.myserver.com {
    proxy / http://otherserver:80/cops/ {
        header_upstream Host cops.myserver.com
        header_upstream Scheme https
    }
    log stdout
    errors stderr
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`/usr/sbin/caddy -log stdout -agree=true -email="my@emailaddr.es" -conf="/etc/caddy/Caddyfile" -root=/var/tmp`

Run from systemd as user `www-data`. Also tested it by running as `root` from command line. Same effect.

### 5. What did you expect to see?

A request to `/cops/download/2731/abc%2Cdef.mobi` on the upstream server.

### 6. What did you see instead (give full error messages and/or log)?

A request to `/download/2731/abc%2Cdef.mobi` on the upstream server. Which returns a 404 page.

Caddy shows:

    Jan 18 16:05:37 myserver caddy[15171]: 145.243.xxx.xxx - [18/Jan/2017:16:05:37 +0100] "GET /download/2731/abc%2Cdef.mobi HTTP/2.0" 404 2968

Upstream Apache (`otherserver`) shows:

    127.0.0.1 - - [18/Jan/2017:16:05:37 +0100] "GET /download/2731/abc%2Cdef.mobi HTTP/1.1" 404 2968 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Setup Caddy as a proxy as above. Watch the requests on the upstream server. Experiment with URLs containing `%2C`.

**If I omit the `%2C` from the URL, Caddy queries the correct URL on the upstream server.**

(The `abc%2Cdef` part is irrelevant to COPS, because it only cares about the `2731` and the `.mobi`. If you remove the `%2C`, Caddy queries the correct URL including `/cops` in the front.)

Caddy:

    Jan 18 16:05:52 myserver caddy[15171]: 145.243.xxx.xxx - [18/Jan/2017:16:05:52 +0100] "GET /cops/download/2731/abcdef.mobi HTTP/2.0" 200 271861

Upstream Apache:

    127.0.0.1 - - [18/Jan/2017:16:05:51 +0100] "GET /cops/download/2731/abcdef.mobi HTTP/1.1" 200 1679160 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"

**Comment by julianvmodesto** [comment]
Hi @mbirth, maybe I'm understanding this incorrectly, but the upstream Apache server also returns a 404 when Caddy returns a 404.

Is `request -> Caddy reverse proxy -> Apache` the correct flow? If so, isn't Caddy correctly proxying the 404?

**Comment by mbirth** [comment]
@julianvmodesto Yes, but the upstream Apache returns a 404 because Caddy queries the wrong URI.

Instead of `/cops/download/2731/abc%2Cdef.mobi`, Caddy queries `/download/2731/abc%2Cdef.mobi` on the upstream Apache which causes the 404.

**Comment by mholt** [comment]
Actually this might not be a bug. Change your proxy to:

```
proxy /cops http://otherserver:80 {
```

And see what happens.

**Comment by mbirth** [comment]
@mholt But this would mean I'd have to call it with `https://cops.myserver.com/cops/` from the outside, wouldn't it? That's not what I want.

Just for clarification:

The URL I request from the outside is:

    https://cops.myserver.com/download/2731/abc%2Cdef.mobi

And Caddy **should** query:

    http://otherserver:80/cops/download/2731/abc%2Cdef.mobi

(Which works fine with every other URL not containing `%2C` in it!!)

But instead, Caddy queries:

    http://otherserver:80/download/2731/abc%2Cdef.mobi

which returns the 404.

**Comment by mholt** [comment]
Did you try it? :wink:

**Comment by mbirth** [comment]
@mholt 

I did now. And as expected: Instead of `https://cops.myserver.com/index.php` (which gives a 404 now), I have to use `https://cops.myserver.com/cops/index.php` and thus `/cops/download/...` in the external URL. That's not what I want.

And as I said earlier: Caddy proxies everything just fine with my previous setting, unless the URL contains `%2C`.

**Comment by mholt** [comment]
Oh, I see what you mean. So if you take the comma (%2C) out, it works fine. That probably is a bug.

**Comment by mbirth** [comment]
Exactly! :+1:

To sum up:

URLs without comma
==============

Query from outside:

    https://cops.myserver.com/download/2731/abcdef.mobi

Query from Caddy to Upstream:

    http://otherserver:80/cops/download/2731/abcdef.mobi
                          ^^^^

Result: File downloads, everything :ok: 


URLs WITH comma
============

Query from outside:

    https://cops.myserver.com/download/2731/abc%2Cdef.mobi

Query from Caddy to Upstream:

    http://otherserver:80/download/2731/abc%2Cdef.mobi
                          ^^^^ missing!!

Result: 404 :no_entry_sign:

**Comment by tw4452852** [comment]
Please check the latest master to confirm the problem is fixed. Thanks.
