### ISSUE TITLE
Unable to download custom builds with hugo plugin included

### ISSUE THREAD

**Issue by curioussavage** [mholt/caddy#1367]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.4

### 2. What are you trying to do?
download the latest version with the many plugins including hugo (Linux 64bit)

### 3. What is your entire Caddyfile?
NA

### 4. How did you run Caddy (give the full command and describe the execution environment)?

NA
### 5. What did you expect to see?
I just want the latest version.

### 6. What did you see instead (give full error messages and/or log)?
```
Error:

Sorry about that. You can try again or download Caddy core from our backup site (without any extra features).
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Just go try to make a build, select Hugo and try linux 64 bit, I only tried that platform

apologies if this is the wrong place. I assume the hugo plugin has an issue with the latest version of caddy but it is breaking builds of caddy on the site.

**Comment by mholt** [comment]
Yes, the hugo plugin is broken right now. /cc @hacdias. This is not a caddy issue so I'm closing this, but we'll get it fixed in the next day or two. Sorry about that.
