### ISSUE TITLE
FastCGI POST requests body always empty when QUIC is enabled

### ISSUE THREAD

**Issue by ghyster** [mholt/caddy#1370]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.4

### 2. What are you trying to do?
use fastcgi and quic

### 3. What is your entire Caddyfile?
```text
  root /srv/default
  gzip

  log stdout
  errors stdout

  fastcgi / php7:9000 php
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/bin/caddy -quic --conf /etc/Caddyfile --log stdout

environment :
- one docker container for caddy
- one docker container for php

### 5. What did you expect to see?
I expected every requests to work

### 6. What did you see instead (give full error messages and/or log)?
POST requests are not transmitted correctly to the php server, the request body is always empty.
GET requests work
POST requests work when quic is disabled 

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
create a docker container for caddy with quic enabled
create another docker container for php
create a Caddyfile like the one I've provided
create a php file on the php container that prints the $_POST array and make a POST request to that script

**Comment by tobya** [comment]
I have been running php fastCGI with QUIC on Windows for several months without this issue.  Perhaps it is some issue with system setup

**Comment by Henrocker** [comment]
Exact same problem here: when using TLS, POST body gets filled by requests but with QUIC enabled, Caddy even crashes and restarts only because my caddy.service file inculdes: `Restart=on-failure`. 

In my configuration I am accessing over https.

**Comment by marten-seemann** [comment]
I'm not very familiar with the fastCGI module in Caddy, but maybe this could be related to https://github.com/lucas-clemente/quic-go/issues/405. I just fixed this bug, so if anyone could rebuild Caddy with the current `master` of quic-go, this would be very helpful.

@Henrocker: Can you please provide us a stack trace (preferably in a new issue in quic-go)?

**Comment by Henrocker** [comment]
@marten-seemann That is the stack trace i get:
panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody

```goroutine 13 [running]:
panic(0xbda020, 0xc420049800)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc420256a00, 0xc420422280, 0xc420ab3a40, 0x0, 0x104df20, 0xc420001380)
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x17c
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
        /home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x628```

I guess it is the same as your linked issue at quic-go.

**Comment by marten-seemann** [comment]
Yes, this was [quic-go#405](https://github.com/lucas-clemente/quic-go/issues/405).
Is the POST body correctly filled using QUIC now?

**Comment by Henrocker** [comment]
I could tell you if I knew how to build the current master of Caddy against the current quic-go library.

Could you tell please?

**Comment by mholt** [comment]
@Henrocker Assuming you have Go installed:

```
go get -u github.com/mholt/caddy/caddy
```

That should update Caddy and all its dependencies including quic-go to the latest. Then cd into the $GOPATH/src/github.com/mholt/caddy/caddy folder and run `go run main.go`.

**Comment by Henrocker** [comment]
Thanks for your help @mholt. I managed to recompile caddy and now caddy does not crash anymore when using POST. However, if I'm testing my little mini Speedtest [over here](https://henrock.net/speedtest), the Upload does not really work when QUIC is enabled.

When QUIC is disabled, Upload works properly.

**Comment by mholt** [comment]
That's good. If you can provide more details on what "does not really work" means, that would be helpful. It looks like you're using Flash (:confused:) -- that might be a separate issue entirely... I suspect this issue is now fixed, though -- thanks to @marten-seemann! So I will close this issue.
