### ISSUE TITLE
Roll all logs by default - no configuration for rolling

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#1372]
I can't think of a reason why log files shouldn't be rolled (renamed when they get large, then begin writing to a new file in its place). Caddy does this for the process log by default with no way to configure its rolling, and I've _never_ heard a single complaint about not being able to disable or change that.

So, log files should be rolled. Should the rolling be configurable?

Right now, to do this, you have to do something like:

```plain
example.com {
     log access.log {
          rotate {
             size 100
             age  14
             keep 10
         }
     }
     errors {
         log error.log {
             size 100
             age  14
             keep 10
         }
     }
}
```

This is tedious, and this is the _only_ nested block is valid Caddyfile syntax. One of the beauties of the Caddyfile is that it's shallow: at most only two levels of indentation are needed, unless you roll your logs. We have really hacky code in the parser that enables an extra level of indentation for this rotation configuration but it was just experimental. I don't like it (but thank you to who implemented it!).

Nearly all Caddyfiles I see that enable log rolling use the default values as given in the docs. I think they're pretty sensible values, and it doesn't look like anyone is changing them.

I vote to roll all logs by default and just remove the rolling configuration from the Caddyfile. Any opposed? Anyone want to submit a pull request? I don't think this will be too difficult. You mostly get to rip out some code, with only a little refactoring needed.

**Comment by wmark** [comment]
If your *log file* is a *FIFO special file* indeed you don't want any rolling, or the option to disable it. And no `O_CREATE | O_TRUNC` or the like on it.

**Comment by mwpastore** [comment]
I basically agree with you, but I feel the defaults are too low. I personally like to keep my access logs for six months for analysis. Will I still be able to configure it?

**Comment by mholt** [comment]
@wmark Right, this applies only to files on disk.

@mwpastore I wasn't planning on it (lower surface area for complexity, is kinda appealing) but if we had to make it configurable, perhaps no nesting, just new subdirectives for log and errors directives:

```plain
log access.log {
    # prefix with "log" because it'll be the same in the "errors" directive or others that open logs?
    log_size 100MB
    log_age 14d
    log_keep 10
}
```

What if we set the log age to 90 days? Or we could do 6 months if it's not too long for most servers...

**Comment by mwpastore** [comment]
My vote's for the flattened subdirectives!

**Comment by mholt** [comment]
Maybe they should instead be:

```plain
rotate_size
rotate_age
rotate_keep
```

Which is still descriptive and pretty easy to remember, without being redundant.

Would anyone like to whip up a PR?

**Comment by julianvmodesto** [comment]
I'm new! Would love to volunteer to submit a PR for this.

Looks like the plan is:

- rip out nested block parsing
- add new subdirectives + share between logging middleware
- set defaults to rotate logs

**Comment by mholt** [comment]
@julianvmodesto Ding ding ding! You got it. Right now, the `httpserver` package has a [`ParseRoller()`](https://godoc.org/github.com/mholt/caddy/caddyhttp/httpserver#ParseRoller) function you could adopt to the flattened subdirectives, but you can't assume they are next to each other... which makes parsing it quite interesting, now that I think about it. We might have to change it up slightly so that either there is a single `rotate` or `rotate_log` subdirective that contains all 3 values on the same line (kinda unwieldy though), or maybe come up with some other hack :smile: Oh well. Let's cross that bridge when we come to it. Feel free to ask here if you get stuck.

@mwpastore How much do you really require customizing it, if we choose generous defaults?

**Comment by mwpastore** [comment]
I'm flexible, although I suspect what works for me isn't going to work for the next guy or gal.

**Comment by recollir** [comment]
Since work is going to be done on the logs I would rather like to see an option to rotate logs by age/time rather than by size. Something like

rotate_intervall 1h
rotate_intervall 1d
rotate_intervall 1w

Or perhaps even

rotate size 100
rotate intervall 1d

to allow for both option.

**Comment by mholt** [comment]
@natefinch has good reasons for not implementing rotation by age. If you want that, use a specialized tool for it. The point of rotation is to limit disk usage.

**Comment by recollir** [comment]
Fair enough, @mholt.

**Comment by julianvmodesto** [comment]
Opened #1379. For now, I went with the 3 separate subdirectives instead of the single rotate or rotate_log subdirective that contains all 3 values, but open for comments.

```
rotate_size
rotate_age
rotate_keep
```
