### ISSUE TITLE
Docker container - Caddy + php-fpm and docker network, not working.

### ISSUE THREAD

**Issue by SanderV1992** [mholt/caddy#1383]
Can't make caddy working with php-fpm, when I use own network. This works only if I use host network **--net=host**, also I tried same with nginx, I created own network and everything worked fine, why then caddy don't want work, everything is very similar.

**Caddy:**
`docker run -it --net caddy_network -p 80:80 -p 443:443 -v /etc/caddy/:/etc/caddy/:ro -v /srv/default/:/srv/default:ro --name caddy registry.gitlab.com/container_images/caddy`

**Сonfig file:**
```
caddy-test.ee:80 {
	root /srv/default/

	ext .htm .html .php

	fastcgi / php-fpm:9000 php {
	    index index.php
	}

	rewrite {
		to {path} {path}/ /index.php?{query}
	}
}
```

-----------------

**Php-fpm:**
`docker run -it --net caddy_network -v /srv/default/:/srv/default:ro --name php-fpm registry.gitlab.com/container_images/php-fpm
`

**Nginx:**
`docker run -it --net caddy_network -p 80:80 -p 443:443 -v /etc/nginx/default.conf:/etc/nginx/nginx.conf:ro -v /srv/default/:/srv/default:ro --name caddy nginx`

**Config:**
```
events {
    worker_connections  1024;
}

http {
    server {

        listen 80;
        server_name caddy-test.ee;

        root /srv/default;
        index index.php index.html;

        location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass php-fpm:9000; 
            fastcgi_index index.php;
            fastcgi_next_upstream error timeout;
            fastcgi_keep_conn on;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME $fastcgi_script_name;
            fastcgi_hide_header "X-Powered-By";
            include fastcgi_params;
        }

    }
}
```

**Php-fpm:**
`docker run -it --net caddy_network -v /srv/default/:/srv/default:ro --name php-fpm registry.gitlab.com/container_images/php-fpm`

**Comment by mholt** [comment]
Hey @SanderV1992, thanks for posting your question. However, since this seems more like a question about using Caddy with Docker and PHP-FPM, and is not a bug report with Caddy, can I suggest that you post this on the forum? https://forum.caddyserver.com - more people who know how to use Docker and PHP-FPM will be able to help you. :)

**Comment by SanderV1992** [comment]
Thank you

**Comment by SanderV1992** [comment]
This solution works, need write ip manually:

docker run -d --net caddy_network --ip 172.18.0.3 -p 80:80 -p 443:443 -v /etc/caddy/:/etc/caddy/:ro -v /srv/default/:/srv/default:ro --name caddy registry.gitlab.com/container_images/caddy

docker run -d --net caddy_network --ip 172.18.0.2 --expose 9000 -v /srv/default/:/srv/default/:ro --name php-fpm registry.gitlab.com/container_images/php-fpm

```
fastcgi / 172.18.0.2:9000 php {
    index index.php
}
```

**Comment by reefki** [comment]
Old issue but got the same problem recently, I resolve this by changing the `listen` IP of php-fpm www pool config to 0.0.0.0:9000 from 127.0.0.1:9000
