### ISSUE TITLE
Error in Documentation for Multipass

### ISSUE THREAD

**Issue by fey0** [mholt/caddy#1386]
There are two mistakes in the multipass documentation at https://caddyserver.com/docs/multipass .

The examples at the bottom are missing their < and > at "mail_from".
It is included in one of the three examples, but missing in the other two.
It should be:     `mail_from "Multipass <no-reply@dallas>"`

Not including these will have caddy not start and throw an error. 

I wasnt sure where to report this. Whether here, the multipass github or somewhere else. Sorry if its wrong.

**Comment by mholt** [comment]
Thanks for reporting this @fey0, even if it is in the wrong place. :wink: For future reference, there's a link on that page in the green box that shows you where to report bugs with the plugin. :)

Pinging @namsral

**Comment by fey0** [comment]
Wasnt a bug with the plugin itself, thats why I was unsure. No idea if @namsral himself is managing the documentation on the caddy site. But thanks :) 

Great job on caddy, btw. Replaced nginx on all my servers. Love the caddyfile

**Comment by mholt** [comment]
Thanks. Yeah, the docs are in https://github.com/caddyserver/caddyserver.com but that will be changing soon. :+1:
