### ISSUE TITLE
Docker - caddy + php-fpm, network problem.

### ISSUE THREAD

**Issue by SanderV1992** [mholt/caddy#1387]
I am using Docker with [caddy + php-fpm] containers, where I created own network. Network name is **wordpress_net**.
Why on nginx it's works fine, but on caddy, I have this strange problem with this configuration.

**I need use this**
[container_name].[network_name]
php-fpm.wordpress_net

```
  fastcgi / php-fpm.wordpress_net:9000 php {
      index index.php
  }
```

---

**Instead of this**
php-fpm

```
  fastcgi / php-fpm:9000 php {
      index index.php
  }
```

------------------------------------------------------------------
_for nginx and other soft, enough just write php-fpm._

**Example:**
root@69f36ea04b37:/srv/default# getent hosts php-fpm
172.18.0.3      php-fpm

root@69f36ea04b37:/srv/default# getent hosts php-fpm.wordpress_net
172.18.0.3      php-fpm.wordpress_net

=======

It's strange, why this not working with php-fpm?

**My tests:**
1)
Nginx + php-fpm (separate containers) in host network - works fine 
Caddy + php-fpm (separate containers) in host network - works fine 
2)
Nginx + php-fpm (separate containers) in my custom network "wordpress_net" - fine 
Caddy + php-fpm (separate containers) in my custom network "wordpress_net" - fail

**Comment by krishamoud** [comment]
Just for clarity.

Are you running in swarm mode with an overlay network?  If so, is it swarm 1.12 or greater?  

Could you share the dockerfile(s) and docker run commands and/or docker-compose template?

**Comment by SanderV1992** [comment]
no it's not swarm, it's just 1-one server, with 3 containers.

**Comment by SanderV1992** [comment]
I did more test and find something strange, but now I confused (I use CentOS on my VM): 
1)
_fastcgi / php-fpm:9000 php {_
 on local (dev) docker-compose **works** 
 on stage(VM) docker-compose **fail** 

2)
_fastcgi / php-fpm.wordpress_net:9000 php {_
 on local (dev) docker-compose **fail** 
 on stage(VM) docker-compose **works**

**Comment by mholt** [comment]
This may be better suited for our forum, since I'm not sure/convinced it's a bug in Caddy itself, might just be a misconfiguration of a Docker container or something. Feel free to ask here: https://forum.caddyserver.com - where the container gurus tend to hang out more!
