### ISSUE TITLE
detectable latest version

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#139]
There needs to be a way for scripts to determine which caddy is the latest by architecture.

maybe something like https://caddyserver.com/dist/armv6l-hf/latest which would be a file that has no newlines or anything, just `v0.7.1` or `0.7.1`.

It's important that this can be done by architecture because there will be bugs in golang that affect one arch but not another or it will be difficult to build on an architecture for some particular feature and so the versions will become out-of-sync.

**Comment by coolaj86** [comment]
Here's how node (meaning io.js) does it:

https://iojs.org/dist/

https://iojs.org/dist/latest/

https://iojs.org/dist/index.tab

https://iojs.org/dist/index.json

**Comment by mholt** [comment]
How about this for now: https://api.github.com/repos/mholt/caddy/releases/latest - use the `tag_name` field. (Or if all you need is an ID, use the `id` field.)
