### ISSUE TITLE
quic-go panics when loading web pages over QUIC

### ISSUE THREAD

**Issue by hansfilipelo** [mholt/caddy#1393]
### 1. What version of Caddy are you running (`caddy -version`)?

Compiled from source,  `(untracked dev build)` as well as `0.9.5`.

### 2. What are you trying to do?

Serve web pages over QUIC.

### 3. What is your entire Caddyfile?
```text
$hostname:443
root $webRoot
gzip
log $logFolder/caddy.access.log
errors $logFolder/caddy.error.log

tls $certFolder/cert.pem $certFolder/key.pem {
	protocols tls1.2 tls1.2
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -quic -conf="a_folder/config/netem.Caddyfile" -pidfile="a_pidfile"

### 5. What did you expect to see?

Caddy serving web pages without crashing, as it does with the same settings but using HTTP/1.1 or HTTP/2. This issue should be fixed within quic-go according to this issue: https://github.com/lucas-clemente/quic-go/issues/405

### 6. What did you see instead (give full error messages and/or log)?
```
panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody

goroutine 790 [running]:
panic(0x9ca1c0, 0xc420932900)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc420217d00, 0xc420984fa0, 0xc42098c000, 0x0, 0xd1e3a0, 0xc42011c4e0)
	/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x17c
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
	/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x628
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Load web pages over QUIC continuously (happens on many different web pages). I'll attach a list of my test domains that I've scraped and are serving as static content with Caddy. 
[urls.txt](https://github.com/mholt/caddy/files/744172/urls.txt)

**Comment by Henrocker** [comment]
Do `go get github.com/mholt/caddy/caddy`,

then `cd $GOPATH/src/github.com/mholt/caddy/caddy`

then `./build.bash`

then take the binary from `$GOPATH/bin` and run it again with QUIC.

The error should no longer disappear.

**Comment by hansfilipelo** [comment]
The error was that I, in my script, initialized a subshell where $GOPATH/bin wasn't in path. Sorry for bothering you @Henrocker and thanks for your quick response.

**Comment by mholt** [comment]
Thanks @Henrocker for helping out! Glad you got it resolved Hans.

**Comment by elvizlai** [comment]
@Henrocker  I follow the instruction to build and run.
It turned out `no action found for directive 'cors' with server type 'http' (missing a plugin?)`

So, any doc or script about self-build caddy with plugin?

**Comment by Henrocker** [comment]
@elvizlai before running my mentioned commands for rebuilding caddy, you will need to include the cors plugin into the `$GOPATH/src/github.com/mholt/caddy/caddy/caddymain/run.go` under the import block like this:

```
import (

...

github.com/captncraig/cors
```

**Comment by vladbondarenko** [comment]
# go get github.com/mholt/caddy/caddy
package context: unrecognized import path "context" (import path does not begin with hostname)
#

cant compile package. can you plz check how to fix it?

**Comment by mholt** [comment]
You need Go 1.8 ;)
