### ISSUE TITLE
Show where certs will be written?

### ISSUE THREAD

**Issue by ramontayag** [mholt/caddy#1394]
I got stuck in a [silly predicament](https://forum.caddyserver.com/t/staging-saving-certificates/1385/4) for longer than I care to admit, and I was thinking, printing where the certs will be written during bootup would have helped me. What do you think?

**Comment by mholt** [comment]
Yeah, I've been wanting to add a sort of debug log mode for things like this. Thanks for the suggestion!

**Comment by tobya** [comment]
@mholt When you have time if you would like to elaborate on thoughts of how you would like a debug log to be implemented.
