### ISSUE TITLE
maxrequestbody has no effect

### ISSUE THREAD

**Issue by xrstf** [mholt/caddy#1395]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Limit the size of request bodies for my application to 64KB on all routes except for ``/upload``, which should be allowed to receive 10MB. For this test however, the goal is to limit all incoming request bodies to 2,000 bytes (for simplicity sake).

### 3. What is your entire Caddyfile?
```text
:8000 {
  maxrequestbody 2000
}
```

(I tried ``2000``, ``2000B`` and ``2KB``.)

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Linux amd64 binary (no plugins, downloaded from Github releases) on Ubuntu 16.10 Mate, running on zsh. Simple caddyfile in an empty directory, then calling

    $ caddy
    Activating privacy features... done.
    http://:8000
    WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".

to start the caddy binary in ``~/bin``.

For testing purposes, I have a 12KB text file called [dummy.txt](https://github.com/mholt/caddy/files/745965/dummy.txt) with pseudo random data to prevent gzip from interferring.

Then I'm using cURL to perform a simple POST request with the file content (with should not be a file upload, but a normal text field):

    $ curl -v --data "foo=$(cat dummy.txt)" http://localhost:8000/

### 5. What did you expect to see?
a HTTP 413 error

### 6. What did you see instead (give full error messages and/or log)?
    $ curl -v --data "foo=$(cat dummy.txt)" http://localhost:8000/
    *   Trying 127.0.0.1...
    * Connected to localhost (127.0.0.1) port 8000 (#0)
    > POST / HTTP/1.1
    > Host: localhost:8000
    > User-Agent: curl/7.50.1
    > Accept: */*
    > Content-Length: 12003
    > Content-Type: application/x-www-form-urlencoded
    > Expect: 100-continue
    > 
    * Done waiting for 100-continue
    * We are completely uploaded and fine
    < HTTP/1.1 404 Not Found
    < Content-Type: text/plain; charset=utf-8
    < Server: Caddy
    < X-Content-Type-Options: nosniff
    < Date: Wed, 01 Feb 2017 19:52:25 GMT
    < Content-Length: 14
    < 
    404 Not Found
    * Connection #0 to host localhost left intact

Note the ``Content-Length`` header showing that 12KB of data are actually sent.

**Comment by Henrocker** [comment]
It seems like, according to the documentation, you did not set a path for maxbodyrequest to operate in, but for me it worked to set the full path inner the site configuration.
So instead of:

`:8000 {
  maxrequestbody 2000
}
`
Try: 

`:8000 {
  maxrequestbody / 2000
}
`

**Comment by xrstf** [comment]
The documentation states that the path is optional: https://caddyserver.com/docs/maxrequestbody

I tried setting ``maxrequestbody / 2000``, but it also has no effect.

**Comment by Henrocker** [comment]
Ohh Okay... sorry, didn't notice that.

**Comment by mholt** [comment]
Thanks for the detailed issue, @xrstf! I do not think this is a bug, though. The request body is only read if needed, you have no other directives in your Caddyfile that would cause the request body to be read (e.g. fastcgi or proxy or log or something like that). The 413 error will appear on the occasion that the request body is read and is found to be too large.
