### ISSUE TITLE
Missing hyphen in common log format

### ISSUE THREAD

**Issue by thomasheller** [mholt/caddy#1398]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
I'd like Caddy to log access attempts to a file, using the Common Log Format.

### 3. What is your entire Caddyfile?
```text
localhost

log
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy` (on Linux, using a binary downloaded from caddyserver.com without extra features)

### 5. What did you expect to see?

In file `access.log`:

```
::1 - - [03/Feb/2017:11:32:57 +0100] "GET / HTTP/1.1" 404 14
::1 - - [03/Feb/2017:11:32:57 +0100] "GET /favicon.ico HTTP/1.1" 404 14
```

According to the Caddy docs (https://caddyserver.com/docs/log), the default log format is Common Log Format.

According to [NCSA docs](http://publib.boulder.ibm.com/tividd/td/ITWSA/ITWSA_info45/en_US/HTML/guide/c-logs.html#common), the commong log format fields are as follows:

1. IP address of remote host
1. user-identifier according to identd (if available)
1. user-identifier according to HTTP authentication (if available)
1. date, time, time zone
...

This is also how Apache (https://httpd.apache.org/docs/2.4/logs.html#accesslog) and IIS (https://www.iis.net/configreference/system.applicationhost/sites/site/logfile) describe the common log format.

### 6. What did you see instead (give full error messages and/or log)?
```
::1 - [03/Feb/2017:11:32:57 +0100] "GET / HTTP/1.1" 404 14
::1 - [03/Feb/2017:11:32:57 +0100] "GET /favicon.ico HTTP/1.1" 404 14
```

Note that the second hyphen is missing in both lines. This is due to how the constant `CommonLogFormat` is defined in [`caddyhttp/log/log.go`](https://github.com/mholt/caddy/blob/v0.9.5/caddyhttp/log/log.go). The second hyphen is also missing in the [Caddy docs](https://caddyserver.com/docs/log).

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Run Caddy in an otherwise empty directory, containing the above Caddyfile.

**Comment by tobya** [comment]
I'm not sure whether caddy has the values for user-identifier according to identd or even user-identifier according to HTTP authentication (presumabley using basicauth plugin)

Do you need these values if they exist or simply the additional - ?

@mholt what is your opinion on this issue?  I cant see a {user} or {>user} placeholder.  We could add the additonal -  (the first one simply seems to be [added in](https://github.com/mholt/caddy/blob/v0.9.5/caddyhttp/log/log.go#L85)  or make it clear that the common log format is not "common"

**Comment by thomasheller** [comment]
@tobya Additional "-" would be fine, this is just for compatibility with parsing "Common Log Format" logs.

**Comment by mholt** [comment]
Can't believe I missed this somehow -- nobody reported it? 🤔 Thanks!
