### ISSUE TITLE
tar.gz versions for *nix / *bsd

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#140]
`zip` and `unzip` aren't always included on *nix and *bsd systems, but `tar` and `guzip` almost always are (except maybe on busybox systems).

For automating the install process it's important to have `.tar.gz` packages.

We could just ship the bin without packaging it in .tar.gz or .zip at all, but I think in the future we may want to have custom files / templates for things like the directory listing and meta redirects, which would need to go into `/usr/local/share/caddy` or similar.

**Comment by mholt** [comment]
Good point, .tar.gz for the Linux and BSD distributions makes more sense. I'll keep this open until I make the changes in dist/automate.sh.

**Comment by mholt** [comment]
Got this working on the build server locally, will update automate.sh next. Right now it assumes .tar.gz for linux, freebsd, and openbsd, and .zip for all the others.

@coolaj86 and @abiosoft - do you think it is necessary to add a query string parameter to the endpoint to allow people to force either format?

**Comment by mholt** [comment]
Okay, well, this will be available at the next release which is any day now.
