### ISSUE TITLE
build.bash does not work in releases

### ISSUE THREAD

**Issue by bsiegert** [mholt/caddy#1405]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 2. What are you trying to do?

I downloaded the release tarball. Now I am trying to build caddy (in order to package it).

### 5. What did you expect to see?

I expected `caddy/build.bash` to run the build.

### 6. What did you see instead (give full error messages and/or log)?

```
$ ./build.bash 
fatal: No names found, cannot describe anything.
$ bash -x build.bash 
+ set -euo pipefail
+ :
+ :
+ :
+ : .
+ pkg=github.com/mholt/caddy/caddy/caddymain
+ ldflags=()
+ name=github.com/mholt/caddy/caddy/caddymain.buildDate
++ date -u '+%a %b %d %H:%M:%S %Z %Y'
+ value='Mo Feb 06 15:23:17 UTC 2017'
+ ldflags+=("-X" "\"${name}=${value}\"")
+ name=github.com/mholt/caddy/caddy/caddymain.gitTag
+ set +e
++ git -C . describe --exact-match HEAD
+ value=
+ set -e
+ ldflags+=("-X" "\"${name}=${value}\"")
+ name=github.com/mholt/caddy/caddy/caddymain.gitNearestTag
++ git -C . describe --abbrev=0 --tags HEAD
fatal: No names found, cannot describe anything.
+ value=
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

1. Download and extract release tarball.
2. `cd caddy; ./build.bash`

**Comment by mholt** [comment]
Hmm, it requires the git repository to be pulled... including all the tags. I'm not really sure what else would be causing that. Did you do a git fetch?

**Comment by bsiegert** [comment]
No. I downloaded the source code archive. As far as I can tell, it does not
contain any git metadata (and it should not).

Matt Holt <notifications@github.com> schrieb am Mo., 6. Feb. 2017, 17:32:

**Comment by mholt** [comment]
Okay, gotcha. You'll need the git repository in order for build.bash to succeed, because it needs to embed version information.

If you don't need the version information (I don't recommend this, but to each their own), you can just run `go build`.

**Comment by bsiegert** [comment]
But that is exactly what I complained about in the first place. When you download a release tarball, it does not contain the git metadata. So perhaps `build.bash` could skip embedding that information and print a warning (which would amount to it running `go build`).

**Comment by mholt** [comment]
Build.bash is being replaced in a few weeks or a couple months with a Go script anyway, and you're the only one I know of as of yet who has this complaint (most people use go get or git clone), so I'm not going to spend time changing it. Thanks though!
