### ISSUE TITLE
cors and quic panic when using chrome

### ISSUE THREAD

**Issue by elvizlai** [mholt/caddy#1406]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.4

### 2. What are you trying to do?
config cors and start caddy with -quic 
using chrome to visit will cause panic. 
safari work well because it not support quic.
run without -quic flag, chrome works.

### 3. What is your entire Caddyfile?

```
cors /api {
        origin            *
        methods           GET,POST,OPTIONS
        allow_credentials true
        max_age           3600
        allowed_headers   DNT,X-Mx-ReqToken,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization
        exposed_headers   exposedHeaders
    }
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
using -quic flag

### 5. What did you expect to see?
cors works well

### 6. What did you see instead (give full error messages and/or log)?
panic

```
panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody

goroutine 109 [running]:
panic(0x1c834c0, 0xc4204da000)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc4203256c0, 0xc420453360, 0xc42043c0f0, 0x0, 0x2b5d580, 0xc4200c3520)
	/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x17c
created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
	/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x628
Activating privacy features... done.
```

**Comment by tw4452852** [comment]
Duplication of issue #1393.

**Comment by elvizlai** [comment]
@tw4452852  I think it maybe re-open, I downloaded from caddyserver.com, it does not work.

**Comment by mholt** [comment]
The issue is resolved, the build server just needs to be updated... which I have to do manually. I'll get around to it eventually. Sorry :-/

**Comment by elvizlai** [comment]
@mholt  Is this solved if I download the newest bin file from caddyserver.com?

**Comment by mholt** [comment]
Sorry, haven't gotten around to it yet.

The joys of old infrastructure. I'm putting more effort into the replacement.
