### ISSUE TITLE
No server types plugged in when trying to embed caddy in go program

### ISSUE THREAD

**Issue by mahaben** [mholt/caddy#1407]
Here is my code:

	caddy.AppName = "Sprocket"
	caddy.AppVersion = "1.2.3"

	caddyfile, err := caddy.LoadCaddyfile("http")
	if err != nil {
		log.Fatal(err)
	}

	instance, err := caddy.Start(caddyfile)
	if err != nil {
		log.Fatal(err)
	}

	instance.Wait()

And my caddyfile is as following:

localhost:8080

Thanks,

**Comment by mahaben** [comment]
Solved it. Need to add  import _ "github.com/mholt/caddy/caddyhttp"

Can you update the example please?

Thanks,

**Comment by mholt** [comment]
Good point -- done.
