### ISSUE TITLE
index not found, 502 Bad Gateway

### ISSUE THREAD

**Issue by aliefarlingga** [mholt/caddy#141]
I'm sorry if my problem has been issued before.
But I have this kind of problem...

I want my web server redirect automatically to index php, so here's my "Caddyfile"

==================================================
localhost:80
log log/access.log
errors log/error.log
#tls certs/self.crt certs/self.key

fastcgi / 127.0.0.1:9000 php {
        ext .php
        index index.php
}
==================================================

But when i tried to access "localhost" from my Chrome, the output is "502 bad gateway".
Then i tried to access "localhost/index.php", the output is still the same.

But when I change it into "index index.html", it redirect itself automatically to index.html

Here is the log error : 
[ERROR 502 /] malformed MIME header line: Access to the script '/home/alief/Downloads/caddy' has been denied (see security.limit_extensions)
[ERROR 502 /favicon.ico] malformed MIME header line: Access to the script '/home/alief/Downloads/caddy/favicon.ico' has been denied (see security.limit_extensions)

Any leads or information would be so helpful for me, thanks :)

**Comment by aliefarlingga** [comment]
I'm sorry I just found my mistake. 

It's just the configruation.

=====================================
localhost:80
log log/access.log
errors log/error.log
tls certs/self.crt certs/self.key
#fastcgi / 127.0.0.1:9000
fastcgi / 127.0.0.1:9000 {
        ext .php
        split.php
        index index.php
}
====================================

well i just erase the [preset] and it's working, thanks :)

**Comment by abiosoft** [comment]
Glad to hear that. If you are sure it now works as expected, you can close this issue.

Thanks.

**Comment by abiosoft** [comment]
There is a typo in your config. `split.php` should be `split .php`. This issue still exists but a fix is on the way.
