### ISSUE TITLE
Caddy times out proxied websocket connections despite data being passed

### ISSUE THREAD

**Issue by benpye** [mholt/caddy#1416]
With the new `timeouts` directive in Caddy, proxied websocket connections are also affected. This is problematic for applications such as quassel-webserver which uses the Websocket connection for a constant stream of messages.

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Provide a reverse proxy in front of quassel-webserver

### 3. What is your entire Caddyfile?
```text
https://domain {
    tls email {
        dns cloudflare
    }

    proxy / quassel-webserver:64080 {
        transparent
    }

    proxy /p/socket quassel-webserver:64080 {
        websocket
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy --conf /etc/Caddyfile --log stdout --agree`

Within an Alpine Linux docker container.

### 5. What did you expect to see?
Expected quassel-webserver to function behind the reverse proxy.

### 6. What did you see instead (give full error messages and/or log)?
quassel-webserver works fine for 10 seconds then times out.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Run a long running websocket server behind caddy, such as https://github.com/gorilla/websocket/tree/master/examples/chat . The application should time out if affected the same. Only application I know 100% is affected is quassel-webserver.

**Comment by benpye** [comment]
I am aware this is very similar to https://github.com/mholt/caddy/issues/1384 however even when data is passed should the websocket be timing out? Quassel provides a heartbeat every 30s but extending the timeouts to a value greater than that is not sufficient unfortunately.

**Comment by mholt** [comment]
Hi Ben, thanks for the issue and following the format.

> even when data is passed should the websocket be timing out?

Yes, because attackers will pass data slowly intentionally to drain system resources. You should disable timeouts or lengthen them if you do not want to be protected from these kinds of attacks.
