### ISSUE TITLE
Markdown ext directive applies across all markdown blocks for server

### ISSUE THREAD

**Issue by tobya** [mholt/caddy#1419]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

0.9.5
### 2. What are you trying to do?

Use a different extension for md in different folders

### 3. What is your entire Caddyfile?
```text
aubergine.kinchik.ie:80 {
    root d:\caddy\webroot\mdissue
    markdown /md {

    ext .html

    }

    markdown /mdmd {
     ext .md
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
 > caddy -conf=d:\godev\bin\caddymd.txt -log stdout

### 5. What did you expect to see?

I expected to see http://aubergine.kinchik.ie/mdmd/file.md rendered as markdown

### 6. What did you see instead (give full error messages and/or log)?

>  http://aubergine.kinchik.ie/mdmd/file.md rendered as html 

however
 
>  http://aubergine.kinchik.ie/mdmd/file.html is rendered as markdown.

The ext used in the first markdown block applies to all markdown blocks.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
use supplied caddyfile

### Discussion :

I'm not sure if this bug needs to be fixed or just the documentation updated to indicate that this is the case.  It is reasonably unlikely that someone requires that 2 seperate and non transferable ext be used.

If #1418 was fixed this could simply be documented.

**Comment by mholt** [comment]
Hmm, so was this fixed @tobya? The other issue is closed...

**Comment by tobya** [comment]
@mholt yes this appears to have been fixed.
