### ISSUE TITLE
your installer script, sir

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#142]
https://github.com/coolaj86/caddy-install-script

On OS X and most *nixes:

```bash
curl -fsSL bit.ly/install-caddy | bash
```

On Ubuntu and minimal *nix installations:

```bash
wget -nv bit.ly/install-caddy -O - | bash
```

I think it'll work on all existing supported OSes and platforms except arm

We still need:
* `caddy_linux_armv6l-hf.zip`
* `caddy_linux_armv6l.zip`
* `caddy_freebsd_armv6l-hf.zip`
* `caddy_freebsd_armv6l.zip`

**Comment by mholt** [comment]
Cool! I've been working on lots of deployment/ops stuff lately, so I'll come back to this when I'm ready to use it.

**Comment by mholt** [comment]
Ported it to getcaddy.com for some trial runs. Thanks!
