### ISSUE TITLE
needs better explanation of http2 support

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#144]
To me http2 means these things:
* mandatory TLS
* mandatory gzip (or is it snappy?)
* script, link, and img tags are preparsed such that the content is sent via push along with the initial request.

What does caddy mean by http2 support?

**Comment by jaredfolkins** [comment]
Http2 is the new binary HTTP protocol. It is thoroughly defined.

https://http2.github.io/http2-spec/

Does this help?
Jared

**Comment by coolaj86** [comment]
No.

I know what http2 is (more or less).

I want to know what subset of http2 caddy supports.

There are a million things that http2 does that caddy may or may not be taking advantage of. I want to know what parts of the http2 spec caddy is implementing.

**Comment by mholt** [comment]
Caddy uses [bradfitz/http2](https://github.com/bradfitz/http2) as its HTTP/2 implementation. You may refer to that package for the latest progress. Eventually, it will probably be merged into the standard library.

- **Mandatory TLS**: HTTP/2 does not require TLS. But most major implementations won't support plaintext, so it's HTTPS-only *in practice*. Caddy reverts to HTTP 1.1 for plaintext HTTP.
- **Mandatory gzip**: HTTP/2 uses HPACK to compress headers.
- **Prioritized server push**: There's some great working going on by @brk0v for this, see https://github.com/bradfitz/http2/pull/39.

The only thing about HTTP/2 that can be toggled is HTTP/2 itself, using the `-http2=false` flag value. Hope that helps.

**Comment by coolaj86** [comment]
That answers my question. I would like to further suggest this be included in the docs, especially noting that server push is in-the-works.

**Comment by mholt** [comment]
It's worth noting that Caddy isn't 1.0 yet, meaning there's still lots of development happening. Not sure if it's worth the effort to keep an updated list of http2 details, though, separate from the http2 package. Sounds like a lot of work. :)

**Comment by nemothekid** [comment]
Compression isn't mandatory with http2, and might not even be encouraged due to [BREACH](http://breachattack.com/) attacks.

**Comment by coolaj86** [comment]
Tangent - BREACH attack
======

Here's a better explanation of BREACH <http://security.stackexchange.com/a/39953>.

It sounds like BREACH has no effect on static files or APIs - only on ruby-style sites where the same CSRF (or other) token is **both** sent by the client along with user data.

I can't think of any modern pattern that would be susceptible to that kind of attack.

**Comment by nemothekid** [comment]
>I can't think of any modern pattern that would be susceptible to that kind of attack.

CSRF tokens are still used by default on Rails, Django, and some PHP frameworks. This likely won't affect the future of Caddy but for the sake of clarity there will likely be many people using Caddy as a frontend for applications like Rails. A better solution is to not compress secrets at all, but it should be clear that the pattern is still fairly modern.

**Comment by coolaj86** [comment]
But rails generates a new CSRF for each request, does it not? So it's still not susceptible.

**Comment by coolaj86** [comment]
Wait a minute... even if it did use the same CSRF it wouldn't matter because a CSRF doesn't gain privileged access to any resource.

In order to be able to use the CRSF you would have had to compromised the user's browser... at which point you can already send privileged requests on their behalf and it becomes a moot point.

**Comment by nemothekid** [comment]
I'm not 100% sure on the details of BREACH, nor what Rails is doing, but only wanted to point out that mandatory compression isn't part of http2.
