### ISSUE TITLE
ERR_QUIC_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by coleplx** [mholt/caddy#1440]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Trying to enable QUIC support on my site

### 3. What is your entire Caddyfile?
```text
XXXXX.zlx.com.br {
        root /home/hosting/xxxxx/public_html
        fastcgi / 127.0.0.1:9000 php
        log /var/log/caddy.log
        errors /var/log/caddy-errors.log
        realip cloudflare
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -quic

### 5. What did you expect to see?
The site working with QUIC

### 6. What did you see instead (give full error messages and/or log)?
ERR_QUIC_PROTOCOL_ERROR

**Comment by mholt** [comment]
Are you loading the site through Cloudflare?

**Comment by coleplx** [comment]
I'm using Cloudflare's DNS only.
The cloud is grey (cache disabled).

**Comment by mholt** [comment]
Is there anything in the log? (Run with `-log`)

**Comment by coleplx** [comment]
Oh boy... I feel very embarrassed right now.
It seems I was blocking all UDP traffic to my server. Gosh....

**Comment by mholt** [comment]
That'd do it. :) Glad you fixed it.
