### ISSUE TITLE
About markdown dev command

### ISSUE THREAD

**Issue by jet10000** [mholt/caddy#1449]
I fond caddy-0.7.5 had a markdown dev command, but caddy-0.9.5 not worked. 

during development, I don't want to cache templates. how to do it?

Thanks a lot.

**Comment by mholt** [comment]
Caddy 0.9.5 doesn't do static site generation, so the dev subdirective didn't make much sense to keep, which instructed markdown to re-generate the site on every page load. If you're having caching problems, make sure your browser is fetching the new content! ;)

**Comment by jet10000** [comment]
Change markdown file, and refresh my browser, the new content display. but change markdown template, and refresh my browser, the template changes not display, except I restart caddy.

**Comment by tobya** [comment]
A `-dev` flag that ran caddy with various development / non production features might be quite useful.

In this case reread the templates from disk each request to allow for easy development might be quite useful.

Perhaps it could also turn on debug logging (when it is implemented :)  ) .  There would need to be a strong reminder not to run with -dev flag in production.

**Comment by mholt** [comment]
I think #1445 is a more concise and well-formed issue about this, so I'll defer this conversation to that issue instead (same thing I think).
