### ISSUE TITLE
Where to update docs?

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#145]
In https://github.com/mholt/caddy/pull/128 I mentioned that I forgot to add docs.

I went back to update the docs, but I can't find caddyserver.com in https://github.com/search?q=user%3Amholt+caddy, nor do I see a docs directory.

**Comment by mholt** [comment]
Great idea! Already brought up in #9 even. I'm actively working on it (one reason I haven't made a lot of progress on other things lately). Hopefully will have this taken care of within the next week or two.
