### ISSUE TITLE
Add burp mitm detection.

### ISSUE THREAD

**Issue by kyhwana** [mholt/caddy#1454]
Client hello from burp version 1.7.17, with Firefox 51.0.1 proxied through it, copied from wireshark dump of the client->caddy server. (Burp to caddy)

0000   16 03 03 00 dc 01 00 00 d8 03 03 58 a9 2f 4d ac
0010   a9 5a cc 2f 6a 10 a9 c5 0d 73 61 35 ea e3 94 06
0020   d3 09 02 38 46 45 40 d4 82 67 76 00 00 3a c0 23
0030   c0 27 00 3c c0 25 c0 29 00 67 00 40 c0 09 c0 13
0040   00 2f c0 04 c0 0e 00 33 00 32 c0 2b c0 2f 00 9c
0050   c0 2d c0 31 00 9e 00 a2 c0 08 c0 12 00 0a c0 03
0060   c0 0d 00 16 00 13 00 ff 01 00 00 75 00 0a 00 34
0070   00 32 00 17 00 01 00 03 00 13 00 15 00 06 00 07
0080   00 09 00 0a 00 18 00 0b 00 0c 00 19 00 0d 00 0e
0090   00 0f 00 10 00 11 00 02 00 12 00 04 00 05 00 14
00a0   00 08 00 16 00 0b 00 02 01 00 00 0d 00 18 00 16
00b0   06 03 06 01 05 03 05 01 04 03 04 01 04 02 02 03
00c0   02 01 02 02 01 01 00 00 00 17 00 15 00 00 12 6a
00d0   61 67 75 61 72 2e 6b 79 68 77 61 6e 61 2e 6f 72
00e0   67

**Comment by mholt** [comment]
Thanks @kyhwana! This ClientHello is just what I need. However, I also need your full User-Agent string to complete the test case. Can you provide that too?

Strangely, the tests are be passing even with this ClientHello added to the corpus. Are you sure it was not being detected? Were you running with the latest on master (from a day or two ago)?

**Comment by kyhwana** [comment]
I pulled master again, all i'm seeing in my access log is: 
<ip> - - [20/Feb/2017:10:53:41 +1300] "GET / HTTP/2.0" 404 14

Is there a directive to enable the mitm checking?

User agent for firefox: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0"

**Comment by tobya** [comment]
You just need to include the {mitm} placeholder in your log format directive.

It provides 1 of 3 values - likely, unlikely, unknown

[Details](https://github.com/mholt/caddy/pull/1430)

**Comment by mholt** [comment]
Oops, yes, this 👆 - since all the tests are passing with that Client Hello, I suspect it will actually show up as "likely" in your logs. Please confirm whether that is the case!

And to complete the test case I would still like your full User-Agent string. Thank you!

**Comment by kyhwana** [comment]
User agent that shows up using FF with burp: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:51.0) Gecko/20100101 Firefox/51.0"
(Burp doesn't add/change the user agent string by default)

**Comment by mholt** [comment]
Excellent, thank you! I have amended the test case to include your user agent. I have plans to improve the testing on this feature in the future, and user-agent string will be an important part of that.

I'll close this now, since the test case update is being pushed soon. Were you able to see it indicate "likely" in the logs?

**Comment by kyhwana** [comment]
I did see "likely" in the caddy logs when using FF via burp, yes. 👍
