### ISSUE TITLE
Commit 286d8d1 breaks http loading

### ISSUE THREAD

**Issue by SchumacherFM** [mholt/caddy#1455]
### 1. What version of Caddy are you running (`caddy -version`)?

https://github.com/mholt/caddy/commit/286d8d1e898c19d0b678892e908156fb45d2f369 on OSX 10.11

### 2. What are you trying to do?

`curl -i http://127.0.0.1:2017/`

### 3. What is your entire Caddyfile?
```text
# front facing webserver
http://127.0.0.1:2017 {
    tls off
    root ./www_root/
    # gzip
    browse
    ext    .html
    log    ./cdy_test_2017_access.log
    errors ./cdy_test_2017_errors.log
    #errors visible

    esi {
        cmd_header_name X-Esi-Cmd
        log_file ./cdy_test_2017_debug.log
        log_level debug
        resources ./CaddyfileResources.xml
    }
}

# micro service (ms) end point
http://127.0.0.1:3017 {
    tls off
    root ./www_root/
    log    ./cdy_test_3017_access.log
    errors ./cdy_test_3017_errors.log
}
```

https://github.com/SchumacherFM/caddyesi/blob/master/Caddyfile

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
user at mbp in ~/GoPro/src/github.com/SchumacherFM/caddyesi on master [+!]
$ go run -tags esiall $GOPATH/src/github.com/mholt/caddy/caddy/main.go -conf ./Caddyfile
```

### 5. What did you expect to see?

An HTML page and integration tests are passing

### 6. What did you see instead (give full error messages and/or log)?

~10-20s loading and then downloading nothing or some tiny weird bytes.

```
$ hexdump -C page_grpc.html
00000000  15 03 01 00 02 02 0a                              |.......|
00000007
```

Content of page_grpc.html located here: https://github.com/SchumacherFM/caddyesi/blob/master/www_root/page_grpc.html

Same results when compiling with master branch latest commit. 

The MITM feature works perfect.

**Comment by wendigo** [comment]
Will investigate :)

**Comment by wendigo** [comment]
Can you check @SchumacherFM this fix: https://github.com/mholt/caddy/pull/1456 ?

**Comment by wendigo** [comment]
Don't worry about build failing (forgot to run gofmt 😭 )

**Comment by SchumacherFM** [comment]
Works! Please merge
