### ISSUE TITLE
Generate certificates with SAN extensions

### ISSUE THREAD

**Issue by wendigo** [mholt/caddy#1459]
As for now Caddy obtains certificate per domain/subdomain. I would like Caddy to obtain single certificate with multiple Subject Alternate Names extensions and single Common Name.

As far as I can see lego client supports that: https://github.com/xenolf/lego/blob/0c0d57a545045b8a88f0a07e04050119a777b9f9/acme/client.go#L350

**Comment by mholt** [comment]
It does, but there are no plans to generate SAN certificates with Caddy. See https://github.com/mholt/caddy/issues/831.
