### ISSUE TITLE
Websocket feature potentially broken with "out-of-box" example

### ISSUE THREAD

**Issue by deckarep** [mholt/caddy#146]
Hi @mholt,

Spoke to you briefly last night on #slack:

I downloaded Caddy for OSX and when trying to get the websocket sample working with the `cat` command am seeing the following error (after turning on `errors` directive):

Caddyfile:
    localhost
    log caddy.log
    errors error.log
    root .
    websocket /echo cat

Panic in logs:
`
[PANIC /echo] /Users/matt/Dev/src/golang.org/x/net/websocket/server.go:74 - interface conversion: *middleware.responseRecorder is not http.Hijacker: missing method Hijack
`

Great, great framework!

**Comment by mholt** [comment]
Ah! I should have known. See #133, fixed in #134. Should go out in the next release. You are welcome to pull from source and confirm it is fixed, but I won't require it of you. Sorry again for the trouble.

**Comment by deckarep** [comment]
@mholt - bingo, i'll try this tomorrow to confirm.

**Comment by deckarep** [comment]
@mholt - I have confirmed that the issue I experienced is exactly the same as above..going to close.
