### ISSUE TITLE
websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by b3ntly** [mholt/caddy#1468]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy (untracked dev build)

### 2. What are you trying to do?

Reverse-proxy a websocket server using the gorilla/websocket library

### 3. What is your entire Caddyfile?
```text
# Host and port to listen and serve on.
localhost:8080

# set the root directory from which to serve files to the public
root ./static

# compress all returned files
gzip

# prettify urls by truncating file extensions
ext .html .css .js

# publish basic application statistics
expvar /stats

# publish basic server statistics
pprof

# set log file to our /logs directory relative to this file
log ./logs/caddy.log

# set error log file to our /logs directory relative to this file
errors ./logs/errors.log

# pass requests sent to /api to our running web application
proxy /api 127.0.0.1:8020 {
    transparent
    websocket
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

./caddy --conf=caddyDevFile

### 5. What did you expect to see?

A working websocket connection

### 6. What did you see instead (give full error messages and/or log)?

After 10 seconds the connection was timed out with the server-side error:

```
websocket: close 1006 (abnormal closure): unexpected EOF
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Running this example application behind a proxied connection:

```
https://github.com/gorilla/websocket/tree/master/examples/chat
```
------

This is a duplicate issue of https://github.com/mholt/caddy/issues/1384. I want to leave breadcrumbs that may better fit the queries of people running into the problem in the future.

Essentially websocket connections sit open and the default read timeout in Caddy will kill it after ten seconds. Using the 'timeouts none' directive or similar will solve the issue though I imagine it would have potential issues in a production environment and should at minimum be limited to ws connections only..

**Comment by mholt** [comment]
Thanks for filing this, and as you mentioned, this is a duplicate, so I'm going to close this -- and the next version of Caddy (or now if you build from source) will not have default timeouts enabled.

**Comment by steviesama** [comment]
@b3ntly I realize the 10 second thing is a common config, but it's sort of hilarious how it reminds me of how I set up a systemd service for a golang backend server I wrote once and I noticed sometimes it would cut out when I connected with the client but seemed to be running. A bit later when I did more with the code, I figured out that having "notify" and not notifying systemd and having "simple" is a bad idea. xD
