### ISSUE TITLE
undefined: toml.Unmarshal

### ISSUE THREAD

**Issue by artpar** [mholt/caddy#147]
I just did the "go get" for caddy and got this error

```
➜  github.com  cd mholt/caddy
➜  caddy git:(master) go build
# github.com/mholt/caddy/middleware/markdown
middleware/markdown/metadata.go:119: undefined: toml.Unmarshal
```

Unable to build. While go get for toml works fine
```
➜  caddy git:(master) go get -u github.com/BurntSushi/toml
```

**Comment by abiosoft** [comment]
What version of Go are you running ? Ensure it is 1.4 and above.

**Comment by mholt** [comment]
Weird.

Try deleting the caddy repo (the whole folder) and also the toml repo, then do `go get  github.com/mholt/caddy` again, just to be sure...

**Comment by mholt** [comment]
Closing this unless there is still a problem (I don't think it is directly related to Caddy, especially not without more information. Feel free to reopen if it is.)
