### ISSUE TITLE
Request Placeholders - {?keyName} to extract value from {query}

### ISSUE THREAD

**Issue by samber** [mholt/caddy#1470]
Hi guys,

Thanks for the great work on this project !

I wanted to make a conditional rewrite, testing if an argument is set in ```{query}```.
It would be great to be able to extract a value from ```{query}``` such as ```{?keyName}```.

The workaround is to use a regexp: ```if {query} match (^|&)keyName=(.+)(&|$)```.

**Comment by tobya** [comment]
Hi @samber - thank you for the request.  

This seems to me like a feature that is best dealt with further down the line by a dynamic language such as php, python etc  .  We are hoping to keep the Caddyfile as simple as possible.  

Perhaps if  you explain in more detail exactly what you wish to do there may be some suggestions to help you solve the issue.

**Comment by DIDE35** [comment]
coll

**Comment by samber** [comment]
My use case is to make a redir if a query argument is not set.

**Comment by mholt** [comment]
Toby is right, we want to avoid making the Caddyfile something that you end up scripting. I don't think this feature adds any complexity we don't already have, so we could look into doing this. It would be good for someone new to the project too.
