### ISSUE TITLE
Caddy deploys SHA-1 based letsencrypt certificates

### ISSUE THREAD

**Issue by zaolin** [mholt/caddy#1472]
Hey guys,

normally it's possible to configure the hash algorithm for a letsencrypt certificate.
Caddy instead uses the standard hash algorithm (SHA-1) in automatic https mode.
SHA-1 is nearly dead and Google released yesterday: http://shattered.io/.

I would recommend to switch to SHA-256 as default. Maybe also offer a way
to configure yourself the hash algorithm like it's for the asymmetric algorithm (rsa/ecc).

Best Regards
Zaolin

### 1. What version of Caddy are you running (`caddy -version`)?
v0.9.5

### 2. What are you trying to do?
Choosing a different hash algorithm for the automatic https mode is not possible

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Check a caddy served domain via https://www.ssllabs.com/ssltest/

**Comment by zaolin** [comment]
Sorry my fault the Letsencrypt DST Root CA X3 uses SHA-1 Oo

**Comment by mholt** [comment]
The signatures of root certificates are not used for trust decisions because the root certificate is trusted explicitly anyway. They're essentially self-signed. See https://community.letsencrypt.org/t/sha-1-signed-certificate-in-chain/24897/2?u=mholt for more explanation.

**Comment by zaolin** [comment]
Thanks for the explanation and also for the great work on caddy :) .

**Comment by mholt** [comment]
You're welcome - and thanks for keeping us in line. ;)
