### ISSUE TITLE
Add a way to dynamically add directives

### ISSUE THREAD

**Issue by nahidakbar** [mholt/caddy#1473]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

Source

### 2. What are you trying to do?

Implement a new plugin type

### 3. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Run from go sources

### 5. What did you expect to see?

Expected there to be a way to register new middleware plugin from setup.go of the plugin.
It never called setup.

### 6. What did you see instead (give full error messages and/or log)?

Ended up having to manually hack the source at caddy/caddyhttp/httpserver/plugin.go. Worked after that. 

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

This is explained in step 3 https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-Directives . However, a better system would be to not have to maintain a master list of directives in caddy source code. Better to have a way of registering them. Assuming, it makes no difference in performance.

**Comment by mholt** [comment]
Thanks for the feedback, @nahidakbar . I'm glad you're writing a plugin. :)

> Assuming, it makes no difference in performance.

Worse, it makes a difference in _correctness_.

You can use [RegisterDevDirective()](https://godoc.org/github.com/mholt/caddy/caddyhttp/httpserver#RegisterDevDirective) for convenience, but in the end, the order of the directives has to be hard-coded to be correct.

If anyone has a solid, simple solution to this dilemma I'm all ears. :)

**Comment by mastercactapus** [comment]
I've considered this problem a few times. Best I've thought of was
optionally registering "before" and/or "after" directives, having caddy
calculate the order from that, being careful for cycles.

It's one approach anyhow. It's the same way systemd unit file dependencies
are handled for startup.

**Comment by nahidakbar** [comment]
Thanks, RegisterDevDirective is perfect for my use. Don't know how I missed it.

If it was me, I'd probably do it by categorising the current plugins into buckets in within witch order of things would not matter and have the specify the bucket their directive belongs to.
