### ISSUE TITLE
RPM repository availability for Caddy

### ISSUE THREAD

**Issue by dvershinin** [mholt/caddy#1475]
I've been looking at #424 but I can't seem to find any info on installing Caddy via yum.
If it's not available via yum by this point, let me know so I can build up RPM repository for it.

**Comment by Xe** [comment]
https://copr.fedorainfracloud.org/coprs/xena/caddy/ is the one I maintain.

**Comment by dvershinin** [comment]
Thanks. Can you include info on what plugins are included there?

**Comment by dvershinin** [comment]
Alright I see it now) Now enough for my use case unfortunately :) Need proxy module.

**Comment by mholt** [comment]
For a related discussion about packaging Caddy: https://forum.caddyserver.com/t/packaging-caddy/61?u=matt

**Comment by carlwgeorge** [comment]
@dvershinin Caddy RPMs are now available in Fedora and EPEL.
