### ISSUE TITLE
bind can't be used well with virtual hosts

### ISSUE THREAD

**Issue by jrobeson** [mholt/caddy#1477]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9..5

### 2. What are you trying to do?
use the bind directive to bind to 127.0.01 with multiple vhosts

### 3. What is your entire Caddyfile?
This isn't my Caddyfile but shows what is intended.
```text
bind 127.0.0.1
localhost {
   
}
localhost/foo {
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`./caddy`
no software running on 2015 port

### 5. What did you expect to see?
I expected to be able to bind all virtualhosts to a single address.

### 6. What did you see instead (give full error messages and/or log)?
```
Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address: 
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
try the above Caddyfile

It seems like bind needs to be able to appear on the first line of the file, and potentially be available as a command line switch like port

**Comment by mholt** [comment]
I don't really understand, bind works fine with virtual hosts, you just do it like this:

```plain
localhost {
   bind 127.0.0.1
}
localhost/foo {
   bind 127.0.0.1
}
```

**Comment by jrobeson** [comment]
ah, I didn't think of it like that, since bind seems like the the kind of thing you shouldn't try to do twice. I've never configured anything with one instance and two bind directives before :)

**Comment by jrobeson** [comment]
would you be averse to the idea of a`-bind` param to `caddy ? If not, I'll file a separate feature request.

**Comment by mholt** [comment]
> ah, I didn't think of it like that, since bind seems like the the kind of thing you shouldn't try to do twice.

You need to think differently when using Caddy than with using other, traditional servers. Caddy is configured per site, not per server.

> would you be averse to the idea of a -bind param to caddy? If not, I'll file a separate feature request.

I don't think I want to add that; I prefer not to duplicate directives in command line flags.
