### ISSUE TITLE
gzip: no Content-Length header is set for file downloads

### ISSUE THREAD

**Issue by mbertschler** [mholt/caddy#1479]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.5 (abiosoft/caddy:latest Docker container)

### 2. What are you trying to do?

Downloading a file, using gzip. `curl -LO --compressed -v http://example.com/url/to/big/file`

### 3. What is your entire Caddyfile?
```text
example.com:80 {
        tls off
        gzip
        root /www
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Default abiosoft/caddy:0.9.5 Docker container and the above Caddyfile

### 5. What did you expect to see?

A **Content-Length** header set like this: 
```
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 50020064
< Content-Type: application/octet-stream
< Etag: W/"58b43808-2fb3ee0"
< Last-Modified: Mon, 27 Feb 2017 14:30:32 GMT
< Server: Caddy
< Date: Mon, 27 Feb 2017 15:58:20 GMT
```
This is the curl output from running `curl -LO -v http://example.com/url/to/big/file` (no gzip)

### 6. What did you see instead (give full error messages and/or log)?

No **Content-Length** header present in the response.

```
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Encoding: gzip
< Content-Type: application/octet-stream
< Etag: W/"58b43808-2fb3ee0"
< Last-Modified: Mon, 27 Feb 2017 14:30:32 GMT
< Server: Caddy
< Vary: Accept-Encoding
< Date: Mon, 27 Feb 2017 16:02:36 GMT
< Transfer-Encoding: chunked
```
This is the curl output from running `curl -LO --compressed -v http://example.com/url/to/big/file` (with gzip)

#### Note: **Content-Length**  is set when I download a small .html file
```
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Encoding: gzip
< Content-Type: text/html; charset=utf-8
< Etag: W/"588f5fc8-1900"
< Last-Modified: Mon, 30 Jan 2017 15:46:16 GMT
< Server: Caddy
< Vary: Accept-Encoding
< Date: Mon, 27 Feb 2017 16:11:15 GMT
< Content-Length: 1686
```
### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

- turn on gzip in your Caddyfile and specify a root
- download the file using `curl curl -LO -v {URL}` 
- download the file using `curl curl -LO --compressed -v {URL}`

**Comment by tobya** [comment]
I am having difficulty reproducing this.  I have tried

- Large .exe file
- Large .zip file 
- Browser and curl

Is there any more information you can provide?  What type of file are you downloading is it a large 500mb HTML file, a zip file, a binary.  When I download a 100MB zip file I get these headers

    < Accept-Ranges: bytes
    < Content-Length: 107825752
    < Content-Type: application/x-zip-compressed
    < Etag: "ohvxtp1s72vs"
    < Last-Modified: Thu, 08 Dec 2016 21:17:49 GMT
    < Server: Caddy
    < Date: Tue, 28 Feb 2017 22:42:38 GMT

Any more information you could give would be great.

**Comment by tobya** [comment]
I'm having a little difficulty reproducing this bug.  Could you provide any more detail that you might have.  

What type of file are you downloading (HTML, exe, zip etc)?  Is this your full Caddyfile?  Can you reproduce without Docker?  Any more information you have would be great.

**Comment by mbertschler** [comment]
@tobya the files I am using this with are medium sized binaries in the 50~100MB range. I think there are two usecases that are relevant here:

1. The file is gzipped on the fly, and it is streamed with chunked encoding. Including a Content-Length here would require buffering, and since the main reason for zipping is large files, that would probably not a good idea and would probably also increase latency.

2. The file bigfile is requested, and caddy finds the file bigfile.gz on the filesystem. I checked this case, and also did not see a Content-Length header.

I consider the second point a bug, and I will submit a pull request for that.
