### ISSUE TITLE
Specify `SingleInstance` feature for Caddy Websocket directive

### ISSUE THREAD

**Issue by deckarep** [mholt/caddy#148]
Hi @mholt,

I'm exploring some use cases around the websocket feature for Caddy which I'm really liking.  Particularly, I noticed that if I open up multiple .html pages that connect to a Caddy websocket that multiple processes are spun up for each websocket connection.  I'm wondering if this is intended and if it is...how do you feel about having some type of `SingleInstance` option that basically only ever creates one process no matter how many websocket clients are connected.

Of course, the onus is on the developer to create a websocket process that can deal with multiple clients and they would have to build such logic into each client to allow for identifying individual client requests.

Curious to hear your thoughts.

**Comment by nemothekid** [comment]
I'm pretty sure thats a mistake - I don't think caddy `forks()` at all so it should all be single process. It is go, so goroutines/threads are preferred over multiple processes.

**Comment by mholt** [comment]
Caddy's `websocket` directive acts a bit like CGI for WebSockets, in that it spawns a new process process for each WS connection. The idea is that it works with programs, written in any language, that aren't designed to be used with web sockets, necessarily.

Maybe you're looking for something more like a websocket proxy? Something like this:

```
proxy / localhost:8080 {
	websocket
}
```

That doesn't spawn processes - each request shares the same process.

**Comment by deckarep** [comment]
Interesting,

Using this method would I still be able to associate the Websocket to a process that reads/writes to stdin/stdout as well?

Thanks!

-Ralph

**Comment by mholt** [comment]
No, I think in that case the websocket process has to support the websocket protocol.

The tricky thing about a single shared process with the `websocket` directive is, as you said, distinguishing one client from another. Just curious, how would you do that?

(But I guess if all you needed was a cheap way to do server push via stdout to all clients, the idea of a single process could work quite well.)

**Comment by deckarep** [comment]
Yeah exactly,

Some of this is bordering on novel ideas but I'm just experimenting.

You can keep track of the websockets at the client side by invoking all requests with some sort of session id.

There could be more interesting use cases.

**Comment by mholt** [comment]
How about something like this:

```
websocket share /echo cat
```

Every client "shares" the same process. (I'm open to discussing the exact keyword that would be used.)

The tricky part about implementing this is keeping track of active requests and multiplexing the stdin and stdout from/to all current clients. I'd accept a PR :smile:

**Comment by deckarep** [comment]
That's sounds good...I'll see if I can put together a P.o.C on this.

Thanks @mholt!

**Comment by mholt** [comment]
@deckarep Any luck with this?
