### ISSUE TITLE
Upload stalling with HTTPS

### ISSUE THREAD

**Issue by oliverpool** [mholt/caddy#1480]
*Probably similar to #1147*

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 2. What are you trying to do?
Upload large file (with caddy acting as reverse proxy in front of [tus](https://github.com/tus/tusd))

### 3. What is your entire Caddyfile?
```text
tus.example.com {
  proxy localhost:3001 { #adress of the tus server
    transparent
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy.exe`
on windows 10

### 5. What did you expect to see?
Upload of 10MB file coimpleting fine over https

### 6. What did you see instead (give full error messages and/or log)?
When trying on http, the upload works fine.
On https, the upload stalls at about 60%. From the client side, the JS doesn't send (no more `progress` events)

I don't know how I could dig deeper to debug this situation: any input is appreciated!

**Comment by oliverpool** [comment]
If I pause the upload, `tus` is capable of writing what has been sent until now: if I then resume the upload, everything works fine (the last 4MB are uploaded successfully)

**Comment by tobya** [comment]
This may be related to default timeouts set in 0.9.5 (they will be disabled in next release)
try
    tus.example.com {
      timeouts 0
      proxy localhost:3001 { #adress of the tus server
       transparent
      }
    }

**Comment by oliverpool** [comment]
> This may be related to default timeouts set in 0.9.5 (they will be disabled in next release)
try

But then it should also fail on http (not only on https), no?

Anyway, I will try it tomorrow

**Comment by tobya** [comment]
@oliverpool  ohh sorry didnt notice that, but it may be worth a try anyway.

**Comment by Unknwon** [comment]
I have the exact same problem.

If I set `timeouts none` my client just hangs forever. Then if I upload with raw IP:port, everything goes fine. Also using 0.9.5.

**Comment by mholt** [comment]
@Unknwon Is `timeouts 0` or `timeouts none` set?

**Comment by Unknwon** [comment]
@mholt yes,

```
domain.com {
        timeouts {
                read none
        }
        proxy / localhost:8086
}
```

**Comment by Unknwon** [comment]
And just realize same for download, hangs on about 16.1MB.

**Comment by mholt** [comment]
@Unknwon You've only set the read timeout to 0, set all of them to 0 and try again.

**Comment by Unknwon** [comment]
Sorry about multiple comments so quickly, roll back to 0.9.4 immediately solved the problem. 

>You've only set the read timeout to 0, set all of them to 0 and try again.

At first I didn't set any timeouts, and it just hangs on upload about 13.8MB until it timeout.

**Comment by mholt** [comment]
>  roll back to 0.9.4 immediately solved the problem.

That's interesting. Would you be able to spare a few minutes to help debug this since I have nothing to reproduce this with from this issue so far?

Just brainstorming here... if you could try before these commits/PRs (like bisect?) and see if any of them are the culprit:

- https://github.com/mholt/caddy/pull/1358
- https://github.com/mholt/caddy/commit/ae10122f7e3459214acaf3826c7e473a52d3dda8
- https://github.com/mholt/caddy/pull/1314
- https://github.com/mholt/caddy/commit/4babe4b201eef3e9794851b74f734a03338f7a20
- https://github.com/mholt/caddy/commit/153d4a5ac62ffcef77df8ad29ae13e7d68b188b6

**Comment by Unknwon** [comment]
@mholt sure, but probably half an hour later...

**Comment by Unknwon** [comment]
I can't enable HTTPS for local fake domain for all sorts of reason, it is giving me hard time to debug. And HTTP seems working fine.

**Comment by mholt** [comment]
@Unknwon Even with `tls self_signed` for localhost? Should make it much easier.

@oliverpool Would you please be able to try Caddy at those commits/PRs I linked to above and see which one causes it?

**Comment by oliverpool** [comment]
@mholt & @Unknwon : I found a preciser cause !

It seems to be the `write timeout` (tests with version 0.9.5):
- when the write timeouts is set to `none`, everything works fine (http & https)
- when the write timeouts is unset (or set to some value smaller than my upload duration) strange things happen:
  - `https`: the upload simply stalls (no more progress whatsoever). When I interrupt the upload, the end of the request is sent to my tus server and everything seems fine
  - `http`: the upload goes to the end, but the tus server doubly receives the request and only the last one is sent back to my browser (which is a failure because the first one was properly proceeded by the tus server)

So a simple workaround is to correctly set the timeouts :smile: 

But there might still be a bug regarding what happens when a timeout occurs.

**Comment by oliverpool** [comment]
According to https://blog.cloudflare.com/exposing-go-on-the-internet/, there is a bug regarding `readTimeout` for http/2: https://github.com/golang/go/issues/16450 in Go 1.7.

I will try to compile caddy with go 1.8 and update my bug report.

**Comment by oliverpool** [comment]
Compiled with go 1.8 (go version go1.8 windows/amd64):

The `write timeout` seems to be ignored: everything works fine for http and for https (no stall / no double request).

**Comment by mholt** [comment]
@oliverpool Ah, excellent. I forgot about that bug mentioned in the blog post! 😁 Oops.

Okay, so for now, disable timeouts completely on Caddy 0.9.5 if you're having this problem. The next version will be built on Go 1.8 so that should resolve the bug (and default timeouts will be disabled anyway).

Thanks for figuring it out! :tada:

**Comment by oliverpool** [comment]
I will just use the one I compiled it with go 1.8 ;-)

Thank you for your support!

**Comment by michalmedvecky** [comment]
I can confirm this issue with 0.9.5. with https, upload fails after some time (502), with http, it just infinitely waits.

Downgrading to 0.9.4 helped.

Can I help debugging this issue?

**Comment by oliverpool** [comment]
> Can I help debugging this issue?

Did you try with Go 1.8 ?

**Comment by michalmedvecky** [comment]
I'm using abiosoft/caddy docker image. No clue which go is it using, but Dockerfile looks like it's downloading the official binary from caddyserver.com.

**Comment by oliverpool** [comment]
Well then you will have to wait a bit (https://github.com/mholt/caddy/issues/1480#issuecomment-283030700 from mholt):

> Okay, so for now, disable timeouts completely on Caddy 0.9.5 if you're having this problem. The next version will be built on Go 1.8 so that should resolve the bug (and default timeouts will be disabled anyway).

**Comment by tobya** [comment]
This may be a known issue with default timeouts.

Try 

    Timeouts none 

In your caddyfile

**Comment by krisak** [comment]
Is this something ongoing? I cant upload files above certain size. Also 'limits' directive Parse error: Unknown directive 'limits'.

Is there any way how to go around this?

**Comment by oliverpool** [comment]
@krisak which version of Caddy are you using ?

If this is happening with version 0.10.3, it might be a good idea to open a new issue.

**Comment by krisak** [comment]
Oh damn i am still 0.10.2. I will try to update and see whats going on.
