### ISSUE TITLE
[Suggestion] New `signal` directive

### ISSUE THREAD

**Issue by oliverpool** [mholt/caddy#1485]
I (unfortunately) have to use caddy under windows. It means that I can't use the signals to control Caddy (especially SIGUSR1 to reload the Caddyfile).

Maybe it could be possible to add a new directive called `signal` (or any other better name) to control Caddy via http requests:
```
signal {
  reload    /reload/randomStringForSecurity
  shutdown  /shutdown/otherRandomStringForSecurity
  hangup    /hangup/otherRandomStringForSecurity
  terminate /terminate/otherRandomStringForSecurity
}
```

A `GET` request to `/reload/randomStringForSecurity` would then reload the caddyfile (just like SIGUSR1)

Since the security implications are quite important, appropriate warning should be advertised on the documentation.

If you think that this suggestion is worth something, I can try to put up a PR with this!

**Comment by mholt** [comment]
Thanks for the suggestion! Caddy will be getting an API that will make use on Windows a little easier. And each request will be authenticated, so no security woes. ;)

We're working on it.

**Comment by VanCoding** [comment]
Any progress on this?
I also want to use caddy on a windows server, but reload is a must, so I have to delay it unit the API is ready.

**Comment by mholt** [comment]
Not yet, but after our launch event next month, the API will be the next major project we're taking on.
