### ISSUE TITLE
Websocket and HTTP timeouts

### ISSUE THREAD

**Issue by mibk** [mholt/caddy#1487]
I just ran into #1384 and I think it'd be worth mentioning about that in the [websocket part of the *proxy*](https://caddyserver.com/docs/proxy#presets) documentation to prevent potential confusion for other users.

What do you think?

**Comment by mholt** [comment]
Default timeouts are going to be disabled in the next version (they already are on master), so these timeout issues will become irrelevant I think. Otherwise, yes, I would agree with making that change in the docs. :) Thanks for the comment!
