### ISSUE TITLE
Templates: Add support for sub-requests

### ISSUE THREAD

**Issue by indeyets** [mholt/caddy#1490]
(after discussion in #392 @mholt suggested to open a new issue)

Caddy tries to replace usage of SSI with [Templates](https://caddyserver.com/docs/template-actions), but they, currently, do not handle one common use case: Sub-requests aka `include virtual`

The idea is that `<!--# include virtual='/some/url?param=value' -->` allows user to specify a need for a sub-request (usually implemented by hooking into server's processinig pipeline, not doing real tcp stuff).

After this, the body of response from `/some/url?param=value` is inserted into the place of template.

@mholt mentioned that `{{.HTTPInclude "..."}}` might be used for this.

NGINX has [some additional options](http://nginx.org/en/docs/http/ngx_http_ssi_module.html#commands) for virtual requests such as `wait="yes"` and `set="varname"` which can be useful in this context

**Comment by mholt** [comment]
This has been implemented in Caddy 2.
