### ISSUE TITLE
"redir" command returning wrong url

### ISSUE THREAD

**Issue by veryexcited** [mholt/caddy#1493]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 2. What are you trying to do?
run caddy behind haproxy. coexists with ocserv and softether by haproxy's sni function.

### 3. What is your entire Caddyfile?
```text
example.com:567 {
  header / -Server
  root /var/www
  redir {
    if {scheme} not https
    to https://example.com/
  }
}

www.example.com:567 {
  header / -Server
  redir https://example.com/
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/local/bin/caddy -agree=true -conf=/etc/caddy/Caddyfile -pidfile=/var/run/caddy/caddy.pid -log=stderr

### 5. What did you expect to see?
visit http://www.example.com and http://example.com
returns https://example.com/
(as defined in the caddyfile)

### 6. What did you see instead (give full error messages and/or log)?
visit http://www.example.com and http://example.com
returned https://example.com:567/
(not expected)

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
should recurrent stably
```text
curl --head http://example.com
curl --head http://www.example.com
```

**Comment by mholt** [comment]
You have a typo in your Caddyfile. :wink: `redir` doesn't take `to` in an opened block - remove it and it will work. See the docs here: https://caddyserver.com/docs/redir

**Comment by veryexcited** [comment]
but still returns a url with port "567"
it should return what i defined in the caddyfile, not with ":567"
