### ISSUE TITLE
Option to generate logs for connection timeouts

### ISSUE THREAD

**Issue by xrl** [mholt/caddy#1495]
This is a feature request

### 1. What version of Caddy are you running (`caddy -version`)?

`0.9.5`

### 2. What are you trying to do?

I spent too much time trying to figure out what was going on with my connections when pushing docker containers. There's nothing specific to docker but when the layers are large the connections stay open for a long time while data is pushed. I didn't realize my connections were being dropped by the new timeout functionality (I absolutely should have connected the dots myself...).  I thought if the connection was actively being used it wouldn't be dropped.

In any case, I was chasing this Caddy behavior and going up and down my networking stack.

### 3. What is your entire Caddyfile?
```text
https://docker-registry.mysite.com {
	proxy / http://registry:5000 {
		transparent
	}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

In a docker container with the following command line invocation:

```
            "Cmd": [
                "-conf",
                "/etc/Caddyfile",
                "-log",
                "stdout",
                "-agree",
                "-email",
                "me@myemail.com"
            ],
```

### 5. What did you expect to see?

I saw startup logs for my domains and I expected to see a "connection to $MY_HOME_IP dropped due to $TIMEOUT seconds of being open" or similar.

### 6. What did you see instead (give full error messages and/or log)?

Nothing. I would have to run tcpdump inside the container to see a TCP RST being sent by Caddy.

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Run a Caddy server and push a big amount of data to a proxied service.

**Comment by mholt** [comment]
Timeouts are logged -- are you not seeing any "timeout" log entries?

> I thought if the connection was actively being used it wouldn't be dropped.

This might be a Go bug that is fixed in Go 1.8.

**Comment by xrl** [comment]
I do not see timeouts in my build. I'm pretty sure it's built with Go 1.7.

**Comment by tobya** [comment]
@xrl The timeout defaults which was introduced in 0.9.5 will be removed in next release.  

However it may still be of benefit to log a more obvious timeout item.

**Comment by mholt** [comment]
@tobya The go standard library should already be writing logs on timeouts...

**Comment by tobya** [comment]
@mholt I guess by the feature request I meant we could try to provide more info in the logs.

 It may be worth considering (if possible) logging some slightly more obvious timeout or connection dropped errors or log entries.  We have seen the difficult people have had tracking down these issues and even if default timeouts are removed people may still have similar issues if they set timeouts too low.

**Comment by xrl** [comment]
@mholt I did not see timeouts in my logs. I am running the `abiosoft/caddy:0.9.5` image. Perhaps I should try building with Go 1.8 and see if it's different?

**Comment by mholt** [comment]
It may be that only the HTTP client when proxying is logging; how do we log the timeouts, then?

**Comment by xrl** [comment]
I'm not following. The HTTP client access Caddy or the HTTP client from Caddy to the backend server?

I could see the EOF error in my client but I didn't know why there was an EOF. I thought there was a network connectivity issue. There was no descriptive log. Can the timer firing in Caddy be tied to a log statement?

Or are you saying that the timer is outside of the Caddy process?

**Comment by mholt** [comment]
> I'm not following. The HTTP client access Caddy or the HTTP client from Caddy to the backend server?

The HTTP client code from Caddy to the backend server when proxying, yes (the second one).

> I could see the EOF error in my client but I didn't know why there was an EOF. I thought there was a network connectivity issue. There was no descriptive log. Can the timer firing in Caddy be tied to a log statement?

That's the one; that's also what I see for timeouts with proxy.

I'm not sure -- without investing some time -- how to log timeouts specifically.

**Comment by mholt** [comment]
Haven't heard about this issue for a while, so I'm gonna close it. Also, there's some rumors that Go 1.8 fixed some issues with timeouts (including, perhaps, logging them consistently? I dunno off the top of my head) - and Go 1.9 comes out any day with further improvements to timeouts, which are now off by default (except for an idle timeout).

Feel free to continue discussion on this issue if you'd like, but for now I don't really know what would be actionable here; from what I have seen, "timeout" is logged by the Go standard library when a connection times out...
