### ISSUE TITLE
leaking goroutines after SIG USR1 with proxy directive's healthcheck worker

### ISSUE THREAD

**Issue by davejhilton** [mholt/caddy#1503]
I recently ran into an issue where caddy (with the `proxy` directive) was flooding its backends with healthcheck requests... on the order of 15+ healthcheck requests per second to each backend.

I was able to determine that it's due to caddy reloads via the `USR1` signal mechanism.  Each time caddy is reloaded, it starts sending another healthcheck every `health_check_interval`. Over time and with multiple reloads... the healthchecks really start to add up.

### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.4 (+8464020 Sun Jan 15 10:11:28 UTC 2017)

### 2. What are you trying to do?
Use the `proxy` directive, and occasionally trigger a reload via `SIGUSR1` when the Caddyfile is changed.

### 3. What is your entire Caddyfile?
```text
localhost:80 {
    proxy / http://localhost:8081 {
        health_check /healthcheck
        health_check_interval 10s
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
running this via

```bash
sudo caddy -conf /path/to/Caddyfile
```
with `0.9.4` on MacOS Sierra 10.12.3 (caddy installed via `homebrew`)
The same issue is present when running from source (`go1.8`, same OS)
Also present on our CentOS 7 hosts, with caddy built from source.

### 5. What did you expect to see?

Even after sending `USR1` to reload from the updated Caddyfile, I expected that the healthchecks would continue to be sent to the proxy backends at the configured `health_check_interval` (once per 10s)

### 6. What did you see instead (give full error messages and/or log)?

The number of healthcheck requests that are sent to the backend server increases with each reload of caddy. Here's the (simplified) access logs of a simple backend server that's receiving these healthchecks:

```text
GET /healthcheck @ 10:00:01  - A <-- call this "healthcheck series A" (every 10s on the 1's)
GET /healthcheck @ 10:00:11  - A
GET /healthcheck @ 10:00:21  - A
GET /healthcheck @ 10:00:31  - A
GET /healthcheck @ 10:00:41  - A
***** triggered a reload via SIG USR1 here *****
GET /healthcheck @ 10:00:52  - B <-- call this "series B" (every 10s on the 2's)
GET /healthcheck @ 10:00:51  - A
GET /healthcheck @ 10:01:02  - B
GET /healthcheck @ 10:01:01  - A
***** triggered a reload via SIG USR1 here *****
GET /healthcheck @ 10:01:03  - C <-- series C (on the 3's)
GET /healthcheck @ 10:01:12  - B
GET /healthcheck @ 10:01:11  - A
GET /healthcheck @ 10:01:13  - C
GET /healthcheck @ 10:01:22  - B
***** triggered a reload via SIG USR1 here *****
GET /healthcheck @ 10:01:24  - D <-- series D (on the 4's)
GET /healthcheck @ 10:01:21  - A
GET /healthcheck @ 10:01:23  - C
GET /healthcheck @ 10:01:32  - B
GET /healthcheck @ 10:01:34  - D
***** triggered a reload via SIG USR1 here *****
GET /healthcheck @ 10:01:35  - E <-- series E (on the 5's)
...
...
***** lots more reloads *****
...
...
GET /healthcheck @ 10:03:22  - B
GET /healthcheck @ 10:03:22  - J
GET /healthcheck @ 10:03:22  - Y
GET /healthcheck @ 10:03:22  - N
GET /healthcheck @ 10:03:22  - Q
GET /healthcheck @ 10:03:22  - S
GET /healthcheck @ 10:03:22  - T
GET /healthcheck @ 10:03:22  - L
GET /healthcheck @ 10:03:22  - F
GET /healthcheck @ 10:03:22  - Z
GET /healthcheck @ 10:03:22  - R
GET /healthcheck @ 10:03:22  - W <-- roughly 12 healthchecks per second by now
GET /healthcheck @ 10:03:23  - C
GET /healthcheck @ 10:03:23  - M
...
...
etc
```

### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

- create the `Caddyfile` above
- run a simple "backend" server on localhost:8081 that prints access logs with timestamps (I used `python -m SimpleHTTPServer 8081 .`)
- run caddy, configured with the Caddyfile given
- observe `/healthcheck` being requested once every 10 seconds as expected.
- run `sudo kill -s USR1 <caddy_pid>` 5 times
- observe `/healthcheck` being requested six times in each 10 second window

also—you can see the number of goroutines increase consistently with each caddy reload by adding a simple ticker like this into caddy's `Run()` function:

```golang
// Run is Caddy's main() function.
func Run() {
	// ...

	go func() {
		ticker := time.NewTicker(2 * time.Second)
		for {
			select {
			case <-ticker.C:
				fmt.Printf("---- %d goroutines\n", runtime.NumGoroutine())
			}
		}
	}()

	// ...
}
```

here's caddy's stdout content after adding that ticker:
```
Activating privacy features... done.
http://localhost
---- 11 goroutines
---- 11 goroutines
---- 11 goroutines
---- 11 goroutines
---- 11 goroutines
---- 11 goroutines
---- 11 goroutines
---- 13 goroutines  <--- after a reload
---- 13 goroutines
---- 13 goroutines
---- 15 goroutines  <--- after another reload
---- 15 goroutines
---- 17 goroutines  <--- another
---- 19 goroutines  <--- another
---- 21 goroutines  <--- another
---- 23 goroutines  <--- another
```

---

My  use case (if anyone is interested) is that I am using [`consul-template`](https://github.com/hashicorp/consul-template) to dynamically re-render the Caddyfile whenever the list of its backends changes. Basically, `consul-template` is set up to watch for membership changes in a consul service pool. Whenver new nodes are added or removed from the consul service, it updates the Caddyfile's `proxy` directive with the current list of hosts. 

That's coupled with an orchestration system ([`nomad`](https://github.com/hashicorp/nomad)), which spins up/down new backend instances occasionally as needed, within a pool of available hosts. So I end up with caddy being reloaded on a fairly regular basis... which is how I got into the situation of having 15+ healthchecks per second. (I hadn't needed to restart caddy for ~30 days or so).

**Comment by davejhilton** [comment]
For whatever it's worth... I have just started poking around in the code to see if I can come up with a solid fix, but I'm pretty new to Go still.

It looks like it may just need a "stop" channel passed into the call to 
```golang
go upstream.HealthCheckWorker(nil)
```
([here](https://github.com/mholt/caddy/blob/463c9d9dd250344fd20069449d3bab82cffb292a/caddyhttp/proxy/upstream.go#L111)) instead of passing `nil`. Then I think it'd just be a matter of listening to the stop channel, and breaking from the `HealthCheckWorker`'s ticker loop, [here](https://github.com/mholt/caddy/blob/463c9d9dd250344fd20069449d3bab82cffb292a/caddyhttp/proxy/upstream.go#L382). Otherwise new healthcheck workers just get spun up with each call to `inst.Restart()`, since `NewStaticUpstreams()` appears to be called each time the `proxy` directive's `setup()` func is called—with an additive effect.

I could also be on the completely wrong track 😄

**Comment by mholt** [comment]
Oops, you're right. That's a TODO. 😓 Those goroutines need to be shut down with the server when restarted.

**Comment by dividinglimits** [comment]
I suggest implementing the technique described by Rachel in https://rakyll.org/leakingctx/
