### ISSUE TITLE
help wanted using alternate ports for ACME

### ISSUE THREAD

**Issue by dncohen** [mholt/caddy#1504]
I must be missing something, I can't get the feature added for https://github.com/mholt/caddy/issues/1293 to work (PR #1500).  Don't think I could re-open those, so posting new issue (sorry).

Running caddy this way:

```
bin/caddy -ca https://acme-staging.api.letsencrypt.org/directory -http-port 8080 -https-port 8433
```

Then I hit my https://caddy.mydomain.com

I do see what looks like a 404 in the log:

```
127.0.0.1 - - [08/Mar/2017:03:56:26 +0000] "GET /.well-known/acme-challenge/K-S0qZZm14npxfyc8WqrWG40L1ZkEJUFelNuSb0ocxE HTTP/1.1" 404 14
```

I do see files created:

```
$ ls -lthr /home/dave/.caddy/acme/acme-staging.api.letsencrypt.org/users/default/
total 8
-rw-------  1 dave  dave   288B Mar  8 03:56 default.key
-rw-------  1 dave  dave   643B Mar  8 03:56 default.json
```

Chrome browser shows ERR_SSL_PROTOCOL_ERROR

openssl shows
```
# openssl s_client -showcerts -connect caddy.mydomain.com:443
CONNECTED(00000003)
24800973474784:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:/usr/src/lib/libssl/ssl/../../libssl/src/ssl/s23_clnt.c:441:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 326 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
---
```

Would appreciate any help.  Don't understand why working for others but not for me.  Thanks!

**Comment by mholt** [comment]
What's your entire Caddyfile?

**Comment by dncohen** [comment]
Here's Caddyfile:

```

0.0.0.0:8443 {
        #tls self_signed
        tls {
                max_certs 10
        }
        root examples/markdown

        markdown / {
                template blog templates/blog.html
                template index templates/index.html
        }
        log caddy.log
        errors caddy.err
}

0.0.0.0:8080 {
        root examples/markdown
        markdown / {
                template blog templates/blog.html 
                template index templates/index.html
        }
        log caddy-8080.log
        errors caddy-8080.err
}
```

Running with -log produced:

```
2017/03/08 09:19:36 https://0.0.0.0:8443
2017/03/08 09:19:36 http://0.0.0.0:8080
2017/03/08 09:19:59 [INFO] Obtaining new certificate for caddy.electricgroups.com
2017/03/08 09:19:59 [INFO][caddy.electricgroups.com] acme: Obtaining bundled SAN certificate
2017/03/08 09:19:59 [INFO][caddy.electricgroups.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/qBLCdtbut6Mk4KKsVj-xxT8LKKK2kOsDvHZ4qcUdmdI
2017/03/08 09:19:59 [INFO][caddy.electricgroups.com] acme: Could not find solver for: dns-01
2017/03/08 09:19:59 [INFO][caddy.electricgroups.com] acme: Trying to solve TLS-SNI-01
2017/03/08 09:20:01 [INFO] Obtaining new certificate for 6da8f83a592ffd5b83de9ef63a89bda1.7d7abc45e836cc5fb4c25ede4e3b548e.acme.invalid
2017/03/08 09:20:06 http: TLS handshake error from 127.0.0.1:22859: [caddy.electricgroups.com] failed to get certificate: acme: Error 400 - urn:acme:error:connection - Failed to connect to 45.63.92.49:443 for TLS-SNI-01 challenge
Error Detail:
        Validation for caddy.electricgroups.com:443
        Resolved to:
                45.63.92.49
        Used: 45.63.92.49


2017/03/08 09:20:06 [INFO][6da8f83a592ffd5b83de9ef63a89bda1.7d7abc45e836cc5fb4c25ede4e3b548e.acme.invalid] acme: Obtaining bundled SAN certificate
2017/03/08 09:20:06 http: TLS handshake error from 127.0.0.1:12342: caddy.electricgroups.com: throttled; refusing to issue cert since last attempt on 2017-03-08 09:20:06.645827527 +0000 UTC failed
2017/03/08 09:20:06 http: TLS handshake error from 127.0.0.1:45891: [6da8f83a592ffd5b83de9ef63a89bda1.7d7abc45e836cc5fb4c25ede4e3b548e.acme.invalid] failed to get certificate: acme: Error 400 - urn:acme:error:malformed - Name does not end in a public suffix
```

I suspect there's good clues in there, but not quite enough for me to spot what's wrong.

**Comment by mholt** [comment]
@dncohen Are you _absolutely sure_ that port 443 is accessible to the outside and is being forwarded to 8443?

**Comment by dncohen** [comment]
Appreciate your help!

Changing 0.0.0.0 to caddy.electricgroups.com makes caddy not accept the tcp traffic forwarded from relayd.  This made it caddy fail right away
```

$ bin/caddy -ca https://acme-staging.api.letsencrypt.org/directory -http-port 8080 -https-port 8433 -log /tmp/caddy.log
Activating privacy features...2017/03/08 17:16:25 [caddy.electricgroups.com] failed to get certificate: acme: Error 400 - urn:acme:error:connection - Failed to connect to 45.63.92.49:443 for TLS-SNI-01 challenge
Error Detail:
        Validation for caddy.electricgroups.com:443
        Resolved to:
                45.63.92.49
        Used: 45.63.92.49
```
and made relayd log an error.
```
relay tcp_forwarder, session 155 (1 active), 0, 66.133.109.36 -> 127.0.0.1:8443, socket error
```
The above is true with out the tls clause in Caddy file, or with `tls myemail@mydomain.com`.  I couldn't get just `tls` to work when I commented out max_certs.

In order to test is 443 being forwarded to 8443, I went back to 0.0.0.0, and removed the `tls` clause.  Then visited http://caddy.electricgroups.com:443 (not https not https) and Caddy served the page.  So I do believe tcp traffic is being forwarded to 8443.

If you have any further suggestions, please let me know!

**Comment by mholt** [comment]
Thanks for the info, I was able to replicate this.

**Comment by mholt** [comment]
@dncohen I am only seeing that behavior when my port is not correctly being forwarded. When I set up port forwarding, it worked correctly.

I ran Caddy (with `-https-port 8443`) with this Caddyfile, with port 443 NOT being forwarded to 8443:

```plain
:443
tls {
	max_certs 2
}
```

And saw the exact same output you are reporting. Notice that my site's address is on port 443; that was an accident on my part, but interestingly, this was the only test run that produced what you are seeing. This makes sense, though: when the "obtaining new certificate" begins, LE attempts to make a special TLS connection using the name `6da8f83a592ffd5b83de9ef63a89bda1.7d7abc45e836cc5fb4c25ede4e3b548e.acme.invalid` for SNI. Caddy on port 443 hears it, but has no certificate to serve up for that handshake on that port, so the connection fails.

I then forwarded the port 443 -> 8443, and everything worked as you would expect.

I then fixed my Caddyfile:

```plain
:8443
tls {
	max_certs 2
}
```

This also succeeded, as expected.

I then turned off the port forwarding, and tried again with this corrected Caddyfile, but still set `-https-port 8443`. It failed, but without the log entries related to the special token SNI (`6da8f83a592ffd5b83de9ef63a89bda1.7d7abc45e836cc5fb4c25ede4e3b548e.acme.invalid`), which makes sense, because nothing is listening on port 443 anymore to serve that handshake.

I suspect that your Caddy instance must be listening on 443 still... either that or something is wonky with your port forwarding. But everything on my end checks out and this is working correctly.

**Comment by dncohen** [comment]
Thanks for that, Matt.  I'll do more investigating and let you know.  Really appreciate your time.  Esp if this turns out to all be on my end.

**Comment by mholt** [comment]
Sorry, I just don't know what else to tell ya at this point. Feel free to update with more information as you get it. :)

**Comment by dncohen** [comment]
I've retried, with some changes to the way I'm forwarding packets, but still not successful.

Earlier we noticed the `...acme.invalid` error.  I believe that line comes from there is already a ~/.caddy/acme directory, generated from earlier attempts to connect.

When I delete that directory and restart, the errors look like below.

I tried to reach the same acme-challenge URL shown in the log.  When I try, I see Caddy's 404 error page.  I think it is reaching caddy at that point, but caddy is not answering the challenge.

```
2017/03/12 18:11:03 [INFO] Obtaining new certificate for caddy.electricgroups.com
2017/03/12 18:11:04 [INFO] acme: Registering account for
2017/03/12 18:11:04 [INFO][caddy.electricgroups.com] acme: Obtaining bundled SAN certificate
2017/03/12 18:11:04 [INFO][caddy.electricgroups.com] AuthURL: https://acme-staging.api.letsencrypt.org/acme/authz/GZ9uk58tXy8F5Sl9TssH-C41eg9xh76Gl8CwoBy3z70
2017/03/12 18:11:04 [INFO][caddy.electricgroups.com] acme: Trying to solve HTTP-01
2017/03/12 18:11:05 http: TLS handshake error from 172.56.38.58:48722: [caddy.electricgroups.com] failed to get certificate: acme: Error 403 - urn:acme:error:unauthorized - Invalid response from http://caddy.electricgroups.com/.well-known/acme-challenge/WOznvR4uLqJr-Z_FxGicObr6_9IsoinSLPvKq4y41tA [45.63.92.49]: 404
Error Detail:
        Validation for caddy.electricgroups.com:80
        Resolved to:
                45.63.92.49
        Used: 45.63.92.49


2017/03/12 18:11:06 http: TLS handshake error from 172.56.38.58:52952: caddy.electricgroups.com: throttled; refusing to issue cert since last attempt on 2017-03-12 18:11:05.892125687 +0000 UTC failed
```

**Comment by mholt** [comment]
> I tried to reach the same acme-challenge URL shown in the log. When I try, I see Caddy's 404 error page. I think it is reaching caddy at that point, but caddy is not answering the challenge.

The URL changes for every new challenge, so Caddy won't answer it.
