### ISSUE TITLE
Add oauth2_proxy support

### ISSUE THREAD

**Issue by tracker1** [mholt/caddy#1506]
I came across [oauth2_proxy](https://github.com/bitly/oauth2_proxy) and was thinking it would be a *really* nice feature for caddy to support oauth2 authentication... since it would take yet another server and/or configuration detail away from something that needs to be added/maintained/developed.

**Comment by mholt** [comment]
You mean like [this plugin](https://github.com/captncraig/caddy-oauth)? (Pinging @captncraig :wink:)

Thanks for your request Michael! I also think this would be a fantastic feature for Caddy. I know Craig is busy but gosh I really liked where that plugin was going. I'll close this issue now in favor of that repo but I do hope it'll work out. Maybe he'd like some contributions.
