### ISSUE TITLE
Caddy seems to not forward the authorization headers

### ISSUE THREAD

**Issue by skorokithakis** [mholt/caddy#1508]
I recently upgraded to Caddy 0.9.5 from 0.9.3 and I notice an odd breakage: Caddy's proxy directive doesn't forward the `Authorization` header any more. I am doing basic auth on caddy, but also relying on the proxied server getting that authorization, but this broke after the upgrade.

Here's my config:

~~~
hostname.com {
    gzip
    log /var/log/caddy/hostname.log
    header / Strict-Transport-Security "max-age=31536000; includeSubdomains";
    basicauth / user1 htpasswd=../../../../etc/caddy/htpasswd
    basicauth / user2 htpasswd=../../../../etc/caddy/htpasswd
    basicauth / user3 htpasswd=../../../../etc/caddy/htpasswd
    proxy / http://localhost:5232/ {
        transparent
    }
}
~~~

**Comment by skorokithakis** [comment]
As I suspected, this was removed in #1325 because double authentication was deemed useless. I'm afraid that was misguided, as my use case is not that I'm doing *authentication* twice, but that I'm *reusing the username* of the first authentication for the second.

I like having all my auth done by Caddy, because I can then have a single authentication source, but, since a user already authenticated, I would like to reuse this authentication upstream. However, the change in #1325 breaks this workflow, as it doesn't allow me to use `header_upstream` to add either the `{>Authorization}` header or the `{remote_user}`, thus completely removing my upstream's knowledge of who authenticated.

This is much worse than "double-dipping", because it means that now I must legitimately perform authentication twice, which is very inconvenient for everyone. Given that I don't even have the passwords from my users in a format that I can add to the upstream service, I'm forced to tell everyone that they just can't authenticate to the service any more.

**Comment by skorokithakis** [comment]
Also, even if you disagree with this, there's no rationale in completely removing the `Authorization` header so I can't use it (or `remote_user`) in `header_upstream` to work around this issue.

**Comment by mholt** [comment]
I took out the Authorization header upon successful authentication because of https://github.com/mholt/caddy/issues/1324 - but the username is now stored on the context of the request: https://github.com/mholt/caddy/commit/977a3c322631b41b534f079e2466689f9aa3d3f7

Rather than passing the password upstream when it's not needed, and if all you need is the username, we could add a `{remote_user}` placeholder. Then you could set a header going upstream with that information in your proxy directive. Would that work?

**Comment by skorokithakis** [comment]
Wasn't that added in #1426? Regardless, I don't think that will work with Radicale (which is what I'm using), because it only expects to parse the username from a custom header, and I doubt Caddy can base64-encode the placeholder :/

Can the Authorization header be removed after the proxy directive has been evaluated, so people can readd it with a `header_upstream` directive?

**Comment by mholt** [comment]
Do you have a moment to try something? Can you take out the line of code in basicauth that strips the header, and then use this in your proxy directive:

```plain
header_upstream -Authorization
```

And see if it does indeed prevent the Authorization header from being sent? (It should, I think.)

If so, I suppose I can revert my change, as it was more of a "this would be a good idea but isn't super-critical for security I guess" change...

**Comment by skorokithakis** [comment]
Sure, let me try to build it and I'll report back. For what it's worth, I agree with you that people who don't trust their backend can just strip the header off (but why aren't people trusting their backends)?

**Comment by skorokithakis** [comment]
Actually, can I just use an older version? I don't have Go 1.8 anywhere...

**Comment by mholt** [comment]
@skorokithakis Maybe... I know we've worked on the proxy/header code recently though. (I would test it but I'm on my way out the door for today.)

**Comment by skorokithakis** [comment]
I tested `header_upstream Authorization ""`, which properly cleared the header. I tried to test `-Authorization` but 0.9.1 choked, I'll try a more recent version.

**Comment by skorokithakis** [comment]
0.9.4 doesn't remove it with `-Authorization`... I'll try building 0.9.5.

**Comment by skorokithakis** [comment]
Alright, yes, I can confirm that removing that line and removing the auth header does what you'd expect (removes the auth header) with the latest master.

**Comment by mholt** [comment]
Excellent. In that case, I will remove the line in basicauth that strips the header, essentially reverting my change.

**Comment by skorokithakis** [comment]
Great, thank you!

**Comment by sandrozbinden** [comment]
When will this feature be in a new release?
