### ISSUE TITLE
"executable file not found in PATH" when using startup with &

### ISSUE THREAD

**Issue by jpoehls** [mholt/caddy#151]
I'm getting the error `exec: "&": executable file not found in $PATH` when I use:

```
startup "& ./env/bin/python ./jdarc/manage.py runserver localhost:8000"
```

Caddy version: 0.7.1

If I just remove the `&` portion then it works fine, but of course blocks caddy from starting up.

Am I doing something wrong here?

Full Caddyfile:

```
localhost:5001 {
	startup "& ./env/bin/python ./jdarc/manage.py runserver localhost:8000"
	log access.log
	gzip
	proxy / localhost:8000
}
```

**Comment by mholt** [comment]
The command goes first; put the ampersand at the end, after the command and its arguments.

**Comment by jpoehls** [comment]
Gah. That worked. Thanks!

Related: I think it would be a more obvious if we had both `startup` and `startupd` perhaps. Sorry to bikeshed if that's already been hammered out. :)

**Comment by mholt** [comment]
No problem, I thought about that but ultimately decided to go with the bash-style syntax since Caddy doesn't really daemonize the process. Glad it's working for you!
