### ISSUE TITLE
[feat] Configuration API

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#1516]
I'd like to be able to configure Caddy in a very dynamic fashion that allows for defaults, templates, per-site configuration, and fallbacks.

The basic structure of the hierarchy would be something like this:

```
global
  default_email :john@foobar.net

caddy
  maxconn 8192
  maxmem 4096
  modules
    - caddyfile
      allow true
    - api
      allow true

tls
  templates [root tls scope]
    - my-template-name
      modules
        - acme
          acme provider (letsencrypt.org, etc)
          email :default_email
          tos true (or string url)
          san www.*
  global [root tls scope, loaded before domains scope]
  defaults [root tls scope, loaded after domains scope]
    modules
      - acme
    use template: my-template-name
  domains [per-site scope, after global and before defaults]
    - example.com
    - example.net
      modules [ local scope ]
        - acme
          san foo.example.net,bar.example.net,baz.example.net
    - example.org
      modules [ local scope ]
        - acme
          acme provider bettertls.example.com
          email joe@example.com

http
  templates [root http scope]
    - my-template-name
      modules
        - redirect
          nowww true
  global [root tls scope, loaded before local]
    paths
      - /assets/com.jquery/
      modules
        - jquery
          filepath /srv/www/assets/com.jquery/
      - gzip
        extensions html,css,js,json,txt,bmp
  defaults
    modules [root http, fallback]
      - serve
        pathname /srv/www/:hostname
    use template: my-template-name
  domains [per-site scope, use defaults as fallback]
    - example.com
      modules
        - serve
          pathname /home/joe/www/example.com
    - example.net
    - example.org
      modules [ local scope ]
        - acme
          acme provider bettertls.example.com
          email joe@example.com

dns
    (same pattern)

smtp
    (same pattern)
```

This is very generic and very extensible allowing for all sorts of adoption patterns which can be communicated directly in json, and a subset of it could easily be translated to the caddy file format (or yaml or xml) for less generic, more streamlined, use cases.

The end-user doesn't need to be any the wiser

**Comment by mholt** [comment]
Hey AJ, thanks for the feature request! Just scanning this initially, what comes to mind is that this could make an ideal Caddyfile Loader plugin: https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-Caddyfile-Loader

These kinds of plugin are simply a function that gets passed the server type that is being run ("http", "dns", etc.) and it returns a `caddy.Input` (a Caddyfile with which to configure Caddy).

Here's how I foresee this being implemented so far: the plugin would load your configuration file (with whatever templated syntax you prefer) and then convert it to Caddyfile. It may mean there is some duplication in the Caddyfile result -- that's okay, it won't be seen by humans at all in this case, and parsing and executing the Caddyfile only happens once when the server is starting (or restarted) -- never during request-time when performance is critical.

The disadvantage to this approach is that somewhere in the plugin's logic, a mapping of some sort from your template to the current Caddyfile syntax will be required. It's possible that a large amount of the manual mapping here could be reduced if the template format borrowed keywords and directives from the Caddyfile.

The advantage of this approach, however, is that it will work _right now_ without having to require all plugins to change or implement some new config interface to match the templating syntax.
