### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by kirillDanshin** [mholt/caddy#1520]
Hi @mholt! Thanks for such awesome project.

Is [`{name of copyright owner}`](https://github.com/mholt/caddy/blob/master/LICENSE.txt#L189) really your name? :)

**Comment by mholt** [comment]
Hey Kirill, thanks for your feedback. That line is part of the appendix, which is not part of the license. It's just some generic recommendations.

**Comment by kirillDanshin** [comment]
@mholt please look at readme, nettls_*.go and /3rd-Party Licenses. is it ok that I copied caddytls into gramework to integrate it with fasthttp and gramework itself? should I change something?

**Comment by mholt** [comment]
@kirillDanshin Thanks for reading the license. :) Yes, that's fine. Thank you for the credit.
