### ISSUE TITLE
Dynamic DNS Update Plugin

### ISSUE THREAD

**Issue by geek1011** [mholt/caddy#1525]
It would be nice to have a dynamic dns update plugin. 

The plugin would be able to:
- Use the DNS providers which can be configured with caddy to update
- Support the /nic/update method of updating
- Call a custom update url with an optional username and password at a user-specified interval
- Be a part of a server entry in the Caddyfile

Example configurations:

````
www.example.com {
    dynamicdns {
        type nicupdate
        url http://mydynamicdnsprovider/nic/update
        username test
        password test
        interval 5m
    }
}
````

````
mycomputer.example.com {
    dynamicdns {
        type dnsprovider
        provider dnsimple
        interval 1h
    }
}
````

````
*.example.com {
    dynamicdns {
        type custom
        url http://myusername@example.com/update/{domain}/{ip}
        interval 10s
    }
}
````

I might work on this myself if I can find the time.

**Comment by mholt** [comment]
Thanks for your interest again @geek1011! Like the last issue, I'll close this since third-party plugins are developed outside of this repository. Feel free to propose this [in our forums](https://forum.caddyserver.com) where the idea can be discussed with other developers!
