### ISSUE TITLE
Allow hashing password for basicauth directive

### ISSUE THREAD

**Issue by geek1011** [mholt/caddy#1526]
It would be better if the password used for basicauth could be stored as a hash in the file.

**Comment by geek1011** [comment]
I think this could be added by adding a new type of matcher which matches hashes, and by having the sha sum in the config prefixed with `sha1=` (similarly to `htpasswd=`)

**Comment by pbeckmann** [comment]
I think it's already discussed here: https://github.com/mholt/caddy/issues/1142

**Comment by tobya** [comment]
@geek1011 thank you for the issue, I think we should keep the discussion of hashed passwords on issue #1142

**Comment by mholt** [comment]
@pbeckmann @tobya You both are right, this is a duplicate issue, thank you for flagging it as such! This is an odd case though, since #1142 ended up really confusing. Let's start fresh with this issue. So, sorry to revert your actions on this issue -- normally I wouldn't.

**Comment by tobya** [comment]
@mholt  no problem. 

Now that sha1 seems to be compromised, what hash should be used as the default for a feature like this?

**Comment by mholt** [comment]
My vote is for a bcrypt or scrypt hash. Might also be worth requiring a salt.

**Comment by jeremiahmegel** [comment]
What would be the format for hashed/salted passwords? Others in #1142 have [suggested](https://github.com/mholt/caddy/issues/1142#issuecomment-250432123) the format used by [htpasswd](https://httpd.apache.org/docs/current/misc/password_encryptions.html) and [shadow](http://man7.org/linux/man-pages/man3/crypt.3.html#NOTES) (i.e. `$algorithm$salt$encrypted`), which I would agree with, though this could break backwards compatibility for a very small number of users (those whose passwords follow the pattern `$…$…$…`).

**Comment by pbeckmann** [comment]
I would hold my opinion from https://github.com/mholt/caddy/issues/1142 again, and suggest to give the possibility to use different algorithms and prefix the hash with sth like `bcrypt=`. This would enable us to enable backward-compatibility and to use different algorithms.
Another way to succeed this, would be to use different attributes and different the algorithms with those. This has the benefit to use the existing configuration way.

**Comment by mholt** [comment]
I never really liked htpasswd style. I bet we can do better.

Also, the choice of hash algorithms should be limited to those which are cryptographically secure.

**Comment by mhoIt** [comment]
And now, go away because caddy is being discontinued. I hate caddy

**Comment by mholt** [comment]
(Disregard any comment notifications you may have gotten from a user account that _looked like mine_ earlier today.)

**Comment by pbeckmann** [comment]
Just a small update: I'm currently experimenting with this feature. And I will implement this.

**Comment by 20zinnm** [comment]
Anyone interested in using multihashes to support multiple hash algorithms? https://github.com/multiformats/multihash

**Comment by My1** [comment]
I would say a crypt-style hash format whch includes all the needed params, also for the simple reason that is a common format already and therefore also works with other solutions for storing passwords. e.g. one could have a website for password change which could then update the password file accordingly for example, and also in my opinion a very important thing. humans can easily recognize, read and understand the format, and see if a password hash is garbage (e.g. a bcrypt with a work factor of 5).

@20zinnm multihash looks intresting but has a few weaknesses. most importantly that it isnt designed to work with highly parametric hashes like bcrypt or argon2 where you can just plug in one or more work factors because the function, also looking at the function list of multihash this also doesnt seem to be made for password hashes anyway. no salts no nothing.

**Comment by zul-jin** [comment]
Any update on this?

**Comment by tobya** [comment]
Not really.  We would be delighted if someone would like to submit a PR for this.  I will add it to list for Hacktoberfest

**Comment by whalehub** [comment]
@mholt Are there still plans to implement this feature in Caddy?

**Comment by tobya** [comment]
We are happy to recieve a PR to implement this feature.

**Comment by mholt** [comment]
Caddy 2 will revise how authentication is handled; either this will not be (as) relevant or this will be possible.
