### ISSUE TITLE
Inconsistent / unexpected behavior while proxying grafana

### ISSUE THREAD

**Issue by brasilikum** [mholt/caddy#1532]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Use caddy as a proxy for Grafana

### 3. What is your entire Caddyfile?
```text
georg-hartmann.com {
  redir / https://www.linkedin.com/in/georg-m-hartmann
}

grafana.georg-hartmann.com {
  proxy / localhost:3000 {
  }
  log /home/freebsd/caddy.log
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`sudo caddy -conf /usr/local/www/Caddyfile`

### 5. Please paste any relevant HTTP request(s) here.
https://grafana.georg-hartmann.com
(paste curl command, or full HTTP request including headers and body, here)

### 6. What did you expect to see?
The grafana login form

### 7. What did you see instead (give full error messages and/or log)?
The browser showed that a https connection has been established and the favicon loads. The screen keeps being white.
Most of the time the first reload showed showed the desired page, sometimes only the second.

If you access georg-hartmann.com:3000 directly, the grafana loginform is visible on the first load.

```
[IP REMOVED] - [24/Mar/2017:23:35:50 +0000] "GET / HTTP/2.0" 302 29
[IP REMOVED] - [24/Mar/2017:23:35:50 +0000] "GET /login HTTP/2.0" 200 7704
[IP REMOVED] - [24/Mar/2017:23:35:51 +0000] "GET /public/css/fonts.min.css HTTP/2.0" 200 9463
[IP REMOVED] - [24/Mar/2017:23:35:54 +0000] "GET /public/css/grafana.dark.min.b4255f90.css HTTP/2.0" 200 184916
[IP REMOVED] - [24/Mar/2017:23:36:00 +0000] "GET /public/app/boot.6d63bd8b.js HTTP/2.0" 200 589824
[IP REMOVED] - [24/Mar/2017:23:36:02 +0000] "GET /public/img/fav32.png HTTP/2.0" 200 3607
[IP REMOVED] - [24/Mar/2017:23:36:06 +0000] "GET /login HTTP/2.0" 200 7704
[IP REMOVED] - [24/Mar/2017:23:36:12 +0000] "GET /public/app/boot.6d63bd8b.js HTTP/2.0" 206 622592
[IP REMOVED] - [24/Mar/2017:23:36:16 +0000] "GET /login HTTP/2.0" 200 7704
[IP REMOVED] - [24/Mar/2017:23:36:19 +0000] "GET /public/app/boot.6d63bd8b.js HTTP/2.0" 206 430130
[IP REMOVED] - [24/Mar/2017:23:36:21 +0000] "GET /public/img/grafana_icon.svg HTTP/2.0" 200 5764
[IP REMOVED] - [24/Mar/2017:23:36:21 +0000] "GET /public/fonts/opensans/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2 HTTP/2.0" 200 15572
[IP REMOVED] - [24/Mar/2017:23:36:21 +0000] "GET /public/fonts/grafana-icons.ttf?okx5td HTTP/2.0" 200 29748
[IP REMOVED] - [24/Mar/2017:23:36:21 +0000] "GET /public/fonts/opensans/k3k702ZOKiLJc3WVjuplzOgdm0LZdjqr5-oayXSOefg.woff2 HTTP/2.0" 200 16276
[IP REMOVED] - [24/Mar/2017:23:36:24 +0000] "GET /public/fonts/fontawesome-webfont.woff?v=4.2.0 HTTP/2.0" 200 65452
```

```text


### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
1. Install caddy
2. Install grafana
3. Start grafana (default config)
4. Start caddy (provided config)

**Comment by mholt** [comment]
Thanks for opening a detailed issue, @brasilikum! 

But, hmm, it works for me, every time. Browser issue probably? Try with curl, verify that any number of the other things in your stack isn't causing the problem (network, browser, grafana, etc...) -- you'll have to convince me/us this is an issue in Caddy specifically.
