### ISSUE TITLE
[Suggestion] Proxy having primary/secondary upstreams

### ISSUE THREAD

**Issue by francislavoie** [mholt/caddy#1535]
So I have this use-case where I need to have two servers with the same application, but the application is not built in such a way that load balancing would work correctly right now (would need changes to session management, some weird stuff with websockets that would complicate things by having two connection backends since they would need to share information etc, but that's besides the point).

As a short term solution, I'd like to set up a failover solution so that if the primary server no longer responds, I could automatically have the secondary server pick up the slack in the meantime. The primary server's DB would always be acting like a master (both reads and writes) and replicating to the secondary.

I don't see a way to set that kind of rule for the `proxy` directive in Caddy. Basically always use the primary server unless the health check fails, in which case use the secondary.

Would that be something that could be implemented?

Thanks

**Comment by mholt** [comment]
Good news, that's what this does: https://github.com/mholt/caddy/pull/1513

So it's just a matter of building from source or waiting until the next release. :+1:

**Comment by francislavoie** [comment]
Oh, my bad. Thanks 😀
