### ISSUE TITLE
Automatic HTTPS gives 301 and forwards to port 2015

### ISSUE THREAD

**Issue by mathwhiz1212** [mholt/caddy#1538]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Set up domain.com and domain.org with automatic HTTPS.

### 3. What is your entire Caddyfile?
```
domain.com {

root /var/www/caddy/public

fastcgi / unix:/run/php/php7.0-fpm.sock {
log berean.log
ext .php
split .php
index index.php

}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
sudo setcap cap_net_bind_service=+ep ./caddy
screen -S caddy ./caddy -conf=cf
```

I running Ubuntu 16.04 Server `uname -a` returns: 
```
Linux hostname 4.4.38-std-1 #1 SMP Mon Dec 12 10:45:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
### 5. Please paste any relevant HTTP request(s) here.
```
Host: domain.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

### 6. What did you expect to see?

My website on https://domain.com/

### 7. What did you see instead (give full error messages and/or log)?

Caddy returns a 301 moved permanently header, forwarding me to https://domain.com:2015/ which returns error because Caddy isn't listening on port 2015.

Return headers:

```
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Date: Sun, 26 Mar 2017 22:23:31 GMT
Location: https://domain.com:2015/
Server: Caddy
Status: 301 Moved Permanently
X-Firefox-Spdy: h2
```

Curl command `curl -v https://domain.com/`

Response:
```
*   Trying 111.111.111.11...
* Connected to domain.com (111.111.111.11) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 704 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: domain.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=domain.com
* 	 start date: Sun, 26 Mar 2017 21:51:00 GMT
* 	 expire date: Sat, 24 Jun 2017 21:51:00 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> GET / HTTP/1.1
> Host: domain.com
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=UTF-8
< Location: https://domain.com:2015/
< Server: Caddy
< Status: 301 Moved Permanently
< Date: Sun, 26 Mar 2017 23:25:56 GMT
< Content-Length: 0
< 
* Connection #0 to host domain.com left intact
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Download Caddy v0.9.5 with git middleware. Use the caddyfile above. Run with `./caddy -conf=cf`. Try to visit https://domain.com/

**Comment by mholt** [comment]
Thanks for the detailed issue @mathwhiz1212 ! That makes assessing the problem much easier.

I used your Caddyfile and the same curl command and did not get a 301 (I saw an expected 404, no index file).

(Also, you should move your `log` directive outside of fastcgi.)

So, that's weird. I'm not sure what's going on here. Does it still happen if you remove the fastcgi directive? Try an empty Caddyfile, etc.

**Comment by brasilikum** [comment]
@mathwhiz1212, have you tried to open the page in an other browser (or anonymous mode)? I have seen some weired behavior recently as well, and I suspect some kind of browser optimization (caching?) for redirects, because it followed a recent configuration that I had since then changed.

**Comment by mholt** [comment]
Looks like (s?)he's using curl.

**Comment by brasilikum** [comment]
@mathwhiz1212 I found the answer (at least for my behavior) here:

http://stackoverflow.com/questions/1393280/http-redirect-301-permanent-vs-302-temporary
> Browser: if a browser finds 301 status code then it caches the mapping of the old URL with the new URL, the client/browser will not attempt to request the original location but use the new location from now on unless the cache is cleared.

My guess is that you used 'redir' instead of 'proxy' in your Caddyfile at some point.
Clear your browsercache and you should be fine.

**Comment by brasilikum** [comment]
> Looks like (s?)he's using curl.
Uff, missed that!

**Comment by mathwhiz1212** [comment]
@mholt You're welcome. If I remove the fastcgi section there is no issue. I'll have to figure out what's causing the issue.

**Comment by mholt** [comment]
Knowing that taking out fastcgi fixes it led me to a hypothesis but I did a quick check which proved it false, indeed, by the time the fastcgi middleware is set up, the host and port information is properly set to domain.com:443, not :2015. So I suspect something strange with your PHP backend, not the fastcgi middleware. If you can show otherwise, feel free to reopen!

Also, why not just use the `php` preset?
