### ISSUE TITLE
Unable to set BasicAuth username placeholder for access log, header directive overrides

### ISSUE THREAD

**Issue by jamesboswell** [mholt/caddy#1543]
### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5  (fbd6412359be76bcfbb2ba5cfdecbc273e040674)

### 2. What are you trying to do?
Log BasicAuth username to access.log with custom {user} placeholder

### 3. What is your entire Caddyfile?
```text
localhost {
  tls off

  log / /tmp/access.log "{remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
  errors /tmp/error.log

  radiusauth {
          server 127.0.0.1:1812 127.0.0.1:9012
          secret testing123
          realm  "RADIUS Auth"
          except /public /img
          cache /tmp
          cachetimeout 60
          }

  root /var/www/hugo

  fastcgi / 127.0.0.1:9000 php

  # Hardening headers
  header / {
    X-Content-Type-Options "nosniff"
}

}

localhost/img {
  tls off
  basicauth / bob hello
  log / /tmp/access.log "{remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} \"{>Referer}\" \"{>User-Agent}\""
  errors /tmp/error.log
  root /data/tmp/img/

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Testing local checkout
`go run main.go -conf ~jboswell/caddyfile3`

### 5. Please paste any relevant HTTP request(s) here.
```
curl -I -u bob:hello http://localhost:2015
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 7363
Content-Type: text/html; charset=utf-8
Etag: "nqf40l5oj"
Last-Modified: Tue, 23 Jun 2015 22:05:09 GMT
Server: Caddy
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Tue, 28 Mar 2017 22:28:03 GMT
```
### 6. What did you expect to see?
Expect to see "bob" in the access log,  instead see  "-"

### 7. What did you see instead (give full error messages and/or log)?
```
::1 - - [28/Mar/2017:18:28:03 -0400] "HEAD / HTTP/1.1" 200 0 "-" "curl/7.53.1"
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
On Mac,   `brew install freeradius-server`
`vim /usr/local/etc/raddb`
find `canonical user` and edit to set a simple user and password such as 
```
# The canonical testing user which is in most of the
# examples.
#
bob     Cleartext-Password := "hello"
        Reply-Message := "Hello, %{User-Name}"
```

Start radius with  `radiusd -X`    
Add radiusauth plugin to Caddy
Add radiusauth directives to Caddyfile
Add header directives to Caddyfile
Start Caddy

**Header directive will override {user} placeholder**
Remove header from Caddyfile;  restart Caddy,  {user} will work

(Please strip away any extra infrastructure such as containers, reverse proxies, upstream apps, dependencies, etc, to prove this is a bug in Caddy and not an external misconfiguration. Your chances of getting this bug fixed go way up the easier it is to replicate. Thank you!)

**Comment by jamesboswell** [comment]
This issue is fixed by https://github.com/mholt/caddy/pull/1937

A big thank you @kujenga for your work on 1937!  Awesome to have this issue fixed.   thank you as well to @tobya and @mholt

**Comment by tobya** [comment]
Now that #1937 is merged I will push a PR later in the week.
