### ISSUE TITLE
Could you please add QR code generation to filemanager

### ISSUE THREAD

**Issue by deathrush** [mholt/caddy#1544]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 3. What is your entire Caddyfile?
```text
(Put Caddyfile here)
```

### 5. Please paste any relevant HTTP request(s) here.

(paste curl command, or full HTTP request including headers and body, here)

### 6. What did you expect to see?
add QR code generation to filemanager

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

(Please strip away any extra infrastructure such as containers, reverse proxies, upstream apps, dependencies, etc, to prove this is a bug in Caddy and not an external misconfiguration. Your chances of getting this bug fixed go way up the easier it is to replicate. Thank you!)

**Comment by mholt** [comment]
Hi @deathrush - thank you for your feature request. This is the issue tracker for Caddy, but filemanager is a 3rd party plugin, as noted in the [docs](https://caddyserver.com/docs/filemanager):

<img width="703" alt="screen shot 2017-03-28 at 8 39 15 pm" src="https://cloud.githubusercontent.com/assets/1128849/24436088/9f6097e8-13f6-11e7-8a1c-eeb4012976b1.png">

So, please feel free to file this issue at https://github.com/hacdias/caddy-filemanager. Thanks!
