### ISSUE TITLE
Log documentation doesn't match the code

### ISSUE THREAD

**Issue by rickb777** [mholt/caddy#1549]
The documentation for log (https://caddyserver.com/docs/log) describes the rotation using the keywords 'size', 'age' and 'keep'.

These don't work. The reason is obvious from the source code: https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/roller.go

The keywords are listed as 'roller_size', 'roller_age' and 'roller_keep'.

One of these is incorrect. I suggest that the source code should be altered to match the documentation.

**Comment by mholt** [comment]
Are you running from master? The documentation is for the latest release.

**Comment by rickb777** [comment]
Yes. Have they been renamed somewhere?

**Comment by mholt** [comment]
Yep, they're changing in the next release. Log rolling will be enabled by default and we get rid of the nested block for configuring rolling. Thanks for your question!

**Comment by rickb777** [comment]
ok no worries

**Comment by rickb777** [comment]
I tried to use it but failed so I dug around to find out why.

**Comment by mholt** [comment]
Props for digging. We'll have everything updated at the 0.10 release.
