### ISSUE TITLE
Status replaced with 200 if request body isn't blank when using filters

### ISSUE THREAD

**Issue by Niosop** [mholt/caddy#1552]
Using Caddy 0.9.5 

```text
example.com {

  proxy / https://127.0.0.1:4443 {
    insecure_skip_verify
    transparent
  }

  filter rule {
    content_type   application/javascript.*
    search_pattern http://
    replacement "https://"
  }

  filter rule {
    content_type   text/css.*
    search_pattern http://
    replacement "https://"
  }

  tls example@example.com
  timeouts 5m
  log / syslog "remote={remote} host={host} method={method} uri=\"{uri}\" status={status} size={size} latency={latency}"
}

```

When proxying and using filters, it seems if the request body contains anything, Caddy will change the status code to 200.

The following PHP file will cause Caddy to return a 200 to the client (but log a status of 303 to its log file).

```
<?php
  header('Location: https://example.com/t2.php', true, 303);
  print("Here's some data!");
  die();
?>
```

Going directly to the upstream server results in a 303 as expected.

If you remove the print statement, then the 303 is returned to the client properly.  Alternatively, commenting out the filter code results in proper redirection as well.

**Comment by Niosop** [comment]
Just realized filter issues should be sent to that maintainer.  Feel free to close this if you feel it's an issue w/ the filter project and not with how Caddy handles extensions.  Will post this over there as well.

**Comment by mholt** [comment]
Yep, this seems to be related to the `filter` plugin, so I'll let the author of that take care of it. Thank you!

**Comment by Niosop** [comment]
Actually seems to be fixed in a version downloaded today, so looks like a fix he put in 6 days ago made it to the build server.  Don't remember when the version I was using was built.  Sorry for the false alarm.

**Comment by mholt** [comment]
No problem, thanks @Niosop.
