### ISSUE TITLE
Can not use Chinese url?

### ISSUE THREAD

**Issue by zuohuadong** [mholt/caddy#1553]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?
0.9.5

### 2. What are you trying to do?
like：
https://www.drixn.com/categories/%E6%95%99%E7%A8%8B/
Can‘t find~

**Comment by tobya** [comment]
Hi thanks for the issue. Can you provide some more detail? Your full caddy file and the full error you are receiveing

**Comment by zuohuadong** [comment]
look, my files name is "中文" , 

`http://45.77.17.111:2015/中文`

Encode is

`http://45.77.17.111:2015/%E4%B8%AD%E6%96%87`

But I can not access it

**Comment by zuohuadong** [comment]
Nginx is  successful in 80

`http://45.77.17.111/中文`

http://45.77.17.111/%E4%B8%AD%E6%96%87

**Comment by tobya** [comment]
Can you please provide 

1. Your full Caddfile 
2. What version of Caddy are you running?
2. How are you running caddy, what is the command line

Can you access another not chinese character file in the same directory?

**Comment by tobya** [comment]
I can fine a chinese characgter file 

http://chard.kinchik.ie/%E4%B8%AD%E6%96%87.txt

with no difficulty, so there must be something else going on.

**Comment by zuohuadong** [comment]
thaks， utf8 is OK
