### ISSUE TITLE
custom middleware want httpserver.Logger to do log by itself

### ISSUE THREAD

**Issue by Zeymo** [mholt/caddy#1554]
We add a WAF middleware  to caddy , and it want we injure the `httpserver.Logger.Logger`as io.Writer  since they want do log by itself. If we treat it's scope as sitconfig(like TLS) ,this leads to circular dependencies. 

it hope to do log separate with `main` log that write `/home/tmp/waf.log` but which lifecycle also managered by `httpserver.Logger`

httpserver.plugin
```
caddytls.RegisterConfigGetter(serverType,func(c *caddy.Controller) *waf.Config { 
return GetConfig(c).Waf })
```

struct define maybe
```
type waf  struct {
   log      *httpserver.Logger
   client  *waf.Proxy
   ...
}
```

In waf.Proxy
```
func SetLog(l *log.Logger) {
	std_log = l
}
```

**Comment by Zeymo** [comment]
resolve it

**Comment by mholt** [comment]
Hey @Zeymo, thanks for your question. How did you resolve it?

**Comment by Zeymo** [comment]
Hey @mholt , Exactly I just take a shortcut to meet the demand😝 

I just move `log.go` and `roller.go` to top level package (e.g. caddy)  which  change waf  dependencies and also effect other middleware (e.g. `log` , `error`)

then setup file block like 
```
waf {
        config_server_url http://xxx.yyy
        conn_num  4
        timeout 10
        log ./waf.log {
            rotate_size 1
            rotate_age 1
            rotate_keep 3
        }
}
```

parser llike
```
waf.log = &framework.Logger{
		Output: path,
	        Roller: logRoller,
}
waf.log.Attach(c)
...
c.OnStartup(func() error {
		waflog.SetLog(waf.log.Logger)
		waf.client.Init()
		return nil
})
```
I‘m a  new-come for caddy , to some extent, the solution is ugly and I hope official resolver 😄

**Comment by mholt** [comment]
Nice work hacking what you needed into it! Thanks for sharing.
