### ISSUE TITLE
Health check fails when using insecure_skip_verify

### ISSUE THREAD

**Issue by francislavoie** [mholt/caddy#1556]
### 1. What version of Caddy are you running (`caddy -version`)?

Compiled from source, this commit: https://github.com/mholt/caddy/commit/a148b923810f2c10f6015d1db82666d6b1aaf7a7

### 2. What are you trying to do?

Load balancing using `first` policy https://github.com/mholt/caddy/pull/1513

### 3. What is your entire Caddyfile?

```text
https://<domain> {

  proxy / https://10.0.1.5 {
    policy first

    health_check /health
    health_check_interval 30s
    health_check_timeout 60s

    transparent
    websocket
    insecure_skip_verify # Use self-signed certs on servers
    fail_timeout 5s
    try_duration 5s

    # Additional servers
    upstream https://10.0.1.6
  }

  log /var/log/caddy/access.log
  errors /var/log/caddy/error.log

  tls <email>
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Docker, using the below Dockerfile (alpine currently only has Go 1.7.3, so I had to use someone else's `alpine-golang` which includes Go 1.8)

```Dockerfile
FROM nimmis/alpine-glibc
MAINTAINER Francis Lavoie <flavoie@bluink.ca>

ENV GOROOT=/goroot \
    GOPATH=/gopath \
    GOBIN=/gopath/bin \
    PATH=${PATH}:/goroot/bin:/gopath/bin \
    CADDY_REPO_OWNER=mholt \
    CADDY_REPO_NAME=caddy \
    CADDY_BRANCH=a148b923810f2c10f6015d1db82666d6b1aaf7a7 \
    CADDYPATH=/root/.caddy \
    SRVPATH=/srv \
    UID=192 \
    GID=192

RUN addgroup -g $GID -S caddy \
 && adduser -u $UID -g $GID -S caddy

RUN apk add --update musl curl \
 && apk upgrade \
 && apk add --no-cache build-base libcap git \
 && curl https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz | tar xzf - -C / \
 && mv /go /goroot \
 && mkdir -p $GOPATH/src/github.com/$CADDY_REPO_OWNER \
 && cd $GOPATH/src/github.com/$CADDY_REPO_OWNER \
 && git clone https://github.com/$CADDY_REPO_OWNER/$CADDY_REPO_NAME \
 && cd $CADDY_REPO_NAME \
 && git checkout $CADDY_BRANCH \
 && go get github.com/$CADDY_REPO_OWNER/$CADDY_REPO_NAME/... \
 && mv $GOPATH/bin/caddy /usr/bin \
 && setcap cap_net_bind_service=+ep /usr/bin/caddy \
 && apk del --purge build-base go curl \
 && mkdir -p $CADDYPATH \
 && rm -rf $GOPATH $GOROOT /var/cache/apk/*

EXPOSE 80 443 2015
VOLUME ["$CADDYPATH"]
WORKDIR "$SRVPATH"
ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout"]
```

### 5. Please paste any relevant HTTP request(s) here.

N/A

### 6. What did you expect to see?

A properly proxied request. Works fine with `health_check` commented out.

### 7. What did you see instead (give full error messages and/or log)?

If I enable `health_check` I always get `502 Bad Gateway`. The health check endpoint definitely works (see access logs below).

In the error logs I get a bunch of these:

```
31/Mar/2017:19:03:01 +0000 [ERROR 502 /health] no hosts available upstream
```

In the access logs I get either successes if `health_check` is off, or fails if `health_check` is on.

```
<ip> - - [31/Mar/2017:19:04:14 +0000] "GET /health HTTP/2.0" 502 16
<ip> - - [31/Mar/2017:19:06:31 +0000] "GET /health HTTP/2.0" 502 16
<ip> - - [31/Mar/2017:19:06:42 +0000] "GET /health HTTP/2.0" 200 39
<ip> - - [31/Mar/2017:19:31:03 +0000] "GET /health HTTP/2.0" 200 39
```

I think the health check might not be respecting `insecure_skip_verify` or `transparent` rules? Would that be the root cause?

My servers are running Caddy as well, they have Caddyfiles like this:

```
<domain>:443 {
        root /var/www/html/public

        # PHP-FPM
        fastcgi / php-fpm:9000 php {
                index index.php
        }

        # Websocket rewrite to proxy
        rewrite / {
                if {>Connection} has Upgrade
                if {>Upgrade} is websocket
                to /stream
        }

        # PHP URL rewrite rule
        rewrite {
                r .*
                ext /
                to /index.php?{query}
        }

        # Websocket proxy
        proxy /stream sockets:8888 {
                without /stream
                transparent
                websocket
        }

        gzip
        log /var/log/caddy/access.log
        errors /var/log/caddy/error.log

        tls self_signed
}
```

**Comment by pbeckmann** [comment]
I'm currently looking into it. 
I were able to reproduce your problem. But i think it is a general problem in the proxy middleware. Just to be sure, can you just remove the `policy first` line and try it again. AFAIK it shouldn't run too.

**Comment by francislavoie** [comment]
I don't get TLS errors on upstream hosts, because I do `insecure_skip_verify`. Are you running in debug mode to get those or something? I'm not running debug right now. I suspect it's a proxy middleware issue too. `policy first` really doesn't do much different than other policies, so I find it unlikely that it's a problem there.

**Comment by pbeckmann** [comment]
So, looking into the codebase, i think the problem is, that we are creating in https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/upstream.go#L108 a normal http.Client, without any parameters. This client then tries to connect in https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/upstream.go#L360 to the upstream host.

So in conclusing we are ignoring the `insecure_skip_verify` flag for the health check completely.

**Comment by francislavoie** [comment]
Is that something that can be fixed? I understand that could be a volatile change. What do you think @mholt?

**Comment by mholt** [comment]
If the user enables insecure_skip_verify, then we should be sure to do that whenever we are communicating with the upstream, even for health checks. I'm reluctant to have this feature at all, but let's at least make it consistent. I think health checks should respect insecure_skip_verify. Can you help with that @pbeckmann ?

**Comment by francislavoie** [comment]
Thanks. I'm planning on doing this within a private network so I'm not worried about the SSL being valid. Using self signed certs lets the proxy be the front-end for SSL and then I don't need to worry about my upstreams having matching certs or dealing with renewals not getting synced, etc.

**Comment by pbeckmann** [comment]
Yes of course. We just should add 
`Transport: &http.Transport{
	TLSClientConfig: &tls.Config{InsecureSkipVerify: upstream.insecureSkipVerify},
},`
to the http.Client creation. On this way, the client respect the setting. I just don't have a single idea to do tests for this case :D

**Comment by mholt** [comment]
@pbeckmann Maybe just test that the field is set to true or false, instead of a full end-to-end test.

**Comment by pbeckmann** [comment]
@mholt So i tried to get the field. Without and with reflection. Unfortunately the field is not accessible. So the only way, i see at the moment, would to submit a PR without a test.

**Comment by mholt** [comment]
@pbeckmann Go ahead and submit what you have. :) I'll catch up on PR reviews soon, I am thankful that some people are helping with that.

Have you tried using a type assertion? Either way, we'll take a look.

**Comment by francislavoie** [comment]
Thanks! Closing this.

**Comment by francislavoie** [comment]
Unfortunately I think I need to re-open this. I'm still getting the same behaviour as before the merge. I recompiled with the latest from master (https://github.com/mholt/caddy/commit/7d15435361c95aa029be244f962b47950487a539). I get `502 Bad Gateway`. My Caddyfile is the same as in the OP. Any ideas to help debug? Maybe order matters for the settings in the Caddyfile here (I hope not)?

**Comment by mholt** [comment]
@francislavoie What's in the error log, and process log too for good measure? Make sure you use the `errors` directive and the `-log` CLI option.

**Comment by francislavoie** [comment]
Stdout logs, running in docker, full command is: `caddy --conf /etc/Caddyfile --log stdout`
```
caddy_1  | Activating privacy features... done.
caddy_1  | http://<snip>
caddy_1  | 2017/04/11 16:25:18 http://<snip>
caddy_1  | https://<snip>
caddy_1  | 2017/04/11 16:25:18 https://<snip>
```

Error logs:
```
11/Apr/2017:16:18:28 +0000 [ERROR 502 /] no hosts available upstream
11/Apr/2017:16:18:33 +0000 [ERROR 502 /favicon.ico] no hosts available upstream
11/Apr/2017:16:18:43 +0000 [ERROR 502 /] no hosts available upstream
11/Apr/2017:16:18:48 +0000 [ERROR 502 /favicon.ico] no hosts available upstream
11/Apr/2017:16:21:14 +0000 [ERROR 502 /] no hosts available upstream
11/Apr/2017:16:21:15 +0000 [ERROR 502 /] no hosts available upstream
11/Apr/2017:16:21:21 +0000 [ERROR 502 /favicon.ico] no hosts available upstream
11/Apr/2017:16:21:37 +0000 [ERROR 502 /] no hosts available upstream
11/Apr/2017:16:21:42 +0000 [ERROR 502 /favicon.ico] no hosts available upstream
```

Access logs:
```
72.139.43.38 - - [11/Apr/2017:16:18:28 +0000] "GET / HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:18:33 +0000] "GET /favicon.ico HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:18:43 +0000] "GET / HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:18:48 +0000] "GET /favicon.ico HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:21:14 +0000] "GET / HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:21:15 +0000] "GET / HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:21:21 +0000] "GET /favicon.ico HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:21:37 +0000] "GET / HTTP/2.0" 502 16
72.139.43.38 - - [11/Apr/2017:16:21:42 +0000] "GET /favicon.ico HTTP/2.0" 502 16
```

**Comment by mholt** [comment]
Hmm, it should be working; we have a test that verifies that InsecureSkipVerify is set properly.

Could you recompile with a log.Print or fmt.Print line here: https://github.com/mholt/caddy/blob/7d15435361c95aa029be244f962b47950487a539/caddyhttp/proxy/upstream.go#L379 - and see if that is what is causing it? Try to print the error message, maybe we should consider writing this to a log anyway.

**Comment by mholt** [comment]
Huh, I dunno about Dockerfiles but you shouldn't need to fork it... just pull from this repo and make the one-line change and run `go run main.go`.

**Comment by francislavoie** [comment]
The Dockerfile does the git clone, I never have the repo on my host
filesystem. Look at the Dockerfile in the OP to see how it runs :)

**Comment by mholt** [comment]
Right, I just mean that this would be so much simpler without Docker. But, whatever floats your boat is fine. :+1: Thanks for helping investigate!

**Comment by francislavoie** [comment]
So I tried this, I see no output in stdout. Maybe I did it wrong?

https://github.com/francislavoie/caddy/compare/7d15435...HEAD

**Comment by mholt** [comment]
@francislavoie Aye, that should do it -- if you aren't seeing any output, then either you didn't run the re-compiled code, or it's not the same issue and we can close this. If the latter, then your backend is legitimately down. If the former, well, I can't help much since I don't use Docker - just be absolutely sure you're running the latest code.

**Comment by francislavoie** [comment]
Alright, that last one was my bad, I had a problem in my Dockerfile that caused it not to recompile. Oops.

I'm getting these logs:

```
caddy_1  | Upstream status: &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Type:[text/plain; charset=utf-8] Server:[Caddy] X-Content-Type-Options:[nosniff] Date:[Tue, 11 Apr 2017 19:13:20 GMT] Content-Length:[20]] 0xc42019f3c0 20 [] false false map[] 0xc42000bd00 0xc4200138c0}
caddy_1  | Upstream status: &{404 Not Found 404 HTTP/1.1 1 1 map[Server:[Caddy] X-Content-Type-Options:[nosniff] Date:[Tue, 11 Apr 2017 19:13:19 GMT] Content-Length:[20] Content-Type:[text/plain; charset=utf-8]] 0xc42024c500 20 [] false false map[] 0xc420244100 0xc420013b80}
```

Which leads me to believe that it's because it's not passing the upstream headers on the health check request. My upstream is a caddy server (see OP for the Caddyfile) which specifies a hostname, so I need the `Host` header to be passed along. The headers from `transparent` and `websocket` aren't being used in the http client for health checks.

**Comment by mholt** [comment]
@francislavoie That's a good point, we don't pass the headers upstream for healthchecks.

Since this issue is already quite long and about something else, would you mind opening a new issue for this? You don't have to follow the whole bug template, just link to this issue and say what needs to happen.

If you want an intro to Go, I'd recommend this is a good way to start. :) All you have to do is modify that health check function to do something like this: https://github.com/mholt/caddy/blob/7d15435361c95aa029be244f962b47950487a539/caddyhttp/proxy/proxy.go#L185-L191 - I'd welcome a PR, I'm pretty swamped before the next release in 9 days.

Either way -- thanks!

**Comment by francislavoie** [comment]
Sounds good :+1: I'll take a shot at it.
