### ISSUE TITLE
502 errors when proxing requests

### ISSUE THREAD

**Issue by Cinerar** [mholt/caddy#1557]
### 1. What version of Caddy are you running (`caddy -version`)?

/bin # caddy --version
Caddy 0.9.5

### 2. What are you trying to do?
proxy requests from docker container with caddy to docker container with apache

### 3. What is your entire Caddyfile?
```text
https://mytestsite.net
{
timeouts 1m
proxy /videostore storeprestashop:80 {
transparent
}
tls myemail
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Inside docker container
```
FROM alpine:3.5
RUN curl --silent --show-error --fail --location \
      --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
      "https://caddyserver.com/download/build?os=linux&arch=amd64" \
    | tar --no-same-owner -C /usr/bin/ -xz caddy \
 && chmod 0755 /usr/bin/caddy
ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile", "--http2=false"]
```
### 5. Please paste any relevant HTTP request(s) here.

GET /videostore/dolphin/themes/transformer/cache/v_15_00e76f8380a81db6c64071f3ff124d0d.js HTTP/1.1

### 6. What did you expect to see?
[31/Mar/2017:23:00:36 +0000] "GET /videostore/dolphin/themes/transformer/cache/v_15_00e76f8380a81db6c64071f3ff124d0d.js HTTP/1.1" 200 100587 "https://mytestsite.net/videostore/dolphin/" "Mozilla/5.0 (Windows NT 6.3; WO                                                       W64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

### 7. What did you see instead (give full error messages and/or log)?
SOMETIMES i see 502 (bad gateway) in browser for some images and/or js this happens one in a while, sometimes i need to press ctrl+f5 in browser 20+ times

31/Mar/2017:23:00:36 +0000 [ERROR 502 /videostore/dolphin/themes/transformer/cache/v_15_00e76f8380a81db6c64071f3ff124d0d.js] dial tcp: lookup storeprestashop on 127.0.0.11:53: dial udp 127.0.0.11:53: operation was canceled

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
...

I believe it is same issue or at least related to:
https://github.com/mholt/caddy/issues/1345 
but there it states that it is fixed in 0.9.5 and i'm still having it.

**Comment by mholt** [comment]
Did you try extending timeouts (or disabling them) and if you could try building from source on Go 1.8, I wonder if it's a bug that's been fixed in Go 1.8.

**Comment by Cinerar** [comment]
timeouts 1m are already in caddyfile 
will try to build from source later today, but i thought this bug affects only http2

**Comment by Cinerar** [comment]
Ok built from source with golang:1.8 
caddy -version
Caddy 0.9.5 (+ce47cf5 Sat Apr 01 10:19:03 UTC 2017)
no 502 errors after couple thosands of retries

Any plans when it will be on https://caddyserver.com/download ?

**Comment by mholt** [comment]
@Cinerar Yep! See our launch event for the date, and we'll have technical details then too.

**Comment by Magic815** [comment]
So I believe I'm having the same issue, but in Caddy v0.10.3 - should this have been fixed by that version? Or is building from source with Go 1.8 still needed? Just trying to figure out if I need to make a new issue request here on github.

**Comment by elcore** [comment]
You need to use Go 1.8.X

**Comment by Magic815** [comment]
Got it. I don't have any experience building from source, but will look into it.

Is Go 1.8.X something that will natively be a part of Caddy at some point, though? Just curious in case it might be easier for me to just wait for a certain release.

**Comment by Cinerar** [comment]
@Magic815  Versions after 0.9.5 should have this bug fixed, so probably you have something else.

**Comment by ZeekoZhu** [comment]
I got the same problem with caddy 0.10.4 in docker
I fixed it by running caddy on host directly, but I know that is not a good solution...
