### ISSUE TITLE
Concurrent map writes crash

### ISSUE THREAD

**Issue by jleclanche** [mholt/caddy#1560]
Not sure if this is the same as #1045.

Caddy 0.9.5, with modules `realip`, `ratelimit` and `cloudflare`.

Crash log: https://gist.github.com/beheh/2c5e69ad1fbb46c5ed4d777e1066b696

**Comment by jleclanche** [comment]
Service file:
```
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network.target
Wants=network.target

[Service]
User=www-data
Group=www-data
Environment=HOME=/opt/caddy CLOUDFLARE_EMAIL=admin@example.com CLOUDFLARE_API_KEY=redacted
ExecStart=/opt/caddy/caddy --log /opt/caddy/caddy.log --agree=true --conf=/opt/caddy/Caddyfile --root=/var/tmp --email=admin@example.com
ExecReload=/bin/kill -USR1 $MAINPID
LimitNOFILE=1048576
LimitNPROC=64

[Install]
WantedBy=multi-user.target
```

**Comment by mholt** [comment]
Looks like the trace shows it happening in the ratelimit plugin, I'll ping @xuqingfeng about it, and ask that this issue be migrated to that repository. Thanks!

**Comment by xuqingfeng** [comment]
@jleclanche I fixed this issue a few weeks ago - see https://github.com/xuqingfeng/caddy-rate-limit/issues/8

Can you build `caddy` from source with the latest `ratelimit` based on https://github.com/mholt/caddy/issues/1341#issuecomment-271672886 and give it another try?

**Comment by jleclanche** [comment]
@xuqingfeng Does downloading from the site build ratelimit from source?

**Comment by mholt** [comment]
No, I have to update it. But the current build server will not receive any more updates from me, as a new site is coming to replace it in 2 weeks.

**Comment by jleclanche** [comment]
An update of the ratelimit plugin would be nice then, it's a pretty serious issue :) I'll do a custom build locally for the time being but yeah.

**Comment by mholt** [comment]
Sorry. For multiple reasons, I won't be able to update the current build server anymore. But in 2 weeks the plugin developers can do their own deploys and I'm off the hook. :smile:
