### ISSUE TITLE
Caddy tries to mkdir . (why?), but permission denied

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#1565]
Caddy v0.9.5

I was debugging the infamous systemd script that everyone seems to want so that, y'know, caddy would be easier to use and install (but that the maintainers seem to actively disavow and lock issues and throw people off to the never ending stream of forum posts)... only to find that one of the bugs may actually reside in caddy itself.

```
root@proxy-dev:~# sudo -u www-data CADDYPATH=/etc/ssl/caddy /usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
Activating privacy features...2017/04/06 21:47:13 [WARNING] Stapling OCSP: no OCSP stapling for [test.example.com]: ocsp: error from server: unauthorized
 done.
2017/04/06 21:47:13 mkdir .: permission denied
```

If I change into any directory where the user running caddy has permissions to write, it seems to work without the `permission denied` error. In system scripts the default directory is `/`... hence so many troubles.

Why is it trying to create the current directory?

**Comment by elcore** [comment]
Hi,

I am using the service file without any issues (slightly modified), I will try it on a new (and fresh) server.

See you tomorrow 😄 

ping @wmark

**Comment by elcore** [comment]
Hi @coolaj86,

I could not wait 😄, I cannot reproduce this error (Ubuntu 16.10) (I used the original service file and your command)

**Comment by mholt** [comment]
Thanks for taking a look, @elcore .

@coolaj86 When Caddy starts, it will attempt to allocate disk space for TLS assets such as certificates and OCSP staples inside the CADDYPATH. A system call is made with `os.MkdirAll()`, and I _believe_ this call ends up doing `mkdir` for each component of the path. If a directory already exists, it should ignore that and move on to the next component; at least, this is how I understand it. Maybe something funny with the permissions in the system? This is just my hypothesis; I could be totally wrong.

What if you run `mkdir -p /etc/ssl/caddy/ocsp` (from the same state you were in when you got the permissions error from caddy; i.e. the directories don't exist yet) _as the www-data user_? Take care to run it from the same directory from which you're running caddy.

**Comment by coolaj86** [comment]
It's true, it could be funkiness.

I'll admit had to try a bunch of different things and it worked on one system and didn't work on another until I had the startup script change the working directory and made sure that the directory that it needs existed with the correct permissions and then it worked. It appeared to be an issue of the current working directory, but it very well may have been something else. `mkdir .: permission denied` is somewhat ambiguous.

Would totally be great if there were an `install.sh` (and an `install.bat`) that would just detect the system that you're on and do the Right Thing (TM).

The process for getting this installed as a proper system service currently requires a lot of documentation and a lot of trial and error (as evidenced by the abundance of issues and forum threads about it) that would do well to be scripted away to the "will work for most people that aren't doing extremely weird things".

I've done that for node at the os level: https://git.daplie.com/coolaj86/node-install-script/tree/master

(the same set of scripts that I mentioned when talking about the curl downloader)

I'm imagining that on Linux you don't have to determine the nitty gritty of "is it systemd or upstart or initv", but you can just install the script into each folder (if it exists) and whichever system is in use will become the default.

Since you can't reproduce and I've spent all the hours of debugging that I'm willing to spend I'll just close this issue.

**Comment by wmark** [comment]
> I was debugging the infamous systemd script 

Try the initial one. I don't recognize the current one. ;-)

> In system scripts the default directory is `/`…, hence so many troubles.

Might be the case for some *init daemons*, but the statement itself in its absolute is not correct. But yes, ideally you'd want to set a well-defined *working directory*, as seen by `PWD` by its first process.

> maintainers seem to actively disavow

Please, don't be offensive.

Back to the issue.  
Based on @mholt's comment I suspect you overlooked creating those folder(s). Link goes to the old README file:
https://github.com/mholt/caddy/blame/bee9c50a71c61962c070c0b700b014d46a5b15ce/dist/init/linux-systemd/README.md#L27-L29

**Comment by coolaj86** [comment]
> > I was debugging the infamous systemd script

> Try the initial one. I don't recognize the current one. ;-)

Yeah... why was the set_cap stuff removed? That should probably be turned back on. That's one source of perms problems right there.

> > maintainers seem to actively disavow

> Please don't be corrosive.

Yeah, I came in a little hot.

You have no idea how many issues and forum posts and SO posts I found as I was encountering about every error that anyone encounters during this process and the one person would be saying "hey, I got this perms error" or whatever and the other answered with something like "we don't support community contributed scripts, I'm closing this", or "caddy is so easy to use it doesn't need an installer" and such.

There's nothing polite about responding with "I don't care about your problem and it's not important, go somewhere else" and such. Someone can use polite words to say it, but the polite thing to do would be to "cc/ @whomever wanna take a look at this?" (exactly as was done in this issue) or to just let someone who does care answer.

That said, I do the same thing on my repos sometimes (particularly with package managers and build tools and such - because they *are* annoying), but this *is* a server so it kinda needs support for the things it does as a server. It's critical to the use case.

> I suspect you overlooked creating those folder(s)

They existed, but they may have had the wrong permissions somewhere along the way.

I encountered:

* the PAM error where you can't run the service because it failed to run too many times: somehow having the server run as `www-data` and wanting to do `root`-y things in `root`-y places would cause it to be black listed for a time
* bind permission errors (80, 443) because set_cap was required
* `mkdir .` permission error... no idea what that was about

Between the various errors and switching back and forth between trying as root, and as www-data and as my own current user and chown-ing and chmod-ing it may be that the ocsp folder had bad perms... but it appeared that the most immediate change I had made when reporting the error was only changing the directory from which I was running the command and since it said `.` as the folder (and CADDYPATH was set), I assumed it was the current folder which I was in that was the `.` and when I changed folders it seemed to go away.

Anyway, thanks for the direction. I'll have to take a look at the comments on the merge request and see what I can update to make it more useful to the greatest number of people.

**Comment by wmark** [comment]
**systemd** does not need permissions set on the binary *suid*-style: Directives for ambient capabilities etc. have been available since v229 and have been used. This minimum version has been documented, but eventually a change slipped through, dumbing down the file in favour of old habits.

Other *init*-daemons don't need this as well. You can just use `chpst`. I've given an example in a different ticket. No idea which.

Most *Caddy* users are not familiar with running a server, and whenever a »hard-earned« achievement whose symptom is »but it runs like this« gets a »you'd better«, disappointment follows. The perceived »do it this way, and this way only« is sometimes not understood as benevolent, but as patronizing. Key is not to compare estimated experience(s) (the sum of our mistakes we've learned from ;-) ), which is exceptionally hard especially in this field, but to trust.

We care. Reviewed PR's are testament to this. See you there!

**Comment by mholt** [comment]
@coolaj86 

> mkdir .: permission denied is somewhat ambiguous.

I wish I could change that, but that's just the error returned from the `os` package, and that error I believe originates from the system call. Still, to try to improve on it, I do have long-term plans to elaborate on error messages based on context (with translations to other languages) but probably not before 1.0.

I second @wmark's sentiment:
> We care. Reviewed PR's are testament to this. See you there!

We're trying to make the project the best we can, so I appreciate your feedback AJ. I'm hoping the init scripts in this repo is a temporary solution only.

**Comment by coolaj86** [comment]
Fixed the problem... once and for all?

https://git.daplie.com/Daplie/caddy-installer

**Comment by elcore** [comment]
>Fixed the problem... once and for all?
>
>https://git.daplie.com/Daplie/caddy-installer

Yes and No!!!!!

**Comment by coolaj86** [comment]
@elcore ??

**Comment by elcore** [comment]
@coolaj86 It will solve issues for *some* users

**Comment by wmark** [comment]
This is a closed issue!

**Comment by elcore** [comment]
> This is a closed issue!

@wmark We are talking about the installer :smile:

**Comment by mholt** [comment]
Please do that on the forum or the other, open issue. Thanks ;)

**Comment by coolaj86** [comment]
Doesn't matter if it's closed, it still gets SEO and people who are having the problem I was having will still come across this hoping for a resolution... like the 10 or 15 forum posts and issues I came across while trying to figure this out that didn't have a clear resolution.

On some parts of the web it's considered polite to go back and update your previous posts with "Here's the quick fix!", y'know?

**Comment by mholt** [comment]
(@coolaj86 I wasn't referring to you, sorry.)
