### ISSUE TITLE
Caddy how to use something like ngx_pagespeed.

### ISSUE THREAD

**Issue by ibenchu** [mholt/caddy#1569]
Caddy how to use something like ngx_pagespeed.

**Comment by ibenchu** [comment]
https://github.com/pagespeed/ngx_pagespeed

**Comment by mholt** [comment]
The correct answer is plugins! Caddy already has standard directives for gzip and HTTP/2 -- which alone makes a lot of pagespeed optimizations obsolete. There's a minify plugin for Caddy, and Caddy also serves pre-compressed .gz and .br files.
