### ISSUE TITLE
filemanager: can't disallow new file upload with basicauth

### ISSUE THREAD

**Issue by windymindy** [mholt/caddy#1570]
### 1. What version of Caddy are you running (`caddy -version`)?
CADDY 0.9.5 32-bit for windows

### 2. What are you trying to do?
I was checking https://caddyserver.com/docs/filemanager example with bassicauth right at the bottom of the doc.

### 3. What is your entire Caddyfile?
filemanager /admin {
    show           ./
    allow_commands false
    admin:
    allow_commands true
    allow_command  rm
    allow_command  mv
    allow          dotfiles
    manager:
    block          /admin/financial
    editor:
    allow_new      false
    block          /admin/financial
}

basicauth /admin admin pass
basicauth /admin manager pass
basicauth /admin editor pass

### 6. What did you expect to see?
I expected user editor not to be able to upload new files through filemanager.

### 7. What did you see instead (give full error messages and/or log)?
Despite what is said in the doc, editor can successfuly upload new files.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Just run Caddy with sample Caddyfile. Navigate to /admin, enter editor/pass credentials and drag any file into browser window or press Upload button.

**Comment by pbeckmann** [comment]
Hey.
thx for the bug report.
But as stated at https://caddyserver.com/docs/filemanager. The bug occurs in an addon. So the bug report should be send there. Maybe you could copy and paste it to https://github.com/hacdias/caddy-filemanager/issues?

Thanks

**Comment by mholt** [comment]
I second @pbeckmann's advice, this looks like a question for the filemanager repository. Fortunately, Henrique is very helpful! He can help you more than we can.

**Comment by windymindy** [comment]
I am sorry. I wasn't paying attention.
https://github.com/hacdias/caddy-filemanager/issues/83

**Comment by mholt** [comment]
It's okay, I need to try to make it clearer anyway. Thank you!
