### ISSUE TITLE
quic protocol cause caddy exit unexpectedly with POST request 

### ISSUE THREAD

**Issue by everpcpc** [mholt/caddy#1572]
### 1. What version of Caddy are you running (`caddy -version`)?

`Caddy 0.9.5`

### 2. What are you trying to do?

POST in quic protocol

### 3. What is your entire Caddyfile?
```text
https://saki.everpcpc.com {
    header / Server  "{host}"
    root /home/everpcpc/www/
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`/usr/local/bin/caddy -agree=true -email=xxx@xxx.com -conf=/etc/caddy/caddy.conf -pidfile=/var/run/caddy.pid -quic`

`Ubuntu 16.04 with systemd`

### 5. Please paste any relevant HTTP request(s) here.

POST https://saki.everpcpc.com

### 6. What did you expect to see?

`response header`
```text
date: xxxx
last-modified: xxxx
server: saki.everpcpc.com
etag: W/"xxxxxxxx-x"
content-type: text/html; charset=utf-8
status: 200
accept-ranges: bytes
content-length: 7
```

`response content`
```text
さき
```

### 7. What did you see instead (give full error messages and/or log)?

`response header`
```text
last-modified: xxxxxx
server: saki.everpcpc.com
etag: W/"xxxxxxxx-x"
content-type: text/html; charset=utf-8
status: 200
content-length: 7
accept-ranges: bytes
alt-svc: quic=":443"; ma=2592000; v="36,35,34"
alternate-protocol: 443:quic
```

`response content is empty`
```text
```

`error log`
```text
caddy[107761]: panic: interface conversion: io.ReadCloser is struct { io.Reader; io.Closer }, not *h2quic.requestBody
caddy[107761]: goroutine 74 [running]:
caddy[107761]: panic(0x9ca1c0, 0xc420296a00)
caddy[107761]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
caddy[107761]: github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest.func1(0xc420287680, 0xc4201004b0, 0xc4200b40f0, 0x0, 0xd1e3a0, 0xc42039a1a0)
caddy[107761]: #011/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:193 +0x17c
caddy[107761]: created by github.com/lucas-clemente/quic-go/h2quic.(*Server).handleRequest
caddy[107761]: #011/home/caddy/go/src/github.com/lucas-clemente/quic-go/h2quic/server.go:202 +0x628
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

The config above is already the minimal case. 
I created the POST request with *request maker* extension in `Chrome 56.0.2924.87 (Official Build) (64-bit)`.

**Comment by mholt** [comment]
Hi @everpcpc - thank you for filing a bug report. I have good news, this has already been reported in numerous issues such as #1519 and fixed. It will be released in less than two weeks!
