### ISSUE TITLE
wildcard host does not resolve multi-level subdomains

### ISSUE THREAD

**Issue by eipiminus1** [mholt/caddy#1578]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
I use caddy as a reverse proxy in front of multiple applications, one of which needs many (multi-level) subdomains.

### 3. What is your entire Caddyfile?
As an minimal example I put together this config:

```text
*.example.org:80 {
  redir http://google.com/
}

:80 {
  redir http://yahoo.com/
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy is executed in a docker environment with the following command:
`docker run --rm -it -v `pwd`/Caddyfile:/etc/Caddyfile -v `pwd`/:/srv/ abiosoft/caddy`

### 5. Please paste any relevant HTTP request(s) here.

```bash
# curl example.org
<a href="http://yahoo.com/">Moved Permanently</a>.

# curl sub.example.org
<a href="http://google.com/">Moved Permanently</a>.

# curl sub2.sub.example.org
<a href="http://yahoo.com/">Moved Permanently</a>.
```

### 6. What did you expect to see?

```bash
# curl example.org
<a href="http://yahoo.com/">Moved Permanently</a>.

# curl sub.example.org
<a href="http://google.com/">Moved Permanently</a>.

# curl sub2.sub.example.org
<a href="http://google.com/">Moved Permanently</a>.
```

### 7. What did you see instead (give full error messages and/or log)?
see 5.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
start caddy in a folder where the above Caddyfile is present and add
```text
127.0.0.1 example.org
127.0.0.1 sub.example.org
127.0.0.1 sub.sub.example.org
```
to your /etc/hosts file.

**Comment by mholt** [comment]
Hi @eipiminus1, this isn't a bug; a `*` in the hostname only applies to one label as per the spec. If you want two subdomains, you simply need `*.*.example.com`, etc.

**Comment by eipiminus1** [comment]
Hey @mholt, thanks for pointing that out. And btw thanks for all the great work on caddy! I love the simplicity.
