### ISSUE TITLE
Caddy 0.9.5 on Windows checks propagation via Google DNS, Linux uses host resolvers

### ISSUE THREAD

**Issue by obrienmd** [mholt/caddy#1580]
### 1. What version of Caddy are you running (`caddy -version`)
0.9.5 for Windows and Linux

### 2. What are you trying to do?
Use Automatic HTTPS

### 3. What is your entire Caddyfile?
Same Caddyfiles in Windows and Linux, relevant:
tls myemail@mydomain.com {
  dns cloudflare
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Windows Server 2012 R2: Set env vars for Caddyhome & Cloudflare, then caddy -agree=true -conf=Caddyfile
Ubuntu 16.04.2: Set env vars for Caddyhome & Cloudflare, then caddy -agree=true -conf=Caddyfile

### 5. Please paste any relevant HTTP request(s) here.
n/a

### 7. What did you see instead (give full error messages and/or log)?
On Windows, Caddy checks Google DNS, though the host points to resolvers inside the network. This is good, as the internal resolvers have alternate records for internal-IP  resolution of the hosts. On Linux, Caddy checks the resolvers inside our network, which causes issues.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
n/a

**Comment by obrienmd** [comment]
Hrm, looks like https://github.com/xenolf/lego/blob/master/acme/dns_challenge.go hardcodes to check /etc/resolv.conf and Google DNS. Is there a way to force this to use specific resolvers?

**Comment by mholt** [comment]
@obrienmd I don't think I had noticed this change, thanks for bringing it up.

It looks like (at least part of) it is due to this PR: https://github.com/xenolf/lego/pull/293

I would suggest opening an issue with lego instead; that would be a better place for this discussion. (I wonder if it had something to do with cgo and linux or something...)

**Comment by obrienmd** [comment]
I'll do so - if lego makes it configurable, how would we pass the option through caddy?

**Comment by mholt** [comment]
Depends how lego does it. If it's an env variable, no changes needed. We'll just see.

**Comment by obrienmd** [comment]
For reference, lego issue I created: https://github.com/xenolf/lego/issues/379
