### ISSUE TITLE
Proposal: Add a request id placeholder

### ISSUE THREAD

**Issue by GlurG** [mholt/caddy#1590]
Something similar to what nginx already provides: [$request_id](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_id).
In a microservice design it is common to assign each request an id (also called correlation id) so an error can be traced through all services processing the request.

**Comment by tobya** [comment]
@GlurG Thank you for the feature request.

Can you provide a bit more detail as to how this would be used?  Do you really mean it to be a placeholder to be used in logs and proxy urls?

Would it be added to headers anywhere?

Could you give some more detail about how you would envisage it being used?

**Comment by GlurG** [comment]
Sure,

I'm currently using the $request_id for nginx in the following way:

```
upstream api-gateway {
	server			api-gateway:3000;
}

location /api {
	proxy_pass		http://api-gateway;
	proxy_set_header	X-Request-Id $request_id;
}
```
This way, nginx will generate a unique identifier for each request to /api (which is my [api gateway](http://microservices.io/patterns/apigateway.html)). The header "X-Request-Id" is extracted in the microservice and passed along to all subsequent calls to other microservices. If an error occurrs during the request, the logs will contain the request-id so I can trace all calls between the microservices which generated the error.
You can read more about loggin/correlation ids here: https://homeadvisor.tech/software-antipatterns-microservices/ (under "Logging Can Wait Pitfall")

**Comment by mholt** [comment]
Is generating a request ID just a matter of using math/rand to generate a random string or number of  16 bytes? That's easy enough.

We'd either want to do this in replacer.go where we only attach the request ID to the context if needed (although we might run into the request dereferencing issues holding up #1542) or we should generate it for all requests always in httpserver/server.go and attach it to the request there (which will be safe -- will it be fast?).

**Comment by tobya** [comment]
There seems to be a go package for generating uuids 

https://github.com/nu7hatch/gouuid

Perhaps we could use that.  I think I would favour generating on usage if possible.

**Comment by tobya** [comment]
A few thoughts.

With the issues @mholt raises in mind I was wondering if it was worth having a `request_id` directive?  The requestid could then be generated in `server.go` but only for server blocks that needed it, rather than for ever request - which would be an unnecessary overhead.  `{request_id}` would return '' (or other empty  placeholder value} unless the `request_id` directive was also used.  

eg.  This would be used in the Caddyfile

    example.com {
      root c:\website
      request_id
      header X-Request-Id {request_id}
     }

**Comment by sachinwalia2k8** [comment]
@mholt @tobya there is another UUID that seems to be popular as well: https://github.com/satori/go.uuid
I think either should be fine.

**Comment by Whitestrake** [comment]
I like the directive idea. Could it have an optional [arg...] to specify header(s) to append the resulting request_id upstream and downstream automatically?

**Comment by tobya** [comment]
@Whitestrake I'm not sure if arg on the request_id directive would be needed.  As I see it the request_id indicated that caddy should generate a request_id for every request.  The user can then set any headers or log replacements they like.  

However if there is a very common use case then perhaps we could have a preset that sets a particular header

**Comment by Whitestrake** [comment]
True, but with an optional arg,

```
request_id X-Request-Id
proxy / backend
```

and

```
request_id
header X-Request-Id {request_id}
proxy / backend {
  header_upstream X-Request-Id {request_id}
}
```

are pretty much equivalent. You could do it however you liked. Not needed, obviously, but makes things a fair bit neater, no?

**Comment by tobya** [comment]
This was implemented by @elcore in #1711

**Comment by elcore** [comment]
We both implemented the feature @tobya - - Thank you for your time and effort

**Comment by tobya** [comment]
@glurg can you take a look if this works for you?
