### ISSUE TITLE
No way to disable "insecure CA URL" error in some private networks.

### ISSUE THREAD

**Issue by ntrrgc** [mholt/caddy#1592]
### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
Test my server deployment with virtual machines before deploying it in the public Internet.

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Systemd service inside a CentOS 7 virtualized with libvirt in a Linux host. This same host runs a [Boulder](https://github.com/letsencrypt/boulder) instance, running in Docker, whose port 4000 is forwarded to the host and made accessible to the CentOS 7 server.

```
/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp -ca http://192.168.122.1:4000/directory
```

### 6. What did you expect to see?

There should be a way to use this "fake" CA server so that I can use my servers with a self signed CA.

### 7. What did you see instead (give full error messages and/or log)?

```
caddy[10172]: Activating privacy features...2017/04/18 12:22:54 http://192.168.122.1:4000/directory: insecure CA URL (HTTPS required)
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Set the `-ca` parameter in Caddy to any URL you want to test. The error, if any, is shown before any connection is made.

The actual problem is here in the code: https://github.com/mholt/caddy/blob/6bc3e7536e915c0f7dd0c22be36201760e9d816d/caddytls/client.go#L64-L66

Non HTTPS CAs are only accepted if the host is a loopback address or it starts with `10.` (one of the several prefixes used for private networks in IPv4, but not the one I'm using). I could workaround this in several ways, for instance, running a forwarding daemon in localhost like this:

```
ncat -k -l 4000 -e "$(which ncat) 192.168.122.1 4000"
```

But it is quite hacky. It would be nicer if just a configuration option was added to remove this check, or at least private network ranges were checked properly.

**Comment by mholt** [comment]
Hey @ntrrgc thanks for the issue! How about if we add "192.168." to the list of allowed-insecure prefixes?

**Comment by ntrrgc** [comment]
@mholt It would be an incomplete fix, as those IPv4 addresses between 172.16.0.0 and 172.31.255.255 (inclusive) are also private, so are IPv6 in the `fc00::/7` range plus arguably the link-local range (`fe80::/10`). Also, the host may not be an IP address but a hostname that resolves to one of these IPs.

**Comment by mholt** [comment]
There's still only a small handful of exceptions for (most) internal networks, I think we can hardcode those, even if it means pulling the if statement into a separate function - should be doable and I think it's worth it to forbid HTTP connections at this critical part.

**Comment by francislavoie** [comment]
Closing this since it's been merged. @ntrrgc would you mind trying it out and confirming?

**Comment by ntrrgc** [comment]
It works with IPv4 addresses, but it doesn't with IPv6:

```
❯ ./bin/caddy -ca http://[fc00::1]/ -host example.com -email test@example.com
Activating privacy features...2017/04/21 15:24:27 http://[fc00::1]/: insecure CA URL (HTTPS required)
```

It also does not allow hostnames that resolve to local addresses (you can test it adding a new entry in your `/etc/hosts` pointing to `127.0.0.1`).

**Comment by francislavoie** [comment]
Alright I'll re-open this, enabling loopback is trivial, but my understanding of IPv6 CIDRs is limited, so I'm not sure why `[fc00::1]` doesn't match `fc00::/7`.

**Comment by ntrrgc** [comment]
@francislavoie The IPv6 address is `fc00::1`, but it has to be encoded in a URI as `http://[fc00::1]/` as the colon symbol would otherwise specify the port number. Make sure you are decoding the IPv6 address from the host part correctly: addresses must have no brackets, host strings must have them.

**Comment by francislavoie** [comment]
@ntrrgc you can take a look at the code here if you want to verify: https://github.com/mholt/caddy/pull/1599/files

**Comment by ntrrgc** [comment]
@francislavoie That's where I was looking, and I find quite strange that you mix IPv6 addresses (`::1`, `fc00::1`) with IPv6 URI host parts (`[::1]`, `[fc00::1]`).

**Comment by francislavoie** [comment]
Ah, I see what's happening. So `net.SplitHostPort` does strip the `[]`, but that only works if there's a port. If there's no port we're just taking the input directly.

**Comment by francislavoie** [comment]
Alright I made a PR to fix that issue, but it still needs an additional change to do a host lookup if we do want to support hosts pointing to loopback (e.g. http://lvh.me).

**Comment by francislavoie** [comment]
@mholt what do you think, should hosts pointing to loopback be supported for this? If not, I guess this can be closed again.

**Comment by mholt** [comment]
@francislavoie That seems pretty niche, and I like to avoid lookups whenever possible; let's go ahead and close this. Your patch is pretty good for this issue I think. :+1:
