### ISSUE TITLE
nginx rewrite to caddy rewrite (vue)

### ISSUE THREAD

**Issue by ibenchu** [mholt/caddy#1597]
nginx conf  is ：
```
location / {
             try_files $uri $uri/ @router;
             index index.html;
         }

        location @router {
            rewrite ^.*$ /index.html last;
        }

```

how to use  it

**Comment by francislavoie** [comment]
Questions like this are generally better asked on the [forums](https://forum.caddyserver.com/).

I'll close this for now as it's not really an issue report, but feel free to continue discussing if someone answers your question here.

**Comment by tanpengsccd** [comment]
look here 
https://caddy.community/t/caddy-try-files/3248
