### ISSUE TITLE
Support a way to pass a and address binding from the CLI

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#16]
Heroku assigns each app a dynamic port, we need a way to pass $PORT as the port caddy should listen on. The ideal solution may be to allow a user to pass a Caddyfile snippet from the command-line the way nginx does with it's -g flag. http://nginx.org/en/docs/switches.html

**Comment by mholt** [comment]
Would a -port flag be sufficient? (for now?) e.g. `-port=1234` (Actually, I like the idea of being able to pipe configuration into Caddy. Maybe for later...)

**Comment by j-mcnally** [comment]
Yes that will work for now

On Tuesday, April 28, 2015, Matt Holt <notifications@github.com> wrote:

> Would a -port flag be sufficient? (for now?) e.g. -port=1234 (Actually, I
> like the idea of being able to pipe configuration into Caddy. Maybe for
> later...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mholt/caddy/issues/16#issuecomment-97293945>.
>


-- 

<http://www.kohactive.com>
Justin McNally
Technology Director / Principal
p: 312.273.3074 <+13122733074> | e: justin@kohactive.com | skype:
justinmcnally211 <http://is.gd/UuXAGG>
  <https://github.com/j-mcnally>  <https://twitter.com/j_mcnally>
<https://www.linkedin.com/profile/view?id=143776726>
