### ISSUE TITLE
Minor breaking change in release downloads

### ISSUE THREAD

**Issue by francislavoie** [mholt/caddy#1601]
So previously we could use the assumption that the filenames were in the structure `caddy_<os>_<arch>.tar.gz`, but with `0.10` there's the version number in there.

Just pointing it out, not sure if that's something we want to still keep consistent, I think it would make sense, personally. It made scripting pretty easy to get a specific version like this:

`https://github.com/mholt/caddy/releases/download/v$VERSION/caddy_linux_amd64.tar.gz`

**Comment by mholt** [comment]
Yep, we added the version to the release filenames. It should be pretty consistent from now on, but this was something I always wanted to do; and finally it became feasible/easy. :)

**Comment by francislavoie** [comment]
:+1: 

Also FYI https://github.com/abiosoft/caddy-docker/pull/53, v0.10 is built! :smile: 

Good luck with the event tonight!
