### ISSUE TITLE
Proxy # sign in url 

### ISSUE THREAD

**Issue by Cinerar** [mholt/caddy#1606]
### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.10.0

### 2. What are you trying to do?
 Proxy request

### 3. What is your entire Caddyfile?
```text
localhost:8888 {
  # proxy to "nc -l localhost 9999"
  proxy / http://localhost:9999
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Just  run caddy with this caddyfile

### 5. Please paste any relevant HTTP request(s) here.

```
 curl localhost:8888/test/#/foo
```

### 6. What did you expect to see?
```
nc -l localhost 9999
GET /test/#/foo HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.47.0
Accept: */*
X-Forwarded-For: 127.0.0.1
Accept-Encoding: gzip
```
### 7. What did you see instead (give full error messages and/or log)?
```
nc -l localhost 9999
GET /test/ HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.47.0
Accept: */*
X-Forwarded-For: 127.0.0.1
Accept-Encoding: gzip
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
1. Caddyfile:
```
localhost:8888 {
  #proxy to "nc -l localhost 9999"
  proxy / http://localhost:9999
}
```
2. Run
```
nc -l localhost 9999
```
3. Run
```
curl localhost:8888/test/#/foo
```
4. See
```
GET /test/ HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.47.0
Accept: */*
X-Forwarded-For: 127.0.0.1
Accept-Encoding: gzip
```

@tw4452852 please check it out if you could

**Comment by x2764tech** [comment]
The fragment part (i.e. the #) is evaluated by the client, and not sent to the server.

See [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.5)

**Comment by Cinerar** [comment]
Right. 
So looks like the problem with proxy to RabbitMQ is something else. 
Working with 0.9.4 
Not working with 0.9.5 and 0.10
will try to find out what 
thanks.
