### ISSUE TITLE
Update Documentation about proxy policy "next"

### ISSUE THREAD

**Issue by ckeeney** [mholt/caddy#1608]
On the proxy docs, https://caddyserver.com/docs/proxy, the syntax block shows 
```
policy random | least_conn | round_robin | ip_hash
```

This should be updated to include `next` as an option.  It has been added to the bullet list below but the big syntax-highlighted box is the first place I look.

**Comment by ckeeney** [comment]
Also, the "Policies" section below is missing both `ip_hash` and `first`:


![image](https://cloud.githubusercontent.com/assets/8799010/25298644/a9ee5c3c-26ab-11e7-9d20-56b717e6b0cb.png)

**Comment by francislavoie** [comment]
https://github.com/caddyserver/website/pull/4/files

Made a PR or this 👍

**Comment by mholt** [comment]
I assume you meant "first" -- I'm on it!

**Comment by mholt** [comment]
Wait, nevermind. I was beat.

**Comment by ckeeney** [comment]
I did mean `first`.  I didn't realize the website source was in this repo or I would have opened a pull request.  Thanks.

**Comment by mholt** [comment]
No problem. It's over in https://github.com/caddyserver/website.

**Comment by ckeeney** [comment]
Have you considered moving this repo to that namespace?

**Comment by francislavoie** [comment]
>(I sure wish GitHub auto-updated these pages.)

@mholt I guess it was my bad for not linking to this issue from the PR, otherwise it would've shown up in here.
