### ISSUE TITLE
Dynamically named logfiles based on the host header.

### ISSUE THREAD

**Issue by jgeusebroek** [mholt/caddy#1617]
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.10.0

### 2. What are you trying to do?

Write to dynamically named logfiles based on the host header.

### 3. What is your entire Caddyfile?
```text
  *.some.site.name {
    tls selfsigned {
      max_certs 10
    }
    gzip

    proxy / http://172.20.20.20:80 {
        fail_timeout 300s
        transparent
    }

    log "/var/log/caddy/{host}.access.log" {
      rotate_size 100
      rotate_age  14
      rotate_keep 2
    }

  }

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Not relevant

### 5. Please paste any relevant HTTP request(s) here.

Not relevant

### 6. What did you expect to see?

Logfiles named /var/log/caddy/bla.some.site.name.access.log

### 7. What did you see instead (give full error messages and/or log)?

Logfiles named /var/log/caddy/{host}.access.log

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

(Please strip away any extra infrastructure such as containers, reverse proxies, upstream apps, dependencies, etc, to prove this is a bug in Caddy and not an external misconfiguration. Your chances of getting this bug fixed go way up the easier it is to replicate. Thank you!)

**Comment by tobya** [comment]
Thanks for the feature request.  This was requested before and worked on #1414 for issue  #1396.

I made some progress but then the goalposts changed.  Perhaps someone with a little more go experience than me might take a look.

Fundamentally I think this is a good feature request.

**Comment by mholt** [comment]
I can see why this would be nice, but how do we prevent abuse?

**Comment by mholt** [comment]
Actually wait -- I'm gonna close this as a duplicate, since I also find value in this feature request, but I'm gonna direct the discussion into the first/original issue, #1396 so that it's all in one place.
