### ISSUE TITLE
Redo without on proxied response

### ISSUE THREAD

**Issue by jgsqware** [mholt/caddy#1619]
### 1. What version of Caddy are you running (`caddy -version`)?
9.5.0

### 2. What are you trying to do?
When I do a proxy, with the `without` feature, on the response the url are changed without the path, so the subsequent request are not correct

### 3. What is your entire Caddyfile?
```text
http://www.lam.local {
  proxy /mattermost gitlab:80 {
    without /mattermost
    header_upstream Host mattermost.lam.local
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    header_upstream X-Forwarded-Proto {scheme}
  }
  log stdout
  
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
from docker container

### 5. Please paste any relevant HTTP request(s) here.

`curl -X GET http://www.lam.local/mattermost`

subsequent request auto-generated

`curl -X GET http://www.lam.local/static/info.js`

### 6. What did you expect to see?
I would like to have the subsequent request like this:

`curl -X GET http://www.lam.local/mattermost/static/info.js`

**Comment by francislavoie** [comment]
I'm not sure I understand what you're asking. `without` is meant to remove that part from the requested URL so that you can have a virtual `/path` for the proxied site. It seems to me like you should just remove your `without` directive to get the expected result. If that doesn't fix it, can you give us more information about what you're trying to achieve?

**Comment by mholt** [comment]
I'm also confused, it looks like it's working as expected... feel free to clarify and, if this is a bug, we can re-open it.

**Comment by jgsqware** [comment]
Sorry for the late response, it was I'm misconfiguration on my side !!
Thanks for this project
