### ISSUE TITLE
Markdown: Enable use of CommonMark tools for generating HTML

### ISSUE THREAD

**Issue by geewrites** [mholt/caddy#162]
CommonMark's syntax is [unambiguous](http://spec.commonmark.org/0.20/#why-is-a-spec-needed-), [implemented in C](https://github.com/jgm/cmark), and a Go wrapper is [available](https://github.com/rhinoman/go-commonmark). This would require a Caddyfile directive to tell the server to use the option instead of the default.

**Comment by mholt** [comment]
Unfortunately, Caddy may not use cgo. Is there a pure Go implementation available?

**Comment by geewrites** [comment]
Not yet. Efforts to create native implementations are waiting for CommonMark v1.0. I'll keep an eye on it and let y'all know.

I hope you'll consider the plugin option! There are lots of Markdown flavors, and someone else is sure to want theirs. :-)

**Comment by mholt** [comment]
@geewrites Just letting you know, plugins are now doable (see https://github.com/mholt/caddy/wiki/Extending-Caddy). However, I wonder if this is something we can implement in the standard markdown middleware without having to fragment this feature. It's worth waiting until there's a pure Go implementation anyway.

**Comment by geewrites** [comment]
@Mholt, good to know. I agree, fragmenting a core feature would not be helpful. Learning Go is on my list...

**Comment by mholt** [comment]
Looks like the blackfriday library we already use will support CommonMark in its next major version. https://github.com/russross/blackfriday/issues/114

**Comment by mholt** [comment]
I'm going to label this as deferred and close it since I'm not personally interested in implementing CommonMark, but will wait for it to be supported by blackfriday (if you want it sooner, feel free to jump over to that project and help it along). However, I'll keep my eye on blackfriday, and when its 2.0 is ready, we'll look at upgrading. Thanks for the suggestion!

**Comment by mholt** [comment]
Oh hey, v2 does this :grin:
