### ISSUE TITLE
Header Overwrite doesn't work with proxy

### ISSUE THREAD

**Issue by mschneider82** [mholt/caddy#1623]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.0

### 2. What are you trying to do?
I had problems fixing the wrong "Location:" header got from a proxy backend, header overwrite didnt work, i had to remove the header first in a hop with "header /fixredirect -Location", in my case the backend replyed the wrong url for Location, e.g. "http://wrong.domain/"

```text
test.example.com:443 {
        header /fixredirect Location "/fixredirect/"
        proxy / localhost:10080 {
                        header_upstream Host {host}
                        header_upstream X-Real-IP {remote}
                        header_upstream X-Forwarded-Proto {scheme}
        }


        gzip
        tls some@example.com
}


:10080 { 
        header /fixredirect -Location
        proxy / https://backend:443 {
                                header_downstream Host test.example.com
                                header_upstream Host test2.example.com
                                header_upstream X-Real-IP {remote}
                                header_upstream X-Forwarded-Proto {scheme}
                                insecure_skip_verify
        }

 
        gzip
        tls off
}
```

They way it should work (but it doesn't):
```text
test.example.com:443 {
        header /fixredirect Location "/fixredirect/"
        proxy / https://backend:443 {
                        header_upstream Host {host}
                        header_upstream X-Real-IP {remote}
                        header_upstream X-Forwarded-Proto {scheme}
        }


        gzip
        tls some@example.com
}
#with this example browsing to test.example.com:443/fixredirect will redirect to http://wrong.domain not to /fixredirect/
```

**Comment by mholt** [comment]
The [docs for header](https://caddyserver.com/docs/header) state:

> Note that if you wish to remove response headers from a proxied backend, you must do so in the proxy directive.

Have you tried using `header_downstream` instead? It seems that should do what you want.

**Comment by mschneider82** [comment]
I cant set the /fixredirect location for `header_downstream`

**Comment by mholt** [comment]
But you can for `proxy`. (You can have more than one proxy directive.)

**Comment by mschneider82** [comment]
ok thank you! it seems that both (``proxy`` and ``header``) are prefix matches, is there a way todo a exact match? Currently the "Location:" Header is also fixed when i browse to ``/fixredirect/some_other_page``

**Comment by mholt** [comment]
@mschneider82 Not at this time; sorry. You might be able to do a clever rewrite and then combine that with `without` in proxy (which is currently undergoing a bug fix) - but I think the best solution here would be to fix your upstream so it sets the right header, this is a very odd use case indeed 🤔

**Comment by mschneider82** [comment]
Ok, I think it would be a good feature for ``header`` to make the searchtype configurable.

Thank you for support & caddy!

**Comment by mholt** [comment]
Yeah, I want to make request matching better in a future version of Caddy.
