### ISSUE TITLE
On-Demand TLS, Redirect http->https fails

### ISSUE THREAD

**Issue by jgeusebroek** [mholt/caddy#1625]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.0

### 2. What are you trying to do?
Use On-Demand TLS, without specifying the scheme.

### 3. What is your entire Caddyfile?
```text
  *.bla.something {
    tls email@address {
      max_certs 10
    }
  }
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
N/A

### 5. Please paste any relevant HTTP request(s) here.
N/A

### 6. What did you expect to see?
Redirect  http://something.bla.something to https://something.bla.something

### 7. What did you see instead (give full error messages and/or log)?
Redirect to https://*.bla.something, which of course fails.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
N/A

**Comment by mholt** [comment]
Oops -- not quite sure how this slipped through, but I can see where the missing test cases are. Fix coming soon.
