### ISSUE TITLE
Where are SSL options?

### ISSUE THREAD

**Issue by 0xbaadf00d** [mholt/caddy#1627]
Hello,

I try to migrating from Nginx to Caddy (0.10), But I dont find SSL options to keep the enable same features.

How to enable _Session resumption_ and _HSTS_ ?

![image](https://cloud.githubusercontent.com/assets/1005086/25470041/5d87e952-2b20-11e7-9f01-af8576e489dc.png)

Thanks

**Comment by francislavoie** [comment]
For HSTS you can do `header / Strict-Transport-Security "max-age=31536000;"`, see the example here: https://caddyserver.com/docs/header

As for session resumption, it was talked about in this blog post: https://caddyserver.com/blog/caddy-0_8_3-released. I don't know much about this feature so I can't really comment further.

But FYI, questions like this should usually go on the forums if it's not an explicit issue: https://caddy.community/

I'm closing this, but feel free to continue discussing here 😄

**Comment by mholt** [comment]
You don't want session resumption by caching, it's not a great idea for servers to be storing that extra state anyway. If it gets compromised, every other client goes down with it. Session resumption by tickets is simpler and safer.

**Comment by 0xbaadf00d** [comment]
Caching or by ticket, both are not enabled... And I don't find option to enable it.  I have open a discussion at https://caddy.community/t/how-to-enable-ssl-session-resumption/1886
