### ISSUE TITLE
fastcgi on Windows: Caddyfile is accessible

### ISSUE THREAD

**Issue by l5h5t7** [mholt/caddy#1628]
Just created a Caddyfile, then run a site, I am surprised that Caddyfile is accessible through https://example.com/Caddyfile .
If add `browser /` to Caddyfille, then Caddyfile is inaccessible https://example.com/Caddyfile through https://example.com/Caddyfile .
Does this meet expectations?
I add `basicauth` to Caddyfile for another site, so I think it's unsafe.

**Comment by mholt** [comment]
Hi @l5h5t7  - I cannot reproduce this behavior:

```
::1 - - [27/Apr/2017:05:38:48 -0600] "GET /Caddyfile HTTP/1.1" 404 14
```

Next time, please follow the issue template so we have enough information to see what you're seeing.

**Comment by l5h5t7** [comment]
OK! I will follow the issue template next time.

### 1. What version of Caddy are you using (`caddy -version`)?

Web Server: Caddy 0.10.0;
PHP: 5.4.28.0 (In fact, in any FastCGI);
OS: Windows 2003, Windows 10.

### 3. What is your entire Caddyfile?

```
:2020 {
	fastcgi / 127.0.0.1:9000 php
}
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

The Caddyfile is in webroot.
Access http://localhost:2020/Caddyfile ,then you can reproduce it.

**Comment by mholt** [comment]
What's your backend doing? If it's serving static files, then of course it can read the Caddyfile. Caddy can't stop your fastcgi process from reading it. You'll have to move it out of the site or change permissions to forbid it.

**Comment by tobya** [comment]
Caddy prevents the caddyfile from being served as a static file.

It should prevent the file from being passed to fastcgi also.

**Comment by mholt** [comment]
I disagree. It's not Caddy's place to meddle in what upstreams are doing on the file system. The OS and the site owner are responsible for that.

**Comment by l5h5t7** [comment]
Even FastCGI backend doesn't work (close php-cgi.exe), Caddyfile is still accessible.
My backend runs PHP using `fastcgi / 127.0.0.1:9000 php` only.

**Comment by mholt** [comment]
@l5h5t7 Not sure I follow. You mean you took out the fastcgi directive and you could still access the Caddyfile? (Did you restart the server after changing the Caddyfile?)

**Comment by l5h5t7** [comment]
Yes, I restarted caddy after changing the Caddyfile.
Just now, I tried to reproduce it on Linux, but it doesn't work ("404 Not Found" showed).

So I think:
1. on Windows;
2. Caddyfile is in wwwroot, and `fastcgi` in Caddyfile;
3. Needn't run FastCGI backend (but if you run it, it still works).

You can access Caddyfile though http(s)://{yourdomain}/Caddyfile .

**Comment by mholt** [comment]
@l5h5t7 If `fastcgi / ...` is in your Caddyfile, then it's proxying the request to your backend app, which probably doesn't know to hide the Caddyfile.

On Windows: if you take that directive out entirely (don't just turn off your fastcgi process - but remove the directive altogether), does it still show the Caddyfile?

I don't have Windows so I can't test this. I'll need your help. ;)

**Comment by l5h5t7** [comment]
If remove `fastcgi / ...` from Caddyfile, caddy return "404 Not Found" when access http(s)://{yourdomain}/Caddyfile .

**Comment by tobya** [comment]
If fastcgi is being used with the ` php` preset, my understanding is that fastcgi should never be called for the `Caddyfile` as it does not have a `.php` extension.  

I wonder is it being mistaken for a directory?  Or perhaps there is a differnt path that means it is being served by staticfiles but not being hidden.

**Comment by mholt** [comment]
Sigh. Yeah, that is weird. Can somebody with Windows investigate this? @l5h5t7 if you'd like, it would be a good way for you to get familiar with the code. :) And it would speed things up!

**Comment by Whitestrake** [comment]
Replicated this on Windows 10 Pro 1703 build 15063.138.

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.0

### 2. What are you trying to do?
Serve any website (bare minimum configuration) without also serving the Caddyfile

### 3. What is your entire Caddyfile?
```text
localhost
root C:\Users\micro\Downloads\caddy_v0.10.0_windows_amd64\webroot
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
PS C:\Users\micro\Downloads\caddy_v0.10.0_windows_amd64\webroot> .\caddy.exe
Activating privacy features... done.
http://localhost:2015
```

### 5. Please paste any relevant HTTP request(s) here.
localhost:2015/Caddyfile


### 6. What did you expect to see?
Error 404

### 7. What did you see instead (give full error messages and/or log)?
```text
localhost
root C:\Users\micro\Downloads\caddy_v0.10.0_windows_amd64\webroot
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
1. Download 0.10.0 from caddyserver.com/download
2. Extract .exe to some path
3. Make a minimal Caddyfile and place in webroot
4. Run caddy.exe from command line
5. Browse to localhost:2015/Caddyfile

**Comment by slightfoot** [comment]
The `FileServer.IsHidden` function tries to open each hidden file with `http.FileSystem` which always uses `/` as path the separator. So `\Caddyfile` on windows isn't located and this is enabled to pass through.

The PR patches this issue by using the `filepath.ToSlash` to correct the path before saving it to the `HiddenFiles`.

** http.FileSystem **
https://golang.org/pkg/net/http/#FileSystem
> A FileSystem implements access to a collection of named files. The elements in a file path are separated by slash ('/', U+002F) characters, regardless of host operating system convention.

** FileServer.IsHidden **
https://github.com/mholt/caddy/blob/master/caddyhttp/staticfiles/fileserver.go#L210
