### ISSUE TITLE
how to loadbalance using caddy?

### ISSUE THREAD

**Issue by kellertobi91** [mholt/caddy#1636]
At this time, we are using nginx to terminate http and https for 3 scaling groups (different versions) of our app. the scaling group do have multiple running instances of our app (e.g. 10.0.0.1:3000 and 10.0.0.2:3000)

In nginx, i can define an upstream with multiple servers in it.

is something like this also possible in caddy?

**Comment by Omar-H** [comment]
https://caddyserver.com/docs/proxy

**Comment by kellertobi91** [comment]
Thanks.
Just overread this in my enthusiasm.

Am 30.04.2017 13:40 schrieb "Omar H." <notifications@github.com>:

**Comment by elcore** [comment]
Have fun with Caddy 😄

**Comment by kellertobi91** [comment]
is it possible to do a connection like ip_hash but that works behind a NAT? e.g. a cookie based balancing like nginx plus supports?

**Comment by mholt** [comment]
No, that feature doesn't exist at this time.
