### ISSUE TITLE
Should still run when DNS fails to resolve

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#164]
for whatever reason my server can't resolve itself `foo.example.com` and so caddy bails instead of listening on `0.0.0.0` to handle vhost for `foo.example.com`.

**Comment by mholt** [comment]
I think this is valid. To see how this is handled in nginx, for example, I added this to nginx.conf:

    server {
        listen 8081;
        server_name foobar.fizz;
        root /Users/matt/Sites/matt.life;
    }

I ran nginx *then* added foobar.fizz to my /etc/hosts file. When I loaded foobar.fizz:8081 in my browser, the server responded with the site. I then tried using 127.0.0.1:8081 and localhost:8081 in my browser, and both also worked. It seems that nginx listens on the wildcard host.

We can still print a warning if the name does not resolve. Any objections? If not, I can go forward with this.

**Comment by mholt** [comment]
(I bet we can knock out this and #136 at the same time)
