### ISSUE TITLE
Proxy broken over QUIC on commit 0146bb4 onwards

### ISSUE THREAD

**Issue by wildtang3nt** [mholt/caddy#1643]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.0 (+e0ed709)

### 2. What are you trying to do?
Visit sites served behind proxy over QUIC protocol

### 3. What is your entire Caddyfile?
```text
subdomain.example.com {
    proxy / http://internal:8080 {
        websocket
        transparent
    }
    log / /var/log/caddy/access.log "{combined}"
    errors /var/log/caddy/error.log
    tls {
        protocols tls1.2
        ciphers ECDHE-RSA-WITH-CHACHA20-POLY1305 ECDHE-RSA-AES256-GCM-SHA384 ECDHE RSA-AES256-CBC-SHA
        curves p384
        key_type rsa4096
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -quic

### 6. What did you expect to see?
Not a 500 error

### 7. What did you see instead (give full error messages and/or log)?
01/May/2017:22:57:10 -0400 [PANIC /web/home.html] caddyhttp/httpserver/recorder.go:96 - *h2quic.responseWriter is not a closeNotifier
01/May/2017:22:57:10 -0400 [PANIC /favicon.ico] caddyhttp/httpserver/recorder.go:96 - *h2quic.responseWriter is not a closeNotifier
01/May/2017:22:57:11 -0400 [PANIC /web/serviceworker.js] caddyhttp/httpserver/recorder.go:96 - *h2quic.responseWriter is not a closeNotifier

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Build any commit after 7ee4ea2 and try to access a proxied site with QUIC.

**Comment by wildtang3nt** [comment]
Addendum: Works as expected after updating to latest HEAD and reverting the files touched by 0146bb4
caddyhttp/gzip/gzip.go
caddyhttp/header/header.go
caddyhttp/httpserver/error.go
caddyhttp/httpserver/recorder.go
caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

**Comment by mholt** [comment]
Hmm. @tw4452852 What do you think is causing this? What's not a CloseNotifier, I wonder?

**Comment by mholt** [comment]
@wildtang3nt Does it work without `-quic`? If so, do that for now.

**Comment by mholt** [comment]
Nevermind my earlier comment, which I deleted. It's late and I'm not reading things fully. :smile:

This will require a change in the upstream quic library. I'll open an issue there, they've been really awesome about fixing little things like this. It won't get fixed for tonight's release, but that's okay, it'll get in soon I'm sure. :)

**Comment by wildtang3nt** [comment]
Yes, unmodified HEAD works fine as long as you avoid QUIC by omitting -quic, blocking UDP, disabling QUIC in browser, etc. It is definitely something isolated to the changes in 0146bb4 or something they rely on in quic-go.

**Comment by mholt** [comment]
@wildtang3nt Yes, the changes in that commit require that, when using proxy, any ResponseWriter implementation be a CloseNotifier, to properly handle when clients cancel the connection. It just so happens that h2quic doesn't do this. No biggie, I think.

**Comment by wildtang3nt** [comment]
Well that puts me at ease. Until then, I can just keep using my franken-caddy. Mostly e0ed709 with a bit of 7ee4ea2 thrown in for flavour :)

**Comment by wildtang3nt** [comment]
https://github.com/lucas-clemente/quic-go/pull/584 solves this problem for me.
