### ISSUE TITLE
Wildcard Subdomains & Automatic HTTPS - Redirected to %2A

### ISSUE THREAD

**Issue by dfiel** [mholt/caddy#1646]
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.0

### 2. What are you trying to do?
Wildcard Subdomains with Automatic HTTPS

### 3. What is your entire Caddyfile?
```text
A.com {

        proxy / 10.250.10.47 {
            transparent
            websocket
        }
        tls {
           max_certs 5000
        }
}

*.A.com {

        proxy / 10.250.10.47 {
            transparent
            websocket
        }
        tls {
           max_certs 5000
        }
}

XXX.XXX.XXX.XXX:80 {
        redir https://A.com
}

A.B.com:80 {
        redir https://othersite.com
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -log stdout

### 6. What did you expect to see?
Wildcard subdomains with automatic HTTPS works as expected.

### 7. What did you see instead (give full error messages and/or log)?
Browser is redirected to https://%2A.A.com/

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Any server directive with a wildcard subdomain and automatic HTTPS, will have all subdomains redirected to %2A

This issue only started after updating from an older version (don't remember which) to the newest.

**Comment by mholt** [comment]
Hey, thanks for filling out the whole issue template. You get a cookie for that. :cookie: 

This is fixed in 0.10.1, and now 0.10.2 is out. Please upgrade! :innocent: Thanks.

**Comment by dfiel** [comment]
Gah. Seems like every time I submit an issue its always an out of date version. Seemed not so long ago that I updated. Oh well, thanks for pointing me in the right direction. Loving your application!

**Comment by mholt** [comment]
@dfiel Glad you like it!

With the new build server we can release very often -- every day, if we wanted to. 🤔 I may need to implement automatic updates to help people keep up...
