### ISSUE TITLE
Self-signed TLS: Chrome 58 no longer allows certificates without Subject Alternative Name (SAN)

### ISSUE THREAD

**Issue by wildtang3nt** [mholt/caddy#1647]
Oh, pretty self-explanatory. Just updated Chrome to version 58 and now you get a privacy error for self-signed certificates because nobody ever bothers to include the SAN extension for those, right? I know you're thinking 'Big deal, you get a scary warning anyway and just click through.' Unfortunately, if the server enables HSTS, Chrome won't allow you to bypass.

**Comment by mholt** [comment]
@wildtang3nt Thanks for the issue. :)

> Oh, pretty self-explanatory.

Sorry, but I'm super lost. What is the issue here exactly?

**Comment by wildtang3nt** [comment]
For self signed certs generated by Caddy? I don't see a CommonName or any AltNames. Before Chrome 58 this wouldn't be a problem. After it wouldn't be a problem for most web servers, unless you set HSTS then Chrome will refuse to let you bypass the warning.

**Comment by mholt** [comment]
Caddy has always set the name of its self-signed certs [in the SAN extension](https://github.com/mholt/caddy/blob/dfebffb1eeb7ff0eba1e922bb8b452670675535f/caddytls/crypto.go#L200). If you look at the cert you'll see it there:

<img width="330" alt="self signed san" src="https://cloud.githubusercontent.com/assets/1128849/25649566/c568d848-2f93-11e7-9747-90bc38c153eb.png">

So it should be fine before and after Chrome 58. (I'm using Chrome 58, no problems.)

**Comment by wildtang3nt** [comment]
Nevermind, user error. The way my caddy file was setup I didn't use a hostname so got no AltName.
