### ISSUE TITLE
Add support for TLS_RSA_WITH_AES_128_GCM_SHA256

### ISSUE THREAD

**Issue by Zewy** [mholt/caddy#1650]
### 1. What version of Caddy are you using (`caddy -version`)?
```0.10.2```

### 2. What are you trying to do?
```openssl s_client -cipher AES128-GCM-SHA256 -connect mysite.com:443```

### 3. What is your entire Caddyfile?
```https://mysite.com {
	tls /etc/caddy/ssl/mysite-bundle.crt /etc/caddy/ssl/mysite.key
	root /home/caddy	
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```./caddy -quic```

### 5. Please paste any relevant HTTP request(s) here.
```openssl s_client -cipher AES128-GCM-SHA256 -connect mysite.com:443```

### 6. What did you expect to se
```SSL handshake has read 4305 bytes and written 417 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : AES128-GCM-SHA256
```

### 7. What did you see instead (give full error messages and/or log)?
```CONNECTED(00000003)
140106362275744:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:744:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 99 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
---
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Just run ```openssl s_client -cipher AES128-GCM-SHA256 -connect yourcaddysite.com:443```

**Comment by francislavoie** [comment]
That cipher suite is blacklisted: https://http2.github.io/http2-spec/#BadCipherSuites

**Comment by mholt** [comment]
Hmm, yup, Francis is right. TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c) is on the blacklist. I don't see a productive reason to add this to Caddy. Thanks for the feature request though!
