### ISSUE TITLE
Feature request: HTTP2 in Proxy

### ISSUE THREAD

**Issue by vladbondarenko** [mholt/caddy#1657]
Hi,

For now when request via HTTP2 goes to caddy, caddy sends request to backend (in proxy mode) using HTTP/1.1

Is it possible to not downgrade proto in case if backend can http2?

Something like:
proxy / 127.0.0.1:80 {
     proxy_proto h2, h2c, h1
}

**Comment by mholt** [comment]
Caddy, as a client, should already be proxying with HTTP/2 into the backend if it is supported. Are you sure it's not? (You'll need to use HTTPS)

**Comment by mholt** [comment]
I am pretty sure HTTP2 is used by default for the proxy to a backend for all HTTPS connections. Feel free to re-open if you confirm that is not the case!

**Comment by vladbondarenko** [comment]
Seems i cant test now, as i cant make Caddy work fine with Hitch and Varnish http2 feature.
May 10 08:57:16 ip-172-31-6-118 hitch[740]: 127.0.0.1:57020 :0 12:13 Handshake failure: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request
May 10 08:57:16 ip-172-31-6-118 hitch[740]: 127.0.0.1:57022 :0 12:13 Handshake failure: error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request

Need some time to figure this out.

Anyway, thanks, i will re-open if no.

**Comment by vladbondarenko** [comment]
From Caddy side:

proxy / 127.0.0.1:555 {
header_upstream Host "my.domain"
header_upstream X-Forwarded-Proto "https"
}

On 555 port nginx (to terminate TLS):
server {
    listen                555 ssl http2;
     ssl_certificate       /etc/nginx/ssl/my.domain.crt;
     ssl_certificate_key   /etc/nginx/ssl/my.domain.key.key;
     ssl_protocols         TLSv1 TLSv1.1 TLSv1.2;
     ssl_ciphers           HIGH:!aNULL:!MD5;
     ssl_session_cache     shared:SSL:20m;
     ssl_session_timeout   4h;
     location / {
        proxy_pass            http://localhost:80;
     }
  }

(localhost:80 is Varnish with http2 enable feature)

While accessing Caddy on 443 port i got this from Nginx:

400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.11.9

Seems Caddy sends plain HTTP request to 555 port.
JFI: 555 port accepted HTTP2 as per Network Console in Chrome. And Caddy should also.

If i`m doing smthing wrong?

**Comment by elcore** [comment]
Hello, 

this should work:

```
proxy / https://127.0.0.1:555 {
header_upstream Host "my.domain"
header_upstream X-Forwarded-Proto "https"
}
```

**Comment by vladbondarenko** [comment]
For now i got 502

....... - - [12/May/2017:09:15:01 +0000] "GET / HTTP/2.0" 502 40

Caddy cant connect to backend.

**Comment by vladbondarenko** [comment]
Bang!

I made that work, BUT:

proxy / https://127.0.0.1:555 {
header_upstream Host "my.domain"
header_upstream X-Forwarded-Proto "https"
insecure_skip_verify
}

[root@ip-172-31-6-118 caddy]# varnishlog|grep HTTP
-   ReqProtocol    HTTP/2.0
-   ReqProtocol    HTTP/2.0

Varnish starts to operate via /2
Nginx (as Varnish backend) also got HTTP2
127.0.0.1 - - [12/May/2017:09:42:58 +0000] "GET / HTTP/2.0" 200 6151 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" "204.11.108.17"

Certificates used by TLS terminator are the same as for Caddy.
But HTTP2 worked only in "insecure_skip_verify"

Is that bug?

**Comment by elcore** [comment]
Do you use a signed certificate for NGINX?

**Comment by vladbondarenko** [comment]
I use LetsEncrypt cert.

**Comment by elcore** [comment]
Hello, 

are you 100% sure that you use a signed and valid Let's Encrypt certificate? The validation is handled by the Go standard library (as far as I know). 

ping @mholt

**Comment by elcore** [comment]
Hello,

I am so sorry, I forgot you are using an IP and not an domain! 

You need to use `insecure_skip_verify`, because the certificate is not valid for the domain.

You cannot get a CA signed certificate for a private IP address, Let´s Encrypt does not issue certificates for public IP addresses.

ping @mholt

**Comment by vladbondarenko** [comment]
Yes.

From openssl s_client -connect my.domain:443 (Caddy):

CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=my.domain
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGGjCCBQKgAwIBAgISA1izPb9cmhmHOl40VXLM21k5MA0GCSqGSIb3DQEBCwUA
.....
USFAcQK4B+5Wqcy6paZh3yR1O9C5Kr3dbHaP6YAM
-----END CERTIFICATE-----
subject=/CN=my.domain
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

From openssl s_client -connect my.domain:555 (TLS terminator)

CONNECTED(00000003)
---
Certificate chain
 0 s:/CN=my.domain
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGGjCCBQKgAwIBAgISA1izPb9cmhmHOl40VXLM21k5MA0GCSqGSIb3DQEBCwUA
.....
USFAcQK4B+5Wqcy6paZh3yR1O9C5Kr3dbHaP6YAM
-----END CERTIFICATE-----
subject=/CN=my.domain
issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3

Certs are the same.

**Comment by elcore** [comment]
@vladbondarenko see my answer above, I am sorry!!!

**Comment by vladbondarenko** [comment]
>I am so sorry, I forgot you are using an IP and not an domain!

Yup, (where is dumb smile?) :)

**Comment by vladbondarenko** [comment]
Thanks! Seems that only my infrastructure situation. Completely forgot about this.

**Comment by elcore** [comment]
>Yup, (where is dumb smile?) :)

That is not funny at all! I am stressed (I slept for only 2 hours), nonetheless I am helping you.

> Thanks! Seems that only my infrastructure situation. Completely forgot about this.

😄

**Comment by vladbondarenko** [comment]
Damn, SORRY!!! you should not if that. Nothing is as important as health.

**Comment by elcore** [comment]
> Damn, SORRY!!! you should not if that. Nothing is as important as health.

Do not be sorry 😄!!!! Everything is fine 😄 -- I had to learn for an important exam

**Comment by mholt** [comment]
@vladbondarenko I'm implementing h2c into the v2 reverse proxy over in https://github.com/caddyserver/caddy/issues/3218 -- the [h2c](https://github.com/caddyserver/caddy/tree/h2c) branch. If you could try it out and join the discussion there, that'd be helpful!
