### ISSUE TITLE
Two systemd setups?

### ISSUE THREAD

**Issue by infogulch** [mholt/caddy#1659]
There seems to be two different examples for setting up caddy to run under systemd:

https://github.com/caddyserver/examples/tree/master/systemd

https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd

Is one canonical?

**Comment by francislavoie** [comment]
I'd say the one in this repo is more likely to be the recommended one, it's more recently modified.

**Comment by infogulch** [comment]
I would agree. It also seems more complete.

Should the other one be taken down or have a note pointing to this one?

**Comment by mholt** [comment]
Honestly, I want to get the `init` scripts out of this repo entirely. But having them in two places is probably confusing, you're right.

I'd elect we take down the one in the examples repo and leave this one for now, until we figure out what to do with them.

**Comment by infogulch** [comment]
Sure. Which would you prefer?

1. Just remove it.
2. Remove it, add note in /README.md pointing to this repo.
3. Remove caddy.service, change /systemd/README.md to point to this repo.

**Comment by francislavoie** [comment]
I think 3 is fine imo.

**Comment by mholt** [comment]
Sure, either 1 or 3 are fine.

**Comment by infogulch** [comment]
[Pull request submitted](https://github.com/caddyserver/examples/pull/63)

**Comment by mholt** [comment]
Thanks!
