### ISSUE TITLE
browse shows symlinked folders as files

### ISSUE THREAD

**Issue by theel0ja** [mholt/caddy#1660]
### 1. What version of Caddy are you using (`caddy -version`)?
0.9.5

### 2. What are you trying to do?
Use caddy with browse.

### 3. What is your entire Caddyfile?
I do not have Caddyfile, but the CLI command has `browse` as it.

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy browse`

### 5. Please paste any relevant HTTP request(s) here.

Just http://localhost:2015/

### 6. What did you expect to see?
Something like this:
![image](https://cloud.githubusercontent.com/assets/5832930/25861755/489a23a2-34ee-11e7-80f4-4bf9df328c36.png)

### 7. What did you see instead (give full error messages and/or log)?
![image](https://cloud.githubusercontent.com/assets/5832930/25861729/38cf7e86-34ee-11e7-8917-864d287d716f.png)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

```
mkdir folder/
cd folder/
mkdir hello/
mkdir hello/world/
ln -s hello/world/ ./
caddy browse
```

Go to http://localhost:2015/ and see `world` as file, while it's folder.

Like this:
![image](https://cloud.githubusercontent.com/assets/5832930/25861857/aa1c82c8-34ee-11e7-8007-2d94bb5db342.png)

**Comment by mholt** [comment]
Nice issue, @theel0ja  - thanks for all the info. I think this should be easy enough for someone new to the project to be able to contribute to, so I'll try to leave this for someone who has little (but some) Go experience to see if they want to submit a pull request!

**Comment by henkburgstra** [comment]
I would like to fix this issue if that's ok :-)

**Comment by mholt** [comment]
@henkburgstra @cez81 already beat you to it, but we do need some icons if you are savvy with SVG graphics.

**Comment by henkburgstra** [comment]
I missed that, sorry.  Also not very good with SVG :( 
isSymlinkTargetDir by @cez81 doesn't seem to take into account that a symlink can point to another symlink. If that's the case it should recurse and protect itself against endless recursion.

**Comment by mholt** [comment]
@henkburgstra No problem, maybe make that comment in-line on the pull request itself. :) Thanks!

**Comment by cekvenich** [comment]
Has this been fixed? Working w/ ln -s?
And what about a mounted filesystem?

**Comment by elcore** [comment]
>Has this been fixed?

Yes (in 0.10.4)

> And what about a mounted filesystem?

You can try it for yourself and report it
