### ISSUE TITLE
proxy requests always return response status of 0

### ISSUE THREAD

**Issue by achernyak** [mholt/caddy#1662]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.9.5

### 2. What are you trying to do?
I am using the `caddy-prometheus` plugin, which returns http response statuses as one of the metrics. This metric is retrieved by calling by the below code. However, it appears that all proxy responses come through with the status code 0 from caddy. I don't believe this is an issue with `caddy-prometheus` issue since it still works for files not behind a proxy.

```
rw := httpserver.NewResponseRecorder(w)
status, err := next.ServeHTTP(rw, r)
```

### 3. What did you expect to see?
I expected to see the proper response status as with non proxy requests.

### 4. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Enable a proxy route and enable `prometheus` plugin. Try hitting the proxy route. View metrics for `caddy_http_response_status_count_total` on the prometheus dashboard.

I am sure there is a simpler method to accomplish this without having to go through `caddy-prometheus` but I am not familiar enough with caddy internals.

**Comment by slightfoot** [comment]
This is expected behaviour. The `0` is the response from plugins that it was successful. You should check `rw.Status()` to get the actual response code.

Refs:
> https://github.com/mholt/caddy/wiki/Writing-a-Plugin:-HTTP-Middleware
> https://godoc.org/github.com/mholt/caddy/caddyhttp/httpserver#Handler

**Comment by achernyak** [comment]
@slightfoot Thank you so much for the help!
