### ISSUE TITLE
predefined log format doesn't work with prefix or suffix

### ISSUE THREAD

**Issue by tw4452852** [mholt/caddy#1663]
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?

958abcf

### 2. What are you trying to do?

log with predefined format together with additional prefix and suffix.

### 3. What is your entire Caddyfile?
```text
localhost:1234 {
  log / stdout "prefix {common} suffix"
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -log stdout

### 5. Please paste any relevant HTTP request(s) here.

(paste curl command, or full HTTP request including headers and body, here)

curl -v localhost:1234

### 6. What did you expect to see?

logout output like this:

```
prefix ::1 - - [11/May/2017:16:10:32 +0800] "GET / HTTP/1.1" 200 58 suffix
```

### 7. What did you see instead (give full error messages and/or log)?

```
prefix - suffix
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Use above Caddyfile and give a request with curl.

(Please strip away any extra infrastructure such as containers, reverse proxies, upstream apps, caches, dependencies, etc, to prove this is a bug in Caddy and not an external misconfiguration. Your chances of getting this bug fixed go way up the easier it is to replicate. Thank you!)

**Comment by mholt** [comment]
Thanks for the report! Good find.
