### ISSUE TITLE
Page not responding if status code != 200 and gzip enabled

### ISSUE THREAD

**Issue by alehano** [mholt/caddy#1670]
### 1. What version of Caddy are you using (`caddy -version`)?
v0.10.2

### 2. What are you trying to do?
Use Caddy as a proxy to gin-gonic router. Any pages with status code != 200 (4xx, 5xx) not responding. If I remove gzip, works fine. 
### 3. What is your entire Caddyfile?
```text
http://127.0.0.1:8000 {
    proxy / dev_main:8001
    gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Run in a Docker. Same problem on server and local machine.

**Comment by mholt** [comment]
What do you mean by "not responding"? (I wish you had followed the issue template, so we could clearly understand the problem...)

**Comment by theel0ja** [comment]
Have you some example code, etc. so people here can reproduce the issue?

**Comment by alehano** [comment]
Sorry it was on my production server, I didn't have time to figure out where is exactly a problem. I just can say I used caddy as a proxy server to Gin web framework. 200 status served ok, but 4xx, 5xx errors not. Server seems to not send enything. Browers said no data. Gin without Caddy worked fine and on previous versions of Caddy was fine. May be problem with gzip module, cause turning it off helped.

**Comment by francislavoie** [comment]
That's really not enough information to go by. If you run into it again and can provide more info, we can re-open this issue.

**Comment by mholt** [comment]
Has anyone tried reproducing this with the info given, though, even if without gin-gonic or Docker? I haven't had a chance.

**Comment by francislavoie** [comment]
Yeah, I proxy to some sites with a Caddy backend serving PHP via fastcgi, and I definitely get errors correctly, with gzip on both the backend and the proxy, in Docker. So based on that, I think the only difference between my environment and @alehano is gin-gonic.
