### ISSUE TITLE
Run static site with parameters

### ISSUE THREAD

**Issue by sredXNY** [mholt/caddy#1677]
Hi, I am having an issue deploying a static site, I have caddy installed in my CentOS server. There, I have some other sites running and everything is ok.
Now, I want to be able to use routes with parameters, for example:`
mysite.com/products/:someid`

The site was built using React.js and the static file generated using `npm run build` 
I can open the index and some other pages that are not receiving parameters in the URL. Right now, the definition for the site in the caddyfile is as follows:

```
mysite.com {
   root PathToProject/build/
   log logs/pagelog.log
}

What am I missing?
```

**Comment by mholt** [comment]
Looks like you got some help on the forum for your question: https://caddy.community/t/dynamic-routes-not-working-in-react-with-caddy/2008/2?u=matt

The forum is a better venue for questions like this. :) Thanks!
