### ISSUE TITLE
Caddy stops replying to requests

### ISSUE THREAD

**Issue by OmgImAlexis** [mholt/caddy#1684]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.9.4

### 2. What are you trying to do?
Load a site running behind caddy

### 3. What is your entire Caddyfile?
```text
seafile.example.com {
    tls xo@example.com
    proxy / 192.168.1.150:8000 {
        transparent
    }
    gzip
    log stdout
    errors stdout
}

seafile.example.com/seafhttp {
    tls xo@example.com
    proxy / 192.168.1.150:8082 {
       transparent
    }
    rewrite /seafhttp {
        regexp (.*)
        to     {1}
    }
    gzip
    log stdout
    errors stdout
}

medusa.example.com {
    tls xo@example.com
    proxy / 192.168.1.150:8081 {
        transparent
    }
    gzip
    log stdout
    errors stdout
}

deluge.example.com {
    tls xo@example.com
    proxy / 192.168.1.150:8112 {
        transparent
        header_upstream X-Forwarded-Host {host}
    }
    gzip
    log stdout
    errors stdout    
}

buddy.example.com {
    tls xo@example.com
    proxy / 192.168.1.243 {
        transparent
        websocket
    }
    gzip
    log stdout
    errors stdout
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Caddy is run inside a docker container using this [container](https://github.com/BlackGlory/caddy-proxy).

### 5. Please paste any relevant HTTP request(s) here.
N/A.

### 6. What did you expect to see?
Caddy load the page.

### 7. What did you see instead (give full error messages and/or log)?
Page timed out yet I can still access the backend locally without going through Caddy.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Not sure.

Is there anyway to have Caddy use verbose logging or something along those lines? This seems to happen once a week or so and I haven't found anything that fixes this other than just restarting the container or sending a USR1 signal to caddy.

**Comment by 0xbaadf00d** [comment]
I have encountered the same issue (random) with the version 0.9.4. Currently, I have no problems with the last version (0.10.3)

**Comment by mholt** [comment]
Hi, yes, I agree with bad food -- please first, and if this is still happening, feel free to re-open the issue.
