### ISSUE TITLE
Caddy stops after an application stops

### ISSUE THREAD

**Issue by sredXNY** [mholt/caddy#1685]
Hi, I have Caddy installled in the server, and mainly I have been using it as a proxy server, there we have some node and Golang applications. So, when I stop at least one of them Caddy stops serving any other site and I have to be running caddy again and again. How Can I fix it? and which monitor tool can I use to track the fall downs of Caddy? I found #853 but I don't see any solution there

I posted it here because it doesn't seems to be the intended behaviour of the server.

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.0

### 2. What are you trying to do?
I am trying to maintain caddy serving all the others sites while one have been stopped (for updating, etc).  And also, when I run again the application Caddy should be running and not to ask for me to execute caddy again.

### 3. What is your entire Caddyfile?
```text
demo.mydomain.com {
  proxy / :8000 {
    max_fails 1
  }
  log logs/mysite/log
}

api.mydomain.com {
  proxy / :3000 {
    max_fails 1
  }
}

pgadmin.mydomain.com {
  root /usr/share/phpPgAdmin/
  log logs/pgadmin/pgadmin.log
  errors pgadminerrors.log

  fastcgi / 127.0.0.1:9000 php
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
nohup caddy -conf caddyfile&
OS: CentOS 7

### 5. Please paste any relevant HTTP request(s) here.

Not relevant

### 6. What did you expect to see?
I expect when I stop some of my web applications that caddy don't stops, and when I run again my web Application I should not be executing again caddy.

### 7. What did you see instead (give full error messages and/or log)?
I get Caddy stopped and I have to execute it again

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

- Execute an application in some port (lets say 8000)

- Stop Application, am doing it with:  kill -9 $(lsof -t -i:8000)

- Run Again the application, then Caddy is stopped, the application is running but not caddy

**Comment by mholt** [comment]
Hi, can you explain what you mean by "Caddy stops serving" - what errors are you getting in the log or in response to an HTTP request? (I think that question 5 **is** relevant, because you're apparently making HTTP requests that aren't getting answered?) Is the process stopping or is it not responding to certain requests, or what exactly is happening?

**Comment by sredXNY** [comment]
@mholt with 'stops serving' I mean Caddy is stopped, I also checked and the application is not running. Briefly, if I stop some of my webapps then caddy is also stopped. The way that I'm stopping my webapps has something to be?

**Comment by mholt** [comment]
Huh, well I just tried it locally (using your instructions and kill command) and Caddy is still running. I think something else must be going on for you, I'm not able to reproduce it.

**Comment by mholt** [comment]
Scratch that. Platform differences. I see it now. When you run `kill -9 $(lsof -t -i:8000)` you are killing all processes that are connected to port 8000, including Caddy. Don't kill the Caddy process. :wink:
