### ISSUE TITLE
TLS CAUrl Option

### ISSUE THREAD

**Issue by zikes** [mholt/caddy#1689]
Currently the ACME CA URL is configured via the `-ca` command line argument. This means changing the value involves restarting the process and that all domains must use the same ACME CA.  I think this option would be better suited for the `tls` directive, e.g.:

```
staging.mydomain.com {
  tls {
    ca https://acme-staging.api.letsencrypt.org/directory
  }
  ...
}

other.mydomain.com {
  tls {
    ca https://acme-v01.api.letsencrypt.org/directory
  }
  ...
}
```

I think I can whip up a PR for this idea if it has value.

**Comment by kminehart** [comment]
Definitely has value for the caddy-ingress-controller.

**Comment by mholt** [comment]
I think this is reasonable, and should be fairly easy to do. Any newcomers to the project or Go who would like to take this, feel free!
