### ISSUE TITLE
Use casbin as the authorization plugin for caddy

### ISSUE THREAD

**Issue by hsluoyz** [mholt/caddy#1690]
Hi, I'm the author of [Casbin](https://github.com/casbin/casbin), a Go library for authorization based on access control policy. Casbin supports multiple access control models like ACL, BLP, RBAC. The access control rules can be persisted into files, DB.

I saw there's a guide about how to make a Caddy plugin [here](https://github.com/mholt/caddy/wiki/Extending-Caddy). But it doesn't show explicitly a filter plugin like an authorization module can be developed. So is it supported to develop an authorization plugin? Thanks!

**Comment by pbeckmann** [comment]
Hey,

yes oft course. I didn't try it personally, but there is already https://github.com/namsral/multipass.

Maybe the author or the source code can help you a bit more than me. 

Greetings

**Comment by mholt** [comment]
Hey Yang, thanks for your question! As Peer said, this is definitely possible -- you could write an entire web app in a Caddy plugin if you wanted to. You can look at basicauth for a simple example or multipass as Peer linked to for another more advanced example.

Then you can ask [on the forums](https://caddy.community) if you have more questions! :+1:

**Comment by hsluoyz** [comment]
Hi, I have successfully published a plugin: https://github.com/casbin/caddy-authz.

The PR to register the directive is here: https://github.com/mholt/caddy/pull/1693

**Comment by abiosoft** [comment]
@hsluoyz how is this meant to be used. Does it not require any Caddyfile config ? I can only see code samples to integrate.

**Comment by hsluoyz** [comment]
Hi @abiosoft , this plugin requires to read Caddyfile for a parameter of the config path, see here: https://github.com/casbin/caddy-authz/commit/0e681f0884d007ff2d197de35453c0e7a1834c3e

**Comment by pbeckmann** [comment]
So as i understand correctly, your plugin needs an additionaly configuration file for the plugin?

**Comment by hsluoyz** [comment]
The configuration file is optional. But it needs another model file with the ``.conf`` format. Is this supported?

**Comment by tobya** [comment]
@hsluoyz  could your caddyfile spec allow the user to specify the `.conf` file to be loaded?  This would link the two together nicely.  Ideally of course the config could be specified in the Caddyfile.
