### ISSUE TITLE
X-Accel-Redirect causes redirect loop when proxied backend insists on trailing slash

### ISSUE THREAD

**Issue by si14** [mholt/caddy#1701]
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?

0.10.3

### 2. What are you trying to do?

I'm trying to use X-Accel-Redirect header to serve a file from a protected folder

### 3. What is your entire Caddyfile?
```text
http://127.0.0.1:8001 {
  tls off;

  internal /protected

  proxy / 127.0.0.1:8000 {
    transparent
    except /protected
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`./caddy` on top of OS X

### 5. Please paste any relevant HTTP request(s) here.

Please don't mind the URL, it's just the one I've used during testing.

```text
> curl -v http://127.0.0.1:8001/en/for-press/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> GET /en/for-press/ HTTP/1.1
> Host: 127.0.0.1:8001
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Language: en
< Content-Type: text/html; charset=utf-8
< Date: Fri, 02 Jun 2017 17:34:50 GMT
< Location: /en/for-press
< Server: WSGIServer/0.2 CPython/3.5.1
< Set-Cookie: csrftoken=sGS3Sc3rlUVxZzNJahAs17vdBtfbzQpusArLPbyu32kmmYx9IWMAo2atSC53KtaV; expires=Fri, 01-Jun-2018 17:34:50 GMT; Max-Age=31449600; Path=/
< Vary: Cookie
< X-Xss-Protection: 1; mode=block
< Content-Length: 48
<
<a href="/en/for-press">Moved Permanently</a>.
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact

> curl -v http://127.0.0.1:8001/en/for-press
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8001 (#0)
> GET /en/for-press HTTP/1.1
> Host: 127.0.0.1:8001
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Language: en
< Content-Type: text/html; charset=utf-8
< Date: Fri, 02 Jun 2017 17:34:55 GMT
< Location: /en/for-press/
< Server: WSGIServer/0.2 CPython/3.5.1
< Content-Length: 0
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intac
```

A fragment of django request log:

```text
18:34:14 django.1  | INFO 2017-06-02 17:34:14,299 basehttp.py:log_message:131 "GET /en/for-press HTTP/1.1" 301 0
18:34:17 django.1  | INFO 2017-06-02 17:34:17,147 basehttp.py:log_message:131 "GET /en/for-press/ HTTP/1.1" 200 86403
18:34:17 django.1  | INFO 2017-06-02 17:34:17,161 basehttp.py:log_message:131 "GET /en/for-press HTTP/1.1" 301 0
18:34:20 django.1  | INFO 2017-06-02 17:34:20,087 basehttp.py:log_message:131 "GET /en/for-press/ HTTP/1.1" 200 86403
18:34:20 django.1  | INFO 2017-06-02 17:34:20,095 basehttp.py:log_message:131 "GET /en/for-press HTTP/1.1" 301 0
```

### 6. What did you expect to see?

Hidden file

### 7. What did you see instead (give full error messages and/or log)?

Redirect loop

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

* set up a web server that redirects to URLs with slashes
* set up Caddy in front with `internal` setting enabled
* use X-Accel-Redirect

So when Caddy sees `X-Accel-Redirect` it answers with 301 to a URL with no trailing slash for some reason (it doesn't happen when there is no `X-Accel-Redirect`). That request hits the backend again, and if it redirects to a URL that contains trailing slash, the whole thing results in a redirect loop.

**Comment by mholt** [comment]
Is Caddy serving static files anywhere in your setup? If so, I think this might be the same issue as one I just experienced today.

**Comment by si14** [comment]
It does on production! The URL in question is reverse proxied, though.

**Comment by francislavoie** [comment]
@si14 could you try the latest from the master branch? It might be fixed by https://github.com/mholt/caddy/commit/f4b6f15e07b91976d6579c8445a3321dcc63d8ae

**Comment by mholt** [comment]
@si14 Any update on this? Closing for now, as I assume this is fixed.
