### ISSUE TITLE
Plugins Not Included Properly

### ISSUE THREAD

**Issue by Injust** [mholt/caddy#1704]
Downloading Caddy for Linux 64-bit with the dns plugin does not seem to properly include the DNS plugin. Caddy errors with `unknown server type 'dns'` when running with `-type=dns`.
However, downloading Caddy for Linux 64-bit with both dns and net plugins works fine.

Is there some issue with the build infrastructure that could be causing this?

**Comment by mholt** [comment]
This is a known issue in CoreDNS, addressed here: https://github.com/coredns/coredns/issues/696 - @miekg has merged a fix, it should be available whenever it gets released, I suppose.

**Comment by miekg** [comment]
We usually push master (after an release), but I can click buttons now, master branch of CoreDNS is (should be) in a good state
