### ISSUE TITLE
Is there any way plugin http.browse args could be a absolute path?

### ISSUE THREAD

**Issue by tosone** [mholt/caddy#1705]
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?

-  Caddy 0.10.3

### 2. What are you trying to do?

- File browser

### 3. What is your entire Caddyfile?
``` text
0.0.0.0 {
        browse /
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

- caddy

### 5. Please paste any relevant HTTP request(s) here.

- `http://127.0.0.1:2015/`

### 6. What did you expect to see?

- Now plugin http.browse args relative to current command running path.
- Is there any way plugin http.browse args could be a absolute path?

**Comment by francislavoie** [comment]
Yes, specify `root`.

https://caddyserver.com/docs/root

For future reference, questions like this should be asked on the forums, as noted in the issue template.
