### ISSUE TITLE
Redirect loop when rewriting from directory URI to file URI

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#1706]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.3

### 2. What are you trying to do?

Rewrite `/` to `/file.html`.

### 3. What is your entire Caddyfile?
```text
localhost

rewrite {
	if {mitm} not likely
	to /file.html
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

### 5. Please paste any relevant HTTP request(s) here.

`curl -v http://localhost:2015/`

### 6. What did you expect to see?

Since there's no MITM, I expect to see the contents of `/file.html`.

### 7. What did you see instead (give full error messages and/or log)?

Redirect loop, 301'ing to location `/`.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

See above.

The problem is that the static file server reads and redirects the external, un-rewritten URI instead of the internally-rewritten URI. The external, incoming URI is `/` (a directory) but the rewritten one is `/file.html` (a file). This causes the file server to redirect to a canonical URI. Since the redirect is _external_, it uses the original, un-rewritten URI for this.

I think this was introduced in #1633.

This might (?) be related to #1701, although this bug is definitely in the static file server.

**Comment by renaudguerin** [comment]
I believe this issue, or a very similar one, is still occurring in 0.10.11

All of the details are below (the thread is closed but I can confirm the problem is still here in 0.10.11, and did not occur in 0.9.x )
https://caddy.community/t/basicauth-exception-for-a-health-check-url-or-rewrite-exactly/2159

**Comment by Whitestrake** [comment]
Possible this is because you're rewriting to `/index.html`, which is a unique case as I believe the file server redirects these requests to the index `/`.
