### ISSUE TITLE
Add request_size placeholder for logging

### ISSUE THREAD

**Issue by bkcsfi** [mholt/caddy#1708]
I am using caddy as a front-end server for a Python based AS2 server. The AS2 server is receiving 'truncated' messages from an MS Biztalk server.

Unfortunately I cannot determine where the truncation is happening. I assume it's biztalk itself, or a failed tcp connection.  But it could be between caddy and the AS2 server, or the AS2 server itself.

Having a request_size placeholder would help me debug this issue by allowing me to compare the request size vs the stated content-length in the http headers, the later is being logged by the AS2 server.

**Comment by mholt** [comment]
The problem with this is we don't know the actual content length until we read it... which has a few problems:

- The content can't be used
- To use the consumed body, we'd have to buffer a copy of the whole thing
- We could populate the placeholder only if the body is read for some purpose (like proxying upstream) but it's not necessarily the true value then if the connection is dropped or some other error happens...

**Comment by bkcsfi** [comment]
Hi, thanks for responding. It sounds like you're saying that under some conditions the socket can be passed to another process and that caddy itself may not read the socket, so doesn't know the actual number of bytes read.

I can see that would make this feature difficult to add.

In the meantime to resolve my particular problem I have setup tcpflow logging in the hopes of capturing a 'bad' transmission.   

Given the difficulty of implementing the feature request and the fact that external tools do exist that might be able to help me achieve my goal of pinpointing transmission problems, I respectfully ask that you reject my feature request.

Thanks

**Comment by mholt** [comment]
> It sounds like you're saying that under some conditions the socket can be passed to another process and that caddy itself may not read the socket, so doesn't know the actual number of bytes read.

No, that's not quite what I meant. I was just talking about the request body; once it's drained, it's either gone or buffered. If we let some other middleware read the body (like a proxy middleware) and we just count the number of bytes it reads, that's possible.

**Comment by bkcsfi** [comment]
I think I have found a possible issue with caddy not proxying chunked encoding downstream correctly, I will open  a new issue. hopefully its just a config problem

**Comment by mholt** [comment]
Okay, new issue sounds great. I'll close this one at your request, but the discussion is allowed to continue as needed, of course.
