### ISSUE TITLE
I cannot download Caddy with the options I requested

### ISSUE THREAD

**Issue by dschissler** [mholt/caddy#1712]
(Are you asking for help with using Caddy? Please use our forum instead: https://caddy.community. If you are filing a bug report, please take a few minutes to carefully answer the following questions. If your issue is not a bug report, you do not need to use this template. Thanks!)

### 1. What version of Caddy are you using (`caddy -version`)?

Can't download

### 2. What are you trying to do?

I'm trying to download Caddy with specific plugins.

### 5. Please paste any relevant HTTP request(s) here.

```
wget https://caddyserver.com/download/linux/amd64?plugins=http.filemanager,tls.dns.gandi
--2017-06-14 22:47:02--  https://caddyserver.com/download/linux/amd64?plugins=http.filemanager,tls.dns.gandi
Resolving caddyserver.com (caddyserver.com)... 138.68.240.78, 2604:a880:2:d0::1145:e001
Connecting to caddyserver.com (caddyserver.com)|138.68.240.78|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2017-06-14 22:47:44 ERROR 500: Internal Server Error.
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Simply run the wget command.

**Comment by dschissler** [comment]
It works with the generic URL `https://caddyserver.com/download/linux/amd64` but not with the custom options which I selected.

**Comment by dschissler** [comment]
It seems that just adding the Gandi DNS provider breaks it: `https://caddyserver.com/download/linux/amd64?plugins=tls.dns.gandi`.

**Comment by dschissler** [comment]
`wget https://caddyserver.com/download/linux/amd64?plugins=tls.dns.dnspod` works.  It seems that only the Gandi plugin is broken.

**Comment by mholt** [comment]
Aha, that's actually good news, it means the system works I think it does!

(I had the gandi DNS provider plugin set to the `origin/master` release which always pulls the latest, whereas every other DNS provider is just set to release `master` which doesn't always pull from origin. You know, git things.)

I've redeployed this plugin at commit bbadd53f2ab1e5193e280e8cdddc2d5aae35c619 which should be before the breaking change.
