### ISSUE TITLE
Smal documentation bug in fastcgi 

### ISSUE THREAD

**Issue by dschissler** [mholt/caddy#1714]
https://caddyserver.com/docs/fastcgi

The directive description is different than the actual directive.  Its my first time and I kept scanning for "root" and I couldn't find it.

**directory** specifies the root directory used by the FastCGI server if different from the root directory of the virtual host. Useful if the FastCGI server is on a different server, chroot-jailed, and/or containerized.

should be:

**root** specifies the root directory used by the FastCGI server if different from the root directory of the virtual host. Useful if the FastCGI server is on a different server, chroot-jailed, and/or containerized.

**Comment by dschissler** [comment]
I suppose that its not technically incorrect but it doesn't make much sense.  I think that if you look at it with new eyes then you'll see that it should be different.

**Comment by mholt** [comment]
Oh, yeah, that should be fixed. Thanks for bringing it up! Although https://github.com/caddyserver/website is the right repo for mentioning this. ;)

**Comment by dschissler** [comment]
Oh ya.  I knew I was being bad when I posted here but I scanned the repo list and since I was on a bender I was too tired to find it.
