### ISSUE TITLE
Is it possible to rewrite assets to another directory? 

### ISSUE THREAD

**Issue by dschissler** [mholt/caddy#1715]
### 1. What version of Caddy are you using (`caddy -version`)?

`0.10.3`

### 2. What are you trying to do?

 I'm trying to reference files outside of the root path in my development environment.  My build environment puts it all together.  The following snippet is from my nginx config.  I don't know if there is a way to do it in caddy.

```
  location ~ ^/assets/(.+)$ {
    root "{{config.path.appDir}}theme/assets";
    rewrite ^/assets/(.*)$ /$1;
    break;
  }
```

### 3. What is your entire Caddyfile?

Caddyfile only includes this file below:

```text
{{config.site.domains[0]}}:8080 {
  tls off
  root {{config.dev.path.devDir}}public

  fastcgi / 127.0.0.1:9000 php {
    index index.php
  }

#  rewrite /assets {
#    r /(.*)
#    root "{{config.path.appDir}}theme/assets"
#    to /{1}
#    rewrite ^/assets/(.*)$ /$1; break;
#  }

  rewrite / {
    if {path} not_match ^\/assets
    r /(.*)
    to {path} index.php?url={1}&{query}
  }
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

I'm running Ubuntu 16.04 with systemd service file.

**Comment by mholt** [comment]
Thanks for your question, although in the future please use [the forum](https://caddy.community) for usage questions; issues are for active development-focused discussion.

Caddy locks access (from requests) to the file system to within the root directory; individual middlewares aren't _required_ to honor this (but they are strongly encouraged to; it depends on the use case). For example, the `log` directive can write to a log file outside of the site root, and the `git` plugin can pull to areas outside the site root, but these locations are explicitly defined in the Caddyfile; allowing requests to access the file system outside of the root is a very, very bad idea.

If you need to do this, you could make your site root less specific (remove elements from the path), thus moving the dir you need to get into in the root of the site; of course, this'll expose other directories in the tree, too.
