### ISSUE TITLE
Push more than one file (multiple links per Link header)

### ISSUE THREAD

**Issue by si14** [mholt/caddy#1717]
I'm sorry for not following the template, but I'm not sure if it makes sense in this case.

I use Caddy to push resources from the backend. To do this conditionally, I use Link header and a little bit of logic in the backend. However, if I understand Caddy's code correctly, it's currently implied that one Link header = one resource. Unfortunately, a lot of backends (e.g. Django) don't really support multiple headers with the same name, limiting http2 push to one resource.

Cloudflare had exactly this problem and solved it by allowing multiple links per Link header: https://blog.cloudflare.com/http-2-server-push-with-multiple-assets-per-link-header/ Do you think it's reasonable to do the same in Caddy?

**Comment by xfalcox** [comment]
Oh just got this problem too, looks like in Rails it's the same.

**Comment by wendigo** [comment]
Here you go: https://github.com/mholt/caddy/pull/1798/files
