### ISSUE TITLE
systemd service file goes into bad state and won't restart caddy

### ISSUE THREAD

**Issue by dschissler** [mholt/caddy#1718]
### 1. What version of Caddy are you using (`caddy -version`)?

`0.10.3`

### 2. What are you trying to do?

I'm trying to restart caddy while testing new configs and after a while it will not restart.

### 3. What is your entire Caddyfile?
```text

{{config.site.domains[0]}}:8080 {
  tls off

  root {{config.dev.path.devDir}}public
  gzip

  fastcgi / 127.0.0.1:9000 php
  rewrite / {
    r /(.*)
    to {path} index.php?url={1}&{query}
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

I'm using Ubuntu 16.04 and restarting in the terminal with `systemctl restart caddy`.

### 7. What did you see instead (give full error messages and/or log)?

@klingtnet posted this on https://github.com/mholt/caddy/issues/711#issuecomment-308885617

It looks like the settings for StartLimitInterval, StartLimitBurst are to conservative.

```
$ journalctl -xefu caddy
Jun 15 18:02:08 m253 systemd[1]: caddy.service: Unit entered failed state.
Jun 15 18:02:08 m253 systemd[1]: caddy.service: Failed with result 'start-limit-hit'.
Jun 15 18:02:10 m253 systemd[1]: caddy.service: Start request repeated too quickly.
```

A workaround is to [deactivate the start limit check](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=) until we decided which values StartLimitInterval, StartLimitBurst should be set to.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

To reproduce the problem simply start caddy's service `systemctl start caddy` call `systemctl restart caddy` and it will fail to restart eventually (after ~10 retries on my machine).

**Comment by neilstuartcraig** [comment]
FWIW, i hit this issue too and decided to bin the restart limit for the moment. i don't find it particularly useful anyway in all honesty.

**Comment by dschissler** [comment]
Maybe I'm missing something but I think that if the system is continually restarting a vital service so much for whatever reasons then there are worse problems to deal with.

**Comment by unquietwiki** [comment]
I ended up writing my own systemd service a few days ago; and that was before finding the default one elsewhere on the site.

* Ubuntu 16.04.2 LTS, installed as  **/etc/systemd/system/caddy.service**
* Created a user with **useradd -m caddy**
* Using /etc/default/caddy as my config file: seems to be in keeping with how to edit services on Ubuntu and RHEL/CentOS.

```
[Unit]
Description=Caddy Server
After=network.target
[Service]
Type=simple
LimitNOFILE=8192
ExecStart=/usr/local/bin/caddy -conf /etc/default/caddy
User=caddy
Group=caddy
[Install]
WantedBy=multi-user.target
```

**Comment by mholt** [comment]
Closing, since there is a PR open that seems to relate to this.
