### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by ahmdrz** [mholt/caddy#1721]
Hi , I'm using Caddy 0.10.3.
With caddy I can handle multi websites using proxy connection.
But sometimes I receive 502 error from my website response.

In error file :

`17/Jun/2017:23:09:44 +0430 [ERROR 502 /] dial tcp :1224: socket: too many open files`

How can I fix this ?

A part of my caddy file is :

```
        proxy / :1224 {
                except (static files)
        }
        root ###/server/public
        errors ###.errors
        tls {
                dns cloudflare
        }
        ratelimit 20 20 hour {
                /login routes
        }
        ratelimit 20 20 minute {
                /api routes
        }
```

I have more than 5 websites that using proxy with caddy...

**Comment by mholt** [comment]
What's the output of `ulimit -n`?

**Comment by ahmdrz** [comment]
The output is `1024`

**Comment by ahmdrz** [comment]
I changed it with `ulimit -n 8192` So now the output is `8192`, Hope fix the problem.
Thank you @mholt for Caddy.

Regards.
