### ISSUE TITLE
Caddyfile config for Supervisor web

### ISSUE THREAD

**Issue by temamagic** [mholt/caddy#1726]
On Nginx my config looks like
```
server {
    listen 80;
    server_name supervisor.domain.name;
    location / {
        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;
        proxy_pass http://localhost:9001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

How should it look right in Caddyfile?
I tried this:
```
supervisor.domain.com { 
  basicauth / user pass
  proxy / localhost:9001
}
```

It works, but when I press any buttons, i see that my page url is changed to 

`http://localhost:9001/?message=Page%20refreshed%20at%20Wed%20Jun%2021%2000%3A46%3A33%202017`
What am I doing wrong?

**Comment by mholt** [comment]
Hey @temamagic - thanks for your question. I'm not really sure what is going on here (it's something your backend is doing), but a better place to ask this would be in the **[community forum](https://caddy.community)** where there are more people who can answer your question! These issues are for Caddy development only, so it's less likely that someone here has used "Supervisor web".  I invite you to ask your question over there! :+1:
