### ISSUE TITLE
ext: Only append extension if request path is not a directory

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#173]
Given a file structure like this in the site root:

```
/
  /foo        (empty directory)
  /foo.html   (file)
```

and this ext directive:

```
ext .html
```

A request to /foo should serve /foo.html, but a request to /foo/ (notice the trailing slash) should serve the directory. This is especially noticeable when the `browse` middleware is also enabled, which should turn on file listings for directories.

Changing a line in ext.go to add a second condition would fix this:

```go
if path.Ext(urlpath) == "" && r.URL.Path[len(r.URL.Path)-1] != '/' {
```

I'd really like to fix this. Even though it is against the standard, it might break people if they expect /foo/ to serve /foo.html. Thoughts?

(Note: I'm okay with breaking changes pre-1.0. I'd rather we get it right while we can.)

**Comment by abiosoft** [comment]
I agree with this. If a directory exists then `/foo/` should serve the directory.

**Comment by guilhermebr** [comment]
I agree.

**Comment by pedronasser** [comment]
I agree.
