### ISSUE TITLE
Problem with requests without a trailing slash (some cases)

### ISSUE THREAD

**Issue by PaulsBarkans** [mholt/caddy#1732]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.3

### 2. What are you trying to do?
Problem: Caddy does not redirect a request without a trailing slash to location with a trailing slash if a folder exists and user makes a request without a trailing slash. This happens if both fastcgi and rewrite modules are used and also if a folder contains index (index.php) file.

Sample project structure is like this:
```
/www/default
├── folder
│   └── index.php
└── index.php
```

### 3. What is your entire Caddyfile?
```text
localhost:80 {
  root /www/default
  fastcgi / localhost:9000 php
  rewrite {
    to {path} {path}/ /index.php?{query}
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf /etc/caddy/Caddyfile

### 5. Please paste any relevant HTTP request(s) here.
```
# curl -v http://localhost/folder
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /folder HTTP/1.1
> Host: localhost
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=UTF-8
< Server: Caddy
< Date: Tue, 27 Jun 2017 21:26:59 GMT
< Content-Length: 34
< 
Content of a /folder/index file..
* Connection #0 to host localhost left intact
```

### 6. What did you expect to see?
I expected to see a 301 redirect to location /folder/. 

### 7. What did you see instead (give full error messages and/or log)?
Header 200 and output of a /folder/index.php

Please note that Nginx and Apache does redirect to /folder/ in similar configuration. 

P.S. I noticed that if /folder/index.php file is removed, response does have a redirect.
```
# rm folder/index.php 
# curl -I http://localhost/folder
HTTP/1.1 301 Moved Permanently
Location: /folder/
Server: Caddy
Date: Tue, 27 Jun 2017 21:34:05 GMT
Content-Type: text/plain; charset=utf-8
```
Redirect also happens if fastcgi or rewrite modules are removed from the configuration.

I hope this can be fixed/improved as applications in some cases expect to have a slash at the end or they break.

**Comment by mholt** [comment]
Hmm, well in this case, your PHP backend is handling the request. Why isn't it issuing the redirect? When Caddy serves static files, it issues redirects because that's it's job, but when it's proxying... not so much the case.

**Comment by mholt** [comment]
What happens if you change the `to` line to be `to {path}/ {path} /index.php?{query}`?

**Comment by PaulsBarkans** [comment]
> Hmm, well in this case, your PHP backend is handling the request. 

Should it though at this point? Shouldn't the server make a redirect because of a rewrite rule `{path}/` ? 

> but when it's proxying... not so much the case

Sorry, what do you mean by "proxying"? Do you mean the fastcgi part or the rewrite part?

You see, if I leave just the fastcgi/php part, the redirect happens and php is not handling the initial request. With configuration like this:
```
localhost:80 {
  root /www/default
  fastcgi / localhost:9000 php
}
```
..there is a redirect:
```
# curl -I http://localhost/folder
HTTP/1.1 301 Moved Permanently
Location: /folder/
```

Redirect also happens if I leave just the rewrite part and remove fastcgi part.
```
localhost:80 {
  root /www/default
  rewrite {
    to {path} {path}/ /index.php?{query}
  }
}
```

```
# curl -I http://localhost/folder
HTTP/1.1 301 Moved Permanently
Location: /folder/
```

---

> Why isn't it issuing the redirect?

I'm not sure as I'm not an author of a php application that was installed in the subfolder, but I suspect because other web servers (nginx, apache) does not behave in this way and developers don't have this in mind while developing software. Php logic is outside of the scope in this case as i've created empty php files for testing.

For testing purposes I also created a nginx configuration like this:
```
server {
        listen 8080;
        root /www/default;
        server_name _;

        location ~ \.php$ {
                fastcgi_pass 127.0.0.1:9000;
        }

        location / {
                try_files $uri $uri/ /index.php?$query_string;
        }
}
```
This configuration is very similar but because of `$uri/` the redirect also happens as expected, php is not handling the initial request:
```
# curl -I http://localhost:8080/folder
HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.0 (Ubuntu)
Date: Wed, 28 Jun 2017 07:09:44 GMT
Content-Type: text/html
Content-Length: 194
Location: http://localhost:8080/folder/
```

---

I can probably fix this by modifying php part or maybe make a manual redirect in configuration, but I filled out this issue as I was thinking that Caddy should behave similar to other web servers and should not rely on workarounds.

> I'm not sure if this will do anything different, but what happens if you change the to line to be to {path}/ {path} /index.php?{query}?

You are right, this does not change the outcome.

**Comment by mholt** [comment]
Thanks for elaborating!

> Should it though at this point? Shouldn't the server make a redirect because of a rewrite rule {path}/ ?

No, rewrites aren't redirects. Rewrites are internal; redirects are external.

> Sorry, what do you mean by "proxying"? Do you mean the fastcgi part or the rewrite part?

Yes, sorry for the confusion: fastcgi. FastCGI is a proxy to a fastcgi responder.

So far it looks like Caddy is behaving as I intended. Caddy's redirect-to-canonical-URL behavior is implemented in its static file server. If the static file server isn't serving the request, then the redirect won't happen from within Caddy. You can manually configure these redirects with the Caddyfile, of course.

Yes, it's a little different than other web servers. But I think this makes more sense, frankly. 😁

**Comment by PaulsBarkans** [comment]
> No, rewrites aren't redirects. Rewrites are internal; redirects are external.

Yes, the fundamental difference is clear. What I meant was.. because the rule with the trailing slash matches request, web server should not proxy it to php but rather interpret it as a static resource (because folder exists on the file system) and so the redirect should happen as it would for static content. I don't know, I guess I was also looking at the examples in documentation where I saw this line: 

> [...] and path is not a valid file/directory, rewrite to the mobile index page

.. and I got a bit confused with my own configuration. Now I realized it's really not about rewriting when "_is not a valid file/directory_". In my case thinking about this in a way of "_rewrite to this resource (if it exists), otherwise rewrite to /index.php_" would help me avoid the confusion. But that's on me. I think I got this now.

> Yes, it's a little different than other web servers. But I think this makes more sense, frankly.

I like this :) it does make sense, thank you for taking time to explain and looking into this. Much appreciated!

**Comment by mholt** [comment]
> Yes, the fundamental difference is clear. What I meant was.. because the rule with the trailing slash matches request, web server should not proxy it to php but rather interpret it as a static resource (because folder exists on the file system) and so the redirect should happen as it would for static content.

Ah, so `fastcgi` is configured to handle all requests to `/` that meet its criteria, which your request did. The static file server takes over if nothing else handles the request.

>  I don't know, I guess I was also looking at the examples in documentation where I saw this line:

Yeah, it rewrote the request path (or not), but it doesn't change how the request is actually handled, since fastcgi still found it to match its criteria.

> In my case thinking about this in a way of "rewrite to this resource (if it exists), otherwise rewrite to /index.php" would help me avoid the confusion.

That makes more sense. Would you like to submit a PR to [caddyserver/website](https://github.com/caddyserver/website) to improve the wording in a way that's not as confusing?

Thanks for the issue!
