### ISSUE TITLE
Revert fastcgi's persistent connections

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#1736]
I propose we revert #1082 and #1087 (which was finalized in #1129). While I appreciate the contributions by @Echsecutor and later refinement by @abiosoft, it has added considerable complexity and some obscure bugs, which we haven't been able to figure out without Sebastian's help.

The issue is complex and not well understood, so even if there is a way to fix it, I would still like to gut the feature first then, if there is demand for it, re-implement it carefully as long as there is a strong, compelling explanation of and resolution for the symptoms.

Problems were first reported in #1204 by @adamwathan and @taylorotwell, developers of Laravel Valet, which was using Caddy but then switched back to nginx after problems with, I suspect (but have not actually confirmed, I admit), the persistent fastcgi connections. [Persistent connections were introduced in 0.9.2](https://github.com/mholt/caddy/compare/v0.9.1...v0.9.2) but were [broken](https://github.com/mholt/caddy/issues/1123); they were ["fixed" between 0.9.2 and 0.9.3](https://github.com/mholt/caddy/compare/v0.9.1...v0.9.2). Combined, these were the only changes made to fastcgi between 0.9.1 (working) and 0.9.3 (reportedly sporadically broken).

More recently, reports have come in that have me suspecting the same culprit:

- #1722 and its related [forum thread 2194](https://caddy.community/t/getting-fairly-frequent-502-bad-gateway-errors/2194?u=matt)
- [Forum thread 1419](https://caddy.community/t/php-fpm-via-fastcgi-throws-502-bad-gateway-after-10-requests/1419?u=matt)
- [Forum thread 1453](https://caddy.community/t/502-under-heavy-load-benchmark-test-with-low-load-no-problem/1453?u=matt)

This revert is more than just clicking the button because the files have changed since the commits took place.

Essentially, we need to revert pretty much all the changes in #1087, #1129, and probably #1134.

Abiola, would you be able to spearhead this? It is just a revert, so it won't really involve writing new code, but the git revert won't be clean. You'll have to manually wrangle it a bit.

The hope is that we can get this pushed to a branch so the Laravel Valet developers can test it, as well as other affected users!

**Comment by abiosoft** [comment]
Yeah. I'll help with this, as previously discussed.

**Comment by mholt** [comment]
Thanks Abiola. Always a refreshing thing to have your contributions, which make possible things I couldn't do on my own. :smile:
