### ISSUE TITLE
rewrite with regexp stopped working in 0.10.4

### ISSUE THREAD

**Issue by ubergesundheit** [mholt/caddy#1743]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.4 on linux 64 bit

### 2. What are you trying to do?
Use this rewrite
```
  rewrite /explore {
    regexp .*
    to /index.html
}
```

### 3. What is your entire Caddyfile?
https://github.com/sensebox/osem-caddy/blob/master/vhosts/opensensemap.enabled

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Caddy is running in docker image derived from abiosoft/caddy 
https://github.com/sensebox/osem-caddy

### 5. Please paste any relevant HTTP request(s) here.
This request is made against Caddy 0.10.4 with the Caddyfile from above

```bash
$ curl -I "https://opensensemap.org/explore/57946712d0a5af1100ccd9d3"
HTTP/2 301 
cache-control: public, max-age: 300
location: /
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
content-type: text/plain; charset=utf-8
date: Tue, 04 Jul 2017 06:36:01 GMT
```

### 6. What did you expect to see?
This request is made against Caddy 0.10.3 with the Caddyfile from above
```bash
$ curl -I "https://opensensemap.org/explore/57946712d0a5af1100ccd9d3"
HTTP/2 200 
accept-ranges: bytes
cache-control: public, max-age: 300
content-type: text/html; charset=utf-8
etag: "or6bdk5il"
last-modified: Wed, 07 Jun 2017 10:48:56 GMT
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block
content-length: 7149
date: Tue, 04 Jul 2017 07:17:56 GMT
```
### 7. What did you see instead (give full error messages and/or log)?
The rewrite works as intended in Caddy 0.10.3 and all versions of 0.9.x before.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Obtain binaries of Caddy 0.10.4 and 0.10.3 and run the Caddyfile mentioned above.

**Comment by tw4452852** [comment]
I think the final redirection comes from static file server:

At first, your request URL is `https://opensensemap.org/explore/57946712d0a5af1100ccd9d3`, after rewrite middleware, it turns into: `https://opensensemap.org/index.html`. Finally it comes into static file server, obviously this URL points to index file, so static file server strips the file part and gives a redirection to `/`.

I think this is triggered by [this commit](https://github.com/mholt/caddy/commit/021eff91bd3d3b1c47e15f2a7157f714c4f06898).

**Comment by mholt** [comment]
Yep, this is actually a bug _fix_. And a duplicate issue. ;) See #1737 and #1732 for instance. Thanks!

**Comment by ubergesundheit** [comment]
thanks
