### ISSUE TITLE
UNIX time stamp for `when`

### ISSUE THREAD

**Issue by jeffling** [mholt/caddy#1745]
http://help.apm.scoutapp.com/#request-queuing

Hi, this monitoring package we use requires that we have use a unix timestamp in the header. 

https://caddyserver.com/docs/placeholders

seems to imply we only have ISO and "Human Readable" formats right now. Are there any plans to allow users to set the timestamp format?

**Comment by mholt** [comment]
Not as yet, but we can add it to our list! This should be fairly easy. `when_unix` maybe?

**Comment by jeffling** [comment]
@mholt that would work perfectly :)

**Comment by tobya** [comment]
fixed in #1748
