### ISSUE TITLE
Requesting dynamic client-side redirects

### ISSUE THREAD

**Issue by diazona** [mholt/caddy#1749]
I'm making this feature request to consolidate previous requests for dynamic redirects, by which I mean the ability to issue client-side redirects (HTTP 3xx status codes) based on matching the URL to a pattern - presumably a regular expression - not just a fixed string. `redir` already issues client-side redirects but cannot match a URL pattern, whereas `rewrite` can match patterns using regular expressions, but doesn't do client-side redirection, so neither of these existing directives are significant.

# Background and justification

This has been previously brought up in

- Issue #726 
- Issue #856 
- [One forum thread](https://caddy.community/t/rewrite-with-redirect-or-redirect-with-regex/600) related to #726 
- [Another forum thread](https://caddy.community/t/any-chance-of-dynamic-redirects/2261) (my own, which prompted opening this issue)

Those pages identify several situations in which dynamic redirection would be useful:

- redirect all URLs with a given file extension, with the new URL depending on the old one
- redirect all URLs under a directory tree, with the new URL depending on the old one
- stripping or adding terminal slashes
- redirecting URLs with single-digit months to have leading zeros

In each case internal rewriting as performed by `rewrite` is not suitable because it's necessary to signal a change in the page's location to search engines and other visitors.

All of these cases can be addressed with workarounds, but in some cases the workaround is rather impractical, like creating a long list of exact-match redirect rules ([1](https://caddy.community/t/rewrite-with-redirect-or-redirect-with-regex/600/4?u=diazona), [2](https://caddy.community/t/any-chance-of-dynamic-redirects/2261/5?u=diazona)). That wouldn't even work if, say, the destination URL is proxied on to a dynamic backend site where it's not possible to enumerate all valid destinations. (Though in that case one could probably let the backend handle the redirection, but it's not hard to imagine reasons that might be difficult.) So even though it could be argued that dynamic redirection isn't _necessary_, it would massively simplify the configuration in a wide variety of situation.

Plus, dynamic client-side redirects is something that webmasters typically expect a server to do. Most (all?) other popular web servers include this functionality. I think there are enough cases justifying it that it's worth implementing in Caddy too.

**Comment by astei** [comment]
I've actually been looking to implement this feature, so I'm going to consider giving this a go.

**Comment by mholt** [comment]
This is made much easier in Caddy 2.
