### ISSUE TITLE
hook.pluginloader is error

### ISSUE THREAD

**Issue by zuohuadong** [mholt/caddy#1756]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.4

### 2. What are you trying to do?
```
curl https://getcaddy.com | bash -s hook.pluginloader
```

curl: (22) The requested URL returned error: 500

**Comment by abiosoft** [comment]
The documentation for [Plugin Loader](https://caddyserver.com/docs/hook.pluginloader) clearly stated that it is not compatible with Caddy's build server yet.

> NOTE: plugin currently incompatible with build server. Do not download. Alternative instructions are on plugin website.

However, you can follow the instructions on the project page to install it.

Firstly install caddyplug.
```
go get github.com/abiosoft/caddyplug/caddyplug
```
Then use caddyplug to install caddy and other plugins as demonstrated in [this video](https://www.youtube.com/watch?v=uKSgHhh6-rA).
