### ISSUE TITLE
Cannot register custom directive

### ISSUE THREAD

**Issue by nicolasazrak** [mholt/caddy#1758]
After developing my plugin using `RegisterDevDirective` I want to make a pull request to get it published. I added it to run.go like the docs say (https://github.com/mholt/caddy/wiki/Extending-Caddy) in https://github.com/nicolasazrak/caddy/commit/2f29d154b10ee04fdf32bd7e40ee3e0a496dbeae but after compiling ok it does not recognize the cache directive. 

Am I doing something wrong? Something I have doubts is the position the plugin should have. Can it cause any trouble registering it before root?

### 1. What version of Caddy are you using (`caddy -version`)?
master branch

### 2. What are you trying to do?
Add a new plugin (https://github.com/nicolasazrak/caddy-cache)

### 3. What is your entire Caddyfile?

```text
caddy.test:2015 {
  root /tmp/caddy-benchmark
  cache
}  
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
cd caddy/
./build.bash
./caddy
```

### 6. What did you expect to see?

The plugin working. 

### 7. What did you see instead (give full error messages and/or log)?

`Caddyfile:3 - Parse error: Unknown directive 'cache'`

**Comment by mholt** [comment]
Huh, that _should_ work. What is the output of `caddy -version`? Are you absolutely sure you're in the folder of your fork?

**Comment by nicolasazrak** [comment]
I finally resolved it. When forking a go repo every import get broken. As imports are absolute my fork was importing the original code and not my fork code. So any change I made was not compiled.
