### ISSUE TITLE
Add support for {upstream} in headers

### ISSUE THREAD

**Issue by gregmac** [mholt/caddy#1762]
The `{upstream}` placeholder only works in log files, but it would be useful for debugging if it could be added to response headers, for example:

    header_downstream X-Backend {upstream}

**Comment by mholt** [comment]
I have a hunch; we set the `{upstream}` placeholder [here in proxy.go](https://github.com/mholt/caddy/blob/ba1132214e29fc9a47ad012cc6584b691d01adf4/caddyhttp/proxy/proxy.go#L165) for the Replacer on the ResponseWriter, but we use [a separate Replacer for the proxy itself](https://github.com/mholt/caddy/blob/ba1132214e29fc9a47ad012cc6584b691d01adf4/caddyhttp/proxy/proxy.go#L104) -- maybe we should use the same Replacer (not guaranteed to exist on the ResponseWriter, but sometimes will, like if using `log`!) or set the placeholder on both.

This is an easy-medium difficulty task, that requires a little investigation and some ingenuity to make a nice, clean solution with an elegant/simple test case. I'll open this up if anyone wants to contribute it!

**Comment by mholt** [comment]
Hey @tobya - do you think this issue is improved with #1937?

**Comment by mholt** [comment]
I have a feeling this works now, with the PR I linked to. Closing, unless it's shown otherwise.
