### ISSUE TITLE
Add support for conditions in errors

### ISSUE THREAD

**Issue by jovandeginste** [mholt/caddy#1764]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.4

### 2. What are you trying to do?
I have a Caddy server serving error pages, in case the actual server is gone (for whatever reason). This is easy. However, sometimes the real server is gone because of planned maintenance. It would be useful to me if we could also plan the error page accordingly.

Basically, default error page: "we-are-down-please-call-us.html"
Error page between 15/07/2017 and 17/07/2017: "we-are-upgrading-please-dont-call.html"

I tried to use `rewrite` (which supports conditions and I think even time based, using `when`), but error pages are not rewritten...

**Comment by jovandeginste** [comment]
I just found a way around this. Maybe everyone knew this already, but for anyone not knowing, this is my solution:

```Caddyfile
http://example.net:18080 {
	root ./sites/example.net/
	header / {
		Cache-Control "private,no-cache,must-revalidate"
	}

	rewrite {  # Planned maintenance on 2017-07-15
		if {when_iso} starts_with 2017-07-15T
		to /maintenance.html
	}
	rewrite { # Default case, 
		to /unreacheable.html
	}
}

http://example.net:18080/maintenance.html {
	root ./sites/example.net/
	errors {
		404 maintenance.html
	}
}

http://example.net:18080/unreacheable.html {
	root ./sites/example.net/
	errors {
		404 unreacheable.html
	}
}
```

I can not find any way to specify time ranges - I suppose this is not implemented yet?

**Comment by mholt** [comment]
Interesting idea, thanks for the feature request! I'll consider it.

**Comment by jovandeginste** [comment]
@mholt my above solution does not work since any existing files in `./sites/example.net/` are not served (but also redirected). Is there a way to rewrite non-existing paths only? I need css, jpg, ... to be served in my beautifully styled maintenance page :-)

**Comment by jovandeginste** [comment]
@mholt Obviously, making `if ...` commands possible inside the `errors` stanza would probably fix the whole thing

**Comment by jovandeginste** [comment]
(I can obviously add any number of extra conditions to the `rewrite` stanza, like this:)

```Caddyfile
    if {path} not_ends_with png 
    if {path} not_ends_with gif 
    if {path} not_ends_with jpg 
```

**Comment by mholt** [comment]
Routing conditional on timestamps is now implemented in Caddy 2.
