### ISSUE TITLE
Support certificates from Windows Certificate Store

### ISSUE THREAD

**Issue by kostrse** [mholt/caddy#1765]
Would be great to have support for Certificate Store for storage of TLS certificates on Windows.
It would make managing secrets on machine much easier.

As I understand this is not supported now but potentially can be implemented via pluggable certificate manager (#860).

Is this on radar for implementation (as first-party or third-party plugin), or maybe someone could share any insight on it?

**Comment by tobya** [comment]
This would certainly be a possibility.  Is there expertise in Microsoft to get this set up in GO.  My initial thought is it probably works best as a plugin, and we are always delighted to get PR's!

**Comment by mholt** [comment]
This is possible now, someone just has to implement the [certmagic.Storage interface](https://godoc.org/github.com/mholt/certmagic#Storage) using Windows Certificate Store.
