### ISSUE TITLE
undefined: Context  undefined: ServerListener

### ISSUE THREAD

**Issue by goodforever** [mholt/caddy#1766]
go build caddy.go  (go version go1.8.3)
./caddy.go:78: undefined: Context
./caddy.go:81: undefined: ServerListener

**Comment by elcore** [comment]
Caddy binaries have no dependencies and are available for every platform. Get Caddy any one of these ways:

Download page allows you to customize your build in the browser

Latest release for pre-built, vanilla binaries

go get to build from source: go get github.com/mholt/caddy/caddy (requires Go 1.8 or newer)

**Comment by goodforever** [comment]
where is the run file after build?

**Comment by mholt** [comment]
Go get will put the binary in $GOPATH/bin; if you use `go build` or this repo's `build.bash` then it'll be in the current folder.
