### ISSUE TITLE
Caddy pushes in incorrect order

### ISSUE THREAD

**Issue by twdkeule** [mholt/caddy#1776]
### 1. What version of Caddy are you using (`caddy -version`)?
master

### 2. What are you trying to do?
use server push

### 3. What is your entire Caddyfile?
```text
push /push0.html {
    /dash.all.debug.js	
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`$GOPATH/bin/caddy -http2=true`

### 6. What did you expect to see?
The server should first respond to the original request (200 header, push_promise and data) before sending all the push resources (200 header and data). 

### 7. What did you see instead (give full error messages and/or log)?
The server first sends responses for the push resources (push_promise, 200 header and data) and only afterwards responds to the initial requet (both header and data).
This drastically decreases performance when pushing a lot of data as the client has to wait for all pushed resources before receiving the initial page.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Serve 2 files, push one of them, watch with Wireshark.
Here are my logs: https://www.dropbox.com/sh/oucup2az15tmzhq/AACG45efML_zl7LhX7rXNarMa?dl=0

I am already trying to fix it.

**Comment by twdkeule** [comment]
The push_promise should be sent before the initial response so the order is correct in Caddy.

**Comment by mholt** [comment]
@twdkeule By the way, if you have in fact verified this claim:

> The server first sends responses for the push resources (push_promise, 200 header and data) and only afterwards responds to the initial requet (both header and data). This drastically decreases performance when pushing a lot of data as the client has to wait for all pushed resources before receiving the initial page.

Then perhaps it is worth opening an issue with Go about this. I'm under the impression that Push() only sends PUSH_PROMISE frames, not necessarily pushing the data (content) of the promise immediately. I'd have to dig deeper, but from reading the spec and docs, it seems to be just a promise that the data will be sent; that the stream is reserved for future use.
