### ISSUE TITLE
Log to syslog

### ISSUE THREAD

**Issue by stephane-martin** [mholt/caddy#178]
This one should be an easy feature:
1 - provide a way to log to the system syslog (eg using standard C syslog function).
2 - Possible enhancement: log to a remote syslog (TCP or UDP).

Obviously 1 is the most needed and should be very easy to implement.

Thanks,
Stephane

**Comment by abiosoft** [comment]
Does not look too hard to implement. If no one is picking this up, I should be able to work on this in the next one week as an add-on.

**Comment by mholt** [comment]
Ideally, this would be part of the existing log directive. We already have preset log file names like `stdout` and `stderr` -- perhaps we could add another one called `syslog`.

**Comment by abiosoft** [comment]
That makes sense.

**Comment by joshix** [comment]
@abiosoft I've been fiddling with this syslog suggestion a little bit, and to satisfy the project's cross-platform goals, I think we may want something like https://github.com/hashicorp/go-syslog, which wraps the standard library `log/syslog` in a way that fails nicely on Windows. Or, say, Plan 9.

Side note: The `hashicorp/go-syslog` `README` mentions OS X as one such place, but I'm not sure why; *syslog*(1) on such systems is indeed an Apple-specific implementation, but AFAICT with a toy go program, accepts input from the standard lib's `log/syslog` in the expected manner.

**Comment by mholt** [comment]
@joshix Awesome, that looks like a fine package to use to accomplish this. I think this adds enough value to the project that we should do this.

Would this basic Caddyfile syntax work well enough? `log syslog` and similarly, for error logging, `errors syslog`

**Comment by joshix** [comment]
@mholt Yes I think that simple consistent form should be enough, because the various *syslogs* are configured in a file in /etc or similar. So configuration of endpoint isn't really needed.

@abiosoft I haven't done anything beyond cursory research of this enhancement so I want to make sure you know I'm not hijacking your claim to it. I'm quite sure you'll write useful code before I do.

**Comment by abiosoft** [comment]
@joshix go ahead actually. I am currently working on other caddy tools. :)

**Comment by evermax** [comment]
I will have a look at it as well. @joshix is it ok with you?

**Comment by joshix** [comment]
@evermax It is absolutely ok with me. Thank you for taking up the task!

**Comment by mholt** [comment]
Merged in afd6b7ea2733cc2b43f99234e5dd9353cd96f0fb - cheers!

**Comment by johnwigley** [comment]
Could we get syslog supported on Windows? I just attempted to use syslog on Windows to log to a syslog server and it errored, although it's obvious that writing to default system syslog isn't going to work on Windows, there isn't any reason why logging to a specific syslog server via udp/tcp isn't possible is there?
Thanks

**Comment by LeTink** [comment]
@johnwigley - Sure. You just need to write something for windows that listens on 514/udp and passes the logs on to your preferred log-server on  the network.  I don't think that it's a feasible thing to do for a minimal web-server to implement its own syslog facility (easy as it might be), feature bloat?

**Comment by johnwigley** [comment]
> @johnwigley - Sure. You just need to write something for windows that listens on 514/udp and passes the logs on to your preferred log-server on the network. I don't think that it's a feasible thing to do for a minimal web-server to implement its own syslog facility (easy as it might be), feature bloat?

So you're saying that Caddy already has the ability to log to Syslog on Windows but only to localhost? Are you sure about that? Because if so, then all that's needed is to just run a Windows Syslog server on the same host and it should work.
