### ISSUE TITLE
BasicAuth PAM

### ISSUE THREAD

**Issue by casdr** [mholt/caddy#1783]
It would be nice to be able to use PAM as an BasicAuth provider.

Example for nginx: https://github.com/sto/ngx_http_auth_pam_module

**Comment by 20zinnm** [comment]
Looks like there's a Go wrapper for the PAM API at https://github.com/msteinert/pam. If we're still interested in this I could get into it @mholt

**Comment by mholt** [comment]
Sure @20zinnm - what do you propose? (i.e. what would it look like to configure, etc)

**Comment by johandorland** [comment]
PAM is very straightforward to use, you just specify which module to use and any configuration of that module is done via the PAM configuration file. The Go wrapper @20zinnm is referring to uses cgo however and that seems to be a no-go here.
