### ISSUE TITLE
Change Markdown provider blackfriday to blackfriday.v2

### ISSUE THREAD

**Issue by TooYoungTooSimp** [mholt/caddy#1785]
According to caddy's markdown provider blackfriday [there](https://github.com/russross/blackfriday/tree/v2#versions)
> Currently maintained and recommended version of Blackfriday is v2

So could you consider migrating caddy's markdown engine to blackfriday.v2 ?

**Comment by mholt** [comment]
I'm definitely looking at that, but I want to wait until the API is a little more stable. Looks like it's still fluctuating a bit (from that readme), and wait until more of the bugs are ironed out. I'm anxious to switch, though; the current v1 isn't lint-compatible.

**Comment by mholt** [comment]
(Closing, but issues tagged deferred will be revisited even if closed.)
