### ISSUE TITLE
v0.10.5 runtime error 

### ISSUE THREAD

**Issue by Rurik19** [mholt/caddy#1786]
For fastcgi sites i get 
```
/usr/local/go/src/sync/atomic/asm_linux_arm.s:109 - runtime error: invalid memory address or nil pointer dereference
```
php7 , connected by sock, architecture armhf7

**Comment by mholt** [comment]
Thanks for the report, @Rurik19 - even though this issue was first, the other linked issue has more info and discussion, so I'll mark this as the duplicate and we'll use the other one for it.
