### ISSUE TITLE
Minify directive failed to correctly minify css block

### ISSUE THREAD

**Issue by TooYoungTooSimp** [mholt/caddy#1792]
### 1. What version of Caddy are you using (`caddy -version`)?
caddy 0.10.6

### 2. What are you trying to do?
minify a html file

### 3. What is your entire Caddyfile?
```text
minify
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf Caddyfile

### 5. Please paste any relevant HTTP request(s) here.
curl 127.0.0.1/test.html

### 6. What did you expect to see?
<style>.lr-border{border-left:1px solid rgba(86,61,124,.2);border-right:1px solid rgba(86,61,124,.2)}</style>

### 7. What did you see instead (give full error messages and/or log)?
<style>.lr-border{border-left:1px solid transparent;border-right:1px solid transparent}</style>

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
just write a html file like this
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        .lr-border {
            border-left: 1px solid rgba(86,61,124,.2);
            border-right: 1px solid rgba(86,61,124,.2);
        }
    </style>
</head>
<body>
</body>
</html>
```
and using a Caddyfile with single line: `minify`
then you can reproduce it.

In fact, minify a single css file can produce the same situation.

**Comment by TooYoungTooSimp** [comment]
Sorry, I put this issue into a wrong place. maybe I should put it to https://github.com/hacdias/caddy-minify

**Comment by mholt** [comment]
^ That'd be correct. Thanks
