### ISSUE TITLE
Reloading caddy doesn't update import directive

### ISSUE THREAD

**Issue by OmgImAlexis** [mholt/caddy#1795]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.5

### 2. What are you trying to do?
Reload caddy server and pickup the new domain/s added via include.

### 3. What is your entire Caddyfile?
```text
import /root/.caddy/vhosts/*
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy --conf /etc/Caddyfile`

### 5. Please paste any relevant HTTP request(s) here.
N/A

### 6. What did you expect to see?
New domains found and activated.

### 7. What did you see instead (give full error messages and/or log)?
After this the newly added domains aren't accessable.
```text
2017/07/30 04:46:21 [INFO] SIGUSR1: Reloading
2017/07/30 04:46:21 [INFO] Reloading
2017/07/30 04:46:21 [INFO] Reloading complete
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
```
echo -e "import $(pwd)/vhosts/*" > Caddyfile
mkdir vhosts
echo -e "example.com {\n    tls off\n    proxy / google.com\n}" > ./vhosts/example.com
caddy --conf ./Caddyfile --log stdout
```

In another terminal window run this in the same directory.
```
echo -e "example2.com {\n    tls off\n    proxy / google.com\n}" > ./vhosts/example2.com
pkill -USR1 caddy
```

At this point I would expect that the import directive would have seen the new files and loaded them as well. Yet example2.com isn't accessible until I restart caddy completely.

**Comment by mholt** [comment]
Huh, works for me:

```plain
Activating privacy features... done.
http://localhost:2015
2017/07/31 10:56:28 http://localhost:2015
http://localhost:2016
2017/07/31 10:56:28 http://localhost:2016
2017/07/31 10:57:01 [INFO] SIGUSR1: Reloading
2017/07/31 10:57:01 [INFO] Reloading
2017/07/31 10:57:01 [INFO] Reloading complete
2017/07/31 10:57:01 http: Server closed
2017/07/31 10:57:01 http: Server closed
```

This is my Caddyfile:

```
import testfiles/*
```

And this is the contents of testfiles:

test1:

```
localhost:2015 {
}
```

test2:

```
localhost:2016 {
}
```

Then I start Caddy, and create this new file:

```
localhost:2017 {
}
```

When I reload with USR1, I can load localhost:2017 in my browser, as expected... can you see this as well? Your output (if run with -log stderr) should be exactly the same (except for times) as shown above.

**Comment by OmgImAlexis** [comment]
Can you try it with different domains? Seems localhost with different ports works fine as you state.

**Comment by mholt** [comment]
@OmgImAlexis As in, take the same setup I've replied with and just change `localhost` to `example.com` and `sub.example.com` (but obviously with a real domain I own)? And you can recreate it by doing that?

**Comment by OmgImAlexis** [comment]
Yes that exactly.

**Comment by mholt** [comment]
Hmm, it works for me with real domains too. I even followed your exact bash script instructions. Are you sure you're accessing the right ports and hostname? (Turning TLS off also turns off automatic HTTPS, as you know, so the port will be the default 2015.)

**Comment by mholt** [comment]
Checking up on this, @OmgImAlexis - have you any new insights? Try slowly turning the config that exhibits the issue for you into my config slowly/gradually, and see if/when it starts working.

**Comment by OmgImAlexis** [comment]
So I can close this, looks like caddy doesn't start serving anything until the reload is completed and I was just being too impatient.
