### ISSUE TITLE
[RFC] add http.asciidoc support 

### ISSUE THREAD

**Issue by netroby** [mholt/caddy#1797]
Now caddy support http.markdown . to display markdown as html
https://caddyserver.com/docs/markdown
so i suggest if caddy can support asciidoc

The asciidoc format was a better format for document written.

http://asciidoctor.org/
http://asciidoc.org/

There already golang implement for asciidoc

https://github.com/VonC/asciidocgo

**Comment by francislavoie** [comment]
This is an ideal use-case for a plugin.

**Comment by mholt** [comment]
That's true. I've added this to [the forum thread](https://caddy.community/t/requested-plugins-ideas-for-developers/127?u=matt) about plugin ideas. I think we'll leave it at that! :+1:
