### ISSUE TITLE
redir can not handle ?q=abc123

### ISSUE THREAD

**Issue by ElvizLai** [mholt/caddy#180]
I need to redid all http to https.
Router handles path well. But it can not handle query after "?"
For example:
http://127.0.0.1:8000?id=001
but after it redirects to https. The query after "?" is missing. It become only https://127.0.0.1:8080

**Comment by abiosoft** [comment]
oops. Sorry.

**Comment by abiosoft** [comment]
Have you considered using `proxy` https://caddyserver.com/docs/proxy ?

**Comment by mholt** [comment]
I think we're talking about redirects, but the query string is not preserved. Could be a bug. @ElvizLai What does the redir line in your Caddyfile look like?

Am traveling right now but will check it out later this week unless somebody beats me to it.

**Comment by abiosoft** [comment]
I have confirmed this.

Is this supposed to be the default behaviour or it can be configurable.

**Comment by ElvizLai** [comment]
@mholt Here is my Caddyfile
```
http://127.0.0.1:8000 {
	redir https://127.0.0.1:12306
}

https://127.0.0.1:12306 {
	tls cert.pem key.pem
	log access.log
	gzip
	proxy / 127.0.0.1:12315
}
```

@abiosoft I think this should be default behavior. Redirects mean redirect all path to other.

**Comment by pedronasser** [comment]
@abiosoft I think the full path (including query) should be passed. Unless that behavior is "overwritten".

Example:
```
http://mysite.com {
       redir https://mysite.com/myNewPath/ # (in this case should overwrite the path)
}
```

What do you think?

**Comment by abiosoft** [comment]
Yeah. I think both the request path and query should be passed along except overridden.
So, given a request
```
http://somesite.com/somepath?somequery=someval
```
The behaviours will be

config | destination
-------- | --------------
`redir http://newsite.com` | `https://newsite.com/somepath?somequery=someval`
`redir http://newsite.com/newpath` | `https://newsite.com/newpath?somequery=someval`
`redir http://newsite.com/newpath?newquery=newval` | `http://newsite.com/newpath/?newquery=newval`

**Comment by mholt** [comment]
Then it is a bug, indeed. Looks like you both figured out the correct behavior - is anyone on this? I can be unless somebody has already started.

**Comment by mholt** [comment]
@ElvizLai The fix is deployed now; feel free to update Caddy.
