### ISSUE TITLE
Caddy crashing on multiple servers multiple times per day

### ISSUE THREAD

**Issue by watermelonjuice** [mholt/caddy#1802]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.6

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Arch linux caddy-full-bin AUR package
Running from systemd service

### 7. What did you see instead (give full error messages and/or log)?

Aug 02 13:08:09 server1 caddy[1417]: runtime: failed to create new OS thread (have 8 already; errno=11)
Aug 02 13:08:09 server1 caddy[1417]: runtime: may need to increase max user processes (ulimit -u)
Aug 02 13:08:09 server1 caddy[1417]: fatal error: newosproc
Aug 02 13:08:09 server1 caddy[1417]: runtime stack:
Aug 02 13:08:09 server1 caddy[1417]: runtime.throw(0x1431c9f, 0x9)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/panic.go:596 +0x95
Aug 02 13:08:09 server1 caddy[1417]: runtime.newosproc(0xc4203fa400, 0xc420476000)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/os_linux.go:163 +0x18c
Aug 02 13:08:09 server1 caddy[1417]: runtime.newm(0x0, 0xc420019300)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/proc.go:1628 +0x137
Aug 02 13:08:09 server1 caddy[1417]: runtime.startm(0xc420019300, 0x2166500)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/proc.go:1698 +0x17e
Aug 02 13:08:09 server1 caddy[1417]: runtime.handoffp(0xc420019300)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/proc.go:1725 +0x55
Aug 02 13:08:09 server1 caddy[1417]: runtime.entersyscallblock_handoff()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/proc.go:2566 +0x3a
Aug 02 13:08:09 server1 caddy[1417]: runtime.systemstack(0x2166000)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/asm_amd64.s:327 +0x79
Aug 02 13:08:09 server1 caddy[1417]: runtime.mstart()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/proc.go:1132
Aug 02 13:08:09 server1 caddy[1417]: goroutine 25 [syscall]:
Aug 02 13:08:09 server1 caddy[1417]: runtime.notetsleepg(0x2165f08, 0xffffffffffffffff, 0xc420018000)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/lock_futex.go:205 +0x42 fp=0xc4201b91a0 sp=0xc4201b9170
Aug 02 13:08:09 server1 caddy[1417]: runtime.gcBgMarkStartWorkers()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/mgc.go:1413 +0xb1 fp=0xc4201b91d8 sp=0xc4201b91a0
Aug 02 13:08:09 server1 caddy[1417]: runtime.gcStart(0x0, 0xe129483eeb175a00)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/mgc.go:997 +0x339 fp=0xc4201b9210 sp=0xc4201b91d8
Aug 02 13:08:09 server1 caddy[1417]: runtime.mallocgc(0xc0, 0x120b6a0, 0xbf1c468ea7e6f701, 0x58e9682e58950021)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/malloc.go:785 +0x491 fp=0xc4201b92b0 sp=0xc4201b9210
Aug 02 13:08:09 server1 caddy[1417]: runtime.newobject(0x120b6a0, 0xf0fee5456722926c)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/malloc.go:820 +0x38 fp=0xc4201b92e0 sp=0xc4201b92b0
Aug 02 13:08:09 server1 caddy[1417]: crypto/elliptic.p256Inverse(0xc4203339c0, 0x4, 0x4, 0xc420303f00, 0x4, 0x4)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/elliptic/p256_amd64.go:286 +0x3f fp=0xc4201b9398 sp=0xc4201b92e0
Aug 02 13:08:09 server1 caddy[1417]: crypto/elliptic.initTable()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/elliptic/p256_amd64.go:406 +0x30e fp=0xc4201b9478 sp=0xc4201b9398
Aug 02 13:08:09 server1 caddy[1417]: sync.(*Once).Do(0x21823a0, 0x19df7a0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/sync/once.go:44 +0xbe fp=0xc4201b94b0 sp=0xc4201b9478
Aug 02 13:08:09 server1 caddy[1417]: crypto/elliptic.(*p256Point).p256BaseMult(0xc420303e00, 0xc4201b9590, 0x4, 0x4)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/elliptic/p256_amd64.go:426 +0x4b fp=0xc4201b9560 sp=0xc4201b94b0
Aug 02 13:08:09 server1 caddy[1417]: crypto/elliptic.p256Curve.ScalarBaseMult(0xc42031f280, 0xc4203339a0, 0x20, 0x20, 0xc4201b9650, 0x20)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/elliptic/p256_amd64.go:240 +0xc5 fp=0xc4201b95c8 sp=0xc4201b9560
Aug 02 13:08:09 server1 caddy[1417]: crypto/elliptic.GenerateKey(0x20cbec0, 0xc42031f280, 0x20afa80, 0xc42005a210, 0xa80, 0x3, 0xc420019350, 0xc420019300, 0xc4203fca80, 0xc42031f180, ...)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/elliptic/elliptic.go:299 +0x2cb fp=0xc4201b9680 sp=0xc4201b95c8
Aug 02 13:08:09 server1 caddy[1417]: crypto/tls.(*ecdheKeyAgreement).generateServerKeyExchange(0xc42031b130, 0xc4203ee180, 0xc420321cc0, 0xc4203f8000, 0xc420243a00, 0x9a8, 0x0, 0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/tls/key_agreement.go:228 +0xccc fp=0xc4201b9848 sp=0xc4201b9680
Aug 02 13:08:09 server1 caddy[1417]: crypto/tls.(*serverHandshakeState).doFullHandshake(0xc4201b9c00, 0xc42003ab00, 0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/tls/handshake_server.go:404 +0x3f3 fp=0xc4201b9bc0 sp=0xc4201b9848
Aug 02 13:08:09 server1 caddy[1417]: crypto/tls.(*Conn).serverHandshake(0xc420309c00, 0x19e37b8, 0xc420309d20)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/tls/handshake_server.go:85 +0x325 fp=0xc4201b9ce8 sp=0xc4201b9bc0
Aug 02 13:08:09 server1 caddy[1417]: crypto/tls.(*Conn).Handshake(0xc420309c00, 0x0, 0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/crypto/tls/conn.go:1309 +0x2db fp=0xc4201b9d58 sp=0xc4201b9ce8
Aug 02 13:08:09 server1 caddy[1417]: net/http.(*conn).serve(0xc420321c20, 0x20c4080, 0xc4203f23f0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/http/server.go:1737 +0x121 fp=0xc4201b9fc8 sp=0xc4201b9d58
Aug 02 13:08:09 server1 caddy[1417]: runtime.goexit()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4201b9fd0 sp=0xc4201b9fc8
Aug 02 13:08:09 server1 caddy[1417]: created by net/http.(*Server).Serve
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/http/server.go:2668 +0x2ce
Aug 02 13:08:09 server1 caddy[1417]: goroutine 1 [semacquire]:
Aug 02 13:08:09 server1 caddy[1417]: sync.runtime_Semacquire(0xc42001314c)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/sema.go:47 +0x34
Aug 02 13:08:09 server1 caddy[1417]: sync.(*WaitGroup).Wait(0xc420013140)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/sync/waitgroup.go:131 +0x7a
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy.(*Instance).Wait(0xc4201d0ea0)
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddy.go:384 +0x2f
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy/caddy/caddymain.Run()
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddy/caddymain/run.go:165 +0x435
Aug 02 13:08:09 server1 caddy[1417]: main.main()
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddy/main.go:13 +0x27
Aug 02 13:08:09 server1 caddy[1417]: goroutine 18 [syscall]:
Aug 02 13:08:09 server1 caddy[1417]: os/signal.signal_recv(0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/sigqueue.go:116 +0x104
Aug 02 13:08:09 server1 caddy[1417]: os/signal.loop()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Aug 02 13:08:09 server1 caddy[1417]: created by os/signal.init.1
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Aug 02 13:08:09 server1 caddy[1417]: goroutine 19 [select]:
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy/caddytls.maintainAssets(0xc420054420)
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddytls/maintain.go:54 +0x457
Aug 02 13:08:09 server1 caddy[1417]: created by github.com/mholt/caddy/caddytls.init.2
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddytls/maintain.go:18 +0x58
Aug 02 13:08:09 server1 caddy[1417]: goroutine 24 [select, locked to thread]:
Aug 02 13:08:09 server1 caddy[1417]: runtime.gopark(0x19e3688, 0x0, 0x142d053, 0x6, 0x18, 0x2)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/proc.go:271 +0x13a
Aug 02 13:08:09 server1 caddy[1417]: runtime.selectgoImpl(0xc420038f50, 0x0, 0x18)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/select.go:423 +0x1364
Aug 02 13:08:09 server1 caddy[1417]: runtime.selectgo(0xc420038f50)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/select.go:238 +0x1c
Aug 02 13:08:09 server1 caddy[1417]: runtime.ensureSigM.func1()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
Aug 02 13:08:09 server1 caddy[1417]: runtime.goexit()
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
Aug 02 13:08:09 server1 caddy[1417]: goroutine 7 [chan receive]:
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy.trapSignalsCrossPlatform.func1()
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/sigtrap.go:29 +0xcb
Aug 02 13:08:09 server1 caddy[1417]: created by github.com/mholt/caddy.trapSignalsCrossPlatform
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/sigtrap.go:47 +0x35
Aug 02 13:08:09 server1 caddy[1417]: goroutine 8 [chan receive]:
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy.trapSignalsPosix.func1()
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/sigtrap_posix.go:18 +0x159
Aug 02 13:08:09 server1 caddy[1417]: created by github.com/mholt/caddy.trapSignalsPosix
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/sigtrap_posix.go:89 +0x35
Aug 02 13:08:09 server1 caddy[1417]: goroutine 13 [IO wait]:
Aug 02 13:08:09 server1 caddy[1417]: net.runtime_pollWait(0x7ff9c7acef60, 0x72, 0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/runtime/netpoll.go:164 +0x59
Aug 02 13:08:09 server1 caddy[1417]: net.(*pollDesc).wait(0xc4203dce68, 0x72, 0x0, 0xc4203f61a0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
Aug 02 13:08:09 server1 caddy[1417]: net.(*pollDesc).waitRead(0xc4203dce68, 0xffffffffffffffff, 0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
Aug 02 13:08:09 server1 caddy[1417]: net.(*netFD).accept(0xc4203dce00, 0x0, 0x20b4e00, 0xc4203f61a0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/fd_unix.go:430 +0x1e5
Aug 02 13:08:09 server1 caddy[1417]: net.(*TCPListener).accept(0xc42000c260, 0xc4203f2510, 0xc42003fe48, 0x5821bd)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
Aug 02 13:08:09 server1 caddy[1417]: net.(*TCPListener).AcceptTCP(0xc42000c260, 0x6b5d23, 0xc42003fe60, 0xc42003fe58)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/tcpsock.go:215 +0x49
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy/caddyhttp/httpserver.tcpKeepAliveListener.Accept(0xc42000c260, 0xc4203f24e0, 0x1263180, 0x2149850, 0x1346da0)
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:480 +0x2f
Aug 02 13:08:09 server1 caddy[1417]: net/http.(*Server).Serve(0xc4203ec210, 0x20c3180, 0xc42000c260, 0x0, 0x0)
Aug 02 13:08:09 server1 caddy[1417]:         /usr/local/go/src/net/http/server.go:2643 +0x228
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy/caddyhttp/httpserver.(*Server).Serve(0xc42000f2c0, 0x20c3180, 0xc42000c260, 0x432638, 0x19e3500)
Aug 02 13:08:09 server1 caddy[1417]:         src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:307 +0xa7
Aug 02 13:08:09 server1 caddy[1417]: github.com/mholt/caddy.startServers.func1.1(0xc42000f560, 0x20c4600, 0xc42000f2c0, 0x20c3180, 0xc42000c260, 0xc4201d0ea0)
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Unit entered failed state.
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Failed with result 'exit-code'.
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Service hold-off time over, scheduling restart.
Aug 02 13:08:09 server1 systemd[1]: Stopped Caddy HTTP/2 web server.
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Start request repeated too quickly.
Aug 02 13:08:09 server1 systemd[1]: Failed to start Caddy HTTP/2 web server.
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Unit entered failed state.
Aug 02 13:08:09 server1 systemd[1]: caddy.service: Failed with result 'exit-code'.

**Comment by mholt** [comment]
This looks like the same thing as #1723  - in other words, it seems to be a misconfiguration of systemd (sigh), not a Caddy issue. Try running without systemd.
