### ISSUE TITLE
DNS SRV record based load balancing

### ISSUE THREAD

**Issue by vramanx** [mholt/caddy#1803]
Does caddy support DNS SRV record based load balancing? This will help integrate with orchestrators like Kubernetes and Microsoft Service Fabric

**Comment by francislavoie** [comment]
See here: https://caddyserver.com/docs/proxy#policies

That mode isn't supported yet, but it could probably be added. Marking this as a feature request. PRs are welcome!

**Comment by jungle-boogie** [comment]
Wouldn't this also need to be supported by the browser?

https://bugzilla.mozilla.org/show_bug.cgi?id=14328

**Comment by francislavoie** [comment]
@jungle-boogie I might be wrong but my understanding is that Caddy would do the DNS lookup for the list of services to use as proxy backends. Don't need browser support for that, browser just sees Caddy

**Comment by jungle-boogie** [comment]
Ah, I think you're right.
I was thinking of setting the DNS records at the DNS level and then have the browser look that up.

**Comment by Gufran** [comment]
I am going to work on it, my idea is to resolve SRV records for endpoints starting with `srv://`. any suggestions?

**Comment by francislavoie** [comment]
@mholt this isn't actually ready to be closed yet. This issue talks about a `proxy` load balancing policy, whereas the PR was for `fastcgi`. See my comment here: https://github.com/mholt/caddy/pull/1870#issuecomment-329590425 and @Gufran's response https://github.com/mholt/caddy/pull/1870#issuecomment-329657025 saying he'll work on the `proxy` implementation next. We should leave this open until he's done that.

**Comment by Gufran** [comment]
Yes, right. I didn't start working on proxy package because it is not exactly a trivial change like fastcgi, I thought I'd hold off until we are in the clear about fastcgi package in case there is any problem with that change. Now that the other PR is merged I'll implement the changes in proxy package.

**Comment by mholt** [comment]
Sounds like a great plan, @Gufran - thank you!
