### ISSUE TITLE
consistent hashing based load balancing

### ISSUE THREAD

**Issue by vramanx** [mholt/caddy#1804]
Does caddy support consistent hashing based load balancing like nginx? We use Microsoft Service Fabric and this will give us the ability to target the right nodes especially for websocket scenarios.

**Comment by francislavoie** [comment]
As with the other issue, see here: https://caddyserver.com/docs/proxy#policies

There's IP hashing and URI hashing available. I'll close this for now, let me know if that doesn't answer your question.
