### ISSUE TITLE
browse works only root dir?

### ISSUE THREAD

**Issue by ElvizLai** [mholt/caddy#181]
Here is my Caddyfile

#passed
http://127.0.0.1:8000 {
	browse
}

#passed
http://127.0.0.1:8001 {
	browse / template.tpl
}

#failed photos is a dir in same root with caddy server.
http://127.0.0.1:8002 {
	browse photos template.tpl
}

**Comment by ElvizLai** [comment]
ops....I know that this func for

**Comment by mholt** [comment]
No problem. If there's any way we can make the documentation clearer, let us know!
