### ISSUE TITLE
Caddy does not recognize middleware for server type other than HTTP

### ISSUE THREAD

**Issue by Mohammed90** [mholt/caddy#1810]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.6

### 2. What are you trying to do?

Run Caddy with server type DNS as a DNS proxy to Google's DNS-over-HTTPS

### 3. What is your entire Caddyfile?
```text
.:53 {
	proxy . 8.8.8.8:53 8.8.4.4:53 {
		protocol https_google
	}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`./caddy -type dns`

### 5. Please paste any relevant HTTP request(s) here.

N/A

### 6. What did you expect to see?

The server is running and proxying DNS queries to Google's DNS-over-HTTPS

### 7. What did you see instead (give full error messages and/or log)?

`2017/08/06 22:40:23 no action found for directive 'proxy' with server type 'dns' (missing a plugin?)`

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Download caddy with the DNS plugin, create the Caddyfile referenced above, then run caddy.

For the record, I am able to run Coredns with the same file successfully.

**Comment by mholt** [comment]
Hmm, I wonder if the dns plugin is configured to plug in the correct package?

/cc @miekg

**Comment by miekg** [comment]
`./caddy -plugins` should list them all? Note that caddy also has a proxy plugin....

I would just use CoreDNS binary is itself: https://github.com/coredns/coredns/releases/latest
(and https://coredns.io)

**Comment by mholt** [comment]
Well, it should work when built from the website, too. From what I can tell, the CoreDNS plugin on the Caddy website should be configured to have this as its package: `github.com/coredns/coredns/core`- because that package imports all the plugins. If the website has a different package then it's probably configured wrong.

@Mohammed90 What is the output of `caddy -plugins`?

**Comment by Mohammed90** [comment]
This is the output of `caddy -plugins`:
```
Server types:
  dns
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.errors
  http.expvar
  http.ext
  http.fastcgi
  http.gzip
  http.header
  http.index
  http.internal
  http.limits
  http.log
  http.markdown
  http.mime
  http.pprof
  http.proxy
  http.push
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.websocket
  shutdown
  startup
  tls
  tls.storage.file
```

**Comment by mholt** [comment]
Hmm, I'm seeing it too. @miekg, what is the package configured on the website?

**Comment by miekg** [comment]
What? What do you need?

**Comment by mholt** [comment]
@miekg Sorry to not be clear -- I mean, when publishing a plugin to the Caddy website, the submitter needs to give the package import path. i.e. `github.com/coredns/coredns/core` - is this the package path for your plugin? (You can log into the devportal and take a look. I could too but I'd have to write a little bit of code to inspect it, and I'm at work right now...)

Just saying, if it's simply a wrong package path, this is an easy fix. :)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Caddy does not re..." ]
>@miekg Sorry to not be clear -- I mean, when publishing a plugin to the Caddy website, the submitter needs to give the package import path. i.e. `github.com/coredns/coredns/core` - is this the package path for your plugin? (You can log into the devportal and take a look. I could too but I'd have to write a little bit of code to inspect it, and I'm at work right now...)
>
>Just saying, if it's simply a wrong package path, this is an easy fix. :)

Oh I had coredns/coredns/core/dnsserver ... 
Did a new deploy with the above path.

/Miek

--
Miek Gieben

**Comment by mholt** [comment]
Yay \o/

Now it will import all the things :tada: Thanks!

**Comment by mholt** [comment]
@miekg Oops:

```
package github.com/mholt/caddy/caddy
	imports github.com/mholt/caddy/caddy/caddymain
	imports github.com/coredns/coredns/core/: non-canonical import path: "github.com/coredns/coredns/core/" should be "github.com/coredns/coredns/core"
```

Lose the trailing slash ;)

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Caddy does not re..." ]
>@miekg Oops:
>
>```
>package github.com/mholt/caddy/caddy
>	imports github.com/mholt/caddy/caddy/caddymain
>	imports github.com/coredns/coredns/core/: non-canonical import path: "github.com/coredns/coredns/core/" should be "github.com/coredns/coredns/core"
>```
>
>Lose the trailing slash ;)

Ack, but that interface could use some finishing touches :)

**Comment by mholt** [comment]
I'm sorry! I'll get around to it eventually. I'll try to add a thing that just strips any trailing slash.

**Comment by mholt** [comment]
I confirmed it works now. Thanks!

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Caddy does not re..." ]
>I confirmed it works now. Thanks!

Awesome! \0/

/Miek

--
Miek Gieben
