### ISSUE TITLE
Invalid roller parameter

### ISSUE THREAD

**Issue by Stonedestroyer** [mholt/caddy#1813]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.6

### 2. What are you trying to do?
Starting caddy after upgrade from 0.10.4

### 3. What is your entire Caddyfile?
```text
Server types:
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.basicauth
  http.bind
  http.browse
  http.cache
  http.errors
  http.expires
  http.expvar
  http.ext
  http.fastcgi
  http.filemanager
  http.filter
  http.gzip
  http.header
  http.hugo
  http.index
  http.internal
  http.ipfilter
  http.jwt
  http.limits
  http.log
  http.login
  http.mailout
  http.markdown
  http.mime
  http.minify
  http.nobots
  http.pprof
  http.proxy
  http.proxyprotocol
  http.push
  http.ratelimit
  http.realip
  http.reauth
  http.redir
  http.request_id
  http.rewrite
  http.root
  http.status
  http.templates
  http.timeouts
  http.websocket
  shutdown
  startup
  tls
  tls.dns.cloudflare
  tls.dns.namecheap
  tls.storage.file
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf caddyfile -host 192.168.1.5

### 6. What did you expect to see?
For it to start

### 7. What did you see instead (give full error messages and/or log)?
Activating privacy features... done.
2017/08/08 13:34:42 invalid roller parameter

**Comment by mholt** [comment]
Hi, you probably have a syntax error in your Caddyfile, but you did not post your Caddyfile. You will have to show what the contents of your Caddyfile (Caddy configuration) are before we can see if this is a bug. (You posted the output of caddy -plugins. Nice to know, but not necessary in this case.)

**Comment by Stonedestroyer** [comment]
I removed this and it works again, 
```
	log dl-domain-com.log {
		rotate_size 50
		rotate_age  90
		rotate_keep 20
		rotate_compress	true
	}
````

**Comment by mholt** [comment]
Ah, there we go. The `true` value was never needed, we fixed that bug in one of the most recent versions. You just say `rotate_compress` to turn on compression.
