### ISSUE TITLE
geoip functionality

### ISSUE THREAD

**Issue by carlwgeorge** [mholt/caddy#1819]
I'm currently using nginx and its geoip module to add the `X-Forwarded-For-Latitude` and `X-Forwarded-For-Longitude` headers to requests before passing them to my app server.  I love Caddy and its automatic https integration, and would like to use it instead of nginx.  However, I don't see any geoip functionality mentioned in the Caddy documentation.  Does this exist and I'm missing it?  If not, can it be added?

**Comment by mholt** [comment]
Hey Carl, thanks for asking! It'll need to be a plugin, which anyone can write. (In fact, I've written geolocation stuff in Go before using MaxMind's GeoIP database.) (In fact again, the [http.ipfilter plugin](https://caddyserver.com/docs/http.ipfilter) does this but for a different purpose.) It's fairly straightforward. Here are the instructions: https://github.com/mholt/caddy/wiki/Extending-Caddy

**Comment by mholt** [comment]
@carlwgeorge Take a look at #2066 :)

**Comment by carlwgeorge** [comment]
Thanks for the follow up Matt!

**Comment by kodnaplakal** [comment]
@carlwgeorge Enjoy :) https://caddyserver.com/docs/http.geoip
