### ISSUE TITLE
Aborted, error 2 in command: gpg

### ISSUE THREAD

**Issue by scheesman** [mholt/caddy#1826]
I am running into an issue trying to install Caddy from the CLI.  I have replicated the issue on 2 clean install Ubuntu 16.04 installs on GCE.  Here is the command and output I am running:
```
root@web-1:/home/scheesman# curl https://getcaddy.com | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5593  100  5593    0     0  12837      0 --:--:-- --:--:-- --:--:-- 12857
Downloading Caddy for linux/amd64...
https://caddyserver.com/download/linux/amd64?plugins=
Aborted, error 2 in command: gpg --keyserver ha.pool.sks-keyservers.net --recv-keys $caddy_pgp > /dev/null 2>&1
root@web-1:/home/scheesman#
```
It doesn't make a difference if I run it as sudo or even as root (as in that example).  I can set up a fresh VM if you would like to see it hands-on.

**Comment by mholt** [comment]
Thanks for the report. I think this would be better at https://github.com/caddyserver/getcaddy.com/issues, however. /cc @pepa65

**Comment by pepa65** [comment]
What happens (output) when you execute `gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 65760C51EDEA2017CEA2CA15155B6D79CA56EA34` on the commandline??
