### ISSUE TITLE
Latency placeholders do not work with any directive

### ISSUE THREAD

**Issue by watermelonjuice** [mholt/caddy#1830]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.6

### 2. What are you trying to do?
Add server latency to http headers

### 3. What is your entire Caddyfile?
```text
example.com {
        root /path/to/public/
        tls admin@example.com
        fastcgi / unix:/run/php-fpm/php-fpm.sock php
        rewrite {
                to {path} {path}/ /index.php?{query}
        }
        gzip
        expires {
                match .(ico|pdf|jpg|jpeg|png|gif|svg|css|js|ttf|eot|woff)$ 1y
        }
        errors /var/log/caddy/errors.log {
                rotate_size 50
                rotate_age  90
                rotate_keep 20
        }
        push
        header / +x-server-latency {latency_ms}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemd

### 5. Please paste any relevant HTTP request(s) here.
curl --head

### 6. What did you expect to see?
cache-control: no-cache, private
content-type: text/html; charset=UTF-8
date: Wed, 16 Aug 2017 14:09:17 GMT
server: Caddy
x-powered-by: PHP/7.1.8
x-server-latency: 100ms

### 7. What did you see instead (give full error messages and/or log)?
cache-control: no-cache, private
content-type: text/html; charset=UTF-8
date: Wed, 16 Aug 2017 14:09:17 GMT
server: Caddy
x-powered-by: PHP/7.1.8
x-server-latency: 

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
As per https://caddyserver.com/docs/fastcgi and https://caddyserver.com/docs/placeholders it is not clear which directives support the latency placeholders.

**Comment by tobya** [comment]
Thanks for the detailed issue report.  You specify fast-cgi as the issue.  Does the {latency_ms} placeholder work when the fastcgi directive is not used?

**Comment by watermelonjuice** [comment]
Can confirm it does not work when only serving plain files. Changing x-server-latency to latency does not fix the problem.

**Comment by mholt** [comment]
The latency placeholders are *response* placeholders, and directives which support them do mention that in the docs (for example the [`log` directive](https://caddyserver.com/docs/log) supports response placeholders) - the header directive does not.
