### ISSUE TITLE
Launch caddy with existing ssl certificates before attempting to renew certificates

### ISSUE THREAD

**Issue by watermelonjuice** [mholt/caddy#1831]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.6

### 2. What are you trying to do?
Start caddy
### 3. What is your entire Caddyfile?
```text
example.com {
        root /path/to/public/
        tls admin@example.com
        fastcgi / unix:/run/php-fpm/php-fpm.sock php
        rewrite {
                to {path} {path}/ /index.php?{query}
        }
        gzip
        expires {
                match .(ico|pdf|jpg|jpeg|png|gif|svg|css|js|ttf|eot|woff)$ 1y
        }
        errors /var/log/caddy/errors.log {
                rotate_size 50
                rotate_age  90
                rotate_keep 20
        }
        push
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemd

### 5. Please paste any relevant HTTP request(s) here.
n/a

### 6. What did you expect to see?
Caddy should launch with existing certificates before renewing if they have not expired.

### 7. What did you see instead (give full error messages and/or log)?
Aug 16 14:02:34 server1 caddy[19272]: Activating privacy features...2017/08/16 14:02:34 [INFO] Certificate for [sub.example.com] expires in 498h21m25.768730787s; attempting renewal
Aug 16 14:02:34 server1 caddy[19272]: 2017/08/16 14:02:34 [INFO][sub.example.com] acme: Trying renewal with 498 hours remaining
Aug 16 14:02:34 server1 caddy[19272]: 2017/08/16 14:02:34 [INFO][sub.example.com] acme: Obtaining bundled SAN certificate
Aug 16 14:02:34 server1 caddy[19272]: 2017/08/16 14:02:34 [ERROR] Renewing: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many invalid authorizations recently.; trying again in 10s
Aug 16 14:02:44 server1 caddy[19272]: 2017/08/16 14:02:44 [INFO][sub.example.com] acme: Trying renewal with 498 hours remaining
Aug 16 14:02:44 server1 caddy[19272]: 2017/08/16 14:02:44 [INFO][sub.example.com] acme: Obtaining bundled SAN certificate
Aug 16 14:02:45 server1 caddy[19272]: 2017/08/16 14:02:45 [ERROR] Renewing: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many invalid authorizations recently.; trying again in 10s
Aug 16 14:02:55 server1 caddy[19272]: 2017/08/16 14:02:55 [ERROR] too many renewal attempts; last error: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many invalid authorizations recently.
Aug 16 14:02:55 server1 caddy[19272]:  done.
Aug 16 14:02:55 server1 caddy[19272]: http://*
Aug 16 14:02:55 server1 caddy[19272]: 2017/08/16 14:02:55 http://*
Aug 16 14:02:55 server1 caddy[19272]: http://sub.example.com
Aug 16 14:02:55 server1 caddy[19272]: 2017/08/16 14:02:55 http://sub.example.com

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
When letsencrypt has rate limited the domain caddy take an extra 30 seconds to launch.

**Comment by mholt** [comment]
Hi, thanks for following the issue template! Your certificate was expiring in less than 30 days (just 20 days, in fact), so Caddy took the effort of renewing your certificate for you to prevent downtime. Renewing certificates after they expire will lead to downtime. I know these few seconds at initial launch can be annoying, but it only happens once (thereafter in the background while running) and is significantly less trouble than doing it yourself.

If you're running into rate limits with Let's Encrypt, you'll either need to slow down deployment of your subdomains or use their staging endpoint for testing your configuration.
