### ISSUE TITLE
Broken redirect when the filename requested ends with an "index" value

### ISSUE THREAD

**Issue by bendem** [mholt/caddy#1835]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.6

### 2. What are you trying to do?
Access any file with the name ending with one of the index values applicable for https://caddyserver.com/docs/index.

### 3. What is your entire Caddyfile?
Reproducible with the default config

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`touch test-index.html; caddy`

### 5. Please paste any relevant HTTP request(s) here.
`curl -I http://localhost:2015/test-index.html`

### 6. What did you expect to see?
```
HTTP/1.1 200 Found
```

### 7. What did you see instead (give full error messages and/or log)?
```
HTTP/1.1 301 Moved Permanently
Location: /test-
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Following the steps above

### 9. Wild guessing as to why it happens
I'm guessing the server checks wether the path requested ends with any "index value" and redirects to the same path without it. It should instead check against the full filename.

### 10. Workaround
Specify `index` with another value that doesn't conflict with your filenames

**Comment by lukegb** [comment]
Fixed in #1812.

**Comment by bendem** [comment]
Ah, I didn't think to check pull requests too. @mholt, should I close this or wait for the fix to be released?

**Comment by mholt** [comment]
@bendem Both ;) Thanks for the report! I hope to get a release out soon.
