### ISSUE TITLE
QUIC Version Unsupported on Chrome 60+

### ISSUE THREAD

**Issue by dhannyz** [mholt/caddy#1836]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.6

### 2. What are you trying to do?
Enable QUIC

It seems the most recent update to the QUIC IETF draft, and a subsequent update in QUIC versions used in Chrome 60+ is not supported by caddy. 
I assume this stems from the quic go library used.

Is there any timeline on updating the supported quic versions in caddy?

**Comment by mholt** [comment]
The quic-go library is usually updated before each release, so if it supports the latest version that Chrome does, so will Caddy. There's no set timeline, we just update whenever we do a new release. They're pretty good about staying up with changes, but no guarantees.
