### ISSUE TITLE
Support more response placeholders

### ISSUE THREAD

**Issue by vicanso** [mholt/caddy#1837]
I want to log response header in log directive, is it possible to add a placeholder to support it? 

```
{>Header}  --> request header
{<Header}  --> response header
```

**Comment by tobya** [comment]
hi viscanso, thank you for the feature request.  Do you have a specific use case in mind for this?

**Comment by vicanso** [comment]
No specific use case. I want this feature to be similar as the feature of Nginx

**Comment by mholt** [comment]
Wish granted. Thanks @tobya!
