### ISSUE TITLE
Error message for ProtectHome misconfigurations isn't descriptive

### ISSUE THREAD

**Issue by jackjennings** [mholt/caddy#1838]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.6

### 2. What are you trying to do?
Set up a web directory inside of the home directory.

### 3. What is your entire Caddyfile?
```text
example.com {
	root /home/transfer/www
	gzip
	tls example.com
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`sudo service start caddy`

### 5. Please paste any relevant HTTP request(s) here.
N/A

### 6. What did you expect to see?
I expected the web server to run from the /home/transfer/www directory. I did receive an error message that the "permissions" were not set correctly, but the issue was actually that `ProtectHome` was set to true in the service definition. So, while the directory permissions were set correctly, they were being reported as incorrect.

This page describes the resolution, but this simple explanation would be very helpful to have in the error message instead of either `Parse error` or `permission denied`, neither of which helped me understand why caddy was not starting.

https://caddy.community/t/unable-to-access-root-path-when-using-systemd/756

### 7. What did you see instead (give full error messages and/or log)?
```shell
$ sudo service caddy status 
● caddy.service - Caddy HTTP/2 web server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-08-24 22:36:52 UTC; 10s ago
     Docs: https://caddyserver.com/docs
  Process: 19572 ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp (code=exited, status=1/FAILURE)
 Main PID: 19572 (code=exited, status=1/FAILURE)

Aug 24 22:36:52 pp-downloads systemd[1]: Started Caddy HTTP/2 web server.
Aug 24 22:36:52 pp-downloads caddy[19572]: 2017/08/24 22:36:52 /etc/caddy/Caddyfile:3 - Parse error: Unable to access root path '/home/transfer/www': stat /home/transfer/www: permission denied
Aug 24 22:36:52 pp-downloads systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Aug 24 22:36:52 pp-downloads systemd[1]: caddy.service: Unit entered failed state.
Aug 24 22:36:52 pp-downloads systemd[1]: caddy.service: Failed with result 'exit-code'.
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Set the root directory anywhere in the home directory and attempt to start caddy using `service`

**Comment by mholt** [comment]
Thanks for filling out the issue template!

So as I understand it, this is basically a request to change the wording of "Parse error: Unable to access root path ..." to something more correct, since it's not a parse error. (However, the permission denied part IS accurate, as that is simply the error returned from the system call.)

**Comment by jackjennings** [comment]
Right, while it is tecchnically correct that it is a permissions issue, it would be helpful to understand that this was because of a default configuration of caddy to prevent the home dorectory from being used. I spent a number of hours tweaking file and directory permissions, and being puzzled over why running the caddy command outside of the system service wasn't producing the same error.

For my case, the ideal would be if the error message changed when this setting was turned on and one is is trying to host in the home directory, so that the setting can be modified or the root directory moved elsewhere.

**Comment by mholt** [comment]
> this was because of a default configuration of caddy to prevent the home dorectory from being used

This is not a configuration in Caddy; especially not a default one. Do you mean systemd?

**Comment by jackjennings** [comment]
Yes—I'm using the systemd service included in this repo, which includes the configuration to protect the home directory: https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service#L36

I used the tutorial on DigitalOcean that includes installing this as part of the setup process: https://www.digitalocean.com/community/tutorials/how-to-host-a-website-with-caddy-on-ubuntu-16-04

I don't dispute that this is a good default to have, it was just difficult for me to diagnose the problem that I was having because it wasn't clear that this configuration was the culprit. I also realize that this is not caddy configuration per-se, but it was a sticking point in getting caddy to work properly for me.

**Comment by mholt** [comment]
Okay. Well, I don't support the systemd script, and the error Caddy gave was accurate (except for the "parse error" part -- that could be worded better) -- so I don't think there's anything to do here, so I'll close the issue. I'm glad you got it working!
