### ISSUE TITLE
browse and 404

### ISSUE THREAD

**Issue by testcaoy7** [mholt/caddy#1845]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.7

### 2. What are you trying to do?
I was trying to serve a iso file via plain HTTP. The iso saved in /root/iso

### 3. What is your entire Caddyfile?
```text
:80
gzip
browse /root/iso
```
However, replace "browse /root/iso" with simple "browse" do work. It listed all files in "/root" as caddy binary was saved and excuted in "/root".

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -conf caddy.conf

### 6. What did you expect to see?
List all files in directory "/root/iso".

### 7. What did you see instead (give full error messages and/or log)?
404

**Comment by wader** [comment]
Hi, I think you want:
```
:80
gzip
root /root/iso
browse
```

**Comment by mholt** [comment]
^ Yes, that should do it. :)
