### ISSUE TITLE
What field should I use instead of nginx inside the alias field

### ISSUE THREAD

**Issue by lihuacai168** [mholt/caddy#1851]
Hi bro
My caddy root directory is / usr / local / caddy / www / file
If I do not want to create a soft link by ln -s / testfile / usr / local / caddy / www / file to access the / testfile directory.
But directly through the alias way to visit, in the following nginx / alias / testfile / on it.
I can not implement this function by configuring redir and rewrite
![image](https://user-images.githubusercontent.com/11568297/29909442-78da056e-8e58-11e7-9ed7-b581f9fad759.png)

How should i do this?

**Comment by francislavoie** [comment]
I recommend you go ask your questions at https://caddy.community/, this is the issue board for bugs and feature requests.
