### ISSUE TITLE
Command line flag to configure reloading Caddyfile on SIGUSR2

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#1854]
SIGUSR2 facilitates graceful binary upgrades, but it does not reload the Caddyfile.

I'm wondering if it _should_ also reload the Caddyfile (like SIGUSR1 does) as it reloads the binary, so that breaking changes - if any - could be gracefully made. Both SIGUSR1 and SIGUSR2 will abort and rollback if there's a failure in the reload, like if the Caddyfile isn't a good configuration or isn't compatible with that version of Caddy.

Once we get to 1.0, I expect breaking changes to be very rare (you can't compare this to the likes of Chrome; servers are much less malleable) -- so I don't know if this will be useful, but perhaps a command line flag could change how the Caddyfile is treated upon SIGUSR2.

So, should the default be to load the updated Caddyfile on SIGUSR2? Or not? And should we introduce a CLI flag to toggle that behavior? (Remember that once Caddy is started, that preference can't be changed without downtime.) (The upcoming API -- yes, it will eventually happen -- will likely make this entire discussion irrelevant, but we still need to decide what to do about SIGUSR2.)

**Comment by francislavoie** [comment]
Would you get the same effect by sending both signals in sequence? Not sure if that's possible

**Comment by mholt** [comment]
No; once a signal is acquired, it locks and won't process the next signal (of the two) until the first one is complete. If there is an incompatible Caddyfile which causes an error when Caddy starts, the reload or upgrade will be rolled back.

**Comment by tobya** [comment]
I think SIGUSR2 should reload the caddyfile.  What is the scenario where this is a bad idea?

**Comment by mholt** [comment]
@tobya Good question, I'm not entirely sure. Just seems like the safe thing to do...

**Comment by pepa65** [comment]
When upgrading the binary, why at the same time change the configuration?? Keep them separate is good. Unless the upgraded binary requires a different Caddyfile, which would be a backwards-incompatible situation; wouldn't a SIGHUP or something like that just restart (reload binary and Caddyfile)?

**Comment by mholt** [comment]
@pepa65 Yeah, that's true. Maybe if you're doing a breaking update, just reloading the binary and the Caddyfile at the same time a different way is a better procedure...

Hm, I'll close this since it's mostly just an aimless brainstorm at this point. Discussion still welcome if there's anything new to add!
