### ISSUE TITLE
redir BUG For HTTP to HTTPS

### ISSUE THREAD

**Issue by zuohuadong** [mholt/caddy#1855]
why HTTP can't redir to HTTPS ?

### 1. What version of Caddy are you using (`caddy -version`)?
0.10.7

### 2. What are you trying to do?

https://hstspreload.org/?domain=notadd.io
### 3. What is your entire Caddyfile?
```text
www.notadd.io:80 www.notadd.io:443 notadd.io:80 notadd.io:443 {
    root /home/wwwroot/notadd.io
    redir 301 {
        if {>X-Forwarded-Proto} is http
        / https://{host}{uri}
    }
    header / Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    tls /home/wwwroot/ssl/notadd_io.crt /home/wwwroot/ssl/notadd_io.key
    gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -service start

**Comment by midzer** [comment]
For my sites Caddy auto-redirects from http to https.

**Comment by zuohuadong** [comment]
Can you try to use your own certificate?

**Comment by francislavoie** [comment]
You need to use the https:// scheme in front of your domains on the first line.

**Comment by mholt** [comment]
Hmm, why are you redirecting based on X-Forwarded-Proto? What is setting that header?

**Comment by zuohuadong** [comment]
```
https://www.notadd.io http://www.notadd.io https://notadd.io http://notadd.io {
    root /home/wwwroot/notadd.io
    redir 301 {
        if {>X-Forwarded-Proto} is http
        / https://{host}{uri}
    }
    header / Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    tls /home/wwwroot/ssl/notadd_io.crt /home/wwwroot/ssl/notadd_io.key
    gzip
}
```
See:   https://caddyserver.com/docs/redir#examples   The last。

you can try it ,use yourself

**Comment by mholt** [comment]
@zuohuadong That makes sense if you're being proxied to, but what is setting the X-Forwarded-Proto header? Browsers aren't sending it, that's for sure...

**Comment by zuohuadong** [comment]
I want to "http://" rewrite to  "https".

Do I have to reopen a `{}`?

**Comment by zuohuadong** [comment]
```
http://www.notadd.io http://notadd.io {
       redir 301 {
       / https://{host}{uri}
     }
}
https://www.notadd.io  https://notadd.io  {
    root /home/wwwroot/notadd.io

    header / Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    tls /home/wwwroot/ssl/notadd_io.crt /home/wwwroot/ssl/notadd_io.key
    gzip
}

```

like it ?

**Comment by mholt** [comment]
Just try `if {scheme} not https` instead, in your redir.

**Comment by zuohuadong** [comment]
Thanks.

`https://docs.getcaddy.cn`

I am translating it.

caddy is very easy to use.

**Comment by mholt** [comment]
Ohh that's great! Keep us posted, especially in #574
