### ISSUE TITLE
need to update support chrome 61 quic/39

### ISSUE THREAD

**Issue by favortel** [mholt/caddy#1858]
The current version of caddy cann't support the newewst version quic/39 with chrome61

KEY word: QUIC 39

**Comment by wendigo** [comment]
It will when quic-go 0.6 will be released: https://github.com/lucas-clemente/quic-go/blob/master/Changelog.md

**Comment by favortel** [comment]
wo, thank you

**Comment by marten-seemann** [comment]
Please don't wait for quic-go releases. We're really lazy tagging releases on Github.
Please just go ahead and use the current master. We're making sure that the current master always works with the current version of Chrome.

**Comment by LFlare** [comment]
Ping @wendigo @mholt :)
