### ISSUE TITLE
listing-templates supporting <.include>

### ISSUE THREAD

**Issue by vedam** [mholt/caddy#186]
hi,
experimenting through the userguide I stumbled upon including code snippets inside of a listing-template:
```
[ERROR 500 /portfolio/] template: listing:30:4: executing "listing" at <.Include>: Include is not a field of struct type browse.Listing
```
Wouldn't it be useful to reuse some static html-parts (i.e. footer) via <.include> in listing-templates?

**Comment by vedam** [comment]
In addition to that it costs me a while to figure out, that uncommenting an <.include> in the listing-template seems to getting parsed by the html-parser and results in mentioned 500.
```
in the html-listing-template
    <!--
      {{.Include "/path/to/file.html"}}
    -->
```
is this intended?
Special thx to Maxime Lasserre for helping me out here @slack
Thought I'll have to give up   ;-)

**Comment by mholt** [comment]
Was this resolved in Slack then @vedam?

**Comment by vedam** [comment]
Yes, but it's the reason for this question. Solution was:
No outcommented actions inside templates.
And I wondered if that's intended?

**Comment by mholt** [comment]
To comment template actions, you can do this:

```
{{/* ... */}}
```

As far as including, that is currently only supported with the `templates` directive - not yet in `browse` or `markdown` templates. I can see why that would be useful though. Did I understand right, that is what you are asking for?

**Comment by vedam** [comment]
Yes. That was it:
"..that is currently only supported with the templates directive - not yet in browse or markdown templates." I didn't got that.

I wanted to make a browse-template by my own and tried to use <.include> inside
```
...
<body>
  {{.Include "/path/to/some-file.html"}}
</body>
...

```
This throws the 500-error mentioned at the top.
So I went back to the browse-template and put the {{.include...}} inside a html-comment, assuming, it wouldn't get parsed then. 
```
...
<body>
  <!--
  {{.Include "/path/to/some-file.html"}}
  -->
</body>
...
```
But it got parsed. Throwed the same 500 and that made me wonder ("Why is this error here again. I've no <.include> inside my template. I put it in a comment").

Sorry for the confusion. I've got to dive deeper. Into caddy, into go and maybe more into server-side-stuff.

**Comment by mholt** [comment]
No problem, our documentation needs to improve. Thanks for your efforts! Having your feedback is important to make sure caddy works well for everyone of its target users.

We'll work on adding the .Include action to browse and markdown templates too. @evermax and I will be taking a look at that.
