### ISSUE TITLE
Improve Caddy auth system

### ISSUE THREAD

**Issue by dhaavi** [mholt/caddy#1863]
The intro from my other issue reads:

> I am currently using Caddy on multiple production server in different settings. So far I really love the simplicity, speed and stability of Caddy. In the last weeks I have also experienced two limits of Caddy. Both of them are, I think, very important to discuss, as they may become a dealbreaker easily. In order to secure the future Caddy (you want companies to buy these plans, right?), these issues should be thoroughly discussed - as they are also breaking changes.

The second issue is about authentication in Caddy. Currently this seems to be a bit of a mess and should be uniformed and managed by the core.

I would like to introduce you to a concept how this might work:

The Caddy core is responsible for checking permissions on requests, plugins provide user authentication and authorization.
The basicauth plugin may for example authenticate a user and then save that a certain request is made by a particular user. Another plugin (e.g. providing a static list of permissions) is then queried for the permissions that this user has. Permission could look like this:

    auth_users {
      # Alice is allowed to access anything (explicit allow default rule), but is
      # only allowed to use GET and HEAD HTTP methods on paths starting with /api
      Alice {
        default allow
        GET,HEAD /api
      }
      # Bob is allowed to access anything (allow default rule from default user),
      # and is allowed to use GET, HEAD, POST, PUT and DELETE HTTP methods on
      # paths starting with /api
      Bob {
        rw /api # rw is a shortcut for GET,HEAD,POST,PUT,DELETE
      }
      # Charlie is only allowed to access his own space in /charlie and nothing else.
      Charlie {
        default deny
        * /charlie
      }
      # * specifies default rules for all authenticated users. If omitted,
      # default rule is "deny". If no path of an authenticated user matches,
      # these paths will be checked before reverting to their own or this
      # default rule.
      * {
        default allow
        - /api
      }
      # - specifies the rules if authentication failed / the user did not
      # provide authentication.
      - {
        default deny
        ro /public # ro is a shortcut for GET,HEAD
      }
    }

Methods are HTTP methods and HTTP commands:
GET, POST, HEAD, PUT, MOVE, DELETE, WEBSOCKET (the permission to initiate a websocket upgrade), etc...

Added/Changed Caddyfile directives:

- `auth`
  defines a plugin that both handles user authentication and authorization
- `auth_users`
  defines a list of plugins and their order in which they are tried to authenticate a user
- `auth_perms`
  either defines a static list of permissions (as above) or defines a plugin that handles user authorization

There may be only one list/plugin defining permissions per vhost, but many plugins doing authorization.

There numerous great use cases for such a system:

    # use TLS client certificates for authentication (CN=username),
    # then ask a backend service for permissions of that user
    auth_users tls
    auth_perms request {
      10.0.0.1/auth/{username}
    }

    # use a backend service for both authentication and authorization
    auth request {
      # note: both HTTP basic auth and cookies are forwarded
      10.0.0.1/auth
    }

    # or completely defined inside the Caddy config file
    auth_users basicauth {
      Alice   [password]
      Bob     [password]
      Charlie [password]
    }
    auth_perms {
      Alice {
        rw /api
      }
      * {
        default allow
        r /api
      }
      - {
        default deny
        r /public
      }
    }

Such a system would really bring much more flexibility and power to Caddy, as it the can integrate seamlessly into any existing environment for handling authentication and authorization, making it easy to extend existing web applications with powerful Caddy plugins. This is a big thing and something I think a lot of people would love to have.

I hope I have explained the concept enough to make sense, I will of course try to explain further if that is not the case.

The challenge in creating such a central authentication management is to keep the system as simple as possible. That was my aim for this concept, but I am pretty sure that I missed something. ;)

Again, keep up the great work!

**Comment by tobya** [comment]
Thanks for the issue. This is an interesting discussion, however I think this sort of discussion may be better to have on the community forum at https://caddy.community 

If you are happy to post it there we can continue the discussion

**Comment by mholt** [comment]
@dhaavi Thanks for the brain dump! It is an interesting idea, to have authentication managed by Caddy core. It seems like what you are suggesting is that there's a single place within Caddy at the base/root of the HTTP middleware chain (probably?) that is delegating authentication to relevant auth plugins.

I do want to pursue this discussion further, but I think I agree with Toby that, at this point in the proposal (early stages), we move the discussion to the forum. You can link to this issue if you want -- whatever you prefer.

Lately, I've been trying to focus the issues on just bug reports or specific feature requests. This looks like a nice proposal but is out of reach at the moment because it too requires a fundamental redesign of much of Caddy and a few of its plugins. By posting this on the forum, it will/might get more exposure, and will help flush out the idea to maturity so we can take a more serious look at it for implementation.

As always, feel free to continue discussing here, but I'll close this issue nonetheless. I've marked it as 'deferred' which is the label we use when we revisit something later that has been closed because it's not really something we can address right now.

**Comment by dhaavi** [comment]
Yes, exactly.

Here is the Caddy forum thread: https://caddy.community/t/improve-caddy-auth-system/2688

I have also decided to implement this as a plugin for now, as I would have implemented something similar anyway.

**Comment by mholt** [comment]
Relevant discussion thread, for v2: https://github.com/caddyserver/caddy/issues/2894

I think v2 can handle this use case much better.
