### ISSUE TITLE
Caddy-Sponsors header is worded poorly

### ISSUE THREAD

**Issue by Zarthus** [mholt/caddy#1873]
I'm extracting this from PR #1866 because I think this is a separate issue to discuss (although made less relevant if the outcome of said PR is to revert it.)

@captncraig said the following ([source](https://github.com/mholt/caddy/pull/1866#issuecomment-329345288)):
>Furthermore, I feel like the header, in its' current form is somewhere between confusing and an outright lie:
>
>This free web server is made possible by its sponsors: Minio, Uptime Robot, and Sourcegraph
Which server? To an uninformed observer, it looks like those services are sponsoring each and every site served by caddy. This is obviously not the case. If someone sees that header on a paid site, are they going to be confused at why it says it is free? Are these sponsors really ok if really offensive content is displaying their names as primary benefactors? Did they really sign up to be a source of controversy in your open source project?

**Comment by mholt** [comment]
The header has been removed.
