### ISSUE TITLE
Default download link with no license specified still allows downloading

### ISSUE THREAD

**Issue by adisbladis** [mholt/caddy#1877]
I would expect not specifying a license from the download url to result in an error.
The current behaviour does not make it clear that an eula applies.

- `curl -v 'https://caddyserver.com/download/linux/amd64?plugins=http.cgi'` results in response code 200
- `curl -v 'https://caddyserver.com/download/linux/amd64?plugins=http.cgi&license='` results in response code 200
- `curl -v 'https://caddyserver.com/download/linux/amd64?plugins=http.cgi&license=somethingunknown'` results in response code 400

I expect all of these requests to error out.

**Comment by adisbladis** [comment]
I also read the "One step installer" script and it seems like that the script is defaulting to a personal license.
This makes it incredibly easy to be accidentally non-compliant with the EULA.

**Comment by mholt** [comment]
Hi, thanks for your report.

See, this is another example of people just not reading the things...

The announcement blog post says:

>  To ease the transition into this, though, we'll allow the current syntax (no license parameter) to work for at least 30 more days, and a personal license will be assumed.

And the script itself issues a warning:

> [[ -z $caddy_license ]] && echo "Notice! You will soon be required to specify a license; see website for details." && caddy_license="personal";

So I am not too concerned about this; in about a month the point will be moot anyways as we enforce a license parameter.

**Comment by adisbladis** [comment]
I read it which is why I'm here writing a report about it.
Not everyone will though and you have changed one of the fundamental expectations of the software distribution, namely the license, right under a lot of peoples noses.

Just look at all the some of the images on Docker hub: https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=caddy&starCount=0 or search "caddy ansible" or something similar on github.

You will find tons of things just like [this one](https://hub.docker.com/r/adriel/caddy/~/dockerfile/) which just pulls the latest version.
A good Ansible example is [this one](https://github.com/antoiner77/caddy-ansible). 

Some of these deployment tools/images are used by companies which would not have purchased your license.
This kind of change has to be clearly communicated with all users, not just the ones that read your announcements.

Currently it's far to easy to transition right into non-compliance.

**Comment by mholt** [comment]
Thanks for all the links.

> This kind of change has to be clearly communicated with all users, not just the ones that read your announcements.

I'm not sure how you propose we do this, if not with announcements. :smile:

The point of the transition period is to give them time to be made aware of the change; if we just error out immediately, it's not nice. :) They have some time to switch over -- it's a very small technical change -- and then things are fine.

**Comment by adisbladis** [comment]
> I'm not sure how you propose we do this, if not with announcements. 😄

My proposal _is_ erroring out. In my opinion that is far nicer than pushing something encumbered by a new license to unknowing users.

**Comment by mholt** [comment]
Again, I'm not worried about it. We give them a grace period to update their systems without breaking them. And that's that.

**Comment by adisbladis** [comment]
No this is _not_ something that can be considered a grace period. One day the license is Apache2.0 and the next it's not the case anymore. You have completely changed the terms without offering a reasonable way to find that out.
IANAL but I would even think this makes your EULA unenforceable.
