### ISSUE TITLE
Quic not working on newest chrome release google now using quic/39

### ISSUE THREAD

**Issue by squadramunter** [mholt/caddy#1881]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.9

### 2. What are you trying to do?
Serving Quic over google chrome browser but not working.

### 3. What is your entire Caddyfile?
```text
https://www.dl.squadrasec.com/files/Caddyfile
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
service caddy start / stop using systemd file running on Ubuntu 16.04 LTS command -quic enabled in systemd file.

### 5. Please paste any relevant HTTP request(s) here.

Request URL:https://www.dl.squadrasec.com/
Request Method:GET
Status Code:304 
Remote Address:185.166.236.59:443
Referrer Policy:no-referrer-when-downgrade
Response Headers
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35"
caddy-sponsors:This free web server is licensed only for non-commercial use, made possible by its sponsors: Minio, Uptime Robot, and Sourcegraph
content-encoding:gzip
date:Sun, 17 Sep 2017 12:48:04 GMT
etag:W/"ov21x3k9"
status:304
strict-transport-security:max-age=31536000;
unset:Keep-Alive
vary:Accept-Encoding
x-content-type-options:nosniff
x-frame-options:SAMEORIGIN
x-xss-protection:1; mode=block
Request Headers
:authority:www.dl.squadrasec.com
:method:GET
:path:/
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding:gzip, deflate, br
accept-language:nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4
cache-control:max-age=0
cookie:_ga=GA1.2.2036500920.1505651715; _gid=GA1.2.2126516273.1505651715
dnt:1
if-modified-since:Mon, 21 Aug 2017 21:48:39 GMT
if-none-match:W/"ov21x3k9"
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

### 6. What did you expect to see?
A working quic/39 protocol that is working on chrome 61.0.3163.91 (Officiële build) (64-bits) (cohort: Stable)

### 7. What did you see instead (give full error messages and/or log)?
The only thing I now see is h2 not h2 with quic protocol.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
https://codereview.chromium.org/2809773002/

**Comment by francislavoie** [comment]
This is a duplicate of https://github.com/mholt/caddy/issues/1858

See the quic-go changelogs here: https://github.com/lucas-clemente/quic-go/blob/master/Changelog.md

Once the update to quic-go is released, Caddy will support it.
