### ISSUE TITLE
Maybe tag a new release now that the sponsor header has been removed?

### ISSUE THREAD

**Issue by princemaple** [mholt/caddy#1885]
Hi,

I have no problem building from source.
However, currently if you build from source with the latest stable, i.e. 0.10.9, it contains the sponsor header.

Could you tag a new release so when people try and write scripts to build from latest stable, they don't get the unexpected sponsor header still? I know I can simply remove the code or use master when building from source, I mean it would be better if I don't have to special case this particular version in the build script, which many people are going to write one at some point from now on.

Thanks a lot.
If you don't want to do that, it's totally fine, I will just wait for the next release :)
Feel free to close and ignore this one, no hard feelings. Thanks for keeping the source code open.

**Comment by mholt** [comment]
I think my first duty is to respond to the hundreds of messages I've received in response to last week, and then to revise pricing to be affordable for smaller businesses. I'll get around to a new release soon, though.
