### ISSUE TITLE
IP whitelist in basicauth plugin

### ISSUE THREAD

**Issue by mdcollins05** [mholt/caddy#1891]
What I'm hoping for is a way to add an IP range so that internal users (requests from the LAN network) bypass basic auth while external requests are required to authenticate.

I've done this on nginx and it was quite nice to have. The plugin should pay attention to the `X-Forwarded-For` IP address, if it exists, otherwise there may be a way to bypass auth depending on how the request comes in.

I'm really loving Caddy and have even converted a couple of people to use it, due to the ease it provides. Thanks!

**Comment by mholt** [comment]
Thanks, glad you like using Caddy.

Do you think there's a way to do this with a plugin currently? I know some plugins are related to IP addresses and auth.

**Comment by mdcollins05** [comment]
I've taken a look at the plugins within the Caddy documentation and it doesn't seem that any could do so without writing or running some sort of backend authentication service to do the work. For my own home use, that would be over the top.

Not being familiar enough with the Caddy code, I'm not sure how simple of a request this is.

**Comment by mholt** [comment]
Maybe better is to set up a site like this:

```
example.com {
    proxy / backend:1234
    basicauth / user pass
}

192.168.1.3:80 {
    bind 192.168.1.3
    proxy / backend:1234
}
```

Or something. The point is, have two sites that listen on different interfaces: the LAN interface and the global one.

**Comment by mdcollins05** [comment]
Honestly, that makes things more complicated than I'd like. It'd require me to enter in the correct name/IP based on location and wouldn't scale for more than a single name on a host.

**Comment by mholt** [comment]
I think you'll have to be more specific with what you want, then.

**Comment by gucki** [comment]
I was looking for this too. Basically it should be possible to combine different authentication schemes.

For example allow users from certain countries using the ipfilter plugin automatically and require basic auth for others. Of course is not 100% secure then (ex. fake ip address), but it's a good basic protection is some scenarios.

**Comment by mholt** [comment]
> For example allow users from certain countries using the ipfilter plugin automatically and require basic auth for others. Of course is not 100% secure then (ex. fake ip address), but it's a good basic protection is some scenarios.

**Comment by agrrh** [comment]
Looking for this feature too!

It's not always fine to set up 2 sites. Sometimes you would like to close resource from outer world but let someone take a look: some legacy software w/o auth support, grandpa, etc.

I also suppose a couple of questions to think of:

- Should `basicauth` plugin have option like `allow_cidr` or should it be combined somehow with `ipfilter` plugin rules?
- Which policy should be default: allow if any of auth/ip passed or both of those satisfied? I've seen both of those cases in real life.

Thanks for great web server though!

**Comment by mholt** [comment]
This will be possible with Caddy 2's improved routing design.

**Comment by rmoriz** [comment]
An important use case for this functionality is the receiving of external webhook while the site is protected with l/p. 

The nginx way is documented in https://github.com/caddyserver/caddy/pull/2406#issuecomment-449644255 

One would white-list the IP ranges of the webhook source.

**Comment by mholt** [comment]
Okay, yes; if this issue is strictly about whitelisting IP addresses or deciding whether auth is needed based on IP address, this is possible in Caddy 2. Would you like to try it out? Check out the v2 branch: https://github.com/caddyserver/caddy/tree/v2 - the wiki has documentation for using it; you'd be interested in the `remote_ip` matcher: https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpmatchersremote_ip

Note that Caddy 2 doesn't yet have basic auth (it will) but it seems that is somewhat ancillary to the core of this issue which is IP whitelisting. Give it a whirl and feel free to comment on our forums or open a new issue with questions/feedback!
