### ISSUE TITLE
Error during parsing when using imports with files that share the same name

### ISSUE THREAD

**Issue by jakelucas** [mholt/caddy#1892]
### 1. What version of Caddy are you using (`caddy -version`)?

0.10.9

### 2. What are you trying to do?

Use imports with common directives in them to set up mulitple similar sites.

### 3. What is your entire Caddyfile?

In my main `Caddyfile` I have this:

```
import "a/foo.caddyfile"
```

`a/foo.caddyfile` contains this:

```
https://local.foo.co.uk {
    import "../b/bar.caddyfile"
}
```

and finally `b/foo.caddyfile` contains this:

```
tls self_signed

proxy / localhost:3000 {
    transparent
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

I'm running Caddy locally on a Windows 10 machine, so I opened the standard Windows `cmd` prompt and changed directory to the location of the `caddy.exe` file. I then just ran the `.exe` file with `caddy.exe`; my `Caddyfile` is in the same directory.

### 5. Please paste any relevant HTTP request(s) here.

N/A

### 6. What did you expect to see?

Caddy starting up normally.

### 7. What did you see instead (give full error messages and/or log)?

This is the error that Caddy displayed:

>  foo.caddyfile:3 - Error during parsing: Unexpected '}' because no matching opening brace

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

- Unzip caddy into a new directory
- Create a new `Caddyfile` in the same directory as `caddy.exe`
- Create a new folder named `a` in the same directory as `caddy.exe`
- Create a new folder named `b` in the same directory as `caddy.exe`
- Inside of folder `a` create a new file named `foo.caddyfile`
- Inside of folder `b` create a new file named `foo.caddyfile`
- Inside of `Caddyfile` type this:
```
import "a/foo.caddyfile"
```
- Inside of `a/foo.caddyfile` type this:
```
https://local.foo.co.uk {
    import "../b/foo.caddyfile"
}
```
- Inside of `b/foo.caddyfile` type this:
```
tls self_signed

proxy / localhost:3000 {
    transparent
}
```
- Open a command prompt and `cd` to the `caddy.exe` directory
- Run Caddy with `caddy.exe`
- You should see the following:
> foo.caddyfile:3 - Error during parsing: Unexpected '}' because no matching opening brace

This seems to be caused by having two files that have the same name being used in `import`.
If you rename `b/foo.caddyfile` to `b/bar.caddyfile` and update the `import` directive in `a/foo.caddyfile`, then run `caddy.exe` again, the problem should be resolved.

**Comment by mholt** [comment]
Thanks, your instructions made this super easy to reproduce. Looking into this.

**Comment by mholt** [comment]
Your detective work made this go very quickly. Thanks!
