### ISSUE TITLE
caddy proxy  statics  other The server

### ISSUE THREAD

**Issue by shuyabin** [mholt/caddy#1893]
### 1. What version of Caddy are you using (`caddy -version`)?
The latest version

### 2. What are you trying to do?

Dynamic separation 

### 3. What is your entire Caddyfile?
```text
:8082
gzip

proxy  /document-api-fineuploader.html  test.daili.com

proxy ~* \.(jpg|jpeg|gif|png|swf)$ test.daili3.com

proxy / test.daili.com test.daili2.com {
    policy ip_hash
    health_check_timeout  60s
}

log ./access.log

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
windwos service 2008 

I want to use caddy as a static resource to separate from other servers, but the URL rule doesn't work

**Comment by mholt** [comment]
```
proxy ~* \.(jpg|jpeg|gif|png|swf)$ test.daili3.com
```

This looks like a rule written for nginx, not Caddy. I'm not really sure what this is trying to do, but you'll need to make rules understood by Caddy: https://caddyserver.com/docs/proxy

**Comment by shuyabin** [comment]
Thank you very much for your answer
Can you give me some advice?
I want to use caddy as a static resource to separate from other servers,
I've seen the document but  I can't find it

**Comment by mholt** [comment]
I'd suggest asking in our forums, since this issue tracker is for bugs and feature development. https://caddy.community - more people will see your question there. :)
