### ISSUE TITLE
Regexp in proxy,and placeholder in proxy from,to

### ISSUE THREAD

**Issue by lvhuat** [mholt/caddy#1894]
Do these feature will support in future, i'am running my program in docker env, so i want to route my restful apis to my different container,i need any function like:

```
proxy /v1/users/(.*)/node  {1}.agent
```
so i may route the path `/v1/user/user1001/node` to  dns address `user1001.agent`

or maybe some more powerful:
```
proxy /v1/users/(.*)/node  uppercase({1}).agent
```

**Comment by mholt** [comment]
Thanks for the feature request, but I think this is covered in #1639.
