### ISSUE TITLE
Handle upstream errors with errors directive

### ISSUE THREAD

**Issue by jahands** [mholt/caddy#1897]
This is a feature request and may be out of scope / a bad idea.

I posted this question on the forum: https://caddy.community/t/errors-page-for-proxied-requests/2800
I want to be able to handle errors of upstream proxied requests.
```
proxy / https://jac.nyc3.digitaloceanspaces.com {
    header_upstream Host jac.nyc3.digitaloceanspaces.com
}
errors {
    403 404.html
}
```
The reason I want to do this is to hide the bucket name of my DigitalOcean Spaces (S3 clone) bucket.

**Comment by francislavoie** [comment]
I think this is a duplicate of a few others: https://github.com/mholt/caddy/issues/1447, https://github.com/mholt/caddy/issues/753 and should probably be covered by https://github.com/mholt/caddy/issues/1639 when it's implemented

**Comment by jahands** [comment]
You're right this is a bullet point on #1639

**Comment by mholt** [comment]
Cool. Thanks for the feature request! Closing in favor of the earlier issue instead.
