### ISSUE TITLE
Add a TLS configuration option to disable TLS session tickets

### ISSUE THREAD

**Issue by fbis251** [mholt/caddy#1898]
Hi, would it be possible to add a Caddyfile option to disable TLS session tickets? According to Filippo Valsorda's blog post [We need to talk about Session Tickets](https://blog.filippo.io/we-need-to-talk-about-session-tickets/) they they have several flaws and are problematic for Perfect Forward Secrecy. At the moment, there is no way to disable them from Caddy's TLS config without editing the source code.

Ideally this could be done via the TLS config, something like this could be good:
```text
example.com {
	root /var/www/example.com
	tls {
		disable_session_tickets
	}
}
```

**Comment by francislavoie** [comment]
I was thinking about this too.

I hope you don't mind the notification @FiloSottile. What do you think Caddy should do here? Since this issue is based on your opinion post, I think it's worth asking for your input.

**Comment by mholt** [comment]
I do not think disabling them is really necessary for most threat models. Regrettably, the article doesn't mention this directly (although the linked paper _does_), but Caddy rotates STEKs every few hours. It doesn't dispose of old ones (the mechanisms did not exist in the Go standard lib back when it was implemented to make this easily possible -- technically, it used to be racy too; only recently did Go make it thread-safe, which Caddy now uses) but the rotation alone still makes it very difficult to conduct a coordinated attack against a targeted session using session tickets.

My understanding is that TLS 1.3 will more or less resolve this by not using session resumption, instead utilizing a PSK mode.

Gonna close this issue on that note, but the discussion can go on if necessary (or if Filippo would like to comment, always welcome here!).

**Comment by FiloSottile** [comment]
Matt is right, Caddy was not the target of the article because indeed it rotates by default, but even more importantly because it has no support for multi-machine key syncing, which is what makes the key easier to persist and more valuable to steal.

**Comment by Avamander** [comment]
Would it be possible to limit TLS session resumption to TLSv1.3?
