### ISSUE TITLE
Feature Suggestion: Plugin System

### ISSUE THREAD

**Issue by Immortalin** [mholt/caddy#19]
Hi, how about a plugin system via pingo or lua?

**Comment by Immortalin** [comment]
(Pingo)[https://news.ycombinator.com/item?id=9445707]

**Comment by mholt** [comment]
Thanks for the suggestion! I've seen that another Go web server, [Algernon](https://github.com/xyproto/algernon), allows for Lua scripting. I also saw Pingo and thought it was pretty cool (even though I'm personally a fan of stdin/stdout communications between processes). Did you have any ideas for plugins in particular?

**Comment by Immortalin** [comment]
It's mainly good for separation of concerns e.g. you can offload the
markdown feature into a plugin and add plugins for emails etc.




<div>-------- Original message --------</div><div>From: Matt Holt <notifications@github.com> </div><div>Date:30/04/2015  12:02  (GMT+08:00) </div><div>To: mholt/caddy <caddy@noreply.github.com> </div><div>Cc: Immortalin <immortalin@icloud.com> </div><div>Subject: Re: [caddy] Feature Suggestion: Plugin System (#19) </div><div>
</div>Thanks for the suggestion! I've seen that another Go web server, Algernon, allows for Lua scripting. I also saw Pingo and thought it was pretty cool (even though I'm personally a fan of stdin/stdout communications between processes). Did you have any ideas for plugins in particular?

**Comment by mholt** [comment]
Similar enough to #36 - so I will close this one to avoid confusion. Thanks again!

**Comment by mholt** [comment]
@Immortalin Did you see that this is finished now?

**Comment by Immortalin** [comment]
Thanks for the heads up!

On 3 July 2015 00:21:21 GMT+08:00, Matt Holt <notifications@github.com> wrote:
>@Immortalin Did you see that this is finished now?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mholt/caddy/issues/19#issuecomment-118083467

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
