### ISSUE TITLE
Caddy support for php-fpm

### ISSUE THREAD

**Issue by Nixtren** [mholt/caddy#190]
Hi,

It seems Caddy only works with the old CGI implementation (php-cgi). If I try to use the new one (php-fpm) I only get a 502 Bad Gateway error. I have checked the active sockets, so that's not the problem.

Socket: 127.0.0.1:9000 (I have also tried with the Unix Socket)

I would appreciate if I could get confirmation on this, otherwise I'm doing something wrong. Thanks for the attention.

P.S: Linux.

**Comment by mholt** [comment]
Hmm, I've actually only ever used php-fpm with it. It should work. What does your Caddyfile look like?

**Comment by abiosoft** [comment]
Same here, I have only used it with php-fpm. However, I've seen someone on Windows that uses php-cgi without issues too.

**Comment by Nixtren** [comment]
Thanks for the answers. This is my Caddyfile:

0.0.0.0:2015
fastcgi / 127.0.0.1:9000 php

**Comment by abiosoft** [comment]
Have you tried connecting with nginx ? Just for confirmation if php-fpm is running correctly.

**Comment by Nixtren** [comment]
It's strange. It works in nginx with the following configuration:
```
server {
    location / {
        fastcgi_pass  localhost:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param QUERY_STRING    $query_string;
    }
}
```
But if I take the fastcgi_param lines it stops working. An easy solution would be Caddy to pass these FastCGI params to php-fpm.

I have also managed to get Caddy working with php-fpm without passing the FastCGI params, to do that I had to put the Caddy executable in the nginx document root folder and run it under the user www-data (the same user as php-fpm). So, it seems this is a permission problem, unless those FastCGI params are passed.

**Comment by mholt** [comment]
Yeah, php-fpm is a beast. You might be able to glean more information from a Caddy error log, if you use `errors error.log` in your Caddyfile then try a request.

The php preset does configure a couple things related to what nginx does with fastcgi_params, see [the docs for fastcgi](http://caddyserver.com/docs/fastcgi). Also, try renaming php.php to something else, like test.php... just to experiment.

**Comment by Nixtren** [comment]
Caddy error:
```
18/Jul/2015:09:56:19 -0500 [ERROR 502 /php.php] malformed MIME header line: Primary script unknown
18/Jul/2015:09:56:24 -0500 [ERROR 502 /test.php] malformed MIME header line: Primary script unknown
```
It seems PHP can't find the script, the same happens with nginx if I change the document root folder to match Caddy's folder. So, looks like a permission issue and not Caddy's problem itself. All files have to be from the user www-data. By the way, I can run Caddy as root to serve the document root folder owned by www-data and it works normally.

**Comment by mholt** [comment]
Mention what, where, exactly? I'm still not clear as to whether this is a php-fpm, file permissions, or Caddy issue. You aren't able to run Caddy as www-data? Are the error messages always the same?

**Comment by Nixtren** [comment]
The issue can be considered resolved as I'm able to run Caddy as www-data and is able to serve the PHP files normally (assuming the files are in a folder owned by www-data too). However, I still have to go deeper in this to see if it's just a permissions problem or the parameters passed by nginx to php-fpm do some difference (the difference between running the PHP script or throwing an error due to insufficient permissions), I just don't have time right now to do that. I will be closing this issue and get back to it once I have time (or someone else that experiences the same problem can give some infomation).

**Comment by mholt** [comment]
Okay. Thanks for your detective work and answering my questions. :+1: Let me know if there's any other way we can help!

**Comment by Prezto** [comment]
I am experiencing this now too with caddy version 0.7.5. I am a normal user and no dev. 

0.0.0.0:9090
root /root/test
log access.log
errors error.log
fastcgi / /var/run/php.sock php
rewrite {
    regexp .*
    ext    /
    to     /index.php?{query}
}

**Comment by Prezto** [comment]
Nevermind Nixtren. I have finally found out this morning that if i add the user to the group php-fpm all works fine. So for others having the same problem. Add the user that runs Caddy to the php-fpm or hhvm group. Whichever you are using.

**Comment by Nixtren** [comment]
Thanks @Prezto for giving out information on how you fixed it :)

**Comment by Prezto** [comment]
Yes. All files are owned by the user/group hhvm/php-fpm. I have tested with both phpfpm and hhvm and both work fine.

**Comment by wayneashleyberry** [comment]
@Nixtren how exactly did you run Caddy as www-data? I've also come across this problem :(

**Comment by notanark** [comment]
I found the answer, you need a space after your content-type: 

I was having the same problem with C# playing around.
