### ISSUE TITLE
How to force download file types?

### ISSUE THREAD

**Issue by squadramunter** [mholt/caddy#1900]
Hi my question is how can I download a file type without showing it in my browser I need to force download the file when I click on that file.

What is the correct configuration for this to place in my caddyfile?

**Comment by magikstm** [comment]
Basically this?
https://stackoverflow.com/questions/10615797/utility-of-http-header-content-type-application-force-download-for-mobile

Possibly with this?
https://caddyserver.com/docs/header

Or that?
https://caddyserver.com/docs/mime

Which file type are you trying to force download for?

I think this question should be asked here: https://caddy.community/latest

**Comment by francislavoie** [comment]
Yep, as @magikstm said, this kind of question should be asked on the forums. Closing this since it's not an issue, but feel free to continue discussion here if you like.
