### ISSUE TITLE
InstanceStartupEvent isn't defined in the source code...

### ISSUE THREAD

**Issue by joncalhoun** [mholt/caddy#1901]
Looking at this source: https://github.com/mholt/caddy/blob/118cf5f24032c1aefb7545576ae1595a24baadf0/onevent/hook/config.go#L17

It references an `InstanceStartupEvent` type that isn't in the source code anywhere as far as I can tell. Where is this defined? Did this not get pushed with a recent change?

It looks like the change was very recent so I'm guessing the commit just has an issue of some sort.

**Comment by francislavoie** [comment]
It's because this PR hasn't been merged yet. https://github.com/mholt/caddy/pull/1888

**Comment by mholt** [comment]
Yes, we know :) We're waiting for that branch to be rebased and to have a merge conflict resolved. (Master branch is not guaranteed to always be stable.)

**Comment by joncalhoun** [comment]
Is there a branch that is reliably stable?

Thanks!

**Comment by mholt** [comment]
Tags are!
