### ISSUE TITLE
How to make a rewrite rule of "Redirect Trailing Slashes If Not A Folder."

### ISSUE THREAD

**Issue by fanybook** [mholt/caddy#1903]
Like this :

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

caddy's rewrite can't use 301
caddy's redir can't use regexp  :(
caddy's rewrite & redir can't -d -f

hope  caddy  support a separate configuration files like .htaccess！because don't need to restart the server when modify the rewrite  rule

**Comment by francislavoie** [comment]
Please ask questions at https://caddy.community/, you'll get a better chance of response.

I'll close this as it's not an issue.
