### ISSUE TITLE
Startup/down deprecation notice should be written to log not stdout.

### ISSUE THREAD

**Issue by tobya** [mholt/caddy#1907]
### 1. What version of Caddy are you using (`caddy -version`)?

0.1.10
### 2. What are you trying to do?

run caddy
### 3. What is your entire Caddyfile?

a caddyfile with the startup directive.

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy

### 6. What did you expect to see?

> NOTICE: Shutdown directive will be removed in a later version. Please migrate to 'on shutdown'

written to logfile not to stdout

### 7. What did you see instead (give full error messages and/or log)?
 written to stdout

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

run caddy with a caddyfile using the startup directive

--

@elcore I think the line [here](https://github.com/mholt/caddy/blob/master/startupshutdown/startupshutdown.go#L43) and for shutdown should us log instead

    log.Println("NOTICE: Shutdown directive will be removed in a later version. Please migrate to 'on shutdown'")

Sorry I didnt notice this before.

**Comment by mholt** [comment]
I feel like logs are less visible at startup than stdout though. I never check logs for when I'm still at the terminal, I would expect this to be written to stdout.

Is it just me?

**Comment by elcore** [comment]
> I feel like logs are less visible at startup than stdout though.

I agree 😄

**Comment by francislavoie** [comment]
Using docker, I never see the stdout logs unless I have an actual problem
with the container that I need to debug.

**Comment by tobya** [comment]
If everyone is happy with it, that's fine.  I'll close.

**Comment by mholt** [comment]
To be clear, I wasn't against it -- just not motivated to make the change myself. 😅
