### ISSUE TITLE
Caddyfile parsing fails when import is used as a "short" CLI Caddyfile

### ISSUE THREAD

**Issue by Whitestrake** [mholt/caddy#1910]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.10 (non-commercial use only)

### 2. What are you trying to do?
Run Caddy without a main Caddyfile by importing all matching `*.caddy` files from a specific folder (a la Apache sites-enabled).

### 3. What is your entire Caddyfile?
`test.caddy` file in $PWD:
```
localhost:2015
browse
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -log stdout "import $PWD/*.caddy"

### 5. Please paste any relevant HTTP request(s) here.
N/A

### 6. What did you expect to see?
```
Activating privacy features... done.
http://localhost:2015
```

### 7. What did you see instead (give full error messages and/or log)?
```
whitestrake at apollo in ~/Projects
→ caddy -log stdout "import $PWD/*.caddy"
2017/10/11 15:44:32 /Users/whitestrake/Projects/test.caddy:1 - Error during parsing: Unknown directive 'localhost:2015'
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
```
mkdir test && cd test
echo "localhost:2015\nbrowse" > test.caddy
caddy -log stdout "import $PWD/*.caddy"
```

**Comment by ekini** [comment]
According to the documentation at https://caddyserver.com/docs/cli, the "short" Caddyfile uses default host and port. Therefore, it can't contain other hosts inside of it.
Looking at the code https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L249,
this is what you actually have (by default):
```
localhost:2015
arguments, joined by newline
```

**Comment by mholt** [comment]
Ah, good point -- I hadn't noticed before, for some reason, @francislavoie that you were trying to define a host and port in the Caddyfile as well. You can change the host and port with the -host and -port flags though, and then just put directives in the Caddyfile. Otherwise import itself should work, I think?

**Comment by Whitestrake** [comment]
Are we open to changing this behaviour?

Currently I'm running Caddy with `-conf /path/to/Caddyfile`, the entirety of which is `import /path/to/*.caddy`. I'd be nice to remove the necessity for that Caddyfile altogether, if possible.

**Comment by mholt** [comment]
Well the point of the "short" Caddyfile is to be... short... and simple. Are you really looking for `-conf /path/to/*.caddy` to work instead?

**Comment by Whitestrake** [comment]
Y'know, in school I was taught not to listen to what a client _thinks_ they want, rather, figure out what they _actually_ want. Ironic...

Yep, that's pretty much it exactly.

We can definitely remove bug from this issue at this point, I think, given that it's working as expected right now. At this stage it's a feature request (for globbing on the `-conf` CLI flag).
