### ISSUE TITLE
On-demand TLS broken in master?

### ISSUE THREAD

**Issue by stp-ip** [mholt/caddy#1912]
### 1. What version of Caddy are you using (`caddy -version`)?
Running with master due to development of plugins.

### 2. What are you trying to do?
On-demand TLS.

### 3. What is your entire Caddyfile?
```text
    :443 {
      tls {
        max_certs 100
      }
      proxy / 127.0.0.1:8042 {
        transparent
      }
      errors
    }
    # redirect to secure address
    :80 {
      tls off
      proxy / 127.0.0.1:8042 {
        transparent
      }
      errors
    }
    # meta redirect
    :8042 {
      tls off
      meta-plugin
      prometheus
      log / stdout "{remote} - [{when_iso}] \"{method} {uri} {proto}\" {status} {size} {latency}"
      errors
    }
    :80/healthz {
      tls off
      status 200 /
    }
    :80/probez {
      tls off
      status 200 /
    }
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy --agree --email=cert@example.com --conf=/config/caddyfile

### 5. Please paste any relevant HTTP request(s) here.
curl -v https://example.com

### 6. What did you expect to see?
On-demand issuance working.

### 7. What did you see instead (give full error messages and/or log)?
On-demand issuance breaking. No error messages in caddy log.
Error: * error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Run caddy on-demand tls with the latest build from master.

Sidenote: A build from 23 days ago works with the same configuration. Serving already available certificates works also. Just retrieving new on-demand certs fails with current master.

**Comment by stp-ip** [comment]
Good to know that this needs to be enabled on the command line additionally.

Probably due to a golang version switch on the build. Old version can load the root cert without issues. The new one can't. Will check it out. Closing for now as it seems more a environment issue. Thanks

**Comment by mholt** [comment]
Well, keep me posted if you figure it out, I'd be interested to know in case others have the same problem!

**Comment by stp-ip** [comment]
Was due to the root certificates not being available to caddy, which would have been clear using the --log flag.
