### ISSUE TITLE
Unable to chain rewrites

### ISSUE THREAD

**Issue by mwpastore** [mholt/caddy#1917]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.10 (unofficial)

### 2. What are you trying to do?

I am trying to chain rewrites such that rewrites affect the path pattern-matching aspects of subsequent rewrites. For example, I'd like to rewrite `/bar/*` to `/foo/*` and have subsequent rewrites be able to focus on `/foo/*` (since `/bar/*` becomes "unreachable"); for example, to protect files in that directory from being accessed directly. Unfortunately, it seems as though subsequent rewrites always use the original path, even when I explicitly use the `{rewrite_path}` placeholder.

### 3. What is your entire Caddyfile?

```Caddyfile
0.0.0.0

tls off

rewrite /bar {
  regexp (.*)
  to /foo{1}
}

rewrite /foo {
  ext .txt
  to /
}

# This also doesn't work:
#rewrite {
  #ext .txt
  #if {rewrite_path} starts_with /foo
  #to /
#}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```console
$ docker run --rm -it -p 2015:2015 \
  -v $(pwd)/Caddyfile:/etc/Caddyfile \
  -v $(pwd):/srv \
  abiosoft/caddy
```

### 5. Please paste any relevant HTTP request(s) here.

```
GET /
GET /foo/test.txt
GET /bar/test.txt
```

### 6. What did you expect to see?

```console
$ curl localhost:2015
Index
$ curl localhost:2015/foo/test.txt
Index
$ curl localhost:2015/bar/test.txt
Index
```

### 7. What did you see instead (give full error messages and/or log)?

```console
$ curl localhost:2015
Index
$ curl localhost:2015/foo/test.txt
Index
$ curl localhost:2015/bar/test.txt
Test
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

1. Copy the above Caddyfile
2. Create the directory structure:

    ```console
    $ mkdir foo
    $ echo Index >index.html
    $ echo Test >foo/test.txt
    ```
3. Start Caddy (doesn't have to be through Docker)
4. Execute the above cURL commands

**Comment by mholt** [comment]
Thanks for filling out the issue template!

The rewrite directive simply chooses the first matching configuration and applies that. Instead, make a single rewrite that goes directly to what you want:

```
rewrite {
    regexp /bar/(.*)
    to /foo/{1}
}
```

(Something like that, anyway.)

Since what can be done by multiple rewrites can also be done with one rewrite, and is simpler, I don't think we're going to make rewrites an optimization function that runs until they converge. We tend to like the simplicity of just "one rule to bind them all." :wink:
