### ISSUE TITLE
Cannot start caddy service as non-root user on FreeBSD

### ISSUE THREAD

**Issue by frickiericker** [mholt/caddy#1923]
### 1. What version of Caddy are you using (`caddy -version`)?

`Caddy (untracked dev build) (unofficial)` from FreeBSD ports (0.10.10 according to [freshports](http://www.freshports.org/www/caddy)).

### 2. What are you trying to do?

Start caddy as a non-root user via the FreeBSD init script.

### 3. What is your entire Caddyfile?

```text
localhost {
    root /www/html
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

In rc.conf:

    caddy_enable="YES"
    caddy_cert_email="nobody@example.com"
    caddy_config_path="/www/Caddyfile"
    caddy_user="www"
    caddy_group="www"

Command:

    sudo service caddy start

### 5. Please paste any relevant HTTP request(s) here.

None

### 6. What did you expect to see?

Caddy starts.

### 7. What did you see instead (give full error messages and/or log)?

Caddy does not start. In caddy.log:

    daemon: failed to set user environment

And in syslog:

    daemon: initgroups(www,80): Operation not permitted

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

1. Install `www/caddy` from ports and configure rc.conf as shown above
2. Allow port 80 binding following [the handbook](https://www.freebsd.org/doc/handbook/mac-policies.html):
    ```
    sudo kldload mac_portacl
    sudo sysctl net.inet.ip.portrange.reservedlow=0
    sudo sysctl net.inet.ip.portrange.reservedhigh=0
    sudo sysctl security.mac.portacl.port_high=1023
    sudo sysctl security.mac.portacl.suser_exempt=1
    sudo sysctl security.mac.portacl.rules=uid:80:tcp:80
    ```
3. `sudo service caddy`

**Comment by francislavoie** [comment]
Did you read this section of the README? https://github.com/mholt/caddy#running-in-production

At a glance this doesn't seem like a problem with Caddy, but rather with your environment.
