### ISSUE TITLE
Server header is included in HTTPS redirect response even if disabled in config

### ISSUE THREAD

**Issue by cskr** [mholt/caddy#1926]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.10 (unofficial)

### 2. What are you trying to do?

Disable the `Server` header in all responses of a site.

### 3. What is your entire Caddyfile?
```text
blog.thecskr.in {
        root /var/www/blog

        header / {
                Strict-Transport-Security "max-age=31536000; includeSubDomains"
                -Server
        }
        header /images {
                Cache-Control "public, max-age=604800"
        }
        gzip

        log /post /var/log/caddy/blog-access.log {combined}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
/usr/local/bin/caddy -log /var/log/caddy/caddy.log -agree=true -email=my@email -conf=/etc/caddy/Caddyfile -root=/var/tmp
```

### 5. Please paste any relevant HTTP request(s) here.

```
$ curl -i http://blog.thecskr.in/
HTTP/1.1 301 Moved Permanently
Location: https://blog.thecskr.in/
Server: Caddy
Date: Wed, 18 Oct 2017 04:23:21 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 59
Accept-Ranges: none
Connection: close

<a href="https://blog.thecskr.in/">Moved Permanently</a>.
```

### 6. What did you expect to see?

```
$ curl -i http://blog.thecskr.in/
HTTP/1.1 301 Moved Permanently
Location: https://blog.thecskr.in/
Date: Wed, 18 Oct 2017 04:23:21 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 59
Accept-Ranges: none
Connection: close

<a href="https://blog.thecskr.in/">Moved Permanently</a>.
```

### 7. What did you see instead (give full error messages and/or log)?

The `Server` header was present.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Try creating a site with `-Server` specified in Caddyfile and access site with `http://` instead of `https://`.

**Comment by tobya** [comment]
Thanks for the issue.

**Comment by mholt** [comment]
This is probably because the automatic HTTP->HTTPS redirects don't use the middleware chain defined by the user. Perhaps we should see if there is a way to get the `header` middleware copied over to the HTTP one when we set up the custom redirect. (It's a special case.)

**Comment by theodesp** [comment]
I suppose we have to revisit the redirPlaintextHost function call to apply any other middeware once in order to honor the Caddyfile directives.
Can I work on this?

**Comment by elcore** [comment]
> Can I work on this?

Sure :)

**Comment by NicolasLM** [comment]
Hi,
I figured that the same issue exists with proxies. The header is removed while serving normal files, but as soon as it goes through the proxy, the headers comes back in the response.

Here is a snippet to reproduce the issue:
```
(common) {
    header / {
        -Server
    }
}

https://foo.bar.com:443 {
    import common

    proxy / {
        transparent
        upstream 127.0.0.1:8000
    }
}
```

Let me know if I should open a different issue if these are not related.

**Comment by riker09** [comment]
Any news on this issue? I stumbled across this behaviour today and wound up here on my quest for knowledge.

## My config

```
(common) {
  header / {
    Server "nginx"
    X-Powered-By "Unicorns"
  }
}

my-domain.tld {

  gzip
  tls mymail@mailprovider.tld

  import common
}

www.my-domain.tld {
  import common      

  redir https://my-domain.tld{uri}
}
```

## The response

```bash
$ curl -IL http://www.my-domain.tld
HTTP/1.1 301 Moved Permanently
Connection: close
Content-Type: text/html; charset=utf-8
Location: https://my-domain.tld/
Server: Caddy
Date: Mon, 15 Apr 2019 10:05:57 GMT

HTTP/2 301 
content-type: text/html; charset=utf-8
location: https://my-domain.tld/
server: nginx
x-powered-by: Unicorns
date: Mon, 15 Apr 2019 10:05:57 GMT

HTTP/2 200 
accept-ranges: bytes
content-type: text/html; charset=utf-8
etag: "ppzy2tyy"
last-modified: Mon, 15 Apr 2019 09:52:05 GMT
server: nginx
x-powered-by: Unicorns
content-length: 1258
date: Mon, 15 Apr 2019 10:05:57 GMT
```

The first block in the `curl` response contains a header `Server: Caddy`.

**Comment by mholt** [comment]
I believe you can define your own port 80 server and remove the header manually, along with issuing the redirect.

**Comment by github-sys-admin** [comment]
not fixed
