### ISSUE TITLE
Encoded forward slash (%2F) in URI not honored.

### ISSUE THREAD

**Issue by thedodd** [mholt/caddy#1927]
### 1. What version of Caddy are you using (`caddy -version`)?
Using 0.10.10

### 2. What are you trying to do?
Use the reverse proxy directive to proxy traffic back to the rabbitmq control panel (not AMQP, just standard tcp/http).

### 3. What is your entire Caddyfile?
```text
:80/admin/mq-management/ {
    # Log everything to stdout. Pattern is as follows:
    # {remote} - [{when}] "{method} {upstream} {uri} {proto}" {status} {size} "{>Referer}" "{>User-Agent}"
    log / stdout "{combined}"

    proxy / rabbitmq:15672 {
        transparent
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy` (defaults to using the Caddyfile mentioned above as it is in the same directory).

### 5. Please paste any relevant HTTP request(s) here.
This fails with `405`:
`curl -XPUT -i http://localhost/admin/mq-management/api/permissions/%2F/guest`

This succeeds with `401` (as in, that is what is expected):
`curl -XPUT -i http://localhost:15672/api/permissions/%2F/guest`

### 6. What did you expect to see?
I expected the behavior between the two curl commands above to be the same & that the proxy would not manipulate the URI.

### 7. What did you see instead (give full error messages and/or log)?
The curl command which goes through the proxy appears to be collapsing the forward slashes. 

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Using docker (this is obviously the easiest way):
- spin up a rabbitmq instance named `rabbitmq`. Expose the needed ports (`15672` mainly).
- spin up a container with caddy 0.10.10 installed with the caddy file above in the CWD; start the container with command `caddy` will read the Caddyfile above as long as it is in the same directory.

**NOTE:** looks like there have been a **decent number of issues reported about this already.** I've pored over them, none of them appear to present a fix.

**Comment by lirener** [comment]
Although I know it is a question and the suggestion,But！（虽然我知道这是一个问题与建议,但是！）

Thank you very much!Finally let me find the regarding print log output to the CMD command line writing I have seen a lot of tutorials didn't mention it...【log / stdout "{combined}"】
（谢谢！终于让我找到了 关于打印日志输出到cmd命令行的写法了 我看过很多教程 都没提到它……【log / stdout "{combined}"】）
![233333](https://user-images.githubusercontent.com/19354130/33798987-cb4be494-dd5d-11e7-90bb-f34f5b051f10.png)

**Comment by tobya** [comment]
@thedodd Thanks for the issue. I've been able to reproduce this.  I dont have rabbitmq but I can reproduce it by simple proxy code.

caddyfile1

```redgrapes.kinchik.ie:80/nonsene {

  log / d:\caddy\logs\redgrapes.log 
  proxy  http://springonion.kinchik.ie:9080 {
    transparent
   
  }
}```

caddyfile2

```springonion.kinchik.ie:9080 {
    tls off
  log / d:\caddy\logs\springonion.log  {common}
    root d:\Development\websites\bcsstudents\Attached
  browse 
}

redgrapes.kinchik.ie:9080 {
tls off
  log / d:\caddy\logs\redgrapes9080.log 
  root D:\godev\bin
  browse
}```

This will cause the logfile d:\caddy\logs\redgrapes9080.log  to contain 

> 127.0.0.1 - - [19/Dec/2017:19:51:43 +0000] "GET /store///nonsens HTTP/1.1" 404 14

You can see the %2f is decoded in this.  There is a workaround until the bug is fixed.

```redgrapes.kinchik.ie:80 {
  log / d:\caddy\logs\redgrapes.log 
  proxy /nonsense http://springonion.kinchik.ie:9080 {
    transparent
    without /nonsense
  }
}```

Instead of putting the path in the host directive at the top, put it in the proxy directive and use the without subdirective to remove it when sending.  This should fix your issue until bug is fixed.

**Comment by mararn1618** [comment]
Here's my ..

### Workaround for Caddy 2 + RabbitMQ with encoded forward slash %2FE

#### 1. --- My environment ---
 - Docker-Compose
 - Caddy
 - RabbitMQ
 - Java Spring Producer (spring-boot-starter-amqp)
 - NodeJS Consumer (amqplib)

.. and I run RabbitMQ on `https://host/rabbitmq` and could not access `https://host/rabbitmq/#/queues/%2f/QUEUE_ISSUE_DLQ`.
```
{$APP_SERVER}:443 {
    redir /rabbitmq     /rabbitmq/

    handle_path /rabbitmq/* {
        rewrite * {path}
        reverse_proxy http://dai-rabbitmq:15672 {
        }
    }
}
```
#### 2. --- Change the default RabbitMQ virtual host ---

According to [this guy](https://github.com/rabbitmq/rabbitmq-management/issues/602#issuecomment-413720536) we can just change the default "virtual host", which is defaulted to '/' (or %2f), which will change the URI to `https://host/rabbitmq/#/queues/NEW_HOST/QUEUE_ISSUE_DLQ`.

#### 2.1 Change the default virtual host in docker-compose.yml
Start RabbitMQ with a different virtual host via docker environment variable:
```
    dai-rabbitmq:
        image: rabbitmq:3-management-alpine
        restart: unless-stopped
        ports:
         - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_VHOST: NEW_HOST
```

#### 2.2 Alternative - Change the default virtual host in the RabbitMQ config
Alternatively you can change the [RabbitMQ config](https://github.com/rabbitmq/rabbitmq-server/blob/v3.6.x/docs/rabbitmq.config.example#L180).

#### 3 --- Change your Java Spring producer/consumer configuration ---
For Spring I prefer to configure via application.yml
```
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
    host: localhost
    virtual-host: NEW_HOST
    username: ********************************
    password: *********************************
```

#### 4 --- Change your NodeJS amqplib producer/consumer configuration ---
For amqplib ..
```
export const environment = {
    "rabbitmq": {
        "host": "dai-rabbitmq",
        "virtual-host": "NEW_HOST",
        "username": "********************************",
        "password": "********************************"
    }
}
```
... and ...
```
amqp.connect('amqp://' + environment.rabbitmq.username + ":" + environment.rabbitmq.password
  + "@" + environment.rabbitmq.host + "/" + environment.rabbitmq["virtual-host"], 
  (error0, connection) => {
    /* your init code */
  });

```

**Comment by tobya** [comment]
This is a closed case. 

This issue is for V1, you are using V2.

May I suggest you post a new issue fillingout the template,  or look for help on https://caddy.community forum
