### ISSUE TITLE
Is Caddy TLS implementation FIPS-140-2 compliant (openssl is compliant)

### ISSUE THREAD

**Issue by vramanx** [mholt/caddy#1928]
Looks like the boringcrypto branch of GO is FIPS compliant: https://github.com/golang/go/tree/dev.boringcrypto.go1.8

Is it possible to make Caddy use this branch?

**Comment by lbguilherme** [comment]
Useful read: http://veridicalsystems.com/blog/secure-or-compliant-pick-one/

**Comment by mholt** [comment]
It's of course possible; you can build Caddy from source, after all.

We will not be doing this, in the interest of progressing better security for the Web.

**Comment by mholt** [comment]
@gedw99 That's very interesting; thanks for the link. Further discussion on this topic is welcome in a new issue or on the forums, as this issue is almost 10 years old and has nothing to do with the current major version of Caddy.
