### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by bigtan** [mholt/caddy#193]
18/Jul/2015:17:10:00 +0800 [PANIC /] /usr/local/go/src/sync/atomic/asm_386.s:118 - runtime error: invalid memory address or nil pointer dereference

My server is Debian 7.5.0 x64, I download the caddy file from github.com and the error above is reported.

Maybe I need to compile it from source.

**Comment by mholt** [comment]
You closed this issue. Did you figure out what was wrong?

Did you download the master branch or the api branch? What does your Caddyfile look like?

**Comment by bigtan** [comment]
@mholt Yes, I just change the architectures of my server, so it is my mistake.
