### ISSUE TITLE
Load environment variables from a .env file

### ISSUE THREAD

**Issue by JulienDuf** [mholt/caddy#1941]
### 2. What are you trying to do?
Load my environment variables from a .env file.

### What I propose
Use the github.com/joho/godotenv package.   
With this package, we can load .env file from anywhere. 

I'm using caddy with a lot of environment variables and it would be useful to put all those variables in a single file

**Comment by tobya** [comment]
Thank you for the issue.  

We are also always happy to look at a PR.  😄

**Comment by SmilingNavern** [comment]
Would like to try to implement this:)

**Comment by abiosoft** [comment]
Sure, you can go ahead.
