### ISSUE TITLE
TLS 1.2 instead of QUIC in Caddy !

### ISSUE THREAD

**Issue by shinichikudo987** [mholt/caddy#1947]
I am using Caddy as Server to serve QUIC. I follow the instruction of caddy.
When I installed the caddy and run the caddy, the result as in picture.
![caddy](https://user-images.githubusercontent.com/9009495/32600908-a770d0ea-c573-11e7-83d4-9bd81bde4b94.png)
When I access to a domain, it run TLS instead of QUIC.
![quic](https://user-images.githubusercontent.com/9009495/32601016-ee2225f2-c573-11e7-9b68-03db44ef0b58.png)
However, it run QUIC when I access to example.org/
![example](https://user-images.githubusercontent.com/9009495/32601039-0122d7aa-c574-11e7-9a2f-c26220e459e9.png)

Any body know why? I run in Chromium 64 which I built from https://www.chromium.org/quic.

This is my Caddyfile:
quic.com:6121 {
tls GenerateKey/out/leaf_cert.pem GenerateKey/out/leaf_cert.key
root /home/bkcs-quic/Desktop/
ext    .html
log access.log
}

**Comment by mholt** [comment]
Probably the same as this and other issues: #1858 - if you build Caddy from source and update its vendored quic-go dependency, it should work.

**Comment by taoyunxing** [comment]
I have the same problem as 	shinichikudo987, could you give me a detailed instruction to update the vendored quic-go dependency? @shinichikudo987 @mholt
