### ISSUE TITLE
Caddy serves Brotli compressed files even if browser doesn't support it

### ISSUE THREAD

**Issue by TroniQ89** [mholt/caddy#1949]
Hi,

I found, I think, a bug with Caddy and Brotli.

### 1. What version of Caddy are you using (`caddy -version`)?

I am using Caddy 0.10.10

### 2. What are you trying to do?

I am trying to add support of Brotli in my developement branch - and then in my production branch -

### 3. What is your entire Caddyfile?
```text
www.mydomain.eu {
   cache {
    path /tmp/website
    default_max_age 60m
   }
   minify
   gzip // I tried with this with both disabled and enabled.
   root /home/website/
   fastcgi / unix:/var/run/php/php7.0-fpm.sock {
      split .php
      index index.php
   }
   expires {
      match .js$ 7d
      match .css$ 7d
      match .png$ 7d
      match .svg$ 7d
   }
basicauth /dev/ myuser mypass {
realm "...."
}

tls XXXXXX@mydomain.com {
 key_type rsa8192
 protocols tls1.1 tls1.2
 dns cloudflare
}
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

screen caddy -quic -http2 -agree
Environment : Linux Debian x64 ; and I've got my CloudFlare API credentials in my environment vars.

### 5. Please paste any relevant HTTP request(s) here.
```text
curl https://www.mydomain.com/dev/index.html -u myuser:mypass
<a href=/dev/>Moved Permanently</a>.
```

### 6. What did you expect to see?

My index.html page served with brotli

### 7. What did you see instead (give full error messages and/or log)?

Firefox / Opera error about a problem of enconding or compression.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

I used 
brotli --input index.html --output index.html.br
And keeping index.html in.
I did the same thing but for gzip, and no problems. 

Thank you for your help! (and sorry for my english ^^)

**Comment by gmemstr** [comment]
This could possibly be done with the [Accept-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding) request header, I'll take a deeper look. Unless there's an underlying issue in the config I'm not seeing (does it serve the non-brotli files fine?)

**Comment by tobya** [comment]
I'm going to close this issue for now.
