### ISSUE TITLE
CommonLogFormat needs to be updated to include {user} placeholder

### ISSUE THREAD

**Issue by magikstm** [mholt/caddy#1951]
Following this PR: #1937

I think this line should be updated to use the {user} placeholder:
https://github.com/mholt/caddy/blob/baf6db5b570e36ea2fee30d50f879255a5895370/caddyhttp/log/log.go#L94

Or another predefined format be created with it.

Documentation here isn't up-to-date:
https://caddyserver.com/docs/log

On the current common log format:
```
{common} (default)
{remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size}
```

**Comment by mholt** [comment]
Probably a good idea, thanks for bringing this up.

**Comment by tobya** [comment]
Merged
