### ISSUE TITLE
Sprig templates

### ISSUE THREAD

**Issue by gillesdemey** [mholt/caddy#1958]
The [sprig library](https://github.com/Masterminds/sprig) contains a lot of useful functions that would make the current templates directive more powerful — in particular `default`, `coalesce` and some crypto functions like `sha256sum`.

Anything in particular we should be mindful of if we decided to add these?

I could submit a PR if this sounds like a good idea 😊

**Comment by mholt** [comment]
Implemented in Caddy 2.
