### ISSUE TITLE
Request body not passed to PHP for GET requests

### ISSUE THREAD

**Issue by warpr** [mholt/caddy#1961]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.10 (unofficial)

### 2. What are you trying to do?

Read the request body of a GET request.

### 3. What is your entire Caddyfile?
```text
127.0.0.1 {
    tls off
    
    errors /var/log/caddy/bliid.errors.log
    log /var/log/caddy/bliid.access.log
    
    browse /
    root /home/kuno/code/bliid/www
    fastcgi / /var/run/php-fpm/www.sock php
    
    rewrite /bliid/ {
        to {path} {path}/ /index.php?uri={uri}
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
/usr/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp -port=80
```
### 5. Please paste any relevant HTTP request(s) here.

```sh
11:26 kuno@18-volt:~/code/bliid (master)$ curl -X GET http://127.0.0.1/bliid/ --data '{ "port": 8080 }'
Request body: 

Done.
```

### 6. What did you expect to see?

```sh
11:26 kuno@18-volt:~/code/bliid (master)$ curl -X SOMETHING http://127.0.0.1/bliid/ --data '{ "port": 8080 }'
Request body: { "port": 8080 }

Done.
```

### 7. What did you see instead (give full error messages and/or log)?

```
18/Nov/2017:20:48:21 -0500 [ERROR 502 /index.php] http: request method or response status code does not allow body
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Set up Caddy to serve PHP, then use the following as index.php:

```php
<?php

$body = file_get_contents('php://input');

echo "Request body: $body\n\nDone.\n";
```

**Comment by abiosoft** [comment]
This isn't entirely a bug as request body is not expected for GET requests.

**Comment by thepatrick** [comment]
My understanding is that request body processing should ignore the method (per [RFC 7230 3.3 Message Body](https://tools.ietf.org/html/rfc7230#section-3.3)

**Comment by francislavoie** [comment]
Is there any reason to not fix this? From my perspective there isn't really a downside, it's really up to the application to determine what to do with it. I don't think there's any security concerns with that either, as long as the application doesn't do anything weird.

**Comment by abiosoft** [comment]
This is more of a feature than a fix, I don't see it as a bug.
And I'm indifferent, I'm willing to handle this if there is enough vote in favour of it.

**Comment by warpr** [comment]
I understand it's not something commonly needed.

The typical use-case (used by elasticsearch if I'm not mistaken), is that you're doing a GET request with some kind of search query or filter.  But the filter or query is too large to include in the query string, so you want to send it in the request body instead.

**Comment by EtienneBruines** [comment]
> *https://tools.ietf.org/html/rfc7231#section-4.3.1*:
> A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.

Body on GET request isn't forbidden, so there's also no RFC-reason not to do this.
