### ISSUE TITLE
Reload caddyfile with sigusr1: no Caddyfile loader with which to reload Caddyfile

### ISSUE THREAD

**Issue by pwFoo** [mholt/caddy#1964]
Hi,

I used caddy with a reload by "kill -SIGUSR " and it worked fine in the past.
Now I updated to latest caddy version yesterday and tried it again, but it stopped working:
2017/11/24 08:03:37 [INFO] SIGUSR1: Reloading
2017/11/24 08:03:37 [ERROR] SIGUSR1: no Caddyfile loader with which to reload Caddyfile

Is it broken? How to reload a changed config without restart?

**Comment by mholt** [comment]
> Hi,

> I used caddy with a reload by "kill -SIGUSR " and it worked fine in the past.
> Now I updated to latest caddy version yesterday and tried it again, but it stopped working:
> 2017/11/24 08:03:37 [INFO] SIGUSR1: Reloading
> 2017/11/24 08:03:37 [ERROR] SIGUSR1: no Caddyfile loader with which to reload Caddyfile

> Is it broken? How to reload a changed config without restart?

Hi, please fill out the issue template, because we need that information or we cannot help you. Feel free to re-open the issue after you've filled out the issue template.
