### ISSUE TITLE
Security: Padding Oracle Attack

### ISSUE THREAD

**Issue by zaolin** [mholt/caddy#1976]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?
Attacking caddy via https://github.com/RUB-NDS/TLS-Attacker/wiki/Attacks
using the Padding Oracle Attack.

### 6. What did you expect to see?
```
18:28:32 [main] CONSOLE attacks.impl.Attacker - A server is considered vulnerable to this attack if it responds differently to the test vectors.
18:28:32 [main] CONSOLE attacks.impl.Attacker - A server is considered secure if it always responds the same way.
18:28:32 [main] CONSOLE attacks.impl.Attacker - The server shows no behaviour difference on the protocol / socket layer. The Server seems to be fine.
18:28:32 [main] INFO  attacks.Main - Vulnerable:false
```

### 7. What did you see instead (give full error messages and/or log)?
```
18:32:11 [main] CONSOLE attacks.impl.Attacker - A server is considered vulnerable to this attack if it responds differently to the test vectors.
18:32:11 [main] CONSOLE attacks.impl.Attacker - A server is considered secure if it always responds the same way.
18:32:11 [main] CONSOLE attacks.impl.Attacker - Found an equality Error: RECORD_COUNT
18:32:11 [main] CONSOLE attacks.impl.Attacker - The server responds with different amounts of records.
18:32:11 [main] INFO  attacks.Main - Vulnerable:true
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Use the TLS Attacker toolkit https://github.com/RUB-NDS/TLS-Attacker
```
 java -jar Attacks.jar padding_oracle -connect [host]:[port]
```

**Comment by mholt** [comment]
Thanks for the report. This is a [known issue with Go's implementation of CBC ciphers](https://golang.org/pkg/crypto/tls/#pkg-note-BUG):

> The crypto/tls package only implements some countermeasures against Lucky13 attacks on CBC-mode encryption, and only on SHA1 variants. See http://www.isg.rhul.ac.uk/tls/TLStiming.pdf and https://www.imperialviolet.org/2013/02/04/luckythirteen.html.

The right place to deal with this would be to submit a patch to the Go project.

Or you can disable CBC ciphers in your Caddyfile if you're concerned about this. Modern clients will not choose CBC cipher suites, so you'll only break old and already-broken clients anyway. We'll probably update Caddy's cipher suite defaults in 2018.

**Comment by zaolin** [comment]
Cool! Thanks for the professional answer :) . Only wanted to make sure you are aware of it regarding the caddy ciphersuites.
