### ISSUE TITLE
Create official Docker image

### ISSUE THREAD

**Issue by lorddaedra** [mholt/caddy#1977]
I would like to use Caddy as main server proxy for Docker-containers. I can use only Docker images (and data volumes) to do that.

It's not clear, which image to choose. For now I use https://hub.docker.com/r/abiosoft/caddy/ bacause of it has more stars than other images on search results page (I used word `caddy` for search on Docker Hub). Can you please, create official image, based on latest Go and Alpine?..

**Comment by tobya** [comment]
@abiosoft Docker image is as official as it gets, so I think you can be confident of using that one.

**Comment by abiosoft** [comment]
There have been discussions around official docker image both on the community and here and I don't want to resurrect that. 
However, if you want more flexibility you can easily fork [abiosoft/caddy](https://hub.docker.com/r/abiosoft/caddy/) and extend it for your use case just like what many does.

**Comment by lorddaedra** [comment]
@abiosoft You image looks good, I'm completely satisfied with it. I just confused, there is no any links from official Caddy site to it in docs. And about prefix.

I mean, https://hub.docker.com/_/golang/ or https://hub.docker.com/_/postgres/ looks as official image because of `_` in url.
