### ISSUE TITLE
if/else in Caddyfile?

### ISSUE THREAD

**Issue by milewski** [mholt/caddy#1983]
hey guys is it possible to add a ternary (or some sort of if else) somehow into caddy config file?? i cant really version control it and have a common .env file for staging and production... im looking something like this:

```
*.{$DOMAIN} {
    tls {$PRODUCTION} == 'true' ? {$TLS_BUNDLE} {$TLS_PRIVATE} : {$EMAIL}
}
```

**Comment by mholt** [comment]
It's on its way; see #1948 - closing this issue to move any necessary discussion there.
