### ISSUE TITLE
[Feature] http.rewrite - FallbackResource

### ISSUE THREAD

**Issue by magikstm** [mholt/caddy#1985]
I think Apache's mod_dir `FallbackResource` feature would be a nice addition to Caddy's `http.rewrite` directive.

Ref: https://httpd.apache.org/docs/trunk/en/mod/mod_dir.html#fallbackresource
Ref: https://caddyserver.com/docs/rewrite

Something like:

> rewrite [basepath] {
>    fallbackresource
>    to destinations
> }

It was first requested here in the forum: https://caddy.community/t/what-is-the-equivalent-of-apaches-fallbackresource/1309

**Comment by lbguilherme** [comment]
You can already specify multiple values to `to`. It will try in order and use the first one for which the file exists, or the last one. This is what I do for React applications:

```
  rewrite {
    to {path} {path}/ /
  }

**Comment by abiosoft** [comment]
If I get you right, you want to rewrite everything that is not a static file to the index page.
```
rewrite {
  to {path} /index.html
}
```
And like @lbguilherme pointed out, you can have multiple values under `to`.

I'll be closing this until we can ascertain your request is indeed not possible yet.

**Comment by magikstm** [comment]
@lbguilherme thanks a lot. It works perfectly with my app. The `{path} {path}/` is really powerful and I didn't know it could be used that way.

@abiosoft thanks for this example. this one doesn't retain location. It might be useful in the member's area or to ensure a proper workflow if needed. I'll possibly use it in that project.

I would suggest adding @lbguilherme example to the [http.rewrite](https://caddyserver.com/docs/rewrite) Examples section.
