### ISSUE TITLE
TLS Handshake

### ISSUE THREAD

**Issue by justinglock40** [mholt/caddy#1986]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?
Reverse Proxy

### 3. What is your entire Caddyfile?
```text
####################################################################################
# web domain server block 
####################################################################################

********.dynu.net {

  tls justin@icloud.com       # Email for Let's Encrypt Verification

  on startup C:\caddy\php\php-cgi.exe -b 127.0.0.1:9000 &
  
  import common.conf

}


*******.dynu.net {

  tls justin@icloud.com        # Email for Let's Encrypt Verification
  
  import nowshowing.conf

}


####################################################################################
# localhost server block 
####################################################################################

http://localhost {

  import common.conf

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Running as NSSM service in windows
### 6. What did you expect to see?
Webpage

### 7. What did you see instead (give full error messages and/or log)?
Blank Page no resolution

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Use AdvanceTomato Router Firmware instead of stock

Original Message from forum:

Trying to use caddy as a reverse proxy to applications running on my server such as Sonarr and Radarr. This all worked fine when I was using the Stock firmware on Netgear R7000, but now I loaded up Tomato (AdvancedTomato) and I can not access any of my proxies such as “proxy.dynu.net/open” (which worked prior to the firmware change). Now only the base url responds appropriately e.g., “proxy.dynu.net”.

All others return this message in the log:

_http: TLS handshake error from 192.168.1.1:54149: read tcp 192.168.1.10:443->192.168.1.1:54149: wsarecv: An existing connection was forcibly closed by the remote host._

**Comment by magikstm** [comment]
Are ports 80, 443 and 54149 available externally?

I would suggest trying DMZ at that IP temporarily to see if the issue is resolved with it.

Then, I would review port-forwarding for the above ports.

**Comment by justinglock40** [comment]
Port 80, 443 are forwarded. The port 54149 doesn’t need to be forwarded for the stock nether firmware

**Comment by magikstm** [comment]
Does it work on DMZ?

**Comment by justinglock40** [comment]
Didn’t try I reloaded the stock firmware because i need those services available.

**Comment by dinhngtu** [comment]
Could you post the proxy directives that you used? Does the upstream require SNI?

**Comment by justinglock40** [comment]
I have no earthly idea. Below are is my .conf:

############ Code starts below #################################################


ext .html .htm .php
  root C:\caddy\www\Landing

  gzip

  header / {
    X-Content-Type-Options nosniff
    X-XSS-Protection "1; mode=block"
    Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
	  -Server
  }


  log /caddy/logs/access.log {
    rotate_size 1          # Rotate after 1 MB
    rotate_age  7          # Keep log files for 7 days
    rotate_keep 2          # Keep at most 2 log files
  }

  errors /caddy/logs/error.log {
    rotate_size 1          # Set max size 1 MB
    rotate_age  7          # Keep log files for 7 days
    rotate_keep 2          # Keep at most 2 log files
  }
  
 
  proxy /pihole 192.168.1.17/admin/ {          
      without /pihole
      transparent
      header_upstream X-Deluge-Base "/pihole"
  }
 
  proxy /ombiv3 127.0.0.1:5000 {      # https://github.com/rembo10/headphones
      transparent
  }

  proxy /sonarr localhost:8989 {          # https://sonarr.tv/
      transparent
  }

  proxy /tautulli 127.0.0.1:8183 {          # https://github.com/JonnyWong16/plexpy
      header_upstream X-Forwarded-Host {host}
      transparent
  }
 
  proxy /nzbget 127.0.0.1:6789 {          # http://nzbget.net/
      transparent
  }
 
  proxy /nzbhydra 127.0.0.1:5075 {        # https://github.com/theotherp/nzbhydra
      transparent
  }
 
  proxy /deluge 127.0.0.1:8112 {          # http://deluge-torrent.org/
      without /deluge
      transparent
      header_upstream X-Deluge-Base "/deluge"
  }
 
  proxy /headphones 127.0.0.1:8181 {        
      transparent
  }
   
  proxy /radarr 127.0.0.1:7878 {          # https://github.com/Radarr/Radarr
      transparent
  }

  proxy /jackett 192.168.1.10:9117 {          # https://github.com/Radarr/Radarr
      transparent
  }

**Comment by mholt** [comment]
I believe this has something to do with your router, not Caddy. I would look into what about the firmware update you did might change about the router so that it won't properly connect like it used to. If you have further questions about Caddy, you may ask them in the forum: https://caddy.community!
