### ISSUE TITLE
QUIC 39

### ISSUE THREAD

**Issue by vladbondarenko** [mholt/caddy#1987]
Hi guys,

As for Lucas:
v0.6.0 (2017-12-12)
    Add support for QUIC 39, drop support for QUIC 35 - 37

But when i try to download caddy from home i got only 
alt-svc:quic=":443"; ma=2592000; v="38,37,36,35"

Can you please update to the latest version?

Thanks.

**Comment by francislavoie** [comment]
See https://github.com/mholt/caddy/pull/1968, it's coming soon.
