### ISSUE TITLE
caddy dies on startup with faulty DNS

### ISSUE THREAD

**Issue by root360-AndreasUlm** [mholt/caddy#1992]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.10

### 2. What are you trying to do?
Running caddy with DNS managed by third party and let's encrypt managed certificates.
The third party might change their DNS anytime without notifying us and by that break the ACME challenge.

### 3. What is your entire Caddyfile?
```text
https://invalid-domain {
  redir / https://www.{host}[uri} 301
  tls {
    key_type rsa4096
  }
  request_id
  log / syslog "({request_id}) {combined} {host} {latency_ms}"
  errors syslog
  header / Strict-Transport-Security "max-age=31536000; includeSubDomains";
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Started using the sysv-init script extended by me with PR #1984 .
* started as www-data
* CADDYPATH=/etc/ssl/caddy/
```text
/usr/local/bin/caddy -agree=true -log=/var/log/caddy.log -conf=/etc/caddy/Caddyfile
```

### 5. Please paste any relevant HTTP request(s) here.
None, as the error happens on startup.

### 6. What did you expect to see?
Caddy starting correctly and logging an error message that ACME failed like it does in On-Demand mode and on config reload.

The current behaviour (exiting with error message) is nice for development and when you have full control over the configuration and the DNS of domains delivered by caddy.
Unfortunately it is very bad for a use-case where the delivered domains aren't under your control because you are e.g. a hosting provider. This behaviour results in an outage of your service until you found every domain that won't succeed the initial ACME challenge on startup of caddy.

### 7. What did you see instead (give full error messages and/or log)?
```text
Activating privacy features...2018/01/11 11:22:55 [INFO][invalid.root360.eu] acme: Obtaining bundled SAN certificate
2018/01/11 11:22:55 [INFO][invalid.root360.eu] AuthURL: https://acme-v01.api.letsencrypt.org/acme/authz/-rMU242AAl2oe8nv1y2iu3HlZRAy_l97FHkpaCNkfiE
2018/01/11 11:22:55 [INFO][invalid.root360.eu] acme: Trying to solve HTTP-01
2018/01/11 11:22:57 [invalid.root360.eu] failed to get certificate: acme: Error 400 - urn:acme:error:connection - DNS problem: NXDOMAIN looking up A for invalid.root360.eu
Error Detail:
        Validation for invalid.root360.eu:80
        Resolved to:

        Used:

```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
* caddy config:
```text
https://invalid-domain.org {
  tls le-test@example.com
}
```
* run caddy with:
```text
caddy -log stdout -conf Caddyfile
```

**Comment by mholt** [comment]
Hi Andreas -- this is intentional; Caddy can't serve your site securely without being able to verify the domain. If you don't have control over DNS, then it can't serve your site with a certificate from Let's Encrypt.

You appear to be starting a new Caddy process, yet claiming that the current behavior results in an outage, even though Caddy was not running, since you are just starting it up. If you want to change Caddy's configuration without stopping the process, use SIGUSR1.

If you prefer that Caddy always start even though it knows it cannot properly serve the sites you require, use on-demand TLS (set max_certs in the `tls` directive). That is probably a better fit if you are serving an undetermined number of sites.

**Comment by root360-AndreasUlm** [comment]
I'm already using on-demand TLS for most domains.
Unfortunately I see some issues with generating the certificates which I currently try to reproduce and debug in a testing environment.
When I can reproduce it, I'll open a new issue.

**Comment by mholt** [comment]
Hmm, alright. If you're relying on the TLS-SNI challenge for renewals (which it doesn't seem like it, based on what you posted here), that could be the problem since that challenge is disabled indefinitely.

Why not use on-demand for all sites?

**Comment by root360-AndreasUlm** [comment]
No I even disabled TLS-SNI yesterday via cli-flag after reading about the deactivation.
Therefore I updated the PR #1984 to allow overwriting DAEMONOPTS.

We aren't using only on-demand mode because we found that #1994 happens when migrating from a third-party certificate to let's encrypt.

**Comment by mholt** [comment]
I think #1994 might be a duplicate of https://github.com/mholt/caddy/issues/1991. If so, I've already started working on a fix (but am delayed as my computer was in for repairs for a while).
