### ISSUE TITLE
sigtrap only triggers on INT

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#1993]
killing caddy (and coredns) should trigger OnFinalShutdown callbacks, while looking at the code (on why this isn't happening), I see https://github.com/mholt/caddy/blob/master/sigtrap.go#L40 is only trapping on SIGINT. 

Is this intentional? Add SIGTERM here would make a lot of sense of kill sends this by default.

**Comment by mholt** [comment]
Yeah, this is intentional, and is as-documented: https://caddyserver.com/docs/cli#signals -- SIGINT and SIGQUIT execute the shutdown hooks.

**Comment by miekg** [comment]
fair enough
(/me should RTFM)

Thanks!

**Comment by mholt** [comment]
No problem! Let me know if it causes any trouble as-is.

**Comment by miekg** [comment]
thinking some more. SIGTERM should do this as well, can prolly find in the posix spec. But graceful shutdown usually is done via TERM (and then a KILL). 

Kubernetes uses TERM as well, not sure I can find a way to change this for a specific deployment.

**Comment by miekg** [comment]
Yes, please change; as SIGTERM *and then* a SIGKILL is pretty normal.

Alternatively I could prepare (or move invasive PR) to makes this configurable, so CoreDNS can behave differerently than Caddy in this regard.

**Comment by miekg** [comment]
looked at the wrong file. I (only?) need the `sigtrap_posix.go` on. This is trivial if you want to make TERM call the callback as well.
If not a `caddy.<Variable>` could be exported that when set will just call `fallthrough` from the syscall.SIGTERM case.
