### ISSUE TITLE
Duplicate site not caught by -validate command line param

### ISSUE THREAD

**Issue by tobya** [mholt/caddy#1999]
I found this issue, I will come back with more info, but wanted to record here.
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.9

### 2. What are you trying to do?

Validate that the caddyfile is valid before restarting caddy
### 3. What is your entire Caddyfile?
```text

myhost.ie {
 browse
}

anotherhost.ie myhost.ie {
browse
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -Validate

### 5. Please paste any relevant HTTP request(s) here.

NA

### 6. What did you expect to see?

Caddy file not valid 

>2018/01/19 10:37:11 duplicate site address: myhost.ie

### 7. What did you see instead (give full error messages and/or log)?

Caddyfile Valid
### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

use a caddyfile with a duplicate host and try to validate.

**Comment by root360-AndreasUlm** [comment]
Hi,

please try the current Caddy version 0.10.10.
For me this version complains correctly:
```
# cat test-1999.conf 
myhost.ie {
 browse
}

anotherhost.ie myhost.ie {
browse
}

# caddy -conf test-1999.conf -validate
2018/01/24 07:47:08 duplicate site address: myhost.ie
# echo $?
1
# caddy -version
Caddy 0.10.10                                              
```

**Comment by mholt** [comment]
@tobya I'm also not able to reproduce this, it works fine for me in Caddy 0.10.10. Not sure what would have changed to make it start working (off the top of my head). I used your exact Caddyfile.

Feel free to open if there's any more information. :)
