### ISSUE TITLE
Real client IP forwarding for reverse proxy

### ISSUE THREAD

**Issue by ianchen06** [mholt/caddy#20]
Hi I'm wondering if it is possible that Caddy can forward the real ip address of the clients, like the X-Forwarded-For and X-Real_Ip? I would like to use the clients IP address in my rails app which Caddy is proxying to.

Thanks and great work!

**Comment by abiosoft** [comment]
The proxy middleware is implemented using `NewSingleHostReverseProxy` in `net/http/httputil` package which seems to cater for `X-Forwarded-For` if you look [here](https://golang.org/src/net/http/httputil/reverseproxy.go#L138).

What is the current behaviour ?

Thanks.

**Comment by mholt** [comment]
@ianchen06 Are you still having trouble? If so, feel free to re-open this issue with more details. Thanks for your comments!
