### ISSUE TITLE
maybe you could use godep manage third dependency

### ISSUE THREAD

**Issue by Alienero** [mholt/caddy#200]

**Comment by mholt** [comment]
Yeah, this is something we're looking into. We'll probably have dependencies pinned down before we reach 1.0.

**Comment by rmrio** [comment]
Just interesting, what you think about using gb tool?

**Comment by mholt** [comment]
gb is a good tool. When I tried it, it didn't support cross-compilation which was a show-stopper. It does now, so I need to try again. I'm also waiting to see how the Go 1.5 vendor experiment goes.

**Comment by Unknwon** [comment]
@mholt checkin vendor to VCS feels so rude, just discovered `glide` which just locks version of deps (thinking using it for my projects too).

**Comment by mholt** [comment]
Nice. Yeah, and with Caddy we have somewhat of a unique situation since builds are done live in production. The updated build server that I've already started working on sort of does its own dependency management.

**Comment by mholt** [comment]
We might use the Go tool vendor feature coming with Go 1.6, so I'm going to close this. Vendoring at least certain dependencies is something I'll be looking into.
