### ISSUE TITLE
Google Cloud documentation for auto-https

### ISSUE THREAD

**Issue by brianmhunt** [mholt/caddy#2000]
This is an issue related to documentation at: 

- https://caddyserver.com/docs/automatic-https
  - under the `Enabling the DNS Challenge` section
    - at `googlecloud`

The Google Cloud DNS resolver seems to also need all three environment variables (so "and"):

- `GCE_PROJECT`
- `GCE_DOMAIN` (the Google Cloud DNS zone)
- `GOOGLE_APPLICATION_CREDENTIALS`

Currently it says `GOOGLE_APPLICATION_CREDENTIALS` or `GCE_PROJECT`, but all three appear to be needed (based on experimentation and brief inspection of the code).

**Comment by mholt** [comment]
Oh yes, I seem to remember this change happening but I guess I forgot to update the docs. Thanks, I've updated the docs locally and they will go out with the next release.
