### ISSUE TITLE
New release with quic_go 0.6?

### ISSUE THREAD

**Issue by neilstuartcraig** [mholt/caddy#2002]
Hey all

I was just wondering roughly when we could expect a new version of Caddy with quic_go 0.6 (https://github.com/lucas-clemente/quic-go/releases/tag/v0.6.0) which I believe supports quic 39.

Cheers :-)

**Comment by mholt** [comment]
Soon, please see #1968. Thanks!

**Comment by neilstuartcraig** [comment]
Ah cool, thanks @mholt - i didn't see that issue. Looking forward to it :-)
