### ISSUE TITLE
HTTP/2 push over quic does not work.

### ISSUE THREAD

**Issue by Henrocker** [mholt/caddy#2003]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?
Push Assets via h2/quic to the browser.

### 3. What is your entire Caddyfile?
```text
https://example.com {
        tls /etc/caddy/cert.crt /etc/caddy/key.key {
                protocols       tls1.0 tls1.2
        }
        gzip {
                ext *
                level 4
        }
        fastcgi / unix:/run/php/php7.0-fpm.sock php {
                root    /etc/html
        }
        push /index.html {
                /css/asset1.css
                /css/asset2.css
                /js/script1.js
                /js/script2.js
        }
        header / {
                X-XSS-Protection "1; mode=block"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "SAMEORIGIN"
        }
                root /etc/html
                ext .html .htm .php
                log /etc/caddy/log/access.log
                errors /etc/caddy/log/error.log
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
screen ./etc/caddy/caddy -quic

### 6. What did you expect to see?
Assets get pushed to the client while using h2/quic

### 7. What did you see instead (give full error messages and/or log)?
Assets are downloaded as per seperate request by the browser.

When i turn off quic in caddy, then the files get pushed to the client.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Starting the caddy webserver with quic support, setting up a html file with one or more assets and then use the push directive in caddyfile to push assets to the client. When turning off quic, the files will get pushed to the client, just not when using quic.

**Comment by francislavoie** [comment]
See https://github.com/mholt/caddy/pull/1968, it's on the way!

**Comment by Henrocker** [comment]
Okay, thanks, and with Quic v39, http2 push will work over quic?

**Comment by twdkeule** [comment]
Unfortunately not yet.
https://github.com/lucas-clemente/quic-go/pull/715
