### ISSUE TITLE
Plugin for generating podcast feeds

### ISSUE THREAD

**Issue by jpoehls** [mholt/caddy#201]
This is a proposal for a new add-on. I don't have time to work on it myself right now but would like to get the spec flushed out and help in any other way I can.

Read, comment, let's get all the details ironed out so it is easy for someone to pick up and implement!

# Use case

Generates RSS and Atom podcast feeds from a directory of audio files.

- Simple podcast serving
- Simple way to create private/personal podcast feeds for your audio book files, etc by just dropping them into a folder and letting Caddy create the feed for you.

Caddy uses metadata from the audio files themselves for the episode information, or lets you provide more detailed metadata as desired.

Caddy handles generating the various podcast feed formats and ensuring compliance with fancy features of iTunes and such.

# Caddy config

```
podcast basepath {
	dirpath
	cover			[path]
	itunes_cover	[path]
	generator		[name]
	author			[author]
	contributor		[contributor]
	publisher		[publisher]
	link			[link]
}
```

- **basepath** is the base path to match. Podcast will not activate if the request URL is not prefixed with this path. Podcast will match the following specific paths under the base path to serve the feeds from:
    - **/rss.xml** for the RSS 2.0 feed
    - **/atom.xml** for the Atom 1.0 feed
     
     E.g., if basepath is /podcast then the RSS feed will be at /podcast/rss.xml
 
- **dir** is the directory path that contains the MP3 files that should be included in the podcast feed.
cover is the path to the JPEG that should be used as the podcast's cover art.
- **itunes_cover** is the path to the JPEG that should be used as the podcast's cover art in iTunes.
- **generator** is the metadata to include about the program that generated the podcast feed. Defaults to `Caddy/1.7.1`. Used as `/atom10:feed/atom10:generator` and `/rss/channel/generator`.
- **author** is the metadata to include about the podcast's author or creator. Used as `/atom10:feed/atom10:author`, `/rss/channel/dc:creator`, and `/rss/channel/itunes:author`
- **contributor** is the metadata to include about the podcast's contributors. Used as `/atom10:feed/atom10:contributor` and `/rss/channel/dc:contributor`.
- **publisher** is the metadata to include about the podcast's publisher. Used as `/rss/channel/dc:publisher` and `/rss/channel/itunes:owner`.
- **link** is the URL to the podcast's website.

## Simple directory structure example

```
|- PilgrimsProgress
	|- chapter_01.mp3
	|- chapter_02.mp3
	|- chapter_03.mp3
```

Caddy would serve a podcast feed at `/PilgrimsProgress/rss.xml` with the three chapters each as episodes.

## Episode generation

Each MP3 in the specified directory is included in the podcast feed as an episode. Metadata is extracted from the ID3 tags of the MP3 to provide information about the episode. Alternatively, you can provide a companion metadata file for each episode which will be used instead of the ID3 data.

https://github.com/dhowden/tag is used to extract the ID3 tags.

Here is the podcast feed metadata for episodes and how it is determined.

- GUID: is generated when the feed is generated. **TODO: GUID should be persisted between feed regeneration for same episodes.**
- Title: is the Title from ID3
- Description: defaults to empty
- Duration: is read from the MP3 file
- Publication Date: is the Created On timestamp of the MP3 file
- Comments: defaults to empty
- Author: defaults to the Artist from ID3, falls back to the feed author
- Publisher: defaults to the feed publisher
- Link: defaults the feed link
- Show Notes: defaults to the Lyrics from ID3

## Episode ordering

Order of episodes in the feed will be alphabetical based on the episode filenames.

## Audio files 

You can provide multiple formats for your audio by naming the files the same with different file extensions.

If you have the following file structure:

```
|- episode_01.mp3
|- episode_01.ogg
```

Then only one episode will be generated and will include both MP3 and OGG as audio formats.

We will try to extract ID3 data from the files in alphabetical order.

## Side car metadata files

You can provide explicit metadata for each episode in side car file like so.

```
|- episode_01.mp3
|- episode_01.json|yaml|toml|xml
```

Example file format:

```
guid: _
title: _
description: _
link: _
duration: _
publication_date: _
comments: _
author: _
publisher: _
show_notes: _
enclosure: _
```

## Serving audio files from S3, etc.

You can also serve your audio files from S3 or any other non-Caddy location by simply providing the sidecar metadata files and specifying enclosure.

Example:

```
|- episode_01.json|yaml|toml|xml
```

**episode_01.yaml**

```
     ...
     enclosure: https://example.com/path/to/episode.mp3
```

**TODO: Specify how multiple enclosures should be specified, their file sizes, media type, etc.**

**TODO: In addition to a file per episode's metadata, should we also allow all episode metadata to be in a single file that we read? Something like index.json?**

Podcast guidelines: https://github.com/gpodder/podcast-feed-best-practice/blob/master/podcast-feed-best-practice.md

**Comment by mholt** [comment]
Hey @jpoehls - thanks for your comment! This is a nice proposal, so I have linked to this issue from [a thread in our community forum](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127?u=matt) where we are aggregating ideas/requests for Caddy plugins.

If you want to continue discussing the plugin before development begins on it, feel free to start a new topic on the forum. :+1: Hope to see you participate with us there!
