### ISSUE TITLE
mitm: False positive with Firefox ESR

### ISSUE THREAD

**Issue by Clavis0** [mholt/caddy#2021]
### 1. What version of Caddy are you using (`caddy -version`)?
None (i.e. https://caddyserver.com/docs/mitm-detection)

### 2. What are you trying to do?
use it

### 3. What is your entire Caddyfile?
```text
n/a
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?
n/a

### 5. Please paste any relevant HTTP request(s) here.
n/a

### 6. What did you expect to see?
chrome on same machine shows "MITM unlikely"
firefox 52.6..0 ESR in safe mode shows "MITM likely"

### 7. What did you see instead (give full error messages and/or log)?
n/a

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
install firefox esr. 
view https://caddyserver.com/docs/mitm-detection

**Comment by mholt** [comment]
Thanks for your report! Can you please provide:

- The exact TLS ClientHello bytes (hex-encoded is preferred)
- The exact User-Agent string
- Your OS and platform and environment information (should be in UA, I know, but I need to know anything else relevant to your system)
- Some convincing verification that your connection is not, in fact, being intercepted

Looking forward to making our MITM detector more accurate!

**Comment by mholt** [comment]
Going to close this for inactivity. :( Please feel free to reopen if you can get me that information!

**Comment by Clavis0** [comment]
I had answered your questions (extensively) by email answer to you on Feb 13th, 23:14, answering your email.

**Comment by Clavis0** [comment]
and, FWIW, I don't have any clue how to reopen this....

**Comment by mholt** [comment]
Oh... now that you mention it, I do seem to remember something about it. You sent it to my personal inbox, and I can't find it there anymore. I think the files that I downloaded were lost when I replaced my crashed computer recently. Sorry.

I think the best way to fix this will be if you can just post the hex-encoded bytes here on GitHub so they won't get lost. (I can't afford to offer free support out of my personal email inbox anyway. It's gotta be public.)

**Comment by Clavis0** [comment]
well, I answered to notifications@github, because the mail claimed that was a way to do it.  Apparently their mechanism to append email answers to tickets is faulty.

Anyway - here we go:

Date: Tue, 13 Feb 2018 23:14:06 +0100
To: Matt Holt <notifications@github.com>

> The exact TLS ClientHello bytes (hex-encoded is preferred)

From Wireshark, Copied via right-click on "TLSv1.2 Record Layer: Handshake
Protocol: Client Hello" -> "Copy" -> "Bytes as Hex and ASCII Dump"

0000   16 03 01 00 bf 01 00 00 bb 03 03 79 64 f6 3d 13  ...........yd.=.
0010   3b 61 f3 6e 4b a5 a6 f7 b6 33 02 68 69 44 31 4f  ;a.nK....3.hiD1O
0020   fc 41 a5 77 a4 8c 68 07 50 de ff 00 00 1e c0 2b  .A.w..h.P......+
0030   c0 2f cc a9 cc a8 c0 2c c0 30 c0 0a c0 09 c0 13  ./.....,.0......
0040   c0 14 00 33 00 39 00 2f 00 35 00 0a 01 00 00 74  ...3.9./.5.....t
0050   00 00 00 14 00 12 00 00 0f 63 61 64 64 79 73 65  .........caddyse
0060   72 76 65 72 2e 63 6f 6d 00 17 00 00 ff 01 00 01  rver.com........
0070   00 00 0a 00 0a 00 08 00 1d 00 17 00 18 00 19 00  ................
0080   0b 00 02 01 00 00 23 00 00 00 10 00 0e 00 0c 02  ......#.........
0090   68 32 08 68 74 74 70 2f 31 2e 31 00 05 00 05 01  h2.http/1.1.....
00a0   00 00 00 00 ff 03 00 00 00 0d 00 18 00 16 04 03  ................
00b0   05 03 06 03 08 04 08 05 08 06 04 01 05 01 06 01  ................
00c0   02 03 02 01                                      ....

> The exact User-Agent string
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

> Your OS and platform and environment information (should be in UA, I know,
>>but I need to know anything else relevant to your system)

Windows 7, 64bit, SP1, fully patched

> Some convincing verification that your connection is not, in fact, being intercepted

Well ... "convincing" is a big word. I can offer 2 approaches:

1.a the same page says it is likely not intercepted on Chrome
1.b The sha1 fingerprint of the caddyserver.com certificate  on Chrome and Firefox are the same
1.c From that I conclude Firefox is not intercepted as well

2.a the sha1-fingerprint of the caddyserver.com certificate is

    63:0E:D2:0C:AE:FA:E4:F1:27:9B:64:5A:A6:33:9A:57:13:78:D2:25

Its serial is 03:BF:C8:DB:01:29:E3:D8:1E:77:96:73:10:EF:BA:63:84:70, its
issuing date is Sun Dec 17th, 2017, and its expiry date is Sat March 17th, 2018.

You can compare that to the certificate presented via a known good connection.
If the certificates match, you might assume I get the correct certificate and thus
my connection is not effectively intercepted as well.

Of course, both methods assume that I do not intentionally lie to you,
that I am capable of retrieving those numbers correctly, and that my OS and
Browser are not thoroughly enough corrupted  to present those numbers to
me falsely.
(for a more fundamental discussion of that same question you might check
Ken Thompson's famous 1984 ACM Turing Award Lecture "Reflections on
Trusting Trust ")

Anyway ... hope this helps

Regards

Chris

**Comment by mholt** [comment]
Thanks for re-posting it here. I'll take a look!

**Comment by theodesp** [comment]
I've used both the latest

https://download.mozilla.org/?product=firefox-esr-latest-ssl&os=osx&lang=en-GB
and v60 of Firefox Esr

https://download.mozilla.org/?product=firefox-60.0.2esr-SSL&os=osx&lang=en-GB

but I couldn't reproduce that issue.

See attached screenshot.

@Clavis0 Can you try downloading the latest versions above?

![screen shot 2018-06-11 at 16 11 37](https://user-images.githubusercontent.com/328805/41240389-4b0acd7a-6d92-11e8-82de-135452648ce6.png)

**Comment by magikstm** [comment]
I tested with Firefox 60.5 ESR on Windows 7 x64 and couldn't reproduce this issue.

This issue may have been related to a difference in the proxy settings between Firefox and Chrome. Chrome uses system settings on Windows unless these are overridden while Firefox has it's own.

I'll close this issue for inactivity.

**Comment by Clavis0** [comment]
> I'll close this issue for inactivity.
No objections here, as I can't currently test anyway - I'm still on the latest 52.x esr which is eol since october '18.
