### ISSUE TITLE
500 error with {{.Files}} template action

### ISSUE THREAD

**Issue by Cinerar** [mholt/caddy#2026]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?

List files in a directory

### 3. What is your entire Caddyfile?
```
 http://0.0.0.0
{
    templates
}
```
Template file files.txt
```
{{.Files}}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Tried windows and linux versions, behavior is the same

### 5. Please paste any relevant HTTP request(s) here.
```
curl 127.0.0.1/files.txt
```

### 6. What did you expect to see?
list of files

### 7. What did you see instead (give full error messages and/or log)?
500 Internal Server Error

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Follow steps 1 to 7

**Comment by mholt** [comment]
You need to use `errors` directive to see the error details. Then make sure you're using .Files correctly: http://localhost:2015/docs/template-actions -- it requires an argument, the directory to scan. Then you have to iterate through the values with range.
