### ISSUE TITLE
Markdown parsing problem with use of underscores in links

### ISSUE THREAD

**Issue by mottosso** [mholt/caddy#2030]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.7

### 2. What are you trying to do?

Use underscores in a Markdown link directive, e.g. `[MY_LINK](https://google.com)`

### 3. What is your entire Caddyfile?
```text
markdown /
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```bash
caddy
```

### 6. What did you expect to see?

This is possibly a markdown parsing error, for which a [link_like_this](https://google.com) is meant to produce the link you see here on GitHub.

### 7. What did you see instead (give full error messages and/or log)?

Instead, it produces a [link*like*this](https://google.com) (note the italic "this" due to the surrounding underscores).

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Any link with this syntax should do.

```bash
[link_like_this](https://google.com)
```

**Comment by magikstm** [comment]
Try escaping the `"_"` with `"\"`:
`[link\_like\_this](https://google.com)`

I tested and it works with version 0.10.10.

**Comment by mottosso** [comment]
Thanks, that works for me as well. I had previously used backtick like this [`link_like_this`]() which works as well.

I would still consider this a bug though.

**Comment by magikstm** [comment]
Caddy uses blackfriday as the markdown parser:
https://github.com/russross/blackfriday

Specs are vague with this behavior:
http://commonmark.org/

This one doesn't have this behavior:
http://spec.commonmark.org/dingus/

This one does:
http://markdownlivepreview.com/

I'm unsure if it may be an issue or not. I would suggest creating an issue in that repo.

It has been discussed a bit here:
https://github.com/russross/blackfriday/issues/278

**Comment by mholt** [comment]
Hm, yeah, this seems to be a parser issue. I'm probably going to switch to blackfriday v2 for the next release of Caddy (after this week's release) so maybe that'll help address it. Either way, I think the upstream repo is the better place to discuss it. Thanks!
