### ISSUE TITLE
Remove deprecated startup/shutdown directives

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#2031]
Now that `startup` and `shutdown` have been replaced by `on` and have not been documented for some time, let's remove those directives completely (AFTER the 0.10.11 release).

We can remove this folder then: https://github.com/mholt/caddy/tree/master/startupshutdown

Eldin, would you like to submit a PR for this when you have a chance in the next couple weeks?

**Comment by elcore** [comment]
@mholt Sure :)
