### ISSUE TITLE
Wrong version info with 0.10.11

### ISSUE THREAD

**Issue by Remonli** [mholt/caddy#2036]
$ ./caddy -version
Caddy (untracked dev build) (unofficial)

This was downloaded from https://github.com/mholt/caddy/releases.

**Comment by centminmod** [comment]
Yeah getting the same with building my own Caddy binaries using GCC 7.2.1, GCC 4.8.5 and Clang 4.0.1

```
/usr/local/bin/caddy -version
Caddy 0.10.10 (+106d62b Tue Feb 20 20:04:26 UTC 2018) (unofficial)
2 files changed, 52 insertions(+)
caddy/caddymain/run.go
caddyhttp/httpserver/plugin.go

/usr/local/bin/caddy-gcc7 -version
Caddy 0.10.10 (+106d62b Tue Feb 20 20:04:58 UTC 2018) (unofficial)
2 files changed, 52 insertions(+)
caddy/caddymain/run.go
caddyhttp/httpserver/plugin.go

/usr/local/bin/caddy-clang4 -version
Caddy 0.10.10 (+106d62b Tue Feb 20 20:05:31 UTC 2018) (unofficial)
2 files changed, 52 insertions(+)
caddy/caddymain/run.go
caddyhttp/httpserver/plugin.go
```

/usr/local/bin/caddy -plugins
Server types:
  http

Caddyfile loaders:
  short
  flag
  default

Other plugins:
  http.authz
  http.awses
  http.awslambda
  http.basicauth
  http.bind
  http.browse
  http.cache
  http.cgi
  http.cors
  http.datadog
  http.errors
  http.expires
  http.expvar
  http.ext
  http.fastcgi
  http.filemanager
  http.filter
  http.forwardproxy
  http.git
  http.gopkg
  http.gzip
  http.header
  http.hugo
  http.index
  http.internal
  http.ipfilter
  http.jekyll
  http.jsonp
  http.jwt
  http.limits
  http.locale
  http.log
  http.login
  http.mailout
  http.markdown
  http.mime
  http.minify
  http.multipass
  http.nobots
  http.oauth
  http.pprof
  http.prometheus
  http.proxy
  http.proxyprotocol
  http.push
  http.ratelimit
  http.realip
  http.reauth
  http.redir
  http.request_id
  http.restic
  http.rewrite
  http.root
  http.search
  http.status
  http.templates
  http.timeouts
  http.upload
  http.webdav
  http.websocket
  on
  shutdown
  startup
  tls
  tls.dns.azure
  tls.dns.cloudflare
  tls.dns.digitalocean
  tls.dns.dnsmadeeasy
  tls.dns.dyn
  tls.dns.godaddy
  tls.dns.googlecloud
  tls.dns.linode
  tls.dns.namecheap
  tls.dns.ns1
  tls.dns.ovh
  tls.dns.powerdns
  tls.dns.rackspace
  tls.dns.route53
  tls.dns.vultr
  tls.storage.file
```

**Comment by centminmod** [comment]
ah forgot to pull latest from master https://caddy.community/t/wrong-version-number-in-0-10-11/3376/3

**Comment by mholt** [comment]
I've been investigating this and honestly, I'm baffled. `go run build.go` (in the caddy subfolder of this repo) embeds the proper version information into the resulting binary, and the releaser program I use to release new versions uses the same code as the production build worker, which AFAICT, works properly -- did something change in Go 1.10? Maybe a bug? Because I haven't changed anything here. I'm trying to figure out what makes this case different, but so far, no luck.

**Comment by Remonli** [comment]
@mholt  The version download from [https://caddyserver.com/download/windows/amd64?license=personal](url) works well , FYI

**Comment by mholt** [comment]
Yeah, the build server (fortunately) works correctly! It just doesn't work locally, which is very strange. I'll look at it again today but I won't let it delay the release tomorrow.

**Comment by elcore** [comment]
I cannot confirm this

**Comment by mholt** [comment]
Narrowed this down to one thing; using `-ldflags` in `go build` doesn't work anymore if the GOPATH is a temporary folder (e.g. `/var/folders/d4/3d8k5bgd62v9h2c5f05xkyx80000gn/T/gopath_03-26-1231.918262153`) but it DOES work if the GOPATH is my usual working GOPATH. I'm frankly not sure why it cares.

**Comment by mholt** [comment]
Meh. Hacked in a fix for darwin builds of the build server so that the temporary directory is in the current folder instead of the system's temporary folder location specified by `$TMPDIR`. The next release will have proper version information. Thanks again for the report. I hated this, haha. 😛

**Comment by mholt** [comment]
Damian Gryski in the Gophers slack and Brad Fitzpatrick on Twitter both helped figure out the cause. I don't fully understand this, but... apparently `$TMPDIR` is inside `/var` and `/var` is a symlink to `/private/var` which is mounted with `noexec`:

```bash
$ mount | grep private
/dev/disk1s4 on /private/var/vm (apfs, local, noexec, journaled, noatime, nobrowse)
```

Now, I have no idea why `go build` works in there but the `-ldflags` part doesn't, but I'm satisfied with just putting the temporary dir in some other place on Mac. Oh well.

Weird bug.

Disappointing breaking change in High Sierra.
