### ISSUE TITLE
Caddy 0.10.11 builds fails with status code 500

### ISSUE THREAD

**Issue by klingtnet** [mholt/caddy#2040]
Builds for caddy 0.10.11—with many but not all plugins—fail with status code 500:

How to reproduce:
```sh
$ curl 'https://caddyserver.com/download/linux/386?plugins=http.hugo%2Chttp.upload%2Ctls.dns.cloudflare%2Chttp.awses%2Chttp.jekyll%2Chttp.mailout%2Ctls.dns.otc%2Ctls.dns.ns1%2Chttp.webdav%2Chttp.locale%2Chttp.minify%2Chttp.expires%2Ctls.dns.azure%2Ctls.dns.dnsmadeeasy%2Ctls.dns.cloudxns%2Chttp.restic%2Chttp.realip%2Cdns%2Chttp.datadog%2Ctls.dns.auroradns%2Ctls.dns.exoscale%2Ctls.dns.gandi%2Ctls.dns.googlecloud%2Ctls.dns.dnsimple%2Ctls.dns.route53%2Ctls.dns.lightsail%2Chttp.cors%2Ctls.dns.linode%2Cnet%2Ctls.dns.gandiv5%2Ctls.dns.godaddy%2Ctls.dns.namecheap%2Ctls.dns.vultr%2Chttp.nobots%2Ctls.dns.dnspod%2Chttp.awslambda%2Ctls.dns.rfc2136%2Cdyndns%2Chttp.git%2Chttp.authz%2Chttp.login%2Chttp.cgi%2Ctls.dns.digitalocean%2Chttp.gopkg%2Ctls.dns.dyn%2Ctls.dns.powerdns%2Chttp.jwt%2Chttp.filter%2Chttp.proxyprotocol%2Chttp.ratelimit%2Chttp.cache%2Chttp.prometheus%2Ctls.dns.rackspace%2Chttp.ipfilter%2Ctls.dns.ovh%2Chttp.reauth%2Chttp.filemanager%2Chttp.forwardproxy'
provisioning build environment: git fetch {github.com/caddyserver/dnsproviders/cloudxns v0.1.2 https://github.com/caddyserver/dnsproviders.git}: fork/exec /usr/bin/git: no such file or directory
```

It does not matter which architecture you use, i.e. `amd64` and `arm` builds fail with them same message.

**Comment by klingtnet** [comment]
A link to the [broken CI run](https://circleci.com/gh/klingtnet/caddy-release-downloader/68) where I build caddy for the AUR package [caddy-full-bin](https://aur.archlinux.org/packages/caddy-full-bin).

**Comment by mholt** [comment]
It seems some plugins are currently incompatible with this version of Caddy; I'll reach out to the devs and see if I can get them to release an update, since I think most of them have already pushed the necessary changes. They just need to go to the site. Thanks!

**Comment by klingtnet** [comment]
Unfortunately, it is still broken https://circleci.com/gh/klingtnet/caddy-release-downloader/71. Do you have any idea which plugin could be the problematic one?

**Comment by mholt** [comment]
I would if I ssh'ed in to check the logs. However I am currently mobile with limited connectivity so I am not able to do that at the moment, sorry. I'll try to do so as soon as I'm back on my home continent!

**Comment by klingtnet** [comment]
Any news on this? The problem still persits.

**Comment by geek1011** [comment]
It's the DNS plugins. I had the same issue.

**Comment by klingtnet** [comment]
@geek1011 Thank you very much, I can confirm that the `dns` plugin (server type) breaks the build.

**Comment by geek1011** [comment]
@geek1011 No problem! It took me quite a while to test everything. Maybe if @mholt made the build server automatically test a build with each plugin and showed something saying it's broken on the download page?

**Comment by klingtnet** [comment]
I have to omit all plugins starting with `tls.dns` and the `dns` plugin to build caddy.

**Comment by mholt** [comment]
It only fails if the `dns` plugin is selected, as far as I can tell. @miekg just has to do a new release sometime.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Caddy 0.10.11 bui..." ]
>It only fails if the `dns` plugin is selected, as far as I can tell. @miekg just has to do a new release sometime.

I tried, it failed :-( I gave up after that.

**Comment by mholt** [comment]
I would love to help you fix it, rather than just leaving it broken. :)

**Comment by geek1011** [comment]
Hmm. I did some more testing and found something unusual: If you select ` tls.dns.rfc2136` along with either `tls.dns.route53` or `tls.dns.vultr`, the build breaks. Maybe conflicting vendored dependencies?

**Comment by mholt** [comment]
I will look into it again by checking the logs after the Caddy release tomorrow. (Plugins can be released whenever.)
