### ISSUE TITLE
quic is not used over caddy 0.10.11

### ISSUE THREAD

**Issue by BaoZhihong** [mholt/caddy#2049]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.11

### 2. What are you trying to do?
 I want to see quic 

### 3. What is your entire Caddyfile?
quic.com:443 quic:443 {
        tls self_signed
        root /root/Desktop/test_web/
        log /var/log/access.log
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -quic -conf /root/Desktop/Caddyfile

### 5. Please paste any relevant HTTP request(s) here.
request:
:authority: www.quic.com
:method: GET
:path: /test1/js/plugins.js
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9
cache-control: no-cache
pragma: no-cache
referer: https://www.quic.com/test1/
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3356.0 Safari/537.36

response:
accept-ranges: bytes
alt-svc: quic=":443"; ma=2592000; v="39"
content-length: 2817
content-type: application/javascript
date: Wed, 28 Feb 2018 03:38:16 GMT
etag: "olqz82269"
last-modified: Tue, 21 Feb 2017 23:14:26 GMT
server: Caddy
status: 200

### 6. What did you expect to see?
I want to see the connection use quic but now is like follow:
The connection to this site is encrypted and authenticated using TLS 1.2 (a strong protocol), ECDHE_ECDSA with X25519 (a strong key exchange), and AES_256_GCM (a strong cipher).

### 7. What did you see instead (give full error messages and/or log)?
the only error I can find is 
Certificate - missing
This site is missing a valid, trusted certificate 
(net::ERR_CERT_AUTHORITY_INVALID).

before I use 0.10.10 ,and I meet the same problem even if I use --quic-version=QUIC_VERSION_38 to start chrome ,now I use 0.10.11,but it still did not use quic

**Comment by elcore** [comment]
QUIC requires a valid/signed certificate

**Comment by BaoZhihong** [comment]
where is the certificate of caddy Self-Signed，I want to install in brrowser to trust ,I dont have me own donaim,thanks a lot

**Comment by elcore** [comment]
Caddy stores the self signed certificate in memory, you'll have to generate your own certificate https://caddyserver.com/docs/tls
