### ISSUE TITLE
Configurable reverse proxy timeout

### ISSUE THREAD

**Issue by fishnux** [mholt/caddy#2050]
```
proxy / 8.8.8.8 backend1.local
```
In a real-world scenario, 8.8.8.8 would represent an offline server (i.e.: no HTTP connection, complete packet loss).
If you load balance between those two servers, the client may hang for about 30 seconds before Caddy returns "502 Bad Gateway" (because, obviously, the backend 8.8.8.8 is offline).
Currently there's no way to configure this reverse proxy timeout, it's hard-coded here:
https://github.com/mholt/caddy/blob/5552dcbbc7f630ada7c7d030b37c2efdce750ace/caddyhttp/proxy/reverseproxy.go#L49
It would be nice to be able to configure this timeout in Caddyfile.

**Comment by francislavoie** [comment]
You could use `health_check` and `health_check_timeout` for now (if you're proxying to an HTTP service)

**Comment by tchaudhry91** [comment]
Hi, I'd like to try and implement this. 
is this something like what we're looking for?
```
proxy / 8.8.8.8 backend1.local {
    timeout 10
}
```

**Comment by mholt** [comment]
LGTM! Feel free to submit a PR. :)

**Comment by tchaudhry91** [comment]
PR here:
https://github.com/mholt/caddy/pull/2070
I'm still new to this, so looking for a bit of validation there before I finalize it.
Thanks

**Comment by tchaudhry91** [comment]
Merged. https://github.com/mholt/caddy/pull/2070
Can be closed.
