### ISSUE TITLE
After dns challenge, dns record stops working

### ISSUE THREAD

**Issue by CWRau** [mholt/caddy#2051]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.11 (non-commercial use only)

### 2. What are you trying to do?
Automatic SSL certificates with namecheap dns challenge.

### 3. What is your entire Caddyfile?
```text
import conf.d/*
```
conf.d/chat
```text
chat.cwrcoding.com {
    proxy / localhost:1519 {
        transparent
        websocket
    }

    import ../ssl.conf
}
```

ssl.conf
```text
tls admin@cwrcoding.com {
    protocols tls1.2
    key_type p384
    dns namecheap
    must_staple
}

tls admin@cwrcoding.com {
    protocols tls1.2
    key_type rsa4096
    dns namecheap
    must_staple
}

header / Strict-Transport-Security 'max-age=63072000; includeSubDomains;      preload'
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -log stdout
inside docker

Dockerfile
```text
FROM alpine
LABEL maintainer="CWRau"

ARG plugins=tls.dns.namecheap

RUN apk add --no-cache tar curl

RUN curl --silent --show-error --fail --location --header "Accept: application/tar+gzip, application/x-gzip, application/octet-stream" -o - \
      "https://caddyserver.com/download/linux/amd64?plugins=${plugins}" \
    | tar --no-same-owner -C /usr/bin/ -xz caddy && \
    chmod 0755 /usr/bin/caddy && \
    /usr/bin/caddy -version

EXPOSE 80 443
WORKDIR /caddy

CMD ["caddy", "-log", "stdout"]
```

### 6. What did you expect to see?
Certificate request and then a working site

### 7. What did you see instead (give full error messages and/or log)?
The certificate got requested correctly, but after that the dns record for the website (chat.cwrcoding.com) stops working. I verified it with `nslookup chat.cwrcoding.com dns1.registrar-servers.com`
This happened before with rancher.cwrcoding.com, which I then resetted via namecheap support.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Minimal Caddyfile like 'conf.d/chat' merged with 'ssl.conf', used together with namecheap API credentials

I'm willing to do any tests with namecheap API, if it helps.

My dns records are wildcard records. After the challenge every subdomain works, except the one used for the challenge.

**Comment by mholt** [comment]
Hmm, this looks like a bug in the integration for namecheap's API. Could you post this issue instead at https://github.com/xenolf/lego and maybe tag the contributor of the namecheap package there? That will ensure the best people can work on a fix for it. Thanks!
