### ISSUE TITLE
Caddy not finding index.html

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [mholt/caddy#2056]
I'm trying to create the most basic demo caddy server via an AWS userdata script. caddy runs, but I always get a `404 Not Found` error. It doesn't seem to find the index page.

```
#!/bin/bash
cd /tmp
curl https://getcaddy.com | bash -s personal
sudo touch /usr/local/bin/index.html
echo '<!DOCTYPE html>
<html>
<head>
<title>Test Page</title>
</head>
<body>
<h1>Test Page...< /h1>
</body>
</html>
' | sudo tee -a /usr/local/bin/index.html
/usr/local/bin/caddy
```

Caddy Version: **Caddy 0.10.11**
AWS AMI: **Amazon Linux AMI 2017.09.1 (HVM), SSD Volume Type - ami-403e2524 t2.micro**

**Comment by francislavoie** [comment]
Caddy will look in your current dir, i.e. `/tmp`, not in the directory of the Caddy executable.
