### ISSUE TITLE
missing vendored lib ?

### ISSUE THREAD

**Issue by gedw99** [mholt/caddy#2057]
Running tool: /usr/local/opt/go/libexec/bin/go test -timeout 30s github.com/mholt/caddy/caddyhttp/httpserver -run ^TestConditions$

# github.com/mholt/caddy/caddyhttp/httpserver
logger_test.go:29:2: cannot find package "gopkg.in/mcuadros/go-syslog.v2" in any of:
	/Users/apple/workspace/go/src/github.com/mholt/caddy/vendor/gopkg.in/mcuadros/go-syslog.v2 (vendor tree)
	/usr/local/opt/go/libexec/src/gopkg.in/mcuadros/go-syslog.v2 (from $GOROOT)
	/Users/apple/workspace/go/src/gopkg.in/mcuadros/go-syslog.v2 (from $GOPATH)
FAIL	github.com/mholt/caddy/caddyhttp/httpserver [setup failed]
Error: Tests failed.

### 1. What version of Caddy are you using (`caddy -version`)?

latest go get

### 2. What are you trying to do?

compile 

### 3. What is your entire Caddyfile?

none

### 4. How did you run Caddy (give the full command and describe the execution environment)?

from VSCode

### 6. What did you expect to see?

Compiling with no errors

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

go get github.com/mholt/caddy
code $(GOPATH)/src/github.com/mholt/caddy
go test ./...

**Comment by mholt** [comment]
Thanks for the report! We don't vendor test dependencies because they tend to get out of hand down the dependency tree AND they aren't required for compilation -- what you're actually trying to do is run tests, which is a good time to expose missing libraries.
