### ISSUE TITLE
Headers containing JSON

### ISSUE THREAD

**Issue by Gunni** [mholt/caddy#2063]
https://caddy.community/t/header-containing-json/3468

### 1. What version of Caddy are you using (`caddy -version`)?
`Caddy 0.10.11 (unofficial)` from fedora `caddy-0.10.11-1.fc27.src.rpm`

### 2. What are you trying to do?
Add the following header:
`Report-To "{'url': 'https://example.com/csp/enforce', 'group': 'example-com-csp-enforce', 'max-age': 3600}"`

### 3. What is your entire Caddyfile?
I'm not willing to post the entire thing, but here is the relevant part:

    example.com {
        header / {
            Report-To "{'url': 'https://example.com/csp/enforce', 'group': 'example-com-csp-enforce', 'max-age': 3600}"
        }
    }

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`/usr/bin/caddy -conf /etc/caddy/caddy.conf -log stdout -root /tmp -quic -agree`

### 5. Please paste any relevant HTTP request(s) here.
`curl --http2 --http2-prior-knowledge --head https://example.com`

```
HTTP/2 200
accept-ranges: bytes
access-control-allow-origin: null
alt-svc: quic=":443"; ma=2592000; v="39"
content-security-policy: default-src 'none'; style-src 'self'; font-src 'self'; img-src 'self'; manifest-src 'self'; frame-ancestors 'none'; form-action 'none'; upgrade-insecure-requests; block-all-mixed-content; sandbox; require-sri-for script style; disown-opener; base-uri 'none'; report-uri 'https://example.com/csp/enforce'; report-to example-com-csp-enforce;
content-type: text/html; charset=utf-8
etag: "xxxxxxxxx"
expect-ct: max-age=60, enforce, report-uri=https://example.com/ct/enforce
expect-staple: max-age=3600; includeSubDomains; report-uri=https://example.com/staple/reportOnly
last-modified: Wed, 07 Mar 2018 02:30:38 GMT
referrer-policy: no-referrer
report-to:
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
content-length: 0
date: Mon, 12 Mar 2018 03:22:05 GMT
```

### 6. What did you expect to see?
The `report-to` header should contain the provided json dict.

### 7. What did you see instead (give full error messages and/or log)?
The `report-to` has an empty value.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
On any vhost, add a header contining a value with a json dict, example: 

    example.com {
        header / {
            Report-To "{'a': '1', 'b': '2'}"
        }
    }

### 9. Cause
I believe the [placeholders](https://caddyserver.com/docs/placeholders) feature is the cause.

It gets called for adding headers [here](https://github.com/mholt/caddy/blob/master/caddyhttp/header/header.go#L56).

[This](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L145) function performs the replacement using [this](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L211) piece of code and since my "key" does not match anything, it replaces my "placeholder" with [r.emptyValue](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L380).

And finally [this part](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L173) removes the matched `{ ... }` section.

### 10. Suggested fix
Add a way for users to put in "raw" headers without additional processing, or even better, allow us to "escape" the `{ ... }` around keys, for example using `\{` and `\}`, so that the replacer does not match on them. That can probably be done [here](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/replacer.go#L147).

**Comment by Whitestrake** [comment]
I like escaping `{}` like we already allow for `"`. Thanks for the issue, @Gunni!

**Comment by Whitestrake** [comment]
Looking into implementing this. Disclaimer: I'm a less-experienced Go coder.

The first thing I noted is that it seems like it'd probably be ludicrously simple, actually, to provide a flag along the lines of `+` and `-` to signal the `header` directive's `Handler` not to run the `Replacer` at all, effectively adding the value exactly as provided. Maybe three extra lines. That would of course only affect `header`, whereas changing the `Replacer` itself to support escaping would be universal.

As for the escaping option... Now, I haven't done much string parsing with respect to escaping, so there might be a better way to do it, but my thoughts were along these lines:

1. Leave the loop `break` tests as-is, i.e. proceed only if we have an opening and a closing brace
2. Test for `idxStart > 0 && idxStart-1 == strings.Index(s, "\\{")` (the opening brace is escaped) and for `idxEnd-1 == strings.Index(s, "\\}")` (the closing brace is escaped)
3. If either is true:
a. Instead executing `getSubstitution`, simply strip out the escape characters
b. Append prefix + un-escaped placeholder directly to `result`
c. Strip out `s` all the way to `idxEnd+1` as normal and continue the loop

Didn't want to make a PR or anything just yet in case I'm missing something obvious or there's a much better way about it.

**Comment by Gunni** [comment]
Hey, the problem with that might be the following example:

    X-Json-Hostname "\{ 'hostname': '{hostname}' \}"

The replacer could be run on the values inside to solve that.

**Comment by Whitestrake** [comment]
I don't believe this can ever occur with the existing implementation. Currently the Replacer searches for the first opening brace, else it breaks the loop; then it searches for the first closing brace after the opening brace, else it breaks the loop. That means, in your example, the first placeholder would be ` 'hostname': '{hostname` and it would be substituted by the `emptyValue`, becoming `"\' \}"`.

Perhaps the Replacer loop should be reworked entirely?
