### ISSUE TITLE
[Documentation] RenewDurationBefore not documented

### ISSUE THREAD

**Issue by root360-AndreasUlm** [mholt/caddy#2064]
Hi,

I just searched for the time period when caddy starts the renewal process for on-demand certificates.
In the code I found the variable 'RenewDurationBefore' defined in 'caddytls/maintain.go'.
That with this definition I could calculate the renewal time (about 30 days before expire time).

It would be nice if the documentation of the tls-directive would specify this time.
That way you don't have to search the code to find the renewal time.

Regards,
Andreas

**Comment by mholt** [comment]
I've added that information to https://caddyserver.com/docs/automatic-https#renewing-certificates -- it will be live on the next update of the site. Thanks!
