### ISSUE TITLE
Some progress on "dep" for loading Caddy dependencies; but possible "filebrowser" bug

### ISSUE THREAD

**Issue by unquietwiki** [mholt/caddy#2069]
I'm trying to make a build of the latest Caddy, using go 1.10 + some plugins. It seems like an ["official"](https://about.sourcegraph.com/go/the-new-era-of-go-package-management/) way of handling dependencies came out in the past year/two, and I was able to figure out how to leverage that. At least one error remains thus far. I tried using an override to have it load [Archiver](https://github.com/mholt/archiver) 1.2, instead of 2.0; that made it worse, not better.

Procedure; used [this plugins list](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go) for reference

<code>

curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

go get github.com/mholt/caddy/caddy && go get github.com/caddyserver/builds

cd $GOPATH/src/github.com/mholt/caddy/caddy

nano caddymain/run.go // edit to add additional plugins

dep init

nano Gopkg.toml // edit to an override for github.com/russross/blackfriday version 1.5.1

dep ensure

go run build.go

</code>

**Error that remains after updating Gopkg.toml per https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md**

<code>

github.com/mholt/caddy/caddy/vendor/github.com/filebrowser/filebrowser/http

vendor/github.com/filebrowser/filebrowser/http/download.go:75:11: ar.Write undefined (type archiver.Archiver has no field or method Write)

</code>

**Comment by unquietwiki** [comment]
Not about the Filebrowser / Archiver bug, but rather versioning: it seems there's a bit of a fight going on, and folks (on Reddit at least) are balking at using dep, in favor of vgo.

https://research.swtch.com/vgo

**Comment by elcore** [comment]
Hi,

this seems to be an issue with `file browser`/vendoring. I kindly refer you to github.com/filebrowser/filebrowser or the Go Slack/IRC Channel.

> Not about the Filebrowser / Archiver bug, but rather versioning: it seems there's a bit of a fight going on, and folks (on Reddit at least) are balking at using dep, in favor of vgo.

This is out of context

**Comment by unquietwiki** [comment]
@elcore @francislavoie I reported the issue there, as directed. Thanks! https://github.com/filebrowser/filebrowser/issues/384
