### ISSUE TITLE
Contacting CA takes too much time, and it times out.

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [mholt/caddy#2077]
Recently I am experiencing an issue while contacting ACME for certificate renew.
[root@prod1 ~]# time curl https://acme-v01.api.letsencrypt.org/directory
{
  "B9GMAHh9hjQ": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-v01.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf"
  },
  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"
}
real	2m6.353s
user	0m0.086s
sys	0m0.082s

It takes more than 2 minutes, so Caddy timeouts doing that. I want to propose a config option that can configure timeout value on contacting CA. Thanks.

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.11 (non-commercial use only)

### 2. What are you trying to do?
Renew my TLS certificate from LetsEncrypt

### 3. What is your entire Caddyfile?
```text
(paste Caddyfile here)
oreon.feroko.com:443 {
proxy / localhost:3002
gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy

### 6. What did you expect to see?
Continue serving the site without an error.

### 7. What did you see instead (give full error messages and/or log)?
[root@prod1 ~]# ./caddy
Activating privacy features...2018/03/18 11:44:35 get directory at 'https://acme-v01.api.letsencrypt.org/directory': failed to get "https://acme-v01.api.letsencrypt.org/directory": Get https://acme-v01.api.letsencrypt.org/directory: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Maybe use some network hacking

**Comment by mholt** [comment]
Use the -catimeout CLI flag.
