### ISSUE TITLE
400 error with http challenge let's encrypt

### ISSUE THREAD

**Issue by MattMattV** [mholt/caddy#2086]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.12 (unofficial) (from https://github.com/abiosoft/caddy-docker)

### 2. What are you trying to do?
Serve multiple subdomains with automatic https (let's encrypt)

### 3. What is your entire Caddyfile?
```text
https://domain1.mydomain.com {
    gzip
    tls my@email.com {
        max_certs 10
    }
    proxy / container:3000 {
        transparent
    }
}

https://domain2.mydomain.com {
    gzip
    tls my@email.com {
        max_certs 10
    }
    proxy / container:80 {
        transparent
        websocket
    }
}

https://domain3.mydomain.com {
    gzip
    tls my@email.com {
        max_certs 10
    }
    proxy / container:2368 {
        transparent
        websocket
    }
}

https://domain4.mydomain.com {
    gzip
    tls my@email.com {
        max_certs 10
    }
    proxy / container:80 {
        transparent
    }
}

https://domain5.mydomain.com {
    gzip
    timeouts none

    tls my@email.com {
        max_certs 10
    }
}

https://domain6.mydomain.com {
    gzip
    tls my@email.com {
        max_certs 10
    }

    proxy / container:80 {
        transparent
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Launched Docker image via docker-compose (the full command is `/usr/bin/caddy --conf /etc/Caddyfile --log stdout`)

### 5. Please paste any relevant HTTP request(s) here.

a GET on any of my domains

### 6. What did you expect to see?

Proper proxy to my containers

### 7. What did you see instead (give full error messages and/or log)?
In browser : `ERR_SSL_PROTOCOL_ERROR`
In logs :
```
2018/03/27 14:29:19 [INFO] Obtaining new certificate for domain2.mydomain.com
2018/03/27 14:29:19 [INFO] acme: Registering account for my@email.com
2018/03/27 14:29:20 http: TLS handshake error from xxx.xxx.xxx.xxx:yyyy: registration error: acme: Error 400 - urn:ietf:params:acme:error:malformed - must agree to terms of service
2018/03/27 14:29:20 http: TLS handshake error from xxx.xxx.xxx.xxx:yyyy: domain2.mydomain.com: throttled; refusing to issue cert since last attempt on 2018-03-27 14:29:20.30311559 +0000 UTC m=+48.499206522 failed
```

**Comment by mholt** [comment]
Hi,

Good news, this is not a bug; you simply have to agree to the Let's Encrypt terms like the log message says: `must agree to terms of service`. So use the [`-agree` flag](https://caddyserver.com/docs/cli#agree) or run Caddy manually on the container first.

**Comment by MattMattV** [comment]
Thank you for your quick answer ! I'll try to submit a patch to the Docker image to prevent this issue.

Sorry to have wasted your time instead of having read manual...
