### ISSUE TITLE
Consider a 'catch-all' server block

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#209]
Another suggestion from @peterbourgon is to have a way to specify directives that apply to all server blocks declared in a Caddyfile. For lots of servers, using `import` isn't always practical.

The syntax of the Caddyfile forbids directives from appearing outside a server block, but we may be able to do define a special sever name that means its contents will be applied to all other servers. For example:

```
all {  # or maybe 'default' or '*'
    # directives here
}
```

I can see the value in this, however, I want to give this a lot of careful thought before going forward, if we do this. I don't want to choose a solution that paints us into a corner for possible future changes.

We would need to ensure that the behavior of all directives is consistent in how they handle repeated uses. Some may favor the first, others the last, and yet others may use all of them, depending on what they do.

**Comment by mbirth** [comment]
There needs to be a way to negate directives if we need a setting for all but one server.

But I'd love such a feature to be able to specify my email address (`tls <email>`) for all servers in one place in the Caddyfile instead of giving it as a parameter during startup.

**Comment by pwFoo** [comment]
Maybe a 'default' instead of a catch-all?
Could be a helpful feature.

**Comment by mholt** [comment]
FWIW, I'm not so hot about the idea of having to negate directives... in other words, allowing overlapping server blocks doesn't appeal to me. If they do overlap, only the most specific match should be used, not a mixture of them.

Thanks for the feedback so far! Closing this issue to funnel the discussion into #619.
