### ISSUE TITLE
RFE: tls cancel

### ISSUE THREAD

**Issue by henrypijames** [mholt/caddy#2090]
Caddy currently lacks the ability to reject certain HTTPS requests by cancelling the TLS handshake even before certificates are exchanged, which would be useful for security and efficiency reasons. Therefore, I propose a new syntax to the `tls` directive:

`tls cancel [error_code]`

It can be used like this:

```
https://www.example.com {
  # normal web host
  tls webmaster@example.com
}

https://ftp.example.com {
  # ftp.example.com has the same IP address as www.example.com
  # which Caddy is listening on, but it should reject HTTPS requests to this hostname
  tls cancel unrecognized_name
}

https://1.2.3.4 {
  # 1.2.3.4 is the IPv4 address of www.example.com which Caddy is listening on
  # but if should reject HTTPS request to this literal IP address as well
  tls cancel handshake_failure
  # note that this will also reject HTTPS requests meant for www.example.com or ftp.example.com
  # if the client does not use the Server Name Indication TLS extension for the handshake
  # because without SNI, Caddy has no way of knowing whether the client will be asking for
  # the literal IP address or a hostname afterwards
}
```

The implementation of `tls cancel` should conform to RFC 5246 (TLS 1.2) and RFC 6066 (TLS extensions). If `tls cancel` is defined for a host in the Caddyfile, Caddy should terminate the TLS handshake upon receiving `client_hello` by sending a (fatal) error alert with the specified `error_code`. If unspecified (default), the `error_code` should be either `unrecognized_name` (112) if the client has sent a valid SNI within its `client_hello`, or `handshake_failure` (40) if the client has sent no SNI or an invalid one.

I'm not sure whether additional error codes (as defined in the TLS standard) other than the two above should be allowed. Allowing them would give the user more flexibility, but would also make Caddy behave non-conforming to the standard.

**Comment by mholt** [comment]
Caddy 2 grants more control over the TLS handshake, making this kind of configuration possible through "connection policies."

**Comment by henrypijames** [comment]
Sorry, I read the docs but couldn't understand how `tls_conn_policies` is supposed to work, let alone how it could provide a solution to this RFE. Could you please give an example?

**Comment by mholt** [comment]
Ah, the `error_code` stuff is not yet implemented but what I mean is that the flexibility for this kind of config is now possible.

Except, I'm not quite sure that Go's crypto/tls package even exposes which TLS alert gets raised. However the Go 1.14 tree should be open to something like this, or at least semantics around the alerts you'd want: https://github.com/golang/go/issues/18377
