### ISSUE TITLE
Interactive prompting for agree to the terms

### ISSUE THREAD

**Issue by jfb** [mholt/caddy#2091]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.12 (non-commercial use only)

### 2. What are you trying to do?

run caddy with supervisor

### 3. What is your entire Caddyfile?
```text
*.xxoo.com
tls {
    dns cloudflare
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

supervisor config file

```
[program:caddy]
command= caddy -agree=true -conf caddy.conf  -email admin@xxoo.com
directory = /var/www/caddy/
```

### 7. What did you see instead (give full error messages and/or log)?

supervisor log

```
Activating privacy features...

Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Do you agree to the terms? (y/n):
```

**Comment by mholt** [comment]
Hi, I'm not sure what to do with this, since you didn't answer all the questions, so I'll close this issue.

**Comment by elcore** [comment]
Hi,

this should work:

`caddy --agree ....`
