### ISSUE TITLE
Don't allow root folder to be executable path.

### ISSUE THREAD

**Issue by pix64** [mholt/caddy#21]
It seems unwise to serve files from the same directory Caddy is running from.

* http://localhost:2015/caddy.exe downloads the server it self.
* CHANGES.txt and README.txt which are distributed with Caddy will also automatically be the in server root.
* Any backup or template caddyfiles will be public
* If plugins are added which would reside in a /plugin directory or such. They'll also be served by the server.

At the very least I think the default server root should be /root or something similar.

**Comment by abiosoft** [comment]
Caddy would ideally be installed as a binary available in `PATH` which makes it suited to be started in the directory to serve.

Regarding template files/plugin directory, I agree there needs to be more flexibility and I see that as something that can be achieved via Caddyfile.

**Comment by devil1591** [comment]
This is simply default configuration, you can create a Caddyfile with this directive:
`root www` and put your web in the www folder.

**Comment by mholt** [comment]
Caddy was designed to be able to serve a site that has the configuration file (Caddyfile) in it (it serves a 404 instead) and it has support for hiding other files as well. But I didn't intended for the caddy binary itself would literally be in the root of the site. Given that Caddy is (eventually) geared toward a less-technical crowd, that may be something to consider.

I have been spinning the idea around in my head of how to make a way to configure Caddy to hide any file using a `hide` directive, perhaps. Still not sure if it should be built into the core fileServer or if it should be a middleware. I also am wondering if it should be able to match simple patterns not just exact names/paths. (In either case, I agree it should be configurable.)

**Comment by mholt** [comment]
@pix64 Anything else on this? If so, feel free to comment or re-open with more details.

(I can move my own question about hiding files to a different issue.)
