### ISSUE TITLE
Caddy v0.10.12 cannot build/download with grpc plugin

### ISSUE THREAD

**Issue by bianbian-org** [mholt/caddy#2101]
### 1. What version of Caddy are you using (`caddy -version`)?
want to use v0.10.12

### 2. What are you trying to do?
download

### 3. What is your entire Caddyfile?
```text
(download failed)
```

### 5. Please paste any relevant HTTP request(s) here.

$ wget "https://caddyserver.com/download/darwin/amd64?license=personal"
--2018-03-30 08:38:42-- https://caddyserver.com/download/darwin/amd64?license=personal
Resolving caddyserver.com (caddyserver.com)... 138.68.240.78
Connecting to caddyserver.com (caddyserver.com)|138.68.240.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
...

$ wget "https://caddyserver.com/download/darwin/amd64?plugins=http.grpc&license=personal"
--2018-03-30 08:39:14-- https://caddyserver.com/download/darwin/amd64?plugins=http.grpc&license=personal
Resolving caddyserver.com (caddyserver.com)... 138.68.240.78
Connecting to caddyserver.com (caddyserver.com)|138.68.240.78|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2018-03-30 08:39:42 ERROR 500: Internal Server Error.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
download with selecting http.grpc plugin.

**Comment by mholt** [comment]
Hi, thanks for opening an issue with the template! This appears to be an issue with the grpc plugin, though, and you should open an issue in that repo instead.

For reference, the error in the backend is:

```
pieterlouw/caddy-grpc/server.go:45:54: cannot use director (type func("context".Context, string) (*grpc.ClientConn, error)) as type proxy.StreamDirector in argument to proxy.TransparentHandler
```

**Comment by scara** [comment]
Just for cross-reference: https://github.com/pieterlouw/caddy-grpc/issues/3
