### ISSUE TITLE
Unstable connectivity when acting as proxy to Jenkins backend

### ISSUE THREAD

**Issue by agrrh** [mholt/caddy#2102]
### 1. What version of Caddy are you using (`caddy -version`)?

`Caddy 0.10.12 (unofficial)`

Built with:

```
docker build -q https://github.com/abiosoft/caddy-docker.git \
--build-arg plugins=cache,cors,expires,filemanager,filter,forwardproxy,git,ipfilter,locale,minify,prometheus,ratelimit,realip,restic,upload
```

### 2. What are you trying to do?

Running proxy to Jenkins backend.

### 3. What is your entire Caddyfile?

```
# Caddyfile
import ./conf.d/*.conf

# conf.d/jenkins.conf
jenkins.example.tld {
  proxy / <jenkins-ip>:<jenkins-port> {
    transparent
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
docker run -d \
    --name caddy \
    --restart unless-stopped \
    --network host \
    -v /etc/localtime:/etc/localtime:ro \
    -v /etc/caddy:/etc/caddy:ro \
    -v /etc/ssl/caddy/.caddy:/root/.caddy \
    -v /var/www:/srv \
    -v /var/log/caddy:/var/log/caddy \
    -p 80:80 -p 443:443 -p 2015:2015 \
    registry.example.tld/caddy:latest \
    --conf /etc/caddy/Caddyfile --log stdout --email <email> --agree
```

### 5. Please paste any relevant HTTP request(s) here.

From time to time I face really slow response or 502 error:

```
$ http https://jenkins.example.tld
GET / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: jenkins.example.tld
User-Agent: HTTPie/0.9.9

HTTP/1.1 502 Bad Gateway
Content-Length: 16
Content-Type: text/plain; charset=utf-8
Date: Sun, 01 Apr 2018 11:02:16 GMT
Server: Caddy
X-Content-Type-Options: nosniff
```

### 6. What did you expect to see?

Expecting stable Jenkins connection.

### 7. What did you see instead (give full error messages and/or log)?

1 concurrent client, sending requests one after another:

```
HTTP/1.1 403   0.11 secs:     793 bytes ==> GET  /
HTTP/1.1 403   3.17 secs:     793 bytes ==> GET  /
--> HTTP/1.1 502  18.84 secs:      16 bytes ==> GET  /
HTTP/1.1 403   1.23 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.07 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.08 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.08 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.06 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.08 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.07 secs:     793 bytes ==> GET  /
-->  HTTP/1.1 403  15.59 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.07 secs:     793 bytes ==> GET  /
HTTP/1.1 403   0.07 secs:     793 bytes ==> GET  /
```

Notice 502 error and 15 seconds response. Issue is not present when using e.g. nginx/traefik, so I assume it's not Jenkins-related issue.

Another fact is that Jenkins answers with generic "Unauthorized" page, so I believe it don't produce much load.

Main reason I created this issue is #938 . It seems very similar and it's now impossible to set `max_fails 0`. The minimum possible value is `1`. Probably there was some changes which break things out.

I also tried `keepalive 0`, `max_fails 0` and `alpn http/1.1`, no luck.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

I just reproduced it with a brand new VPS:

- install docker ce: https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce-1
- run jenkins: `docker run -d -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts` 
- run caddy in docker with related config
- run `siege -c1 -v jenkins.example.tld`

Is there some more info I can provide you with?

**Comment by agrrh** [comment]
My bad!

I was mistakenly using `jenkins:latest` image in my deploy instead of `jenkins/jenkins:lts`. Moving containers to second one somehow resolved the issue.

Sorry for blaming precious Caddy server. In fact, I'm really happy to use it. Thanks, @mholt :)

**Comment by mholt** [comment]
Excellent, no problem - thank you!
