### ISSUE TITLE
caddy tries to create certificates with port number

### ISSUE THREAD

**Issue by ekle** [mholt/caddy#2103]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.10.12 (unofficial)

### 2. What are you trying to do?
some (broken?) clients send queries which contain a port-number in the hostname.
caddy tries to create certificates for mail.abc.org:443 which will fail because of the port-number.
caddy creates an empty folder for the certificate with port-number on disk.
there is also a folder for the correct certificate without port number.

/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/mail.abc.mobi:443 (empty)
/etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/mail.abc.mobi

likely caddy should strip the port-number before creating the certificates

### 3. logs:

```
Mär 30 11:28:27 proxy caddy[612]: 2018/03/30 11:28:27 [INFO] Obtaining new certificate for mail.abc.mobi:443
Mär 30 11:28:27 proxy caddy[612]: 2018/03/30 11:28:27 [INFO][mail.abc.mobi:443] acme: Obtaining bundled SAN certificate
Mär 30 11:28:28 proxy caddy[612]: 2018/03/30 11:28:28 [INFO][] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
Mär 30 11:28:28 proxy caddy[612]: 184.154.74.67 https mail.abc.mobi:443 "GET / HTTP/1.1" 301 20byte 0ms
Mär 30 11:28:29 proxy caddy[612]: 2018/03/30 11:28:29 [INFO] Obtaining new certificate for mail.abc.mobi:443
Mär 30 11:28:29 proxy caddy[612]: 2018/03/30 11:28:29 [INFO][mail.abc.mobi:443] acme: Obtaining bundled SAN certificate
Mär 30 11:28:30 proxy caddy[612]: 2018/03/30 11:28:30 [INFO][] Certificate written to disk: /etc/ssl/caddy/acme/acme-v02.api.letsencrypt.org/sites/.crt
```

**Comment by mholt** [comment]
Hi, thanks for the report, but you stripped away the issue template and unfortunately there's not enough information for me to be able to recreate the issue. :( I will have to close this, unless you edit your issue and answer all the questions on the issue template. Thanks.

**Comment by ekle** [comment]
### 3. What is your entire Caddyfile?
```* {
  log / stdout "{remote} {scheme} {host} \"{method} {uri} {proto}\" {status} {size}byte {latency_ms}ms"
  errors stdout
  proxy / 127.0.0.1:88 {
    transparent
  }
  tls root@ajnw.de {
    max_certs 500
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp -disable-tls-sni-challenge

### 5. Please paste any relevant HTTP request(s) here.

```
openssl s_client -servername mail.abc.mobi:443 -connect mail.abc.mobi:443
ONNECTED(00000003)
139860022331032:error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error:s23_clnt.c:769:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 334 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1522746903
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

### 6. What did you expect to see?

caddy uses the existing mail.abc.mobi cert

### 7. What did you see instead (give full error messages and/or log)?

caddy creates a folder for a cert with port number: `mail.abc.mobi:443` which is empty

i haven't found any more relevant log lines


### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

reproduction is quiet easy:
add a port number to the servername in an ssl-connect
`openssl s_client -servername mail.abc.mobi:443 -connect mail.abc.mobi:443`

**Comment by mholt** [comment]
Thanks. The empty folder/file issue was fixed in this commit: https://github.com/mholt/caddy/commit/73b61af58d31d88763c865ef85377eccf1b9bb22

As for the hostname, you won't be able to get a certificate for `mail.abc.mobi:443` because it contains a port, and only hostnames are supposed to be sent in the SNI extension (see RFC 3546). Send the hostname without the port as is described by the RFC and it will work correctly.

**Comment by ekle** [comment]
it would be cool if caddy could handle such broken clients, which send a port-number in SNI.

i have many such requests in my logs from various sources. (some broken web-crawlers maybe)

**Comment by mholt** [comment]
Actually, I believe that excusing broken clients will _not_ further Caddy's mission to make the Web better. I think it's better for the clients to be fixed. So, this is probably something I will not implement. Thanks for the request though!
