### ISSUE TITLE
Plugin deployment failure

### ISSUE THREAD

**Issue by 0xbaadf00d** [mholt/caddy#2106]
Hello,

We can't deploy new version of our plugin (id: MR5wbPDJu6) cause of Caddy error :

```
ok      github.com/mholt/caddy/caddyhttp/extensions     1.026s
ok      github.com/mholt/caddy/caddyhttp/fastcgi        1.111s
ok      github.com/mholt/caddy/caddyhttp/gzip   2.235s
ok      github.com/mholt/caddy/caddyhttp/header 1.019s
--- FAIL: TestHostname (0.03s)
        tplcontext_test.go:290: Test [0]: Expected hostname 1.1.1.1, found 1dot1dot1dot1.cloudflare-dns.com.
FAIL
FAIL    github.com/mholt/caddy/caddyhttp/httpserver     0.098s
ok      github.com/mholt/caddy/caddyhttp/index  1.044s
ok      github.com/mholt/caddy/caddyhttp/internalsrv    1.019s
ok      github.com/mholt/caddy/caddyhttp/limits 1.021s
```

**Comment by elcore** [comment]
Hi,

this has been fixed in https://github.com/mholt/caddy/commit/2966db7b7800e97fe8635e94dafc4ebad834c7e0

**Comment by mholt** [comment]
@0xbaadf00d Sorry for the error -- Cloudflare broke our tests unexpectedly 😏 -- I will do a release this week or early next week and then you will be able to release updates to your plugin. Again, sorry for the inconvenience, and thanks for maintaining your plugin!!

**Comment by 0xbaadf00d** [comment]
No problem, Thank you
