### ISSUE TITLE
rewrite except drops trailing / 

### ISSUE THREAD

**Issue by rstupek** [mholt/caddy#2107]
### 1. What version of Caddy are you using (`caddy -version`)?
latest version

Caddyfile

proxy / http://10.1.3.72 {
transparent
except /i/
}

The server will proxy requests to any url starting with /i when logically you would think it would only proxy such requests where the url starts with /i/

see discussion
https://caddy.community/t/rewrite-and-header-directives/3629

**Comment by tobya** [comment]
Hi @rstupek Thanks for the issue.  A little more detail here would be useful.  The forum issue is good for background if you were able to put the basics of the bug in the issue here.   Thanks.

**Comment by rstupek** [comment]
Caddyfile

proxy / http://10.1.3.72 {
transparent
except /i/
}

The server will proxy requests to any url starting with /i when logically you would think it would only proxy such requests where the url starts with /i/
