### ISSUE TITLE
Download caddy with few plugins fails

### ISSUE THREAD

**Issue by phob0s-pl** [mholt/caddy#2109]
### 1. What version of Caddy are you using (`caddy -version`)?
Lastest one

### 2. What are you trying to do?
Download caddy with few plugins

### 3. What is your entire Caddyfile?
n/a

### 4. How did you run Caddy (give the full command and describe the execution environment)?
n/a

### 5. Please paste any relevant HTTP request(s) here.
[https://caddyserver.com/download/linux/amd64?plugins=dns,http.filemanager,http.hugo&license=personal](https://caddyserver.com/download/linux/amd64?plugins=dns,http.filemanager,http.hugo&license=personal)

### 6. What did you expect to see?
Download will start successfully

### 7. What did you see instead (give full error messages and/or log)?
```
Webbrowser:
provisioning build environment: go get github.com/coredns/coredns/core: exit status 1
```
```
wget https://caddyserver.com/download/linux/amd64\?plugins\=dns,http.filemanager,http.hugo\&license\=personal
--2018-04-08 12:37:28--  https://caddyserver.com/download/linux/amd64?plugins=dns,http.filemanager,http.hugo&license=personal
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving caddyserver.com... 138.68.240.78, 2604:a880:2:d0::1145:e001
Connecting to caddyserver.com|138.68.240.78|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2018-04-08 12:37:37 ERROR 500: Internal Server Error.
```

With curl command:
```
curl https://getcaddy.com | bash -s personal dns,http.filemanager,http.hugo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7299  100  7299    0     0   7299      0  0:00:01 --:--:--  0:00:01  8128
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Trye download caddy with dns, filemanager and hugo.

**Comment by elcore** [comment]
Hello,

I kindly refer you to https://caddy.community, this isn't an issue with Caddy

**Comment by mholt** [comment]
Some plugins need to be updated by their maintainers for Caddy to build successfully with them included.
