### ISSUE TITLE
Plugin deploy fails

### ISSUE THREAD

**Issue by smancke** [mholt/caddy#2110]
Hi, the deployment of a new plugin version for loginsrv failes, because of a test error in `caddyhttp/httpserver`, when executed by the buildserver.

```
ok  	github.com/mholt/caddy/caddyhttp/gzip	2.190s
ok  	github.com/mholt/caddy/caddyhttp/header	1.022s
--- FAIL: TestHostname (0.03s)
	tplcontext_test.go:290: Test [0]: Expected hostname 1.1.1.1, found 1dot1dot1dot1.cloudflare-dns.com.
FAIL
FAIL	github.com/mholt/caddy/caddyhttp/httpserver	0.080s
ok  	github.com/mholt/caddy/caddyhttp/index	1.020s
```

When running the tests on my local machine, they pass.

**Comment by elcore** [comment]
Hi,

this has been fixed in https://github.com/mholt/caddy/commit/2966db7b7800e97fe8635e94dafc4ebad834c7e0, I recommend searching for an issue report before creating a new one!

**Comment by mholt** [comment]
Yeah, it'll be fixed on the build server when the next version of Caddy is released, sometime this week. Sorry for the trouble -- but thanks for maintaining your plugin!! Keep your eyes peeled for the release.
