### ISSUE TITLE
Cannot enable HTTPS for EC2 domain name

### ISSUE THREAD

**Issue by buckle2000** [mholt/caddy#2118]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.12 (non-commercial use only)

### 2. What are you trying to do?
Proxy a HTTP server

### 3. What is your entire Caddyfile?
```text
ec2-<IP address here>.compute-1.amazonaws.com

proxy /api localhost:9080
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Just `caddy`

### 5. Please paste any relevant HTTP request(s) here.
None. The server failed to start

### 6. What did you expect to see?
I want to server to start

### 7. What did you see instead (give full error messages and/or log)?
```
Activating privacy features... <TIME> open /home/ubuntu/.caddy/acme/acme-v02.api.letsencrypt.org/sites/ec2-<IP>.compute-1.amazonaws.com/ec2-<IP>.compute-1.amazonaws.com.crt: no such file or directory
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Just register an EC2 on AWS, install caddy, write the Caddyfile and run caddy.

**Comment by buckle2000** [comment]
If I change the domain name to `buckle2000.com` everything works fine.

**Comment by mholt** [comment]
Can you please run `caddy -log -ca https://acme-staging-v02.api.letsencrypt.org/directory` (use [the staging environment](https://letsencrypt.org/docs/staging-environment/) for testing!!!) and report the output of the log? I'm guessing LE can't verify your DNS.

**Comment by buckle2000** [comment]
It's likely not related to network.

**Comment by buckle2000** [comment]
```
$ caddy -log -ca https://acme-staging-v02.api.letsencrypt.org/directory
Error during parsing: Unknown directive 'https://acme-staging-v02.api.letsencrypt.org/directory'
```

**Comment by buckle2000** [comment]
```bash
$ caddy -log - -ca https://acme-staging-v02.api.letsencrypt.org/directory
Activating privacy features... 

Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf
Please enter your email address to signify agreement and to be notified
in case of issues. You can leave it blank, but we don't recommend it.
  Email address: 
<TIME> open /home/ubuntu/.caddy/acme/acme-v02.api.letsencrypt.org/sites/ec2-<IP>.compute-1.amazonaws.com/ec2-<IP>.compute-1.amazonaws.com.crt: no such file or directory
```

**Comment by mholt** [comment]
No... in fact it's already been fixed -- there's a bug in the underlying ACME package. https://github.com/mholt/caddy/commit/73b61af58d31d88763c865ef85377eccf1b9bb22#diff-ca5efc16a1b80256678f740af5f2647dR322

This usually happens when Let's Encrypt is unable to reach your server to verify you own the domain name. Make sure your network is configured properly and try again.

**Comment by mholt** [comment]
Okay. Well, the empty certificate file is fixed already, and will go out with the next release (soon).

**Comment by mholt** [comment]
We're pretty sure we've isolated the root cause of the bug in the upstream package, and are working on a fix, so a workaround won't be needed in Caddy anymore.

**Comment by mholt** [comment]
We're pretty sure we've isolated the root cause of the bug in the upstream package, and are working on a fix, so a workaround won't be needed in Caddy anymore.
