### ISSUE TITLE
Caddy: Support the s390x platform (update vendored github.com/lucas-clemente/aes12)

### ISSUE THREAD

**Issue by carlwgeorge** [mholt/caddy#2119]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy v0.10.12

### 2. What are you trying to do?

While packaging Caddy for Fedora, I haven't been able to get it to build on s390x.  For a long time I assumed it was something strange Fedora was doing to golang on that architecture and just excluded building for it.  However, once I got time to debug it, I found the problem.

### 3. What is your entire Caddyfile?
```text
n/a
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`n/a`

### 5. Please paste any relevant HTTP request(s) here.

`n/a`

### 6. What did you expect to see?

Successful build of Caddy

### 7. What did you see instead (give full error messages and/or log)?

`src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/aes12/cipher.go:36:9: undefined: newCipher`

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Build Caddy for the s390x platform

`env GOOS=linux GOARCH=s390x go build`

The [commit of github.com/lucas-clemente/aes12 that is vendored](https://github.com/mholt/caddy/blob/v0.10.12/vendor/manifest#L129-L134) has a [build tag to exclude the s390x architecture](https://github.com/lucas-clemente/aes12/blob/25700e67be5c860bcc999137275b9ef8b65932bd/cipher_generic.go#L5).  The literal [next commit removes that build tag](https://github.com/lucas-clemente/aes12/commit/2278c3bb5d33bb2676838161c8cc023e70d5d2d5).

**Comment by elcore** [comment]
Hello,

we (or rather Matt) regularly update vendored dependencies. 

Please be patient, in the meantime you can update it yourself

:smile:

**Comment by mholt** [comment]
Yeah, we update vendored dependencies before a release.

Although I think soon we should switch to updating them just after a release.

Will happen soon!

**Comment by carlwgeorge** [comment]
> regularly update vendored dependencies

Sorry, that doesn't seem to be the case.  github.com/lucas-clemente/aes12 hasn't been updated since [it was first commited](https://github.com/mholt/caddy/commit/6fde3632ef34ee205b3a89a2a594076742bb1024).  I count nine releases since then.

> you can update it yourself

I've already addressed the issue locally, the point of opening an issue was to let yall know about the problem.  To phrase it differently, Caddy fails to build on s390x architecture.  I don't want to rush yall, but can this issue be left open until the problem is resolved?

**Comment by elcore** [comment]
> Sorry, that doesn't seem to be the case. github.com/lucas-clemente/aes12 hasn't been updated since it was first commited. I count nine releases since then.

It seems there is an issue with the update process, thank you for pointing this out!

> I've already addressed the issue locally, the point of opening an issue was to let yall know about the problem. To phrase it differently, Caddy fails to build on s390x architecture. I don't want to rush yall, but can this issue be left open until the problem is resolved?

We are really thankful!!! I will rewrite this issue report into a feature request for further reference.

**Comment by carlwgeorge** [comment]
Sorry I didn't fill out the whole issue template at first, I had all those n/a's too and they made it seem like not a great fit.

**Comment by mholt** [comment]
Done in a674c0051a62615c9c1bba60719ba35d91de1852.
