### ISSUE TITLE
Wordpress HTTPS: Too many redirects

### ISSUE THREAD

**Issue by DenBeke** [mholt/caddy#212]
Something strange is happening when I try to enable HTTPS for Wordpress.
I installed all needed dependencies on a fresh FreeBSD installation. Compiled Caddy from source.

I installed Wordpress and then I tried to change site url from HTTP to HTTPS, which yields in a *"too many redirects"* error in the browser.

I have the most basic Caddyfile possible, which doesn't do any redirects. And in Wordpress both `SITE_URL` and home url are set to the HTTPS url of my site.

```
http://freebsd.denbeke.be {
	root site
	fastcgi / 127.0.0.1:9000 php
	log access.log

}

https://freebsd.denbeke.be {
	root site
	tls server.crt server.key
	fastcgi / 127.0.0.1:9000 php
	log access.log
}
```

In the past I successfully switched from HTTP to HTTPS on other Wordpress sites, but here I don't understand what's going on.

Something I'm doing wrong with the Caddy configuration? Or is Wordpress just messing things up?

**Comment by mholt** [comment]
Odd. I can't think of any reason why Caddy would be initiating any redirects with that configuration. This [doesn't appear to be an isolated occurrence](https://www.google.com/search?q=wordpress+redirect+loop). Maybe fiddle with the WordPress config a little bit?

Pinging @thomas4019 - I know it's been a while, but you ran Caddy with WordPress. Did you ever encounter redirect loops?

**Comment by DenBeke** [comment]
I also suspect Wordpress somehow. But since I'm not really experienced in Caddy I wanted to ask it here.

The redirect loop looks like this:

```
--2015-08-03 19:46:00--  https://freebsd.denbeke.be/wp-login.php
Resolving freebsd.denbeke.be (freebsd.denbeke.be)... 46.101.215.15
Connecting to freebsd.denbeke.be (freebsd.denbeke.be)|46.101.215.15|:443... connected.
WARNING: cannot verify freebsd.denbeke.be's certificate, issued by ‘/C=BE/ST=Some-State/O=Internet Widgits Pty Ltd/CN=freebsd.denbeke.be’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 302 Found
Location: https://freebsd.denbeke.be/wp-login.php [following]
--2015-08-03 19:46:00--  https://freebsd.denbeke.be/wp-login.php
Reusing existing connection to freebsd.denbeke.be:443.
HTTP request sent, awaiting response... 302 Found
Location: https://freebsd.denbeke.be/wp-login.php [following]
--2015-08-03 19:46:00--  https://freebsd.denbeke.be/wp-login.php
Reusing existing connection to freebsd.denbeke.be:443.
HTTP request sent, awaiting response... 302 Found
Location: https://freebsd.denbeke.be/wp-login.php [following]
--2015-08-03 19:46:00--  https://freebsd.denbeke.be/wp-login.php
Reusing existing connection to freebsd.denbeke.be:443.
HTTP request sent, awaiting response... 302 Found
Location: https://freebsd.denbeke.be/wp-login.php [following]
```

**Comment by DenBeke** [comment]
I have copied the `is_ssl()` function from Wordpress hoping this could reveal the error. Created the following test file:

```php
/**
 * Determine if SSL is used.
 *
 * @since 2.6.0
 *
 * @return bool True if SSL, false if not used.
 */
function is_ssl() {
        if ( isset($_SERVER['HTTPS']) ) {
                if ( 'on' == strtolower($_SERVER['HTTPS']) )
                        return true;
                if ( '1' == $_SERVER['HTTPS'] )
                        return true;
        } elseif ( isset($_SERVER['SERVER_PORT']) && ( '443' == $_SERVER['SERVER_PORT'] ) ) {
                return true;
        }
        return false;
}



// Some tests...
header("Content-Type:text/plain");

echo 'is_ssl(): '; var_dump(is_ssl());

echo '$_SERVER[\'HTTPS\']: '; var_dump($_SERVER['HTTPS']);

echo '$_SERVER[\'SERVER_PORT\']: '; var_dump($_SERVER['SERVER_PORT']);
```

**Nginx**  
Using Nginx and PHP-FPM on another server this yields (of course for an HTTPS request):

```
is_ssl(): bool(true)
$_SERVER['HTTPS']: string(2) "on"
$_SERVER['SERVER_PORT']: string(3) "443"
```

**Caddy**  
Running the same script using Caddy and PHP-FPM it yields this:

```
is_ssl(): bool(false)
$_SERVER['HTTPS']: <br />
<b>Notice</b>:  Undefined index: HTTPS in <b>/usr/home/mathias/site/test.php</b> on line <b>26</b><br />
NULL
$_SERVER['SERVER_PORT']: string(0) ""
```

This seems to be causing the redirect, since Wordpress will think an HTTP request is sent, which doesn't match the HTTPS in the canonical domain.

**Comment by mholt** [comment]
Holy moly, you figured it out. Thanks! I think the latest commit should do the trick: 8d81ae88dacaf94d0fc70268cb03050a9e3e6bef

Let me know if it doesn't. Should go out on the next release (or you can compile from source to try it now).

**Comment by DenBeke** [comment]
I just recompiled from source, looks all good!

```
is_ssl(): bool(true)
$_SERVER['HTTPS']: string(2) "on"
$_SERVER['SERVER_PORT']: string(0) ""
```

And Wordpress works perfectly now! 
Thank you!

**Comment by bigtan** [comment]
@DenBeke 
In your Caddy file is `127.0.0.1:9000` an apache server virtualname ?

**Comment by DenBeke** [comment]
@bigtan 
`127.0.0.1:9000` is PHP-FPM.
