### ISSUE TITLE
Expires headers are added to errors page

### ISSUE THREAD

**Issue by commarla** [mholt/caddy#2122]
### 1. What version of Caddy are you using (`caddy -version`)?
0.10.10

### 2. What are you trying to do?
Serve a static js page. Sometimes the source page is not present and caddy serve a 404 error page (as expected) but the header `Expires` is present and the browser cache the error page.

### 3. What is your entire Caddyfile?
```text
*:80 {
        tls off

        expires {
             match .(js|css|rdf|xml|ico|txt|gif|jpg|png|jpeg|swf|mp3|mp4|webm|pdf)$ 6h
             match .(ttf|svg|eot|woff|woff2)$ 30d
        }
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy -conf Caddyfile`

### 5. Please paste any relevant HTTP request(s) here.
A good one :
```bash
❯ http localhost/test.js
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 8
Content-Type: application/javascript
Date: Wed, 18 Apr 2018 08:05:18 GMT
Etag: "p7dfbi8"
Expires: Wed, 18 Apr 2018 16:05:18 CEST
Last-Modified: Wed, 18 Apr 2018 07:54:54 GMT
Server: Caddy

ALLOOOO
```
A bad one :
```bash
http :/test1.js
HTTP/1.1 404 Not Found
Content-Length: 14
Content-Type: text/plain; charset=utf-8
Date: Wed, 18 Apr 2018 08:10:06 GMT
Expires: Wed, 18 Apr 2018 16:10:06 CEST
Server: Caddy
X-Content-Type-Options: nosniff

404 Not Found
```

### 6. What did you expect to see?
Same response without the `Expires` header.

### 7. What did you see instead (give full error messages and/or log)?
This *annoying* header and my browser which caches the 404

![screenshot 2018-04-18 10 10 56](https://user-images.githubusercontent.com/4509360/38919716-b1c2a306-42f1-11e8-9514-0a53b98fab22.png)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Just run the Caddyfile and curl a existing file and a non existing.

**Comment by mholt** [comment]
Hi, thanks for filing an issue and using the template! However, it seems your bug report is about a third party plugin. Please file this [issue with the plugin's repository](https://github.com/epicagency/caddy-expires/issues) and they can help you there with it.

**Comment by commarla** [comment]
Hi, 

Thanks for the attached issue. I have the same behavior with the `header` directive. Is there a way to remove some headers when the response is an error ?

```
header /pupitre/public/js Cache-Control "public, max-age=21600"
```

```
❯ http :/pupitre/public/js/test.1.js
HTTP/1.1 404 Not Found
Cache-Control: public, max-age=21600
Content-Length: 0
Content-Type: text/html; charset=utf-8
Date: Wed, 18 Apr 2018 13:44:13 GMT
Server: Caddy

```

Thanks.

**Comment by schmkr** [comment]
Running into this issue too, that the `header` directive cannot be configured in any way to configure response headers (adding and/or removing) when a response is erroneous.

Would it be an idea to add an option to the header directive to restrict it to certain status codes?

```
header / {
  if_status 404
  -Cache-Control
}
```

or

```
header / {
  if_status 200
 Cache-Control "public, max-age=21600
}
```

**Comment by schmkr** [comment]
Any change to get this issue reopened @mholt? Since it is not caused by the addon as suggested in your message before closing this issue?

**Comment by mholt** [comment]
@schmkr If a plugin is writing headers, it will need to be made conditional at write-time (i.e. configured by the plugin); the headers middleware doesn't have the conditional logic to handle all the other plugins.

But Caddy 2's header logic can do this. I just implemented it today. Thanks for bringing it to my attention.

What do you think (relevant part of a Caddy 2 config):

```js
{
	"middleware": "headers",
	"response": {
		"require": {
			"status_code": [4, 5],  // matches all 4xx and 5xx statuses
			"headers": {
				"Field-Name": ["example"] // can also match on headers
			}
		},
		"set": {"Cache-Control": ["no-cache"]}
	}
}
```

**Comment by schmkr** [comment]
Thanks Mat, that looks like it could work. I also notice the mentioned plugin at the beginning of the issue seems to have added a `match_headers` directive, but that would only be for the expires functionality.

Curious to see what kind of requirements can into the `require` block? Also the mimetype/content-type of a response? Would this work:

```
{
	"middleware": "headers",
	"response": {
		"require": {
			"status_code": [2],  // matches all 4xx and 5xx statuses
			"headers": {
				"Content-Type": ["text/html"] // can also match on headers
			}
		},
		"set": {"Content-Security-Policy": ["default-src 'none'"]}
	}
}
```

**Comment by mholt** [comment]
@schmkr Yeah, that should work; although usually Content-Type has `; charset=utf-8` appended to it (that's the most common but it doesn't have to be that), so keep that in mind.

Stay tuned, the v2 source code will be published today.
