### ISSUE TITLE
Ambiguity in documentation for http.errors directive

### ISSUE THREAD

**Issue by boxofrox** [mholt/caddy#2123]
While reading the documentation \[[1](https://caddyserver.com/docs/errors)] for http.errors, I noticed the follow contradiction.

In the "Syntax" section, `errors [logfile]` specifies that `logfile` defaults to `stderr`.  I assume the brackets around `[logfile]` indicate that value is optional, and when omitted defaults to `stderr`.

Below that in the "Examples" section, the first example reads:

> Log errors to **error.log**:
> ```
> errors
> ```

Given the description from "Syntax", I expected the first example to read like so:

> Log errors to **stderr**:
> ```
> errors
> ```

**Comment by mholt** [comment]
You're right, this is confusing; it will be updated shortly!

**Comment by mholt** [comment]
Fixed locally, will be pushed with next release. Thanks!
