### ISSUE TITLE
rewrite the request URI instead of just the path?

### ISSUE THREAD

**Issue by mytbk** [mholt/caddy#2129]
I'm hosting a cgit instance using a subdomain recently, and I use the rewrite rule:

    rewrite {
            regexp ^/([^?/]+/[^?]*)?(?:\?(.*))?$
            to /cgit.cgi?url={1}&{2}
    }

However, the site doesn't work properly for requests like ``.../commit/?id=...``. After checking the code, I found caddy only rewrites the URL.Path. After I do this change, it works properly:

    sed -i 's/URL.Path/URL.RequestURI()/g' caddyhttp/rewrite/rewrite.go

So should caddy do the rewrite on the URI or just the path? If just rewrite the path, what to do when the rewrite rule want to do with query string?

**Comment by tobya** [comment]
Could you please show a diff of the change you have made rather than just the `sed` command.

It would be great if you could submit a PR with this change so we can review.

**Comment by tobya** [comment]
I will close this until we get more information.
