### ISSUE TITLE
How to listen to 80 ？

### ISSUE THREAD

**Issue by Kevinl7** [mholt/caddy#2138]
### 1. What version of Caddy are you using (`caddy -version`)?
I must now operate caddy -port 2015 every time before you can access it properly.
```
root@iZbp16z10dzvv6jyd1i6wrZ:/etc/caddy# caddy -port 2015 
Activating privacy features... done. 
https://ojbk.fun 
http://ojbk.fun
```

### 2. What are you trying to do?
How to listen to 80 ？

### 3. What is your entire Caddyfile?
```
ojbk.fun {
root /var/www 
gzip
}
```

**Comment by abiosoft** [comment]
Your question is not clear and ensure you fill the issue template. You cannot start Caddy with `-port 2015` flag and expect a miracle of listening on port 80.

By default, when using a domain, Caddy listens on port 80 for http and 443 for https. 
And you can explicitly request to listen on port 80 by using `http://ojbk.fun` or `ojbk.fun:80`.

**Comment by mholt** [comment]
Remove the `-port` flag, and Caddy will listen on ports 80 and 443, with redirects set up for you. See https://caddyserver.com/docs/automatic-https.
