### ISSUE TITLE
Forcing wildcard on sub-domain and using client-cert on another sub-domain

### ISSUE THREAD

**Issue by lbguilherme** [mholt/caddy#2148]
### 1. What version of Caddy are you using (`caddy -version`)?

0.10.14

### 2. What are you trying to do?

Create a sub-domain protected by a client certificate. And another plain-old sub-domain.

### 3. What is your entire Caddyfile?
```text
a.example.com {
  tls {
    dns cloudflare
    wildcard   # removing this line "fixes" the problem
    clients /data/caddy/sites/certs/ca.crt
  }
}

b.example.com {
  tls {
    dns cloudflare
    wildcard
  }
}
```

 incompabile TLS configurations for the same SNI name (*.example.com) on the same listener: multiple hosts requiring client authentication ambiguously configured

### 4. How did you run Caddy (give the full command and describe the execution environment)?

Inside a Docker container, inside Kubernetes, inside AWS:

    caddy -agree -email mail@example.com -log stdout -conf /data/caddy/Caddyfile -grace 60s -pidfile /tmp/caddy.pid

### 6. What did you expect to see?

Caddy starts

### 7. What did you see instead (give full error messages and/or log)?

`incompabile TLS configurations for the same SNI name (*.example.com) on the same listener: multiple hosts requiring client authentication ambiguously configured`

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Simply run with that Caddyfile

**Comment by mholt** [comment]
Thanks for opening an issue -- but this isn't a bug. Without this restriction, clients could bypass TLS Client Authentication by manipulating SNI values. See https://github.com/mholt/caddy/commit/4d9ee000c8d2cbcdd8284007c1e0f2da7bc3c7c3.

**Comment by lbguilherme** [comment]
I'm not sure if I quite understood it. The two hosts `a.example.com` and `b.example.com` are distinguishable from the SNI value. The error says the SNI would be `*.example.com`, but this isn't a valid SNI value AFAIK.

The check makes sense if they are the same domain but differ on a path or something else. But I fail to see what it is protecting here. If this check were removed, how could I bypass client auth?

(I'm fine with the workaround of removing "wildcard" from my config, just wanting to fully understand what is going on)

**Comment by mholt** [comment]
> The error says the SNI would be *.example.com, but this isn't a valid SNI value AFAIK.

True, the error message is a bit naive in this case.

> If this check were removed, how could I bypass client auth?

The client could send SNI for the unprotected name, `b.example.com`, and then send HTTP requests for `Host: a.example.com`. In general, this is undesirable by site owners (even though I cringe at the conflating of the layers, but oh well that's how most people use it).

**Comment by lbguilherme** [comment]
Why not always reject later requests with a `Host` that disagrees with SNI?

**Comment by mholt** [comment]
Because that can be useful when domain fronting, or optimizing performance across a batch of related sites. It's very niche, we have to be selective how much rejection we implement.

**Comment by lbguilherme** [comment]
Understood. Thanks!

**Comment by mholt** [comment]
I don't fully understand what you mean by this: `# removing this line "fixes" the problem` - can you elaborate?

**Comment by mholt** [comment]
Thanks for the explanation/clarification.

> The same way that a.example.com/path1 and a.example.com/path2 share the same cert. And by sharing the same certificate, they share the same listener. Am I assuming correctly?

Almost! The error message is a bit misleading in this case because the check that creates it is naive, I admit. The reason you get the error is not obvious. A listener is based on the port, not the names or certificates. These sites share a port, so they are on the same listener.

You have fully-qualified domain names specified, `a.example.com` and `b.example.com`. When you use `wildcard`, Caddy replaces the left-most label with a wildcard `*` so it will obtain and manage a wildcard cert instead: `*.example.com`. When you do it to both, they both have the same "SNI" name: `*.example.com` -- and yes that's not really an acceptable value for SNI, but the error message doesn't consider wildcard names in this case. But the error checking logic still applies.

Perhaps the error check could be expanded to support wildcards; however, in your case, for now, I'll just advise not to use client auth with one name on a listener and without it on another.

**Comment by maciekish** [comment]
Hi, I am having the same issue. I want a Letsencrypt wildcard certificate and client certificate authentication on all my listeners. How can i do this?

`
    tls { //Reused config in each site block below. I want all sites to share this wildcard cert and require the same client cert.
    dns namecheap
    wildcard
    clients require /mnt/user/appdata/caddy/conf/ca.crt
}

service1.domain.com {
    import tls
        proxy / https://10.0.1.0:8443 {
        transparent
        websocket
        insecure_skip_verify
    }
}

service2.domain.com {
    import tls
        proxy / https://10.0.1.0:8443 {
        transparent
        websocket
        insecure_skip_verify
    }
}
`
