### ISSUE TITLE
Add zstd compression

### ISSUE THREAD

**Issue by rugk** [mholt/caddy#2153]
https://github.com/facebook/zstd is a new compression algorithm and it is currently [being standardized](https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-01.html) so browsers may implement it (see https://github.com/facebook/zstd/issues/409 about nginx support).

So support in Caddyserver would be a nice thing to have – maybe even before major browsers implement it.

**Comment by centminmod** [comment]
@rugk thanks for that would be great to have. Did my ztd benchmarks and speed is good https://community.centminmod.com/threads/compression-comparison-benchmarks-zstd-vs-brotli-vs-pigz-vs-bzip2-vs-xz-etc.12764/ :)

**Comment by tobya** [comment]
We would be delighted with a PR 😄

**Comment by darshanime** [comment]
I am a newbie here, can I pick this up?

**Comment by abiosoft** [comment]
Go for it @darshanime.

**Comment by tobya** [comment]
WE will close this until a go implementation of zstd becomes available.

**Comment by mholt** [comment]
See https://github.com/restic/restic/issues/21#issuecomment-391757629 for insights into a pure-Go zstd implementation.

**Comment by rugk** [comment]
BTW:
> Zstd has been standardized as RFC 8478, which included registering a "zstd" content coding for HTTP.

from https://github.com/facebook/zstd/issues/409#issuecomment-285572998

**Comment by mholt** [comment]
Zstd compression is available in Caddy 2 (see the v2 branch).
