### ISSUE TITLE
Video streaming site becomes unresponsive to new requests when I use QUIC

### ISSUE THREAD

**Issue by mustafa1024m** [mholt/caddy#2156]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.14 (unofficial)

### 2. What are you trying to do?
Use Caddy with QUIC

### 3. What is your entire Caddyfile?
```text
http://cinema.example.com {
        redir https://cinema.example.com{uri}
}

https://cinema.example.com {
        tls /etc/certs/example.crt /etc/certs/example.crt
        log /var/log/caddy.log
        proxy / {
                policy least_conn
                fail_timeout 3s
                max_fails 3
                try_duration 5s
                health_check /
                health_check_interval 10s
                health_check_timeout 5s
                keepalive 100

                upstream 10.1.5.54
                upstream 10.1.5.57
                upstream 10.1.12.25

                transparent
        }
}

cnth1.example.com:443 {
        tls /etc/certs/example.crt /etc/certs/example.crt
        log /var/log/caddy.log
        proxy / {
                policy uri_hash
                fail_timeout 3s
                max_fails 3
                try_duration 5s
                health_check /
                health_check_interval 10s
                health_check_timeout 5s
                keepalive 100

                upstream 10.100.3.229:8080
                upstream 10.100.3.230:8080
                upstream 10.100.3.226:8080
                upstream 10.100.3.227:8080

                transparent
        }
}

cndw1.example.com:443 {
        tls /etc/certs/example.crt /etc/certs/example.crt
        log /var/log/caddy.log
        proxy / {
                policy uri_hash
                fail_timeout 3s
                max_fails 3
                try_duration 5s
                health_check /
                health_check_interval 10s
                health_check_timeout 5s
                keepalive 100

                upstream 10.100.3.229:8080
                upstream 10.100.3.230:8080
                upstream 10.100.3.226:8080
                upstream 10.100.3.227:8080

                transparent
        }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
ulimit -n 8192 ; QUIC_GO_LOG_LEVEL=DEBUG ; echo $QUIC_GO_LOG_LEVEL ; ./caddy -quic

### 6. What did you expect to see?
QUIC keeps working normally

### 7. What did you see instead (give full error messages and/or log)?
After a while, new request doesn't reach the server (or don't get logged), and the link presses makes no action, I used Chrome Dev tools to capture this:

Request URL: https://cinema.example.com/page/home
Request Method: GET
Status Code: 200 
Remote Address: 10.1.4.126:443
Referrer Policy: no-referrer-when-downgrade
alt-svc: quic=":443"; ma=2592000; v="39"
content-encoding: gzip
content-type: text/html; charset=UTF-8
date: Tue, 08 May 2018 11:10:11 GMT
server: nginx
server: Caddy
set-cookie: ci_session=PyQNfCmcJRYRO4MkAaSdqxV7y1kowYigCM2xlDMAXadXSiQ54h%2BIBXgFYXTZONeRb5kJ3FYh8bjVISXCRLLEwveF%2Fw9TOqvn6CcDKCzkb1PoAkLBXSmtmKtBIY9O%2FR3HNpN7BgLz5Kn0j2C12fZzcPcZsmzumHR5KGO1rDYYgVz3MMtN1Gjc9m3jC8zc6ZQbAyKsfgrlG6alYrApNZY5ubLl4IUb9TlKm6SOKWnr95%2BdB4Mq0TufjfQQjfbqCT7Lm%2Fv%2BcKJMaVy8Jysgtm2J4OGwcKfRjnSk8qzbnK%2FMbup1MNIWI6qikuDXCN6TMBYyFArLJCEptTdr2MK2Z0KsNq37KxcryWObFxybWbLmYlC26ew5WhhofjG%2B4YYaxNBvxudXN54wonYt5t0aG%2Fnh1we7N5nOwu5nTvrmLfEXx%2Baxf8vEP9mum1my70a6qIXdf%2BEW0sjzCOEqVmLsEimv8A%3D%3D; path=/
set-cookie: csrf_cookie_name=e185f5b2581f8fd9a346a080076fd82b; expires=Tue, 08-May-2018 13:10:10 GMT; Max-Age=7200; path=/
status: 200
vary: Accept-Encoding
x-cache: BYPASS
x-powered-by: PHP/7.1.16
:authority: cinema.example.com
:method: GET
:path: /page/home
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: no-cache
cookie: csrf_cookie_name=e185f5b2581f8fd9a346a080076fd82b; userInfo=%7B%22pbip%22%3A%2237.239.255.250%22%2C%22prip%22%3A2%2C%22refrrer%22%3A1%2C%22rsrv%22%3A2%7D; CnWatchHistoryV2=%5B%7B%22id%22%3A160706%2C%22videoName%22%3A%22Black%20Panther%20%22%2C%22videoTime%22%3A2.184718%7D%5D; dataAnalytics=%5B%7B%22eventID%22%3A0%2C%22eventInt%22%3A%223%22%2C%22videoID%22%3A%22160706%22%2C%22currentTime%22%3A2%7D%2C%7B%22eventID%22%3A0%2C%22eventInt%22%3A%223%22%2C%22videoID%22%3A%22160706%22%2C%22currentTime%22%3A2%7D%2C%7B%22eventID%22%3A0%2C%22eventInt%22%3A%221%22%2C%22videoID%22%3A%22160706%22%2C%22currentTime%22%3A2%7D%5D; ci_session=V73R9Fa8q10loYY%2FjQjXEz7RazhzLTtPAyAn0%2B2JPDsiCQA0F1Ur13yrPybdohz7QlogSEEnOxtxQe4Y0jNmXe8WK8gXThJNRAy6u4EZuaNiFbQzGKqwrUS4Q6sihBdD2rW6nrSnCeqIcSYFSBKNbytAZerQm9DMchauSb4sRcNyjPJ3eTzfdTzsBVeVjVRePh2WyFthc%2FAzYHzF72WVjShNscIXq6NgKCiPFrPzdRNHfLezt7UK4VvlY6oshGXgJJZCQTVRQCF2xYtAZprmy%2FDJve7iONpXAqZGf2VxHNR2TnaCdOWIB22HK36YhGQP%2FVr41yQkWI9dJqRjTWIAUbXFl3jjBCvWEQ8rr6x94592xA1hwYwCDPPJBzqtT6WtvywcVoLNuyD5xU6kasmH5%2B%2FlJudExL8%2FYNnvLYIxZfqClxYJx9MV992vpxDrslUoA690UkSgyQQqtmHRJ%2B6U5Q%3D%3D
pragma: no-cache
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

in a new tab, and nothing got loaded.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Not sure, but I use a web page with videojs player playing an mp4 file, this can be related to the problem, using http2 is normal, but with QUIC I am having this problem, I couldn't find quic-go log to post to the issue I reported to quic-go, if I get this log, I think I can give much more useful info.

**Comment by midzer** [comment]
This might be related to https://github.com/lucas-clemente/quic-go/issues/1243

**Comment by mustafa1024m** [comment]
Probably, but the problem is that I can't get quic-go log from caddy, I previously reported this issue:
https://github.com/lucas-clemente/quic-go/issues/1337
But I still don't have the required log.

**Comment by magikstm** [comment]
@mustafa1024m could you please test with Caddy 0.11.3?
