### ISSUE TITLE
http2 push doesn't works

### ISSUE THREAD

**Issue by evgygor** [mholt/caddy#2157]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.10.14

### 2. What are you trying to do?
push files on request

### 3. What is your entire Caddyfile?
```text
localhost:443 {
log "caddy.log"
errors "caddyerror.log"

tls cert.crt cert.key

	push /index.html {
		/static/css/main.css
		/static/js/polyfills.798e1f94.js
		/creditcard2.png
		/static/js/main.34dcc934.js
	}

root "C:\Git_work\webserver\"
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
C:\dev\servers\caddy_v0.10.14_windows_amd64_personal>caddy

### 5. Please paste any relevant HTTP request(s) here.
I haven't nothing specific

### 6. What did you expect to see?
In Chrome dev tool see the  Initiator "Push"

### 7. What did you see instead (give full error messages and/or log)?
In caddy's log:
::1 - - [08/May/2018:15:45:34 +0300] "GET / HTTP/2.0" 200 1530
::1 - - [08/May/2018:15:45:34 +0300] "GET /creditcard2.png HTTP/2.0" 200 1807
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/js/polyfills.798e1f94.js HTTP/2.0" 200 24817
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/css/main.css HTTP/2.0" 200 147677
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/js/main.34dcc934.js HTTP/2.0" 200 238063
::1 - - [08/May/2018:15:45:34 +0300] "GET /fonts.css HTTP/2.0" 200 2191
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/css/main.css HTTP/2.0" 200 147677
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/js/footer.21e3cb50.js HTTP/2.0" 200 44256
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/js/main.34dcc934.js HTTP/2.0" 200 238063
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/css/main.css.map HTTP/2.0" 200 496420
::1 - - [08/May/2018:15:45:34 +0300] "GET /msapi/id HTTP/2.0" 404 14
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/js/footer.21e3cb50.js.map HTTP/2.0" 200 551807
::1 - - [08/May/2018:15:45:34 +0300] "GET /static/js/main.34dcc934.js.map HTTP/2.0" 200 5653329

No errors exists
In Chrome Dev Tool:
For relevant (should  be pushed) CSS/JS the Initiator is index 
Desired creditcard2.png not exists in Dev Tool network monitor

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
No proxies, local environment.

**Comment by elcore** [comment]
Hello @evgygor,

HTTP/2 Server Push does not work with a self-signed cert, you will have to use a valid cert.

**Comment by mholt** [comment]
@elcore Are you sure about that?

**Comment by elcore** [comment]
@mholt 100%
