### ISSUE TITLE
Automatic build is broken: "provisioning build environment: go get github.com/mholt/caddy: exit status 1"

### ISSUE THREAD

**Issue by vovcacik** [mholt/caddy#2159]
The URL https://caddyserver.com/download/linux/amd64?plugins=tls.dns.cloudflare&license=personal returns `provisioning build environment: go get github.com/mholt/caddy: exit status 1`.

**Comment by mholt** [comment]
Should be fixed now!

**Comment by vovcacik** [comment]
Great, thanks!
