### ISSUE TITLE
Make FastCGI except - match prefix rather than exact file

### ISSUE THREAD

**Issue by tobya** [mholt/caddy#2160]
Following this issue in Caddy.community https://caddy.community/t/excluding-folder-from-fastcgi/3833/2

with a fastcgi block except will only match an exact file

The request if for the following to work

    fastcgi / /run/php/php7.0-fpm.sock php {
        except /wp-content/uploads/
    }

anything that starts with `/wp-content/uploads/` would be excluded.

**Comment by mholt** [comment]
This'll probably be handled by #1948 if/when we can get that done.

**Comment by mholt** [comment]
This should be a non-issue in Caddy 2 since middlewares will not have to do their own request matching.
