### ISSUE TITLE
RFE: placeholder for hashed ip

### ISSUE THREAD

**Issue by UweOhse** [mholt/caddy#2162]
I'd like to have a new placeholder returning a hash of the IP address.

Rationale: 
1. i do not want to see IP addresses in my logs, especially as i sometimes want to keep them for a long time.
2. masking the IP addresses, in way compatible with the privacy laws, makes them unusable for debugging in some cases (i do have a number of users who end up in the same /24 every few days).

a hash of the IP address, even a crc32, would satisfy privacy, and be unique enough for debugging.

It might be done this way in caddyhttp/httpserver/replacer.go:
`29a30
>       "hash/crc32"
339a341,346
>       case "{remotehash}":
>               host, _, err := net.SplitHostPort(r.request.RemoteAddr)
>               if err != nil {
>                       host = r.request.RemoteAddr
>               }
>               return strconv.Itoa(int(crc32.Checksum([]byte(host), crc32.IEEETable)))
`

Is there an easy way to see whether the connection uses IPv4 or v6?
If yes, it might be useful to add another placeholder, as this information is lost with hashing.

**Comment by mholt** [comment]
I don't think hashing an IP address really offers any more privacy than just storing the IP address.

Especially IPv4 addresses: those can be enumerated in a matter of minutes. Why is hashing them more private, exactly? (Here's a recent, real example: https://twitter.com/einaros/status/951437795528265728)

(The same goes for IPv6, as the subset of allocated IPv6 addresses is extremely small compared to the size of the whole space.)
