### ISSUE TITLE
acme: Error 403 - urn:ietf:params:acme:error:unauthorized

### ISSUE THREAD

**Issue by samcro1967** [mholt/caddy#2166]
I am trying to revoke a certificate.  I ran caddy -revoke subdaomin.domain.net and get the following error back:
"Error 403 - urn:ietf:params:acme:error:unauthorized - The key ID specified in the revocation request does not hold valid authorizations for all names in the certificate to be revoked"

I also tried *.domain.net and domain.net and neither of those worked either.  Both return no certificate and key for domain.net.
 I am running Caddy 0.11.0 on Windows 10.

**Comment by mholt** [comment]
Caddy doesn't yet support revoking certificates using ACMEv2, sorry.

Why are you trying to revoke the certificate? You should only do that in case of private key or DNS compromise.

**Comment by samcro1967** [comment]
I created a few new ones and got rate limit reached so I was going to revoke some old names I was no longer using.  Didn't want to wait 24 hours before it would let me create some more.  Also want to follow good practice and help cleanup.  Would be nice to be able to list the ones registered and then revoke any unused ones.  Thanks for the response.

**Comment by mholt** [comment]
> I created a few new ones and got rate limit reached so I was going to revoke some old names I was no longer using.

Don't do this: only revoke if you lose control of your DNS or your private key.

> Didn't want to wait 24 hours before it would let me create some more.

That's not how this works; revocation is only an additive function - it does not undo an issuance. Also, the LE rate limits (for issuing too many certs for a given name or its subdomains) last one week, not 24 hours.

> Also want to follow good practice and help cleanup.

Where did you hear this is good practice? Don't revoke to "cleanup" - it actually creates more of a mess.

> Would be nice to be able to list the ones registered and then revoke any unused ones.

No, no no -- definitely not going to happen, sorry.

The best way to avoid rate limits is to use the Let's Encrypt staging endpoint when testing your setup.
