### ISSUE TITLE
Include README / instructions for selected plugins

### ISSUE THREAD

**Issue by edbond** [mholt/caddy#2167]
^ Subject ^

**Comment by mholt** [comment]
I don't know what you mean by this :(

**Comment by edbond** [comment]
Nice reply for someone trying to sell software.
Great support BTW!
Thanks Matt

**Comment by elcore** [comment]
> Nice reply for someone trying to sell software.
Great support BTW!
Thanks Matt

@edbond We cannot help you if we don´t understand your question!

**Comment by magikstm** [comment]
Documentation of all third-party plugin is available in their own Github repo.

If you visit the Download page here:
https://caddyserver.com/download

Select plugins then click the little (i) icon and you'll have more details on them. At the bottom of that screen you'll have links to the "Documentation", "Support" and "Website" of that plugin.

The same links are available at the bottom of each plugins at that page:
https://caddyserver.com/docs

It wouldn't really be feasible at the moment to include plugins readme with a Caddy download as plugin documentation format varies quite a lot depending on the plugin.
