### ISSUE TITLE
add a compress directive

### ISSUE THREAD

**Issue by darshanime** [mholt/caddy#2173]
Currently we have a `gzip` directive for adding compression, which accepts additional configuration.
```
gzip {
    ext        extensions...
    not        paths
    level      compression_level
    min_length min_bytes
}
```
We can refactor this to a general directive `compress` which could accept alternative compress methods (#2153)

Something like this:

```
compress gzip # uses gzip to compress
compress zstd # uses zstd to compress
```

Additional parameters can be passed like before

```
compress gzip {
    ext        extensions...
    not        paths
    level      compression_level
    min_length min_bytes
}
```

**Comment by tobya** [comment]
Should we have a default so 

    compress 

would be the same as 

    compress gzip

**Comment by mholt** [comment]
Yeah, good idea.

**Comment by tobya** [comment]
I'm going to close this now as it is currently not relevant until there is a go implementation of zstd.

We can reopen if one becomes available.

**Comment by mholt** [comment]
This has basically been implemented into Caddy 2 (with some differences). See the v2 branch.
