### ISSUE TITLE
Error400;URN:IETF:PARAM:ACME

### ISSUE THREAD

**Issue by sanwzzz** [mholt/caddy#2174]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (non-commercial use only)

### 2. What are you trying to do?
My web

### 3. What is your entire Caddyfile?
sanwzzz.club:443 {
root /caddy/www/index.html
tls 1023837091@qq.com
log    /caddy/log/access.log
gzip
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -conf /caddy/Caddyfile
Centos 7 *64

### 7. What did you see instead (give full error messages and/or log)?
Activating privacy features... 2018/05/19 13:31:48 [sanwzzz.club] failed to get certificate: acme: Error 400 - urn:ietf:params:acme:error:connection - Fetching http://sanwzzz.club/.well-known/acme-challenge/PZKK9RVy9xETP0wAtgid_dd5gHyCKAlzyTeudM7zHfI: Error getting validation data

**Comment by mholt** [comment]
This usually means that Let's Encrypt cannot reach your server. Make sure that your site is accessible to the public.

And if you have any other questions for debugging your setup, please use our forum: https://caddy.community

Thanks!

**Comment by sanwzzz** [comment]
I don't understand what you are saying. My domain name has been resolved to the server. What should I do?

**Comment by mholt** [comment]
As this doesn't appear to be a bug in Caddy, you should ask on our forum, like I said. More people will be able to help you there. This is an issue with your infrastructure; Let's Encrypt's servers are apparently unable to access your site (even if your domain resolves properly).

**Comment by sanwzzz** [comment]
okay，thanks.
