### ISSUE TITLE
Gzip directive - Should .m3u and .m3u8 files be added?

### ISSUE THREAD

**Issue by magikstm** [mholt/caddy#2175]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0

### 2. What are you trying to do?
Visit a page with an HLS stream and using a .m3u or a .m3u8 files which are HTTP Live Streaming playlist files.

They're basically text files.

Ref:
https://en.wikipedia.org/wiki/M3U
https://en.wikipedia.org/wiki/HTTP_Live_Streaming
https://datatracker.ietf.org/doc/rfc8216/
https://developer.apple.com/library/content/technotes/tn2288/_index.html

Code ref:
https://github.com/mholt/caddy/blob/master/caddyhttp/gzip/requestfilter.go#L31

### 3. What is your entire Caddyfile?
```text
http://localhost:8080/ {
  root C:\Users\xyz\site
  gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
I double-clicked caddy.exe on Windows 7 x64.

### 5. Please paste any relevant HTTP request(s) here.
None.

### 6. What did you expect to see?
These files gzipped.

### 7. What did you see instead (give full error messages and/or log)?
No gzip.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Try to view a .m3u or .m3u8 file in your browser or a page with an HLS stream.

**Comment by mholt** [comment]
Sure, we can add them. Want to submit a pull request?
