### ISSUE TITLE
Allow events to be cancelled

### ISSUE THREAD

**Issue by oliverdunk** [mholt/caddy#2177]
A major limitation of Caddy's Event Hook system is the lack of a way to cancel a given event. This does make sense in some instances, but for `CertRenewEvent`, for example, I would love to be able to allow or block this based on my own logic. 

This becomes more useful with the events that I have added in my own Caddy fork, such as the `ObtainOnDemandCertEvent`. This is called just before a cert is obtained on demand and I would love to be able to decide with code if this request can be allowed. I know about the `Ask` directive but adding similar functionality in a plugin seems like something that should be possible.

I am opening this issue to discuss if this is an addition worth opening a PR for, and to also discuss the best approach. Based on my current understanding, this feels like the best route:

- Cancellable events should be called before the action rather than after. They are already blocking which means the action will not occur until all hooks have been processed.
- Update `EmitEvent` to return a boolean, which is usually false, but set to true if any event hook returns false as a new second return value.
- Handle the result of `EmitEvent` where it is called, such as aborting obtaining an on demand certificate if the return value is false.

**Comment by mholt** [comment]
Canceling events mid-execution sounds a little clunky/dirty. Is canceling the obtaining of an on-demand certificate the only motivation for this? Why is the ask endpoint unsuitable, exactly?

**Comment by oliverdunk** [comment]
@mholt We would make it clear based on the name of each event when it is called, and that should hopefully make it less dirty. For example, there could be an `ObtainOnDemandCertificate` event at the start of the process, and an `OnDemandCertificateObtained` event at the end. Only the former would be cancellable.

The reason for the Ask endpoint example is as follows:
- I have a Caddy plugin which already has a connection to MongoDB.
- MongoDB contains the data which decides which URLs I want to allow certificates from.
- It seems silly to have to host a web server from my Caddy plugin, or write an entirely new program, just to serve this data, when the plugin could just talk to Caddy directly by letting the event pass or cancelling it.

For a similar reason I'd also like to be able to cancel the proposed `CertRenewEvent` as it doesn't seem like Caddy checks with the `Ask` endpoint first before renewal?

In honesty I have limited examples at the moment, but especially if plugins start adding new events which seems like a good assumption to make, being able to cancel them will come in handy.

**Comment by mholt** [comment]
You could just add a little site definition in your Caddyfile that is only exposed locally that answers the `ask` endpoint, that should be just a couple lines of config.

And no, once a certificate is obtained and loaded, it will be managed as long as the name is being served, so `ask` is not checked in that case.

**Comment by oliverdunk** [comment]
@mholt The main motivation for this issue was to see if a PR implementing cancellable events was likely to get merged. I'm happy for you to close this if you think that's unlikely 🙂

**Comment by mholt** [comment]
Hmm, well, I don't think it's convincingly motivated at this point -- so, probably not, sorry. Especially since the `ask` feature can do what you want with pretty minimal effort I think.
