### ISSUE TITLE
http.browse: missing right padding/margin

### ISSUE THREAD

**Issue by MichaelSchmidle** [mholt/caddy#2179]
### 1. What version of Caddy are you using (`caddy -version`)?
v0.11.0

### 2. What are you trying to do?
I am using Caddy as a static file server with activated [directory listing (``browse``)](https://caddyserver.com/docs/browse).

### 3. What is your entire Caddyfile?
```text
{$TRAEFIK_HOST}:80 {
    root /var/www/html
    browse
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
With Docker Compose as per https://github.com/MichaelSchmidle/wapps/tree/master/get.

### 5. Please paste any relevant HTTP request(s) here.
—

### 6. What did you expect to see?
I expected to see the same rendering of the directory index in all browsers like in this screenshot of Chrome: 
![image](https://user-images.githubusercontent.com/552446/40439908-aa4aff92-5ebc-11e8-8b8c-4fdc0e56b086.png)

### 7. What did you see instead (give full error messages and/or log)?
I saw different rendering of the directory index depending on browser like in this screenshot of Firefox: 
![image](https://user-images.githubusercontent.com/552446/40439952-ca479378-5ebc-11e8-963b-900b0f8c8bb6.png)

**Note how the timestamp on the right do not have any right padding/margin.**

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Simply run Caddy to serve files from a directory without index file (like index.html) and activate the directory listing (i.e. add the ``browse`` directive to the Caddyfile as in the example above).

**Comment by magikstm** [comment]
Related to #1952 and #1954.

**Comment by hartwork** [comment]
Here is minimal (not-)working example to see the issue in action in Firefox (but not in Chromium) for download: [padding_right_issue_demo_firefox.htm](https://github.com/mholt/caddy/files/2193600/padding_right_issue_demo_firefox.htm.txt)
Not it needs a rename from `.txt.htm` to `.htm` after download.

**Comment by francislavoie** [comment]
I can confirm this issue on Firefox Linux.
