### ISSUE TITLE
Use environment variable for directive 'root' as the document path not working

### ISSUE THREAD

**Issue by delapecci** [mholt/caddy#2180]
My caddy version is Caddy 0.11.0 (non-commercial use only) on my MacOS High Sierra
I would set the root path using environment variables, likes:

```text
hardcore.local {
  root {$SITEROOT1}
}
```
then I set the environment:
```shell
export SITEROOT1=/home/caddy/site/root1
```
and start caddy:
```
caddy -conf /home/caddy/Caddyfile -log stdout
```
![image](https://user-images.githubusercontent.com/2783025/40466040-589f91ea-5f56-11e8-905c-cdd7367cf17e.png)
but when I open http://hardcore.local, got 404
![image](https://user-images.githubusercontent.com/2783025/40466114-97f3521e-5f56-11e8-9cd9-52167bf7be06.png)

**Comment by mholt** [comment]
What's `ls /home/caddy/site/root1` show?

**Comment by delapecci** [comment]
@mholt Hi, thanks for ur quick response, this is not issue, it was my miss, I use sudo start caddy without setting the env variable SITEROOT1 for root user, -_-!!
