### ISSUE TITLE
Strange behavior with documentation example

### ISSUE THREAD

**Issue by MOZGIII** [mholt/caddy#2183]
### 1. What version of Caddy are you using (`caddy -version`)?
`Caddy 0.11.0 (non-commercial use only)`, amd64

### 2. What are you trying to do?
Use a documentation sample to host a server on both HTTP and HTTPS.

From [here](https://caddyserver.com/docs/http-caddyfile#addresses):
```
example.com              # Host: example.com; Ports: 80->443
```

Instead of working as expected, it does something else (see below).
Other domain names / tls configurations have the same issue.

### 3. What is your entire Caddyfile?
```text
example.com

log stdout
errors stdout

tls self_signed
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Ubuntu 16.04.

I have a dir with `Caddyfile`. I `su` as root and do (from that dir):

```shell
# caddy 
Activating privacy features... done.
https://example.com:2015
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```

### 5. Please paste any relevant HTTP request(s) here.

Not relevant.

### 6. What did you expect to see?

Documentation explicitly states that caddy will listen on two ports (443 & 80), and not port 2015.

Something like this in the `caddy` command output:
```shell
Activating privacy features... done.
https://example.com
http://example.com
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```

### 7. What did you see instead (give full error messages and/or log)?

```shell
Activating privacy features... done.
https://example.com:2015
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with "ulimit -n 8192".
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Just use the provided `Caddyfile` - it's a simplified version of what I actually have.

**Comment by tobya** [comment]
When you use your own cert the autohttps does not kick in.  The examples specify that AutoHTTPS is presumed to apply.

You need to specify :443 in this instance.

    example.com:443

     log stdout
     errors stdout

     tls self_signed

of dont use a self_signed cert.

**Comment by MOZGIII** [comment]
If I specify `example.com:443`, it won't listen on port `80`, right?
I want it to listen on both ports, and serve http/https traffic.

**Comment by tobya** [comment]
Thanks for the issue.  This is not the way caddy works.  It works a specific way with autoHTTPS, if you are not using autoHTTPS you are responsible for the redirect yourself, it is very easy to do.

    example.com:80 {
     redir https://example.com
     }

    example.com:443 {
      tls self_signed
      #other directives
    }

This is the way that caddy works for tls and autoHTTPS.
