### ISSUE TITLE
Confusion about the license

### ISSUE THREAD

**Issue by spekulatius** [mholt/caddy#2185]
Hello @mholt 

Thanks for developing Caddy! It looks very cool and I'm keen to try it out. Before I go down this road more I would like to find out if I can use it for my business. Sorry if I ask something that has been discussed before somewhere. I had a look around the issues and couldn't find a more information. 

I'm confused about the license - on the website it suggests that commercial usage is only with a monthly license possible https://caddyserver.com/products/licenses while the license file here on github looks like a commercial usage is possible https://github.com/mholt/caddy/blob/master/LICENSE.txt

Is this the typical modal of paid support or do I misread this? I've seen a conversation around this on Twitter too - so I guess I'm not the only one.

It would be great if you could share some more light on this.

Cheers,
Peter

**Comment by abiosoft** [comment]
Commercial use is prohibited **only** if downloaded from https://caddyserver.com/download. But it is allowed if you build from source.

**Comment by spekulatius** [comment]
Ah okay, that makes sense. Cheers

**Comment by mholt** [comment]
Yep, these are good questions. The FAQ on the licenses page answers them:

> Which license do I need?
> If your company uses official Caddy binaries internally, in production, or distributes Caddy, a commercial license is required. This includes companies that use Caddy for research. The personal license is appropriate for academic research, personal projects, websites that aren't for profit, and development at home.
> 
> Is Caddy open source?
> Yes, it is. Caddy's source code is licensed under Apache 2.0, which requires attribution and stating changes made to the code when forking it, using it in your own projects, or distributing it. This website distributes official, compiled Caddy binaries, which are licensed differently.
> 
> Does this license apply to the source code?
> These licenses do NOT apply to the source code. If you use Caddy source code in your work or product, you must give attribution and state all changes. Please email us if you would like to purchase a custom license to the source code, which can waive these requirements!
>
> If I build Caddy from source, which license applies?
> The source code is Apache 2.0 licensed. It requires that you give attribution and state changes. Building from source does not give you permission to white-label Caddy in your own work. You will also have to manage Caddy plugins on your own.

It's similar to how vscode and Microsoft Visual Studio Code, OpenJDK and OracleJDK, etc, are licensed. Open source project but commercial finished product.

**Comment by spekulatius** [comment]
Hello @mholt 

thanks for clearing this up a bit more. I missed the FAQ part under the pricing table. 

I also just found the startup pricing model. A bit more attractive for me. I'll see if I can fit this in.

Cheers,
Peter
