### ISSUE TITLE
Allow specifying a proxy for certificate generation

### ISSUE THREAD

**Issue by orenyomtov** [mholt/caddy#2186]
Hey,

Loving ease of use of Caddy so far, and finally I found something that Caddy can't currently do.

Let's say the Caddy server is behind a firewall which doesn't allow arbitrary outside communication (but incoming traffic passes through via a load balancer/reverse proxy).

But the local network does offer an internal socks5 proxy which can communicate with the outside world.

In such a scenario, Caddy won't be able to communicate with the Let's Encrypt servers.

I would like to be able to specify a proxy that Caddy will use for all its certificate generation communication (including DNS Challenges).

If someone can point me in the right direction on how to implement such a feature, I might be able to even pull it off myself.

Cheers,
Oren

**Comment by mholt** [comment]
Does HTTP(S)_PROXY support SOCKS5 yet? https://github.com/golang/go/issues/18508 -- might be something to look into, because it's possible that it might already be supported.

**Comment by orenyomtov** [comment]
I didn't think about HTTP(S)_PROXY, but looks like it is working (a socks5 proxy was made available on localhost:1080):
```bash
HTTPS_PROXY=socks5://localhost:1081 caddy 
Activating privacy features... 2018/05/28 19:54:56 making ACME client to get ToS URL: get directory at 'https://acme-v02.api.letsencrypt.org/directory': failed to get json "https://acme-v02.api.letsencrypt.org/directory": Get https://acme-v02.api.letsencrypt.org/directory: proxyconnect tcp: dial tcp [::1]:1081: connect: connection refused

HTTPS_PROXY=socks5://localhost:1080 caddy
Activating privacy features... 

Your sites will be served over HTTPS automatically using Let's Encrypt.
...
```

**Comment by mholt** [comment]
Uhhh haha I'm not gonna make any guarantees about that since I haven't put much thought into supporting it and it's not in our docs, but I do believe that any Go transport using ProxyFromEnvironment (the vast majority of them in Caddy, if not all of them) will use it.

**Comment by orenyomtov** [comment]
Alright, thank you for the quick responses!
