### ISSUE TITLE
caddy -quic not working

### ISSUE THREAD

**Issue by delinage** [mholt/caddy#2190]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0

### 2. What are you trying to do?
Use -quic function

### 3. What is your entire Caddyfile?
```
:11220 {
    gzip
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Server: caddy.exe -quic 
Client: chrome with quic option enabled

### 6. What did you expect to see?
QUIC packets in wireshark

### 7. What did you see instead (give full error messages and/or log)?
TCP packets

Why isn't QUIC option using QUIC packets?

**Comment by mholt** [comment]
Probably because our QUIC lib has not been updated in a while, see here: https://github.com/mholt/caddy/issues/2194
