### ISSUE TITLE
Bind to Unix socket

### ISSUE THREAD

**Issue by AliveDevil** [mholt/caddy#2192]
I'd like to request the feature to bind to unix sockets.

Technical background for this feature request:
* Master Caddy-server handling SSL-certificates running under www-data, connecting to unix sockets as proxies
* Per-User Caddy-instances running under the user account with sockets being accessible to www-data:www-data

Following things would be great for bind configuration:
> bind &lt;host&gt;

Binds to TCP

> bind unix://path <user>:<group> umask

Binds to Unix path with owner being `user:group` with permission `umask`. This feature is only available to Unix-like systems as Windows does not allow sockets.

Using Unix sockets should automatically disable all HTTPS-functionality.

As I'm not comfortable with Go I cannot add this functionality by myself.

**Comment by theodesp** [comment]
There are actually 2 main parts here:
1. Using Caddy as a client. For example, dialing into a Unix socket
2. Start a Caddy server instance and bind to Unix Domain Socket

**Comment by francislavoie** [comment]
Is this what you're looking for? https://caddyserver.com/docs/net

**Comment by theodesp** [comment]
It's not actually the same as Unix Domain Sockets bind with permissions also. But the approach to have a `host` or `server` directive is flexible as it will allow binding to different types of connections.

**Comment by mholt** [comment]
Binding to unix socket is possible with Caddy 2.
