### ISSUE TITLE
failed to get certificate: acme: Error 403

### ISSUE THREAD

**Issue by purplehorse** [mholt/caddy#2193]
I have last version of Caddy on Windows.

My caddy file it's just:

`matt.life
`

And when I run caddy.exe (in a cmd with administrator credentials) I get:

`Activating privacy features... 2018/06/06 10:27:54 [matt.life] failed to get certificate: acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Invalid response from http://matt.life/.well-known/acme-challenge/icmlZULzOHulTgNJkCTvUrAWbJEbmdz0fs7e2SzEU0E [2604:a880:2:d0::2e7f:8001]: 404`

**Comment by mholt** [comment]
Yeah, you have to use your own domain name, you can't get a certificate for my domain. :)

**Comment by zrzs** [comment]
@mholt but i used my domain but failed,the logs are same
![image](https://user-images.githubusercontent.com/11783334/42615795-52f606da-85de-11e8-9a87-807be3173ddd.png)

**Comment by francislavoie** [comment]
@zrzs make sure you're not running another server which is intercepting the traffic

**Comment by zrzs** [comment]
@francislavoie ngnix
