### ISSUE TITLE
Caddy TLS Certificate

### ISSUE THREAD

**Issue by purplehorse** [mholt/caddy#2196]
I have created my own certificate:

![image](https://user-images.githubusercontent.com/39902415/41148073-556f03d0-6b08-11e8-8d02-05c8d0bfef24.png)

I have used this certificate in my caddyfile:

![image](https://user-images.githubusercontent.com/39902415/41147791-9ff2c37a-6b07-11e8-91e6-8d8309c78aec.png)

I have loaded this certificate to Google Chrome:

![image](https://user-images.githubusercontent.com/39902415/41147894-da9d5418-6b07-11e8-901c-5ea394149e27.png)

But when I try to access from Google Chrome:

![image](https://user-images.githubusercontent.com/39902415/41147980-0f1f5222-6b08-11e8-8273-a57ded39dd2f.png)

why isn't Caddy working with tls and certificates?

**Comment by mholt** [comment]
Well, Caddy is working fine with TLS and certificates. I think you need to add the CA/signing authority public key to your trust store, not the site's certificate itself, but I also don't read that language so I don't really know what I'm looking at, sorry. :)

You can try asking on https://caddy.community for an answer to your question.
