### ISSUE TITLE
feature: compile time configuration file

### ISSUE THREAD

**Issue by sobolevn** [mholt/caddy#2197]
Hi, thanks for this awesome software!

We are using `caddy` in production for almost a year now. It works like a charm.
However, there's a thing that bothers me: compilation step. Let me explain. 

First of all, we all know that `telemetry` was a widely discussed topic all around `caddy` community.
I like it for some projects (as some kind of simple monitoring tool), but I surely won't enable it for all of my projects.

Secondly, plugins. I mostly don't use them. But sometimes I really need `http.expires` and `http.cache` plugins.

We also use `docker` for mostly all of our projects.  So, we need to build `docker` image with compiled `caddy` inside it. And that's does not work the way it should work.

Here's an example on how to disable `telemetry`:

```bash
# telemetry
run_file="/go/src/github.com/mholt/caddy/caddy/caddymain/run.go"
line=$(awk '/const enableTelemetry = true/{print NR}' $run_file)
if [ "$line" ] && [ $TELEMETRY = "false" ]; then
    sed -i.bak -e "${line}d" $run_file
    cat > "$run_file.disablestats.go" <<EOF
    package caddymain
    import "os"
    var enableTelemetry = $TELEMETRY
    func init() {
        switch os.Getenv("ENABLE_TELEMETRY") {
        case "0", "false":
            enableTelemetry = false
        case "1", "true":
            enableTelemetry = true
        }
    }
EOF
fi
```

It is taken from here: https://github.com/abiosoft/caddy-docker/blob/master/builder/builder.sh#L15-L33

Also, we can not just add plugins into the app with a simple configuration. We have to do some very complex stuff.

It could be something like (my wild guess):

```yaml
plugins:
  - http.cache 
  - http.expires

telemetry: off
```

So, my question is: do you plan to support some kind of compile time configuration to make it easier to build `caddy` with some plugins and switching off features that are not needed for the specific setup?

Thanks!

**Comment by mholt** [comment]
Well, that's kind of what our build server does for you. 🙃You're of course welcome to use that (given the proper licensing) and then your custom Caddy build is just a GET request away.

**Comment by sobolevn** [comment]
Oh, I see. That's a paying-users-only feature.

**Comment by mholt** [comment]
No, you can use it here: https://caddyserver.com/download

If you're using Caddy commercially, then yes, there are commercial licenses available.
