### ISSUE TITLE
curl download size with gzip is bigger than curl download size without gzip

### ISSUE THREAD

**Issue by sugizo** [mholt/caddy#2198]
### 1. What version of Caddy are you using (`caddy -version`)?
```
$ ./caddy -version
Caddy 0.11.0 (non-commercial use only)
```

### 2. What are you trying to do?
using gzip

### 3. What is your entire Caddyfile?
```text
*:8080 {
    root /Users/sugizo/Downloads/www
    gzip {
        level 9 # tested level 1 till 9 got the same result = 49, bigger than 31 (curl without gzip)
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
$ ./caddy -conf ~/Downloads/Caddyfile
```

### 5. Please paste any relevant HTTP request(s) here.

```
$ curl http://localhost:8080 --silent --write-out "%{size_download}\n" --output /dev/null
31
$ curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
49
$ curl http://localhost:8080 --compressed --silent --write-out "%{size_download}\n" --output /dev/null
49
```

### 6. What did you expect to see?
size download is smaller when using gzip compressed than the curl without using gzip compressed

### 7. What did you see instead (give full error messages and/or log)?
```
$ curl http://localhost:8080 --silent --write-out "%{size_download}\n" --output /dev/null
31
$ curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
49
$ curl http://localhost:8080 --compressed --silent --write-out "%{size_download}\n" --output /dev/null
49
```

downloaded size using gzip = 49, expected is smaller than 31 (without using gzip compressed)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

```
$ cd ~/Downloads
$ curl -L -o caddy.zip -C - https://caddyserver.com/download/darwin/amd64?license=personal&telemetry=off
$ unzip caddy.zip caddy
$ mkdir -p ~/Downloads/www
$ cat << EOF > ~/Downloads/www/index.html
<html><body>work</body></html>
EOF
$ cat << EOF > ~/Downloads/Caddyfile
*:8080 {
    root /Users/sugizo/Downloads/www
    gzip {
        level 9 # tested level 1 till 9 got the same result = 49, bigger than 31 (curl without gzip)
    }
}
EOF
$ ./caddy -conf ~/Downloads/Caddyfile
```
tested without gzip compressed
```
$ curl http://localhost:8080 --silent --write-out "%{size_download}\n" --output /dev/null
```
tested with gzip compressed
```
$ curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
or
$ curl http://localhost:8080 --compressed --silent --write-out "%{size_download}\n" --output /dev/null
```

**Comment by sugizo** [comment]
another test with picture (above is just plain html text), got the same result size is equal not compressed
**expectation** 
the image size curl with gzip is smaller than curl without gzip compression
```
$ ls -la ~/Downloads/www/test.png 
-rw-r--r--  1 sugizo  staff  6849 Dec 14  2012 /Users/sugizo/Downloads/www/test.png
$ curl http://localhost:8080/test.png --silent --write-out "%{size_download}\n" --output /dev/null
14
$ curl http://localhost:8080/test.png --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
14
$ curl http://localhost:8080/test.png --compressed --silent --write-out "%{size_download}\n" --output /dev/null
14
```

**Comment by magikstm** [comment]
.png files are already compressed by an algorithm and file size may vary a bit (up or down), but it isn't a file that is recommended to be compressed. .png files are lossless.

I would suggest using .jpg (a lossy format) instead of .png if a small quality loss is acceptable.

Ref:
- https://stackoverflow.com/questions/11289369/why-png-size-doesnt-change-after-using-http-gzip-compression?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
- https://developers.google.com/speed/docs/insights/OptimizeImages

**Comment by sugizo** [comment]
same result for *.jpg and *.png, not sure, the file size is different (check using ls -la), but the curl download size is same = 14 (for both (*.jpg and *.png) ), those file is definitely different in both size and content
```
$ ls -la ~/Downloads/learn/www/test.jpg 
-rw-------  1 sugizo  staff  2599708 Sep  1  2012 /Users/sugizo/Downloads/learn/www/test.jpg
$ curl http://localhost:8080/test.jpg --silent --write-out "%{size_download}\n" --output /dev/null
14
$ curl http://localhost:8080/test.jpg --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
14
$ curl http://localhost:8080/test.jpg --compressed --silent --write-out "%{size_download}\n" --output /dev/null
14
```

**Comment by magikstm** [comment]
.jpg, .png and a few other file types shouldn't be gzipped as it bring minimal benefit in file size (if any) and it may make these files bigger.

There are other strategies to reduce file size on these files:
- Strip metadata (exif data)
- Reduce quality
- Etc.

I would suggest using another tool to reduce image sizes such as [ImageMagick](https://github.com/ImageMagick/ImageMagick).

It can be used by script, so can be ran in batch on folders.

**Comment by sugizo** [comment]
agree, better to reduce image sizes (optimize images), rather than using gzip, thx for detail explaination, btw is it normal for my first comment about html file size ?
the html file size is bigger when using curl gzip compression : **49** while the same html file size is **31** when test without gzip 
**no 5 & 7** in my first issue above

**Comment by magikstm** [comment]
There is a small overhead when using gzip compression. That small overhead may make some file bigger occasionnally if there's not enough gain when compressing them.

It may be what is happening with the html file in no 5 & 7.

**Comment by magikstm** [comment]
You could reduce that effect by using gzip's `min_length` parameter.

Ref: https://caddyserver.com/docs/gzip

**Comment by sugizo** [comment]
not sure how gzip work in caddy, tested using html file (first comment above)
- tested using level 1 till 9 got the same result (curl with or without compressed)
- tested with min_length parameter never got the value under the curl without gzip

**without min_length**
```
cat << EOF > ~/Downloads/learn/Caddyfile
*:8080 {
    root /Users/sugizo/Downloads/learn/www
    gzip {
        #level 9 # tested level 1 till 9 got the same result
        #min_length 1
    }
}
EOF
./caddy -conf ~/Downloads/learn/Caddyfile
```

```
$ curl http://localhost:8080 --silent --write-out "%{size_download}\n" --output /dev/null
31
$ curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
49
```

**min_length = 1**
```
cat << EOF > ~/Downloads/learn/Caddyfile
*:8080 {
    root /Users/sugizo/Downloads/learn/www
    gzip {
        #level 9 # tested level 1 till 9 got the same result
        min_length 1
    }
}
EOF
./caddy -conf ~/Downloads/learn/Caddyfile
```

```
$ curl http://localhost:8080 --silent --write-out "%{size_download}\n" --output /dev/null
31
$ curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
49
```

**min_length = 1000000000000000000**
```
cat << EOF > ~/Downloads/learn/Caddyfile
*:8080 {
    root /Users/sugizo/Downloads/learn/www
    gzip {
        #level 9 # tested level 1 till 9 got the same result
        min_length 1000000000000000000
    }
}
EOF
./caddy -conf ~/Downloads/learn/Caddyfile
```

```
$ curl http://localhost:8080 --silent --write-out "%{size_download}\n" --output /dev/null
31
$ curl http://localhost:8080 --silent -H "Accept-Encoding: gzip,deflate" --write-out "%{size_download}\n" --output /dev/null
31
```

**Comment by theodesp** [comment]
FYI Caddy uses https://golang.org/pkg/compress/gzip/ internally
