### ISSUE TITLE
Add a CI server

### ISSUE THREAD

**Issue by groob** [mholt/caddy#22]
drone.io is free for open source projects.

**Comment by gsquire** [comment]
https://travis-ci.org/ is also a popular site for open source.

**Comment by mholt** [comment]
:+1: Will do, especially once I get more tests in place. There's some refactoring that has to happen first (unless I want to rewrite the tests later...) which will happen as soon as I get my feet back under me.

**Comment by avelino** [comment]
+1

**Comment by mholt** [comment]
Also looking into integrating https://coveralls.io

**Comment by mholt** [comment]
Okay, using Travis CI. Thanks for the suggestion @groob!
