### ISSUE TITLE
Simple Output Feature Request

### ISSUE THREAD

**Issue by tracker1** [mholt/caddy#2207]
Given the use case of pretty much a static http(s) service, I'm wondering if there is an option, and if not if it could be added to be able to specify an output for a specific path?

For example, I have a React application, where I want a hosting application in a container just to serve the application and its' content files.  However, I want to be able to specify an API_HOST environment variable, then when the application does an XHR/fetch for "/api-host"  I can have the caddy server simply return that single environment variable.

Ideally, a `write` option similar to `rewrite` ...

```
write {
  if {path} is /api-host
  send "{API_HOST}"
}
```

maybe an option to set the return type... or maybe a simple JSON encode.  I'm not really sure... just really wanting a very lightweight http server, where I can have it default to returning index.html instead of a 404.  And use one environment variable to let the app know where an API endpoint is.

**Comment by mholt** [comment]
This is implemented in Caddy 2 as the static responder.
