### ISSUE TITLE
FCGI variables PATH_INFO, SCRIPT_NAME, and possibly others contain incorrect values.

### ISSUE THREAD

**Issue by CMB** [mholt/caddy#2208]
In my caddyfile, I have an entry like this:

http://myhost:8080 {
...
fastcgi /fcgi unix:/run/caddy/fcgi.sock
}

There's a simple fastcgi application started with spawn-fcgi listening
on that socket.  It's just an echo service that echos environment variables
and request data.

The application is reachable using http://myhost:8080/fcgi/fcgiecho.
The binary is at /srv/http/myhost/fcgi/fcgiecho.
However, I see some surprising values for SCRIPT_NAME and PATH_INFO:

PATH_INFO=/fcgi/fcgiecho

SCRIPT_NAME=/

SCRIPT_FILENAME=/srv/http/myhost

I've tried with both v0.11.0 and the latest from git.
With v0.11.0, only PATH_INFO and SCRIPT_NAME were incorrect.
SCRIPT_FILENAME was what I would expect it to be:
/srv/http/myhost/fcgi/fcgiecho.  SCRIPT_FILENAME is just incorrect when
running from master.

**Comment by mholt** [comment]
Hi, can you fill out the issue template please, so we can help you? Then re-open the issue. Thanks. :)
