### ISSUE TITLE
Caddy can't write host logfiles.

### ISSUE THREAD

**Issue by M4lik** [mholt/caddy#2209]
Caddy can't write host logfiles if the owner of the file is not `www-data` (or the user which caddy is run as).
In this config caddy runs with `www-data:www-data`

```
root@myhost: /var/log/caddy ls -la
drw-rw-r--  2 root www-data   4096 Jun 25 09:34 .
drwxrwxr-x 12 root syslog     4096 Jun 25 09:31 ..
-rw-rw-r--  1 root www-data   4841 Jun 25 09:14 caddy.log
-rwxrwxrwx  1 root www-data      0 Jun 24 18:04 mydomain.yay.log
```

Usually I have set the permissions of `mydomain.yay.log` to 664 (like `caddy.log`).
The interesting part is, that caddy CAN write to caddy.log but not to `mydomain.yay.log` (See **4.**)

I've noticed this as I wanted to setup log files correctly and created a logrotate config. Usually logrotate is a little bit up set if you don't set the su parameter correctly. The intended ownage of logfiles is one of these:

- `root:root`
- `root:adm`
- `syslog:adm`
- `root:APPLICATION_GROUP`

### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (non-commercial use only)

### 2. What are you trying to do?
Start caddy server

### 3. What is your entire Caddyfile?
```text
mydomain.yay {
  root      /var/www/mydomain.yay
  fastcgi   / unix:/var/run/php/php7.0-fpm.sock php 
  log       / /var/log/caddy/mydomain.yay.log {combined}                                                                                    
  gzip
  rewrite {
    if {path} not_match ^\/wp-admin
     to {path} {path}/ /index.php?{query}
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
via a caddy.service file
```text
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target

[Service]
Restart=on-abnormal

; User and group the process will run as.
User=www-data
Group=www-data

; Letsencrypt-issued certificates will be written to this directory.
Environment=CADDYPATH=/etc/ssl/caddy

; Always set "-root" to something safe in case it gets forgotten in the Caddyfile.
ExecStart=/usr/local/bin/caddy -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp -log=/var/log/caddy/caddy.log
ExecReload=/bin/kill -USR1 $MAINPID

[Install]
WantedBy=multi-user.target

```

### 5. Please paste any relevant HTTP request(s) here.
none

### 6. What did you expect to see?
Caddy starting

### 7. What did you see instead (give full error messages and/or log)?
```text
Jun 25 10:02:21 murdock systemd[1]: Started Caddy HTTP/2 web server.
Jun 25 10:02:21 murdock caddy[25445]: Activating privacy features... done.
Jun 25 10:02:21 murdock caddy[25445]: 2018/06/25 10:02:21 open /var/log/caddy/mydomain.yay.log: permission denied
Jun 25 10:02:21 murdock systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
Jun 25 10:02:21 murdock systemd[1]: caddy.service: Unit entered failed state.
Jun 25 10:02:21 murdock systemd[1]: caddy.service: Failed with result 'exit-code'.
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

1. run `sudo mkdir -p /var/log/caddy && sudo chmod -R 664 /var/log/caddy && sudo chown -R root:www-data /var/log/caddy`
2. Create a caddy file like the one in **3.**
3. Create a service file under /etc/systemd/system/ with the content from **4.**
4. run `sudo systemctl daemon-reload && sudo systemctl start caddy.service`

**Comment by M4lik** [comment]
Ok, seems like I'm was just too tired for linux permissions :sweat_smile: The actual problem was that caddy didn't have execute permissions on this directory (`/var/log/caddy`).

Sorry for the inconvenience.

**Comment by harshrathod50** [comment]
In my case I didn't even create the logging folder 🤣:

```bash
mkdir /var/log/caddy
chown caddy:caddy /var/log/caddy
```
