### ISSUE TITLE
Env var parsing in Caddyfile

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#2213]
### 1. What version of Caddy are you using (`caddy -version`)?
latest master

### 2. What are you trying to do?
using Env var inside the config

### 3. What is your entire Caddyfile?
export LOG="log stderr"
```text
http://localhost:2015 {
    root /home/miek/html/test

    {$LOG}
    errors stderr
}
```
This errors with:
~~~
% export LOG='log stderr'  
% echo $LOG 
log stderr
% ./caddy -conf test 
2018/06/29 21:24:00 test:4 - Error during parsing: Unknown directive '{$LOG}'
~~~
It's non-obvious from the [docs](https://caddyserver.com/docs/caddyfile#env) that this doesn't work as advertised.

**Comment by mholt** [comment]
Hmmm... 🤔 Yeah we should take a look at this. I'll try to get to it soon, or if someone else wants to jump in, go for it! Just claim it here or in a PR.

**Comment by francislavoie** [comment]
If this is implemented it would simplify https://github.com/mholt/caddy/issues/1235 for me, so 👍 from me 😄

**Comment by darshanime** [comment]
I can work on this please.

**Comment by mholt** [comment]
Please do; would love it if you could!

**Comment by theodesp** [comment]
It looks like that test case was not covered:

https://github.com/mholt/caddy/blob/053373a38519d8cdf4ee7582ed9dc6ce239597cc/caddyfile/parse_test.go#L451

**Comment by mholt** [comment]
@miekg I just noticed that your use case is attempting to replace a single env variable with a whole line of config, but the docs _do_ clarify:

> A single environment variable does not expand out into multiple tokens, arguments, or values.

So, what is it you're asking for here exactly?

**Comment by miekg** [comment]
as @darshanime says, having an env var *do* expand to multiple token would be nice.

failing that I think the documentation could use an example that says: so this aint going to work.
