### ISSUE TITLE
Merge to the master branch of QUIC-GO

### ISSUE THREAD

**Issue by railjty** [mholt/caddy#2218]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11

### 2. What are you trying to do?
Add gQUIC 42 and 43 to use quic in Chrome Canary(newest)

### 3. What is your entire Caddyfile?
```text
(paste Caddyfile here)
```
There is no need of Caddyfile
### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy -quic -http2 

### 6. What did you expect to see?

Chrome Canary(newest) can use quic 43 with caddy
### 7. What did you see instead (give full error messages and/or log)?

It use TLS

**Comment by mholt** [comment]
We need to fix this first: https://github.com/lucas-clemente/quic-go/issues/1353

It's already on the to-do list, but not a priority right now as I've been really busy with other stuff.
