### ISSUE TITLE
If rewrite expression not a REGEX, should caddy assume it is a file path?

### ISSUE THREAD

**Issue by kjk** [mholt/caddy#2219]
Using latest caddy on mac from homebrew:
```
$ caddy -version
Caddy 0.11.0 (unofficial)
```

It seems like at some point a change in Caddy broke parsing of Caddyfile (I upgraded Caddy but not Caddyfile).

But this bug is about some error messages from parsing Caddyfile not being helpful:
```
$ caddy -validate
2018/07/09 13:38:40 error parsing regexp: invalid nested repetition operator: `++`
```

The error message should be more verbose like: `error parsing Caddyfile line ${lineNo} '${lineContent', error parsing regexp...`

As it stands today, I had to guess that the error was from parsing Caddyfile and then had to guess which part of the file is incorrect.

Good error message are already happening for some parsing errors e.g. with a line like:
```
rerite "/article/11t/c-interfaces-and-implementations.html" "/blog/11t.html"
```
I get a good error message:
```$ caddy -validate
2018/07/09 13:49:55 Caddyfile:384 - Error during parsing: Unknown directive 'rerite'
```

As to parsing error itself, it looks like a bug.

The clue is info about `++`. The only instance of `++` in the file is:
```
rewrite "/tag/c++" "/blog/archives-by-tag-cplusplus.html"
```
Removing this line fixes the issue.

The doc says that in `rewrite from to`, `from` is either an exact path or regular expression.

If parsing `from` as regular expression fails, it should be considered an exact path, not an error.

**Comment by mholt** [comment]
> If parsing from as regular expression fails, it should be considered an exact path, not an error.

Hmm, I disagree: I think errors should be explicit. @abiosoft does `rewrite` return parse errors from the dispenser when parsing regular expressions?

As for the missing line numbers, that's strange -- we _used_ to have line numbers on parse errors... 🤔

**Comment by francislavoie** [comment]
Should be easy to escape the string like this: `"/tag/c\+\+"`

**Comment by kjk** [comment]
Not to mention this is a backwards-incompatible change to a core functionality.

This seems to be caused by https://github.com/mholt/caddy/commit/9fe2ef417c933efaa5d4ee79821428d84ad15b9c

**Comment by francislavoie** [comment]
https://stackoverflow.com/a/695467

`+` is not a URL-safe char.

**Comment by kjk** [comment]
@francislavoie If I knew the regular syntax in question, I'm pretty sure it's an NP problem. Since I don't know it, it's an impossible problem.

And caddy is more than happy to accept '+' otherwise, for example this is valid:
```
rewrite "/articles/go-cookbook.html+" "/book/go-cookbook.html"
```

**Comment by francislavoie** [comment]
Re: BC break, quoting from @abiosoft https://github.com/mholt/caddy/pull/2082#issuecomment-381381228

> it is not 100% backward compatible, from is now with regex support.

> My argument is that the one-liner should be a sensible default and people should only open a config block for more control, but what is currently happening is no one is using the one liner and many people open a config block to only use regex.

Another suggestion, since you're autogenerating these, switch to this syntax for each rewrite:

```Caddyfile
rewrite "/tag/c++" {
    to "/blog/archives-by-tag-cplusplus.html"
}
```

**Comment by kjk** [comment]
Finally, let me appeal to your own self-interest.

Other people will hit this problem because what I did is both intuitive and correct based on my reading of rewrite docs.

Some of those people will come back here to file bugs or to support forum asking why this doesn't work.

It'll come back to you as never ending support burden.

You can keep explaining why it works this way or you can make a simple fix to conform to people's expectations.

**Comment by abiosoft** [comment]
> Not to mention this is a backwards-incompatible change to a core functionality.

@kjk This is intended as it serves wider audience. I believe the breaking change was communicated in the release. In fact, you are the first real user of the exact match I have come across, the opposite has always been the case, people wanting regex with claims that the exact match is too limiting.

If you consider that converting any path to exact match is by surrounding with `^$` and the fact that most users prefer regex, you'd realise the decision is made with users in consideration.

I agree that the documentation can be better. The following should work for your example. What makes your case a bit challenging is due to the `+` character.
```
rewrite "^/tag/c\+\+$" "/blog/archives-by-tag-cplusplus.html"
```
As mentioned, `+` is actually not a safe character for URL. You probably have your reasons for this but I think it is safer to use something else.

**Comment by tobya** [comment]
I will close this now but please feel free to continue the discussion.
