### ISSUE TITLE
Suggestion: Command line flag for "browse"

### ISSUE THREAD

**Issue by kkovacs** [mholt/caddy#222]
It would be nice to have a command line flag to turn on "browse".

I often use caddy to quickly transfer files from one computer to another, and to have browsing functionality, I have to start it for example: 

	echo "0.0.0.0:2015\nbrowse" | caddy

It would be better just to write

	caddy -b

or similar :)

Keep up the good work!

**Comment by mholt** [comment]
Thanks. I agree it could be even easier to spin up certain features directly from the command line. Will take a look at this!

**Comment by kkovacs** [comment]
Thank you, Matt!

**Comment by shazow** [comment]
+1, I was thinking maybe a set of predefined configs that we can call "modes"  or something. Something like:

```
$ caddy -mode browse
```

I suspect there will be at least a few common scenarios that people will want, but browse is probably the most common indeed.

**Comment by mholt** [comment]
^ That's a good idea. Let's assume caddy can build its own internal, ephemeral Caddyfile based on command line inputs like this (this example shows all available keywords):

```
$ caddy --enable browse,errors,gzip,log,markdown,templates
```

would produce this Caddyfile internally:

```
0.0.0.0:2015
browse
errors error.log
gzip
log
markdown /
templates
```

But of course, you could do just `caddy --enable browse` which only turns on the "browse" directive. I haven't examined the plausibility of this, but it seems very useful as you've said. Feel free to refine this idea further.

Anyone is also welcome to get started on it before I do. Probably wouldn't be too hard; there's a function in main.go called loadConfigs which might be a good place to start.

**Comment by shazow** [comment]
Maybe this deviates too much from the Caddyfile format, but could support these as normal command args, like `caddy [enable...]`

```
$ caddy browse
$ caddy browse errors=error.log gzip
```

Ideally the Caddyfile format would be perfectly backwards compatible, except one argument per arg (quoted if necessary) rather than one argument per line. Might make sense to make the Caddyfile format also work with =, then. Such as:

```
browse
errors=error.log
gzip
```

Maybe taking this too far, though. :)

**Comment by mholt** [comment]
Adapting your idea slightly, consider:

```
$ caddy "browse, errors error.log, gzip, header { ... }, "
```

We can leave the Caddyfile syntax the same but when parsing it from the command line like this, we just replace commas with newlines, and presume the address is the default. It'll work only for one listener (the default, unless modified by -host or -port flags) but it'll get you up and running quickly:

```
$ caddy browse
```

How about that?

**Comment by shazow** [comment]
What's the benefit of bundling all the options into one big argument string, rather than separate ones? Could even stick with no = if that's what's bothersome (now that I think of it, that addition is superfluous anyways—it just reads a bit better in the cli).

```
$ caddy "browse" "errors error.log" "gzip" "header"
```

Quoting an argument merges into one Arg slot, so it'll be really easy to parse. Quoting is optional if it's just one thing, so:

```
$ caddy browse
```

will still work as desired; as will

```
$ caddy browse gzip
```

and other quick shortcuts like that.

I feel like having to quote the entire thing is going to be more harm than good unless we're expecting to add more positional arguments that are unrelated to the config.

**Comment by mholt** [comment]
The only reason I suggested containing it in quotes is to keep the parsing simple. With an arbitrary number of arguments, we need to distinguish stuff like this:

```
$ caddy -quiet -host=abc.com -port=1234
```

from this:

```
$ caddy header / { -host }
```

(Slightly contrived I know, but imagine there's a header called "host" that they want to strip from the response for some reason.) And what if the user wants want to do both?

```
$ caddy -quiet -host=abc.com -port=1234 header / { -host }
```

We either need to specify a certain order/place for the Caddyfile content to appear in the arg list, like requiring it to be last, or stick to the flag convention a little more.

**Comment by shazow** [comment]
Right, you'll need to quote anything that is not a single word. This should work with the `flag` module without any extra work, though:

```
$ caddy -quiet -host=abc.com -port=1234 "header / { -host }"
```

Although, if we use commas as separators, comma value escaping will still be required, whereas quote position arg escaping is already done by every flag parser.

**Comment by mholt** [comment]
Yeah, I think that'll be fine. This is just supposed to be for simple Caddyfiles anyway. :stuck_out_tongue:

**Comment by kkovacs** [comment]
Thank you guys!

My personal use case is when I occasionally run Caddy on my Android phone to share a directory with people on the same WiFi for 10-15 minutes; since I have to type everything on a tiny-tiny keyboard, I'm very happy about every character saved (especially special ones)... :)

**Comment by mholt** [comment]
^ First actual use case I've heard of on Android. Awesome :+1: We're on it.

**Comment by humboldtux** [comment]
I submit a PR #234 as a start to work on this

**Comment by mholt** [comment]
Merged! You can now pass configuration without flags:

```
$ caddy browse
```

will do what you want @kkovacs, and similarly:

```
$ caddy browse "log acccess.log" "errors error.log" gzip
```

should work.
