### ISSUE TITLE
Increase speed of -validate

### ISSUE THREAD

**Issue by lukenowak** [mholt/caddy#2220]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.11.0 (non-commercial use only)

### 2. What are you trying to do?

`caddy -validate` and have the result in about 1 second.

### 3. What is your entire Caddyfile?
[Caddyfile](https://drive.google.com/file/d/1hifSbFuaIC-hQ04OD85a1z0J7Bk1-1R3/view?usp=sharing)

### 4. How did you run Caddy (give the full command and describe the execution environment)?

I am doing validation of big Caddyfile using the command:

`/usr/bin/time -f "%e" ./caddy -validate -conf Caddyfile`

Environment: Intel(R) Xeon(R) CPU D-1531 @ 2.20GHz, 32G RAM, SSD drive.

### 5. Please paste any relevant HTTP request(s) here.

n/a

### 6. What did you expect to see?

Validation of this Caddyfile takes about 1 second.

```text
Caddyfile is valid
1.03
```

### 7. What did you see instead (give full error messages and/or log)?

Validation of the Caddyfile takes about 7 seconds.

```text
Caddyfile is valid
7.68
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Fetch the attached Caddyfile.

Provide some certificate and key.

Run `/usr/bin/time -f "%e" ./caddy -validate -conf Caddyfile` and see the execution time.

**Comment by tobya** [comment]
Implementing #1396 may reduce the size of the caddyfile and make this issue go away.

**Comment by lukenowak** [comment]
Thank you for labelling.

I will give a try when #1396 is ready, but anyway I am ready to improve the situation by myself.

**Comment by magikstm** [comment]
Did you try using the [import](https://caddyserver.com/docs/import) directive to make reusable snippets?
