### ISSUE TITLE
Can provide an installer to install caddy as a system service?

### ISSUE THREAD

**Issue by hyingreborn** [mholt/caddy#2224]
just like nginx，install caddy as a system service，Such as:
```
c:/program file/caddy/caddy.exe

c:/program file/caddy/Caddyfile
```
It can boot on system startup，then I can add virtual hosts by modifying this files

**Comment by magikstm** [comment]
What is your OS?

If Linux or Mac there are scripts there:
https://github.com/mholt/caddy/tree/master/dist/init

If Windows, this may help depending on your exact version:
https://github.com/mholt/caddy/wiki/Caddy-as-a-service-examples

**Comment by francislavoie** [comment]
This type of question is more suited for https://caddy.community/. This is the issue board for bug reports and feature requests. Thanks @magikstm for answering :smile:
