### ISSUE TITLE
wildcard certificate generation not working

### ISSUE THREAD

**Issue by Wareing** [mholt/caddy#2229]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0

### 2. What are you trying to do?
issue a wildcard certificate for *.mp.distribution-points.net

### 3. What is your entire Caddyfile?
```text
log / requests.log "{remote} {proto} Request: {method} {host}{path}" {
        rotate_size 50  # Rotate after 50 MB
        rotate_age  90  # Keep rotated files for 90 days
        rotate_keep 20  # Keep at most 20 log files
        rotate_compress # Compress rotated log files in gzip format
}
*.mp.distribution-points.net {
tls {
    dns cloudflare
    max_certs 1
    wildcard
}
        root /var/www/html/filtering

request_id
header / {
Chance-of-MITM {mitm}
-Server
Request-ID {request_id}
}
redir 307 {
        /dl/software/latest/teamviewer.exe      https://dl.tvcdn.de/download/TeamViewer_Setup.exe
        /dl/software/latest/teamviewer.dmg  
   https://download.teamviewer.com/download/TeamViewer.dmg
        /dl/software/latest/putty.exe           https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe
        /dl/data https://{host}/dl/data/
        /dl/iso  https://{host}/dl/iso/
}
login /dl/data/ {
         simple josh=R0sebr1dge,admin=R0sebr1dge
}

proxy /dl/data/ https://eu1-cdn.servlist.distribution-points.net https://eu2-cdn.servlist.distribution-points.net {
transparent
policy round_robin
}

proxy /console/eu-proxy/ http://localhost:60103/ {
transparent
}

proxy /dl/iso/ https://eu1-cdn.servlist.distribution-points.net https://eu2-cdn.servlist.distribution-points.net {
transparent
policy round_robin
}
pprof

}
plex.mp.distribution-points.net {
import *.mp.distribution-points.net #(it's this bit that isn't working... not sure what I've done wrong here)

        root /var/www/html/filtering
proxy / 46.105.99.30:32400/ {
transparent
}
}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -log /var/log/caddy.log
runs within a named screen session
### 6. What did you expect to see?
wildcard certificate issuance
### 7. What did you see instead (give full error messages and/or log)?

2018/07/18 10:40:52 Caddyfile:5 - Error during parsing: Cannot convert domain name '*.mp.distribution-points.net' to a valid wildcard: already has a wildcard label

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
put import *.SOMEDOMAINYOUOWN.COM in Caddyfile within a domain configuration.

**Comment by mholt** [comment]
Take out the `wildcard` from inside the `tls` directive -- it's automatic when you've specified a literal wildcard domain.
