### ISSUE TITLE
error 413 not logged when "limits 200" is triggered

### ISSUE THREAD

**Issue by Tintinabula** [mholt/caddy#2232]
### 1. What version of Caddy are you using (`caddy -version`)?
caddy v0.11.0 on FreeBSD 11.2

### 2. What are you trying to do?
define "limits 200" to trigger an error HTTP 413 back to the client and log the 413 to the access.log . The error 413 is sent back to the client as expected. The error 413 is _not_ logged in the access.log though.

### 3. What is your entire Caddyfile?
caddy is listening on localhost port 8080 and redirected using Pf.

```
https://:8080 {

  bind 127.0.0.1
  limits 200

   tls /usr/local/etc/caddy/fullchain.cer /usr/local/etc/caddy/domain.org.key {
      ciphers ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-WITH-CHACHA20-POLY1305 ECDHE-ECDSA-AES256-GCM-SHA384
      protocols tls1.2
   }

   log / /var/log/caddy-access.log "{when} {status} {remote} {method} {uri} {proto} {size} {tls_cipher} {latency}"
   errors / /var/log/caddy-error.log

   header / {
      alt-svc "quic=\":443\"; ma=31536000; v=\"39\""
   }

   root /web
   index index.html

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/local/bin/caddy -quic -log stdout -conf /usr/local/etc/caddy/caddy.conf

### 6. What did you expect to see?
An error 413 should have been printed in the access.log . 

### 7. What did you see instead (give full error messages and/or log)?
No log of the over-sized request.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

set "limits 200" and make a request to the caddy server with chrome, firefox or chrome on android. All requests are larger than 200 bytes and will trigger an error 413 back to the client. The access log will not show any errors.

**Comment by tobya** [comment]
I presume no error is logged to the errors file either?

**Comment by francislavoie** [comment]
@Tintinabula same as the other issue, could you mention why you closed it, if you resolved your problem?
