### ISSUE TITLE
QUIC TLS cipher logged as "UNKNOWN"

### ISSUE THREAD

**Issue by Tintinabula** [mholt/caddy#2233]
### 1. What version of Caddy are you using (`caddy -version`)?
caddy v0.11.0 on FreeBSD 11.2

### 2. What are you trying to do?
force QUIC connect and log the TLS cipher used by the client. QUIC connections work correctly, but the access.log cipher logged says, "UNKNOWN" instead of ECDHE-ECDSA-AES128-GCM-SHA256 or similar.

### 3. What is your entire Caddyfile?
caddy is listening on localhost port 8080 and redirected using Pf.

```
https://:8080 {

  bind 127.0.0.1
  limits 200

   tls /usr/local/etc/caddy/fullchain.cer /usr/local/etc/caddy/domain.org.key {
      ciphers ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-ECDSA-WITH-CHACHA20-POLY1305 ECDHE-ECDSA-AES256-GCM-SHA384
      protocols tls1.2
   }

   log / /var/log/caddy-access.log "{when} {status} {remote} {method} {uri} {proto} {size} {tls_cipher} {latency}"
   errors / /var/log/caddy-error.log

   header / {
      alt-svc "quic=\":443\"; ma=31536000; v=\"39\""
   }

   root /web
   index index.html

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/local/bin/caddy -quic -log stdout -conf /usr/local/etc/caddy/caddy.conf

### 6. What did you expect to see?
The log should show the cipher instead of "UNKNOWN"

### 7. What did you see instead (give full error messages and/or log)?

Logs of client making a true QUIC connection in our custom log format"
```
24/Jul/2018:14:26:45 -0400 200 85.230.x.x GET /index.html HTTP/2.0 10239 UNKNOWN 25ms
24/Jul/2018:14:26:46 -0400 200 85.230.x.x GET /image.jpg HTTP/2.0 120236 UNKNOWN 242ms
```

Log of a client first requesting the index.html using TLS1.2 and then requesting the image using QUIC.
```
24/Jul/2018:13:29:01 -0400 200 201.71.x.x GET /index.html HTTP/2.0 19156 ECDHE-ECDSA-AES128-GCM-SHA256 208µs
24/Jul/2018:13:29:03 -0400 200 201.71.x.x GET /image.jpg HTTP/2.0 260017 UNKNOWN 172ms
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Start Chrome and force QUIC connections to your domain. Check the cipher log lines with the  {tls_cipher} placeholder defined.

```
google-chrome --incognito --origin-to-force-quic-on=example.org:443
```

**Comment by Henrocker** [comment]
The alternative service header is implemented to be sent automatically when using the -quic flag.

**Comment by francislavoie** [comment]
@Tintinabula were you able to resolve your issue? Would be nice if you could mention why you closed the issue, in case someone else comes by this later.
