### ISSUE TITLE
Caddyfile in .gitignore?

### ISSUE THREAD

**Issue by sssilver** [mholt/caddy#2237]
Hi,

We're using Caddy as a dependency for our project through `dep`, and we check in our vendored dependencies. However, because of the fact that Caddy's `.gitignore` contains an entry `Caddyfile`, that particular directory under vendor/ remains ignored and doesn't get pushed into our repository. This causes the build to be broken for whoever clones the repo, as they have to delete the vendor Caddy directory and re-run `$ dep ensure` to get `caddyfile` back.

It may be intentional that the .gitignore lists `Caddyfile` with an uppercase C, and the directory itself is called `caddyfile` with a lowercase c, however on a macOS system `git` disregards the case difference.

Please advise.

Thanks,
Areg

**Comment by sssilver** [comment]
This is a little confusing. Is there a difference between `caddyfile` and `Caddyfile`?

**Comment by francislavoie** [comment]
Yes, `Caddyfile` is the filename for the config file Caddy uses. `caddyfile` is the name of a folder of Go code which implements parsing of the `Caddyfile` file format.

**Comment by sssilver** [comment]
Ah, that makes it quite prone to problems.

I vote for `!caddyfile/`, since it disambiguates the pattern and the intentions. Shall I open a PR?

**Comment by francislavoie** [comment]
Yeah, sounds good :+1:
