### ISSUE TITLE
Reload config(via USR1) has no effect after upgrading(via USR2)

### ISSUE THREAD

**Issue by soforth** [mholt/caddy#2242]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (+1f7b5ab Thu Jul 26 10:48:36 UTC 2018) (unofficial)

### 2. What are you trying to do?
testing USR1 feature after USR2, then watch the log output
```
pkill -usr1 caddy
pkill -usr2 caddy
pkill -usr1 caddy
```

### 3. What is your entire Caddyfile?
it's empty
```
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -log nohup.out 

### 5. Please paste any relevant HTTP request(s) here.
no request

### 6. What did you expect to see?
2018/07/26 18:54:31 [INFO] SIGUSR1: Reloading
2018/07/26 18:54:31 [INFO] Reloading
2018/07/26 18:54:31 [INFO] Reloading complete

### 7. What did you see instead (give full error messages and/or log)?
2018/07/26 18:55:33 [INFO] SIGUSR1: Reloading
2018/07/26 18:55:33 [ERROR] SIGUSR1: no Caddyfile loader with which to reload Caddyfile

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

I dig a little into the source code, it seems that before upgrade, the caddy use Caddyfile to trigger reload action, however, in the upgrading process, the caddy config will be piped(via pipe()) to the child(in the memory), then the Caddyfile is useless after that.(the loaderUsed.loader is no longer take effect after then)

**Comment by mholt** [comment]
Well... turns out, config reloads are totally rearchitected in Caddy 2, making this a non-issue.
