### ISSUE TITLE
-version should show the bundled plugins

### ISSUE THREAD

**Issue by FiloSottile** [mholt/caddy#2243]
When trying to update an existing instance of Caddy, I have to reverse-engineer what plugins I need to bundle for my current services to keep working. It would be much easier if `-version` listed them.

**Comment by Mohammed90** [comment]
I think the command `caddy -plugins` lists all the bundled plugins.

**Comment by FiloSottile** [comment]
Oh hey, that's new in v0.11.0. Should have tested with the latest version. Thank you!

**Comment by mholt** [comment]
`-plugins` has been around for a while :) But glad that works for you!
