### ISSUE TITLE
log if request was with full ssl handshake

### ISSUE THREAD

**Issue by asafcombo** [mholt/caddy#2245]
### 1. What version of Caddy are you using (`caddy -version`)?
`caddy - 0.10.4`

### 2. What are you trying to do?
I'm trying to add to the http log file a custom `bool` field that would indicate if the request was with *full SSL handshake* or with *SSL resumption*
The purpose is to later analyze the logs to see the distribution.

~help wanted

**Comment by mholt** [comment]
Thanks for taking the initiative on these issues, while I am busy with other things!

Actually I think the issue tracker is a good place for specific feature requests. We can discuss implementation details here.

Note that this will be changing in TLS 1.3. I'm not sure what kind of effort is required to adjust for that. Might be worth waiting? Or maybe not -- someone can feel free to explore.

**Comment by mholt** [comment]
Will probably be possible in Caddy 2.
