### ISSUE TITLE
reverse proxy with / path: GET /.well-known/acme-challenge/..." 404

### ISSUE THREAD

**Issue by mbana** [mholt/caddy#2247]
Is the configuration below meant to work? I'm asking because I am seeing the `404` listed below.

I am just wondering if I need to exclude `/.well-known/` from being proxied, but then again, I thought Caddy would handle this automatically.

Please clarify.

```Caddyfile
site.ga www.site.ga {
  tls m@site.ga

  proxy / backend-servere:4000 {
    websocket
    transparent
  }

  log stdout
  errors stderr

  gzip
}
```

```sh
2018/07/31 13:21:09 [INFO] Scanning for stale OCSP staples
2018/07/31 13:21:09 [INFO] Done checking OCSP staples
2018/07/31 13:24:34 [INFO] 35.230.158.145 - No such site at :80 (Remote: 10.154.0.3, Referer: )
10.154.0.2 - - [31/Jul/2018:13:26:00 +0000] "GET /.well-known/acme-challenge/a HTTP/1.1" 404 14714
2018/07/31 13:34:12 [INFO]  - No such site at :80 (Remote: 10.0.2.1, Referer: )
10.154.0.2 - - [31/Jul/2018:13:34:13 +0000] "GET /.well-known/acme-challenge/b HTTP/1.1" 404 14713
```

**Comment by mholt** [comment]
That message is just saying that Caddy isn't configured to serve `35.230.158.145` or `` hosts (from the Host HTTP header) -- your configuration is only for `site.ga` and `www.site.ga`. It has nothing to do with the proxying.

**Comment by mbana** [comment]
can you please reopen this. the reason i suspect it's related to proxying is because i am seeeing those `/.well-known/acme-challenge/a` reequests being proxied to `backend-server` whilst i hoping they wouldn't.
