### ISSUE TITLE
Some logs aren't being written with the log directive

### ISSUE THREAD

**Issue by plurry** [mholt/caddy#2249]
### 1. What version of Caddy are you using (`caddy -version`)?

`Caddy 0.11.0 (unofficial)` that I installed on Fedora with `dnf install caddy`.

### 2. What are you trying to do?

I want to save the time-stamped messages with just the `log` directive in the Caddyfile instead of having to use the `-log` option when I start Caddy.

### 3. What is your entire Caddyfile?

```text
:2015
log stdout
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -log stdout` works and `caddy` alone does not.

### 5. Please paste any relevant HTTP request(s) here.

```text
curl localhost:2015
pkill -USR1 caddy
```

### 6. What did you expect to see?

```text
2018/08/03 00:17:08 http://:2015
2018/08/03 00:17:09 [NOTICE] Sending telemetry: we were too early; waiting 10m0s before trying again
::1 - - [03/Aug/2018:00:17:16 +0000] "GET / HTTP/1.1" 404 14
2018/08/03 00:17:25 [INFO] SIGUSR1: Reloading
2018/08/03 00:17:25 [INFO] Reloading
2018/08/03 00:17:25 [INFO] Reloading complete
```
(This is what I see when I run `caddy -log stdout`.)

### 7. What did you see instead (give full error messages and/or log)?

```text
::1 - - [03/Aug/2018:00:17:50 +0000] "GET / HTTP/1.1" 404 14
```
(This is all I see when I just run `caddy`.)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Launch Caddy with logging enabled by the directive in the Caddyfile and notice that the log file isn't written when, for example, you reload Caddy.

**Comment by mholt** [comment]
This is working as expected... the `log` directive is for HTTP requests and is only recognized by the HTTP server plugin.

Why can you not use the `-log` flag? That's exactly what it's for.

**Comment by plurry** [comment]
Ah, I get it now... I was thinking the `-log` flag and the `log` directive overlapped like, for example, the `-email` flag and the `tls` directive do, and I was trying to keep all my configuration in the Caddyfile.

But, yes, I can just start Caddy with some flags, no problem.
