### ISSUE TITLE
Add additional method OnRestartFailed() to caddy.Controller

### ISSUE THREAD

**Issue by ekleiner** [mholt/caddy#2250]
### 1. What version of Caddy are you using (`caddy -version`)?

caddy dev version (build from master)

### 2. What are you trying to do?

I am working on external plugin which makes self-tests. It sends request to server and intercepts own request while it goes through it's Handler.
While restart (SIGUSR1) it is disabled in favor to a new plugin when OnRestart() is called.
And it is removed totally when OnShutdown is called. But there is no hook for the case when reload failed. I need to have a hook like OnRestartFailed(). So every OnRestart for plugin would finish by either OnShutdow() or OnRestartFailed().

### 3. What is your entire Caddyfile?
```text
localhost:2020 {
    atepmonitor
}
```

**Comment by ekleiner** [comment]
Also adding this method should simplify other plugins (like prometheus) to support the reload feature.

**Comment by elcore** [comment]
Feel free to create a PR :smile:

**Comment by ekleiner** [comment]
Ok. I will. Just wanted to make sure that others are ok with the changes.

**Comment by elcore** [comment]
> Ok. I will. Just wanted to make sure that others are ok with the changes.

Changes are always welcome, we will review your PR and decide if it is suitable :smile:

**Comment by fturib** [comment]
@ekleiner : while you are here, I think we need to think how to handle the errors during a Reload process.

- What if a OnRestart() fails ?
- I guess if the new Server fails, then we call all OnRestartFailed() on the initial instance.
- But what if one of the OnRestartFailed() fails ... ?

Maybe we should introduce some fatal error when we are not able to catch-up ...
Or not allow the event function to return an error.

**Comment by fturib** [comment]
@elcore , @mholt : I guess it is worth to validate that the proposition is correct before proposing a PR. At least that nobody is against this proposition of adding an event OnRestartFailed().

Is this issue the right location to get a pre-approval ?

**Comment by tobya** [comment]
Hi @fturib this is the right place to discuss and get approval for a PR.

On the face of it I would think that this is an interesting idea for a PR.  It seems @elcore suggests the same.

I wouldnt go too far down the rabbit hole of worrying about failing failures.  We can simply do that same as what happens now.

**Comment by ekleiner** [comment]
Working on it.
