### ISSUE TITLE
Large file downloads issue

### ISSUE THREAD

**Issue by Henrocker** [mholt/caddy#2254]
### 1. What version of Caddy are you using (`caddy -version`)?
caddy 0.11.0 (+053373a Thu Jul 12 14:38:42 UTC 2018)

### 2. What are you trying to do?
Download a large file served by caddy webserver (No fastcgi, etc.)

### 3. What is your entire Caddyfile?
```text
https://domain.com, https://www.domain.com	{
	tls /etc/caddy/crt.crt /etc/caddy/key.key {
		protocols	tls1.2 tls1.2
	}
	forwardproxy {
	        basicauth foo bar
	        ports     80 443
	        hide_ip
	        hide_via
	        response_timeout 30
	        dial_timeout     30
	}
	gzip {
		ext *
		level 4
	}
	fastcgi / unix:/run/php/php7.0-fpm.sock php {
		root	/etc/caddy/html
	}
	header / {    
		Strict-Transport-Security "max-age=31536000; includeSubdomains; preload;"
		X-XSS-Protection "1; mode=block;"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Referrer-Policy "strict-origin-when-cross-origin"
	}
	limits {
		header 64kb
		body 8gb
	}
	markdown
	log /etc/caddy/log/access.log {
                rotate_size     10
                rotate_age      14
                rotate_keep     10
                rotate_compress
        }
	root /etc/caddy/html
	ext .html .htm .php
	errors /etc/caddy/log/error.log
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -agree=true -conf=/etc/caddy/Caddyfile -email=my@mail.com -quic

### 5. Please paste any relevant HTTP request(s) here.

Example: https://henrock.net/mod-v45.apk

### 6. What did you expect to see?
Download completes successfully.

### 7. What did you see instead (give full error messages and/or log)?
Download suddenly breaks up with: Network error
![error](https://user-images.githubusercontent.com/15855905/43716966-3fef8488-9986-11e8-9d17-fd4ff71ad216.PNG)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Take the config file, upload a larger file (>200MB), and try to download it. My download speed is approx. 2 MB/sec., when I download a 200 MB file, like the one provided in the example link above, I get to 80 MB/s and the the downloads gets canceled with network error. So if you have a fast internet connection, you might be able to download the full 200MB, so when testing, please use around 2 MB/s.

Tried other browsers (IE, Chrome, Firefox), Also tried without QUIC, same error.

**Comment by magikstm** [comment]
I do also get the error on that file on Chrome and Firefox on Windows 7 x64.

Are you using a timeout setting or did you try setting:
timeouts none

Docs (https://caddyserver.com/docs/timeouts) mention:
Because timeouts apply to an entire HTTP server which may serve multiple sites defined in your Caddyfile, the timeout values for each site will be reduced to their minimum values (with 0 or none being the lowest) across all sites that share that server. It's a good idea to keep your timeouts the same or just set them on one site to avoid confusion. A timeout set on one site will apply to all sites that share that server.

**Comment by Henrocker** [comment]
Hi,

right now, I've got timeouts set to none.
Before that, I didn't have a timeouts setting in my Caddyfile.

Do you see any change? I can download the file completely now.

Br
Henrik

**Comment by magikstm** [comment]
I tested it on Firefox and Chrome on Windows x64 and both downloads completed. Seems to correct it.

I'm unsure if it's the right way to correct it or if at first it was the expected behavior.

**Comment by Henrocker** [comment]
Works for me. Hence, closing
