### ISSUE TITLE
https   Not working properly

### ISSUE THREAD

**Issue by slzzz** [mholt/caddy#2255]
caddy -version
Caddy 0.11.0 (+1f7b5ab Thu May 10 15:51:18 UTC 2018) (unofficial)
1 file changed, 1 insertion(+), 1 deletion(-)
caddy/caddymain/run.go
curl http Moved Permanently  ,it's ok
curl https
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* gnutls_handshake() failed: The TLS connection was non-properly terminated.
* Closing connection 0
curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.

**Comment by Henrocker** [comment]
What does your Caddyfile look like?

**Comment by mholt** [comment]
Can you please fill out the issue template. :(
