### ISSUE TITLE
http.ext error 500 no such file

### ISSUE THREAD

**Issue by KyonLi** [mholt/caddy#2256]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.11.0

### 2. What are you trying to do?

Use http.ext to clean URL

### 3. What is your entire Caddyfile?
```text
example.com {
    gzip
    tls webmaster@example.com
    root /var/www/www
    index index.html index.htm
    ext .md .markdown .txt
    markdown {
        ext .md .markdown .txt
    }
    status 404 {
        /index.html
    }
    errors {
        404 index.html
    }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```bash
root@ubuntu:~# ls /var/www/www
demo.md  index.html
root@ubuntu:~# systemctl restart caddy
```

### 5. Please paste any relevant HTTP request(s) here.

```bash
iMac:~ kyon$ curl -I https://example.com/demo
HTTP/2 200

iMac:~ kyon$ curl -I https://example.com/demoxxx
HTTP/2 404

iMac:~ kyon$ curl -I https://example.com/demoxxx.md
HTTP/2 500
```

### 6. What did you expect to see?

request /demoxxx.md return 404

### 7. What did you see instead (give full error messages and/or log)?

request /demoxxx.md return 500

Aug 07 04:58:37 ubuntu caddy[22625]: 07/Aug/2018:04:58:37 -0400 [ERROR 500 /demoxxx.md] open /var/www/www/demoxxx.md: no such file or directory

**Comment by SmilingNavern** [comment]
I will check this and test this.

**Comment by SmilingNavern** [comment]
I believe issue is here, because if Stat call is failed(which is our case) then no actual error is returned. I will think how to fix this.
```.go
// ServeHTTP implements the httpserver.Handler interface.
func (e Ext) ServeHTTP(w http.ResponseWriter, r *http.Request) (int, error) {
	urlpath := strings.TrimSuffix(r.URL.Path, "/")
	if len(r.URL.Path) > 0 && path.Ext(urlpath) == "" && r.URL.Path[len(r.URL.Path)-1] != '/' {
		for _, ext := range e.Extensions {
			_, err := os.Stat(httpserver.SafePath(e.Root, urlpath) + ext)
			if err == nil {
				r.URL.Path = urlpath + ext
				break
			}
		}
	}
	return e.Next.ServeHTTP(w, r)
}
```
