### ISSUE TITLE
Caddy subdomain status OK but always got 404

### ISSUE THREAD

**Issue by delapecci** [mholt/caddy#2258]
With Caddy 0.11.0 (non-commercial use only)

I want to configure a site with domain p8ji.cn, the caddyfile is following:
```text
p8ji.cn {
  root /var/tmp/p8ji.cn
  log /var/log/caddy/p8ji.cn.log
}
```
the root path /var/tmp/p8ji.cn layout is:
<img width="387" alt="3" src="https://user-images.githubusercontent.com/2783025/43817102-71db23aa-9b0a-11e8-9dc5-52113fb68346.png">

I started caddy.service and got right status:
<img width="742" alt="1" src="https://user-images.githubusercontent.com/2783025/43817007-f9936fba-9b09-11e8-8d14-3b89944bc049.png">

Then open the https://p8ji.cn in browser, but 404, refresh, always 404
<img width="1393" alt="2" src="https://user-images.githubusercontent.com/2783025/43817050-29ba2a12-9b0a-11e8-9488-5f1dd5deb5eb.png">

Any help?😢

**Comment by SmilingNavern** [comment]
Hello, @delapecci 

Could you please provide full content of your systemd unit?

**Comment by SmilingNavern** [comment]
Actually i got this one. 

If you are using the standard caddy systemd unit there is directive PrivateTmp=true, so there is new directory which is created for you and there are no files which you need.

Change your root in Caddyfile to something other than /tmp or /var/tmp and it would work for you.

**Comment by tobya** [comment]
I will close this for now.  Thank you @SmilingNavern .
@delapecci feel free to post more info if you wish.
