### ISSUE TITLE
Reverse proxy exchange autodiscover error

### ISSUE THREAD

**Issue by boscorelly** [mholt/caddy#2259]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0

### 2. What are you trying to do?
Reverse proxy for Exchange

### 3. What is your entire Caddyfile?
```autodiscover.solutek.fr {
         root /
                 proxy / https://autodiscover.domain.fr/ {
                         insecure_skip_verify
                         transparent

                 }
        tls team@solutek.fr {
                alpn http/1.1
        }
        log /apps/TygerCaddy/TygerCaddy/data/logs/autodiscover.log
        errors visible
 }
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
TygerCaddy with just hook.service

### 5. Please paste any relevant HTTP request(s) here.
192.168.254.254 - - [07/Aug/2018:19:03:48 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 401 0
192.168.254.254 - - [07/Aug/2018:19:03:48 +0200] "POST /autodiscover/autodiscover.xml HTTP/1.1" 502 117

### 6. What did you expect to see?
Prompt login on web page

### 7. What did you see instead (give full error messages and/or log)?
When it tries Windows login, i have 
[ERROR 502 /Autodiscover/Autodiscover.xml] stream error: stream ID 3; HTTP_1_1_REQUIRED
Forcing http/1.1 does nothing

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Make a fresh install :D

**Comment by boscorelly** [comment]
Now i have the prompt, but one logged and activating Windows Authentication i still have

08/Aug/2018:09:58:20 +0200 [ERROR 502 /autodiscover/autodiscover.xml] stream error: stream ID 23; HTTP_1_1_REQUIRED

**Comment by tobya** [comment]
I am going to close this.  If you have further information we can reopen.
