### ISSUE TITLE
Allow use of existing .htpasswd files for Basic Auth

### ISSUE THREAD

**Issue by tgulacsi** [mholt/caddy#227]
I have a legacy htpasswd file, I don't know the passwords, just the hashes, and I need to support this.
If nobody opposes, I'll create a PR.

**Comment by mholt** [comment]
How about if you could put the hashes in the Caddyfile? Would that work? (What kind of hash is it, by the way? Is it always the same for .htaccess?)

**Comment by tgulacsi** [comment]
See that dreadful md5: https://github.com/jimstudt/http-authentication/blob/master/basic/md5.go#L39
and sha does not have a salt...

So nothing cyptographically sane, just legacy.

**Comment by mholt** [comment]
Merged in your #228 - thanks!
