### ISSUE TITLE
Compilation error in httpserver/replacer.go

### ISSUE THREAD

**Issue by laszlo-kiss** [mholt/caddy#2275]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (+5e5f9b0 Wed Aug 22 14:54:40 UTC 2018) (unofficial)

### 2. What are you trying to do?
Build caddy according to documentation.

### 3. What is your entire Caddyfile?
Not applicable, compilation/build error fix.

### 4. How did you run Caddy (give the full command and describe the execution environment)?
N/A. Build error fix.

### 5. Please paste any relevant HTTP request(s) here.
N/A. Build error fix.

### 6. What did you expect to see?
No build error.

### 7. What did you see instead (give full error messages and/or log)?
```
server1|vagrant$ go run build.go
# github.com/mholt/caddy/caddyhttp/httpserver
../caddyhttp/httpserver/replacer.go:464:22: cert.Issuer.String undefined (type pkix.Name has no field or method String)
../caddyhttp/httpserver/replacer.go:476:23: cert.Subject.String undefined (type pkix.Name has no field or method String)
2018/08/22 07:53:30 exit status 2
exit status 1
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Just check out the latest master and try to build.

**Comment by tobya** [comment]
You need Go 1.10 installed to build.
