### ISSUE TITLE
Plans for next release?

### ISSUE THREAD

**Issue by hartwork** [mholt/caddy#2280]
Hi!

Are there plans for a release date of the next release already? I would love to see some of the post-0.11.0 commits in a release. Thanks!

Best, Sebastian

**Comment by hartwork** [comment]
Any thoughts?

**Comment by magikstm** [comment]
Last release (0.11.0 on May 10) was nearly 6 months ago.

Any plans on when the next release may be?

**Comment by francislavoie** [comment]
FYI, New version was just released.
