### ISSUE TITLE
bytes from sync.Pool not zeroed

### ISSUE THREAD

**Issue by komuw** [mholt/caddy#2292]
This is more of a question/bug report. 
From my understanding of sync.Pool(https://golang.org/pkg/sync/#Pool); once you get an item from it, you should zero it before using it. 
However, in this case; caddy does not do so;
https://github.com/mholt/caddy/blob/13a54dbdda25c5da12f34d49f22b8d3eb23e3140/caddyhttp/proxy/reverseproxy.go#L63

Is there a reason why caddy doesn't zero the []byte before use, or is it a bug?

here's an example of the zeroing i'm talking about;
https://github.com/bradfitz/http2/blob/aa7658c0e9902e929a9ed0996ef949e59fc0f3ab/server.go#L1414-L1416

**Comment by crvv** [comment]
Please read the document of `io.CopyBuffer`.
https://golang.org/pkg/io/#CopyBuffer

`buf` is just a buffer. The content doesn't matter.

**Comment by theodesp** [comment]
You could zero it out, but it's not the responsibility of the pool consumer to do that. The pool might zero it out if the implementation change.
