### ISSUE TITLE
Reflection-based config unmarshaller. 

### ISSUE THREAD

**Issue by sirkon** [mholt/caddy#2295]
Hi!

We use Caddy at my job with set of custom plugins. Our configs are a bit too large for `c.Next()`, thus reflection based unmarshaler was developed. It worked, but the code design was subpar, thus it turned to be too hard to extend it.

I am also planning to write open source thing with large config as a plugin for Caddy and it would be nice to have unmarshaling into structure – the one I did for my job is closed source.

So the 2nd, open source version appeared, with better code design and larger feature set.

I have already moved my plugins at the job and they work. 

https://github.com/sirkon/caddycfg

I guess you may consider its inclusion into Caddy source tree for the ease of plugin development after some more testing. And of course README.md better be improved as my English is subpar.

**Comment by mholt** [comment]
Thanks for releasing that! (Somehow I just saw this now.)

Configuration will be vastly improved in Caddy 2.
