### ISSUE TITLE
Caddy listening on port 2015 instead of 80/443 for some domain names

### ISSUE THREAD

**Issue by mkishere** [mholt/caddy#2299]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0 (unofficial)

### 2. What are you trying to do?
Setting up a domain with .link TLD with Caddy

### 3. What is your entire Caddyfile?
```text
xxxxx.link {
   tls xxx@gmail.com
   browse
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Via custom build Docker image from abiosoft/caddy (but I think it is irrelevant)
caddy -conf /etc/Caddyfile -agree

### 5. Please paste any relevant HTTP request(s) here.
curl -IL http://xxx.link

### 6. What did you expect to see?
When following [document](https://caddyserver.com/docs/http-caddyfile#addresses), I was expecting Caddy would automatically listen to 80/443 given a real domain name.

### 7. What did you see instead (give full error messages and/or log)?
Caddy was listening on port 2015 instead of 80/443. Instead I have to use config
```text
http://xxxx.link {
...
}
```
### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Try to use a domain name with uncommon TLD in config.

Actually I think this is not a bug, but the Caddy should give more information on the doc what domain it would consider as a dev env and listen on port 2015 and whats not.

**Comment by mholt** [comment]
What is your full, unredacted/unedited Caddyfile that you were using before?

**Comment by mkishere** [comment]
To better illustrate, I reproduced the issue with following Caddyfile:
```
https://git.equa.link {
   tls [redacted]@gmail.com
   proxy / http://gitea:3000/
}

www.equa.link {
   tls off
}
```
where equa.link is a valid and real domain with .link TLD.

git.equa.link listens to 80 and 443 (expected)
while www.equa.link listens to 2015
Log:
```
caddy_1     | https://git.equa.link
caddy_1     | https://ci.equa.link
caddy_1     | http://www.equa.link:2015
```

**Comment by francislavoie** [comment]
Seems to work as advertised. https://caddyserver.com/docs/http-caddyfile

>The default port is 2015 (unless the site qualifies for automatic HTTPS, in which case it's changed to 443 for you).

If you want it to bind to 80/443, then prefix the label with `https://` or for just 80, prefix with `http://`

**Comment by mkishere** [comment]
Actually why I raised the question is that the doc has the following line:
```
example.com              # Host: example.com; Ports: 80->443
```
In what case does it qualifies? Both cases are FQDN I suppose?

**Comment by francislavoie** [comment]
A couple sentences later:

>For example (this table assumes automatic HTTPS is applied where it qualifies):

The assumption here is that `example.com` qualifies for automatic HTTP. Read https://caddyserver.com/docs/automatic-https for the specifics of how that's determined. It's all there in the docs!

**Comment by mkishere** [comment]
I see! Thanks
