### ISSUE TITLE
Default to index.html or index.php 

### ISSUE THREAD

**Issue by devil1591** [mholt/caddy#23]
Can't find this in documentation, there is no default index file like index.html. 
The php preset for fastcgi  `index index.php` isn't working, at least on Windows x86.

Thanks for this very nice project :)

**Comment by abiosoft** [comment]
I got it to work. Ensure php-fpm has started.

My Caddyfile looks like this
```
127.0.0.1 

root /path/to/php/dir

fastcgi / 127.0.0.1:9000 php {
	ext .php
	index index.php index.html
}
```

Hope this helps.

**Comment by devil1591** [comment]
Thanks Abiosoft, this is not working with Caddy Win x86, it outputs this error: 
`http: multiple response.WriteHeader calls`

**Comment by mholt** [comment]
That's interesting @devil1591. It means that more than one middleware thinks it has the floor. In other words, either:

- one middleware that actually writes the response isn't telling others properly (via return value, maybe?) that it wrote to the response, or
- a middleware that *was* told that somebody else wrote to the response still wrote to the response when it shouldn't have.

What kind of response was the client seeing? An error, or a page successfully served?

**Comment by devil1591** [comment]
The error is `No input file specified. 404 Not Found`

**Comment by mholt** [comment]
Do you have Go installed? Could you change line 119 of fastcgi.go to:

```go
return 0, nil
```

Because I suspect that php-fpm is giving 404 and writing "No input file specified" but the fastcgi handler is incorrectly returning the 404, signaling to Caddy that it needs to handle the error by writing "404 Not Found" - in this case, Caddy should not add anything to the response...

**Comment by abiosoft** [comment]
@devil1591 what is your middleware stack ? It could probably be a bug not limited to windows.

**Comment by devil1591** [comment]
@mholt sorry, I don't have Go installed.
@abiosoft, I'm using php-cgi.exe (v5.4.40)

**Comment by mholt** [comment]
@devil1591 No problem. [Here's a modified binary](http://s000.tinyupload.com/?file_id=01778081656740942496). I wouldn't expect it to fix the index file issue, but it should no longer say "multiple response.WriteHeader calls" - can you confirm that?

**Comment by devil1591** [comment]
That's right, the error is now `No input file specified.` and there is no error on the console anymore. The index issue is still there.

**Comment by mholt** [comment]
Awesome - 1 down, 1 to go.

@devil1591 Now I need some more details. Could you paste the contents of your Caddyfile? And also the URL exactly as it appears in your browser when that message appears? I need to make sure it ends with a forward slash `/` character.

**Comment by devil1591** [comment]
I confirm that Caddy 0.5.1 fixes the index file issue.
My URL was entered with a trailing slash. 
Here is my caddy.conf:
`192.168.10.66:80, 0.0.0.0:80
gzip
log logs/access.log
root apache2/htdocs
fastcgi / 127.0.0.1:9123 php {
    ext .php
    index index.php index.html
}`

I used both 0.0.0.0 and 192.168.10.66 because 0.0.0.0 wasn't working.

**Comment by abiosoft** [comment]
@devil1591 glad to hear that. The are few new improvements to FastCGI middleware coming in the next release. Stay tuned.
