### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by updater1234** [mholt/caddy#2300]
### 3. What is your entire Caddyfile?
```text
(paste Caddyfile here)
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Actually,I find a spelling mistake on https://caddyserver.com/features.
![2018-09-21 21-11-30](https://user-images.githubusercontent.com/31512600/45883182-ed856100-bde2-11e8-990d-a8ac83bcfdf1.png)
It should be automatic TLS not automagic TLS

**Comment by tobya** [comment]
Thank you for the issue. My understanding is that we actually call it Automagic TLS as its not just automatic TLS it does other things such as get a cert, which makes it a little bit magic 😄

**Comment by updater1234** [comment]
OK,I got it.
