### ISSUE TITLE
webdav plugin seems no longer to be maintained.

### ISSUE THREAD

**Issue by devil418** [mholt/caddy#2307]
The webdav caddy plugin seems no longer to be maintained. The last commit is from november, and my issue raised in march seems not to have any comments yet. WOuld it be okay if I forked and made the modifications I need? Would that be accepted into webdav?

If yes, what's the stance of caddy on plugins and backwards compatibility? Should I try to ensure it or can I go with breaking things a little for existing users and requiring caddyfile tweaks in exchange for much greater flexibility? I can probably do both, though the second option would be easier.

**Comment by hacdias** [comment]
Hello! Sorry for not answering in time @devil418! Yes, you can open a PR implementing the feature you asked for. They're always welcome. If you could, please take a look at [this issue](https://github.com/hacdias/caddy-webdav/issues/9) which I think is related to yours.

**Comment by magikstm** [comment]
I think this issue can be closed.
