### ISSUE TITLE
Rewrite documentation error

### ISSUE THREAD

**Issue by smlx** [mholt/caddy#2308]
This is really a documentation bug. The first example given in https://caddyserver.com/docs/rewrite is incorrect. To only match `/`, you must use:

    rewrite ^/$ /index.php

This behavioural change appears to have occurred in v0.10.13 when single-line rewrite rules got regex matching.

### 1. What version of Caddy are you using (`caddy -version`)?

    Caddy 0.11.0 (unofficial)

### 2. What are you trying to do?

Rewrite only a request for the bare root path `/` using the example single-line rewrite configuration from https://caddyserver.com/docs/rewrite

### 3. What is your entire Caddyfile?
```text
example.com {
  # Set the document root of the site
  root /var/www/html

  # Set the path to the php-fpm process.
  fastcgi / backend-host:9000 php

  # rewrite root path
  rewrite / /index.php

  # Main rewrite to route non-existent files to index.php file.
  rewrite {
    if {file} not favicon.ico
    if {file} not cron.php
    if {file} not update.php
    to {path} {path}/ /index.php?{path}&{query}
  }

  gzip
  tls off
  log / stdout "{common} (rewrite_uri: {rewrite_uri}, latency_ms: {latency_ms})"
  errors stderr
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd

### 5. Please paste any relevant HTTP request(s) here.

n/a

### 6. What did you expect to see?

Requests rewritten to `index.php` only for bare root requests (`/`).

### 7. What did you see instead?

All requests rewritten to `/index.php`.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Use a rewrite rule like this in your Caddyfile:

    rewrite / /index.php

**Comment by mholt** [comment]
Hm, @abiosoft was this change intended do you think?

**Comment by smlx** [comment]
Is there a way to avoid regex interpretation in a single-line rewrite? A disadvantage of this change is that regex matching is slower.

**Comment by mholt** [comment]
Fixed in a recent issue / site deploy.
