### ISSUE TITLE
Can't access files with hashes (#) if rewrites are being used

### ISSUE THREAD

**Issue by ngyikp** [mholt/caddy#2310]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (non-commercial use only)

### 2. What are you trying to do?
I'm trying to serve a file with a hash in its file name, it doesn't work if I use `rewrite`

### 3. What is your entire Caddyfile?
```text
http://127.0.0.1:2015

root /Users/ngyikp/Desktop/test

# no need to run php, just a demo of a common config
fastcgi / /run/php/php7.2-fpm.sock php

rewrite {
	# if {file} not_has "#"
	to {path} {path}/ /index.php?{query}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
On macOS 10.14:
`./caddy -conf /Users/ngyikp/Desktop/test/Caddyfile`

On the production server running Debian GNU/Linux 9.5:
`/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp`

### 6. What did you expect to see?
It should be possible to navigate to filenames with hashes on them

### 7. What did you see instead (give full error messages and/or log)?
Assuming the file "#abc.htm" contains a success message

```
$ http "http://127.0.0.1:2015/%23abc.htm"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 34
Content-Type: text/html; charset=utf-8
Date: Tue, 02 Oct 2018 10:29:15 GMT
Etag: "pfyvl5y"
Last-Modified: Tue, 02 Oct 2018 10:24:41 GMT
Server: Caddy

<a href="%23abc.htm">click me</a>
```

I found a workaround by excluding rewrites with hashes on the filename, if you uncomment the line in the `rewrite` section on my config, then it is possible to navigate to it

```
$ http "http://127.0.0.1:2015/%23abc.htm"
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 16
Content-Type: text/html; charset=utf-8
Date: Tue, 02 Oct 2018 10:29:04 GMT
Etag: "pfyvojg"
Last-Modified: Tue, 02 Oct 2018 10:26:43 GMT
Server: Caddy

<h1>Success</h1>
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
```bash
echo '<a href="%23abc.htm">click me</a>' > index.htm
echo '<h1>Success</h1>' > '#abc.htm'

# launch caddy with the config
# launch your web browser and browse to http://127.0.0.1:2015/index.htm
# try to click the link
```

**Comment by mholt** [comment]
Fragments aren't sent to the server; they are for the client to use. See https://stackoverflow.com/questions/940905/can-i-read-the-hash-portion-of-the-url-on-my-server-side-application-php-ruby for a discussion about it.

**Comment by jakelucas** [comment]
@mholt I can see the confusion since this is about the `#` character, but I don't think @ngyikp is talking about the fragment here.

In this case they're talking about the `#` character being used in the path of a URL encoded as `%23`, which does get sent to the server.

**Comment by tobya** [comment]
@ngyikp  I may be doing something wrong or misunderstanding the issue, but I cant reproduce this with latest code.

With your caddyfile

``` 
http://127.0.0.1:2015

root /Users/ngyikp/Desktop/test

# no need to run php, just a demo of a common config
fastcgi / /run/php/php7.2-fpm.sock php

rewrite {

	to {path} {path}/ /index.php?{query}
}
```
Everything gets redirected to index.php with the %23 intact eg

http://example.com/%23asdf.txt is redirected to index.php

With the line included

```
http://127.0.0.1:2015

root /Users/ngyikp/Desktop/test

# no need to run php, just a demo of a common config
fastcgi / /run/php/php7.2-fpm.sock php

rewrite {
        if {file} not_has "#"
	to {path} {path}/ /index.php?{query}
}
```
Any file such as #asdf.txt that is requested as http://example.com/%23asdf.txt is displayed in the browser.

This appears to work correctly.  Perhaps you could explain the issue to me again if I have misunderstood.
