### ISSUE TITLE
Fix NameServer for caddyserver.com

### ISSUE THREAD

**Issue by mapl** [mholt/caddy#2311]
Please take a look at [https://mxtoolbox.com/SuperTool.aspx?action=dns%3acaddyserver.com&run=toolpage](url)

Local NS list does not match Parent NS list
107.181.178.180 was reported by the parent, but not locally<br/>88.198.106.11 was reported by the parent, but not locally

**Comment by mholt** [comment]
Thanks, forgot to get rid of those buddyns nameservers.

**Comment by mapl** [comment]
You're welcome. I've got a dns servfail back and couldn't reach the website. I wondered why and checked the dns health state.
