### ISSUE TITLE
Imports and snippets

### ISSUE THREAD

**Issue by p3lim** [mholt/caddy#2312]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0

### 2. What are you trying to do?
Using the [import directive](https://caddyserver.com/docs/import) I expect to be able to do either/both of the following:
1. Use a snippet defined in Dockerfile in imported files
2. Use a snippet in an imported file, also defining the snippet in the same file

### 3. What is your entire Caddyfile?

	$ tree /config
	├── Caddyfile
	└── domains
	    ├── domain1.com
	    └── domain2.com

Case 1:

	$ cat /config/Caddyfile
	(test) {
		root /www
	}
	import domains/*

	$ cat /config/domains/domain1.com
	foo.domain1.com {
		import test
	}

Case 2:

	$ cat /config/Caddyfile
	import domains/*

	$ cat /config/domains/domain1.com
	(test) {
		root /www
	}
	foo.domain1.com {
		import test
	}

### 4. How did you run Caddy (give the full command and describe the execution environment)?
See https://github.com/p3lim/docker-caddy

### 6. What did you expect to see?
No errors.

### 7. What did you see instead (give full error messages and/or log)?
Error message (same for both cases):

> Error during parsing: File to import not found: /config/domains/test

From the documentation for the directive:

> import allows you to use configuration from another file or a reusable snippet. **It gets replaced with the contents of that file or snippet.**

If the part in bold was true, both of my cases would work fine.

**Comment by p3lim** [comment]
Either consider it as an issue with the wording in the docs, or as a feature request to actually make it work.

**Comment by zul-jin** [comment]
Try replacing `import domains/*` with `import ../domains/*` and see if that works.

**Comment by p3lim** [comment]
Using `import ../domains/*` didn't seem to load any of the files in the domains directory.

**Comment by p3lim** [comment]
A way around this issue is ignoring snippets entirely and using imports like this:

	$ tree /config
	├── Caddyfile
	├── test
	└── domains
	    ├── domain1.com
	    └── domain2.com

	$ cat /config/Caddyfile
	import domains/*

	$ cat /config/test
	root /www

	$ cat /config/domains/domain1.com
	foo.domain1.com {
		import ../test
	}

Would still prefer snippets working though.

**Comment by dpantel** [comment]
I think this was fixed, but hasn't made it into a new release yet.  See #2204 and #2205.

**Comment by p3lim** [comment]
Thanks for finding that, seems like that covers this issue exactly. Closing this as a duplicate then.
