### ISSUE TITLE
feature request: directive to specify host-to-path mapping

### ISSUE THREAD

**Issue by indrora** [mholt/caddy#2317]
### 1. What version of Caddy are you using (`caddy -version`)?

Caddy 0.11.0 (unofficial)

### 2. What are you trying to do?

I'd like to have a directive that lets me specify how to mangle the path relative to the root based on the hostname that the request came through, similar to lighttpd's [mod_evhost](https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModEVhost) module.

Searching through the forums, this appears to have been a common request, and one which has had varying answers of varying states of working-ness. The "easy" way is to use 

```
rewrite / {
  to {host}{uri}
}
```

but when I attempted this, I was left in a redirect loop. Other suggestions included 

```
rewrite { 
  to /{host}/{path}
}

```

but that would fail when the path was a directory but the request path did not end in a trailing slash. This has lead me to simply bulk up on each domain and its children for directives, making the resulting caddyfile longer than it really needs to be. 

while this would make a good candidate for a plugin, I don't know that the plugin architecture as it stands can in-situ rewrite the path that a file is served from internally. I briefly glanced at the documentation for middleware and could not find a good way to in-situ modify the request as it flowed through the request handlers. 

I don't know Go, or I'd have more technical words to put here. 

### 3. What is your entire Caddyfile?
```text
zaibatsutel.net {
	root /srv/www/zaibatsutel.net/  # let's hope this works?
	browse
	tls hell@zaibatsutel.net
}

atdot.xyz {
	root /srv/www/atdot.xyz/  # let's hope this works?
	tls hell@zaibatsutel.net
}

layer-eight.photography {
	root /srv/www/layer-eight.photography/  # let's hope this works?
	tls hell@zaibatsutel.net
}

tsunami.zaibatsutel.net {
	root /srv/www/tsunami.zaibatsutel.net/  # let's hope this works?
	browse
	tls hell@zaibatsutel.net
}
rendezvous.zaibatsutel.net {
	proxy / localhost:8384
	tls hell@zaibatsutel.net
}

```

it would be nice if I could turn this into 

```text

zaibatsutel.net,
atdot.xyz
layer-eight.photography {
   root /srv/www/
   vhost_pattern {host}
}
# .... rest of config
```

previously with lighttpd I was using evhost's pattern directive to make it such that /(domain)/_/ was the root of the top level domain and /(domain)/(subdomain)/ was used if you went to any subdomain of that path that did not have a proxy already. 

### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -conf /opt/caddy/Caddyfile -accept=true `

### 5. Please paste any relevant HTTP request(s) here.
n/a

### 6. What did you expect to see?

n/a

### 7. What did you see instead (give full error messages and/or log)?

n/a

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

n/a

**Comment by mholt** [comment]
This is resolved in Caddy 2.
