### ISSUE TITLE
Allow multiple server blocks for same fqdn

### ISSUE THREAD

**Issue by thenewguy** [mholt/caddy#2325]
It would be very helpful when templating a caddyfile if caddy could handle site definitions that duplicate fqdn.  Here is a discussion: https://caddy.community/t/caddy-tls-cert-for-domain-certs/4556/6

I've been told that caddy wouldn't know which definition to use.  Perhaps there could be a way to specify priority or simply using definition order to decide would solve my use case

**Comment by tobya** [comment]
Thank you for the issue. 

I will close this issue.   However if you have a more specific feature request or would like to submit a PR we would be happy to take it.
