### ISSUE TITLE
Caddy does not start up anymore when docker service is running

### ISSUE THREAD

**Issue by VanCoding** [mholt/caddy#2326]
I've installed docker on a server, where I also have caddy running as a reverse proxy for a lot of sites. But as soon as I start the docker service and then try to restart caddy, caddy won't start up with the message: 
```
Caddyfile loaded multiple times; first by docker, then by flag
# Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
New CaddyFile:
```

I guess this is because of the docker plugin detecting that there is docker running in the background and trying to do something with it. But in my case, this is not desired.

Is there a way to disable the plugin through a paramter?
I think it would be even be better to disable this by default and then require the user to enable it through a parameter, since probably noone expects caddy to interact with docker when a Caddyfile was provided.

**Comment by francislavoie** [comment]
I think you should ask here: https://github.com/lucaslorentz/caddy-docker-proxy

You could also redownload or recompile Caddy without the docker plugin
