### ISSUE TITLE
Weird behavior with file browser when directory has seperate root directory

### ISSUE THREAD

**Issue by steamp0rt** [mholt/caddy#2328]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0 

### 2. What are you trying to do?
Have a directory with a different root, and be able to use look through the files with `browse`

### 3. What is your entire Caddyfile?
```text
www.sunsetstation13.com sunsetstation13.com {
        proxy / https://sunsetstation.github.io
        proxy /sunset https://sunsetstation13.com/parsed-logs/sunset
}

www.sunsetstation13.com/parsed-logs sunsetstation13.com/parsed-logs {
        root /var/www/sunsetstation13.com/stats/parsed-logs
        browse
        gzip
}

```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd

### 6. What did you expect to see?
Clicking on the `sunset` folder in `sunsetstation13.com/parsed-logs` should take me to `sunsetstation13.com/parsed-logs/sunset`

### 7. What did you see instead (give full error messages and/or log)?
Clicking on the `sunset` folder takes me to `sunsetstation13.com/sunset`

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Literally copy the caddyfile config above and strip the `proxy /sunset https://sunsetstation13.com/parsed-logs/sunset` (current workaround i'm using)

**Comment by mholt** [comment]
Ah, I remember this one. It's not really a bug; Caddy is technically doing what you told it to do. Append your site definitions with a `/` forward slash, so `www.sunsetstation13.com/parsed-logs/ sunsetstation13.com/parsed-logs/` and then it will know that there is a directory delineation there. The path in the address part of the Caddyfile is technically a prefix, not bounded by directory structure, since it might not be serving a directory structure.

**Comment by steamp0rt** [comment]
Also, @mholt, this is completely unrelated, but how do I serve already gzipped .txt files and letting the browser un-zip them?

**Comment by mholt** [comment]
>  this is completely unrelated, but how do I serve already gzipped .txt files and letting the browser un-zip them, like what you'd get with nginx and gzip_static on;?

Don't use the gzip directive, then add this header to the response: `Content-Encoding: gzip`

**Comment by steamp0rt** [comment]
@mholt Yeah but I can't find a way to apply headers exclusively to .gz files

**Comment by steamp0rt** [comment]
and it breaks `browse`, @mholt
