### ISSUE TITLE
Caddy run failed and display: "...... remote error: tls: bad record MAC"

### ISSUE THREAD

**Issue by kennethgao** [mholt/caddy#2329]
### 1. What version of Caddy are you using (`caddy -version`)?

pakage which download from github : caddy_v0.11.0_windows_amd64.zip
version info:

``` text
D:\App\caddy_v0.11.0> .\caddy.exe -version
Caddy 0.11.0 (+1f7b5ab Thu May 10 15:51:56 UTC 2018) (unofficial)
1 file changed, 1 insertion(+), 1 deletion(-)
caddy/caddymain/run.go
```

### 2. What are you trying to do?
  
I want to run an https server automatic.  I have run cmd :  ".\caddy.exe"

### 3. What is your entire Caddyfile?
```text
booking.xxx.org {

	#-----这一节配置不要动-------
	header / -Server	
	tls 123456789@qq.com
	root D:\App\caddy_v0.11.0\wwwroot\
	index index.html
	errors ./errors.log
	#-----------end-----------------
	
	#----------Tomcat 站点分发-------------
	#配置格式：
	#proxy /项目名  http://10.161.230.2:Tomcat项目端口 {
	#	transparent
	#}
	
	##
	proxy /p1839 http://10.161.230.2:1839 {
		transparent
	}
	#-----------end-----------------
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
OS:  windows server 2008  R2 Enterprise 
how I run the caddy:

``` text
> D:\App\caddy_v0.11.0\
>.\caddy.exe
```
the config file is D:\App\caddy_v0.11.0\caddyfile

### 6. What did you expect to see?

run caddy success and automatic https server.

### 7. What did you see instead (give full error messages and/or log)?

When run the command ".\caddy.exe" trying to start caddy, errors report below:

``` text
Activating privacy features... 2018/10/29 14:02:14 [booking.xxx.or
g] failed to obtain certificate: Failed to post JWS message. -> Failed to HTTP P
OST to https://acme-v02.api.letsencrypt.org/acme/new-order -> Post https://acme-
v02.api.letsencrypt.org/acme/new-order: remote error: tls: bad record MAC
```

**Comment by mholt** [comment]
That's odd. Is there a TLS proxy between you and the Let's Encrypt servers?

**Comment by magikstm** [comment]
@kennethgao could you please test with Caddy 0.11.3?
