### ISSUE TITLE
Could not stop/restart Caddy on Windows Server 2008

### ISSUE THREAD

**Issue by chinkung** [mholt/caddy#2331]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0

### 2. What are you trying to do?
Try to stop/restart Caddy after change configuration file on Windows Server 2008 but it did not stop.

### 3. What is your entire Caddyfile?
```
https://example.com {
	gzip
	push
	tls C:/caddy/certs/example.crt C:/caddy/certs/example.key {
		ciphers ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-WITH-CHACHA20-POLY1305 ECDHE-RSA-WITH-CHACHA20-POLY1305 ECDHE-RSA-AES128-CBC-SHA ECDHE-ECDSA-AES128-CBC-SHA RSA-AES128-CBC-SHA
		curves X25519 p256
	}
	header / {
		X-XSS-Protection "1; mode=block"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "SAMEORIGIN"
		Strict-Transport-Security "max-age=31536000;"
		-Server
		-X-Powered-By
	}
	proxy / http://example.com {
		transparent
	}
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
caddy -service install -quic -conf c:\caddy\Caddyfile -name caddy
```
and start/stop Caddy using **Administrative Tools > Services**

I have tried to run with command line by open cmd.exe and run caddy.exe directly and found this problem happen after Caddy run for a while and there is connection open with the client, if you press Ctrl+C, Caddy didn't response to kill signal and leave caddy.exe running (Caddy did not receive new connection anymore after your press Ctrl+C on console, just running and you need to restart server to make it run again).

### 5. Please paste any relevant HTTP request(s) here.
N/A

### 6. What did you expect to see?
Can stop/restart Caddy without problem

### 7. What did you see instead (give full error messages and/or log)?
There is no error log, Caddy just failed to stop and leave caddy.exe process that could not be killed and finally need to restart server to make Caddy run and receive connection again.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
N/A

**Comment by mholt** [comment]
Hi, thanks for filling out the issue template. However, this looks more like a bug with the service plugin, which is not maintained by us. Please take a moment to open this issue [on the service plugin's repository](https://github.com/hacdias/caddy-service/issues). Thanks! /cc @hacdias

**Comment by chinkung** [comment]
Thanks for suggestion @mholt , I have opened https://github.com/hacdias/caddy-service/issues/23

The reason I open issue here because I can reproduce this issue using command line by run caddy.exe through Windows command prompt and wait for a while until there is a connection open with multiple client, if you press Ctrl+C, Caddy didn't response to kill signal and leave caddy.exe running (Caddy did not receive new connection anymore after your press Ctrl+C on console, just running and you need to restart server to make it run again)
