### ISSUE TITLE
failed to get certificate: acme: Error 400 when getting validation data

### ISSUE THREAD

**Issue by yunfengsay** [mholt/caddy#2332]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (+1f7b5ab Thu May 10 15:51:18 UTC 2018) (unofficial)

### 2. What are you trying to do?
run caddy

### 3. What is your entire Caddyfile?
```text
api.position.group

ext .html
log log.log
errors error.log {
	404 404.html
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Linux VM_72_172_centos 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### 5. Please paste any relevant HTTP request(s) here.

2018/11/02 10:00:50 [INFO][api.position.group] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/r_dFKHEo1VFSRYewmohlLDVccqwDOcGm3tekybUduzA
2018/11/02 10:00:50 [INFO][api.position.group] acme: Could not find solver for: tls-alpn-01
2018/11/02 10:00:50 [INFO][api.position.group] acme: Trying to solve HTTP-01
2018/11/02 10:00:56 [api.position.group] failed to get certificate: acme: Error 400 - urn:ietf:params:acme:error:connection - Fetching http://api.position.group/.well-known/acme-challenge/hOVRAbhkr8I7KsAfwf1HUTh7JR66ZI4v12djal18nek: Error getting validation data

### 6. What did you expect to see?
caddy normal

### 7. What did you see instead (give full error messages and/or log)?
caddy can not get https certificate

**Comment by yunfengsay** [comment]
The reason is china's domain need to record ....

**Comment by GeonChen** [comment]
i got the same issue, but it no relate with china's domain，i solved the issue when closed my firewall service.

**Comment by me1ting** [comment]
> i got the same issue, but it no relate with china's domain，i solved the issue after closed my firewall service.

I got the same issue when i change linux distribution from debians(debian,ubuntu...) to redhats(redhat,cenos...), and i solved the issue with your way.
