### ISSUE TITLE
Feature request: add "agree" to tls directive

### ISSUE THREAD

**Issue by dpantel** [mholt/caddy#2337]
This has been touched on before in #421.

At that time the argument was that the LetsEncrypt T&C agreement was not needed per site, but per user, and so the request was denied.

However, I would like to re-request that 'agree' flag be added to the tls directive.

Firstly, it saves those of us who install Caddy programmatically from having to edit the system init scripts.  And secondly, I can see a scenario where people use different users (email) to obtain certificates for different domains.  So multiple agreements have to be accepted.

**Comment by mholt** [comment]
Will be a non-issue in Caddy 2 since TLS configuration has been totally rearchitected.
