### ISSUE TITLE
Add new TLS client cert placeholders in documentation

### ISSUE THREAD

**Issue by Alex131089** [mholt/caddy#2342]
Hello, 

in https://github.com/mholt/caddy/pull/2217 new TLS placeholders were added, but they cannot be found in the documentation (https://caddyserver.com/docs/placeholders).
#2146 seems related.

Btw, is the documentation source hosted here? I tried to search if this was maybe corrected in an unreleased version but I couldn't find it.

Best,

**Comment by mholt** [comment]
Updated, thanks
