### ISSUE TITLE
dependency vendoring errors due to #2345

### ISSUE THREAD

**Issue by cblecker** [mholt/caddy#2348]
The changes introduced in #2345 (https://github.com/mholt/caddy/commit/d9e6e7ffa58bdd21cd9cef0d41802221a7b2fdc1) have caused issues when vendoring caddy in godep, and likely other tools.

In particular, the line endings in the following files show as changes, as soon as you clone the repo:
```
dist/CHANGES.txt
dist/README.txt
```

The error godep throws is this:
```
# cd /tmp/gopath.KZbghM/src/github.com/mholt/caddy; git checkout 2de495001514ed50eac2e09f474c32d417100c5c
error: Your local changes to the following files would be overwritten by checkout:
	dist/CHANGES.txt
	dist/README.txt
Please commit your changes or stash them before you switch branches.
Aborting
godep: error downloading dep (github.com/mholt/caddy/caddyfile): exit status 1
```

**Comment by cblecker** [comment]
cc: @tobya @mholt

**Comment by linquize** [comment]
Manually delete these files, then git reset --hard

**Comment by cblecker** [comment]
This is off a fresh clone. Extra steps shouldn't be needed. This is a problem with the source repo.

**Comment by cblecker** [comment]
It looks like it's just three files that have bad line endings:
```
warning: CRLF will be replaced by LF in dist/CHANGES.txt.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in dist/LICENSES.txt.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in dist/README.txt.
The file will have its original line endings in your working directory
```

Might be able to be fixed with https://github.com/mholt/caddy/pull/2351

**Comment by mholt** [comment]
Please verify that #2351 has fixed this, and then we can close it.

**Comment by cblecker** [comment]
We’ve verified that godeps is now back up and running.

Thanks for your prompt attention to this!
