### ISSUE TITLE
How to disable telemetry server at build time is not clear for someone not an experienced golang developer

### ISSUE THREAD

**Issue by krader1961** [mholt/caddy#2350]
I recently switched from a LAMP+Wordpress stack to Caddy+Hugo and am loving the experience. However, I'm annoyed by the telemetry warnings:

```
2018/11/17 20:01:48 [WARNING] Sending telemetry (attempt 1): telemetry server replied with unknown content-type: 'text/plain; charset=utf-8' and HTTP 502 Bad Gateway - backing off and retrying
```

I have no objection to sending telemetry data in principal. But since I'm experimenting with enabling a custom plugin to blacklist IP addresses I decided to try disabling the telemetry feature, to reduce that noise, without success. The documentation at https://caddyserver.com/docs/telemetry seems to presume a knowledge of how to build  Golang projects that may not be entirely reasonable. I resorted to editing *caddy/caddymain/run.go*:

```
diff --git a/caddy/caddymain/run.go b/caddy/caddymain/run.go
index e17fdde..ef84b70 100644
--- a/caddy/caddymain/run.go
+++ b/caddy/caddymain/run.go
@@ -525,4 +525,4 @@ var (
 )

 // This variable defines whether telemetry is enabled in Run.
-var EnableTelemetry = true
+var EnableTelemetry = false
```

**Comment by abiosoft** [comment]
Yeah, that is how to go about it. The other option is to disable telemetry when downloading from https://caddyserver.com/download. 

Currently you cannot disable telemetry at startup/runtime, only in the source before building.

**Comment by krader1961** [comment]
> If building from source, you can set  enableTelemetry to false to turn it off.

I was confused by that sentence in part because it followed the paragraph that talked about the `-disabled-metrics` run-time flag. Coupled with the fact it can be disabled when downloading a custom build suggested to me that the `enableTelemetry` mention was a reference to doing the Go equivalent of `cc -DenableTelemetry=0`. It might be worth rewording that sentence along the following lines:

> If building from source you can edit *caddy/caddymain/run.go* changing `var EnableTelemetry = true` to `false`.

Or not if this is just a case of my reading comprehension suffering due to being slightly inebriated at the time. :smile:
