### ISSUE TITLE
Why doesn't caddy have a Patreon?

### ISSUE THREAD

**Issue by zllovesuki** [mholt/caddy#2355]
1. From what I understand, caddy (the open-source) is still driven by community, while caddy (the binary) is trying to be sustainable by running a business
2. Again, from my limited insight of the past debates/discussions, Patreon would be a good way for the community to give back monetarily ($1 is still a $1). 
3. Those who wish to contribute intellectually (read: code) can still do so
4. Also, https://caddyserver.com/telemetry/summary is giving me a 502

**Comment by mholt** [comment]
> 1. From what I understand, caddy (the open-source) is still driven by community, while caddy (the binary) is trying to be sustainable by running a business

Correct! :)

> 2. Again, from my limited insight of the past debates/discussions, Patreon would be a good way for the community to give back monetarily ($1 is still a $1).

It's a nice gesture, but I'd rather have people contribute by making contributions, reviewing changes, and helping them get merged to make the project better.

> 4. Also, https://caddyserver.com/telemetry/summary is giving me a 502

Yeah, we ran out of space. No one has expressed interest in seriously using it so it's not really a priority  for me to pay for and maintain.

**Comment by francislavoie** [comment]
But if you let us pay you via Patreon, you could afford to keep telemetry running. Just sayin' 😛 

IMO I don't really see myself ever paying for a license as it stands because I run Caddy from Docker anyways.

**Comment by mholt** [comment]
> But if you let us pay you via Patreon, you could afford to keep telemetry running. Just sayin' 😛

Doubtful -- it's quite expensive... next time I work on it I will probably be culling old data on a regular basis so that only the most recent ~100 GB or so is kept. (I know that's not much but my budget is tight for it.)
