### ISSUE TITLE
Failed to set up quic proxy connection between caddy

### ISSUE THREAD

**Issue by yjp211** [mholt/caddy#2357]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.1
### 2. What are you trying to do?
Deploy two Caddy
The proximal caddy receives the HTTP request, turns it into quic and sends it to the distal caddy

### 3. What is your entire Caddyfile?
proximal caddy(ip: 192.168.40.201)
```
192.168.40.201

log ./access.log
errors ./error.log

proxy /quic quic://192.168.40.202:2015 {
}
```
distal caddy(ip:192.168.40.202)
```
192.168.40.202

log ./access.log
errors ./error.log
tls self_signed
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
 QUIC_GO_LOG_LEVEL=DEBUG ./caddy -quic -log stdout
```

### 5. Please paste any relevant HTTP request(s) here.

```
 [20/Nov/2018:13:44:46 +0000] "GET /quic HTTP/1.1" 502 16
```

### 6. What did you expect to see?

proxy success and return the data from 192.168.40.202

### 7. What did you see instead (give full error messages and/or log)?
Quic connection between caddy was not established successfully.

```
2018/11/20 14:51:47 client Certificate validation failed: x509: certificate signed by unknown authority
2018/11/20 14:51:47 client Closing session with error: ProofInvalid
2018/11/20 14:51:47 client -> Sending packet 0x7 (37 bytes) for connection (empty), unencrypted
2018/11/20 14:51:47 client 	Long Header{Type: Handshake, DestConnectionID: 0x1e422fc654effd98, SrcConnectionID: (empty), PacketNumber: 0x7, PacketNumberLen: 4, Version: gQUIC 44}
2018/11/20 14:51:47 client 	-> &wire.ConnectionCloseFrame{ErrorCode:0x2a, ReasonPhrase:""}
2018/11/20 14:51:47 client Connection (empty) closed.
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

It is easy to reproduce according to my configuration

**Comment by francislavoie** [comment]
Well, the error says `certificate signed by unknown authority` and you used `tls self_signed`, so that would be the first thing to look at. Does it work if you use a real certificate?

**Comment by yjp211** [comment]
> Well, the error says `certificate signed by unknown authority` and you used `tls self_signed`, so that would be the first thing to look at. Does it work if you use a real certificate?

Thx
After configuring the domain name and using certbot to make SSL certificates, it works.

But it must be configured as follows to work:
distal caddy(Must start on port 443):
```
replica.yjp211.com

log ./access.log
errors ./error.log

tls /data/www/cert/fullchain.pem /data/www/cert/privkey.pem
```
proximal caddy:
```
10.10.3.202

log ./access.log
errors ./error.log

proxy /quic quic://replica.yjp211.com
```

The caddy would be exposed, and I just wanted it to take on quic forwarding.

**Comment by francislavoie** [comment]
At this point, I don't see this as an issue with Caddy, but rather with QUIC. So I'll point you to ask here: https://github.com/lucas-clemente/quic-go. This can be reopened if an actual issue regarding this is found, but as far as I can tell, it seems to be working as intended.

**Comment by yjp211** [comment]
It works, but it's not ideal.  I've had the experience of using quic-go packaged for GRPC, quic-go doesn't seem to limit certificates and ports.
Caddy is great, and I hope I can contribute something to it. Thanks again

**Comment by neil88** [comment]
> 好吧，错误说`certificate signed by unknown authority`并且你使用过`tls self_signed`，所以这将是第一件要看的东西。如果您使用真实证书，它是否有效？

hi，I've been wondering，  Why we must apply for domain and certificate, what is their function?
