### ISSUE TITLE
Caddy will add one goroutine each time reload the configure file

### ISSUE THREAD

**Issue by chengsurf** [mholt/caddy#2358]
Recently I ran into an issue: when caddy is running, my test script keeps sending the USR1 signal to it, then I find the free memory of the device is decreasing slowly. I doubt if there is memory leak under the certain occasion that send the USR1 signal to the running caddy engine.

To verify this，I add a special goroutine just in the file “run.go” to print the number of all used goroutine through the function call : runtime.NumGoroutine. Finally, I see the number of goroutine is indeed adding one every time caddy reloads the configure file. The increasing trend is not apparently instead one by one.

After code review and log analysis, I find the problem in the function “startServers” of the file “caddy.go”. In this function, the variable of “errChan” is created at the beginning and used in the next three goroutine. But the last goroutine that loop this channel, it’s running forever until the channel “errChan” is closed. However this channel is not closed. So the channel “errChan” is keep alive since it’s created. Even if caddy receive the USR1 signal and reload config , this goroutine is not exited and cause memory leak. 

### 1. What version of Caddy are you using (`caddy -version`)?

0.11.0

### 2. What are you trying to do?
I add a special goroutine just in the file “run.go” to print the number of all used goroutine through the function call : runtime.NumGoroutine. Then  my test script keeps sending the USR1 signal to caddy.

### 3. What is your entire Caddyfile?
http://www.testexample.com {
    proxy /  10.67.8.123
}

### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -conf ./Caddyfile

### 5. Please paste any relevant HTTP request(s) here.

NULL

### 6. What did you expect to see?

 The total number of goroutine is not increased after reloading the configure file and the free memory is not decreased.

### 7. What did you see instead (give full error messages and/or log)?

After caddy reload the configure file, the free memory of the device is decreased and the total number of goroutine is increased.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
**test script:**
while true
do
    sudo kill -s USR1 112030
done

**caddy modify:**      run.go  add the follow function:
func printgoNum() {
    for {
        time.Sleep(1*time.Second)
        fmt.Println("number goroutine is ", runtime.NumGoroutine(), "\n")
    }
}

**log** 

number goroutine is  100
number goroutine is  101
number goroutine is  102

**Comment by francislavoie** [comment]
Would you be willing to submit a pull request to fix it?

**Comment by mholt** [comment]
Ah, great observation. Thank you! I am on holiday at the moment but would happily accept a PR to fix this. :)
