### ISSUE TITLE
http.log

### ISSUE THREAD

**Issue by neil88** [mholt/caddy#2360]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1

### 2. What are you trying to do?
I configured the custom log output format，but it not effect

### 3. What is your entire Caddyfile?
```text
xxx.com
log /home/ubuntu/neil/caddy_log/ access.log "{proto} Request: {method} {path}"
errors /home/ubuntu/neil/caddy_log/error.log
tls /home/ubuntu/neil/cert/fullchain.pem /home/ubuntu/neil/cert/privkey.pem
proxy / http://localhost:8080
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -conf /usr/local/bin/Caddyfile -quic -port 443 &

### 5. Please paste any relevant HTTP request(s) here.

curl https://sync.yjp211.com/

### 6. What did you expect to see?
I wanna see the proto,method path,Time consuming

### 7. What did you see instead (give full error messages and/or log)?
open {proto} permission deny

**Comment by krader1961** [comment]
> log /home/ubuntu/neil/caddy_log/ access.log "{proto} Request: {method} {path}"

You have a space in the pathname to the log file: `...log/ access...`. Also, you are missing the "path" argument which specifies which URL paths that match the prefix should be written to the log file which is the second argument. If you want every request written to that log file you should write `log / /home/ubuntu/...`.

**Comment by francislavoie** [comment]
Ha! You beat me to it @krader1961

I'll close this as it's a question and not an issue with Caddy. I recommend you ask on the forums next time: https://caddy.community/
