### ISSUE TITLE
Add `{when_iso_local}` placeholder

### ISSUE THREAD

**Issue by krader1961** [mholt/caddy#2362]
### 1. What version of Caddy are you using (`caddy -version`)?

Git commit 8f7a1d6a2 from Nov 18, 2018.

### 2. What are you trying to do?

I prefer the ISO 8601 timestamp format but when perusing the log file it is friendlier if the human readable timestamps are in the local timezone of the server rather than UTC. So I'd like to propose adding a `{when_iso_local}` placeholder. The implementation is trivial:

```
diff --git a/caddyhttp/httpserver/replacer.go b/caddyhttp/httpserver/replacer.go
index 945b93e..8755f40 100644
--- a/caddyhttp/httpserver/replacer.go
+++ b/caddyhttp/httpserver/replacer.go
@@ -368,6 +368,8 @@ func (r *replacer) getSubstitution(key string) string {
                return url.QueryEscape(r.request.URL.RequestURI())
        case "{when}":
                return now().Format(timeFormat)
+       case "{when_iso_local}":
+               return now().Format(timeFormatISO)
        case "{when_iso}":
                return now().UTC().Format(timeFormatISOUTC)
        case "{when_unix}":
@@ -539,6 +541,7 @@ func (r *replacer) Set(key, value string) {

 const (
        timeFormat        = "02/Jan/2006:15:04:05 -0700"
+       timeFormatISO     = "2006-01-02T15:04:05" // ISO 8601 with timezone to be assumed as local
        timeFormatISOUTC  = "2006-01-02T15:04:05Z" // ISO 8601 with timezone to be assumed as UTC
        headerContentType = "Content-Type"
        contentTypeJSON   = "application/json"
```

For automated log file analysis I also include the `{when_unix_ms}` placeholder. This gives analysis tools an unambiguous timestamp while giving humans an easier to interpret string via the `{when_iso_local}` placeholder. Yes, this is itself problematic if you have personnel in different time zones who need to peruse the logs. But in that case you can either use the UTC timestamps and/or a tool to convert the UTC timestamps to each person's local timezone. This enhancement is primarily for people who are using Caddy as a personal web server.

**Comment by francislavoie** [comment]
Cool, feel free to make a PR for this change!
