### ISSUE TITLE
always returns 502 after the quic proxy's upstream restart

### ISSUE THREAD

**Issue by yjp211** [mholt/caddy#2364]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.1

### 2. What are you trying to do?

Deploy two Caddy
The proximal caddy receives the HTTP request, turns it into quic and sends it to the distal caddy.

It works well, but as long as you restart the distal caddy, it always returns 502. No matter how restored, can you only restart proximal caddy.

### 3. What is your entire Caddyfile?

distal Caddyfile:
```
replica.yjp211.com:5050

log ./access.log
errors ./error.log

tls /data/www/cert/fullchain.pem /data/www/cert/privkey.pem
```
proximal Caddyfile:
```
:5050

log ./access.log
errors ./error.log

proxy /quic quic://replica.yjp211.com:5050
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
QUIC_GO_LOG_LEVEL=DEBUG ./caddy -quic -log stdout

### 5. Please paste any relevant HTTP request(s) here.

502 Bad Gateway

### 6. What did you expect to see?

after the restart can continue to work

### 7. What did you see instead (give full error messages and/or log)?

it return to 502 until I restart proximal caddy

log of distal caddy:
```
2018/11/22 12:50:35 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:35 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:35 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:36 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:36 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:37 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:37 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:38 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:40 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:40 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
2018/11/22 12:50:44 server error handling packet from 52.80.128.218:58677: dropping small packet for unknown connection
```
log of proximal caddy:
```
2018/11/22 12:50:53 client -> Sending packet 0x1c (57 bytes) for connection (empty), forward-secure
2018/11/22 12:50:53 client 	Short Header{DestConnectionID: 0x45a028f31fb3fdd7, PacketNumber: 0x1c, PacketNumberLen: 2, KeyPhase: 0}
2018/11/22 12:50:53 client 	-> &wire.ConnectionCloseFrame{ErrorCode:0x19, ReasonPhrase:"No recent network activity."}
2018/11/22 12:50:53 client Connection (empty) closed.
2018/11/22 12:50:53 client Error handling header stream: NetworkIdleTimeout: No recent network activity.
```
proximal caddy seems to be using the previous connection and not trying to make a new one

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

It is easy to reproduce according to my configuration

**Comment by yjp211** [comment]
RoundTripper of quic-go causes this problem

**Comment by magikstm** [comment]
@yjp211 could you please test with Caddy 0.11.3?
