### ISSUE TITLE
Caddyfile lexer bug

### ISSUE THREAD

**Issue by dafanasiev** [mholt/caddy#2366]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1 (+ce0988f Mon Nov 19 11:57:34 UTC 2018) (unofficial)

### 2. What are you trying to do?
I'm try to setup very simple configuration (see below), but caddy wont work normally (because configuration file lexer bug?)

### 3. What is your entire Caddyfile?
```text
https://localhost:8888 {

    header / X-Cert-ClientSubjectDn "{tls_client_s_dn}"

    tls self_signed {clients verify_if_given ca.crt}

}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
Just put config file near the bin and run `./caddy`

### 5. Please paste any relevant HTTP request(s) here.

```
 curl --insecure -E client.crt:1234 --key client.key -i https://localhost:8888
```

### 6. What did you expect to see?
```
<h1>Its work!</h1>
```

### 7. What did you see instead (give full error messages and/or log)?
```
curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
```

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
//you can generate client certs using this manual https://gist.github.com/mtigas/952344
Ok, and now about 'real' bug.
I see that lexer in [line 118](https://github.com/mholt/caddy/blob/master/caddyfile/lexer.go#L118) tokenize input and think that lexems separates by `unicode.IsSpace(ch)`. Its ok, but in my case lexer produce `{client` and `ca.crt}`  (yes, with curves) tokens (bug?)

Im not sure, that  this is not expected, can u explain caddy configuration file rules more detailed?

**Comment by mholt** [comment]
No, I don't think that's the bug. From [the docs](https://caddyserver.com/docs/caddyfile):

> Directives may span multiple lines by opening a block. Blocks are enclosed by curly braces { }. The opening curly brace { must be at the end of the directive's first line, and the closing curly brace } must be the only token on its line:

So your Caddyfile is malformed, but the bug is that Caddy should show an error when parsing the Caddyfile, not silently allowing it to pass.
