### ISSUE TITLE
Unchecked runtime.lastError: The message port closed before a response was received.

### ISSUE THREAD

**Issue by rjhilgefort** [mholt/caddy#2372]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.0

### 2. What are you trying to do?
Serve static sites

### 3. What is your entire Caddyfile?
```text
rob.hilgefort.me, www.rob.hilgefort.me, robhilgefort.com, www.robhilgefort.com {
  root /var/www/rjh-personal-page/public
  tls rjhilgefort@gmail.com
  internal /.git
  git  {
    repo git@github.com:rjhilgefort/rjh-personal-page.git
    branch master
    key /home/rjhilgefort/.ssh/id_rsa
    path ../
    then yarn install --offline
    then yarn run gatsby:build
    hook /caddyhook not-my-real-secret
  }
  gzip
  redir 301 {
    if {scheme} is http
    /  https://{host}{uri}
  }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp`
VPS on Digital Ocean. Debian.

### 5. Please paste any relevant HTTP request(s) here.
https://robhilgefort.com

### 6. What did you expect to see?
no errors in the console

### 7. What did you see instead (give full error messages and/or log)?
I'm seeing an issue when it loads and while the page is running.
> Unchecked runtime.lastError: The message port closed before a response was received.

![image](https://user-images.githubusercontent.com/2034823/48390921-77ee9080-e6c1-11e8-829e-beb6893d9603.png)

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
I'm just running on a Digital Ocean VPS, serving up a static site using the command I pasted above. Please let me know what other info would be helpful.

**Comment by rjhilgefort** [comment]
This is also causing problems in iOS safari that causes the page not to load.

**Comment by mholt** [comment]
Hmm, this does not look like a Caddy error. (Caddy errors would not be rendered client-side.)

**Comment by francislavoie** [comment]
This seems like a browser extension issue, or due to some JS loaded on your page. Nothing here points to an issue with Caddy.

https://stackoverflow.com/questions/43154963/promise-error-the-message-port-closed-before-a-reponse-was-received

**Comment by rjhilgefort** [comment]
I installed FireFox and tried- does seem to be some extension. Sorry for the issue.
