### ISSUE TITLE
Glitch text crashes Caddy

### ISSUE THREAD

**Issue by Henrocker** [mholt/caddy#2373]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (+03b10f9 Wed Oct 17 21:25:30 UTC 2018) (unofficial)
3 files changed, 19 insertions(+), 7 deletions(-)
caddy/caddymain/run.go
caddyhttp/browse/setup.go
caddytls/config.go

### 2. What are you trying to do?
Performing a GET request against a text file by typing glitch characters into the request form.

### 3. What is your entire Caddyfile?
```text
https://domain.com, https://domain.com    {
        tls /etc/crt.crt /etc/key.key
        gzip {
                ext *
                level 4
        }
        fastcgi / unix:/run/php.sock php {
                root    html
        }
        header / {
                Strict-Transport-Security "max-age=31536000; includeSubdomains; preload;"
                X-XSS-Protection "1; mode=block;"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "SAMEORIGIN"
                Referrer-Policy "strict-origin-when-cross-origin"
        }
        limits {
                header 64kb
                body 8gb
        }
        markdown
        log / logs/access.log {
                rotate_size     10
                rotate_age      14
                rotate_keep     10
                rotate_compress
        }
        root html
        ext .html .htm .php
        errors logs/error.log
        timeouts none
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
`./caddy -agree=true -conf=/etc/Caddyfile -email=mail@mail.com -quic` 

### 6. What did you expect to see?
Caddy returning an error/refusing the query

### 7. What did you see instead (give full error messages and/or log)?
Caddy crashed and exited. Nothing written to error.log.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?

Setup simple html form with a get request to a file. Use [this](https://hnrk.io/test) glitch character, insert it into the form and submit. Then caddy stopps working.

**Comment by linquize** [comment]
I created index.html and paste the glitch text into the text box then submit. But caddy did not crash.

```html
<html>
<body>
<form method="POST">
<input type="text" name="test">
<input type="submit">
</form>
</body>
</html>
```

**Comment by Henrocker** [comment]
@linquize [This](https://github.com/Henrocker/cfresolv) is my example.

A html form, that performs a GET, not a POST,  request to a text file via php.

Now when I type in the strange character, caddy dies.

**Comment by magikstm** [comment]
Please share strange character that you type in a text file.

What version of PHP are you using?

What OS are you using?

**Comment by Henrocker** [comment]
I am using PHP 7.2, on Debian 9.

txt file [here](https://hnrk.io/char.txt).

**Comment by magikstm** [comment]
What is the exact version of PHP that you are using?

Did you try it with a reduced caddyfile such as:
```
https://domain.com, https://domain.com    {
        tls /etc/crt.crt /etc/key.key
        fastcgi / unix:/run/php.sock php {
                root    html
        }
        root html
        errors logs/error.log
}
```

**Comment by Henrocker** [comment]
Issue still exists after I've recompiled caddy and used the config above, but not with the character I provided anymore, strangely. Generated a new one that is attached here: https://hnrk.io/char.html, that one crashes my caddy instance every time when inserted into a form that carries variable to php.

PHP version is 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215

**Comment by Henrocker** [comment]
I start to think this might be a duplicate of the sigsev ticket regarding quic errors.
