### ISSUE TITLE
Block HTTP Verbs or Whitelist HTTP Verb

### ISSUE THREAD

**Issue by jewome62** [mholt/caddy#2376]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1 

### 2. What are you trying to do?
Block HTTP verb TRACE or Custom Verb

I don't find any documentation about this.
Does that exist?

Thanks

**Comment by tobya** [comment]
You could use the redir directive to redirect to a 401 page when {method} is TRACE.

You will get better help on our forum here https://caddy.community/

**Comment by painslie** [comment]
Old post, but this response could help others.... this worked for me.
```javascript
        @unauthorizedMethod method TRACE
        respond @unauthorizedMethod "Sorry bro! " 401
```
