### ISSUE TITLE
Allow using import within proxy directive

### ISSUE THREAD

**Issue by euh2** [mholt/caddy#2378]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1 (+6f580c6 Sun Dec 02 00:15:50 UTC 2018) (unofficial)

### 2. What are you trying to do?
I'm trying to import a configuration within a `proxy directive`

### 3. What is your entire Caddyfile?
The relevant part of the Caddyfile
```text
example.com {
  import /etc/caddy/Caddyfile.d/log
  import /etc/caddy/Caddyfile.d/ipfilter
  import /etc/caddy/Caddyfile.d/realip
  proxy / 172.20.0.4:80/ {
    import /etc/caddy/Caddyfile.d/security_header_proxy ## <-- This Line causes the Error
    transparent
  }
```
The snippet I want to import with `import /etc/caddy/Caddyfile.d/security_header_proxy`
```text
header_downstream Strict-Transport-Security "max-age=31536000;"
header_downstream X-XSS-Protection "1; mode=block"
header_downstream X-Content-Type-Options "nosniff"
header_downstream X-Frame-Options "DENY"
header_downstream x-powered-by ""
header_downstream Server ""
header_downstream Referrer-Policy "no-referrer"
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?
I'm not sure if this is relevant, but I run Caddy with the Caddy File Loader for Docker (https://github.com/lucaslorentz/caddy-docker-proxy)

### 5. Please paste any relevant HTTP request(s) here.
_I add this if relevant_

### 6. What did you expect to see?
_I add this if relevant_

### 7. What did you see instead (give full error messages and/or log)?
``[ERROR] CaddyFile error: :60 - Error during parsing: unknown property 'import'``

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
_I add this if relevant_

**Comment by francislavoie** [comment]
Unfortunately, I don't think `import` is implemented to work inside of directives currently.

I think some logic to call `doImport` would need to be added around here: https://github.com/mholt/caddy/blob/master/caddyfile/parse.go#L369

A PR (with tests!) is welcome if you're willing to implement it!
