### ISSUE TITLE
fatal error:runtime:out of memory

### ISSUE THREAD

**Issue by hd999ljh** [mholt/caddy#2379]
### 1. What version of Caddy are you using (`caddy -version`)?
0.11.1

### 2. What are you trying to do?
using http.filemanager plugin

### 3. What is your entire Caddyfile?
```text
https://domain.com {
root /home/Downloads
tls xx@mail.com
gzip
filemanager / /home/Downloads {
        database /root/.caddy/filemanager/fm.db
        }
}
```

### 4. How did you run Caddy (give the full command and describe the execution environment)?
/usr/local/caddy/caddy -conf /usr/local/caddy/Caddyfile

### 6. What did you expect to see?
file manager

### 7. What did you see instead (give full error messages and/or log)?
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x109b598, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc4bc000000, 0x56c000000, 0x219ccf8)
        /usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x2182a40, 0x56c000000, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x2182a40, 0x2b43cd, 0x0)
        /usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x2182a40, 0x2b43cd, 0x219cd08, 0x20312c)
        /usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x2182a40, 0x2b43cd, 0xc0005c0101, 0x40bccf)
        /usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x2182a40, 0x2b43cd, 0xc000010101, 0x416395)
        /usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0x568798a00, 0x450101, 0x7fda13300440)
        /usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1229

goroutine 113 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc0005a64f8 sp=0xc0005a64f0 pc=0x459ba0
runtime.mallocgc(0x568798a00, 0xee11a0, 0x40bc01, 0xc0005a65d0)
        /usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc0005a6598 sp=0xc0005a64f8 pc=0x40c276
runtime.makeslice(0xee11a0, 0x568798a00, 0x568798a00, 0x8, 0x68, 0xc0001342a0)
        /usr/local/go/src/runtime/slice.go:70 +0x77 fp=0xc0005a65c8 sp=0xc0005a6598 pc=0x442b57
bytes.makeSlice(0x568798a00, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:231 +0x6d fp=0xc0005a6608 sp=0xc0005a65c8 pc=0x470b8d
bytes.(*Buffer).grow(0xc0001342a0, 0x568798a00, 0xc0005a6688)
        /usr/local/go/src/bytes/buffer.go:144 +0x15a fp=0xc0005a6658 sp=0xc0005a6608 pc=0x4704fa
bytes.(*Buffer).Grow(0xc0001342a0, 0x568798a00)
        /usr/local/go/src/bytes/buffer.go:163 +0x3a fp=0xc0005a6680 sp=0xc0005a6658 pc=0x4706aa
io/ioutil.readAll(0x1942260, 0xc000530000, 0x568798a00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:34 +0x93 fp=0xc0005a66c8 sp=0xc0005a6680 pc=0x4fc913
io/ioutil.ReadFile(0xc00003b680, 0x51, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:73 +0xd3 fp=0xc0005a6720 sp=0xc0005a66c8 pc=0x4fcb23
github.com/filebrowser/filebrowser.(*File).GetFileType(0xc000774f70, 0xc000774f00, 0x0, 0x0)
        /gopath/src/github.com/filebrowser/filebrowser/file.go:273 +0x24c fp=0xc0005a67a8 sp=0xc0005a6720 pc=0xae821c
github.com/filebrowser/filebrowser.(*File).GetListing(0xc0000b5110, 0xc0000f49a0, 0xc000139f00, 0x0, 0x0)
        /gopath/src/github.com/filebrowser/filebrowser/file.go:168 +0x8ca fp=0xc0005a6af0 sp=0xc0005a67a8 pc=0xae78ca
github.com/filebrowser/filebrowser/http.listingHandler(0xc0002ac270, 0x194c060, 0xc0002ac210, 0xc000139f00, 0x0, 0x0, 0x2f00000000741f6b)
        /gopath/src/github.com/filebrowser/filebrowser/http/resource.go:112 +0x81 fp=0xc0005a6c58 sp=0xc0005a6af0 pc=0xd81341
github.com/filebrowser/filebrowser/http.resourceGetHandler(0xc0002ac270, 0x194c060, 0xc0002ac210, 0xc000139f00, 0xffffffffffffffff, 0x6ec882, 0xc00042a2a0)
        /gopath/src/github.com/filebrowser/filebrowser/http/resource.go:81 +0x121 fp=0xc0005a6d90 sp=0xc0005a6c58 pc=0xd80ef1
github.com/filebrowser/filebrowser/http.resourceHandler(0xc0002ac270, 0x194c060, 0xc0002ac210, 0xc000139f00, 0x0, 0x0, 0x0)
        /gopath/src/github.com/filebrowser/filebrowser/http/resource.go:35 +0x427 fp=0xc0005a70e0 sp=0xc0005a6d90 pc=0xd80b67
github.com/filebrowser/filebrowser/http.apiHandler(0xc0002ac270, 0x194c060, 0xc0002ac210, 0xc000139f00, 0xd7b462f5cd3ece01, 0x7fda132ff000, 0x0)
        /gopath/src/github.com/filebrowser/filebrowser/http/http.go:161 +0x7a3 fp=0xc0005a7288 sp=0xc0005a70e0 pc=0xd7e863
github.com/filebrowser/filebrowser/http.serve(0xc0002ac270, 0x194c060, 0xc0002ac210, 0xc000139f00, 0xc000085180, 0x10, 0x10)
        /gopath/src/github.com/filebrowser/filebrowser/http/http.go:72 +0x28c fp=0xc0005a7320 sp=0xc0005a7288 pc=0xd7d8bc
github.com/filebrowser/filebrowser/http.Handler.func1(0x194c060, 0xc0002ac210, 0xc000139f00)
        /gopath/src/github.com/filebrowser/filebrowser/http/http.go:19 +0x99 fp=0xc0005a7408 sp=0xc0005a7320 pc=0xd89c99
net/http.HandlerFunc.ServeHTTP(0xc000085180, 0x194c060, 0xc0002ac210, 0xc000139f00)
        /usr/local/go/src/net/http/server.go:1964 +0x44 fp=0xc0005a7430 sp=0xc0005a7408 pc=0x6b3f24
github.com/filebrowser/caddy/filemanager.plugin.ServeHTTP(0x1942f40, 0xc0000c43c0, 0xc0001be158, 0x1, 0x1, 0x194c060, 0xc0002ac210, 0xc000139f00, 0xc0002a3500, 0x50, ...)
        /tmp/gopath_11-29-2055.350956452/src/github.com/filebrowser/caddy/filemanager/filemanager.go:33 +0x10e fp=0xc0005a7488 sp=0xc0005a7430 pc=0xd8b8ce
github.com/filebrowser/caddy/filemanager.(*plugin).ServeHTTP(0xc0000cc180, 0x194c060, 0xc0002ac210, 0xc000139f00, 0x0, 0x0, 0xc0002adad0)
        <autogenerated>:1 +0x77 fp=0xc0005a74f0 sp=0xc0005a7488 pc=0xd8bcf7
github.com/mholt/caddy/caddyhttp/errors.ErrorHandler.ServeHTTP(0x1942ae0, 0xc0000cc180, 0x0, 0x0, 0xc0002adad0, 0xc00026c480, 0x0, 0x194c060, 0xc0002ac210, 0xc000139f00, ...)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/errors/errors.go:50 +0x105 fp=0xc0005a7660 sp=0xc0005a74f0 pc=0xda82b5
github.com/mholt/caddy/caddyhttp/errors.(*ErrorHandler).ServeHTTP(0xc00032dec0, 0x194c060, 0xc0002ac210, 0xc000139f00, 0x1, 0x8, 0x203000)
        <autogenerated>:1 +0x86 fp=0xc0005a76d8 sp=0xc0005a7660 pc=0xdaa576
github.com/mholt/caddy/caddyhttp/gzip.Gzip.ServeHTTP(0x19410a0, 0xc00032dec0, 0xc00032ddc0, 0x1, 0x1, 0x194d8e0, 0xc000530008, 0xc000139f00, 0x0, 0x0, ...)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/gzip/gzip.go:90 +0x298 fp=0xc0005a77e8 sp=0xc0005a76d8 pc=0xdb74b8
github.com/mholt/caddy/caddyhttp/gzip.(*Gzip).ServeHTTP(0xc0000cc1b0, 0x194d8e0, 0xc000530008, 0xc000139f00, 0x0, 0xc000085100, 0x194eae0)
        <autogenerated>:1 +0x77 fp=0xc0005a7850 sp=0xc0005a77e8 pc=0xdba297
github.com/mholt/caddy/caddyhttp/httpserver.(*Server).serveHTTP(0xc0003bcc60, 0x194d8e0, 0xc000530008, 0xc000139e00, 0x5, 0xc0002ac120, 0x194eae0)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:445 +0x34f fp=0xc0005a79e0 sp=0xc0005a7850 pc=0xcdfd9f
github.com/mholt/caddy/caddyhttp/httpserver.(*Server).ServeHTTP(0xc0003bcc60, 0x194d8e0, 0xc000530008, 0xc000139e00)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:381 +0x5be fp=0xc0005a7bd8 sp=0xc0005a79e0 pc=0xcdf72e
github.com/mholt/caddy/caddyhttp/httpserver.(*tlsHandler).ServeHTTP(0xc0004653e0, 0x194d8e0, 0xc000530008, 0xc000138500)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/mitm.go:128 +0x482 fp=0xc0005a7d70 sp=0xc0005a7bd8 pc=0xcd12e2
net/http.serverHandler.ServeHTTP(0xc000420c30, 0x194d8e0, 0xc000530008, 0xc000138500)
        /usr/local/go/src/net/http/server.go:2741 +0xab fp=0xc0005a7da0 sp=0xc0005a7d70 pc=0x6b6b6b
net/http.initNPNRequest.ServeHTTP(0xc0004d8380, 0xc000420c30, 0x194d8e0, 0xc000530008, 0xc000138500)
        /usr/local/go/src/net/http/server.go:3291 +0x8d fp=0xc0005a7f18 sp=0xc0005a7da0 pc=0x6b85bd
net/http.(*initNPNRequest).ServeHTTP(0xc000084fb0, 0x194d8e0, 0xc000530008, 0xc000138500)
        <autogenerated>:1 +0x63 fp=0xc0005a7f50 sp=0xc0005a7f18 pc=0x6e1983
net/http.Handler.ServeHTTP-fm(0x194d8e0, 0xc000530008, 0xc000138500)
        /usr/local/go/src/net/http/h2_bundle.go:5592 +0x4d fp=0xc0005a7f80 sp=0xc0005a7f50 pc=0x6d9d1d
net/http.(*http2serverConn).runHandler(0xc000030380, 0xc000530008, 0xc000138500, 0xc00055c1c0)
        /usr/local/go/src/net/http/h2_bundle.go:5877 +0x89 fp=0xc0005a7fc0 sp=0xc0005a7f80 pc=0x68eef9
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0005a7fc8 sp=0xc0005a7fc0 pc=0x45bb01
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5611 +0x4d3

goroutine 1 [semacquire, 3 minutes]:
sync.runtime_Semacquire(0xc00028e2d8)
        /usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc00028e2d0)
        /usr/local/go/src/sync/waitgroup.go:130 +0x64
github.com/mholt/caddy.(*Instance).Wait(0xc000138000)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:458 +0x2f
github.com/mholt/caddy/caddy/caddymain.Run()
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy/caddymain/run.go:161 +0x646
main.main()
        src/github.com/mholt/caddy/caddy/main.go:27 +0x27

goroutine 36 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 37 [select, 3 minutes]:
github.com/mholt/caddy/caddytls.maintainAssets(0xc0001c40c0)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddytls/maintain.go:68 +0x120
created by github.com/mholt/caddy/caddytls.init.2
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddytls/maintain.go:32 +0x4e

goroutine 52 [chan receive, 3 minutes]:
github.com/mholt/caddy.trapSignalsCrossPlatform.func1()
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/sigtrap.go:45 +0x100
created by github.com/mholt/caddy.trapSignalsCrossPlatform
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/sigtrap.go:40 +0x35

goroutine 53 [chan receive, 3 minutes]:
github.com/mholt/caddy.trapSignalsPosix.func1()
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/sigtrap_posix.go:34 +0x13f
created by github.com/mholt/caddy.trapSignalsPosix
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/sigtrap_posix.go:30 +0x35

goroutine 54 [select, 3 minutes]:
github.com/robfig/cron.(*Cron).run(0xc0004624b0)
        /gopath/src/github.com/robfig/cron/cron.go:191 +0x28d
created by github.com/robfig/cron.(*Cron).Start
        /gopath/src/github.com/robfig/cron/cron.go:144 +0x58

goroutine 57 [chan receive, 3 minutes]:
github.com/mholt/caddy.startServers.func2(0xc0003bcd20)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:818 +0x41
created by github.com/mholt/caddy.startServers
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:817 +0x327

goroutine 12 [IO wait]:
internal/poll.runtime_pollWait(0x7fda11093f00, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00024cf98, 0x72, 0xc0005aa300, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00024cf98, 0xffffffffffffff00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc00024cf80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc00024cf80, 0x42b378, 0x348, 0xc00050ee00)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001be180, 0x42b1b4, 0xc4b3d12320, 0x7fda10e8f4d0)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).AcceptTCP(0xc0001be180, 0xf9, 0xc0000cedc8, 0x42b5a1)
        /usr/local/go/src/net/tcpsock.go:247 +0x47
github.com/mholt/caddy/caddyhttp/httpserver.tcpKeepAliveListener.Accept(0xc0001be180, 0x44b688, 0x258ecc1c168cc, 0xc026decc6d, 0x26decc6d000cee00)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:528 +0x2f
github.com/mholt/caddy/caddyhttp/httpserver.(*tlsHelloListener).Accept(0xc00053a040, 0xc0000cee50, 0x18, 0xc00025c300, 0x6b70a5)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/mitm.go:361 +0x37
net/http.(*Server).Serve(0xc000420c30, 0x194c1e0, 0xc00053a040, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2826 +0x22f
github.com/mholt/caddy/caddyhttp/httpserver.(*Server).Serve(0xc0003bcc60, 0x194e060, 0xc0001be180, 0x1096a66, 0x14)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:322 +0xa1
github.com/mholt/caddy.startServers.func1.1(0xc0003bcd20, 0x194ef20, 0xc0003bcc60, 0x194e060, 0xc0001be180, 0xc000138000)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:806 +0x49
created by github.com/mholt/caddy.startServers.func1
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:805 +0xac

goroutine 14 [select, 3 minutes]:
github.com/mholt/caddy/caddytls.standaloneTLSTicketKeyRotation(0xc00053db00, 0xc000582000, 0xc0000da000)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddytls/crypto.go:321 +0x239
created by github.com/mholt/caddy/caddytls.RotateSessionTicketKeys
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddytls/crypto.go:280 +0x8d

goroutine 41 [IO wait, 2 minutes]:
internal/poll.runtime_pollWait(0x7fda11093e30, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00024d018, 0x72, 0xc00055ef00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00024d018, 0xffffffffffffff00, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc00024d000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:384 +0x1a0
net.(*netFD).accept(0xc00024d000, 0x50, 0xfacae0, 0xc0000d2d01)
        /usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0001be188, 0xc0000d2dd8, 0xc000462320, 0x7509171b586ef9df)
        /usr/local/go/src/net/tcpsock_posix.go:139 +0x2e
net.(*TCPListener).AcceptTCP(0xc0001be188, 0xc0000d2e00, 0x49f6d6, 0x5c063a5f)
        /usr/local/go/src/net/tcpsock.go:247 +0x47
github.com/mholt/caddy/caddyhttp/httpserver.tcpKeepAliveListener.Accept(0xc0001be188, 0xc0000d2e50, 0x18, 0xc0004bb380, 0x6b70a5)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:528 +0x2f
net/http.(*Server).Serve(0xc0004211e0, 0x194e060, 0xc0001be188, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2826 +0x22f
github.com/mholt/caddy/caddyhttp/httpserver.(*Server).Serve(0xc0003bccc0, 0x194e060, 0xc0001be188, 0x0, 0x0)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/server.go:322 +0xa1
github.com/mholt/caddy.startServers.func1.1(0xc0003bcd20, 0x194ef20, 0xc0003bccc0, 0x194e060, 0xc0001be188, 0xc000138000)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:806 +0x49
created by github.com/mholt/caddy.startServers.func1
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddy.go:805 +0xac

goroutine 1168 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 1228 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5611 +0x4d3

goroutine 1237 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 1236 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5611 +0x4d3

goroutine 1235 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5611 +0x4d3

goroutine 1137 [select]:
net/http.(*http2serverConn).serve(0xc000030540)
        /usr/local/go/src/net/http/h2_bundle.go:4600 +0x52f
net/http.(*http2Server).ServeConn(0xc00053a080, 0x19548e0, 0xc00027e380, 0xc0005c9d50)
        /usr/local/go/src/net/http/h2_bundle.go:4219 +0x704
net/http.http2ConfigureServer.func1(0xc000420c30, 0xc00027e380, 0x1943880, 0xc4b3cd6000)
        /usr/local/go/src/net/http/h2_bundle.go:4057 +0x89
net/http.(*conn).serve(0xc000155ea0, 0x194eae0, 0xc25a4110b0)
        /usr/local/go/src/net/http/server.go:1771 +0xe4d
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 94 [IO wait]:
internal/poll.runtime_pollWait(0x7fda11093c90, 0x72, 0xc0000d0728)
        /usr/local/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc25a424d98, 0x72, 0xffffffffffffff00, 0x1943b00, 0x20e8500)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc25a424d98, 0xc4b3cca000, 0x400, 0x400)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc25a424d80, 0xc4b3cca000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc25a424d80, 0xc4b3cca000, 0x400, 0x400, 0xc4b3cca005, 0x0, 0xc0000d08b8)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0007c92f0, 0xc4b3cca000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x68
github.com/mholt/caddy/caddyhttp/httpserver.(*clientHelloConn).Read(0xc25a411080, 0xc4b3cca000, 0x400, 0x400, 0xfcbfa0, 0xc000590400, 0x7fda10dff000)
        /tmp/gopath_11-29-2055.350956452/src/github.com/mholt/caddy/caddyhttp/httpserver/mitm.go:176 +0x77f
crypto/tls.(*block).readFromUntil(0xc4b3cc8000, 0x7fda10dff000, 0xc25a411080, 0x5, 0xc25a411080, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:492 +0x89
crypto/tls.(*Conn).readRecord(0xc00027e380, 0x17aec17, 0xc00027e4a0, 0x7)
        /usr/local/go/src/crypto/tls/conn.go:593 +0xdd
crypto/tls.(*Conn).Read(0xc00027e380, 0xc4b3cea118, 0x9, 0x9, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1145 +0xf1
io.ReadAtLeast(0x7fda10dbf140, 0xc00027e380, 0xc4b3cea118, 0x9, 0x9, 0x9, 0xc0000d0f28, 0x2, 0x2)
        /usr/local/go/src/io/io.go:310 +0x88
io.ReadFull(0x7fda10dbf140, 0xc00027e380, 0xc4b3cea118, 0x9, 0x9, 0x0, 0x0, 0x28)
        /usr/local/go/src/io/io.go:329 +0x58
net/http.http2readFrameHeader(0xc4b3cea118, 0x9, 0x9, 0x7fda10dbf140, 0xc00027e380, 0x0, 0xc000000000, 0xc4b3e2e1e0, 0xc00047ab08)
        /usr/local/go/src/net/http/h2_bundle.go:1545 +0x7b
net/http.(*http2Framer).ReadFrame(0xc4b3cea0e0, 0xc0000d0ee0, 0x2, 0x0, 0x1)
        /usr/local/go/src/net/http/h2_bundle.go:1803 +0xa3
net/http.(*http2serverConn).readFrames(0xc000030540)
        /usr/local/go/src/net/http/h2_bundle.go:4487 +0xa4
created by net/http.(*http2serverConn).serve
        /usr/local/go/src/net/http/h2_bundle.go:4592 +0x30c

goroutine 1199 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2851 +0x2f5

goroutine 1213 [running]:
        goroutine running on other thread; stack unavailable
created by net/http.(*http2serverConn).processHeaders
        /usr/local/go/src/net/http/h2_bundle.go:5611 +0x4d3

**Comment by francislavoie** [comment]
This is likely an issue with the plugin rather than with Caddy itself. Could you ask in https://github.com/filebrowser/filebrowser instead?

I'll close this for now, but it can be reopened if you have more evidence that it's Caddy's fault.
