### ISSUE TITLE
gandiv5 plugin failed to build with

### ISSUE THREAD

**Issue by romcheck** [mholt/caddy#2385]
After last commits
https://github.com/mholt/caddy/commit/8f583dcf3694a55e32a1eb9ae4316c3f99d38c6f
https://github.com/mholt/caddy/commit/8f583dcf3694a55e32a1eb9ae4316c3f99d38c6f

I get this:

```../../../caddyserver/dnsproviders/gandiv5/gandiv5.go:26:10: undefined: gandiv5.NewDNSProviderCredentials```

**Comment by hijak** [comment]
im also having similar problems

**Comment by mholt** [comment]
All the DNS adapters need reworking; see https://github.com/caddyserver/dnsproviders/pull/46.
