### ISSUE TITLE
caddy community password reset is broken

### ISSUE THREAD

**Issue by rickb777** [mholt/caddy#2386]
Using the password reset function fails. The email is sent but it contains a broken link.

It looks like

https://forum.caddyserver.com/u/password-reset/.........

but it should be

https://caddy.community/u/password-reset/.........

**Comment by mholt** [comment]
Wait -- that's probably tied to the errors that people have reported when logging in via GitHub or Twitter: the OAuth callback URL is wrong, it appears to be `forum.caddyserver.com` so the server rejects it -- even though that's clearly not in any configuration anywhere in the admin dashboard.

How annoying. I'll try to find some time to look into it but I'm pretty busy right now :( Perhaps this could be reported to Discourse to help move things along.

**Comment by mholt** [comment]
I think it's fixed now... see https://meta.discourse.org/t/discourse-insists-on-using-domain-name-that-hasnt-existed-for-2-years/104022/2?u=mholt. Thanks for the report! Feel free to comment if it's still not fixed.
