### ISSUE TITLE
Caddy tries to get let's encrypt cert for self_signed

### ISSUE THREAD

**Issue by sergeyfrolov** [mholt/caddy#2387]
@mholt requested to test integration of Caddy and new [certmagic](https://github.com/mholt/certmagic) library, so, here goes testing of self signed mode. Modifying the issue template, since we are working with caddy directly from Go.

### 1. Versions of things
Caddy: `Caddy (untracked dev build) (unofficial)` - master 393bc2992e3852c05dec0de336b95d51dee20aff
Golang: go1.11.2
Test OS: Ubuntu 16.04

### 2. What are you trying to do?
Use self_signed tls certificates

### 3. Reproducer for multiple cases
```Golang
package main

import (
	"crypto/tls"
	"fmt"
	"net"
	"net/http"
	"net/http/httputil"

	"github.com/mholt/caddy"
	_ "github.com/mholt/caddy/caddyhttp"
)

func panicIfNotNil(e error) {
	if e != nil {
		panic(e)
	}
}

func main() {
	var addr string

	// "localhost" works
	addr = "localhost"

	// all of cases below should work, since cert is self_signed, but don't
	// issues also might be with other tls settings

	// error: tries to get let's encrypt cert
	// addr = "mycaddyserver"
	// addr = "caddyserver.com"

	// TLS handshake error from 127.0.0.1:56458: tls: no certificates configured
	// addr = "127.0.0.1"
	// addr = "127.255.255.1"

	// too many colons in address
	// addr = "::1"

	// "foo.localhost" shouldn't be different "localhost": https://tools.ietf.org/html/rfc6761 - section 6.1
        // this one is probably not a big deal though
	// error: tries to get let's encrypt cert
	// addr = "anything.localhost"

	fulladdr := "https://" + addr + ":12345"

	// spin up caddy Instance
	_, err := caddy.Start(caddy.CaddyfileInput{
		Contents:       []byte(fulladdr + " {\ntls self_signed\n}\n"),
		ServerTypeName: "http"})
	panicIfNotNil(err)

	// test that webserver with self-signed cert can serve something (404, if no root is set)
	cl := http.Client{Transport: &http.Transport{
		DialTLS: func(network, addr string) (net.Conn, error) {
			return tls.Dial(network, addr,
				&tls.Config{InsecureSkipVerify: true})
		},
	}}
	response, err := cl.Get(fulladdr)
	panicIfNotNil(err)

	respByte, err := httputil.DumpResponse(response, true)
	panicIfNotNil(err)
	fmt.Printf("Response was:\n%s", respByte)
}

```

### 4. What did you expect to see?
Caddy creates self_signed certificate and does not hang on a prompt for e-mail, while trying to get Let's Encrypt certificate.

### 5. What did you see instead (give full error messages and/or log)?

 * Caddy hangs on a prompt for e-mail, while trying to get Let's Encrypt certificate.

 * If "127.0.0.1" is used, Caddy throws error "tls: no certificates configured"

### 6. How can someone who is starting from scratch reproduce the bug as minimally as possible?

`go run file_included_above.go`

**Comment by mholt** [comment]
THIS is a fabulous bug report -- thank you! Made it very quick and easy to fix. And thank you for testing the latest changes!

Go ahead and give the new commit on master a try. I was able to reproduce the issue and this resolves it. A teeny bit of logic didn't make the transition correctly when we switched to CertMagic.
