### ISSUE TITLE
Add ssl offloading middleware

### ISSUE THREAD

**Issue by gabrielarrais** [mholt/caddy#24]

**Comment by mholt** [comment]
@gabrielarrais Do you have anything specific about SSL offloading you'd like to recommend/suggest? Like, are you suggesting that Caddy become an SSL offloader for other backend systems? That could perhaps be built into the proxy middleware...

**Comment by guilhermebr** [comment]
I think he want Caddy to work like nginx ssl directive...

(Example from: http://nginx.com/blog/nginx-ssl/)
And now you want to add HTTPS support, with NGINX decrypting the traffic using the certificate and private key and communicating with the backend servers over HTTP:

upstream backends {
   server 192.168.100.100:80;
   server 192.168.100.101:80;
}
server {
   listen              80;
   listen              443 ssl; # The ssl directive tells NGINX to decrypt 
                                # the traffic
   server_name         www.example.com;
   ssl_certificate     www.example.com.crt; # This is the certificate file
   ssl_certificate_key www.example.com.key; # This is the private key file
   location / {
       proxy_pass http://backends;
   }
}

**Comment by mholt** [comment]
I see. If that's the case, that could definitely be a good enhancement for the existing proxy middleware. I think. Someone is welcome to look into this since I may not get around to it for a while.

**Comment by guilhermebr** [comment]
Ok I can look at this =]

**Comment by guilhermebr** [comment]
@gabrielarrais You can try this caddyfile?
```
0.0.0.0 {
   tls web/server.crt web/server.key
   proxy / http://172.17.42.1:8080/
}
```
Using proxy + tls works for me, please try this and see if works for you =]
