### ISSUE TITLE
Http timeout setting can't be increased for fastcgi requests

### ISSUE THREAD

**Issue by tpetry** [mholt/caddy#2401]
### 1. What version of Caddy are you using (`caddy -version`)?
```
/var/www $ caddy -version
Caddy 0.11.1 (unofficial)
```
I am using the `abiosoft/caddy:builder` docker builder container.

### 2. What are you trying to do?
Increasing the timeouts for uploads and php requests.

### 3. What is your entire Caddyfile?
```text
:3333 {
    root /var/www
    tls off

    on startup php-fpm --nodaemonize
    fastcgi / 127.0.0.1:9000 php {
        fastcgi_connect_timeout 600s
        fastcgi_read_timeout 600s
        fastcgi_send_timeout 600s
    }
    rewrite {
        to {path} {path}/ /index.php?{query}
    }

    timeouts 600s
}
```
### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
caddy -conf /usr/local/etc/caddy/Caddyfile
```
It's running within a `php:7.2-fpm-alpine3.8` docker container.

### 5. Please paste any relevant HTTP request(s) here.
```
content-length: 20
content-type: text/plain; charset=utf-8
date: Thu, 20 Dec 2018 10:39:05 GMT
server: Caddy
status: 504
x-content-type-options: nosniff

504 Gateway Timeout
```

### 6. What did you expect to see?
My expectation is to increase the maximum duration of a request. Each request should be able to last up to 10 minutes.

### 7. What did you see instead (give full error messages and/or log)?
Each request will continue to end after 1 minute, no increase will be made. However, reducing the time to 30 seconds works.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Copy the `Caddyfile` and the following files in a folder:

* Dockerfile
```
# build caddy http server
FROM abiosoft/caddy:builder as caddy
ENV VERSION 0.11.1
RUN /bin/sh /usr/bin/builder.sh

# build php image with caddy http server
FROM php:7.2-fpm-alpine3.8
EXPOSE 8080
EXPOSE 8443

COPY --from=caddy /install/caddy /usr/local/bin/caddy

WORKDIR /var/www
COPY Caddyfile /usr/local/etc/caddy/Caddyfile
COPY index.php /var/www/index.php

RUN chown www-data:www-data /var/www
USER www-data:www-data
ENTRYPOINT ["caddy", "-conf", "/usr/local/etc/caddy/Caddyfile"]
```

* index.php
```php
<?php
declare(strict_types=1);

set_time_limit(0);
sleep($sleep = intval(@$_GET['sleep']));

echo "slept {$sleep}s and here is the response :)";
```
Then
*  run `docker build --tag caddy-timeout . && docker run --publish 3333:3333 caddy-timeout`
* open `http://localhost:3333/?sleep=5` to see everything is working correct
* open `http://localhost:3333/?sleep=90` to see that the timeout has not been increased

**Comment by abiosoft** [comment]
Your Caddyfile does not look accurate. The following
```
fastcgi_connect_timeout 600s
fastcgi_read_timeout 600s
fastcgi_send_timeout 600s
```
should be 
```
connect_timeout 600s
read_timeout 600s
send_timeout 600s
```

**Comment by tpetry** [comment]
You're right. Pasted configuration from nginx.
