### ISSUE TITLE
allow the {user} placeholder to be used in the rewrite module.

### ISSUE THREAD

**Issue by calisro** [mholt/caddy#2403]
In the current code, it looks like the basic auth module is positioned as to not be evaluated before rewrite.  This causes that placeholde to be unavailable.  Would it be possible to move basic auth before rewrite to allow the rewrite module to be able to use that placeholder.

https://github.com/mholt/caddy/blob/0684cf861170a112a041137b352322602543ccdf/caddyhttp/httpserver/plugin.go#L626-L639
```

xxxx:81 {
    proxy / localhost:7440 {
        max_fails 1
    }
    browse
    tls xxxx xxxx
    basicauth / calisro xxx
    basicauth / calisro2 xxx
    rewrite {
        if {user} not calisro
	to /method_not_allowed
    }
    status 405 /method_not_allowed
    log / stdout "{remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} - {rewrite_uri}"
    
```

Tests:

```
xxx@notebook2:~$ curl --head --user calisro:xxx https://xxxx:81/
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8
Server: Caddy
X-Content-Type-Options: nosniff
Date: Wed, 19 Dec 2018 19:34:05 GMT
Content-Length: 23

xxx@notebook2:~$ curl --head --user calisro2:xxx https://xxxx:81
HTTP/1.1 405 Method Not Allowed
Content-Type: text/plain; charset=utf-8
Server: Caddy
X-Content-Type-Options: nosniff
Date: Wed, 19 Dec 2018 19:34:14 GMT
Content-Length: 23

x.x.x.x - calisro [19/Dec/2018:14:34:05 -0500] "HEAD / HTTP/1.1" 405 23 - /method_not_allowed
x.x.x.x - calisro2 [19/Dec/2018:14:34:14 -0500] "HEAD / HTTP/1.1" 405 23 - /method_not_allowed

root@xxxx:/data/caddy# ./caddy --version
Caddy 0.11.1 (non-commercial use only)
```

forum reference 
https://caddy.community/t/user-placeholder-not-working-in-rewrite/4948

**Comment by calisro** [comment]
I complied my own with the basicauth moved before the rewrite module and it works great.  I'm unable to test if it broke anything else though. Is it possible to have this changed in the caddy source?

**Comment by mholt** [comment]
While we could do this, it would break anyone who expects basicauth to protect rewritten paths, as opposed to their original paths.

**Comment by calisro** [comment]
Hmm. If that's a ramifications of this change then that's a real concern too. That won't affect me but that surely will affect someone.

**Comment by calisro** [comment]
It sounds like I really should be writing a plug-in to handle this then rather than modifing the order of the existing ones.

**Comment by mholt** [comment]
Maybe. It could probably reuse components from Caddy's basicauth package and just have a different directive name. That should be pretty easy.

**Comment by calisro** [comment]
I'll close this for now as I don't think the enhancement could be implemented without breaking other functionality.
