### ISSUE TITLE
Passing arguments to snippets

### ISSUE THREAD

**Issue by eauchat** [mholt/caddy#2408]
As mentioned in #2042, it would really be great to be able to pass arguments to snippets.   
For example, in the following example, passing arguments like path, and port number would allow to simplify a lot the caddyfile, having snippets like the following:

```
(forwardToVmName) {
    proxy <variablePath> vmName:<variablePort> {
        transparent
        insecure_skip_verify
        ...
    }
}
```

**Comment by nicosmaris** [comment]
Such proposals where rejected in the past, so I assume we have to stop asking for a feature request and find another way to proceed.

What would a caddy developer or experienced user suggest? Making a plugin or preprocessing like [a template engine](http://jinja.pocoo.org/)?

**Comment by mholt** [comment]
I would recommend pre-processing, yes, like with a template engine.
