### ISSUE TITLE
CentOS 6 sysvinit/caddy start-stop-daemon: command not found

### ISSUE THREAD

**Issue by LsnmxNB** [mholt/caddy#2410]
https://github.com/mholt/caddy/blob/master/dist/init/linux-sysvinit/caddy

/etc/init.d/caddy: line 57: start-stop-daemon: command not found
/etc/init.d/caddy: line 52: start-stop-daemon: command not found

start() {
    $USERBIND $DAEMON
    touch $LOGFILE && chown $DAEMONUSER $LOGFILE
    start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
        --background --chuid $DAEMONUSER --oknodo --exec $DAEMON -- $DAEMONOPTS
}

stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE --retry=$STOP_SCHEDULE \
        --name $NAME --oknodo
    rm -f $PIDFILE
}

**Comment by magikstm** [comment]
`start-stop-daemon` is not available on CentOS.

On CentOS 6, you can use `service`.

On CentOS 7 you can use `systemd` (`systemctl`).

You would need to edit this script for CentOS 6. If it's a new server, I recommend installing CentOS 7 instead and to use this script https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd.

**Comment by magikstm** [comment]
I think this issue can be closed.
