### ISSUE TITLE
Service/middleware to support Hugo

### ISSUE THREAD

**Issue by hacdias** [mholt/caddy#242]
Hi everyone!

I've been thinking about creating something which fuses @spf13's [Hugo](https://github.com/spf13/hugo), Caddy and a really nice UI to manage the posts of a blog. This would allow a really simple workflow when creating/modifying new posts: new/change post → Hugo regeneration. Everything on a web browser.

I posted a tweet and @mholt answered:

> @hacdias @spf13 Yes. In fact, if you want to help build a hugo add-on for Caddy, that'd be awesome so you don't have to deploy two binaries

After a bit of searching I found out the [Extending Caddy](https://github.com/mholt/caddy/wiki/Extending-Caddy) page. I read about services and middleware. In this case, what should it be? Middleware maybe, it has to handle the ```/admin``` url and show the UI, save and regenerate. 

What do you think about the whole idea?

**Comment by mholt** [comment]
:+1: Solid. The user would just say `hugo` in their Caddyfile and be on their way. (Of course they could customize it further, but this would be the most basic usage.)

For reference, here are related discussions that @spf13 linked to on Twitter:

- [Hugo GUI?](http://discuss.gohugo.io/t/hugo-gui/1654)
- [Can Hugo play to a wider audience?](http://discuss.gohugo.io/t/can-hugo-play-to-a-wider-audience/575/6)
- [Web-Based Editor?](http://discuss.gohugo.io/t/web-based-editor/155)

I think Caddy could be an excellent way to ship Hugo and expand its reach to more people.

**Comment by hacdias** [comment]
I created a [repo](https://github.com/hacdias/caddy-hugo) to host the code. I'm going to learn more about middleware and ```net``` package. Then I'm going to start it. =D

**Comment by abiosoft** [comment]
I'm keeping an eye on this. ☺

**Comment by hacdias** [comment]
@abiosoft if you wanna help :+1: 

I have a simple question: how do I refer which file is the "404" error page in the middle ware without using Caddyfile? It must be simple, but I'm not getting how to do that. I've never used net/http before O.o

Right now, [caddy-hugo](https://github.com/hacdias/caddy-hugo/blob/master/hugo.go) generates the Hugo and serves its static files.

**Comment by abiosoft** [comment]
I think you should return a 404 and let caddy handle the error.

**Comment by hacdias** [comment]
@abiosoft It's happening something weird. I have this:

```
errors {
  404 404.html
}
```

On Caddyfile, but it still shows me the default message. Do you know what the problem might be?

Thanks, again =D

**Comment by abiosoft** [comment]
Does the 404.html file exists ?

**Comment by hacdias** [comment]
Yup

**Comment by abiosoft** [comment]
Mind sharing snippets ?

Or maybe we chat on slack and tackle this together.

**Comment by hacdias** [comment]
@abiosoft I'm on slack. When you're available...

**Comment by abiosoft** [comment]
Looks like we got the 404 issue resolved from our slack chat. :)

**Comment by hacdias** [comment]
Hi everyone!

Is there some way to include files like css and js into a binary and serve them through an URL? I saw about [go-bindata](https://github.com/jteeuwen/go-bindata). Is it that what I want?

**Comment by hacdias** [comment]
Or even https://github.com/rakyll/statik

**Comment by hacdias** [comment]
Using go-bindata. Fits perfectly.

**Comment by abiosoft** [comment]
Now that we've gotten here https://caddyserver.com/docs/cms, is it safe to close this issue ?

**Comment by mholt** [comment]
Yep!
