### ISSUE TITLE
Reverse proxy, if you hide the http header defined by the backend

### ISSUE THREAD

**Issue by f4nff** [mholt/caddy#2420]
```
https://ww.1qc.ws
{  

		tls ./tls/cert.pem ./tls/key.pem
        	proxy / http://98.43.133.10:80			{ 
                header_upstream Host w.1qc.ws
                header_upstream X-Real-IP {remote}
                header_upstream X-Forwarded-For {remote}
                header_upstream X-Forwarded-Proto {scheme}
			websocket
		
			}
	timeouts {
		read   30s
		header 30s
		write  30s
		idle   30s
	}
}
```

What should I do if I want to ignore the **Server** header returned by the proxy backend?

**Comment by abiosoft** [comment]
Firstly, always follow the issue template.
Secondly, read the docs https://caddyserver.com/docs/proxy
Finally, this type of question should be ask on the community https://caddy.community. It is *not* an issue.

Anyway, `header_upstream -Server` should do what you're asking.
