### ISSUE TITLE
502 error when proxy to https upstream

### ISSUE THREAD

**Issue by renothing** [mholt/caddy#2427]
os: Ubuntu16.04
Caddy:0.11
nginx:1.14.1

> Host A: 172.18.0.1,  caddy1(reverse proxy, as front)
> Host B: 172.18.0.2,  caddy2(backend with https, as backend)
> Host C: 172.18.0.3,  nginx(backend with https and without no default_server option, as backend)

caddy1:
```
www.domain1.com {
  proxy / https://172.18.0.2 {
    insecure_skip_verify
    transparent
  }
  header / -Server
  tls {
    dns cloudflare
  }
}
www.domain2.com {
  proxy / https://172.18.0.3 {
    insecure_skip_verify
    transparent
  }
  header / -Server
  tls {
    dns cloudflare
  }
}
```
caddy2:
```
www.domain1.com {
  root /var/www
  index index.html
  header / -Server
  tls {
    dns cloudflare
  }
}
```
nginx:
```
server {
 listen 80 ;
 listen [::]:80;
 server_name www.domain2.com;
 root   /var/www;
 #ssl
 listen 443;
 listen [::]:443;
  .....
}

```
**results:**

visit `https://www.domain1.com` from caddy1, it will retrun error 502 Bad Gateway
visit `https://www.domain1.com` from caddy2. it works fine and return 200
visit `https://www.domain2.com` from caddy1 or nginx, it works fine and return 200

now, If I change caddy1:
and add host record to caddy1 hosts file
```
echo "172.18.0.2 www.domain1.com" > /etc/hosts
```
and change caddy1 Caddyfile to
```
www.domain1.com {
  proxy / https://www.domain1.com {
    insecure_skip_verify
    transparent
  }
  header / -Server
  tls {
    dns cloudflare
  }
}
www.domain2.com {
  proxy / https://172.18.0.3 {
    insecure_skip_verify
    transparent
  }
  header / -Server
  tls {
    dns cloudflare
  }
}
```
**results:**

visit `https://www.domain1.com` from caddy1 or caddy2 , it works fine and return 200
visit `https://www.domain2.com` from caddy1 or nginx, it works fine and return 200

**Comment by francislavoie** [comment]
Your example doesn't really make sense, because if your domain is `www.domain.com` and you proxy to `www,domain.com`, that'll just be a loop.

This doesn't seem like an issue or bug with Caddy, but simply a usage/configuration question. Please ask on https://caddy.community instead. If it turns out to be a bug and you can provide more info, we could reopen this.

**Comment by renothing** [comment]
> Your example doesn't really make sense, because if your domain is `www.domain.com` and you proxy to `www,domain.com`, that'll just be a loop.
> 
> This doesn't seem like an issue or bug with Caddy, but simply a usage/configuration question. Please ask on https://caddy.community instead. If it turns out to be a bug and you can provide more info, we could reopen this.

it's not a loop.
I post details here:
https://caddy.community/t/502-error-when-proxy-to-caddy-https-upstream/5089

**Comment by mholt** [comment]
@renothing Please try again with the latest master of Caddy. If I don't hear about any problems with the fix soon, I'll do a new release.

**Comment by renothing** [comment]
the problem still exists

Caddy 0.11.2 (+a7aeb97 Wed Jan 23 05:38:58 UTC 2019) (unofficial)
1 file changed, 14 insertions(+), 1 deletion(-)
caddy/caddymain/run.go

**Comment by mholt** [comment]
@renothing Hmm - what is the backend Caddy's full, unredacted Caddyfile?

**Comment by renothing** [comment]
> @renothing Hmm - what is the backend Caddy's full, unredacted Caddyfile?

there is only one site in caddy backend, full Caddyfile content:
```
www.domain1.com {
  log stdout "{proto} Request: {method} {path}"
  root /var/www
  tls {
    dns cloudflare
  }
}
```

**Comment by mholt** [comment]
Thanks. The first error happens I think because you need to specify https for the proxy, otherwise it defaults to http.

The second error is not well worded, but I think it happens because your backend Caddy is not configured to serve 172.18.0.31, only www.domain1.com, (which is redacted, tsk tsk, this has slowed debugging before, please don't do this!) -- you have to configure the backend to serve that IP address, otherwise it won't know which certificate or even which tls config to use.

So far, this is working as expected now.

**Comment by renothing** [comment]
> Thanks. The first error happens I think because you need to specify https for the proxy, otherwise it defaults to http.
> 
> The second error is not well worded, but I think it happens because your backend Caddy is not configured to serve 172.18.0.31, only [www.domain1.com](http://www.domain1.com), (which is redacted, tsk tsk, this has slowed debugging before, please don't do this!) -- you have to configure the backend to serve that IP address, otherwise it won't know which certificate or even which tls config to use.
> 
> So far, this is working as expected now.
it's strange that the backend caddy didn't recieve correct hostname, but if I change the backend to nginx, it will works fine.

**Comment by mholt** [comment]
> it's strange that the backend caddy didn't recieve correct hostname, but if I change the backend to nginx, it will works fine.

Nginx uses different logic to select a certificate in the case of a mismatch.

If the client sends SNI, Caddy honors that. What would you expect to have happen?

**Comment by renothing** [comment]
I tried with bind option in caddy backend
```
* :443 www.domain1.com {
  bind 0.0.0.0
  log stdout "{proto} Request: {method} {path}"
  root /var/www
  tls {
    dns cloudflare
  }
}
```
it still doesn't work.
```
2019/01/23 19:41:55 http: TLS handshake error from 172.18.0.31:35444: no certificate available for 172.18.0.12
```

in my scenes, I use [caddy-docker-proxy](https://github.com/lucaslorentz/caddy-docker-proxy) as dynamic reverse proxy in front. and also backend running caddy in docker container too. it's hard to serve ip address in backend caddy.

**Comment by mholt** [comment]
Not bind, I meant you need to serve your IP address:

```
172.18.0.12 {
  log stdout "{proto} Request: {method} {path}"
  root /var/www
  tls {
    dns cloudflare  # this won't work with IP address
  }
}
```

**Comment by a93h** [comment]
@mholt Sorry to bother you, although, could this still be an issue?

**Comment by francislavoie** [comment]
Unlikely @a93h. Please open a topic on https://caddy.community if you need help.
