### ISSUE TITLE
fedora 29 systemd unit

### ISSUE THREAD

**Issue by anothergituser** [mholt/caddy#2440]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.1 (unofficial) fedora 29 repos

### 2. What are you trying to do?
start caddy as another user than default user which is caddy

### 3. What is your entire Caddyfile?
```text
:80 {
    gzip
    root /usr/share/caddy
}

import conf.d/*.conf
```
this is the default config just after installing and conf.d folder is empty

### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemctl enable caddy.service 
systemctl start caddy.service

### 6. What did you expect to see?
For the service to start just like when using default caddy user

### 7. What did you see instead (give full error messages and/or log)?
Jan 23 19:02:14 box systemd[1]: Starting Caddy HTTP/2 web server...
Jan 23 19:02:14 box systemd[12555]: caddy.service: Failed to execute command: Resource temporarily unavailable
Jan 23 19:02:14 box systemd[12555]: caddy.service: Failed at step EXEC spawning /usr/bin/caddy: Resource temporarily unavailable
Jan 23 19:02:14 box systemd[1]: caddy.service: Control process exited, code=exited status=203
Jan 23 19:02:14 box systemd[1]: caddy.service: Failed with result 'exit-code'.
Jan 23 19:02:14 box systemd[1]: Failed to start Caddy HTTP/2 web server.

### 8. How can someone who is starting from scratch reproduce the bug as minimally as possible?
Fresh fedora 29 install,
dnf install caddy
change user and group in /usr/lib/systemd/system/caddy.service to currently logged in user and try to start the service.

I don't think it's a bug with caddy because ExecStartPre and ExecStart commands run without errors directly in terminal but not in the unit file so it has to be something with fedora..

**Comment by Snailya** [comment]
i got the save issue, 
how did you fix it?

**Comment by anothergituser** [comment]
I had these lines commented out in caddy.service
btw this should be done only for a dev server not prod.
#TimeoutStopSec=5s
#LimitNOFILE=1048576
#LimitNPROC=512
#PrivateTmp=true
#ProtectHome=true
#ProtectSystem=full

**Comment by Dummyc0m** [comment]
If anyone is getting Permission Denied, perhaps try 
sudo restorecon -v /usr/local/bin/caddy

I don't really understand selinux, but this should reset the selinux context for the executable

**Comment by mholt** [comment]
FYI we now have an officially-maintained service file in this repo, and a COPR in progress: https://github.com/caddyserver/dist

**Comment by zjx20** [comment]
> If anyone is getting Permission Denied, perhaps try sudo restorecon -v /usr/local/bin/caddy
> 
> I don't really understand selinux, but this should reset the selinux context for the executable

this is the only working solution for me, thanks @Dummyc0m !
