### ISSUE TITLE
caddy panic in v0.11.2 with quic enable

### ISSUE THREAD

**Issue by kordenlu** [mholt/caddy#2445]
# reason
quic-go in caddy's vendor path is different from quic-go v0.10.1. 

# traceinfo
goroutine 3872 [running]:
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/h2quic.(*Server).handleHeaderStream(0xc0001e2720, 0x7f927bf3ca00, 0xc00065a000)
        /Users/matt/Dev/src/github.com/caddyserver/releaser/cmd/release-caddy/gopath_01-16-1610.520542660/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/h2quic/server.go:145 +0x1cb
created by github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/h2quic.(*Server).serveImpl
        /Users/matt/Dev/src/github.com/caddyserver/releaser/cmd/release-caddy/gopath_01-16-1610.520542660/src/github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/h2quic/server.go:123 +0x177

**Comment by marten-seemann** [comment]
Could you please post the complete trace?

**Comment by kordenlu** [comment]
@marten-seemann this is the complete trace.
the bug has been fixed in  this commit:
https://github.com/lucas-clemente/quic-go/commit/9252e12da53b7eae17b504ed23146f563c59f496
and packed in quic-go v0.10.0
but it seems quic-go in caddy-v0.11.2 is not the version v0.10.0 as the release notes described.

**Comment by marten-seemann** [comment]
The vendored version of quic-go is from https://github.com/lucas-clemente/quic-go/tree/f90751eabaa39364e3861ee5a8b179f140847d7e, which is before that commit happened.
