### ISSUE TITLE
header_upstream Host {host} does not work

### ISSUE THREAD

**Issue by ZTzha** [mholt/caddy#2449]
### 1. What version of Caddy are you using (`caddy -version`)?
Caddy 0.11.2

### 2. What are you trying to do?

caddy-proxy->nginx

### 3. What is your entire Caddyfile?
first i try:
https://www.zha.com {
	gzip
	log /usr/local/caddy/log/caddy.log
	proxy / https://x.x.x.x {
	header_upstream Host www.zha.com
       	 header_upstream X-Real-IP {remote}
       	 header_upstream X-Forwarded-For {remote}
       	 header_upstream X-Forwarded-Proto {scheme}
	}
	tls /usr/local/caddy/cert/tpf-zha.com/server.crt /usr/local/caddy/cert/tpf-zha.com/server.key {
        protocols tls1.0 tls1.2
}
}
it does not work , i can not open my website 

second i try:
https://www.zha.com {
	gzip
	log /usr/local/caddy/log/caddy.log
	proxy / https://x.x.x.x {
	transparent
	}
	tls /usr/local/caddy/cert/tpf-zha.com/server.crt /usr/local/caddy/cert/tpf-zha.com/server.key {
        protocols tls1.0 tls1.2
}
}
it does not work, too...

last i try:
https://www.zha.com {
	gzip
	log /usr/local/caddy/log/caddy.log
	proxy / https://x.x.x.x {
         header_upstream Host www.zha.com
       	 header_upstream X-Real-IP {remote}
       	 header_upstream X-Forwarded-For {remote}
       	 header_upstream X-Forwarded-Proto {scheme}
	insecure_skip_verify 
	}
	tls /usr/local/caddy/cert/tpf-zha.com/server.crt /usr/local/caddy/cert/tpf-zha.com/server.key {
        protocols tls1.0 tls1.2
}
}

It is work, I can open my website, but it is not what my want...

### 4. How did you run Caddy (give the full command and describe the execution environment)?

/usr/local/caddy/caddy -quic

### 5. Please paste any relevant HTTP request(s) here.
open www.zha.com with my chrome

**Comment by tobya** [comment]
Please provide full domain names or additional details such as what kind of cert your upstream host has.

**Comment by ZTzha** [comment]
my domain : www.iyong.com
my cert infomation:
Subject *.iyong.com
SAN *.iyong.com iyong.com
Valid from Wed, 09 May 2018 00:00:00 GMT
Valid until Tue, 07 Jul 2020 12:00:00 GMT
Issuer RapidSSL RSA CA 2018
