### ISSUE TITLE
About rewrite with proxy

### ISSUE THREAD

**Issue by gsxhnd** [mholt/caddy#2457]
I'm trying to host a vue app with Caddy

When I add config, proxy will not work.

Here is my caddy config:
```
example.com {
    root /root/html
    gzip
    proxy /api localhost:8077/api
    rewrite {
        regexp .*
        to {path} /
    }
}
```

And then I try [ Caddy rewrite with proxy](https://stackoverflow.com/questions/51831006/caddy-rewrite-with-proxy) It also not work.

I have really no idea about that.

**Comment by francislavoie** [comment]
Please instead ask on the forums: https://caddy.community/

This is the bugs/issues board, this seems most likely like a configuration issue.
