### ISSUE TITLE
Can't download Caddy

### ISSUE THREAD

**Issue by STaRDoGG** [mholt/caddy#2467]
When I try I get this:

![image](https://user-images.githubusercontent.com/1524526/52735311-f0007700-2f8c-11e9-8bc3-3b6392f284b1.png)

Using this:

`https://caddyserver.com/download/windows/amd64?plugins=dns,docker,hook.service,http.authz,http.cache,http.cgi,http.cors,http.expires,http.filebrowser,http.filter,http.forwardproxy,http.geoip,http.git,http.gopkg,http.grpc,http.ipfilter,http.jwt,http.locale,http.login,http.mailout,http.minify,http.nobots,http.prometheus,http.proxyprotocol,http.ratelimit,http.realip,http.reauth,http.supervisor,http.upload,http.webdav,net,supervisor,tls.dns.cloudflare&license=personal&telemetry=off`

The error dialog doesn't say which plugin(s) is potentially the issue, so I'm not sure if it's one that I "need" or not. As a dev I do tend to use a lot of plugins, whether for testing, or experimenting. I'd _prefer_ not to manually test downloading after checking/unchecking each plugin 1 by 1, lol. Any way to know exactly which one it is?

**Comment by whalehub** [comment]
Try unchecking the file browser plug-in. I believe that one is currently causing problems.

**Comment by whalehub** [comment]
Try unchecking the file browser plug-in. I believe that that one is currently causing problems.

**Comment by mholt** [comment]
Do you actually use all those? 🤔 

I believe the `dns` plugin is not currently compatible with the build server. If you have troubles downloading Caddy with plugins, uncheck the plugins so you only select the ones you need, because it's likely that one of them is currently broken in that case.

**Comment by STaRDoGG** [comment]
Nope, not the dns or filebrowser plugins, I removed them from the URL and still got ...

> building caddy: exit status 2

Isn't there 'a better way?' Maybe have build errors send a notification to you @mholt so you can remove or disable them (temporarily) from the list of plugins, so the download will always succeed for the end user; or put a specific mention in the error of the failing plugin(s) so we can specifically uncheck it/them?

This is kind of  putting the burden more on the end users, to figure out which one is preventing them from downloading your software. imho the end user should always be able to successfully download my software without my having them do detective work and workarounds on their own.

**Comment by STaRDoGG** [comment]
Just a status update; I managed to download the latest version, (you were correct @mholt , it was the dns plugin), but I don't know if the server first checks for a non-expired session or what, because I compared the working URL you can copy at the bottom with the one I had saved (removing the dns plugin as well from the old link) and they are identical.

The only difference is that if I didn't go to the actual caddy dl page first, and just try pasting the link into the browser to directly download it, it'll give an 'error 2'. *shrug*

**Comment by STaRDoGG** [comment]
Another status update: think I was wrong about my last update, unless it's just another new issue from the latest version. Unchecking the DNS plugin doesn't allow me to download Caddy (anymore).
