### ISSUE TITLE
Impossible to implement certmagic.Storage interface while vendored

### ISSUE THREAD

**Issue by BTBurke** [mholt/caddy#2471]
## 1. Which version of Caddy are you using (`caddy -version`)?

Building from source on 396d8e989ffdca4bb5aac2d01d5f4f48c44a6291

## 2. What are you trying to do?

I'm working on a Cluster plugin for etcd at [caddy-etcd](https://github.com/BTBurke/caddy-etcd).  I can't build it with a vendored dependence on certmagic.  It's impossible to implement the `certmagic.Storage` interface because caddy main is referencing the vendored version which I cannot import.  This is likely related to #1697. 

## 3. What is your Caddyfile?
```text
paste entire Caddyfile here - DO NOT REDACT ANYTHING (except credentials)
```
N/A

## 4. How did you run Caddy (give the full command and describe the execution environment)?

1. Add plugin import to run.go
2. Add to httpserver/plugin.go
3. Attempt to build
4. Throws `/cluster.go:16:33: cannot use NewCluster (type func() ("github.com/mholt/certmagic".Storage, error)) as type caddytls.ClusterPluginConstructor in argument to caddytls.RegisterClusterPlugin`
5. Delete vendored dependencies
6. Run `go get -u`
7. Build is successful when there is no vendored certmagic dependency

## 5. Please paste any relevant HTTP request(s) here.

N/A

## 6. What did you expect to see?

Successful build

## 7. What did you see instead (give full error messages and/or log)?

`/cluster.go:16:33: cannot use NewCluster (type func() ("github.com/mholt/certmagic".Storage, error)) as type caddytls.ClusterPluginConstructor in argument to caddytls.RegisterClusterPlugin`

## 8. Why is this a bug, and how do you think this should be fixed?

It's impossible for anyone to write a ClusterPlugin.  My etcd plugin works fine when I build without vendored dependencies.  I can do that for myself, but no one will be able to use it from the caddy buildserver.

## 9. What are you doing to work around the problem in the meantime?

There are a couple of possible fixes:

1. Re-export the certmagic.Storage interface in the caddytls package.  This doesn't work because the definition of the interface still references `certmagic.KeyInfo` which  if you re-export the KeyInfo in caddytls doesn't work.  It will always point at the vendored dependency.

2. Declare a new `caddytls.Storage` interface with a `caddytls.KeyInfo` with associated type aliases to the certmagic package.  That might work? I haven't tried it. (edit: thought of another option - change the certmagic.Storage interface to only return other interfaces instead of concrete types.  In other words, `Stat` should return an interface rather than a concrete type `KeyInfo`.  You could then re-export both interfaces in caddytls and it would probably work.)

3. Throw out vendoring and move to modules.  I was able to build caddy with modules but it requires at least one other package (quic-go) to move to modules or vendor that one dependency and do a mod replace.  It's complicated and might break a lot of other plugins. 

## 10. Please link to any related issues, pull requests, and/or discussion.

#1697 

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Using it for a side project and having etcd clustering is the first step towards the possibility of using it more easily with kubernetes as an ingress controller.  Right now I have it running under kubernetes as a proxy to my istio ingress controllers.

**Comment by mholt** [comment]
Honestly I'm leaning toward option 3 -- getting rid of the `vendor` folder and moving to modules -- to fix this and several other issues.

Unfortunately I won't be ready to do that today or tomorrow or next week, but it'll happen, hopefully right after the Go 1.12 release I'll get around to it. It'll require updating our build server, too, which is the main reason I can't do it right now...

**Comment by 42wim** [comment]
No need to throw out vendor :-)
This works fine using vendor folder generated by go modules (using go1.11.5, no GOPATH set!)

```
$ git clone https://github.com/mholt/caddy
$ cd caddy
$ go mod init
$ vim caddy/caddymain/run.go # add _ "github.com/BTBurke/caddy-etcd" to run.go
$ go get github.com/bifurcation/mint@v0.0.0-20180715133206-93c51c6ce115
$ go mod vendor
$ go build -mod vendor
```
The bifurcation is needed because of https://github.com/lucas-clemente/quic-go/issues/1788 (regardless of building with vendor or modules)

**Comment by mholt** [comment]
@42wim Awesome! Thanks for looking into that. That should buy us some time then. :)

**Comment by BTBurke** [comment]
Thanks @42wim.  That's one thing I didn't try.  I'll give it a shot and see if it works for me.  I guess that still doesn't solve the issue of publishing it as a public plugin, but I'll hold off on that until the build server works with modules.

**Comment by mholt** [comment]
(We no longer use vendor, so, closing.)
