### ISSUE TITLE
nginx -s reload ?

### ISSUE THREAD

**Issue by f4nff** [mholt/caddy#2478]
Does caddy have a command like `nginx -s reload`?

**Comment by francislavoie** [comment]
Yup! Send the USR1 signal to Caddy, e.g. `kill -USR1 $caddypid`. See here: https://caddyserver.com/docs/cli#usr1

FYI, this is the issues/bugs board, please ask questions on https://caddy.community next time.

**Comment by linquize** [comment]
What about Windows? There is no signal in Windows.

**Comment by tobya** [comment]
Its not possible in windows. At the moment you need to kill the process and startup again.  This can be done with a simple script
