### ISSUE TITLE
A way to print the environment

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#2479]
## 1. What would you like to have changed?

Print the environment

`caddy -env` could be all that is needed. Just loop through `os.Environ()` and print it out.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

A lot of times the environment is not set how people think because of complexities running in containers or with systemd.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Currently recompiling to print debug info manually

**Comment by jimen0** [comment]
Hi.

I'd love to start contributing to Caddy and I think this one could be a perfect first contribution. Could you please ellaborate a bit more what do you want it to do?

My guess is that you want a new flag to print the current `os.Environ()` values, am I right? But as far as I see, current master already has an `-env` flag defined [here](https://github.com/mholt/caddy/blob/397d67876cb3063138754250a1e4a01881e60ec2/caddy/caddymain/run.go#L56). My idea is to add a new flag (`-print-env`, `-printenv`, `-show-env`, please, let me know which one you think fits better) that prints the `os.Environ()` values right after loading the environment from file [here](https://github.com/mholt/caddy/blob/397d67876cb3063138754250a1e4a01881e60ec2/caddy/caddymain/run.go#L119).

Also, how would you like me to show the results? One on each line `VARIABLE=VALUE`? In that case, PR would add this code + the new flag.

```go
for _, v := range os.Environ() {
	fmt.Printf("%s\n", v)
}
```

Kind regards

**Comment by mholt** [comment]
> But as far as I see, current master already has an -env flag defined here.

Dang, you're right. I think it'd be better to rename that flag to `-envfile` in the long run, so let's go ahead and do that.

And yes, your proposed output will probably be sufficient! At least for an initial PR.
