### ISSUE TITLE
 disable verification of the proxied HTTPS server certificate in caddy ？

### ISSUE THREAD

**Issue by f4nff** [mholt/caddy#2480]
nginx config：

```
Specifies a file with trusted CA certificates in the PEM format used to verify the certificate of the proxied HTTPS server.
Syntax: | proxy_ssl_verify on \| off;
-- | --
proxy_ssl_verify off;
http, server, location

Enables or disables verification of the proxied HTTPS server certificate.
Syntax: | proxy_ssl_verify on \| off;
-- | --
proxy_ssl_verify off;
http, server, location
```

I want to know how to disable verification of the proxied HTTPS server certificate in caddy？

**Comment by f4nff** [comment]
我还想知道，如何 设置 proxy_ssl_name ？

nginx config：

```
upstream serlist {
server 104.16.70.234:443;
server 104.16.72.234:443;
server 104.16.69.234:443;
server 104.16.71.234:443;
server 104.16.68.234:443;
}

server {
listen 80;

location /{
proxy_pass	https://serlist;
proxy_set_header	Host “www.cloudflare.com”;
proxy_ssl_session_reuse on;
proxy_ssl_protocols	TLSv1.2;
proxy_ssl_verify	off;
proxy_send_timeout	60s;
proxy_ssl_server_name	on;
proxy_ssl_name	“www.cloudflare.com”;	
proxy_redirect	off;
proxy_set_header	X-Real-IP $remote_addr;
proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_http_version	1.1;
proxy_set_header	Upgrade $http_upgrade;
proxy_set_header	Connection “upgrade”;
}
}
```

**Comment by francislavoie** [comment]
As mentioned on the previous issue, please ask your questions on https://caddy.community. This is the issues/bugs board. What you're asking isn't a feature request. You're just asking a question about how to use the webserver.

To turn off verification, you need to use `insecure_skip_verify`. See here: https://caddyserver.com/docs/proxy

There's no direct equivalent to `proxy_ssl_name`, but I think in this case you'll probably want to use the `ca_certificates` option on `proxy` to verify cloudflare's CA certificates. You can probably get more help on this topic in the forums.
