### ISSUE TITLE
Support multiple accounts for single DNS provider

### ISSUE THREAD

**Issue by NEXUS2345** [mholt/caddy#2484]
I have done quite a bit of searching for this and can't seem to find a solution.

## 1. What would you like to have changed?
Add the ability to specify the credentials for a DNS provider per domain in the Caddyfile.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
In environments such as commercial web hosting, it is sometimes necessary to support multiple sets of credentials for when you have multiple customers using the same reverse proxy. Adding support for this makes it significantly easier in terms of configuration complexity and improves the overall usability of the server.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?
The workaround in the meantime is to use multiple instances of Certbot to fetch the certificates and manually specify in the Caddyfile where these certificates are.

## 4. Please link to any relevant issues, pull requests, or other discussions.
https://caddy.community/t/multiple-domains-with-cloudflare-challenge-on-different-accounts/4299

**Comment by mholt** [comment]
This is implemented in Caddy 2.
