### ISSUE TITLE
Build fails on previous versions of Go

### ISSUE THREAD

**Issue by erbesharat** [mholt/caddy#2486]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy (untracked dev build) (unofficial)
72d0debde6bf01b5fdce0a4f3dc2b35cba28241a

## 2. What are you trying to do?

The latest changes on 72d0debde6bf01b5fdce0a4f3dc2b35cba28241a will break the builds that use previous versions of Go. (only works on 1.12)
These changes caused our tests to fail too. For more information you can check: https://travis-ci.org/txtdirect/txtdirect/jobs/498581871

## 3. What is your Caddyfile?
```text
example.test:8080, tor.example.test:8080, pkg.example.test:8080, host.example.test:8080, gomods.example.test:8080, gometa.example.test:8080 {
    tls off
    txtdirect {
        enable path host tor gometa gomods dockerv2 proxy
        resolver 127.0.0.1:5353
				logfile stdout
				redirect 192.168.1.3
        prometheus {
            address localhost:6985
        }
        gomods {
            cache
        }
    }
    log / stdout "{remote} - [{when_iso}] \"{method} {uri} {proto}\" {status} {size} {latency}"
    errors stdout
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

I used our custom build that injects our plugin to caddy. (Don't think its needed but can post the build process too)

## 6. What did you expect to see?

Not fail and work fine on previous versions

## 7. What did you see instead (give full error messages and/or log)?

Fails on previous Go versions.

## 8. Why is this a bug, and how do you think this should be fixed?

It's bug because it causes builds on previous versions to fail. Not sure how you can handle this and fix it.

## 9. What are you doing to work around the problem in the meantime?

Using previous versions of caddy

## 10. Please link to any related issues, pull requests, and/or discussion.

#2399, 72d0debde6bf01b5fdce0a4f3dc2b35cba28241a

**Comment by markustenghamn** [comment]
I guess I am upgrading to go 1.12. 

What is recommended if we do not want to upgrade, should we simply build the latest release from source? Is there an easy way to specify a version number when building from source?

**Comment by abiosoft** [comment]
Go 1.12 is now a requirement to build Caddy. https://github.com/mholt/caddy/issues/2080#issuecomment-467257488.

To use an older version of Go, you would have to stick with an older version of Caddy as well.

**Comment by abiosoft** [comment]
> I guess I am upgrading to go 1.12.
> 
> What is recommended if we do not want to upgrade, should we simply build the latest release from source? Is there an easy way to specify a version number when building from source?

If you download at caddyserver.com/download, you'd get the latest release. 
When building from source, you can always checkout a specific revision or release.
