### ISSUE TITLE
Stable versions go1.12+++TLS 1.3

### ISSUE THREAD

**Issue by LsnmxNB** [mholt/caddy#2487]
Go 1.12在RFC 8446crypto/tls规定的包中添加了对TLS 1.3的选择支持。可以通过将值添加到 环境变量来启用它。它将在Go 1.13中默认启用。

**Comment by whitestrake** [comment]
This was merged into master yesterday: https://github.com/mholt/caddy/pull/2399

You should be able to build from source now, or wait for the next release version.
