### ISSUE TITLE
middleware for API-based uploads

### ISSUE THREAD

**Issue by wmark** [mholt/caddy#249]
This is a heads-up as requested on the wiki page "extending Caddy". I am writing a plugin that supports this use-case:

I'd like to be able to upload files:
```text
# Caddyfile
upload [basepath] {
  to <path>
}
```

```bash
curl \
  -F password=@/etc/passwd \
  -F "file=@/etc/groups;filename=groups.txt" \
  https://caddyserver.com/drop-files-here
```

… aspirational: support for HMACs, option to delete files.

This will enable me to upload build artefacts from CI directly to the server. The path specified by "to" might be ```/tmp``` itself, and might not be used as "root" in *Caddy*. Although in my case another tool will pick up the upload, this could very well be something in a path immediately served by *Caddy* (think: a *html file* or the like).

**Comment by mholt** [comment]
Cool idea. Just thinking ahead: is "upload" the best directive to use if you may later implement the ability to delete files too?

**Comment by wmark** [comment]
You're right, ```DELETE /drop-files-here/passwd``` sounds strange. But those will be past 'uploads', so I think it's okay. I am open to suggestions, though.

There's another use-case which this "middleware" (number one) will enable: Subscribing to file changes, and pulling of changed files. For example, I (1) upload ```curl``` to ```/static/```, (2) publish *pubsubhub* notifications, (3) which get consumed by mirrors running *Caddy* to the effect of them filling their ```/static/``` locations.

**Comment by hacdias** [comment]
Woa, I haven't seen this yet. It appears to be a good plugin to use with my [hugo](github.com/hacdias/caddy-hugo) plugin. I'll keep an eye on this thread.

**Comment by wmark** [comment]
You're welcome. I need this for the aforementioned use-cases, therefore it won't be the upload facility you might expect.

1. HMAC scheme for auth, of course. → You don't want to publish your secret API key.
2. Files must appear atomically in the FS and uploads must cause the absolute minimum notification events. → O_TMPFILE will be used (¬Windows∧¬*gappengine*, not supported by every FS and Linux≤3.11)
3. Large uploads (think: backups, ISOs) should not be stored in memory but streamed to disc, and I'd like to be prepared for the time Go implements zero-copy. → Expand file contents to MMAP'ed files (looking into this for Windows *atm*), not sure if this will work without *insecure* and thus for *gappengine*.
4. No conflict prevention whatsoever.

Though *file upload* progress monitoring is on my list (see Nginx' *upload progress*) as well as [tus](http://www.tus.io/protocols/resumable-upload.html).

**Comment by hacdias** [comment]
I see. So I'll wait for the first release to see how it works. :+1:

**Comment by wmark** [comment]
```O_TMPFILE``` is in. The first iteration should be ready soon.

https://hub.blitznote.com/src/caddy.upload/blob/37cfc0f27cd7c4084ff35f71c09be26b7a0cce89/filewriter_unix.go

**Comment by wmark** [comment]
… and file locking is in, which is a prerequisite to *file streaming*, using scatter/gather facilities of modern NICs, and *mmap'ing* files in a safe manner in general.

https://hub.blitznote.com/src/caddy.upload/blob/e54aa6b9d93bae899fa38e9bd2ae4c95b38f773f/protofile/file2_unix.go

**Comment by wmark** [comment]
*mmap*'ing is in for Unix. I've upgraded the machines I am testing programs on to 10GbE and am about to experiment with thresholds to decrease the total amount of context switches for most users and most workloads. The *thresholds* are like »don't lock if size_file ≤ X; don't mmap if…; mmap total file if smaller than Y or else chunks of Z MB«.

- [x] file »appears« with contents, not before (good for *inotify*)
- [x] use file locking
- [x] mmap ← file streams
- [ ] thresholds for usage scenarios
- [ ] write unit tests (it's currently integration tests)
- [ ] auth using a HMAC scheme
- [ ] pretty documentation

Postponed to a later version:
- [x] mmap for Windows
- [ ] encrypt before writing, wipe memory after writing
- [ ] don't encrypt if TLS is used, just intercept the current key and data stream

**Comment by severak** [comment]
Great idea. I once thinked about creating S3-compatible middleware for uploads, but I postponed it cause I am not good in compiled languages/

**Comment by wmark** [comment]
Programming for S3 (S3, OpenStack, SIS…) middleware-based filesystems (or ZFS, WORM, as well as some more exotic ones) is quite tricky, because they don't support POSIX features which you might expect from like *ext4*, *xfs* or even *NTFS*. Which makes unit-testing almost pointless, and testing itself a challenge.

**Comment by severak** [comment]
I think your solution is enough for most uses. S3 is overkill.

@wmark : seems blitznote.com is down

**Comment by mholt** [comment]
Been fun to follow the progress on this. Will close the issue now unless there's anything else we need to attend to.

**Comment by wmark** [comment]
Mirrored to https://github.com/wmark/caddy.upload

I am currently wondering
 * if the global uploads location is the way to go
 * how I can persist goroutines between Caddy's restarts (for holding and expiring locks)

**Comment by mholt** [comment]
Unfortunately, there's not a way right now to persist your own state between Caddy restarts -- however, I'm working on this. Quite the design challenge...
