### ISSUE TITLE
443 Permission Denied

### ISSUE THREAD

**Issue by fuzunspm** [mholt/caddy#2491]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy 0.11.4 (non-commercial use only)

## 2. What are you trying to do?
Running behind a Caddy Reverse Proxy with Free SSL

## 3. What is your Caddyfile?
```
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target
[Service]
Restart=on-failure
StartLimitInterval=86400
StartLimitBurst=5000
User=www-data
Group=www-data
; Letsencrypt-issued certificates will be written to here in this directory
Environment=CADDYPATH=/etc/ssl/caddy
ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp
ExecReload=/bin/kill -USR1 $MAINPID
LimitNOFILE=1048576
LimitNPROC=64
PrivateTmp=true
PrivateDevices=true
ProtectHome=true
ProtectSystem=full
ReadWriteDirectories=/etc/ssl/caddy
; The following additional security directives only work with systemd v229 or later.
; They further restrict privileges that can be gained by caddy. Uncomment if you want.
; You may need to add capabilities required by the plugins in use.
;CapabilityBoundingSet=CAP_NET_BIND_SERVICE
;AmbientCapabilities=CAP_NET_BIND_SERVICE
;NoNewPrivileges=true
[Install]
WantedBy=multi-user.target
```

## 6. What did you expect to see?
Successfully running caddy service then acquire let's encrypt

## 7. What did you see instead (give full error messages and/or log)?
```
AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/<token>
caddy[15383]: 2019/02/27 16:41:32 [INFO] [mydomain] acme: use tls-alpn-01 solver
caddy[15383]: 2019/02/27 16:41:32 [INFO] [mydomain] acme: Trying to solve TLS-ALPN-01
caddy[15383]: 2019/02/27 16:41:33 [mydomain] failed to obtain certificate: acme: Error -> One or more domains had a problem:
caddy[15383]: [mydomain] [mydomain] acme: error presenting token: presenting with standard provider server: could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied
systemd[1]: caddy.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: caddy.service: Failed with result 'exit-code'.

```

## 8. Why is this a bug, and how do you think this should be fixed?
It's a fresh install of ubuntu 18.04 and caddy. I'm trying to run a Rocket.Chat server on my server with https. Server is running fine locally, my domain is pointing to my server, ports are good but stucked at this errors

## Caddyfile
```
mydomain {
	proxy / 127.0.0.1:3000 {
		header_upstream X-Forwarded-Proto {scheme}
                header_upstream X-Forwarded-For {host}
                header_upstream Host {host}
                websocket
        }
}
```

Thanks

**Comment by mholt** [comment]
Thanks for your question, and I'm thrilled that you're using Caddy! This looks more like a question about how to use Caddy rather than a bug report or feature request. Since this issue tracker is reserved for specific, development-focused discussions, I'm going to close this, but we have a [community forum](https://caddy.community) where more people will be exposed to your question, including people who may be more expert or experienced with the specific question you're facing. I hope you'll ask your question there, and thanks for understanding!
