### ISSUE TITLE
Email Server

### ISSUE THREAD

**Issue by Immortalin** [mholt/caddy#25]
It would be really great if Caddy can be used to handle emails. It would remove the need for a separate email server as setting up a [email](https://www.digitalocean.com/community/tutorials/how-to-configure-a-mail-server-using-postfix-dovecot-mysql-and-spamassasin) server is a royal PITA.

**Comment by mholt** [comment]
I don't think email is in Caddy's future, but that sounds like an excellent experiment for a separate project. [smtpd](https://bitbucket.org/chrj/smtpd) might be a decent starting point.

And yeah, I hate setting up email servers too.

**Comment by ApfelUser** [comment]
It would be nice if Caddy could proxy a mail server backend though.

**Comment by mholt** [comment]
@ApfelUser Thanks for the feedback. Caddy is a web server, so I don't intend to support mail (SMTP) anytime soon. What did you have in mind, specifically (just curious)?

**Comment by ApfelUser** [comment]
NGINX for example has an option to "proxy" an e-mail server. So it opens the standard ports for an e-mail server (25, 143, 995 ...) and is then proxying the requests to an backend of email servers. Kind of like proxying a NodeJS app.

**Comment by mholt** [comment]
Noted; thanks for the expansion. We will see if Caddy's scope evolves over time.

**Comment by DenBeke** [comment]
> It would be really great if Caddy can be used to handle emails. It would remove the need for a separate email server as setting up a email server is a royal PITA.

What part of a mail service do you want to setup, @Immortalin ? Because you need more than a simple MTA, you must also need IMAP (with user/mailbox management), and some decent spam (and spf) handling. I think this is way out of Caddy's scope.

**Comment by mholt** [comment]
Yeah we're not gonna do email. :stuck_out_tongue:  *Maybe* a mail proxying middleware, might make a good add-on.

But I will keep my eye on @DenBeke's project: https://github.com/gopistolet/gopistolet

**Comment by Immortalin** [comment]
@DenBeke just MTA + IMAP. Anything else can be dealt with by the client.
