### ISSUE TITLE
caddy 0.11.5 no longer support tls 1.0 & 1.1?

### ISSUE THREAD

**Issue by vibbow** [mholt/caddy#2512]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy 0.11.5

## 2. What are you trying to do?
Let a website running under tls 1.0

## 3. What is your Caddyfile?
I had following code snips working from caddy 0.11.4
```
tls /etc/ssl/caddy/server.crt /etc/ssl/caddy/server.key {
    protocols tls1.0 tls1.2
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?
Registered caddy into systemd (https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service)

## 5. Please paste any relevant HTTP request(s) here.
I use nmap to scan my server:
nmap -sV --script ssl-enum-ciphers -p 443 example.com

## 6. What did you expect to see?
nmap should show both tls 1.0, 1.1, 1.2 are available

## 7. What did you see instead (give full error messages and/or log)?
nmap only show tls 1.2 is available

## 8. Why is this a bug, and how do you think this should be fixed?
There is no changelog said tls 1.0, 1.1 support is removed in caddy 0.11.5

## 9. What are you doing to work around the problem in the meantime?
downgrade to caddy 0.11.4

**Comment by crvv** [comment]
TLS 1.0 and 1.1 are supported in 0.11.5.
But the default cipher suites only contain AEAD ciphers, which is not supported by TLS 1.0 and 1.1
If you want TLS 1.0 and 1.1 with version 0.11.5, the Caddyfile should be
```
tls {
    protocols tls1.0 tls1.2
    ciphers some_tls_1.0_1.1_ciphers
}
```

**Comment by tobya** [comment]
If this is the case we need to provide a warning to the user that they may need to specify ciphers or make it very obvious in the docs that this is the case.

**Comment by crvv** [comment]
Maybe it is better to add the CBC ciphers as default if TLS 1.0 or 1.1 is enabled.

**Comment by mholt** [comment]
Hmm, I'd rather not do that, because those protocols and ciphers should ultimately be phased out, so let's not make it easier to bring them back. I'll just update the release page to mention needing to specify older ciphers.

**Comment by tobya** [comment]
An additional concern here is that 1.1 is still enabled by default but some ciphers are not.  

Certain older browsers including Safari on older IPads and IPhones still connect with 1.1 with older ciphers making websites unavailable from these clients without intervention.

**Comment by mholt** [comment]
> An additional concern here is that 1.1 is still enabled by default but some ciphers are not.

TLS 1.1 is not enabled by default: https://github.com/mholt/caddy/blob/72d0debde6bf01b5fdce0a4f3dc2b35cba28241a/caddytls/config.go#L406 - the default minimum is TLS 1.2, but older versions can be enabled with 1 line of config (which I recommend against when avoidable).

The device connectivity issue is probably related to their not being updated to support strong cipher suites, but you can still enable weaker cipher suites with another line of config.
