### ISSUE TITLE
Support for quic 46

### ISSUE THREAD

**Issue by wusatosi** [mholt/caddy#2519]
## 1. What would you like to have changed?
Yes... quic seems to have updated again to version 46...
Latest chrome don't love quic version 44 anymore and is not using it... 
So can caddy add support for quic version 46?

## 2. Why is this feature a useful, necessary, and/or important addition to this project?
Since support for quic is an really attractive feature of caddy as an web server, I think it would be great and important to continue supporting & maintaining quic.

## 3. Please link to any relevant issues, pull requests, or other discussions.
Since quic standard is quickly evolving and git repository of quic's rfc is updating every half day , I would argue maybe it's better to wait for the rfc to finalize and then implement it afterwords, then chrome maybe willing to communicate with host even if it's one / two version behind.

(Sorry for my bad english orz

**Comment by marten-seemann** [comment]
Which version are you testing with?
Chrome Canary (75.0.3732.0) still speaks QUIC 43.

**Comment by wusatosi** [comment]
Chrome 73.0.3683.75 (Official Build) (64-bit)

**Comment by marten-seemann** [comment]
Then you're probably on an experiment. We won't support that.

**Comment by wusatosi** [comment]
fine.......................

**Comment by wusatosi** [comment]
sorry...........
