### ISSUE TITLE
Problem with proxy mode

### ISSUE THREAD

**Issue by hdid** [mholt/caddy#252]
Hi
I have a system with caddy 0.7.5 and i want to use it as a simple reverse proxy but i get error: "Internal Server Error"
Should i install any special package!?
Caddyfile:
0.0.0.0
root /var/www
proxy / http://www.onet.pl

**Comment by abiosoft** [comment]
@hdid remove the url scheme. i.e. `www.onet.pl`.

Does that work ?

**Comment by mholt** [comment]
Odd. What's the error being repoted? Add `errors error.log` to your Caddyfile to see the error message.

**Comment by hdid** [comment]
this:
```
20/Sep/2015:12:56:36 -0400 [PANIC /] /usr/local/go/src/sync/atomic/asm_386.s:118 - runtime error: invalid memory address or nil pointer dereference
```

**Comment by hdid** [comment]
Resolved. Because of memory issue, I checked system arch again and i saw it's i686. Then i got 64 bit version of caddy and it worked!

**Comment by hdid** [comment]
On other system; this error happened again. I tested both 386 and amd64 versions but did not work. 
```
# uname -a
Linux xxxxxxxxxx 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) i686 GNU/Linux
```

error log for 386 version:
```
21/Sep/2015:14:47:37 -0400 [PANIC /] /usr/local/go/src/sync/atomic/asm_386.s:118 - runtime error: invalid memory address or nil pointer dereference
```
and amd64 version:
```
-bash: ./caddy: cannot execute binary file: Exec format error
```

**Comment by mholt** [comment]
What was the exact command you used to execute caddy?

**Comment by hdid** [comment]
Simple; `./caddy`

**Comment by mholt** [comment]
Would you please send me a copy of your binary? Find my email at matt.chat and make sure to send me a copy of the exact file you're trying to run. I'm going to try to reproduce it on my machine.

**Comment by hdid** [comment]
Ok.I sent both binary files.Also, you can check Hash value for binaries:
```
File: caddy_linux_386/caddy
SHA1: 45a34330bbbd258661f33e3b0a451a54e6f5afb8
```
```
File: caddy_linux_amd64/caddy
SHA1: 136d61687267cb40c2e57278924a8939314d34a4
```
Thanks

**Comment by mholt** [comment]
Thanks for the email and the SHAs. I executed the 64-bit caddy binary on a fresh vagrant box (hashicorp/precise64) and it worked just fine. Its SHA1 matches: `136d61687267cb40c2e57278924a8939314d34a4`.

This is bizarre... What kind of system are you running caddy on? I know it's Linux, but is it a physical device or VM? Is it special hardware like raspberry pi or something (which is ARM... but anyway, you know what I mean)?

When you run `file ./caddy` what output do you get? I see:

```
caddy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
```

**Comment by hdid** [comment]
Well, 64 bit version does not work (as i pasted above) but 32 bit version runs normally but when i enable proxy mode it gives that error. The system is a Xen VM based on regular Intel:
```
# lscpu
Architecture:          i686
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                1
On-line CPU(s) list:   0
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Stepping:              3
CPU MHz:               3600.068
BogoMIPS:              7200.13
Hypervisor vendor:     Microsoft
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
```
the `file ./caddy` command output is normal:
`./caddy: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), statically linked, not stripped`
And yes it's a strange issue for me too. Thank you anyway ;)

**Comment by mholt** [comment]
I was able to reproduce this on a 32-bit system.

Cause: https://golang.org/src/sync/atomic/doc.go?s=1207:1656#L36

> On x86-32, the 64-bit functions use instructions unavailable before the Pentium MMX. On non-Linux ARM, the 64-bit functions use instructions unavailable before the ARMv6k core. On both ARM and x86-32, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a global variable or in an allocated struct or slice can be relied upon to be 64-bit aligned.

We do call atomic.AddInt64 [in a couple places](https://github.com/mholt/caddy/blob/10ab0378332debbf958617fc236fc70c24e1d69c/middleware/proxy/proxy.go#L106-L108) which is probably the real source of the panic. (Memo to self: A way to get the full stack trace.)

I confirmed it is by re-arranging the fields in the UpstreamHost, moving the Conns field to the first spot according to the suggestion in the Go sync/atomic docs. This made it work for me.

@hdid Feel free to confirm that this is fixed by building from source or wait until the next release to try it.

**Comment by hdid** [comment]
Ok

**Comment by hdid** [comment]
I downloaded the new build and the bug is resolved.
Thanks

**Comment by mholt** [comment]
Good thing too, since it went out like that for the new release today :smile:

:+1:
