### ISSUE TITLE
Dyndns plugin unknown directive

### ISSUE THREAD

**Issue by Zachar2** [mholt/caddy#2520]
I'm on Caddy 0.11.5, Windows 10 x64.

I built it with dyndns plugin on the official website but the following error occurs on startup:
> Error during parsing: Unknown directive 'dyndns'

The problem was reported before in the links below:
https://caddy.community/t/dyndns-questions/4078
https://github.com/linkonoid/caddy-dyndns/issues/1

It seems that the plugin must be officially approved. Is it possible or is this function abandoned?

Thanks.

**Comment by mholt** [comment]
Hi, unfortunately since you did not fill out the issue template, we don't have enough information to assist you. :( If you will update your post to answer the questions in the bug report template, we can help and reopen the issue. Thanks!

**Comment by Zachar2** [comment]
I updated the information. Please, let me know if something is still missing. Thanks.

**Comment by mholt** [comment]
@Zachar2 Thanks. Upon investigating, it seems that the plugin author has not submitted a pull request to add this directive to Caddy: https://github.com/linkonoid/caddy-dyndns/issues/1

Hence, Caddy doesn't recognize it unless you do it manually.

This is something that will have to be resolved by the plugin authors -- thanks for the question!
