### ISSUE TITLE
Compile error due to TLS version

### ISSUE THREAD

**Issue by johncming** [mholt/caddy#2524]
https://ci.appveyor.com/project/mholt/caddy/builds/23118907

![image](https://user-images.githubusercontent.com/11719334/54470519-14e24700-47e4-11e9-96ea-dd00056d3acf.png)

TLS 13 added in go 1.12, So this compilation error is not necessary

**Comment by mholt** [comment]
Yes, we're waiting for AppVeyor to update their images. https://github.com/appveyor/ci/issues/2875
