### ISSUE TITLE
Caddy 1.0 Backwards Compatibility

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#2529]
In preparation for a 1.0.0 tag, I've drafted up a first cut at a Caddy compatibility contract: https://docs.google.com/document/d/1AxKHgt705D76vojhFa2jx5EpbWmzpAyoCeaX5ALQ1jE/edit?usp=sharing *

This is not a legal (binding) contract.

The goal of this document is simply to declare that Caddy will be developed in good faith to adhere to these guidelines to make it easier and more reliable to run in production.

I invite your questions and feedback!

_\* Inspired from the Go's document: https://golang.org/doc/go1compat_

**Comment by mrexodia** [comment]
What is the reason for allowing removal of old/broken TLS versions if I may ask? Even though they should (obviously) be disabled per default I really appreciate the older protocol support for legacy crap...

**Comment by mholt** [comment]
I would consider using broken security protocols a security issue, thus exempt from compatibility promises.

Generally, we only remove support for _very_ old ciphers and versions, so they can be manually enabled (for example, we still allow TLS 1.0 to be enabled, for some reason) - but we may disable them by default.

**Comment by mholt** [comment]
Moved to wiki. May still tweak it before the 1.0 stable release, but I think it's mostly good. https://github.com/mholt/caddy/wiki/Compatibility-Guarantee
