### ISSUE TITLE
Go Code Report Card Errors

### ISSUE THREAD

**Issue by th3architect** [mholt/caddy#253]
http://goreportcard.com/report/mholt/caddy

I came across this great too to see where code could be cleaned up.

**Comment by mholt** [comment]
Oh yeah, that's a pretty cool site. Caddy ranks 33 :+1: I admit some of the cyclomatic complexity is a bit high and I don't run `go fmt -s` as often as I should. As for `go lint`, I don't always agree with it (like returns and if statements), but in this case many of the suggestions seem reasonable. We could implement those in this case.

I've got my hands full for a while. Anyone want to work to improve the code quality even more? We could fix the go fmt -s and most go lint issues without much trouble.

**Comment by zmb3** [comment]
I wouldn't mind taking this on.

**Comment by mholt** [comment]
@zmb3 Go for it! :+1:

**Comment by mholt** [comment]
Thanks to Zac's work we're now number 22 in the high scores :smile:
