### ISSUE TITLE
Switch CI systems

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#2539]
We need tests to run on Linux and Windows.

AppVeyor has been broken for almost 2 months.

Travis is... who knows what, but apparently they've been having issues too.

Looking for a CI system that is free for open source, reliable, easy to use, and uses the latest Go versions right away.

**Comment by Mohammed90** [comment]
It looks like [Azure Pipelines](https://azure.microsoft.com/en-us/pricing/details/devops/azure-pipelines/) offers "10 Free Parallel jobs with unlimited minutes per month" for open source projects. I never used it though, so you'll need someone else's review of their service.

**Comment by tobya** [comment]
Havnt tried it but heart [gitlab](https://about.gitlab.com/product/continuous-integration/) have a pretty good CI system which you can run from a github repo and is free for Open Source Repos.

**Comment by mholt** [comment]
I also got an email for https://buddy.works (but I'm not sure if ~4/day is enough).

@Mohammed90 Nice, that is well within our needs. Looks like the docs for Go are here: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/go?view=azure-devops - wow, and it even does Linux, Mac, and Windows! That might be all we need.

@tobya That also looks good, and it also supports all 3 main platforms.

I like both of those, I guess it'll come down to choosing one or both! I'll look into this.

**Comment by tobya** [comment]
[Podcast here ](https://softwareengineeringdaily.com/2019/03/15/gitlab-with-sid-sijbrandij/)

**Comment by francislavoie** [comment]
For reference regaring AppVeyor https://github.com/appveyor/ci/issues/2875

**Comment by mholt** [comment]
Oof, anyone know why Azure Pipelines needs write access to the code?

**Comment by mholt** [comment]
Done in https://github.com/mholt/caddy/commit/c00b3a520cb2447cd1d196c0b1983a0b77354174
