### ISSUE TITLE
Replace x/net/websocket for gorilla/websocket

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#254]
Apparently /x/net/websocket [has some compliance issues](https://github.com/gorilla/websocket#gorilla-websocket-compared-with-other-packages) and the gorilla project appears to be more active and popular. We should probably switch.

Anyone is welcome to claim this task since I've got my hands full right now. PRs welcome!

**Comment by varun06** [comment]
@mholt I haven't checked the websocket yet but writing api's as my day job. How much work you foresee (apologies for not being too familiar with Caddy yet, but I am going to use caddy cms with my hugo)??

**Comment by mholt** [comment]
Not much work, really. The whole use of websockets isn't more than a couple dozen lines of code. But I think @abiosoft might be working on this but we'd have to double-check.

**Comment by abiosoft** [comment]
Varun can go ahead with it.

Thanks.

**Comment by varun06** [comment]
Okay then, I will fix and PR.

**Comment by varun06** [comment]
@mholt I know it is embarrassing but I am going to ask. I haven't used web socket or caddy yet. But I have changed the package, can you let me know how to run web socket so that I can verify it is doing what it needs to do. my google fu didn't help much??

after my changes caddy tests are passing, I have some thoughts on tests, but they will come later :)

**Comment by mholt** [comment]
No problem @varun06 -- it's not obvious how to do it. I've asked @Karthic-Hackintosh to take a look at it with you, since he's written quite a few tests for Caddy already.

You can use this in your Caddyfile:

```
websocket /echo cat
```

and then a simple websocket page:

```
<script>
	var ws = new WebSocket("ws://localhost:2015/echo");
	ws.onmessage = function(event) {
		console.log("Message received:", event.data);
	};
</script>
```

to test it, by running `ws.send("Hello world")` in the browser console, for instance. You should see it echo your input back to you.

To test this in Go, create a websocket client and send some data through the pipe and see if it comes back to you! Again, Karthic should be able to help with that.

**Comment by Karthic-Hackintosh** [comment]
@varun06 : Whats the progress till now? If you are struggling with tests, dont worry I coud help you out

**Comment by varun06** [comment]
Hey Karthic,

Thanks man. I changed web socket to use gorilla one. I didn’t know how to run it and test. Matt told me and I am going to try that. Once I have it running then I will see if I can add tests to it. I will do it tomorrow or this weekend and I will contact you once I have it working on my machine.

Cheers,
Varun
On Oct 8, 2015, at 8:16 PM, karthic rao <notifications@github.com<mailto:notifications@github.com>> wrote:


@varun06<https://github.com/varun06> : Whats the progress till now? If you are struggling with tests, dont worry I coud help you out

**Comment by Karthic-Hackintosh** [comment]
@varun06  : Sure, Thanks for your time and contributions :) Please feel free to ping back if you need a helping hand .

**Comment by varun06** [comment]
Hey Karthic,

I have made some changes here : https://github.com/varun06/caddy/blob/caddy-issue254/middleware/websockets/websockets.go#L36-L61

It works and I tested it as suggested by Matt, still have some question about the error handling etc. I know I should read the source code and figure it myself too (which I am doing). But figured you will give me inputs fast :)

Thanks,
Varun

On Oct 8, 2015, at 10:43 PM, karthic rao <notifications@github.com<mailto:notifications@github.com>> wrote:


@varun06<https://github.com/varun06> : Sure, Thanks for your time and contributions :) Please feel free to ping back if you need a helping hand .

**Comment by Karthic-Hackintosh** [comment]
@mholt  : Please give a check on the changes made by varun, I'm currently travelling, The ServeHttp seems to be missing.

**Comment by varun06** [comment]
Hi,

Gorilla websocket implementation is little different. It doesn't have serveHttp.

Thanks,
Varun

On Oct 10, 2015, at 9:49 AM, karthic rao <notifications@github.com<mailto:notifications@github.com>> wrote:


@mholt<https://github.com/mholt> : Please give a check on the changes made by varun, I'm currently travelling, The ServeHttp seems to be missing.

-

**Comment by Karthic-Hackintosh** [comment]
Hmmm, I'll take a proper look at it once I settle down in few hours, Thank you Varun

**Comment by varun06** [comment]
Sure. Take your time. This is the first time i looked at that package. So feel free to give me feedback.

Thanks,
Varun

On Oct 10, 2015, at 9:53 AM, karthic rao <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmmm, I'll take a proper look at it once I settle down in few hours, Thank you Varun

-

**Comment by mholt** [comment]
@varun06 Looks good at a glance except for the error handling, like you said - feel free to open a pull request though, and then we can comment on specific lines.

For example, I'm wondering where `wsupgrader` is defined and from where `wshandler` is used.

**Comment by varun06** [comment]
Hey Guys,

You can ignore the code I shared yesterday. But after looking at gorilla web socket implementation and current web socket implementation in caddy, it seems that we might need to change couple of things. gorilla web socket doesn’t have any serveHTTP method and has "func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header) (*Conn, error)” that gives a connection type.

So I need your direction on how to go about it. it might take some time coz I need to read(reading) the caddy code to understand how things are working.

Thanks,
Varun

On Oct 10, 2015, at 9:10 PM, Matt Holt <notifications@github.com<mailto:notifications@github.com>> wrote:


@varun06<https://github.com/varun06> Looks good at a glance except for the error handling, like you said - feel free to open a pull request though, and then we can comment on specific lines.

For example, I'm wondering where wsupgrader is defined and from where wshandler is used.

**Comment by acmacalister** [comment]
I took a look at this issue this morning and think I almost got it figured out. Running into a couple errors with the upgrade, but after I get those resolved, it should be good. I will try to send a PR this afternoon for everyone to review.

**Comment by varun06** [comment]
@acmacalister cool, I couldn't do much this weekend, but if you have it ready, go for it. I will grab another one.

**Comment by acmacalister** [comment]
@varun06 cool. I did a PR if you would like to take a look at. I would appreciate any and all feedback from anyone.

**Comment by mholt** [comment]
Thanks for all who contributed to this!
