### ISSUE TITLE
Lint: Tackle Reported Lint Issues 

### ISSUE THREAD

**Issue by Mohammed90** [mholt/caddy#2541]
## 1. What would you like to have changed?

Clean, successful output of `golangci-lint run -E gofmt -E goimports -E misspell` against Caddy's repo with ~0 issues reported.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

Code hygiene, correctness, and visibility of possible failures.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

🤷‍♂️ 

## 4. Please link to any relevant issues, pull requests, or other discussions.

#2540 

## 5. How to start

- Install `golangci-lint`  with `go get -v github.com/golangci/golangci-lint/cmd/golangci-lint`
- Clone caddy's repo
- Run `golangci-lint run -E gofmt -E goimports -E misspell` against the repo
- Go wild

**Comment by u5surf** [comment]
@Mohammed90 @mholt 
I tried to this issue and fix `gofmt`, `gosimple`, `deadcode`, `unused` and serveral error codes of `staticcheck` which is `SA6002`, `SA6004`, `SA6005`, `SA9004`, `SA1009`
And remaining staticcheck is following
```
$ golangci-lint run -E gofmt -E goimports -E misspell -D errcheck
caddyhttp/proxy/reverseproxy.go:607:3: SA1019: t.Dial is deprecated: Use DialContext instead, which allows the transport to cancel dials as soon as they are no longer needed. If both are set, DialContext takes priority.  (staticcheck)
		t.Dial = b.Dial
		^
caddyhttp/proxy/reverseproxy.go:617:2: SA1019: t.Dial is deprecated: Use DialContext instead, which allows the transport to cancel dials as soon as they are no longer needed. If both are set, DialContext takes priority.  (staticcheck)
	t.Dial = func(network, addr string) (net.Conn, error) {
	^
caddyhttp/proxy/reverseproxy.go:634:5: SA1019: t.Dial is deprecated: Use DialContext instead, which allows the transport to cancel dials as soon as they are no longer needed. If both are set, DialContext takes priority.  (staticcheck)
	if t.Dial != nil {
	   ^
```
because, net/http.Transport has not supported `DialTLSContext` which is `DialContext` compatible yet. https://github.com/golang/go/issues/21526
And all errcheck fix remaining in progress.

**Comment by Inconnu08** [comment]
Hello @Mohammed90 @mholt,
Sorry, I'm new to contributing. I am trying to fix all lint `errchecks`. Would like to know if I'm going towards the right direction. Thank you.

**Comment by Mohammed90** [comment]
@Inconnu08 yes, you got those right. It seems like @u5surf is about to fix those as well, so maybe you two should coordinate.

**Comment by Inconnu08** [comment]
Oh sorry about that, @u5surf. I was only done with `caddy_test.go`, `caddyfile/lexer_test.go` and `caddyhttp/basicauth/basicauth.go `. Let me know if I could do some of them.

Also I just finished lint `structcheck`s. @Mohammed90

**Comment by u5surf** [comment]
@Inconnu80
Oh, I’m sorry I should have said the work in progress in advance 😅
In fact, I burnout to fix these lintings. So you can fix all of them which I remain. I think it is only remained errcheck.
@Mohammed99 Let me tell you whether is enough to fix of linting which we commit.

**Comment by Inconnu08** [comment]
@u5surf it's okay. I'll take it from here. 
@Mohammed90 please assign me this. I would like to complete the rest.

**Comment by mholt** [comment]
@Inconnu08 You got it. (I can only assign collaborators.)

**Comment by Inconnu08** [comment]
@Mohammed90 @mholt done with all `errcheck`s. Please let me know if any changes are needed.

**Comment by Mohammed90** [comment]
It's easier to review the changes if you submit the pull request. This will also allow for the CI to run against the changes and report any failures or lint issues.

**Comment by u5surf** [comment]
@mholt @Mohammed90 @Inconnu08 
I fixed `gofmt`, `gosimple`, `deadcode`, `unused` and serveral error codes of staticcheck which is SA6002, SA6004, SA6005, SA9004, SA1009 in #2554 
Did you review it? It seems not to do yet.
