### ISSUE TITLE
caddy works in ipv4 OR ipv6 mode only

### ISSUE THREAD

**Issue by nmr50** [mholt/caddy#2542]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy 0.11.5 (non-commercial use only)

## 2. What are you trying to do?

I want caddy to listen to v4 AND v6 different resolved addresses at the same time as it was 2-3 weeks ago..

## 3. What is your Caddyfile?
```text
http://v4.domain.tld:80, http://v6.domain.tld:80 {

#bind v4.domain.tld
#bind v6.domain.tld

root /home/tmh/caddy/web
gzip
log access.log
errors error.log

ipfilter / {
        rule allow
        blockpage def.html
        database /home/tmh/caddy/geolite/GeoLite2-Country.mmdb
        country RU UA LV EE IL US
}

gzip
gzip {
    level 6
    not   /images /videos
}
}
```
## 4. How did you run Caddy (give the full command and describe the execution environment)?

sudo batchfile
batch file content:
#!/bin/sh
cd /home/tmh/caddy/
ulimit -n 8192
/home/tmh/caddy/caddy -conf caddyfile &
exit

## 6. What did you expect to see?

Two weeks ago I've running caddy old version (0.9.6 or something) - both v4 and v6 addresses worked well...v6 connections disappeared since then, and I re-installed caddy with fresh version mentioned earlier.

## 7. What did you see instead (give full error messages and/or log)?

The main problem that only v4 -- OR -- v6 addresses are working, not both of them at the same time.

## 8. Why is this a bug, and how do you think this should be fixed?

Don't know, really.

## 9. What are you doing to work around the problem in the meantime?

Still have no soliution, that is why I am issuing this problem...

## 10. Please link to any related issues, pull requests, and/or discussion.

So, when I use standard string http://v4.domain.tld:80, http://v6.domain.tld:80 - only v4 host is answering, so I see only v4 listening port:
#netstat -nl | grep :80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN     

If I use bind for v4 AND v6 addresses, I see only v6 listening port:
tcp6       0      0 2001:..:80  :::*                    LISTEN      11107/caddy
If I comment out v6 bind string - I see again v4 listening port ONLY.

It still unclear - why v4 AND v6 started to ignore each other ?

I repeat - v4 and v6 addresses have different resolved names.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Private homepage.

**Comment by tobya** [comment]
Thank you for the issue.  

Can anyone else reproduce this?

**Comment by mholt** [comment]
Will probably be fixed in Caddy 2 as we've rearchitected the listener facilities.

**Comment by nmr50** [comment]
Seems like v1.0.0 I got from download server is working nice - both addresses - v4 AND v6 - answering now. Many thanks ! :)

**Comment by wmark** [comment]
So — is Caddy no longer 100% open source?

**Comment by mholt** [comment]
@wmark That is very off topic, so please continue that discussion in our forums: https://caddy.community
