### ISSUE TITLE
caddy -host $DOMAIN_NAME fails: "Cannot negotiate ALPN protocol"

### ISSUE THREAD

**Issue by maholloway** [mholt/caddy#2544]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy 0.11.5

## 2. What are you trying to do?
Run `caddy -host $DOMAIN_NAME` as root, where $DOMAIN_NAME is a registered domain name that resolves to the server's WAN IPv4 address. Ports 443 and 80 are open on the server firewall.

## 3. What is your Caddyfile?
N/A - Issue presents without Caddyfile

## 4. How did you run Caddy (give the full command and describe the execution environment)?
as root, run caddy -host $DOMAIN_NAME

## 5. Please paste any relevant HTTP request(s) here.
Server does not start successfully, no HTTP requests handled.

## 6. What did you expect to see?
Caddy successfully handle certbot registration process.

## 7. What did you see instead (give full error messages and/or log)?
Activating privacy features... 2019/04/01 03:24:40 [INFO] [moh.wtf] acme: Obtaining bundled SAN certificate
2019/04/01 03:24:41 [INFO] [moh.wtf] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/wWWhix3JVZhP4Kdnhy7KTCDId75tZRWNWJ57JZFPi88
2019/04/01 03:24:41 [INFO] [moh.wtf] acme: use tls-alpn-01 solver
2019/04/01 03:24:41 [INFO] [moh.wtf] acme: Trying to solve TLS-ALPN-01
2019/04/01 03:24:47 [moh.wtf] failed to obtain certificate: acme: Error -> One or more domains had a problem:
[moh.wtf] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge, url: 

contents of caddy.log (-log output)

> 
2019/04/01 03:26:31 [INFO][FileStorage:/root/.caddy] Started certificate maintenance routine

## 8. Why is this a bug, and how do you think this should be fixed?
The server does not start using the supplied fatbin and using the "on-the-tin" startup command.

## 9. What are you doing to work around the problem in the meantime?
Caddy does not start so I will use another proxy server in the meantime.

## 10. Please link to any related issues, pull requests, and/or discussion.
Also posted to caddy.community, https://caddy.community/t/error-stapling-ocsp/5413/4

## Bonus: What do you use Caddy for? Why did you choose Caddy?
I hope it can be as simple as I need. Don't want to switch to nginx but it might actually be simpler with my current setup.

**Comment by maholloway** [comment]
Workaround so far:
Set selinux to permissive and feelsbadman.gif

I'll see if I can't contribute a policy file for centos 7

**Comment by carlwgeorge** [comment]
Caddy is packaged in EPEL with the necessary selinux integration.  You could just use that.

If you want to keep using your own binary, but want to get selinux working, run the commands in the package's [%post scriptlet](https://src.fedoraproject.org/rpms/caddy/blob/master/f/caddy.spec#_492):

```
if [ -x /usr/sbin/getsebool ]; then
    # connect to ACME endpoint to request certificates
    setsebool -P httpd_can_network_connect on
fi
if [ -x /usr/sbin/semanage -a -x /usr/sbin/restorecon ]; then
    # file contexts
    semanage fcontext --add --type httpd_exec_t        '%{_bindir}/caddy'               2> /dev/null || :
    semanage fcontext --add --type httpd_sys_content_t '%{_datadir}/caddy(/.*)?'        2> /dev/null || :
    semanage fcontext --add --type httpd_config_t      '%{_sysconfdir}/caddy(/.*)?'     2> /dev/null || :
    semanage fcontext --add --type httpd_var_lib_t     '%{_sharedstatedir}/caddy(/.*)?' 2> /dev/null || :
    restorecon -r %{_bindir}/caddy %{_datadir}/caddy %{_sysconfdir}/caddy %{_sharedstatedir}/caddy || :
fi
if [ -x /usr/sbin/semanage ]; then
    # QUIC
    semanage port --add --type http_port_t --proto udp 80   2> /dev/null || :
    semanage port --add --type http_port_t --proto udp 443  2> /dev/null || :
    # HTTP challenge alternate port
    semanage port --add --type http_port_t --proto tcp 5033 2> /dev/null || :
fi
```

Some of the paths are specific to the package and may not match what you are using on your system and will need to be adjusted.

* `%{_bindir}/caddy` is `/usr/bin/caddy`
* `%{_datadir}/caddy` is `/usr/share/caddy` (the welcome index.html)
* `%{_sysconfdir}/caddy` is `/etc/caddy` (system-wide Caddyfile)
* `%{_sharedstatedir}/caddy` is `/var/lib/caddy` (CADDYPATH)
