### ISSUE TITLE
Customize MIME types

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#255]
An [email came in today](http://stackoverflow.com/questions/32727309/caddy-web-server-and-flash-file/32748521) about serving .swf files (old tech, but still used apparently). By default, Caddy serves binary files as, well, binary (application/octet-stream) which triggers a download. But in this case, the user wanted the browser to show the file, not download it to the user's Download folder. The Content-Type needed to be "application/x-shockwave-flash".

This was able to be achieved with the `header` directive but that assumes all the Flash content is in its own folder. Perhaps a `mime` or `filetype` directive is in order:

```
mime .swf application/x-shockwave-flash
```

Or multiple:

```
mime {
    .swf application/x-shockwave-flash
    # more here...
}
```

This would simply change the Content-Type header based on file extension rather than path.

**Comment by abiosoft** [comment]
`mime` sounds better.

I can work on this (provided someone hasn't started already) and I want to assume this is gonna be part of caddy core.

**Comment by mholt** [comment]
Yes, setting the proper Content-Type is a pretty important job of a server. I agree it'll be part of core.
