### ISSUE TITLE
IETF QUIC support

### ISSUE THREAD

**Issue by klaasel** [mholt/caddy#2559]
Is Caddy using the IETF draft implementation of quic-go and supporting IETF QUIC? Or is it still on gQUIC like mentioned [here](https://github.com/quicwg/base-drafts/wiki/Implementations)?

**Comment by francislavoie** [comment]
@marten-seemann can probably answer this

**Comment by marten-seemann** [comment]
It's gQUIC. IETF QUIC doesn't have browser support yet, so there's no point in deploying it on the server side yet.

**Comment by mholt** [comment]
Caddy 2 will support IETF-draft-compatible HTTP/3, very soon: https://github.com/caddyserver/caddy/pull/2727
