### ISSUE TITLE
FastCGI: REQUEST_URI after rewrite

### ISSUE THREAD

**Issue by DenBeke** [mholt/caddy#256]
When querying the `REQUEST_URI` environmental variable without rewrites, it correctly gives the whole request uri, but when a rewrite took place, it only returns the actual script name called...

* Without rewrite:  `REQUEST_URI`: `/index.php/apps/files/`
* With rewrite:  `REQUEST_URI`: `/index.php`

**Comment by mholt** [comment]
Uh oh. Well, unless I'm missing something obvious there's currently no way to deal with this... but I have an idea.

We could make the rewrite middleware set a request header for internal Caddy use only, a header that indicates what the original URI was. Then the fastcgi middleware could check for that header and use it. Kind of a hack but a fair way to keep some simple context between handlers. What do you think @abiosoft? Is there a better way to do this?

**Comment by DenBeke** [comment]
> Uh oh. Well, unless I'm missing something obvious there's currently no way to deal with this... but I have an idea.

That why I didn't even start looking into it, because it's how the middleware is designed, isn't it?

**Comment by mholt** [comment]
Yep. It was a good design in theory :smile: But I think we can make it work. I'll experiment on the train today.

**Comment by mholt** [comment]
@DenBeke Would you please pull the latest and try commit be6fc35326051094b3dcbd5fa7c106ae57705dc1? I don't think it broke anything but just be sure. Also see if it fixes this issue and let me know.

**Comment by DenBeke** [comment]
@mholt This solved the "main error" I was experiencing. Will check again with a cleaner ownCloud installation, because I messed a lot in it's source.

**Comment by DenBeke** [comment]
@mholt This fixes all problems I was experiencing.
Next up is enhancing rewrites for all pages to obtain a completely working ownCloud installation...

**Comment by mholt** [comment]
@DenBeke Sounds good, I will continue that via email with you. Thanks!
