### ISSUE TITLE
Windows Service not there in https://github.com/mholt/caddy/tree/master/dist/init

### ISSUE THREAD

**Issue by joeblew99** [mholt/caddy#2567]
Is this supported ?
I dont see anything for Windows there...

See
https://github.com/mholt/caddy/tree/master/dist/init

**Comment by mholt** [comment]
No, but there's a 3rd-party plugin for installing Caddy as a service: https://caddyserver.com/docs/hook.service

**Comment by francislavoie** [comment]
You could also use https://nssm.cc/ which is a nice tool for configuring your own windows service with a GUI.
