### ISSUE TITLE
quic: Certificates not set in tls.Config issue in 1.0.0-beta1

### ISSUE THREAD

**Issue by elanfer** [mholt/caddy#2568]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy 1.0.0-beta1

## 2. What are you trying to do?

I tried to run the quic vwith caddy 1.0.0-beta1 version (for testing purposes)

## 3. What is your Caddyfile?
```
domain.tld:443 {
        root /home/user/www/
        tls user@mail.tld
}
```
(removed my domain and user names)

## 4. How did you run Caddy (give the full command and describe the execution environment)?

./caddy -log stdout -conf ../caddyfile -quic

## 6. What did you expect to see?

Communication via QUIC 
Chrome 75.0.3766.2 with activated Quic flags was used, browser worked properly on other websites with Quic

## 7. What did you see instead (give full error messages and/or log)?

Only http2 was served. My assumption is that the tls configuration is not properly served to the quic-go modules. On startup the follwoing log message appears:
```
serving QUIC connections: quic: Certificates not set in tls.Config
```

## 9. What are you doing to work around the problem in the meantime?

Used v0.11.5 instead (same configuration is working properly here)

## 10. Please link to any related issues, pull requests, and/or discussion.

 #1483

**Comment by marten-seemann** [comment]
The reason is that for some reason beta1 was shipped with a super outdated version of quic-go. QUIC support won't work anyway, since browsers don't support that old QUIC versions any more.
#2562 will fix this.

**Comment by mholt** [comment]
Just merged it in! Try it out :)
