### ISSUE TITLE
Can't get beanstalkd

### ISSUE THREAD

**Issue by yusupprog** [mholt/caddy#2569]
<img width="1487" alt="Screen Shot 2019-04-18 at 19 55 42" src="https://user-images.githubusercontent.com/11705239/56366127-2f10aa00-6214-11e9-96f0-24fd232a4dae.png">

Tried a couple of times. Also my laradock version is sync with the master branch.
Anybody faced this problem?

**Comment by abiosoft** [comment]
Kindly re-create this issue using the format in the issue template and indicate how it is an issue with Caddy.

Thanks.

**Comment by yusupprog** [comment]
Sorry, I've posted to the wrong repo
