### ISSUE TITLE
1.0.0-beta2 not buildable

### ISSUE THREAD

**Issue by ulrichSchreiner** [mholt/caddy#2574]
hi,

in the `go.mod` of the 1.0.0-beta2 tag there is a dependency to `github.com/caddyserver/builds` which has gone. If you want to build caddy you get an error because of this missing dependency. If you already have it in your local modules cache you won't see this error.

in the master branch you made a `go mod tidy` which removed this dependency so the master can be build.

You should release a new tag with the corrected `go.mod`

**Comment by hectorm** [comment]
Until a new tag is released, it is possible to build Caddy by referencing this specific commit:
```
go get github.com/mholt/caddy/caddy@v1.0.0-beta2.0.20190420233410-0c3d90ed21a4
```

This is what I'm doing in my [Docker image](https://github.com/hectorm/docker-caddy).

**Comment by Henrocker** [comment]
You can also just build from master.

**Comment by ulrichSchreiner** [comment]
I know and i already build from master but as i build docker images, master is suboptimal for tagging.
