### ISSUE TITLE
HTTP 500: curl https://getcaddy.com | bash -s personal http.cors

### ISSUE THREAD

**Issue by dmorris99** [mholt/caddy#2576]
Unable to download Caddy personal license with CORS plugin.

Any ETA on when this will be fixed? Alternatively, is there a build from source script that includes CORS plugin (or all plugins)?

thank you!

**Comment by Henrocker** [comment]
Build server is under maintenance while Caddy is in current beta.

Try building from source or pull a version as stated in the updated README.md.

**Comment by lypyhao** [comment]
When will Build Server restored?

**Comment by Henrocker** [comment]
Whenever Caddy 1.0.0 is out of beta stage.

**Comment by mholt** [comment]
To clarify, the build server works currently (it was down for a few hours over the weekend) -- it's just a combination of how Go modules work + the fact that our latest non-prerelease tag doesn't support modules, that causes some plugins to fail the build.

If plugins move to modules sooner, this problem will mostly disappear I think. Either that or when we tag 1.0 stable, which is very soon anyway.

But I won't be sure until we actually do tag 1.0, sigh.
