### ISSUE TITLE
Removing caddyserver/builds breaks builds < 1.0.0

### ISSUE THREAD

**Issue by envygeeks** [mholt/caddy#2577]
## 1. Which version of Caddy are you using (`caddy -version`)?

0.11.0

## 2. What are you trying to do?

Right now I build a custom version of Caddy < 0.11.0, it relies on caddyserver/builds to build daily to provide potential security updates of both the Docker image, and possibly Caddy, but the removal of caddyserver/builds has broken this build before 1.0.0 comes out of beta.

## 6. What did you expect to see?

caddyserver/builds to remain until 1.0.0 at least.

**Comment by elcore** [comment]
You don't really need caddyserver/builds to build older versions of Caddy. Just run `go build` instead of `go run build.go`

**Comment by mmlb** [comment]
cross linking: https://caddy.community/t/please-bring-back-github-com-caddyserver-builds/5552

**Comment by mmlb** [comment]
It also breaks builds from master it seems:
```
~/code/src/github.com/mholt/caddy @fb316692 #v1.0.0-beta2                                                                                     0.00 11:32:54
❯ git describe --dirty
v1.0.0-beta2

~/code/src/github.com/mholt/caddy @fb316692 #v1.0.0-beta2                                                                                     0.00 11:32:58
❯ echo $GO111MODULE
on

~/code/src/github.com/mholt/caddy @fb316692 #v1.0.0-beta2                                                                                     0.00 11:33:01
❯ git clean -fxd

~/code/src/github.com/mholt/caddy @fb316692 #v1.0.0-beta2                                                                                     0.00 11:33:04
❯ go build
go: finding github.com/caddyserver/builds v0.0.0-20170910200810-c62e2219460a
go: github.com/caddyserver/builds@v0.0.0-20170910200810-c62e2219460a: git fetch -f https://github.com/caddyserver/builds refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/manny/code/pkg/mod/cache/vcs/0cf23b6216c4b8749cc14dad14a5c774e19e9f350db490ddb26c89b9a152e27c: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
go: error loading module requirements

```

**Comment by mmlb** [comment]
```
~/code/src/github.com/mholt/caddy @fb316692 #v1.0.0-beta2                                                                                   1 0.47 11:33:07
❯ git grep caddyserver/builds
go.mod: github.com/caddyserver/builds v0.0.0-20170910200810-c62e2219460a
go.sum:github.com/caddyserver/builds v0.0.0-20170910200810-c62e2219460a h1:/QF4JSis49aT5EttkyiWjj8EQ/HvTLoVF0C90mD3oEY=
go.sum:github.com/caddyserver/builds v0.0.0-20170910200810-c62e2219460a/go.mod h1:+ku9jD54BwZiFQSoYXMc18iQ5u3eED8Mvd174cZno3Q=
```

**Comment by mholt** [comment]
Try building from commit 0c3d90ed21a4df1b5e75ff4d5f908fd3018f902c or newer, it cleans up the go.mod file.

**Comment by mmlb** [comment]
oops, yup I mistook master and beta2

**Comment by envygeeks** [comment]
I will try this tonight! Thanks for letting me know!

**Comment by bitspill** [comment]
I understand the desire to push forward and discourage building old versions however I think the caddyserver/builds repository should at least remain until Caddy 1.0 has actually released rather than disappearing while it's in Beta allowing the stable 0.11.5 to be used until such time as a full release has occurred

**Comment by mholt** [comment]
@bitspill 

> I understand the desire to push forward and discourage building old versions however I think the caddyserver/builds repository should at least remain until Caddy 1.0 has actually released rather than disappearing while it's in Beta allowing the stable 0.11.5 to be used until such time as a full release has occurred

We need to do this to test to make sure all processes depending on the old build script are actually upgraded before finalizing the 1.0 release. Otherwise 1.0 becomes more of a testing release, which we're trying to avoid as much as we can.
