### ISSUE TITLE
Caddy-cache license LGPL

### ISSUE THREAD

**Issue by CMogilko** [mholt/caddy#2578]
## 1. Which version of Caddy are you using (`caddy -version`)?

master, c32a0f5f712f0dee7b473946fcee65e826501e56

## 2. What are you trying to do?

Caddy suggest to use caching plugin which licensed as LGPL
https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L638
Also binaries from caddyserver.com built with this plugin.

## 8. Why is this a bug, and how do you think this should be fixed?

Caddy can't use LGPL plugin while remaining Apache2 licensed. `nicolasazrak/caddy-cache` should change license or Caddy should use another caching plugin.

## 10. Please link to any related issues, pull requests, and/or discussion.

https://github.com/nicolasazrak/caddy-cache/issues/41

**Comment by mholt** [comment]
Yeah, that's against our terms, and is the first item on the checklist for publishing a Caddy plugin: https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page#before-you-publish

I'll see if it can be changed, or if not, I'll remove it from our site.

**Comment by mholt** [comment]
He changed it to MPL so I think we're good now! Thanks.
