### ISSUE TITLE
Download from caddyserver.com failed.

### ISSUE THREAD

**Issue by newcoderlife** [mholt/caddy#2579]
## 1. Which version of Caddy are you using (`caddy -version`)?

None

## 2. What are you trying to do?

Download caddy from [caddyserver.com](https://caddyserver.com).

## 3. What is your Caddyfile?
```text
paste entire Caddyfile here - DO NOT REDACT ANYTHING (except credentials)
```

None

## 4. How did you run Caddy (give the full command and describe the execution environment)?

None

## 5. Please paste any relevant HTTP request(s) here.

None

## 6. What did you expect to see?

Correctly install caddy.

## 7. What did you see instead (give full error messages and/or log)?

```
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"
```

I also see `building caddy: exit status 1` when I get caddy from web page.

## 8. Why is this a bug, and how do you think this should be fixed?

Maybe a plugin page is failed.

## 9. What are you doing to work around the problem in the meantime?

Cancel some of the plugin in download sheet and retry. Only caddy without plugin is ok.

## 10. Please link to any related issues, pull requests, and/or discussion.

None

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Quic

**Comment by newcoderlife** [comment]
I try several VPS in Asia. None of them works correct. Them are newly installed Debian.

**Comment by whitestrake** [comment]
Hey @newcoderlife,

I was able to download Caddy just fine using `curl https://getcaddy.com | bash -s personal`.

```
whitestrake at ishtar in ~
→ curl https://getcaddy.com | bash -s personal
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0   7752      0 --:--:-- --:--:-- --:--:--  7743
Downloading Caddy for linux/amd64 (personal license)...
Download verification OK
Extracting...
Backing up /usr/local/bin/caddy to /usr/local/bin/caddy_old
(Password may be required.)
[sudo] password for whitestrake:
Putting caddy in /usr/local/bin (may require password)
Caddy v1.0.0-beta2 (h1:sG4ac7b3dlTdJG2Jb1q0NxFPDGz6kKA+VXM3QSgvhII=)
Successfully installed
```

Are you downloading it with plugins? If so, refer to https://github.com/mholt/caddy/issues/2576#issuecomment-485455511.

**Comment by newcoderlife** [comment]
Thanks a lot for help. I would try a older version.
