### ISSUE TITLE
Dont install caddy

### ISSUE THREAD

**Issue by 344524488** [mholt/caddy#2581]
curl https://getcaddy.com | bash -s personal http.forwardproxy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0  10407      0 --:--:-- --:--:-- --:--:-- 10394
Downloading Caddy for linux/amd64 (personal license)...
curl: (22) The requested URL returned error: 500 Internal Server Error
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"

**Comment by whitestrake** [comment]
Hi @344524488, please refer to https://github.com/mholt/caddy/issues/2576#issuecomment-485455511.
