### ISSUE TITLE
Simple rewrite rules don't support regex captures

### ISSUE THREAD

**Issue by AndreKR** [mholt/caddy#2586]
This is more a feature request than a bug, but the current behavior is quite confusing.

The simple rewrite syntax (`rewrite [not] from to...`) supports regex matching in `from`, but it **does not support** replacement of numbered regex captures in `to`. Granted, it is not documented that it would, but it **does support** replacement of request placeholders in `to` and that isn't documented either.

**Comment by AndreKR** [comment]
Following your :+1: I have prepared a MR: #2592

**Comment by abiosoft** [comment]
That was actually an oversight from me. It should've been added when I added regex support to simple rule.

Thanks.
