### ISSUE TITLE
Plugin builds can now be made go-gettable with v1 and go modules \o/

### ISSUE THREAD

**Issue by stp-ip** [mholt/caddy#2587]
Thanks for all the effort going into v1 and the final switch to go modules.

This brings a nice feature of cleaner code and making plugin builds go-gettable:

github.com/txtdirect/txtdirect <-- plugin code with setup.go files
github.com/txtdirect/txtdirect/cmd/txtdirect <-- package code as seen below:
```
package main

import (
	"github.com/mholt/caddy/caddy/caddymain"

	_ "github.com/txtdirect/txtdirect"
)

func main() {
	caddymain.EnableTelemetry = false
	caddymain.Run()
}
```

This makes it easily importable as a plugin `import github.com/txtdirect/txtdirect`, but also go-gettable with the correct caddy version etc. `GO111MODULE=on go get github.com/txtdirect/txtdirect@master`.

**Comment by stp-ip** [comment]
Bonus point of your own custom go-gettable caddy version:

```
package main

import (
	"github.com/mholt/caddy/caddy/caddymain"

	_ "github.com/SchumacherFM/mailout"
	_ "github.com/captncraig/caddy-realip"
	_ "github.com/miekg/caddy-prometheus"
	_ "github.com/txtdirect/txtdirect"
)

func main() {
	caddymain.EnableTelemetry = false
	caddymain.Run()
}
```

Now you can go get that main package and get your custom Caddy build including the imported plugins.

_Sidenote: For commercial use don't hesitate to get a subscription for Caddy https://caddyserver.com/products/licenses to make it sustainable :wink:_

**Comment by mholt** [comment]
Indeed! I'm glad you pointed this out. We updated our build instructions a few days ago to suggest that very workflow: https://github.com/mholt/caddy#build

Will probably stay this way for Caddy 2 as well.
