### ISSUE TITLE
Using HTTPS wildcards to find all domains, breaking security through obscurity 

### ISSUE THREAD

**Issue by herohamp** [mholt/caddy#2593]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy 0.11.0 (non-commercial use only)

## 2. What are you trying to do?
I have a DNS record pointed to my server with no entry in my caddyfile. If I then try to connect to that domain over HTTPS I get an error about an invalid certificate, from one of my domain seemingly at random, by reload enough I was able find to what I believed to be hidden domains.

## 6. What did you expect to see?
I expected to see an error for an invalid SSL cert not tied to one of my websites.

## 7. What did you see instead (give full error messages and/or log)?
I explained in #2

## 8. Why is this a bug, and how do you think this should be fixed?
I explained in #2

## 9. What are you doing to work around the problem in the meantime?
Ive added login methods to all those websites.

## Bonus: What do you use Caddy for? Why did you choose Caddy?
I chose Caddy because it simplified my stack and deploying websites

**Comment by whitestrake** [comment]
Duplicate of https://github.com/mholt/caddy/issues/1303.

Fixed in https://github.com/mholt/caddy/commit/79810d3d2372a583a81f5200928adb215a197732.

Please update Caddy.

**Comment by tobya** [comment]
Domains are not hidden, ct logs list all letsencrypt tls certs in publically accessible lists
