### ISSUE TITLE
Callback to expand address in caddyfile/loader.go

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#2596]
## 1. What would you like to have changed?
I would like to propose a callback in the default caddyfile.Loader (https://github.com/mholt/caddy/blob/master/caddyfile/parse.go) that expands the addresses found on the line via a callback function.

This should be called somewhere in https://github.com/mholt/caddy/blob/master/caddyfile/parse.go#L155

Another way for us (coredns) to implement this is to fork the entire loader, but this seems a waste as it duplicates the effort.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

We want to allow folks to type `10.129.60.0/22` which gets *expanded* to
60.129.10.in-addr.arpa. 61.129.10.in-addr.arpa. 62.129.10.in-addr.arpa. 63.129.10.in-addr.arpa.
by the loader so reverse DNS zones *just work*. 

See https://github.com/coredns/coredns/issues/2779 and https://github.com/coredns/coredns/issues/2779

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

Fork the caddyfile/loader and write our own - not a fan of this as the alternative is a few lines of code here.

## 4. Please link to any relevant issues, pull requests, or other discussions.
https://github.com/coredns/coredns/issues/2779 and https://github.com/coredns/coredns/issues/2779

**Comment by mholt** [comment]
Is this something you can do in your `InspectServerBlocks()` callback? For example, Caddy's HTTP server iterates each key and normalizes them: https://github.com/mholt/caddy/blob/a2ed91bc45c8b3faa1577ed4c18334d38a581ca7/caddyhttp/httpserver/plugin.go#L132-L138

You could do something similar: iterate each key, and append to the keys by expanding applicable keys for the server blocks that you return.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Callback to expan..." ]
>Is this something you can do in your `InspectServerBlocks()` callback? For example, Caddy's HTTP server iterates each key and normalizes them: https://github.com/mholt/caddy/blob/a2ed91bc45c8b3faa1577ed4c18334d38a581ca7/caddyhttp/httpserver/plugin.go#L132-L138
>
>You could do something similar: iterate each key, and append to the keys by expanding applicable keys for the server blocks that you return.

Thanks.

I think the current PR does something like that, but does that mean 
(https://github.com/coredns/coredns/blob/master/plugin/file/setup.go#L67) 
c.ServerBlockKeys is *also* updated? Got a feeling this is happening too late in 
the process.

/Miek

--
Miek Gieben

**Comment by mholt** [comment]
Should be fine. According to the [godoc for InspectServerBlocks](https://godoc.org/github.com/mholt/caddy#Context):

```
    // Called after the Caddyfile is parsed into server
    // blocks but before the directives are executed,
    // this method gives you an opportunity to inspect
    // the server blocks and prepare for the execution
    // of directives.
```

So the directives within the server block have not yet been executed. By the time they are, your InspectServerBlocks function will have already expanded the keys.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Callback to expan..." ]
>Should be fine. According to the [godoc for InspectServerBlocks](https://godoc.org/github.com/mholt/caddy#Context):
>
>```
>    // Called after the Caddyfile is parsed into server
>    // blocks but before the directives are executed,
>    // this method gives you an opportunity to inspect
>    // the server blocks and prepare for the execution
>    // of directives.
>```
>
>So the directives within the server block have not yet been executed. By the time they are, your InspectServerBlocks function will have already expanded the keys.

OK, cool. Thanks for rtfm-ing :)

**Comment by mholt** [comment]
No problem, it's not obvious!
