### ISSUE TITLE
build caddy with plugin dnspod failed

### ISSUE THREAD

**Issue by colachg** [mholt/caddy#2598]
## 1. Which version of Caddy are you using (`caddy -version`)?

caddy v1.0.0

## 2. What are you trying to do?

```
package main

import (
	"github.com/mholt/caddy/caddy/caddymain"
	
	// plug in plugins here, for example:
	// _ "import/path/here"
	_ "github.com/caddyserver/dnsproviders/dnspod"
)

func main() {
	// optional: disable telemetry
	//caddymain.EnableTelemetry = false
	caddymain.Run()
}

```

follow the README, when run `go build`:
```
...
go: github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
...
go: error loading module requirements
```

## 3. Please link to any related issues, pull requests, and/or discussion.

https://github.com/h2non/gock/issues/50

**Comment by colachg** [comment]
add `replace github.com/h2non/gock => gopkg.in/h2non/gock.v1 v1.0.14 ` in go.mod  solve it.
so close it.

**Comment by anaganisk** [comment]
@colachg im not sure id this is the correct way this is solved, ma be better would be this be resolved in the dependencies internally?
