### ISSUE TITLE
Go Noob: Why is this build failing?

### ISSUE THREAD

**Issue by STaRDoGG** [mholt/caddy#2599]
After growing weary of trying to dl caddy updates from the dl page itself, I decided to try getting around the vague website errors by building right from source.

This is my first time trying to build anything Go related from source; I just installed the latest Go: `go1.12.5 windows/amd64`, and created the `.go` file:

**Here:**
https://pastebin.com/gUSBPmvE

Did `go mod init caddy`, and then `go build`.

**After about 5 minutes it just shows:**
"can't load package: package caddy: no Go files in G:\Program Files\Coding\Go\mybuilds\caddy"

**Here's the entire build log:**
https://pastebin.com/iWMGtzht

Not being familiar with Go, that error seems just as vague as the website errors, lol.

Any ideas?
tia

P.S. I KNOW it's a lot of plugins! ;)

**Comment by francislavoie** [comment]
I believe I see `caddy-filter` in there. Currently, that plugin doesn't compile with go modules unfortunately. https://github.com/echocat/caddy-filter/issues/40

**Comment by STaRDoGG** [comment]
@francislavoie thank you, I appreciate the help. I commented the filter plugin out and tried again, but still get the same 'error'.

If I keep re-running `go build` eventually it just shows nothing bu the vague error.

![image](https://user-images.githubusercontent.com/1524526/57326922-31f41180-70d3-11e9-9361-e72950e911cc.png)

When building, I see several that say 'incompatible' while it's finding/downloading/extracting; I'm wondering if that's something I should be paying attention to, or just ignoring?

**Comment by abiosoft** [comment]
@STaRDoGG Well, erm, that's strange. Have you tried building on a Linux machine?
I'll use your exact paste files and see if I can reproduce your error.

**Comment by STaRDoGG** [comment]
@abiosoft no, I haven't tried. I plan to use it solely on a Windows machine.

**Comment by unixfox** [comment]
I just tested to compile it with a linux machine and it worked so I think there is an issue with the caddy build server.

**Comment by STaRDoGG** [comment]
I just tried again (on Windows again) to see if perhaps it was a server glitch then, but same result.

**Comment by mholt** [comment]
@unixfox 
> I just tested to compile it with a linux machine and it worked, so I think there is an issue with the caddy build server.

Could very well be. I will try to look at the logs when I get a chance next!

**Comment by STaRDoGG** [comment]
For the record, I just tried building (on windows) w/out any plugins:

```
package main

import (
	"github.com/mholt/caddy/caddy/caddymain"
)

func main() {
	caddymain.EnableTelemetry = false
	caddymain.Run()
}
```

**And I still get:**

```
G:\Program Files\Coding\Go\mybuilds\caddy
go build
go: finding github.com/mholt/caddy/caddy/caddymain latest
go: finding github.com/mholt/caddy/caddy latest
go: downloading golang.org/x/net v0.0.0-20190328230028-74de082e2cca
go: downloading github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: downloading github.com/miekg/dns v1.1.3
go: extracting github.com/hashicorp/golang-lru v0.0.0-20180201235237-0fb14efe8c47
go: extracting golang.org/x/net v0.0.0-20190328230028-74de082e2cca
go: extracting github.com/miekg/dns v1.1.3
can't load package: package caddy: no Go files in G:\Program Files\Coding\Go\mybuilds\caddy
```

**Comment by STaRDoGG** [comment]
Almost 2 weeks since my last post and gave it another shot; same result.

![image](https://user-images.githubusercontent.com/1524526/58045163-4e4a7200-7b07-11e9-8288-a614653d7958.png)

Any updates?

**Comment by mholt** [comment]
With the current information, this does not appear to be an issue with the build server or with Caddy specifically -- clearly, the rest of us are able to build it fine; I would suggest asking the Go community for help with building Go programs and/or using modules. Thanks!

**Comment by STaRDoGG** [comment]
No worries. I've moved onto Nginx. Caddy was just too wrought with problems for me. Everything's been quick and easy using the linuxserver/letsencrypt container.

**Comment by mholt** [comment]
@STaRDoGG Did you try using our build server? "Caddy was just too wrought with problems for me" isn't really accurate when the problem is actually that you were unable to compile a Go program...

**Comment by STaRDoGG** [comment]
I've run into numerous issues when using (or attempting to use/build, etc.) Caddy; from config issues, to downloading issues, (whether from the download page itself, and having to manually test 1-by-1 which broken plugin is preventing the download, with only an ambiguous error message, or trying to build Caddy myself to get around that), to trying to build a Docker image of it myself, since Abiosoft's container didn't have the plugins I needed, then whether using his container or a stripped bare version of Caddy itself, Caddy kept crashing. Lack of any real support (with the exception of the other Matt; he's great) here or Abio, and so on.

It's been a while since I've dealt with Caddy since moving onto Nginx so I forget off the top of my head all the exact details of all the issues I was having now, but I've posted several times here about them so they'd be easy to dig up.

Caddy's simple syntax is nice when dealing with the caddyfile, but other than that in my own personal opinion it's just not ready for prime time. using linuxservers letsencrypt container has been a dream in comparison, and the config isn't really all that much more difficult to grasp. Perhaps if I ever need to at some point in the distant future, I'll revisit Caddy and see if it's irons out the issues.

**Comment by hangox** [comment]
Always build failed now. event i use docker builder
