### ISSUE TITLE
How to serve an "ongoing maintenance" page with a 503 HTTP status?

### ISSUE THREAD

**Issue by ngrilly** [mholt/caddy#260]
I'm looking into using Caddy to service an "ongoing maintenance" page. I need to return the same static page for all hosts and paths, with a 503 HTTP status code. Is there a way to achieve this with Caddy?

**Comment by mholt** [comment]
Good question. I'm not sure we've had that request before but I can see why it would be useful.

How about we add a third argument/parameter to `rewrite` which is a status code (similar to `redir`, except redir only allows you to set redirect status codes, 3xx).

```
rewrite {
    regexp .*
    to     /maintenance.html
    status 503
}
```

What do you think? Also @abiosoft

**Comment by ngrilly** [comment]
Adding a status parameter to the rewrite directive would make it, but I'm not a fan of having to use regexp when I just need to match every paths.

What would you think of something like the [return directive in nginx](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html)?

**Comment by mholt** [comment]
I suppose we could do something like this:

```
status /base_path 503
```

Or for all requests:

```
status 503
```

As for the regexp: the rewrite directive is designed to do exact matches without regexp because after some real use we found it more convenient and intuitive that way. I know splicing out to the next line to specify a catch-all regex isn't the most convenient but I don't know a better way to do it right now. ¯\_(ツ)_/¯ Any other thoughts?

I need to do some refactoring on Caddy's internals before we add more directives, but does that look better?

**Comment by abiosoft** [comment]
What I would prefer is to have a setting that checks if the maintenance page exists and serves it, otherwise it behaves normally.

How about an `offline` directive. If any of the pages exists, it displays it. 

```
offline [path] {
    page file1.html file2.html file3.html // in order of priority
    status 503
}
```

**Comment by ngrilly** [comment]
Another requirement is that most maintenance pages use external stylesheets or images. Every request must return a 503, except the stylesheets and images that must be served normally and return a 200. I realise my use case is not as simple as it sounds…

**Comment by ngrilly** [comment]
As for the `offline` directive` suggested by @abiosoft, it could be a good solution, but are you not afraid it's too much ad hoc?

**Comment by abiosoft** [comment]
My reason for suggesting that was simplicity and the directive name is self explanatory.

How about adding `allowed` and `blocked` which will be paths that are allowed and blocked during offline mode. And regarding the statuses, can serving static (css, js, images) files normally cater for that ?

I hope I am not making it too complex. :smile:

**Comment by mholt** [comment]
@ngrilly Okay, in that case:

```
rewrite {
    regexp .*
    to /maintenance.html
}
status /maintenance.html 503
```

Thus only the maintenance page gets a 503. (We'd have to be careful to put the status directive after rewrite in the middleware chain.)

**Comment by mholt** [comment]
Oh wait. I just realized that will rewrite the style sheets to maintenance.html too.

I'll come back to this after class, I have one more idea.

**Comment by mholt** [comment]
Thanks to @abiosoft, this should now be possible with the upgraded `rewrite` directive. (To be released this week in 0.8.1.)

**Comment by hubertbanas** [comment]
@abiosoft
Could you please provide the correct syntax for 503?

**Comment by jleclanche** [comment]
@mholt I'm sorry I missed this discussion! A common nginx pattern is to perform "does maintenance.html exist? if it does, return 503", and it seems it wasn't discussed.

An `exists` keyword would be a nice addition which would solve the problem in this space.

```Caddyfile
rewrite {
    r (.*)
    to /maintenance.html
    if exists /path/to/maintenance.html
}
status /maintenance.html 503
```

However it feels like the logic is the wrong way around. A better solution, imho:

```Caddyfile
status 503 {
    /
    if exists /path/to/maintenance.html
    body /path/to/maintenance.html
}
```

(I'm a little surprised that `status` doesn't yet support writing a body, but maybe I'm missing something from the docs)

**Comment by abiosoft** [comment]
This should work
```
rewrite {
    to /maintenance.html {path}
}
```

**Comment by jleclanche** [comment]
@abiosoft this will always rewrite, and will not correctly return a 503.

**Comment by abiosoft** [comment]
oh missed out the 503 part.

You want to write a body while still responding with 503 ?

**Comment by abiosoft** [comment]
This unfortunately won't include the body but does return 503 if maintenance.html exists.
```
status 503 /maintenance.html
rewrite {
    to /maintenance.html {path}
}
```

I think you have a good case for status returning body.
@mholt what do you think of other directives having access to the fileserver. So rather than processing the file themselves, the fileserver can be triggered instead.

There may be better ways around this but that is one that comes straight to my mind.

**Comment by mholt** [comment]
@abiosoft 

> what do you think of other directives having access to the fileserver. So rather than processing the file themselves, the fileserver can be triggered instead.

That's the idea behind #1649 - let the file server do the file serving.

**Comment by jleclanche** [comment]
@mholt any thoughts on the syntax [in my previous comment](https://github.com/mholt/caddy/issues/260#issuecomment-301409498)?

**Comment by mholt** [comment]
@jleclanche Yes, I did see it - I need to give it some thought because the scopes of redir, status, and rewrite is very delicately balanced... we need to be careful if status starts writing response bodies, for instance (is that what a status middleware should do?).

**Comment by mholt** [comment]
@jleclanche @abiosoft What if `status` simply controlled the status code but then passed the request through so whatever it wrote would write out with a status code as set by the directive?

**Comment by jleclanche** [comment]
How do you envision that working? You'd be passing 503 to the underlying app?

That kinda defeats the point of maintenance mode (which is usually pulled when the underlying app is unavailable for some reason).

**Comment by mholt** [comment]
@jleclanche Let's open a new issue to discuss this. Feel free to reference this one, but this one started in 2015 when Caddy was but a babe.

**Comment by jleclanche** [comment]
:) sure: #1707 for discussion on the feature

**Comment by andreasnuesslein** [comment]
I ended up solving it like this:
```
@hasMaintenance file /path/to/your/maintenance_file.html
handle @hasMaintenance {
    try_files /path/to/your/maintenance_file.html
    file_server {
        status 503
    }
}
```  
( https://stackoverflow.com/a/75736064/1518734 )

**Comment by mholt** [comment]
@andreasnuesslein Slightly less redundant:

```
@hasMaintenance file /path/to/your/maintenance_file.html
handle @hasMaintenance {
    rewrite * /path/to/your/maintenance_file.html
    file_server {
        status 503
    }
}
```

(`try_files` checks for file existence, but `file` already did that)

As can be seen in the linked issue, there are numerous ways to do this, but this works well if you place a file in your site root to indicate it's undergoing maintenance.
