### ISSUE TITLE
Documentation on http.proxy health_check_contains

### ISSUE THREAD

**Issue by folex** [mholt/caddy#2603]
I see there's a resolved issue #324 & the corresponding PR #1691 that enables users to check content body of the healthcheck response in the following fashion:
```
    proxy / :80 {
        health_check /path
        health_check_port 1234
        health_check_contains 'value you're looking for'
    }
```
But I can't seem to find information about this in the docs at https://caddyserver.com/docs/proxy

**Comment by mholt** [comment]
Oops, I missed that one. Will try to update it for the next site release

**Comment by mholt** [comment]
Done locally, will be pushed next time I update the site. Thanks!
