### ISSUE TITLE
Self-check before requesting certificate

### ISSUE THREAD

**Issue by moander** [mholt/caddy#2604]
I'm using Caddy in Kubernetes. It works great as long as the LoadBalancer is up. A new Kubernetes service will take a minute or two to become active. During this time Caddy will get itself banned. Also if the pod is restarted when there are problems with the LB it will get banned.

To solve this problem it would be great to have the possibility to do a self-check to see if Caddy is available from the outside world.

```
sub.mysite.com {
    selfcheck http://my-tester.com/test?callback=http://sub.mysite.com
}
```

The above example will instruct Caddy to call the selfcheck url and postpone the certreq until a 200 OK is returned.

**Comment by mholt** [comment]
I am not sure this can be done reliably.

(Also, please fill out the template next time; closing for lack of sufficient information.)

**Comment by tobya** [comment]
You can use the sandbox CA to help with testing which prevents caddy from getting banned.

https://caddyserver.com/docs/cli

https://letsencrypt.org/docs/staging-environment/
