### ISSUE TITLE
can't build http.filebrowser on arm64

### ISSUE THREAD

**Issue by xunni1000** [mholt/caddy#2605]
hi,

Direct link to download:
https://caddyserver.com/download/linux/arm64?plugins=http.filebrowser&license=personal&telemetry=off

500:
building caddy: exit status 1

**Comment by hacdias** [comment]
Hello @xunni1000! Unfortunately, we (File Browser) removed the support for Caddy. For more information and a way to keep using File Browser with Caddy, please see: https://github.com/filebrowser/filebrowser/issues/723
