### ISSUE TITLE
disable auto certificate renewal for specific domains or for all process

### ISSUE THREAD

**Issue by asafcombo** [mholt/caddy#2607]
## 1. What would you like to have changed?
I have a multi region aws setup. Currently within each region I keep the certificates in sync using an `NFS` (`efs`).

I started using it, because in each region we have tens of servers, and it we needed a centralized place to hold the certificate (and thus solving the **let's encrypt** api limit).

As I move some of the servers to a multi region deployment, I think of syncing the `main` efs with other regions efs. 

For those regions I want to disable the auto renew option. Again, I fear the due to the  **let's encrypt** api limit, some of the server's start ups will fail

**Comment by tobya** [comment]
Thanks for the issue.  

It may be worth discussing this a bit on https://caddy.community to get clarity on exactly the feature you are looking for.

**Comment by mholt** [comment]
Closing since the feature request template is not filled out with enough information. Feel free to open a topic on our forums if you merely want a discussion!
