### ISSUE TITLE
QUIC not working

### ISSUE THREAD

**Issue by TomDai** [mholt/caddy#2608]
## 1. Which version of Caddy are you using (`caddy -version`)?

`Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)`

## 2. What are you trying to do?

I'm trying to get QUIC to work.

## 3. What is your Caddyfile?
```text
tomd.ai {
        root /root/server/root
        gzip
        header / {
                Referrer-Policy "strict-origin-when-cross-origin"
                X-Content-Type-Options "nosniff"
                X-Frame-Options "SAMEORIGIN"
                X-XSS-Protection "1; mode=block"
                Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
                -Server
                -X-Powered-By
        }
        proxy /api localhost:3000
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy -quic`

## 5. Please paste any relevant HTTP request(s) here.

Go to `https://tomd.ai/` with Chrome.

## 6. What did you expect to see?

<img width="226" alt="image" src="https://user-images.githubusercontent.com/5054148/57588457-7c65fb80-74e2-11e9-89b7-99bd7ba47985.png">

## 7. What did you see instead (give full error messages and/or log)?

<img width="230" alt="image" src="https://user-images.githubusercontent.com/5054148/57588468-8687fa00-74e2-11e9-9da8-acc379a8fd96.png">

## Additional Information

QUIC is enabled in Chrome.
<img width="741" alt="image" src="https://user-images.githubusercontent.com/5054148/57588620-cb149500-74e4-11e9-8c89-54debbbd9378.png">

---

The HTTP response header includes:
`alt-svc: quic=":443"; ma=2592000; v="44,43,39"`

---

In Chrome's net export, I got:
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/5054148/57588533-9fdd7600-74e3-11e9-8b9f-89e29f0fa091.png">

---

When I launched Chrome in command line with `--origin-to-force-quic-on=tomd.ai:443` I got in Chrome's net export:
```
594: QUIC_SESSION
tomd.ai
...
t=3869 [st=2001]    QUIC_CONNECTION_MIGRATION_ON_PATH_DEGRADING
t=3869 [st=2001]    QUIC_CONNECTION_MIGRATION_FAILURE
                    --> connection_id = "f97c850919133835"
                    --> reason = "Migration on path degrading not enabled"
t=4122 [st=2254]    QUIC_SESSION_STREAM_FRAME_SENT
                    --> fin = false
                    --> length = 1024
                    --> offset = 0
                    --> stream_id = 1
t=4122 [st=2254]    QUIC_SESSION_PACKET_SENT
                    --> packet_number = 5
                    --> sent_time_us = 190331860165
                    --> size = 1350
                    --> transmission_type = 1
t=5869 [st=4001]    QUIC_SESSION_CONNECTION_CLOSE_FRAME_SENT
                    --> details = "No recent network activity."
                    --> quic_error = 25 (QUIC_NETWORK_IDLE_TIMEOUT)
t=5869 [st=4001]    QUIC_SESSION_PACKET_SENT
                    --> packet_number = 6
                    --> sent_time_us = 190333607161
                    --> size = 60
                    --> transmission_type = 0
t=5869 [st=4001]    QUIC_SESSION_CLOSED
                    --> details = "No recent network activity."
                    --> from_peer = false
                    --> quic_error = 25 (QUIC_NETWORK_IDLE_TIMEOUT)
t=5869 [st=4001]    QUIC_SESSION_CLOSED
                    --> details = "No recent network activity."
                    --> from_peer = false
                    --> quic_error = 25 (QUIC_NETWORK_IDLE_TIMEOUT)
t=5870 [st=4002] -QUIC_SESSION
```

---

With the command `lsof -i | grep caddy`, I got:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/5054148/57588573-4aee2f80-74e4-11e9-89d6-a18746856bd4.png">

---

**Comment by marten-seemann** [comment]
Which QUIC version is Chrome trying to speak?

**Comment by TomDai** [comment]
<img width="194" alt="image" src="https://user-images.githubusercontent.com/5054148/57620173-f84d5b80-7555-11e9-8e13-fea39b0ea68a.png">

@marten-seemann This is what I see when I go to google.com. So QUIC version 43?

**Comment by marten-seemann** [comment]
Can you please enable quic-go logging?

**Comment by TomDai** [comment]
Thank you @marten-seemann for following up.
I run the command `QUIC_GO_LOG_LEVEL=DEBUG caddy -quic -log caddy.log`, and got the log. 
I put the log in a Github Gist [here](https://gist.github.com/TomDai/46f0e7bc26bcc4732543c03626d7a455).

**Comment by marten-seemann** [comment]
Looks like QUIC is blocked on your path, only the Initial packet reaches the server.

**Comment by TomDai** [comment]
@marten-seemann Could you please suggest any way to look into the problem?

**Comment by TomDai** [comment]
Found the problem!
I am using DigitalOcean's Floating IP that points to the real IP. 
QUIC didn't work when the domain directed to the Floating IP, and it started to work when I changed it to direct to the real IP.
