### ISSUE TITLE
Build caddy from source error

### ISSUE THREAD

**Issue by suntong** [mholt/caddy#2609]
Following on https://github.com/mholt/caddy/issues/2560, which is _closed_ now, I tracked down to the very _latest_ solution, which should be:
https://github.com/mholt/caddy/issues/2560#issuecomment-484255220

And here is the quote of the relevant parts:

> . . . 
> 
> > If you want to build Caddy v0.11.5, you will have to use these instructions. (`GO111MODULE` should be set to `auto` - `export GO111MODULE=auto`)
> > 
> > 1. `go get github.com/mholt/caddy`
> > 2. `go get github.com/caddyserver/builds`
> > 3. `cd $GOPATH/src/github.com/mholt/caddy/caddy`
> > 4. `git checkout tags/v0.11.5`
> > 5. `go run build.go`

However, when I tried it, I got:

```
$ go get github.com/caddyserver/builds
# cd .; git clone https://github.com/caddyserver/builds /path/to/src/github.com/caddyserver/builds
Cloning into '/path/to/src/github.com/caddyserver/builds'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/caddyserver/builds: exit status 128
```

without it, when doing the next step, `go run build.go`, I'll get `build.go:41:2: cannot find package "github.com/caddyserver/builds" in any of ...` error. 

Thus, I'd like to know, what's the latest solution to build caddy from source?

PS. the above error is due to that https://github.com/caddyserver/builds no longer exist.

**Comment by mholt** [comment]
As you can see, those instructions are for an old version of Caddy.

Please use the build instructions in the README instead: https://github.com/mholt/caddy#build
