### ISSUE TITLE
Two (or more) spaces in filename or folder name issue

### ISSUE THREAD

**Issue by hdid** [mholt/caddy#261]
Hi matt
I have problem when using browse mode and if a file or folder contains more than one space in it's name. Then caddy just shows the name just with one space.
Is it possible that caddy shows the exact name for files (and folders)?

**Comment by mholt** [comment]
Hmm, I'm not having that issue. Can you provide more details or a screenshot of what you're seeing? The file names appear correctly for me (even files with more than one space).

**Comment by hdid** [comment]
I created one folder with name "test[SPACESPACE]files" and one file that is "net[SPACESPACESPACE]iso.txt" but you can see that there is just one SPACE on list

![issu1](https://cloud.githubusercontent.com/assets/3944323/10291931/4018a2a8-6bb9-11e5-8490-d202fac46c66.jpg)
![issu2](https://cloud.githubusercontent.com/assets/3944323/10292112/459b82d0-6bba-11e5-912f-b198eb40bc6d.jpg)

I tested with both Firefox and Opera browsers and the result is same

**Comment by mholt** [comment]
Oh, you mean *consecutive* spaces. Thank you for clarifying. That's makes sense, since HTML ignores extra whitespace. I've got my hands kind of full right now but maybe @pyed could take a look at this? Should be easy enough with one or two lines of CSS.

**Comment by mholt** [comment]
Thanks @pyed!

**Comment by hdid** [comment]
Thank you both @pyed @mholt

**Comment by hdid** [comment]
@mholt @pyed 
Hi
Your correction just applies to the names not title.
I created a folder with name "88[4SPACES]99":
![sp1](https://cloud.githubusercontent.com/assets/3944323/11302044/26ead7ea-8fb0-11e5-813a-860fb8887e7e.jpg)

But trim on title:
![sp2](https://cloud.githubusercontent.com/assets/3944323/11302086/7a2838da-8fb0-11e5-9642-d888fb65aec7.jpg)
