### ISSUE TITLE
Caddy keeps serving partial content to some requests

### ISSUE THREAD

**Issue by skorokithakis** [mholt/caddy#2610]
## 1. Which version of Caddy are you using (`caddy -version`)?

Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)

## 2. What are you trying to do?

A browser outside my network is trying to download a large file.

## 3. What is your Caddyfile?
```text
myhostname.com {
    root /home/user/htdocs
    log / /var/log/caddy/hostname.log "{remote} - {user} [{when}] \"{method} {uri} {proto}\" {status} {size} {request}"

    browse /stuff
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

```
sudo -Hu www-data /usr/sbin/caddy -agree=true -conf=/etc/caddy/Caddyfile -email=hi@stavros.io
```

## 5. Please paste any relevant HTTP request(s) here.

```
Log line: GET /video.mkv HTTP/2.0" 206 123797504

Request body:
GET /video.mkv HTTP/2.0
Host: myhostname.com
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.5
If-Match: "prf7f62qymb3d"
If-Unmodified-Since: Mon, 13 May 2019 02:11:30 GMT
Range: bytes=2672463872-
Te: trailers
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
```

## 6. What did you expect to see?

Caddy should have served the entire file. Instead, it seems to return a 206 after chunks of around 120 MB.

## 7. What did you see instead (give full error messages and/or log)?

Caddy serves a 206 with part of the file.

## 8. Why is this a bug, and how do you think this should be fixed?

I am not entirely sure, but I don't see anything in the request headers that could cause this. wget and my browser works well, but externally it fails. Would a forced connection close by some router cause caddy to return a 206?

## 9. What are you doing to work around the problem in the meantime?

I am having users resume a lot :/

**Comment by skorokithakis** [comment]
Sorry, I just saw this part in the log:

```
2019/05/13 19:10:02 [ERROR] failed to copy buffer:  context canceled
```

That was when the error ocurred.

**Comment by skorokithakis** [comment]
I saw this occur again without the download stopping immediately. The download stopped some time later without the error. Trying the request myself, it looks like Caddy does return a 200 if the client just drops the connection, so this might just be a client/ISP issue.

**Comment by skorokithakis** [comment]
This seems to be due to the client's network card, closing, sorry.

**Comment by mholt** [comment]
Fascinating though! Thanks for documenting this.

**Comment by lmeyerov** [comment]
@mholt  we're seeing this as well, either 1.0.0 or 1.0.1, haven't been able to reliably repro yet

**Comment by lmeyerov** [comment]
cc @skorokithakis  reopen?

**Comment by mholt** [comment]
@lmeyerov Is it reproducible? We can't do anything without a minimal reproducible test case.

**Comment by skorokithakis** [comment]
In my case, it wasn't Caddy's fault. If you're seeing this reliably from multiple clients, @lmeyerov, and can post a reproduction, then it might be Caddy's fault in your case.

**Comment by lmeyerov** [comment]
It's recurring, but difficult to reproduce. Any pointers for running caddy w/ heightened diagnostics?

**Comment by mholt** [comment]
@lmeyerov Depends what you need diagnostics on. Instead of filling up a closed issue, try asking on our [forum](https://caddy.community). :)
