### ISSUE TITLE
failed to build caddy

### ISSUE THREAD

**Issue by slavablind91** [mholt/caddy#2612]
caddy version: c238b72d5dbc97ea0075013e5fb2e516982d7bc9
Try to build caddy and got `cannot find package "github.com/lucas-clemente/quic-go/h2quic"` because package `github.com/lucas-clemente/quic-go/h2quic` doesn't exist

**Comment by mholt** [comment]
Not enough info. Please ask in our forums with more information: https://caddy.community

**Comment by wmark** [comment]
@slavablind91 You need to use Go's methods for modules to fetch dependencies. (Enable Go modules, optionally run `go mod download`.) That way the package will be reverted to a predefined version which has `h2quic`.

**Comment by slavablind91** [comment]
@wmark thanks

**Comment by wmark** [comment]
If you don't need anything special then this should do the trick:

```bash
cd "$(mktemp -d)"
mkdir caddy deps

# These lines or `git clone` from below to get the sources.
curl -fLRsS -o - "https://github.com/mholt/caddy/archive/v1.0.0.tar.gz" \
| tar -C caddy/ -xz --no-same-owner --strip-components=1

# git clone --depth=1 -o mholt "https://github.com/mholt/caddy.git"

cd caddy/ # formerly known as ~/go/src/github.com/mholt/caddy, the repo's root directory
(cd caddy/; env GOPATH="$(realpath ../deps)" GO111MODULE=on go build -o ../caddyserver)
```

The binary then is `caddyserver`, like in `./caddyserver -help`.

(You could cache directory `../deps` with its dependencies – or don't set GOPATH to use your usual one.)
