### ISSUE TITLE
Homebrew Caddy 1.0.0 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [mholt/caddy#2613]
Currently, I am trying to upgrade Caddy to 1.0.0. I did manage to fix the install step. But did not quite get test part working. 

Post the issue in here for some visibility in case some folks are interested.

Relates to https://github.com/Homebrew/homebrew-core/pull/39795

**Comment by tobya** [comment]
Hello @chenrui333  thank you for the issue.  Feel free to add further detail but I am going to close this now until there is better clarity on the issue.
