### ISSUE TITLE
Would you add tls-.dns.alidns DNS Providers plug-in ?

### ISSUE THREAD

**Issue by AkkunYo** [mholt/caddy#2616]
I find the code here but i dont know how to add it .I almost have no idea about golang [https://godoc.org/github.com/go-acme/lego/providers/dns/alidns](https://godoc.org/github.com/go-acme/lego/providers/dns/alidns).

**Comment by IceCodeNew** [comment]
Read before ask.
https://github.com/mholt/caddy/wiki/Plugging-in-Plugins-Yourself

**Comment by francislavoie** [comment]
For any future usage questions, please ask on https://caddy.community. This is the issue board for bugs and feature requests.
