### ISSUE TITLE
Proxy redirects don't seem to be rewriting the URL properly

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [mholt/caddy#2617]
## 1. Which version of Caddy are you using (`caddy -version`)?

```
5823dc22c1
```

## 2. What are you trying to do?

I'm trying to use [Invidious](https://github.com/omarroth/invidious) proxied with Caddy to the world, and the URLs don't seem to be rewriting properly.

See https://github.com/omarroth/invidious/issues/542 for more context.

## 3. What is your Caddyfile?
```text
myurl:2500

proxy /invidious localhost:3000

basicauth /invidious myusername mypassword

tls off (YES THIS IS INTENTIONAL)

```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

``caddy`` -- have Invidious running on port ``3000``

## 5. Please paste any relevant HTTP request(s) here.

N/A

## 6. What did you expect to see?

The URL be rewritten properly

## 7. What did you see instead (give full error messages and/or log)?

The URL gets "non-rewritten," and is sending requests to the server that should just be ``/``

## 8. Why is this a bug, and how do you think this should be fixed?

The URL seems to not be rewritten

## 9. What are you doing to work around the problem in the meantime?

N/A

## 10. Please link to any related issues, pull requests, and/or discussion.

https://github.com/omarroth/invidious/issues/542

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Because I've followed it since the beginning, and it's worked amazingly!

**Comment by whitestrake** [comment]
Howdy @ThatNerdyPikachu!

There's no rewriting going on in your Caddyfile at the moment. The `/invidious` part of the `proxy` directive is a base path, think of it like a filter that determines which requests go upstream. Even if it meets this base path, the entire URI gets sent to the upstream server, including the prefix `/invidious`.

If you want to remove the prefix, there's a `proxy` subdirective that does that:

```
proxy /invidious localhost:3000 {
  without /invidious
}
```

https://caddyserver.com/docs/proxy

**Comment by ThatNerdyPikachu** [comment]
Alright, [thank you!] I got the page loading (see https://i.pinged-b1nzy-for.fun/i/nl3aaahb.png
), but it's unstyled: https://i.pinged-b1nzy-for.fun/i/nl3aaahb.png, and the ``Login`` button, for example, takes me to ``/login``, instead of ``/invidious/login``

_Originally posted by @ThatNerdyPikachu in https://github.com/omarroth/invidious/issues/542#issuecomment-494197927_

**Comment by whitestrake** [comment]
Oh! Looking over that linked issue, it seems like you actually mean to proxy it into the subfolder.

I've written a bit about this problem in the past as it relates to Caddy. This post in particular has been seeing a bit of usage.

https://caddy.community/t/proxy-url-not-loading-site/5393/2

In short: Invidious needs to be able to set a Base URL / base path setting so that it accepts `/invidious` as a path prefix, OR you need to use a subdomain instead, OR you can try to get creative with Caddy's `http.filter` and proxy header rewriting (which can range from simple to extremely complicated).

**Comment by ThatNerdyPikachu** [comment]
Just a different thing, I tried doing what you mentioned in https://caddy.community/t/proxy-url-not-loading-site/5393/7, my Caddyfile is something like this:
```
subdomain.myurl {
...
}

anothersubdomain.myurl {
...
}
```
And it's saying that subdomain.myurl.. is an invalid directive.

Am I doing this wrong or something?

**Comment by whitestrake** [comment]
Caddy will do that if the braces aren't matched properly. You might be short one, perhaps one of your directives in the first site has a block missing its own closing brace?

**Comment by whitestrake** [comment]
I might just close this issue, too, because it doesn't look like it's a bug or anything, just help with configuration.

Feel free to keep fielding questions here in the closed issue, but the Caddy Community is the best place to get this kind of help.

**Comment by ThatNerdyPikachu** [comment]
alright.

yeah:
```
my-url:2500

subdomain.my-url:2500 { 
	proxy / localhost:3000
	basicauth / username password
}
```

```
Error during parsing: Unknown directive 'subdomain.my-url:2500'
```

**Comment by whitestrake** [comment]
Yeah, if you're putting in multiple sites, each site block _needs_ to be a block of its own.

Way it is now, it thinks the latter is a directive of the former.

You can just add an empty block - open a brace `{` on the end of the 1st line, and close the brace `}` on the beginning of the next line.

**Comment by ThatNerdyPikachu** [comment]
@whitestrake Alright, last thing I'll ask you, but is there a way to share ``http.login`` and ``http.jwt`` logins across subdomains?

**Comment by francislavoie** [comment]
@ThatNerdyPikachu you can use the snippets feature to copy the same blocks between site definitions: https://caddyserver.com/docs/caddyfile#snippets

But otherwise, that would be a question for the plugin authors (https://github.com/tarent/loginsrv and https://github.com/BTBurke/caddy-jwt) if you need that feature.
