### ISSUE TITLE
Can't download caddy from Downloads page

### ISSUE THREAD

**Issue by khanhicetea** [mholt/caddy#2623]
## 1. Which version of Caddy are you using (`caddy -version`)?

1.0

## 2. What are you trying to do?

Customize and download binary from Downloads page

## 5. Please paste any relevant HTTP request(s) here.

```https://caddyserver.com/download/linux/amd64?plugins=hook.service,http.cache,http.cors,http.expires,http.filter,http.geoip,http.git,http.ipfilter,http.nobots,http.realip,tls.dns.cloudflare&license=personal&telemetry=off```

## 6. What did you expect to see?

Could download binary

## 7. What did you see instead (give full error messages and/or log)?

<img width="512" alt="Screen Shot 2019-05-24 at 10 38 23" src="https://user-images.githubusercontent.com/4528223/58301298-1b0e2880-7e10-11e9-9b7a-a806dc4685c5.png">

**Comment by bendem** [comment]
Duplicate of #2583

**Comment by khanhicetea** [comment]
Sorry, I close this
