### ISSUE TITLE
Add .wasm to defaultExtensions

### ISSUE THREAD

**Issue by lukenowak** [mholt/caddy#2625]
## 1. What would you like to have changed?

I'd like to add .wasm to defaultExtensions, which would result with compressing content of .wasm files.

## 2. Why is this feature a useful, necessary, and/or important addition to this project?

.wasm files are big and can be compressed, resulting with their smaller size and so faster downloads.

## 3. What alternatives are there, or what are you doing in the meantime to work around the lack of this feature?

The alternative is to repeat defaultExtensions in configuration file like:
```
gzip {
  ext "", ".txt", ".htm", ".html", ".css", ".php", ".js", ".json",
        ".md", ".mdown", ".xml", ".svg", ".go", ".cgi", ".py", ".pl", ".aspx", ".asp", ".m3u", ".m3u8", ".wasm"
}
```

## 4. Please link to any relevant issues, pull requests, or other discussions.
https://github.com/mholt/caddy/pull/2624

**Comment by lukenowak** [comment]
.wasm binaries gain from compression (https://rustwasm.github.io/docs/book/game-of-life/code-size.html)

**Comment by mholt** [comment]
Thanks for the PR!
