### ISSUE TITLE
Can http.header option control all plugins response header?

### ISSUE THREAD

**Issue by naiba** [mholt/caddy#2627]
I use both proxy and cache plugin.  
but now I have to set header control option each plugin to the contronl response from the same origin server.  
```
proxy {
    header x y
}
cache {
    header x y
}
```
Why don't modify the final response header in `http.header` option?  
The author of the cache plugin @nicolasazrak  thinks this is a caddy design issue and is not willing to merge [my pull request](https://github.com/nicolasazrak/caddy-cache/pull/36).

**Comment by mholt** [comment]
FWIW, this is now resolved in Caddy 2.

**Comment by naiba** [comment]
@mholt Hello, resolved by which commit?

**Comment by mholt** [comment]
It's not published yet, but will be later.

I'm still not sure how/if this issue is actually in Caddy itself; if so, feel free to re-open with a proper issue template.
