### ISSUE TITLE
Can compile it (v1.0.0_windows_386) for users who use scoop tool?

### ISSUE THREAD

**Issue by huiyifyj** [mholt/caddy#2628]
👋 Caddy 1.0 is released. But there is no corresponding windows_386 file in the `assets` list.

## Why is this feature a useful, necessary, and/or important addition to this project?

Compiling it for windows x86 maybe add a little maintenance time.
For those who use [`scoop`](https://github.com/lukesampson/scoop) to manage windows software, scoop will download caddy from [github releases page](https://github.com/mholt/caddy/releases).

https://github.com/ScoopInstaller/Main/blob/de887c2fe25abd757c960caec8ad6c9ade24f4fe/bucket/caddy.json#L26

**Comment by huiyifyj** [comment]
Sorry, I used the wrong issue template rashly.
And cause to be added `feature request` label.

**Comment by mholt** [comment]
(No worries, about the label.)

I'm not really interested in supporting 32-bit Windows by default (the number of downloads for that platform justifies this decision) but you are welcome to compile it yourself!

**Comment by huiyifyj** [comment]
Thanks for your reply.
