### ISSUE TITLE
Disable Go's default MIME sniffing behavior

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#2629]
By default, Go sniffs the MIME type if the Content-Type is not set on the response: https://github.com/golang/go/blob/1531192272dfdebc61050a8dafa626ff4b36b3a4/src/net/http/fs.go#L193-L209

We should prevent this in all cases.

Caddy 2 will definitely take care of this; not sure if we'll work this into Caddy 1 yet.

See also https://github.com/golang/go/issues/24513

**Comment by mholt** [comment]
This is done in Caddy 2. Might still work it into Caddy 1, if there's a need for this that for some reason can't wait until Caddy 2, let me know.

**Comment by warsix4** [comment]
Was this ever added to Caddy 1?

**Comment by mholt** [comment]
No, Caddy 1 is mostly done except for critical issues at this point. Turning off MIME sniffing would be a breaking change anyway.
