### ISSUE TITLE
Dynamically-rendered 'static' pages lack some response headers

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#263]
Pages that are rendered by the templates middleware (and I'm sure there are others) don't add some basic response headers, namely `Last-Modified` and `Content-Length`. True static files do have those headers because they are served by net/http's ServeContent function. But the templates handler, for example, takes a static file, executes the template in memory, then writes the resulting bytes to the response without ServeContent, thus neglecting those headers.

When serving what the client thinks is a static file or resource, the Last-Modified header should exist and contain the last modified timestamp of the file on disk.

For _all_ requests, I think, the Content-Length header should exist. (Unless the Content-Length is genuinely not known, but I can't think of a case right now where we don't know its length.)

**Comment by Makpoc** [comment]
You can it in progress. I'm on it.

**Comment by mholt** [comment]
Thanks to Bisser for the PR -- this is fixed; turns out Content-Length header missing is not a bug in the cases I mentioned.
