### ISSUE TITLE
Caddy is serving up wrong website?

### ISSUE THREAD

**Issue by sarahzimmies** [mholt/caddy#2634]
I apologize - not a developer, but am stuck trying to solve this issue. I will try to use the proper language, but forgive me for using any terminology incorrectly. 

I have double-checked the directories, and the sites each have their correct assets, however, caddy is serving up the wrong site assets (at the proper URL) - if that makes sense.

How do I solve this?

**Comment by magikstm** [comment]
What is your entire caddyfile?

**Comment by tobya** [comment]
I am closing this as it is impossible to look at unless the entire caddyfile is provided.

**Comment by mholt** [comment]
Thanks. (We've been in contact via email.)
