### ISSUE TITLE
Medium http.webdav doc bug

### ISSUE THREAD

**Issue by hartzell** [mholt/caddy#2640]
The docs for http.dav on the website (https://caddyserver.com/docs/http.webdav) say this:

> ## Custom Scope
> ```
> webdav {
>       scope /
> }
> ```
>
> WebDAV on /admin for the whole file system.

which doesn't quite make sense.

The "Full documentation" (https://github.com/hacdias/caddy-webdav/blob/master/README.md) says this instead:

> ```
> webdav /admin {
>     scope /
> }
> ```

which makes more sense.

**Comment by mholt** [comment]
Thanks for the report, but please open this with the plugin author so they can fix it; this has nothing to do with Caddy.

**Comment by hartzell** [comment]
Are you sure about this?  I'm not clear on how the documentation **on the Caddy web site** gets there, but the author's github README.md is correct. 

The typo/bug **is here https://caddyserver.com/docs/http.webdav**.

**Comment by mholt** [comment]
Yes, please read the page:

> This plugin is independent of the Caddy project and is not endorsed or maintained by Caddy developers. Use at your own risk. Do not file issues for this plugin on Caddy's bug tracker.

**Comment by magikstm** [comment]
@hacdias could you please review the plugin page and fix the issue?
