### ISSUE TITLE
Failed to request client certs with multiple addresses

### ISSUE THREAD

**Issue by shouya** [mholt/caddy#2641]
## 1. Which version of Caddy are you using (`caddy -version`)?

```
Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)
```

## 2. What are you trying to do?

Enable client cert verification for multiple addresses.

## 3. What is your Caddyfile?
```text
$ cat Caddyfile

(tls) {
  tls webmaster@namunamu.com {
    dns cloudflare
    clients verify_if_given /etc/certs/ca/certs/ca.crt
  }
}

namunamu.com {
  import tls
}
namunamu.com/var/ {
  import tls
}
```

## 4. How did you run Caddy (give the full command and describe the execution environment)?

```
env CLOUDFLARE_EMAIL=<REDACTED> CLOUDFLARE_API_KEY=<REDACTED> caddy -agree
```

## 5. Please paste any relevant HTTP request(s) here.

skipped

## 6. What did you expect to see?

```
Activating privacy features... done.

Serving HTTPS on port 443
https://namunamu.com
https://namunamu.com/var/


Serving HTTP on port 80
http://namunamu.com
http://namunamu.com/var/
```

## 7. What did you see instead (give full error messages and/or log)?

```
Activating privacy features... done.
incompatible TLS configurations for the same SNI name (namunamu.com) on the same listener: multiple hosts requiring client authentication ambiguously configured
```

## 8. Why is this a bug, and how do you think this should be fixed?

I think the tls config compatibility detector may have flaw in it. I'm not familiar with the code base/architecture so it's just my guess.

## 9. What are you doing to work around the problem in the meantime?

I use a subdomain instead of a path for the particular block. i.e. replace `namunamu.com/var/` with `var.namunamu.com`. But it doesn't solve the problem.

## 10. Please link to any related issues, pull requests, and/or discussion.

This issue (https://github.com/mholt/caddy/issues/2251) may be related, but the situations we stuck with are different.

## Bonus: What do you use Caddy for? Why did you choose Caddy?

Less boilerplate config than nginx - ideal for personal projects!

**Comment by mholt** [comment]
Hm, indeed, this is a weird edge case, because there's not really a great way to know that the two sites have the _exact_ same TLS configuration, since their underlying CA pools are different pointers. We _could_ do some deeper inspection but it would be somewhat complex I think. Still, if someone wants to find a simple and elegant solution, we'd welcome a PR!

**Comment by shouya** [comment]
Sorry I don't quite get it.

To me it looks from the source (https://github.com/mholt/caddy/blob/master/caddytls/config.go#L391) that at least one of `ClientAuth` or `ClientCAs` must have mismatched between the two sites. But it doesn't look like it's the case since they all have exactly the same tls config.

**Comment by mholt** [comment]
@shouya The pointers to the underlying CA pools are different, even if their contents are the same.

**Comment by shouya** [comment]
@mholt: I see. So ClientCerts is not really an array of strings as the paths to the CA certs but rather pointers to the CA pools (https://github.com/mholt/caddy/blob/master/caddytls/config.go#L238). In this case I can see it would be a bit tricky.

I'll see if I can fix it - but don't take it as a guarantee 😏

**Comment by mholt** [comment]
One option to consider would be to use the same cert pool for the same configuration, (i.e. don't call NewCertPool when the contents are the same as an existing one) but that might be more complex. Or not, if you find a clever/elegant way to do it. Or, just writing a `Equal()` function to compare two CertPools might be effective, if there's enough information exposed externally.

**Comment by shouya** [comment]
I submitted a pull request (#2648) to fix the problem. It basically just checked the file names instead of CA pool pointers.
