### ISSUE TITLE
Goroutine leak in caddytls NewConfig

### ISSUE THREAD

**Issue by jaredririe** [mholt/caddy#2642]
## Which version of Caddy are you using?

tags/v1.0.0

## What are you trying to do?

This bug reproduces when I instruct Caddy to reload the Caddyfile multiple times before the final shutdown. A goroutine leaks each time I send the `SIGUSR1` signal. 

## What is your Caddyfile?

```text
:33000 {

    pprof

    prometheus

    timeouts {
        idle 4m
        header 2m
    }

}
```

## Please paste any relevant HTTP request(s) here.

If I send several `SIGUSR1` signals to Caddy and then look at the number of goroutines, I see that there is a leak:

```
curl "localhost:9180/debug/pprof/goroutine?debug=1"
```

```
10 @ 0x403172f 0x4007f7a 0x4007f50 0x4007c7b 0x449270b 0x405ed21
#	0x449270a github.com/mholt/caddy/caddytls.NewConfig.func2+0x8a	github.com/mholt/caddy/caddytls/config.go:145
```

## What did you expect to see?

I expected to see a single goroutine for the `NewConfig` function. 

## Why is this a bug, and how do you think this should be fixed?

This is a bug for those for which Caddy is long running and reloads the configs many times throughout its execution. The number of goroutines could easily grow to thousands if an automated event triggered a Caddyfile reload. 

--- 

I have made the following code change (in caddy/caddytls/config.go) to resolve this bug and will happily make a pull request.

```go
storageCleaningTicker := time.NewTicker(12 * time.Hour)
done := make(chan bool)
go func() {
	for {
		select {
		case <-done:
			storageCleaningTicker.Stop()
			return
		case <-storageCleaningTicker.C:
			certmagic.CleanStorage(certmagic.Default.Storage, certmagic.CleanStorageOptions{
				OCSPStaples: true,
			})
		}
	}
}()
inst.OnShutdown = append(inst.OnShutdown, func() error {
	certCache.Stop()
	done <- true
	close(done)
	return nil
})
```

**Comment by mholt** [comment]
Ah, thanks. Yeah, please open a PR and we'll be happy to accept it. (FWIW, this isn't a problem in Caddy 2, but we'll still fix this in Caddy 1.)
