### ISSUE TITLE
[RELATED] 500 Internal Server Error when submitting a new build on the Develop Portal 

### ISSUE THREAD

**Issue by dhaavi** [mholt/caddy#2646]
I wasn't sure how to raise this issue correctly. As it is related to the development and release cycle of caddy plugins, I thought I might very well raise this here.

Every time I deploy a new version on the Dev Center, I get the message that the build has been submitted. Then I press the OK button, and get redirected to a page that returns `500 Internal Server Error`.

I guess you have logs, but I can try things if you need more information.

**Comment by dhaavi** [comment]
Clicking on the `Details` or `Edit` buttons on the dashboard also results in a `500 Internal Server Error`.

**Comment by mholt** [comment]
@dhaavi Thanks, your plugin revealed an obscure bug. I _think_ I've fixed it. Could you try again?

**Comment by dhaavi** [comment]
It works!
