### ISSUE TITLE
Can’t verify after using the filter

### ISSUE THREAD

**Issue by ps2xu** [mholt/caddy#2654]
## 1. Which version of Caddy are you using (`caddy -version`)?
Caddy v1.0.0 (h1:KI6RPGih2GFzWRPG8s9clKK28Ns4ZlVMKR/v7mxq6+c=)
## 2. What are you trying to do?
I can’t verify after using the filter on my website, directly prompting 401 Unauthorizd, no dialog box. And I don’t want to delete the verification, thank you.
[https://caddy.community/t/help-me-about-filter-problem-thanks/5886](https://caddy.community/t/help-me-about-filter-problem-thanks/5886)
## 3. What is your Caddyfile?
```text
https://www.*****.com {
root /usr/local/caddy/www
tls xxx@xxxxx.com
basicauth / 123 456
timeouts none
gzip
filter rule {
content_type text/.*
search_pattern xxxxx/images/
replacement xxxxx/gooimg/
}
}
```
## 4. Please paste any relevant HTTP request(s) here.

-------------------with filter---------------------
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Server: Caddy
X-Content-Type-Options: nosniff
Date: Thu, 27 Jun 2019 00:43:54 GMT
Content-Length: 17

-------------------------After remove the filter--------------------
HTTP/1.1 401 Unauthorized
Content-Type: text/plain; charset=utf-8
Server: Caddy
Www-Authenticate: Basic realm=“Restricted”
X-Content-Type-Options: nosniff
Date: Thu, 27 Jun 2019 01:21:20 GMT
Content-Length: 17

**Comment by mholt** [comment]
This appears to be an issue with a third-party plugin (and the bug report template was not filled out completely); closing in favor of the duplicate issue opened in another repo.
