### ISSUE TITLE
Data races in websocket middleware

### ISSUE THREAD

**Issue by garyburd** [mholt/caddy#277]
How to reproduce:

1. Build caddy with -race enabled.
2. Run caddy with configuration from the readme:

        localhost

        gzip
        browse
        ext .html
        websocket /echo cat
        log ../access.log
        header /api Access-Control-Allow-Origin *

3. Run this client application:

        package main

        import (
            "log"
            "time"

            "github.com/gorilla/websocket"
        )

        func main() {
            c, _, err := websocket.DefaultDialer.Dial("ws://localhost:2015/echo", nil)
            if err != nil {
                log.Fatal("dial:", err)
            }
            defer c.Close()

            go func() {
                defer c.Close()
                for {
                    _, message, err := c.ReadMessage()
                    if err != nil {
                        log.Println("read:", err)
                        break
                    }
                    log.Printf("recv: %s", message)
                }
            }()

            ticker := time.NewTicker(time.Second)
            defer ticker.Stop()

            for t := range ticker.C {
                err := c.WriteMessage(websocket.TextMessage, []byte(t.String()))
                if err != nil {
                    log.Println("write:", err)
                    break
                }
            }
        }

Result: Race detector prints warnings.
Expect: No warnings.

I suggest using the code from Gorilla's new [command example](https://github.com/gorilla/websocket/tree/master/examples/command#readme).

**Comment by acmacalister** [comment]
@garyburd Thanks. I didn't think to run the race detector when writing it. Sounds good. Can't argue with free example code. :smile: I will try it get that fixed shortly.

**Comment by mholt** [comment]
Gary, thanks for the detailed report _and_ the helpful command example!

(Memo to self: Add race detector to CI tests.)

**Comment by garyburd** [comment]
I'd like to point out a difference between my example and the x/net/websocket version of the caddy middleware: My example assumes that lines of text correspond to websocket messages. The line terminator is not included in the message. The x/net/websocket version assumes that messages form a stream of bytes. Message boundaries have no meaning.

The websocketd server also splits messages at line boundaries.

It should be easy to modify my example to match the x/net/weboscket version of the caddy middleware.

**Comment by acmacalister** [comment]
@mholt @garyburd I think I got all the races taken care of. Running it with race detector no longer prints any errors, so that is a plus. :smile:

@garyburd in regard to your last comment, Instead of using Scan like in the example, do you think we should just read up to the next newline and then send that as a message as opposed to each line from the current scanner as it is currently setup? I did a quick look through websocketd code and that appears to me how they are handling it...

PR is #306 if you either of you would like to take a look at it.

**Comment by garyburd** [comment]
The websocketd code reads to the next newline, trims line terminators and sends the result.  Use Scan. It does the same thing with less application code.

**Comment by acmacalister** [comment]
@garyburd sounds good. That's what I will do then. :+1:
