### ISSUE TITLE
Set 0.0.0.0 as default host rather than localhost

### ISSUE THREAD

**Issue by j-mcnally** [mholt/caddy#28]
It would be nice and simplify setup for users on heroku / docker, to just listen on 0.0.0.0 by default.

As pointed out by @mholt this won't break anything for users expecting localhost, and they can choose to explicitly bind to localhost

It would also be nice to accept default host via cli, `-host`

**Comment by mholt** [comment]
I'm pushing these two changes now:

- Default host is now 0.0.0.0
- `-host` flag to override it

Will be included in next patch release.

**Comment by j-mcnally** [comment]
You the man @mholt
