### ISSUE TITLE
OCSP Stapling

### ISSUE THREAD

**Issue by jsha** [mholt/caddy#280]
Hi! I saw you are working on Let's Encrypt integration. That's awesome, thank you!

I wanted to file an issue requesting OCSP stapling support.

From Let's Encrypt's perspective, the more of our subscribers use OCSP stapling, the lower our bandwidth costs. There are also performance and privacy benefits to end users, since data doesn't get sent to a third party.

There are also two big future functionality wins from implement OCSP Stapling:
 - Now that OCSP Must Staple ([TLS Feature](https://tools.ietf.org/html/rfc7633)) is standardized, OCSP stapling is a path to issuing certs where revocation actually works.
 - One of the ways to include a [CT](http://www.certificate-transparency.org/) log proof is via OCSP stapling.

Anyway, great project, I'm looking forward to trying it out.

**Comment by mholt** [comment]
Glad you brought this up. That's a great reason to implement this now. We're on it!

**Comment by xenolf** [comment]
Support for OCSP Stapling landed on the letsencrypt branch in 91465d8e6f33af94655abe50be0e38aae9db667c.

**Comment by jsha** [comment]
Wow, y'all are fast!
