### ISSUE TITLE
Let's Encrypt integration status

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#284]
Tasks done or still to do **before** Let's Encrypt integration will be ready for beta testing (in no particular order):

- Adapt `tls` Caddyfile directive to accommodate Let's Encrypt
  - [x] Email address with `tls my@mail.com`
  - [x] Force plaintext HTTP with `tls off`
- Command line flags/arguments
  - [x] `-email` for default email address
  - [x] `-agree` to agree to Let's Encrypt Subscriber Agreement (SA)
  - [x] `-revoke` to revoke a certificate
  - [x] `-ca` for custom CA URL
- [x] Prompt user if SA is updated (might be hard-coded for beta)
- [x] Use HTTPS by default
- [x] Issue certificates at startup
- [x] Persist certificate and user information to disk
- Certificate renewal
  - [x] Auto-renew
  - [x] Update TLS listener to use renewed cert (requires graceful restart)
  - [x] Robust failover (try again if renewal fails)
- [x] OCSP
- [x] Check for OCSP updates every ~hour (see [these comments](https://github.com/mholt/caddy/commit/91465d8e6f33af94655abe50be0e38aae9db667c#commitcomment-13966080))
- [x] Certificate bundling

This list will be updated as we go. Using [xenolf/lego](https://github.com/xenolf/lego) as client library.

Feel free to comment if you have any questions or suggestions or would like to help!

**Comment by coolaj86** [comment]
How about issuing certificates dynamically based on hostname? Or at least making the code decoupled enough so that can be fixed later?

**Comment by mholt** [comment]
@coolaj86 Ah yes, I haven't forgotten your issue #188 :) This LE work should be orthogonal to your feature request. If it doesn't make it in by our first LE release then it will be next on the list. :+1:

**Comment by coolaj86** [comment]
Another little thing to keep in mind: if the server is one of many behind some kind of proxy there needs to be some sort of hook (even to a bash script) that passes the token domain name as an argument.

By 'token' I mean `jumblejumblejumble.acme.invalid`.

**Comment by mholt** [comment]
Things to work on **during** the beta period:

- [ ] Clean up logging and get it more organized
- [ ] Propose change to ACME spec to make ToS URL available before performing an action
- [ ] More customization of LE integration from Caddyfile

This list will also be updated as we go.

**Comment by mholt** [comment]
Feature-complete for beta. Will open a new issue to track that progress separately.
