### ISSUE TITLE
PHP + SQL examples?

### ISSUE THREAD

**Issue by jordanlev** [mholt/caddy#288]
The docs mention that it's possible to run PHP scripts with caddy server, but I don't see an actual explanation of how to do so. Also, how would one make this work with a separate SQL database server (MySQL or Postgres)? Basically I'm asking "how can I recreate the functionality of MAMP/WAMP/XAMPP using Caddy?".

Thanks, this looks like a great project!

**Comment by mholt** [comment]
There's an example right on the homepage. Basically it can front PHP apps like nginx can through FastCGI:

```
fastcgi /blog localhost:9000 php   # PHP backend
```

Caddy doesn't have anything to do with MySQL, so your PHP app will still connect to the MySQL port to use it.

If you like dynamic sites, you might be interested in the [lua add-on](https://github.com/caddyserver/caddy-lua) we're experimenting with. You can check out the .html file -- it would enable you to create a PHP-like dynamic site but with Lua, and executed entirely in-process, so no extra things to configure.

**Comment by jordanlev** [comment]
Thanks for the info. As someone who is not super knowledgeable about server stuff, I'm unfamiliar with running it as a separate process from the web server (apache 99% of the time for me) -- so this helps clarify the situation for me.

**Comment by mholt** [comment]
We're definitely trying to make things like this easier (although with PHP it's pretty limited what we can do; unfortunately it's a very complex language and no such interpreter exists in Go -- otherwise I'd put it all in-process making it very very easy to use). Thanks for your question!
