### ISSUE TITLE
Global directives

### ISSUE THREAD

**Issue by pierrebeaucamp** [mholt/caddy#291]
Hi,

I'm looking for a way to set directives for multiple servers at once. I was thinking of something like this:

````
0.0.0.0:80
gzip

example.com {
    root /var/www/example.com
}

foo.bar {
    root /var/www/foo.bar
}
````

Basically, I don't want to repeat common settings like `gzip` for every host.
I'm sorry if this is already possible and I'm just missing something. 

Best Regards

**Comment by mholt** [comment]
Right now, you'll have to specify it for each host, but this may change in the future. (Also, it's quite possible we'll enable gzip by default in the future anyway.)

If there's a batch of directives that you need to share, there's the [import](https://caddyserver.com/docs/import) directive that may help a bit.

**Comment by pierrebeaucamp** [comment]
I didn't know about `import`, but that's exactly what I was looking for. Thanks.
