### ISSUE TITLE
Markdown table support

### ISSUE THREAD

**Issue by tonka3000** [mholt/caddy#294]
Hey,

is there an support for an markdown table like f.e.

    | Tables   |      Are      |  Cool |
    |----------|:-------------:|------:|
    | col 1 is |  left-aligned | $1600 |
    | col 2 is |    centered   |   $12 |
    | col 3 is | right-aligned |    $1 |

This should look like this (thx to github-markdown rendering)

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

I can create an table with inline html, but it's not easy to read for a markdown writer.

Is there any support for that in caddy?

I use the latest  version of caddy on a Windows 7 x64 machine (prebuild binary from the caddy website)

Thanks in advance
Tonka

**Comment by mholt** [comment]
Caddy can support this. We just need to enable that extension in the renderer.

While we're at it, any others you'd like to see enabled by default? https://godoc.org/github.com/russross/blackfriday#pkg-constants -- scroll down to the second list, with all the constants prefixed with `EXTENSION_` -- and let me know what you think would be useful to everyone.

**Comment by tonka3000** [comment]
> Caddy can support this. We just need to enable that extension in the renderer.

Can i activate that in the caddyfile or is it only possible in golang code itself?

> While we're at it, any others you'd like to see enabled by default? https://godoc.org/github.com/russross/blackfriday#pkg-constants -- scroll down to the second list, with all the constants prefixed with EXTENSION_ -- and let me know what you think would be useful to everyone.

I think it is easier with an testsite and so i've upload my markdown [testpage](https://github.com/tonka3000/markdowntest/blob/master/index.md). The page contains the markdown command which i regularly use and you can see how github render it. Mostly i write markdown with atom, it would be nice when caddy has this features activated by default.

btw: caddy is extrem cool, i like the idea. good job :+1:

**Comment by mholt** [comment]
> Can i activate that in the caddyfile or is it only possible in golang code itself?

We'll have to change the code. As a user, you shouldn't have to worry about these minutia IMO.

Thanks for your test file! I'll use it to enable some extensions for the next release.

**Comment by mholt** [comment]
I've enabled tables, fenced code blocks, and strikethrough for the next release. It renders the test page as expected.

Great suggestion - thanks!

**Comment by tonka3000** [comment]
> We'll have to change the code. As a user, you shouldn't have to worry about these minutia IMO.

No problem, i've clone your repo and build the lastest master (which is easy because caddy has no dependecies :smile:  ). Works perfect. The code syntax highlighting does not work, but thats a nice to have feature - but that's a different issue :wink: 

> Thanks for your test file! I'll use it to enable some extensions for the next release.

no problem. I have to thank you for such an great application.

**Comment by mholt** [comment]
Code highlighting is actually enabled in the rendered markup, but for now we're leaving it up to the user to provide styling via a template or the `css` property.

Thanks for the compliment, and the feedback!

**Comment by tonka3000** [comment]
hmm, the problem is that my converted html code does not contain any tags/classes to style it. Only the "main"-tag has a class

Here is my example
```
var a = 1;
function foo(){

}
```

Here is my converted html code segment build from the javascript code block:
```html
<pre><code class="language-javascript">var a = 1;
function foo(){

}
</code></pre>
```

If have a little python3 script which use markdown and pygments to create the html code which look like ...
```html
<div class="codehilite"><pre><span class="kd">var</span> <span class="nx">a</span> <span class="o">=</span> <span class="mi">1</span><span class="p">;</span>
<span class="kd">function</span> <span class="nx">foo</span><span class="p">(){</span>

<span class="p">}</span>
</pre></div>
```
Here i can style my code.

Did you get an different result?

**Comment by mholt** [comment]
Why use a python script? Just use something like [highlight.js](https://highlightjs.org/) to do syntax highlighting.

**Comment by tonka3000** [comment]
The python script is my old custom markdown to html converter - has nothing to do with caddy, it was only for comparison.

I will give highlight.js a try.

**Comment by severak** [comment]
Thanks for enabling tables in next version. Also would be nice when markdown extensions/profiles can be configurable in some next version.

**Comment by justintan** [comment]
I pull the latest code. Still not working. Is there configuration to be set? 

|name|age|  
|----|----|  
|Tom|18|

**Comment by mholt** [comment]
Nope, it should just work.
