### ISSUE TITLE
browse and fastcgi

### ISSUE THREAD

**Issue by sinky** [mholt/caddy#297]
Hello,
awesome project thank you.
If i request each file directly, each file is correctly handled. But if i request `http://localhost:81/` or `http://localhost:81/folder/` for dir indexing i get "No input file specified." from php. 

I'm at Windows 7 x64 with newest PHP 5.6.14 x64

``` 
0.0.0.0:81 {
  root www/
  browse /
  fastcgi / 127.0.0.1:9123 php
}
```

Root Dir Content:
* /phpinfo.php
* /test.html
* /folder/
* /folder/test.html

**Comment by mholt** [comment]
Hmm, I wonder if using browse and fastcgi for the same base path isn't compatible. The fastcgi middleware is seeing that /folder/ is a directory so it handles it before browse can have a chance to access it.

To make sure I understand, what are you trying to accomplish by using browse and fastcgi together? (I admit it's the first time I've seen them used with the same base path.)

**Comment by sinky** [comment]
Hmm, i wonder why not. Shouldn't the fastcgi only be triggered with the right Extension at the end?

I try to get the same behavior like Apache.

**Comment by mholt** [comment]
Yes, that's definitely what you would expect.

PHP is hard.

The fastcgi middleware actually looks to see if the URL (within the base path) ends with `/`, indicating a directory. If it does, it passes the request to the fastcgi server, so (presumably) PHP can handle it. This is important for applications like wordpress that serve pages that end with a forward slash. IMO that's bad engineering but that's how it is.

If the URL matches the base path, this condition must evaluate to true in order to be passed to PHP:

```go
// fpath is the path portion of the request
// h.exists tells whether the file that is being requested exists on the file system
if fpath[len(fpath)-1] == '/' || strings.HasSuffix(fpath, rule.Ext) || !h.exists(fpath) {
    // proxy to fastcgi
}
```

We found that this was similar to how nginx does its rewrites and forwarding rules for most PHP sites.

How would you recommend fixing this?

**Comment by sinky** [comment]
I understand, but it should forward the request only for non existent folders. I think nginx or Apache do the Same. 

Like so. (Copied & Paste on Phone)

!h.exists(fpath) && ( fpath[len(fpath)-1] == '/' || strings.HasSuffix(fpath, rule.Ext) )

**Comment by mholt** [comment]
Impressive work on your iPhone! :wink:

**Comment by mholt** [comment]
Impressive work on your iPhone! :wink: I think that's a good idea. Will work that in soon.

**Comment by mholt** [comment]
@sinky Do you have Go installed? I'd like you to try this fix when you have a chance. I can send you a binary or you can build it from source (`go run main.go` should do).

**Comment by sinky** [comment]
Hi, thank you. 😉
A Binary would be nice.

**Comment by mholt** [comment]
@sinky Good attempt :smile: Not sure what is going on, it's possible that GOPATH isn't set properly or something. But here's a Windows x64 binary with the change: http://www.filedropper.com/processing/filedownload.php?id=caddyexe

**Comment by abiosoft** [comment]
@sinky so the expected behaviour is to have fastcgi passthrough directories that exists.

**Comment by abiosoft** [comment]
How about introducing an additional config for this. Some users may want prefer current behaviour.
```
fastcgi {
    ...
    allow_dirs
}
```
This basically enables your use case @sinky.

**Comment by sinky** [comment]
@mholt the binary works good.
@abiosoft that's the right description ;-) I got a mail where you wrote about "additional config" "allow_dirs". +1

**Comment by abiosoft** [comment]
@sinky Yeah. I wrote that at a time I didn't see mholt's suggestion would fix it. After having a second thought and looking at #298, I didn't see the need for it and I deleted the comment.

Naughty me, I thought no one has seen it. :wink:

**Comment by abiosoft** [comment]
This should be fixed now. Feel free to close this issue when you confirm it.

**Comment by sinky** [comment]
Fix confirmed.
