### ISSUE TITLE
browse subdir shows index.php from root dir

### ISSUE THREAD

**Issue by sinky** [mholt/caddy#298]
Hello,
another problem i discovered shortly after https://github.com/mholt/caddy/issues/297

If i request each file directly, each file is correctly handled. So if i request `http://localhost:81/` i get the `index.php` (`phpinfo()`) rendered. But if i request `http://localhost:81/test/` for dir indexing i get the index.php from root dir rendered.

I'm at Windows 7 x64 with newest PHP 5.6.14 x64

``` 
0.0.0.0:81 {
  root www/
  browse /
  fastcgi / 127.0.0.1:9123 php
}
```

Root Dir Content:
* /index.php
* /test.html
* /folder/
* /folder/test.html

**Comment by abiosoft** [comment]
This looks a bug and should not be the case. Trying to find a fix.

**Comment by abiosoft** [comment]
This should be fixed now. Feel free to close this issue when you confirm it.

**Comment by sinky** [comment]
Fix confirmed.
