### ISSUE TITLE
Add regex redirects and rewrite

### ISSUE THREAD

**Issue by gabsoftware** [mholt/caddy#30]
To make redirects and rewrites more powerful, like mod_rewrite.

**Comment by mholt** [comment]
I thought about this from day one, and it's been gnawing at my conscience ever since. Indeed, it would be a powerful way to match paths... but it comes at a cost - both in complexity and in performance. The complexity issue is that even if somebody doesn't need/want to use a regex, they would still get unintended results when the path has a dot in it, for example, causing them to scratch their heads.

I did consider using Go's [path.Match()](http://golang.org/pkg/path/#Match) function, which I may still decide to use before 1.0, since it gives you slightly more powerful matching capabilities than just a prefix match. But I still have to test its performance.

Another issue is that I would like all paths - even those in independent middleware - to be matched consistently across all Caddyfile directives. So if one directive, like rewrite, matches with regex or path.Match, then all directives which take path arguments should match the same way. (But I'm willing to experiment with one or two directives before rolling it out across the board.)

**Comment by gabsoftware** [comment]
Ideally the performance should not change when not using regex in paths. I understand that using regexes for matching paths will reduce the number of request per seconds, but I'm sure you'll still come to implement it one day. Better doing it from the start :-)

About the dot in paths, it should not be an issue as long as it is escaped in the directives.

I also think all directives taking paths arguments should behave the same about path matching.

path.Match() would definitely be an improvement over what we currently have. Not as powerful as regexes though.

A little off topic, but don't know where to say that, I think it's a very promising web server, I already tested that it can run our organisation intranet about twice as fast as using Apache, and almost three times faster with HTTPS and HTTP/2 enabled. So I'm very interested to see how it will evolve :-)

**Comment by abiosoft** [comment]
I now have the need this and I think `path.Match` should be sufficient. I will try to look into this.

**Comment by abiosoft** [comment]
This is what is in the works.

Regexp support for *rewrite* middleware. Not as robust as Apache and Nginx but a leap from current functionality.

Two types are now supported.
* Simple rewrite
* Regexp rewrite

#### Simple Rewrite
This is the current functionality. Same syntax
```
rewrite from to
```

#### Regexp Rewrite
Syntax:
```
rewrite regexp basePath {
    pattern 
    ext 
    to 
}
```
**basePath** - e.g. /home/blog will only rewrite for subpaths of /home/blog. Can be `/` to match entire site.

**pattern** - regular expression pattern

**ext**     - file extension to include or ignore. Prefix with `!` to ignore. 
        `.ext` for ext extension (e.g. /home.ext) or `/` for no extension (e.g. /home)
        `.html` - only rewrite for .html
        `!.html` - rewrite for everything else except .html
        `!.html .txt` - rewrite for only .txt, ignore everything else including .html
        `/` - only rewrite when there's no extension
        `/ .html` - only rewrite for .html and when there's no extension

to      - path to rewrite to. Supports variables `$path` and `$query`
        $path - request path without preceding `/` eg. blog/about
        $query - query string without preceding `?` e.g. name=Matt

##### Example. Personal use case.
Clean urls for [Phalcon](http://phalconphp.com) PHP framework. Converting from Apache mod_rewrite: `RewriteRule ^(.*)$ index.php?_url=/$1 [QSA,L]`
```
rewrite regexp / {
 	pattern .*
 	ext 	/
 	to 		/index.php?_url=/$path
}
```

With simple rewrite, basepath and extensions, I'm trying to minimise the regexp matching that will be done.

Can this fly ?

**Comment by mholt** [comment]
Yeah, almost! I have a few suggestions.

1. Can we drop the "regexp" keyword? Maybe we could replace the "pattern" keyword with "regexp" in the block, but I don't see why it would be necessary to have both. If a block opens and they specify a pattern then it is a regexp.

2. What is the purpose of both ignoring extensions and matching them? Like !.html .txt, why not just say .txt?

3. Can we adopt a similar syntax for the variables as we do for the log middleware, where the variable is enclosed in curly braces? E.g. {path}

These are my thoughts so far. Let me know what you think!

**Comment by abiosoft** [comment]
@mholt I'm okay with 1 and 3. Regarding 2, a possible scenario is if you want to rewrite for all other extensions except the specified one.

**Comment by abiosoft** [comment]
##### Update

Syntax:
```
rewrite [basePath] { # basePath is optional and defaults to /
    r[egexp]    pattern # either r or regexp can be used
    [ext]       ext # optional
    to          to
}
```
Variables are now `{path}` and `{query}`.

**Comment by cbess** [comment]
I personally think that having braces for the log is good, because its a string format. But, for the rewrite, because we are in a *code block* the dollar symbol makes a little more sense. Having curly braces inside of curly seems odd to me. However nginx, Apache, and lighttpd use the `$` prefix for vars in the configs.

**Comment by brk0v** [comment]
Will it work with proxy middleware? 

For example I want to proxy urls something like following: 
```
/static-files/1.jpg –> http://192.168.1.2:/static/1.jpg
/static-files/2.jpg –> http://192.168.1.2:/static/2.jpg  
```

With Caddyfile:
```
rewrite /static-files/ {
    r *\.jpg
    to  /static/
}

proxy /static/ 192.168.1.2
```

**Comment by abiosoft** [comment]
@brk0v yes it will.

**Comment by brk0v** [comment]
Awesome. I've made some hacks inside proxy middleware for this, but your realization looks better than mine =)

Thank you.

**Comment by mholt** [comment]
@cbess I think the consistency is important. With the dollar sign, it's confusing to know sometimes where the variable name ends - it gets worse when variable names are substrings of others or followed immediately by a letter or number. Remember, too, that we're trying to do things differently than other web servers in an effort to break the mold a bit and keep things as easy as possible.

I'll look at the PR later today. Thanks @abiosoft!

**Comment by abiosoft** [comment]
@brk0v your Caddyfile however will be the following (after the PR is merged). Use `{file}` to append the filename.
```
rewrite /static-files/ {
    r *\.jpg
    to  /static/{file}
}

proxy /static/ 192.168.1.2
```

**Comment by cbess** [comment]
@mholt Noted. I concur that it may be confused with not knowing there the variable ends. We could make it more identifiable by using `${var}` or `#{var}` from other langs. But either way, I understand.

**Comment by gabsoftware** [comment]
Wow now this look interesting :-) Can't wait to try it!

**Comment by abiosoft** [comment]
@gabsoftware if you are not willing to wait for the next release, you can build from source and try it right away.

**Comment by gabsoftware** [comment]
@abiosoft Sure :) Will try during the week !

**Comment by splitbrain** [comment]
One thing that seems to be currently missing is accessing any matched groups in the rewrite. Eg, the following wouldn't work currently:

```
rewrite {                                                                                                               
    r  ^/media/(.*?)/(.*?)/$                                                                                                    
    to /something/$2/?media=$1
}
```

**Comment by matthewp** [comment]
Bumping this issue since it's not supported in redirects currently. The need is that the markdown directive serves markdown from `filename` and my blog had legacy paths of `filename.html` so I need to redirect filename.html to filename, and cannot do that currently.

**Comment by kkovacs** [comment]
I totally support @splitbrain 's suggestion. Without matched groups rewrite's usefulness is a bit limited.

Keep up the good work! :)

**Comment by mholt** [comment]
This is landing in 0.8.1.
