### ISSUE TITLE
Arrow in default browse template

### ISSUE THREAD

**Issue by sinky** [mholt/caddy#302]
The arrow character `&#11025;` http://www.charbase.com/2b11-unicode-leftwards-arrow-with-tip-upwards used in the default browse template does not appear on Windows.

Should be replaced with somthing like `&larr;` http://www.charbase.com/2190-unicode-leftwards-arrow witch works.

**Comment by abiosoft** [comment]
Thanks for pointing this out. Will be fixed soon.

**Comment by mholt** [comment]
It's almost 2016 and Windows doesn't support Unicode yet??? :disappointed: 

I specifically chose the upward facing one so as not to be confused with the browser's back button, but I suppose the back arrow will have to do... until Windows learns its lesson. Thanks for the report!

**Comment by sinky** [comment]
Yea shame on Windows.

**Comment by mholt** [comment]
New template in 0.8.1 will use SVG instead.
