### ISSUE TITLE
A repository of examples

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#303]
I received a great suggestion via email today for a folder with a sample website and Caddyfile, so newbies could download it and see how it works without having to set anything up. I like this idea a lot, and I think a repository with several guided example Caddyfiles and websites might be great for beginners.

Not sure I can do this all myself. Who'd like to help? This wouldn't involve programming, but we need to assemble a list of common use cases to make examples for, and write a tutorial Markdown file for each one, preferably with screenshots.

For instance, a simple blog that serves markdown files with a simple style sheet. Or a WordPress+fastcgi setup. Those types of things.

**Comment by pierrebeaucamp** [comment]
I can help with that and yes, this should be in a separate repo. 

Do you want to host the website using Github pages or do you want Caddy to serve the files?

**Comment by mholt** [comment]
Thanks!

> Do you want to host the website using Github pages or do you want Caddy to serve the files?

Ah, that is the existential question. :smile: I was actually thinking that the repo could just have a README.md file with a brief explanation and list of examples, then each folder could have its own Markdown file with a simple tutorial and maybe some screenshots. The user could download the repo as a zip file or clone it using git.

**Comment by pierrebeaucamp** [comment]
Sounds good to me.

**Comment by mholt** [comment]
Alright, repo is up: https://github.com/caddyserver/examples - and I've added you as a collaborator. Others are welcome to contribute!

**Comment by mholt** [comment]
Closing, since the repository exists, but will still continue to promote it and encourage others to contribute!

**Comment by faddat** [comment]
The repo was off immediate use to me, thank you!
