### ISSUE TITLE
How to use environment variables in a Caddyfile?

### ISSUE THREAD

**Issue by calebmer** [mholt/caddy#304]
How do I use environment variables in a Caddyfile?

For example, say I am using the proxy directive, I want to be able to do the following:

```
proxy /api localhost:$API_PORT
```

**Comment by mholt** [comment]
In keeping with the syntax of placeholders, how about something like this?

```
proxy /api localhost:{$API_PORT}
```

We could also allow the following syntax, so that Windows users could feel right at home:

```
proxy /api localhost:{%API_PORT%}
```

**Comment by abiosoft** [comment]
I do not see the need to support both syntaxes but this is very useful.

**Comment by calebmer** [comment]
@mholt That sounds great 😊

**Comment by mholt** [comment]
@abiosoft Was just thinking of the comfort/intuition of the Windows users who aren't used to using `$` for env vars. I think supporting both will be trivial enough, and I can't think of any common collisions right now.

**Comment by abiosoft** [comment]
Okay. Let me get my hands on it.

**Comment by calebmer** [comment]
Thanks guys. It was really awesome seeing you guys work. Super excited to try out caddy in production 😊
