### ISSUE TITLE
0.8 beta

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#307]
Things to look at or work on **during the beta period** (before 0.8 is ready) in no particular order:

- [x] Clean up logging and get it more organized
- [x] Propose change to ACME spec to make ToS URL available before performing an action
- [x] More customization of LE integration from Caddyfile (if necessary)
- [x] Upstream change: have lego bind to domain:port, not just :port
- [x] Handle 500 Internal Server Errors from CA better (not really sure what to do yet)
- [x] Be able to complete challenges for hosts that need them during reload/restart (deferred to next patch release)

... and bug fixes as they come in.

This list will also be updated as we go.

[Please try the beta!](https://github.com/mholt/caddy/releases/tag/v0.8-beta.4)

**Comment by coolaj86** [comment]
:+1:  :-)

**Comment by avelino** [comment]
+1

**Comment by lenovouser** [comment]
:+1:

**Comment by mholt** [comment]
Some bugs related to restarts in the current beta 3 -- I'm in the process of fixing them on master and will deploy an updated beta in a few days (or sooner).
