### ISSUE TITLE
Static builds (CGO_ENABLED=0) for Docker images

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#31]
*Continuation from discussion at end of issue #13. /cc @darron*

> I created a Docker image for Caddy - https://github.com/darron/caddy-docker - but in order to do that and make a really small image I needed to statically link the final binary. The final Docker image was 23MB - vs using Ubuntu as a base image which was 148MB.
>
> If possible, using your binaries would be better - people trust the author more than some random person compiling it - but you'd need to build them a little differently and statically link them.
>
> Would that be possible for you to look at doing?
>
> ...
>
> CGO_ENABLED=0 go build -a -installsuffix cgo

-installsuffix doesn't appear to have any effect on `go build` (without -i, anyway)?

I'm using gox to do the builds so I'll have to experiment. But this doesn't fail, at least: `CGO_ENABLED=0 gox github.com/mholt/caddy` - if I sent you a build from this would you try it to see if it works? And if so I'll make it part of the automated build process.

**Comment by darron** [comment]
Absolutely - I'd love to try - running `ldd` on the binary shows if it's linked to any shared libraries - if it shows nothing linked to it, it should be good to go.

**Comment by mholt** [comment]
Hmm, ldd is reporting "not a dynamic executable" both with and without the CGO_ENABLED variable explicitly set to 0. Is that right?

**Comment by darron** [comment]
You're right - I just realized that your standard executable is totally static.

When I compiled it from src to get the Docker specific patches in - I must have made it so that it was shared.

So - in essence - you're doing it right already - and I'll just patiently wait for the next release.

Sorry about that - totally my fault.

**Comment by mholt** [comment]
No problem, glad you were able to figure it out! It'll be great to have a Docker image for it. Stay tuned for point release today.

**Comment by darron** [comment]
Perfect - I'll update the Docker image with the point release as soon as I
can.

**Comment by darron** [comment]
Looks great - I updated the docker container - https://registry.hub.docker.com/u/darron/caddy/

Repo is here: https://github.com/darron/caddy-docker

**Comment by mholt** [comment]
Nice. I'll add this to the readme or wiki. Or both. :+1:
