### ISSUE TITLE
v0.8 panics when run as a child process

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#315]
I found the magic smoke:

```
[stderr] panic:
[stderr] runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x4a71db]

goroutine 7 [running]:
github.com/mholt/caddy/caddy.init.5.func1()
        /home/aj/go/src/github.com/mholt/caddy/caddy/sigtrap_posix.go:25 +0x1ab
created by github.com/mholt/caddy/caddy.init.5
        /home/aj/go/src/github.com/mholt/caddy/caddy/sigtrap_posix.go:42 +0x2b

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x0, 0xc8200ce200, 0x200, 0xc820116220, 0xc82000be30, 0x86fea0)
        /usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x0, 0xc8200ce200, 0x200, 0x200, 0x410c38, 0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x5f
syscall.Read(0x0, 0xc8200ce200, 0x200, 0x200, 0x200, 0x0, 0x0)
        /usr/local/go/src/syscall/syscall_unix.go:160 +0x4d
os.(*File).read(0xc82002e008, 0xc8200ce200, 0x200, 0x200, 0xc820000180, 0x0, 0x0)
        /usr/local/go/src/os/file_unix.go:211 +0x53
os.(*File).Read(0xc82002e008, 0xc8200ce200, 0x200, 0x200, 0x200, 0x0, 0x0)
        /usr/local/go/src/os/file.go:95 +0x8a
bytes.(*Buffer).ReadFrom(0xc8200cbad0, 0x7f7e9eb82348, 0xc82002e008, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:173 +0x23f
io/ioutil.readAll(0x7f7e9eb82348, 0xc82002e008, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:33 +0x154
io/ioutil.ReadAll(0x7f7e9eb82348, 0xc82002e008, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:42 +0x51
github.com/mholt/caddy/caddy.CaddyfileFromPipe(0xc82002e008, 0x0, 0x0, 0x0, 0x0)
        /home/aj/go/src/github.com/mholt/caddy/caddy/caddy.go:321 +0xe5
github.com/mholt/caddy/caddy.LoadCaddyfile(0xaf4ed0, 0x0, 0x0, 0x0, 0x0)
        /home/aj/go/src/github.com/mholt/caddy/caddy/caddy.go:287 +0x3c0
main.main()
        /home/aj/go/src/github.com/mholt/caddy/main.go:74 +0x4c1

goroutine 17
[stderr]  [
[stderr] syscall
[stderr] , locked to thread
[stderr] ]:

[stderr] runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [chan receive]:
github.com/mholt/caddy/caddy.init.4.func1()
        /home/aj/go/src/github.com/mholt/caddy/caddy/sigtrap.go:16 +0x143
created by github.com/mholt/caddy/caddy.init.4
        /home/aj/go/src/github.com/mholt/caddy/caddy/sigtrap.go:32 +0x2b

goroutine 8 [select, locked to thread]:
runtime.gopark(0xaf5540, 0xc82002d728, 0x9ff690, 0x6, 0x42da18, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002d728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002d728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

[close] 2 null
```

```
# Digital Ocean Ubuntu
uname -a
Linux aj 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

# From https://storage.googleapis.com/golang/go1.5.1.linux-amd64.tar.gz
go version
go version go1.5.1 linux/amd64

caddy --version
Caddy 0.8 beta
```

**Comment by coolaj86** [comment]
Here's the test case:

```javascript
'use strict';

function run() {
  var spawn = require('child_process').spawn;
  var caddypath = '/usr/local/bin/caddy';
  var caddyfilepath = '/srv/walnut/Caddyfile';
  var caddy = spawn(caddypath, ['-conf', caddyfilepath]);

  caddy.stdout.on('data', function (str) {
    console.log('[stdout]', str.toString('utf8'));
  });

  caddy.stderr.on('data', function (errstr) {
    console.error('[stderr]', errstr.toString('utf8'));
  });

  caddy.on('close', function (code, signal) {
    console.log('[close]', code, signal);
    clearInterval(caddy._interval);
    run();
  });

  caddy._interval = setInterval(function () {
    caddy.kill('SIGUSR1');
  }, 5 * 1000);
}

run();
```

**Comment by coolaj86** [comment]
Oh, and my Caddyfile:

```
https://lds.io {
  gzip
  tls /srv/walnut/certs/live/lds.io/fullchain.pem /srv/walnut/certs/live/lds.io/privkey.pem
  root /srv/walnut/init.public/
  proxy /api http://localhost:4080
}

https://ldsconnect.org {
  gzip
  tls /srv/walnut/certs/live/ldsconnect.org/fullchain.pem /srv/walnut/certs/live/ldsconnect.org/privkey.pem
  root /srv/walnut/init.public/
  proxy /api http://localhost:4080
}

https://oauth3.org {
  gzip
  tls /srv/walnut/certs/live/oauth3.org/fullchain.pem /srv/walnut/certs/live/oauth3.org/privkey.pem
  root /srv/walnut/init.public/
  proxy /api http://localhost:4080
}
```

This works fine when run not as a child and it also works fine with 0.7.6

**Comment by tpng** [comment]
It seems caddy was reading the Caddyfile from stdin, when the USR1 signal arrived, the global `caddyfile` was still nil and thus the panic.

**Comment by coolaj86** [comment]
Thanks! That had crossed my mind, but I the default for 'process.stdin' was changed to paused and so I thought stdin was as well.

Why does it read from stdin when '-conf' is specified? Is that for a new feature in 0.8 or a new bug?

**Comment by mholt** [comment]
When the process forks, it has to transfer the Caddyfile to the child process. It does this using a pipe. Specifying -conf just tells the original process where to load the Caddyfile, and subsequent reloads will also load that file, but the re-loaded file is still transferred over a pipe after forking.

I will add a nil check on that line to prevent this panic in the future... but am still not sure _what_ to do if nil.

**Comment by coolaj86** [comment]
Just got around to testing this...

Yep, it seems to be working. :-)

**Comment by mholt** [comment]
Ok. That's not a workaround, that's correct code. Glad it's working now! ^_^ Pushing a fix for the panic in a moment.

**Comment by coolaj86** [comment]
I reread what you wrote ^^, but I'm still not clear.

Why is checking stdin when `-conf` is used correct? When it forks does it still have `-conf`in the arguments so there's no way to know it was a fork?

Also, for the sake of sanity, please do print an error message if it gets a signal before the config is read. In my case a useful error message would have directed me to close stdin. :-)

**Comment by mholt** [comment]
Because [pipe has precedence over the conf flag](https://github.com/mholt/caddy/blob/fc7f7dffa869ad1a4a3f097a302282e1b7de8996/caddy/caddy.go#L289-L295).

**Comment by coolaj86** [comment]
This still sounds like a bug to me.
Why would the **default** behavior use **implicit** configuration that overwrites an **explicit** configuration?

I see that you've even commented that you're doing this on purpose, but I'm not understanding why.

It seems like `loader` should accept an argument to the file specified by `-conf` and then loader should read from the pipe if the filename is nil.

Then if you're calling it as the new process you don't pass the filename, but if the user has said "this is what I want, here's `-conf`, you're not ignoring the user's intent".

**Comment by mholt** [comment]
Piping data into a process is an explicit action.

**Comment by coolaj86** [comment]
There's something that you understand that I don't understand or vice versa.

If I just run `caddy` from the command line with `-conf`, it doesn't halt and wait for user input.

If I write a node program for the command line and I want to read from stdin I have to explicitly tell it to read from stdin in node.

As a user I did not specify the "read from stdin" flag in caddy (typically this would be the `-` character for most programs that support the option), but it decided to read from stdin anyway.

I agree that you as the developer are explicitly opening and reading from the os.Stdin, but I disagree that I as the user specified to send data to stdin. I gave it a commandline argument.

This is where I'm confused. From my experience, it did something I explicitly told it not to do by virtue that I gave it `-conf`.

Furthermore, I'm trying to understand why stdin should have priority over flags. I don't understand your use case and it is counter-intuitive to my experiences with other programs.

Not that I'm spawning a child process from a node cluster in my day-to-day, but on the few occasions that I have I've never run into this before.

I understand that you are intending to do what you're doing on purpose. My knowledge is incomplete as to why this is good or necessary or both because I haven't experienced a program behaving this way before.

**Comment by coolaj86** [comment]
I'm reasoning about this and because I've not created a program to behave this way, I may lack some fundamental background knowledge.

Perhaps the case is that the default state of stdin is paused, but when you use something like `cat filename.txt | caddy` then `cat` is explicitly choosing to open stdin, which `caddy` can detect.

And also what you're saying is that running just `caddy` would leave stdin paused, but `cat filename.txt | caddy` would cause it to open and that `cat filename.txt | caddy -conf ./Caddyfile` would ignore the explicit behavior that the user specified `-conf` and instead choose the explicit behavior of `cat`.

I would argue that since the case of `cat filename.txt | caddy -conf ./Caddyfile` is generally not intuitive either to humans or to machines, it should throw an error and quit rather than choosing to obey either the user or the piper.

**Comment by mholt** [comment]
Caddy [only reads from the pipe if there is one](https://github.com/mholt/caddy/blob/cf5aa1bed1983db427ce5b8a8eb6ce0a23ce464c/caddy/caddy.go#L314). It is the parent process' responsibility to open that pipe or not.

> I would argue that since the case of cat filename.txt | caddy -conf ./Caddyfile is generally not intuitive either to humans or to machines, it should throw an error and quit rather than choosing to obey either the user or the piper.

Yeah, don't do that. Choose one or the other.

**Comment by coolaj86** [comment]
But... that's ambiguous and arbitrary. That's... confusing.

That means that people have to guess why something happened the way that it did and spend time debugging it (and your time explaining it).

**Comment by mholt** [comment]
How is it arbitrary and confusing?

If you have a Caddyfile to pipe into Caddy, then open a pipe, send the bytes, and close the pipe.

If instead you have a Caddyfile on disk for Caddy to load, then use `-conf` to specify it.

**Comment by coolaj86** [comment]
Here's the litmus test:

1. Go find a few programmers (or people that have used pipes in the command line).
2. Show them this text `cat wow.txt | caddy -conf awesome.txt`.
3. Ask them what they think might happen.
4. Then show them this text `cat /etc/a/Caddyfile | caddy -conf /etc/b/Caddfile`.
5. Ask them what they think might happen.

It's arbitrary because:

  * the choice wasn't made by the user (or rather the user unknowingly made two conflicting choices)
  * it isn't empirically deterministic.

If it discrete - say there were a unix standard for this behavior (and there actually is: it's to throw an error, same as the python zen) we wouldn't have had this conversation because I would have known "the standard unix way is to read from a pipe first and the standard unix way is to open a pipe to a child process with stdin open".

But neither of those statements are true. For any given program x it may or may not use stdin or commandline flags. For any program y it may or may not open a pipe when running a child process.

You just arbitrarily decided to do one. I didn't know what that was. It was documented. There was actually a bug that caused a panic because you hadn't foreseen that another person would encounter a situation that would arbitrarily decide to do something different.

Now, I'm sure *you* have a reason for wanting it one way or the other, so it doesn't seem to be arbitrary to use because you're the arbitrator in this case.

**Comment by mholt** [comment]
I'll have Caddy throw an error if both a pipe is open and the -conf flag is used.

**Comment by coolaj86** [comment]
I love you Matt.

I mean this completely sincerely: You are a true genius.

You think things through very critically and once you've decided on you don't just go with what someone says, you make them work to prove its legitimacy. I genuinely appreciate that about you.

:-)

**Comment by coolaj86** [comment]
P.S. I can PR if you'd like. You've shown me where the code is and I know how to test it locally.

Let me know.

**Comment by mholt** [comment]
Thanks - I actually want to move the code that calls LoadCaddyfileFromPipe into the loader() function in main.go, since I think that should be up to the discretion of the users of the caddy package, not forced. So I'll take care of this one. But the pidfile issue could use your help when you have a chance. :+1:
