### ISSUE TITLE
v0.7.6 bind: address already in use

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#316]
My workaround for the v0.8 child process bug would have been to use v0.7.6 and just kill and restart it. 

However, when run as a child process, killed, and respawned caddy can't rebind to it's port.

Restart the parent process and boom, it works.

**Comment by mholt** [comment]
Well 0.7.6 was never intended for port reuse / restarts as a child process. We'll fix 0.8 beta instead of supporting workarounds in older versions. :wink:
