### ISSUE TITLE
needs option for pidfile

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#317]
My workaround for the previous two issues was going to be to start caddy with something like upstart and then issue a kill directly to its pidfile... but I don't see an option for writing a pidfile in the docs or in the `--help`

**Comment by coolaj86** [comment]
Ugh... and the **workaround won't work** either because **caddy changes its pid** when it receives `SIGUSR1`.

Normally you'd do this:

```
exec start-stop-daemon --start --make-pidfile --pidfile /srv/walnut/caddy.pid --exec /usr/local/bin/caddy -- -conf /srv/walnut/Caddyfile
```

But since caddy changes its own process, not even `exec` knows what process it is.

**Comment by coolaj86** [comment]
This one is still a beast.

Sometimes when running as a child process, the parent dies and then caddy takes on a life of its own. Since it changes PIDs and there's no way to create a pidfile, I can't programmatically shut it down.

**Comment by mholt** [comment]
There are a few ways to do this -- feel free to propose a PR. Preferably, the user will not have to specify a pidfile location (maybe use the system pidfile store?).

**Comment by coolaj86** [comment]
The user does need to specify the pid file, if they want one - otherwise when you're running two instances of caddy you would be overwriting a single pid file, or you would be guessing at witch of the caddy.<<random>>.pid files you need to use.

Typically the user would want the pid file to go to /var/run/caddy.pid on linux.

Would you like it as a global in the Caddyfile? A commandline option? both?

**Comment by mholt** [comment]
I doubt that many users run more than once instance of Caddy, but we shouldn't assume that's always the case, I agree.

The Caddyfile doesn't have globals, so how about a command line option. `-pidfile` maybe. (Besides, this will mostly be used by programs in automation environments, so I'm OK with making the pidfile an explicit option like this.)

**Comment by coolaj86** [comment]
I'm sure I can find the command line argument parser with ease. I think I've been in that code before.

Looks like I'll need to use either [Getpid](https://golang.org/pkg/os/#Getpid) or [Getppid](https://golang.org/pkg/os/#Getpid), I can test and figure that out.

Would this be the correct place to perform the file write?
Would that be here - Getppid on the inside, Getpid in an `else`? https://github.com/mholt/caddy/blob/fc7f7dffa869ad1a4a3f097a302282e1b7de8996/caddy/caddy.go#L171

If so, it looks like I'll need to add another argument to the function which would change the public Api of caddy.Start() to accept a process-global options object.

**Comment by mholt** [comment]
Probably do it in main() or at least in main.go -- I don't think this needs to affect other Go programs if Caddy is used as a library.

**Comment by coolaj86** [comment]
Ah, yes.

However, if I observed the behavior correctly (and I believe I did), the pid changes when the server creates a child process for itself during the `SIGUSR1` restart, which is why using the conventional `start-stop-daemon` approach didn't work.

**Comment by mholt** [comment]
I haven't tried start-stop-daemon, I dunno, but if a pidfile allows the child process to change the process id to the new one, then, that'll work right? I don't know how to keep the pid the same...

**Comment by coolaj86** [comment]
I'm pretty sure you don't keep the pid the same. A child process will have its own distinct pid from its parent.

The issue is that the main function isn't called when the child process is created. The caddy.Start() function is called, right?

Writing the pidfile in main doesn't allow it to be rewritten when the child is spawned and supersedes its parent because main only runs once. Is that correct?

Perhaps a pointer to a pidWriter func as part of an options object should get passed to `caddy.Start(caddyfile, options)`?

Wherever the fork() on SIGUSR1 is happening is where the pidfile needs the option of being rewritten.

**Comment by mholt** [comment]
main is the program's entry point - it is always called. It subsequently calls caddy.Start, but not before all the init() functions run first.

**Comment by coolaj86** [comment]
So when ForkExec happens here [0], you're saying that it actually is called here, execution of the child begins in main.go here [1]?

0: https://github.com/mholt/caddy/blob/fc7f7dffa869ad1a4a3f097a302282e1b7de8996/caddy/restart.go#L80
1: https://github.com/mholt/caddy/blob/fc7f7dffa869ad1a4a3f097a302282e1b7de8996/main.go#L48

I ask because in C forking looks something like this where the fork immediately pops into existence on the next line:

```
do_stuff();

int f = fork();
if (CHILD == f) {
  do_child_worker_stuff();
} else {
  do_parent_stuff();
}

do_more_stuff();
```

But it sounds like go fork begins at main() regardless of where it was forked?

(that's also how node.js does cluster.fork(), but it does child_process.fork() differently)

If that's correct, that should be a fairly easy PR.

**Comment by mholt** [comment]
Go processes apparently don't fork well, so syscall.ForkExec forks, then execs, a new process, in a thread-safe way. So it starts back at main(). And yes, it shouldn't be too bad :)
