### ISSUE TITLE
Custom proxy upstream health check

### ISSUE THREAD

**Issue by kavun** [mholt/caddy#324]
Currently the proxy middleware supports a health check that requests a path and executes the following  logic on the response.

```
host.Unhealthy = r.StatusCode < 200 || r.StatusCode >= 400
```

What would be the best way to add support for logic to **fail the health check if the response content does not match a given regex**? My initial thought would be to add another parameter to the health_check like `health_check path [duration] [content_regex]`. Would a different syntax be clearer?

Thoughts?

**Comment by mholt** [comment]
Although I shudder at the thought of the user needing to use and maintain a regex, your proposed syntax is probably how I would do it, if it were to be implemented.

Does it need to be a full-blown regex or can we get away with substring matching? (i.e. look for that string in the response body to be considered healthy)

**Comment by kavun** [comment]
Yea you're probably right - for all cases where I've done something similar with other load balancers a simple string substring match has been enough.

Would the syntax have to be this instead since `duration` would be required if you wanted to supply the `content_substring`? `health_check path [duration [content_substring]]` - just trying to make sure this ends up being clean without introducing a breaking change.

**Comment by mholt** [comment]
Yeah, duration would be required then.

This isn't ideal but let's try it and see how it goes. Saying '10s' isn't too bad.
