### ISSUE TITLE
Make tls automatically generate self-signed cert if desired

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#327]
[There should be a way](https://twitter.com/mholt6/status/662353183344164864) for Caddy to generate and use in-memory, self-signed certificates (and keys) for local development/testing, if requested by the user.

Maybe something like:

```
tls testing
```

to make sure the user is clear about it only for use in testing environments. (Some users may not know what "self-signed" certificates are.)

This'll be really convenient when you want to test your site over HTTPS but don't want to go through the trouble of generating a certificate and key and putting them on the file system.

Anyone is welcome to get on board and help with this, or provide feedback -- it may not land in 0.8 but probably in the next version anyway.

**Comment by sinky** [comment]
+1

**Comment by mbanzon** [comment]
+1

**Comment by mbanzon** [comment]
Does the std lib or any third party library provide certificate generation?

**Comment by mholt** [comment]
Yep, or there's also this code from lego as a good, simplified example: https://github.com/xenolf/lego/blob/6a6af837dd43b76a5fe1c3014cae25dad4b1884e/acme/crypto.go#L253-L260

**Comment by My1** [comment]
"in-memory [...]" certs, does that mean that they are recreated every time?

**Comment by mholt** [comment]
Yeah, just something that you would use locally in a pinch.

**Comment by My1** [comment]
it that it's for local testing is obvious but when I wanna test locally I dont really want to accept a new cert on every reboot...

**Comment by mholt** [comment]
It's not ideal, but at least in my own dev workflows I'm not restarting my server all the time.

What about a Caddy flag or subcommand that plops the cert & key on your file system? e.g. `caddy -testcert localhost` would plop two files in the current directory, localhost.crt and localhost.key.

**Comment by My1** [comment]
well I am usually dev'ing on my own PC (usually using XAMPP right now) and well that one usually gets shut down at the end of the work.

**Comment by sinky** [comment]
+1 for a Caddy subcommand

**Comment by mjio** [comment]
+1 On a subcommand to generate self-signed certificates. This would not just be handy for development but also when you use a CDN like CloudFlare, where you can use self-signed certificates between your server and the CloudFlare servers.

**Comment by My1** [comment]
I think it would be better using the caddyfile since you dont have to invoke a certain special command, also helpful when using multiple testcert-domains.

**Comment by mjio** [comment]
@My1 True. Sounds like a Caddyfile setting with an optional command line option to me.

**Comment by mbanzon** [comment]
How about something like:

```
tls cert key generate
```

**Comment by My1** [comment]
when cert and key mean paths then nah, not really. I would spay the behavor of cert creation similar to the automatic LE certs, just store them on a convenient (to the server) place.

**Comment by mholt** [comment]
Another benefit of this is to enable http/2 on localhost with ease.

I can probably get around to this before the next release.

**Comment by mholt** [comment]
What I'm gonna do is make the syntax `https testing` (I probably will rename the `tls` directive to `https`) and it will just generate the cert in memory and use that, discarding it when the server quits or is restarted. I don't think a subcommand is necessary since openssl does a better job of it.

[Chrome has a flag](chrome://flags/#allow-insecure-localhost) you can set to disable warnings for self-signed certificates loaded over localhost, so it won't interrupt your testing workflow.

**Comment by Skilgarriff** [comment]
Any update on this/any way for us to help? I would love to be able to test [alpine-caddy](https://github.com/ZZROTDesign/alpine-caddy) on travis as a reverse proxy using tls.

**Comment by mholt** [comment]
I plan on rolling this out with 0.9, which I've already begun.

**Comment by nwgat** [comment]
nice

**Comment by Bitti09** [comment]
:+1:

**Comment by mholt** [comment]
This is now implemented on my local branch.

It's pretty cool.

You'll see this pushed with the 0.9 changes later this month.

**Comment by Skilgarriff** [comment]
Awesome! Really looking forward to that!

**Comment by mbanzon** [comment]
Great work! This is really going to help a lot!

**Comment by mholt** [comment]
You can see this in the [0.9-wip-readonly](https://github.com/mholt/caddy/tree/0.9-wip-readonly) branch (the branch is temporary and will be deleted before 0.9 is more mature) - right now, Caddy's in a very minimally-functioning state in that branch. But you can create a Caddyfile with a hostname on port 443 and `tls self_signed` and see it working. [Here's the function](https://github.com/mholt/caddy/blob/e340cf3b69e749ef51b81ec43ecca4059ab0a48b/caddytls/setup.go#L220) that generates a self-signed certificate.

**Comment by alexellis** [comment]
Hey @mholt where did you get to with this issue and status? I've just got the dreaded LE error of `registration error: acme: Error 429 - urn:acme:error:rateLimited - Error creating new registration :: too many registrations for this IP: see https://letsencrypt.org/docs/rate-limits/` due to an incorrect configuration.

**Comment by mholt** [comment]
It's implemented now as `tls self_signed`: https://caddyserver.com/docs/tls
