### ISSUE TITLE
Graceful restart and SIGUSR1

### ISSUE THREAD

**Issue by hdid** [mholt/caddy#334]
Hi
As notes, I tested the the SIGUSR1 signal but i could not understand how it works!?
I ran the command `kill -SIGUSR1 $PID`; the caddy process forked but old process did not die and just duplicated:

![caddyfork](https://cloud.githubusercontent.com/assets/3944323/11126545/aad8d9f8-8984-11e5-9883-4c116bff0f29.jpg)

caddy is 0.8 beta x86 run under Debian wheezy

**Comment by mholt** [comment]
Did you compile from source or download the binary on the beta release page?

**Comment by hdid** [comment]
No i did not compile. It is pre-built binary

**Comment by mholt** [comment]
I think this bug is fixed on master. I'll deploy a new beta release in a few days with that and other bug fixes.

**Comment by mholt** [comment]
I've fixed this locally and will push the changes soon. Thanks for the report!

Stay tuned for that commit or wait until the next beta release.
