### ISSUE TITLE
How can I return Status 403 Forbidden

### ISSUE THREAD

**Issue by ElvizLai** [mholt/caddy#335]
I want to refuse all visitor from IP address and return 403 status. Any directive can fulfill this feature？

**Comment by mholt** [comment]
Perhaps the ipfilter plugin can help: https://caddyserver.com/docs/ipfilter

**Comment by abiosoft** [comment]
Seems we have some good news.

The feature is being worked on. https://github.com/pyed/ipfilter/issues/1

**Comment by mholt** [comment]
This is done upstream and should be available from the download page with the 0.8 release. Thanks @pyed!
