### ISSUE TITLE
Internal proxies

### ISSUE THREAD

**Issue by bhilton** [mholt/caddy#336]
The X-Accel-Redirect header support is useful as a way of injecting an authentication middleware into the request stack, but once authentication is complete, I would like to be able to redirect client requests to another backend api, not just to a local directory for serving files.

Could you consider adding support for X-Accel-Redirect into proxy routes and also supporting the internal keyword inside a proxy definition?

**Comment by mholt** [comment]
Let me defer to @mschoebel on this, as I don't have much (any) experience using the X-Accel suite of headers. If we do make a change, we should be careful not to duplicate much/any code, if possible...

**Comment by mschoebel** [comment]
The `internal` directive is not restricted to serving files. I just tried this ...

```
0.0.0.0:8000
internal /backend/protected_api
proxy /backend http://0.0.0.0:9000
```

```go
package main

import (
    "fmt"
    "net/http"
)

func apiAuthenticationHandler(w http.ResponseWriter, r *http.Request) {
    w.Header().Set("X-Accel-Redirect", "/backend/protected_api")
    w.WriteHeader(http.StatusOK)

    fmt.Fprint(w, "This is ignored.")
}

func protectedApiHandler(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)

    fmt.Fprint(w, "Protected API result.")
}

func main() {
    http.HandleFunc("/backend/api_authentication", apiAuthenticationHandler)
    http.HandleFunc("/backend/protected_api", protectedApiHandler)

    http.ListenAndServe(":9000", nil)
}
```

... and it works like expected: accessing `http://localhost:8000/backend/protected_api` results in a 404 and `http://localhost:8000/backend/api_authentication` returns the "Protected API result.".

@bhilton Does this match your use case?

**Comment by bhilton** [comment]
Yes, this is perfect, thank you! It wasn't clear to me that I could combine the internal keyword and the proxy keyword for the same path. Now that I see your example it makes sense and in my local testing it works exactly as desired.

**Comment by mholt** [comment]
Hurray - drinks all around! :tropical_drink:
