### ISSUE TITLE
Site and docs translations

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#337]
As suggested by @unknwon in Slack today, Caddy could serve a much wider audience if it had Chinese documentation.

I don't know Chinese.

But I'm willing to upgrade the site to support additional languages.

This is probably a lot to ask for, and it will require some degree of maintenance as the docs change over time. This can be a collective effort, but I myself cannot do any of it.

Help?

**Comment by transtone** [comment]
Who can I get in?

**Comment by Unknwon** [comment]
I think we need to unified the way to handle translations first.

**Comment by mholt** [comment]
Let me try to set up the site so it can support multiple languages. I'll ping you here when it's ready :+1:

**Comment by My1** [comment]
may I ask, why we start with chinese?

**Comment by mholt** [comment]
Because it's the only language so far that's been requested.

**Comment by My1** [comment]
well that makes sense.

**Comment by Fristing** [comment]
@mholt if you want i can traduce your doc and your presentation page on french language.

**Comment by ragrum** [comment]
@mholt Count me in to help with translation into Spanish.

**Comment by mholt** [comment]
Woo! Okay, I'll work on upgrading the site to support multiple languages and will ping back when ready.

**Comment by ragrum** [comment]
Maybe change the issue title?, something like "Site and documentation translation", perhaps.

**Comment by Depado** [comment]
I can give a hand for the french translation too.
If you want @Fristing we can split the task of translating or if you want I can review your translation if that helps :+1:

**Comment by Fristing** [comment]
@Depado no problem. Ask the question at @mholt i'm not the creator of caddy x).

**Comment by abiosoft** [comment]
Haha. I'm sure @mholt only cares about French translation getting done, not who does it.

**Comment by Fristing** [comment]
@abiosoft it's a joke  x)

**Comment by vdemario** [comment]
I'd like to help with Brazilian Portuguese as well. We've done this recently on github.com/gobridge/bwag, almost 10 brazilians got involved. This is a good moment to get people to help. :)

**Comment by mholt** [comment]
Thanks for offering to help as well!

Yes, I agree, it is a good moment. I am still not ready to do the translations as I don't have a mechanism on the site to change languages. Would anyone like to help with that?

**Comment by Fristing** [comment]
I don't know your website structure but you can use I18N.

**Comment by mholt** [comment]
The site is here: https://github.com/caddyserver/caddyserver.com

**Comment by DenBeke** [comment]
If wanted I could do a Dutch translation. Maybe something for you too, @trtstm?

**Comment by trtstm** [comment]
@DenBeke sure, count me in

**Comment by mholt** [comment]
Would anyone like to take the lead on this after 0.9 lands? If not, I will close this issue and defer until another time...

**Comment by mholt** [comment]
Actually, closing this in favor of #574, which is basically the same thing. If you're interested, comment over on that issue!

**Comment by Fristing** [comment]
I work on this after 1st july !

**Comment by mholt** [comment]
Okay cool! Looking forward to it.
