### ISSUE TITLE
Compile for Android

### ISSUE THREAD

**Issue by gedw99** [mholt/caddy#338]
Can Caddy be compiled for Android ? 
It mentions it on the web site, but i would like to do this myself.
Would be really useful

**Comment by mholt** [comment]
If your Android phone is newer, it probably runs on Linux ARM. Just download or build Caddy for Linux ARM and follow these instructions. https://github.com/mholt/caddy/wiki/Running-Caddy-on-Android

There are ways to do native Android builds but I haven't gone down that road at all.
