### ISSUE TITLE
support caddy deployment in openshift & heroku

### ISSUE THREAD

**Issue by shivakumargn** [mholt/caddy#342]
Current Caddyfile is not suitable for using in openshift and heroku like environments.

**Comment by mholt** [comment]
I'm nofamiliar with either service. Care to elaborate, including your idea for making it more compatible?

**Comment by mholt** [comment]
Feel free to re-open if you have more to say. Thanks!

**Comment by shivakumargn** [comment]
Working with openshift essentially requires caddy to use the configuration from environment variables than hard coded in Caddfile as done currently.
Environment variables decide multiple configuration aspects such as IP,port, directories for home,logging,tmp,data, etc.

I will come back to look at caddy source code to make it compatible.

**Comment by mholt** [comment]
That's a tall order... I know that [Docker has something like this](http://docs.docker.com/registry/configuration/) but it's a bit of a handful... can't you just use the command line args for most of what you'd have to configure?
