### ISSUE TITLE
Edit filenames addon

### ISSUE THREAD

**Issue by SoreGums** [mholt/caddy#344]
Got browse - would be nice if could edit filenames.

The way I see this working is:

1. Put a pencil icon next to the folder/file icon
2. Click it and filename loads in a textbox with save icon button on the right
3. Clicking the save icon button renames the file to what is in the textbox
  - of course optimisation is, if not different don't waste time writing to disk

If this can be done in the browser via html, then should be doable from other places, aka its an api thing. /orginal-filename.txt?rename=new-filename.txt - I don't know something simple...

so there are two parts

1. a new default template for browse if browse & rename are enabled at the same time
2. own middleware looking out for renaming directions

need to make the call on rename = moving... not sure about that. I am going to just do simple rename and edit out os_directory_separator (whatever the go_lang of this is).

-----
so this stuff below has ZERO to do with caddy, it is simply why I came to Caddy and why I want a http in road to renaming files ;)

grand plan is to make a useful media manager for Kodi (or any multi platform player that has a http/websockets api) - been using it and Kore (remote on android) and frankly, some really annoying ux things that shouldn't exist (weird sorting, cut off file names, doesn't allow fixing matches of scrapers to filenames). Kodi has a functional API to control & play content remotely - awesome!, media library/navigating lots of files is weird - less awesome...

Writing the media manager in Ember.js using local storage and firebase (multi-device sync) - so need static file serving. Simplest way to get content over the network to kodi is via http, hence Caddy browse. Webapp being Ember needs some static hosting love as well. Caddy runs on android (bit awkward, however it works... must be possible to wrap in a minimal app like aria2 currently is)

ultimate plan = have screens, have files, have people, have devices = everything talk to everything and let people keep track of separate things or same things... purposefully vague, cryptic and open ended.

**Comment by mholt** [comment]
Let me share my thoughts on this and maybe that will help materialize a vision for your plans a bit more.

I like the idea of a file manager add-on for Caddy, but renaming files shouldn't be part of the browse middleware. Implicit in the idea of any kind of mutations through a Caddy plugin is authentication. You probably don't want just anyone renaming/changing your files.

Caddy is a great platform on which to deploy your web app - so I think you're on the right track, but it should be separate from browse.

**Comment by SoreGums** [comment]
indeed @mholt - I intend to make this rename addon standalone. All I need is some simple api to rename files. This is something I could take on and complete in a reasonable amount of time. A full blown file manager is way out of scope for me :) *(i see the upload addon is coming along, so nearly have all the bits that would make a file manager)*

With relation to browse my only interaction with that addon is through the existing interface of specifying a template file *(I've already tweaked the existing template as it would wrap lines and wasn't using a monospaced font)* in the in the caddyfile. This is where i would expose an example UI or implementation of the rename functionality. In other words rename doesn't have any UI and doesn't care about any other middlewares.

Regarding auth, yes a feature complete rename addon should consider auth as randoms renaming files willy nilly is to be avoided. For v1 though renaming files is the goal, v2 can figure out auth. Will look at existing auth strategies and see how that might be used for rename. Out of the box though specify rename in the caddyfile should be all that is needed to enable, if auth is required then add extra params or middleware.

**Comment by SoreGums** [comment]
for whatever reason I missed the "setup" part of creating middleware...
https://github.com/mholt/caddy/wiki/Writing-Middleware

Now that I've re-read the docs, I'll probably be able to get this up and running shortly :)
Was playing on hard mode for some reason...

**Comment by mholt** [comment]
Maybe auth should be a separate middleware (smaller, simpler middleware are good). See #246 and #109 for that.

A Caddy file manager seems like an appropriate add-on to have, though, at yours or anyone's leisure. :smile:

**Comment by SoreGums** [comment]
separate auth +1 _(you get an auth, you get an auth, every middleware gets an auth)_

nearly getting to the point where I really want this. however have a couple of other things I want to work first _(nothing to do with caddy, involve the same files that eventually get served by caddy)_

re-thought the rename functionality, it needs to be able to move files around the current filetree. example:

- root /home/user/www/html
- currently at http://domain/dir1/dir2/
- want to rename file /dir1/dir2/file1.txt to /dir1/dir3/renamed_file1.txt = works
  + thus the result is /home/user/www/html/dir1/dir2/file1.txt becomes /home/user/www/html/dir1/dir3/renamed_file1.txt _(dir3 is created if it doesn't exist)_
- so can only move/rename files around within current root :)
- auto create parent directories as needed _(assuming stdlib has this, otherwise that is a bit painful, still doable though)_

**Comment by mholt** [comment]
> full blown file manager addon would be ideal, however that is pretty full on, go with a php or other solution i reckon :P

No, no PHP. :-1: It can be written in Go. :wink:

**Comment by SoreGums** [comment]
haha - i mean they already exist, if a full on file manager is required, use an [existing one](http://extplorer.sourceforge.net/) :)

**Comment by wmark** [comment]
Could make it to one of the next versions of #249. For our notes, from WebDAV:

```bash
curl \
  -X MOVE \
  --header 'Destination: /to/new.file' \
  https://caddyserver.com/from/old.file
```

**Comment by wmark** [comment]
@SoreGums if you can, have a look at my plugin. I've implemented DELETE in wmark/caddy.upload@f77c34aa2a506b14d75bf65cb2acdc4ae08778ac

**Comment by wmark** [comment]
Caddy with plugin *Upload* are out. There are not many auth plugins available, yet, so you could ping all authors and standardize a flag (header?) and, if it's set, display that button in middleware **browse**. Should be very few lines of JS on top of that.

**Comment by mholt** [comment]
@SoreGums and @wmark - thanks for your comments! There is a lot of good stuff here, so I have linked to this issue from [a thread in our community forum](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127?u=matt) where we are aggregating ideas/requests for Caddy plugins.

If you want to continue discussing the plugin before development begins on it, feel free to start a new topic on the forum. :+1: Hope to see you participate with us there!

**Comment by wmark** [comment]
You can rename files using plugin *Upload*.
