### ISSUE TITLE
TestHealthCheck failed

### ISSUE THREAD

**Issue by tw4452852** [mholt/caddy#346]
go test -v -run=HealthCheck
=== RUN   TestHealthCheck
--- FAIL: TestHealthCheck (15.06s)
        upstream_test.go:18: Expected first host in testpool to not fail healthcheck.
FAIL
exit status 1
FAIL    github.com/mholt/caddy/middleware/proxy 15.067s

google.com is forbidden in my country,sigh... so this test is failed on my local environment

**Comment by mholt** [comment]
Thanks for the fix :smile:
