### ISSUE TITLE
Proxy all headers

### ISSUE THREAD

**Issue by calebmer** [mholt/caddy#348]
I am using caddy in front of an API which requires many HTTP headers to operate. Currently I have to write a `proxy_header` directive for each header. Is there a way to pass all headers, except a few? Maybe the same syntax as the `header` directive?

**Comment by mholt** [comment]
We can probably do this -- just not quite sure how it will look in the Caddyfile yet.

**Comment by iamveen** [comment]
:+1:

**Comment by mholt** [comment]
Related reading: #666

**Comment by mholt** [comment]
I wonder if @Burmudar, who just finished some proxy header related work, would be interested in this or at least have some feedback about how this might look in the Caddyfile.

Note that `proxy_header` is being replaced with `header_upstream` in 0.9.

**Comment by Burmudar** [comment]
I'm not quite sure I follow. I tried recreating this (from what I understood) and all headers are passed upstream and all headers received are passed downstream by the proxy. Unless specifically told to alter the headers. Am I missing something ?

**Comment by mholt** [comment]
Oh, maybe I missed something from earlier!

That's good news, I'll close this then unless there's still an issue with it that remains to be addressed. Thanks for looking into it!
