### ISSUE TITLE
setcap method to run on port 80 doesn't work

### ISSUE THREAD

**Issue by cganterh** [mholt/caddy#353]
Sorry if it is a stupid question, but I couldn't find an answer to my problem. This isn't even a caddy problem. :(

I used the `setcap` method (from the FAQ) to bind caddy to the port 80. But I'm still getting a "permission denied" message.

This is what I did:

```
$ sudo setcap 'cap_net_bind_service=+ep' /home/cristobal/bin/caddy
$ caddy
localhost:80
2015/11/20 19:39:56 listen tcp :80: bind: permission denied
```

**Comment by mholt** [comment]
What does `which caddy` output?

**Comment by cganterh** [comment]
```
$ which caddy
/home/cristobal/bin/caddy
```

**Comment by mholt** [comment]
Hmm, that's weird. What is your OS/version?

**Comment by cganterh** [comment]
I'm using Ubuntu Gnome 15.10.

**Comment by mholt** [comment]
Interesting, same question as http://askubuntu.com/questions/564996/problems-with-setcap-in-ubuntu-14-04-lts which doesn't have an answer... I wonder if your file system does not support attributes? But I'm pretty sure the default file system should be fine...

Ha, same thing here: http://superuser.com/questions/865310/file-capabilities-setcap-not-being-applied-in-linux-mint-17-1 - also unanswered. That's annoying.

You should ask Stack Exchange for help, I'm afraid I don't know. Alternate plan is to use iptables: http://serverfault.com/questions/112795/how-can-i-run-a-server-on-linux-on-port-80-as-a-normal-user

**Comment by cganterh** [comment]
Thank you!

I saw this unanswered questions. That's why I didn't ask my question in StackExchange.

I've previously used iptables to run a Tornado server, but I always found it a dirty solution. Then I ended using nginx as my reverse proxy. In this case using nginx as reverse proxy doesn't make sense. So I really wanted `setcap` to work.

**Comment by mholt** [comment]
This is going to bother me. :smile: I'll keep my eye out for a solution; sorry about that. (I've also heard of running caddy as root with no problems -- just FYI, if your risk tolerance is high enough) But as you said, it's not directly a caddy issue, so I'll close this now.

If anyone has a solution after-the-fact, please feel free to share it!
