### ISSUE TITLE
runtime error: invalid memory address

### ISSUE THREAD

**Issue by jungle-boogie** [mholt/caddy#363]
Full log:
http://termbin.com/531v

Excerpt:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x38 pc=0x54e267]

Replication steps:
0. start caddy
1. browse to site
2. click in a directory
3. remove file
4. refresh browser
5. observe file is gone and 404 message is present
6. go back/up one directory and see caddy crash

You may need to go to root level and back into sub-directory to cause crash. Refreshing the page may also be necessary.

caddyfile:

     % cat caddyfile
    :2020
    gzip {
    level 9
    }
    log access.log
    log error.log
    ext .txt .csv
    browse
    search
    root ../

I'm using the binary generated for freebsd 64 bit with hugo and search.

**Comment by mholt** [comment]
Whoops, looks like a bug in the search add-on.  /cc @pedronasser 

@jungle-boogie, Could you move this issue to the [caddy-search](https://github.com/pedronasser/caddy-search) repo? That way we can keep track of it better.

Also, a few tips about your Caddyfile:

- If you call the file `Caddyfile` (capital C), you won't have to use `-conf=caddyfile`
- You have two access logs enabled, but one is called error.log; you might have intended `errors error.log` for an error log.
- You can replace `gzip { level 9 }` with just `gzip`

:+1:

**Comment by jungle-boogie** [comment]
Hi @mholt,

Thanks for the feedback on the Caddyfile. I glanced over that you set the `gzip` level to 9 already.
I also see that I completely got the error logging incorrect: https://caddyserver.com/docs/errors

Thanks!
