### ISSUE TITLE
caddy with inetd?

### ISSUE THREAD

**Issue by jungle-boogie** [mholt/caddy#364]
Hello,

I have not yet tested caddy with inetd, but I'm just curious if there's any known problems with running Caddy with inetd. Otherwise, what ways do you recommend running caddy in the background?
A simple `./caddy &` will work but may unexpectedly crash.

How is matt.life setup with caddy to keep the process running?

Thanks!

**Comment by mholt** [comment]
I'm not familiar with inetd, and haven't heard about anyone using it for Caddy; so you're one of the first I think! Let me know how it goes :) Are you running 0.7.6 (the latest stable from the website) or 0.8 beta (from the GitHub releases)?

As far as matt.life goes, I'm just doing `caddy &` :smile:

**Comment by jungle-boogie** [comment]
Hi @mholt,

I'm using the release but I usually like to track projects at head, so I may try getting go working. I have used go the past but I get hung up on the gopath thing.

**Comment by mholt** [comment]
Okay, but which release? (Which version?) It matters because 0.8 beta does restarts which changes its process ID and your process manager may need to know about that.

**Comment by jungle-boogie** [comment]
> Okay, but which release? (Which version?)

    % ./caddy -version
    Caddy 0.7.6

here's an wiki article on inetd: https://en.wikipedia.org/wiki/Inetd

**Comment by mholt** [comment]
Okay; in that case, it should be fairly easy as Caddy 0.7.6 doesn't do restarts.

**Comment by mholt** [comment]
I'll close this for now, but feel free to open if there's anything else to discuss about this. Thanks!
