### ISSUE TITLE
[discuss]Support TLS session shared use redis or memcache or other

### ISSUE THREAD

**Issue by pyinx** [mholt/caddy#367]
Are there any plans for this future?

**Comment by mholt** [comment]
Nope. But if you want to persist user authentication, I recommend looking at #109 - it might make a good plugin, if it's implemented well. (Or I might be misunderstanding what you mean. Feel free to elaborate more than just in the title with more details.)

**Comment by mholt** [comment]
Feel free to re-open if there's more to say/explain about this. Thanks for the question!
