### ISSUE TITLE
DOSing myself with LetsEncrypt : Too many currently pending authorizations.

### ISSUE THREAD

**Issue by chilts** [mholt/caddy#368]
When starting caddy on a new server and setting up a new https endpoint, caddy will try and talk to LetsEncrypt. However, if I haven't yet set my DNS to the new server, LetsEncrypt will fail (which is understandable) but caddy keeps on trying and trying. Eventually I DoS myself and so even once I've fixed my DNS to point to the new server, I'm still rate limited.

Here's a log sample and as you can see, it's `Activating privacy features` every second if the previous try failed.

```
Activating privacy features...
2015/11/26 05:00:01 [javascript-minifier.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations.
[www.javascript-minifier.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations.
Activating privacy features...
2015/11/26 05:00:02 [javascript-minifier.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations.
[www.javascript-minifier.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new authz :: Too many currently pending authorizations.
```

Perhaps there needs to be a delay between each try and incremental backoff or something like 2s, 5s, 10s, 30s and eventually giving up ... etc instead of every second.

**Comment by mholt** [comment]
Thanks for trying it!

Does the retry only happen once? Also, are you using `-log stderr`? (If not, could you please enable the process log so that I could have more information? You can also log to a file if you wish; the complete log would help, either way.)

**Comment by mholt** [comment]
Wait, are you using a process manager or something to retry if Caddy fails to start? "Activating privacy features..." should only ever appear once, since an error returned from the function that calls the function that prints that output invokes a log.Fatal, killing the process.

**Comment by chilts** [comment]
Ah yes, so sorry. I'm using upstart and it'll respawn if it dies. Ok, I'll have to go recheck why it's just trying again and again instead of a maximum number of times.

Really sorry for not realising this. I'll close for now and report back if I do find anything else.

**Comment by mholt** [comment]
Sounds good, no problem. If Caddy fails to start, I doubt reteying in a second will help, unless you expect a port to be freed up or something. Usually startup failures require attention.

Also keep in mind that Caddy will restart sometimes during its life so use the pidfile flag if upstart needs to keep track of the changing process id.

**Comment by pavlik** [comment]
I have the same problem. For start/restart Caddy I'm using `supervisord`

**Comment by mholt** [comment]
I strongly recommend using the staging endpoint while testing your configuration. `-ca "https://acme-staging.api.letsencrypt.org/directory"` - much higher rate limits.

**Comment by pavlik** [comment]
If I use this param then receive this error:
```
Activating privacy features...2016/02/05 00:40:21 [kuda.pro] failed to get certificate: acme: Error 400 - urn:acme:error:badNonce - JWS has invalid anti-replay nonce IE8Of-HDxfVw5PVLagVeZUyZ7ppxWIEVBVMzMDXKsps
```

**Comment by mholt** [comment]
Oh, yeah, you can't use the same user account from the live endpoint as on the staging endpoint. Delete your .caddy/letsencrypt/users/<user> folder or choose a different email address.

**Comment by pavlik** [comment]
This help. But certificate is fake & not trusted :(

**Comment by mholt** [comment]
Yep, it's fake. But if you're sure that your env is set up properly and you won't hit rate limits, you can switch to the live endpoint for real certificates.

**Comment by pavlik** [comment]
Yes, I test config - it work. How to switch to the live endpoint?
If i start caddy without params, my cert still `happy hacker fake CA`

**Comment by mholt** [comment]
Yeah, because once it's one disk it will re-use the certificate. So to switch back delete that certificate from the .caddy/letsencrypt/sites folder and don't forget to delete your user folder or use another email address.

Just remove the `-ca` flag to go back to the live endpoint.

**Comment by pavlik** [comment]
Thanks! This help me. Need to include this workflow to documentation FAQ :+1:

**Comment by mholt** [comment]
Probably will, but didn't at first because this is only necessary in advanced setups. The vast majority of users won't have this problem.
