### ISSUE TITLE
[feature request] htaccess-permission, but with 3rd party auth

### ISSUE THREAD

**Issue by My1** [mholt/caddy#369]
well it it possible to do Basic HTTP login for permissions and stuff with pretty much any server but is it possible to make a 3rd party authorization possible?

I think this could go like this:
caddy pushes relevant data (like cookies and so on) to the auth functions
the auth function answers in a way caddy undertands it (maybe a json array of user and group ID or false for not logged in) and if not logged in throw a 401 and display login form, if already logged in do user/group matching as it would be done normally with htaccess.

the obviously good thing is that anyone could include a plugin to do the authorisation (for example I have my auth PHP script which works upon a mysql database, making htpasswd files useless or you could even make a login with any login provider you want, even github)

**Comment by mholt** [comment]
This sounds similar enough to #109 - let's keep the discussion together over in that issue.
