### ISSUE TITLE
browse sort by size with files of same size

### ISSUE THREAD

**Issue by areve** [mholt/caddy#371]
If browse is sorting by size and the files have the same size the order is not predictable.

I'd suggest that the fix should be if sorting by size (or modified) to secondarily sort by name.

**Comment by mholt** [comment]
This sounds complicated. Is the deterministic sorting of items with the same size/date/name/whatever really important? What situations are you finding that you need the exact same order of elements with the same value?

**Comment by areve** [comment]
I spotted it during messing with the browse code. I created some more files in the test folder and the json test started failing. I doubt it's something that would ever bother me, and I solved it by making my test files have different sizes.

**Comment by mholt** [comment]
Although unlikely, the obvious next question is, what if the elements have the same first and second values (e.g. same size and modify timestamp -- not unheard of if files are generated programmatically)? I think for the sake of unit tests we'll just have to ensure the elements have different values (i.e. every file has a different timestamp or size, depending on what is being tested). If it ever comes up in practice, then perhaps we could revisit it if the situation was common enough and really merited the extra complexity.

Thanks for thinking about it and raising an issue!
