### ISSUE TITLE
tests on windows

### ISSUE THREAD

**Issue by areve** [mholt/caddy#372]
A number of the unit tests fail on windows, usually due to using external commands e.g. `mkdir`.

**Comment by mholt** [comment]
Can you give more details? [The tests seem to be fine on Windows](https://ci.appveyor.com/project/mholt/caddy/build/264).

**Comment by areve** [comment]
I commented some out while looking at the code, there are others but here is an example

    --- FAIL: TestStartup (0.25s)
        startupshutdown_test.go:50: Test 0 recieved an error of:
            exec: "mkdir": executable file not found in %PATH%
        startupshutdown_test.go:54: Test 0 recieved an error of:
            remove C:\Users\me\AppData\Local\Temp\temp_dir_for_testing_startupshutdown.go: The system cannot find the file specified.
        startupshutdown_test.go:50: Test 1 recieved an error of:
            exec: "mkdir": executable file not found in %PATH%

**Comment by mholt** [comment]
How does your Windows not have `mkdir`? https://technet.microsoft.com/en-us/library/bb490930.aspx

Sounds like your PATH might be missing something...

**Comment by areve** [comment]
Yes a good point, I do of course have mkdir it's not a path program though I think it's built into cmd.exe . I wonder if this machine 64bit has a 32bit go installation on it that might be causing this.

**Comment by areve** [comment]
I have 64bit go installed. This machine has hardly anything installed (no gcc, mingw or cygwin etc). Looking at 
http://stackoverflow.com/questions/20437336/how-to-execute-system-command-in-golang-with-unknown-arguments I see more evidence that exec does not run shell built in commands.

If I add a mingw built gnu mkdir.exe to my path the test I mentioned above works, that's a good enough solution for me.

**Comment by mholt** [comment]
I don't have Windows, but it does work on my Windows VM. Do you have git installed? I think installing git might add some of those commands to the PATH.

Anyway, thanks for the report! Maybe some day we can find a more universal way to do these tests.
