### ISSUE TITLE
Redirecting on subdomain and port issue

### ISSUE THREAD

**Issue by mjio** [mholt/caddy#373]
Hi, I'm currently setting up a Caddy server and would like to only use `https://www.example.com`. When a request comes in from port 80 or non-www, I would like to redirect. My current Caddyfile looks like this:

```
https://www.example.com {
  tls cert.pem cert.key
}

https://example.com, http://www.example.com, http://example.com {
  redir https://www.example.com
}
```

However, I'm getting the following error: `2015/11/29 23:20:20 listen tcp 0.0.0.0:443: bind: address already in use`

**Comment by mholt** [comment]
Are you using version 0.7.6 or 0.8 beta?

**Comment by mjio** [comment]
Hi @mholt. I'm using 0.7.6

Should I use 0.8 beta instead?

**Comment by mholt** [comment]
It's up to you, but since the two are very different I wanted to be sure I had the version right.

Do you already have another process listening on port 443? Is that your entire Caddyfile?

**Comment by mjio** [comment]
The Caddyfile looks actually like the following:

```
https://www.example.com {
  redir /index.html / 301
  tls cert.pem cert.key
  log access.log
  errors errors.log
}

https://example.com, http://www.example.com, http://example.com {
  redir https://www.example.com
}
```

And yes, the Caddy server is the only process listening on port 443 as well as 80.

My goal is to make sure https and the www subdomain is always used.

**Comment by mjio** [comment]
I tried to use 0.8 beta but I can't get it to work either. I generated the certificates with Let's Encrypt but I'm only getting as far as `failed to get certificate: The server could not validate our request.`

Is there more documentation around how to get Caddy 0.8 with Let's Encrypt working?

**Comment by mholt** [comment]
I'm having trouble reproducing the error locally with your Caddyfile. I've replaced the hosts `www.example.com` and `example.com` to be hosts that resolve to my machine, but kept the scheme definition as you have them.

Keep in mind, on 0.7.6, your `https://example.com` host will be served on port 443 but won't be served with TLS because you haven't enabled it. (That changes in 0.8, where it will be enabled automatically. In fact it takes care of the HTTP->HTTPS redir for you, too.)

**Comment by mjio** [comment]
I updated to 0.8 beta 4, so I don't need to worry about the http -> https redirect and changed the Caddyfile to contain nothing but `example.com`, for now.

I haven't used Let's Encrypt before but generating the certs using the following command works just fine. I couldn't find any docs around Caddy and Let's Encrypt, so I'm just following an trial and error approach here, it this how the setup is suppose to work?

```
./letsencrypt-auto certonly --standalone --standalone-supported-challenges tls-sni-01
```

Afterwords I'm trying to start Caddy and get the following error: `failed to get certificate: The server could not validate our request.`

Am I missing any steps? The server is a Debian host from DigitalOcean with nothing other that Caddy running on it.

**Comment by mholt** [comment]
No, Caddy will generate the certificates for you -- no need to do it yourself. :smile: You'd just need this Caddyfile, in your case:

```
www.example.com {
  redir /index.html / 301
  log access.log
  errors errors.log
}

example.com {
  redir https://www.example.com
}
```

It is probably failing because of the error you're seeing above. I'm still not able to reproduce it, but I've asked @abiosoft to help me out and take a look also.

**Comment by mjio** [comment]
Thanks @mholt. I really appreciate your work. Caddy looks almost like my new default webserver, I just need to get the Let's Encrypt issue sorted. :)

**Comment by abiosoft** [comment]
@mjio Am I right to assume the only issue remaining is getting SSL certificates to work ?

**Comment by mjio** [comment]
@abiosoft Yes since I updated to 0.8 beta that is the case.

**Comment by abiosoft** [comment]
What error does Caddy give you now ?

**Comment by mjio** [comment]
```
$ ./caddy -version
Caddy 0.8 beta 4

$ cat Caddyfile
www.example.com

$ ./caddy -log stderr
Activating privacy features...2015/12/01 18:08:35 [INFO] acme: Obtaining bundled certificates for www.example.com
2015/12/01 18:08:35 [ERROR] acme: Could not find solver for: tls-sni-01
2015/12/01 18:08:35 [INFO] acme: Trying to solve HTTP-01

2015/12/01 18:08:37 [www.example.com] failed to get certificate: The server could not validate our request.
```

I'm running Debian 8.2 x64 on a new machine from DigitalOcean.

**Comment by mholt** [comment]
Hmm, works for me. :-/

That empty line in the log output is interesting.

What's the hostname of your machine? (I'm kinda shooting in the dark at this point.) What happens if you try it without Let's Encrypt? Does anything change as you remove addresses from the Caddyfile one at a time?

**Comment by mjio** [comment]
I have changed the Caddyfile to `example.com` notice the no-www. And suddenly the server did the authentication and started just fine. After recreating the www CNAME even www subdomain works just fine. I'm not sure what caused the issue but I belief my CND caused the issue. Thanks for your patience! :smile:
