### ISSUE TITLE
[feature request] build PHP directly in caddy or as plugin

### ISSUE THREAD

**Issue by My1** [mholt/caddy#376]
with the statement that caddy is also "It's easy to set up and doesn't get in the way." or "If you've ever found it difficult to configure a web server, try Caddy." as the website says I would say that a PHP plugin should be there, maybe even MySQL, because not everyone knows (or wants to know) how to do stuff with a fastCGI "server", well I got it to work but in the end, but having it integrated would make it a LOT easier.

**Comment by coolaj86** [comment]
How did you get it to work? Let's add that to the wiki.

Also, {rant} don't use php. Use a programming language like ruby, python, or node.js if you need a programming language. Or if you need a template language consider something like jekyll or octopress or hexo or hugo. Caddy has built-in support for Hugo.

**Comment by jungle-boogie** [comment]
SQLite may be considered over mysql as its even less work to setup than MySQL.

**Comment by My1** [comment]
Well nothing against sqlite, it is easy to use and also should be in there, but I'm afraid the number of software that supports sqlite is not comparable to mysql. 

Also for fastcgi I checked in the internet for "fastcgi windows" and thwre was a tutorial originally intended for nginx but the fastcgi setup steps are mostly the same. I'll check it later, on mobile right now.

**Comment by abiosoft** [comment]
In Nginx also, you need FastCGI for PHP :)

I initially considered this but it does not look that straightforward to implement. 

There seems to be preference for nginx+php-fpm over apache+mod_php already and this makes me favour sticking to FastCGI route.

Anyone is free to contribute this (even though I do not think it is worth it).

**Comment by My1** [comment]
Is fastcgi so much better than apache php? Because now I use xampp because it is seriously easy to use because pretty much everything is already there, webserver with php, optionally you have mysql, an ftp server, an email server and tomcat (whatever that might do)

**Comment by My1** [comment]
@coolaj86 you ask, I deliver.
but before so you know how many forum/blog etc. softwares are written in PHP? I would say: more than enough. also my whole programming life (ok almost) was with PHP I cant just simply start a new language.

--------------------
PHP for caddy mini tutorial (windows):
download caddy as you like (I got win64 without plugins)
download this http://windows.php.net/download/ (I used the x86 thread-safe version)
extract both to a nice location (I got php right in my caddy-dir/php)
make a php.ini (or just use one of the samples in the php folder)
make a batchfile for simple starting of fastcgi (which I put in the caddy folder, one level above the PHP folder, therefore I need to give the directory in the path)
```
PHP\php-cgi.exe -b 127.0.0.1:9000
```
the 9000 is the port which you can change but you need to reflect this on your caddyfile:
```
localhost:2020 {
gzip # <- compression
root c:\htdocs # <- your webroot
fastcgi / 127.0.0.1:9000 php # <- this line is important for PHP 
}
```
on windows it might be easier to make your caddyfile a textfile. I named mine caddyconf.txt for exmaple. then make a bat file for launching caddy
```
caddy -conf="caddyconf.txt"
```
you can name your caddyfile as you want but be sure to reflect the change in the bat or start caddy yourself.

as final step you just launch the fastcgi bat-file and then the caddy bat-file.

-------------------------------
so here you have it in full what I did to get my PHP running. you might want to change the php.ini when you got one of the samples. I for example needed to enable mysql/mysqli because it seemed to be off in the production ini

**Comment by alexbilbie** [comment]
I think you demonstrated for yourself @My1 that PHP doesn't need to be built in because it's so trivial to get fastcgi working with Caddy :+1:

**Comment by My1** [comment]
Well technically I am an IT professional (even if I ended my apprenticeship like just 3 months ago) so it is a lot easier for me. But anyone who just wants a running wordpress might not even know what fastcgi is. Also it never hurts to add it as a plugin

**Comment by alexbilbie** [comment]
There is an example of getting WordPress working here https://github.com/caddyserver/examples/tree/master/wordpress (discussion about examples can be found in #303)

**Comment by My1** [comment]
It was just an example. Replace wordpress with pretty much any php based software. Also on Windows you dont have you package manager or repos, so you would need to get all by yourself. And when talking about easy quicksetup then xampp at least in my experience beats all, since you have a webserver with php mysql and other stuff all there and you can disable each of the parts relatively easy over the gui.

**Comment by My1** [comment]
well about the plugin for PHP it could maybe be dont if the PHP you would usually just DL from the site is included into caddy and caddy launches that automatically that way everyone can add their extensions etc.

**Comment by DenBeke** [comment]
I was thinking about the same thing: built-in PHP plugin. Like e.g. MAMP.

To do this we would need to statically compile PHP with plugins and hope they don't rely on other libraries a user potentially doesn't have on his system. Would be nice though...

**Comment by mholt** [comment]
@abiosoft's Docker image of Caddy was updated to include a PHP-bundled variant: https://github.com/abiosoft/caddy-docker

```
docker pull abiosoft/caddy:php
```

**Comment by My1** [comment]
will there also be a way without some weird extra software? one of the best things of caddy is that it is lightweight (well with PHP it's being a bit heavier, but probably not that bad), portable, runs on its own and (supposed to be) easy to use.

I just want my zip with the exe and needed other stuff to run this thing on my windows machine with PHP, is there some way to get that?

**Comment by DenBeke** [comment]
@My1 If someone can create a portable PHP-FPM executable it could be possible :)

Regarding Mac, since OS X 10.8, OS X comes with PHP(-FPM) preinstalled, so this can come in handy for the Mac gui.
Remaining part is a portable/static MySQL installation...

**Comment by My1** [comment]
what is FPM?
at least I have been able to use a DL from php.net directly in a portable way with the php-cgi.exe (since caddy uses fastcgi)

a static MySQL, for that we might check what XAMPP is using as far as I know it doesnt do much to the system aside from giving the possibility to add services for auto-start and better control (only admins can mess with services) and similar but XAMPP is largely portable once you got that thing extracted, as far as I know.

**Comment by DenBeke** [comment]
PHP-FPM is the most commonly used FastCGI for PHP: http://php-fpm.org

**Comment by alexbilbie** [comment]
@My1 essentially FPM runs PHP as a seperate process that a webserver passes HTTP requests to. This is different from something like mod_php which is an embedded Apache module (i.e PHP runs as Apache)

**Comment by My1** [comment]
okay all worries are cleared now: "PHP-FPM is now included in PHP core as of PHP 5.3.3." so the version from http://windows.php.net/download/ should work with it already.

but when talking about PHP I think the user should be able to select a version when DLing caddy (similar to the plugins) because I think PHP7 is still too young.
or maybe even include multiple PHP versions to switch via caddyfile (maybe even up to directory/file-extension level, I've seen that already at some web hosting)

**Comment by alexbilbie** [comment]
@my1 I think perhaps you're asking for too much of Caddy. It would be more realistic if you were able to find a tool that lets you run an FPM process on Windows for which ever PHP version you want to run, and then run Caddy separately. This is a variation of what XAMPP does.

**Comment by My1** [comment]
well a lot of the stuff is just an Idea (especially the multiversion stuff)

but including PHP in a similar way as a "plugin" of some sort which could be auto-called and "managed" by caddy would be neat.

**Comment by abiosoft** [comment]
What you're asking for is outside the scope of Caddy. Even Apache requires installation of an additional module to get PHP support. You won't notice because there are tools that does the bundled installation.

What can be done is a similar installer that includes both Caddy and PHP-FPM or the creation of an independent CAMP (Caddy Apache MySQL PHP) project.

**Comment by My1** [comment]
well php cant be exactly "in" caddy is iirc clear enough, also a reason why I wrote the word plugin in "". plainly bundling and making it "work" (mostly by autostarting with caddy) would do it.
and with the point of plugin I also meant more for the Download way, because caddy can DL its plugins right on the site by selecting the proper checkbox and the idea is that the bundled PHP can be similarly selected for DL as a plugin.

**Comment by DenBeke** [comment]
The only thing that could work, would be having Caddy start PHP-FPM on start-up, and killing it together with Caddy. This way also other services could be launched through Caddy. (Like e.g. MySQL or Gogs).
This would be a new directive which specifies which scripts should run along with the virtual  host.

But actually bundling them together might not be in the scope of Caddy, this would lead to complex stuff. PHP executables are not the same on Windows, Mac, Linux, *BSD, so you'll need specific version for all of those systems. You then need to fix dependencies for all the used shared libraries.
Creating a LCMP (cfr how abiosoft called it.) Would need precise fine tuning for both MySQL and PHP, which are gigantic projects with dependencies, multiple executables, ...

**Comment by abiosoft** [comment]
There are two things involved
* Caddy
* PHP

All that can be done is just for the communication between the two. Which can be any of 
* Module (Apache)
* FastCGI (Nginx, Caddy)

Whatever communication method is used, PHP installation is still a requirement. Same as it is for other web servers.

**Comment by abiosoft** [comment]
Looks like @DenBeke suggestion looks most realistic (at least for now).

Caddy can start any process at startup https://caddyserver.com/docs/startup and the example used is even php. 

An additional line in the Caddyfile should not hurt.

**Comment by DenBeke** [comment]
> Caddy can start any process at startup https://caddyserver.com/docs/startup and the example used is even php.

What I meant was spawning PHP-FPM as a sub process, so it doesn't run PHP-FPM as a detached service/daemon, but runs PHP-FPM, and when Caddy "dies", PHP-FPM "dies" as well.

**Comment by abiosoft** [comment]
@DenBeke I get your point, but @mholt was critical of using Caddy as a mini process manager and believes that should be handled by external apps. Which I agree to some extent.

How do I know? When I added long running process support to Git, he objected to some use cases.

**Comment by DenBeke** [comment]
Yeah, it's just a suggestion here :)
Personally I think running PHP-FPM as another service is much cleaner, but people tend to want the "all-in-one solution".

**Comment by My1** [comment]
"Whatever communication method is used, PHP installation is still a requirement" well not really, I have it just lying around in my downloads directory and just run php-cgi.exe, so it doesnt need to be installed at all, it just have to lie around somewhere (obviously near caddy is best place).

**Comment by mholt** [comment]
Frankly I'd love to solve this with [caddy-lua](https://github.com/caddyserver/caddy-lua) - it's not PHP but it'd run in-process with no configuration required.

**Comment by jungle-boogie** [comment]
:+1: on caddy-lua

**Comment by mholt** [comment]
I'm going to close this because it won't be built into the Caddy process (even with a plugin - unless you somehow get a solid PHP interpreter written in pure Go) but discussion on the topic is still welcome if there's anything to add.

**Comment by My1** [comment]
well not directly into the process but as an "extra" that caddy can start and (more or less) manage, e.g. auto-select a free port to use it or whatever else might be needed

**Comment by alexandreteles** [comment]
I don't think that we need something like that. Caddy already have the
"startup" and "shutdown" directives that can easily be used to run a
external statically built fcgi binary. You just need to ship a static
binary of PHP, Lua or any other language, use the two directives on your
Caddyfile to start/stop the binary and use fcgi to connect to then. You can
see a example of a static compiled PHP fcgi exe here:
https://code.google.com/p/osspack32/downloads/detail?name=php-5.4.10_static.7z

*---*
*Alexandre Teles*
Bacharelando Interdisciplinar em Ciência e Tecnologia - *Universidade
Federal da Bahia*
Gerente de Infraestrutura Auxiliar - *Projeto Ekaaty Linux*
Tel.: +55(71)9262-7837 (TIM) - +55(71)8534-4536 (OI)
Skype: *kabbalista*
Facebook: https://fb.com/AlexandreSLTeles
Website: https://www.alexteles.com
Currículo Lattes: http://lattes.cnpq.br/9003865905026858

2016-01-20 10:38 GMT-03:00 My1 <notifications@github.com>:

**Comment by My1** [comment]
but for some reason the docker image has PHP inbuilt, so why not also for the "normal" version?

**Comment by alexandreteles** [comment]
The Docker image should ship with PHP installed on the container. Can
someone confirm if PHP is built in the Caddy binary on the Docker image?

*---*
*Alexandre Teles*
Bacharelando Interdisciplinar em Ciência e Tecnologia - *Universidade
Federal da Bahia*
Gerente de Infraestrutura Auxiliar - *Projeto Ekaaty Linux*
Tel.: +55(71)9262-7837 (TIM) - +55(71)8534-4536 (OI)
Skype: *kabbalista*
Facebook: https://fb.com/AlexandreSLTeles
Website: https://www.alexteles.com
Currículo Lattes: http://lattes.cnpq.br/9003865905026858

2016-01-20 11:06 GMT-03:00 My1 <notifications@github.com>:

**Comment by DenBeke** [comment]
Afaik, PHP is shipped within the docker image, not statically in Caddy... @abiosoft ?

**Comment by My1** [comment]
so the PHP runs alongside caddy instead of "in caddy", but if that's the case for the docker then it shouldnt be a problem to do pretty much the same with the "normal" version, or should it?

**Comment by abiosoft** [comment]
Of course PHP is **not** built in the caddy binary. It is installed separately in the container. In fact the default version does not include php, you need to pull the php variant.

**Comment by My1** [comment]
and it isnt hard to do the same with the normal version or is it?

**Comment by DenBeke** [comment]
In the "normal" Caddy version there are different operating systems that need to be supported. On Docker you create one image/configuration for one operating system, so you can adapt everything for that OS. You also can access system files and configurations, which you can't do from within Caddy.

Caddy is meant to be one single executable without extra config files and installations all over the system.

**Comment by faddat** [comment]
This seems like a plugin that could be selected on the download page, and it seems liek a GREAT one.  Let's talk about why caddy is so good.  Caddy is so good because it makes hosting things WAAAAAY easier.  What if Caddy could claim above all the others, I am not a pain in your ass when you have to do php.  

Caddy, we love caddy.

**Comment by captncraig** [comment]
I only see two options for how this could technically be possible within caddy, and I don't like either of them. 

1. If a static executable is available for php-fpm we could include it as bindata in source code for each platform. Extract and drop it to disk and start it when caddy starts up. This will lead to tons of huuuge source files, and really fragile processes when new platforms are supported.

2. Make cgo bindings for some php distribution and actually run it in the caddy process. This will have similar problems with testing and portability I fear.

 Perhaps as a plugin we care less about portability, but I doubt matt will even want to include such things in the build server for stability, and even security reasons.

**Comment by mholt** [comment]
^ You're right, and even plugins can't use cgo. (Well, they can, but not to be listed on the download page of the Caddy website.)

If you want PHP "bundled" in, use a Docker container (linked above) with php installed, or consider getting involved with caddy-lua (also linked above) to enable serving Lua apps with Caddy.

**Comment by faddat** [comment]
Assume that both of you are familiar?

https://github.com/stephens2424/php
https://github.com/deuill/go-php



Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by mholt** [comment]
I do remember seeing the first one some time ago. It's not a PHP interpreter, however. (Unless I missed something.) The second one is not acceptable for Caddy since it uses cgo.

**Comment by My1** [comment]
@mholt how does lua relate to PHP?

**Comment by mholt** [comment]
@My1 It doesn't, but the caddy-lua project can be built out to begin replacing PHP.

**Comment by My1** [comment]
but when lua replaces PHP you have to reqrite all your stuff in Lua, which certainly isnt what I wanna do, since I specialize in PHP/HTML/CSS

**Comment by mholt** [comment]
Then use PHP. This would be for new web apps.

**Comment by DenBeke** [comment]
PHP and Lua are completely different. Use the right tool for the job. You can't replace Lua with PHP and vice verse.

**Comment by mholt** [comment]
What I meant is you can do similar things with them. If your app is already in PHP, then leave it; if you find Lua to be better for your next app, then Caddy will (hopefully) one day be able to run it.

**Comment by My1** [comment]
but even then you have to learn a whole new language.

**Comment by mikorist** [comment]
Yes we can. With HHVM
![screen shot 2017-11-28 at 9 57 47 pm](https://user-images.githubusercontent.com/31393531/33344047-d4291aac-d487-11e7-868c-fcef334bab0c.png)

**Comment by diyism** [comment]
This caddy module can manage php-fpm from caddy server(automatically start and stop php-fpm): https://github.com/delfick/caddy-php-fpm

**Comment by francislavoie** [comment]
@diyism this issue is extremely old and no longer relevant. 

That said, these days we have https://frankenphp.dev/

**Comment by diyism** [comment]
@francislavoie  Thanks, I'll give a try to https://github.com/dunglas/frankenphp
