### ISSUE TITLE
gzip middleware does not adapt Content-Length header

### ISSUE THREAD

**Issue by mschoebel** [mholt/caddy#38]
Hi,

I have a simple server listening on port `9000`:

```go
package main

import (
	"fmt"
	"net/http"
)

func testHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "test\n")
}

func main() {
	http.HandleFunc("/test", testHandler)
	http.ListenAndServe(":9000", nil)
}
```

Caddy forwards requests and gzips responses:

```
0.0.0.0:8000
proxy /test http://localhost:9000
gzip
```

For the URL `http://localhost:8000/test` Chrome says `ERR_CONTENT_LENGTH_MISMATCH`.

```
$ curl -v localhost:9000/test
* Connected to localhost (127.0.0.1) port 9000 (#0)
> GET /test HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:9000
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Sat, 02 May 2015 10:25:03 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
<
test

$ curl -v -H "Accept-Encoding: gzip" localhost:8000/test
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /test HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8000
> Accept: */*
> Accept-Encoding: gzip
>
< HTTP/1.1 200 OK
< Content-Encoding: gzip
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
< Date: Sat, 02 May 2015 10:25:24 GMT
* Server Caddy is not blacklisted
< Server: Caddy
<
* transfer closed with 5 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 5 bytes remaining to read
```

It looks like the `Content-Length` header value from the backend response (`proxy` middleware) is not adapted by the `gzip` middleware. In this case (string `test\n`) the `Content-Length` should be > 30 bytes.

**Comment by mholt** [comment]
Was able to reproduce this. The gzip's ResponseWriter calls an underlying Write method, which returns:

`0, "Conn.Write wrote more than the declared Content-Length"`

Still not 100% sure why this is happening. (I hope that we don't have to buffer the proxy's output, then write it out ourselves...)

**Comment by mholt** [comment]
Okay, so the httputil.ReverseProxy type has a [ServeHTTP](http://golang.org/src/net/http/httputil/reverseproxy.go?s=2744:2819#L93) method that copies the entire header, including Content-Length. Then it immediately writes the response. Of course, by the time the response would be written and gzipped, Content-Length is already set.

Currently looking into a way of fixing this without copying the entire stdlib ReverseProxy and changing it.

**Comment by mholt** [comment]
I love Go. What a simple way to fix this.

```
func (w gzipResponseWriter) WriteHeader(code int) {
	w.Header().Del("Content-Length")
	w.ResponseWriter.WriteHeader(code)
}
```

@mschoebel Can you add these lines at [line 66](https://github.com/mholt/caddy/blob/9df9ad975d53db20f665787bd7c41a4ae4b094e1/middleware/gzip/gzip.go#L66) of gzip.go and confirm that it's working? Both your proxied pages and non-proxied pages, just to make sure I didn't break anything. But it all seems to be working here.

**Comment by abiosoft** [comment]
@mholt That works for me too

**Comment by mschoebel** [comment]
Works great. :+1:

**Comment by mholt** [comment]
Thank you for the clear report, and for trying the fix! Will be included with next release.

**Comment by icetech233** [comment]
> I love Go. What a simple way to fix this.
> 
> func (w gzipResponseWriter) WriteHeader(code int) {
>     w.Header().Del("Content-Length")
>     w.ResponseWriter.WriteHeader(code)
> }
> [@mschoebel](https://github.com/mschoebel) Can you add these lines at [line 66](https://github.com/mholt/caddy/blob/9df9ad975d53db20f665787bd7c41a4ae4b094e1/middleware/gzip/gzip.go#L66) of gzip.go and confirm that it's working? Both your proxied pages and non-proxied pages, just to make sure I didn't break anything. But it all seems to be working here.

why need del it
