### ISSUE TITLE
Supported cipher suit list

### ISSUE THREAD

**Issue by mxxcon** [mholt/caddy#380]
As originally brought up in #53 caddy(at least as of `v0.8-beta.4`) does not support all of the recommended cipher suits, while supporting apparently some of the less-desirable ones as reported by https://ssldecoder.org/.
Mozilla's https://wiki.mozilla.org/Security/Server_Side_TLS and https://mozilla.github.io/server-side-tls/ssl-config-generator/ for the "Intermediate" lists about 25-30 different ciphers. Their "Modern" profile has about 20 ciphers.
Meanwhile https://cipherli.st/ uses even simpler list `EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH`.
Would be nice if caddy supported:
* all of the mozilla's recommended suites
* short-hand notation the way cipherli.st has it.

**Comment by jungle-boogie** [comment]
The default ciphers and their order can be seen here:
https://caddyserver.com/docs/tls

https://ssldecoder.org complains about just these two:
ECDHE-RSA-DES-CBC3-SHA
DES-CBC3-SHA

You will notice these are the second to last and the last ciphers on the list from the link I provided.

ssllabs.com gives me an A for the configuration as is, even with the ciphers disliked above.

As we move into 2016, perhaps the disliked ciphers can be removed and perhaps the cipher TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)  could be moved in front of TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)

**Comment by jungle-boogie** [comment]
Of course by June 2016, I sincerely hope TLS 1.0 will be **removed** from the default configuration altogether in Caddy.

https://www.pcicomplianceguide.org/pci-dss-v3-1-and-ssl-what-you-should-do-now/

**Comment by mholt** [comment]
It will. And the DES ciphers will be removed from default configuration by the next patch release.

**Comment by mholt** [comment]
I guess this is solved with #412
