### ISSUE TITLE
"No such file or directory" in 0.8

### ISSUE THREAD

**Issue by jojomi** [mholt/caddy#386]
After updating caddy executable from 0.8 beta to 0.8, something seems to have changed.
My docker image fails to execute now telling me
    
    no such file or directory

Unfortunately there is no `--verbose` flag or anything I can find to debug this further.

I have cloned my [docker-caddy repository](https://github.com/jojomi/docker-caddy) and ran
     
    docker build --no-cache=true -t jojomi/caddy . && docker run -v $(pwd)/app:/app jojomi/caddy

with old and new `caddy` binary. Additionally I created an empty file `app/Caddyfile` for testing purposes. With 0.8 beta this container spawns, version 0.8 shows above the error.

Can anyone give a hint on what might have changed? Perhaps something related to letsencrypt?

**Comment by mholt** [comment]
You're running this in Docker? Does it have a $HOME folder? What's your Caddyfile look like?

**Comment by abiosoft** [comment]
This could be due to non-static binary.

**Comment by mholt** [comment]
Ah, flip - I probably forgot to re-run make.bash with CGO_ENABLED=0.

* facepalm *

Will do it tomorrow so downloads are completely static again.

Even if that's not the problem, I need to do this. Thanks for the reminder :smile:

**Comment by jojomi** [comment]
Sounds like that could be the problem, because I built the exactly same container otherwise. Waiting for your new build :-).

**Comment by mholt** [comment]
Okay, I think this is fixed; downloads should now be fully static again. See if that fixes it!

**Comment by jojomi** [comment]
Fixes it for me. Thanks for updating!
