### ISSUE TITLE
Explicit Port 80 makes Caddy try and get a LE cert

### ISSUE THREAD

**Issue by Moter8** [mholt/caddy#391]
```
:80 {        # https://caddyserver.com/docs/caddyfile
  gzip
  browse
  ext .html
  log access.log
  header /api Access-Control-Allow-Origin *

  root www/
}

chag.xyz:80, chagemann.de:80 {
  root www/portfolio/build
}
```
This config file makes Caddy try to automatically get a cert from LE, despite the [docs](https://caddyserver.com/docs/automatic-https) saying that it shouldn't happen if the port is explicitely `:80`:
```
2015/12/05 22:33:55 [chag.xyz] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: chag.xyz
```

I have to include `tls off` into the second block in order for it to work.

**Comment by mholt** [comment]
Will look into this soon by trying to replicate the behavior; it shouldn't happen.

**Comment by mholt** [comment]
This is fixed locally and will be pushed soon. Thanks!

**Comment by purcell** [comment]
Didn't easily find the commit which fixes this, but I just thought I'd note here that the same thing happens with the `http://` prefix -- hopefully the fix covers both cases.

**Comment by mholt** [comment]
Yeah, it's not pushed yet. That's fixed.

**Comment by purcell** [comment]
Awesome, thanks for the confirmation.
