### ISSUE TITLE
SSI - server side includes ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#392]
Any plans for SSI support in Caddy ? Ideally to follow Nginx's supported syntax http://nginx.org/en/docs/http/ngx_http_ssi_module.html ?

I ask as I use SSI extensively in Nginx :)

**Comment by mholt** [comment]
I've thought about adding it, maybe to make it easier for people to switch from nginx or Apache (as I used SSI all the time myself) but [templates](https://caddyserver.com/docs/template-actions) are much more powerful, easier to use, and can be swapped in with a search & replace.

**Comment by centminmod** [comment]
i hope you can add support i'm trying to envision how it would work for me as my Centmin Mod LEMP stack is Nginx now, but i plan to integrate other web servers into the stack, Apache 2.4, h2o and openlitespeed. Caddy is on the list to evaluate too. The goal is to being able to serve a site from common vhost structure interchangeably between Nginx, Apache 2.4, h2o and openlitespeed and maybe Caddy.

**Comment by mholt** [comment]
Well I won't ask you to hold your breath, then, because although I've fiddled with the idea, Caddy is a progressive web server and is supposed to do things differently from the other ones. So SSI doesn't really fit in with the goals of Caddy in the long run...

**Comment by centminmod** [comment]
ok no probs.. thanks for the heads up :)

**Comment by kidwm** [comment]
@mholt So is it possible to write such addon in current architecture?

**Comment by mholt** [comment]
@kidwm Of course. Although, as I've said, templates do the same job of SSI and more. A plugin would only be helpful for older/legacy sites.

**Comment by indeyets** [comment]
Is it possible to get equivalent of ssi's `include virtual` via templates? Not obvious from the docs

**Comment by mholt** [comment]
@indeyets Yes; the include path, if absolute, is relative to the site root.

**Comment by indeyets** [comment]
Will it do http sub-request? Documentation tells about files, so I interpreted that as simple file inclusion

**Comment by mholt** [comment]
@indeyets No, not for including files. Just loads from disk and inserts the contents there.

**Comment by indeyets** [comment]
So, that's not `virtual` then

**Comment by mholt** [comment]
What's the use case for a sub-request?

**Comment by indeyets** [comment]
The most common scenario is having several applications which dynamically generate pieces of html markup (blocks). For example: banner-code generator, or application which generates contents-area of the website.

Such dynamic pieces are wrapped in a static template and it is a usual practice to use SSI for such templates.

**Comment by mholt** [comment]
@indeyets If you open a new issue as a feature request, we can track that better.

It would probably be implemented as something like `{{.HTTPInclude "..."}}`.
