### ISSUE TITLE
LE: ambiguous error message

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#393]
Problem
=======

It takes about a minute from `Activating privacy features...` and waits and waits and then fails, but it's not clear to me why it failed or what my course of action should be from there:

```bash
sudo ./caddy -agree=true -conf Caddyfile -email=coolaj86@gmail.com
Activating privacy features...
2015/12/06 03:51:44 [blog.coolaj86.com] failed to get certificate: The server could not validate our request.
```

(note to self: use the setcap thing to make 80 a non-sudo port)

.

.

.

.

.

.

.

.

.

Update: the issue was that the LE dns resolver uses WaCKy CasE and by DNS server didn't support it. However, the ambiguity problem of the message stands.

This is how I installed Caddy on my RPi:

```bash
wget 'https://caddyserver.com/download/build?os=linux&arch=arm&features='
mv build* caddy.tar.gz
mkdir caddy
pushd caddy
tar xvf ../caddy.tar.gz
```

This is my Caddyfile

`cat caddy/Caddyfile`:
```
blog.coolaj86.com
```

A Note on Port Forwarding
-------

I am using port forwarding. If caddy is selecting a dvsni port other than 443, I need the ability to specify that port so that I can make sure it gets forwarded.

Sanity checks
===========

I've logged into coolaj86.com, what the IP address?

```bash
ping coolaj86.com
PING coolaj86.com (67.166.110.237) 56(84) bytes of data.
64 bytes from c-67-166-110-237.hsd1.ut.comcast.net (67.166.110.237): icmp_req=1 ttl=64 time=0.792 ms
```

I believe blog.coolaj86.com is also coolaj86.com, is that correct?

```bash
ping blog.coolaj86.com
PING blog.coolaj86.com (67.166.110.237) 56(84) bytes of data.
64 bytes from c-67-166-110-237.hsd1.ut.comcast.net (67.166.110.237): icmp_req=1 ttl=64 time=0.702 ms
```

Yes it is.

Can I get to http://blog.coolaj86.com with caddy?

`cat caddy/Caddyfile`:
```
http://blog.coolaj86.com:80 {
  browse
}
```

```bash
sudo ./caddy -conf Caddyfile
Activating privacy features...
(wating for 30 seconds or so)
2015/12/06 04:13:49 [blog.coolaj86.com] failed to get certificate: Could not start HTTPS server for challenge -> listen tcp :443: bind: address already in use
```

okay, looks like I'll have to stop my webserver and try again

```bash
sudo ./caddy -conf Caddyfile
Activating privacy features...
(wating for 30 seconds or so)
2015/12/06 04:15:43 [blog.coolaj86.com] failed to get certificate: The server could not validate our request.
```

This cannot be tested. Citing issue https://github.com/mholt/caddy/issues/391

**Comment by mholt** [comment]
Crypto on the Raspberry Pi is slow -- it is not uncommon for the LE challenges to take upward of a minute to complete for a domain.

You can get more information about the challenge process using `-log`, like `-log stderr` - which should let you know if the ACME server is able to reach the solver or not.

The error message, "The server could not validate our request" is as much as we know (otherwise we would definitely tell you more). The ACME server responds to our poll with [a status of "invalid"](https://letsencrypt.github.io/acme-spec/#authorization-objects) and that's all we know.

**Comment by coolaj86** [comment]
Interesting, the python client `letsencrypt` gives much more detailed error messages.
See https://github.com/letsencrypt/boulder/issues/1244

I'll ping over there to ask how they're doing it.

Good news about the key slowness: ECDSA support is coming. ECDSA 256-bit keys are cryptographically stronger than RSA and *much* less computationally expensive.

**Comment by mholt** [comment]
True, EC will be nice.

We'll look into better error messages; this belongs more in xenolf/lego - but we've already talked about it. Thanks!
