### ISSUE TITLE
Changes to project organization

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#395]
This project is growing and I'm really loving how the community is turning out. One of my favorite things is being able to personally attend to every question, issue, pull request, and contributor to the level of detail that they deserve. With the demand, though, I'm not sure how much longer I can keep it up!

Caddy is an open source project built entirely on donated time and talent -- thank you, to all who have contributed -- we do it because we love the Web, Go, and it's a lot of fun! But seeing as I can't make a living off of this, it's going to continue to get harder for me to balance my life with this project. I love it, but my life immediately around me (family, school, work, etc.) obviously takes priority.

There's a lot of different aspects that make Caddy possible. It used to just be the core server, middleware, a website, and some documentation. I could manage all that. But now I'm starting to get a little overwhelmed. In order to ensure I don't hinder the growth and progress of Caddy, I propose that we group Caddy into separate, but tightly coupled, projects:

![caddy-organization](https://cloud.githubusercontent.com/assets/1128849/11611430/2b9397e2-9b8a-11e5-9185-70d54b1f29aa.png)
<sup>Figure A. Proposed project structure. (Don't read too much into this. Placement and ordering doesn't really matter.)</sup>

- **Build Server** The back-end software that powers the [Download](https://caddyserver.com/download) page. Produces custom builds of Caddy on-demand.

- **Middleware** All the middleware components located in the [middleware](https://github.com/mholt/caddy/tree/master/middleware) folder. These give Caddy its magic powers.

- **Production Ops** Caddy is a web server, but being one, is closely tied to sysadmin tasks which prepare the system to run a web server. I never intended to get into this because production environments are harsh and highly varied, but we've had a lot of issues, questions, and blog posts about this. People are skeptical that Caddy can be used in production, but I am confident that Caddy belongs in production as much as it does in dev. This team will help make Caddy easy to run in production.

- **Distribution** This team will package up Caddy for Linux repos (apt-get, yum, ...), homebrew, and others, maintain the install script at [getcaddy.com](https://getcaddy.com) (which right now is just an experiment), and help make Caddy generally available to as wide an audience as possible. I'd love to see it on the Android and iPhone app stores some day.

- **Website** This is, obviously, the Caddy website. Marketing, but also the download page.

- **Documentation** This aspect includes the docs on the website, the developer wiki on GitHub, the main README.md file, the README.txt file in the dist folder, and the godoc comments.

- **Plugins** This is an umbrella for all the various Caddy plugins (add-ons). Each plugin author is of course responsible for their own plugin but it'd be good to have a way to coordinate them all, especially where plugins may overlap or use code from one another.

- **API** In version 0.9, Caddy will get an API. This aspect is all about the API's endpoints and client development.

- **Plugin Tooling** Caddy developers benefit from caddydev and caddyext right now, but these tools need real names (might as well) and better unification, if possible. Anyway, developing plugins without these tools is very inconvenient, so they deserve our attention.

---------------

I'd like to appoint some volunteers to head up these projects and be the decision-makers for these aspects of Caddy. Of course I'm still able to provide direction where necessary, but I'd like to spread out the autonomy across all these aspects without me having to oversee/approve everything. This way the project can continue to progress without being hindered by my lack of time for it all.

To clarify, I'm not withdrawing from the project. :smile: I'm just trying not to be spread too thin.

**Update (March 7, 2016):** No longer looking to segment the project into these "buckets" but, instead, to give more people commit rights to the project. See [this comment](https://github.com/mholt/caddy/issues/395#issuecomment-193496422).

### Thoughts? Volunteers?

I dunno how this is going to go over with everyone else, so what do you think about this? Expectations for project leads aren't any different from regular contributions; it's basically just a more focused approach to development and directing questions to a project manager or lead contributor for that aspect of Caddy, rather than always to me.

Let me know what you think. If you'd be willing to be a project lead for one of these aspects, also let me know and I'll see about assembling a good team and making sure you have push rights, etc.

**Comment by mholt** [comment]
For what it's worth, I'll still oversee Caddy core and probably be heavily involved with website, API, build server, and documentation, at least in the short term. (Did you know? A new build server is already under way.)

**Comment by acmacalister** [comment]
I think it is a good idea. I help my brother with a couple repos that are way less traffic than caddy I know how exhausting it can be responding to everyone. Sharing the load will keep you from getting burned out and keep the caddy project growing. I like the project structure you proposed. Those seem like logical divisions of skills, interest, etc. for each project.

That being said I would be happy to help with whatever. Personally I think I would be most helpful working on the middleware project as that is what I have done in the past and is most relevant for what I use caddy for. I looked at couple of a the reverse proxy issues that have been opened up and think I could address most of those pretty easily. I also want to move some of my static sites over to using caddy and should have some bandwidth in the coming weeks to look at creating some caching middleware for those sites.

**Comment by abiosoft** [comment]
This is a good decision for the progress of the project. I really appreciate and I am pretty impressed with how much time you devote to the maintenance of a growing project like this. You have managed to get it this far and I think you have made the right decision.

My main contributions have revolved around Middleware, Plugins and Plugin Tooling. I am also pretty familiar with the different parts of the codebase bar API. I think I am best suited to those three but I am willing to help out in any aspect as I have been doing. 

I also share the opinion that caddydev and caddyext may need to be merged for better all round experience.

Well done.

**Comment by dencold** [comment]
Hey Matt, I haven't (yet!) contributed to Caddy, but I just wanted to chime in here and add to the gratitude and praise others have shown. Thank you so much for all the time you have devoted to the project, it is a true inspiration to me to see all the progress you've made with the server.

Splitting things up and getting some extra help to help on the issue tracker and prioritization are the right steps to take. Hopefully after I've gotten a couple of pull requests under my belt I'll be in a place to be more helpful. 

For now. Thank you for everything you've done here! Big fan of caddy!

**Comment by Unknwon** [comment]
Awesome idea! Big step push forward!

**Comment by captncraig** [comment]
I think it is an ok, idea, but would caution against over-organizing too early. Would not be good to get into a situation where such and such can't be touched because it is so and so's domain only. It does seem this is growing beyond an individual effort and that is great.

There is a fairly active community, and lots of people willing to contribute. I am happy to contribute where I see a need, but also have a hard time wanting to pick a "bucket". I'd consider myself more general purpose / miscellaneous stuff.

**Comment by nicholasa** [comment]
I've reached out to a RH consultant to have a public yum package. Is there a repo to store things like SPEC files or signed package keys?

**Comment by mholt** [comment]
@nicholasa Thanks for doing that; not yet, but let's chat [on gitter](https://gitter.im/mholt/caddy) about it or in a new issue rather than in this one.

@captncraig Yeah, that's something that I'm trying to be sensitive to. Leading an aspect isn't so much about ownership as it is about coordinating and delegating the decision-making.

Thanks for those who have commented so far, I'm taking notes. :smile: Further feedback and suggestions are welcome.

**Comment by joeblew99** [comment]
Wish I could help. This is really great package, and fantastic for the golang community. When I get time I will come back for sure, and see what I can help with.

**Comment by joeblew99** [comment]
Wish I could help. This is really great package, and fantastic for the golang community. When I get time I will come back for sure, and see what I can help with.

**Comment by joeblew99** [comment]
Oops double post...

**Comment by hubertbanas** [comment]
I like the idea. Count me in.

**Comment by Xe** [comment]
@wafture https://github.com/Xe/rpmspecs/tree/master/caddy https://copr.fedoraproject.org/coprs/xena/caddy/

**Comment by wafture** [comment]
@Xe while i'm not opposed to using systemd, it cuts out a severely large portion of servers, essentially anything below 7.x. It might be the future but millions of servers are still rockin 6.x, like all 5000 of the servers i manage during the day for example.

**Comment by Xe** [comment]
Yeah, I get that. I'd be willing to take a patch for RHEL 6 support. I just need a sysvinit script.

**Comment by dprandzioch** [comment]
Looks like a good idea although I see "production ops" and "distribution" somewhat combined because their responsibility overlaps for me, if I'm wrong it would be nice to have a clear separation in the description. 

I'm not able to help on a daily basis but I would be glad helping with some pull requests as well as filing issues for enhancement and design ideas from time to time, especially addressing packaging for the various Linux and BSD flavors (maybe we could provide init scripts and sample configuration within the `dist/` folder of the repository as well as a packaging system based on Vagrant or Docker for automatically building packages for the respective distribution) as well as API server and client design, if desired (I'm working in API development almost all day and could provide client libraries for PHP and Ruby as well as maybe Python and Swift).

**Comment by mholt** [comment]
Hey everyone, sorry it's taking me some time to get around to this. I wanted to leave the issue open long enough to give more people a chance to see it and participate. I think we're having a pretty good response and I should have responded to this sooner!

I will be very happy to accept all of you into the project and to have you contribute simply where your expertise is or where you feel a certain amount of interest. I'm also thinking of giving commit rights to everyone who has submitted non-trivial, merged PRs. Node.js does something like this, and I like their model for a growing open source project: https://medium.com/the-javascript-collection/healthy-open-source-967fa8be7951

This'll hopefully grow our base of maintainers and hopefully bring more people back to improving the project by getting involved in bug fixes, code reviews, etc. I'm still mulling the details of this over in my head, but I'd like to know what you think of this.

**Comment by mholt** [comment]
@dencold What's your availability look like as far as contributing? I'll help onboard you.

@wafture Should those be in this repo or something separate? I know nothing when it comes to this stuff. :smile:

@hubertbanas Are you still interested in contributing again? If so, I'll give you push rights so you can help with issues and PRs when you can.

@dprandzioch and @acmacalister Thanks for your contributions so far! You're both collaborators now (Austin has been for a while, woo hoo!), so feel free to contribute whenever you are able and with whatever interests you. You have both already been a significant part of what makes Caddy great!

@Unknwon Of course I'd welcome contributions from a talented engineer such as yourself. :smile: But Gogs is so cool, you know? It must demand a lot of your time!

@captncraig I hear ya, so I'm gonna give people collaborator status and let the contribute how and when they wish. I hope that having more collaborators will be able to help with reviewing and merging PRs and spreading out the load of fixing bugs, etc.

**Comment by hubertbanas** [comment]
Absolutely. I will try to help as much as I can.

**Comment by Unknwon** [comment]
Go go go! :blush:
