### ISSUE TITLE
How to run own custom SSL certificate but not force HTTP to HTTPS redirect ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#396]
After reading https://caddyserver.com/docs/automatic-https, how would I go about configuring Caddy to serve a site using a custom SSL certificate (i.e. wildcard ssl so not LE SSL cert) + DO NOT force the HTTP to HTTPS redirect so I can test on both HTTP and HTTPS protocols ?

Also how about all above but not listening on port 443 but something like 445 ?

> Certificate and key files are not already specified by you

I guess defining my custom SSL cert is enough to disable Caddy auto LE cert deployment/setup but what about not forcing the HTTP to HTTPS redirect ?

cheers

George

**Comment by centminmod** [comment]
I tried something like this with HTTP port 81 and HTTPS port 445 but the sites are not loading ?

Caddyfile contents at https://gist.github.com/centminmod/ca5830b089a3bdb3b979

**Comment by mholt** [comment]
Example:

```
example.com:445

tls wildcart.crt wildcard.key
```

Should do everything you want. No automatic redirect, custom port, and your own wildcard certificate. (Just like before version 0.8.)

**Comment by centminmod** [comment]
cheers got that working but this Caddyfile https://gist.github.com/centminmod/ca5830b089a3bdb3b979 isn't working if i try to setup HTTP port 81 and HTTPS port 445 for Caddy ? 

Caddyfile format correct for multiple hosts ?

**Comment by mholt** [comment]
Mostly - I'm surprised you're not getting an error because I think you're missing a closing curly brace on the line after 29: https://gist.github.com/centminmod/ca5830b089a3bdb3b979#file-caddyfile-L29 - maybe you could clarify what "isn't working" means.

**Comment by centminmod** [comment]
not working as in sites on port 445 or 81 didn't load 

but your pin pointed line 29 is the culprit ! thanks added missing curly brace and it's working nicely now :)

thanks Matt :+1:

**Comment by mholt** [comment]
Ah, cool - still, I'm gonna make sure the parser is throwing errors appropriately in that case ;) Glad you got it working.

**Comment by mholt** [comment]
Update: I tried starting Caddy with your Caddyfile and I got a parse error; Caddy wouldn't even start, as expected. So that all seems to be working properly. Not sure how you got it to start O.o
