### ISSUE TITLE
Is OCSP stapling enabled if custom SSL cert/key defined in tls directive ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#397]
I tested Caddy with Caddyfile with specific defined custom cert/key on port 445 but both cipherscan and testssl are reporting OCSP as not enabled or not offered ? According to https://caddyserver.com/docs/automatic-https OCSP is automatically enabled for tls but is that only if Caddy auto generates the LE SSL cert and HTTPS setup ?

Plan is to put Caddy up against other web servers on the same server similar to https://h2ohttp2.centminmod.com/flags.html so trying to make sure Caddy configuration is as close to the rest of the web servers and that I have Caddy properly configured. Not sure what I am missing for OCSP support in Caddy ? Thanks !

Caddyfile using a LE SSL cert I already generated from my Centmin Mod LEMP stack LE integration

    le12.http2ssl.xyz:445
    gzip {
            level 6
    }
    browse
    #tls off
    tls /etc/letsencrypt/live/le12.http2ssl.xyz/fullchain.pem /etc/letsencrypt/live/le12.http2ssl.xyz/privkey.pem {
            protocols tls1.0 tls1.2
            ciphers ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-CBC-SHA ECDHE-RSA-AES256-CBC-SHA ECDHE-ECDSA-AES256-CBC-SHA ECDHE-ECDSA-AES128-CBC-SHA RSA-AES128-CBC-SHA RSA-AES256-CBC-SHA ECDHE-RSA-3DES-EDE-CBC-SHA RS$
    }
    root /home/nginx/domains/le12.http2ssl.xyz/public

    fastcgi / 127.0.0.1:9000 {
            ext   .php
            split .php
            index index.php
    }

    log /opt/caddy/le12.http2ssl.xyz-access.log {
            rotate {
                    size 100 # Rotate after 100 MB
                    age  14  # Keep log files for 14 days
                    keep 10  # Keep at most 10 log files
            }
    }

cipherscan output for caddy on port 445

    cipherscan le12.http2ssl.xyz:445         
    .......................
    Target: le12.http2ssl.xyz:445
    
    prio  ciphersuite                  protocols              pfs                 curves
    1     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
    2     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
    3     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
    4     AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
    5     AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
    6     ECDHE-RSA-DES-CBC3-SHA       TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1,secp384r1,secp521r1
    7     DES-CBC3-SHA                 TLSv1,TLSv1.1,TLSv1.2  None                None
    
    Certificate: trusted, 2048 bits, sha256WithRSAEncryption signature
    TLS ticket lifetime hint: None
    OCSP stapling: not supported
    Cipher ordering: server
    Curves ordering: server - fallback: no
    Server supports secure renegotiation
    Server supported compression methods: NONE
    TLS Tolerance: yes

cipherscan output for nginx on port 443

    cipherscan le12.http2ssl.xyz:443
    ............................
    Target: le12.http2ssl.xyz:443
    
    prio  ciphersuite                  protocols              pfs                 curves
    1     ECDHE-RSA-CHACHA20-POLY1305  TLSv1.2                ECDH,P-256,256bits  prime256v1
    2     ECDHE-RSA-AES128-GCM-SHA256  TLSv1.2                ECDH,P-256,256bits  prime256v1
    3     ECDHE-RSA-AES256-GCM-SHA384  TLSv1.2                ECDH,P-256,256bits  prime256v1
    4     DHE-RSA-AES128-GCM-SHA256    TLSv1.2                DH,2048bits         None
    5     DHE-RSA-AES256-GCM-SHA384    TLSv1.2                DH,2048bits         None
    6     ECDHE-RSA-AES128-SHA256      TLSv1.2                ECDH,P-256,256bits  prime256v1
    7     ECDHE-RSA-AES128-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
    8     ECDHE-RSA-AES256-SHA384      TLSv1.2                ECDH,P-256,256bits  prime256v1
    9     ECDHE-RSA-AES256-SHA         TLSv1,TLSv1.1,TLSv1.2  ECDH,P-256,256bits  prime256v1
    10    DHE-RSA-AES128-SHA256        TLSv1.2                DH,2048bits         None
    11    DHE-RSA-AES128-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,2048bits         None
    12    DHE-RSA-AES256-SHA256        TLSv1.2                DH,2048bits         None
    13    DHE-RSA-AES256-SHA           TLSv1,TLSv1.1,TLSv1.2  DH,2048bits         None
    14    AES128-GCM-SHA256            TLSv1.2                None                None
    15    AES256-GCM-SHA384            TLSv1.2                None                None
    16    AES128-SHA256                TLSv1.2                None                None
    17    AES256-SHA256                TLSv1.2                None                None
    18    AES128-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
    19    AES256-SHA                   TLSv1,TLSv1.1,TLSv1.2  None                None
    
    Certificate: trusted, 2048 bits, sha256WithRSAEncryption signature
    TLS ticket lifetime hint: 3600
    OCSP stapling: supported
    Cipher ordering: server
    Curves ordering: server - fallback: no
    Server supports secure renegotiation
    Server supported compression methods: NONE
    TLS Tolerance: yes

**Comment by mholt** [comment]
No - OCSP stapling is only implemented for managed ACME certificates.

**Comment by centminmod** [comment]
Thanks Matt - any change of getting OCSP working on custom defined tls directive certs ?

**Comment by mholt** [comment]
Yeah, I don't see why not -- just a matter of manpower right now!

**Comment by centminmod** [comment]
no worries - definitely understand time and resource limitations of working on an open source project :)

**Comment by mholt** [comment]
@centminmod I believe this is fixed upstream in the branch; when I merge this into master will you be able to test it again by building from source?
