### ISSUE TITLE
gzip_min_length ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#398]
Hi is there a nginx equivalent to gzip_min_length so to tell Caddy only gzip files of minimum length and higher ?

**Comment by mholt** [comment]
Not at this time. PRs welcome!

**Comment by centminmod** [comment]
cheers.. unfortunately I'm no GO coder heh

**Comment by abiosoft** [comment]
I'll help with this. 

It is gonna rely on `Content-Length` header as nginx's gzip_min_length also does.

**Comment by abiosoft** [comment]
My assumption was wrong, `Content-Length` will not be used in Caddy's case.

**Comment by abiosoft** [comment]
My initial assumption was correct :smile:

**Comment by abiosoft** [comment]
The feature will be available in the next patch release or right now if you build from source.
