### ISSUE TITLE
per vhost config files ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#399]
Is there support or planned support for per vhost site config files and an include directory to read them ? Similar to Nginx so

    include /opt/caddy/conf.d/*.conf

then in /opt/caddy/conf.d/ you could have per vhost config files ?

    sitea.com.conf
    siteb.com.conf

Would be great so you can script a Caddy vhost file generator for each site :)

**Comment by mholt** [comment]
Yeah, actually, see #385 - I think when this lands it should do what you want?

**Comment by centminmod** [comment]
no GO programmer, so can't say for sure.. but if it allows in your main Caddyfile to specify a directory wildcard /opt/caddy/conf.d/*.conf to other vhost.conf files, then excellent :)

**Comment by mholt** [comment]
Yes, it allows you to import a glob of files using `*`. Will be available soon then!
