### ISSUE TITLE
custom log format - missing user-agent ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#400]
I am trying to replicate as close to possible the log format Nginx users but I can not found the user-agent placeholder https://caddyserver.com/docs/placeholders ? Is there one ?

**Comment by mholt** [comment]
That's just a header, right? `{>User-Agent}` should do the trick.

**Comment by centminmod** [comment]
cheers so like this ?

    log /opt/caddy/le12.http2ssl.xyz-access.log "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency}" { 
        rotate {
                size 100 # Rotate after 100 MB
                age  14  # Keep log files for 14 days
                keep 10  # Keep at most 10 log files
        }
    }

**Comment by mholt** [comment]
That's how I'd do it!

**Comment by centminmod** [comment]
thanks.. strange  though haven't had any logged entries since the change even after visiting the site 

    IP - [07/Dec/2015:00:37:33 +0000] "GET / HTTP/2.0" 200 548
    date
    Mon Dec  7 17:59:22 UTC 2015

any further debug mode logging available ?

**Comment by mholt** [comment]
Is that a log entry generated by the format you specified above? They don't seem to match, and what's with the newlines?

**Comment by centminmod** [comment]
Oh the last 2 lines was date of system when i did the tail on the log to show that there was like ~17hrs 26mins since the last log entry in the log

the format shown above is the default log format, since switching to the custom format no new log entries have been logged even after visiting the sites

**Comment by mholt** [comment]
Oh, I just noticed you're missing the base request path to match in order to log the request. Change your first line to:

```
log / /opt/caddy/le12.http2ssl.xyz-access.log "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency}" {
```

(notice the extra `/` at the beginning, according to the [log](https://caddyserver.com/docs/log) format. Right now you probably have a file called  "{remote} {when} {method} {uri} {proto} {status} {size} {>User-Agent} {latency}" on your system somewhere. :smile:)

**Comment by centminmod** [comment]
doh thanks for catching that :)
