### ISSUE TITLE
[HELP] Https Caddy Server

### ISSUE THREAD

**Issue by PabloCariel** [mholt/caddy#401]
Error: Activating privacy features...
2015/12/06 20:39:45 [pablo.sundde.dev] failed to get certificate: The server could not validate our request.

[hosts]
192.168.1.1       pablo.sundde.dev

[Caddyfile]
pablo.sundde.dev

Help Me Please.
THX

**Comment by mholt** [comment]
Where is the 192.168.1.1 coming from? (It isn't in your Caddyfile?)

**Comment by abiosoft** [comment]
@mholt that is from his hosts file `/etc/hosts`, I guess.

**Comment by mholt** [comment]
Oh, gotcha.

I just noticed the domain ends in .dev -- Let's Encrypt is probably not able to issue a certificate for internal domain names.

You *could* set up your own [Boulder](https://github.com/letsencrypt/boulder) instance and use that as your CA, but you'd have to add your Boulder instance to the trust store of all the computers that use them or you'll get certificate errors in the browser.

**Comment by PabloCariel** [comment]
[/etc/hosts]
172.16.1.109    rdsitr.com

[Caddyfile]
rdsitr.com

[run]
./caddy

[ERROR]
Activating privacy features...
2015/12/08 14:32:35 [rdsitr.com] failed to get certificate: The server could not validate our request.

Help Me please.

**Comment by mholt** [comment]
Run caddy with `-log stderr` to get more information, then report back here.

**Comment by PabloCariel** [comment]
[run]
./caddy -log stderr

[error]
Activating privacy features...2015/12/08 14:47:00 [INFO] acme: Obtaining bundled certificates for spdy.life
2015/12/08 14:47:00 [INFO] acme: Trying to solve HTTP-01

2015/12/08 14:47:02 [spdy.life] failed to get certificate: The server could not validate our request.

**Comment by PabloCariel** [comment]
./caddy -log=stderr 
Activating privacy features...2015/12/08 14:49:03 [INFO] acme: Obtaining bundled certificates for spdy.life
2015/12/08 14:49:04 [INFO] acme: Trying to solve TLS-SNI-01

2015/12/08 14:49:06 [spdy.life] failed to get certificate: The server could not validate our request.

**Comment by mholt** [comment]
You said your Caddyfile is this:

```
rdsitr.com
```

But Caddy is serving spdy.life. What is your Caddyfile that you're using?

**Comment by PabloCariel** [comment]
No change domain /etc/hosts to spdy.life

**Comment by PabloCariel** [comment]
[Caddyfile]
spdy.life

[/etc/hosts]
172.16.1.109    spdy.life

**Comment by mholt** [comment]
Right, okay, so that domain (spdy.life) isn't registered. You'll have to purchase the domain name from a registrar before you can use it. Let's Encrypt doesn't read your hosts file. It issues certs for public domains only.

**Comment by bradparks** [comment]
Ahhh.... So this means that the LetsEncrypt certificates can't be used to test internal domains? And I can't for example set  `microsoft.com` to point to 127.0.0.1 in my local `/etc/hosts` file, and run a local site using caddy for that, correct? 

This makes sense once I hear it of course - otherwise, any hacker would be able to run a fake "paypal" or any site at all, and the SSL cert for it would look completely legit, thus tricking a user into supplying their real username/password to a fake site!

And to be clear, this is a `LetsEncrypt` security check, and has nothing to do with Caddy at all, right? Thanks for the info!

**Comment by mholt** [comment]
@bradparks Correct. You can run your own ACME server, like a Boulder instance, on your local network, but the certificates will not be trusted unless users install your root certificate.

**Comment by bradparks** [comment]
:+1:
