### ISSUE TITLE
equivalent to nginx default_server ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#403]
Does Caddy have an equivalent to default_server so that any domains with with dns pointing to a Caddy server can redirect to default_server if there is not a specific host config setup for it in the Caddyfile ?

cheers

George

**Comment by mholt** [comment]
I believe if you specify the address as something like `:80` (for example) that should do what you want.

**Comment by jojomi** [comment]
This seems to work for me. Since my caddy server was listening on port `2015` I configured it like this:

```
:2015 {
    tls off
    ...
}
```

Thanks for the hint. Is it documented somewhere?

**Comment by mholt** [comment]
Kind of implicitly, in the [Caddyfile docs](https://caddyserver.com/docs/caddyfile) but I could probably make it clearer.

Also, PS., you don't need `tls off` for an address like `:2015` - doesn't hurt to have it, but I think Caddy figures that out by itself.
