### ISSUE TITLE
Remove 3DES ciphers from default TLS config

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#405]
This is a TODO. We should probably remove `ECDHE-RSA-3DES-EDE-CBC-SHA` and `RSA-3DES-EDE-CBC-SHA` from the default TLS config. They'd still be available if users want the extra compatibility but they're not preferred (they're already at the bottom of the list).

**Comment by mholt** [comment]
I'm going to reserve this issue for anybody who would like to make their first contribution to a Go project. It should just be a few simple changes in [tls.go](https://github.com/mholt/caddy/blob/master/caddy/setup/tls.go).

**Comment by pavlik** [comment]
I picked up this

**Comment by JasonSwindle** [comment]
Should Caddy not match what mozilla states on this?

https://wiki.mozilla.org/Security/Server_Side_TLS

**Comment by mholt** [comment]
Does it not?

**Comment by incon** [comment]
Closed by PR #412 ?
