### ISSUE TITLE
email in Caddyfile

### ISSUE THREAD

**Issue by JasonSwindle** [mholt/caddy#414]
> -email AUTO

> Email address to use for SSL certificate generation if not specified for a site in the Caddyfile. It is not required, but is strongly recommended so you can recover your account if you lose your private key. If an email is not available, Caddy may prompt you for an email address during runtime. This option is recommended in automated environments if not specified in the Caddyfile. 

How do I go about supplying this in the Caddyfile? I cannot find a good example in the docs? 

Thanks,
Jason

**Comment by JasonSwindle** [comment]
Nevermind, I found it under tls. It maybe good to link the docs to https://caddyserver.com/docs/tls when talking about email in LE.

**Comment by mholt** [comment]
Good idea. Just added the link and will push it soon.
