### ISSUE TITLE
Create "Soft" restart mode

### ISSUE THREAD

**Issue by captncraig** [mholt/caddy#416]
Currently, the graceful restarts fork the caddy process and the parent process exits. This causes trouble with certain process managers (supervisor and docker) to name a few, as they can't track the pid change (even if you argue they should.)

I would like to propose a "soft" reset mode.

Perhaps `-reset inProc` as opposed to the default of `-reset fork`.

It would stop all of the servers, apply configuration changes, and then restart servers. I realize it is not quite as seamless as the graceful restart mode. Existing connections will need to be dropped, and there may be some (very brief I hope) downtime before the re-bind takes effect. I am ok with that for the simpler management this can allow.

**Comment by tpng** [comment]
For supervisor, they provide a utility `pidproxy` exactly [for this purpose](http://supervisord.org/subprocess.html#pidproxy-program), which can be used with caddy's `-pidfile` flag.

**Comment by mholt** [comment]
You're right.

But since not all supervisors follow pidfiles (??? still boggles my mind) there should be a way to force Caddy to stay a single process - this is possible, but it will incur some brief downtime on occasion.

**Comment by mholt** [comment]
There's a 90% chance I will do this -- it won't be in 0.8.1 (I think) but it will be soon enough.

**Comment by pwFoo** [comment]
If the process changes a docker container will die during reload (if started as primary command). Would be great to have a graceful reload without spawn a new process.

**Comment by mholt** [comment]
@pwFoo Sure would. If you figure out a good way, let me know. :wink:

**Comment by alehano** [comment]
+1 for this feature. I had this problem with Docker and I couldn't figure out why my container stops. Because Caddy don't write to log about reloading.

**Comment by mholt** [comment]
Can't Docker follow a pidfile?

**Comment by captncraig** [comment]
nope.

**Comment by captncraig** [comment]
Unless you run supervisor or something as pid 1. Once the main process
exits, the container stops.

**Comment by abiosoft** [comment]
Caddy being pid 1 in the container is necessary for os signals. I'm sure there are other cons if Caddy is not pid 1 but the only other one I've experienced is slow shutdown.

**Comment by mholt** [comment]
Wow, that's an awful oversight on Docker's part. But this will be coming soon. Shouldn't be too hard to do. (Unfortunately though you'll lose zero downtime restarts.)

**Comment by brodock** [comment]
Upstart also doesn't support pidfile. While I would love to use systemd, If I want to use a modern supervisor (read: not sysv) in Ubuntu 12.04 / 14.04, it's the only way.

**Comment by tpng** [comment]
@brodock 
You can use [start-stop-daemon](http://manpages.ubuntu.com/manpages/karmic/man8/start-stop-daemon.8.html) in front of Caddy to track the pid file for Upstart.

Something like this:
```
exec start-stop-daemon --start --pidfile /var/run/caddy.pid caddy -pidfile /var/run/caddy.pid
```
http://stackoverflow.com/questions/9972023/ubuntu-upstart-and-creating-a-pid-for-monitoring/10539980#10539980

**Comment by jemaltz** [comment]
@tpng Does this work with the respawn stanza?  Let's just say I had an unpleasant experience.

**Comment by tpng** [comment]
@jemaltz Sorry, I don't use Upstart in my setup so I don't know either.

**Comment by mholt** [comment]
I propose `-restart=inproc` to force in-process restarts. All in favor, say aye! And submit a pull request :smile: (unless there is a better solution from anyone)

**Comment by tpng** [comment]
I will create the pull request today, hopefully!
