### ISSUE TITLE
LE: use defacto standard cert names

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#418]
Instead of using yet another naming convention for certs, how about sticking with what letsencrypt has already specified?

* {{letsencrypt-base}}/live/example.com/
* privkey.pem -- the private key
* fullchain.pem -- the cert + intermediates
* cert.pem -- the cert only

**Comment by mholt** [comment]
Too late to change it now. (At least, for patch releases. We'd have to do another point release and tell everyone to reset their .caddy storage folders.)

What's wrong with the way we're doing it now?

**Comment by coolaj86** [comment]
It's not that it's *wrong*, it's that every tutorial on the entire internet has a different way of doing things that's just different enough to completely confuse anyone who is looking for information.

With letsencrypt we have an opportunity to start fresh and collectively follow a standard -- or go back to the same choas we had before letsencrypt with everyone just doing it their own way.

**Comment by mholt** [comment]
I see what you mean.

Putting all the Let's Encrypt certs in one place is probably going to break clients. There are already dozens of client implementations and they all store the certificates in different places. Running multiple clients that manipulate the same certificate storage is asking for trouble, especially given that every client does things differently. Caddy is a unique client in that the certificates are fully managed and the average user will not ever need to even know where they're stored (as long as they take care of their server).

I think I'm mostly not convinced that a centralized certificate store is necessary or worth the trouble to do right. I don't like the idea of multiple clients stepping on the toes of others.

**Comment by coolaj86** [comment]
I'm not saying centralize, I'm saying follow the convention. Same folder names. Same file names. If it doesn't need to be different then just do it the same as they do.

**Comment by captncraig** [comment]
could they potentially be moved fromt he current layout to the proposed one? Perhaps dropping a "layoutV2" file once migrated so we know it has been done.

**Comment by mholt** [comment]
Okay, so different base paths, that's a little better.

But I'm not convinced that making this change is worth the effort. There doesn't seem to be anything wrong with the current folder structure, so I'm going to close the issue. Thanks for the feedback, though!
