### ISSUE TITLE
log, errors: Log file management

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#42]
Both the log and errors packages create log files. When the logs get really big, then what?

A middleware that creates log files should watch the size of the file (either by file size or number of entries - preferably file size) and gzip it when it gets large, and then start a new file. It could then keep only the last ~5 or so files to conserve disk space, purging the oldest ones when a new one is created.

Since log management spans multiple middlewares, it might be best for each middleware that makes logs to have a field for some sort of log management policy. Perhaps this "LogPolicy" type could be defined in the helper middleware package, which is allowed to be used by the middlewares. A LogPolicy type could define how big to allow each file to become, what to do when a file is full, how many to keep, etc. It could also have methods on it which execute these policies on a log file that gets passed in.

The default policy should probably be a conservative one that will ensure the disk does not become full. We could later build in ways to customize the policy as time permits and needs arise.

**Comment by qq08420** [comment]
As a user.Here is some problem.
1.How to use the route?Just like the keyword location in nginx...
location /xxx {
    root /xxx
}
2.When I use root and proxy as same time , the root will be failed
root /
proxy / http://xxxx

**Comment by hunter** [comment]
It would also be useful to have logging to stdout/stderr for the use in Docker containers.

**Comment by mholt** [comment]
@hunter I just realized I forgot to document this, but you can actually specify `stdout` or `stderr` as the log filename.

**Comment by hunter** [comment]
Excellent! Good to know :)

**Comment by mholt** [comment]
I forgot to update this issue, but thanks to work by @evermax this is now implemented as log rolling. See the [docs](https://caddyserver.com/docs/log) for info.
