### ISSUE TITLE
Pub-Sub directive

### ISSUE THREAD

**Issue by msoedov** [mholt/caddy#420]
I found this nginx module https://nchan.slact.net/readme quite useful in my sideproject. Does it make sense to add similar middleware  to caddy?

**Comment by sh-wn** [comment]
No. You could simply use Nchan or similar alongside your applications.

**Comment by mholt** [comment]
Possibly; Caddy is pluggable, meaning you can sideload your own web apps into it, including message queues and such. Anyone is welcome to write their own plugins as they deem them useful, and if it's generally useful, you can add it to the Download page for others to use, too.
