### ISSUE TITLE
directive for letsencrypt email and agree-tos?

### ISSUE THREAD

**Issue by coolaj86** [mholt/caddy#421]
I just wrote a few articles (listed) demonstrating how to use Let's Encrypt (specifically with Caddy) and I was about to write another article digging a little deeper and showing common config stuff (including upstart https://github.com/mholt/caddy/issues/388, for example) and so I went to look at the docs for the letsencrypt options here https://caddyserver.com/docs/automatic-https but I don't see any directives mentioned.

* [Let's Encrypt in (literally) 90 seconds](https://daplie.com/articles/lets-encrypt-in-literally-90-seconds/)
* [Let's Encrypt with Digital Ocean & Caddy!](https://daplie.com/articles/lets-encrypt-on-digital-ocean-with-caddy/)

**Comment by mholt** [comment]
Directives? What are you looking for, exactly?

Neat articles btw.

**Comment by mholt** [comment]
Do you mean the -email and -agree command line flags? https://caddyserver.com/docs/cli

**Comment by coolaj86** [comment]
The commandline flags are global. I mean something per-domain.

I keep saying `directives` because that's the lingo I know as a generic term for blocks of configuration.

Something like this:
```
example.com {
  letsencrypt {
    agree
    email coolaj86@gmail.com
    key /etc/letsencrypt/live/example.com/privkey.pem
    cert auto
  }
}
```

So that if I'm hosting for multiple users each user can have their own email and if they already have public key pinning / stapling set up I can specify their private key that they would like to use.

**Comment by coolaj86** [comment]
I now see that there is an `email` option in `tls` https://caddyserver.com/docs/tls.

Didn't notice it before because when I did `ctrl+f` to search the page for things like "let's encrypt", "acme", "letsencrypt"... they're never mentioned.

Also, the TLS config isn't mentioned at https://caddyserver.com/docs/automatic-https

Would still be good to be able to specify private key rather than a new one being generated.

I'm going to go update my articles to include the `tls email` option...

**Comment by coolaj86** [comment]
Also needs a way to specify `acmeServerUrl`.

**Comment by mholt** [comment]
Why do you want to specify the ACME server URL on a per-domain basis? And terms agreement? That sounds like way more effort than it's worth. Just use one ACME endpoint. Just agree to the terms once; it's per user, not per domain.

**Comment by coolaj86** [comment]
Lots of factors - circumventing rate-limiting by using multiple authorities, tlds that aren't owned by verisign or otherwise have political encumberments preventing use with the normal server, having some sites that use peer authentication with a private instance, because the spec allows it, etc

**Comment by coolaj86** [comment]
And ideally the tosUrl would be stored as the agree parameter (as suggested by the LE flow) so that when there are new terms and that url changes I could have the opportunity to decide if I agree to the new terms - but if the value is exactly 'true' it would mean I agree to accept new terms without review.

**Comment by mholt** [comment]
> circumventing rate-limiting by using multiple authorities

This is not a goal of Caddy. Maybe you want [another tool](https://github.com/xenolf/lego) instead?

> tlds that aren't owned by verisign or otherwise have political encumberments preventing use with the normal server

Huh?

> having some sites that use peer authentication with a private instance, because the spec allows it

Okay, well, that's kind of strange. But the change is not trivial to make this work on a per-site basis.

So, in conclusion, probably _no_ for the per-site terms agreement, and _no for now_ on the per-site CA url. Hope that's okay. :smile:
