### ISSUE TITLE
gzip and websocket

### ISSUE THREAD

**Issue by bigeagle** [mholt/caddy#422]
Hi,

As websocket does not work with gzip, I need to manually disable gzip for websocket locations.
Can we implement automatically disabling gzip for websocket?

Cheers,
Justin

**Comment by abiosoft** [comment]
By manually, do you mean using `not` parameter from [gzip's  configuration](https://caddyserver.com/docs/gzip) ?

**Comment by bigeagle** [comment]
yep, I need to find the websocket route and use `not`.

**Comment by mholt** [comment]
Yep, that should do it.
