### ISSUE TITLE
Caddy serves random certificate from configuration for undefined subdomains

### ISSUE THREAD

**Issue by sh-wn** [mholt/caddy#423]

**Comment by mholt** [comment]
I believe this is what nginx does too. The Go standard library will always present one certificate to the client so the client can at least report what machine it actually ended up connecting to.

**Comment by sh-wn** [comment]
With SNI the hostname is sent unencrypted during the TLS handshake. Is this accessible prior to replying to the request? What about a directive for strict SNI (i.e. denying connections lacking a `Host` header)?

**Comment by Zenexer** [comment]
@mholt You asked me to open a new issue for the discussion that took place in #1991.  I believe this is the same issue.  Can we open this one?

**Comment by mholt** [comment]
@Zenexer Thank you for taking the effort to search, but no, this is the same issue as #1303 -- not the one you brought up more than a year after it closed.
