### ISSUE TITLE
Is there a way caddy can write access logs in JSON format? 

### ISSUE THREAD

**Issue by harshavardhana** [mholt/caddy#425]
For example as below - unmarshalling this type of struct? 

```
   // HTTP detailed message
        HTTP struct {
                ResponseHeaders http.Header
                Request         struct {
                        Method     string
                        URL        *url.URL
                        Proto      string // "HTTP/1.0"
                        ProtoMajor int    // 1
                        ProtoMinor int    // 0
                        Header     http.Header
                        Host       string
                        Form       url.Values
                        PostForm   url.Values
                        Trailer    http.Header
                        RemoteAddr string
                        RequestURI string
                }
        }
```

```
{"StartTime":"2015-06-17T03:43:22.289131896Z","Duration":457855,"StatusMessage":"OK","ContentLength":"0B","HTTP":{"ResponseHeaders":{"Accept-Ranges":["bytes"],"Connection":["close"],"Content-Length":["0"],"Content-Type":["application/xml"],"Server":["Minio"]},"Request":{"Method":"HEAD","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/updates","RawQuery":"","Fragment":""},"Proto":"HTTP/1.1","ProtoMajor":1,"ProtoMinor":1,"Header":{"Authorization":["AWS4-HMAC-SHA256 Credential=AC5NH40NQLTL4D2W92PM/20150617/milkyway/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=70bbb1cf8f133b1fd33eca46d77859527b4bb267208856f1b7322f75e2565d92"],"User-Agent":["Minio/Fri, 12 Jun 2015 02:05:16 GMT (/home/minio/go/bin/mc; linux; amd64)  minio-go/0.1.0 (linux; amd64)"],"X-Amz-Content-Sha256":["e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"],"X-Amz-Date":["20150617T034322Z"]},"Body":{"Closer":{"Reader":null}},"ContentLength":0,"TransferEncoding":null,"Close":false,"Host":"dl.minio.io:9000","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"10.134.253.170:51043","RequestURI":"/updates","TLS":{"Version":771,"HandshakeComplete":true,"DidResume":false,"CipherSuite":49199,"NegotiatedProtocol":"","NegotiatedProtocolIsMutual":true,"ServerName":"dl.minio.io","PeerCertificates":null,"VerifiedChains":null,"TLSUnique":"GRVvG32qlXzFR4Lp"}}}}
```

If not possible does caddy provide support for external middleware / handlers? - I couldn't see much in documentation.

**Comment by captncraig** [comment]
The current log directive is somewhat customizable, but maybe not to the degree you want. You can certainly make a custom middleware. I'd recommend https://github.com/abiosoft/hello-caddy for a good getting-started guide. 

It is possible you could extend the log middleware to allow `json` as a format string, but @mholt may not like that since there are numerous ways you could want the json structured.

**Comment by harshavardhana** [comment]
> It is possible you could extend the log middleware to allow json as a format string, but @mholt may not like that since there are numerous ways you could want the json structured.

Not a generic one which caddy provides, i know it gets really hard to provide through a config file. Just wanted to know if there is a proper way to go about.

I can live with that.

**Comment by harshavardhana** [comment]
> The current log directive is somewhat customizable, but maybe not to the degree you want. You can certainly make a custom middleware. I'd recommend https://github.com/abiosoft/hello-caddy for a good getting-started guide.

Thanks a lot @captncraig  - https://github.com/minio/minio-caddy - here is the custom middleware that i am able to use. 

Thanks for the inputs.

**Comment by harshavardhana** [comment]
> Thanks a lot @captncraig - https://github.com/harshavardhana/caddylogger - here is the custom middleware that i am able to use.

The only problem i see now is that i cannot really add other middlewares on top of the new one. Unless i am missing something in documentation please advise. 

```
0.0.0.0
caddylogger
browse / browse.tpl
``` 

Following config fails to write to access.log - where as without the `browse` tag it works fine.

**Comment by mholt** [comment]
What's your directives.go file look like?

**Comment by harshavardhana** [comment]
> What's your directives.go file look like?

I was able to fix it properly by looking jsonp middleware, thanks though :-)  here are the working changes. https://github.com/harshavardhana/caddylogger/blob/master/caddylogger.go

**Comment by harshavardhana** [comment]
I missed out ``.Next.ServeHTTP()`` an obvious one.

**Comment by mholt** [comment]
This is done with https://github.com/caddyserver/caddy/pull/2831.

Also see #1109.

**Comment by mholt** [comment]
This has been merged and is going out with Caddy 2 beta 7 today. Check out the docs in the wiki and give it a try!
