### ISSUE TITLE
Does/will caddy use semantic versioning?

### ISSUE THREAD

**Issue by bmintz** [mholt/caddy#427]
It would be nice if, after 0.y, [semantic versioning] could be used. Or are there plans for this?

[semantic versioning]: http://semver.org

**Comment by mholt** [comment]
Yes, that'll be done starting with version 1.0.

Right now, Caddy releases are stable enough to be used in production, but changes between versions *may* be breaking, so check the release notes to be sure. Currently we increment the minor version for "major" changes and the patch version for "minor" changes. But once we hit 1.0, we'll splice in that extra digit and it'll be semantic just like you'd expect.

**Comment by bmintz** [comment]
Hooray!
