### ISSUE TITLE
user agent based rewrite/redirects possible ?

### ISSUE THREAD

**Issue by centminmod** [mholt/caddy#428]
Are user agent based rewrite and redirects possible in Caddy ? Similar to what I did here https://community.centminmod.com/threads/letsencrypt-ssl-certificates-and-windows-xp-workarounds.5272/ ?

cheers

George

**Comment by mholt** [comment]
No, but this may be slated for the future.

**Comment by centminmod** [comment]
awesome thanks @mholt

**Comment by abiosoft** [comment]
With 0.8.1, you'll be able to do string/regex match against user agent in rewrite via the `{>Header}` placeholder.
```
rewrite {
    if {>User-Agent} has some_strings
    if {>User-Agent} match /some(_regex)
    to ...
}
```

Feel free to reopen if that is not satisfactory.
