### ISSUE TITLE
Panic when markdown-sitegen combined with network-related template actions

### ISSUE THREAD

**Issue by qjcg** [mholt/caddy#430]
Using caddy's markdown -> sitegen directive with the network-related template actions results in an immediate runtime panic (tested at commit aba0ae3), which goes against [best practices](https://github.com/golang/go/wiki/CodeReviewComments#dont-panic). Using any of the following template actions with markdown/sitegen will trigger a panic:

- `{{.Cookie "name"}}`
- `{{.Header "name"}}`
- `{{.IP}}`
- `{{.URI}}`
- `{{.Host}}`
- `{{.Port}}`
- `{{.Method}}`
- `{{.PathMatches "/some/path"}}`

To reproduce, run `caddy` with the following simple configuration (Caddyfile + index.md + templates/main.html).

Caddyfile:
```
localhost

markdown / {
        ext .md
        sitegen
        template templates/main.html
}
```

index.md

```
---
title: Test
---

# Test 123

Test
```

templates/main.html (can replace `{{.IP}}` with any of the template actions listed above).
```html
<!DOCTYPE html>
<html>
  <head>
    <title>{{.Doc.title}}</title>
  </head>
  <body>
    Your IP is: {{.IP}}
    <br />
    <br />
    {{.Doc.body}}
  </body>
</html>
```

Immediate panic on execution:

```
$ caddy
Activating privacy features... done.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x5a4a30]

goroutine 9 [running]:
text/template.errRecover(0xc8200bcff8)
        /usr/lib/go/src/text/template/exec.go:100 +0xbb
github.com/mholt/caddy/middleware.Context.IP(0x7f08e29ebb48, 0xc820112840, 0x0, 0x0, 0x0, 0x0)
        /home/john/.local/go/src/github.com/mholt/caddy/middleware/context.go:81 +0xa0
github.com/mholt/caddy/middleware/markdown.(*Data).IP(0xc82012e540, 0x0, 0x0)
        <autogenerated>:30 +0x4d
reflect.Value.call(0x9d8280, 0xc82012e540, 0x753, 0x9fb7f8, 0x4, 0xcebf38, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/lib/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x9d8280, 0xc82012e540, 0x753, 0xcebf38, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go/src/reflect/value.go:300 +0xb1
text/template.(*state).evalCall(0xc8200bcf88, 0x9d8280, 0xc82012e540, 0x59, 0x9d8280, 0xc82012e540, 0x753, 0x7f08e29ebf70, 0xc8200cd410, 0xc8200f1c9b,
...)
        /usr/lib/go/src/text/template/exec.go:602 +0xb38
text/template.(*state).evalField(0xc8200bcf88, 0x9d8280, 0xc82012e540, 0x59, 0xc8200f1c9b, 0x2, 0x7f08e29ebf70, 0xc8200cd410, 0xc8201132a0, 0x1, ...)
        /usr/lib/go/src/text/template/exec.go:494 +0x338
[...]
```

**Comment by mholt** [comment]
Oh, @abiosoft - how should handle template actions that expect a remote visitor during sitegen when there is no remote visitor?

**Comment by abiosoft** [comment]
Oops. Whatever the situation, panic firstly needs to be suppressed. Then we need to find a way of indicate the value is missing.

**Comment by mholt** [comment]
That's correct. @abiosoft would you have a chance to look into this sometime? (As you know, aside from finishing my last finals, I'm trying to get a patch release ready and that's taking most of my time. At least stopping the panic shouldn't be too hard.)

**Comment by abiosoft** [comment]
It is on my todo-list. I should have time this weekend.

**Comment by abiosoft** [comment]
We will need to document it that those values are only available at runtime and hence sitegen is not compatible with them.

**Comment by mholt** [comment]
Awesome; I'll close this as soon as I make a note in the docs that sitegen does not support request-time template actions.
