### ISSUE TITLE
"not a valid e-mail address"

### ISSUE THREAD

**Issue by k0nsl** [mholt/caddy#431]
This appears when I try to run caddy after specifying my personal e-mail address. My e-mail is "i.am@k0nsl.org". I registered for their closed beta (Let's Encrypt) and they accepted that e-mail.

Nevertheless, this is what comes up when running caddy:

```
Activating privacy features...
2015/12/12 13:15:42 error creating client: registration error: acme: Error 400 - urn:acme:error:malformed - Error creating new registration :: Validation of contact mailto:on failed: not a valid e-mail address
```

In fact, it doesn't matter what e-mail I put in. It displays the same error even for Gmail accounts.

**Comment by k0nsl** [comment]
Never mind, I believe it must have been a oversight on my end.

**Comment by mholt** [comment]
Did you put `tls on` in your Caddyfile?

I don't recommend that ;)
