### ISSUE TITLE
[rp1.rempe.us] failed to get certificate: The server could not validate our request.

### ISSUE THREAD

**Issue by grempe** [mholt/caddy#432]
Hi,

I'm having a problem similar to that in issue https://github.com/mholt/caddy/issues/401

````
glenn@rp1 ~/www $ caddy -version
Caddy 0.8
````

My Caddyfile:

````
https://rp1.rempe.us {
#  tls off
  tls glenn@rempe.us
  root /home/glenn/www/public/www.rempe.us
  gzip
  log /home/glenn/www/logs/www.rempe.us/access.log
  git https://github.com/grempe/www.rempe.us.git
}
````

and when I run caddy (with the extra logging you mentioned in the other issue):

````
glenn@rp1 ~/www $ caddy -log stderr
Activating privacy features...2015/12/12 13:21:53 [INFO] acme: Obtaining bundled certificates for rp1.rempe.us
2015/12/12 13:21:54 [INFO] acme: Trying to solve TLS-SNI-01

2015/12/12 13:22:31 [rp1.rempe.us] failed to get certificate: The server could not validate our request.
````

Note that there is a long pause before the final line is output.

I had a though perhaps this was related to IPv6 so I also ran the following as specified in issue #383 which had no effect as far as I can tell:

````
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
````

I have tried removing the files in ~/.caddy with no change.

Any thoughts on how I can get this to work or get more info about what exactly is failing?

I am able to run caddy if I turn tls off. I am running this on a Raspberry Pi. The host rp1.rempe.us is a real public host in DNS.

Thanks.

**Comment by mholt** [comment]
The long pause on a raspberry pi is because the tls-sni-01 challenge is computationally expensive on such weak hardware. So the ~45s delay is normal in that case.

As far as the challenge failing, I'd need to double-check how the tls-sni-01 challenge works. @xenolf would there be any extra log output if the LE server is able to reach the client? My initial thought is that rp1.rempe.us isn't reachable by LE.

**Comment by grempe** [comment]
OK, I followed up on your initial thought.  You were right.  I had some forgotten firewall rules in place that allowed me access to that host from cloudflare and my local network but NOT from the rest of the outside world. Duh.

Now:

````
glenn@rp1 ~/www $ caddy -log stderr
Activating privacy features...2015/12/13 09:43:39 [INFO] acme: Obtaining bundled certificates for rp1.rempe.us
2015/12/13 09:43:40 [INFO] acme: Trying to solve TLS-SNI-01
2015/12/13 09:43:56 The server validated our request
2015/12/13 09:43:56 [INFO] acme: Validations succeeded; requesting certificates
2015/12/13 09:44:28 [INFO] acme: Requesting issuer cert from https://acme-v01.api.letsencrypt.org/acme/issuer-cert
2015/12/13 09:44:28 [rp1.rempe.us] Server responded with a certificate.
2015/12/13 09:44:29 [INFO] Checking certificates for 2 hosts
 done.
From https://github.com/grempe/www.rempe.us
 * branch            master     -> FETCH_HEAD
Already up-to-date.
2015/12/13 09:44:31 https://github.com/grempe/www.rempe.us.git pulled.
rp1.rempe.us:https
Warning: File descriptor limit 1024 is too low for production sites. At least 4096 is recommended. Set with "ulimit -n 4096".
rp1.rempe.us:http
````

So my bad.  That being said, it would be great if it were possible to get more visibility into these kinds of issues from LE or elsewhere in the HTTPS setup process for Caddy so we could self-diagnose these issues more easily.

TLS 'A' Rating:
https://www.ssllabs.com/ssltest/analyze.html?d=rp1.rempe.us&s=75.101.102.123&hideResults=on

Thanks for helping me out. Case closed.
