### ISSUE TITLE
caddy started with -quiet=true option should send no output to stdout with git enabled

### ISSUE THREAD

**Issue by grempe** [mholt/caddy#434]
I have git enabled in my Caddyfile for a site.  If I start caddy with the -quiet=true option I would expect no output on startup at all. But I still see the output of the git initialization every time.  The core caddy startup output is the only part that seems to be suppressed.

````
$ /usr/local/bin/caddy -conf="/home/glenn/www/Caddyfile" -quiet=true
From https://github.com/grempe/www.rempe.us
 * branch            master     -> FETCH_HEAD
Already up-to-date.
2015/12/13 13:34:22 https://github.com/grempe/www.rempe.us.git pulled.
^C

$ /usr/local/bin/caddy -conf="/home/glenn/www/Caddyfile" -quiet=false
Activating privacy features... done.
From https://github.com/grempe/www.rempe.us
 * branch            master     -> FETCH_HEAD
Already up-to-date.
2015/12/13 13:35:28 https://github.com/grempe/www.rempe.us.git pulled.
rp1.rempe.us:https
rp1.rempe.us:http
````

````
$ caddy -h
Usage of caddy:
...
  -quiet=false: Quiet mode (no initialization output)
...
````

I would expect this to quiet all output, not just part of it, from the startup sequence no matter what config options I have provided in the Caddy file for git or any other options.

**Comment by abiosoft** [comment]
Can you create the issue here instead. https://github.com/abiosoft/caddy-git/issues.

Thanks.
