### ISSUE TITLE
Caddy & PHP-FPM

### ISSUE THREAD

**Issue by wayneashleyberry** [mholt/caddy#435]
Hi Everyone :)

I've been trying to get Caddy working with PHP-FPM on a fresh Digital Ocean droplet with Ubuntu 14.04 and honestly can't figure it out. I'm pretty sure this should be really simple but I'm just oblivious to some weird Linux things.

Here are the exact steps I'm following:

**1. Log in to Digital Ocean**

**2. Create Droplet using the default settings**

- $10/mo
- 1GB/1CPU
- New York 3
- Ubuntu 14.04.3 x64
- Add SSH key

**3. Update local ~/.ssh/config**

```sh
host 104.236.25.160
  User root
  IdentityFile ~/.ssh/foo
```

**4. SSH**

```sh
ssh root@104.236.25.160
```

**5. Install Things**

**5.1 PHP & Git**

```sh
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install git php5-cli php5-fpm -y
```

**5.2 SCP Caddy**

```sh
scp -r ~/Downloads/caddy_linux_amd64_custom root@104.236.25.160:/root/caddy
```

**5.3 Clone Project**

```sh
git clone https://github.com/wayneashleyberry/caddy-test.git
cd caddy-test
```

**6. Run Caddy**

```sh
/root/caddy/caddy
Activating privacy features... done.
104.236.25.160:2015
Warning: File descriptor limit 1024 is too low for production sites. At least 4096 is recommended. Set with "ulimit -n 4096".
```

**7. Test**

Visting http://104.236.25.160:2015/ returns a `502 Bad Gateway` error.

Here's the error log:

```sh
root@caddy:~/caddy-test# cat error.log
14/Dec/2015:01:13:39 -0500 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
```

**8. Debugging**

```sh
root@caddy:/etc/php5/fpm# git --version
git version 1.9.1
```

```sh
root@caddy:/etc/php5/fpm# php -v
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
```

```sh
root@caddy:/etc/php5/fpm# /root/caddy/caddy -version
Caddy 0.8
```

```sh
root@caddy:/etc/php5/fpm# ps aux | grep php-fpm
root      5139  0.0  1.2 140264 13044 ?        Ss   01:02   0:00 php-fpm: master process (/etc/php5/fpm/php-fpm.conf)
www-data  5168  0.0  0.4 140264  4096 ?        S    01:02   0:00 php-fpm: pool www
www-data  5169  0.0  0.4 140264  4096 ?        S    01:02   0:00 php-fpm: pool www
root      6632  0.0  0.0  11712   668 pts/0    S+   01:21   0:00 grep --color=auto php-fpm
```

**Comment by abiosoft** [comment]
Firstly, share your Caddyfile.

Then, since this is the default Ubuntu php-fpm settings, it will be listening on a unix socket, not port. Change `127.0.0.1:9000` to `/var/run/php5-fpm.sock`

**Comment by wayneashleyberry** [comment]
Oh, sorry @abiosoft, I thought it was clear in the `git clone` section :)

The test project + Caddyfile is here: https://github.com/wayneashleyberry/caddy-test

**Comment by wayneashleyberry** [comment]
Error logs now look like this @abiosoft 

```
14/Dec/2015:01:34:47 -0500 [ERROR 502 /] malformed MIME header line: Primary script unknown
14/Dec/2015:01:34:49 -0500 [ERROR 502 /] malformed MIME header line: Primary script unknown
```

**Comment by abiosoft** [comment]
Change this line in your Caddyfile

```
fastcgi / /var/run/php5-fpm.sock
```
to 
```
fastcgi / /var/run/php5-fpm.sock php
```
`php` is missing. :blush:

**Comment by wayneashleyberry** [comment]
Whoops! Haha, sorry it's still early here

Added `php` and restarted Caddy, didn't make a difference as far as I can tell.

**Comment by wayneashleyberry** [comment]
Still getting the following errors:

```
14/Dec/2015:01:38:54 -0500 [ERROR 502 /] malformed MIME header line: Primary script unknown
14/Dec/2015:01:40:13 -0500 [ERROR 502 /] malformed MIME header line: Primary script unknown
```

**Comment by abiosoft** [comment]
The issue has been found.

The source file is created in the home directory of root user `/root` and php-fpm's `www-data` cannot read from there.

#### Solution:
Create a new user.
```
adduser <username>
```
Add user to `www-data` to enable it read php-fpm's unix socket file at `/var/run/php5-fpm.sock`. Useful if you will start caddy in the user session.
```
adduser <username> www-data
```
Login as `<username>`, clone the source repo and start caddy. Everything should be fine.

**Comment by abiosoft** [comment]
@wayneashleyberry feel free to close this issue when you're satisfied.

**Comment by wayneashleyberry** [comment]
Working perfectly, thanks so much for all of your help @abiosoft
