### ISSUE TITLE
Rewriting URL's for Laravel

### ISSUE THREAD

**Issue by wayneashleyberry** [mholt/caddy#436]
Given the following Caddyfile and a fresh Laravel setup with the following routes:

```
root ./public
fastcgi / /var/run/php5-fpm.sock php
errors error.log
```

```php
<?php

Route::get('/', function () {
    return view('welcome');
});

Route::get('/foo', function () {
	return 'bar';
});
```

The index route works perfectly, but the `/foo` route can only be accessed at `/index.php/foo`.

**Comment by wayneashleyberry** [comment]
The recommended NGINX configuration for Laravel is:

```
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
```

Don't know if that helps?

**Comment by abiosoft** [comment]
This should work
```
rewrite {
    r .*
    ext /
    to /index.php?{query}
}
```

**Comment by wayneashleyberry** [comment]
Perfect :ok_hand: 

You're my hero @abiosoft :)
