### ISSUE TITLE
'browse' middleware default template is not using full screen width

### ISSUE THREAD

**Issue by fboyer** [mholt/caddy#439]
As discussed on Slack with @mholt , I have found that using the default template delivered with the browse middleware does not leverage the complete width of the screen in a responsive manner. 

This can be seen in the attached screenshot taken in Chrome 47.0.2526.80 with a 1920x1080 resolution.

![image](https://cloud.githubusercontent.com/assets/5251551/11824080/a1be00e8-a345-11e5-8abd-ad1575aedade.png)

The longest filename being displayed is "sunxi-xf86-video-fbturbo-e094e3c8f9004ca3347694bd05b99d136e8621b9.tar.gz".

@mholt also mentioned adding better handling of the text wrapping.

**Comment by mholt** [comment]
Cool, thanks to @incon's work and the commits on the [browse-tpl branch](https://github.com/mholt/caddy/tree/browse-tpl), I think you'll find this new template much nicer. Will land soon in master. Thanks!
