### ISSUE TITLE
example for golang web framework

### ISSUE THREAD

**Issue by redaready** [mholt/caddy#44]
could be good if there are some examples in tutorial for integrating the existing golang web framework like echo or martini

**Comment by mholt** [comment]
Do you mean an example of using Caddy middleware in your own web application, or using Caddy as a web server in front of your Go web application?

**Comment by redaready** [comment]
maybe the both, if Caddy has echo's router, it will become a very good application server too

**Comment by mholt** [comment]
There is a brief [tutorial in the wiki](https://github.com/mholt/caddy/wiki/Using-Caddy-Middleware-in-Your-Own-Programs) that describes how to use Caddy middleware in your own applications. As for using Caddy to front another Go application, that's possible, but I haven't seen that happening yet. Anyone is welcome to write an example/tutorial for the wiki if you'd like.

And echo is a very good router, but Caddy doesn't use a router. If it does in the future, I've also looked at using echo for it. Thanks for the suggestion!

**Comment by Pym** [comment]
@redaready have you found a solution for that use case?

**Comment by bharatkrishna** [comment]
The link to wiki page for "Using Caddy Middleware in Your Own Programs" seems to be broken. 
I wanted to know how I could merge my existing go web app into caddy. I'm not using any framework or middleware but just "net/http" and templates.

**Comment by mholt** [comment]
@bharatkrishna That page is gone; Caddy middleware are not well-suited for just any Go program anymore. But you can make your web app a Caddy plugin (mostly) easily enough. There are instructions on the wiki how to do that. It especially helps that you're only using net/http.

**Comment by bharatkrishna** [comment]
Thanks, I'll give it a shot by following the docs.
