### ISSUE TITLE
Caddy won't pass _SERVER["HOSTNAME"] (php5-fpm)

### ISSUE THREAD

**Issue by audhen** [mholt/caddy#443]
First things first: Thank you for this wonderful piece of software! :+1: 

My issue:
I've setup a new Ubuntu box for hosting my services.
So I thaught I'd give caddy a productive go - everything is running smoothly, except for CouchCMS.

The links are totally messed up like https://example.org/https/somePage.php
I've looked into the CouchCMS code and it appears that it is referencing to _SERVER["HOSTNAME"].

phpinfo() tells me, that _SERVER["HOSTNAME"] == no value

I double checked my www.conf of php5-fpm - the environment variables are uncommented.

So, I might have found a little flaw. :-(

**Comment by mholt** [comment]
It's not a flaw, "HOSTNAME" is not a standard CGI variable: http://stackoverflow.com/questions/6070810/php-getenvhostname

Hostname lookups aren't exactly cheap; why should Caddy set this non-standard env var? Why can't the PHP app just create it itself?

**Comment by audhen** [comment]
Oh, you are totally right! Sorry for bothering. :-(

**Comment by mholt** [comment]
It's okay, others might have the question later. We'll see if it comes up again.
