### ISSUE TITLE
Option to bundle domain names in Lets encrypt Cert

### ISSUE THREAD

**Issue by fbatschi** [mholt/caddy#445]
When you define multiple hostnames in the Caddyfile, caddy requests an LE cert for every hostname.

So 
`hostname1.com, www.hostname1.com, hostname2.com, www.hostname2.com {
.....
}`

will generate 4 certs with LE.

It would be great if there is an option to define that they should all go into one cert with alternative names, which LE supports during the creation process.

**Comment by captncraig** [comment]
This would certainly help with the rate-limiting people are experiencing during the beta.

**Comment by mholt** [comment]
I don't think bundling will affect the rate limiting.

Why do you want the certs bundled? They are easier for Caddy to manage separately. If you want to manage them yourself then Caddy is not the right tool for you.

**Comment by captncraig** [comment]
According to https://community.letsencrypt.org/t/quick-start-guide/1631, the certificate per domain limit is based on certificates issued, not on total subdomains. So 100 subdomains on a cert would only count as 1 against your rate limit. 

It would definitely require a bit of a reorg of the sites tree. Maybe it could be accomplished by simply copying the multi cert into each individual site folder and somehow indicating that they should share the renewal logic somehow. 

A bit of a pain to do for something we expect to go away.

**Comment by mholt** [comment]
Yeah, I don't fancy the extra complexity.
