### ISSUE TITLE
How to keep the original url using proxy?

### ISSUE THREAD

**Issue by gustavohenrique** [mholt/caddy#446]
Hi! It's my Caddyfile:

myapp.mydomain.com {
    proxy / 172.17.0.10:8001
    log /var/log/myapp.log
    tls off
}

When I access via browser the url http://myapp.mydomain.com, the url in the address bar changes to http://172.17.0.10:8001.
This IP is a docker container running a specific webapp.

**Comment by novaeye** [comment]
try 
```
myapp.mydomain.com {
    proxy / 172.17.0.10:8001 {
        proxy_header Host {host}
    }
    log /var/log/myapp.log
    tls off
}
```

**Comment by gustavohenrique** [comment]
The proxy_header worked! Thanks!

**Comment by wesm-outreach** [comment]
I'm getting `Error during parsing: unknown property 'proxy_header'`. and don't see this directive in the docs. Was this deprecated?

**Comment by mholt** [comment]
Yes; use `header_upstream` instead.

**Comment by wesm-outreach** [comment]
@mholt Thanks! I was doing some google searches around converting from nginx to Caddy, and this issue popped up. I didn't quite equate the `header_downstream` from the docs to my use case until now. Thanks for the reply! Sorry for resurrecting an old issue.
