### ISSUE TITLE
I need help to run Caddy as a service

### ISSUE THREAD

**Issue by Nixtren** [mholt/caddy#447]
Hey,

I'm currently running CentOS 7 and I'm struggling to make Caddy run properly as a service. So far I have attempted to create a systemd service:
```
[Unit]
Description=Caddy Service
After=network.target

[Service]
Type=simple
User=caddy
Group=caddy
ExecStart=/home/caddy/caddy
#Restart=on-abort


[Install]
WantedBy=multi-user.target
```
Caddy works, but it doesn't read/find the Caddyfile. I have also attempted to pass the Caddyfile location parameter, and it says it can't find the file, though the file really exists (I confirmed with cat).
```
ExecStart=/home/caddy/caddy -conf="/home/caddy/Caddyfile"
```
```
caddy[7456]: 2015/12/18 12:09:53 open "/home/caddy/Caddyfile": no such file or directory
```
I believe someone here has managed to run a Caddy service, so I would appreciate if you could tell me how you did it.

Thanks for reading :)

**Comment by jahmad** [comment]
I also run Caddy service with systemd, and see nothing wrong with your unit file. Did you confirm it works as expected when you run it manually in the command line?

You could also try adding working directory, as Caddy will look for Caddyfile there by default.

    WorkingDirectory=~

Unrelated to your question, I think you unit file is incompatible with Caddy's graceful restart, which will make your service just gone when it's time for Caddy to renew your letsencrypt's certificate. You will need to provide pidfile so systemd could track your service. from my unit file:

    PIDFile=/run/caddy/caddy.pid
    ExecStart=/usr/bin/caddy -conf=/etc/Caddyfile -pidfile=/run/caddy/caddy.pid -agree=true
    ExecReload=/bin/kill -USR1 $MAINPID

**Comment by Nixtren** [comment]
Thanks @jahmad, I solved the problem by adding WorkingDirectory :)

Here's my final caddy.service:
```
[Unit]
Description=Caddy Service
After=network.target

[Service]
Type=simple
User=caddy
Group=caddy
ExecStart=/home/caddy/caddy -pidfile=caddy.pid -agree=true
WorkingDirectory=/home/caddy
PIDFile=/home/caddy/caddy.pid
ExecReload=/bin/kill -USR1 $MAINPID

[Install]
WantedBy=multi-user.target
```
WorkingDirectory needs an absolute path though, that's why I didn't use "~".
