### ISSUE TITLE
gzip in combination with browse doesn't return header Content-Encoding: gzip

### ISSUE THREAD

**Issue by sanderhahn** [mholt/caddy#448]
Nice project, clean and simple :)

One bug seems that the browse feature in combination with the gzip feature doesn't explicitly return the Content-Encoding: gzip header. The gzip compression is triggered because Chrome shows unreadable binary output.

**Comment by mholt** [comment]
Yeah, we saw this crop up a few days ago; it's only true with the latest on master; download 0.8 stable from the [Download](https://caddyserver.com/download) page and it should be fine.

**Comment by abiosoft** [comment]
The fix has been merged. You can build from source now or wait for the next patch release.

Thanks for reporting this.
