### ISSUE TITLE
Improperly requesting SSL certificate for local :80 site

### ISSUE THREAD

**Issue by mgibbs189** [mholt/caddy#450]
Hey @mholt,

Caddy 0.8, OSX 64-bit. Caddyfile:

```
wp.dev:80 {
  root /usr/local/var/www/wp.dev/public
  fastcgi / localhost:9000 php
}
```

Error:

```
$ sudo caddy
Activating privacy features...
2015/12/18 16:48:50 [wp.dev] failed to get certificate: The server could not validate our request.
```

The <a href="https://caddyserver.com/docs/automatic-https">documentation</a> claims that Automatic HTTPS is skipped when the port is `80`.

If I add `tls off` into the above Caddyfile, the SSL certificate request is (correctly) skipped.

Is this a bug or a feature? Great project BTW :smile:

**Comment by abiosoft** [comment]
For now, use `http://wp.dev` instead.

**Comment by jahmad** [comment]
actually, explicit port 80, explicit scheme http, and caddy's inability to bind port 80 and 443 will only resolve in error.

the only way to disable automatic https which works on 0.8 is "tls off" directive, and explicitly setting non-standard port.

additional info, setting with only host without port and permission to privileged port:
 * on 0.7 -> will bind to default port 2015
 * on 0.8 -> wil try to bind port 80, and error

**Comment by mholt** [comment]
Thanks for the report. This seems to be a duplicate of #391. If you agree, feel free to close this one and I'll get around to it soon. :)

**Comment by mgibbs189** [comment]
Roger that, thanks again
