### ISSUE TITLE
Support block syntax for `internal`

### ISSUE THREAD

**Issue by bmintz** [mholt/caddy#451]
Plain and simple.

```
internal {
    /no-snooping
    /config/
    /nope/nope/double-nope
}
```

**Comment by abiosoft** [comment]
You can achieve same with multiple lines.

```
internal /no-snooping
internal /config/
internal /nope/nope/double-nope
```

**Comment by mholt** [comment]
For ~3 lines, I don't see a reason to have a block syntax. I can't imagine most sane web apps would have more than a handful.

Thanks for the suggestion though!

**Comment by bmintz** [comment]
The best reason I can think of for having this is that it makes _adding_ new lines easier. Caddy's all about ease of configuration, right? :stuck_out_tongue_winking_eye:
