### ISSUE TITLE
Caddy blocks sometimes

### ISSUE THREAD

**Issue by DenBeke** [mholt/caddy#455]
When running (various) PHP sites, Caddy sometimes blocks. All of a sudden nothing loads anymore. If you have some luck, things start loading again after a while. It seems to be non-deterministic, because the same page loads perfectly afterwards, and other pages that loaded perfectly don't load anymore.

There is no high load or high cpu usage for a process whenever this happens. Restarting Caddy helps for a very short period of time.

I had this issue with ownCloud and Piwik, on multiple versions of Caddy on different servers (both Ubuntu). The Piwik site I tried was my actual production site which is normally served by Nginx on the same machine, never experienced such a thing on Nginx. 

Anyone else having this issue?

(video coming soon)

**Comment by DenBeke** [comment]
Video will appear at https://youtu.be/hu-h8qf4X7Q once YouTube processed it...

**Comment by abiosoft** [comment]
Whenever that happens, php-fpm log adds this line.
```
WARNING: [pool www] server reached pm.max_children setting (5), consider raising it
```
After bit of Googling, I found [this](http://serverfault.com/questions/479443/php5-fpm-server-reached-pm-max-children) which solves the problem for me.

#### Solution
Edit `php-fpm.conf`

Change line `pm.max_children = 5` to `pm.max_children = 300`

Restart php-fpm

**Comment by DenBeke** [comment]
I'll look if I have the same here...

But why doesn't Nginx have the same problem?

**Comment by abiosoft** [comment]
It does. 

The link I posted was based on nginx.

**Comment by abiosoft** [comment]
Erm.. I was right and wrong. :smile: 

A bug in caddy is responsible for this and a fix is on the way.

However, it is still advisable to increase `pm.max_children` if you are expecting large amount of requests.

Thanks a lot @DenBeke for catching this.

**Comment by DenBeke** [comment]
Want me to test the pull request #457 ?

**Comment by abiosoft** [comment]
Sure, go ahead. Thanks.

**Comment by DenBeke** [comment]
#457 works perfectly for me!
If things hang a little now it's clearly due to high mysql/php load... Thanks, @abiosoft !

**Comment by mholt** [comment]
Yay! Drinks all around :hotsprings:
