### ISSUE TITLE
Add support for LetsEncrypt SAN certificates

### ISSUE THREAD

**Issue by scottweston** [mholt/caddy#456]
Currently if I create the following entry in my `Caddyfile`:

```
site.example, www.site.example {
  root /srv/site.example
}
```

I end up with two certificates (one for `site.example` and one for `www.site.example`). It would seem to me that in this situation a single SAN certificate would make more sense.

**Comment by mholt** [comment]
Not really interested in doing this; certificates are automatically managed so you as the user shouldn't really have to care about it, plus it adds needless complexity; see #445. Thanks for the comment though!

**Comment by upsuper** [comment]
SAN certificates have an advantage that client would not need to send SNI to get the proper certificate.

There are two advantages for not requiring SNI:
1. it enables some old systems / browsers to access the website
2. it allows users to avoid leaking the domain they are visiting

**Comment by mholt** [comment]
I appreciate the comment, so let me respond to both advantages you've mentioned.

> 1. it enables some old systems / browsers to access the website

This is not a goal of Caddy. Especially with regards to security, people need to update their software. If you have to serve insecure clients, use other software.

> 2. it allows users to avoid leaking the domain they are visiting

True, SNI transmits a hostname in the clear, but even without SNI, the hostname can be leaked by the preceding DNS lookup. Also, without SNI, the IP address of the request uniquely identifies the hostname. Finally, [TLS 1.3 will probably introduce encrypted SNI](https://www.ietf.org/proceedings/interim/2014/07/20/tls/slides/slides-interim-2014-tls-2-6.pdf).
