### ISSUE TITLE
Prevent access to hidden files not working

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#458]
https://caddyserver.com/docs/rewrite gives:

```
rewrite {
    r   ^\.(.*)
    to  /403.html
}
````

As a snippet to hide dotfiles.

However it doesn't work in two simple test cases:

* http://s.natalian.org/2015-12-21/1.sh.txt
* http://s.natalian.org/2015-12-21/2.sh.txt

```
X1C3:/tmp/foo$ bash 1.sh.txt
v0.8.0-24-ga5836ae
2015/12/21 21:33:11 Caddyfile:2 - Parse error: Unknown directive 'r'
1.sh.txt: line 1: kill: (12041) - No such process
X1C3:/tmp/foo$ bash 2.sh.txt
v0.8.0-24-ga5836ae
Activating privacy features... done.
localhost:2015
pass=secret
FAIL
```

**Comment by abiosoft** [comment]
The first line in the caddyfile must be a site.

```
localhost

rewrite {
    r   ^\.(.*)
    to  /403.html
}
```

**Comment by kaihendry** [comment]
Oh ok, I updated my little test case. Same problem:

http://s.natalian.org/2015-12-22/1.sh.txt

```
X1C3:~/tmp/caddy/cases/1$ bash 1.sh.txt
v0.8.0-24-ga5836ae
Activating privacy features... done.
localhost:2015
pass=secret
FAIL
```

**Comment by mholt** [comment]
I may be reading it wrong, but it looks like your regex `^\.(.*)` only matches requests that begin with a dot, which request paths never do (they always start with `/`)

**Comment by kaihendry** [comment]
Well, I got that rule from your docs: https://caddyserver.com/docs/rewrite

I think as you say `r   ^/\.(.*)` works for TLD dotfiles. but not for paths like `/foobar/.creds.ini`.

I think the docs "to hide dotfiles" should be updated to `r   /\.(.*)`. On cursory testing it seems to work for me. http://s.natalian.org/2015-12-22/3.sh.txt

**Comment by mholt** [comment]
Ah, that would do it. No need to limit the pattern to the beginning of the path, I guess. Just updated it locally and will deploy eventually. Thanks!

**Comment by jiko** [comment]
I realize this issue is closed, but I want to share my approach to hiding dotfiles:
```
rewrite {
  if {file} starts_with .
  status 404
}
```
I find this much more readable, and was surprised it works. Thanks for including conditionals.

**Comment by kaihendry** [comment]
That's cool. I still don't 100% grok Caddyfile's syntax. I wonder if that can by applied globally, across all my sites without duplication?

**Comment by mholt** [comment]
You can use import to achieve that.

**Comment by kaihendry** [comment]
So every service definition would have a line like: `import notdotfiles.conf` ?
