### ISSUE TITLE
error creating client: registration error: acme: Error 400 - urn:acme:error:malformed - Unable to read/verify body :: Parse error reading JWS

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#459]
```
sg:~/caddy$ cat test.sh
go version
GIT_DIR=~//go/src/github.com/mholt/caddy/.git git describe --always
curl ip.dabase.com # show my ip is right
host ssl.dabase.com
cat << EOF > Caddyfile
https://ssl.dabase.com {
}
EOF
caddy -agree -email hendry@iki.fi -log stderr
sg:~/caddy$ bash test.sh
go version go1.5.2 linux/amd64
v0.8.0-24-ga5836ae
128.199.115.232
sg.dabase.comssl.dabase.com is an alias for sg.dabase.com.
sg.dabase.com has address 128.199.115.232
Activating privacy features...2015/12/21 21:49:36 [INFO] acme: Registering account for hendry@iki.fi

2015/12/21 21:49:36 error creating client: registration error: acme: Error 400 - urn:acme:error:malformed - Unable to read/verify body :: Parse error reading JWS
sg:~/caddy$
```

**Comment by mholt** [comment]
That's strange. What happens if you clear your ~/.caddy folder and try again? (Note: If you have previously-issued certs you want to keep, then try deleting just the ~/.caddy/letsencrypt/users folder)

**Comment by mholt** [comment]
Ah, actually, I knew I saw this error somewhere before... I bet you're running into this http2 issue: https://github.com/xenolf/lego/issues/51

**Comment by kaihendry** [comment]
After reading through #51.. I'm not sure how to work around the issue... do I need to wait it out until LetsEncrypt's "boulder" is fixed?

**Comment by mholt** [comment]
Are you using Go tip? Or Go 1.5?

**Comment by kaihendry** [comment]
I was using go version go1.5.2 linux/amd64 but I could update I guess.

**Comment by mholt** [comment]
Not necessary; was just curious if your env matched the one in that other issue. Keep an eye on it and see if any fixes are made upstream. I'm not sure of a workaround right now (haven't experienced this issue myself) but if you find one, feel free to let us know!

Going to close this but feel free to comment if there's anything useful to add (like a workaround).
