### ISSUE TITLE
Leveraging http2 server pushing in a directive?

### ISSUE THREAD

**Issue by calebmer** [mholt/caddy#460]
Is there a directive to leverage http2 server pushing? For example, I have a caddy proxying an html page with a couple of scripts and styles. Can caddy detect these styles and scripts then push them to the browser using http2?

**Comment by mholt** [comment]
Not yet, we're waiting for the Go standard library to support this.

**Comment by mholt** [comment]
This is in the words in #1215.

**Comment by calebmer** [comment]
This is awesome 🎉

Caddy just keeps getting better and better. Thanks for notifying me 😊
