### ISSUE TITLE
Wrog mime type for css files

### ISSUE THREAD

**Issue by kkayal** [mholt/caddy#462]
It seems that caddy serves css files with the mime type **"text/plain"** instead of **"text/css".**

Firefox definitely loads my css file, but ignores the content with the following error message on the console:

    The stylesheet http://localhost:2015/main.css was not loaded because its MIME type, "text/plain", is not "text/css". hallo.html

I can also see that in the headers. The request header contains

    Accept: text/css,*/*;q=0.1

And the Response header contains:

    Content-Type: text/plain; charset=utf-8

My configuration;

- Windows 7
- Downloaded Caddy with all options enabled for windows
- No Caddyfile
- I am browsing http://localhost:2015/hallo.html and the content is shown, just without the css
- I have launched caddy on the console with no options.

My hallo.html:
~~~~~~~~
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Hallo</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" type="text/css" href="main.css" />
	</head>
	<body>
		<p>Hallo</p>
	</body>
</html>
~~~~~~~~

My main.css file
~~~~~~~~
body {
	color: red;
}
~~~~~~~~

Any ideas how to tell Caddy to serve *.css files with the mime type "text/css"

**Comment by mholt** [comment]
That's strange, never seen that before.

But `mime .css text/css` should do the trick.

**Comment by kkayal** [comment]
Thanks, that solved the issue.
