### ISSUE TITLE
Consider using fasthttp instead

### ISSUE THREAD

**Issue by thedrow** [mholt/caddy#466]
See https://github.com/valyala/fasthttp
It currently doesn't support HTTP 2.0 but it is 10 times faster than net/http.
The library can be used to handle anything that isn't HTTP 2.0 or alternatively we can contribute HTTP 2.0 support.

**Comment by abiosoft** [comment]
The first 4 points under _"Are there known net/http advantages comparing to fasthttp?"_ section of the readme for fasthttp should answer your question.
> * net/http supports HTTP/2.0 starting from go1.6.
> * net/http API is stable, while fasthttp API constantly evolves.
> * net/http handles more HTTP corner cases.
> * net/http should contain less bugs, since it is used and tested by much wider audience.

**Comment by thedrow** [comment]
If we, as a community want to adopt a better library we need to be able to test it in production.

**Comment by mholt** [comment]
I'm not currently interested in swapping out net/http. The reasons aren't compelling enough.
