### ISSUE TITLE
listen tcp :5000: bind: adress already in use

### ISSUE THREAD

**Issue by computerlyrik** [mholt/caddy#473]
I want to setup caddy as a proxy for https.

Setup example:
- I have a docker VM with a service running on ```localhost:5000```
- my Caddyfile as follows:
```
https://mydomain.com:5000  {
  proxy / localhost:5000
}
```

....the above error appears. Why?

I verified via nmap, that the port 5000 on public IP (mydomain.com) is closed.

**Comment by mholt** [comment]
Which address is already in use? Run `caddy -log stderr` to get the full output and share it here.

**Comment by computerlyrik** [comment]
...updated title, added https:// in first post
```
Activating privacy features...2015/12/31 22:55:22 [INFO] Checking certificates for 2 hosts
 done.
2015/12/31 22:55:22 listen tcp :5000: bind: address already in use
```

When using the directive `bind mydomain.com` then Caddy starts with ports 80 and 5000.
But i get a `502 Bad Gateway` on the site.

**Comment by mholt** [comment]
It can't bind to :5000 because your backend is already doing that, I'd imagine.

**Comment by computerlyrik** [comment]
Yes, with bind directive it is working. See updated comment above

**Comment by mholt** [comment]
See issue #28 about that... we can't just keep flip-flopping.
