### ISSUE TITLE
The “{>Header}” placement should be case-insensitive

### ISSUE THREAD

**Issue by kseistrup** [mholt/caddy#476]
Since [HTTP message headers are case-insensitive](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2), the `{>Header}` placement should also be case-insensitive.

**Comment by mholt** [comment]
Thanks for the report! Feel free to pull the latest from master if you want to double-check the fix.

**Comment by kseistrup** [comment]
That was fast!  Thanks, and happy new year!  I'll check the patch tomorrow.
