### ISSUE TITLE
Regular expressions in proxy paths?

### ISSUE THREAD

**Issue by cboettig** [mholt/caddy#478]
Can proxy paths use regular expressions?

I'm trying to translate [this nginx file](https://gist.github.com/cboettig/8643341bd3c93b62b5c2) into Caddy.  My [attempt at a Caddyfile](https://gist.github.com/cboettig/18e1becaa8974139adff),  errors in the same way that the nginx file would error if the regular expression in the second proxy line was wrong, and that proxy line uses regular expressions:

```nginx
     location ~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
            proxy_pass http://jupyter;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

        }
``` 

I tried translating that into Caddyfile as: 

```
  proxy {{.PathMatches "~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/?"}} jupyter:8888 {
    proxy_header X-Real-IP {remote}
    proxy_header Host {host}
    websocket
  }
```

but it's not clear to me from the documentation if I can actually do that (e.g. if `.PathMatches` takes regular expressions.  I guess it doesn't say that it does...)  Any suggestions?

**Comment by mholt** [comment]
Go regular expressions are slow so I haven't implemented regexp path matching. If I were you, I'd put all those behind a single unique path to proxy (e.g. `/backend/whatever`) to keep everything organized, then proxy `/backend`. There might be some caveats to that but it's a good way to structure your web app.

**Comment by abiosoft** [comment]
Yeah. This could work.
```
rewrite {
    r "~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/?"
    to /proxy/{uri}
}
proxy /proxy/ jupyter:8888 {
    proxy_header X-Real-IP {remote}
    proxy_header Host {host}
    websocket
    without /proxy/
}
```

**Comment by cboettig** [comment]
Thanks both.  Right, it would be nice if the Jupyter dev team had made the webapp a bit more tidy for proxy use, but rewriting that is beyond my scope.  

The rewrite command looks like is should do the trick.  Using that, the app mostly works but cannot connect to the python kernel.  But you've answered the `regex` question so I suspect the remaining issue is beyond the scope here, so marking this closed. Thanks again for the help.

**Comment by ghostsquad** [comment]
sorry for resurrecting an old thread, but is this string accurate?
`r "~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/?"`

This looks like it's including a parameter from the nginx config `~*` and that actually shouldn't be part of the pattern.

**Comment by onny** [comment]
@ghostsquad doesn't work for me too
