### ISSUE TITLE
Multiple imports fail

### ISSUE THREAD

**Issue by kseistrup** [mholt/caddy#480]
I installed the latest git version in order to test if #476 had been solved properly, and all of a sudden I can't even start caddy.

My caddy file is basically a long list of
```py
import vhosts/vhost1.conf
import vhosts/vhost2.conf
  ⋮
import vhosts/vhostN.conf
```
and caddy now barfs at the second import:

```sh
2016/01/01 16:01:41 caddy.conf:2 - Parse error: Unknown directive '/etc/caddy/vhosts/vhost2.conf'
```
Any suggestions?

**Comment by kseistrup** [comment]
Given the two files, `caddy.conf`
```sh
# example.com

example.com {
  root /srv/example.com
  import /etc/caddy/logging.conf
}

www.example.com {
  redir https://example.com{uri}
  import /etc/logging.conf
}

# example.net

example.net {
  root /srv/example.net
  import /etc/caddy/logging.conf
}

www.example.net {
  redir https://example.net{uri}
  import /etc/logging.conf
}

# eof
```
and `logging.conf`
```shㅁ
  errors /var/log/caddy/errors.log
  log  / /var/log/caddy/access.log "{when}	{remote}	{scheme}://{host}{uri}	{method} {proto} {status} {size}	{>User-Agent}"
```
caddy will barf at
```sh
2016/01/01 16:14:43 caddy.conf:8 - Parse error: Unknown directive 'https://example.com{uri}'
```
and if I comment out the two first `import` directives, caddy will instead barf at
```sh
2016/01/01 16:26:01 caddy.conf:21 - Parse error: Unknown directive 'https://example.net{uri}'
```

**Comment by mholt** [comment]
Oops, no that might be a bug. Let me look into it.

Btw, with #385 (which may or may not be contributing to your problem) you can use just one `import vhosts/vhost*.conf` instead.

**Comment by kseistrup** [comment]
Using `import vhosts/*.conf` doesn't really solve my problem. In each `vhosts/*.conf` file I have at least two imports:

```sh
redir {
  # redirects that are common to more than one host
  import redir.conf
  # redirects that are unique to this host
  /foo /bar
}
#  make it easy to change the logging format for more than one host at a time
import logging.conf
```
It would be a pity to be restricted by a single import per caddy file.

For now I have reverted to 0.8 that didn't have this problem.

**Comment by mholt** [comment]
You can't use import inside another directive, it is it's own directive.

**Comment by kseistrup** [comment]
That is not clear from the documentation that reads

»
### Syntax
```python
import file
```
* ` file` is the file to include. Its contents will replace this line, as if that file's contents appeared here to begin with.

«

**Comment by kseistrup** [comment]
But even if I put the entire `redir` stanza in its own `.conf` file I would still have two imports per caddy file.

**Comment by mholt** [comment]
I was able to reproduce the bug introduced in #385 thanks to your instructions. The commit I'm about to push should fix the issue. Thanks for the detailed report!

Tested with multiple imports and with glob pattern (which should save you some typing).

**Comment by kseistrup** [comment]
Thanks, I look forward to trying it.
