### ISSUE TITLE
Failed to get certificate: The server could not validate our request.

### ISSUE THREAD

**Issue by Fristing** [mholt/caddy#482]
Hi,
I want to use https with my config but i don't know why i have this error : 
"./caddy -conf="test/Caddyfile" -agree
Activating privacy features...
2016/01/02 21:47:09 [test.qlaffont.com] failed to get certificate: The server could not validate our request.".

This is my config file:

```
localhost:80, test.qlaffont.com {
	startup php-cgi -b 127.0.0.1:9000 &
	bind 1925.168.1.163:80 
	errors {
		log error.log
	}
	browse
	root /home/uiop/Bureau/test
	ext .html .htm .php 
	fastcgi / 127.0.0.1:9000 {
		ext   .php
		split .php
		index index.php
	}
	gzip
	basicauth /secret Bob mdp 
	rewrite /contact /secret
	tls qlaffont13.2@gmail.com
}
```

Thanks for all.
QL.

**Comment by Fristing** [comment]
2016/01/02 22:24:22 [test.qlaffont.com] failed to get certificate: Could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied
uiop@debian:~/Bureau$ ./caddy -conf="test/Caddyfile" -agree -email "qlaffont13.2@gmail.com"
Activating privacy features...
2016/01/02 22:24:32 [test.qlaffont.com] failed to get certificate: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied

**Comment by mholt** [comment]
Run with `-log stderr` and report back all the output. Thanks!

**Comment by Fristing** [comment]
Thanks. This is the output : 
root@debian:/home/uiop/Bureau# ./caddy -conf="test/Caddyfile" -agree -email "qlaffont13.2@gmail.com" -log stderr
Activating privacy features...2016/01/03 09:45:45 [INFO] acme: Obtaining bundled certificates for test.qlaffont.com
2016/01/03 09:45:45 [INFO] acme: Trying to solve TLS-SNI-01

2016/01/03 09:45:47 [test.qlaffont.com] failed to get certificate: The server could not validate our request.

**Comment by Fristing** [comment]
@mholt  after that if you want i can traduce your doc + your presentation page on french language.

**Comment by hubertbanas** [comment]
```bash
    bind 1925.168.1.163:80
            ^
```

Probably not related to the issue but just noticed this.

**Comment by Fristing** [comment]
wtf xD. i check this

**Comment by Fristing** [comment]
Thanx @hubertbanas I correct and I have new error output. "
root@debian:/home/uiop/Bureau# ./caddy -conf="www/Caddyfile" -agree -email "qlaffont13.2@gmail.com" -log stderr
Activating privacy features...2016/01/03 17:03:35 [INFO] acme: Obtaining bundled certificates for test.qlaffont.com
2016/01/03 17:03:35 [INFO] acme: Trying to solve TLS-SNI-01

2016/01/03 17:03:38 [test.qlaffont.com] failed to get certificate: The server could not validate our request.
"

**Comment by mholt** [comment]
The most likely reason for this is that you're behind a load balancer or SSL terminator. Or the domain is not pointing to your machine. Any of those relevant to you?

**Comment by Fristing** [comment]
I'm soing some test on linux server ( on a virtual machine powered by virtualbox). Test.qlaffont.com have the same ip that my local machine.
And i'm not behind a load balancer or ssl terminator.

**Comment by mholt** [comment]
That's the problem.

```
$ nslookup test.qlaffont.com
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	Test.qlaffont.com
Address: 192.168.1.163
```

It resolves to an internal IP. It must be globally resolvable for LE to issue a cert successfully.

**Comment by Fristing** [comment]
Yes it's work on my dedicated server. Thanks for all QL.

**Comment by mholt** [comment]
@Fristing Don't let me forget about your offer to translate the docs into French. :smile: Maybe post a comment in #337 which is related.

**Comment by Fristing** [comment]
no problem ^^

**Comment by yitzhakbg** [comment]
___"...the domain is not pointing to your machine."___
Precisely my problem. I'm using a CDN so it doesn't issue a certificate. How can I get around it?

**Comment by mholt** [comment]
@yitzhakbg You'll have to wait until the dns-01 challenge is supported by Let's Encrypt. They're working on it; it's already on in their staging environment, but it's a little rough around the edges still. The DNS challenge simply requires them to do a DNS lookup rather than making requests to your machine.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks.
    
    On 19/1/16 01:59, Matt Holt wrote:
    
    
      @yitzhakbg You'll have to wait until
        the dns-01 challenge is supported by Let's Encrypt. They're
        working on it; it's already on in their staging environment, but
        it's a little rough around the edges still. The DNS challenge
        simply requires them to do a DNS lookup rather than making
        requests to your machine.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by Stalbek** [comment]
qlaffont would you please share how did you solve the nslookup issue... I face the same issue. I use dynamic dns bound to my server. What are the further steps for the following my be? I appreciate any comment just got stuck... Thanx a lot!
-----------------------------------------------------
nslookup mycom.dyndns.org

Server:  UnKnown
Address:  192.168.0.1

Non-authoritative answer:
Name:     mycom.dyndns.org
Address:  91.135.191.175

**Comment by robxx** [comment]
toggle your record's Cloudflare setting [DNS + HTTP proxy (CDN)] to **_off_** ie., set it to [**DNS only**] the first time.

**Comment by gRanid** [comment]
Answer here [https://stackoverflow.com/questions/48985995/gitkraken-and-github-failed-to-get-server-certificate-the-handle-is-in-the-wr](url)

**Comment by danilakacta** [comment]
//gitkraken
git config --global http.sslVerify false
git config --global https.sslVerify false
git config --global http.proxy ""
