### ISSUE TITLE
Install failed on Windows 64 bit machine

### ISSUE THREAD

**Issue by ankitgupta100** [mholt/caddy#485]
I downloaded caddy (windows 64 bit version) and tried installing it but it did not get installed and only shows 'activating privacy features'' in the log (attached). Tried custom build too, but same issue. 
![caddy1](https://cloud.githubusercontent.com/assets/2139778/12090755/ac1df430-b317-11e5-950f-9bcc32760afa.png)

**Comment by abiosoft** [comment]
It is running perfectly :blush:,  open `http://localhost:2015` in your browser.

You probably want to create a Caddyfile and add more configurations.

**Comment by ankitgupta100** [comment]
I tried that, but the page doesn't exist. I also don't see any installation files in the system.

**Comment by abiosoft** [comment]
It is not an installer, it is just a single binary. If you get a 404 page, it is valid. Try creating an `index.html` page in that directory and see if it shows.

**Comment by ankitgupta100** [comment]
Ah, got it working. Thanks.

**Comment by abiosoft** [comment]
Glad to hear that.
