### ISSUE TITLE
Allow basicauth to use environment variables?

### ISSUE THREAD

**Issue by ianwalter** [mholt/caddy#486]
This didn't seem to work for me:
```
basicauth / user {$PASSWORD}
```
While this did:
```
basicauth / user password
```
If this is not a mistake on my part, please consider it a feature request.

**Comment by abiosoft** [comment]
Try 
```
basicauth / user {$PASSWORD} 
# it can be any other path apart from /
```

That syntax is for multiple lines. e.g.
```
basicauth user {$PASSWORD} {
    /home/protectedfile.txt
    /protected
}
```

**Comment by ianwalter** [comment]
@abiosoft Sorry, my example was incorrect, I did include the path `/`. Still not able to use an environment variable.

**Comment by abiosoft** [comment]
What version of Caddy are you running  ?
```
caddy -version
```

**Comment by ianwalter** [comment]
v0.8.0

**Comment by abiosoft** [comment]
I could not reproduce this. Works for me.

What platform are you on and do you get the password prompt at all? 

Kindly double check if the environment variable is set. Or for test purpose, pass it directly when starting caddy.
```
PASSWORD=password /path/to/caddy
```

Thanks.

**Comment by mholt** [comment]
Also works for me. Unable to reproduce:

```
$ export PASSWORD=asdf
$ caddy
```

with this Caddyfile:

```
localhost {
	basicauth / user {$PASSWORD}
}
```

**Comment by ianwalter** [comment]
The use running Caddy probably didn't have access to the variable. Thanks!
