### ISSUE TITLE
New Browse Template

### ISSUE THREAD

**Issue by sinky** [mholt/caddy#488]
Hi,
i want to show you my browse template. -> https://github.com/sinky/caddy-utils/tree/master/browse_tpl
I've put together an static HTML demo. http://sinky.github.io/caddy-utils/browse_tpl/

In my opinion the current template is not very mobile friendly, even if it is responsive.

**Comment by abiosoft** [comment]
There are current and upcoming updates to the browse template that should roll out with the next patch release 0.8.1. It is available on `browse-tpl` branch. https://github.com/mholt/caddy/tree/browse-tpl

**Comment by sinky** [comment]
Oh, looks pretty nice. 
I would love to see that the entire table row is linked to the file / folder. Similar as in my template.

**Comment by abiosoft** [comment]
Contributions are always welcome but you will need to wait a bit for the template related PRs to be resolved.

Note that this is just the **default** template and it is configurable. You can always use your custom template.

Thanks :+1:

**Comment by sinky** [comment]
>Contributions are welcomed but you will need to wait a bit for the template related PRs to be resolved.
Can's get running my go installation. So i can't test changes. Perhaps someone else can do this.

> Note that this is just the default template and it is configurable. You can always use your custom template.
I know, i'm using my template right now.

Thank You.

**Comment by mungayree** [comment]
I wish to provide input that while browsing files can the template have mono-space fonts ?
Also I see the DeafultName width can be '*' to autoadjust the size/date aligned.

currently it is san-seriff. which align the web page fonts on various space and the date stamps look way sticking to the browser's edge.

mono-space fonts align all letter of same size so 'i' 'u' 'w' take same pixel width. i hope inputs provided will be helpful for presentation of file listing.
