### ISSUE TITLE
Sanity-check the root directory

### ISSUE THREAD

**Issue by RobertGrantEllis** [mholt/caddy#489]
Is it possible to implement a Caddyfile or command-line switch that forces Caddy to check whether the root directory exists and has appropriate permissions, and quits if not? Right now, it continues running even if the specified root directory does not exist, then serves 404 for every request.

**Comment by mholt** [comment]
No, because it's possible for the root directory to be created later during startup, for example, by cloning down a [git](https://caddyserver.com/docs/git) repository.
