### ISSUE TITLE
Use hostname

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#491]
When I setup a VPS/droplet/EC2 instance whatever, I use a FQDN like:

    core@foo ~ $ hostname
    foo.bar.example.com

In my ideal world I could have a `Caddyfile` like so:

    core@foo ~ $ cat Caddyfile
    tls hendry@example.com
    root /srv

I.e. it just takes on $(hostname) & so https://foo.bar.example.com would immediately work. But on 0.8 that doesn't seem to work by default. Unless I am missing something?

**Comment by abiosoft** [comment]
Is it possible to set the hostname as environment variable and use the environment variable inside Caddyfile as a workaround ?

```
{$HOSTNAME}
...
```

**Comment by mholt** [comment]
I believe your Caddyfile is missing the first line, which is the address to serve on?

**Comment by abiosoft** [comment]
@mholt yeah, he actually wants to omit the line and let Caddy infer it. I think.

**Comment by mholt** [comment]
Then how do we know if the first token is an address or a directive? It's ambiguous.

**Comment by abiosoft** [comment]
I see it gets even more complex here
```
http://server1, http://server2 {
    ...
}
```

**Comment by kaihendry** [comment]
It would be an address if it's before the curly brackets, no?

E.g. `$(hostname) { ... }`

**Comment by mholt** [comment]
Yes, or just at the top of the file. But I don't plan on executing shell code when parsing the Caddyfile ;)

**Comment by kaihendry** [comment]
What about some keyword that resolves to hostname? I am trying to avoid pre-processing my Caddyfiles, since I am setting up several machines with the same configuration.

**Comment by mholt** [comment]
Does a $HOSTNAME env var not work for you?

**Comment by kaihendry** [comment]
No... http://ix.io/niA doesn't work, unless I'm mistaken how to employ an ENV var in your configuration?

**Comment by mholt** [comment]
See https://caddyserver.com/docs/caddyfile - you need to use the placeholder notation like `{$HOSTNAME}`

**Comment by kaihendry** [comment]
Still don't understand. http://ix.io/niG also doesn't work.

**Comment by abiosoft** [comment]
Nope hostname environment variable does not work. I think it is a shell feature not an environment variable. You need to export it manually to the session running Caddy to use it. 

Except Caddy is gonna intercept the environment variable and call `os.Hostname()`.

**Comment by mholt** [comment]
That's what I mean, it's not a special case, you just have to set the env variable and then you can use it in all the Caddyfiles.

**Comment by kaihendry** [comment]
I still don't quite follow. Sorry. Are you going to add a hostname placeholder so that a `{HOSTNAME}` will work? https://caddyserver.com/docs/placeholders Or are you saying it's working already and I haven't got it working yet? :sad

**Comment by mholt** [comment]
It's working already. Set an env variable called HOSTNAME:

```
export HOSTNAME=example.com
```

Then use the placeholder in your Caddyfile:

```
{$HOSTNAME}
```

**Comment by kaihendry** [comment]
Sorry, it took me sometime to realise I need to pass HOSTNAME into Docker.

* http://s.natalian.org/2016-01-11/caddy.service
* http://s.natalian.org/2016-01-11/Caddyfile

Thank you for your patience!

**Comment by lgaticaq** [comment]
How to use a environment variable with multiple hostnames. Example:
```bash
export HOSTNAME="subdomain1.example.com, subdomain2.example.com, subdomain3.example.com"
```
I got a error
```bash
parse //subdomain1.example.com, subdomain2.example.com, subdomain3.example.com: invalid character " " in host name
```

**Comment by mholt** [comment]
Hi @lgaticaq, from the [Caddyfile tutorial](https://caddyserver.com/tutorial/caddyfile):

> A single environment variable does not expand out into multiple arguments/values.

Any further questions can be asked on the [forum](https://caddy.community).
