### ISSUE TITLE
Actually knowing when an asset was properly downloaded & how long it took

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#492]
In the old skool Apache/nginx httpd world one has to jump hoops to figure out if a large file was downloaded. For example an old nginx snippet I found:

          location /webc-27.1.iso {
                  index webc-27.1.iso;
                  post_action /afterdownload;
          }

          location /afterdownload {
                  resolver 8.8.8.8;
                  internal;
                  proxy_set_header Request $request;
                  proxy_pass http://dlcount.example.com/eu.php?elapsed=$request_time&ip=$remote_addr&body_bytes_sent=$body_bytes_sent&status=$request_completion;
          }

I don't know if this is possible to do with Caddy logging: https://caddyserver.com/docs/placeholders

But anyway would be nice if you had this use case nailed, since anyone delivering files on httpd could really do with this complete information.

**Comment by abiosoft** [comment]
Yeah, response placeholders can do that for you.

**Comment by kaihendry** [comment]
Cool, like how can I tell `largefile.iso` was entirely sent and how long it took?

**Comment by abiosoft** [comment]
> {latency} - Approximate time the server spent handling the request
> {size} - The size of the response body
> {status} - The HTTP status code of the response

I guess those three values should be enough to deduce that.

Example.
```
log / /access.log "{proto} Request: {method} {path} | Time: {latency}, Size: {size}, Status: {status}"
```

**Comment by mholt** [comment]
Closing, unless that didn't answer your question (feel free to reopen if need be).

**Comment by kaihendry** [comment]
I can confirm it works!

```
X1C3:/tmp$ time wget http://0.0.0.0:2015/f-23.iso
--2016-01-10 11:10:45--  http://0.0.0.0:2015/f-23.iso
Connecting to 0.0.0.0:2015... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1469054976 (1.4G) [application/x-iso9660-image]
Saving to: ‘f-23.iso’

f-23.iso              100%[==========================>]   1.37G  1.55GB/s   in 0.9s

2016-01-10 11:10:46 (1.55 GB/s) - ‘f-23.iso’ saved [1469054976/1469054976]


real    0m0.888s
user    0m0.093s
sys     0m0.793s
```


    HTTP/1.1 Request: GET /f-23.iso | Time: 879.801516ms, Size: 1469054976, Status: 200

**Comment by mholt** [comment]
Woo hoo!

**Comment by kaihendry** [comment]
Random thought:

    HTTP/1.1 Request: GET /latest.iso | Time: 4m26.48638024s, Size: 427819008, Status: 200
    HTTP/1.1 Request: GET /latest.iso | Time: 4.056127907s, Size: 28016640, Status: 200

First request downloaded successfully. Second was interrupted. I wouldn't know it was interrupted from the log unless I compared the file sizes.  Would be nice if there was simple a binary 1 or 0 log to determine if the entire asset was properly downloaded or not.

Another random thought, feel free to ignore is if the log was a line based JSON, like that proposed by http://jsonlines.org/examples/ it would way easier to parse.

**Comment by mholt** [comment]
I'll leave the "properly downloaded" part available for anyone who would like to contribute it - as long as it does not add considerable complexity to the log middleware.

As for JSON lines, you can specify your own custom log format.
