### ISSUE TITLE
No way to define multiple basic auth passwords

### ISSUE THREAD

**Issue by nob13** [mholt/caddy#493]
Right now there is no way to define multiple Basic Auth accounts in the configuration.

The basic auth-configuration sets only one username and password. Also the option with htpasswd-Files only fetches one user from it.

**Comment by captncraig** [comment]
```
basicauth / foo bar
basicauth / foo2 bar
```
works for me. Either uname/password gives access.
you could even do

```
basicauth / foo bar
basicauth / foo bar2
```
although I wouldn't recommend it. I'm not sure why the htpasswd option has the depreciation warning though. It seems a useful feature.

**Comment by mholt** [comment]
Ah yes, you can use basicauth more than once to specify multiple users. Let's go with that for now and see what happens.

And htpasswd support is a useful feature for those converting from Apache, but I would rather people not get too used to it going forward...

**Comment by clement-igonet-at-galaxy-semi** [comment]
Well, what's the acceptable solution at the moment ?
htpasswd allows to not write plain text password. What about my config files I would like to track on git ?
I can't imagine to put my Caddyfile with plain text password in any repo, so why not include htpasswd hash directly in Caddyfile itself ???
As in htpasswd file, blowfish, sha1 or "Unix crypt" could be available...
So, I do not understand how we can depreciate a method without providing a decent other one...

**Comment by mholt** [comment]
@clement-igonet-at-galaxy-semi If you would like to discuss this more, please open a new issue about it, thanks.
