### ISSUE TITLE
Global logging configuration

### ISSUE THREAD

**Issue by klingtnet** [mholt/caddy#494]
I would like to configure global settings for error and request logging.
Because I run caddy as a systemd service, the log should always be written to `std{out/err}`.
The [documentation](https://caddyserver.com/docs/errors) should mention the [default logging target](https://github.com/mholt/caddy/blob/cf5aa1bed1983db427ce5b8a8eb6ce0a23ce464c/caddy/setup/errors.go#L41), too.
Furthermore, suppressing the log of 4xx errors by default is also questionable.

**Comment by mholt** [comment]
Your first link is to the errors directive which logs errors in requests, the other link is to the process log, which are very different things.

> Furthermore, suppressing the log of 4xx errors by default is also questionable.

All request error logging is off by default. You can turn it on with the `errors` directive.

**Comment by klingtnet** [comment]
This means that I have to add the `errors` directive to every site definition to get request error logging on each request?

**Comment by mholt** [comment]
Yep. Like everything else with Caddy. If you want `gzip`, you have to add `gzip to every server block, etc. You can use `import` to reduce the number of repeated lines though.

**Comment by klingtnet** [comment]
Ok, I will accept that.
