### ISSUE TITLE
[question] How to rewrite wp-admin for wordpress

### ISSUE THREAD

**Issue by hubertbanas** [mholt/caddy#498]
With no rewrite the web structure looks like this

```
https://domain.com/index.php/about/
https://domain.com/index.php/news/
```
To make it "pretty" I added the following rewrite

```
rewrite {
  regexp .*
  ext    /
  to     /index.php?_url={uri}
}
```

So now it looks like this:
```
https://domain.com/about/
https://domain.com/news/
```
However, with the above rewrite the admin area at ```https://domain.com/wp-admin/``` is no longer accessible.

It can still be accessed when going directly at
```
https://domain.com/wp-admin/index.php
```
My question is how to exclude wp-admin from the rewrite.

**Comment by abiosoft** [comment]
An easier solution is coming in 0.8.1 but for now add another rewrite entry before that for the path, so it will now become.

```
rewrite /wp-admin {
  regexp .*
  ext    /
  to     /index.php?_url={uri}
}
rewrite {
  regexp .*
  ext    /
  to     /index.php?_url={uri}
}
```

**Comment by hubertbanas** [comment]
I just tried your suggestion but it doesn't work.
Can you explain how this will be handled in 0.8.1 please?

**Comment by abiosoft** [comment]
Sorry I made a mistake.

```
rewrite /wp-admin {
  regexp .*
  ext    /
  to     /wp-admin/index.php?_url={uri}
}
rewrite {
  regexp .*
  ext    /
  to     /index.php?_url={uri}
}
```

**Comment by abiosoft** [comment]
You can try that now if you can build from source.
In 0.8.1 its gonna be. Translates to if path does not start with `/wp-admin` and its not a valid file or directory, perform rewrite.
```
rewrite {
  if    {path} not_match ^\/wp-admin
  to    {path} {path}/ /index.php?_url={uri}
}
```

**Comment by hubertbanas** [comment]
This makes wp-admin accessible however nothing underneath is accessible anymore

Working links 
```
https://domain.com/wp-admin/edit.php?post_type=portfolio
```

Is now rewritten like this
```
https://domain.com/edit.php?post_type=portfolio
```

Which makes it inaccesible

I'm going to try 0.8.1

**Comment by hubertbanas** [comment]
@abiosoft 
I just tested it with the latest 060ab92d295ba9dd8e34115c92557d5eff5896ff and this works exactly how you described.

@mholt 
I will leave this open as a reminder for now. When you find a moment please add the following snippet to the https://caddyserver.com/docs/rewrite

Wordpress permalink
```
rewrite {
  if    {path} not_match ^\/wp-admin
  to    {path} {path}/ /index.php?_url={uri}
}
```

**Comment by mholt** [comment]
Thanks for the update. Is that rewrite guaranteed necessary for every Wordpress installation tho? Can't permalinks be customized?

**Comment by hubertbanas** [comment]
Permalink is not necessary to make Wordpress work with Caddy. By default the links in Wordpress are like this:
https://domain.com/?p=123

This rewrite will only be needed to make "pretty" links look like this:
```
https://domain.com/news
```

The settings is under:
Dashboard > Settings > Permalinks
and will need to be configure like this:
```
Custom Structure	https://domain.com/%postname%/
```

Taking Wordpress popularity I can only assume this question may come back quite often.

**Comment by mholt** [comment]
Cool, thanks for the clarification. I'll leave your comment here in case anyone with the same question is searching for it!

**Comment by TTy32** [comment]
Note: in caddy v2 you can just use:
`try_files {path} {path}/ /index.php`

**Comment by mholt** [comment]
@TTy32 Correct, but readers should be aware that the v2 `php_fastcgi` directive does this for you: https://caddyserver.com/docs/caddyfile/directives/php_fastcgi#expanded-form

**Comment by TTy32** [comment]
Ah, thanks for the heads-up, missed that!
