### ISSUE TITLE
Site search middleware

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#5]
How awesome would it be if your web server kept a static page search index (periodically updated) for your site and rendered search results onto a custom HTML template? No need for external services and no hassle setting it up - just another directive in the Caddyfile. I can think of many times in the past I would have used something like this if it was built right into my web server.

Thoughts on this? Feel free if you want to give it a shot - just comment here. This could be a fun and really useful middleware to have.

**Comment by pedronasser** [comment]
Could you give some more information you have in mind for this idea? An example?
How would this search work? How would the result be printed?

**Comment by mholt** [comment]
Here's what I was thinking:

- At startup, the middleware launches a service goroutine that runs for the lifetime of the server. Initially it creates an index of the site... presumably in memory, although there are good packages for lightweight persistent data stores available too.
- Periodically the service function re-indexes.
- An endpoint is "exposed" (meaning that a request to a certain URL would be handled by the search middleware and not passed onto other handlers) such as /search (customizable). A GET request here with a "q" parameter would perform a search.
- The search results would be rendered by a template specified by the user (or perhaps a custom template), similar to the browse middleware.
- The search endpoint could also be exposed as a JSON API

**Comment by pedronasser** [comment]
Ok, got everything.
I'll try work something out.

**Comment by mholt** [comment]
Awesome! You got it. This is something that would make a great addition to any site.

There is a pretty popular indexing library called [bleve](http://www.blevesearch.com) that might be worth looking into.

**Comment by mholt** [comment]
Yay, this is done! \o/ Thanks @pedronasser

**Comment by blankoworld** [comment]
@mholt what's about this functionnality? Which directive should I use to have a search bar in my website and a /search endpoint?

**Comment by francislavoie** [comment]
@blankoworld I think it was https://github.com/pedronasser/caddy-search, but it doesn't seem supported anymore as far as I can tell. It's not in the official list of plugins anymore
