### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by alehano** [mholt/caddy#501]
Hi. When I set `redir https://mydomain.com{uri}` to https redirect, as described here https://caddyserver.com/docs/redir
my browser say "infinite redirect".

May be I should write `redir / https://mydomain.com{uri}` ?

**Comment by abiosoft** [comment]
Why would you want to redirect all requests to same server ? That's truly a redirect loop.

**Comment by mkody** [comment]
I think he's trying to redirect `http` to `https`.
You should try this:
```
http://mydomain.com {
	redir https://mydomain.com{uri}
}
https://mydomain.com {
	# Your website config
}
```

**Comment by alehano** [comment]
Yes, I'm trying redirect http to https. Thanks @mkody!
