### ISSUE TITLE
Multiple servers and Lets Encrypt Domain Validation

### ISSUE THREAD

**Issue by martijnve** [mholt/caddy#503]
When you have multiple servers, say for failover or loadbalancing purposes, the Domain Validation by Lets Encrypt is a problem. Imagine server B is trying to do DV and the request from LE gets routed to server A.

I'm aware this is not a simple issue, resolving it will require some form of communication between multiple caddy servers.

My idea for the simplest solution would be to have a configurable datastore (either on the FS or some DB) that can optionally be shared between hosts. This way assuming the storage is protected against race conditions, very little complicated server logic will be needed.

**Comment by mholt** [comment]
This will be worked around much more easily once Let's Encrypt activates the dns-01 challenge on their servers. We'll work some way into Caddy to take advantage of it (probably using env variables) and that should solve the load balancing situation.

For the record, it's a known issue: https://caddyserver.com/docs/automatic-https
