### ISSUE TITLE
How to disable "redirect http to https"?

### ISSUE THREAD

**Issue by kk44** [mholt/caddy#504]
I want to listen :80 with nginx, and listen :443 with caddy's "Automatic HTTPS". 
But I don't known how to disable the "redirect http to https".

**Comment by mholt** [comment]
That's not gonna work, unfortunately - Caddy needs port 80 to solve challenges with Let's Encrypt.

**Comment by abiosoft** [comment]
A workaround could be to have a config block for port 80 and proxy requests to Nginx. Caddy has to be in control of both 80 and 443 for auto LE and Nginx will need to listen on another port.
```
https://yoursite.com {
    ... # your caddy configs.
}
http://yoursite.com {
    proxy / localhost:<ngnix_port>
}
```

**Comment by kk44** [comment]
Thanks for your help! @mholt @abiosoft
