### ISSUE TITLE
0.8.1 causing 404 on sub-pages

### ISSUE THREAD

**Issue by mgibbs189** [mholt/caddy#506]
In prior versions, the following config worked properly on a WordPress install:

```
wp.dev:80 {
  root /usr/local/var/www/wp.dev/public
  fastcgi / localhost:9000 php
}
```

After upgrading, all sub-pages show a 404 error.

After noticing this error, I modified my `Caddyfile` based on the 0.8.1 rewrite feature (see below). It works now, but I'm wondering - **is this a bug, or an intentional change?**

```
wp.dev:80 {
  root /usr/local/var/www/wp.dev/public
  fastcgi / localhost:9000 php
  rewrite {
    ext /
    to /index.php
  }
}
```

**Comment by mholt** [comment]
What do you mean by "sub-pages"?

**Comment by mgibbs189** [comment]
I mean `http://wp.dev/about/` or `http://wp.dev/docs/installation/` -- anything that isn't the homepage.

**Comment by mholt** [comment]
Hmmm no that shouldn't have changed. Nothing in the commits since 0.8 stick out to me as an obvious cause of this. @abiosoft is our resident PHP expert :smile: so I'll ping him and see if he has an idea.

**Comment by hubertbanas** [comment]
@mgibbs189 
Check https://github.com/mholt/caddy/issues/498 for the new rewrite syntax.

**Comment by abiosoft** [comment]
I'm actually surprised the former config works directly without adding `/index.php/path` e.g. `https://domain.com/index.php/about/`. :neutral_face: 

You can do without `ext`. In fact there's consideration depreciating `ext` since rewrite condition can now be used to achieve it.

Go with the recommendation by @hubertbanas.
```
rewrite {
  if    {path} not_match ^\/wp-admin
  to    {path} {path}/ /index.php?_url={uri}
}
```

**Comment by mholt** [comment]
Ohhh yeah, I keep forgetting WordPress doesn't use actual files like that. Now I'm also surprised that your old config worked without a rewrite. Anyway, that recommendation should do the trick.

**Comment by mgibbs189** [comment]
Thanks. closing

**Comment by pwFoo** [comment]
This example should also be added to the documentation?
```
rewrite {
  if    {path} not_match ^\/wp-admin
  to    {path} {path}/ /index.php?_url={uri}
}
```
