### ISSUE TITLE
Rebuild 32 bit downloads.

### ISSUE THREAD

**Issue by teodor-pripoae** [mholt/caddy#508]
Hi,

There was a security release for go (1.5.3) which addresses a security vulnerability in `crypto/tls`. Since caddy is handing ssl, I think the binaries available for download should be rebuilt using the patched version.

https://groups.google.com/forum/#!topic/golang-dev/MEATuOi_ei4

**Comment by incon** [comment]
Go 1.4 is used to create the builds.

**Comment by teodor-pripoae** [comment]
Cool, thank you for your fast response !

**Comment by mholt** [comment]
[Truth](https://twitter.com/caddyserver/status/686633940363288576) - and thanks for the concern. We'll be skipping 1.5 entirely and will upgrade to Go 1.6 when it is stable.
