### ISSUE TITLE
Gzip svg

### ISSUE THREAD

**Issue by alehano** [mholt/caddy#509]
Gzip doesn't compress .svg by default. How can I set default extensions + svg?

**Comment by mholt** [comment]
Submit a PR to add .svg to this list: https://github.com/mholt/caddy/blob/a8c9d47805f17e6ae1e067b6fbc773d69cbb0ff4/middleware/gzip/request_filter.go#L18

**Comment by alehano** [comment]
Submitted https://github.com/mholt/caddy/pull/510

**Comment by alehano** [comment]
Here is another issue. The default ext list includes empty ext ``""``, but in a Caddy file I can't set `""` for urls without extension.

**Comment by mholt** [comment]
What do you mean exactly? (And thanks for the PR!)

**Comment by alehano** [comment]
I'm trying to add to a Caddyfile this:

```
gzip {
    ext "", ".html", ".md"
}
```
To gzip any pages without extension and specified extensions.
But get an error. Something like `extension must start from .`

**Comment by mholt** [comment]
[The extensions should be space-separated](https://caddyserver.com/docs/gzip) - no commas needed. And thanks for the report; I've committed a fix that will allow the empty value!
