### ISSUE TITLE
Sites isn't bound to http should not have auto-redirect to https

### ISSUE THREAD

**Issue by upsuper** [mholt/caddy#513]
I have a config similiar to
```
domain1 {
    ...
}

https://domain2 {
    ...
}
```

If I visit `http://domain2`, the server replies a 301 redirect to `https://domain2` which I do not expect, as domain2 is only bound to https, no http visit on that is expected.

I suppose the server should reply `No such host at :80` just like no rule is defined on that domain at all.

I finally add another rule with `http://domain2` to stop it from auto-redirecting.

**Comment by kk44** [comment]
duplicate issues #504 ?

**Comment by mholt** [comment]
This behavior is well-defined at the top of the [Automatic HTTPS](https://caddyserver.com/docs/automatic-https) page:

> Caddy will also redirect all HTTP requests to their HTTPS equivalent if the plaintext variant of the hostname is not defined in the Caddyfile.

It is quite likely that your users will not type https:// into their browser every time they access your site, so Caddy creates a 301 redirect for you. Trust me, your users *will* expect that redirect, even if you as the site owner don't. You can disable this, however, by defining your own port 80 variant of the host in the Caddyfile, as you discovered.

The redirects also serve a utility purpose: Caddy needs to guarantee that it can use port 80 to solve the Let's Encrypt http-01 challenge to obtain certificates.

I think @kk44 is right, this is the same question as that other issue. Thanks for your comment!
