### ISSUE TITLE
bind address and "Activating privacy features"

### ISSUE THREAD

**Issue by joeblew99** [mholt/caddy#517]
Got a simple problem.
Have a caddy web server runnng on my laptop, and i want to reach it from my Android phone.

Caddy config:
````
:8000 {
    #bind 0.0.0.0
    root ./dist
    log access.log
    rewrite /warehouse {
        r  (.*)
        to /?path={1}
    }

}

```

my laptop is 192.168.100.77 the network says.
i turned OFF the firewall
So everything should be sweet....

So from my android phone:
http://192.168.100.77:8000 gives me nada, zip, nothing.

I am on Mac. Any ideas ?

also when i run it from terminal i get this magical "Activating privacy features". Hmm is this maybe whats stopping reaching it from another machine ?

Thanks in advance. Caddy is freaking awesome BTW.

**Comment by mholt** [comment]
By "nothing" what do you mean? Most browsers usually display an error if there was, well, an error. Can you access it locally?

The "Activating privacy features" is just Caddy checking to see if it should enable TLS on your hosts. In your case it does nothing.

Frankly I do pretty much the same thing on my LAN (no `bind` needed) and it works fine.

**Comment by joeblew99** [comment]
hey Matt,

Yes i can access it locally using "localhost:8000" and "192.168.100.77:8000"

In the android browser i get a "ERR_ADDRESS_UNREACHABLE"

Mhhh...

**Comment by mholt** [comment]
Sounds like a LAN misconfiguration. Hmm. I would suggest making doubly sure that your phone is connected to the exact same network as your laptop...

**Comment by joeblew99** [comment]
Yeah good point. 99%sure they were both on the same 2.4 GHz WiFi.
I am on my way home and will try it at home. Will see how that goes.
Sorry about such a simple thing...

**Comment by joeblew99** [comment]
Yep it was the crazy office router. Works at home first time .
Closing this issue
