### ISSUE TITLE
Etags question

### ISSUE THREAD

**Issue by joeblew99** [mholt/caddy#518]
Does caddy support this now ? Just wanted to check since caddy is getting functionality so fast

**Comment by mholt** [comment]
Nope, this is still an open issue - #191 - also see #10 and #390. Anyone is welcome to tackle this, although it's related to caching so is kind of tricky to get right (which is one reason I haven't attempted it yet).

(Don't mind me for closing this as a duplicate, just want to keep the conversation in one place.)

**Comment by joeblew99** [comment]
Mhh would love to give it a crack, but on mad deadline so will have to take a rain cheque
