### ISSUE TITLE
CMS ajax file / image upload fails with 500 error code

### ISSUE THREAD

**Issue by pwFoo** [mholt/caddy#520]
I tested the Processwire CMS with Caddy. Backend and frontend works fine, but Ajax image upload fails with a 500 http error.

Is there a known bug? Or should it  be a CMS / PHP related problem? Works fine with apache.

**Comment by mholt** [comment]
I'm going to need more details -- use the [`errors`](https://caddyserver.com/docs/errors) directive to get the details of the error and report back what the error is, what action causes it, and all other pertinent, supporting information.

**Comment by pwFoo** [comment]
Hi @mholt,

I take a closer look. No caddy error message, just a 500 error code in the access log. It isn't a Caddy issue / bug, just a missing PHP package! Caddy works like a charm!

CMS error log
````
Error:  Call to undefined function ProcessWire\mb_strtolower()
````

Solution: Just install php-mbstring package...

**Comment by mholt** [comment]
Awesome, glad you figured it out!

**Comment by pwFoo** [comment]
No, thanks for your awesome work! :+1: 
I would love to replace Apache with Caddy as webserver and revproxy! :)
