### ISSUE TITLE
[small stuff] Newlines in README.txt,LICENSE.txt and CHANGES.txt files

### ISSUE THREAD

**Issue by My1** [mholt/caddy#521]
in the windows version of Caddy it might be desirable to use Windows newlines for those files as .txt files are usually opened with notepad which doesnt understand linux newlines which results in quite some mess. an alternative may be RTFs which should be the same in every OS...

**Comment by mholt** [comment]
Heh, forgot about that, thanks. :stuck_out_tongue: I changed the line endings to Windows style (\r\n) so the next release should be more readable. AFAIK editors on Linux can read Windows line endings without problem.

**Comment by My1** [comment]
well vi always shows a ^M althoutgh.
