### ISSUE TITLE
Segmentation fault on Raspberry Pi 2

### ISSUE THREAD

**Issue by TopHattedCat** [mholt/caddy#522]
When attempting to start Caddy on Raspbian installed on a Raspberry Pi 2, it gives a segmentation fault error and quits. If it is ran as root, it displays no error at all.

[Demonstration](https://tophattedcat.co.uk/files/2016/01/2016-01-20_21-19-45.webm)

**Comment by Xe** [comment]
Interesting. Can you install the `strace` package and run caddy by doing:

```console
$ strace caddy
```

**Comment by TopHattedCat** [comment]
![image](https://cloud.githubusercontent.com/assets/1351887/12465038/09d30a76-bfc4-11e5-8267-5649784c4ea9.png)

**Comment by mholt** [comment]
Woah, cool.

Is that just the Linux ARM from the download page? (any add-ons?) Or how did you build it?

**Comment by mholt** [comment]
Are you using the proxy directive, perchance? We saw this once before but it was fixed ages ago... What's your Caddyfile?

**Comment by mholt** [comment]
One more thing -- can you send me a copy of the binary you're running? (I want an exact copy, not re-downloaded or re-built.)

**Comment by mbirth** [comment]
On my RasPi2 with Ubuntu 15.10, it works fine as a normal user. Downloaded the binary yesterday (without addons).

**Comment by TopHattedCat** [comment]
It is the Linux ARM version from the download page with no addons. At first I tried it with a proxy directive, but the same thing happens still if it is removed.

[Caddy binary](https://tophattedcat.co.uk/files/2016/01/caddy)
[Caddyfile](https://tophattedcat.co.uk/files/2016/01/Caddyfile)

**Comment by jungle-boogie** [comment]
Hi @TopHattedCat, are you launching caddy with sudo?

**Comment by TopHattedCat** [comment]
Caddy gives a segmentation fault when **not** ran with sudo, and if it is ran with sudo it gives no error at all

**Comment by jungle-boogie** [comment]
@TopHattedCat,

okay, that makes sense because you're running on a port your user can't bind to.

**Comment by TopHattedCat** [comment]
The seg fault error also happens when the port is set to something >1024 with no sudo

**Comment by mholt** [comment]
@jungle-boogie No, segmentation faults go lower-level than lacking permissions. This is a memory violation.

@TopHattedCat I can reproduce the behavior. Your binary is only 5 MB. Caddy for ARM is 10 MB. What version is it, or how long ago did you download it?

**Comment by jungle-boogie** [comment]
hi @mholt, okay, but I've also experienced this with non root priv on low ports. Happy to see this is being looked into. I also understand correlation doesn't equal causation so I will try to reproduce on my own.

**Comment by mholt** [comment]
@TopHattedCat Your binary's SHA1 is `2f1c6bfede2d50c435a405d62ee8fbd6d8f14aaf`, but as downloaded from the website is `e90c61a2330296ae743162d6d544ef27c49543a3` - I think your file was just truncated/corrupted. Re-download and it should be fine.
