### ISSUE TITLE
Getting started not readable on IE11

### ISSUE THREAD

**Issue by peterennis** [mholt/caddy#524]
![capture17](https://cloud.githubusercontent.com/assets/140737/12469598/ebf288c8-bfa1-11e5-84a7-ed685ed36beb.PNG)

**Comment by mholt** [comment]
Sigh.

Does adding `display: block` to the `<main>` element of the page fix it?

**Comment by Xe** [comment]
It works fine on Edge:

![](https://i.imgur.com/kwdbnQ3.png)

Before adding `display: block` in IE 11 on Win 10:

![](https://i.imgur.com/hL9VsdK.png)

After:

![](https://i.imgur.com/jAxrBfX.png)

I suggest adding this CSS element.

**Comment by mholt** [comment]
Yeah, I figured it was that. I hate IE.

Made the change, will roll it out today.
