### ISSUE TITLE
Layered request handling

### ISSUE THREAD

**Issue by smcmurray** [mholt/caddy#526]
It would be nice to be able to layer request handling such that you could do things like:

* serve from one directory, and failing that, server from a different directory
* serve from filesystem, then failing that, proxy to app server (or vice versa).

**Comment by abiosoft** [comment]
Rewrite can cater for this to some extent.

**Comment by mholt** [comment]
Yes, rewrite is good for most of this. The problem with layering the handling is that it can quickly get out of control. Essentially it turns into scripting your own web server, and at that point you might as well just be using Go or JavaScript or something.

**Comment by mholt** [comment]
Going to close the issue for now.
