### ISSUE TITLE
caddy specific user-agent for ACME requests

### ISSUE THREAD

**Issue by jmhodges** [mholt/caddy#527]
I know the lego client underneath needs to add support for this, but it'd be cool for the Let's Encrypt project to see how many folks are using caddy specifically. We're really curious about its usage! Plus, if bugs come up later, we can have an easier time figuring out which project to contact.

**Comment by mholt** [comment]
Oops, are you not already seeing some user agents with "Caddy" in it? https://github.com/mholt/caddy/blob/6e340cb1d6debf00bfc208b28b27a4655285d2ba/main.go#L57

I'm curious too :smile: Please let me know if we have a bug and are not sending the proper UA!

**Comment by jmhodges** [comment]
*head in hands*

I just read the code wrong. I missed that global UserAgent. Whew, I'm going to get out of your tickets!

**Comment by mholt** [comment]
Haha, you're fine! Please don't hesitate at this stage because we want to make sure it's all working smoothly. You should already see Caddy in your UA logs but if you don't please let me know... :sweat:

**Comment by jmhodges** [comment]
Did a quick search and it's totally there!

**Comment by mholt** [comment]
In all honesty, that's the most relieving news I've heard all day :sweat_smile: phew
