### ISSUE TITLE
Caddyfile:2 - Parse error: Unknown directive 'template'

### ISSUE THREAD

**Issue by zemadmat** [mholt/caddy#530]
Hi,

I'm trying to use Caddy on a raspberrypi to serve markdown file. My Caddyfile looks like this
```
markdown / {
    template blog templates/blog.html
    template index templates/index.html
}
```
However when i start Caddy i have the following error:
> 2016/01/23 15:59:35 Caddyfile:2 - Parse error: Unknown directive 'template'

Should i add something sothat caddy will be able to understand the template directive ?

Cheers

**Comment by mholt** [comment]
The first line of your Caddyfile needs to be an address to serve on, e.g. `localhost`.

**Comment by zemadmat** [comment]
Many thanks for your quick reply !!
