### ISSUE TITLE
Add backend to log options

### ISSUE THREAD

**Issue by pwFoo** [mholt/caddy#531]
I will use Caddy as reverse proxy / load balancer and it looks good so far, but would be great to get backend address (proxy "to") logged to access.log. How could backend address / ip added?

**Comment by mholt** [comment]
Hmm, this isn't obvious to do because log executes before proxy does, so log doesn't know the request will be proxied. But there may be a clever way around this.

**Comment by pwFoo** [comment]
Would be great to know the backend for debugging, but shouldn't generate to much overhead...

**Comment by mholt** [comment]
I'll look into this, but in the meantime it would be ideal for your upstream to have a log.

**Comment by pwFoo** [comment]
Thanks, that isn't a problem! Would just be a nice to have ;)

**Comment by mholt** [comment]
@pwFoo Happy Birthday, this will go out with the next release of Caddy, or you can use it now by building from source. :+1: The placeholder you can use in your log format is `{upstream}`.
