### ISSUE TITLE
Htaccess Convertor ?

### ISSUE THREAD

**Issue by Fristing** [mholt/caddy#532]
Hi,
I want to use Cakephp Framework but url rewriting don't work.
It is possible to translate my 2 htaccess on caddy rules ?

.htaccess \rootwebserver
<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule    ^$    webroot/    [L]
    RewriteRule    (.*) webroot/$1    [L]
</IfModule>

.htaccess \rootwebserver\webroot
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

Thanks for All.
Best Regards
Quentin Laffont

**Comment by abiosoft** [comment]
```
rewrite  {
    to {path} {path}/ /index.php&{query}
}
```

**Comment by Fristing** [comment]
Thanks but this solution doesn't work.
Example my path css is : \rootwebserver\webroot\css\style.css and i can access with this url localhost/css/styles.css

and the browser don't find the style.css on the url.

**Comment by Fristing** [comment]
The framework is Cakephp 3 http://cakephp.org

**Comment by abiosoft** [comment]
can you share your Caddyfile ? I'll like to know the value of `root` if it is set.

**Comment by Fristing** [comment]
Caddyfile
localhost:80 {
  browse
  startup php-cgi -b 127.0.0.1:9000 &
  startup mysqld &
  header / {
      Access-Control-Allow-Origin  *
  }
  fastcgi / 127.0.0.1:9000 {
    ext   .php
    split .php
    index index.php
  }
  root C:\caddy\www
  tls off
  log access.log
  shutdown mysqladmin -u root shutdown
  rewrite  {
    to {path} {path}/ /index.php&{query}
    }
}

And structure is 
www
->cakephp
-->bin
-->config
-->logs
-->plugins
-->src
-->tmp
-->tests
-->vendor
-->webroot
---->css
---->img
---->js
->wordpress

**Comment by abiosoft** [comment]
Off topic: remove the ampersands (&) from your startup functions, they have no effect in here, that's only useful in a terminal.

Is cakephp the only app you want to serve. i.e. Will you reference it via `http://localhost` or `http://localhost/cakephp` ?

**Comment by Fristing** [comment]
is http://localhost/cakephp

**Comment by abiosoft** [comment]
Are you having other apps apart from cakephp on the same root directory ? If yes, then you should navigate to `localhost/cakephp/css/styles.css` instead.

```
rewrite /cakephp {
    r (.*)
   to /cakephp/webroot/{1} /cakephp/webroot/index.php&{query}
}
```
But if you want only cakephp to own localhost and you prefer to get the css file at `localhost/css/styles.css`.
```
rewrite{
   to /cakephp/webroot/{path} /cakephp/webroot/index.php&{query}
}
```

**Comment by mholt** [comment]
> Off topic: remove the ampersands (&) from your startup functions, they have no effect in here, that's only useful in a terminal.

Actually the ampersand runs the command in the background so as to not block the startup of the server.

**Comment by abiosoft** [comment]
> Actually the ampersand runs the command in the background so as to not block the startup of the server.

Is that a caddy feature ? or `os.Exec` does that out of the box ?

**Comment by mholt** [comment]
Caddy feature. :D https://caddyserver.com/docs/startup

> Each command that is executed at startup is blocking, unless you suffix the command with a space and &, which will cause the command to be run in the background.

**Comment by abiosoft** [comment]
:+1: 
> Caddy feature. :D https://caddyserver.com/docs/startup

**Comment by Fristing** [comment]
I try each solution and i have "No input file specified. 404 Not Found"

**Comment by abiosoft** [comment]
were you able to access the css files at least ?

**Comment by Fristing** [comment]
I am able to access to css file for the first solution but he don't load my index.php (root folder).

**Comment by abiosoft** [comment]
Now it shows its just a matter of getting cakephp config right, not that the rewrite is entirely wrong.

Try 
```
rewrite /cakephp {
    r (.*)
   to /cakephp/webroot/{1} /cakephp/webroot/index.php?{1}&{query}
}
```

**Comment by Fristing** [comment]
nice it's work thanks !
