### ISSUE TITLE
Repo for example Caddyfiles?

### ISSUE THREAD

**Issue by Sirikon** [mholt/caddy#533]
Related to Issues #532 and #497, I've seen many people using Caddy with PHP-FPM/HHVM (I use Caddy and HHVM for my personal website) and 'translating' the .htaccess files to Caddyfiles is a common and repeated task.

A repo of Caddyfiles for most popular PHP projects (or any environment which requires many redirect and url-rewrite rules) would be really helpful.

**Comment by mholt** [comment]
Yeah, feel free to add your examples to github.com/caddyserver/examples
