### ISSUE TITLE
Certificate requests too frequent

### ISSUE THREAD

**Issue by yitzhakbg** [mholt/caddy#534]
I'd like to understand this. I'm using the (default) automatic SSL certificate mechanism. Development entails frequent restarts drawing error messages (which cause server to fail) to the effect that that the requests are coming in too frequently.  Could defining an e-mail address certificate ID solve this by informing the certificate authority that its OK to reissue the same certificate?

**Comment by abiosoft** [comment]
Do you not define email address to bypass startup prompt or you only use the `-agree` flag ?

Are you running Caddy inside containers? If yes, I'd suggest you mount a host filesystem path that persists the certificates.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Now I hadn't thought of that? I am running in a container (with
    -agree) but I could persist the certificate. Where are the
    certificates located?
    
    On 25/1/16 14:18, Abiola Ibrahim wrote:
    
    
      Do you not define email address to bypass startup prompt or you
        only use the -agree flag ?
      Are you running Caddy inside containers? If yes, I'd suggest
        you mount a host filesystem path that persists the certificates.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by abiosoft** [comment]
`$HOME/.caddy` which will translate to `/root/.caddy` in the container.

I advised same on my docker image https://github.com/abiosoft/caddy-docker#run-the-image-1.

**Comment by yitzhakbg** [comment]
Error message:
caddy_1   | 2016/01/25 15:08:44 [levpoem.co.il] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: levpoem.co.il
sitescommon_caddy_1 exited with code 1

It worked before and I just ran it after a 24 hour rest. It says too many certificates already issued. **

Any way to erase/reset that?** .caddy is mapped to docker-caddy/dotcaddy but I never saw anything in there
According to your docker setup, mine seems OK. Do you see anything wrong in my setup (attached)

**Comment by yitzhakbg** [comment]
Error message:

caddy_1 | 2016/01/25 15:08:44 [levpoem.co.il] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: levpoem.co.il
sitescommon_caddy_1 exited with code 1

It worked before and I just ran it after a 24 hour rest. It says too many certificates already issued. **Any way to erase/reset that?** .caddy is mapped to docker-caddy/dotcaddy but I never saw anything in there
According to your docker setup, mine seems OK. Do you see anything wrong in my setup [HERE](https://www.dropbox.com/s/tuc9li9tocaalhh/caddy_setup.pdf?dl=0)?

**Comment by abiosoft** [comment]
You'll have to wait for some days. Its rate limit error from Let's Encrypt.

**Comment by yitzhakbg** [comment]
Wow! How many days? Would it help if I gave my e-mail address in the 
Caddyfile?

**Comment by abiosoft** [comment]
Its a domain level limit.

https://community.letsencrypt.org/t/quick-start-guide/1631/6
5 certificates per domain per 7 days per.

**Comment by mholt** [comment]
Email address or not, what you have to make sure to do is that the certificates stay on disk so Caddy can re-use them.

**Comment by yitzhakbg** [comment]
Thank you. How can I configure Caddy to run without SSL in the meantime?
I thought it was "tls off" but it seems not. Also, why you don't you 
issue -accept in the caddy command?

My Caddyfile:
http://192.168.99.100, https://192.168.99.100 {
   root /var/www/levpoem
#  tls yitzhakbargeva@gmail.com
}
http://www.levpoem.co.il {
   root /var/www/levpoem
   tls off
}
http://www.heartbt.co.il {
   root /var/www/heartbt
   tls off
}
46.101.221.201 {
   root /var/www/heartbt
   tls off
}

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Yes, I realize that now too bad I didn't know. How can I operate
    without SSL while I'm waiting for the renewal?
    
    On 25/1/16 17:54, Matt Holt wrote:
    
    
      Email address or not, what you have to make sure to do is that
        the certificates stay on disk so Caddy can re-use them.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mholt** [comment]
`tls off` or explicitly specifying `http://` in the address should do what you want.

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Tnx
    On 25/1/16 18:40, Matt Holt wrote:
    
    
      tls off or explicitly specifying http://
        in the address should do what you want.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mholt** [comment]
Hopefully that works for you :+1: Sorry about the rate limits, not much we can do about that for now, but while you're still experimenting with getting your setup right, you should use Let's Encrypt's staging server (use the -ca flag to set it to `https://acme-staging.api.letsencrypt.org/directory`)

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    thanks again. Does -ca have to be set explicitly or is it st that
    way by default? Correct me, but I understand that -ca is meaningless
    until 7 days pass to revive my certificates, right?
    
    On 25/1/16 19:59, Matt Holt wrote:
    
    
      Hopefully that works for you  Sorry about the rate
        limits, not much we can do about that for now, but while you're
        still experimenting with getting your setup right, you should
        use Let's Encrypt's staging server (use the -ca flag to set it
        to https://acme-staging.api.letsencrypt.org/directory)
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mholt** [comment]
No, try it again with the -ca option set to the staging server URL. By default, it is set to Let's Encrypt real production endpoint. The staging server has much higher rate limits, so you should be able to get certificates that way (but they won't be accepted by browsers -- use for testing and experimenting).

**Comment by yitzhakbg** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Wow. That's great just what I need over the coming week. Thanks
    
    On 25/1/16 20:49, Matt Holt wrote:
    
    
      No, try it again with the -ca option set to the staging server
        URL. By default, it is set to Let's Encrypt real production
        endpoint. The staging server has much higher rate limits, so you
        should be able to get certificates that way (but they won't be
        accepted by browsers -- use for testing and experimenting).
      —
        Reply to this email directly or view
          it on GitHub.
