### ISSUE TITLE
wildcard vhosts

### ISSUE THREAD

**Issue by asaif** [mholt/caddy#535]
I'm trying to create a vhost where all subdomains under example.org will serve the same content 
I've tried the following:

```
*.example.org {
root /var/www/
}
```
caddy started without any error, and  I got the following output 
*.example.org:80
but actually, it didn't work.

On nginx, I used to do this config 
```
server {
    listen       80;
    server_name  *.example.org;
    ...
}
```
or even to catch all 

```
server {
    listen       80;
    server_name  _;
    ...
}
```

**Comment by mholt** [comment]
Thanks for your comments -- already being discussed in #310 and #209. Caddy will eventually support wildcard characters in the hostname.
