### ISSUE TITLE
Serving static files from unrelated directories with proxy

### ISSUE THREAD

**Issue by calebmer** [mholt/caddy#536]
I develop node apps and in the past to serve static files I'd use the [`serve-static`](http://npmjs.com/serve-static) module. I'd like to use caddy for this instead. My root directory is `/static`, I proxy all other requests from `/` to my node app (`http://localhost:4000`). And I'd like to serve static files from `/dist` (not nested in `/static`) to `/assets`. Here's a folder structure:

```
├─┬ static
│ ├── promo.html
│ └── template.html
├─┬ dist
│ └── common.js
├─┬ lib
│ └── index.js
└── Caddyfile
```

Some preferred responses would be as follows:

- `/` → A response from the node server.
- `/people/1` → Another response from the node server.
- `/promo` → `/static/promo.html`
- `/template` → `/static/template.html`
- `/assets/common.js` → `/dist/common.js`

Looking at the docs, I couldn't find a good way to combine these functionalities. Do you have a recommendation?

**Comment by abiosoft** [comment]
Try this
```
# if directory is /assets/ change it to /dist/
rewrite {
    if {dir} is /assets/
    to /dist/{file}
}
# if /static/<path>.html exists; use it. otherwise, use the url the way it was.
rewrite {
    to /static/{path}.html {uri}
}
```

**Comment by calebmer** [comment]
This almost works, accept if I have nested assets. I tried:

```
rewrite {
    if {dir} starts_with /assets
    to /dist/{file}
}
```

…but there is no way to remove the base path from `{path}` short of regular expressions, which the docs warn about.

**Comment by calebmer** [comment]
Also, it looks like if a proxy rule has a base path of `/`, it overrides the rewrites.

**Comment by abiosoft** [comment]
proxy does not override rewrites, the url is sure rewritten before it gets to proxy and proxy will forward the new request path. A base path of `/` for proxy is saying you want to proxy all requests.

You can use regexp if you need to. Its not **that** bad though its a known issue that Go's regexp (written in Go) is not as fast as some other languages' (which are written in C).
```
rewrite /assets {
    r (.*)
    to /dist/{1}
}
```

**Comment by calebmer** [comment]
Ok, that helps. Would adding a `without` argument to `rewrite` make this faster? So for example:

```
rewrite /assets {
  without /assets
  to /dist{path}
}
```

**Comment by abiosoft** [comment]
It feels redundant since you can achieve it with regex and numbered captures as I did above and regex gives more flexibility.

On the basis of speed, you have a point but I'll like to know @mholt's view on this.

**Comment by mholt** [comment]
I'd use regex in this case, rather than adding another option.

**Comment by abiosoft** [comment]
I think we can close this now.
