### ISSUE TITLE
$_GET variables incorrect (WordPress)

### ISSUE THREAD

**Issue by mgibbs189** [mholt/caddy#537]
Hi, with the following (recommended) rewrite rules in place, `$_GET` variables are not being correctly handled by PHP.

```
rewrite {
  if    {path} not_match ^\/wp-admin
  to    {path} {path}/ /index.php?_url={uri}
}
```

URL: `http://mysite.dev/blog/?my_category=abcd`

Input: `$_GET`

Expected output:
```
array(
    'my_category' => 'abcd'
)
```

Actual output:
```
array(
    '_url' => '/blog/?fwp_category=indexing'
)
```

What am I missing?

**Comment by abiosoft** [comment]
Oh okay.

Try this rewrite instead
```
rewrite {
  if    {path} not_match ^\/wp-admin
  to    {path} {path}/ /index.php?_url={path}&{query}
}
```

**Comment by mgibbs189** [comment]
Better, thanks!
