### ISSUE TITLE
Deny access to special folder

### ISSUE THREAD

**Issue by Fristing** [mholt/caddy#539]
Hi,
How i can bind 127.0.0.1 to a special folder ?
Best Regards 
Quentin Laffont

**Comment by abiosoft** [comment]
Can you elaborate ? .

If you mean denying access to a folder, check https://caddyserver.com/docs/internal.
Or return 403 status with rewrite for the folder.
```
rewrite /folder {
    status 403
}
```

**Comment by Fristing** [comment]
Work

**Comment by flaviocopes** [comment]
Sorry to comment on this closed issue but `status` seems no longer working inside rewrite, what's an alternative way to do the same task?

**Comment by elcore** [comment]
Hello,

just use https://caddyserver.com/docs/status

**Comment by flaviocopes** [comment]
Thanks @elcore, I'd need it to use a regex. Basically I want to update https://github.com/getgrav/grav/blob/develop/webserver-configs/Caddyfile which worked with Caddy 0.8.2, but it's not working any more with the latest version of Caddy

**Comment by flaviocopes** [comment]
Got suggested to use something like

```
rewrite {
    r /(.git|cache|bin|logs|backups|tests)/.*$
    to /denyaccess
}

rewrite {
    r /(system|vendor)/.*\.(txt|xml|md|html|yaml|php|pl|py|cgi|twig|sh|bat)$
    to /denyaccess
}

status 403 /denyaccess
```

is this the only way?

**Comment by elcore** [comment]
I guess so, I am not 100% sure

ping @abiosoft
