### ISSUE TITLE
Suggestion: RPC library

### ISSUE THREAD

**Issue by joeblew99** [mholt/caddy#54]
https://github.com/grpc/grpc-go

It will provide language agnostics and a solid performance RPC base that looks like it will last a good while.

The IDL aspects will possibly supply transport agnostics too, but I have not dug deep enough on that yet

**Comment by bluecmd** [comment]
Is this suggestion for having the webserver expose RPCs or being able to proxy them?

**Comment by fabware** [comment]
I need grpc proxy, finding solutions.

**Comment by joeblew99** [comment]
Grpc gateway. It's on github and well supported I have found.

**Comment by nwgat** [comment]
to have future parity with other httpd server then this and #776 is required

**Comment by joeblew99** [comment]
Here is the GRPC gateway i was mentioning above:
https://github.com/gengo/grpc-gateway

From the GRPC model, it generates the JSON interfaces for Browsers to consume.
It does not provide two way true RPC. In other word, browsers can initiate calls, and it results in a standard restful call hitting the gateway, and then via GRPC hitting your GRPC facacde where computation happens and a Response goes back out through the same chain up to the Browser.

But if your Server initiates the call, it will not pass up to the Browser via WS or SSE. 

I think this is the true state of the code base. 

There looks to be the possibility to expose GRPC directly to the Browser as of a few days ago.
Trailer Header support is no in Chrome Browser. This was needed to allow the Browser to parse the GRPC protocol properly.  However what i dont know currently is if this Trailer support means that WS / SEE Proxy server becomes redundant now or not.

I would very much like to know myself, so please yell if you know.

https://github.com/grpc/grpc/issues/2786

**Comment by mholt** [comment]
@joeblew99 - and others in this issue - thanks for your comments! There is a lot of good value here, so I have linked to this issue from [a thread in our community forum](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127?u=matt) where we are aggregating ideas/requests for Caddy plugins. It's possible that such a proxy would be better suited as a Caddy plugin. But if all that was needed was a (fairly simple?) change to the proxy directive, perhaps we should explore that route.

If you want to continue discussing the plugin before development begins on it, feel free to start a new topic on the forum. :+1: Hope to see you participate with us there!

**Comment by joeblew99** [comment]
One last thing. The coachroachdb team has a great setup for handling grpc.
Worth checking out their code.

**Comment by mholt** [comment]
FYI, there is now a [grpc plugin](https://caddyserver.com/docs/http.grpc) that may do what you're looking for.
