### ISSUE TITLE
Allow for scheme prefix before fastcgi server's IP address

### ISSUE THREAD

**Issue by alexbilbie** [mholt/caddy#540]
My Caddyfile has the following directive

```
fastcgi / {$PHP_URL} php
```

The env var `PHP_URL` equates to `tcp://172.17.0.1:9000` and is set by my Docker setup. It appears Caddy does not support any sort of scheme prefix before the IP address and fails with the following error:

```
27/Jan/2016:17:04:40 +0000 [ERROR 502 /index.php] dial tcp: too many colons in address tcp://172.17.0.1:9000
```

Caddy also fails with a similar message if the scheme is set to `fastcgi://`

**Comment by abiosoft** [comment]
Yeah, you will need to remove the scheme.

**Comment by alexbilbie** [comment]
Could Caddy perhaps support `tcp` and `fastcgi` schemes at some point to save having to do some find and replace trickery before starting Caddy?

**Comment by abiosoft** [comment]
Yeah. Considering it already supports optional `unix:` prefix for unix sockets, it makes sense to allow it for tcp.

It's pretty straightforward for a newbie if anyone is interested in picking this up. But if no one does for a few days, I'll add it.

**Comment by mholt** [comment]
Should add tests too. Anyone who is new to Go or this project is welcome to make the change! Just comment here that you're going to do it.

**Comment by cudevmaxwell** [comment]
I'll try taking this on. I'll let @abiosoft know with a comment here if I can't get it done.

**Comment by alexbilbie** [comment]
Thanks :+1:
