### ISSUE TITLE
ask for email address for letsencrypt

### ISSUE THREAD

**Issue by jmhodges** [mholt/caddy#544]
One of the things that caddy makes difficult while figuring out stuff like #523 is that there's no contact email given by these users. Figuring out who's server is causing problems and how to reach them is hard.

It would be nice for caddy to support sending and nudge users towards including an email address.

**Comment by mholt** [comment]
Well, it does. When Caddy starts for the first time with a config that needs a certificate, it prompts the user with the ToS and asks for an email address. It doesn't force one, of course, but it does ask:

```plain
$ caddy
Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
Email address: _
```

After Caddy has started, the user disappears. Once an account has been created, Caddy will reuse that account unless the user specifies a different email address.
