### ISSUE TITLE
Leverage browser caching & Problem Reduce Server response time - Page Speed Insight

### ISSUE THREAD

**Issue by Fristing** [mholt/caddy#545]
Hi,
I want to modify this but the rule is a htaccess conditions. How i can do it on caddy with php or caddyfile?
Example htaccess :

```
## EXPIRES CACHING ##
<IfModule mod_expires.c>
ExpiresActive On
ExpiresByType image/jpg "access 1 year"
ExpiresByType image/jpeg "access 1 year"
ExpiresByType image/gif "access 1 year"
ExpiresByType image/png "access 1 year"
ExpiresByType text/css "access 1 month"
ExpiresByType text/html "access 1 month"
ExpiresByType application/pdf "access 1 month"
ExpiresByType text/x-javascript "access 1 month"
ExpiresByType application/x-shockwave-flash "access 1 month"
ExpiresByType image/x-icon "access 1 year"
ExpiresDefault "access 1 month"
</IfModule>
## EXPIRES CACHING ##
```

Best Regards 
Quentin Laffont

**Comment by Fristing** [comment]
Another Problem Reduce server response time !
In our test, your server responded in 0.78 seconds. There are many factors that can slow down your server response time. Please read our recommendations to learn how you can monitor and measure where your server is spending the most time.

**Comment by mholt** [comment]
Caching features aren't yet implemented; see #390, #191, #10.

As for the response time, there are a number of things that could be slowing it down. I encourage you to look at their recommendations (whatever they are).

**Comment by Fristing** [comment]
@mholt i check linked topic so we don't have any solution at this time to cache website ?

**Comment by mholt** [comment]
Not yet, but it's up for grabs if anyone wants to do it. (Will require more discussion though.)
