### ISSUE TITLE
Random error 502

### ISSUE THREAD

**Issue by Fristing** [mholt/caddy#546]
Hi,
Random time i have a 502 error in my caddy server. I don't know why, how i can resolve this error ?
Best Regards
Quentin Laffont

**Comment by abiosoft** [comment]
You will need to reveal more information.

Firstly, enable error log and share the log output.
```
errors error.log
```
Then, share part of your Caddyfile relating to the virtualhost giving that error.

**Comment by Fristing** [comment]
no problem i wait a 502 error

**Comment by lenovouser** [comment]
@Fristing 502 errors are mostly occurring if you proxy to another backend over ports and the backend isn't accessible. Mostly not a fault on caddy's side.

**Comment by Fristing** [comment]
Output : 
29/Jan/2016:12:12:09 +0100 [ERROR 502 /index.php] write tcp 91.228.167.130:27235: broken pipe
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:22 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:26 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:27 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:32 +0100 [ERROR 502 /wp-admin/async-upload.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:32 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:32 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:32 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:41 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:47 +0100 [ERROR 502 /wp-admin/async-upload.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:47 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:47 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:47 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:56 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:58 +0100 [ERROR 502 /wp-admin/async-upload.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:16:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:11 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:11 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:11 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:11 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:12 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:26 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:26 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:26 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:26 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:41 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:41 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:41 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:41 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:44 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:52 +0100 [ERROR 502 /wp-admin/async-upload.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:52 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:52 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:52 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:59 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:17:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:10 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:10 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:10 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:10 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:14 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:14 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:25 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:25 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:29 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:40 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:44 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:44 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:55 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:59 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:18:59 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:04 +0100 [ERROR 502 /wp-admin/revision.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:04 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:11 +0100 [ERROR 502 /wp-admin/revision.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:11 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:11 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:15 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:25 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:27 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:28 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:29 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:29 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:29 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:42 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:42 +0100 [ERROR 502 /wp-admin/async-upload.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:42 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:43 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:43 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:43 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:43 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:43 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:48 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:48 +0100 [ERROR 502 /wp-admin/async-upload.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:48 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:58 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:19:59 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:20:09 +0100 [ERROR 502 /wp-admin/admin-ajax.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:21:09 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:27:43 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:27:45 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:27:50 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:27:51 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:27:57 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:28:28 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:28:33 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:28:34 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:28:37 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:28:39 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:29:12 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:29:16 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:29:37 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:29:39 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:29:40 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:31:25 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:35:50 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:37:08 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:46:12 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:15:56:15 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:01:07 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:03:19 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:03:21 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:12:24 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:15:47 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:31:11 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:36:53 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:37:12 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:37:38 +0100 [ERROR 502 /webroot/index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:37:38 +0100 [ERROR 502 /webroot/index.php] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:37:45 +0100 [ERROR 502 /] dial tcp 127.0.0.1:9000: connection refused
29/Jan/2016:16:37:45 +0100 [ERROR 502 /index.php] dial tcp 127.0.0.1:9000: connection refused

**Comment by mholt** [comment]
Your backend is down, or is not listening on 127.0.0.1:9000.

**Comment by Fristing** [comment]
but i create php-cgi instance
my caddyfile :
srv.familyofgaming.fr {
  browse
  startup php-cgi -b 127.0.0.1:9000 &
  #startup service mysql start &
  header / {
      Access-Control-Allow-Origin  *
  }
  fastcgi / 127.0.0.1:9000 {
    ext   .php
    split .php
    index index.php
  }
  root /caddy/www
  tls qlaffont13@gmail.com
  log access.log
errors errors.log
  errors errors.log
  #shutdown service mysql stop &

  rewrite /vipminecraft {
    r (.*)
   to /vipminecraft/webroot/{1} /vipminecraft/webroot/index.php?{1}&{query}
  }
  gzip

}

**Comment by abiosoft** [comment]
php-cgi is not running.
Try running the command directly in the terminal and see if it works.

**Comment by mholt** [comment]
Also, you'll find using backticks (`) a nice way to format your posts, please. Much easier to read.

**Comment by Fristing** [comment]
thanks :+1:

**Comment by Fristing** [comment]
fast-cgi crash without error ! You have a solution ?

**Comment by mholt** [comment]
I'm guessing that's evident from the first log line:

```
29/Jan/2016:12:12:09 +0100 [ERROR 502 /index.php] write tcp 91.228.167.130:27235: broken pipe
```

I don't know off hand. Enable logging on php-cgi (which I'm not familiar with these days) - hopefully it will tell you what happened.

Gonna close this, but feel free to re-open if this is a bug in Caddy.

**Comment by Fristing** [comment]
Okey no problem thanks.

**Comment by Fristing** [comment]
I correct the problem with a script : 
`#!/bin/bash

log=$(date +"%d-%m-%Y %T")

case "$(pidof php-cgi | wc -w)" in

0)  log="$log - Demarrage instance PHP"
    echo "$log" >>/var/log/scriptphp.txt
    exec php-cgi -b 127.0.0.1:9000 &
    ;;
1)  # all ok
    log="$log - Instance en cours"
    echo "$log" >>/var/log/scriptphp.txt
    ;;
*)  log="$log - PHP-CGI DOUBLON"
    echo "$log" >> /var/log/scriptphp.txt

    ;;
esac`

**Comment by mholt** [comment]
Clever way to log, hopefully you can find the problem soon. Although php-cgi should not be crashing, if it's something that Caddy is doing wrong too, let me know.
