### ISSUE TITLE
using caddy as HTTPS Proxy on a specific port returns a strange response to http requests

### ISSUE THREAD

**Issue by mqus** [mholt/caddy#547]
I use caddy mainly for getting https on my gogs server, so I set up caddy like the following:

```
e.xo.to:3000 {
	proxy / localhost:3001
}
```

gogs is listening on http://localhost:3001.

If I type `https://e.xo.to:3000` correctly, everything works as it should.

The problem is, when I write `e.xo.to:3000` (forgetting the protocol prefix)in the address bar of my browser (Chromium, Linux x64), it wants to reach http://e.xo.to:3000 and downloads a strange file (just 7 bytes of binary data). If I try curl or wget the same happens, it doesn't even seem to be an HTTP response.

It would be nice if trying to reach a https port by http would redirect to the https protocol(if that's even possible) or would just send some kind of "not supported" response.
Well, you can try to download that file by yourselves, the server is online, but don't overdo it, its hosted on an arm board (just some private thingy of me)

thanks

**Comment by mholt** [comment]
The browser has to use the right protocol. If they're not speaking the same language then the server can't tell the client to redirect. With browsers, this means you need to type the scheme or somehow tell it that port 3000 is a HTTPS port.

**Comment by mqus** [comment]
Well, don't get me wrong, this is definitely some case where there's no standard behavior defined and I do have to change my setup slightly but there have to be better alternatives to the current 'http(s)' reply than doing it with some nonsense data, some examples:

```
$ curl http://paypal.com:443 -I
curl: (52) Empty reply from server
$ curl http://facebook.com:443 -I
curl: (56) Recv failure: Connection reset by peer

//just for reference:

$ curl http://e.xo.to:3000 -I

```

I just don't know if this has something to do with the golang libraries (and would be hard, if not impossible to fix) or just needs a tiny if clause somewhere.

**Comment by mholt** [comment]
The TLS handshake is handled by the Go standard library - you should search the issues on the Go project or file a bug if you feel it is one.
