### ISSUE TITLE
caddy must not assume it is the only letsencrypt client

### ISSUE THREAD

**Issue by denquixote** [mholt/caddy#549]
Any attempts to delegate challenges for certs that are not under control of caddy to other letsencrypt clients fail with 500 error, w/o any helpful error message. Any settings in the caddy file for the host names in question are ignored (e.g. "header / -Server", errors visible). 

I've tried 

* proxy / http://[::1]:402
* proxy /.well-known/acme-challenge http://[::1]:402
* root with subdirectory ".well-known/acme-challenge"
* rewrite /.well-known/acme-challenge /delegate/acme-challenge

Whenever a request has ".well-known/acme-challenge" as path prefix, caddy trips over its ego.

**Comment by mholt** [comment]
To ensure the site is always available, the Let's Encrypt handler is a special case that happens before any middleware are executed, including proxy, root, or rewrite.

> Any attempts to delegate challenges for certs that are not under control of caddy to other letsencrypt clients fail with 500 error, w/o any helpful error message.

Can you explain more what you mean by this? What are your "attempts to delegate challenges" and "clients fail with 500 error" -- which clients?

I'm not sure running more than one ACME client at a time is a good idea unless you're solving the DNS challenge exclusively.

**Comment by denquixote** [comment]
Not "clients fail", but "attemps to delegate [...] fail with 500 error."

acmetool does a selftest, i.e it tries to fetch some files from port 80, with Host header set to the requested cert host and path .well-known/acme-challenge/somefile. This request fails with code 500, response-body "\r\n". 

There are other services than http that deserve transport layer security and DNS challenges may not be feasible for various reasons. ;)

I could proxy port 80 through nginx to caddy, just to enable the letsencrypt setup that fits my use cases and procedures. But that doesn't sound like fun. 

Caddy's letsencrypt middleware could check the host header against the list of certs it is responsible for and delegate to the usual chain of middlewares/host-definitions. That's the simplest fix that comes to my mind.

**Comment by denquixote** [comment]
I could try a PR, I'd have 8 weeks until my first in-production non-www cert expires. :D

**Comment by mholt** [comment]
The main issue with this is how do you differentiate ACME requests that are intended for Caddy and ACME requests intended for the other client?

**Comment by denquixote** [comment]
1. Negatively: If there is no vhost definition with that hostname, which demands tls, then caddy is not responsible.
2. Positively: By enumerating hostnames under a config keyword like "acmehandoff". This could catch edge cases, when there are non-www services with the same hostname, but a different port that for some reason should have an independent cert. I cannot imagine a use case for this edge case, but possibly this is easier to implement than 1. 

Both would be affected by and/or depend on #209, #310?

**Comment by mholt** [comment]
> Negatively: If there is no vhost definition with that hostname, which demands tls, then caddy is not responsible.

Although non-obvious, this is not always the case. Caddy 0.8.2 (not released yet) will be able to issue certificates dynamically, on-demand, for certain configurations (e.g. an address of `:443`).

> Positively: By enumerating hostnames under a config keyword like "acmehandoff". This could catch edge cases, when there are non-www services with the same hostname, but a different port that for some reason should have an independent cert. I cannot imagine a use case for this edge case, but possibly this is easier to implement than 1.

But extra state and configuration makes me sad. :disappointed:

Don't get me wrong, I understand the frustration in your case. The DNS challenge is online now, and most ACME clients support it or will later this weekend - is that not a workable solution for you?

**Comment by denquixote** [comment]
TBH, I have some deep antipathy against "I am the world" software. Maybe Microsoft "I will happily overwrite your boot manager" Windows spoiled me at a younger age and the fact that it took me three days and reading source code in order to debug caddy's obscure and egocentric behaviour made me a little stubborn. 

DNS challenges are ... challenging in some cases. ;)

**Comment by mholt** [comment]
> DNS challenges are ... challenging in some cases. ;)

If you want software to play nicely with others then I need more information in order to help understand the problem.

**Comment by denquixote** [comment]
If I understand DNS challenge correctly, the acme client needs to be able to do some [RFC 2136](RFC 2136) DDNS updates, or equivalent actions. Not all ns zones and/or procedures allow to actually do this. 

For now I'll just do a dirty, local hack in /caddy/letsencrypt/handler.go.

**Comment by mholt** [comment]
@denquixote That RFC seems to be very seldom implemented, but most decent DNS providers have an API that allow you to set records. For example, [lego](https://github.com/xenolf/lego) (which Caddy uses under the hood) supports DigitalOcean, CloudFlare, DNSimple, and AWS out of the box, with the ability to plug in others. We've seen that it works very well. I actually prefer DNS challenge to any others since it only makes requests out, not in.

In your case, I suppose changing handler.go is a decent workaround. Good luck!

**Comment by denquixote** [comment]
Thanks! :)

Just for entertainment about the "challenging" aspect of DNS challenges: Some DNS zones are under the regime of some management systems, that do not allow DDNS. E.g. think of a zone as a plain BIND text file, manually crafted, supervised by git, a few scripts that do template voodoo, validation, whatnot and push zones to a stealth master DNS. Setups like these may not play well with DDNS. Now if you wanted to enable DDNS anyway, you could delegate a zone solely for _acme-challenge.imap.example.com. (i.e. the _acme-challenge label is its own origin), possibly delegating to a different DNS server. This is annoying, but doable. But then [some assumptions](https://github.com/xenolf/lego/blob/50031525c928047be91a62a2daaf4bd5426cc9a6/acme/dns_challenge.go#L84) about which NS to ask about the challenge RR, combined with caching effects, can make a quite volatile or broken setup. 

What I like about ACME is the diversity of methods to choose from. Now, if the clients play nice along each other, even better. :)

**Comment by MaikuMori** [comment]
I just spent couple hours trying to debug this. This is somewhat crazy. At least some meaningful error should be added. But I should be able to disable the middle-ware and proxy the challenges to another server. There are valid use-cases for this.

**Comment by slightfoot** [comment]
This got me today. I needed to generate a SANs certificate and use caddy to host the `.well-known/acme-challenge` files but even with `tls off` caddy was swallowing the requests for these files. Interesting sometimes it would allow the first request and then subsequent request would fail with 500. I was creating these files manually with the `--manual` option to `letsencrypt/certbot` binary. And I triple checked the files existed with all the right permissions.

**Comment by mholt** [comment]
Another problem is that Caddy must be able to solve the challenges for hosts it does not yet serve, for example, if you add a new host to your Caddyfile and trigger a reload, Caddy obtains a certificate for it even though it is not yet serving that hostname until after the reload completes.

**Comment by mholt** [comment]
@ghost / @denquixote / @MaikuMori @slightfoot I believe 8e75ae249524e4d39b9ff21907b227c88d1f5a21 should resolve this, allowing you to use the HTTP challenge from another ACME client on the same machine for names that Caddy is not obtaining a certificate for. When you have the chance, please pull the latest and give it a try!
