### ISSUE TITLE
Should 127.0.0.1 = localhost?

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#55]
When specifying a server address in the Caddyfile, should 127.0.0.1 be interchangeable with localhost? Right now, you'd have to specify both in the Caddyfile for the clients to be able to use both when making requests. Sometimes that's annoying.

`localhost` isn't always the only hostname to map to 127.0.0.1. I do believe that `localhost` is always 127.0.0.1 but I'm pretty sure the other way around isn't always true.

**Comment by abiosoft** [comment]
I would not totally agree to that and the reason is you can edit your hosts file and replace localhost.

What I would suggest instead is to add a condition that if a resolve of `localhost` gives `127.0.0.1` then allow it.

**Comment by j-mcnally** [comment]
I say no, while its a convetion its very much os / system specific, the only reason, 127.0.0.1 == localhost is because DNS / Posix host file says so. If someone remapped localhost for what ever reason it would return an unexpected behaviour.

I agree with @abiosoft

**Comment by j-mcnally** [comment]
In ipv6 only systems, it also is not true.... because it equals `::1`

**Comment by mholt** [comment]
Okay, sounds good to me. Both your points make sense, and I like the simplicity of not having to deal with the special case.
