### ISSUE TITLE
Import should wrap imported file in curly braces if applicable

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#550]
This was mentioned on gitter the other day. If your Caddyfile looks like this:

``` plain
import site1.conf
import site2.conf
```

Then both site1.conf and site2.conf need to use curly braces:

``` plain
site1.example.com {
    ...
}
```

``` plain
site2.example.com {
    ...
}
```

For import statements that appear at the top level of a Caddyfile, perhaps it should check if the imported file uses curly braces, and if not, it should add them internally, so that the individual conf files can stay "flat":

``` plain
site1.example.com
...
```

``` plain
site2.example.com
...
```

I'm just opening this idea as a memo to self, but I haven't decided on it entirely quite yet. I like the idea of import being a simple drop-in replacement.

**Comment by captncraig** [comment]
would it make sense to have an additional import statement for this? `import` vs `importFlat` or something like that? If you can detect that it needs curlys I would say do that, but it sounds hard.

**Comment by mholt** [comment]
It's only hard if we don't assume that the import is not well formed.

Given these files:

**Caddyfile**
```plain
import site1.conf
site2.dev {
    gzip
    browse
}
```

**site1.conf**
```plain
site1.dev

gzip
templates
```

Because the import occurs in the Caddyfile where an address should be, we can assume that the first line in the imported file is an address. Thus if that first line doesn't end with `{` then we know we have to wrap it in curly braces.

However, a malformed import would be the same Caddyfile, for example, but with this site1.conf:

```plain
gzip
templates
```

If the imported file doesn't, in fact, start with an address, it will interpret `gzip` as the address, and wrap `templates` in curly braces. This is obviously an error, but the import was poorly formed.

Any import directive inside a server block will not have the imported file wrapped in curly braces. Just the ones that appear where an address should be.

**Comment by alexandreteles** [comment]
I think that we should have only one import directive, the one that we already have, with the exactly behavior that we have today. The user should be responsible for writing the imported files using the correct syntax for where he will import it. If we start to make assumptions, we can't predict where edge cases will appear and how bad it can turn. Just leave it as it is.

**Comment by tw4452852** [comment]
At first look at this issue, I don't like this feature. As @alexandreteles says, it will lead some edge cases.

But for the possible way of implementation, I think we could drop the braces entirely. We could add braces internally, but we should check the conflict scope definition:

1. If the imported file doesn't start with address, it belongs the scope which imports it. If it is the uppermost one, it belong the default global scope.

2. If the imported file start with address, it create a new scope, but if it already belongs a scope, import failed.

For the address identification, we could simple assume the first non blank line of file is the address unless it starts with a known directive.

Despite of scope conflict, we should also check the directive duplication.

**Comment by tobya** [comment]
I agree with @alexandreteles .  I think it is easy to get into the habit of using braces

    site1.dev {
         errors errors.log
    } 

Personally I find it confusing that you can write a caddy file without braces but _only_ if you only have one host defined in the file.  I find this confusing and I think it is particuarily confusing when used in examples and code samples on the site.  Often it is not possible to copy and paste an example (some may think this is a good thing) because you need to add in braces if you have other sites defined in your caddyfile - the most likely scenario.

I think most people running sites with caddy will be configuring multiple sites with it and so in my opinion using braces should be the default use case.

I would recommend that the caddy file require braces but I assume that would break too many existing installations

**Comment by tobya** [comment]
This is made additionally confusing by the fact that this works
 
   site3.com {
     root c:\web\rootsite3
   }
    import site1.conf
    import site2.conf

but this doesnt

     import site1.conf
     import site2.conf
      site3.com {
        root c:\web\rootsite3
      }

could we just output an error when an imported caddyfile does not begin with a braced directive?

**Comment by mholt** [comment]
@tobya That is weird. Maybe we should fix that.

**Comment by mholt** [comment]
Seems like we fixed the import issue, I no longer have a problem with that. And I think I will decline my own feature request about the braces. :smile:
