### ISSUE TITLE
Error Too many certificat

### ISSUE THREAD

**Issue by Fristing** [mholt/caddy#553]
Hi,
I have a error : 
```
root@debian:/caddy# cd /caddy && ./caddy -conf="config.caddyfile"
Activating privacy features...2016/01/30 14:15:16 [bgp.familyofgaming.fr] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: familyofgaming.fr
```

How i can resolve this error ?
Best Regards
Quentin Laffont

**Comment by Fristing** [comment]
Problem solved : 5 certificates / 7 days(Let's encrypt)

**Comment by mholt** [comment]
Yeah, if you're testing or experimenting be sure to use their staging endpoint which isn't subject to the same tight rate limits: https://acme-staging.api.letsencrypt.org/directory

**Comment by faddat** [comment]
aha and so good to know.  Sorry guys but I think that this is a bug.  I just hit the same issue, and I think that Caddy's behavior needs to change to ensure that this isn't a bug.  

1) Currently, does Caddy save certificates it used in the past anywhere?  Perhaps it should.  
2) When re-launching, perhaps caddy should default to certificates used in the past until those certificates would expire, at which time it would renew them.  

It is currently super-easy to launch caddy 5 times not knowing any of this.  One could have, I suppose, set up a new nodebb, for exsample, told some folks about it, needed to make a config change, and suddenly run into the rate limit.  This may be sysadmin-ish stuff, but @mholt:  That's what you get for creating the world's best http server.....

**Comment by abiosoft** [comment]
Caddy saves certificates and reuses them. This specific scenario is common to people running it in containers or temporary environments.

**Comment by mholt** [comment]
If you're deleting the certificates from disk when you restart Caddy, then that's not a bug in Caddy.

**Comment by faddat** [comment]
I ddin't delete them, and this is not a bug.  I didn't know that caddy was saving the certificates in ~/.caddy  .  

:).
