### ISSUE TITLE
Created host... key is reachable public?!

### ISSUE THREAD

**Issue by IAMONSYS** [mholt/caddy#554]
Hi everyone,

so we've just tried out caddy. Basically 
`    cd /var/www/example.com/html && exec /usr/bin/caddy -conf "/etc/caddy/example.conf"`

Config looked like this:
```
    example.com {
        gzip
        log /var/log/caddy/example.access.log
    }
```

And it created a .caddy folder within /var/www/example.com/html which is fully being served by Caddy, exposing the key via 
`    https://example.com/.caddy/letsencrypt/sites/example.com/example.com.key`

Do we agree that for a webserver which claims to be very userfriendly ("easy to use") this should not happen under any circumstances? Where does the problem reside?

Edit:
User "caddy" has a home folder at /home/caddy/

**Comment by mholt** [comment]
I cannot replicate this behavior. What system are you running on?

Using your instructions on my Mac, I run `cd /Users/matt/Sites/example.com && exec /Users/matt/Dev/bin/caddy -conf "/etc/caddy/example.conf" -log stderr` and load https://example.com/.caddy/letsencrypt/sites/example.com/example.com.key and I get "404 Not Found".

You're running Caddy without specifying a root folder in your Caddyfile, so it will use the current working directory as a site root. Is your site being served properly?

What's the output of `exec pwd`?

**Comment by abiosoft** [comment]
I think he's starting Caddy from `$HOME` and that's very possible. Yeah we need to blacklist the directory.

**Comment by denquixote** [comment]
How do you feel about regexing out any paths that have .caddy in it? I didn't know if a URI like /../.caddy/ could do any harm.

**Comment by denquixote** [comment]
Well, after thinking about it, I do not like the regex over every fileserver request, performance-wise. Anyway, I feel this is a high priority issue.

**Comment by abiosoft** [comment]
Navigating to a relative parent folder is not possible. You can try it and let's see.

Yeah, it's a high priority issue and will be part of next release.

For now, just use rewrite to take care of that.
```
rewrite {
    if {path} has .caddy
    status 403
}
```

**Comment by IAMONSYS** [comment]
I've used Ubuntu 14.04. Changed the setup completely now (using root folder config as mentioned, and starting caddy one folder below root). $HOME was in this case /root/ as caddy was started as root-user. But even if I'd have started as user caddy, the server would have used /home/caddy/ 

Thanks for giving the attention this requires.

**Comment by mholt** [comment]
@IAMONSYS Please do the following:

```
$ cd /var/www/example.com/html && exec pwd
$ cd /var/www/example.com/html && exec echo $HOME
```

and let me know the output. Also let me know which user you are running the commands as.

@denquixote:
> How do you feel about regexing out any paths that have .caddy in it?

No.

> I didn't know if a URI like /../.caddy/ could do any harm.

It can't; Caddy uses http.Dir to strips those kinds of sequences from paths.

**Comment by IAMONSYS** [comment]
@mholt Sure thing.

```
root@example:~# cd /var/www/example.org/html && echo $HOME
/root
root@example:/var/www/example.org/html# cd /var/www/example.org/html && pwd
/var/www/example.org/html
root@example:/var/www/example.org/html# whoami
root
```

```
root@example:/var/www/example.org/html# su - caddy
caddy@example:~$ cd /var/www/example.org/html && echo $HOME
/home/caddy
caddy@example:/var/www/example.org/html$ cd /var/www/example.org/html && pwd
/var/www/example.org/html
caddy@example:/var/www/example.org/html$ whoami
caddy
```

**Comment by denquixote** [comment]
Apologies for the noise. I admit, I've "abused" this issue to dive into the inner workings of caddy. It did work for me. :)

**Comment by pwFoo** [comment]
I tested caddy inside a docker container and it feels like .caddy directory will be created inside the current directory. Would be great to configure the crtdir as caddy option?

**Comment by IAMONSYS** [comment]
Whatever it is, it may never be served by the Webserver, as it is a huge security risk (and let's admit it: Let's Encrypt probably doesn't appreciate the keys being leaked either). 

So to fix this particular issue, a filter on .caddy will probably a good fix in my opinion. If for whatever reason (... yeah even if it's a user failure...) the .caddy dir lands in the root dir of the webserver, it is not being served.

Let me know what you think.

**Comment by abiosoft** [comment]
It will be blacklisted, same way Caddyfile is blacklisted.

**Comment by mholt** [comment]
@IAMONSYS Thanks, but you didn't run `exec`...

@pwFoo:
> Would be great to configure the crtdir as caddy option?

According to [the documentation](https://caddyserver.com/docs/automatic-https) you can do this by setting the $HOME env variable.

**Comment by IAMONSYS** [comment]
As requested with exec:
```
root@example:/var/www/example.org/html# cd /var/www/example.org/html/ && exec echo $HOME
/root
root@example:/var/www/example.org/html# cd /var/www/example.org/html && exec pwd 
/var/www/example.org/html
root@example:/var/www/example.org/html# whoami
root



root@example:/var/www/example.org/html# su - caddy
caddy@example:~$ cd /var/www/example.org/html/ && exec echo $HOME
/home/caddy
caddy@example:~$ cd /var/www/example.org/html && exec pwd
/var/www/example.org/html
caddy@example:~$ whoami
caddy

```

**Comment by mholt** [comment]
From our discussion on gitter we concluded that I don't know what caused the problem but it's not reproducible, so probably a system/environment misconfiguration.

Serving the .caddy folder is like committing keys to a repository. It's not a bug, just be careful.

We may blacklist requests with "/.caddy/letsencrypt" in the URL.
