### ISSUE TITLE
Rewrite for Silex

### ISSUE THREAD

**Issue by mlalbuquerque** [mholt/caddy#555]
I have this Caddyfile for a Silex PHP Project:

```
project.local:80

root /path/to/my/project/web
gzip

log access.log
errors error.log

rewrite {
    r .*
    ext /
    to /index.php?{query}
}

fastcgi ^.* 127.0.0.1:9000 php
```
The problem is that Caddy is showing the PHP source of the **_index.php_** file - showed below - instead running it. _**index.php**_ file is in the _**web**_ directory (same as root).
```
<?php

declare(strict_types=1);

require_once __DIR__.'/../vendor/autoload.php';

$app = require __DIR__.'/../src/app.php';
require __DIR__.'/../config/prod.php';
require __DIR__.'/../src/controllers.php';
$app->run();
```

What's the problem? Little desparate already... :smile:

I'm in love with Caddy!! Test it with some static files projects that I have. The search module is beautiful!! That's why I'm a little desparate to test with my Silex projects!!

**Comment by mholt** [comment]
The fastcgi directive doesn't support regular expressions in its base path argument (most directives don't). Change it to `/`.

**Comment by mlalbuquerque** [comment]
THANKS A LOT!!

Now learning GO to help develop Caddy!!

**Comment by mholt** [comment]
Woo! We could use your help :+1:
