### ISSUE TITLE
Reusing LE certificates

### ISSUE THREAD

**Issue by sirtux** [mholt/caddy#556]
Hi, 

I have a hopefully small feature request:

I would like to reuse requested certificates and keys for other services then using http,
because caddy is already having those if it serves web pages for a particular dns name,
and even not just putting up a dummy site and getting certificates is simpler than using
any other client ;)

Therefore I would like to have configuration option to specify the posix group and the chmod
parameters used for the key and certificate storage - today the path and files are only r/w for
the caddy user, not even the group under which caddy runs.

The second thing would be some kind of hook to call an external script if caddy gets a new certificate,
so that I could notify any other application to also reload the certificate.

Thanks,
Tom

**Comment by mholt** [comment]
I think you're looking for a certificate daemon, which Caddy is not. But you can follow the progress of https://github.com/mholt/certs or https://github.com/everyday/certd for a tool that will do what you need.
