### ISSUE TITLE
Caddy proxying to an application written in Rust/Iron does not work

### ISSUE THREAD

**Issue by vegai** [mholt/caddy#559]
Not sure what the reason for all this is, but a simple proxy to an application running localhost does not seem to work with Caddy.

Here's the caddyfile:

```
https://valid_url

log access.log
proxy / localhost:8080
```

But even with the application server listening to port 8080, Caddy always responds with HTTP 502.

And here's what tcpdump has to say about it when I make an https request to that valid_url, port 443:

```
root@n1:~# tcpdump -i lo -vv port 8080
tcpdump: listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
12:49:03.605055 IP (tos 0x0, ttl 64, id 2448, offset 0, flags [DF], proto TCP (6), length 60)
    localhost.34556 > localhost.http-alt: Flags [S], cksum 0xfe30 (incorrect -> 0x75a9), seq 4210934331, win 43690, options [mss 65495,sackOK,TS val 1362859 ecr 0,nop,wscale 7], length 0
12:49:03.605063 IP (tos 0x0, ttl 64, id 48990, offset 0, flags [DF], proto TCP (6), length 40)
    localhost.http-alt > localhost.34556: Flags [R.], cksum 0x4e07 (correct), seq 0, ack 4210934332, win 0, length 0
```

So there's some activity on that port, but not quite successful. I suppose Iron (or probably hyper underneath) might be doing something funny too, but then again, if I drop nginx on caddy's place, the proxying works fine.

**Comment by mholt** [comment]
What's the working nginx config?

**Comment by mholt** [comment]
Closing unless there's anything else.
