### ISSUE TITLE
feature request: Allow templates to include (parsed) markdown

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#560]
This is a feature request to extend the templating to be able to include markdown files, parse them and get the generated html.

I.e.:
`{{.Include <file>}}` will just include a file, I am proposing something like:

`{{.Markdown <file>}}` that will parse `<file>` and include the generated html. This nicely compliments the markdown and templating.

**Comment by miekg** [comment]
Quick 'n dirty first try (not doing pr as of yet, because I don't know if I have the time to finish it :) ). Does do the fancy stuff the markdown middleware does, but a) not all of that is needed here b) didn't look to closely how that worked. Also: not tested. But something like this should be enough to implement it.

```
diff --git a/middleware/context.go b/middleware/context.go
index 5876420..f448f2c 100644
--- a/middleware/context.go
+++ b/middleware/context.go
@@ -9,6 +9,8 @@ import (
 	"strings"
 	"text/template"
 	"time"
+
+	"github.com/russross/blackfriday"
 )
 
 // This file contains the context and functions available for
@@ -49,6 +51,26 @@ func (c Context) Include(filename string) (string, error) {
 	return buf.String(), nil
 }
 
+// Markdown returns the HTML contents of the markdown contained in filename (relative to the site root).
+func (c Context) Markdown(filename string) (string, error) {
+	file, err := c.Root.Open(filename)
+	if err != nil {
+		return "", err
+	}
+	defer file.Close()
+
+	body, err := ioutil.ReadAll(file)
+	if err != nil {
+		return "", err
+	}
+	// copied from markdown/process.go
+	extns := blackfriday.EXTENSION_TABLES | blackfriday.EXTENSION_FENCED_CODE | blackfriday.EXTENSION_STRIKETHROUGH
+	renderer := blackfriday.HtmlRenderer(0, "", "")
+	markdown := blackfriday.Markdown(body, renderer, extns)
+
+	return string(markdown), nil
+}
+
 // Now returns the current timestamp in the specified format.
 func (c Context) Now(format string) string {
 	return time.Now().Format(format)
```

**Comment by miekg** [comment]
@mholt would something this simple pass review? If so, I will open a PR. Or do you want to have some directives ala the Markdown one (which throws in some complications)

**Comment by mholt** [comment]
I like simple. :smile:

But why not just use the `markdown` directive instead of the `templates` directive? You can still use all the template actions with markdown files. AFAIK it should render markdown in included files.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddy] feature request: Allow ..." ]
>I like simple. :smile:
>
>But why not just use the `markdown` directive instead of the `templates` directive? You can still use all the template actions with markdown files. AFAIK it should render markdown in included files.

technically that would work, but would invert the current setup I have right
now, and clutter the markdown files with a whole lot of html (although that can
be included as well)...

I my use case I like someone to just to edit some (small) markdown files which
can then to be included from the larger (html) template. This would also makes
it harder to screw up the entire page (although still possible).

/Miek

--
Miek Gieben

**Comment by mholt** [comment]
You can use HTML files with the markdown directive - have you tried? I'd much rather just leave things as-is if possible.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddy] feature request: Allow ..." ]
>You can use HTML files with the markdown directive - have you tried? I'd much rather just leave things as-is if possible.

No. To be clear, you mean: html with {{.Include}} that includes markdown?


--
Miek Gieben

**Comment by mholt** [comment]
Yeah, you can tell markdown to render .html files as markdown and you can use Include and all the markdown will be rendered as HTML.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddy] feature request: Allow ..." ]
>Yeah, you can tell markdown to render .html files as markdown and you can use Include and all the markdown will be rendered as HTML.

Cool, that will work. I'll update this issue with some "docs" on how I did this
and then close it.

Thanks!

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
So with:
```
    markdown / {
        ext .md .markdown .html
    }
```

then using {{.Include}} 'n friends in a test.html leads to
```
<!DOCTYPE html> {{.Include "/include/head.html"}} {{.Include "/include/nav.html"}}

  <div class="row header-image">
```
while viewing the html. This is with Caddy master from a view days ago.

**Comment by mholt** [comment]
Oh, hmm, you have to use the `template` property of the markdown directive. Save the template (with the includes) to a file and try that. Maybe I'm misunderstanding your use case a bit though. If that doesn't work for ya let me know.

**Comment by miekg** [comment]
So the template then is the same thing as the html that Im rendering...?
This is becoming more obscure by the minute : ) a simple markdown function
in the templates would solve this somewhat easier, at least for my use
case...

**Comment by miekg** [comment]
So, with this:
```
   ext .html .md
    gzip

    internal /include
    internal /md
    internal /template

    markdown {
        ext .md
        template test template/test.html
    }
```
I have a html template that get's called when I ask for `test.md`  which has:
```
+++
template = "test"
+++
```
So far, so good. Now the html template contains this directive:
`{{.Include "/md/test-list.md"}}`
Which makes that .md file to be included in the page. However that .md file is *not* converted to HTML be included as-is:
```
      Test Include

* Item1
* Item2
* ...
```
