### ISSUE TITLE
Feature request: rate limiting

### ISSUE THREAD

**Issue by sebastianbroekhoven** [mholt/caddy#562]
A nice feature to have would be a rate limit (per client)
In a test environment Caddy accepted a huge load of requests.
I't didn't crash, but it took a lot of resources of the server, witch caused other things to crash.
Is this something: https://github.com/golang/go/wiki/RateLimiting

**Comment by mholt** [comment]
Thanks for the suggestion -- but let's keep all the discussion about this in one issue so we don't lose track of it. #79.

Somebody please feel free to implement this or find a way to fund this feature if you'd like it sooner than later.
