### ISSUE TITLE
Redirect everything except `/`

### ISSUE THREAD

**Issue by klingtnet** [mholt/caddy#566]
Is it possible to redirect everything request *except* requests to `/` ?
Every path inside the `redir` directive must mach exactly, but I can't specify every single one so I need something like:

```ini
redir https://blog..name.domain/{uri} {
      except /
}
```

This is a sample config:

```ini
name.domain, www.name.domain {
    tls "admin@name.domain"
    gzip
    redir https://blog.name.domain/{uri}
    root /var/www/sites/name.domain
}

blog.name.domain {
    gzip
    log stdout
    errors stderr
    tls "admin@name.domain"
    root /var/www/sites/blog.name.domain
}
```

**Comment by abiosoft** [comment]
This is tricky because Caddy interprets `/` as wildcard path.

**Comment by captncraig** [comment]
I have had use cases for such a thing as well. I wonder if some extra syntax for "this is an exact match only" would make sense. 

`except !/`? `except /$`? `except ^/$`? Would require a bit of extension to the path matches helper, but pretty much everything should be using that as is.

**Comment by orbitaltourist** [comment]
Why not simply `except /`?

**Comment by mholt** [comment]
Thanks for your feedback! Closing this issue to funnel the discussion into #619.
