### ISSUE TITLE
Specify the location of the .caddy directory?

### ISSUE THREAD

**Issue by ianwalter** [mholt/caddy#568]
Sorry if I missed this, but is there a way to specify `.caddy`'s location?
I'm running Caddy inside of Docker so it would be a lot easier if that directory could be mounted from the host system.

**Comment by mholt** [comment]
Yes, it goes into the $HOME folder. https://caddyserver.com/docs/automatic-https

Make sure the folder is persisted even if the container disappears or you'll run into LE rate limits pretty quick.

**Comment by ianwalter** [comment]
When I try to mount /somedir/.caddy:/root/.caddy and try to start the Caddy container I get: 
```
Activating privacy features... done.
2016/02/03 03:31:28 open : no such file or directory
```
Not sure if `open : no such file or directory` is from Caddy or not but the .caddy directory does get mounted to the container. If anyone has any ideas, I'd appreciate it. Thanks!

**Comment by hubertbanas** [comment]
Does ```/somedir/.caddy``` exist on the host?
Can you please provide more info on how you run your docker container?

**Comment by ianwalter** [comment]
@hubertbanas Yup, the directory exists on the host. I'm using this image: https://github.com/ianwalter/docker-caddy and I'm running it like so: `docker run --name caddy -p 80:80 -p 443:443 -v /var/www:/var/www -v /var/data/.caddy:/root/.caddy --link influxdb quay.io/ianwalter/caddy`

**Comment by abiosoft** [comment]
Try a directory within the home directory on the host. I've had that issue before.

To clear your doubt that it is not caddy related, remove the `.caddy` mount and leave only `/var/www` and see if it works.

**Comment by ianwalter** [comment]
@abiosoft I just tried that and got the same error. I had Caddy working before I added the mount for .caddy. Also, when I tried to mount the .caddy directory I just created on the host's home directory, it **did** get populated with the letsencrypt data so it seems like the mount is working properly and it's Caddy thats having a problem reading it.
