### ISSUE TITLE
Middleware Request: Case insensitivity

### ISSUE THREAD

**Issue by jemaltz** [mholt/caddy#569]
Hi All,

It would be great to have middleware that either rewrites or redirects (preferably a configurable option?) requests to paths that otherwise match the requested URI, other than the case.

By way of example, you have a file named "filename", and a user requests "FileName".  The middleware would either rewrite the request (serving the content of "filename"), or issue a redirect from "FileName" to "filename".

This is particularly useful for users who may attract links with mixed cases, or whose content has mixed cases.  The end result is that visitors should not receive 404s for content that exists with "the wrong" case for that request.

In Apache, the rewrite functionality is exposed by way of the ["mod_speling"](https://httpd.apache.org/docs/2.2/mod/mod_speling.html) module's CheckCaseOnly directive.  (The name of the module is correct, they must have a sense of humor.)

Thanks!

**Comment by captncraig** [comment]
I wonder if caddy naturally works like this on windows as it is. 

Would this only need to apply to static files? I would assume if you are proxying it would be the upstream's responsibility to ignore case or not.

The real trick here is how to do a case insensitive file lookup on *nix systems. Best I can think of is list the containing directory and look for matches one by one. That could potentially be a bit slow.

It sounds like the base static file handler could implement it if there was a good way to do it.

**Comment by mholt** [comment]
I hate everything. :smile: Some file systems are case-sensitive and some are not. Truth is, most Internet-connected devices run some sort of Unix operating system and they typically have case-sensitive file systems. [URLs should be treated as case-sensitive](https://www.w3.org/TR/WD-html40-970708/htmlweb.html). If "a.jpg" and "A.jpg" are different files, they are different resources, and case-insensitivity breaks that.

This will not be built into Caddy core, but could be an add-on if somebody feels like they need it.

**Comment by jemaltz** [comment]
I was wondering the same re: Windows.  I would guess it does work like this, but have not tested it.

Regarding static vs. dynamic file support, that's an interesting question.  I haven't done much with Caddy and dynamic files, but if all dynamic requests are sent to FastCGI, perhaps this needs to be left to the FastCGI server.  On the other hand, if a mismatched case can prevent a request from making it to the FastCGI middleware (by issuing an error instead of passing the request along), then it's on the web server to do the heavy lifting.

For proxying, I agree that it is left to the upstream.  The only scenario that I could see this affecting the proxy functionality would be an option to lowercase all requests.

Well, this was closed while writing my response.  Oh well.

**Comment by mholt** [comment]
I think the safer thing to do would be to not mess with the case of the URL, even in path matching (even though I can see arguments both ways).

**Comment by jemaltz** [comment]
Fair enough.  I liked it as an option, not a default, and its inclusion in other web servers implies that I'm not the only one ;)

**Comment by mholt** [comment]
I know you're not the only one. One of Caddy's values/philosophies is simplifying and enforcing good practices. That includes correct URLs. Just goes with the territory...
