### ISSUE TITLE
hosting subdirectories

### ISSUE THREAD

**Issue by curiouseag** [mholt/caddy#57]
I have a question.

Is it possible to host multiple sites in subdirectories?

www.XYZ.com
www.XYZ.com/blog 
www.XYZ.com/owncloud
www.XYZ.com/.....

**Comment by abiosoft** [comment]
@curiouseag Sure you can. Are you having any issues ?

**Comment by curiouseag** [comment]
no I just did not found an example in the documentation.
I am newbie to hosting. I played with nginx and apache.
I like nginx more but I did like to use a simple web server.
Caddy looks really good. I just need examples to be able to 
understand how it works.

I am going to use nginx for now. More resources.
But I keep an eye on this one ;)

**Comment by mholt** [comment]
@curiouseag Thanks for your question - it's good to know what we can improve on. I agree that more examples are needed.

I'd like to know what you're trying to do exactly. Do you mean that all your sites have the same domain name? Can you clarify what you mean by "multiple sites in subdirectories"?

**Comment by curiouseag** [comment]
Sure. I am no native speaker. I mean multiple services.
I did like to keep my main domain free, let's say www.example.com
I want to host owncloud at www.example.com/owncloud and 
wordpress at www.example.com/blog
and so on.
I have a few services in mind. Email hosting and music streaming too.

That all sad. I am newbie to hosting. SECURE hosting.
With nginx you can configure everything wrong....
I am playing with a digital ocean droplet. Its my 7th now cause I played with and broke the others on purpose.

I just want a simple less brainer. With nginx you need to configure secure ciphers.
I think security must come by default. One problem I see with nginx is that you need to search  recent guides for an up to date configuration. Nginx is to complex to simply understand it. Even some recent guides have wrong configuration examples.

I wish for caddy to be simple and secure by default. And 1 place for the latest good configuration.

**Comment by mholt** [comment]
:+1: Totally agree. Thanks for the explanation.

I've never used owncloud, but here's an example Caddyfile that might be close to what you want:

```
# Serve a HTTPS (secure) site
https://www.example.com

tls certificate.crt server.key    # this simple line enables HTTPS and is secure by default
proxy /owncloud http://your-owncloud-url    # proxy to owncloud
fastcgi /blog 127.0.0.1:9000 php    # wordpress blog, assuming PHP is on port 9000
```

**Comment by curiouseag** [comment]
thx for the example.
I am going to try https://yunohost.org
Hope it works for me.
I will follow caddy's development. Its an awesome project.
I think you should email the developers of https://yunohost.org one day.
Would be awesome to have a simple webserver and a gui for deployment.

**Comment by mholt** [comment]
Cool, good luck - feel free to reopen this issue if you still have questions about this. (And I'll check out that web host.)
