### ISSUE TITLE
caddy sometimes just exists

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#575]
Caddy seems to spontaneous exit... Nothing in the logs, it just stops :-( Anyway to debug this?

I do add my custom middleware, so that surely good be it, but then I would expect a panic or something :)

```
Feb 04 14:08:19 x64 caddy[10216]: xx.xx.xx.xx - [04/Feb/2016:14:08:19 +0000] "GET /image-test.html HTTP/2.0" 200 1188
Feb 04 14:49:33 x64 systemd[1]: Started Caddy HTTP/2 web server.
```

**Comment by mholt** [comment]
Are you using HTTPS at all?

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddy] caddy sometimes just ex..." ]
>Are you using HTTPS at all?

Yep, with let's encrypt certs

/opt/bin/customCaddy -http2 -agree=true -email miek@miek.nl -conf=/opt/etc/Caddyfile

(http2 was a test thing)

**Comment by mholt** [comment]
See https://caddyserver.com/docs/automatic-https - Caddy will restart on occasion to renew certificates or update OCSP stapling. It gets a new process ID when this happens.

You can use the -pidfile flag to write a PID file: https://caddyserver.com/docs/cli - see that page for the flags recommended in automated environments, like with systemd. Make sure systemd follows the PID file.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [caddy] caddy sometimes just ex..." ]
>See https://caddyserver.com/docs/automatic-https - Caddy will restart on occasion to renew certificates or update OCSP stapling. It gets a new process ID when this happens.

Ah! Still there wasn't a caddy process running, but that might be systemd doing
it weird thin.

>You can use the -pidfile flag to write a PID file: https://caddyserver.com/docs/cli - see that page for the flags recommended in automated environments, like with systemd. Make sure systemd follows the PID file.

Check. Had that in the unit file, but caddy couldn't write to /var/run/caddy.
Go figure.

/Miek

--
Miek Gieben

**Comment by mholt** [comment]
And you can put the PID file anywhere you want for systemd, I think. Anyway, hope that cleared that up.
