### ISSUE TITLE
Feature-request: Auto-update Caddy

### ISSUE THREAD

**Issue by devil1591** [mholt/caddy#576]
I'd like to see an auto-update directive, in order to Caddy update itself to latest version.

Is this something you'd like too?

**Comment by captncraig** [comment]
if you are building from source you can use the git plugin:

```
git https://github.com/mholt/caddy.git /gopath/src/github.com/mholt/caddy {
  then go install
}
```

You'd still have to manually restart though.

**Comment by mholt** [comment]
We could make this an add-on, but I think it should be a command line flag rather than a directive in the Caddyfile.

Zero-downtime upgrades can be done (I think) by replacing the binary and then sending USR1. It does reload the configuration, though, so be aware of that.

**Comment by captncraig** [comment]
plugins you want installed can make this pretty complicated though.

**Comment by devil1591** [comment]
@mholt, I was thinking of auto-update on Windows, probably with a full reboot of Caddy, but yes, this would apply on Linux too maybe more smoothly. I don't really mind of a downtime of few seconds, maybe we could even configure a late hour for restart.

**Comment by faddat** [comment]
This is really interesting, and if we could somehow implement it, would be another major differentiator of "caddy vs anything else"

**Comment by jungle-boogie** [comment]
I don't want caddy to be windows 10 where things are auto updated. Even with nginx and apache, someone needs to tell their package mgmt system to fetch updates.

**Comment by devil1591** [comment]
@jungle-boogie, if you don't want it to be auto updated you won't activate the option and tadaaa!

**Comment by mholt** [comment]
The more I think about this, less more wary I am of automatic updating, and yeah, updating with the right plugins is tricky/impossible right now. If somebody wants to work on an add-on to do this, feel free, just let me know how you plan to solve the problem of figuring out which add-ons are installed. We may need to expose that list in a []string var or something.

**Comment by m13253** [comment]
Cloudflare has released a Go library named [tableflip](https://github.com/cloudflare/tableflip) which implements a method to graceful restart the server after upgrading. It also supports automatic rollback in case the new version fails to run.

I think it can be used if we want to implement zero-downtime upgrading.

Generally speaking, without automatic upgrading, many server administrators will be living with security risk, but we are really not paying enough attention to it.

**Comment by mholt** [comment]
@m13253 Caddy already has graceful upgrades and restarts. That's not the problem; it's making sure that caddy is being run in a way with permissions to replace its own binary without breaking things (i.e. in a docker container).

**Comment by RussellLuo** [comment]
@mholt Sorry for disturbing you, does Caddy v2 still supports graceful binary upgrades, which was implemented by this PR https://github.com/caddyserver/caddy/pull/1814 ? I found no upgrading logic in the latest codebase.

**Comment by mholt** [comment]
No; haven't had any requests for it yet.

**Comment by RussellLuo** [comment]
Okay, I got it. Thanks for your reply!
