### ISSUE TITLE
Missing includes in templates lead to "Internal Server Failure"

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#581]
When using `{{.Include}}` or the (new) `{{.Markdown}}`` \o/ you get a server failure whenever the file being included does not exists. This is really helpful in alerting you about this issue, but quite annoying that an entire page might not render because of one failing include.

Would it be acceptable to return `err.Error()` (i.e. `caddy: error: .... `) in this case in let that be included in the page instead of a server failure?

**Comment by mholt** [comment]
I don't think so. If an Include (or Markdown) fails, it means your site is broken. That's an error. Do you really want to be displaying a half-complete web page? Further, do you want to be exposing error details to your visitors? The answer to both is no.

Of course, you can expose error details to visitors using the `errors` directive: `errors visible` -- but this is intended only for dev purposes. You can use `errors` to log error messages and debug them, and your site visitors don't need to see that.

But after years of embarrassing broken PHP between `include()` and `require()` I just threw my hands up and decided I wasn't gonna let Caddy be subject to the same fails.

**Comment by miekg** [comment]
fair enough :)
