### ISSUE TITLE
Proxy with HTTPS

### ISSUE THREAD

**Issue by rimusz** [mholt/caddy#582]
Can I use proxy mode with HTTPS, forward it to HTTP and take advantage of Let's Encrypt?

**Comment by dlapiduz** [comment]
Yes you can!

Just set your Caddyfile to something like this:
```
:443 {
  tls "my@email.com"
  proxy / 10.0.0.0 {
    policy round_robin
  }
}
```

You just have be sure that the connection goes over a secure network after termination.

**Comment by faddat** [comment]
Here's the Caddyfile I use to do just that:


```
sharebitstalk.io {
gzip
proxy / localhost:4567
tls email=jake@klouds.org
}

www.sharebitstalk.io {
gzip
proxy / localhost:4567
tls email=jake@klouds.org
}

chat.sharebitstalk.io {
gzip
proxy / localhost:3131
tls email=jake@klouds.org
}

technologistguild.com {
gzip
proxy / localhost:4567
tls email=jake@klouds.org
}

www.technologistguild.com {
gzip
proxy / localhost:4567
tls email=jake@klouds.org
}
```

If anyone has suggestions/criticism/whatever, they'll find me quite grateful for them.  This is the one I hit the rate limit with....

**Comment by mholt** [comment]
FYI @faddat your config sets your email to `email=jake@klouds.org` not `jake@klouds.org`.

**Comment by hubertbanas** [comment]
@faddat you could probably combine ```www``` with ```non-www``` together like this:

```
sharebitstalk.io www.sharebitstalk.io technologistguild.com www.technologistguild.com {
  gzip
  proxy / localhost:4567
  tls jake@klouds.org
}

chat.sharebitstalk.io {
  gzip
  proxy / localhost:3131
  tls jake@klouds.org
}

```

**Comment by faddat** [comment]
@hubertbanas 
Thank you-- exactly the kind of awesome feedback I'd hoped I might get :)
