### ISSUE TITLE
systemd acme error: invalid email

### ISSUE THREAD

**Issue by Fahrradflucht** [mholt/caddy#585]
I try to run caddy as a service (CaaS) ( 😉) with systemd on Centos 7. I have (seemingly) the same setup working on a Fedora 23 server and I don't know whats going on.

My caddy.service file looks like this:
```
[Unit]
Description=Caddy Webserver
Documentation=https://caddyserver.com/docs
After=network.target

[Service]
User=caddy
WorkingDirectory=/srv/www
LimitNOFILE=4096
PIDFile=/var/run/caddy/caddy.pid
ExecStart=/usr/bin/caddy -agree -email="mail@mydomain.de" -pidfile="/var/run/caddy/caddy.pid"
Restart=on-failure
StartLimitInterval=600

[Install]
WantedBy=multi-user.target
```

When I try to start this service it fails with this message:
```
Feb 08 21:31:15 my.host.de caddy[13456]: Activating privacy features...2016/02/08 21:31:15 error creating client: registration error: acme: Error 500 - urn:acme:error:invalidEmail - not a valid e-mail address
```

First I had a typo in the e-mail address, but now it's correct and it still fails with the same error.

I tried running ```/usr/bin/caddy -agree -email="mail@mydomain.de" -pidfile="/var/run/caddy/caddy.pid"``` as ```caddy``` in ```/srv/www``` and it works just fine.

Any suggestions why it's failing with systemd?

**Comment by mholt** [comment]
Is there a folder in `$HOME/.caddy/letsencrypt/users`? If so, and it looks like the wrong email address, delete it and try again. Let me know!

**Comment by Fahrradflucht** [comment]
yes there is one, but only one, and it's titled with the right email address :/

**Comment by mholt** [comment]
What about in the $HOME folder according to systemd?

**Comment by Fahrradflucht** [comment]
I don't fully understand why that is the case, but you seem to be right with your guess, that the way $HOME is set in systemd causes the problem. With this caddy.service it's working:
```
[Unit]
Description=Caddy Webserver
Documentation=https://caddyserver.com/
After=network.target

[Service]
User=caddy
WorkingDirectory=/srv/www
LimitNOFILE=4096
PIDFile=/var/run/caddy/caddy.pid
ExecStart=/bin/bash -c "/usr/bin/caddy -agree -email=\"mail@mydomain.de\" -pidfile=\"/var/run/caddy/caddy.pid\""
Restart=on-failure
StartLimitInterval=600

[Install]
WantedBy=multi-user.target
```
I think thats kind of a hack, but I wasn't able to resolve the $HOME systemd is using...

Thanks for your help.

**Comment by hubertbanas** [comment]
$HOME issue may be related more to how your ```caddy``` user was created. I'm thinking ```useradd``` vs ```adduser```

**Comment by hubertbanas** [comment]
What if you remove?
```
WorkingDirectory=/srv/www
```

That should make caddy use existing
```
$HOME/.caddy
```

**Comment by mholt** [comment]
You probably have a user account in systemd's $HOME with the bad email address. If you can confirm then I can possibly work on a fix (no guarantees tho).

**Comment by Fahrradflucht** [comment]
@hubertbanas Do you mean like so:
```
[Unit]
Description=Caddy Webserver
Documentation=https://caddyserver.com/
After=network.target

[Service]
User=caddy
LimitNOFILE=4096
PIDFile=/var/run/caddy/caddy.pid
ExecStart=/usr/bin/caddy -agree -email="mail@mydomain.de" -pidfile="/var/run/caddy/caddy.pid" -conf=/srv/www/Caddyfile
Restart=no
StartLimitInterval=600

[Install]
WantedBy=multi-user.target
```
That doesn't work either...

@mholt I don't really know what do you mean be "systemd's $HOME". There is no systemd user on the system if you mean that...

**Comment by hubertbanas** [comment]
@Fahrradflucht 
Here is the one that works for me: https://github.com/mholt/caddy/wiki/Caddy-as-a-service-examples

email is in my Caddyfile like so
```
tls name@email.com
```

**Comment by Fahrradflucht** [comment]
@hubertbanas Interesting, I moved the email to the caddy file and it worked without the ```bash -c``` hack.

**Comment by hubertbanas** [comment]
Cool

**Comment by mholt** [comment]
I'm guessing Caddy created a user account with the typo'd email in the .caddy folder in $HOME as set by systemd, or if not set, then in the current working directory, and it reused that in subsequent runs.

**Comment by Fahrradflucht** [comment]
I think that's plausible, but I didn't managed to find it. Neither in caddy's $HOME directory nor in the working directory I set...

Anyway thanks for your help.

**Comment by jxsl13** [comment]
I think I found the cause of this problem, at least in my case:
After I hit my 7 day certificate limit, I switched to the staging api, everything worked fine, but one of my subdomains was not accessible, so I switched tls off using "tls no" in my Caddyfile. After trying to switch back to the production api of let's encrypt, it seems that exactly this "tls no" line in one of my subdomains caused the issue with the invalid email, whatsoever.

**Comment by francislavoie** [comment]
@jxsl13 you wanted "tls off", not "no".
