### ISSUE TITLE
Feature-request: add capabilities to ignore and hide headers in the proxy directive

### ISSUE THREAD

**Issue by alexandreteles** [mholt/caddy#586]
The Caddy proxy directive lacks better abilities to handle proxy redirects. It should, at least, implement functions to hide and ignore headers on the transaction. Looking for the Nginx ngx_http_proxy_module module, we can take two definitions:

> From http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ignore_headers:
>
> proxy_ignore_headers
> 
> Disables processing of certain response header fields from the proxied server. The following fields can be ignored: “X-Accel-Redirect”, “X-Accel-Expires”, “X-Accel-Limit-Rate” (1.1.6), “X-Accel-Buffering” (1.1.6), “X-Accel-Charset” (1.1.6), “Expires”, “Cache-Control”, “Set-Cookie” (0.8.44), and “Vary” (1.7.7).
> 
> If not disabled, processing of these header fields has the following effect:
> 
> “X-Accel-Expires”, “Expires”, “Cache-Control”, “Set-Cookie”, and “Vary” set the parameters of response caching;
> “X-Accel-Redirect” performs an internal redirect to the specified URI;
> “X-Accel-Limit-Rate” sets the rate limit for transmission of a response to a client;
> “X-Accel-Buffering” enables or disables buffering of a response;
> “X-Accel-Charset” sets the desired charset of a response.

and

> From http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_hide_header:
> 
> proxy_hide_header
> 
> By default, nginx does not pass the header fields “Date”, “Server”, “X-Pad”, and “X-Accel-...” from the response of a proxied server to a client. The proxy_hide_header directive sets additional fields that will not be passed. If, on the contrary, the passing of fields needs to be permitted, the proxy_pass_header directive can be used.

Related to #378

**Comment by mholt** [comment]
I think this can be done now with https://github.com/mholt/caddy/pull/788, no?
