### ISSUE TITLE
Feature-request:Whether the project will support ECC?

### ISSUE THREAD

**Issue by fourstring** [mholt/caddy#589]
Hello,
Thank you for the great project!It helps me with the very fast website build and without copying nginx's configuration files over and over again.
I heard that let's encrypt project will support ECC in 2016,so do you have the plan to join the support of ECC?I think it will make our sites faster.
Thank you!

**Comment by mholt** [comment]
Thanks for your feedback! Yes, Caddy will soon use ECC from Let's Encrypt.
