### ISSUE TITLE
Allow Sourcegraph browsing

### ISSUE THREAD

**Issue by idawes** [mholt/caddy#59]
Would be nice to be able to browse Caddy source using sourcegraph...

https://sourcegraph.com/github.com/mholt/caddy. (It should only take 30 seconds.)

**Comment by mholt** [comment]
Oops, I think I borked it: https://sourcegraph.com/github.com/mholt/caddy/.builds/2266962

**Comment by mholt** [comment]
Ah, there we go. https://sourcegraph.com/github.com/mholt/caddy/.builds/2267028

Thanks for the suggestion!

**Comment by idawes** [comment]
Awesome!
