### ISSUE TITLE
Feature-request: example command

### ISSUE THREAD

**Issue by humboldtux** [mholt/caddy#590]
It would be great to be able to execute something like:

    caddy --examples gogs

To read from https://github.com/caddyserver/examples and test some example conf.

Be it a core feature or an add-on, i can work on it.

**Comment by mholt** [comment]
I think part of the point of examples is so that a user can practice setting it up and actually doing it. I'm afraid that automatically doing it all for the user would kind of defeat the purpose, ya know?

**Comment by hubertbanas** [comment]
@mholt :+1:
