### ISSUE TITLE
Requests to websocket handler aren't logged

### ISSUE THREAD

**Issue by edrex** [mholt/caddy#593]
Result of websocket connection: no log line
Expected: log line

I imagine this is because github.com/gorilla/websocket is handling connections.

https://gist.github.com/61ba42e4c1cb7c82b25a - access.log is the result of running caddy and then loading root in browser

**Comment by mholt** [comment]
We knew about this in https://github.com/mholt/caddy/issues/133 but I justified it thinking that they aren't HTTP requests so we don't need to log it... but off-hand, I don't see why we shouldn't be able to log those.

**Comment by mholt** [comment]
Okay, actually, they are logged, but only once the websocket connection closes

**Comment by edrex** [comment]
I updated the test case to close the connection https://gist.github.com/edrex/fb947c6fc6460c1629b4

I was hoping for logging of websocket lifecycle events (connection opened, closed) since they are usually long-lived.

**Comment by mholt** [comment]
That'd be cool; if you know a way to do that from the log middleware, please feel free to suggest it here and then submit a PR if it's sound. What would you expect the log line to look like? (Right now we default to common log format.)

**Comment by mholt** [comment]
Also, you can customize the log format and use the `{latency}` placeholder to see how long the connection was open.

Although maybe I should rename that placeholder to `{duration}` instead.

**Comment by edrex** [comment]
Interesting.. yeah, it doesn't seem like there is any prior art for logging websocket connections using common log format. Websockets are kind of an odd duck.

I like your idea about using `{latency}`/`{duration}`.

I guess you could also do logging within the socket handler, although muxing the log lines from all the processes gets really complicated.
