### ISSUE TITLE
proxy to websocket broken with without parameter

### ISSUE THREAD

**Issue by edrex** [mholt/caddy#594]
Test setup:

https://gist.github.com/edrex/b7ccaf04b49fdf5c8b4c

Wireshark shows no traffic to the backend when a websocket request in made to a proxy handler. The proxy handler responds with `404`.

**Comment by edrex** [comment]
It works as expected with `-http2=false`. Updating title and referencing #189.

**Comment by mholt** [comment]
HTTP/2 is only used on HTTPS connections, so I find it interesting that disabling HTTP/2 makes it work, since it shouldn't matter on plaintext HTTP connections. I know HTTP/2 doesn't support protocol upgrade (sigh) but maybe it's something in the underlying lib, too. Maybe it'll be fixed or handled better in Go 1.6...

**Comment by edrex** [comment]
Related discussion in the original issue #81

**Comment by edrex** [comment]
I might not get back to this for awhile, so wanted to get my findings down.

It turns out that the HTTP/2 thing was a red herring. I didn't find any cases where it works with http but not with https/2 on the frontend. 

There are multiple issues, which I haven't fully characterized yet.

 - Proxy doesn't work with the `without` param. `proxy /echo upstream/`, where upstream has a websocket at `/echo`, works, but `proxy /echo1 upstream/echo {without: /echo1} ` param results in a 404 with no traffic to upstream. 
 - Proxy to websocket on another/same caddy instance fails with 404 (with traffic). This is either a bug in the proxy middleware being revealed by websocket middleware behavior, or the reverse.
 - I'm seeing an early-terminating websocket with a particular application (https://github.com/magne4000/quassel-webserver), but I haven't found the cause yet.

These issues obviously should be in separate tickets, but I'd like to keep this open until they're created, if that's ok.

**Comment by mholt** [comment]
Thanks for the clear instructions and test case! But I cannot reproduce this. I refreshed the index.html page a few times; here's the output:

```plain
$ go run wsecho.go
echoHandler
echoHandler
echoHandler
echoHandler
```

```plain
$ caddy
Activating privacy features... done.
localhost:2015
```

<img width="890" alt="screen shot 2016-03-05 at 4 49 14 pm" src="https://cloud.githubusercontent.com/assets/1128849/13551309/3ae48b52-e2f2-11e5-9122-0fca9b7c51f1.png">

I don't see any 404 errors.

**Comment by edrex** [comment]
Yeah, i see same. I think I had multiple overlapping causes in the initial report. The first two two issue items in my last comment should be reproducible. Will make test cases Mondayish.

**Comment by edrex** [comment]
*Note to self:* Autobahn project maintains [a standard test suite](http://autobahn.ws/testsuite/) for websocket conformance. I'd like to run the suite with both the websocket and proxy directives, and see what shakes out.

**Comment by mholt** [comment]
@edrex Any updates with this? I'll probably ask for others to help look into this as I'm unable to do so at the moment.

**Comment by edrex** [comment]
I haven't had a chance to go further. I think a good start would be to look into why `proxy` doesn't work with endpoints provided by Caddy's `websocket` directive.

**Comment by mholt** [comment]
Hmm, you know `proxy /echo1 upstream/echo {without: /echo1}` isn't a valid syntax, right? I assumed this was just a shorthand representation but that won't work in a real Caddyfile, at least not the way you expect.

**Comment by edrex** [comment]
yeah, upstream was meant to be shorthand for "http://somedomain", but it
wasn't clear

**Comment by edrex** [comment]
I made a test case for `proxy { websocket }` `=>` `websocket` and couldn't reproduce the issue I had previously reported, so it looks like it was probably an error on my part.

Test case:

https://gist.github.com/edrex/7af8da336fbd1ec6a2f9

**Comment by mholt** [comment]
Sounds good, thanks.
