### ISSUE TITLE
301 on RSS feed

### ISSUE THREAD

**Issue by bigeagle** [mholt/caddy#595]
Hi there,

I'm serving my blog using Caddy, and the URL for rss feed is `https://example.com/feed`. But before I switched to HTTPS, many subscribers were using `http://example.com/feed`. 

Using nginx I just return 301 to the https URL and everything works, but using caddy, the 301 redirection has it's content of `<a href="https://example.com/feed">Moved Permanently</a>.`, and many RSS readers (feedly, inoreader) went confused. They thought the content of the feed were `<a></a>`.

Is it possible to just return a empty-body 301 response? 

Cheers,

**Comment by mholt** [comment]
Heh, I forgot that the Go standard library does that. It's for clients that don't follow redirects so users can still go where they ought.

The comment explains why:

```go
// RFC2616 recommends that a short note "SHOULD" be included in the
// response because older user agents may not understand 301/307.
// Shouldn't send the response for POST or HEAD; that leaves GET.
```

So it satisfies a "SHOULD" in the RFC, but it's for older clients.

Still, I don't think clients should be reading the body for a 301 response code. Really surprised even a modern one like feedly is doing it wrong...

**Comment by bigeagle** [comment]
According to http://webmasters.stackexchange.com/questions/63217/301-redirecting-a-blogs-rss-feed-url , it seems like Feedly has this issue for a while

**Comment by bigeagle** [comment]
Hi, I rechecked Nginx's 301 response, the body is also non-empty. Maybe my issue is not related to go's body content. 
I'll recheck this problem later.

Thanks.
