### ISSUE TITLE
Cannot run caddy from source in Termux

### ISSUE THREAD

**Issue by oliof** [mholt/caddy#597]
Termux is an Android app providing a full Linux environment, complete with compilers and a golang runtime.

Naturally, I tried running caddy from Termux, but building fails (to my untrained eye it looks like the build expects a cross compiler, not a native one):

    $ go get github.com/mholt/caddy
    # runtime/cgo
    /data/data/com.termux/files/usr/tmp//cc7fKY9V.s: Assembler messages:
    /data/data/com.termux/files/usr/tmp//cc7fKY9V.s: Warning: end of file in comment; newline inserted
    # runtime/cgo
    /data/data/com.termux/files/usr/tmp/go-build926370973/runtime/cgo/_obj/gcc_linux_arm.o: In function `threadentry':
    ../usr/lib/go/src/runtime/cgo/gcc_linux_arm.c:56: undefined reference to `crosscall_arm1'
    collect2: error: ld returned 1 exit status
    $

**Comment by mholt** [comment]
Did you follow these instructions? https://github.com/mholt/caddy/wiki/Running-Caddy-on-Android#using-termux-root-not-required You need CGO_ENABLED=0.

**Comment by oliof** [comment]
No, I did not -- it works with CGO_ENABLED=0

Thanks!
