### ISSUE TITLE
Websocket SSL Docs - Question

### ISSUE THREAD

**Issue by dishcandanty** [mholt/caddy#599]
Can we get an example somewhere of caddy and ssl websockets? The websockets docs weren't particularly clear on this :/

Want to give caddy a shot :)

Sorry if this is the wrong place to post. Couldn't find anywhere offhand to submit questions

**Comment by mholt** [comment]
You mean like `wss://` in the client and then proxy to a websocket backend? Assuming the websocket app is listening on `localhost:1234`:

```plain
example.com

proxy /websocket_path localhost:1234 {
    websocket
}
```

Did I miss this example in the docs?

**Comment by jrudio** [comment]
I am getting hit with a 200 status code even though the end point that caddy is proxying to is suppose to upgrade the connection.

```
proxy /ws localhost:4040 {
   websocket
}
```

It's a Go server that is listening on `:4040` and has a websocket handler for `/ws`
From the client I am trying to connect via a secure websocket

Is that snippet of my caddyfile wrong? Any ideas on what I could be doing wrong?

**Comment by mholt** [comment]
Are you using HTTP/2? i.e. is this over HTTPS? If so, http2 doesn't support protocol upgrade. You'll have to disable it to use websockets (-http2=false)

**Comment by jrudio** [comment]
That solved my issue.

Thank you so much!
