### ISSUE TITLE
GitHub webhooks middleware

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#6]
Imagine: middleware that pulls the latest version of your site when you push it to GitHub... built right into your web server.

I have bigger plans for automating deployment, but would this be useful to anyone in the interim? Would anyone like to start working on it sooner than I can get around to it?

**Comment by influx6** [comment]
this would be a rad feature

**Comment by abiosoft** [comment]
I can help with this.

**Comment by r3wt** [comment]
:+1: this is an awesome idea.

**Comment by mholt** [comment]
Oooookay - this is as awesome as I hoped it would be. I'll add some docs.
