### ISSUE TITLE
Start renewal process sooner or make it configurable

### ISSUE THREAD

**Issue by scottweston** [mholt/caddy#603]
LE starts to send nagmail around 19 days remaining on a cert that hasn't been renewed and caddy doesn't start the renewal process until 14 days remaining so I'm getting renewal reminders for all my certs despite the fact that the process is now automated - this seems silly. I'd only want to see that email if caddy couldn't renew for some reason (i.e. use the emails from LE as a signal that something is wrong).

I'd like to see caddy start the renewal process before the LE nagmail trigger perhaps closer to 30 days out from expiry (or make it configurable) that way if I get the LE expiry warning email I can know I need to investigate a possible issue.

Cheers,
Scott.

**Comment by scottweston** [comment]
Nevermind, I see 30 is the new 14 in the code (should have checked the code fist ;))

**Comment by mholt** [comment]
Yeah, originally, 30 days before seemed slightly paranoid since 14 was working just fine. At the time LE had no email reminders. As you saw, though, the certificates will be renewed 30 days before starting in the next version.
