### ISSUE TITLE
Implement the equivalent of nginx proxy_redirect directive

### ISSUE THREAD

**Issue by andrioid** [mholt/caddy#606]
Hello, I'm trying to replace nginx with caddy as a proxy for an existing service.
### Problem / Use Case

The problem is that when the web-service sends the header "Location: /", I'm redirected to https://moo.example.com/ instead of https://moo.example.com/sa where the services lives.

nginx solves this with _proxy_redirect_ which I use on the existing machine as follows: `proxy_redirect / /sa/`. Then nginx will intercept the redirect and rewrite it so that the client receives the expected page.

The service is dumb, it has no idea it's being served from a sub-directory and this can't be a very rare use-case in the world of micro-services.
### Suggestion

Implement something like proxy_redirect in Caddy that rewrites any redirects sent by the remote server to the client.

I even found an (unfinished) [PR](https://github.com/mholt/caddy/pull/442) on the subject, but I didn't want to re-open without being sure. 
### Config:

```
moo.example.com {
        root /var/www/example.com
        proxy /sa cow.example.com:8097 {
                without /sa
                proxy_header Host {host}
        }
}
```

**Comment by captncraig** [comment]
Could this be accomplished with multiple dummy server blocks perhaps?

```
moo.example.com {
     proxy /sa localhost:7777 {
      ...
     }
}

localhost:7777 {
   rewrite #not sure exactly what this looks like, but it removes the /sa
   proxy / cow.example.com:8097
}
```

I do like your way better, but I would be interested to see if it is possible by composing existing components.

**Comment by andrioid** [comment]
It might work, if you send `proxy_header Host moo.example.com` from the localhost one. Otherwise the redirect will probably hit client's localhost.

I'm at work now, but I can try your suggestion tonight.

I still see this as a possible work-around, instead of a solution. There are countless use-cases where tiny services are bundled under one hostname.

**Comment by mholt** [comment]
Did that workaround work? (just curious)

Why does the service return `Location: /`? You say it doesn't know it's being served in a subdirectory, but doesn't it see the request URL as being to `/sa`?

**Comment by andrioid** [comment]
No, the work-around doesn't work for me. The service still redirects to "/login" instead of "/sa/login".

It's a dumb service, I'll give you that. But I've used this nginx directive on number of occasions, professionally and privately. Seems like a normal thing, to be able to intercept redirects for a proxied service.

**Comment by mholt** [comment]
I don't like the idea of bending to backwards backends that make things complicated, since part of the point of Caddy is to push cleaner architecture / app design, but I guess if we want it to be adopted we need to support certain features.

Nothing I wouldn't mind removing for a potential 2.0 version someday anyway.

**Comment by mholt** [comment]
Unfortunately the proxy_redirect PR is now closed due to inactivity, but if this feature is wanted enough, somebody feel free to pick it up and finish it. :+1:

**Comment by slightfoot** [comment]
I might take a stab at this one. Since I needed similar functionality myself recently.

**Comment by slightfoot** [comment]
Reference:
> [Related Nginx documentation](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect)

**Comment by mholt** [comment]
This should be possible now with #2144.
