### ISSUE TITLE
pprof integration

### ISSUE THREAD

**Issue by captncraig** [mholt/caddy#610]
https://golang.org/pkg/net/http/pprof/ is really useful for profiling and determining performance and memory bottlenecks.

The default behaviour is that it registers  handlers with net/http's default serve mux on init. That probably won't work since I doubt we ever use that.

That package also has basic handlers you can hook. A simple directive to add those routes would be pretty trivial. https://golang.org/src/net/http/pprof/pprof.go#L67 is the only code the directive would really need. Is this worth making a plugin for, or should it just be a simple built-in one?

**Comment by jaredfolkins** [comment]
As someone who has done a lot of golang profiling, I'd suggest simply wrapping the following package.

https://godoc.org/github.com/pkg/profile

You can then use the created file (cpu.pprof in the example below) to extrapolate information from and you will not have to spin up an internal web server with its overhead or potential conflicts.

```go tool pprof -pdf cpu.pprof > caddy_cpu.pdf```

FYI - I used it primarily when Dave was the maintainer.

https://github.com/davecheney/profile

**Comment by captncraig** [comment]
The thing I like about http mode is that I can attach to a running server and profile it without starting and stopping it. That lets me observe it in a realistic workload. In caddy we are already spinning up webservers, so it really isn't much overhead to using the listeners. 

I wouldn't expect very many people to use this, but it is nice to have as an option.
