### ISSUE TITLE
PHP-FPM

### ISSUE THREAD

**Issue by jacobmischka** [mholt/caddy#611]
I see that there are several closed issues involving php-fpm, but none of them have helped me. 

I believe I have php-fpm configured and running correctly, but I keep getting `[ERROR 404 /] Primary script unknown` errors when trying to access any PHP files. The user running caddy is a member of the group `http`, which is the owner and group configured for php-fpm in Arch. 

Caddyfile: 
```
localhost:8080
errors error.log
fastcgi / 127.0.0.1:9000 php
```

PHP-FPM configs: https://gist.github.com/jacobmischka/30d328f4e58717cda1db

```
$ ps aux | grep php-fpm
root      3260  0.0  0.1 266528 30128 ?        Ss   11:14   0:00 php-fpm: master process (/etc/php/php-fpm.conf)
http      3262  0.0  0.0 266528  8192 ?        S    11:14   0:00 php-fpm: pool www
http      3263  0.0  0.0 266660 11264 ?        S    11:14   0:00 php-fpm: pool www
mischka   3474  0.0  0.0  10728  2304 pts/1    S+   11:18   0:00 grep php-fpm
```

```
$ netstat -an | grep :9000
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN
```

**Comment by abiosoft** [comment]
Add `root` to your Caddyfile. Caddy may be started from the wrong directory.
```
root /path/to/php/source/files.
```

**Comment by jacobmischka** [comment]
I'm running caddy from the directory that the php files are in, but I've added root, still doesn't seem to work.

Caddyfile:
```
localhost:8080
errors error.log
root /home/mischka/Downloads/dokuwiki
fastcgi / 127.0.0.1:9000 php
```

/home/mischka/Downloads/dokuwiki/test.php:
```php
<?php
	phpinfo();
```

![image](https://cloud.githubusercontent.com/assets/3939997/13118566/730c21ba-d56a-11e5-97a6-0133771e3080.png)

**Comment by abiosoft** [comment]
What about the permissions of the files. Are they readable by php-fpm and what do you have in error log ?

**Comment by jacobmischka** [comment]
They should be readable, yes. I'm particularly confused as to why it's throwing a 404 error and not a 500 level one. Non-PHP files are showing up fine. I've never used php-fpm before, so I may well be doing something wrong, but I believe the configuration is correct. If you could take a look at them to confirm that that would be great. 

```
-rw-r--r--  1 mischka http       18 Feb 17 11:31 test.php
```

error.log:
```
17/Feb/2016:13:15:28 -0600 [ERROR 404 /] Primary script unknown
17/Feb/2016:13:15:32 -0600 [ERROR 404 /test.php] Primary script unknown
```

**Comment by abiosoft** [comment]
This is strange. Seeing this the first time. 

What platform are you on ?

**Comment by jacobmischka** [comment]
Arch Linux x64, kernel 4.4.1-2-ARCH.
`php 7.0.3-1`, `php-fpm 7.0.3-1`, `caddy 0.8.1-1`

**Comment by mholt** [comment]
Did you see https://github.com/mholt/caddy/wiki/Troubleshooting-PHP-FPM-and-FastCGI? Any of those tips help?

**Comment by jacobmischka** [comment]
I did, and I believe I've been through them all. I've tried both a unix socket and a TCP port for php-fpm's listener. My error message doesn't match any of those examples and I can't see anything in php-fpm's configs that's wrong

**Comment by abiosoft** [comment]
If you don't mind. You can mail me temporary ssh details to the server and let me help with troubleshooting.

I have not been able to reproduce it in my own environments.

**Comment by humboldtux** [comment]
Can you do the following commands just to be sure that the `http` user can go through all directoris of the Root Dir:

```
ls -ld /home/mischka/Downloads/dokuwiki
ls -ld /home/mischka/Downloads/
ls -ld /home/mischka/
ls -ld /home/
```

**Comment by jacobmischka** [comment]
@abiosoft Unfortunately I can't, it's my development computer on my employer's network, it doesn't allow incoming connections. 

I'll try setting it up on my personal computer tonight or tomorrow and if I run into the same problem I'll send you ssh info. Thanks for trying, I must have done something wrong but I can't figure out what it is.

**Comment by jacobmischka** [comment]
Okay well, turns out Downloads wasn't readable, but I've moved it out and it's still giving me the same error. https://gist.github.com/jacobmischka/dc75426d172f37c82d10

I moved it to the regular http server location but I'm still getting the same thing. https://gist.github.com/jacobmischka/43a58335f7fd80df3532

```
23/Feb/2016:08:50:08 -0600 [ERROR 404 /test.php] Primary script unknown
23/Feb/2016:08:54:49 -0600 [ERROR 404 /test.php] Primary script unknown
23/Feb/2016:08:55:24 -0600 [ERROR 404 /test.php] Primary script unknown
23/Feb/2016:08:55:31 -0600 [ERROR 404 /test.php] Primary script unknown
23/Feb/2016:08:58:21 -0600 [ERROR 404 /test.php] Primary script unknown
```

**Comment by mholt** [comment]
[This page](http://serverfault.com/questions/517190/nginx-1-fastcgi-sent-in-stderr-primary-script-unknown) says it's due to a wrongly set "SCRIPT_FILENAME" variable. It should be whatever the absolute path to that test.php file is. @jacobmischka We're still having trouble reproducing this, do you have Go installed?

**Comment by jacobmischka** [comment]
I do yes

**Comment by mholt** [comment]
@jacobmischka Cool, it'd be helpful if we could see the value of the vars like SCRIPT_FILENAME ([this whole env map](https://github.com/mholt/caddy/blob/4f5fe2de24d965530b03bee5edc01a640c002ce8/middleware/fastcgi/fastcgi.go#L67) would be good) -- I think that'd be a good start.

**Comment by jacobmischka** [comment]
Well, I haven't looked at this since my last comment, but it's actually working now. Either I needed to reboot after installing php-fpm and I hadn't done that, or I'm an idiot and I forgot to edit the `root` path after moving it out of the non-readable Downloads folder.
 
![image](https://cloud.githubusercontent.com/assets/3939997/13828896/05bdc030-eb92-11e5-8273-ff9752ae09a8.png)

I am very sorry for all of the confusion. Thank you all for your help.

**Comment by mholt** [comment]
Oh, great to hear :+1:

**Comment by terah** [comment]
Just to help some else out:

I had the exact same error and fixed it by changing the user/group in /usr/local/etc/php/7.0/php-fpm.d/www.conf to my own user and group.  I then restarted php-fpm with 
```
sudo brew services stop php-fpm.
brew services start php-fpm
```

Here is my Caddyfile:
```
# Your site's address 
# The http:// part makes caddy listen on port 80
# You need sudo to start caddy on port 80
http://testsite.local   
# Disable https
# The bootup letsencrypt stuff doesn't like .local domain suffix
tls off
ext .html   # Clean URLs
errors {
    log ../errors.log    # Error log
    404 error-404.html   # Custom error page
}
# php-fpm is configured on 9001 so as to not collide with xdebug which defaults on 9000
fastcgi / localhost:9001 php {
    ext 	.php
    split	.php
    index	index.php
}
# Rewrite rules to work with slim framework and alike
rewrite {
    r .*
    ext /
    to /index.php?{query}
}
```

I run it from within my public directory with sudo caddy --conf=../Caddyfile

**Comment by mholt** [comment]
Note that you don't need `tls off` if you specify `http://` in the address of the site. ;)

**Comment by kenfdev** [comment]
Just in case somebody cannot solve the `Primary script unknown` problem with the above solutions.  Be sure `SELinux` is disabled.  That fixed it in my case.
