### ISSUE TITLE
Feature-request: Limit maximum connection to backend (just like NginX's max_conns)

### ISSUE THREAD

**Issue by kokizzu** [mholt/caddy#613]
There's a need to limit maximum number of connection to prevent DoS/DDoS to slow upstream.

http://nginx.org/en/docs/stream/ngx_stream_upstream_module.html

**Comment by mholt** [comment]
This would be a good thing to do. Not too hard, either, since the number of active connections are already tracked: https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/proxy/proxy.go#L110

All we'd have to do is modify upstreamHost's [Select() method](https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/proxy/upstream.go#L219) to account for number of active connections. If all backends are "full" then we don't return any of them.

Any takers?

**Comment by gunjan5** [comment]
I will give it a shot after work today

**Comment by jupiter** [comment]
How much does it matter whether max_conns is per server or per pool? 

If it is per server, it seems we need to do the check in the various [policy Select() methods](https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/proxy/policy.go#L54), as well as in [upstreamHost's Select() method](https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/proxy/upstream.go#L219) - basically, everywhere `Down()` is called. We could therefore refactor `Down()` to `Available()` and simply add the check in [one place](https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/proxy/upstream.go#L81). @mholt what do you think?

**Comment by mholt** [comment]
@jupiter Thanks for heading this up! I'd rather just add the check in one place for simplicity. I think Available() is a good name, too, but the logic will have to be reversed, since Available means the opposite of Down.

**Comment by mholt** [comment]
#664 just landed - thanks!

**Comment by b4stien** [comment]
Hi there! Sorry to revive an old issue, this thread is well referenced on the net on the topic of "how to limit concurrent connections to an upstream host", but the discussion, solution and code linked is not applicable recent Caddy versions (I suspect it changed with Caddy 2). `max_conns` does not seem to be a valid directive anymore, there is `max_conns_per_host` but it does not seem scoped to a specific upstream server.

Can you point future readers to the right direction?

**Comment by francislavoie** [comment]
@b4stien please open a new issue, this one is over 8 years old and not relevant at all anymore.
