### ISSUE TITLE
caddy + letsencrypt fails to start when letsencrypt is down

### ISSUE THREAD

**Issue by niv** [mholt/caddy#617]
Just like now, le is in maintenance mode and the directory returns invalid data.

Activating privacy features...2016/02/19 18:06:03 error creating client: get directory at 'https://acme-v01.api.letsencrypt.org/directory': invalid character '<' looking for beginning of value

The surprise of the server not coming up and having to edit your config to manually point at the existing certificates isn't the first thing one needs in life. :)

caddy should simply reuse the existing certificates when LE is unresponsive and start up regardless.

**Comment by mholt** [comment]
Thanks for the report. Fixed for the next release.

**Comment by niv** [comment]
Nice, tyvm.
