### ISSUE TITLE
DNS name does not have enough labels (probably Let's Encrypt)

### ISSUE THREAD

**Issue by nubunto** [mholt/caddy#618]
Hi!

I am serving a web site, and I decided to use Caddy.
So, I want that for static files, Caddy serves them. For my route, that handles email sending logic, I want a proxy!

It looks like this:

    http://localhost:80 {
        gzip
        root /www/
        log /www/log/access.log
    }
    proxy /foo http://localhost:8080

Pretty neat. I was feeling quite clever. But then I got this:

`2016/02/20 00:41:53 [proxy] failed to get certificate: acme: Error 400 - urn:acme:error:malformed - Error creating new authz :: DNS name does not have enough labels`

I'm pretty sure that's Let's Encrypt complaining about something, but I couldn't figure out after 5 rounds of Googling. Please halp.

Thanks!
PS: It works if I remove the `proxy` part, though.

**Comment by mholt** [comment]
Yeah, you can't put `proxy` outside of a server block. Caddy thinks `proxy` is an address you want to serve.

**Comment by nubunto** [comment]
Duh. Of course. That makes sense.
And it worked!
Thanks!

**Comment by louwers** [comment]
It would be useful if this was in the documentation.
