### ISSUE TITLE
Middleware for set Remote Address to Real one

### ISSUE THREAD

**Issue by sijad** [mholt/caddy#621]
inspired by [Nginx Module Realip](http://nginx.org/en/docs/http/ngx_http_realip_module.html)
Real IP Middleware sets the *Remote Address* from a specific header. it's useful if you're behind a proxy or CDN
in chain (Caddy directives/extensions) it should be after *shutdown* (before log), because *log* uses [replacer](https://github.com/mholt/caddy/blob/master/middleware/replacer.go#L50) to set `{remote}` in logs
please let me know if you think it has the quality to be registered in to registry.go

**Comment by mholt** [comment]
Oh, like this! https://github.com/captncraig/caddy-realip

I think it's on its way to becoming a registered add-on.

**Comment by sijad** [comment]
Exactly what was in mind :smile:

**Comment by mholt** [comment]
Cool. Hey @captncraig - let's work on getting that added to the registry this week.
