### ISSUE TITLE
Any interest in minifiers?

### ISSUE THREAD

**Issue by cathalgarvey** [mholt/caddy#622]
I was browsing [@tdewolff's minify](https://github.com/tdewolff/minify) and thought "this would be pretty cool on Caddy". :)

If there are docs on how to write extensions/plugins I could investigate contributing, if I find time. Is anyone else playing with this idea, though? A caching minifier middleware for caddy would be a really nice feature, especially for highly cacheable sites like static blogs?

**Comment by mholt** [comment]
I'd like to see something like this as well as a SASS/SCSS preprocessor built in, so developers wouldn't have to add yet another external tool to their workflow.

Anyway, I haven't heard of any work on a JIT minifier, but that would be pretty greatni think. First see if you can get it working without caching. There are plans for a caching middlewares that should take care of that for you. (But still looking for someone to contribute that.)

Check out the wiki on this repo for instructions on extending Caddy.

**Comment by jacobhands** [comment]
This would be awesome! I have a blog that uses [Hugo](https://gohugo.io) and the output is pretty bloated. A built in minifier would be really helpful!

**Comment by sijad** [comment]
how about implementing some features of [pagespeed](https://github.com/pagespeed/mod_pagespeed):
> * Image optimization, compression, and resizing
> * CSS & JavaScript concatenation, minification, and inlining
> * Cache extension, domain sharding, and domain rewriting
> * Deferred loading of JavaScript and image resources
> * and many others...

**Comment by DenBeke** [comment]
> I'd like to see something like this as well as a SASS/SCSS preprocessor built in, so developers wouldn't have to add yet another external tool to their workflow.

Wouldn't that be out of Caddy's scope? Because when using Sass, one often has other Sass dependencies (think of stuff like Bourbon).

**Comment by captncraig** [comment]
The other problem is most of the tools in that realm are in node or some
other non-go language. If not in pure go, then there are still dependencies
you have to install to make it work. I like the idea though. Even if I have
to install stuff, an on the fly translator with a cache could be pretty
cool.

Generally I'd recommend using the standard tools for dev and serving the
final artifacts on your actual server though.

**Comment by mholt** [comment]
@DenBeke 

> Wouldn't that be out of Caddy's scope? Because when using Sass, one often has other Sass dependencies (think of stuff like Bourbon).

Yeah, you're right. Maybe it's out of the scope of Caddy core, but not out of the scope for add-ons; that's the point of add-ons (plugins, whatever) -- is to extend the functionality of your web server to fit your workflow/situation better.

@captncraig 

> The other problem is most of the tools in that realm are in node or some
other non-go language. If not in pure go, then there are still dependencies
you have to install to make it work.

Very good point -- the minifier should be pure Go. We do have the git addon which does depend on having git installed, for example, but that's not *too* unreasonable and it's a totally separate command, not a C binding -- C bindings are a no-no, but if there is absolutely no pure Go alternative, add-ons can probably get away with requiring an external program to be installed.

**Comment by DenBeke** [comment]
> Yeah, you're right. Maybe it's out of the scope of Caddy core, but not out of the scope for add-ons; that's the point of add-ons (plugins, whatever) -- is to extend the functionality of your web server to fit your workflow/situation better.

Yes, you're right!

**Comment by cathalgarvey** [comment]
@mholt @captncraig Well I suggested minifiers and sass on the basis that both features have pure-Go implementations. :)

There's [c6 for sass](/c9s/c6), and the [aforementioned minifiers](/tdewolff/minify) are pure Go, also.

I did imagine these as addons, probably third party. I'm wondering where one should start out when making addons for caddy, it might make for a fun project!

**Comment by mholt** [comment]
@cathalgarvey It will indeed! Here's a step-by-step guide to put together a plugin for Caddy: https://github.com/mholt/caddy/wiki/Extending-Caddy

**Comment by cathalgarvey** [comment]
Thank you!

On 2 April 2016 02:03:02 IST, Matt Holt <notifications@github.com> wrote:
>@cathalgarvey It will indeed! Here's a step-by-step guide to put
>together a plugin for Caddy:
>https://github.com/mholt/caddy/wiki/Extending-Caddy
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mholt/caddy/issues/622#issuecomment-204620479

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by juliuse** [comment]
Doing optimizations on static files at runtime (webserver) is probably better than no optimization at all (maybe the reason behind mod_pagespeed), but still would be a poor practice when the proper way to do it should be at build time (same with any preprocessing).

**Comment by mholt** [comment]
@cathalgarvey - and everyone else in this issue - thanks for your comments! I'm going to close this since there's not much actionable development discussion happening in this issue, but I have linked to this issue from [a thread in our community forum](https://forum.caddyserver.com/t/requested-plugins-ideas-for-developers/127) where we are aggregating ideas/requests for Caddy plugins.

If you want to continue discussing the plugin before development begins on it, feel free to start a new topic on the forum. :+1: Hope to see you participate with us there!

**Comment by mholt** [comment]
This has been implemented by @hacdias and will be available for 0.9 soon. https://github.com/hacdias/caddy-minify

**Comment by cathalgarvey** [comment]
Awesome!

On 9 June 2016 16:46:41 IST, Matt Holt <notifications@github.com> wrote:
>This has been implemented by @hacdias and will be available for 0.9
>soon. https://github.com/hacdias/caddy-minify
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mholt/caddy/issues/622#issuecomment-224937461

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
