### ISSUE TITLE
Template Action to List .md Pages in Document Root

### ISSUE THREAD

**Issue by rafecolton** [mholt/caddy#625]
It would be handy to have a template action that would list all markdown pages in the document root for the purpose of automatic menu generation.  I could see a basic version looking something like this:

``` html
<ul class="nav navbar-nav">
{{range .Pages}}
  <li><a href="/{{.StripExt . }}">{{.StripExt . | basename }}</a></li>
{{end}}
</ul>
```

A nice addition would be a way to turn subdirectories into dropdown menus

**Comment by mholt** [comment]
Markdown can kind of already do this, although it's not limited to the root directory.

Hmm. We may be changing the scope of the markdown middleware in the future. It sounds like you want something more like a static site generator, like [hugo](https://caddyserver.com/docs/hugo).

As the hugo plugin matures, we may strip markdown's static site generation features out and just recommend the hugo plugin for that stuff, since it does it so much better and is so much more powerful.

**Comment by sijad** [comment]
how about implementing some features of [pagespeed](https://github.com/pagespeed/mod_pagespeed):
> * Image optimization, compression, and resizing
> * CSS & JavaScript concatenation, minification, and inlining
> * Cache extension, domain sharding, and domain rewriting
> * Deferred loading of JavaScript and image resources
> * and many others...

**Comment by matthewp** [comment]
@mholt I would really be sad if you stripped features from the markdown plugin. I do not want a full static site generator.  I really like the markdown plugin because it makes it easy to build simple sites with links (almost like old Gopher pages).

**Comment by wmark** [comment]
This can be achieved iterating over {{. Dirent}} with @weingart's new stab at Markdown →#762.
[1] https://github.com/mholt/caddy/pull/762/files#diff-7d73b0f149a5e56cccc920f33289de9bR36

[2] https://github.com/mholt/caddy/pull/762#issuecomment-211072496

**Comment by mholt** [comment]
If performance isn't a concern, I think we can keep some of the more basic/useful functionality in markdown, but no static site generation.

One thing that would be nice is a good way to get decent summaries of all the documents that get iterated, and then to be able to paginate the iterations somehow.

**Comment by mholt** [comment]
There is now a `{{.Files "sub/directory"}}` template action that returns a list of all the files in that directory; it might do what you need!
