### ISSUE TITLE
Fastcgi: Content-Length is not set

### ISSUE THREAD

**Issue by humboldtux** [mholt/caddy#626]
Content-Length is not sent in Fastcgi response header.

A sample request to a Wordpress site, Content-Length not set, and Transfer-Encoding always chunked:

```
$ curl -s -D - http://192.168.0.11:8080 -o /dev/null
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Link: <http://192.168.0.11:8080/wp-json/>; rel="https://api.w.org/"
Server: Caddy
Date: Sat, 20 Feb 2016 11:21:57 GMT
Transfer-Encoding: chunked
```

Here https://github.com/mholt/caddy/blob/master/middleware/fastcgi/fastcgi.go#L80, there is always no Content-Length entry in r.Header. And even by forcing contentLength variable to a value doesn't do anything. 

I'm tried to fix this to fix #567 #614, any help is welcome.

**Comment by mholt** [comment]
That's the request's content-length.

Hm, this is strange, though. The response's content-length is set to the value of the header as it comes out of the backend: https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/fastcgi/fcgiclient.go#L453 - this should set it in the response later when fastcgi.go calls writeHeader().

Can somebody with a PHP or just plain ol' fastcgi backend take a look at this? Maybe @abiosoft if you have a chance... :smile:

**Comment by humboldtux** [comment]
Sorry for the confusion Response / request.

Here are the tests:

```
$ curl -s -D - http://192.168.0.11:8080
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Sat, 20 Feb 2016 12:01:32 GMT
Server: Caddy
Status: 200 OK
Content-Length: 63

<h1>Hello, 世界</h1>
<p>Behold my Go web app via FastCGI!</p>
```

```
$ ./fcgisserver 
User-Agent = [curl/7.38.0]
Accept = [*/*]
```

**Comment by mholt** [comment]
So it looks like the Go fastcgi backend is setting Content-Length. Could it be that the PHP app is misbehaving and not setting that header?

**Comment by humboldtux** [comment]
This is possible. I tested with a wordpress site.

**Comment by mholt** [comment]
Just had an idea. Try this. In [fastcgi.go:144](https://github.com/mholt/caddy/blob/c12847e5ba4341f0f8f3e51bcbc362d14254775f/middleware/fastcgi/fastcgi.go#L114), we copy the response body to the HTTP response. We ignore the first return value which is the number of bytes written. Maybe we should use that to set Content-Length if not already set.

Does that solve the problem?

**Comment by abiosoft** [comment]
I think @mholt's suggestion should fix it.

**Comment by humboldtux** [comment]
I tried this with no luck:

```
115       length, err := io.Copy(w, resp.Body)                                                                                                                                                                     
116       if err != nil {                                                                                                                                                                                          
117         return http.StatusBadGateway, err                                                                                                                                                                      
118       }                                                                                                                                                                                                        
119                                                                                                                                                                                                                
120       w.Header().Set("Content-Length", strconv.Itoa(int(length)))                                                                                                                                              
```

Did i missed something?

**Comment by mholt** [comment]
Oh, phooey. There's a `writeHeader()` call just before the copy, which writes the headers, so we need to set all the headers before that.

Perhaps we should just bite the bullet and read into a buffer (from which we can get the length), write all the headers, then write the final response from the buffer.
