### ISSUE TITLE
Support HTTP/2 proxy backends

### ISSUE THREAD

**Issue by bluecmd** [mholt/caddy#631]
Look at nghttpx for inspiration.

If Caddy supported HTTP/2 backends for reverse proxying you could use it to route GRPC connections to the relevant servers. GRPC has the opposite (route non-GRPC requests to a webserver) using cmux I think, might be worth looking into.

**Comment by mholt** [comment]
With Go 1.6, this should be the case, since http2 is enabled by default for clients. The next release of Caddy, slated to come out this week, will be built on Go 1.6.
