### ISSUE TITLE
Documentation request: multiple fastcgi directives

### ISSUE THREAD

**Issue by jung-kurt** [mholt/caddy#633]
I successfully use multiple **fastcgi** directives and a single **root** directive within a server block in a Caddyfile. For example
```
https://foo.example.org {
  # Static files
  root /var/www
  # Bar service
  fastcgi /bar /tmp/bar.sock 
  # Baz service
  fastcgi /baz /tmp/baz.sock
  tls foo@example.org
}
```
However, I haven't found any documentation that supports this usage and consequently don't know if this behavior will continue to be supported. A statement that addresses this in the documentation for the **fastcgi** and other applicable directives would be welcome.

The closest the current documentation gets as far as I can see is the line 

> Some directives accept an argument that specifies a base path to match. 

Perhaps this could be elaborated to identify which directives apply and whether multiple occurrences are supported.

**Comment by mholt** [comment]
Good point. I will add

> This directive may be used multiple times for different request paths.

to the documentation for [fastcgi](https://caddyserver.com/docs/fastcgi). Thanks for the feedback!

**Comment by jung-kurt** [comment]
Thanks!
