### ISSUE TITLE
templating is not applied to error pages

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#634]
If have `templates /` in the Caddyfile, I was expecting this templating to also extend to custom error pages (i.e. `errors 404 404.html`), but it doesn't.

Bug or feature? :-)

**Comment by mholt** [comment]
Error pages don't support templates. Mainly because I never thought about it, but also it introduces another way for something to go wrong (during error handling, which is bad).

Also, middlewares can't really talk to each other, so there's no good way for errors to know that templates is enabled.

**Comment by miekg** [comment]
Understood, but coming from Apache, this is not 100% obvious. just mentioning this in the docs might make sense.

**Comment by mholt** [comment]
Good idea, I'll make a note in the docs. Maybe someday we'll allow templates in error pages. It isn't hard to do, it just has nothing to do with the `templates` directive. How important is this to you?

**Comment by miekg** [comment]
Not *that* important. Nice to have really. A work around (for a custom 404) is to make a 404-tmpl.html page, render that, save the contents and make that the official 404.

**Comment by mholt** [comment]
Okay. I'm going to close this for now but mark it as deferred since we may be able to do this later, if there's demand for it.

**Comment by mholt** [comment]
This is possible in Caddy 2.
