### ISSUE TITLE
Make it possible to remove headers

### ISSUE THREAD

**Issue by stanislavromanov** [mholt/caddy#64]
Right now you can only add and overwrite headers using `header / Key Value`.

What if I want to remove a header? Can we add something that will remove header e.g. `-header / Server` so I can remove headers that are being sent by server or application?

Line in question would probably be: https://github.com/mholt/caddy/blob/master/middleware/headers/headers.go#L25

Function in question would probably be: http://golang.org/pkg/net/http/#Header.Del

I could do it myself but I have no experience in Go and would probably not write it very pretty.

**Comment by mholt** [comment]
I agree we need this feature. We can't change the directive name (well, we could allow "-header" but I'm not fond of changing the parser for that) - so what about something like `header -Server` or `header Server -`? (The first won't allow us to set header fields starting with `-` and the second won't allow us to set header fields with a value of `-`.) - do you have a preference either way?

**Comment by abiosoft** [comment]
I'll go with `header -Server`

**Comment by stanislavromanov** [comment]
`header -{key}` sounds perfect to me.

**Comment by cbess** [comment]
As another option, what about using `~Server`? The ~ seems to be used to negate (bitwise operations).

**Comment by stanislavromanov** [comment]
Okey, I will implement this feature this evening. I already tested on local and it works for me. Just need to do some more tests and make a pull requests.

**Comment by mholt** [comment]
@stanislavromanov Thanks! That's looking good.

@cbess You're right, to us programmers, the ~ is a natural 'negation' operator. However, Caddy's audience is also for non-programmers. I'm still not sure this syntax is perfect, but it is concise, and I think a minus is a little more intuitive than a tilde.

**Comment by cbess** [comment]
@mholt Understood. I guess I see it as for dev it will have a double meaning and thereby (hopefully) easier to remember. For non-programmers, its still a single char, they won't know the difference. Either way great job with the server.

**Comment by stanislavromanov** [comment]
We can change `-` to `~` very easily. Just need to make up our minds, merge and then we can update documentation on the next release.

**Comment by alixaxel** [comment]
Awesome. :)
