### ISSUE TITLE
Build fails due changes at xenolf/lego

### ISSUE THREAD

**Issue by elcore** [mholt/caddy#640]
caddy/https/client.go:37: cannot use &leUser (type *User) as type acme.User in argument to acme.NewClient:

        *User does not implement acme.User (wrong type for GetPrivateKey method)

                have GetPrivateKey() *rsa.PrivateKey

                want GetPrivateKey() crypto.PrivateKey

caddy/https/client.go:37: cannot use rsaKeySizeToUse (type int) as type acme.KeyType in argument to acme.N

https://github.com/xenolf/lego/pull/130

**Comment by hkjn** [comment]
Confirmed that reverting https://github.com/xenolf/lego/commit/0e26b (and fixing up the conflicts to pick the older versions of the code) allows `go build github.com/mholt/caddy` to succeed.

**Comment by mholt** [comment]
Yeah, lego was just barely updated last night.

Will fix this soon. I need to build in a good way to add ECC support into Caddy.

**Comment by hkjn** [comment]
After some exciting learning opportunities involving git and me not understanding git, I believe my PR https://github.com/mholt/caddy/pull/641 can be safely merged to patch up the build.
