### ISSUE TITLE
Encoded slash in URL

### ISSUE THREAD

**Issue by flecno** [mholt/caddy#643]
I want to address a resource with the name `/`. So rabbitmq api requests look like this: `/api/queues/%2F/queue.fetchtasks`. I can't proxy this requests with caddy, because caddy modify the url path.

My simple Caddyfile:

```
localhost:8888 {
  # proxy to "nc -l localhost 9999"
  proxy /test http://localhost:9999
}
```

If I run `curl localhost:8888/test/%2F/foo`, then caddy decodes the path before proxy (`%2F` to `/`). This results in `/test///foo` but it should be `/test/%2F/foo`. For apache there is an option [AllowEncodedSlashes](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes). Is there any equivalent in caddy?

**Comment by mholt** [comment]
Hmm, good question. Never even heard of that before. :smile: Anyone want to look into this?

**Comment by jleedev** [comment]
I would argue that a front-end HTTP proxy should _never_ do this kind of unescaping. It breaks composability.

Bearing in mind that I don’t have extensive experience coupling various applications to various load balancers, it nevertheless seems that this unescaping behavior is a vestige of CGI, where the PATH_INFO variable is decoded from its URL representation to look like a usable filesystem path.

Modern applications aren’t CGI anymore. Their interface is HTTP, and so should be equally usable pointing the client directly at it for development and testing, and proxying the requests for production. Likewise, a request traversing two reverse proxies will have the URL path double-decoded. Who could possibly be relying on this multitude of behaviors?

I would modify caddy to make as few changes as possible to proxied requests, and only when necessary to comply with RFCs and common practice. (Is there even an RFC for reverse proxies?)

**Comment by jupiter** [comment]
I am unable to reproduce this with the provided config. 

For `$ curl localhost:8888/test/%2F/foo`, I get:

```
$ nc -l localhost 9999
GET /test/%2F/foo HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.47.0
Accept: */*
X-Forwarded-For: ::1
Accept-Encoding: gzip
```

@flecno Which version of Caddy are you running and on what platform?

**Comment by flecno** [comment]
Oh year.. I can reproduce this with version 0.8.1 (darwin amd64). I see there is version 0.8.2 and this version has fixed the problem! :+1: 

So thanks for your help.

**Comment by mholt** [comment]
Huh, cool, I'm not sure why! But glad it's better now.

**Comment by mholt** [comment]
A little birdie told me this might be because of a change to http.Dir in Go 1.6, and 0.8.2 is the first to be built on Go 1.6. (Something about calling path.Clean.)

**Comment by robxu9** [comment]
Unfortunately bumping an old issue, but I'm on Caddy 0.8.3 and it seems that I'm still running into this problem. Jenkins attempts to detect whether a reverse proxy is broken, and so hits a url like `http://192.168.0.108/jenkins/administrativeMonitor/hudson.diagnosis.ReverseProxySetupMonitor/testForReverseProxySetup/http%3A%2F%2F192.168.0.108%2Fjenkins%2Fmanage/`.

However, because Caddy seems to decode the second `%2F%` and changes it to an actual `/`, Jenkins only sees the `http:/` part of the URL, not the whole `http://192.168.0.108/jenkins/manage`.

**Comment by jupiter** [comment]
I can reproduce this. Currently looking into it.

**Comment by jupiter** [comment]
@wmark I see this was introduced here https://github.com/mholt/caddy/commit/f31875dfdeb73db9dddf6a2a175a6b0b349d9b28

We should probably send the original path on the upstream servers. I see that you noted that we can use `URL.RawPath` in middlewares, but modifying the incoming request path at this point may not be expected by all middlewares. In fact, the recommendation in the Go docs is to use the [URL.EscapedPath](https://golang.org/pkg/net/url/#URL.EscapedPath) method and to not use `URL.RawPath` directly, which is exactly what is happening in the upstream request.

We have two options: 1. Remove this modification of the path at this global level, or 2. Create a new URL in the Proxy middleware. What do you think?

**Comment by wmark** [comment]
If middleware *proxy* needs the verbatim üazj, than don't pass the cleaned-up one.

**Comment by mholt** [comment]
@jupiter Does URL.EscapedPath not work for this case? I wonder why it suggests not reading RawPath directly.

**Comment by jupiter** [comment]
@mholt It looks like [URL.EscapedPath](https://golang.org/pkg/net/url/#URL.EscapedPath) creates a new escaping of `URL.Path` if a `URL.RawPath` is not available or invalid.

@wmark The above PR fixes this particular issue. However, we should be careful not to introduce potential latent defects wherever we are matching against a modified `URL.Path`, such as here https://github.com/mholt/caddy/blob/a0e6eb3ba950e94eb0d061c0c7697d3f8005f975/middleware/proxy/proxy.go#L81, https://github.com/mholt/caddy/blob/f4c729bd2205b939f93fad068bbbd7161802f695/middleware/redirect/redirect.go#L22, https://github.com/mholt/caddy/blob/da016f8d5a14cdce2925556ae0e5a7bc72ddbb1a/middleware/headers/headers.go#L25, etc.

**Comment by wmark** [comment]
@jupiter I am the wrong person to talk to about middleware *proxy*, I am afraid. The way I see it your changes do not, and will most probably not affect the core of Caddy. Feel free to ping me if that changes or when you have direct questions. Until then I unsubscribe from this issue because I cannot contribute anything to it at the moment.

**Comment by Cinerar** [comment]
Reproduceble with (got same problem with rabbit as in first post)
Caddy 0.9.5 (+ce47cf5 Sat Apr 01 10:19:03 UTC 2017) 
```
localhost:8888 {
  # proxy to "nc -l localhost 9999"
  proxy /test http://localhost:9999
}
```
```
 curl localhost:8888/test/%2F/foo
```
```
nc -l localhost 9999
GET /test/foo HTTP/1.1
Host: localhost:9999
User-Agent: curl/7.47.0
Accept: */*
X-Forwarded-For: 127.0.0.1
Accept-Encoding: gzip
```

**Comment by mararn1618** [comment]
Hey guys, after a bit of work, I found a workaround for Caddy+RabbitMQ and posted it over here: [Workaround for Caddy 2 + RabbitMQ with encoded forward slash %2FE](https://github.com/caddyserver/caddy/issues/1927#issuecomment-840341897)

**Comment by mholt** [comment]
@mararn1618 This issue is 5 years old and is about Caddy v1. You are using Caddy 2; please don't comment on such old and unrelated issues.
