### ISSUE TITLE
Can't use certificate backup

### ISSUE THREAD

**Issue by klingtnet** [mholt/caddy#647]
I moved my domain to a new server and made a fresh caddy installation.
I've expected to get a rate-limiting error when caddy tries to get certificates for each subdomain (8 in number), so I decided to make a backup of the (still valid) letsencrypt certs of my old caddy installation.
Below you can see the steps of the backup procedure (note that I've anonymized the log, a  #bit):

```sh
sudo cp -r /backup/letsencrypt /srv/http/.caddy/
chown -R http:http /srv/http/.caddy/letsencrypt && chmod og-rwx /srv/http/.caddy/letsencrypt/
runuser -s $(which bash) -l http -c 'caddy -conf=/etc/caddy/myuser/caddy.conf -agree -email=mail@somedomain'
Activating privacy features...2016/02/29 02:07:10 too many renewal attempts; last error: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: klingt.net
diff --brief /srv/http/.caddy/letsencrypt /backup/caddy/letsencrypt
```

I don't know why, but caddy want's to issue new certificates, even that the domains and mail address are still the same. This caused a rate limiting like you can easily see and eventually I've to serve my website for 7 days \wo https because of the rate limiting :tired_face:.
What did I do wrong?

**Comment by jahmad** [comment]
Duplicate issue, it's currently being discussed in #642. please chime in :)

**Comment by klingtnet** [comment]
@jahmad Thanks! I close this issue in favor of #642

**Comment by mholt** [comment]
You know that certificates are only valid for 90 days and need to be renewed, right?

When does your certificate expire?

**Comment by klingtnet** [comment]
The certificate is still valid until 2016/3/13.
