### ISSUE TITLE
regression: 8.2 fails on startup due to acme ratelimiting

### ISSUE THREAD

**Issue by niv** [mholt/caddy#648]
Having deployed the new caddy version 8.2, I tried restarting it - and it tries to refresh all certificates in one go; the problem is, they exceed LE's rate limiting (due to amount of domains). The server fails hard at trying to refresh them all, even though there was still time on the old certs:

too many renewal attempts; last error: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: DOMAIN

When I rolled back to 8.1, it tries to request the outdated certificates (not showing any error, but presumably running into the rate limit again) on startup, but runs regardless:

Activating privacy features...2016/02/29 12:18:06 [INFO] Checking certificates for 22 hosts
2016/02/29 12:12:27 [INFO] Certificate for DOMAIN has 14 days remaining; attempting renewal
2016/02/29 12:12:27 [INFO][fwn.silm.pw] acme: Trying renewal with 340 hours remaining
2016/02/29 12:12:28 [INFO][fwn.silm.pw] acme: Obtaining bundled SAN certificate
2016/02/29 12:12:28 [INFO][fwn.silm.pw] acme: Could not find solver for: tls-sni-01
2016/02/29 12:12:28 [INFO][fwn.silm.pw] acme: Could not find solver for: dns-01
2016/02/29 12:12:28 [INFO][fwn.silm.pw] acme: Trying to solve HTTP-01
2016/02/29 12:12:29 [INFO][fwn.silm.pw] Served key authentication
2016/02/29 12:12:30 [INFO][fwn.silm.pw] The server validated our request
2016/02/29 12:12:30 [INFO][fwn.silm.pw] acme: Validations succeeded; requesting certificates
2016/02/29 12:12:40 [INFO][fwn.silm.pw] acme: Trying renewal with 340 hours remaining
2016/02/29 12:12:40 [INFO][fwn.silm.pw] acme: Obtaining bundled SAN certificate
2016/02/29 12:12:40 [INFO][fwn.silm.pw] acme: Could not find solver for: dns-01
2016/02/29 12:12:40 [INFO][fwn.silm.pw] acme: Trying to solve HTTP-01
2016/02/29 12:12:42 [INFO][fwn.silm.pw] Served key authentication
2016/02/29 12:12:43 [INFO][fwn.silm.pw] The server validated our request
2016/02/29 12:12:43 [INFO][fwn.silm.pw] acme: Validations succeeded; requesting certificates
2016/02/29 12:12:43 [INFO] Certificate for NEXTDOMAIN has 14 days remaining; attempting renewal
...
<server up with partially old certs>!

Is there a workaround/fix for this? Either back off on cert renewal if running into limits, or - preferably(?) - request multi-domain certs. That would probably have to be configurable globally and not on a per-vhost basis.

Cheers!

**Comment by mholt** [comment]
What was your log output when running 0.8.2.?

**Comment by mholt** [comment]
Shower thoughts...

This is not a regression, just a consequence of resizing the renewal window from 14 days to 30. Four weeks is definitely better than 2, but in some cases the upgrade can have this effect. You probably obtained certificates for these names incrementally (or at least not all at once) with previous versions, and 0.8.1 still has the smaller renew window, so it only tries to renew the first batch and is able to succeed. 0.8.2 sees that *more* certificates are in its new renewal window, so it tries to renew all of them and fails.

It's temporary and only affects a small subset of users, so there's nothing for me to do here, I think, however the startup issue is being discussed in #642.
