### ISSUE TITLE
redir like nginx rewrite

### ISSUE THREAD

**Issue by clandmeter** [mholt/caddy#649]
I'm looking into replacing our current reverse proxy (nginx) with caddy's proxy feature.
I have a few rewrite rules defined in nginx that will forward some of our redmine urls to cgit ie:
```
rewrite "^/projects/alpine/repository/revisions/(.*)$"  "http://git.alpinelinux.org/cgit/aports.git/commit/?id=$1"  last;
rewrite "^/projects/abuild/repository/revisions/(.*)$"  "http://git.alpinelinux.org/cgit/abuild.git/commit/?id=$1"  last;
rewrite "^/projects/apk-tools/repository/revisions/(.*)$"   "http://git.alpinelinux.org/cgit/apk-tools.git/commit/?id=$1"   last;
rewrite "^/projects/squark/repository/revisions/(.*)$"  "http://git.alpinelinux.org/cgit/squark.git/commit/?id=$1"  last;
rewrite "^/projects/awall/repository/revisions/(.*)$"   "http://git.alpinelinux.org/cgit/kunkku/awall.git/commit/?id=$1"    last;
```
I have addressed this issue on gitter and it was suggested this would currently not work with only redir and I should try something like this: 
```
redir /project.tld http://{uri}
rewrite {
    r ^/project/id/(.*)
    to /project.tld/test?id={1}
}
```
But this doesn't seem to work. 
Should I put this on hold for now, or is there another solution to fix this issue?

**Comment by mholt** [comment]
You can't rewrite a URL to a different host because rewrite is an internal operation, and a separate host is served elsewhere. Are you trying to do a rewrite or a redirect?

**Comment by clandmeter** [comment]
I'm trying to redirect in a proxy config, so certain url's will not be proxied but redirected to an external server.

**Comment by clandmeter** [comment]
@mholt anyway around this?

**Comment by mholt** [comment]
@clandmeter Is something like #442 (cf. #606) what you need?

**Comment by mholt** [comment]
Closing, due to inactivity.
