### ISSUE TITLE
Backslashes in startup directive on Windows

### ISSUE THREAD

**Issue by jpoehls** [mholt/caddy#65]
I tried using backslashes in my startup directive but it appears they might need escaped?
`startup "C:\php\php-cgi.exe -b 127.0.0.1:9123 -c C:\php\php.ini" &`

Error:
`exec: "C:phpphp-cgi.exe": file does not exist`

Seems like unexpected behavior to me but if it must remain it should definitely be documented.

**Comment by stanislavromanov** [comment]
Did you try `C://php//php-cgi.exe`?

**Comment by jpoehls** [comment]
Sorry, I had a typo in my original. Using single backslashes (`\`) causes the error. If I double them `\\` it makes no difference. If I use forward slashes it works fine (`/`).

**Comment by mholt** [comment]
It's a bug in the lexer when the string is quoted. I'll fix that today.

**Comment by beppe9000** [comment]
hey what is the current syntax to do this ?

**Comment by francislavoie** [comment]
This is a nearly 6 year old issue. The `startup` directive no longer exists, as you can see in the docs: https://caddyserver.com/docs/caddyfile/directives

You should instead use the https://github.com/abiosoft/caddy-exec plugin.

Hi! Thanks for trying Caddy!

Next time, please ask your usage questions on the [Caddy community forums](https://caddy.community). We prefer to keep the GitHub issue board for bugs and feature requests. Don't forget to fill out the thread template so we can help you!
