### ISSUE TITLE
Regression with Internet Explorer 8?

### ISSUE THREAD

**Issue by phptools** [mholt/caddy#650]
Upgrading from 0.8 to 0.8.1 appears to introduce a little regression - I'm no longer able to connect to my test website using Internet Explorer 8 - both http:// and https:// requests fail, and don't show up in the log file (when requesting an https://testabc.local/..... URL, I'm not even prompted to accept my certificate).

Out of curiosity I checked again and IE8 does indeed work with Caddy 0.8.0; upgrading to 0.8.2 does not solve the issue, so it's probably something in the changelog from 0.8.1 - 0.8.

While IE8 is outdated and it certainly shouldn't be a top priority, a fix would be nice nevertheless.

Thank you for your great work!

My Caddyfile:
http://testabc.local {
  redir https://testabc.local
}
https://testabc.local {
  root /vagrant/www/
  tls /vagrant/assets/server.crt /vagrant/assets/server.key
  gzip
  fastcgi / /var/run/php5-fpm.sock php {
    ...
  }
  ...
}

**Comment by mholt** [comment]
This isn't particularly concerning to me, but I'm curious anyway. Are you running Windows xp?

**Comment by phptools** [comment]
Yes, in a virtual machine (the vagrant test environment is of course on another virtual machine too.)

**Comment by mholt** [comment]
Thought so; it's Windows XP that's broken, and it won't receive any more updates I'm afraid. Sorry.

**Comment by jungle-boogie** [comment]
@phptools,

You can use this to test your web browser capabilities:
https://www.ssllabs.com/ssltest/viewMyClient.html
