### ISSUE TITLE
Add domain directive to tls plugin

### ISSUE THREAD

**Issue by otm** [mholt/caddy#654]
As there is currently a rate limit on 5 certificates/domain/week it would be nice to be able to create certificates for several domains in one request. 

The configuration could look something like:

```
tls {
   domains example.com foo.example.com bar.example.com
}
```

The expected outcome from this is that Caddy would create one (1) certificate that includes all domains. No certificates would be created on demand.

**Comment by mholt** [comment]
SAN certificates will not be supported, sorry. It's a deep, deep, deep rabbit hole.

But this Caddyfile will allow you to obtain certificates for known names at startup:

```plain
example.com,
foo.example.com,
bar.example.com {
    # directives in here
}
```

I'm trying to avoid writing code specifically around Let's Encrypt's rate limits.
