### ISSUE TITLE
CLI option for providing a config/working directory

### ISSUE THREAD

**Issue by dprandzioch** [mholt/caddy#656]
Right now Caddy uses the `cwd` to place it's `.caddy` folder containing all the certificate stuff  for letsencrypt. While this is a great way to provide simple set up and usability for smaller projects and development environments, this is a problem when it comes to automatically launching caddy upon boot as well as packaging it for distribution. While `systemd` provides a possibility to define the working directory within the service definition, FreeBSD's `rc.d` and OpenRC (as far as I remember) don't. It would be great to be able to tell Caddy where to store those files.

There is already a `-conf` argument that enables the user to directly provide the path to a `Caddyfile` but as there is more data that's relevant to run the server (namely the `.caddy` directory) it seems to me that the current implementation is kind of incomplete.

I'd see this as a option to override the default behavior if the CLI argument is set like this:

`./caddy -agree -email foo@bar.com -confpath /etc/caddy`

That way, caddy would automatically place its `letsencrypt` folder (and all the other contents that former were created in `.caddy`) in `/etc/caddy` as well as searching the `Caddyfile` within that path. This would make life much more easy for packaging because from a system administrators' point of view you want to have your configuration files where you expect them to be and this is also true for the most distributions' packaging guidelines.

This wouldn't violate the principles currently implemented as you may just run `./caddy` without that argument and have the default behavior as it is.

**Comment by mholt** [comment]
Caddy actually uses $HOME to place the .caddy folder. If no $HOME is set, it uses cwd. See https://caddyserver.com/docs/automatic-https. So if you want to change where .caddy is, set or change the $HOME environment variable.

**Comment by mholt** [comment]
Closing, assuming that to be sufficient.
