### ISSUE TITLE
X number of subdomains

### ISSUE THREAD

**Issue by Ozzadar** [mholt/caddy#658]
Hey guys,

Caddy works awesome but I have a question:

Is there a way to create a listing for X number of subdomains under the same entrypoint?

I was trying something like

```

0.0.0.0:80 {
proxy sub.domain.com backend:port {
}

proxy sub2.domain.com backend2:port {
}

proxy sub3.domain.com backend3:port {
}

}

```

but it wasn't working. Is there a way to achieve my desired result?

Thanks,
-Ozzadar

**Comment by mholt** [comment]
It looks like you're trying to proxy different sites to different backends, so define multiple sites in your Caddyfile instead:

```plain
sub.domain.com {
    proxy / backend:port
}
sub2.domain.com {
    proxy / backend2:port
}
sub3.domain.com {
    proxy / backend3:port
}
```

Note that you don't need the empty `{ }` after each proxy line.

Remember that the first argument is a base path, not a hostname, to match.

**Comment by Ozzadar** [comment]
the problem is that we're generating subdomains on a dynamic level and caddy is complaining that we've "issued too many certificates to domain.com" when I get past 2.

this is my Caddyfile:

```
ghost2.klouds.org {
proxy / 192.168.194.171:32769 {
policy least_conn
fail_timeout 10s
max_fails 0
}
}




ghost.klouds.org {
proxy / 192.168.194.171:32768 {
policy least_conn
fail_timeout 10s
max_fails 0
}
}






minecraft.klouds.org {
proxy / 192.168.194.171:32770 {
policy least_conn
fail_timeout 10s
max_fails 0
}
}
```

and this is the output:

```
Activating privacy features...2016/03/06 14:18:46 [minecraft.klouds.org] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for: klouds.org
```

**Comment by mholt** [comment]
That's a [rate limit imposed by Let's Encrypt](https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769). Sorry, you'll just have to wait this one out or use a different CA for the meantime.

If you ever want to test your configuration (as the [documentation recommends](https://caddyserver.com/docs/automatic-https) for larger setups) remember that Let's Encrypt has a staging server that doesn't have the same rate limits (it issues fake certificates): https://acme-staging.api.letsencrypt.org/directory.
