### ISSUE TITLE
[question] - Problem with html5mode on caddy

### ISSUE THREAD

**Issue by marioidival** [mholt/caddy#665]
Exists some solutions to solve this with Nginx, Apache etc...

How can do with Caddy?

[Examples](https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-configure-your-server-to-work-with-html5mode)

**Comment by 1lann** [comment]
Using `ext .html` should work, which first tries to access the base URL, and then tries with .html appended to the end. See: https://caddyserver.com/docs/ext

**Comment by marioidival** [comment]
@1lann Don't work :(

```caddyfile
0.0.0.0:2015

root /site/frontend/templates
startup "sh /site/frontend/start.sh"

gzip
ext .html

header /api Access-Control-Allow-Origin *
proxy  /api http://192.168.99.100:7000/ {
    without /api
}
```

**Comment by 1lann** [comment]
Oh sorry, I misread the other configurations, how about
```
rewrite {
	to {path} {path}/ index.html
}
```

**Comment by mholt** [comment]
Assuming that worked, closing. :smile:

**Comment by marioidival** [comment]
Sorry to delay, with views that worked, but the calls to `/api` not work now.
