### ISSUE TITLE
browse: hide dotfiles

### ISSUE THREAD

**Issue by niv** [mholt/caddy#669]
Hi,

I can't find a way to hide dotfiles (.hidden) in caddy's 8.2 default template. (I just grabbed it out of git and configured the browse directive manually).

I've tried messing with ```{{if (.Truncate .Name 1) ..``` to see if it starts with a dot, but I can't figure the syntax and caddy doesn't give any parser/error messages at all except 503.

Please advise. :)

**Comment by 1lann** [comment]
Using
```
{{if ne ($.Truncate .Name 1) "."}}
	// Is not a hidden file
{{end}}
```
Works for me.

**Comment by niv** [comment]
Thank you very much!
