### ISSUE TITLE
Except in fastcgi directive

### ISSUE THREAD

**Issue by andreimarcu** [mholt/caddy#670]
After seeing that location blocks aren't a thing yet I came across the "except" clause of the proxy directive. That seems at the most basic level something that would work in the meantime, however I was surprised to see that it doesn't exist for the fastcgi directive. Is there a specific reason for this or can it be a quick fix?

**Comment by abiosoft** [comment]
Yeah it can be added but a more universal solution is still in the works.

**Comment by mholt** [comment]
I'm wondering if the proxy and fastcgi directives can be combined, so that fastcgi becomes a `preset` just like the `websocket` is. That way, fastcgi gets the benefit of load balancing, multiple backends, etc.

**Comment by mholt** [comment]
Actually, nix the idea of combining fastcgi and proxy.

@abiosoft Do we still have a 'universal' solution in the works? If it's what I'm thinking, we nixed that idea too. :smile: Maybe we should just have somebody add `except` to this directive.

It should be able to appear multiple times so users can add more than one path exception.

**Comment by abiosoft** [comment]
This has been implemented. It will be available in the next release or now if you build from source.
