### ISSUE TITLE
Re-enabling prometheus middleware after restart

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#675]
_If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!_
#### 1. What version of Caddy are you running (`caddy -version`)?

caddy dev version (build from master)
#### 2. What are you trying to do?

Re-enabling the prometheus handler after a restart (SIGUSR1)
#### 3. What is your entire Caddyfile?

``` text
localhost:2020 {
    prometheus
}

localhost:2021 {
    prometheus
}
```
#### 6. What did you see instead (give full error messages and/or log)?

The handler fails to run because of

```
err listen tcp 127.0.0.1:9180: bind: address already in use
```

But I can't stop the previous handler before the new caddy process starts, because there are no hook. I'm wondering what to do here?
Seems the Shutdown function could help here, but that is _only_ run on server stops, not restarts?

Help?

**Comment by mholt** [comment]
Ohh, your add-on opens a new port and does its own listening. Is there a way to serve prometheus metrics at a path on an existing listener? In other words, to set up a Handler rather than having to start a whole HTTP server? That'd be preferable, I think.

**Comment by miekg** [comment]
The problem with re-using another listener is that you want to protect your metrics. I might have taken a shortcut here, but just listening on localhost (and nothing else) is safest. Other use cases would include listening on a private address just for monitoring. 
IOW: there are use-cases where you want to start a new listener, I think. Even though it is possibly to protect with other means (passwords, IP blocks).

**Comment by mholt** [comment]
Okay, so basically, you need a callback like Restart() so that you can close your listener. Would that do?

**Comment by miekg** [comment]
yes, but I wonder why `Shutdown` is not called for middleware on these restarts?

**Comment by mholt** [comment]
@miekg Because that's just how I decided it should work. A restart is technically not a shutdown, especially on Unix. Users would not equate Shutdown with Restart/Reload. For example, if you use the `shutdown` directive, it is executed only when the server is stopped, not when you reload it. Other middlewares rely on startup and shutdown being executed only when the server first starts and finally shuts down, like the git add-on.

I'll look at adding a Restart hook.

**Comment by miekg** [comment]
Ok, fair enough, I Restart hook makes a lot of sense. Hopefully other middleware would find this useful as well.

**Comment by ericdreeves** [comment]
Hi, @miekg. There are some methods that have been added to caddy.Controller since you opened this issue: https://godoc.org/github.com/mholt/caddy#Controller

Are OnStartup, OnRestart, or OnShutdown sufficient? I see that you're using OnStartup in your setup function since Caddy 0.9.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [mholt/caddy] Re-enabling prome..." ]
>Hi, @miekg. There are some methods that have been added to caddy.Controller since you opened this issue: https://godoc.org/github.com/mholt/caddy#Controller
>
>Are OnStartup, OnRestart, or OnShutdown sufficient? I see that you're using OnStartup in your setup function since Caddy 0.9.

Yes, I think this *should* be fixed, but I never bothered to double check, hence
this issue is still open.

**Comment by miekg** [comment]
Yes those should be enough.
