### ISSUE TITLE
Markdown files not named index return HTTP 404

### ISSUE THREAD

**Issue by johntopley** [mholt/caddy#678]
Hi,

I've just started converting my pure HTML blog over to Caddy using the `markdown` and `template` directives with TOML front matter. The issue I'm having is that files I've named `index.md` are served fine, but Markdown files with different filenames return an HTTP 404.

These files are in a nested `blog/yyyy/mm/dd` folder structure and have a permalink style filename e.g. `custom-url-scheme.md`. Unless I'm fundamentally misunderstanding how these features are supposed to work, I would expect to be able to visit (for example) `http://localhost:2015/blog/2014/11/20/custom-url-scheme` and have the Markdown file converted to HTML. If I rename my `custom-url-scheme.md` to `index.md` then visiting `http://localhost:2015/blog/2014/11/20/` works as expected.

This is my Caddyfile:

```
localhost:2015 {
  gzip
  ext .html
  header / -Server
  log access.log {
    size 20
    age  365
    keep 52
  }
  
  errors {
    404 404.html
    500 500.html
    log error.log {
      size 20
      age  365
      keep 52
    }
  }
  
  internal /templates
  
  markdown {
    template root templates/root.html
    template blog templates/blog.html
    template date templates/date.html
    template post templates/post.html
  }
}
```

What am I doing wrong? Thanks in advance.

**Comment by mholt** [comment]
If you want the .md extension to be implicit, you can use `ext .md` in your Caddyfile. See the [ext directive](https://caddyserver.com/docs/ext). Index files are a special case, where `index.md` files are tried if a directory is requested.

**Comment by johntopley** [comment]
Ah, of course! So simple. Thanks Matt.
