### ISSUE TITLE
Caddy doesn't handle static request with additional get when using proxy

### ISSUE THREAD

**Issue by kokizzu** [mholt/caddy#680]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
untracked dev build (latest)

#### 2. What are you trying to do?
curl http://localhost/js/jquery.js
curl http://localhost/js/jquery.js?_=1457939263837

#### 3. What is your entire Caddyfile?
```text
127.0.0.1:80, localhost:80 {
        gzip
        root /home/web/public
        errors {
                log /home/web/.log/x.caddy-error.log {
                        size 4 # rotate after 4MB
                }
                500 /home/web/public/502.html
                502 /home/web/public/502.html
                503 /home/web/public/502.html
                504 /home/web/public/502.html
        }
        proxy / 127.0.0.1:12345 {
                proxy_header Host {host}
                proxy_header X-Forwarded {remote}
                proxy_header X-Real-IP {remote}
                proxy_header X-Forwarded-Proto {scheme}
        }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy

#### 5. What did you expect to see?
not 404 on the second request (one with `?_=` on the url)

#### 6. What did you see instead (give full error messages and/or log)?
passed to the backend

**Comment by mholt** [comment]
Maybe your backend is returning 404? Can you verify that Caddy itself is producing 404? Also, if you use build.bash, we'll have a better idea what changes have been made to the code and that may aid us in helping you.

**Comment by kokizzu** [comment]
yes, we have change our backend code so it could handle `?_=` requests, before we use `caddy`, `nginx` is the one that normally handle those kind of requests..

**Comment by mholt** [comment]
I tried reproducing this without the proxy backend (because, obviously, I don't have the same one you do), and am unable to. Can you cause it to happen without the proxy?

**Comment by kokizzu** [comment]
this doesn't happened without the proxy.

**Comment by mholt** [comment]
Hmm, so I made two Caddyfiles. This one:

```plain
localhost

proxy / localhost:8080 {
	proxy_header Host {host}
	proxy_header X-Forwarded {remote}
	proxy_header X-Real-IP {remote}
	proxy_header X-Forwarded-Proto {scheme}
}
```

And this one as a backend:

```plain
localhost:8080

browse
log stderr
errors stderr
gzip
```

And all requests for static files (and browse, templates, markdown, and others) to localhost:2015 with `?_=` on the URL succeed, no 404s.

I'd recommend checking your proxy configuration and your backend to make sure they're set up properly. Good luck!
