### ISSUE TITLE
`go get` fails on fedora due to elliptic.P224

### ISSUE THREAD

**Issue by dncohen** [mholt/caddy#690]
I'm brand new to caddy, and almost as new to golang, so please forgive me if this is a FAQ.

My problem is this on fedora23:

```
[user@sandbox ~]$ go get -u github.com/mholt/caddy/caddy
# golang.org/x/crypto/ocsp
gocode/src/golang.org/x/crypto/ocsp/ocsp.go:199: undefined: elliptic.P224
```

A little searching tells me the dependency is omitted on fedora due to a patent issue.  But the searching has yet to turn up a workaround.

I'm wondering if this dependency could be made optional in Caddy?

It occurs to me possibly the change has to be in crypto/ocsp.  If so, pardon the noise!  Caddy looks quite nice and I'm eager to try it out.

Thanks. -Dave

**Comment by dncohen** [comment]
Ok, so I did I miss the "You will need Go 1.6 or newer." in the README.md

In case it saves any fedora users some time... first `sudo dnf remove golang`, then follow instructions on https://golang.org/doc/install, which are simple and clear.

Then `go get -u github.com/mholt/caddy/caddy` will succeed.  (Although does not create a $GOPATH/bin/caddy.  Haven't figured that out yet.)

**Comment by weingart** [comment]
go test github.com/mholt/caddy/...
go install github.com/mholt/caddy/caddy

-Toby.

**Comment by zoowar** [comment]
This issue persists with Fedora 24. Today I upgraded to Fedora 24 so I would have a 1.6 version of golang.

```
[user]$ go version
go version go1.6.3 linux/amd64

[user]$ go get -u github.com/mholt/caddy/caddy
# golang.org/x/crypto/ocsp
work/golang/src/golang.org/x/crypto/ocsp/ocsp.go:199: undefined: elliptic.P224
````

**Comment by elcore** [comment]
Hello @zoowar,

please follow the instructions on https://golang.org/doc/install

**Comment by anovanmaximuz** [comment]
Hi @elcore it solve or just trying ? I seem problem like @dncohen 

go build mattermost.go 
# github.com/mattermost/platform/vendor/golang.org/x/crypto/ocsp
../go/src/github.com/mattermost/platform/vendor/golang.org/x/crypto/ocsp/ocsp.go:199: undefined: elliptic in elliptic.P224
../go/src/github.com/mattermost/platform/vendor/golang.org/x/crypto/ocsp/ocsp.go:199: undefined: elliptic in elliptic.P256
../go/src/github.com/mattermost/platform/vendor/golang.org/x/crypto/ocsp/ocsp.go:202: undefined: elliptic in elliptic.P384
../go/src/github.com/mattermost/platform/vendor/golang.org/x/crypto/ocsp/ocsp.go:205: undefined: elliptic in elliptic.P521

**Comment by elcore** [comment]
Hello @anovanmaximuz,

> please follow the instructions on https://golang.org/doc/install, download Caddy here https://caddyserver.com/download or use https://getcaddy.com

> In case it saves any fedora users some time... first sudo dnf remove golang, then follow instructions on https://golang.org/doc/install, which are simple and clear. Then go get -u github.com/mholt/caddy/caddy will succeed.

P.S: This is Caddy and not mattermost!!!!!!!!!!!!!!!!!!!!!!!

**Comment by anovanmaximuz** [comment]
@elcore thanks it works
step :
1. remove golang
2. install caddy
3. install golang for latest (1.7.x) , do not package manager llinux, download manual and add it into PATH,  follow https://golang.org/doc/install 
4. try build - no errors affect
