### ISSUE TITLE
Need advice for secure link, streaming server

### ISSUE THREAD

**Issue by meepeek** [mholt/caddy#692]
I want to make a website like udemy and I will need a streaming server that has token feature (I am looking into nginx secure link then see this project on the way but I cannot find the feature in your list) Please give me some advice.

**Comment by mholt** [comment]
I imagine you're referring to this: http://nginx.org/en/docs/http/ngx_http_secure_link_module.html. Caddy doesn't currently have secure link features. This would make a good add-on, though. Anyone is welcome to make it!

**Comment by meepeek** [comment]
Does Caddy do mp4 streaming out of the box ?

**Comment by meepeek** [comment]
I serve an mp4 file and it just works somehow.

**Comment by mholt** [comment]
You can serve "static" files out of the box, yes, so if the mp4 file is just sitting on disk and you want people to be able to download it, Caddy can definitely do that.

**Comment by tgulacsi** [comment]
I think the "jws" module is a better (at least more complaint) alternative, which provides the link secure feature, too. But if needed, an nginx-compliant secure link feature can be implemented, too.
(It is just the URLSafe-base64 encoded string of MD5 of the "<timestamp><path><client IP>" string, appended to the link as "?md5=<md5>&expires=<timestamp>")

**Comment by mholt** [comment]
Good point; [`jwt`](https://caddyserver.com/docs/jwt) is a little more 'standardized' way of doing it. I'll close this issue then, in favor of that plugin, but if somebody still really wants secure link like nginx does it, you're welcome to write the plugin to do it.
