### ISSUE TITLE
IP Filter does not accept single ip's and ranges

### ISSUE THREAD

**Issue by dragon2611** [mholt/caddy#693]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
0.82

#### 2. What are you trying to do?
Add both single IP's and ranges to IP filter as per documentation.

#### 3. What is your entire Caddyfile?
Do not wish to provide.

However to reproduce create an IP filter and list multiple IP's with some ranges e.g

ipfilter /mydirectory {
rule allow
ip 192.168.1.1 10.0.0.3 10.0.17.0-254 10.0.24.0-255
}

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
N/A

#### 5. What did you expect to see?
All traffic from listed IP's allowd

#### 6. What did you see instead (give full error messages and/or log)?
Traffic sourced from an IP within the defined Ranges appears to be allowed, however traffic sourced from one of the individual IP's listed is NOT allowed, If you remove the Ranges from the config then the single IP's are then granted access.

**Comment by mholt** [comment]
Hi, this is an add-on which we do not maintain; please file this issue in [the add-on's repo](https://github.com/pyed/ipfilter). Pyed will be able to help you better.

**Comment by dragon2611** [comment]
Apolagies, refiled to correct repo.
