### ISSUE TITLE
SIGTERM should call shutdown callbacks on POSIX systems

### ISSUE THREAD

**Issue by mwmahlberg** [mholt/caddy#694]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.2

#### 2. What are you trying to do?

When calling `kill <caddypid>`, as it basically would be done by initscripts, SIGTERM is sent to caddy.
In this case, the `shutdown` directive does not get executed, potentially leaving processes open.

#### 3. What is your entire Caddyfile?
```text
:80
log stdout
# the '&' is needed, as fcgiapp does not for to background
startup /usr/local/bin/fcgiapp &
shutdown /usr/bin/killall fcgiapp
fastcgi / 127.0.0.1:10000
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

 * Docker image:

```
FROM alpine:latest
COPY caddy /usr/local/bin/caddy
COPY Caddyfile /etc
COPY testfcgi /usr/local/bin/fcgiapp
EXPOSE 80
ENTRYPOINT /usr/local/bin/caddy -conf="/etc/Caddyfile"
```

* Started with `docker run -i -t -P --entrypoint="/bin/sh" <imageid>`
* Started caddy with `caddy -conf="/etc/Caddyfile" &`
* Sent `kill <caddyPid>`

#### 5. What did you expect to see?

After killing the caddy process with SIGTERM, I would expect `fcgiapp` to be stopped. However, it is not.

#### 6. What did you see instead (give full error messages and/or log)?

`fcgiapp` was soll running and had to be manually stopped.

#### 7. Note

While this is not necessarily a problem in a docker environment and with the setup described above, some processes started with `startup` might benefit from or even require a graceful shutdown (persisting sessions, finishing transactions etc.). However, since the process was started through Caddy, the next signal to be sent to the process would be SIGKILL.

Put differently: Since SIGTERM is defined as the request to shutdown the process gracefully, it should trigger the execution of the `shutdown` directive.

**Comment by mholt** [comment]
Hi, thanks for the detailed report!

This is not a bug, SIGTERM is defined as a forceful stop. If you want to stop gracefully and execute shutdown hooks, use SIGINT. https://caddyserver.com/docs/cli#signals

**Comment by mwmahlberg** [comment]
This is exactly my point: SIGTERM is used by almost all init systems to signal the request for a graceful shutdown, and is defined this way in POSIX, unless I am mistaken here.

**Comment by mholt** [comment]
nginx uses TERM as a "fast" shutdown: http://nginx.org/en/docs/control.html

**Comment by mwmahlberg** [comment]
Admitted. But also

> NGINX does not automatically spawn FCGI processes. 

The problem arises from the fact that Caddy ignores the signal on behalf of the process started with `startup` and presumably shut down with `shutdown`, in effect.

**Comment by mholt** [comment]
It doesn't ignore the signal, it just does a forceful shutdown, as documented. Use SIGINT to execute shutdown hooks, and it should stop your fcgiapp just fine. :blush:

**Comment by mwmahlberg** [comment]
Well, as said before, that defies the standard shutdown procedure most init systems follow: 

 1. `Shutdown Script ` – graceful
 2. `SIGTERM` – graceful as per POSIX and SUS, may be ignored if no graceful shutdown needed, something that Caddy can not decide for dependent processes it spawned, imho
 3. `SIGKILL` (hard)

And hence, it is problematic not allowing the user to have dependent processes shut down gracefully on a signal that is widely accepted to trigger a graceful shutdown. This forces the user of Caddy to implement an init script to ensure graceful shutdown and imho violates the Principle of Least Surprise / Law of Least Astonishment.

Calling the callbacks on SIGTERM and doing a fast shutdown on SIGKILL would be compliant. NGINX can do a fast shutdown on SIGTERM, since it does not spawn other processes.

Anyway, I take your decision for granted.

**Comment by mholt** [comment]
> a signal that is widely accepted to trigger a graceful shutdown.

I think it depends on the program. For example, nginx *does* spawn processes and TERM is a fast shutdown.

> This forces the user of Caddy to implement an init script to ensure graceful shutdown and imho violates the Principle of Least Surprise / Law of Least Astonishment.

No, it doesn't. Just use SIGINT instead of SIGTERM.
