### ISSUE TITLE
Clean up ineffectual assignments

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#697]
I've added a new command to the CI test scripts, ineffassign, which checks for any ineffectual assignments (assignment operations that end up seeing no use). We have [a number of these](https://goreportcard.com/report/github.com/mholt/caddy#ineffassign) in existing code that are now causing the CI tests to fail. Would be great if somebody -- preferably somebody new to Go or new to this project -- would clean them up! Submit a pull request with your changes.

You can also see them in the [actual CI test output](https://travis-ci.org/mholt/caddy/jobs/118724807) if that's helpful.

**Comment by p4tin** [comment]
I would love to take this on.
