### ISSUE TITLE
TCP proxy / SSL terminator

### ISSUE THREAD

**Issue by robotiv** [mholt/caddy#701]
Hi,

Great project! I looked through the documentation but couldn't find a way to use caddy as a dumb ssl terminator or transparent proxy. The 'proxy' option strictly matches the 'from' field to forward to a backend. Is there any way to use caddy to match the incoming request based on SNI field, strip off the SSL, and then proxy the rest of the request to the given backends without any further actions?

Something like:

mysite.com {
  proxy 127.0.0.1:8080
}

This could also be accomplished if the 'proxy' option would accept a default backend option, similar to haproxy. Instead of explicitly matching on a 'from', if none of the proxy fields matched it would use the default set one.

**Comment by captncraig** [comment]
Caddy is currently a full http server, not a tcp server. It would be rather difficult to have it do raw connection proxies. I would probably recommend nginx or other similar software for that purpose.

**Comment by mholt** [comment]
@robotiv You can do this, I think, unless I misunderstand what you mean.

```
mysite.com {
    proxy / 127.0.0.1:8080
}
:443 {
    # default/catchall
    tls cert.pem key.pem
    proxy / 127.0.0.1:8081
}
```

Or whatever. You can specify as many sites/hostnames as you need to.
