### ISSUE TITLE
Establish a canonical caddy site/Caddyfile location

### ISSUE THREAD

**Issue by alfiepates** [mholt/caddy#702]
At the moment, Caddy docs don't recommend any particular location to store the site, leaving it up to the user's discretion. While this is fine for dev environments, for production sites a "canonical" location would be preferred, especially where Caddy is being run as a service.

 I propose the following, where `SITENAME` is the name of the caddy site being served, and `Caddyspec` is a hypothetical file that gives Caddy a list of Caddyfiles to load: 

```
/var/caddy-www/SITENAME # SITENAME root
/var/caddy-www/SITENAME/Caddyfile # Caddyfile for SITENAME 
/var/caddy-www/Caddyspec # Caddyspec file containing the path /var/caddy-www/SITENAME/Caddyfile
```

**Comment by mholt** [comment]
> for production sites a "canonical" location would be preferred

Can you explain why this is? The Caddyfile is intended to live by the site(s) it is serving, not in some system folder.

**Comment by tboerger** [comment]
Alpine puts a global config to /etc/caddy/caddy.conf

**Comment by mholt** [comment]
Haven't heard back from @alfiepates in a couple months so I'm closing this for now.

I'm not sure I want the Caddy documentation to get into individual systems and recommended locations; in fact, the docs already say that the Caddyfile should live by the site you're serving -- this works very nicely in dev environments but I can see why you might want just "one" Caddyfile (you could use imports?) in production.

But maybe that discussion is not really a Caddy issue, more of a deployment/sysadmin question that belongs [on the forum ("Production Use" category perhaps?)](https://forum.caddyserver.com/c/production-use) - feel free to continue this over there!
