### ISSUE TITLE
Fedora 23 + PHP-FPM

### ISSUE THREAD

**Issue by ricardson** [mholt/caddy#703]
Hi all,

  Iḿ doing some tests with caddy + php-fpm, in a "vagrant" enviroment and I did:

1 - installed php-fpm
2 - start the php-fpm (systemctl start php-fpm)
3 - the default php-fpm configuration is socket (listen = /run/php-fpm/www.sock)
4 - I have "index.php" to test
5 - My Caddyfile

http://0.0.0.0
gzip
browse
markdown /blog
ext .html .php
log logs/access.log
errors logs/errors.log
header / -Server
fastcgi / /run/php-fpm/www.sock php

6 - I'm start the caddy process as root.

When I try to access "http://localhost" show the below error: 

29/Mar/2016:19:28:06 +0000 [ERROR 404 /index.php] Primary script unknown
29/Mar/2016:19:28:35 +0000 [ERROR 404 /index.php] Primary script unknown

**Comment by abiosoft** [comment]
Does php-fpm have access to the source files ?

**Comment by abiosoft** [comment]
The most common case of this error is when the user running php-fpm does not have read access to the source files. I hope the owner of the source files is not root.

**Comment by ricardson** [comment]
found the problem. Let show the solution :) 

I'm using vagrant to test caddy, so I want to run caddy as "vagrant" user.

1 - Install php-fpm (dnf install php-fpm)

2 - Changes php-fpm configuration, find the option "**listen.acl_users =**" and add the "vagrant' user.

3 - Start the service (systemctl start php-fpm)

4 - Copy the site files to /var/www/html and set the permission(owner/group) to "**apache**" in my case directory name was "**site**"

5 - Setting the vagrant environment to run caddy, in my case I have /vagrant folder where I have caddy binary.

cd /vagrant/caddy
sudo setcap cap_net_bind_service=+ep ./caddy
ulimit -n 4096
./caddy

6 - My Caddyfile for reference.

http://0.0.0.0
gzip
root /var/www/html/site 
ext .php
log /var/www/html/site/logs/access.log
errors /var/www/html/site/logs/error.log
header / -Server
fastcgi / /run/php-fpm/www.sock php


Cheers,

**Comment by mholt** [comment]
Thanks for sharing the solution!
