### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by HalisCz** [mholt/caddy#709]
Hi, 

would you mind considering some changes for making reproducible builds possible?

I think that this should be great for increased trustability for pre-built binaries.

I am thinking about issues like:
- compilation steps, submodules and libraries versions and checksums of pre-built binaries
- print used built-in libraries versions along with caddy version (making possible to check if affected by bug in built-in library, etc.)
- signed checksums of pre-built binaries
- etc.

**Comment by mholt** [comment]
Hi Michal, thank you for your question. We're probably going to vendor our dependencies before 1.0, so all builds should be reproducible at that point. See #200 and #630.
