### ISSUE TITLE
Graceful reload with systemd services breaks due to PID change

### ISSUE THREAD

**Issue by joepie91** [mholt/caddy#711]
#### 1. What version of Caddy are you running (`caddy -version`)?

0.8.2

#### 2. What are you trying to do?

Writing a systemd service file to manage Caddy as a service, and adding 'reload' functionality.

#### 3. What is your entire Caddyfile?
```text
import /etc/caddy/sites/*
```

(`/etc/caddy/sites/` only contains a single empty file, as I haven't gotten to that point yet)

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Via a systemd service:

```
[Unit]
Description=Caddy HTTP Server

[Service]
EnvironmentFile=-/etc/default/caddy
ExecStart=/home/caddy/caddy $EXTRA_OPTS
ExecReload=/bin/kill -USR1 $MAINPID
WorkingDirectory=/home/caddy
LimitNOFILE=4096
IgnoreSIGPIPE=false
KillMode=process
User=caddy

[Install]
WantedBy=multi-user.target
```

Emphasis on the `ExecReload` specification.

#### 5. What did you expect to see?

Ability to repeatedly successfully reload Caddy with updated configuration.

#### 6. What did you see instead (give full error messages and/or log)?

After initial run, `systemctl status caddy`:

```
* caddy.service - Caddy HTTP Server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled)
   Active: active (running) since Sat 2016-04-02 08:56:26 EDT; 2s ago
 Main PID: 15862 (caddy)
   CGroup: /system.slice/caddy.service
           `-15862 /home/caddy/caddy
```

First `systemctl reload caddy` works fine. However, `status` now shows:

```
* caddy.service - Caddy HTTP Server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled)
   Active: inactive (dead) since Sat 2016-04-02 08:57:13 EDT; 2s ago
  Process: 15873 ExecReload=/bin/kill -USR1 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 15862 ExecStart=/home/caddy/caddy $EXTRA_OPTS (code=exited, status=0/SUCCESS)
 Main PID: 15862 (code=exited, status=0/SUCCESS)
```

A second attempt at `reload` will fail:

```
Job for caddy.service failed. See 'systemctl status caddy.service' and 'journalctl -xn' for details.
```

The cause is that Caddy is now running under a different PID (15874 rather than 15862), post-reload:

```
caddy    15874  0.0  0.9  13628  9692 ?        Sl   08:57   0:00 /home/caddy/caddy
```

How would I best resolve this?

**Comment by DenBeke** [comment]
Doesn't specifying the PID file solve this?

This is how I do it:
```
[Service]
...
PIDFile=/var/run/caddy/caddy.pid
ExecStart=/home/mathias/caddy -agree -email my_lets_encrypt@mail.com -pidfile=/var/run/caddy/caddy.pid
...
```

**Comment by tgulacsi** [comment]
And set

```
Type=forking
```

too.

**Comment by mholt** [comment]
If you build Caddy from source, you can also use `-restart=inproc` to do same-process restarts, preserving the PID. But they won't be graceful restarts.

**Comment by klingtnet** [comment]
[Here](https://www.nginx.com/resources/wiki/start/topics/examples/systemd/) is the systemd file of `nginx`. They also use `Type=forking` and a `PIDFile`.

**Comment by captncraig** [comment]
I use it without type=forking and it works fine. Just use the pidfile.

**Comment by mholt** [comment]
Lots of good options here. Assuming this is not really a Caddy issue, so closing.

**Comment by dschissler** [comment]
@mholt I don't understand why this isn't a Caddy issue?  I copied the systemd setup and I can get it working but it breaks after I've restarted it many times as I'm working on my Caddyfile on Ubuntu 16.04.

**Comment by klingtnet** [comment]
@dschissler Did you use [init/linux-systemd/caddy.service](https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service)? Also, you don't have to restart the service to check the configuration, instead send [`SIGUSR1`](https://github.com/mholt/caddy/issues/107#issuecomment-151275963) to only reload the configuration or use `caddy -validate -conf /path/to/Caddyfile`.

**Comment by dschissler** [comment]
@klingtnet Thanks.  Yes I used that provided service file.  I have no idea what SIGUSR1 is and at this moment its just another thing to research.  I don't think that I should need to know any of this and that manually building Caddy into my provision system is enough to ask of anyone.  It would be great if the systemd file just worked as currently it fails rather quickly after some restarts.  This is my first night into Caddy and porting web server configs is always very onerous and just restarting the web server through the known and established way should be enough.  The systemd file is broken.

**Comment by klingtnet** [comment]
@dschissler `SIGUSR1` is the name of a singal that you can send to the caddy process to trigger a config reload, this is a common mechanism that is also used by server's like nginx. You can this signal to caddy like this: ` pkill -SIGUSR1 caddy`.
You didn't provide much information, especially no log messages, so it is hard to know why caddy actually restarted. You can see caddy's log messages through systemd's journalctl `journalctl -u caddy`. The log messages should indicate why the server restarted.
You said that you're porting web server configurations, this could have a caused a Let's Encrypt rate limiting, which you can prevent by [using their staging CA](https://caddyserver.com/docs/automatic-https#testing).

> The systemd file is broken.

That's a bit exaggerated.

**Comment by dschissler** [comment]
I turned tls off.  Look its simple.  The service refuses to restart and the only thing that I've found that fixes this is reloading systemd itself.  So if nothing is wrong with my Caddyfile config then it shouldn't matter what state it was in after I tell it to hard `stop` and then `start` again and also with `restart` then it should just work.  Yeah, so if that doesn't work then the systemd service file that is provided is broken.  Its really not enough if it only works consistently with the manual lower level commands that you seasoned guys send to it.

**Comment by klingtnet** [comment]
@dschissler I can reproduce your issue now. The problem does not occur if caddy is run from a shell:

```sh
$ caddy -conf /tmp/Caddyfile -log stdout &
$ watch pkill -USR1 caddy
```
i.e. there is actually something wrong in the service script.
I don't have a clue at the moment, systemd should also keep track of chaging PIDs.
Has anybody some ideas?

**Comment by dschissler** [comment]
I tried this as well but it didn't seem to help.  Thanks for looking into it.

```
PIDFile=/var/run/caddy/caddy.pid
ExecStart=/usr/local/bin/caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -root=/var/tmp -pidfile=/var/run/caddy/caddy.pid
```

**Comment by mholt** [comment]
Please open a new issue (to discuss changes to the service file) or forum post (to get help) -- Caddy doesn't reload with new PIDs anymore. This issue is well past its time.
