### ISSUE TITLE
Implement TLS ticket key rotation

### ISSUE THREAD

**Issue by wmark** [mholt/caddy#714]
Caddy uses Go's TLS implementation, which on its own does not rotate TLS ticket keys.

Perfect forward secrecy works best if anything that could be used to decrypt a particular TLS session is lost after some minutes (or hours). In this case this is accomplished by using a new TLS ticket key every so often and pruning an old one.

I'd recommend keeping 3–4 TLS ticket keys for a timespan of 16+8+16 hours: Every 10–12 hours, for every controller with Config.TLS.Enabled, set a new random value as first ticket N=0 after having pushed all tickets back in the array, from N to N+1, intentionally »losing« the last one N+3. (→ FIFO)

https://golang.org/pkg/crypto/tls/#Config.SetSessionTicketKeys

**Comment by mholt** [comment]
This is probably easy to do, but will take some inspection of the code by a new contributor in order to be familiar with where to put it.

**Comment by wmark** [comment]
That's the beauty of it. Still work, and important. Hint: ```server/server.go```.

After that it's just a Goroutine (a closure, btw) with

```go
var c tls.Config = s.Server.Server.TLSConfig

for {
	select {
	case <-stopSignal:
		return
	case <-time.After(time.Hour * XXX):
		// currentTicket := c.SessionTicketKey
		// newOne := random(…)
		// c.SetSessionTicketKeys([][32]byte{newOne, currentTicket})
		// more tickets? keep book of them because tls.Config does not export the whole list :-(
	}
}
```

… and writing to the other end of channel ```stopSignal``` somewhere else. (Hint: search for SIGQUIT)

Don't bother saving the tickets for or during restarts: Worst case a returning visitor's browser will start a new full handshake, no error interstitial will appear.

**Comment by mholt** [comment]
Excellent guide. This would be good for anyone new to Go projects to contribute to.

There may be some guidance/discussion needed about some details, so whoever picks this up, feel free to ask questions and submit a pull request -- there's no shame or harm in iterating on a pull request!
