### ISSUE TITLE
UX: Graceful reload inside a docker container

### ISSUE THREAD

**Issue by jordic** [mholt/caddy#717]
My use case: I have caddy inside a docker container, proxing requets to some other containers, and serving statics from volumes. The issue is that I can't force caddy reload the config, and this, derivates to another issue.

If I try to send a signal to caddy, it handles the reload, but when it tries to restart, the container dies. I suspect this is due the nature of container (it detects a died PID 1, and stops it). I also tried to workaround this, using dumb-init (https://github.com/Yelp/dumb-init). But also doesn't work. 

The second issue related to this, is that, if can't handle the caddy reload, I can't relay on the caddyfile validation, and I end up with an unusable caddy (because the config file is wrong)

What can we do, to address this: Perhaps enable a validation mode (like -v nginx) that allows to validate a caddyfile prior to restart the caddy container.

I also found on tip, some kind of inprocess reload (The process don't get killed, and only the config is reload and restarted), perhaps is a workaround, but as it seems to me, that actually, if you force a reload, this way, this feature still lacks, the caddyfile validation logic.

**Comment by 5an1ty** [comment]
That would be fairly simple to do. Start a webserver in node.js as your PID 1 and use it to start and stop caddy:

https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback

With that simple web app you could also reload, edit the caddyfile, show logs, ...

**Comment by mholt** [comment]
I don't want to add another command line flag; let's just make the in-process reload perform a caddyfile validation before it stops and restarts.

**Comment by jordic** [comment]
This sounds good!

**Comment by tpng** [comment]
It seems in case of invalid Caddyfile on reload, Caddy will just keep running with the old Caddyfile and log that reload failed, so it is not possible to end up with a invalid state.

**Comment by tpng** [comment]
Oh, the current check is only on the file format, so if there are mis-configuration then it is possible to have a zombie Caddy on in-process reload.

**Comment by mholt** [comment]
@tpng Just to clarify, does your commit resolve the zombie problem on mis-configuration?

**Comment by tpng** [comment]
@mholt Yes, the commit was to fix the zombie issue on mis-configuration by restarting Caddy with the previous config.

**Comment by mholt** [comment]
That's excellent. I think we can close this now.

**Comment by jordic** [comment]
;)
