### ISSUE TITLE
Certificate download and generation

### ISSUE THREAD

**Issue by jordic** [mholt/caddy#718]
In my use case, I have up to 10 virtualhosts, per caddy instance... and one anyoing thing i found, is that when I add a new domain, (and it misses the certs) caddy is not fully started till it gets the new cert.. This derivates to a worst situation, if caddy files to get the cert (normally because the DNS is still not propagated) and leaves an unusable caddy instance.

What can be done? Not sure at all, I still not digged to much on the source of this parts, but I think, that caddy doesn't fully start till it gots all certs. Is this the case? Should I look at something else? Any good idea on how to workaround this case?

**Comment by mholt** [comment]
I'm not sure what you mean; if Caddy fails to get a cert during reload, it just stops the reload and continues to run as normal. Can you be more specific? Or post some log output?

**Comment by jordic** [comment]
It's not at reload, its at first load ...

**Comment by mholt** [comment]
Okay. You said it "leaves an unusable caddy instance" but if Caddy fails to get a cert at startup, it exits. Is it not exiting for you?

**Comment by jordic** [comment]
I think not... I think it keeps tring to got the cert, but it doesn't full start. (Leaving the rest of the vhosts, inusables)

**Comment by mholt** [comment]
Show me some log output please. `-log stderr` will do.

**Comment by jordic** [comment]
Yeah... finally I understand what's happening... 
I launch containers with --restart always .. and caddy stops.. but, docker tries to restart it in loop... for this reason I have the feeling that is running.. (I'm just doing docker logs on it... ).

I'm still not happy with this, because I don't have any way (programatically) to ensure that the configuration is valid. (prior restarting the container)

Also as a UX, I think that stop the service because caddy can't get a cert for a virtual host is not the best choice.. (It makes manage domain migrations a pain). Could be possible, if something fails on a virtual host (like a cert, a domain is not fully propagated)... to start the rest discarding the failed? Or is too complicated?

**Comment by mholt** [comment]
No, we're not going to do that. See #642 for a related discussion.

Sorry about the misconfiguration issues, but frankly that's something you're going to have to fix. We can track the progress of verifying the Caddyfile config in your other issue, #717.

**Comment by jordic** [comment]
Ok, thanks for the patience :)
I will try to look for a new solution, perhaps cert creation and renewal out of the http service. I can't leave a container running outside and not have the guarantees that if it's destroyed it will rerun again ( on the worst case with an expired cert). If you have any ideas on how to solve the problem I will apreciate them.

**Comment by mholt** [comment]
No problem :) Can't you create a volume or something so that the files are preserved through restarts?

**Comment by jordic** [comment]
This is already done. The problem is with multi hosts. If someone deploys a new site with a wrong config/or a not fully propagated domain it hangs all the vhosts running on the host. If this is a caddy acting as a lb and ssl termination doesnt seem aceptable.. Perhaps deploys a caddy per vhost and put an haproxy infront... :/ but this seems too complicated...

**Comment by mholt** [comment]
Okay. Well, make sure the config is correct and we'll look into that other issue before too long, to help handle that situation better.
