### ISSUE TITLE
Markdown: 500 for YAML metadata

### ISSUE THREAD

**Issue by mschoebel** [mholt/caddy#72]
I played around with the markdown middleware:

Template (`default.html`):

```html
<html>
  <head>
    <title>{{ .title }}</title>
  </head>
  <body>
    {{ .markdown }}
  </body>
</html>
```

Caddyfile:

```
0.0.0.0:8000

markdown / {
    ext .md
    template default default.html
}

errors error.log
log access.log
```

Test markdown file `test_yaml.md`:

  ```markdown
  ---
  template: default
  variables:
  - title: Test
  ---

  # Headline
  Lorem ipsum dolor sit amet ...
  ```

Result when accessing `http://localhost:8000/test_yaml.md` is `500 Internal Server Error`. There is an entry in `error.log` saying: `[PANIC /test_yaml.md] src/github.com/mholt/caddy/middleware/markdown/process.go:66 - assignment to entry in nil map`.

The other formats (JSON, TOML) work as intended.

**Comment by mholt** [comment]
(Known issue - the line number in the panic message is +2 the actual, so line 64 is actual source of panic.)

I thought I fixed this with commit 8ea98f8cced70bffa8a9c7b6e13cfde81b950498 - have you pulled the latest recently?

**Comment by mschoebel** [comment]
Unfortunately, I get the described effect with the latest HEAD ...

I added debug statements to the `load` method (`metadata.go`) ...

```go
func (m *Metadata) load(parsedMap map[string]interface{}) {
	fmt.Printf("-- %v\n", parsedMap)
	if template, ok := parsedMap["title"]; ok {
		m.Title, _ = template.(string)
	}
	if template, ok := parsedMap["template"]; ok {
		m.Template, _ = template.(string)
	}
	if variables, ok := parsedMap["variables"]; ok {
		fmt.Printf("-- %v\n", reflect.TypeOf(variables))
		vars, ok := variables.(map[string]interface{})
		m.Variables = vars
		fmt.Printf("-- %v - %v\n", vars, ok)
	}
}
```

... and get the following output:

(YAML)
```
-- map[template:default variables:[map[title:Test]]]
-- []interface {}
-- map[] - false
```

(TOML)
```
-- map[template:default variables:map[title:Test]]
-- map[string]interface {}
-- map[title:Test] - true
```

` yaml.Unmarshal` (in `Parse` of `YAMLMetadataParser`) seems to return something unexpected.

I might have some more time tomorrow for more debugging.

**Comment by abiosoft** [comment]
Thanks for testing this out.

I have seen the issue, the fix should be out soon.

Firstly, the YAML syntax used for variables `-` is  for an array and not an object. Only indentation is the requirement for a nested objected.

Should be 
```
 ---
  template: default
  variables:
    title: Test
  ---
```

Secondly, the yaml package decodes into a `map[interface{}]interface{}` and I was assuming a `map[string]interface{}`.

Thanks.

**Comment by abiosoft** [comment]
@mschoebel The fix has been merged. Let us know if it works now.

Thanks.

**Comment by mschoebel** [comment]
Works. :+1:

YAML is weird.
