### ISSUE TITLE
Caddy behind ELB - how to redirect http to https

### ISSUE THREAD

**Issue by jswierad** [mholt/caddy#728]
Hi;

Setup as mentioned.
ELB monitors EC2 instance on port 80 (caddy is running on 80 only) using /monitor 
I want to force caddy to redirect all http traffic to https (I'm doing ELB ssl offloading)

Is that somehow possible?

Edit:
I've also tried to run caddy on port 80 and 443 to make this ssl magic, but it doesn't seem to work when I'm behind ELB...

**Comment by mholt** [comment]
Caddy automatically sets up HTTP->HTTPS redirects unless you manually define a HTTP site. So this Caddyfile:

```
example.com
```

will get redirected to https:// but this one:

```
http://example.com
```

will not.

As far as getting a certificate behind a load balancer, as described [here](https://caddyserver.com/docs/automatic-https):

> Load balancing
> If Caddy is behind a load balancer, it may have trouble validating the domain and obtaining certificates. It is your responsibility, then, to ensure SSL certificates are obtained and properly set up on all machines.

A future release of Caddy will support the DNS challenge which should work behind load balancers, you just have to provide DNS provider credentials through env variables.

FWIW, a lot of people just use Caddy as their load balancer and haven't reported any major issues.

**Comment by jswierad** [comment]
Thanks for quick response!

In my case I just need to use ELB in front of my ec2; Given by the bigger infrastructure around...

This is my Caddyfile:

```
:80
gzip
proxy / localhost:8080 {
    except /doc /html /css /env
}
proxy /env localhost:8090
markdown /doc {
    template doc/default.html
}

```
Is this gonna redirect http to https automatically? No.
As being said in docs - I need to run caddy at port 80 and 443 to make it happen, but having issues with obtaining certs because of ELB.

I was trying to look at redir or rewrite, but it doesn't seem to bring me help...

**Comment by mholt** [comment]
On that same documentation page, automatic HTTPS is only enabled if:

> The port is not explicitly 80

So replace :80 with the name of your site like example.com instead. You'll need to make sure that ELB points to that particular EC2 instance so that the ACME server can reach it, so Caddy can solve the certificate challenge.

**Comment by jswierad** [comment]
As mentioned before - I've tried that.

Then I got this error:

```
Activating privacy features...2016/04/05 21:02:12 [terribletest.sanomaservices.nl] failed to get certificate: acme: Error 0 - urn:acme:error:connection - Could not connect to http://terribletest.sanomaservices.nl/.well-known/acme-challenge/0qoKYuEccj5hsBosP6Vz1KXq9FcznxtYsEEVQVqh3OQ
Error Detail:
	Validation for terribletest.sanomaservices.nl:80
	Resolved to:
		52.49.25.83
		52.31.216.114
	Used: 52.49.25.83
```

**Comment by mholt** [comment]
Is 52.49.25.83 your load balancer? And is your load balancer forwarding to that particular EC2 instance where Caddy is running the cert challenge?

**Comment by jswierad** [comment]
52.49.25.83 is NAT address for outgoing traffic from this instance. Again, given setup.

Load balancer of course is forwarding to this EC2. That works, since if I run caddy on port 80 only I can access it via ELB using mentioned domain name (which is just a CNAME of ELB itself)

**Comment by mholt** [comment]
So it's working for you now then?

**Comment by jswierad** [comment]
No, it's not.
I just get error pasted above when I start caddy. So it fails on cert challenge. 

What is working tough - when I run caddy only on port 80, then I can access it via Load Balancer, so the configuration on ELB level is correct. But in this scenario I still don't know how to fix http->https redirects ;)

**Comment by mholt** [comment]
If you can only access Caddy on port 80 even if you're serving port 443, I think your network must be misconfigured somehow; but I don't use ELB so I wouldn't know...

You can, of course, set up a [redirect](https://caddyserver.com/docs/redirect) manually:

```
http://example.com {
    redir https://example.com
}
```

**Comment by jswierad** [comment]
This manual solution looks like it might work, but there is one "but": The /monitor call fired by Load Balancer to do the health check will fail. It expects 200, it will not get 200 in this case.

Is it possible to do something like exclude for such a redir? So I can exclude /monitor from this redir.

**Comment by mholt** [comment]
I don't believe so, sorry. That's really unfortunate that ELB won't follow a redirect to a secure page. I would file an issue with AWS about that. Thanks for your question!

**Comment by elliotdickison** [comment]
For anyone landing here looking for how to do http->https redirects with Caddy V2 behind an SSL-terminating proxy/balancer, here's the magic potion:

```
@insecure {
  header X-Forwarded-Proto http
}
redir @insecure https://{host}{uri} permanent
``
