### ISSUE TITLE
ETag (#707)

### ISSUE THREAD

**Issue by elcore** [mholt/caddy#729]
I don´t want to be nit-picking, but should we rename "Etag" to "ETag" in middleware/fileserver_test.go and move from a weak ETag validator [W/"5703b45f-ab5"] to a strong ETag validator ["5703b45f-ab5"]

cc @mholt, @jupiter, @weingart

#707 

P.S.: I already "fixed" it locally

**Comment by weingart** [comment]
I thought that the Etag -> ETag rename was done.  If not, yes, that should be done.

I'm ok with either weak/strong.  Do you have a good reference as to the practical difference between the two as commonly implemented in browsers?

**Comment by elcore** [comment]
Hello @weingart 

> I'm ok with either weak/strong. Do you have a good reference as to the practical difference between the two as commonly implemented in browsers? 

No (I don´t know it), but it´s common to use the strong ETag validator (NGINX, Apache)

> I thought that the Etag -> ETag rename was done. If not, yes, that should be done.

It is just nit-picking e.g. `etag := responseRecorder.Header().Get("Etag")`

**Comment by jupiter** [comment]
We are using a weak validator, i.e. will not be a byte-for-byte guarantee, and correctly reflecting this as per the [RFC](https://tools.ietf.org/html/rfc7232#section-2.3). If you can find a reference to why the other implementers (Nginx/Apache), I think we should change it.

@weingart is correct that we did change the key when setting of the header, see https://github.com/mholt/caddy/blob/master/middleware/fileserver.go#L134. However, the header key is always specified as "Etag" in the Go core http module, see https://github.com/golang/go/blob/master/src/net/http/fs.go#L300, and changing the casing has no effect on how it is output to the client. For the sake of consistency I am more inclined to want to change it back to the way it is in the core Go http module.

**Comment by elcore** [comment]
> We are using a weak validator, i.e. will not be a byte-for-byte guarantee, and correctly reflecting this as per the RFC. If you can find a reference to why the other implementers (Nginx/Apache), I think we should change it.

I do not have any reference, sorry.

> However, the header key is always specified as "Etag" in the Go core http module, see https://github.com/golang/go/blob/master/src/net/http/fs.go#L300, and changing the casing has no effect on how it is output to the client. For the sake of consistency I am more inclined to want to change it back to the way it is in the core Go http module.

If it´s specified as "Etag" in the Go core http module thank it should be ok -> It´s just the matter of style (as I said: "It is just nit-picking (on a high level)")

**Comment by mholt** [comment]
Currently the ETag is based on size and last-modified date; we're not hashing the contents (slow) so I think weak ETag makes sense, doesn't it?

As far as casing goes, I've mainly seen "ETag" out in the wild. HTTP headers are case-insensitive so I'm not worried about Go using "Etag".

**Comment by elcore** [comment]
> Currently the ETag is based on size and last-modified date; we're not hashing the contents (slow) so I think weak ETag makes sense, doesn't it?

It makes sense, but strong ETag too. According to RFC 7232 they should be the default (we just need to remove the W/), doesn't it?

**Comment by mholt** [comment]
But can we guarantee byte-for-byte correctness?

**Comment by elcore** [comment]
> But can we guarantee byte-for-byte equality with our etag?

NGINX and Apache ETag´s are also based on size and last-modified date -- So, I would say yes.

**Comment by mholt** [comment]
@elcore You are being helpful. I want to understand this better and make sure we do it right.

NGINX and Apache may use size and last-modified, but look at letsencrypt.org's ETag header: `ETag:W/"56fe7e46-46f5"` - they use NGINX.

**Comment by elcore** [comment]
> NGINX and Apache may use size and last-modified, but look at letsencrypt.org's ETag header: ETag: W/"56fe7e46-46f5" - they use NGINX.

OK -- I never saw NGINX using weak ETag -- I would say we should close this issue, weak ETag´s hurt no one.
