### ISSUE TITLE
client_max_body_size directive

### ISSUE THREAD

**Issue by looterz** [mholt/caddy#733]
Is there a caddy equivalent of nginx's client_max_body_size parameter? I need to set it to infinite to accept large git objects over https.

**Comment by mholt** [comment]
Actually I do not believe there is right now. We should implement one, however (using [MaxBytesReader](https://golang.org/pkg/net/http/#MaxBytesReader)) and make it configurable from the Caddyfile. At that point, though, this discussion merges with #79 so I'll close this one.

So for your case, there isn't anything you need to do right now. But stay tuned for changes on that in the future!

**Comment by looterz** [comment]
Thanks for looking into it, look forward to any updates on #79.
