### ISSUE TITLE
Excluding subdirectories from FastCGI

### ISSUE THREAD

**Issue by joepie91** [mholt/caddy#734]
It doesn't currently appear to be possible to 'exclude' a subdirectory from a FastCGI setup. This would, however, be quite useful for security purposes; that is, ensuring that something uploaded by a user cannot be executed.

For example, it might look something like this:

```
example.com {
        root /var/www
        log /var/log/caddy/access.log
        errors /var/log/caddy/error.log
        fastcgi / /var/run/php-fpm.sock {
                exclude /user_uploads
        }
}
```

This way, *even* if a user somehow manages to upload a PHP file to `/user_uploads` (assuming eg. an image uploading script), they will not be able to execute malicious code.

**Comment by mholt** [comment]
You mean [like this](https://github.com/mholt/caddy/commit/e7001e653841811ca752989c519551a4f1bf6871)? ('except' not 'exclude')

Will be available at the next release.
