### ISSUE TITLE
Proxy question about drain connections and sticky ssessions

### ISSUE THREAD

**Issue by fmpwizard** [mholt/caddy#736]
Two part question:

1- Does caddy support sticky sessions?
I'm running two or three instances of the same application, but for reasons outside the scope of this question, if  a user logs in to server 1, they should stay there for the rest of their session.

2- Does caddy support the idea of draining connections to a specific backend?
The use case is, I'm about to deploy a new version of our app, I spin server 4, it starts accepting connections, now I need to tell caddy to stop sending new users to server 1 and 2, once server 1 and 2 have no more users, I can deploy the new version of the app to those two servers.

This may fit more in a load balancer directive, but often times a proxy and load balancer end up the same project.

Thanks

**Comment by mholt** [comment]
Hmm, question 1 seems more a problem for an applications server to solve. Caddy is primarily a web server. Caddy doesn't really have a notion of sessions or state in that sense.

As for two, you can remove servers 1 and 2 from your proxy directive and perform a graceful restart; new connections will not be sent to those backends.

**Comment by fmpwizard** [comment]
thanks for your answers, I'll close this now.
