### ISSUE TITLE
Auto SSL not working

### ISSUE THREAD

**Issue by meepeek** [mholt/caddy#743]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.2

#### 2. What are you trying to do?
I try auto ssl feature

#### 3. What is your entire Caddyfile?
```text
test.me
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
┌─(/home/thee/shared)────────────────────────────────────────────────────────────────────────────────────────────────────────────────(ROOT@ubuntu:pts/0)─┐
└─(16:45:40)──> ./caddy                                                                                                                    ──(Tue,Apr12)─┘
Activating privacy features...2016/04/12 16:45:53 [test.me] failed to get certificate: acme: Error 0 - urn:acme:error:unauthorized - Error parsing key auth
orization file: Invalid key authorization: 73 parts
Error Detail:
        Validation for test.me:80
        Resolved to:
                92.52.105.162
        Used: 92.52.105.162
        Validation for www.test.me:80
        Resolved to:
                92.52.105.162
        Used: 92.52.105.162
        Validation for www.test.me:443
        Resolved to:
                92.52.105.162
        Used: 92.52.105.162
```

#### 5. What did you expect to see?
server started with https

#### 6. What did you see instead (give full error messages and/or log)?
As in #4

**Comment by abiosoft** [comment]
You need to use a valid domain name that belongs to you.
