### ISSUE TITLE
Conditional Environment Variables

### ISSUE THREAD

**Issue by wienczny** [mholt/caddy#745]
It would be great if you could set fastcgi environment variables based on the request. 
Something would imagine something like [nginx map directive](http://nginx.org/en/docs/http/ngx_http_map_module.html)

**Comment by mholt** [comment]
You can set env variables using the `env` keyword in the `fastcgi` directive. Does that not do what you want?

**Comment by wienczny** [comment]
You could use env but you have to copy a lot of configration. Many PHP toolkits are using environment variables to select between development, production and staging. If you want to deploy all of those on the same host using dev.host.com staging.host.com and www.host.com you would have to copy the configuration and change hostname and selected application environment. Imports don't work because the must be outside of server blocks. They might work if they had parameters like 

    import vhosts/vhosttemplate host=some.host stage=prod foo=bar ...

Alternatively I suggest to allow a mapping between placeholders and constants.

**Comment by mholt** [comment]
Hmm, what about using *real* env variables to set your environment? Would this work?

```
$ export STAGE=prod
```

In the Caddyfile (in the fastcgi directive):
```
env stage {$STAGE}
```

**Comment by wienczny** [comment]
This does not work if you want to run all environments at the same time.
Another example might be a single CMS installation with multiple websites  that are choosen by environment variables.

**Comment by mholt** [comment]
@wienczny Sure it does:

```
$ STAGE=prod caddy -conf=...
$ STAGE=dev caddy -conf=...
```

Or am I misunderstanding something?

**Comment by wienczny** [comment]
Aren't you running two instances this way? Do both share port 80 and 443?

**Comment by mholt** [comment]
Yes, it does run two instances. So you want to run both a production and dev environment on the same port?

**Comment by wienczny** [comment]
It's just an example. There are usecases where this can be a valid option. I really want to run Magento stores that use environment variables to distinguish different store views. These could have different languages or products. This is useful if you have .com for english and .de for german for example.There could be different domains for retail and b2b, too. I just thought Magento's usecase was too difficult to explain.

**Comment by mholt** [comment]
If your needs are that complex then perhaps Caddy is not a good fit, we want to keep things simple/easy for the user as much as possible. The Caddy philosophy is that the complexity of a web app should be deferred to the app itself, not in the web server... we'll only bend so far, and programming conditionals into the Caddyfile is too far IMO.

Thanks for the question!
