### ISSUE TITLE
Caddy not running on RPi B+

### ISSUE THREAD

**Issue by adnidor** [mholt/caddy#748]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?

0.8.2 (from the AUR)

#### 2. What are you trying to do?

Start caddy

#### 3. What is your entire Caddyfile?

nonexistent

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

On a Raspberry Pi B+, running Arch Linux ARM

#### 5. What did you expect to see?

Some messages indicating that the program is running

#### 6. What did you see instead (give full error messages and/or log)?

`Illegal instruction`

**Comment by wmark** [comment]
The error message is caused by the provided binary issuing instructions not known to your CPU.

Could you please share the outputs of these commands with us here? I assume you are running GNU/Linux:

```bash
uname -srpio

lscpu

cat /proc/cpuinfo
# please remove any duplicate but the last cpu/processor block
```

**Comment by mholt** [comment]
Is your Raspberry Pi ARM v6? You probably downloaded it with a different ARM version. The download link looks like this:

```
https://caddyserver.com/download/build?os=linux&arch=arm&features=
```

You need to add the ARM version:

```
https://caddyserver.com/download/build?os=linux&arch=arm&features=&arm=6
```

Right now we just build for ARM v7 by default; I could probably have that clarified on the download page.

**Comment by cemk** [comment]
Yep, just checked; Raspberry Pi 2 and Pi 3 run the default version, while Pi 1 (A/A+/B/B+) and Pi Zero need the ARM v6 build.

**Comment by mholt** [comment]
Cool. That'll do it, and I'll update the download page soon to show the ARM version.

**Comment by suiluj** [comment]
@mholt could you please add a compiled armV8 version for raspberry pi 3 users? Thank you.

**Comment by mholt** [comment]
The website and build server will be updated for the 0.9 release which is probably when I'll get around to doing that. In the meantime you can add `&arm=8` in the download link to get ARMv8.

**Comment by suiluj** [comment]
i tried `&arm=8` before but i still get the response `arm version not supported`

**Comment by wmark** [comment]
Does `&arm=aarch64` or `&arm=arm64` work?

**Comment by suiluj** [comment]
no not for me. i think these versions are just not precompiled yet

**Comment by mholt** [comment]
Oh, duh, that's what I get for responding to an issue before my brain's awake.

Use `arch=arm64`, not `arm=8`

**Comment by suiluj** [comment]
ah thanks a lot :)

**Comment by wmark** [comment]
Erm, so why does this all of the sudden work since my comment from one hour ago?

**Comment by suiluj** [comment]
@wmark i had to change the `arch` parameter to `arm64`, and leave the `arm` empty

**Comment by wmark** [comment]
I see, I've had the right value but the wrong key. Thanks!

**Comment by gregbenner** [comment]
I'm not following 100%, what is the exact build/download url that's working for folks for Raspberry pi?

**Comment by elcore** [comment]
Hello @gregbenner,

this should work: https://caddyserver.com/download/build?os=linux&arch=arm&features=

**Comment by mholt** [comment]
Older Raspberry Pis have ARMv6, newer ones have ARMv7, be aware of which yours is.

**Comment by gregbenner** [comment]
Thanks @elcore works for me on a new Raspberry Pi Zero W / Raspian
