### ISSUE TITLE
Global load balance feature request

### ISSUE THREAD

**Issue by meepeek** [mholt/caddy#750]
Since it was not in the document, I think this is a feature request.

I saw proxy load balancing feature but there was no location-base policy. It would be nice to have one in the future.

**Comment by mholt** [comment]
Location-base policy? What is that?

**Comment by elcore** [comment]
@mholt 

> Location-base policy? What is that?

Redirect client to the closest server based on geolocation (am I right @meepeek?)

**Comment by meepeek** [comment]
Yes that what I meant. I thought it was the load balance to do the thing to do.

**Comment by stp-ip** [comment]
Even if it might be possible to let caddy proxy to the closest server all the traffic is still routed through caddy therefore the request might even be slower.

The solution for something like this would probably be geolocation over dns.

DNS from Europe -> caddy Europe -> proxyto Europe backend server
DNS from US -> caddy US -> proxy to US backen server

**Comment by meepeek** [comment]
Seems this feature might not be useful. @stp-ip Thanks for additional explanation. I will look into the DNS as you guys advises.

I am closing the thread.

**Comment by bscott** [comment]
@meepeek  @mholt Sometimes DNS Providers don't provide all of the Locations you wish to route on, especially if your using DNS from DNSSimple or small providers and not using Route53 DNS which provides the best Geo Location routing that I've seen , it would be nice if Caddy supported GEO Routing based on Source IP using the MaxMind Database. I believe a Addon can easily be created to support this.
