### ISSUE TITLE
Wildcard support for error pages

### ISSUE THREAD

**Issue by stp-ip** [mholt/caddy#752]
As far as the documentation goes one can set error pages for all errors above 400 codes. It would be great to have a catch all error file and in addition specific error pages afterwards. Something along the lines of:

* generic_error.html  
500 500_error.html  
502 502_error.html  
429 429_error.html  

This would serve the specific pages on error 500, 502 and 429, but the generic page on evey other error.

**Comment by mholt** [comment]
A default error page is probably fine; but I'm not sure I like the idea of stringing them all together on a single line.

**Comment by stp-ip** [comment]
And the singe line "idea" was just me not formatting the issue right. Sorry for that.

**Comment by evvvvr** [comment]
I`d like to take this one

**Comment by mholt** [comment]
Thanks @evvvvr! @stp-ip, this is now implemented and will go out with the next release. Note that it works like:

```
errors {
    * default_error.html
}
```
