### ISSUE TITLE
Set max_fails default to 0 on single upstream

### ISSUE THREAD

**Issue by stp-ip** [mholt/caddy#754]
As #667 showed it might be beneficial to to use max_tries set to 0 as a default, when only one upstream is available. Marking a single upstream as down for 10s due to one bad request seems too conservative.

**Comment by mholt** [comment]
We're finding that this can have very adverse side-effects (see #784 and #782).

**Comment by nemothekid** [comment]
The default behavior is to try backends for 60 seconds (essentially infinite loop for 60 seconds). If `max_tries` is set to 0, it might make most sense to not bother with retrying connections and just return GatewayUnavailable once the backend fails.

**Comment by mholt** [comment]
^ That's a great idea I think. I was just about to suggest getting rid of that 60 second loop entirely, but breaking out of it only in the case of max_fails=0 is much more pragmatic.

**Comment by jleclanche** [comment]
We just got bit by that during some load testing, FWIW. We have load balancing set up outside of caddy (using amazon ELB), and a single request failure would cause *really weird* behaviour where requests to the hostname in question would be 502'd immediately, but requests using a different host header would be fine.

A `max_fails` default of 1 is *way* too conservative IMHO. If setting it to 0 by default is not an option, I would recommend at the very least bumping it up to 2.

**Comment by mholt** [comment]
I think this is addressed in #1135 because of new default values and slightly different logic. (Feel free to report back if it's not)
