### ISSUE TITLE
FastCGI path doesn't seem to be very restrictive

### ISSUE THREAD

**Issue by ShaRose** [mholt/caddy#758]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.2

#### 2. What are you trying to do?

Make it so that FastCGI will only be used for index.php: All other php files should print text.

#### 3. What is your entire Caddyfile?

```
img.sharo.se {
        tls ShawnAndrewRose@Gmail.Com
        root /opt/img.sharo.se
        fastcgi /index.php /var/run/php5-fpm.sock php
        log stderr
        errors stderr
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Running via upstart script as follows:

```
description "Caddy Server"
author "ShaRose"

start on runlevel [2345]
stop on runlevel [016]

setuid caddy
setgid caddy
respawn
respawn limit 10 5
limit nofile 200000 200000
env HOME=/opt/caddy
script
        cd /opt/caddy
        exec /opt/caddy/caddy -agree -cpu 75% -conf=/opt/caddy/Caddyfile -pidfile=/opt/scripts/pids/caddy.pid
end script
```

#### 5. What did you expect to see?

Tested via generic phpinfo file in 4 locations, and expected all 4 to print the source code.

```
phpinfo.php
INDEX.php
index.php.phpinfo.php
index.phptest/phpinfo.php
```

#### 6. What did you see instead (give full error messages and/or log)?

The last 2 (index.php.phpinfo.php and index.phptest/phpinfo.php) executed the php code, and showed the phpinfo page.

(Do I really need to paste 4 http 200 logs?)

But it seems like caddy only seems to say "Does it start with this?" and if it does, runs the code: While in 99% of environments this is fine, there should be some way to be more restrictive, to the point of specifying a single file or a single folder. For example, in the fastcgi page, it gives this:
> Forward all requests in /blog to a PHP site (like WordPress) being served with php-fpm:
> `fastcgi /blog 127.0.0.1:9000 php`

But one wouldn't expect a file like /blogger/whatever.php to execute with that. (I didn't actually test setting it to a folder, but I can assume it'd do it from the behavior tested)

I'd assume that if I set to /blog and there's a folder named /blog, that anything in that folder is ok: but not a file named blogger.php. Which it seems it will.

**Comment by mholt** [comment]
Hi, thanks for the report.

This isn't a bug, as this is consistent with the path matching described in [the docs](https://caddyserver.com/docs/caddyfile) (bottom of page).

If you want to match a directory specifically, suffix your base path with a `/`, in other words, `/blog/`.

**Comment by ShaRose** [comment]
Yeah, but there doesn't seem to be a way to match a specific FILE, not just a directory. (Also the fastcgi doc page should be updated to /blog/)

**Comment by mholt** [comment]
The Caddyfile is agnostic to what files exist on your system when it comes to path matching.

We should change the documentation to include the forward slash, you're right.

If you don't mind me asking, why do you have files called `index.php.phpinfo.php` and `index.phptest/phpinfo.php`? Part of the Caddy design is that it encourages using an elegant file/folder structure for your site.

**Comment by ShaRose** [comment]
It was kind of a "Hmm, I wonder if that actually works" moment of trying it out. And upon bringing it up on irc, a few people told me to submit a bug report just in case.

**Comment by mholt** [comment]
Ahh, gotcha :smile: Thanks for being thorough and taking the time to do that! I've updated the docs page locally so it will be deployed in the future.

Feel free to comment if there's anything else.
