### ISSUE TITLE
Browse: Internal Server Error

### ISSUE THREAD

**Issue by elcore** [mholt/caddy#767]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.2 | Caddy build from master

#### 2. What are you trying to do?

Running Caddy with browse enabled

#### 3. What is your entire Caddyfile?
```text
domain.com {
        root /var/www/html/

        tls me@domain.com {
                protocols tls1.2 tls1.2
                ciphers ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256
        }

        header / {
                Content
        }

        log /var/log/caddy/access.log {
                rotate {
                        size 100
                        age  14
                        keep 10
                }
        }

        errors {
                log /var/log/caddy/error.log {
                        size 50
                        age  30
                        keep 5
                }
        }

        browse /

        fastcgi / unix:/var/run/php/php7.0-fpm.sock php
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Ubuntu Wily (systemd service)

/usr/sbin/caddy -agree=true -conf=/etc/caddy/Caddyfile -pidfile=/var/run/caddy/caddy.pid -log=stderr

#### 5. What did you expect to see?

no errors with master

#### 6. What did you see instead (give full error messages and/or log)?

500 Internal Server Error

`17/Apr/2016:17:21:40 +0000 [ERROR 500 /linux-dash/] Directory contains index file, not browsable!`

**Comment by wmark** [comment]
Thrown in https://github.com/mholt/caddy/blob/c05c5163e293c92f7e5562df558fe955c7075f7a/middleware/browse/browse.go#L186-L193
with https://github.com/mholt/caddy/blob/c05c5163e293c92f7e5562df558fe955c7075f7a/caddy/setup/browse.go#L22

Introduced in https://github.com/mholt/caddy/commit/4c642e9d3c8ae382c32421462e9f163110e8f621

---
Setting ```IgnoreIndexes``` cannot be configured and is not documented.

**Comment by wmark** [comment]
You have configured both on the same scope:
```
browse /
fastcgi / …php…
```

Only the first as listed in (see ↓) will serve requests to / and below.
https://github.com/caddyserver/buildsrv/blob/e026304d4c4b9f22fdf76624e4b789eab23ab8fb/features/registry.go

Said index file is an actual file in your ```/var/www/html```.

**Comment by mholt** [comment]
Wow, somehow I hadn't even noticed that IgnoreIndexes thing O.o ... or I forgot completely about it.

But I have not seen this error before, I need to go back and review this. @hacdias do you remember what this was for?

**Comment by wmark** [comment]
We need to:

 - [ ] issue an internal redirect if an index exists and the setting is *false* (else the usual directory listing will appear)
 - [ ] create a way to set/unset it
 - [ ] include the setting in the documentations

**Comment by elcore** [comment]
**UPDATE**

If browse is enabled, all directories including "/" receive a 500 Internal Server Error

`17/Apr/2016:21:16:06 +0000 [ERROR 500 /] Directory contains index file, not browsable!`

**Comment by mholt** [comment]
I wonder what changed recently that caused this to start happening? I have not yet had a chance to try your instructions to reproduce, but I haven't seen this issue before.

**Comment by wmark** [comment]
Provided no one else wants this, I will tackle this tomorrow.

@elcore What happens if you remove the offending file?

**Comment by mholt** [comment]
Caddy's browse middleware should pass-thru the request to the file server if the request path is for a directory and that directory contains an index file; in other words, browse renders the file listing if no index file is present, but it should never ever return a 500 unless there's a programmer or configuration error.

**Comment by elcore** [comment]
>  In other words, this works as intended.

Are you sure? There was no 500 Internal Server Error with 0.8.2

> @elcore What happens if you remove the offending file?

Why should I delete my index file? -- (no errors -- I renamed the file)

**Comment by wmark** [comment]
0.8.2 had a ```continue``` there. That resulted in the middleware checking for more applicable scopes — — which is redundant, because we had a matching scope in the first place, or the index would've been found again. Eventually ```Next``` was called:
https://github.com/mholt/caddy/blob/v0.8.2/middleware/browse/browse.go#L276-L280

I will file a PR to reinstal the old behaviour, which I changed.

**Comment by elcore** [comment]
@wmark thank you very much :smile:

**Comment by mholt** [comment]
Interesting, I can reproduce this, but only on some directories. Investigating.

**Comment by hacdias** [comment]
@mholt I don't remind this, but glad to hear that it's fixed! :)

**Comment by mholt** [comment]
I remember now :) It was because your hugo add-on wanted a way to show the directory listing even though it contained an index file, so it's optional for those custom implementations.

**Comment by hacdias** [comment]
Oh! :D Good then!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sem
vírus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-04-18 19:02 GMT+01:00 Matt Holt <notifications@github.com>:

> I remember now :) It was because your hugo add-on wanted a way to show the
> directory listing even though it contained an index file, so it's optional
> for those custom implementations.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mholt/caddy/issues/767#issuecomment-211504976>
>



-- 
Henrique Dias, Author at Pplware
@hacdias <https://twitter.com/hacdias> | henriquedias.com | fb.com/hacdias
