### ISSUE TITLE
Proxy subdomains 

### ISSUE THREAD

**Issue by benno208** [mholt/caddy#771]
I don't think that is it a bug. But I can't find a good example for this use case.

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.2

#### 2. What are you trying to do?
Proxy subdomain to different servers

#### 3. What is your entire Caddyfile?
```text
:443
proxy subdomain.example.de/ someserver:8080 {
  	proxy_header Host {host}
	proxy_header X-Real-IP {remote}
	proxy_header X-Forwarded-Proto {scheme}
}
proxy subdomainA.example.de/ someserver:8000 {
  	proxy_header Host {host}
	proxy_header X-Real-IP {remote}
	proxy_header X-Forwarded-Proto {scheme}
}
tls {
	max_certs 10
}
log /var/log/caddy.log
gzip
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
As a Docker container linked with docker-compose to other containers.

#### 5. What did you expect to see?
The specified servers (someserver)

#### 6. What did you see instead (give full error messages and/or log)?
404 Not Found

**Comment by mholt** [comment]
You want something like this instead:

```
subdomain.example.de {
    proxy / someserver:8080 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log /var/log/caddy.log
    gzip
}

subdomainA.example.de {
    proxy / someserver:8080 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log /var/log/caddy.log
    gzip
}
```

**Comment by benno208** [comment]
Now I get the following error:
``
Parse error: Unknown directive subdomain.example.de
``

**Comment by benno208** [comment]
Okay, I got it. Thanks!
