### ISSUE TITLE
Laravel Nginx Configuration For Caddy Webserver

### ISSUE THREAD

**Issue by bc24fl** [mholt/caddy#775]
Team,

Many thanks for developing this exciting project.  Hopefully one of you can help me with some configuration changes needed.  I have a standard Laravel 5.1 Debian 8 installation and inside my public folder i have an app folder with a small angular js project (I only use laravel as an API backend).  

When hosted on Nginx i get the expected result when i visit http://localhost/app (Converts the URL to http://localhost/app/#/ and page displays) .  

On Caddy i get an error from Laravel NotFoundHttpException.  However if i visit http://localhost:2015/app/index.html then it displays correctly.  Given my current config for both how can i get Caddy to act as Nginx does?  

I found a similar issue here and used some of the suggestions but still cannot get it to work as expected. 

Any help would be much appreciated.

--Caddyfile version 0.8.2------------------------------------------
```
:2015
cors
root laravel/public
log access.log
errors error.log

# PHP-FPM with Unix socket
fastcgi / /var/run/php5-fpm.sock php {
  ext .php
  index index.php index.html
}

#Routing for laravel
# This will allow you to access routes like /test instead of index.php/test
rewrite {
    r .*
    ext /
    to /index.php?{query}
}
```

---nginix conf------------------------------------------------------
```
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    root /var/www/html/laravel/public;

    index index.php index.html index.htm;

    location / {
         try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri /index.php =404;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

**Comment by abiosoft** [comment]
Try this. I removed redundant configs as they are the defaults.

```
:2015
cors
root laravel/public
log access.log
errors error.log

# PHP-FPM with Unix socket
fastcgi / /var/run/php5-fpm.sock php

#Routing for laravel
# This will allow you to access routes like /test instead of index.php/test
rewrite {
    to {path} {path}/ /index.php?{query}
}
```

**Comment by bc24fl** [comment]
That got me further.  I have a redirect in Laravel that if you visit / route it redirects to /app .    

On Nginx page display correctly at: http://localhost/app/ 
On Caddy page displays page but incorrectly (ie: shows angular bind variables as {{}}) and redirects me to http://localhost:2015/app 

For some reason Caddy is not adding the extra "/" at the end of the URL.  If i manually add the "/" at the end Caddy displays fine.  

Any ideas?

**Comment by abiosoft** [comment]
Hmmm. Caddy uses trailing `/` as an indicator for a directory and I am not sure if there is a way out.

**Comment by bc24fl** [comment]
I'm having a hard time understanding this, even after reading the docs:

rewrite {
    to {path} {path}/ /index.php?{query}
}

Can someone break this out in English for me?  My assumption is "to {path} {path}/" says if user visits http://url/{path} OR http://url/{path}/  (note the "/" at the end) rewrite to index.php?

**Comment by abiosoft** [comment]
`{path}` - if it exists and it is a file, return here.
`{path}/` - if it exists and it is a directory, return here.

**Comment by bc24fl** [comment]
Ok thanks.  I got it to work by forcing the trailing slash in Laravel's redirect.

Changed this
return redirect('app/');
To this:
return redirect('app/#/');

**Comment by abiosoft** [comment]
Okay. So you did a workaround inside Laravel.

**Comment by mholt** [comment]
Great! This will be helpful for others using Laravel. I don't intend to change the way Caddy handles trailing slashes, and that redirect on Laravel's side is easy enough.
