### ISSUE TITLE
SCGI support

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#776]
We had a [feature request on Twitter](https://twitter.com/nwgat/status/722797329024036868) to add SCGI support.

The [linked package](https://bitbucket.org/mjl/scgi) is very short, as well as this other one, [mlauer/gofcgisrv](https://github.com/mrlauer/gofcgisrv) -- I haven't looked into them in detail yet so I'm not sure which one we'd use, but it seems small and simple enough to add to core -- or even if we don't, the plugin would be pretty easy to write. (Spec is super short too: http://python.ca/scgi/protocol.txt) If it's really easy enough, perhaps we could just inline the ~150 lines of code for ourselves.

**Comment by sijad** [comment]
can I give it a try?

**Comment by abiosoft** [comment]
@sijad. Sure, go ahead. 👍

**Comment by mholt** [comment]
For future readers, see #787 for a WIP pull request.

**Comment by nwgat** [comment]
any progress? #787

**Comment by mholt** [comment]
Upon further consideration, let's make this a plugin. It can still be made available from the download page, of course.

**Comment by sijad** [comment]
I'm working to make plugin of it
@mholt a plugin should cover all test cases to be added to site? creating a SCGI server in go can take time

**Comment by mholt** [comment]
Yes, tests will be good. And docs will be required if we add it to the download page. I'm updating the wiki today with how to do that for Caddy 0.9.

**Comment by ZoomRmc** [comment]
Shouldn't this be reopened? As far as I understand, there's still no scgi support, as #787 stalled.

**Comment by mholt** [comment]
@ZoomRmc Since version 0.9, plugin development happens outside of Caddy, so it's not an appropriate issue for this repo. Feel free to ping @sijad about it or bring it up on the forums! https://forum.caddyserver.com

**Comment by dawidd6** [comment]
So what is the progress on this? @sijad

**Comment by dbohdan** [comment]
There is now https://github.com/Elegant996/scgi-transport for Caddy 2.
