### ISSUE TITLE
Error while doing 'go get' on Caddy package.

### ISSUE THREAD

**Issue by ioArchman** [mholt/caddy#780]
Am trying to use Caddy in my go program. When I tried fetching the package, it throws few errors preventing me to use caddy package in my program.

**Cmd executed**
```
go get github.com/mholt/caddy/caddy
```

**Issue**
```
# github.com/mholt/caddy/middleware/browse
../../github.com/mholt/caddy/middleware/browse/browse.go:279: undefined: http.MethodGet
../../github.com/mholt/caddy/middleware/browse/browse.go:279: undefined: http.MethodHead
../../github.com/mholt/caddy/middleware/browse/browse.go:281: undefined: http.MethodOptions
```
Any thoughts?

**Comment by abiosoft** [comment]
What version of Go are you running ?

Also try `-u` flag to update all dependencies as well.
```
go get -u github.com/mholt/caddy/caddy
```

**Comment by ioArchman** [comment]
Am running:  go version go1.5.1 darwin/amd64
Same is the case with -u too.
```
go get -u github.com/mholt/caddy/caddy
```

**Comment by abiosoft** [comment]
https://github.com/mholt/caddy#running-from-source
> Note: You will need Go 1.6 or newer.
