### ISSUE TITLE
Change base port of 80 and 443

### ISSUE THREAD

**Issue by Skilgarriff** [mholt/caddy#786]
Forgive me if I'm reading this incorrectly, but it seems that Caddy needs to bind to port 80 and 443 no matter what for automatic https to be enabled, even if we declare it to listen to other ports in the Caddyfile?

I'm trying to make Caddy work on a dockerfile by also running that Docker image as a non-root user. By doing this, the user does not have access to privileged ports and thus can't bind to 80 and 443. I'm wonder if there is any way to set up Caddy such that it listens on selected ports say 8080 and 4433, because with the capabilities of docker, we can reroute ports from the outside to different ports on the inside. Thus port 80 on the outside can redirect to 8080 on the inside and 4433 to 443. 

Due to the current capabilities of Docker, neither setcap nor authbind are able to solve the privileged port problem inside of the container. Seeing as how we can still have outside authorities (Let's Encrypt) ping port 80 on an container and it will redirect to a unprivileged port on the inside of the container, it would be wonderful to have this functionality to allow for more secure docker images run as non-root.

**Comment by schlypel** [comment]
set_cap can be used in docker. The limiting part is the filesystem driver. It took me a while to figure it out, but apparently aufs doesnt support the setcap. On my DO droplet i just changed it to be devicemapper et voila.
(with systemd its to be changed in the service unit (/etc/systemd/system/docker.service)
on 14.04 its in `/etc/default/docker/` add a line `DOCKER_OPTS="--filesystem-driver=devicemapper"` (or edit an existing DOCKER_OPTS line)

**Comment by mholt** [comment]
> Forgive me if I'm reading this incorrectly, but it seems that Caddy needs to bind to port 80 and 443 no matter what for automatic https to be enabled, even if we declare it to listen to other ports in the Caddyfile?

Yes, the ACME protocol requires these ports.

>  I'm wonder if there is any way to set up Caddy such that it listens on selected ports say 8080 and 4433, because with the capabilities of docker, we can reroute ports from the outside to different ports on the inside.

That'll work, and in a future version of Caddy you should be able to customize this. I'm working on the foundational changes right now in order to make that possible.

**Comment by Skilgarriff** [comment]
@schlypel I'm using Alpine-Linux for the image, and it doesn't appear to have any capabilities to use set cap as far as I can tell.

**Comment by schlypel** [comment]
@Skilgarriff I use alpine to, there is a package with the setcap utility, it is not pre installed, but a quick `apk update && apk add libcap` should do.

https://pkgs.alpinelinux.org/package/edge/main/x86_64/libcap

**Comment by Skilgarriff** [comment]
@schlypel That's extremely helpful! Thank you! When you say the limiting part is the filesystem driver, what exactly does that cause to fail? In order for me to test this fully on my image I would have to push live to my website to see if permissions are failing, so I'm a bit curious about any errors I may encounter before that happens.

**Comment by wmark** [comment]
Use **OverlayFS** if possible: ```DOCKER_OPTS="--filesystem-driver=overlay"```

… and to tell if *capabilities* had been set and copied over to your local **Docker** images:

```bash
$ find /var/lib/docker/ -name 'caddy' -exec getcap -v '{}' \;

/var/…/[layer_ID]/root/usr/sbin/caddy = cap_net_bind_service+ep
```

**Comment by Skilgarriff** [comment]
@wmark I was looking for a solution that would apply universally to anyone downloading the specific image. I think it may be a bit clunky to ask users to, on top of downloading the image, make sure they are using the correct filesystem

**Comment by wmark** [comment]
With Linux, for a process to use port <2000:

 * the process needs to have an UID ≤999 (not necessarily root!)
 * get the listening socket with the wanted port as filedescriptor (systemd, perhaps *inetd*?)
 * cap_net_bind_service+ep (that is stored on filesystem)

This is really outside of Caddy now, and about issues with Docker (unpredictable fs) or understanding of posix-like operating systems.
