### ISSUE TITLE
Multiple VHosts: Caddyserver stops completely if only one vhosts definition has errors

### ISSUE THREAD

**Issue by treviser** [mholt/caddy#789]
Is there a way to avoid that caddy server stops completely if there is an issue with a particular vhost only? For example when I want to add a new vhost for a domain I had to do a DNS change (new IP address) and the IP change is not yet fully propagated, then the TLS results in an error and Caddy completely stops, all my sites are down.

#### 2. What are you trying to do?
I do host a multi-tenant web application and I'm looking for a procedure to migrate new customers as smoothly as possible to my new environment without impacting existing customers.

#### 3. What is your entire Caddyfile?
```
imestis.ch,
www.imestis.ch { # Your url should go here..
  proxy / http://127.0.0.1:8069 { # Fill in the correct port..
    proxy_header Host {host}
    proxy_header X-Forwarded-Host {host}
    proxy_header Proto {scheme}
    }
#  proxy /longpolling http://127.0.0.1:8072 { # in case you use it
#    proxy_header Host {host}
#    proxy_header X-Forwarded-Host {host}
#    proxy_header Proto {scheme}
#    }
  gzip
  log /var/log/caddy/imestis.access.log
  errors /var/log/caddy/imestis.error.log
#  tls {
#    max_certs 100
#    }
}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Ubuntu 14.04 LTS, running as a service using upstart (see https://denbeke.be/blog/servers/running-caddy-server-as-a-service/ )
My init conf file looks like:

```
description "Caddy Server startup script"
author "Mathias Beke"

start on runlevel [2345]
stop on runlevel [016]


setuid caddy
setgid caddy

respawn
respawn limit 10 5

limit nofile 4096 4096

script
    export HOME=/home/caddy
    cd /home/caddy/
    exec /usr/local/bin/caddy -email="sysdev@twanda.com" -conf="/etc/caddy/Caddyfile" -log="/var/log/upstart" -agree
end script
```

#### 5. What did you expect to see?
I'm looking for a fail safe way to add new vhost files without Caddy stopping completely in case of an error.

**Comment by mholt** [comment]
Thanks for opening an issue! This is intended behavior, however, and I don't intend to change it.

> Caddy completely stops, all my sites are down.

Well, your sites weren't up before, either. If Caddy can't get a certificate for a domain you tell it to serve, that's an error, and it needs to be fixed rather can Caddy serving some of your sites like some sort of estranged zombie process.

**Comment by treviser** [comment]
Thanks for your reply. I do not yet understand enough about all the technical backgrounds, but from using Apache I was used to that only the corresponding website did not work when something was wrong with the vhost definition. I'm just trying to learn how I should define my process of migrating domains to my server without compromising the existing and running sites.

**Comment by mholt** [comment]
You could serve the sites without https until the domain propagates just
like you would with any other web server.

**Comment by treviser** [comment]
Would I use "tls off" then in the corresponding vhost?

**Comment by tboerger** [comment]
Just include the scheme with the domain. 
http://mydomain.com {
}

**Comment by treviser** [comment]
That's easy, thanks for the hint!

**Comment by mholt** [comment]
Yep, either will do the trick!
