### ISSUE TITLE
be more forgiving on the config layout

### ISSUE THREAD

**Issue by nwgat** [mholt/caddy#790]
make the config parser a little bit more forgiving and not freaking out if stuff is some place else
case in point the current one
```
domain.com:80 { 
        root /var/www/
        basicauth / user pass
        browse
        markdown
        gzip
        fastcgi / /run/php/php7.0-fpm.sock php
        rewrite /private { status 403 }
}
```
if the parser was a little forgiving

```
domain.com:80 { root /var/www/
        basicauth / user pass
        browse markdown gzip
        fastcgi / /run/php/php7.0-fpm.sock php
        rewrite /private {status 403} }
```

going from 9 lines down to 5! and as a added bonus it will work

**Comment by mholt** [comment]
But the second one looks ugly and is hard to read.

**Comment by klingtnet** [comment]
This would add more complexity to the parser without returning any real benefit. I agree with @mholt and think that It's more like a feature that one is forced to write clean config files, instead of saving some whitespace and make it less obvious.
