### ISSUE TITLE
.StripExt cannot be used with .URL in a markdown template

### ISSUE THREAD

**Issue by matthewp** [mholt/caddy#791]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?

0.8.2

#### 2. What are you trying to do?

`{{.StripExt .URL}}`  in a markdown template.

#### 3. What is your entire Caddyfile?
```text
localhost:5050
markdown / {
  css /styles/main.css
  template templates/main.html
  template feed templates/feed.html
}
ext .md
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy` in dev.

#### 5. What did you expect to see?

The URL to be stripped of the `.md` extension.

#### 6. What did you see instead (give full error messages and/or log)?

500 server response.

**Comment by mholt** [comment]
The URL is not a string, you'll need to do something like `.URL.Path`.

**Comment by matthewp** [comment]
Ah ok, the .URL struct is not documented I think.  

Should the .StripExt helper be able to take the URL struct? If it's a common interface I think it makes sense to.

**Comment by matthewp** [comment]
Using either .URL.String or .URL.Path (even without .StripExt) gives me a 500 error. How can I get a better error to debug?

**Comment by captncraig** [comment]
Add `errors visible` to your caddyfile.

**Comment by matthewp** [comment]
Ah, so I didn't explain my issue well enough, I am using `.URL` within a `.range` and apparently it is a string and not a URL struct.  I'll take this to gitter as this is more of a support issue than a bug (I think).

**Comment by mholt** [comment]
Using `.URL` in a `range` statement will probably not work since the context/scope changes in a range statement. Use `$.URL` to access the URL as defined from the base/root context.
