### ISSUE TITLE
OCSP stapling error

### ISSUE THREAD

**Issue by maxigas** [mholt/caddy#792]
#### 1. What version of Caddy are you running (`caddy -version`)?

    Caddy 0.8.3

    Linux bantron 3.4.108-bananian #2 SMP PREEMPT Thu Aug 13 06:08:25 UTC 2015 armv7l GNU/Linux

    Debian version 8.4

#### 2. What are you trying to do?

Get scores on SSL Server Test, especially fixing OCSP Stapling.

#### 3. What is your entire Caddyfile?
```
http://localhost, https://relay70.metatron.ai, https://maxigas.metatron.ai {
    redir /history-of-real-time-chat-protocols.html /history-of-real-time-chat-protocols/ 301
    redir /the-rise-and-fall-of-the-open-source-mobile.html /the-rise-and-fall-of-the-open-source-mobile/ 301
    redir /internet-governance-is-a-trap.html /internet-governance-is-a-trap/ 301
    log /var/log/caddy.log
    root /home/relay70/public
}

https://slides.metatron.ai {
    log /var/log/caddy.log
    root /home/slides/public
    browse
}
```
#### 4. How did you run Caddy (give the full command and describe the execution environment)?

/usr/local/bin/caddy -agree=true -email=[censored] -conf=/etc/caddy/caddy.conf

Caddy is daemon is managed by a program called `supervisor` using the following config file:

```
[program:caddy]
directory=/home/relay70/
command=/usr/local/bin/caddy -agree=true -email="[censored]" -conf="/etc/caddy/caddy.conf"
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/caddy_stdout.log
stderr_logfile=/var/log/supervisor/caddy_stderr.log
```

The domain is managed through the `pagekite` service.

#### 5. What did you expect to see?

I expect "Yes" **without comments** on this page:

https://www.ssllabs.com/ssltest/analyze.html?d=relay70.metatron.ai

#### 6. What did you see instead (give full error messages and/or log)?

This link:

https://www.ssllabs.com/ssltest/analyze.html?d=relay70.metatron.ai

Displays `OCSP STAPLING ERROR`:

```
OCSP stapling	Yes 
OCSP STAPLING ERROR: OCSP response expired on Fri Apr 15 03:00:00 PDT 2016
```

Comment: My tentative guess is that Apr 15 was when the Let's Encrypt certificate was renewed automatically by Caddy, and maybe OCSP issue started then...

**Comment by wmark** [comment]
I can confirm that an expired OCSP response has been confirmed by ssllabs.com at the time of writing. So this ticket is about *Caddy* serving lapsed OCSP responses.

**Comment by mholt** [comment]
I'm not convinced that your tests are testing what you think they are. Caddy doesn't serve SSLv3 by default (it will be removed entirely with the 0.9 release) and your cipher suites have obviously been changed but your configuration does not reflect that. I'm not even 100% sure that we're looking at Caddy 0.8.3 here.

Using pagekite and a process manager to run Caddy are red flags already. Try cd'ing into the folder with Caddy 0.8.3 (confirm with `./caddy -version`) and run Caddy plainly.

**Comment by wmark** [comment]
I am looking at 0.8.3 here and it is possible that *Caddy* serves expired OCSP staples whence:

1. The OCSP responder does not issue responses valid for a full hour (but less). For example, if the OCSP responder caches responses for some time.
2. Caddy gets started, gets an OCSP response, and then is stopped.
3. Caddy is started again, fetching an OCSP response that has less of the full one hour validity left.
4. The OCSP staple expires some minutes after that, but Caddy does not renew until the next hourly tick.

https://github.com/mholt/caddy/blob/5c96ee1d9ca0ca2be087c0b5f1281ea2ca0c6f1d/caddy/https/maintain.go#L17
https://github.com/mholt/caddy/blob/5c96ee1d9ca0ca2be087c0b5f1281ea2ca0c6f1d/caddy/https/maintain.go#L31

After this a check ```cert.OCSP.NextUpdate < now() + OCSPInterval``` would ideally apply a negative offset (for an earlier renewal) to ```ocspTicker```. (Which then would by a ```time.Timer```.)

https://github.com/mholt/caddy/blob/5c96ee1d9ca0ca2be087c0b5f1281ea2ca0c6f1d/caddy/https/maintain.go#L198-L204

**Comment by maxigas** [comment]
Running the binary from the directory without supervisor gives the same result. I am not sure how to test without PageKite.

**Comment by mholt** [comment]
@wmark I've never seen an OCSP responder with validity less than an hour. Almost all the ones I've seen have validity windows at of at least a few days...

@maxigas I don't know anything about PageKite, sorry. :confused: If you can test Caddy on a different machine that might be worthwhile.

**Comment by maxigas** [comment]
OK I try to reproduce the configuration on another machine where I don't have to use PageKite and report back.

**Comment by maxigas** [comment]
I try to do that this week and get back to you about the issue. Thanks again for engaging!

**Comment by mholt** [comment]
I'm just going to close this unless the issue can be verified and reproduced; feel free to comment again if there's anything more to add.
