### ISSUE TITLE
browse: displays »Invalid Date«

### ISSUE THREAD

**Issue by hdid** [mholt/caddy#793]
i updated caddy to 0.8.3. in browse mode the caddy does not show dates and just print "Invalid Date":
![caddydate](https://cloud.githubusercontent.com/assets/3944323/14856468/65d7bfa2-0cad-11e6-9272-fa28a79a2ccd.jpg)
it was ok with v0.8.2 but this fail occurred after update.
the os is debian 8 x64

**Comment by wmark** [comment]
What browser are you using, and can you please post a line from the HTML output that contains the string ```<time```? (One is enough.)

**Comment by hdid** [comment]
Firefox 45 and IE11. both have the same issue but Opera is ok and show correctly
```
<td class="hideable"><time datetime="2016-03-05 20:32:37+0000">03/05/2016 08:32:37 PM</time></td>
```

**Comment by wmark** [comment]
Thanks for reporting!

ISO 8601 datetime format allows a notation without T as delimiter between date and time, and ```Z``` as alias for the numeric timezone ```+0000```. Internet Explorer and Firefox decided to implement a subset of the datetime notation. I've used one that all browsers parse.

Another new safeguard is that we check whether the datetime has been read correctly. If not then the listing will not be localized.

This is the change to the default template (*browse* accepts templates!) that will be pushed soon:

```diff
diff --git a/caddy/setup/browse.go b/caddy/setup/browse.go
index 4d3eaf8..6039480 100644
--- a/caddy/setup/browse.go
+++ b/caddy/setup/browse.go
@@ -385,7 +385,7 @@ footer {
                                                {{- else}}
                                                <td data-order="{{.Size}}">{{.HumanSize}}</td>
                                                {{- end}}
-                                               <td class="hideable"><time datetime="{{.HumanModTime "2006-01-02 15:04:05-0700"}}">{{.HumanModTime "01/02/2006 03:04:05 PM"}}</time></td>
+                                               <td class="hideable"><time datetime="{{.HumanModTime "2006-01-02T15:04:05Z"}}">{{.HumanModTime "01/02/2006 03:04:05 PM -07:00"}}</time></td>
                                        </tr>
                                        {{- end}}
                                        </tbody>
@@ -401,6 +401,12 @@ footer {
                                        return;
                                }
                                var d = new Date(e.getAttribute('datetime'));
+                               if (isNaN(d)) {
+                                       d = new Date(e.textContent);
+                                       if (isNaN(d)) {
+                                               return;
+                                       }
+                               }
                                e.textContent = d.toLocaleString();
                        }
                        var timeList = Array.prototype.slice.call(document.getElementsByTagName("time"));
```
