### ISSUE TITLE
Can't access object created in markdown front matter

### ISSUE THREAD

**Issue by MrH100000** [mholt/caddy#794]
#### 1. What version of Caddy are you running (`caddy -version`)?
8.3, But it doesn't matter. It's the same in 8.2 also.

#### 2. What are you trying to do?
Access an object in markdown front matter:

In template:
```html
<p>{{ .Doc.someobject.somefield }}</p>
```

In front matter (TOML, but the same in all front matter):
```toml
+++
title = "sometitle"

[someobject]
somefield = "somevalue"
+++
```

#### 3. How did you run Caddy (give the full command and describe the execution environment)?
Run on mac osx, with just ```caddy```

#### 4. What did you expect to see?
On the page, ```<p>somevalue</p>```

#### 5. What did you see instead (give full error messages and/or log)?
Nothing at all, no error, and nothing on the page. Inspecting the page reveals an element ```<no value>``` put in place instead of the actual value.

#### 6. To reproduce this bug:
Create a Caddyfile with a markdown directive, the options don't matter, just make it so that it will read files in the ```markdown``` directory as markdown files and the file ```template.html``` as the default template. 

Create a directory ```markdown``` and create a markdown file in the directory, call it ```index.md```.

Put the following in the file ```index.md```:
```md
+++
key = "value"
[object]
objkey = "objvalue"
+++
Page
```

Create the file ```template.html``` and put the following in it:
```html
<!doctype html>
<html lang="en">
<head>
  <title>Title</title>
</head>
<body>
Key: {{ .Doc.key }}
Objkey: {{ .Doc.object.objkey }}
</body>
</html>
```

Now, start caddy and go to <your-caddy-server-url>/markdown/index.md in a browser.

You will see:
```text
Key: value
Objkey:
```
The desired result is:
```text
Key: value
Objkey: objvalue
```

**Comment by abiosoft** [comment]
Sorry, front matter does not support objects.

Thanks.

**Comment by mholt** [comment]
I could probably clarify that in the documentation.

Why are objects needed in your case, just curious?

**Comment by MrH100000** [comment]
Mostly for keeping it clean, and some other things. I like having sections, and I use them in templates for various things. (Most other markdown servers with front matter support them.)
Thanks anyways though. I think I've figured out how to add it in to my own build anyways.

**Comment by mholt** [comment]
@MrH100000 Is it complicated? We could take another look. Mostly we were trying to avoid complexity.

**Comment by MrH100000** [comment]
My solution was the use of interfaces, it wasn't very complicated. You can either add another variable alongside Flags, and Variables in metadata.go, and in process.go so you could use it like ```{{ .DocObjects }}``` or whatever you want to call it and then set a ```default:``` in metadata.load in the parsedMap for loop. Or you can just change Variables (in markdown.go) and Doc (in process.go) to ```map[string]interface{}``` and then around line 190 in process.go change ```[]byte(title)``` to ```[]byte(title.(string))```

**Comment by abiosoft** [comment]
That looks fine. 

If you are willing to contribute that, add/edit a test case or two to include objects for json, toml, yaml. We'll be glad to merge it :)

**Comment by MrH100000** [comment]
Okay, I'll do that now.

**Comment by MrH100000** [comment]
So it all works fine except for the JSON, because JSON objects use { and }. so the metadata parser thinks that the } is the end of the front matter, not the object. So do you want to just not support JSON objects, or change the beginning/ending tags for JSON? (You could just make the beginning and ending {{ and }}, and drop the 2nd { or } when parsing it)

**Comment by mholt** [comment]
Can you just surround the JSON bytes with `{` and `}` before you unmarshal?

**Comment by MrH100000** [comment]
Hmm. Let me check.

**Comment by MrH100000** [comment]
I don't think so.

**Comment by mholt** [comment]
Go ahead and open a pull request anyway, we'll take a look.

**Comment by MrH100000** [comment]
Ok, I will.

**Comment by MrH100000** [comment]
Looking at other repo's of projects that try and use JSON front matter, I think it would be best to just change the start and end tags to something like {{{ or {{

**Comment by weingart** [comment]
I have a change to the markdown middleware that fixes the parsing of the JSON front-matter in such a manner that actually parses things until all "{" and "}" are parsed.

**Comment by abiosoft** [comment]
Maybe @MrH100000 should hold on till @weingart's PR (https://github.com/mholt/caddy/pull/762) is merged, to avoid possible conflicts.
