### ISSUE TITLE
More advanced request matching

### ISSUE THREAD

**Issue by samadivk** [mholt/caddy#799]
I would find it useful if, in `header` directives, for example, one could use wildcards, etc. as request matching is very limited at the moment, compared to NGINX. Of course, it is possible to do some things by (mis)using `rewrite`, but it would be advantageous to many, I think, to be able to perform more advanced request matching.

If regex or even simple wildcards could be implemented, that would be awesome. Let me know if I can help out with this.

**Comment by abiosoft** [comment]
I think this is related to https://github.com/mholt/caddy/issues/619.

**Comment by samadivk** [comment]
Ah yes, of course, sorry I didn't see that one.

**Comment by mholt** [comment]
That's alright. Going to close this, to focus the discussion on this in one place, but feel free to comment there if you have any feedback. We're trying to have a careful balance between usability / Caddy philosophy, and feature set.
