### ISSUE TITLE
Does caddy support online configuration via a remote API?

### ISSUE THREAD

**Issue by kelseyhightower** [mholt/caddy#8]
I would like the ability to add and remove backends from a site hosted by Caddy. Is this possible today, if not any plans for the future?

**Comment by mholt** [comment]
It's not possible today, but in the future, definitely yes. Caddy's middleware handlers are designed to be hot-swappable without having to restart the process. A remote management API is one of the primary goals, as well as a nice web UI.

I need to do some refactoring but those are the next major features I hope.

**Comment by mholt** [comment]
@kelseyhightower Okay, I'm starting on this. When you say "add and remove backends" are you referring to the proxy directive? What's on your API dream list?

**Comment by alixaxel** [comment]
@alfonsodev Just because I know you'd :+1: this.

**Comment by amerine** [comment]
@mholt I can't speak for @kelseyhightower but personally the top priority for me would be to remotely manage `proxy`, `tls` and `websocket`

**Comment by mholt** [comment]
Cool, I'll try to do those first. I'm cooking up some other neat things too thstnill be excited for you to try.

**Comment by nodesocket** [comment]
:+1: on a web-ui to configure and change common directives.

**Comment by mholt** [comment]
I have refactored a good portion of the server code to allow another package (the API) to change it. So far, new servers can be started and I have a few endpoints wired up that both get and post middleware configuration.

There is still lots to do, but I hope we'll have something to show within a few weeks.

**Comment by j-mcnally** [comment]
Can the api support client TLS auth? I started using this pretty heavy with apis "docker/etcd" and it would be nice to standardize this as an auth option for the caddy api as well. I think you posted some material related to this recently on twitter.

**Comment by mholt** [comment]
At this point, I don't see why not. (As of the latest version, 0.7.1, [Caddy supports TLS client auth](https://caddyserver.com/docs/tls).) I haven't decided on API authentication, but TLS client auth would not be the only way to authenticate.

An API service will not be allowed without TLS (unless it's only accessible to localhost).

**Comment by mholt** [comment]
Anyone interested in this may now try out an early prototype of the API - the details are in issue #111. It doesn't do much yet, but next on the list are endpoints for TLS and proxy configuration. Feel free to check it out and comment in that issue.

**Comment by amerine** [comment]
@mholt Awesome stuff so far.

**Comment by sinni800** [comment]
I tried to find code on this feature but the api branch is gone (it was described why, I can see that) and there are no more hints on this. 
 
Is there any progress on this?

Personally, I think a tiny web interface that only gives you the config file as a plain text to edit would be a pretty good start. The config file is so easy to read and manipulate anyway.

**Comment by mholt** [comment]
@sinni800 Yeah, we've been working on the front-end UI, and I actually have a file stashed locally here that implements a sort of API, for experimenting. But right now most of the effort has been going into the new site and build system... trust me, it's all worth the wait. :) Yes, the API will start simple. We'll build out from there.

**Comment by sinni800** [comment]
Good to know, thanks :)

**Comment by yroc92** [comment]
@kmanley I've been working with @mholt on this, though admittedly it took a back seat this summer because of my graduation and wedding 😅. We're back on it now though! Again, it'll be simple endpoints to start out, as we want to get the general structure out to the public ASAP. Out of curiosity, what's your use case? Is this a personal project or for a business, etc?

**Comment by emctoo** [comment]
maybe we could setup some plans or todos or disscussion, people could join in @yroc92

**Comment by pcj** [comment]
I'd like to be able to dynamically add proxy entries to new docker containers that come up and down in a build pipeline app, simple as adding stanza such as:

```
pr-101.example.com {
    proxy / localhost:8101 {
        transparent
    }
}
```

**Comment by francislavoie** [comment]
@pcj until this is available in Caddy, check out https://traefik.io/ which does service discovery

**Comment by francislavoie** [comment]
Quick update to this issue - there's now `srv://` support for service discovery for both fastcgi and proxy. In addition, there's a [docker plugin](https://github.com/lucaslorentz/caddy-docker-proxy) that can be used as well.

**Comment by mholt** [comment]
We have implemented this in Caddy 2.
