### ISSUE TITLE
Rewrite directive can only return 200 status code for any 2xx success class

### ISSUE THREAD

**Issue by bmeng** [mholt/caddy#801]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
$ ./caddy -version
Caddy 0.8.3

#### 2. What are you trying to do?
Get return code 2xx via rewrite directive 

#### 3. What is your entire Caddyfile?
```
$ cat Caddyfile2 
localhost
rewrite {
    regexp ^/1
    status 403
}
rewrite {
    regexp ^/2
    status 201
}
rewrite {
    regexp ^/3
    status 202
}
rewrite {
    regexp ^/4
    status 203
}
rewrite {
    regexp ^/5
    status 204
}
rewrite {
    regexp ^/6
    status 401
}
rewrite {
    regexp ^/7
    status 402
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
./caddy -conf Caddyfile2

#### 5. What did you expect to see?
$ curl -I http://localhost:2015/5
HTTP/1.1 204 No Content

#### 6. What did you see instead (give full error messages and/or log)?
$ curl http://localhost:2015/5 -I
HTTP/1.1 200 OK
Server: Caddy

**Comment by mholt** [comment]
It is likely that rewrite will soon no longer be able to rewrite status codes; track #1012 instead for progress on this front. Thanks!
