### ISSUE TITLE
Redirected you too many times.

### ISSUE THREAD

**Issue by eklundkristoffer** [mholt/caddy#805]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3

#### 2. What are you trying to do?
Trying to add configuration to Caddyfile

#### 3. What is your entire Caddyfile?
```text
mydomain.com {
    root /var/www/mydomain.com
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Using Caddy on ubuntu 16.04. I have a folder on desktop with my Caddyfile.I try to run "sudo caddy"

#### 5. What did you expect to see?
I expect to see my website. 

#### 6. What did you see instead (give full error messages and/or log)?
The mydomain.com page isn’t working
mydomain.com redirected you too many times.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
I don't know if it is just me, but what I did was download caddy, added it to PATH. Created a folder on desktop, added a Caddyfile and tried to run it.

**Comment by eklundkristoffer** [comment]
https://laracasts.com/discuss/channels/forge/lets-encrypt-ssl-too-many-redirects

Accepted answer in this thread solved it for me.

**Comment by mholt** [comment]
For the convenience of any future readers, the solution is:

> Try changing your Cloudflare -> 'Crypto' tab -> SSL to 'Strict'
