### ISSUE TITLE
Reload signal not ideal to run caddy in a container

### ISSUE THREAD

**Issue by alexex** [mholt/caddy#806]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3

#### 2. What are you trying to do?
I change the config of Caddy running in a container and send it `SIGUSR1` to make it reload the configuration file.

#### 3. What is your entire Caddyfile?
Works even when I do not specifiy a caddyfile at all.

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
I just run `caddy` without any parameters, but it is run in a docker container.

#### 5. What did you expect to see?
I would expect the config file to be reloaded without the container stopping and thus stopping to listen on these ports, which automatically leads to actually non graceful behavior.

#### 6. What did you see instead (give full error messages and/or log)?
The container just stops and the container does not restart unless (obviously) I specified --restart-always to docker. Unfortunately this also means potentially losing requests and similar things.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Have docker installed and run:

    docker run -p 2015 --name caddy-test-reload alexanderjulo/caddy
    docker kill --signal="SIGUSR1" caddy-test-reload

As you will easily able to see the first command will keep running until you send the signal and then the container will just stop.

**Comment by alexex** [comment]
I btw. already saw https://github.com/mholt/caddy/issues/717 but I does not seem to resolve this issue really. I think one of the advantages of caddy is that it leaves me with a very small container (which I need because I deploy quite a lot of them), as soon as I start adding more external dependencies to it, this becomes way less great.

**Comment by tpng** [comment]
Can you try to run `caddy -restart=inproc` and see if it solves your problem?

**Comment by alexex** [comment]
That only returns `flag provided but not defined: -restart` and then caddy stops

**Comment by tpng** [comment]
The feature is only available in 0.8.3, can you check the output of `caddy -version`?

**Comment by alexex** [comment]
Okay, my image was already 2 weeks old and still on 0.8.2, this seems to work just fine with that flag. Thank you very much!! 😃 

It should probably be incorporated into the documentation, I did not find any reference of this anywhere?

**Comment by tpng** [comment]
The documentation is at https://caddyserver.com/docs/cli.

**Comment by alexex** [comment]
Actually with a real config file it does not seem to update correctly, no that I tried a little further. The container does not restart anymore, the logs also state that it is reloading (shows `Activating privacy features` and all the virtual hosts again) but for one of the hosts the proxy statement has changed (different IP) and caddy seems to go the the old URL still and thus getting a 502. Although this hardly seems like the same bug.

Is there any potential for the caddyfile not to be reloaded entirely? Because when I then restart the container completely everything reloads correctly. My setup is as follows.

I have container running [alexanderjulo/caddy-gen](https://hub.docker.com/r/alexanderjulo/caddy-gen)  (bases on docker-gen) that watches for container changes, generates a new Caddyfile (into a volume that is shared between caddy & caddy-gen) and then sends the SIGUSR1 signal to my caddy container (running [alexanderjulo/caddy](https://hub.docker.com/r/alexanderjulo/caddy), which according to the logs received this signal and reloads, but the proxy still seems to go to the IP address (not sure about this one, as I just get a 502 but do not know where caddy sent a request internally). If I check the Caddyfile it points at the correct IP and when I telnet the IP and port given in the Caddyfile, I can open a connection and when I enter crap I get a 400, so that part seems to be working.

From my perspective this looks like caddy might not be completely reloading the caddyfile, but maybe something completely different is going on here that I do not understand, I am open for any ideas on this one. :-)

**Comment by tpng** [comment]
Could you provide a sample of the old and new Caddyfile used in the restart?

**Comment by alexex** [comment]
Yes, i.e.:

Before

```
ci.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.5:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
git.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.6:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
julo.ch {
    tls alexander@julo.ch
    proxy / 172.17.0.9:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
registry.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.3:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
s3.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.7:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
```


After:
```
ci.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.5:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
git.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.6:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
julo.ch {
    tls alexander@julo.ch
    proxy / 172.17.0.11:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
registry.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.3:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
s3.julo.services {
    tls alexander@julo.ch
    proxy / 172.17.0.7:80  {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-For {remote}
        proxy_header X-Forwarded-Proto {scheme}
    }
    log stdout
}
```

As you can see the only difference is the IP of julo.ch, which is now pointing to another container. I am not 100% sure of this, but it might be possible that there is also an intermediate configuration in which julo.ch is missing, but I did not see it so far.

**Comment by tpng** [comment]
Yes, I can reproduce the issue on my machine too. I will file a new issue for you, thanks!

**Comment by alexex** [comment]
thank you for your support and walking me through the process, it is much appreciated! :-)
