### ISSUE TITLE
proxy: Add websockets support to reverse proxy middleware

### ISSUE THREAD

**Issue by download13** [mholt/caddy#81]
Hey, I was trying to use Caddy as a reverse proxy for a few sites but some of them use websockets.

I'm not completely sure it can't do this, but I can't figure out how to make it. Adding ws:// in front of the upstream endpoint just made it throw a 502 error.

It seems like the code to do this should go somewhere in the [reverseproxy.go](https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go) file, but I'm not sure how it all works.

**Comment by mholt** [comment]
You're right, Caddy can reverse proxy HTTP, but not WebSockets yet (not in the way you want to do it, but it can do WebSockets kind of like CGI).

@nemothekid What do you think would be needed to support proxying the ws protocol?

**Comment by nemothekid** [comment]
I looked into and from what I can understand you could probably get websockets to "work" if you forwarded the `Connection` and `Upgrade` headers (just going off a quick skin of nginx's implementation). I don't have a WS enabled server to test it with right now, but a config like this:

```
proxy / http://my-web-socket-enabled-server:3000 {
  proxy_set_header Connection {>Connection}
  proxy_set_header Upgrade {>Upgrade}
}
```

*might* work. If that works (as in it handshakes and you can send data back and forth for 10 seconds), the next steps would be making sure you could set some arbitrarily large timeout, and probably a better directive than manually setting the `Connection`/`Upgrade` headers (that would also NOT set them when they aren't websocket related).

**Comment by download13** [comment]
I just tried using those settings but for some reason the `Connection` and `Upgrade` headers still aren't making it to the backend.

Also, after reading through the [go transport](https://golang.org/src/net/http/transport.go) code it seems like RoundTrips aren't meant to handle back and forth connections (or at least the default one isn't). They just make a request and then return the response. I'm not sure about that part, but that's what it looks like.

**Comment by nemothekid** [comment]
The Connection and Upgrade headers get stripped out [here](https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L117), but should get reset again [here], which should mean the headers get passed to the backend. I erroneously put `proxy_set_header` in my previous comment, those should be `proxy_header`. I would make sure first that the headers are actually being sent (even if its a random custom one).

I've looked over the go transport code as well, and it seems like it should work as long it doesn't timeout. Requests and Responses are served by different goroutines.

**Comment by download13** [comment]
You're right, I tried it again with the right directives and it worked. The websocket connection goes through now, but it looks like it closes almost immediately after connecting.

**Comment by jaredfolkins** [comment]
The proxy middleware appears to force HTTP 1.1, am I misreading something?

@download13 As a test, could you configure the server and force it to use HTTP 1.1 with the caddy file? That may keep the ws open.

**Comment by download13** [comment]
It does look like it forces HTTP 1.1.

Do you mean I should make the backend server use HTTP 1.1? It's a Node app using the standard http library so it should be using 1.1 already.

Or do you mean I should force caddy to use 1.1? It already appears to be doing that too, and I don't know of a directive that would change it.

**Comment by jaredfolkins** [comment]
@download13 I was just suggesting forcing your entire stack to HTTP 1.1 for this test.

I don't know the directive but [here](https://github.com/mholt/caddy/blob/5f72b7438a7ebf6999f6f8c155a77becf0259bce/app/app.go#L37
) is the boolean for this.


In order for this middleware to play nice long term, there needs to be translations between the protocols.

https://nghttp2.org/documentation/nghttpx-howto.html

*nghttpx is a proxy translating protocols between HTTP/2 and other protocols (e.g., HTTP/1, SPDY). It operates in several modes and each mode may require additional programs to work with. This article describes each operation mode and explains the intended use-cases. It also covers some useful options later.*

Also, FWIW, I predict as the world transitions to HTTP2, [this](https://github.com/bradfitz/http2/issues/38) type of misconfiguration will continue to bite people.

**Comment by jaredfolkins** [comment]
Hah. Never mind that boolean :-) I didn't see the TODO.

**Comment by jaredfolkins** [comment]
@download13 Caddy is in front of your nodejs app yes? I've fairly confident that Chrome or Firefox will initialize the connection using HTTP2. 

So browser(http2)->proxy(http1.1)->nodejs(http1.1)->proxy(http1.1)->browser(http2)? Does that make sense? Nothing ever notifies the browser of the protocol change, hence the ws closes. Again, this is just a guess.

**Comment by download13** [comment]
I looked at the current HTTP2 sessions while using Chrome and my session with caddy doesn't seem to show up on it, so I think it's already using 1.1.

**Comment by mholt** [comment]
HTTP/2 will only be used over HTTPS. And you can force HTTP/1 using the flag `-http2=false` - it's not something you can configure from the Caddyfile.

So anyway, at this point, it looks like we need a way to keep the connection open.

**Comment by download13** [comment]
I managed to get it working but I'm pretty sure it has bugs related to error, timeout, and close handling.

https://github.com/download13/caddy/commit/42e4782c4ae74f228335a1f1ce9af0c427d7a8f4

**Comment by download13** [comment]
@nemothekid I forgot to mention. If you need a websocket server to test on and have npm you can use `npm install -g wscat` to install wscat as a command line utility.

`wscat -l 8001` starts a listening websocket server
and
`wscat -c http://localhost:8000` connects to the reverse proxy (use your own ports obviously).

Though now that I think about it you could also just make a Caddyfile that does `websocket /echo cat` but then you'd also have to make it serve an HTML file with some client websocket code.

**Comment by mholt** [comment]
@download13 This is a good start. I'll mark this as "in progress" so that we can work out the rest of the issues you mentioned and make sure that tests are added.

**Comment by tatsuhiro-t** [comment]
Some clarification about WebSocket and HTTP/2.
Currently, there is no standard way to carry out WebSocket in HTTP/2.
HTTP/2 disallows connection upgrade, so you cannot upgrade HTTP stream to WebSocket inside HTTP/2 connection.  The discussion to enable WebSocket over HTTP/2 has been done quite sometime, but there is still no consensus and no implementation exists.
So I'm sure that web browser connects to server via HTTP/1 if it wants to make WebSocket connection.  That is the only way ATM.

**Comment by mholt** [comment]
Ah, that's right - I forgot about that. Fortunately, the HTTP version is a client choice, so we can probably assume HTTP/1 for now without having to worry about it.

**Comment by fatih** [comment]
I wrote a websocket proxy based on gorilla, check it out for more info: https://github.com/koding/websocketproxy it's a http handler. Thought it's not HTTP2 compatible :)

**Comment by guilhermebr** [comment]
Nice, I can get this =]

**Comment by acmacalister** [comment]
@download13. I'm working on a project that needs reverse proxying for WebSocket connections and I would like to use Caddy. I've done some work with WebSockets before and would be happy to help you get this added if that would be helpful.

**Comment by mholt** [comment]
I actually found myself needing this feature today. :smile:

**Comment by download13** [comment]
@acmacalister I don't really know go well enough to implement it safely, so if you want to take a crack at it I wouldn't mind.

**Comment by acmacalister** [comment]
@download13 sounds good. I got a environment setup this evening. I will give it a go in the morning.
