### ISSUE TITLE
How to move from RSA2048 → P384

### ISSUE THREAD

**Issue by kseistrup** [mholt/caddy#813]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.3

#### 2. What are you trying to do?

I've been using Caddy with the default RSA2048 keys for a domain and wanted to transision to P384 keys.

#### 3. What is your entire Caddyfile?
```text
example.com {
  tls {
    key_type p384
  }
  root /srv/example.com
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

```sh
/usr/bin/caddy -agree=true -email=me@example.com -conf=/etc/caddy/caddy.conf
```
Linux 4.5.2 (64 bit)

#### 5. What did you expect to see?

I expected Caddy to switch to P384 keys once the keys were up for renewal.

#### 6. What did you see instead (give full error messages and/or log)?

TLS keys are still RSA2048.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Set up a subdomain that hasn't had a TLS key yet.

```text
sub.example.com {
  root /srv/sub.example.com
}
```

After the default RSA208 key has been obtained from Let's Encrypt, add a `key_type` stanza to the config

```text
sub.example.com {
  tls {
    key_type p384
  }
  root /srv/subexample.com
}
```
and wait for renewal to occur. New keys are still of type RSA2048.

**Comment by elcore** [comment]
Hello @kseistrup,

A renewal uses the same private key and does not generate a new one.

**Comment by kseistrup** [comment]
So how do I switch to another type of key for a given domain that already has a key?

**Comment by elcore** [comment]
Hello @kseistrup,

the hard way -- delete the old key

**Comment by iugo** [comment]
maybe `rm -r {user}/.caddy/acme/acme-v02.api.letsencrypt.org/sites/{domain}` now
