### ISSUE TITLE
Support HTTP/2 Server Push Link headers

### ISSUE THREAD

**Issue by FiloSottile** [mholt/caddy#816]
Caddy could send Link headers to use both browser prefetching and CloudFlare server push https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/

**Comment by wmark** [comment]
Could unconditional server push (indication?) become a problem, as in: browsers ignoring any pushes from hosts that they've learned use *push* frivolously (repeatedly pushing what's already in cache)?

**Comment by FiloSottile** [comment]
There's no point in blindly ignoring something the browser already received, and the browser can kill push attempts early when it notices an unfulfilled promise that it does not need.

**Comment by Penagwin** [comment]
At least for telling cloudflare to server push multiple files, you currently can't.
See: https://github.com/mholt/caddy/issues/818

**Comment by brodock** [comment]
I was reading an article somewhere and they said Apache and AppEngine are using Link Header (https://tools.ietf.org/html/rfc5988) to intercept from your App Server and do the HTTP/2 server push, so this seems to became the default standard for that.

**Comment by KyleAMathews** [comment]
Something useful for static sites is a "push manifest". This is what GAE supports apparently https://www.npmjs.com/package/http2-push-manifest

**Comment by mholt** [comment]
This is now implemented, #1215!
