### ISSUE TITLE
Add Headers instead of Set Headers

### ISSUE THREAD

**Issue by Penagwin** [mholt/caddy#818]
Currently the way that cloudflare is supporting server push is by having the server (caddy) set a Link header for each item to be pushed.

Their example:
`Link: </asset/to/push.js>; rel=preload;`

The problem with Caddy is that it sets each header of that name (Link) each time, instead of adding it. So if you wanted to tell cloudflare to push multiple files it isn't currently possible. I have tested it myself by changing Line 30 of the headers.go file from:
`w.Header().Set(header.Name, replacer.Replace(header.Value))`
to
`w.Header().Add(header.Name, replacer.Replace(header.Value))`

Is this something worth changing permanently for caddy?

https://github.com/mholt/caddy/blob/da016f8d5a14cdce2925556ae0e5a7bc72ddbb1a/middleware/headers/headers.go#L30

**Comment by sean-callahan** [comment]
How about using a `+` prefix to add more than one header. For example:
```
header / {
    +Link "</images/image.png>; rel=preload"
    +Link "</css/main.css>; rel=preload"
}
```

**Comment by mholt** [comment]
Yes, I think this functionality should mirror that in `proxy` with proxy headers.

**Comment by marc-gr** [comment]
I can take care of it @mholt if that is okay 👍

**Comment by mholt** [comment]
Certainly, @marc-gr! That would be great.

**Comment by mholt** [comment]
@marc-gr How's this going? Anything we can help with?
