### ISSUE TITLE
h5ai on Caddy

### ISSUE THREAD

**Issue by MSF-Jarvis** [mholt/caddy#819]
I used to host my website on nginx, then httpd, finally @faddat referred me to caddy, and I just migrated yesterday. My homepage is up, being nothin' but a jekyll site, but having an issue with using lrsjng/h5ai, my caddyfile is this : 
```text
#the homepage
msfjarvis.me:80 www.msfjarvis.me:80 {
        root /var/www/html/
        tls msfjarvis@gmail.com
}

#the downloads index
#roms.msfjarvis.me:80 {
#       root /var/www/ROMs/
#       fastcgi / /var/run/php5-fpm.sock {
#               ext     .php
#               split   .php
#               index   _h5ai/public/index.php
#       }
#       tls msfjarvis@gmail.com
#}

roms.msfjarvis.me:80, roms.msfjarvis.me:443 {
        root /var/www/ROMs
        log /root/access.log
        errors /root/errors.log
        fastcgi / /var/run/php5-fpm.sock php {
        ext     .php
        split   .php
        index   _h5ai/public/index.php
        }
}
```

**Comment by abiosoft** [comment]
Firstly, change that fastcgi block to this single line.
```
fastcgi / /var/run/php5-fpm.sock php 
```

**Comment by tboerger** [comment]
Second, do a rewrite where you check for existance of the path, otherwise rewrite to php

**Comment by MSF-Jarvis** [comment]
@tboerger Can you spoonfeed me on this? :/

**Comment by tboerger** [comment]
I can't remember the exact values since I replaced h5ai with the browse directive and a custom template. But it's something like that:

```
rewrite {
    to {path} /_h5ai/public/index.php
}
```

That should server files directly (including CSS and JS) but delegates folders to the h5ai PHP file.

**Comment by faddat** [comment]
So @msf-jarvis, what you probably want to do is look into the browse
directive and how to template it :).

**Comment by nwgat** [comment]
`        rewrite {
		if {path} ends_with /
		to {dir}/index.html {dir}/index.php /_h5ai/server/php/index.php
	}
`
is what i found somewhere i think it has to be in http://[awesome].domain.ninja/_h5ai or in .caddy/_h5ai but i forgot, hope it works got it running at https://awesome.nwgat.ninja/

**Comment by MSF-Jarvis** [comment]
@nwgat, can you let me know how you added the custom header and the needed section of your Caddyfile

**Comment by nwgat** [comment]
```
awesome.nwgat.ninja {
	root /var/www/awesome.nwgat.ninja
	#browse
	#basicauth /test user pass
	gzip
	tls hello@nwgat.ninja
	fastcgi / /var/run/php5-fpm.sock php

        rewrite {
		if {path} ends_with /
		to {dir}/index.html {dir}/index.php /_h5ai/server/php/index.php
	}
}
```

**Comment by nwgat** [comment]
seems you need to put h5ai in `/var/www/awesome.nwgat.ninja/_h5ai`

**Comment by nwgat** [comment]
and there is a bug somewhere, atleast on caddy 0.8.2 as it sometimes hang the whole http server, it might be php that does it

**Comment by faddat** [comment]
Caddy and PHP still don't seem to be very friendly.  I can't wait till php has been go-ified!

**Comment by mholt** [comment]
Looks like there is a working solution here! Thanks to everyone who helped with that.

**Comment by squaresmile** [comment]
In case someone else is looking for the Caddyfile config for h5ai and caddy v2. Here's what I have that works for me.

```
handle {
    php_fastcgi unix//run/php/php7.4-fpm.sock
    file_server {
        browse
    }
    @no_index {
        not file {
            try_files {path}.html {path} {path}/index.html
        }
    }
    rewrite @no_index /_h5ai/public/index.php
}
```

**Comment by Kabouik** [comment]
Thanks a lot @squaresmile, works for me.

I'm wondering if there would be a way to restrict browsing to authenticated user, but allow direct file access when the full URL of a file is used by anonymous users? Would it be something to configure in caddy or in h5ai? My installation of h5ai is several years old, I don't quite remember how it works.

**Comment by Kabouik** [comment]
In case it helps understanding why h5ai is now served on domain.tld with the above h5ai config for just a subfolder, this is my caddyfile:

```
domain.tld, www.domain.tld {
        tls domain@disr.it
        root * /var/www/domain.tld/wordpress
#       handle /misc/* {
#               root * /var/www/domain.tld/wordpress/misc
#               uri strip_prefix /misc
#               file_server browse
#       }

handle /misc/_h5ai/private/* {
    respond 404
}
handle {
    php_fastcgi unix//run/php/php7.3-fpm.sock
    file_server
    @no_index {
        not file {
            try_files {path}.html {path} {path}/index.html
        }
    }
    rewrite @no_index /misc/_h5ai/public/index.php
}

        encode gzip
        php_fastcgi unix//run/php/php7.3-fpm.sock
        # Prevent malicious PHP uploads from running
        @uploads {
                path_regexp path /uploads\/(.*)\.php
        }
        rewrite @uploads /
        file_server
}
```
