### ISSUE TITLE
question about auto conf

### ISSUE THREAD

**Issue by joeblew99** [mholt/caddy#82]
in my path i have the caddy executable.
/users/me/go/bin
on OSX

For general web site stuff i always want to have directory list on.
is there a way to have the caddy always look to the caddyfile configuration in the same folder that the caddy exe exists ?

this would then mean that whenever i type caddy in the terminal, it would always take on the conf file in the /users/me/go/bin

**Comment by joeblew99** [comment]
then if there is a caddfile config in the actual path i am on in terminal that would override the default.

is a good way to have a type of override i think.

so if not config path OR no caddy config file is at the actual path it uses the one where caddy exe is.

**Comment by mholt** [comment]
The big problem here is determining from within the program, in a cross-platform way, where that specific instance of the executable lives.

There are 3 ways of giving Caddy a configuration; they are tried in this order:

1. -conf flag
2. Pipe to stdin
3. Caddyfile in the current working directory

Would -conf or piping it in work for you instead?

**Comment by joeblew99** [comment]
Neither work really. 

But its no biggy.

**Comment by joeblew99** [comment]
Close this

**Comment by mholt** [comment]
Sorry about that! I just don't know a clean way to do it. I still don't understand why you would put Caddyfile in your bin folder? If there is a legitimate use case that would be common, perhaps there is a way to make it work.

**Comment by joeblew99** [comment]
Yeah its not obvious why.
Basically when developing on my laptop I always want the config properties
to be super open. When working on any front end stuff I can then just fire
up caddy from the command line and it would take on those default
properties.

Then when working where I need caddy to have more specific properties, I
would make a caddy conf file at the same folder i start caddy from.

Does this make my use case clearer. I did not explain myself so well before
on the initial issue

**Comment by mholt** [comment]
I see. That's closer to how nginx works. Caddy was designed to be more portable, separate from individual site configurations. You can still run Caddy like `caddy -conf=/users/me/go/bin/Caddyfile` to get what you want, right? Perhaps `alias autocaddy="caddy -conf=/users/me/go/bin/Caddyfile` to make it more convenient?

**Comment by joeblew99** [comment]
Ah I get it.
Did not know the alias trick :)

Thanks !!
