### ISSUE TITLE
Hosting Shopware

### ISSUE THREAD

**Issue by PhilmacFLy** [mholt/caddy#820]
Hey,

I'm trying to host a shopware site with caddy.
Now here comes the problem: shopware is using a very extensive .htaccess file to run.
Now my knowledge in .htaccess files is limited so im not able to translate everything, especially not the rewrite rules, into caddyfile directives so I hoped you could help me out.
See the .htaccess file as attachment.

[htaccess.txt](https://github.com/mholt/caddy/files/263100/htaccess.txt)

**Comment by elcore** [comment]
Hello @PhilmacFLy,

this is not an issue! -- Please go to https://gitter.im/caddyserver/support for support

**Comment by PhilmacFLy** [comment]
Mea culpa. I didnt know that this exists. Thank you very much.

**Comment by KEANO3** [comment]
For documentation purposes: ```
example.org {
    fastcgi / 127.0.0.1:9002 php
    rewrite / {
        to /maintenance.html {path} {path}/ /shopware.php
    }
}
``` 
This does the trick with our shopware installation
