### ISSUE TITLE
use HOME variable for ReadWriteDirectories= in  SystemD-Script

### ISSUE THREAD

**Issue by computerlyrik** [mholt/caddy#821]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3

#### 2. What are you trying to do?
Running Caddy with Systemd

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Debian 8, Systemd

#### 5. What did you expect to see?
Running Systemd

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Set a different ```Environment=HOME=``` in https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service

Is it possible to use $HOME for the ```ReadWriteDirectories=``` parameter?

**Comment by wmark** [comment]
This is a question about variable substitution in systemd unit files. Everything in folder *init* is exemplary and we ask to not file any tickets for that or else we will not be able to tell support requests from bugs and proposed changes. Meet us on Gitter (chatrooms) for that!

If `$HOME` were something outside the protected directories, like `/var/lib/caddy`, then you would not need to add it to `ReadWriteDirectories`.

So, yes, you could use variable subsitution there (the values are taken from the *environment*).

But no, avoid variables in *unit files*. (In this case, even with a changed `$HOME` you would want a fixed and constant location for TLS certificates.)
