### ISSUE TITLE
Error with Priviliges - SystemD Debian

### ISSUE THREAD

**Issue by computerlyrik** [mholt/caddy#822]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3

#### 2. What are you trying to do?
Running as service.

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Debian 8, SystemD, 
with provided SystemD Script  https://github.com/mholt/caddy/blob/master/dist/init/linux-systemd/caddy.service
```setcap cap_net_bind_service=+ep /usr/bin/caddy```

#### 5. What did you expect to see?
running caddy server

#### 6. What did you see instead (give full error messages and/or log)?
caddy[7200]: Activating privacy features...2016/05/14 14:54:49 [INFO][] acme: Obtaining bundled SAN certificate
caddy[7200]: 2016/05/14 14:54:49 [INFO][] acme: Trying to solve HTTP-01
caddy[7200]: 2016/05/14 14:54:49 [] failed to get certificate: [] error presenting token: Could not start HTTP server for challenge -> listen tcp xx.xx.xx.xx:80: bind: permission denied
systemd[1]: caddy.service: main process exited, code=exited, status=1/FAILURE

#### 8. Is there a quickfix?
Works for me as soon as i remove the line ```NoNewPrivileges=true```

**Comment by wmark** [comment]
Again, those files are exemplary (modify them to your liking) and we ask that you not file tickets for them.

That said, you don't need `setcap cap_net_bind_service…` with the suggested systemd unit file. I am using the file myself without issues.

If the error were caused by systemd/the unit file as suspected, then you would get a `Main process exited, code=exited, status=218/CAPABILITIES`.

**Comment by wmark** [comment]
@computerlyrik Do you bind to a private IP? That is, one that differs from the public IP of the site you like to get Letsencrypt certificates for?

**Comment by wmark** [comment]
I got to the bottom of this:

Debian Jessie ships **systemd version 215** (which is quite… old!). The logs read: ```Unknown lvalue 'AmbientCapabilities' in section 'Service'```. That directive has been added in **version 229**.

So you're right, with that obsolete version you need to use `setcap…` and strip `NoNewPrivileges`. This, or just update your *systemd*, which I highly recommend.
