### ISSUE TITLE
day-google-chrome-disabled-http2-nearly-everyone-may-15th-2016

### ISSUE THREAD

**Issue by kibotu** [mholt/caddy#825]
i don't know too much about it so i just forward it: https://ma.ttias.be/day-google-chrome-disabled-http2-nearly-everyone-may-15th-2016/

please close & ignore if that is not an issue

**Comment by abiosoft** [comment]
Apparently, it is not as Matt indicated in this tweet. https://twitter.com/mholt6/status/731469534750756864.

Thanks.
