### ISSUE TITLE
Does internal directive work with websocket

### ISSUE THREAD

**Issue by insteps** [mholt/caddy#826]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3

#### 2. What are you trying to do?
Add internal directive alongwith websocket directive

#### 3. What is your entire Caddyfile?
```text
:2015
browse
root /tmp/wwwroot
internal /hidden
websocket /ls ls 
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
cd /tmp 
./caddy -log /tmp/caddy.log

#### 5. What did you expect to see?

When connecting via websocket the output of `ls` command seems to be displayed when I comment out internal directive, but does not when I use it alongwith websocket.
I could not find if both directive is allowed.

#### 6. What did you see instead (give full error messages and/or log)?

2016/05/15 17:19:05 http: multiple response.WriteHeader calls

**Comment by mholt** [comment]
What is your request?

**Comment by insteps** [comment]
Could you pls tell me I can have both "internal" directive alongwith "websocket" in Caddyfile ?
Thanks

**Comment by DenBeke** [comment]
Why wouldn't you be able to have both `internal` and `websocket` directive in a Caddyfile? It will of course not make any sense if they both handle the same path...

**Comment by mholt** [comment]
Yes, I don't know why you wouldn't be able to... closing unless there's anything else.
