### ISSUE TITLE
Rename Let's Encrypt to Certbot?

### ISSUE THREAD

**Issue by ericmdantas** [mholt/caddy#830]
Since Let's Encrypt's client was renamed to Certbot, I think there might be some places to change the docs/comments.

**Comment by captncraig** [comment]
While their client is now called certbot, the CA itself is still called "Let's encrypt". Caddy was never using any official clients, but a go implementation of the acme protocol. I think it is still valid to call it "Let's encrypt", but to be fair, it should work with any acme CA.

**Comment by mholt** [comment]
Thanks for your suggestion! Version 0.9 will no longer use the term "letsencrypt" unless we specifically mean that CA, but already Caddy works with any ACME-enabled CA.

**Comment by ericmdantas** [comment]
Awesome!
