### ISSUE TITLE
Discussion: SAN certificates

### ISSUE THREAD

**Issue by captncraig** [mholt/caddy#831]
I'm sorry to keep bringing this up, but I continually hit rate limits with Let's Encrypt, and issuing SAN certificates would reduce the pain of having a lot of subdomains all needing certificates.

### Problem
With Let's Encrypt you are currently limited to 5 *certificates* per domain per week. At 90 day lifetime, this puts a hard limit of around 50 subdomains per domain, assuming you properly space your issuance over 10 weeks. Using SAN certificates, you can put up to 100 names per cert and greatly increase this number.

Matt has repeatedly rejected the idea that caddy should issue SAN certs because it increases caddy's complexity by making multiple places to look for certs instead of the simple `$HOME/.caddy/sites/name` pattern. Also, we hope that LE will relax the limits and make this unnecessary, but I have not seen any indication on when/if that will happen.

### Plugin?
I was thinking today that *maybe* a plugin could handle this.

```
a.mydomain.com {
   san foo
}
b.mydomain.tld {
   san foo
}
```

A plugin could:

1. Collect all domain names / san names at parse time.
2. After all domains parsed, get caddy's LE account info, and issue certs using lego.
3. Save certs in `.caddy/sancerts/foo.crt`
4. (hopefully) implicitly add `tls .caddy/sancerts/foo.crt .caddy/sancerts/foo.key` to the relevant domains.
5. Periodically renew certs and restart caddy.

This all seems potentially possible, but I am not sure if it would work because of caddy's startup sequence and if any of this will conflict with caddy's own certificate management steps.

That all feels like it is reproducing most of what caddy already does, and I am not sure if all of the things it needs to do that job are currently available to plugins.

### Native?

It seems like baking this into caddy's own cert management system would not be too hard. 

```
a.mydomain.tld {
   tls {
    san #default.mydomain.tld.crt
   }
}
b.mydomain.tld {
   tls {
   san foo #foo.crt
  }
}
c.otherdomain.tld {
   tls {
    san foo #foo.crt contains multiple tlds
   }
}
d.otherdomain.tld {
  tls {
    san #default.otherdomain.tld, default issues all certs for a tld together, but doesn't mix tlds.
  }
}
```
I like this for a couple of reasons:

1. It must be explicitly activated. There is no ambiguity about where to look for a cert for a given server.
2. Caddy can manage the san certs just like any other.
3. Lego already supports this.

Thoughts?

**Comment by captncraig** [comment]
Additionally a `-useSanCerts` flag could be the equivalent of adding 

```
tls {
  san
}
```
to every server block, and only issue one cert per tld.

**Comment by mholt** [comment]
> With Let's Encrypt you are currently limited to 5 certificates per domain per week.

That's not true, it's 20/week. https://community.letsencrypt.org/t/rate-limits-for-lets-encrypt/6769/2?u=mholt

I still don't like the idea of SAN certificates. Too much room for error...

**Comment by captncraig** [comment]
I wasn't aware of the increase in limits, it looks like that should increase capacity a lot, combined with renewals being on a separate timer. Maybe this is overkill then. If only LE supported wildcards now...

**Comment by mholt** [comment]
No problem. :smile: FWIW, discussion of SAN is still permitted, of course, even though the issue is closed.

**Comment by Kidswiss** [comment]
Hi

@mholt I get your point for not supporting SAN certificates. But there are some enterprise firewalls with SSL/TLS inspection that really struggle with SNI. Users behind one of those get an invalid certificate error when browsing a page with SNI or the page gets blocked completely by the firewall.

**Comment by mholt** [comment]
>  But there are some enterprise firewalls with SSL/TLS inspection that really struggle with SNI.

I'm so sorry. They'll have to move into 2004.

**Comment by jleclanche** [comment]
Reviving this discussion a little. I think it comes up often enough that this *really* merits reconsidering. Any website with a sufficient amount of subdomains will be hit by this, which means that one of caddy's and letsencrypt's main features become completely moot. This isn't just a SNI issue.

The code/logic complexity argument is valid mainly for the case of "Caddy should figure out, all by itself, which certificates fall under which domain name". It doesn't have to work like that, though. We can shift this decision making down to the user. Same for renewal failures.
If we make SAN an opt-in feature requiring changes to the Caddyfile, this puts all responsibility on the user.

I've prototyped a few ways to do it and arrived to the syntax below:

```conf
san {
	# Simple example: multiple subdomains attached to the same domain
	example.org one.example.org two.example.org foo.two.example.org

	# This is okay as long as the provider supports it
	example.net example.com

	# Error: Redefinition of an existing san rule
	example.org three.example.org

	# Wildcard example: Attach all subdomains matching example.com to this one
	# Alternatively, this could request a wildcard cert if an ACME provider ever offers those.
	example.com *.example.com
}
```

 A `san` rule would be defined and parsed early on. Before requesting any cert, caddy would have a lookup table of all the domain it wants, as well as which "main" server these fall under. In the above examples, if a cert is needed for `example.com`, Caddy knows to use the one in `example.net`. Bonus: Fully backwards-compatible.

@mholt If a sufficiently clean and low complexity pull request was filed implementing such a system, would you take it? I think if Caddy becomes popular, SAN support will be a matter of when, not if - so we might as well figure out the wanted design :)

**Comment by captncraig** [comment]
The only reason I think SANs might be needed is for clients who do not support SNI, so you need all of your domains on the default cert for the server. Luckily, those clients are getting to be fewer and fewer. 

The other possibility is getting around rate-limits, but at 20 subdomains a week, I think even that is sufficient for anyone who has a finite number of domains. Anyone else probably needs wildcards. 

For performance, it is actually better to have smaller, single name certs. If your certs are larger than a single packet then handshakes take longer. 

Its not that it isn't possible to figure out. From my point of view it just isn't needed. If LE supported wildcards, there might be a case for caddy to remap domains to a wildcard cert, but that is a question for some unknown future time.

**Comment by captncraig** [comment]
Why do you think SANs are a needed feature in the first place? Not antagonizing. I wanted them too. I'm just out of good arguments for them.

**Comment by jleclanche** [comment]
@captncraig Yeah, wildcards would be great, but we don't have wildcards :)

Having a lot of subdomains is not an uncommon use case. This is why wildcard certs are such a highly requested feature on Let's Encrypt. 20 a week is very easy to hit if each request is separate. let's say I have apex, www and 5 more subdomains; then I want to prepend them with `staging.` and `dev.`. Oops, I'm now at 21 subdomains. Better hope they don't all renew within a week.
If I have multiple servers behind a load balancer each serving a few subdomains, I will also very quickly hit that limit if I don't put a certificate sharing system in place.

**Comment by mholt** [comment]
@jleclanche 

> Having a lot of subdomains is not an uncommon use case.

Actually, I believe it is. It's users who want to scale their service linearly (or exponentially❗) by adding subdomains where things get tight. But those users certainly have the technical ability to manage one wildcard certificate. They're not the long tail of unencrypted sites that Let's Encrypt is trying to encrypt.

> Better hope they don't all renew within a week.

Renewals don't count against the rate limit.

> If I have multiple servers behind a load balancer each serving a few subdomains, I will also very quickly hit that limit if I don't put a certificate sharing system in place.

Caddy now allows this. We're still improving the support for TLS storage plugins and bolstering it up to handle failures better, etc, but it's possible.

**Comment by jleclanche** [comment]
> Actually, I believe it is. It's users who want to scale their service linearly (or exponentially❗) by adding subdomains where things get tight. But those users certainly have the technical ability to manage one wildcard certificate. They're not the long tail of unencrypted sites that Let's Encrypt is trying to encrypt.

I'm not sure I understand. Subdomains are great. Hell even for debugging - for example, in our cloudflare->ELB->Caddy stack, we spun up subdomains for each element in that matrix (CF+ELB disabled, CF enabled ELB disabled, etc) in order to better debug issues in-between those components. And of course, we wanted to make sure HTTPS worked for all those. Caddy is *fantastic* for that.

Asf or Let's Encrypt, we use it in production here for three reasons:
1. We love and support the project
2. It's saving us a significant amount of money (we have a dozen domains, several subdomains on each and not a ton of cash)
3. It's automatable, which gets rid of the human effort of handling certs.

Viewing LE as only a CA for "the long tail" is IMHO viewing it as a toy CA, which is absolutely what it's not. If anything, I'd say they're one of the most serious CAs out there, and certainly the only one I trust.

The reason we're using Caddy is along the same lines: We view it as a tool that automates the certificate handling on our user-facing servers. I believe this is revolutionary - eliminating the human element in TLS configuration is a big deal.

> Renewals don't count against Let's Encrypt's rate limit.

Didn't know that! It's good to hear.

> including handling failures, edge cases, different CAs, etc.

So it seems to me like what most people want is more on the micro level of "we don't want to get throttled by LE" and there is a core feature of LE which is not being used by Caddy right now, which avoids that problem in most cases. It's also very easy for users to find out they're being throttled, wonder why they have so many certs, see that caddy is requesting 1 cert per subdomain and think "Oh, why doesn't Caddy just request a single cert for all those". 
You'll certainly know better than me, but I can argue that this UX goes exactly counter to Caddy's advertised philosophy, of ease of use with automatic HTTPS. :) I think all those users, myself included, would be perfectly happy with a plugin doing that work.

**Comment by captncraig** [comment]
The rate limits are kinda odd though. If you issue a single name cert you can renew it forever at no cost. You can get 20 per week. 

If you start combining, then every new combination counts against your rate limit. Yeah, you can't spin up 75 sub domains the first week, but you can set it up over 4 and be good forever.

**Comment by jleclanche** [comment]
@captncraig That holds up. If you have a.example.org and b.example.org, then you add c.example.org, in the current model you add once and renew 3 certs (at no cost), in the proposed model, you refresh all *once* and renew one cert (at no cost either). If the renewals do not hit the rate limit then they're irrelevant, it's only first-time setup that matters.

**Comment by captncraig** [comment]
Caddy's sweet spot is super simple. There is nothing that says it needs to be your only tool. You could use another tool to generate San certs, and caddy will happily use them.

**Comment by jleclanche** [comment]
That is what I'm currently doing, yes. I'm writing all this from the perspective of improving the user experience for this scenario, which I believe users will hit often enough for a change of some kind to be warranted. :)

**Comment by mholt** [comment]
@jleclanche 

> Viewing LE as only a CA for "the long tail" is IMHO viewing it as a toy CA

Believe me, I don't view LE as a "toy CA." The long tail of sites is what makes the majority of the sites on the Internet, which is why LE is now the second-largest CA by certificates issued. More sites are encrypting now than ever before. (Caddy is only a tiny fraction of that.) And encrypting the long tail [is not something Let's Encrypt takes very lightly either](https://letsencrypt.org/2016/03/08/our-millionth-cert.html).

IMO, a CA's rate limits are a poor justification for the complexity of SAN when frankly Caddy does not need SAN to run optimally.

An ideal user experience is one with minimal surface area, and increasing it so that the user has the burden of configuring SAN management is not an improvement.

**Comment by jazoom** [comment]
Traefik seems to do this well. It's also written in Go. Maybe it's worth checking their implementation?

**Comment by jazoom** [comment]
Even though it's 20 per domain, since Caddy only does one at a time the effective limit is 5, right?

From the link posted by @mholt 
```
20 certificates per registered domain per week (up from 5).
Added an exception to this limit for renewing certificates (issuing a new certificate with same names as a previous one).
Added a new limit on issuing certificates with the exact same set of names: 5 certificates per FQDN set per week.
```

**Comment by captncraig** [comment]
With the new rate limits, I'm less worried about this for most users. You can issue 20 per week, and renewals don't count anymore, so the calculations are much easier. If you need more than that in a hurry, you probably want to customize them more anyway.

**Comment by mholt** [comment]
@jazoom No, it's 20 per domain per week. The limit of 5 is for the exact same set of names on a single certificate per week; there's no reason you will hit this unless you've misconfigured the directory where Caddy stores the certificates (like, for example, deleting it every time you run Caddy, and doing that multiple times per week).

The SANs are kind of a stop-gap anyway, you're still limited, and if you're really needing to deploy at scale, SAN won't really help you (i.e. most organizations I've met with who need massive certificate management are still limited severely with 100 names per cert) - chances are it's a one-time thing anyway, so just ramp up slowly.

Or, honestly, get a wildcard cert. You'll have to manage it the old-fashioned way but it's much simpler if you literally have thousands of subdomains to serve all at once. That's what wildcards are designed for. ;)

**Comment by mholt** [comment]
2020 Update

For the record (and for the information of any searchers who find this thread), the deliberate decision to manage only single-SAN certificates is why **Caddy/CertMagic was (to my knowledge) the singular ACME client unaffected** by [the recent Let's Encrypt CAA Rechecking bug](https://community.letsencrypt.org/t/2020-02-29-caa-rechecking-bug/114591?u=mholt), in which over 3M certificates were slated for revocation in just a few days, and about 2M were actually revoked.

While site owners around the world were scrambling to figure out how to force a renewal of their certificates with their various ACME clients, Caddy users... didn't have to do anything.

Maybe it was just luck, but I am pretty convinced that sticking to simpler design principles is often beneficial when you least expect it.

_(Even if Caddy sites were affected, CertMagic has logic to automatically replace certificates that have a "Revoked" OCSP status.)_

**Comment by eelmasllari** [comment]
It would be great to clarify what target market/target user group is Caddy aiming for. SAN certificates are tightly connected to this "aim".

If Caddy aims for the "Long Tail", tinkerers, and docker-based developer machines, the current limitations are OK. But if Caddy is to be used in enterprises, it *will* need SANs. (speaking from experience with a concrete enterprise deployment)

Enterprise deployments have multiple services that need TLS certificates: web servers, mail servers, database servers, meeting servers, and other infrastructure. Of these, web servers support SNI, but mail and other servers often do not. Even when they do, mail and other clients do not support SNI (e.g Outlook Mail Client, arguably the most used email client in the enterprise world, does not). In case you think it is rare for a mail server to need two names: think of all enterprise mergers, mother-daughter connections, and cases where several domains get redirected to the same mailboxes. All these cases need SAN certificates for mail and other non-webservers

An enterprise using Caddy is then forced to use some other cert management and renewal software -- e.g. certbot -- to deal with the certificates for the non-webservers (mail, meeting, whatever). But once certbot is installed, its certificates, including SANs, can be used for the web servers as well! Why should an enterprise keep Caddy + certbot when a) certbot replaces the cert management part of Caddy, and the enterprise netops have more experience with nginx/apache/haproxy/varnish anyway? Which brings me to what I had to do at the enterprise deployment I worked with: I had to pull Caddy off the production server and replace it with Nginx, with the certificates managed by certbot.

PS. Yes, we were affected by the Let's Encrypt CAA Rechecking bug and we did not have to touch a single thing. Certbot's automated renewal, which is part of the default installation of certbot, did the job brilliantly.

**Comment by mholt** [comment]
@eelmasllari 

Your post is based on several wrong assumptions.

> It would be great to clarify what target market/target user group is Caddy aiming for. SAN certificates are tightly connected to this "aim".

Anyone and everyone.

> If Caddy aims for the "Long Tail", tinkerers, and docker-based developer machines, the current limitations are OK. But if Caddy is to be used in enterprises, it will need SANs. (speaking from experience with a concrete enterprise deployment)

I also speak from experience. Enterprise software is notoriously bloated, unmaintained, and does not get patched well.

> Of these, web servers support SNI, but mail and other servers often do not. Even when they do, mail and other clients do not support SNI (e.g Outlook Mail Client, arguably the most used email client in the enterprise world, does not).

SAN and SNI are orthogonal concepts. You do not need SAN if you do not have SNI. You can configure Caddy (and other servers) to serve up a certificate in the absence of SNI.

> Which brings me to what I had to do at the enterprise deployment I worked with: I had to pull Caddy off the production server and replace it with Nginx, with the certificates managed by certbot.

Using SAN certificates will significantly reduce the reliability and of your certificate management system.

If your enterprise wants to use Caddy, we'd be happy to arrange a development contract to support the functionality you need, tailored just to your business. Contact us here: https://caddyserver.com/business - but if you demand this for free, it's not gonna happen.

> PS. Yes, we were affected by the Let's Encrypt CAA Rechecking bug and we did not have to touch a single thing. Certbot's automated renewal, which is part of the default installation of certbot, did the job brilliantly.

You just got lucky then with regards to your regular renewal date. CertBot was not designed for this contingency, however there was some window where force renewal wasn't required thanks to how OCSP and the scheduling of the revocations worked together:

- https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864/185?u=mholt)

> I got lucky. I renewed my certificate on the 29th of February. I didn’t get an email and only learned of the bug today. 

- https://community.letsencrypt.org/t/revoking-certain-certificates-on-march-4/114864/17?u=mholt

>  no, certbot do not check the revocation status, only the expiration date: https://github.com/certbot/certbot/issues/1028 41
>
> And, after the revocation, the previous (valid) OCSP response may be cached for a few days. So the revocation status may appear a few days later.

- https://community.letsencrypt.org/t/force-renewing-of-all-needed-certificates-with-certbot/115139/2?u=mholt

> Unfortunately, this means we need to revoke the certificates that were affected by this bug, which includes one or more of your certificates. To avoid disruption, you’ll need to renew and replace your affected certificate(s) by Wednesday, March 4, 2020. We sincerely apologize for the issue.
> 
> If you’re not able to renew your certificate by March 4, the date we are required to revoke these certificates, visitors to your site will see security warnings until you do renew the certificate. Your ACME client documentation should explain how to renew.
>
> If you are using Certbot, the command to renew is:
>
> `certbot renew --force-renewal`

Going to close this thread, since it's well past its expiration. Further discussion can happen on the forum: https://caddy.community
