### ISSUE TITLE
Feature request: create PPA.

### ISSUE THREAD

**Issue by skorokithakis** [mholt/caddy#832]
Would it be possible to create a PPA for Caddy? As a web server, getting security releases quickly is very important, and a PPA would help with that by integrating caddy with the system's package manager.

**Comment by DenBeke** [comment]
Someone mentioned that he was working on it on Gitter a while ago, but don't know who anymore and what resulted out of it...
Maybe someone else remembers?

**Comment by elcore** [comment]
Hello @skorokithakis and @DenBeke,

the PPA is located here :smile: --> https://launchpad.net/~hduran-8/+archive/ubuntu/caddy

**Comment by skorokithakis** [comment]
Fantastic, thank you!

**Comment by davidak** [comment]
what add-ons are included?

**Comment by elcore** [comment]
I don't know @davidak

**Comment by mholt** [comment]
Packaging Caddy for distros can be discussed at https://forum.caddyserver.com now!

**Comment by kokizzu** [comment]
@elcore need update 0.10.2 now :3

**Comment by elcore** [comment]
> @elcore need update 0.10.2 now :3

Sorry, I am not responsible for the PPA

**Comment by arjun-menon** [comment]
Just as a note, [the PPA](https://launchpad.net/~hduran-8/+archive/ubuntu/caddy) hasn't been updated in aeons. (It was last updated **2½ years ago**, in Jan 2017.)
