### ISSUE TITLE
Full-on crash

### ISSUE THREAD

**Issue by faddat** [mholt/caddy#841]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3

#### 2. What are you trying to do?
Host web sites?  

More seriously, caddfile uses hugo, proxy, and regular old "serve this folder"

#### 3. What is your entire Caddyfile?
```
jacobgadikian.com www.jacobgadikian.com {
gzip
tls             email=jake@klouds.org
root            /jacobgadikian/public   
basicauth       /admin ******************(redacted)
hugo            /jacobgadikian/        
}

kloudery.com www.kloudery.com {
gzip
tls             email=jake@klouds.org
root            /kloudsweb
}

blog.kloudery.com {
tls             email=jake@klouds.org
proxy           localhost:32768 blog.kloudery.com
gzip
}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemctl restart caddy

and here's the unit file:

[Unit]
Description=Caddy Web Server

[Service]
ExecStart=/usr/bin/caddy -conf /root/Caddyfile

[Install]
WantedBy=multi-user.target

#### 5. What did you expect to see?
Well, what I wasn't expecting was (see below) anyway...

#### 6. What did you see instead (give full error messages and/or log)?
● caddy.service - Caddy Web Server
   Loaded: loaded (/etc/systemd/system/caddy.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2016-05-21 07:16:12 UTC; 7s ago
  Process: 30212 ExecStart=/usr/bin/caddy -conf /root/Caddyfile (code=exited, status=2)
 Main PID: 30212 (code=exited, status=2)

May 21 07:16:12 fuzzbox2 caddy[30212]: /home/caddy/go/src/github.com/hacdias/caddy-hugo/hugo.go:54 +0x3ff
May 21 07:16:12 fuzzbox2 caddy[30212]: github.com/mholt/caddy/caddy.loadConfigs(0x7ffcca5f2f8c, 0x9, 0x7fa0cbf5f4e0, 0xc820226480, 0x0, 0x0, 0x0, 0x0, 0x0)
May 21 07:16:12 fuzzbox2 caddy[30212]: /tmp/custombuild_1635_943691114/src/github.com/mholt/caddy/caddy/config.go:166 +0xa15
May 21 07:16:12 fuzzbox2 caddy[30212]: github.com/mholt/caddy/caddy.Start(0x7fa0cbf23a10, 0xc820226450, 0x0, 0x0)
May 21 07:16:12 fuzzbox2 caddy[30212]: /tmp/custombuild_1635_943691114/src/github.com/mholt/caddy/caddy/caddy.go:145 +0x25a
May 21 07:16:12 fuzzbox2 caddy[30212]: main.main()
May 21 07:16:12 fuzzbox2 caddy[30212]: /tmp/custombuild_1635_943691114/src/github.com/mholt/caddy/main.go:102 +0x9c6
May 21 07:16:12 fuzzbox2 systemd[1]: caddy.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 21 07:16:12 fuzzbox2 systemd[1]: caddy.service: Unit entered failed state.
May 21 07:16:12 fuzzbox2 systemd[1]: caddy.service: Failed with result 'exit-code'.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

I do not know.

**Comment by faddat** [comment]
Tried directions in #840, did not resolve the crash.

**Comment by faddat** [comment]
Here's my systemd unit:

```
[Unit]
Description=Caddy web server
After=network.target

[Service]
; an empty value clears the original (and preceding) settings
ExecStart=
ExecStart=/usr/bin/caddy -conf="/root/Caddyfile"

[Install]
WantedBy=multi-user.target
```

**Comment by wmark** [comment]
This doesn't seem to be related to systemd. Does Caddy/Hugo panic when started without an init daemon?

**Comment by faddat** [comment]
let me check.

**Comment by faddat** [comment]
I'd had my working directory for hugo misconfigured.  Thanks @wmark!
