### ISSUE TITLE
Rewrite rules for Angular.js html5 mode

### ISSUE THREAD

**Issue by Mandeep03** [mholt/caddy#842]
Need help with rewrite rules for Angular.js html5 mode, Basically redirecting user to use index.html on every 404.

In Apache:
```
RewriteEngine On  
# If an existing asset or directory is requested go to it as it is
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
RewriteRule ^ - [L]

# If the requested resource doesn't exist, use index.html
RewriteRule ^ /index.html
```

**Comment by elcore** [comment]
Hello @Mandeep03,

this is not an issue! -- Please go to https://gitter.im/caddyserver/support for support

**Comment by Mandeep03** [comment]
Well, thanks anyways.

**Comment by elcore** [comment]
Hello @Mandeep03,

We are always here to "help" ;) -- Good Luck

**Comment by abiosoft** [comment]
Firstly, it is preferred to use support for this as @elcore stated. Then, this looks straightforward and I would suggest you check out the docs first.

Finally, not using the issue template and not sharing Caddyfile gives the impression you have not bothered to try it out yourself. That is not encouraging.

```
rewrite {
    to {path} {path}/ /index.html
}
```

**Comment by Arman92** [comment]
For anyone else wondering, in order to preserve the URI (child routes of Angular), emit the index.html, resulting the below rewrite:

    rewrite {
        to {path} {path}/ /
    }
