### ISSUE TITLE
Option to remove ETag header

### ISSUE THREAD

**Issue by yene** [mholt/caddy#843]
Caddy 0.8.3

Problem
* cannot remove ETag header in config

**Comment by mholt** [comment]
I'm not sure I understand the reasons, what is wrong with having the ETag header?

**Comment by yene** [comment]
Sorry nothing wrong with it, I just wanted to disable it, for testing and playing around. 

But could not do so in the config, so I compiled my own version.

**Comment by mholt** [comment]
Hmm, gonna close this but mark it as deferred (so we'll come back to it) since there isn't apparently anything wrong with it yet. Thanks for raising the issue though.

**Comment by mholt** [comment]
I'm pretty sure I've done this when testing v2, so I think this is now done.
