### ISSUE TITLE
Filename extension in browse templates

### ISSUE THREAD

**Issue by kaihendry** [mholt/caddy#844]
#### 1. What version of Caddy are you running (`caddy -version`)?

 374d0a3

#### 2. What are you trying to do?

Making a image gallery, but I need to create a template that only rewrites the JPGs.

The idea (better ideas welcome) is to create a template like `{{if eq path.Ext(.Name) "jpg"}}<img src=/thumb/?f={{.URL}}&width=200>{{.Name}}{{end}}` and create a [**/thumb** service](https://github.com/kaihendry/caddy-thumb) to resize and cache the image.

#### 3. What is your entire Caddyfile?

http://s.natalian.org/2016-05-24/Caddyfile

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`

#### 5. What did you expect to see?

Just jpegs in the browse template.

#### 6. What did you see instead (give full error messages and/or log)?

<img src=http://s.natalian.org/2016-05-24/ext.png>

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

* http://s.natalian.org/2016-05-24/Caddyfile
* http://s.natalian.org/2016-05-24/gallery.tpl

I do realise from

* https://caddyserver.com/docs/browse
* https://caddyserver.com/docs/template-actions
* https://github.com/mholt/caddy/blob/master/middleware/browse/browse.go#L102 be best if Fileinfo had **media type**

Anyway, I have noticed you have exposed some functions, but not path.Ext which I think I need here to filter by JPEG since you don't seem to expose the file type?

**Comment by mholt** [comment]
So basically you would like a way to know the file type or extension from a template. We could look into that.
