### ISSUE TITLE
PHP REMOTE_ADDR coming in as `[::1]` instead of `::1`.

### ISSUE THREAD

**Issue by nesl247** [mholt/caddy#845]
*If you are filing a bug report, please answer these questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!*

#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.2

#### 2. What are you trying to do?
Run Symfony

#### 3. What is your entire Caddyfile?
```text
http://shop-front.localhost:8000
root /Volumes/Code/shop-front/web
gzip

rewrite {
  to {path} {path}/ /app_dev.php?{query}
}

fastcgi / 127.0.0.1:9000 php {
  index app_dev.php
}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy`. I'm using php70 and caddy from homebrew on OS X 10.11.

#### 5. What did you expect to see?
`$_SERVER['REMOTE_ADDR']` in PHP should be `'::1'`.

#### 6. What did you see instead (give full error messages and/or log)?
`$_SERVER['REMOTE_ADDR']` in PHP is `'[::1]'`

**Comment by elcore** [comment]
Hello @nesl247,

this issue is related to PHP and not Caddy!!!

`<?php
        echo $_SERVER['REMOTE_ADDR'];
?>
`

Result: 123.111.222.3

**Comment by mholt** [comment]
Hmm, indeed we should probably strip the brackets: http://stackoverflow.com/a/10318990/1048862

Thanks for the report @nesl247. This is an easy fix, I invite someone who is new to Go or this project to get involved and submit a pull request!
