### ISSUE TITLE
Follow XDG Base Dir Spec

### ISSUE THREAD

**Issue by nesl247** [mholt/caddy#847]
Caddy should probably support https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html rather than writing to `$HOME/.caddy`.

While OS X doesn't follow this, linux does. The behavior I've seen frequently enough is to just always use the basedir spec regardless of platform. It makes it easier.

**Comment by nesl247** [comment]
The following is a WIP patch for this. I followed the handling of paths from NeoVim which followed ActiveState which based it off of MSDN docs. 

I didn't submit this as a PR because technically this should be `$XDG_DATA_HOME` instead of `XDG_CONFIG_HOME`. XDG specifies a multitude of directories, with config and data being the ones we would need. From what I can see, the current use for `~/.caddy` is for ssl certs. I'm not 100% sure if that should be considered configuration or data.

If it is data, then we need to be able to support two types of paths, data and configuration. I think I could figure that out, but didn't want to waste my time doing all that if it wasn't going to be used.

The other question I have is that when I went to go do the tests (which I started with, I try to follow TDD), I had no idea on how to stub/mock the `os` package to be able to write tests for each of the different branches. Maybe that's not how things are done in golang, or just in caddy, but it was definitely something I could use help with.

```
diff --git a/caddy/assets/path.go b/caddy/assets/path.go
index 46b883b..bd3469b 100644
--- a/caddy/assets/path.go
+++ b/caddy/assets/path.go
@@ -8,22 +8,21 @@ import (
 
 // Path returns the path to the folder
 // where the application may store data. This
-// currently resolves to ~/.caddy
+// currently resolves to $XDG_HOME_CONFIG/caddy
 func Path() string {
-	return filepath.Join(userHomeDir(), ".caddy")
+	return filepath.Join(userHomeDir(), "caddy")
 }
 
 // userHomeDir returns the user's home directory according to
 // environment variables.
-//
-// Credit: http://stackoverflow.com/a/7922977/1048862
 func userHomeDir() string {
 	if runtime.GOOS == "windows" {
-		home := os.Getenv("HOMEDRIVE") + os.Getenv("HOMEPATH")
-		if home == "" {
-			home = os.Getenv("USERPROFILE")
-		}
-		return home
+		os.Getenv("LOCALAPPDATA")
 	}
-	return os.Getenv("HOME")
+
+	home := os.Getenv("XDG_CONFIG_HOME")
+	if home == "" {
+		home = filepath.Join(os.Getenv("HOME"), ".config")
+	}
+	return home
 }
diff --git a/caddy/assets/path_test.go b/caddy/assets/path_test.go
index 374f813..d2c0ab2 100644
--- a/caddy/assets/path_test.go
+++ b/caddy/assets/path_test.go
@@ -6,7 +6,7 @@ import (
 )
 
 func TestPath(t *testing.T) {
-	if actual := Path(); !strings.HasSuffix(actual, ".caddy") {
+	if actual := Path(); !strings.HasSuffix(actual, "caddy") {
 		t.Errorf("Expected path to be a .caddy folder, got: %v", actual)
 	}
 }
```

**Comment by elcore** [comment]
Hello @nesl247,

I don't like this :-1: -- no backwards compatibility

**Comment by nesl247** [comment]
It's not a final patch anyways, so backwards compatibility could be added into it if that's what would be wanted. I had just started messing around with the idea. A few things I've used, including neovim, didn't go with backwards compatibility so that's what I'm used to.

**Comment by mholt** [comment]
Hey @nesl247, thanks for your feedback and the patch work. You say:

> Caddy should probably support https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html rather than writing to $HOME/.caddy.

But can you give concrete reasons that the added complexity is necessary?

**Comment by nesl247** [comment]
It's not that it's necessary, but everything I know is moving towards supporting it. I enjoy having less in the root of my $HOME, so I've enjoyed seeing more and more software support the spec.

While it's a bit more complex, it's kind of an expectation more and more people are having as well.

**Comment by mholt** [comment]
I was actually considering supporting a `CADDYPATH` environment variable to override the default `$HOME/.caddy` location. How about that? I don't see a need to store Caddy's assets in different places...

**Comment by nesl247** [comment]
I guess it's better than nothing, but I'm a big believer in following specs and not creating a custom thing. If only one directory were to be used, I'd still prefer to see `XDG_CONFIG_HOME` supported.

**Comment by mholt** [comment]
Okay. I'll consider this before the 0.9 rewrite is complete. Thanks!

**Comment by mholt** [comment]
@nesl247 Let's trial your change, but with some slight modifications:

- If CADDYPATH is set, use that.
- If XDG_CONFIG_HOME is set, use `$XDG_CONFIG_HOME/.caddy` (with dot, for consistency)
- Otherwise, use $HOME/.caddy

Tests would be good too! We have an opportunity to improve coverage here.

Note that the assets file moved to [assets.go](https://github.com/mholt/caddy/blob/master/assets.go).

If there is more demand for XDG base dir support, I will add docs for it, but for now, I think we'll leave it undocumented so we don't have to promise anything. (I hesitate to lock it in because of the added complexity that I'm not totally convinced yet is necessary. But I do appreciate your feedback!)

**Comment by nesl247** [comment]
Hey @mholt,

So to actually follow the spec, but still support CADDYPATH, it would actually have to be like:

* Use `$CADDYPATH`
* Use `$XDG_CONFIG_HOME` (`$XDG_CONFIG_HOME/caddy` - without dot to follow spec)
* Use `$HOME/.config/caddy` or `%LOCALAPPDATA%\caddy` on Windows

The spec isn't something that can really be trialed as the procedure you gave breaks the spec. XDG is something that's being expected of applications more and more because it clears away the clutter, and makes it easier to see what configuration there is.

The reason it has to be the way I mentioned above is because the spec itself states that if `$XDG_CONFIG_HOME` isn't set, you must use `$HOME/.config` instead.

For the Windows support, there's no reason to not support XDG if someone has taken the time to edit their PATH for it (not something supported out of the box), so the fallback is for the local appdata. This gets it out of the `%USERPROFILE%`, which is something that annoys me to no end on apps that get ported to Linux, since Windows doesn't hide dotfiles.

The `CADDYPATH` bit is perfectly fine to be there even if we officially supported the spec because it's a user definable path override.

There's really not too much complexity here in my opinion, especially as it's what is expected by default on Linux these days. I'd like to hear what you think before I go trying to implement this. It won't be something I do really quickly because as simple as this is, learning how to write the tests in go will probably be the harder part, and I think this is definitely something that shouldn't be accepted without tests.

**Comment by mholt** [comment]
I'm not really keen on moving the folder at this time, but maybe before the 0.10 betas or before 1.0 it would be acceptable to make that change. We can look into it then. While I think, for right now, the CADDYPATH override will do fine, I really, really appreciate your thorough treatment of the topic! Thank you!

I will close but mark as deferred to be sure we revisit this later.

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
It's been 3 years now, is there at least a CADDYPATH variable now?

**Comment by mholt** [comment]
Caddy 2 follows the XDG spec. Please take a look in the v2 branch and let me know if you think any changes need to be made!

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
Just tried it out, if I'm not mistaken, it generally doesn't use config files at all? That's one way of following the spec lol.

Great to see though, can't wait for v2.

**Comment by mholt** [comment]
@BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F 

> Just tried it out, if I'm not mistaken, it generally doesn't use config files at all? That's one way of following the spec lol.

The use of config files is irrelevant; Caddy has to store resources on disk somewhere, so the XDG spec is used (i.e. environment variables conforming to the names and purposes outlined in that spec). These paths can be overridden in Caddy's config, of course, but by default it conforms to XDG. It should, anyway. Feel free to try it out and verify!
