### ISSUE TITLE
[Question] Does Caddy support functionality similar to Nginx "resolver"

### ISSUE THREAD

**Issue by d6u** [mholt/caddy#848]
**Does Caddy support functionality similar to Nginx "resolver"?**

Like what the author trying to do with "resolver" directive here https://tenzer.dk/nginx-with-dynamic-upstreams/

Basically, the upstream I'm proxying will change on each deployments

```
resolver 172.16.0.23;
set $upstream_endpoint http://some-internal-domain;
location / {
    proxy_pass $upstream_endpoint;
}
```

`172.16.0.23` will be the DNS server IP, `http://some-internal-domain` will resolve to multiple A records.

**Comment by abiosoft** [comment]
No, it doesn't.

**Comment by ghostsquad** [comment]
Any chance this will change in the future?
