### ISSUE TITLE
TLS Client certs with virtual hosts

### ISSUE THREAD

**Issue by ydnax** [mholt/caddy#849]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3

#### 2. What are you trying to do?
Use some (https)vhosts with tls client certificates and some without

#### 3. What is your entire Caddyfile?
```text
https://da.ds.example.com, https://ical.ds.example.com {
        gzip
        proxy /  127.0.0.1:5232

}


pgit.ds.example.com {
        gzip
        proxy / localhost:3000
        tls {
                clients clients_ca.crt
        }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
currently testing on a raspberry pi 2
```
./caddy -email=my.email@example.com
```

#### 5. What did you expect to see?
Normal page if i visit https://da.ds.example.com

#### 6. What did you see instead (give full error messages and/or log)?
Connection fails if no client certificate is provided

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Use the caddy file with different domains and curl/wget the domain without the additional tls directive.

**Comment by elcore** [comment]
Hello @ydnax,

related to #829 and golang/go#15707

**Comment by mholt** [comment]
Thanks for the report @ydnax , I agree this functionality would be nice :smile: Right now the client cert applies to the whole listener, not just certain names. Anyone is welcome to submit a CL to the Go project to support it, I don't have time for it right now.

**Comment by mholt** [comment]
@ydnax Good news, looks like Go 1.8 will probably ship with this feature, so Caddy can take advantage of it. https://go-review.googlesource.com/#/c/30790/
