### ISSUE TITLE
Proxy Stops Working if Destination Server is Killed / Restarted

### ISSUE THREAD

**Issue by orware** [mholt/caddy#853]
So I'm intending to use Caddy as a web proxy server for some new projects due to it's simplicity/ease of setup and to start things off I've set it up as a proxy server to a new Java-based server that will be handling our Single Sign On stuff.

However earlier today I was making an observation.

I had the Caddy process running on the web proxy server (which is a separate virtual machine) while on the SSO server I had a Java-based server process running.

What I noticed was that if I killed/restarted the Java server process, Caddy would stop responding to requests even after the Java server process had fully restarted (I would get the 502 Bad Gateway error from the Caddy side).

If I then killed the Caddy process and restarted it, it started properly responding to the requests again.

However this doesn't feel like correct behavior to me (I feel like the Caddy side should automatically pick and respond to the Java server when it comes back online, rather than continuing to display the 502 Bad Gateway error.

#### 1. What version of Caddy are you running (`caddy -version`)?

I'm running version 0.8.3.

#### 2. What are you trying to do?

Trying to setup Caddy as a reliable proxy server.

#### 3. What is your entire Caddyfile?
```text
https://sso.imperial.edu {  
    proxy / https://apps-xe-identity.imperial.edu:9443 {
		health_check /health
		proxy_header Host {host}
		proxy_header X-Real-IP {remote}
		proxy_header X-Forwarded-Proto {scheme}
	}
    
	#tls C:/caddy/ssl/star_imperial_edu_cert.pem C:/caddy/ssl/star_imperial_edu_key.pem
	
	errors {
		log ../logs/sso_imperial_edu_error.log {
			size 50 # Rotate after 50 MB
			age  30 # Keep rotated files for 30 days
			keep 5  # Keep at most 5 log files
		}
	}

	log ../logs/sso_imperial_edu_access.log {
		rotate {
			size 100 # Rotate after 100 MB
			age  14  # Keep log files for 14 days
			keep 10  # Keep at most 10 log files
		}
	}
	
	#gzip
}

# Redirect HTTP requests to HTTPS
http://sso.imperial.edu {  
    redir https://sso.imperial.edu{uri} 301
	log ../logs/access.log {
		rotate {
			size 100 # Rotate after 100 MB
			age  14  # Keep log files for 14 days
			keep 10  # Keep at most 10 log files
		}
	}
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

On the Caddy server side of things I'm running in a Windows Server 2012 R2 environment and have just manually started caddy from the same directory as the Caddyfile.

The Java side is a different VM running on Redhat Linux.

#### 5. What did you expect to see?

I expected the Caddy side of things to automatically start re-responding to the Java server's requests after the Java server had been killed/restarted.

#### 6. What did you see instead (give full error messages and/or log)?

Instead I only seem to see 502 Bad Gateway errors after stopping/restarting the Java server process.

It's not until I stop and start the caddy process again that it starts responding correctly to requests.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Well, I haven't spent enough time with caddy to know whether or not this would occur in general for other types of proxy setups (aside from the one to the Java server I'm trying to use right now) or if it's a different issue, but if it is a general proxy issue then you should be able to replicate it with a different proxy process by killing/restarting it and then observing if caddy starts throwing the 502 Bad Gateway error after the proxy service is already back up again. If it does, then you can further verify the current fix I've noticed, which is to stop / restart caddy again to fix the issue.

I'm hoping there's a possible fix for this, since it seems to me the way it's behaving right now would be counter productive to using caddy in a production environment (where the proxied services would need to be restarted occasionally...it seems like it would be a shame if every time that occurred it required me to also restart caddy.

Thank you for your time, I hope I was able to explain the situation well enough to understand easily!

**Comment by mholt** [comment]
> What I noticed was that if I killed/restarted the Java server process, Caddy would stop responding to requests even after the Java server process had fully restarted (I would get the 502 Bad Gateway error from the Caddy side).

This is probably because Caddy marks the backend as down when requests to it fail. The default duration is 10s (according to [the docs](https://caddyserver.com/docs/proxy)).

See issue #667 which, I believe, is the same thing. If you think so, then let's close this issue and redirect all discussion to that one. Thanks!

**Comment by orware** [comment]
Good morning Matt,

I was just reading through #667 and it does seem likely it is the probably the same issue.

I'm going to go ahead and try the max_fails 0 option on my end to see if it helps fix things, though I'm also curious if the other option mentioned in that issue (max_fails == upstreams-1) is already available too?

Right now we're mainly using Caddy for the SSL termination functionality (since we don't do a lot of load balancing on our end) so that's likely why it was pretty easy for us to run into this issue.

The only extra comment I wanted to add is that I'm pretty confident I waited longer than 10 seconds on my end, so Caddy seemed to be returning those 502 Gateway errors continuously and didn't seem to recover automatically after the initial 10 seconds had passed.

I'll be doing some more testing with this particular new server today so I'll try running some additional tests with Caddy and report back on how things go.

**Comment by orware** [comment]
Hi Matt,

I just went ahead and retried on my end after adding the max_fails 0 directive into my Caddyfile but the same issue persisted.

Test 1 (Before making any changes to the Caddyfile)
- Site was left up and running over the weekend so my tests this morning coming into the office worked fine and Caddy correctly proxied the requests to the other Java server.
- Killed the process on the Java server and restarted it.
- Started receiving 502 Bad Gateway errors from Caddy.
- Waited for a while then retested. Still was receiving 502 Bad Gateway errors.
- Restarted Caddy server process
- Caddy started responding to the proxy requests correctly again.

Test 2 (After making the addition of max_fails 0 to my Caddyfile):
- After making the change I restarted the Caddy process on my end, so at this point requests are being responded to correctly.
- I then killed the Java server process again, waited a few moments then started it up again.
- Once it was up I went back to Caddy and retried.
- Waited for a bit (longer than 10 seconds) and retried again.
- Left it up and running as I started writing this message (so a few minutes now) and retried again and still received the 502 Bad Gateway error.
- Just restarted the Caddy process again and instantly it started responding to the requests properly again.

-

**Comment by orware** [comment]
I wanted to find out if the same issue seemed to occur with a different server where I'm also using Caddy and it didn't seem to occur over there (it recovered properly after the proxied service came back online).

So doing some comparison between the settings, one that hadn't been working as I expected it to anyway (the health check option) seemed like a likely candidate for me to try and remove.

After removing the health_check /health line from my config and restarting Caddy I went and retried the stop/restart test of the Java server and this time Caddy seemed to come back to life as expected when the Java server process came back online.

I didn't look closely at the health_check option to be honest (my thought was that it was more of a virtual path where you could quickly check, from Caddy's perspective, of whether or not the host was online or not...but reading the description it seems that it actually points to a real path on the server?).

So maybe the fact that I had the health_check option in there pointing to a non-existing location kept Caddy thinking that the server was non-responsive somehow?

**Comment by mholt** [comment]
@orware Probably, if the healthcheck returns an error status (like 404) it is considered down. I've made a minor change locally to the docs to make that clearer. :smile:

Let me know if there's any other issues you encounter about this!
