### ISSUE TITLE
Redirects and rewrites that prevent duplicate content

### ISSUE THREAD

**Issue by razor-x** [mholt/caddy#856]
Caddy has limited tools for preventing [duplicate content](https://support.google.com/webmasters/answer/66359?hl=en).

Here is a common situation for a static site. Suppose I am serving `example.com` with the files

```
./index.html
./about.html
./example/index.html
```

Let's assume I will use `ext .html` in my Caddyfile, but most of the issues below still apply without using `ext`.
1. The content of `index.html` is served at `https://example.com/` AND `https://example.com/index.html`.
2. The content of `./example/index.html` is served at `https://example.com/example/` AND `https://example.com/example/index.html`. Caddy forces a redirect from `https://example.com/example` to `https://example.com/example/`
3. The content of `./about.html` is served at `https://example.com/about` AND `https://example.com/about.html`.
4. The location `https://example.com/about/` returns a 404 error.

Now, what can I do with Caddy to fix any of these?

Note that `rewrite` cannot solve any of these issues since rewrite does not support a redriect code (e.g., [like NGINX does](http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite)).
1. I can manually redirect `/index.html` to `https://example.com/`.
2. I can manually redirect `/example/index.html` to `https://example.com/`, **BUT** `redir` is not dynamic, so I would need a manual redirect for EVERY page like this (intractable).
3. Same issue as 2.
4. I could add a rewrite rule so `https://example.com/about/` serves `https://example.com/about`, and I might be able to make this dynamic to handle all such cases, but then I've created a new duplicate content issue where the about page is served from 3 URIs.

Finally, suppose I want to be consistent and all decide all locations should be served without a terminal `/`. Then `https://example.com/about` works fine, but there is no way to serve from `https://example.com/example` since Caddy automatically redirects this to `https://example.com/example/`.

Or suppose I want to opposite: always have a terminal `/`. Then I'm back to adding manual rewrites for all paths and introducing more duplicate content issues.

I believe most or all of these issues could be solved by giving `rewrite` a redirect option and removing the forced directory redirect.

**Comment by mholt** [comment]
Hey @razor-x, sorry it took me so long to get around to responding to this!

It seems that you are asking about dynamic redirects; that is only one of the suggestions on the linked article. The rest are mainly content-related, regardless of the web server being used.

If we give `rewrite` the ability to redirect, how would it differ from `redir`? Would we even need `redir` anymore? @abiosoft, what do you think.

**Comment by abiosoft** [comment]
I once considered having a special case for rewrite that is going to allow redirection. However, this will only get confusing for the average user, make redir somewhat redundant and will make the already complex rewrite syntax even more complex.

I personally think rewrite should not redirect, but it can be implemented. I will like to know other opinions too.

**Comment by razor-x** [comment]
No worries @mholt. Yes, "dynamic redirects" is the general solution to this issue, with the caveat that the below might still be an issue:

> Finally, suppose I want to be consistent and all decide all locations should be served without a terminal `/`. Then `https://example.com/about` works fine, but there is no way to serve from `https://example.com/example` since Caddy automatically redirects this to `https://example.com/example/`.

-
> rewrite is, by definition, internal and invisible to the client. redir is not

If this functionally gets added, then putting it into rewrite breaks that current definition / logical separation (but I suppose the functionality becomes more consistent with other web servers). I agree it further complicates the rewrite syntax, and it's unclear if one would need the other directives when using the redir mode.

I'd favor implementing it as dynamic redirects, expanding the `from` / `to` syntax to parallel rewrite (with concerns for backwards compatibility here).

**Comment by abiosoft** [comment]
If this is gonna be done, what I have in mind is any `to` prefixed with scheme `http(s)://` will perform a 302 redirect.

That's 99% of use case anyway (I hope). Any user interested in more flexibility should use **redir**.

**Comment by mholt** [comment]
I still don't know about rewrite doing redirects. Does redir need more dynamic functionality?

About the trailing forward slash @razor-x, unless you're serving a directory, don't append your URI's path with a forward slash.

**Comment by razor-x** [comment]
@mholt Not sure if we are on the same page, but to clarify: yes I want to serve without the forward slash.

Even in the case where I am serving `https://example.com/example/index.html`, I want it from `https://example.com/example` in order to present a consistent experience. (There are cases when this file structure may be unavoidable, but the user should never know. E.g., it is the standard setup when not using `ext`.)
 
We also want to be sure the user gets (redirected) to the correct page even if they type the last `/`. Since this varies from site to site, they may be predisposed to type it or leave it off. Or there may be lots of links out in the wild that have the trailing slash, but now shouldn't but can't be updated, e.g., in the case where a blogger switches to the relatively new practice introduced by `ext` or the recent version of Jekyll.

**Comment by mholt** [comment]
[Caddy will automatically redirect](https://github.com/mholt/caddy/blob/6db4771aa851a0d6a4dfc074b698dbcb53bd7605/caddyhttp/staticfiles/fileserver.go#L79-L93) requests to a directory to have the trailing slash, and it will redirect requests to a file to _not_ have the trailing slash. So you needn't worry about that. (Of course, ext or rewrite can alter that behavior.)

> Even in the case where I am serving https://example.com/example/index.html, I want it from https://example.com/example in order to present a consistent experience.

I use the `ext` directive to do this on all my websites, I just don't use index.html files. I kind of think of index files as a legacy way to serve clean URLs, and I don't recommend it to anyone going forward.

**Comment by razor-x** [comment]
> Caddy will automatically redirect requests to a directory to have the trailing slash, and it will redirect requests to a file to not have the trailing slash.

Yes that works correctly.

> (Of course, ext or rewrite can alter that behavior.)

I don't think it alters it, but rather just returns 404 when serving `/example/` (rather then redirecting to `/example`. I understand that Caddy is giving 404 since the directory doesn't exist, but that makes for a bad user experience.

> I use the ext directive to do this on all my websites, I just don't use index.html files. I kind of think of index files as a legacy way to serve clean URLs, and I don't recommend it to anyone going forward.

Completely agree, but for those in transition, right now it's all or nothing in terms on consistency (without the redirs to mask the difference). Also, using the old way currently protects against those pesky 404s, unlike ext.

**Comment by hernandev** [comment]
After playing around. found a solution, Caddy already supports it!

rewrite {
   to {path} {path}/ /index.php?{query}
 }

try path as file
try path as folder
fallback to the php parsing

**Comment by mholt** [comment]
So, thinking on this a little more (and more than a year later), here's how things are from what I understand:

- Caddy redirects non-canonical paths like `/index.html` to `/` by default
- Accessing a directory without a trailing slash or a file with a trailing slash violates the semantics of URLs, so I'm not inclined to make a way to change this behavior
- Using `ext` adds a way to access a URL but does not enforce it as the only way; however, why would a site owner link to both variations? The site should use one or the other.

> I understand that Caddy is giving 404 since the directory doesn't exist, but that makes for a bad user experience.

I'm not so sure about that, as long as your links are consistent.

URLs and file paths are finicky, and there's nothing new about that. We could look into making `ext` have an optional setting that enforces "my way or the highway" (in other words, if a request with an extension comes in that shouldn't have an extension, a redirect is issued), but this extra redirect seems unnecessary when the original request already had a correct URI to a file. I guess the argument comes down to whether ext enforces "canonical" URLs or just "pretty" or "convenient" URLs (which was my original intent).

But I'm pretty set on the slash thing.

I'll close this issue since there's nothing directly actionable with it that I can see, but discussion is still welcome on it.

**Comment by fanybook** [comment]
> Hey @razor-x, sorry it took me so long to get around to responding to this!
>
>It seems that you are asking about dynamic redirects; that is only one of the suggestions on the linked article. The rest are mainly content-related, regardless of the web server being used.
>
>If we give rewrite the ability to redirect, how would it differ from redir? Would we even need redir anymore? rewrite is, by definition, internal and invisible to the client. redir is not, @abiosoft, what do you think.

But at least let the redir support regexp
