### ISSUE TITLE
Add ability to debug log http requests

### ISSUE THREAD

**Issue by klauern** [mholt/caddy#858]
#### 1. What version of Caddy are you running (`caddy -version`)?
any

#### 2. What are you trying to do?
I would like to be able to debug the incoming http request that I'm proxying to another server/service.  Specifically, I would like to debug output the HTTP headers, but it might be useful to debug the http content as well.

See this forum post for reference: https://forum.caddyserver.com/t/logging-http-headers-for-debugging/88/6?u=klauern

**Comment by mholt** [comment]
@klauern How about https://golang.org/pkg/net/http/httputil/#example_DumpRequest - run that example and see the output. Is that alright for your log entries? We can encode literal \r and \n characters and keep everything on one line...

**Comment by klauern** [comment]
@mholt I think that would be perfect!  Would this be an flag that you would set to the `log` directive?

**Comment by mholt** [comment]
It will probably be a placeholder like `{request}`.

**Comment by klauern** [comment]
Ah, so somewhere [in here][1]?

[1]: https://github.com/mholt/caddy/blob/9b4134b287cece8bce83bf5d12e37bb7c770d506/caddyhttp/httpserver/replacer.go#L44

**Comment by mholt** [comment]
Yep!
