### ISSUE TITLE
Internal Error: Controller not found

### ISSUE THREAD

**Issue by mehulsbhatt** [mholt/caddy#863]
(Are you asking for help with Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.3 

#### 2. What are you trying to do?

Configuring kanboard (https://github.com/fguillot/kanboard.git)

#### 3. What is your entire Caddyfile?
```text
https://board.ipay.co.tz {
    gzip
    root /opt/kanboard
    tls /opt/caddy/ssl/server.crt /opt/caddy/ssl/server.key {
    protocols tls1.0 tls1.2
    ciphers ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-CBC-SHA ECDHE-RSA-AES128-CBC-SHA ECDHE-ECDSA-AES256-CBC-SHA ECDHE-ECDSA-AES128-CBC-SHA RSA-AES256-CBC-SHA RSA-AES128-CBC-SHA ECDHE-RSA-3DES-EDE-CBC-SHA RSA-3DES-EDE-CBC-SHA
    }

    header / {
       Access-Control-Allow-Origin *
       Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    }

    rewrite {
       if {file} ends_with .php
       if {path} not_match ^/index\.php(/|$)
       status 404
    }

    rewrite {
        to {path} /index.php?{query}
    }

    log /var/log/caddy/kanboard_access.log {
       rotate {
         size 100
         age 30
         keep 365
       }
    }
    errors {
       log /var/log/caddy/kanboard_error.log {
         size 100
         age 30
         keep 365
       }
    }
    ipfilter / {
       rule allow
       country TZ IN
       database /usr/share/GeoIP/GeoLite2-Country.mmdb 
    }
    
    fastcgi / /var/run/php-fpm/kanboard.sock php {
       ext .php
       split .php
       index index.php
    }
}

http://board.ipay.co.tz { 
    redir https://board.ipay.co.tz{uri} 301
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Installed properly, we have Go Git (Gogs) running well

#### 5. What did you expect to see?

Its working but given error for "Internal Error: Controller not found"

#### 6. What did you see instead (give full error messages and/or log)?

There is no detailed log

**Comment by mholt** [comment]
Where are you seeing this error? And `-log` should almost always give some output.
