### ISSUE TITLE
Reverse proxy help!

### ISSUE THREAD

**Issue by LastStarFighter** [mholt/caddy#865]
Just wanted to start out and say what awesome work everyone is doing on this project! Was looking to start out and learn something new and landed here while doing some research for other servers.  I managed to get caddy setup as a reverse proxy for most of my apps but having a little trouble with the rewrite rules to work for glances WebUI.  I looked at the glances wiki and they gave these examples for Apache and Nginx:

**Apache:**

RewriteEngine on
RewriteCond %{HTTP_REFERER} ^https?://[^/]+/glances
RewriteCond %{REQUEST_URI} !^/glances
RewriteCond %{THE_REQUEST} ^GET
RewriteRule ^/(.*) /glances/$1 [QSA,R]
ProxyPass /glances/ http://localhost:61208/
ProxyPassReverse /glances/ http://localhost:61208/
Redirect permanent /glances http://host/glances/

**Nginx:**

location / {
  if ($http_referer ~ "^https?://[^/]+/glances"){
    rewrite ^/(.*) /glances/$1 redirect;
  }
}

location /glances/ {
  rewrite /glances/(.*) /$1 break;
  proxy_pass http://localhost:61208/;
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
}

Have no experience with either so not sure how to translate the rewrites over to caddy.  I'm sure this is probably something simple that i'm just not getting but any help would be greatly appreciated thanks!

**Comment by mholt** [comment]
Hey @LastStarFighter , thanks for using Caddy! And thanks for asking for help. We try to keep issues focused on development of Caddy -- would you please post your question in [our forum](https://forum.caddyserver.com)? Be sure to post what you tried, precisely what isn't working, and use proper formatting for your code blocks. That will make it easier for someone to help you. :+1:

Take a look at the [available directives](https://caddyserver.com/docs) - it has everything you need!

**Comment by LastStarFighter** [comment]
Sorry totally didn't even think about the forums. Will do, thanks!
