### ISSUE TITLE
Relative paths in import directives behave unexpected

### ISSUE THREAD

**Issue by ponychicken** [mholt/caddy#867]
The import directive seems to resolve relatives path relative to the current directory of the running command. This directory is sometimes unknown to the user. I suggest that the import directive should resolve relative to the caddyfile which specified it.

**Comment by ponychicken** [comment]
### example setup

````
/etc/caddy
-- Caddyfile
-- common/
----- php

````

#### caddyfile

````
import common/php
...

````

This only works as long as the process is run from /etc/caddy

**Comment by abiosoft** [comment]
Do you mean directory ?
>This *directive* is sometimes unknown to the user.

I disagree with making import path relative to the Caddyfile.  Apart from making it more confusing for the average user, it is not consistent with other directives.

**Comment by ponychicken** [comment]
Yes, that was a typo!

**Comment by weingart** [comment]
Possibly a clarification in the documentation to indicate relative vs. absolute paths?

**Comment by mholt** [comment]
> This directory is sometimes unknown to the user.

When is that? I feel like the user should always be aware of the cwd.

**Comment by ponychicken** [comment]
A shared hosting environment would be one example. User A has only access to one folder, into which they ftp. Now they can't use relative paths because the import will most likely fail, but absolute paths are also difficult, since they might not know the cwd.

From most languages where you are able to import something, from nodes require to css imports, the path are always relative to the path of the importinhg document, because you will never know from where the whole thing might be run. If it is not consistent with other directives, I would suggest changing them too.

**Comment by ponychicken** [comment]
for me it's an unexpected behaviour that the command `caddy --conf /etc/caddy/Caddyfile` will run differentl depending on which folder I am. Maybe it would be enough to make it relative to cwd and when the user specifies `--conf`, then that directory is used instead of cwd.

**Comment by mholt** [comment]
Hmmm, maybe this is something that should change. Import is a unique directive since it is executed during the parse phase. I guess in all reality it shouldn't matter where Caddy is run from, the import is relative to the Caddyfile (if relative at all - absolute path imports obviously don't have this problem).

**Comment by mholt** [comment]
Well, I made the change. Import paths are now relative to Caddyfile, not cwd. Hope I don't regret it later! :smile:

Let me know if you find any bugs.
