### ISSUE TITLE
setting up TLS and HTTPS

### ISSUE THREAD

**Issue by joeblew99** [mholt/caddy#87]
Cant find how to set up the config file for this.

Sorry if this is somewhere but no luck so far.

**Comment by joeblew99** [comment]
ok found it...
On CaddfyConfig docs page

**Comment by mholt** [comment]
https://caddyserver.com/docs/tls - just one line should enable https. Does that help?

**Comment by mholt** [comment]
Ah, glad you found it!

**Comment by joeblew99** [comment]
wow thats quick Matt. 

OK, from the folder that i have the caddyfile i ran: openssl req -newkey rsa:2048 -new -nodes -keyout key.pem -out cert.pem
--> Press enter for everything except CN, which is "localhost"

then I update the caddyfile with:
"
localhost
gzip
browse
ext .html
websocket /echo cat
log ../access.log
header /api Access-Control-Allow-Origin *
tls cert.pem key.pem
"

then from terminal its just "caddy", and i get the error:
localhost:2015
2015/05/24 19:21:19 crypto/tls: failed to parse certificate PEM data

**Comment by joeblew99** [comment]
Ok got it working.

No need to add the CN as localhost. Just hit enter on everything when the certs are being created.
too easy :)

**Comment by mholt** [comment]
Using `openssl req` like that generates a CSR, not a certificate. Er, I think. Try this page for more info: https://www.openssl.org/docs/HOWTO/certificates.txt

**Comment by mholt** [comment]
Okay, I guess that works then.

**Comment by joeblew99** [comment]
it works but i get these "strange" outputs form Caddy.
All i have to do is refresh a page

2015/05/24 19:29:23 error reading preface from client 127.0.0.1:59929: read tcp 127.0.0.1:59929: connection reset by peer

**Comment by mholt** [comment]
That's normal with HTTP/2, for now. They should go away as the HTTP/2 library matures.
