### ISSUE TITLE
Feature request: Continue with remaining domains/addresses, if there are an error domain

### ISSUE THREAD

**Issue by kokizzu** [mholt/caddy#872]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy (untracked dev build)

#### 2. What are you trying to do?
starting

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy

#### 5. What did you expect to see?
show warning and continue with existing non-error domains/addresses 

#### 6. What did you see instead (give full error messages and/or log)?
May 18 08:28:26 x systemd[1]: ^[[0;1;39mcaddy.service: Main process exited, code=exited, status=1/FAILURE
May 18 08:28:26 x systemd[1]: ^[[0;1;39mcaddy.service: Control process exited, code=exited status=1
May 18 08:28:26 x systemd[1]: ^[[0;1;39mcaddy.service: Unit entered failed state.
May 18 08:28:26 x systemd[1]: ^[[0;1;39mcaddy.service: Failed with result 'exit-code'.

The systemd file
```text
[Unit]
Description=Caddy reverse proxy
After=network.target

[Service]
Type=simple
User=web
Group=users
WorkingDirectory=/tmp
ExecStart=/tmp/go/bin/caddy
ExecStop=/usr/bin/killall caddy
PrivateTmp=true
ProtectSystem=full
LimitNOFILE=16384

[Install]
WantedBy=multi-user.target
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
just give at least one incorrect domain or domain that fail to resolve, eg. `foo.bar` on Caddyfile
```text
foo.bar, someotherdomainthatvalidbutfailtoresolve.com, someotherdomainthatok.com, 127.0.0.1:80 {
   gzip
	root /tmp
	proxy / 127.0.0.1:3002 {
		proxy_header Host {host}
		proxy_header X-Forwarded {remote}
		proxy_header X-Real-IP {remote}
		proxy_header X-Forwarded-Proto {scheme}
	}
}
```

**Comment by mholt** [comment]
Hi @kokizzu, thank you for your report!

In your case, Caddy is unable to obtain a certificate for a domain name that doesn't resolve, so it is unable to start successfully. The solution is to use a domain that resolves properly or disable TLS (`tls off`) but be aware that turning off TLS makes connections to the site insecure. (And it will disable TLS for all sites that share that block.)

**Comment by kokizzu** [comment]
The problem are, all my other domains is down because just that one problematic domain..

or if my internet connection down, it cannot be resolved, all sites are down even when accessing through IP address from local because caddy fail to start.

it makes higher downtime (editing the caddy file, restarting caddy)

it would be great if caddy can still run even when there are 1 domain that fails..

**Comment by mholt** [comment]
I know it can be frustrating, but I really think it's not a good idea for the server to start when it knows something is wrong or there is an error. Caddy takes a very conservative approach to error handling and this is something we believe in strongly. We've discussed it in issues past too.

> it makes higher downtime (editing the caddy file, restarting caddy)

Well, the sites were already "down" before since Caddy wasn't running at all.

If we do what you propose, just as many (if not more) people will complain that Caddy is starting even though one of the domains is broken.

**Comment by kokizzu** [comment]
> Well, the sites were already "down" before since Caddy wasn't running at all.

no the site is up before, but after editing the caddy, adding a domain, the site is down, and all other domains also down.

> I don't understand, what does your internet connection have to do with your domain resolving? Are you running a DNS server at home?

no, the DNS not yet resolved to new address (we're changing IP, since the old ISP has a problem)

**Comment by mholt** [comment]
> no the site is up before, but after editing the caddy, adding a domain, the site is down, and all other domains also down.

Caddy doesn't bring itself offline until the new configuration starts successfully, unless first you stopped Caddy and restarted it manually. Graceful restarts are with signal USR1.

**Comment by kokizzu** [comment]
yes, after adding the few domain, restarting caddy, it's down because one of them are invalid..

**Comment by mholt** [comment]
How did you restart Caddy?

**Comment by kokizzu** [comment]
`killall -9 caddy && caddy`

**Comment by mholt** [comment]
That's why. You gave caddy the KILL signal, not the reload signal. When you kill caddy, it stops serving. It doesn't provide any guarantees like USR1 does. This is documented at https://caddyserver.com/docs/cli

**Comment by kokizzu** [comment]
Ah I see, so if i use USR1, even when there is one incorrect domain, it would still serve right?

**Comment by mholt** [comment]
Yes. USR1 will not apply the new configuration if it fails to start.

**Comment by kokizzu** [comment]
Ah ok, thanks 👍
