### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by hdid** [mholt/caddy#875]
Hi.I downloaded new beta version but it gives error in running:

```
# ./caddy_linux_amd64
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x59 pc=0x4d7721]

goroutine 1 [running]:
panic(0xaf44a0, 0xc82000a0d0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mholt/caddy/caddytls.RenewManagedCertificates(0xc8200e9601, 0x0, 0x0)
        /Users/matt/Dev/src/github.com/mholt/caddy/caddytls/maintain.go:67 +0x211
github.com/mholt/caddy/caddyhttp/httpserver.activateHTTPS(0x0, 0x0)
        /Users/matt/Dev/src/github.com/mholt/caddy/caddyhttp/httpserver/https.go:37 +0x276
github.com/mholt/caddy.executeDirectives(0xc82006a120, 0xbdcb90, 0x9, 0xf91da0, 0x22, 0x22, 0xc820064700, 0x4, 0x4, 0x0, ...)
        /Users/matt/Dev/src/github.com/mholt/caddy/caddy.go:504 +0x9ec
github.com/mholt/caddy.startWithListenerFds(0x7fafb50fcb38, 0xc820014cc0, 0xc82006a120, 0x0, 0x0, 0x0)
        /Users/matt/Dev/src/github.com/mholt/caddy/caddy.go:398 +0x522
github.com/mholt/caddy.Start(0x7fafb50fcb38, 0xc820014cc0, 0x7fafb50fcb38, 0x0, 0x0)
        /Users/matt/Dev/src/github.com/mholt/caddy/caddy.go:369 +0xc8
github.com/mholt/caddy/caddy/caddymain.Run()
        /Users/matt/Dev/src/github.com/mholt/caddy/caddy/caddymain/run.go:108 +0x924
main.main()
        /Users/matt/Dev/src/github.com/mholt/caddy/caddy/main.go:6 +0x14
```

Arch is x64 (Debian)

**Comment by mholt** [comment]
Can you give a little more information? Please follow the template for reporting bugs when you create a new issue, so we can reproduce it. This gives me the stack trace but I don't know how to replicate it otherwise.

**Comment by hdid** [comment]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9-beta.1

#### 2. What are you trying to do?
Running caddy

#### 3. What is your entire Caddyfile?
```text
:2015 {
root /var/www/statico
browse
tls cassl.crt cassl.key
}

:2016 {
root /var/www/pages
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
/opt/caddy/caddy -conf="/opt/caddy/Caddyfile" > /dev/null 2>&1 &

#### 5. What did you expect to see?
With no errors

#### 6. What did you see instead (give full error messages and/or log)?
As i wrote above

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
-

And yes i'm using my own self-signed cert. While with previous versions i have not any issue!

**Comment by mholt** [comment]
Okay, I know the problem now. Thanks! Will fix soon.
