### ISSUE TITLE
Suggestion: Automatic Caddyfile indentation

### ISSUE THREAD

**Issue by Nixtren** [mholt/caddy#877]
Hey,

Is there any tool to indent Caddyfile? Perhaps Caddy could automatically indent on load (if loading from a file).

What are your thoughts?

**Comment by mholt** [comment]
Just got this same request on Twitter this morning, actually: https://twitter.com/dlsniper/status/740853956461596672

Changing the file on load is definitely a no-no (loading should be a read-only operation; changing the file would be unexpected) but I am willing to consider maybe a `caddy -fmt` to just format the file and exit. What do you think about that?

**Comment by Nixtren** [comment]
That sounds nice as well. I had the idea of automatic indentation because I was doing some edits on Caddyfile and it quickly went a mess, so I wanted to automate the formatting upon Caddy reload. But the `caddy -fmt` flag is fine, I can automate the "format & reload" operation :)

**Comment by mholt** [comment]
I mean, hitting tab isn't that hard either... and is much easier than a `-fmt` flag. :wink:

**Comment by Nixtren** [comment]
I'm using nano and got bored of typing 4 spaces every time I pressed Enter. Thanks for remembering me about the tab key, I completely forgot about it :O

**Comment by mholt** [comment]
This would only be really worth developing if it would be used by site owners. I don't see the incentive for them to do so, and thus I don't really think we need to add that feature to this code base.

Go fmt, on the other hand, is built into so many editor plugins and directly into the Go toolchain that it's even part of the CI process of many applications (including this one).

Basically, this tool would be best implemented as an editor plugin. That, and Caddyfile syntax highlighting. Any takers? Feel free to do it! I'll show it off. Heck, I'll even use it (if you make one for Sublime Text)! :smile: But I'm going to close the issue since I'm not sure it belongs in Caddy core.

Thanks for the suggestion!

**Comment by joshglendenning** [comment]
I dunno about Sublime, but for Vim users out there, I just recently made a [syntax plugin](https://github.com/joshglendenning/vim-caddyfile) for Vim.

**Comment by mholt** [comment]
@joshglendenning Cool. If you can do it without enumerating each possible directive, we'd be interested in having this a part of the official `caddyserver` org on GitHub (like [caddyserver/sublime](https://github.com/caddyserver/sublime))!

**Comment by joshglendenning** [comment]
Ah, didn't realize there was actually a sublimetext plugin! I might steal some of these regexen ;)

**Comment by mholt** [comment]
Go for it!

**Comment by Baughn** [comment]
I'm working on a structured configuration module for NixOS, which inevitably generates *very* broken indentation. Right now I'm fixing that with an awk script, but it'd be awesome (and more reliable) if caddy could do it for me.

**Comment by mholt** [comment]
@Baughn 

> (and more reliable)

I wouldn't count on it. Writing to your configuration file without the user looking?

I much rather would see this as a plugin for editors.

What's your awk script? Just curious. :)

**Comment by Baughn** [comment]
NixOS configuration files aren't supposed to be written by humans at all. They can't be, in fact.

Here's my awk script:
```awk
    awk '
      /^ *$/ { if (indent != "") next; }
      /^.*}/ { sub("  ", "", indent) }
      { 
        sub("^ *", "", $0)
        print indent, $0
      }
      /^.*{/ { indent  = indent"  " }
    ' $src > $out
```

And for comparison purposes, my (experimental) structured Caddy config and the resulting Caddyfile. Importantly, the structured config has almost precisely the same format as the nginx variant.

```
  services.caddy = {
    enable = true;
    agree = true;
    email = "sveina@gmail.com";
    virtualHosts = {
      "brage.info" = {
        forceSSL = true;
        locations."/" = {
          root = "/home/svein/web";
          extraConfig = "browse";
        };
      };
      "ar-innna.brage.info" = {
        forceSSL = true;
        locations."/" = {
          root = "/home/aquagon/web";
          extraConfig = "browse";
        };
      };
    };
```
```
 http://ar-innna.brage.info {
   redir / https://ar-innna.brage.info
   log /var/log/caddy/ar-innna.brage.info.INFO {
     size 100
     age 365
     keep 20
   }
   errors {
     log /var/log/caddy/ar-innna.brage.info.ERROR {
       size 100
       age 365
       keep 20
     }
   }
 }
 
 
 https://ar-innna.brage.info:443/ {
   root /home/aquagon/web
   log /var/log/caddy/ar-innna.brage.info.INFO {
     size 100
     age 365
     keep 20
   }
   errors {
     log /var/log/caddy/ar-innna.brage.info.ERROR {
       size 100
       age 365
       keep 20
     }
   }
   browse
 }
 
 
 http://brage.info {
   redir / https://brage.info
   log /var/log/caddy/brage.info.INFO {
     size 100
     age 365
     keep 20
   }
   errors {
     log /var/log/caddy/brage.info.ERROR {
       size 100
       age 365
       keep 20
     }
   }
 }
 
 
 https://brage.info:443/ {
   root /home/svein/web
   log /var/log/caddy/brage.info.INFO {
     size 100
     age 365
     keep 20
   }
   errors {
     log /var/log/caddy/brage.info.ERROR {
       size 100
       age 365
       keep 20
     }
   }
   browse
 }
 ```
