### ISSUE TITLE
rewrite bug with URL query

### ISSUE THREAD

**Issue by pedronasser** [mholt/caddy#884]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9 (master)

#### 2. What are you trying to do?
Use `rewrite` directive with URL on query
 
#### 3. What is your entire Caddyfile?
```text
0.0.0.0:2015
rewrite {
    r (.*)
    to /proxy/{path}?{query}
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`go run main.go`

#### 5. What did you expect to see?
Caddy should rewrite any URL without changing the query.

Example:
```
/example?url=http://caddyserver.com -> /proxy/example?url=http://caddyserver.com
```

#### 6. What did you see instead (give full error messages and/or log)?
Caddy is removing a `/` from the query.

Example
```
/example?url=http://caddyserver.com -> /proxy/example?url=http:/caddyserver.com
```
#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Just use the caddyfile

**Comment by abiosoft** [comment]
Just like I mentioned here https://github.com/mholt/caddy/pull/885#issuecomment-226404842. `path.Clean` was there for a reason.
