### ISSUE TITLE
Performance numbers

### ISSUE THREAD

**Issue by nelsonmarcos** [mholt/caddy#893]
Hi all!

Not sure if this is the right place but: do you have any performance numbers?

**Comment by mholt** [comment]
Under what conditions? Do your own benchmarks :wink:

Caddy's fast enough for most realistic use cases.

**Comment by nelsonmarcos** [comment]
Hi Matt.

I was just looking for some numbers to show my team. Since we  work on the biggest Latin America portal, those numbers could create some empathy with Caddy  :-)

Thanks for your answer!

**Comment by mholt** [comment]
@nelsonmarcos In that case I _definitely_ don't want to be responsible for problems if the benchmarks aren't _exactly_ what you need to know. I can point you in the right direction, but you'll have to do the performance tests yourself. (Many independent tests have been very promising. And Caddy is still relatively un-optimized.)

You can use `wrk` if you need req/sec, but be sure your Caddyfile is just the way you want it. My wrk tests use an empty Caddyfile so as to take advantage of Unix sendfile. If you want to see its Go code performance, you can run benchmarks using `go test` - if you need pointers on that let me know.

I used to publish performance numbers and they were up there with nginx, but if there are two divisive issues in open source, they're: 1) money and 2) benchmarks. So I withdrew the details, and now I just encourage individuals -- especially corporations with resources -- to perform their own. Thanks for understanding. :smile:

On that note, I'm happy to accept PRs that help optimize Caddy's performance (after some thorough discussion and review of course).

**Comment by somatronicon** [comment]
Yuck @mholt :-1:

Thank you for your question @nelsonmarcos!
