### ISSUE TITLE
Add repo for documentation site

### ISSUE THREAD

**Issue by shreeve** [mholt/caddy#9]
Could you add the repo for the documentation site? This would open it up to contributors as well.

Great job on Caddy, btw! Looks awesome.

**Comment by mholt** [comment]
Thank you! That's a good idea. Will get around to that soon.

**Comment by mholt** [comment]
Here it is for now: https://github.com/mholt/caddyserver.com (/cc @coolaj86)

The repo will probably move soon, but at least it's up.
