### ISSUE TITLE
timeout of 10s for some queries

### ISSUE THREAD

**Issue by miekg** [mholt/caddy#903]
This dashboard show some long timeouts for caddy <https://snapshot.raintank.io/dashboard/snapshot/DNB3UJWPJNrXKXiaIi47R716ic5Z4gdt?panelId=5&fullscreen>, if I look at the logging I think it correlates with
```
Jun 25 17:17:13 x64 caddy[5770]: 2016/06/25 17:17:13 http: TLS handshake error from 103.255.4.78:10389: EOF
Jun 25 17:17:17 x64 caddy[5770]: 2016/06/25 17:17:16 http: TLS handshake error from 212.180.175.80:56260: EOF
~~~

#### 1. What version of Caddy are you running (`caddy -version`)?
~~~
Caddy 0.9-beta.2 (+15fa5cf Fri Jun 24 09:31:02 UTC 2016)
 2 files changed, 6 insertions(+), 3 deletions(-)
caddy/caddymain/run.go
caddyhttp/httpserver/plugin.go
~~~

#### 2. What are you trying to do?
Making sense of my monitoring :)

#### 3. What is your entire Caddyfile?
No really relevant. I've enable 'prometheus' (of course) and a custom middleware that is a backend for my wife's website (nlgids) <https://github.com/miekg/nlgids>

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
~~~text
[Unit]
Description=Caddy HTTP/2 web server
Documentation=https://caddyserver.com/docs
After=network.target

[Service]
PermissionsStartOnly=true
PIDFile=/var/www/caddy.pid
LimitNOFILE=8192
User=www-data
WorkingDirectory=/var/www
#ExecStartPre=/sbin/setcap cap_net_bind_service=+ep /opt/bin/customCaddy
ExecStartPre=/sbin/setcap cap_net_bind_service=+ep /opt/bin/caddy
ExecStart=/opt/bin/caddy -pidfile /var/www/caddy.pid -agree=true -email \
    miek@miek.nl -conf=/etc/caddy/Caddyfile -log stdout
Restart=on-failure

[Install]
WantedBy=multi-user.target
~~~

#### 5. What did you expect to see?
Low latency

#### 6. What did you see instead (give full error messages and/or log)?
High latency

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Think enabling the prometheus middleware should be enough to spot this behavior. (and setup grafana to graph to stuff, etc. etc.: <https://miek.nl/2016/March/02/enable-prometheus-metrics-in-caddy/>

**Comment by mholt** [comment]
Hmm, are these errors ones that you've experienced yourself?

TLS handshake error means that there was an error completing the TLS handshake. I really, really want to see your Caddyfile, I think it is relevant. For example, if it has an address like `:443` then it could be serving any hostname and maybe there is a bug in the way we obtain certificates. I also would be interested in your `tls` directive.

**Comment by miekg** [comment]
~~~text
https://miek.nl https://www.miek.nl https://archive.miek.nl {
    root /opt/www/miek.nl

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors {
        404 404.html
    }

    ext .html
    gzip
    prometheus
}

https://nlgids.london https://www.nlgids.london {
    root /opt/www/nlgids.london

    internal /include
    internal /md

    templates /

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"

    ext .html
    gzip
    prometheus

    nlgids {
        recipients ans@nlgids.london miek@miek.nl
        subject ans@nlgids.london
        secret /etc/caddy/NLgids-fcbeb7928cdb.json
        template /opt/tmpl/nlgids.london
    }

    basicauth x y {
        /api/auth
        /auth
    }
}

http://wereldstadsgidsen.com http://www.wereldstadsgiden.com http://wereldstadgidsen.nl http://www.wereldstadgidsen.nl http://wereldstadgidsen.be http://www.wereldstadgidsen.be {
    root /opt/www/wereldstadgidsen

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"

    ext .html
    gzip
    prometheus
}

https://dnssex.nl https://www.dnssex.nl {
    root /opt/www/dnssex.nl

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"

    ext .html
    gzip
    prometheus
}

https://www.berkestoffering.nl https://berkestoffering.nl {
    root /opt/www/berkestoffering.nl

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"

    ext .html
    gzip
    prometheus

    templates /
}


https://atoom.net {
    root /opt/www/atoom.net

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"

    ext .html
    gzip
    prometheus
}

https://isitinfra.net https://www.isitinfra.net {
    root /opt/www/isitinfra.net

    log / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"
    errors / syslog "{remote} - {host} {method} {path} {proto} {status} {size} {>Referer}"

    ext .html
    gzip
    prometheus
}
~~~

**Comment by mholt** [comment]
Thank you! I do not see anything unusual from this that would cause 10s latency. (Maybe a template that is misbehaving?)

- Do you know which site the latency happens on? Is it just one or all of these sites?
- Does it still happen if you remove either the `prometheus` directives or the `nlgids` directive? 

Thank you for the prometheus middleware, btw, it's quite nice. :smile:

**Comment by miekg** [comment]
well, if I remove the prometheus directive I can't see anymore if this happens or not...
Can't remove `nlgids` directive because that's my wife's commercial website.

I *think* it's clients misbehaving and trigger some kind client-side timeout. Template misbehaving sound weird, but this *is* on a VPS so maybe that *could* be something to look into.

Speaking of the prometheus middleware, it might be nice to a) hook into caddy internals (tls lifetime) and get other middleware to add monitoring as well.

**Comment by mholt** [comment]
Good points; so does this latency occur for all sites then? Or you're not sure.

It would be really useful to know if it only happens on certain sites or all of them, to see if we can figure out what they have in common. I agree with you that template problem is lower on my suspicion ladder.

As API work commences, a lot of effort will go into exposing more of Caddy's internals.

**Comment by weingart** [comment]
Any chance it's a 15 second timeout?

**Comment by miekg** [comment]
`histogram_quantile(0.99, sum(rate(caddy_http_request_duration_seconds_bucket[5m])) by (le, job,host))`, shows the timeout only for `(www.)miek.nl`. This is by far the most used domain. There are some largish (1.6MB) downloads going on a the time... but that does not make sense that these are capped at 10s (@weingart: don't see anything higher, what's the significance of 15s)
~~~
Jun 26 06:46:02 x64 caddy[5770]: 2016/06/26 06:46:02 http: TLS handshake error from 103.51.210.89:52361: EOF
Jun 26 06:46:03 x64 caddy[5770]: 103.51.210.89 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 200 32768 https://www.google.co.in/
~~~
Is such a download, but again, nothing that is really strange.

**Comment by miekg** [comment]
Ah, the default bucket of prometheus only goes to 10s `DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}`. We need moar

**Comment by miekg** [comment]
Forget, 10s <https://snapshot.raintank.io/dashboard/snapshot/kiq2fsUqtfdsIM94h4XGruW2RMRTOeH1?panelId=5&fullscreen>, up to 60s. Nothing weird in the logs around that timeframe.

**Comment by weingart** [comment]
15s is usually related to DNS issues.  Weird, something seems to be going on.

**Comment by miekg** [comment]
Also seeing the 15s timeouts (which would be some DNS). What kind of DNS does Caddy do?

I'll try to poke some more.

**Comment by mholt** [comment]
During requests? None with that Caddyfile. (Although I haven't vetted prometheus or nlgids middlewares.)

**Comment by miekg** [comment]
Again seeing these downloads in the logs:
~~~
Jun 27 16:46:18 x64 caddy[27579]: 180.151.110.15 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 206 11996 https://www.google.co.in
Jun 27 16:46:21 x64 caddy[27579]: 23.22.237.206 - miek.nl GET /feeds/all.rss.xml HTTP/1.0 404 1229 -
Jun 27 16:46:31 x64 caddy[27579]: 86.105.55.25 - miek.nl GET /feeds/all.atom.xml HTTP/1.1 404 1229 -
Jun 27 16:46:32 x64 caddy[27579]: 180.151.110.15 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 206 65536 https://www.google.co.in
Jun 27 16:46:52 x64 caddy[27579]: 180.151.110.15 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 206 65536 https://www.google.co.in
Jun 27 16:47:05 x64 caddy[27579]: 180.151.110.15 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 206 65536 https://www.google.co.in
Jun 27 16:47:09 x64 caddy[27579]: 180.151.110.15 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 200 995036 https://www.google.co.in
Jun 27 16:47:14 x64 caddy[27579]: 180.151.110.15 - www.miek.nl GET /favicon.ico HTTP/2.0 404 3930 -
~~~
Are these 64K responses some sort of chunked stuff? .IN is india

**Comment by miekg** [comment]
Another large time out (> 4m, need to extend caddy-prometheus again). Also has this pdf download (again from Asia):
~~~
Jun 27 16:35:26 x64 caddy[27579]: 112.95.136.95 - www.miek.nl GET /downloads/Go/Learning-Go-latest.pdf HTTP/2.0 200 32768 https://www.google.com.hk
~~~
Still believe this is clients misbehaving, but don't have proof for that.

**Comment by mholt** [comment]
I'm also guessing there is chunking going on; I believe the Go std lib does support that.

Are you still seeing these latencies if you disable HTTP/2? (Or are these already taking place over HTTP/1.1?)

**Comment by miekg** [comment]
Look at the logs :) All HTTP/2

**Comment by mholt** [comment]
Oops, duh :no_mouth: -- try without HTTP/2, see what happens... kind of shooting in the dark here. But if the timeouts go away then it's quite likely a client problem. If they stay, it could still be a client problem, but having a concrete way to reproduce these would be very useful, rather than them being sporadic like this.

**Comment by miekg** [comment]
I rather not. But with some better monitoring it indeed shows up in http/2 only:
https://snapshot.raintank.io/dashboard/snapshot/CQdxZnIxjsimTkwynXxOmTZntJWvTPq1
scroll down to "Response Duration"

**Comment by miekg** [comment]
Nope, also saw a timeout in the HTTP/1 graph. To more I up the timeout limit in the caddy-prometheus the higher the time. Now seeing up to 16 minutes (current max).

**Comment by mholt** [comment]
By "timeout" we actually mean "response time" right? Could it just be a client downloading a file really slowly because of a bad connection?

**Comment by miekg** [comment]
Yes, response time.

**Comment by mholt** [comment]
Well, at this point there's nothing known in Caddy to slow down responses so dramatically, especially when just pumping out static files. Based on my own experiences with slow Internet access, I'm willing to bet at this point, and without further abilities to reproduce the behavior, that it's just slow clients taking their sweet time downloading the files.

But I'm glad you're reporting things like this! That kind of awareness is very good for finding and squishing bugs. :+1:
