### ISSUE TITLE
Caddy from source doesn't download all dependencies

### ISSUE THREAD

**Issue by nesl247** [mholt/caddy#904]
When running the go get command listed in the README, it no longer downloads all the dependencies. I looked through the history, and it was https://github.com/mholt/caddy/commit/e585a74115912c456f87b0aec6f125f5e7125693 that broke it. Basically it removed the second `/caddy` in the url.

Since I'm barely even a go novice, I honestly don't know if the url as it is today is correct and there are other issues at play, or if the url needs to be fixed back to what it was before that commit.

I know it's just a minor change, but I'll submit a PR if you'd like, to fix the URL if that is indeed the issue.

**Comment by mholt** [comment]
Oh, whoops, yeah, you're right. Thanks!
