### ISSUE TITLE
Make storage pluggable

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#906]
If caddytls.Storage was pluggable, it would make it possible to use something other than the local disk for TLS asset storage. In fact, the abstraction doesn't have to be limited to caddytls; if we think of storage as a simple key-value store, we may only need a few methods on an interface for all disk-related functions to be abstracted.

So two ways to do it:

1. Abstract caddytls.Storage, this makes only the TLS assets pluggable
2. Abstract assets.go, which makes all storage pluggable, however I don't know how feasible this is

Someone is welcome to look into this before I have a chance to get around to it.

\* _Adopted from [this forum topic which has more details](https://forum.caddyserver.com/t/any-ssl-solution-for-multi-server-setup-behind-same-domain/215?u=matt) but continue discussion here_

**Comment by cretz** [comment]
From what I see, assets is only used for the TLS storage. I don't think its reasonable to abstract the assets stuff (and the moveStorage stuff or any of that). Instead, the default impl of the TLS storage interface should just leverage the `AssetsPath()` as necessary. If, in the future, there are other assets that leverage the filesystem, no reason to require them to share state like TLS.

**Comment by mholt** [comment]
Well, Caddy does need a place to store assets; the search plugin does, for instance. (The search plugin was written before the auto TLS stuff and there was no concept of a storage place for Caddy assets, but there is now, and it will soon need to use it.)

So the storage abstraction will indeed need to be available to plugins somehow. I think that will be valuable in the long run!

**Comment by cretz** [comment]
@mholt - Here is an early commit of what I am thinking: https://github.com/cretz/caddy/commit/84771da9fd041d534e5c0bd87d28a2251d57fae5. It will allow plugins to add storage just like they add middleware today. I took great care w/ my refactoring scalpel to not upset the code too much.

Please take a peek. Hopefully the benefits of keeping it specific to TLS, such as keeping the changes lean and not touching the rest of the codebase, are clear. I think a generic KV store is orthogonal to this. Also, this data is highly secret, so not sure it should be mixed with other arbitrary storage.

**Comment by mholt** [comment]
@cretz Wow, that's quite the change! I can tell you put some time into it. I have made some comments in-line along with @weingart.

You make some good points about keeping TLS asset storage separate from "regular" Caddy storage, although I hope that all Caddy assets will be stored with care.

Anyway, I really like where this is heading and would be willing to accept a PR for more review and finishing touches (especially docs and tests). It will be valuable to make clear in docs how storage providers can be plugged in. A good example of how to plug into the caddytls package is the DNS providers: https://github.com/caddyserver/dnsproviders

**Comment by mholt** [comment]
This was implemented in #913 - thanks @cretz!
