### ISSUE TITLE
markdown: Listings for pages generated from markdown files

### ISSUE THREAD

**Issue by mdwhatcott** [mholt/caddy#91]
For bloggers, generating a listing of the latest blog posts (either for the index.html page or the rss feed) is a must-have feature.

Hugo addresses this with [list templates](http://gohugo.io/templates/list/).

I imagine the markdown directive in the caddyfile would need another argument for specifying a template to use, which would contain a for loop for recent (or all?) posts. Pagination would be important for large sites. Within the for loop certain variables could be referenced, like the title of the current post, it's publish date, and maybe a snippet of the content.

**Comment by mholt** [comment]
I believe @abiosoft is on this. We want to host a simple Markdown blog on the Caddy website and an index page will be necessary.

**Comment by abiosoft** [comment]
Yeah. In progress.

**Comment by mholt** [comment]
@mdwhatcott This is now working on master. Documentation coming to the website soon. @abiosoft has done a great job with it to get something going on this... it will continue to improve over time. Thanks for the suggestion!

**Comment by mdwhatcott** [comment]
Nifty!
