### ISSUE TITLE
Header removal does not work on Server

### ISSUE THREAD

**Issue by HazCod** [mholt/caddy#910]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3 (+2138270 Mon Jun 20 15:40:46 UTC 2016)

#### 2. What are you trying to do?
Remove Caddy and proxied 'Server' header

#### 3. What is your entire Caddyfile?
```text
website.com {
    header / {
        "Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload"
        "X-Frame-Options" "DENY"
        "X-Content-Type-Options" "nosniff"
        "X-XSS-Protection" "1; mode=block"
        -server
        -Server
    }
   
   gzip

    proxy / mgmt:8080 {
        proxy_header X-Forwarded-For {host}
    }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

On docker:
```
cap_net_bind_service=+ep HOME=/etc/caddy /usr/sbin/caddy -conf /etc/caddy/caddyfile -email "${EMAIL}" -agree
```

#### 5. What did you expect to see?
Removed 'Server' headers.

#### 6. What did you see instead (give full error messages and/or log)?
'Server' headers are shown.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Run website with above caddyfile, inspect headers with 'curl --head https://website.com/`

**Comment by mholt** [comment]
Hey, thanks for the report! If the Server header is added from the proxied backend you need to do this in the proxy directive instead (only available with Caddy 0.9 beta so far):

```
proxy / mgmt:8000 {
    header_downstream -Server
}
```

I know it's annoying that it can't be done with the `headers` directive; it is a quirk of Caddy's design, regrettably.

**Comment by HazCod** [comment]
Hi @mholt , thanks for answering! I'll try it out when it's released as a stable.
FYI, you didn't talk about my other issue; header -server not working on caddys own 'Server' header

**Comment by mholt** [comment]
Does `header -Server` work for that?

**Comment by HazCod** [comment]
I have both `-server` and `-Server` for that, but to no avail.

**Comment by mholt** [comment]
That's strange, it works for me. :confused: If you take out the proxy directive does it work as expected?

**Comment by HazCod** [comment]
I have modified the dav.datapeak.hazcod.com vhost so it has no proxy directive, but still all Server headers;

```
datapeak.hazcod.com {
    header / {
        "Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload"
        "X-Frame-Options" "DENY"
        "X-Content-Type-Options" "nosniff"
        "X-XSS-Protection" "1; mode=block"
        -server
        -Server
    }

   gzip

    proxy / mgmt:8080 {
        proxy_header X-Forwarded-For {host}
    }
}

dav.datapeak.hazcod.com {
    header / {
        "Strict-Transport-Security" "max-age=63072000; includeSubdomains; preload"
        "X-Frame-Options" "DENY"
        "X-Content-Type-Options" "nosniff"
        "X-XSS-Protection" "1; mode=block"
        -server
        -Server
    }

    gzip

    #proxy / dav:8080 {
    #    proxy_header X-Forwarded-For {host}
    #}
}

```

**Comment by mholt** [comment]
I'm sorry, but I'm still not able to reproduce it.
<img width="302" alt="screen shot 2016-07-02 at 2 01 57 pm" src="https://cloud.githubusercontent.com/assets/1128849/16542236/9c90a85e-405d-11e6-926a-db85d9f79447.png">

The server header is gone with:

```plain
header / {
    -Server
}
```

(Even though `header / -Server` is easier I used the same syntax you did just to check.)

**Comment by HazCod** [comment]
@mholt ; you are absolutely right, I mixed up docker containers when testing. Thanks!
