### ISSUE TITLE
Caddy 502 Bad Gateway; No Issue from Other Sources

### ISSUE THREAD

**Issue by Persistent13** [mholt/caddy#911]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.3

#### 2. What are you trying to do?

Proxy to a backend web server with non-standard TLS ports (8080 and 8081) to serve a bare XML document.

#### 3. What is your entire Caddyfile?

-snips-'s to protect private info.

```text
https://-snip- {
    log /etc/caddy/log/-snip-.log {
        size 50
        age 90
        keep 5
    }
    errors /etc/caddy/log/-snip-.errors {
        size 50
        age 90
        keep 5
    }
    proxy / https://192.168.248.160:8080 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
        insecure_skip_verify
    }
    gzip
    tls -snip-
}
https://-snip- {
    log /etc/caddy/log/-snip-.log {
        size 50
        age 90
        keep 5
    }
    errors /etc/caddy/log/-snip-.errors {
        size 50
        age 90
        keep 5
    }
    proxy / https://192.168.248.160:8081 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
        insecure_skip_verify
    }
    gzip
    tls -snip-
}
```

I've also tried changing the server to use port 443 as well, same issue occurs.

```text
    proxy / https://192.168.248.160 {
        proxy_header Host {host}
        proxy_header X-Real-IP {remote}
        proxy_header X-Forwarded-Proto {scheme}
        insecure_skip_verify
    }
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

From the CLI:

`/etc/caddy/caddy -pidfile /tmp/caddy.pid -agree -conf=/etc/caddy/caddy.conf -log stderr`

From a systemd service:

```text
[Unit]
Description=CaddyServer
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
User=-snip-
WorkingDirectory=/etc/caddy
LimitNOFILE=4096
Type=simple
ExecStart=/etc/caddy/caddy -pidfile /tmp/caddy.pid -agree -conf=/etc/caddy/caddy.conf
PIDFile=/tmp/caddy.pid
ExecReload=/bin/kill -USR1 $MAINPID
Restart=on-failure

LimitNOFILE=32768
Restart=always
```

#### 5. What did you expect to see?

An XML document served from the backend server.

#### 6. What did you see instead (give full error messages and/or log)?

502 Bad Gatway

The log shows:

```text
216.93.212.94 - [30/Jun/2016:10:46:39 -0700] "GET / HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:10:47:09 -0700] "GET /favicon.ico HTTP/2.0" 502 16
216.93.212.94 - [30/Jun/2016:10:47:09 -0700] "GET /favicon.ico HTTP/2.0" 502 16
216.93.212.94 - [30/Jun/2016:10:47:16 -0700] "GET /PSDSCPullServer.svc HTTP/2.0" 502 16
216.93.212.94 - [30/Jun/2016:11:29:00 -0700] "GET / HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:11:35:13 -0700] "GET / HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:11:35:29 -0700] "GET /PSDSCPullServer.svc HTTP/2.0" 502 16
216.93.212.94 - [30/Jun/2016:11:36:51 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:11:40:05 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:11:49:03 -0700] "GET / HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:11:58:33 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:11:58:39 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:12:01:32 -0700] "GET / HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:12:01:41 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:12:01:42 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:12:28:23 -0700] "GET / HTTP/1.1" 502 40
216.93.212.94 - [30/Jun/2016:12:29:08 -0700] "GET / HTTP/2.0" 502 40
216.93.212.94 - [30/Jun/2016:12:29:23 -0700] "GET /PSDSCPullServer.svc/ HTTP/1.1" 502 40
216.93.212.94 - [30/Jun/2016:12:29:25 -0700] "GET /PSDSCPullServer.svc/ HTTP/1.1" 502 40
216.93.212.94 - [30/Jun/2016:12:29:36 -0700] "GET /PSDSCPullServer.svc/ HTTP/2.0" 502 40
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

1. Configure a Desired State Configuration server listening on ports 8080 (DSC) and 8081 (Reporting) with TLS enabled
2. Run Caddy proxying to the DSC server via port 8080 with TLS enabled
3. Try to connect from the Caddy proxy

#### 8. Additional Information

By default the index page will serve a 403 error (this is expected, there is no index page and directory browsing is disabled) but direct access to the /PSDSCPullServer.svc/ page serves without issue from a browser and a curl request from the server running Caddy.

Since I am testing this the certificates on the DSC server are self-signed and not valid but insecure_skip_verify should be working around that.

I've also tried serving the pages from 443 on the backend however the same issue persists.

----

If you need anything from me let me know and I'll do my best to respond with the information requested!

Thanks,
Dakota Clark

**Comment by mholt** [comment]
Hey Dakota, thanks for the report!

If the backend responds with something not in the 200-399 range, it views that as an unhealthy endpoint; so this is expected isn't it, if the backend is responding with 403s?

Also the report seems to lean a lot on TLS; does this not happen without TLS?

**Comment by Persistent13** [comment]
Hi @mholt ,

Sorry for the long delay but I've been on a bit of a rabbit hole tracking down the cause of this issue.

Good new is that Caddy is not the cause!
Bad news is that it is a known bug with Go's crypto/tls library.

The DSC service I'm using can prompt for client certificates used to authenticate to the web server.
Microsoft achieves this by renegotiating the TLS connection and as of Go 1.6.2 crypto/tls does not support TLS renegotiation.

There is a bug open with Go located [here](https://github.com/golang/go/issues/5742) and it looks like the aim is to have the patch that fixes the issue applied to version 1.7.

I'm assuming that the issue should be addressed once Caddy is built with the version of Go that has the proposed patch so there's nothing more for us to do until then.

Thanks for hearing me out Matt,
Dakota Clark

**Comment by mholt** [comment]
That's great news actually -- I'll be sure to build Caddy on Go 1.7 when it is released. Thanks for looking into that!

**Comment by irony** [comment]
This means that currently the Caddy proxy doesn't support a standard 302 redirect.. It is really a showstopper for me..

**Comment by mholt** [comment]
@irony 302 is within the accepted 200-399 range.

**Comment by kmanley** [comment]
what about 404 though? that shouldn't make caddy mark a back end as a bad gateway should it?

**Comment by killarny** [comment]
4xx responses shouldn't be marked as a bad gateway - there are plenty of legitimate responses in that range (400, 401, 404, 408, to point out just a few) which have nothing at all to do with the gateway being bad.

IMO, caddy should expand the range of acceptable response codes to 200-499

**Comment by mholt** [comment]
We could discuss that, but let's open a separate issue if you want to do that.

**Comment by jazoom** [comment]
Agreed. It doesn't seem right a proxy should be making these decisions.

**Comment by htfy96** [comment]
Sorry to reply to this issue after one and a half years, but is there any update on the handling of 4xx responses in `http.proxy` module? It seems that due to [a bug in apt](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=795284), it's possible to generate quite a lot valid (from the users' perspective) 416 responses for a proxy to ubuntu mirror.

**Comment by veith** [comment]
> We could discuss that, but let's open a separate issue if you want to do that.

Does the separate issue exist? 
If you proxy to a rest api, the 4xx family has a meaning. I.e. The client can go to the auth page on a 401.
