### ISSUE TITLE
gzip and  clean URL ext not working

### ISSUE THREAD

**Issue by MatthewVance** [mholt/caddy#914]
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.8.3

#### 2. What are you trying to do?
Serve `.html` files with clean URLs with custom gzip settings.

#### 3. What is your entire Caddyfile?
```text
localhost:2015

root ./dist

errors {
  400 exceptions/500.html # Bad Request
  400 exceptions/401.html # Unauthorized
  400 exceptions/403.html # Forbidden
  404 exceptions/404.html # Not Found
  500 exceptions/500.html # Internal Server Error
  log error.log {
    size 50 # Rotate after 50 MB
    age  30 # Keep rotated files for 30 days
    keep 5  # Keep at most 5 log files
  }
}

ext .html .htm

gzip {
    ext        .css .eot .html .js .svg .ttf .txt .xml
    not        /static/images
    level      9
    min_length 256
}

# https://report-uri.io/home/generate
#https://chloe.re/2016/06/23/hardening-content-security-policy/

header / {
  Access-Control-Allow-Methods "GET, POST"
  X-Frame-Options "DENY"
  X-XSS-Protection "1; mode=block"
  X-Content-Type-Options "nosniff"
  Server {host}
  Content-Type "text/html; charset=utf-8"
  #-Server
  Content-Security-Policy "Content-Security-Policy-Report-Only: default-src 'self' *//placehold.it; script-src 'self' https://cdnjs.cloudflare.com:443/ajax/libs/jquery/1.12.4/jquery.min.js https://maxcdn.bootstrapcdn.com:443/bootstrap/3.3.6/js/bootstrap.min.js https://cdnjs.cloudflare.com:443/ajax/libs/html5shiv/3.7.3/html5shiv.min.js https://cdnjs.cloudflare.com:443/ajax/libs/respond.js/1.4.2/respond.min.js"; style-src 'self' https://maxcdn.bootstrapcdn.com:443/bootswatch/3.3.6/paper/bootstrap.min.css; img-src 'self' *://placehold.it/; font-src 'self' https://fonts.gstatic.com:443/s/roboto/v15/ https://maxcdn.bootstrapcdn.com:443/bootswatch/3.3.6/fonts/; connect-src 'none' ; media-src 'none' ; object-src 'none' ; child-src https://www.google.com:443/maps/embed/v1/place; frame-ancestors 'none' ; form-action 'self' ; upgrade-insecure-requests; sandbox allow-same-origin allow-scripts; reflected-xss block; base-uri http://localhost:2015/; manifest-src 'none' ; referrer origin; report-uri https://mvance.report-uri.io:443/r/default/csp/reportOnly;"
}

mime {
	.css text/css
  .gz application/x-gzip
  .html text/html
  .htm text/html
  .ico image/x-icon
  .jpeg image/jpeg
  .js application/javascript
	.pdf application/pdf
}

#tls {
#    protocols 1.2 1.2
#    ciphers   ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256
#}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
I simply run `caddy` from Mac OS X terminal. Caddy is installed in `/usr/local/bin/caddy`.

#### 5. What did you expect to see?
Caddy serving `.html` files via gzip since the `.html` as set as a one of the file types to be gzipped.

#### 6. What did you see instead (give full error messages and/or log)?
The `.html` file was not gzipped. 

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
1. Add the following to a Caddy file:
```text
ext .html .htm

gzip {
    ext        .css .eot .html .js .svg .ttf .txt .xml
}
```
2. Run `Caddy` and view a `.html` page (e.g., example.com/blog) in Google Chrome 
3. Right-click and select "Inspect"
4. Go to "Audits" tab of Chrome developer tools, select "Reload Page and Audit on Load", and then click run (use default options)
5. View "Enable gzip compression" recommendation to determine if the clean URL extension of the page was gzipped or not.

**Comment by mholt** [comment]
I might have these directives out of order, I don't have my computer right now to check my notes but will look into it after the holiday! Thanks for the detailed report.

**Comment by MatthewVance** [comment]
You're welcome. I was afraid it might be too much info, but I want to follow the issue template. Anyway, no rush on this as its a low priority issue. Enjoy the holiday!

**Comment by mholt** [comment]
Oops, indeed. This is because [`gzip` is executed before `ext` in the middleware chain](https://github.com/mholt/caddy/blob/d4b10b69a741c9c04860c5430e0191b1564150b6/caddyhttp/httpserver/plugin.go#L346-L356). So before the '.html' extension is added to a "clean URL" request, the gzip compression has already been decided.

I fixed it locally by re-arranging the order and putting ext before gzip. Carrying it further I am also moving rewrite before gzip too.

Now, this doesn't fix the case for index files, as they are not "rewritten" until in the file server at the very end of the middleware chain. So a request to "/" that loads index.html will not be compressed with your gzip rules. But you can add `""` to the gzip ext list and then index pages will be compressed too.

**Comment by MatthewVance** [comment]
👍
