### ISSUE TITLE
Config multiple server in caddyfile failed with error "Parse error: Unknown directive"

### ISSUE THREAD

**Issue by jaggerwang** [mholt/caddy#917]
#### 1. What version of Caddy are you running (`caddy -version`)?
```
➜  caddy caddy -version
Caddy 0.8.3
```

#### 2. What are you trying to do?
Using caddy to serve multiple server.

#### 3. What is your entire Caddyfile?
```text
localhost

log /data/caddy/access.log

errors {
    log /data/caddy/error.log
}

gzip

www.zaiqiuchang.com {
    root /data/www
}

zaiqiuchang.com {
    redir https://www.zaiqiuchang.com
}

api.zaiqiuchang.com {
    proxy / zqc-app1:1323
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`➜  caddy caddy -conf ~/caddy/Caddyfile -email jaggerwang@gmail.com -agree -log /data/caddy/caddy.log -root /data/www`

#### 5. What did you expect to see?
running

#### 6. What did you see instead (give full error messages and/or log)?
`2016/07/04 17:08:39 Caddyfile:11 - Parse error: Unknown directive 'www.zaiqiuchang.com'`

**Comment by elcore** [comment]
Hello @jaggerwang,

this should work

'''
localhost {

log /data/caddy/access.log

errors {
    log /data/caddy/error.log
}

gzip
}

www.zaiqiuchang.com {
    root /data/www
}

zaiqiuchang.com {
    redir https://www.zaiqiuchang.com
}

api.zaiqiuchang.com {
    proxy / zqc-app1:1323
}
'''

**Comment by elcore** [comment]
Hello @jaggerwang,

this should work:

```text
localhost {

log /data/caddy/access.log

errors {
    log /data/caddy/error.log
}

gzip
}

www.zaiqiuchang.com {
    root /data/www
}

zaiqiuchang.com {
    redir https://www.zaiqiuchang.com
}

api.zaiqiuchang.com {
    proxy / zqc-app1:1323
}
```

**Comment by elcore** [comment]
Hello @jaggerwang,

"To configure multiple servers (virtual hosts) with a single Caddyfile, you must use curly braces around the server block:"

```text

mysite.com {
	root /www/mysite.com
}

sub.mysite.com {
	root /www/sub.mysite.com
	gzip
	log ../access.log
}
```

https://caddyserver.com/docs/caddyfile

**Comment by jaggerwang** [comment]
I've already read the doc, and I've already use curly braces around my server as the example. The doc is a little confuse to understand, and there is no full example, just pecies.

**Comment by jaggerwang** [comment]
With the help of @elcore , I figured it out the correct way to config multiple servers with common config sharing.

```
➜  caddy cat Caddyfile
www.zaiqiuchang.com {
    import common.conf

    root /data/www
}

zaiqiuchang.com {
    redir https://www.zaiqiuchang.com
}

api.zaiqiuchang.com {
    import common.conf

    proxy / zqc-app1:1323
}

➜  caddy cat common.conf
log /data/caddy/access.log

errors {
    log /data/caddy/error.log
}

gzip
```

**Comment by elcore** [comment]
ping @mholt regarding documentation

**Comment by mholt** [comment]
Glad you got it fixed! :smile:

As for docs, they do say:

> To configure multiple servers (virtual hosts) with a single Caddyfile, you must use curly braces around the server block.

I guess I should make the last word ("block") plural ("blocks") -- but it seems pretty clear to me. What is confusing?

**Comment by kevinsimper** [comment]
@mholt I am experience the same problem and I also wonder how a full example would look, because this gives and error and is pretty simple:

```
localhost:2015

http://nginx.dev {
    proxy nginx
}

http://apache.dev {
    proxy apache
}
```

But fails with the weird error: `2016/08/08 19:36:06 /etc/Caddyfile:3 - Parse error: Unknown directive 'http://nginx.dev'`

**Comment by mholt** [comment]
@kevinsimper  See above ^

I changed the wording on the docs to read "all the site blocks" 😛

**Comment by kevinsimper** [comment]
👍 I think the docs need more full examples with sites also in 😄 Will submit PR
