### ISSUE TITLE
SSLv3 Error with curl

### ISSUE THREAD

**Issue by davidak** [mholt/caddy#923]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.8.2

#### 2. What are you trying to do?

```
curl https://static.caddy-test.basecom.de/
```

#### 3. What is your entire Caddyfile?
```text
cat /etc/caddy/caddyfile
import /etc/caddy/sites-enabled/*
import /var/www/static/Caddyfile

cat /etc/caddy/sites-enabled/default
:80 {
    root /var/www/default
    header / X-Backend-Server {hostname}
}

cat /var/www/static/Caddyfile
static.caddy-test.basecom.de {
	root /var/www/static
	gzip
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Ubuntu 14.04 Server, Ubuntu Package, Upstart

```
exec /usr/sbin/caddy -log="/var/log/caddy" -agree -email="***@basecom.de" -conf="/etc/caddy/caddyfile"
```

#### 5. What did you expect to see?

Valid HTTP Response

#### 6. What did you see instead (give full error messages and/or log)?

```
curl: (35) error:140943FC:SSL routines:SSL3_READ_BYTES:sslv3 alert bad record mac
```

reproducible on different systems:

#### 12.04

curl 7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

OpenSSL 1.0.1 14 Mar 2012

#### 14.04

curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP

OpenSSL 1.0.1f 6 Jan 2014

#### NixOS 16.09.git.51119d2 (unstable branch)

curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.47.1 OpenSSL/1.0.2g zlib/1.2.8 libssh2/1.7.0 nghttp2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets

#### Mac OS X 10.9.5

**not** reproducible with

curl 7.30.0 (x86_64-apple-darwin13.0) libcurl/7.30.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: AsynchDNS GSS-Negotiate IPv6 Largefile NTLM NTLM_WB SSL libz

but with `siege`from brew.

SIEGE 3.1.3

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

```
curl https://static.caddy-test.basecom.de/
```

**Comment by davidak** [comment]
it is very strange. i updated the binary to 0.8.3 and the problem is solved.

when i go back to 0.8.2 it still works.

**Comment by mholt** [comment]
Very interesting!

I saw the issue when you opened it but have been in the mountains today so I haven't had a chance to look into it much. Thanks for your detective work and detailing everything here. If it comes up again with the current version, that person should post here with more information.

FWIW, Caddy 0.9 does not have any SSLv3 support at all.
