### ISSUE TITLE
Proxy preset "transparent" should use X-Forwarded-For

### ISSUE THREAD

**Issue by cederberg** [mholt/caddy#924]
The new proxy `transparent` preset is defined to used `X-Real-IP`, but should probably use `X-Forwarded-For` instead. Wikipedia actually has great docs for this: https://en.wikipedia.org/wiki/X-Forwarded-For

Same goes for the docs example that currently recommends `X-Real-IP`.

Weirdly, Nginx seems to default to `X-Real-IP`. No reason stated though. And a quick googling shows that `X-Real-IP` has caused lots of confusion and config errors. Should be avoided.

**Comment by elcore** [comment]
I agree :+1: 

https://github.com/mholt/caddy/blob/80dd95a49528f217a0918e3dd64c82ca3b52d3fb/caddyhttp/proxy/upstream.go#L291

`u.upstreamHeaders.Add("X-Real-IP", "{remote}")`

https://github.com/mholt/caddy/blob/227664336ef5d68c833fe7d0402ba708cec8f63f/caddyhttp/httpserver/replacer.go#L86-L95

```
"{remote}": func() string {
				if fwdFor := r.Header.Get("X-Forwarded-For"); fwdFor != "" {
					return fwdFor
				}
				host, _, err := net.SplitHostPort(r.RemoteAddr)
				if err != nil {
					return r.RemoteAddr
				}
				return host
			}(),
```

We use the IP provided by `X-Forwarded-For`, so we should pass on `X-Forwarded-For`

**Comment by mholt** [comment]
I'll look into this -- also what is @captncraig's feedback? (author of the realip plugin)

**Comment by stp-ip** [comment]
We could go the save route and enable both on "transparent". People concerned about the additional bandwidth of an additional header could just fallback to their own headers.

**Comment by cederberg** [comment]
Both seems safe until you read this:
http://relistan.com/http-header-hell-starring-x-real-ip-and-x-forwarded-for/

Other stories as well. Think the standard is better in this case.

**Comment by stp-ip** [comment]
That should in my opinion not prevent us from using both as default.

**Comment by elcore** [comment]
:+1: for both

**Comment by captncraig** [comment]
I am ok with **setting** both, but I am not ok with [**trusting**](https://github.com/mholt/caddy/blob/227664336ef5d68c833fe7d0402ba708cec8f63f/caddyhttp/httpserver/replacer.go#L86-L95) either as the remote address on incoming requests. Anybody can set that header and there is no way to authenticate it unless it is coming from a proxy you expect and trust. Thats why I made the real-ip module.

**Comment by mholt** [comment]
Okay, consensus, great. :smile: I'll change it to set both headers. Thanks for making the real-ip module @captncraig!
