### ISSUE TITLE
Assignment count mismatch in tls.go

### ISSUE THREAD

**Issue by nesl247** [mholt/caddy#925]
While trying to download or build caddy from master, I get the following:

```
# github.com/mholt/caddy/caddytls
/Users/harrison/.local/share/go/src/github.com/mholt/caddy/caddytls/tls.go:116: assignment count mismatch: 3 = 2
/Users/harrison/.local/share/go/src/github.com/mholt/caddy/caddytls/tls.go:129: assignment count mismatch: 3 = 2
```

It's due to this commit https://github.com/mholt/caddy/commit/2b06edccd355b7b692905968a305712f7d350c25

**Comment by elcore** [comment]
Hello @nesl247,

that's weird! The commit passed all tests!

**Comment by elcore** [comment]
Hello @nesl247 ,

I cannot confirm this bug!

```
ok      _/root/caddy    0.007s
[...]
ok      _/root/caddy/caddytls   0.533s
```

`go version go1.6 linux/amd64`

**Comment by nesl247** [comment]
I'm on `go version go1.6.2 darwin/amd64` on macOS 10.12 Sierra Developer Preview 2 if it helps.

**Comment by mholt** [comment]
Update dependencies; `go get -u github.com/xenolf/lego/acme` :wink:

**Comment by nesl247** [comment]
That did it, thanks.
