### ISSUE TITLE
proxy: Custom Proxy Policy

### ISSUE THREAD

**Issue by acmacalister** [mholt/caddy#93]
I have project I'm working on that would benefit from being able to write a custom policy for load balancing clients. Instead of reimplementing most of the proxy middleware, I thought it might be cool to allow implementing custom policies. It seems like it would be a pretty straight forward addition as it would just take a few tweaks to the current proxy package to allow someone to implement the `Policy` interface to do custom load balancing. Before I coded this up and submitted a PR, I wanted to see if that would fit in the design scope of caddy.

**Comment by nemothekid** [comment]
You should be able to do write custom policies today - what did you think was missing?

You can define your own [policy](https://github.com/mholt/caddy/blob/master/middleware/proxy/policy.go) by using the default implementation 

your_file.go
```go
// Random is a policy that selects up hosts from a pool at random.
type MyPolicy struct{}

// Select selects an up host at random from the specified pool.
func (r *MyPolicy) Select(pool HostPool) *UpstreamHost {
        // pool is just an array of HostPool that were passed to Caddyfile
       return pool[0]
}
```

**Comment by acmacalister** [comment]
Agreed that was what I did. I also had to add another case in the switch statement it in the `NewStaticUpstreams` method in `upstream.go` to support defining my policy from a caddyfile. Maybe I'm missing something, but I was just thinking of a small tweak to avoid having to edit the proxy middleware source for each custom policy

**Comment by acmacalister** [comment]
Exactly. That was what I was thinking. :smile:

**Comment by nemothekid** [comment]
I agree.

It looks like we need to

1. Edit the `Policy` interface to have a `Name() string` function so policies can describe themselves.
2. Edit upstream.go to select from a list of Policies (`var supportedPolicies map[string]func() Policy`) that is populated by a `registerPolicy(string, func() Policy)` function

If you have already done it, you can submit a PR and wait for @mholt to approve.

**Comment by acmacalister** [comment]
Agreed. That is what I working on currently. I will get the PR sent over shortly.
