### ISSUE TITLE
Proxy disregards authentication

### ISSUE THREAD

**Issue by withinboredom** [mholt/caddy#933]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3

#### 2. What are you trying to do?
add this to my caddyfile:

```
:4243 {
	proxy / http://user:password@host.com:4243 {
		policy least_conn
	}
}
```

#### 3. What is your entire Caddyfile?
See above

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Serves blog and proxies outside traffic to another internal router inside docker cluster.

This particular caddyfile is for connecting to staging services from a local machine.

#### 5. What did you expect to see?
I expected it to return a 200 instead of 401 when hitting the api endpoint.

#### 6. What did you see instead (give full error messages and/or log)
401 Unauthorized

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

two caddy instances:

caddyfile1:

```
:80 {
	basicauth / user password
}
```

caddyfile2:
```
:8000 {
	proxy / http://user:password@localhost:80
}
```

Run each and verify that you get a 401 instead of 200 (assuming you have something to serve at the location you're trying to retrieve)

**Comment by mholt** [comment]
Thanks for the report! I don't think this case was considered when building the proxy. The URL is parsed but we don't account for the user/password information. We should probably do that, indeed.
