### ISSUE TITLE
log path relative to root

### ISSUE THREAD

**Issue by davidak** [mholt/caddy#934]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.8.3

#### 2. What are you trying to do?
specify logfile path relative to root.

#### 3. What is your entire Caddyfile?
```text
davidak.binary.lan.davidak.de {
  root /var/www/davidak/web/
  gzip

  log /var/www/davidak/log/access.log {
    rotate {
      age 96
      keep 10
    }
  }

  errors {
    log ../log/error.log {
      age 96
      keep 10
    }
  }
...
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
systemd service on NixOS:

`ExecStart=/nix/store/1ldzjk7sdi8sp0q8m51bl25q2nzvfgxj-go1.6-caddy-0.8.3-bin/bin/caddy -conf=/nix/store/axfyd1piq700v0m3fl9iy52baq2hzkai-Caddyfile -ca=https://acme-v01.api.letsencrypt.org/directory -email=post@davidak.de -agree`

#### 5. What did you expect to see?
caddy starts and log errors to /var/www/davidak/log/error.log

#### 6. What did you see instead (give full error messages and/or log)?
`caddy[1531]: 2016/07/17 02:42:39 open ../log/error.log: no such file or directory`

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
reproduce the caddyfile with your paths.

**Comment by mholt** [comment]
We intentionally made log files relative to current working dir because log files don't necessarily belong in the root of the site; they aren't a part of the site, so it doesn't make sense to make their paths relative to the site root.
