### ISSUE TITLE
Timing attacks mitigation with Caddy

### ISSUE THREAD

**Issue by dlsniper** [mholt/caddy#937]
Hi Matt,

Here's a bit of a crazy idea I've had: what if you'd want to use Caddy as a reverse proxy and also add some security against [timing attacks](https://en.wikipedia.org/wiki/Timing_attack) on your API?

To do this, the way I see it would be: define a "constant reply time" which will hold (buffer) the reply from response until the time ends. If the time is running over the defined time, a predefined message could be used instead so that the receiving end doesn't have any idea what's going on.

What do you think?

**Comment by ammario** [comment]
That doesn't seem like the responsibility of a general purpose webserver, you should have protection against timing attacks in your code.

**Comment by mholt** [comment]
Although timing attacks over external networks are tricky, several white papers suggest they are practical. Caddy mitigates timing attacks at the crypto level (basicauth middleware, for instance) by using constant-time comparisons.

I don't think a sleep -- or even a random sleep -- [will mitigate timing attacks](https://github.com/mholt/caddy/issues/937). This is probably not something I would recommend for Caddy users.

Thanks for the suggestion though!

**Comment by dlsniper** [comment]
I may have not explained it good enough :) The idea is that if you proxy to a service, then you have the opportunity to return the response from Caddy in constant time, regardless of how much it takes the backend to reply, thus removing the issue of timing attacks since the users will receive the reply in the same time regardless of the outcome. Not sure if Caddy wants to do this or not so up to you if you want to reopen or not.

**Comment by paragonie-scott** [comment]
If your application is vulnerable to timing attacks, the correct thing to do is fix your application code. Attempting to solve it upstream is foolhardy and will only degrade performance for no real gain.
