### ISSUE TITLE
Deadlock in Stop function

### ISSUE THREAD

**Issue by FZambia** [mholt/caddy#941]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?
master branch

#### 2. What are you trying to do?
just noticed deadlock

#### 3. What is your entire Caddyfile?
```text
-
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
-

#### 5. What did you expect to see?
-

#### 6. What did you see instead (give full error messages and/or log)?
-

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Just was looking through the code (I am not caddy user yet) and noticed that `Stop` func  (https://github.com/mholt/caddy/blob/master/caddy.go#L698) acquires `instancesMu.Lock()` and then calling `Stop()` method of each instance. Inside that method instanceMu also must be acquired (https://github.com/mholt/caddy/blob/master/caddy.go#L96).

I was able to reproduce this just trying to call `caddy.Stop()` function after instance started.

**Comment by mholt** [comment]
Oops. Not sure how that slipped through. :confused: Thanks for the report!

**Comment by miekg** [comment]
Hmm. Think this might be me...but did test (a bit). Anyway don't have time
to look into this today :(

**Comment by miekg** [comment]
Also should be an easy fix (I hope)

**Comment by mholt** [comment]
Miek, I think this was me actually. I just realized I never use `caddy.Stop()` in 0.9, only `inst.Stop()`.

**Comment by mholt** [comment]
All taken care of. :+1:
