### ISSUE TITLE
Typo in 0.9 release announcement blog post

### ISSUE THREAD

**Issue by jpoehls** [mholt/caddy#942]
See screenshot. Feel free to point me to the git repo where the blog posts are hosted and I'll submit a PR for fixes like this in the future.

https://caddyserver.com/blog/caddy-0_9-released

![screenshot_071916_090431_am](https://cloud.githubusercontent.com/assets/72149/16952723/050d26e8-4d90-11e6-832e-d7c7972d3c42.jpg)

**Comment by mholt** [comment]
Thanks! Fixed; will deploy soon.

FYI the repo is at https://github.com/caddyserver/caddyserver.com
