### ISSUE TITLE
possible regression in TLS protocols directive

### ISSUE THREAD

**Issue by jumanjiman** [mholt/caddy#943]
#### 1. What version of Caddy are you running (`caddy -version`)?

0.9.0

#### 2. What are you trying to do?

upgrade from 0.8.3

#### 3. What is your entire Caddyfile?

```text
redacted.example.com {
  log stdout

  errors {
    log stderr
    404 index.html
  }

  # Provide an email for Automatic HTTPS.
  tls redacted@example.com {
    # Remove tls1.0 and tls1.1
    # https://blog.varonis.com/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/
    # https://en.wikipedia.org/wiki/Template:TLS/SSL_support_history_of_web_browsers
    protocols tls1.2 tls1.2
  }

  # After this line, all other paths are relative to root.
  root /data

  ################################################################################
  # README!!
  #
  # Services to evaluate secure configuration include:
  #   https://www.htbridge.com/ssl/
  #   https://www.htbridge.com/websec/
  #   https://securityheaders.io/
  #   https://www.ssllabs.com/ssltest/analyze.html
  #
  # Other interesting references include:
  #   https://scotthelme.co.uk/still-think-you-dont-need-https/
  #   http://webpolicy.org/2015/08/25/att-hotspots-now-with-advertising-injection/
  ################################################################################

  rewrite {
    if {method} not GET
    status 405
  }

  header / {
    Content-Security-Policy "default-src 'self' ; block-all-mixed-content; reflected-xss block; report-uri https://redacted.report-uri.io/r/default/csp/enforce;"
    X-Frame-Options "SAMEORIGIN"
    X-Xss-Protection "1; mode=block"
    X-Content-Type-Options "nosniff"
    strict-transport-security "max-age=31536000; includeSubdomains"
    -Server
  }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
caddy -conf /data/caddyfile -agree
```

#### 5. What did you expect to see?

https://www.htbridge.com/ssl/ test should show that **only tls1.2** is supported.

![screenshot 2016-07-19 at 11 24 13](https://cloud.githubusercontent.com/assets/332496/16955618/567b341c-4da3-11e6-8a45-54ed28b4dc9f.png)

#### 6. What did you see instead (give full error messages and/or log)?

https://www.htbridge.com/ssl/ shows that tls1.0, tls1.1, and tls1.2 are supported

![screenshot 2016-07-19 at 11 25 20](https://cloud.githubusercontent.com/assets/332496/16955668/85d8e434-4da3-11e6-8f2a-fdd1f01f7dae.png)

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

run caddy on a host with automatic https on a site whose DNS name correctly maps to the public IP of the host. use the above caddy file. switch back and forth between caddy v0.8.3 (as packaged in Alpine Linux) and caddy v0.9.0 (downloaded from caddyserver.com)

**Comment by mholt** [comment]
Thanks for the report! That's what I get for neglecting tests...

Fixed on master; if you want this right now, go ahead and build from source.

**Comment by jumanjiman** [comment]
tyvm!

🚀 ⭐
