### ISSUE TITLE
proxy targets with hyphens cause ParseInt Failures

### ISSUE THREAD

**Issue by slowbluecamera** [mholt/caddy#948]
version 0.9.0

I'm running Caddy as a proxy in front of an artifactory server.
The config below worked find for Caddy 8.2:

```
https://chocolatey.eng.foobar.io {
  proxy / http://artifactory.foobar.corp.msp:8081/artifactory/api/nuget/chocolatey-virtual {
    proxy_header Host {host}
  }
  log /var/log/caddy/chocolatey-proxy.log
  tls /etc/lego/certificates/chocolatey.eng.foobar.io.crt /etc/lego/certificates/chocolatey.eng.foobar.io.key
}
```

Now we are getting this error on startup:

```
# caddy --conf=/etc/Caddyfile
Activating privacy features... done.
2016/07/20 03:47:34 strconv.ParseInt: parsing "8081/artifactory/api/nuget/chocolatey": invalid syntax
```

If I remove the path portion of the URL ("/artifactory/api/nuget/chocolatey-virtual") the config works. As this config worked for earlier version (0.8.2 I believe) this appears to be a change in behavior.

**Comment by tw4452852** [comment]
This is a bug in proxy setup, because your url has a `-` and it is recognized as a port range, I will offer a fix soon.

**Comment by slowbluecamera** [comment]
Aha! Beat me to it, only just worked out the simpler failure case. Thank you @tw4452852 !

Simpler fail Caddyfile is 

```
http://foobar.io:8080 {
  proxy / http://foobar.io:8081/artifactory/api/pypi/pypi-virtual
  tls off
}
```

**Comment by mholt** [comment]
Thanks to @tw4452852 I think this is fixed now. Can you pull the latest and confirm it as well @slowbluecamera? If so, feel free to close.

**Comment by slowbluecamera** [comment]
Confirmed fixed for my observed failure cases. Leave it closed. Magnificent valor, @tw4452852!
