### ISSUE TITLE
proxy: Strip path prefix when proxying requests

### ISSUE THREAD

**Issue by crossbreeze** [mholt/caddy#95]
Is it possible to strip the path when proxying requests?

for example, with this config

localhost:8080
gzip
proxy /api localhost:9999

and a request to http://localhost:8080/api/messages

the API server(on port 9999) receives the requests to /api/messages
I am not sure  if it's feasible to strip /api part from the path so that the api server would receive the request to /messages

**Comment by mholt** [comment]
Nope. But I will take a look at implementing this (maybe after the other work on proxy is completed, to avoid merge conflicts - we'll see).

How about something like this to do what you want:

```
proxy /api localhost:9999 {
    without /api
}
```

All this would do is a `strings.StripPrefix(r.URL.Path, without)` How's that look?

**Comment by crossbreeze** [comment]
yeah that looks good.

**Comment by krists** [comment]
I would like to see this feature as well.

**Comment by brk0v** [comment]
It looks like we should change code in ```NewSingleHostReverseProxy``` while creating Director function: https://github.com/mholt/caddy/blob/master/middleware/proxy/reverseproxy.go#L65

**Comment by brk0v** [comment]
See pull request https://github.com/mholt/caddy/pull/102/

**Comment by mholt** [comment]
Merged that in - so this feature will be available with the next release (or now if you build from source).

**Comment by krists** [comment]
@mholt Thanks!

**Comment by crossbreeze** [comment]
Cool. @mholt @brk0v Thank you.
