### ISSUE TITLE
Gzip not compress / if .htm or .html extensions added to conf

### ISSUE THREAD

**Issue by menangen** [mholt/caddy#954]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.0

#### 2. What are you trying to do?
Load pages in local folder with caddy

#### 3. What is your entire Caddyfile?
```text
127.0.0.1:8080
gzip {
	ext .htm .html
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Mac osx el capitan, caddy binaries from off site.

#### 5. What did you expect to see?
Gzip encoding in Firefox networking tab (developer console) for all / connections. Example:
127.0.0.1:8080/  and 127.0.0.1:8080/folder1 and 127.0.0.1:8080/folder2 with index.html in each folder.

#### 6. What did you see instead (give full error messages and/or log)?
Just bytes transferring without gzip encoding and reduced file size.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
1. Create candy file
2. Create 2 folders: 1 for root with index.html and second with any name and with index.html inside. Open Firefox for testing gzip for / and /secondfolder

**Comment by menangen** [comment]
Have looked to caddy code and rewrite config file to:
```text
gzip {
	ext "" ".txt" ".htm" ".html" ".css" ".js" ".otf" ".woff" ".eot" ".svg"
}
```
This is worked for me...

**Comment by mholt** [comment]
That's because index.html is loaded with the path of `/` and doesn't have the .html extension, and you told gzip to only compress paths with .htm and .html. The default gzip configuration does this correctly as you would expect:

```
gzip
```
