### ISSUE TITLE
Clarify QUIC on wiki

### ISSUE THREAD

**Issue by wendigo** [mholt/caddy#957]
Hi @mholt.
As of Chrome v52 QUIC whitelist is no longer applicable for QUIC protocol versions > 30 so using caddy with -quic will expose QUIC to end user. [QUIC wiki page](https://github.com/mholt/caddy/wiki/QUIC) can be corrected :)

**Comment by mholt** [comment]
Wow, that's the truth!

Chrome 52 sure is _slick_. Thanks for the heads-up.

**Comment by wendigo** [comment]
Great 👍
