### ISSUE TITLE
Reloading (USR1) with QUIC produces error

### ISSUE THREAD

**Issue by mholt** [mholt/caddy#958]
When serving with QUIC enabled, reloading Caddy (using SIGUSR1) results in this error:

```
2016/07/23 16:08:22 [INFO] Reloading
2016/07/23 16:08:23 [ERROR] listening for QUIC connections: listen udp :443: bind: address already in use
2016/07/23 16:08:23 [ERROR] listening for QUIC connections: listen udp :80: bind: address already in use
2016/07/23 16:08:28 [INFO] Reloading complete
```

The site still runs fine and I think the reload even completes successfully, but the site will no longer serve QUIC. Caddy 0.9 can handle UDP listeners now; @lucas-clemente I wonder if you could help implement [UDPServer](https://godoc.org/github.com/mholt/caddy#UDPServer) with me when you have a chance? (This is not a high-priority issue but should probably be fixed at some point.)

**Comment by lucas-clemente** [comment]
Interesting, I've never tried reloading :)

I will take a look at this and the UDPServer some time this week and let you know my thoughts.

**Comment by mholt** [comment]
I know UDP doesn't really have the concept of "graceful" reloads (or the definition is fuzzy) but what Caddy can still do is hand the UDP server a PacketConn after a reload so it doesn't need to make a new one (and fail, because the old one is still bound).

Essentially we just need to make [this ListenPacket method](https://github.com/mholt/caddy/blob/1bbad72ff162bdd92960fb8d69ede9e75250a70f/caddyhttp/httpserver/server.go#L150) return [this *net.UDPConn](https://github.com/lucas-clemente/quic-go/blob/9ef936c94153b1308d346fca54533917346696bc/server.go#L75-L78).

Then [during the restart](https://github.com/mholt/caddy/blob/1bbad72ff162bdd92960fb8d69ede9e75250a70f/caddy.go#L575-L635), Caddy will hand over that UDPConn to the new server instance that's created by calling `Serve()` directly, passing it in. Which means that [the ServePacket method in Caddy's HTTP server](https://github.com/mholt/caddy/blob/1bbad72ff162bdd92960fb8d69ede9e75250a70f/caddyhttp/httpserver/server.go#L193) needs a couple lines of code to call Serve on your QUIC/UDP server. I think.

Anyway, I hope that's helpful. If we did our part right with Caddy I don't think this will be too difficult. :smile: Let me know!

**Comment by miekg** [comment]
Cool :-)
(told you so :) )

**Comment by mholt** [comment]
I'll tag this for Hacktoberfest in case anyone wants to give it a try. It involves a change to the quic-go repo and a simple change in this one as well (as I described above). Should be a simple way to get 2 repos added to your Hacktoberfest progress!
