### ISSUE TITLE
Absolute path broken on Windows with Caddy 0.9

### ISSUE THREAD

**Issue by JanTvrdik** [mholt/caddy#959]
Absolute paths such as `C:\foo\bar` used to work fine in Caddy 0.8 but they seems to be broken with Caddy 0.9.

#### 1. What version of Caddy are you running (`caddy -version`)?
0.9 (Windows 10 x64)

#### 2. What are you trying to do?
`caddy -conf Caddyfile` 

#### 3. What is your entire Caddyfile?
This is enough to break it. But other directives such as import broken as well.
```text
log C:\Web\Soft\Caddy\logs\access.log
errors C:\Web\Soft\Caddy\logs\errors.log
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
`caddy -conf Caddyfile` 

#### 5. What did you expect to see?
no error

#### 6. What did you see instead (give full error messages and/or log)?
~~~
2016/07/24 10:04:21 parse //c:\web\soft\caddy\logs\access.log: invalid character "\\" in host name
~~~

or with absolute path in import (the path is clearly appended and not properly resolved)
~~~
2016/07/24 09:58:38 adminer.dev:8 - Parse error: No files matching import pattern C:\Web\Soft\Caddy\conf\vhosts\C:\Web\Soft\Caddy\conf\vhost-common
~~~

**Comment by mholt** [comment]
Hey @JanTvrdik, thanks for taking the time to open an issue. Your Caddyfile must always start with the address of the site to serve; `log` is a valid hostname, but `C:\Web\Soft\Caddy\logs\access.log` is not.
