### ISSUE TITLE
"transparent" proxy directive not sending Host header as per docs

### ISSUE THREAD

**Issue by kmanley** [mholt/caddy#961]
#### 1. What version of Caddy are you running (`caddy -version`)?

0.9.0

#### 2. What are you trying to do?

I'm using caddy as a reverse proxy in front of Sendy (sendy.co). Sendy is a php5 app running under Apache2.

#### 3. What is your entire Caddyfile?

It *was*
```
sendy.domain.co {
  tls kevin@domain.co
  proxy / 127.0.0.1:8080 {
     transparent
  }
}
```

However although the docs state that "transparent" is shorthand for 

```
header_upstream Host {host}
header_upstream X-Real-IP {remote}
header_upstream X-Forwarded-For {remote}
header_upstream X-Forwarded-Proto {scheme}
```

I noticed by using phpinfo that in fact the Host header was NOT being sent by Caddy to Apache

This caused a problem with Sendy because Sendy validates your license by using a hash including the result of that header value. 

The fix was to replace "transparent" with an explicit header_upstream, like this

```
sendy.domain.co {
  tls kevin@domain.co
  proxy / 127.0.0.1:8080 {
     header_upstream Host {host}
  }
}
```

I don't know if this is a doc bug or a bug in the implementation of 'transparent'

Anyway it's working for me now and I'm happy!

**Comment by tomasdeml** [comment]
I'm also hitting this issue. When I use `transparent` instead of specifying the headers explicitly, the passed `host` header seems to be an empty string.

**Comment by tw4452852** [comment]
@kmanley @tomasdeml Do you have a reproducible example? I think the `host` maybe "", but using `transparent` and specifying the `host` header should be consistent...

**Comment by tomasdeml** [comment]
@tw4452852 

The problem occurs with the following caddyfile when I access `https://subsite.example.org`:
```text
https:// {
    tls self_signed
    header / {
		-Server
        Strict-Transport-Security "max-age=31536000"
        X-XSS-Protection "1; mode=block"
	}
	proxy / localhost:580 {
        transparent
	}
}
```

However with this file, the `host` header is correct:
```text
https:// {
    tls self_signed
    header / {
		-Server
        Strict-Transport-Security "max-age=31536000"
        X-XSS-Protection "1; mode=block"
	}
	proxy / localhost:580 {
        proxy_header Host {host}
		proxy_header X-Real-IP {remote}
		proxy_header X-Forwarded-Proto {scheme}
	}
}
```

**Comment by tomasdeml** [comment]
My apologies, my issues with accessing `https://subsite1.example.org` seem to be caused by #916.

**Comment by abiosoft** [comment]
The behaviour should be consistent (empty or with value) whether using `transparent` or setting explicitly. I cannot see why that should happen. The source is [here](https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/upstream.go#L282-L298).

@tomasdeml start using `header_upstream`, `proxy_header` is depreciated and can be removed in any future version.

**Comment by kmanley** [comment]
This may be a dupe of #916 (not 100% sure though)

**Comment by mholt** [comment]
Hm, #916 has been fixed already and is on master. If any of you having this problem can build from source and try it out, that would help to confirm that a problem still exists.

**Comment by mholt** [comment]
Closing unless someone can show that it's a separate issue. :) Thanks!
