### ISSUE TITLE
Error parsing Caddyfile when saved as UTF-8 with BOM

### ISSUE THREAD

**Issue by maximilian-krauss** [mholt/caddy#962]
#### 1. What version of Caddy are you running (`caddy -version`)?
Version 0.9.0

#### 2. What are you trying to do?
Using Caddy as proxy for logstash and kibana (I think this is not relevant)

#### 3. What is your entire Caddyfile?
```text
#Some comment
:8080 {
  tls off
  # Logstash auth
  basicauth /logstash user password

  # Kibana auth
  basicauth / user password

  # Logstash
  proxy /logstash 127.0.0.1:31311

  # Kibana
  proxy / 127.0.0.1:5601
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
OS: Windows 10 (64 Bit) (UI Culture: German)
Windows command prompt with the following command: `caddy_windows_amd64.exe -conf=".\Caddyfile"`

#### 5. What did you expect to see?
```text
Activating privacy features... done.
http://:8080
```

#### 6. What did you see instead (give full error messages and/or log)?
`2016/07/27 13:37:19 .\Caddyfile:3 - Parse error: Unknown directive ':8080'`

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
* Take mine Caddyfile
* Open in a Texteditor
* Save the Caddyfile as UTF-8 with BOM (Byte Order Mark) (with Notepad++ for example)
* Try to run the Caddy with the saved Caddyfile

**Comment by mholt** [comment]
Thanks for the report! I think 1e1e69b fixes it.

**Comment by maximilian-krauss** [comment]
Hey, wow that was really fast :+1: Thanks a lot :smile:
