### ISSUE TITLE
The -host option seems to be ignored

### ISSUE THREAD

**Issue by dwerder** [mholt/caddy#963]
#### 1. What version of Caddy are you running (`caddy -version`)?

Caddy 0.9.0

#### 2. What are you trying to do?

Use caddy as client authentication proxy for prometheus exporter, which listen on localhost:9100

#### 3. What is your entire Caddyfile?
```text
https://external.domain.name:9100 {

    gzip

    log stdout
    errors stdout

    header / { -Server }
 
    tls /etc/caddy/client.pem /etc/caddy/client.pem {
         # require and validate client certificate
         clients /etc/caddy/trust.crt
    }
  
    internal /
    
    proxy /metrics 127.0.0.1:9100
}

```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

caddy -log stdout -agree=true -conf=/etc/caddy/Caddyfile -host='external.domain.name'

I also tried `-host=127.0.0.3` with no success

#### 5. What did you expect to see?

A running caddy, which listen on external.domain.name (which resolves to something like 123.123.123.123 )

#### 6. What did you see instead (give full error messages and/or log)?

Activating privacy features... done.
2016/07/27 11:45:14 listen tcp :9100: bind: address already in use

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Start some service listening on 127.0.0.1:9100 and then try to start caddy.

**Comment by mholt** [comment]
Hey Daniel, thanks for your question. When you specify a host in the Caddyfile, that has priority. The `-host` flag just sets the default host for convenience when you don't have a Caddyfile.

**Comment by dwerder** [comment]
But that does not explain, why the caddy bounds on every IP.

**Comment by mholt** [comment]
If you want to change only the host that Caddy _binds_ to, use the `bind` directive:

```
bind 127.0.0.3
```

**Comment by dwerder** [comment]
Thanks
