### ISSUE TITLE
documentation layout bug - rewrite

### ISSUE THREAD

**Issue by bdillahu** [mholt/caddy#964]
(Are you asking for help with using Caddy? Please use our forum instead: https://forum.caddyserver.com. If you are filing a bug report, please answer the following questions. If your issue is not a bug report, you do not need to use this template. Either way, please consider donating if we've helped you. Thanks!)

#### 1. What version of Caddy are you running (`caddy -version`)?

0.9.0

#### 2. What are you trying to do?

Read docs :-)

In the docs, on the "rewrite" page, there needs to be a newline/bullet before "destinations" - right now it displays as (note the 4xx.* should be start of new bullet):

* status will respond with the given status code instead of performing a rewrite. In other words, use either "status" or "to" in your rule, but not both. The code must be a number in the format 2xx or 4xx.* destinations... is one or more space-separated paths to rewrite to, with support for request placeholders as well as numbered regular expression captures such as {1}, {2}, etc. Rewrite will check each destination in order and rewrite to the first destination that exists. Each one is checked as a file or, if ends with /, as a directory. The last destination will act as default if no other destination exists.

**Comment by mholt** [comment]
Oops, thanks. Fixed locally, will go out with next deploy.
