### ISSUE TITLE
How can I access the request from within a proxy policy?

### ISSUE THREAD

**Issue by krishamoud** [mholt/caddy#967]
I would like to implement the [ip_hash](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#ip_hash) load balancing policy but I haven't been able to figure out how to access the request from within [policy.go](https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/policy.go).  The closest I could find was within [proxy.go](https://github.com/mholt/caddy/blob/master/caddyhttp/proxy/proxy.go) where it's added to the request header.  

How can I access the client's IP from within a policy?

Thanks,
Kris

**Comment by mholt** [comment]
It's quite possible the interface will need to be modified so that it is passed the `*http.Request` along with the HostPool in `Select()`, because that method will need to look at the request in order to decide which host in the pool to use.

**Comment by krishamoud** [comment]
@mholt Thanks for the reply and sorry for the easy question.  Go is not my strongest language but I do have a WIP I'll push hopefully later today.

**Comment by mholt** [comment]
No problem! Would be happy to welcome your contributions. :)
