### ISSUE TITLE
Cannot rewrite to absolute path

### ISSUE THREAD

**Issue by ponychicken** [mholt/caddy#972]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.0

#### 2. What are you trying to do?
Serve a file from an absolute path under a specific url path

#### 3. What is your entire Caddyfile?
```text
root /home/user-data/www/default
rewrite  /.well-known/autoconfig/mail/config-v1.1.xml /var/lib/mailinabox/mozilla-autoconfig.xml
```

##### This is the corresponding working nginx directive
```text
location = /.well-known/autoconfig/mail/config-v1.1.xml {
    alias /var/lib/mailinabox/mozilla-autoconfig.xml;
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
Using the upstart script

#### 5. What did you expect to see?
Caddy serving the xml file under .well-known/...

#### 6. What did you see instead (give full error messages and/or log)?
404

Unfortunately Caddy seems to be unable to rewrite to an abolute path (or is there some other way to achieve this?)

**Comment by abiosoft** [comment]
`rewrite` only works for path relative to `root`. You can either copy the file or symlink it to a path within `root`.

**Comment by mholt** [comment]
And I think the current behavior is best, since we don't want to make it that easy to jump out of the site root... if at all.
