### ISSUE TITLE
Root path resolved incorrectly in imported files?

### ISSUE THREAD

**Issue by ponychicken** [mholt/caddy#974]
#### 1. What version of Caddy are you running (`caddy -version`)?
0.9.0

#### 2. What are you trying to do?
I have the following setup:

##### /etc/caddy/Caddyfile

```
import /usr/share/project-x/Caddyfile
```

##### /usr/share/project-x/Caddyfile

```
example.com {
    root ./build
}
```

##### ls -l /usr/share/project-x
```
drwxrwxr-x 4 web web 4096 Jul 30 11:51 build/
-rw-rw-r-- 1 web web  123 Jul 30 12:07 Caddyfile
-rw-rw-r-- 1 web web  497 Jul 30 11:51 config.json
drwxrwxr-x 6 web web 4096 Jul 30 11:51 contents/
-rw-rw-r-- 1 web web  121 Jul 30 11:51 package.json
drwxrwxr-x 2 web web 4096 Jul 30 11:51 plugins/
-rw-rw-r-- 1 web web   86 Jul 30 11:51 readme.md
drwxrwxr-x 2 web web 4096 Jul 30 11:51 templates/
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
With upstart script

#### 5. What did you expect to see?
I expect the root to resolve to the ./build folder

#### 6. What did you see instead (give full error messages and/or log)?
``
 [WARNING] Root path does not exist: ./build
``

**Comment by tw4452852** [comment]
I think this is consistent with doc of directive `root` : `A relative root path is relative to the current working directory.`

**Comment by mholt** [comment]
Should root be relative to the Caddyfile path instead?

Main problem with that is if the Caddyfile is loaded some other way than from a file on disk; plugins make it possible to load Caddyfile over the network, for example. Or in the near future, an API request can POST a new Caddyfile that doesn't have a location on disk, only in memory.
