### ISSUE TITLE
no HTTP/2 on Go 1.7

### ISSUE THREAD

**Issue by wjkohnen** [mholt/caddy#975]
My "production" server, with some proprietary patches, serves only HTTP/1.1 instead of HTTP/2. I can't tell since when. Maybe since I switched from 0.8 to 0.9, maybe since my recent Let's Encrypt cert cycle; I can't tell really.

QUIC works.

I have tried this again with vanilla Caddy with a minimal setup, still HTTP/2 does not work. I've also tried to `git bisect`, but I gave up when I realized that some API of dependent libraries changed since 0.9 released, letting my naïve bisect build script fail. 

#### 1. What version of Caddy are you running (`caddy -version`)?
current master
Caddy 0.9.0 (+7157bdc Sat Jul 30 13:04:36 UTC 2016)

#### 2. What are you trying to do?
GET via http/2

#### 3. What is your entire Caddyfile?
```
caddy:2015 { tls self_signed }
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
```
# inside docker container named caddy
echo "caddy:2015 { tls self_signed }" | ./caddy -log stderr
```

```
# inside docker container linked to container caddy, i.e. hostname caddy resolves.
curl --insecure --http2 -v https://caddy:2015/ 2>&1 | grep ALPN
```

#### 5. What did you expect to see?
```
* ALPN, offering h2
* ALPN, offering http/1.1
* ALPN, server accepted to use h2
```
( no log output )

#### 6. What did you see instead (give full error messages and/or log)?
```
* ALPN, offering h2
* ALPN, offering http/1.1
* ALPN, server did not agree to a protocol
```
( no log output )

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

See above. "Expected" output generated by 

```
curl --insecure --http2 -v https://google.com/ 2>&1 | grep ALPN
```

**Comment by wjkohnen** [comment]
OK, interesting. I've totally forgotten I work with Go's 1.7 release branch and above Caddy binary indeed was compiled with Go 1.7rc3. After `go build -a` with Go 1.6.2, HTTP/2 is used again.

**Comment by wjkohnen** [comment]
A little bit of research later...

It seems that the semantic of net/http/(*Server).Serve() has [changed slightly](https://tip.golang.org/pkg/net/http/#Server.Serve) in Go 1.7:

>  If srv.TLSConfig is non-nil and doesn't include the string "h2" in Config.NextProtos, HTTP/2 support is not enabled.

Serve() configures HTTP/2 once after [this check here](https://tip.golang.org/src/net/http/server.go?s=67792:67848#L2224):

```
// shouldDoServeHTTP2 reports whether Server.Serve should configure
// automatic HTTP/2. (which sets up the srv.TLSNextProto map)
func (srv *Server) shouldConfigureHTTP2ForServe() bool {
        if srv.TLSConfig == nil {
                // Compatibility with Go 1.6:
                // If there's no TLSConfig, it's possible that the user just
                // didn't set it on the http.Server, but did pass it to
                // tls.NewListener and passed that listener to Serve.
                // So we should configure HTTP/2 (to set up srv.TLSNextProto)
                // in case the listener returns an "h2" *tls.Conn.
                return true
        }
        // The user specified a TLSConfig on their http.Server.
        // In this, case, only configure HTTP/2 if their tls.Config
        // explicitly mentions "h2". Otherwise http2.ConfigureServer
        // would modify the tls.Config to add it, but they probably already
        // passed this tls.Config to tls.NewListener. And if they did,
        // it's too late anyway to fix it. It would only be potentially racy.
        // See Issue 15908.
        return strSliceContains(srv.TLSConfig.NextProtos, http2NextProtoTLS)
}
```

`strSliceContains` simply searches for the string `"h2"` in the NextProtos slice. When Caddy calls `Serve()` the slice `srv.TLSConfig.NextProtos` is empty. 

So... simply append `"h2"` to it? I am not sure if this has other implications (on Go 1.6).

**Comment by mholt** [comment]
Nice find, @wjkohnen - thanks for investigating! I was not aware of this issue yet (perhaps we need more integration tests to check stuff like this). It [looks like](https://github.com/golang/go/blob/b5f0aff49503e31002b33198e06708e263c445a7/src/net/http/server.go#L2454-L2456) this is safe for Go 1.6 too.
