### ISSUE TITLE
Conditions in "redir" appear to not be working

### ISSUE THREAD

**Issue by schlarpc** [mholt/caddy#977]
#### 1. What version of Caddy are you running (`caddy -version`)?

0.9 on Windows 64 bit, from main download page.

$ caddy -version
Caddy 0.9.0

#### 2. What are you trying to do?

Using conditions in redir directive as documented at https://caddyserver.com/docs/redir

#### 3. What is your entire Caddyfile?

```
:80 {
    redir 307 {
        if {host} is nonsenseasiuhdsauidh
        /test https://example.com
    }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

Caddyfile in same directory as caddy, ran caddy:
```
$ caddy
Activating privacy features... done.
http://
```

#### 5. What did you expect to see?

Navigate to http://127.0.0.1/test and get a 404 not found, since my requested host is not "nonsenseasiuhdsauidh"

(as far as I can tell, this applies to any condition, though)

#### 6. What did you see instead (give full error messages and/or log)?

http://127.0.0.1/test redirects to https://example.com:

```
$ curl -v http://127.0.0.1/test
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 80 (#0)
> GET /test HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.48.0
> Accept: */*
>
< HTTP/1.1 307 Temporary Redirect
< Location: https://example.com
< Server: Caddy
< Date: Sun, 31 Jul 2016 09:02:19 GMT
< Content-Length: 55
< Content-Type: text/html; charset=utf-8
<
<a href="https://example.com">Temporary Redirect</a>.
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

Use an if statement as part of the redir directive.

**Comment by slightfoot** [comment]
I found this also. Removing the "default" code resolved it. Try this.
```
:80 {
    redir {
        if {host} is nonsenseasiuhdsauidh
        /test https://example.com 307
    }
}
```

**Comment by schlarpc** [comment]
Ah, cool, that'll at least get me unblocked for now. Thanks.

**Comment by tw4452852** [comment]
This is a bug, will offer a fix soon.

**Comment by mholt** [comment]
Thanks Tw :smile:
