### ISSUE TITLE
Update examples for embedding Caddy into a Go application

### ISSUE THREAD

**Issue by nubunto** [mholt/caddy#985]
The examples from the wiki to embed caddy in a Go application and the way to actually do it after `go get` are divergent. I might be overlooking something (maybe some specific version or whatnot) -- if that's the case, I apologize.

There are only a few differences in the API, but a updated example would be nice for people starting out (like I just did). The godoc is also out of date.

**Comment by mholt** [comment]
Hi! Thanks for writing in about the docs. Always trying to make them better. What about the godoc is out-of-date? Which examples are divergent?

**Comment by nubunto** [comment]
Hello, Matt! Yeah, I missed some information there. But basically, the example I just reproduced in my machine is the following:
```
caddy.AppName = "Foobar"
caddy.AppVersion = "1.2.3"
caddyfile, err := caddy.LoadCaddyfile(nil)
if err != nil {
	log.Fatal(err)
}
err = caddy.Start(caddyfile)
if err != nil {
	log.Fatal(err)
}
go func() {
	for i := 0; i < 10; i++ {
		err = caddy.Restart(nil)
		if err != nil {
			log.Fatal(err)
		}
		log.Println("Successfully restarted caddy.")
		time.Sleep(10 * time.Second)
	}
}()
caddy.Wait()
```

And the example from the wiki is:
```
caddy.AppName = "Sprocket"
caddy.AppVersion = "1.2.3"

// pass in the name of the server type this Caddyfile is for (like "http")
caddyfile, err := caddy.LoadCaddyfile(serverType)
if err != nil {
    log.Fatal(err)
}

instance, err := caddy.Start(caddyfile)
if err != nil {
    log.Fatal(err)
}

// Start() only blocks until the servers have started.
// Wait() blocks until the servers have stopped.
instance.Wait()
```
You can also restart Caddy:
```
// On Unix systems, you get graceful restarts.
// To use same Caddyfile, just pass in nil.
// Be sure to replace the old instance with the new one!
instance, err = instance.Restart(newCaddyfile)
if err != nil {
    log.Fatal(err)
}
```

Or stop it:
```
err = instance.Stop()
if err != nil {
    log.Fatal(err)
}
```

**Comment by nubunto** [comment]
The plot thickens.

**Comment by nubunto** [comment]
Argh, sorry for wasting your time, Matt. I should have checked this before opening this issue. :disappointed: 
My repo was out of date.

**Comment by mholt** [comment]
No problem, this was easy. :)
