### ISSUE TITLE
import directive is broken in version 0.9.0 win10_x64

### ISSUE THREAD

**Issue by vitr** [mholt/caddy#986]
I have no issues running the same set of config files on previous version, but it's broken in the new version. See the following details
#### 1. What version of Caddy are you running (`caddy -version`)?
Caddy 0.9.0

#### 2. What are you trying to do?
I'm trying to upgrade Caddy from v0.8.3 to v0.9.0

#### 3. What is your entire Caddyfile?
```text
import /Users/Vit/.valet/Caddy/*

:80 {
    fastcgi / 127.0.0.1:9000 php {
        index server.php
    }

    rewrite {
        to /server.php?{query}
    }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?
caddy --conf=\Users\Vit\.valet\Caddyfile

#### 5. What did you expect to see?
this works on version 0.8.3, server runs OK

#### 6. What did you see instead (give full error messages and/or log)?
```
2016/08/02 10:47:35 \Users\Vit\.valet\Caddyfile:1 - Parse error: No files matching import pattern /Users/Vit/.valet/Caddy/*
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?
Use Windows 10 Pro x64, download caddy https://caddyserver.com/download/build?os=windows&arch=amd64&features=
try to import some file using `import /Users/Vit/.valet/Caddy/*`
the contents example
```text
http://Vit.dev:80 {
    redir https://{host}{uri}
}

https://Vit.dev:443 {
    tls \Users\Vit/.valet/Certificates/Vit.dev.crt \Users\Vit/.valet/Certificates/Vit.dev.key

    fastcgi / 127.0.0.1:9000 php {
        index server.php
    }

    rewrite {
        to /server.php?{query}
    }
}
```

**Comment by mholt** [comment]
Thanks for the report, but I don't understand, how is `/Users/Vit/.valet/Caddy/*` a valid file path on Windows? Isn't it supposed to be something like `C:\Users ...` ?

**Comment by vitr** [comment]
sorry, for sure that's my fault, missed %HOMEDRIVE% there, it works just fine if I have `C:\Users ...`.
I guess, the previous version was less strict with paths and I got away from the error.
thanks for your help.

**Comment by mholt** [comment]
Indeed, we did change how imports are handled (slightly) - import paths are now relative to the file's location. I actually think I like this new behavior better since paths like you had before don't make much sense in Windows IMO, and now sensible paths are enforced. Thanks for your issue!
