### ISSUE TITLE
Probably not really a Caddy bug, but some better error can help message

### ISSUE THREAD

**Issue by harikt** [mholt/caddy#988]
There is already a discussion over : https://forum.caddyserver.com/t/primary-script-unknown/191/8?u=harikt . Regarding the query over twitter it was asked to report if it looks like a bug  https://twitter.com/caddyserver/status/760234958329819137

#### 1. What version of Caddy are you running (`caddy -version`)?

Tried  0.8.3 and 0.9.0

#### 2. What are you trying to do?

There is a login form in the route `/login` . I am trying to `POST` values. There is a router which handle the routing so even if the url is `/login` it will be going to `index.php` .

#### 3. What is your entire Caddyfile?
```text
localhost:8000 {
    tls off

    root /var/www/projects/public

    fastcgi / /var/run/php/php7.0-fpm.sock php

    rewrite {
        to /index.php?{query}
    }
}
```

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

```
caddy -log=error.log 
```

#### 5. What did you expect to see?

Login screen or if there is error the error page.

#### 6. What did you see instead (give full error messages and/or log)?

Browser displays 

```
The localhost page isn’t working

localhost unexpectedly closed the connection.
ERR_CONTENT_LENGTH_MISMATCH
```

and `error.log` reports

```
2016/08/02 10:37:05 http: multiple response.WriteHeader calls
```

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

I was able to figure out the problem, but for the current time unable to provide a reproducible behaviour in simple file.

Problem was due to no undefined index in an array. See below, but the app is working on https://github.com/zendframework/zend-expressive , so I will try to create a sample project and try to link here when I get some time.

```
$ cat home.php 
Home Page
```

``` 
$ cat index.php 
<?php
$hello = $_POST['hello'];
header('Location: http://localhost:8000/home.php');
```

```
$ cat Caddyfile 
localhost:8000 {
    tls off

    root /var/www/projects/github.com/harikt/comments/caddytest

    fastcgi / /var/run/php/php7.0-fpm.sock php    
}
```

```
caddy
```

Browse to `http://localhost:8000` . In the above it works without any errors reporting. May be expressive is throwing an Exception or something. I may want to look more into it.

**Comment by mholt** [comment]
Ah. Yeah, the PHP app is writing an error message because 'hello' is not a defined array element in $_POST. Then PHP continues to execute the next line (?? why it's just a warning and not a fatal error I have no clue ??) which sets the Location HTTP header, however; headers have already been written when the warning was printed on the line above.

Indeed, I don't think this is a Caddy bug, thanks for sorting that out and reporting your findings! (In fact, I think the error message is quite helpful here.)

**Comment by harikt** [comment]
> In fact, I think the error message is quite helpful here.

Not really, I wished if I could see something like the same text message which PHP throws. Is there a way, so it helps to debug faster.

**Comment by mholt** [comment]
Possibly. @abiosoft, you know PHP better than I. :smile: What do you think?

**Comment by abiosoft** [comment]
@harikt what is your `error_reporting` value ?

**Comment by harikt** [comment]
@abiosoft `error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT` .

When you asked the question I also checked `display_errors` which was `Off` . But modifying the same to replicate the problem what I noticed was I can see the error in log as 

```
04/Aug/2016:13:33:09 +0530 [ERROR 0 /index.php] PHP message: PHP Notice:  Undefined variable: post in /var/www/projects/github.com/harikt/expressive-auth/src/Action/LoginAction.php on line 44
```

Also it is strange to see why my sample above to replicate the same don't show any warnings or errors on the terminal when there is no post data for `$_POST['hello']` , but redirects it to `http://localhost:8000/home.php'` . Even if I change the `display_errors` to `0n` and restarted `php-fpm` . 

I don't probably know what is the problem though. Currently nginx is there. ( FYI )

**Comment by abiosoft** [comment]
Are you saying nginx's behaviour is different ? That behaviour is correct AFAIK. i.e. redirecting even after the index is missing and you won't get errors if they are disabled.

What interests me is `http: multiple response.WriteHeader calls` and I will try reproducing the error.

**Comment by harikt** [comment]
@abiosoft no. I was saying nginx is also there in my system. Its just an information about what all are there currently .

**Comment by harikt** [comment]
probably is it due to rewrite header asking everything to go via the index.php ?

```
rewrite {
    to /index.php?{query}
}
```

Wild guess.
