### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by bobobo1618** [mholt/caddy#991]
At the moment caddyserver.com supports various ARM architectures but not ARM64.

According to [the Golang wiki](https://github.com/golang/go/wiki/GoArm), the build should be as simple as setting `GOARCH=arm64` instead of `GOARCH=arm`.

I've confirmed that building this way runs on the ODROID-C2, which is an ARM64 device.

I'd just build Caddy myself but there doesn't appear to be a good way to build with all the plugins I want included.

**Comment by bobobo1618** [comment]
Actually I looked into it a little more and it looks like the build server already supports ARM64!

[This](https://caddyserver.com/download/build?os=linux&arch=arm64&features=filemanager%2Cgit%2Chugo%2Cipfilter%2Cjwt%2Clocale%2Cmailout%2Cminify%2Cprometheus%2Cratelimit%2Crealip%2Csearch%2Ccloudflare%2Cdigitalocean%2Cdnsimple%2Cdyn%2Cgandi%2Cgooglecloud%2Cnamecheap%2Crfc2136%2Croute53%2Cvultr) works.

We just need a link on the download page.

**Comment by mholt** [comment]
Oh, we commented at the same time. Yes, the link is not there because it is not a very common platform. The new website that we'll be starting on should have all the options available there.
