### ISSUE TITLE
Proxied requests are forwarding incorrect Host headers

### ISSUE THREAD

**Issue by nullstyle** [mholt/caddy#993]
#### 1. What version of Caddy are you running (`caddy -version`)?

I'm running from source at revision  c110b27.  No custom changes, just a straight checkout

#### 2. What are you trying to do?

I am trying to use caddy as a transparent proxy for some backend services.  It is however improperly rewriting the requests Host header to be the upstream's host, rather than the host of the original http request.

#### 3. What is your entire Caddyfile?
```text
go.nullstyle.com {
    tls off
  proxy / http://10.144.133.222:8080 {
    header_upstream Host {>Host}
    header_upstream X-Real-IP {remote}
    header_upstream X-Forwarded-For {remote}
    header_upstream X-Forwarded-Proto {scheme}
  }
}
```

Note:  using `{host}` also results in incorrect behavior.

#### 4. How did you run Caddy (give the full command and describe the execution environment)?

`caddy`
OS X development laptop
go 1.6

#### 5. What did you expect to see?

I expect that a reverse proxy maintains the Host header as supplied by the original client.  Rewriting it to be the upstream host unfortunately break any virtual hosting done by way of host.

#### 6. What did you see instead (give full error messages and/or log)?

My upstream service returns error messages because the proxy (caddy) is overwriting the header.

#### 7. How can someone who is starting from scratch reproduce this behavior as minimally as possible?

The caddyfile is minimal, simply replace the hosts in the caddy file above.  For the upstream server a simple caddyfile such as the below can illustrate the problem:

```
go.nullstyle.com:8081 {
    log
    tls off
    root .
}
```

With both servers running, make a call to the proxy with a `Host: go.nullstyle.com` and notice how the upstream responds with a "No such site at :8080".  

The issue is possibly here:  https://github.com/mholt/caddy/blob/c110b27ef53484f03509f657b1e8c8cf5e439e64/caddyhttp/proxy/proxy.go#L127-L133 or perhaps here: https://github.com/mholt/caddy/blob/c110b27ef53484f03509f657b1e8c8cf5e439e64/caddyhttp/proxy/proxy.go#L106-L121.  The both modify the host header, but the code is a bit tough to reason about so I can't tell yet.

[Edited by mholt: Replaced code links to be permalinks]

**Comment by tw4452852** [comment]
Hi @nullstyle , This is the behavior of `net/http`, from the doc of `Header` field of the `http.Request`:

```
    // Header contains the request header fields either received
    // by the server or to be sent by the client.
    //
    // If a server received a request with header lines,
    //
    //	Host: example.com
    //	accept-encoding: gzip, deflate
    //	Accept-Language: en-us
    //	fOO: Bar
    //	foo: two
    //
    // then
    //
    //	Header = map[string][]string{
    //		"Accept-Encoding": {"gzip, deflate"},
    //		"Accept-Language": {"en-us"},
    //		"Foo": {"Bar", "two"},
    //	}
    //
    // For incoming requests, the Host header is promoted to the
    // Request.Host field and removed from the Header map.
    //
    // HTTP defines that header names are case-insensitive. The
    // request parser implements this by using CanonicalHeaderKey,
    // making the first character and any characters following a
    // hyphen uppercase and the rest lowercase.
    //
    // For client requests, certain headers such as Content-Length
    // and Connection are automatically written when needed and
    // values in Header may be ignored. See the documentation
    // for the Request.Write method.
    Header Header
```

Pay attention to this paragraph:

```
    // For incoming requests, the Host header is promoted to the
    // Request.Host field and removed from the Header map.
```

So you may check the `Request.Host`.

**Comment by tw4452852** [comment]
Also I just add a test to confirm this.

**Comment by mholt** [comment]
Thanks Scott and Tw for working on this!
