### ISSUE TITLE
Implement Maximum Fragment Length Negotiation for TLS

### ISSUE THREAD

**Issue by marvinroger** [mholt/caddy#997]
IoT devices are fairly limited in terms of memory, so 16k fragments might be too large in some use cases. That is why it would be great if you could implement [Maximum Fragment Length Negotiation](https://tools.ietf.org/html/rfc6066#page-8) (a TLS extension).

Thanks for this great server, it will help the Web getting HTTP2/TLS-ready!

**Comment by mholt** [comment]
Thanks for the feature request, Marvin! However, we use [Go's standard TLS libraries](https://golang.org/pkg/crypto/tls/) so I think this feature request would need to be put in at [golang/go](https://github.com/golang/go/issues).
